STEALS 10K
yogstation13/Yogstation pull request #10000
Opened 2020-10-16 15:03 UTC by nichlas0010

2020-10-16 15:05 UTC, FLME commented
yoggers

2020-10-16 15:20 UTC, Hopekz commented
#9999 was the real get
Can still get 11111 (:

2020-10-16 15:45 UTC, alexkar598 requested changes
Just... remove the proc if you want to do that?

2020-10-17 09:51 UTC, nichlas0010 commented
@alexkar598 this is your code, I just took it from a random branch to make the PR

2020-10-17 09:51 UTC, closed without merging