Makes people shout "Clear!" before defibbing
yogstation13/Yogstation pull request #10018
Opened 2020-10-17 02:44 UTC by MrHorizons

The title says it all, really.

#### Changelog

:cl:  
rscadd: People now shout "clear!" just before defibbing someone. It doesn't take any more or less time.
/:cl:

2020-10-17 02:47 UTC, Darkstick commented
really not a fan of forcing a character to say something. It always comes off as weird and takes me out of the moment a little.

2020-10-17 03:01 UTC, FLME commented
making a character say something bad but if this does get merged please make it so that only medical personnel will do it, if a tider comes in and starts defibbing they dont say it

2020-10-17 03:16 UTC, MrHorizons commented
> making a character say something bad but if this does get merged please make it so that only medical personnel will do it, if a tider comes in and starts defibbing they dont say it

That does sound better. Though I suspect I'll have to do a bit more than just changing `defib.dm`, so I'll close this.

2020-10-17 21:35 UTC, MrHorizons commented
There we go. Only "doctors" shout it before defibbing, which is defined as the user's job being either "Medical Doctor", "Paramedic", or "Chief Medical Officer".

2020-10-22 13:42 UTC, nichlas0010 requested changes, later dismissed

2020-10-22 13:42 UTC, nichlas0010 commented on code/game/objects/items/defib.dm
> +				user.say("Clear!")
```suggestion
				user.say("Clear!", forced = "defib")
```

2020-10-24 10:25 UTC, JamieD1 requested changes
Wont this cancel the defib if they are not a medical doctor or paramedic?

Unintended?

2020-10-24 10:25 UTC, JamieD1 commented on code/game/objects/items/defib.dm
> +		if(do_after(user, 5, target = H)) //Counting the delay for "Clear", revive time is 5sec total
Wont this cancel the defib if they are not a medical doctor or paramedic?

Unintended?

2020-10-24 15:05 UTC, jcatjmeow approved these changes

2020-10-24 15:05 UTC, jcatjmeow commented on code/game/objects/items/defib.dm
> +				return
```suggestion
```
The return here will end the entire proc early. Not what you want.

With this change, if the if condition is not fulfilled, the next code will run, which is what we want.

2020-10-27 09:20 UTC, JamieD1 approved these changes

2020-10-27 09:20 UTC, merged