dying with the rod of asclepius now transfers your mind to the snake
yogstation13/Yogstation pull request #10096
Opened 2020-10-22 09:26 UTC by SomeguyManperson

it's not terribly difficult to kill or lethal so it should be fine

:cl:  
tweak: the snake created on a hippocratic oath rod user's death is now controlled by them
/:cl:

2020-10-22 21:28 UTC, jcatjmeow commented
adorable tbh

2020-10-22 21:47 UTC, jcatjmeow approved these changes

2020-10-22 21:48 UTC, jcatjmeow commented
wait a second

it transfers the mind to the boy
then it deletes you

2020-10-22 21:49 UTC, jcatjmeow requested changes
maybe?

2020-10-22 21:49 UTC, jcatjmeow commented on code/datums/status_effects/buffs.dm
>  			qdel(owner)
```suggestion
			qdel(owner)
			if(owner.mind)
				owner.mind.transfer_to(healSnake)
```

2020-10-22 21:54 UTC, jcatjmeow approved these changes
nvm this works

2020-10-24 11:03 UTC, JamieD1 approved these changes

2020-10-24 11:03 UTC, merged