PISCIS : fishpeople - new donator only roundstart race!
yogstation13/Yogstation pull request #10186
Opened 2020-10-26 22:22 UTC by EdgeLordExe

Who are piscis? Piscis- fish in latin - they are a race of deep sea water fish people that had to adapt to space environment when NT came to their planet. They are weakend in standard pressure, being slower, weak to heat and stuns impacting them longer. their only advantage at standard pressure is slight resistance to cold damage. They require water vapour AND oxygen to breathe in standard pressure otherwise they will slowly start to suffocate and die of asphyxiation. They love raw food, raw vegetables and raw meat, they absolutely hate sugary food, and anything prepared really. When the pressure reaches 325 kpa they become faster (same speed as normal humans) , their resistance to cold increases by 17 % points and their weakness to stuns and heat fades away. They also gain the ability to breathe pure oxygen in those pressurized circumstances. As i said already they are DONATOR only.

I did it for money yet again.

here is the thread :

https://forums.yogstation.net/threads/35-fishpeople-a-donator-race-ss13-server.22396/

#### Changelog

:cl:  
rscadd: NEW DONATOR ONLY RACE : piscis - fresh from the sea water!
rscadd: added a system for adding donator only races and tied it to policy while i was at it.
/:cl:

2020-10-26 22:26 UTC, Marmio64 commented
but what do they even look like

2020-10-26 22:26 UTC, jcatjmeow commented
Do not personally support donor-only races.

Will check the code for quality later. In the meantime, do you have any screenshots of the mechanics in action?

2020-10-26 22:29 UTC, EdgeLordExe commented
lemme pull up the sprites gimme a second

2020-10-26 22:29 UTC, EdgeLordExe commented
and regarding the bounty - they got approved thats all i really care about 
money is money man

2020-10-26 22:39 UTC, jcatjmeow commented
The label is because it's wip not because it will never be merged

2020-10-26 22:46 UTC, Marmio64 commented
why do they look like creatures from the black lagoon

2020-10-26 23:40 UTC, Xoxeyos commented
They look like shit, I doubt this will fulfill the bounty, make them look better, and not like one mess of colors, atleast I can see a tail and a mouth. I suggest you take a look here, if you want more help with your sprites. https://discord.gg/jYquSmy (Spriter's Bay)

2020-10-27 00:34 UTC, wejengin2 commented
These sprites are horrible

2020-10-27 01:50 UTC, Partheo commented
Can you post some images of a few different colors besides this light blue

2020-10-27 02:13 UTC, UselessTheremin commented
Yeah I don’t want to be harsh but this is nothing like what the bounty wanted, it was supposed to be more of a plasma man clone, but this is just a lizard clone and it is very boring.

2020-10-27 03:22 UTC, jcatjmeow requested changes

2020-10-27 03:22 UTC, jcatjmeow commented on code/modules/language/piscis.dm
> +	flags = TONGUELESS_SPEECH
```suggestion
	flags = TONGUELESS_SPEECH
```
Why?

2020-10-27 06:57 UTC, Hopekz commented on code/modules/language/piscis.dm
> +	flags = TONGUELESS_SPEECH
gills
they're fish

2020-10-27 08:38 UTC, EdgeLordExe commented
> Yeah I don’t want to be harsh but this is nothing like what the bounty wanted, it was supposed to be more of a plasma man clone, but this is just a lizard clone and it is very boring.

![image](https://user-images.githubusercontent.com/42111655/97276900-1a18cc00-1838-11eb-8e89-98d65e03081f.png)

2020-10-27 16:25 UTC, neeshacark commented
> > Yeah I don’t want to be harsh but this is nothing like what the bounty wanted, it was supposed to be more of a plasma man clone, but this is just a lizard clone and it is very boring.
> 
> ![image](https://user-images.githubusercontent.com/42111655/97276900-1a18cc00-1838-11eb-8e89-98d65e03081f.png)

someone poke xantam. water vapor needs a use and I don't see why NEGATIVES for a donor race bad

2020-10-27 22:12 UTC, Hopekz commented
Fish people were a terrible idea from the start but this PR isn't bad.

The sprites aren't too great but not everyone is a spriter + coder so I'm pretty sure someone will care about remaking their visuals sometime like with other early mutant races.

2020-10-27 22:15 UTC, Hopekz commented
Also, don't let the down doinks discourage you this whole idea wasn't too popular from the start from what I can tell
![image](https://user-images.githubusercontent.com/24533979/97367899-ec537780-1877-11eb-8cf1-d996268dc6df.png)

2020-10-28 13:22 UTC, jcatjmeow commented
Can you please provide a clip of gameplay with the new race? Either a gif/video or a series of screenshots, showing the new alerts, mechanics, sprites, etc.
@EdgeLordExe

2020-10-28 19:20 UTC, EdgeLordExe commented
> Can you please provide a clip of gameplay with the new race? Either a gif/video or a series of screenshots, showing the new alerts, mechanics, sprites, etc.
> @EdgeLordExe

im currently trying to debug the tails of them disappearing when changing clothes may take some time since the code is grade A shitcode

2020-10-28 23:03 UTC, swissloaf commented
> > > Yeah I don’t want to be harsh but this is nothing like what the bounty wanted, it was supposed to be more of a plasma man clone, but this is just a lizard clone and it is very boring.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/42111655/97276900-1a18cc00-1838-11eb-8e89-98d65e03081f.png)
> 
> someone poke xantam. water vapor needs a use and I don't see why NEGATIVES for a donor race bad

Don't listen to him, we agreed in staff channels that it could be a plasmaman resprite with water vapor tanks if that's possible for you to do

2020-10-29 04:12 UTC, Mqiib commented
![image](https://user-images.githubusercontent.com/43766432/97524544-53a62000-197b-11eb-9d07-58cce51aef89.png)

Shouldnt the bit at the very end there be roundstart_races and not donator_races?

2020-10-29 08:15 UTC, EdgeLordExe commented
> ![image](https://user-images.githubusercontent.com/43766432/97524544-53a62000-197b-11eb-9d07-58cce51aef89.png)
> 
> Shouldnt the bit at the very end there be roundstart_races and not donator_races?

yeah

2020-10-29 18:58 UTC, EdgeLordExe commented
@jcatjmeow i updated the pr body to feature gifs and pictures of piscis

2020-10-29 20:38 UTC, Marmio64 commented
they look MUCH better now at least

2020-11-05 20:05 UTC, swissloaf commented
give them fish bowl head

2020-11-15 18:46 UTC, EdgeLordExe commented
dont feel like solving the conflicts rn, will reopen once i do

2020-11-15 18:46 UTC, closed without merging