Adds the Deagle to the syndicate Uplink
yogstation13/Yogstation pull request #10191
Opened 2020-10-27 06:45 UTC by Moja10

Adds the Desert Eagle and the magazines to the uplink. Specifically balances the fact that the ONLY source of .50 AE magazines are the uplink, there is no way to print .50AE ammo or mags. 12 TC for the gun, 2 TC for the mags, which allows for at max five mags, or 35 rounds total if you go all in. I feel this is balanced to the fact that the revolver is 13 TC, and speedloaders are 4 TC, but .357 ammo is printable at the Autolathe, and generally people who use the revolver will get way more bullets than the deagle's 35. 
#### Changelog

:cl:  
rscadd: The syndicate have been playing too many video games, as they now can purchase Desert Eagles and ammo in their uplinks. 
/:cl:

2020-10-27 06:46 UTC, AdamElTablawy commented
but what's the reasoning for adding another gun to the uplink

2020-10-27 06:48 UTC, FLME commented
sure, unused weapon being put in gameplay would be nice

2020-10-27 06:49 UTC, Moja10 commented
Rule of cool, way more stylish to execute your target with a Desert Eagle. More bullets at start at the trade off of absolutely no new ammo. Uses mags instead of clips. It's a shame the Deagle as it stands is basically admin only because it's cool and I like it.

2020-10-27 09:54 UTC, JamieD1 requested changes
Mags up to 4TC, Yes you can print .357 but it requires alot more steps then just using the autolathe.

2020-10-29 21:09 UTC, JackKindred commented
+1 from me, the Deagle kicks ass but it RARELY sees any use by anyone at all.

2020-10-30 01:28 UTC, Reed0506 commented
jamie it takes like 10 seconds to hack an autolathe. its not any sort of actual block. printing .357 is super fuckin easy.

2020-11-01 19:18 UTC, JamieD1 commented
> jamie it takes like 10 seconds to hack an autolathe. its not any sort of actual block. printing .357 is super fuckin easy.
> a revolver with 10 speedloaders is 66 bullets at the cost of a bit of metal, time, and the TC cost of the gun itself.
> a deagle with 2 spare mags is 21 bullets, compared to 4 spare mags bringing that up to 35. its not unreasonable for them to be 2TC especially with ammo being completely non-renewable.

Its 60 Damage per bullet.

2020-11-01 19:18 UTC, closed without merging