objectives for morph and nightmare
yogstation13/Yogstation pull request #10200
Opened 2020-10-27 16:57 UTC by ynot01

### Intent of your Pull Request

gives generic objectives + stay alive to morph and nightmare
also tells all ghosts morph is antag

#### Changelog

:cl:  
rscadd: Added objectives for morph
rscadd: Added objectives for nightmare
tweak: Morphs now show_to_ghosts
/:cl:

2020-10-27 17:00 UTC, Mqiib commented
Yes let's give the midround antag that already murderboners but could be way cooler an official pass to just murderbone and do nothing else. Good idea, very cool.

2020-10-27 17:03 UTC, ynot01 commented
> Yes let's give the midround antag that already murderbones but could be way cooler an official pass to just murderbone and do nothing else. Good idea, very cool.

that's the plan

2020-10-28 17:09 UTC, nichlas0010 requested changes

2020-10-28 17:09 UTC, nichlas0010 commented on code/modules/antagonists/morph/morph_antag.dm
> +	new_objective.explanation_text = "Consume everything." // you can do whatever
should probably make the objective auto-complete if there's no check for completing it

2020-10-28 17:09 UTC, nichlas0010 commented on code/modules/antagonists/nightmare/nightmare.dm
> +	survival.owner = owner
see above

2020-10-28 20:44 UTC, Mqiib commented
I'd rather nightmares have no objectives than haha funny kill everyone but bold.

2020-10-29 12:06 UTC, nichlas0010 approved these changes

2020-10-29 12:06 UTC, merged