removes the hard age lock on changing jobs
yogstation13/Yogstation pull request #10206
Opened 2020-10-27 23:42 UTC by SomeguyManperson

attempting to switch an ID to a job it can't take closes the job reassignment  bit of the window and the message is sent to chat meaning it is highly likely you could miss it and be like "why isn't this ID changing jobs wtf"

also call me back when you apply this for nonhumans in head roles :^)
:cl:  
tweak: the fail state for changing an ID to a job it is too young to have has been removed
/:cl:

2020-10-28 02:04 UTC, MegaEmpirical commented
Fucking just remove age from the game.

2020-10-28 04:22 UTC, Tipy1802 commented
It’s not a hard lock you num nun, just change the age

2020-10-28 04:29 UTC, Tipy1802 commented
IF your problem is people not realising they have to change the age then that’s really a player problem since I haven’t had a problem with that or seen anyone not realise what happen since it says in the chat, even then you can just make the text bigger so it’s harder to miss

2020-10-28 06:21 UTC, SomeguyManperson commented
yes I COULD make it less of a pain in the ass OOOOOOR I could make it not a pain in the ass at all, which is what I'm doing

2020-10-28 06:57 UTC, Moja10 commented
I'm glad you brought up nonhumans, because I would be totally down to make it so neither underage nor nonhumans could switch their ID to a head/age protected role.

2020-10-29 12:00 UTC, nichlas0010 requested changes
Make it tell the user they're too young but not block it :)

2020-11-01 11:53 UTC, nichlas0010 requested changes

2020-11-01 11:53 UTC, nichlas0010 commented on code/game/machinery/computer/card.dm
> -						return
just remove these 2 lines and keep the other 2 in

2020-11-01 19:11 UTC, JamieD1 commented
Changed to Suggest only as nich wanted.

2020-11-01 19:22 UTC, merged