Syndi pirates no longer spawn with atmos things
yogstation13/Yogstation pull request #10234
Opened 2020-10-28 22:57 UTC by ynot01

### Intent of your Pull Request

they are skeletons
removed atmos alarms
removed atmos piping
removed atmos tank
removed 2 EVA suit storages
removed breath mask and oxy tank from pirate spawn

#### Changelog

:cl:  
rscdel: Syndi pirates no longer spawn with atmos things
/:cl:

2020-10-28 22:58 UTC, Hopekz commented
The ship is stolen not really purpose-built for them

2020-10-28 23:02 UTC, Takahiru commented
> The ship is stolen not really purpose-built for them

tbh makes sense with this reasoning, though theres no reason for them to have oxygen tanks

2020-10-28 23:04 UTC, TheLinuxOS commented
> The ship is stolen not really purpose-built for them

I mean if I was a pirate id remove parts of the ship that do nothing but take up space, such as removing the air alarms and selling the eva suits and oxygen supplies so it makes sense for them to be removed in my opinion

2020-10-29 02:04 UTC, SomeguyManperson commented
suits and stuff are useful for kidnapping people if you don't want to drop the ship right next to the station

2020-10-29 02:46 UTC, ynot01 commented
> suits and stuff are useful for kidnapping people if you don't want to drop the ship right next to the station

valid point, i will counter anecdotally that i have never seen this happen

2020-10-29 07:47 UTC, ToGWtF commented
Because selling living people is so little money compared to just raiding the entire ore supply.

2020-10-29 12:10 UTC, wejengin2 commented
Is there any reason for removing this aside from "It's not used by them".

2020-10-29 12:20 UTC, ynot01 commented
the ship goes blue when atmos goes slightly fucky because theres air alarms and vents

this also alerts the station that theres an atmos alarm in the ship

pretty pointless to have it all

2020-10-29 16:33 UTC, Hopekz commented
> this also alerts the station that theres an atmos alarm in the ship

Sounds like a different PR to make ships outside of the station not send atmos alarms to the station.
If this is the main reason for this PR existing you are fixing it in a very sloppy way that in my opinion is compromising the feel of the pirate ship being stolen.

2020-10-30 08:09 UTC, wejengin2 requested changes
I'm ok with removing only the air alarms as a bandaid fix until a coder fixes the actual issue. Basically what Hopek said.

2020-10-30 16:13 UTC, ynot01 commented
if you're so worried about kidnappings i can put an o2 canister in and you can set it to 101kpa

2020-10-30 16:43 UTC, wejengin2 commented
It's more a matter of being worried of removing things that don't need to be removed. I'm proposing a non code solution that will basically keep the shape and look of the original interior, while solving the problems you listed.

2020-11-01 18:54 UTC, JamieD1 commented
This will ruin live crew interactions completely.

2020-11-02 17:17 UTC, Reed0506 commented
what if the air alarms are such are just smashed and broken by default, not compromising hopek's "stolen" vibes, but also removing the issues that the bits and bobs can cause.

2020-11-04 18:57 UTC, closed without merging