more reasonable genetics nerf
yogstation13/Yogstation pull request #10310
Opened 2020-11-02 18:55 UTC by boodaliboo

alternative to pr https://github.com/yogstation13/Yogstation/pull/10224

hulk changed to 60
thermal changed to 35
space adaptation changed to 40
telekenesis changed to 40

#### Changelog

:cl:  
tweak: tweaked genetics instability
/:cl:

2020-11-02 19:01 UTC, jcatjmeow commented
### Intent of your Pull Request
Explain what the purpose of your PR is. Mention if you tested your changes...

### Why is this good for the game?
Explain why each change in your pr is beneficial to the server. This is less necessary for bugfixes and such, but is always welcome. Remember: something that is self evident to you might not be to others. Explain your rationale even if you feel it goes without saying.

2020-11-02 19:34 UTC, Marmio64 commented
increase SA to 45 so that it cant be combo'd with hulk unless you get a stabilizer chromosome

2020-11-02 19:51 UTC, athena413 commented
space adapt needs a more substantial cost imo because its basically a free space suit except not even a space suit so you can wear armour and other shit with no penalty

2020-11-02 20:36 UTC, MegaEmpirical commented
I feel like your own description is an argument against your PR. I feel so confused.

2020-11-02 20:47 UTC, boodaliboo commented
> I feel like your own description is an argument against your PR. I feel so confused.

look at gamers pr and see his nerfs there ludicrous and it also nerfs mutations that are awful anyways like shock touch

2020-11-03 22:14 UTC, ToGWtF commented
Thermals is literally the reason gamer made his PR. make it more than 35. its literally round ending for every antag type

2020-11-04 18:24 UTC, JamieD1 requested changes

2020-11-04 18:24 UTC, JamieD1 commented on code/datums/mutations/hulk.dm
> +	instability = 60
```suggestion
	instability = 65
```

2020-11-04 18:24 UTC, JamieD1 commented on code/datums/mutations/sight.dm
> +	instability = 35
```suggestion
	instability = 40
```

2020-11-04 18:59 UTC, merged

2020-11-04 22:00 UTC, MegaEmpirical commented
Bastards.