Adds a new captain id fire cabinet to captains office with functionality.
yogstation13/Yogstation pull request #10352
Opened 2020-11-07 20:51 UTC by JamieD1

Adds fire cabinet with the spare id instead of breaking open the locker every round.

#### Changelog

:cl:  
rscadd: Added new spare id locker in captains room
rscdel: Removed spare from captains locker
/:cl:

2020-11-07 20:59 UTC, TheGamerdk commented
godawful code haha

2020-11-07 21:27 UTC, FLME requested changes
This PR only applies to box, meaning that spare IDs will only exist on Boxstation, and not:

Eclipsestation
Metastation
IceBox
Omegastation
Deltastation

2020-11-07 21:48 UTC, JamieD1 commented
> This PR only applies to box, meaning that spare IDs will only exist on Boxstation, and not:
> 
> Eclipsestation
> Metastation
> IceBox
> Omegastation
> Deltastation

Done

2020-11-07 21:59 UTC, FLME approved these changes
Looks good, I just think that this intersecting the air alarm on metastation looks real fucking weird
![image](https://user-images.githubusercontent.com/15719834/98452137-3529ec80-2112-11eb-99c2-561f4cc7cf26.png)

2020-11-07 22:12 UTC, wejengin2 requested changes
What Athena said and my reviews from box

2020-11-07 22:12 UTC, patpol4 commented on _maps/map_files/YogStation/YogStation.dmm
> +	c_tag = "Captains Office";
Captain's Quarters

2020-11-07 22:12 UTC, patpol4 commented on _maps/map_files/YogStation/YogStation.dmm
> +	pixel_y = 30;
only pixel_y = 32

2020-11-07 22:12 UTC, patpol4 commented on _maps/map_files/YogStation/YogStation.dmm
> +	req_access = list(20)
pretty sure you have to do req_access_txt = "20"

2020-11-07 22:12 UTC, patpol4 commented on _maps/map_files/YogStation/YogStation.dmm
> +/obj/structure/dresser,
double dresser hmmmmmmm

2020-11-08 11:51 UTC, JamieD1 commented
I hate you weje

2020-11-08 12:08 UTC, merged