Make events fire slightly more often
yogstation13/Yogstation pull request #10384
Opened 2020-11-10 22:41 UTC by redmoogle

### Intent of your Pull Request

Events now fire between 2-9 minutes instead of 3-10

Makes the game slightly funner and chaotic

### Why is this good for the game?

Slightly more chaotic rounds, more fun

#### Changelog

:cl:  
tweak: Events now happen more often
/:cl:

2020-11-10 23:05 UTC, jcatjmeow approved these changes

2020-11-12 20:37 UTC, TheGamerdk requested changes

2020-11-12 20:37 UTC, TheGamerdk commented on code/controllers/subsystem/events.dm
> +	var/frequency_lower = 1200	//2 minutes lower bound.
```suggestion
	var/frequency_lower = 2 MINUTES //2 minutes lower bound.
```

2020-11-12 20:37 UTC, TheGamerdk commented on code/controllers/subsystem/events.dm
> +	var/frequency_upper = 5400	//9 minutes upper bound. Basically an event will happen every 2 to 9 minutes.
```suggestion
	var/frequency_upper = 9 MINUTES //9 minutes upper bound. Basically an event will happen every 2 to 9 minutes.
```

2020-11-14 09:18 UTC, merged