For bone pickaxe
yogstation13/Yogstation pull request #10427
Opened 2020-11-16 03:17 UTC by Magicut101

Intent of your Pull Request
Adds a Bone Pickaxe to the primal tab in crafting

Why is this good for the game?
I want to see this added for cases where you didn't have or lost your pickaxe. This would allow you to be able to make a pickaxe from scratch by killing fauna. 

Actual bone pickaxe does less damage and takes longer to mine than even a normal pickaxe. Could change that or reduce the amount of materials required for crafting.

I tested this here is my proof

![proof](https://user-images.githubusercontent.com/52367310/99209052-38ffe380-2790-11eb-8192-e4176d4c3b0c.PNG)
![proofitworks2](https://user-images.githubusercontent.com/52367310/99209084-4e750d80-2790-11eb-9a60-3d175c20d8e7.PNG)
![proofitworks3](https://user-images.githubusercontent.com/52367310/99209100-53d25800-2790-11eb-85f5-abf2d5d49040.PNG)
![BonePickaxe4](https://user-images.githubusercontent.com/52367310/99208476-7f544300-278e-11eb-9339-33f15b8450c8.PNG)
🆑
rscadd: Added new things
imageadd: added some icons and images
/🆑

2020-11-16 03:23 UTC, Marmio64 commented
maybe reduce sinew cost to two? If it is worse than a normal pickaxe it sounds like it'd be absolutely dogshit and shouldn't cost that much.

2020-11-16 03:25 UTC, Magicut101 commented
Aight I was thinking of keeping it low but wasn't sure what would be appropriate so I left it be a tad high. Its now 2

2020-11-18 04:07 UTC, Hopekz requested changes

2020-11-18 04:07 UTC, Hopekz commented on code/modules/mining/equipment/mining_tools.dm
> +	desc = "A spine and ribcage tied tightly with weaver sinew...atleast its better than your bare hands at digging up dirt."
```suggestion
	desc = "A spine and ribcage tied tightly with weaver sinew...at least it's better than your bare hands at digging up dirt."
```

2020-12-04 20:50 UTC, jcatjmeow approved these changes

2020-12-07 01:53 UTC, Smudged commented
ashwalkers should start with 1 or 2 two of these instead of the stock pickaxes

2020-12-12 14:20 UTC, merged