Huge Atmospherics Update - Five layer pipes and new funny gases
yogstation13/Yogstation pull request #10447
Opened 2020-11-18 22:21 UTC by JamieD1

Added new gases from https://github.com/tgstation/tgstation/pull/53013
Healium
Proto Nitrate
Cyrion B
Halon
Hexane

Also Added Hydrogen and Freon

Added new devices for RPD: 
Temp Gate
Temp Pump
Pressure Valve
Passive Vent

Added Five layer piping, only devices in picture are five layer.

![image](https://user-images.githubusercontent.com/993128/99594977-d7d44c00-29eb-11eb-82a5-30fc1fc77602.png)

#### Changelog

:cl:  
rscadd: Five layer piping
rscadd: Temp Gate, Temp Pump, Pressure Valve, Passive Vent
rscadd: Healium, Proto Nitrate, Cyrion B, Halon, Hexane
/:cl:

2020-11-18 23:06 UTC, Hopekz requested changes

2020-11-18 23:06 UTC, Hopekz commented on code/game/objects/items/grenades/atmos_grenades.dm
> +	desc = "Some kind of crystal, this shouldn't spawn"
```suggestion
	desc = "Some kind of crystal, this shouldn't spawn."
```

2020-11-18 23:06 UTC, Hopekz commented on code/game/objects/items/twohanded.dm
> +	desc = "A large, menacing axe made of an unkown substance that the most elder atmosians calls Metallic Hydrogen. Truly an otherwordly weapon."
```suggestion
	desc = "A large, menacing axe made of an unknown substance that the most elder atmosians call Metallic Hydrogen. Truly an otherwordly weapon."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +/// Pumps gas from src to output_air. Amount depends on target_pressure
```suggestion
/// Pumps gas from src to output_air. The amount depends on target_pressure
```
Who cares to check comments?
I do apparently

2020-11-18 23:06 UTC, Hopekz commented on code/modules/atmospherics/machinery/components/binary_devices/pressure_valve.dm
> +	desc = "An activable one way valve that let gas pass through if the pressure on the input side is higher than the set pressure."
```suggestion
	desc = "An activable one-way valve that let gas pass through if the pressure on the input side is higher than the set pressure."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/atmospherics/machinery/components/binary_devices/temperature_gate.dm
> +		to_chat(user, "<span class='notice'>You set the target temperature on [src] to [target_temperature] K.</span>")
```suggestion
		to_chat(user, "<span class='notice'>You set the target temperature on [src] to [target_temperature]K.</span>")
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	desc = "Freon. Can absorb heat"
```suggestion
	desc = "Freon. Can absorb heat."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	desc = "Hydrogen, highly flammable"
```suggestion
	desc = "Hydrogen, highly flammable."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	desc = "Healium, causes deep sleep"
```suggestion
	desc = "Healium, causes deep sleep."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	desc = "Proto Nitrate, react differently with various gases"
```suggestion
	desc = "Proto Nitrate, react differently with various gases."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	desc = "Cyrion B, highly toxic"
```suggestion
	desc = "Cyrion B, highly toxic."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	desc = "Halon, remove oxygen from high temperature fires and cool down the area"
```suggestion
	desc = "Halon, used to remove oxygen from high-temperature fires and cool down an area."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	desc = "hexane, highly flammable"
```suggestion
	desc = "hexane, highly flammable."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	description = "A suppresive gas that stops gas reactions on those who inhale it."
```suggestion
	description = "A suppressive gas that stops gas reactions on those who inhale it."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	description = "A Powerful sleeping agent with healing properties"
```suggestion
	description = "A Powerful sleeping agent with healing properties."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	description = "A firefighter gas that remove oxygen and cool down the area"
```suggestion
	description = "A firefighter gas that removes oxygen and cools down the area."
```

2020-11-18 23:06 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	description = "A filtering gas, don't breathe it if you suffer from brain conditions"
```suggestion
	description = "A filtering gas, don't breathe it if you suffer from brain conditions."
```

2020-11-18 23:08 UTC, Hopekz commented on code/game/objects/items/RPD.dm
> +	if(source.incapacitated(ignore_restraints = TRUE, ignore_stasis = TRUE))
This is where your compile error is coming from btw

2020-11-18 23:46 UTC, swissloaf commented on code/modules/atmospherics/machinery/components/binary_devices/temperature_gate.dm
> +		to_chat(user, "<span class='notice'>You set the target temperature on [src] to [target_temperature] K.</span>")
theres a space between temperature and kelvins, this is incorrect

2020-11-19 23:47 UTC, Hopekz commented on code/modules/atmospherics/machinery/components/binary_devices/temperature_gate.dm
> +		to_chat(user, "<span class='notice'>You set the target temperature on [src] to [target_temperature] K.</span>")
> there's a space between temperature and kelvins; this is incorrect

Fair enough; my bad.

2020-11-20 14:23 UTC, AutisticFroggy commented
Awaiting with bated breath

2020-11-20 16:51 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	description = "A firefighter gas that removes oxygen and cools down the area."
```suggestion
	description = "A firefighter gas that removes oxygen and cools down an area."
```
This showed up in my dream as something that needed to be changed

2020-11-21 18:01 UTC, Moja10 commented on code/modules/cargo/exports/large_objects.dm
> +	worth += C.air_contents.get_moles(/datum/gas/proto_nitrate)*5
```suggestion
	worth += C.air_contents.get_moles(/datum/gas/pluonium)*5
```

2020-11-21 18:03 UTC, Moja10 commented on code/modules/cargo/exports/large_objects.dm
> +	worth += C.air_contents.get_moles(/datum/gas/proto_nitrate)*5
```suggestion
	worth += C.air_contents.get_moles(/datum/gas/pluonium)*5
```

2020-11-21 18:04 UTC, Moja10 commented on code/modules/atmospherics/machinery/portable/scrubber.dm
> +		/datum/gas/proto_nitrate,
```suggestion
		/datum/gas/pluonium,
```

2020-11-21 18:04 UTC, Moja10 commented on code/modules/atmospherics/machinery/portable/canister.dm
> +		"proto_nitrate" = /obj/machinery/portable_atmospherics/canister/proto_nitrate,
```suggestion
		"proto_nitrate" = /obj/machinery/portable_atmospherics/canister/pluonium,
```

2020-11-21 18:06 UTC, Moja10 commented on code/modules/atmospherics/machinery/airalarm.dm
> +						/datum/gas/proto_nitrate,
```suggestion
						/datum/gas/pluonium,
```

2020-11-21 18:06 UTC, Moja10 commented on code/modules/atmospherics/machinery/airalarm.dm
> +		/datum/gas/proto_nitrate	= new/datum/tlv/dangerous,
```suggestion
		/datum/gas/pluonium	= new/datum/tlv/dangerous,
```

2020-11-21 18:07 UTC, Moja10 commented on code/modules/atmospherics/machinery/airalarm.dm
> +		/datum/gas/proto_nitrate	= new/datum/tlv/dangerous,
```suggestion
		/datum/gas/pluonium	= new/datum/tlv/dangerous,
```

2020-11-21 18:07 UTC, Moja10 commented on code/modules/atmospherics/machinery/airalarm.dm
> +		/datum/gas/proto_nitrate	= new/datum/tlv/dangerous,
```suggestion
		/datum/gas/pluonium	= new/datum/tlv/dangerous,
```

2020-11-21 18:09 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_formation
```suggestion
/datum/gas_reaction/pluonium_formation
```

2020-11-21 18:09 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	name = "Proto Nitrate formation"
```suggestion
	name = "Pluonium formation"
```

2020-11-21 18:10 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	id = "proto_nitrate_formation"
```suggestion
	id = "pluonium_formation"
```

2020-11-21 18:12 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/gas_types.dm
> +/datum/gas/proto_nitrate
```suggestion
/datum/gas/pluonium
```

2020-11-21 18:12 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/gas_types.dm
> +	id = "proto_nitrate"
```suggestion
	id = "pluonium"
```

2020-11-21 18:12 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/gas_types.dm
> +	gas_overlay = "proto_nitrate"
```suggestion
	gas_overlay = "pluonium"
```

2020-11-21 18:14 UTC, Moja10 commented on code/game/objects/items/grenades/atmos_grenades.dm
> +/obj/item/grenade/gas_crystal/proto_nitrate_crystal
```suggestion
/obj/item/grenade/gas_crystal/pluonium_crystal
```

2020-11-21 18:14 UTC, Moja10 commented on code/game/objects/items/grenades/atmos_grenades.dm
> +	name = "Proto Nitrate crystal"
```suggestion
	name = "Pluonium crystal"
```

2020-11-21 18:15 UTC, Moja10 commented on code/game/objects/items/grenades/atmos_grenades.dm
> +	desc = "A crystal made from the Proto Nitrate gas, you can see the liquid gases inside."
```suggestion
	desc = "A crystal made from the Pluonium gas, you can see the liquid gases inside."
```

2020-11-21 18:15 UTC, Moja10 commented on code/game/objects/items/grenades/atmos_grenades.dm
> +	icon_state = "proto_nitrate_crystal"
Too lazy to rename the icon but I would like to point out that it could be changed to "pluonium_crystal" if you so choose

2020-11-21 18:17 UTC, Moja10 commented on code/__DEFINES/atmospherics.dm
> +#define ATMOS_TANK_PROTO_NITRATE	"proto_nitrate=100000;TEMP=293.15"
```suggestion
#define ATMOS_TANK_PLUONIUM	"pluonium=100000;TEMP=293.15"
```

2020-11-21 18:24 UTC, Moja10 commented on code/__DEFINES/atmospherics.dm
> +#define ATMOS_GAS_MONITOR_INPUT_PROTO_NITRATE "proto-nitrate_in"
```suggestion
#define ATMOS_GAS_MONITOR_INPUT_PLUONIUM "pluonium_in"
```

2020-11-21 18:25 UTC, Moja10 commented on code/__DEFINES/atmospherics.dm
> +#define ATMOS_GAS_MONITOR_OUTPUT_PROTO_NITRATE "proto-nitrate_out"
```suggestion
#define ATMOS_GAS_MONITOR_OUTPUT_PLUONIUM "pluonium_out"
```

2020-11-21 18:25 UTC, Moja10 commented on code/__DEFINES/atmospherics.dm
> +#define ATMOS_GAS_MONITOR_SENSOR_PROTO_NITRATE "proto-nitrate_sensor"
```suggestion
#define ATMOS_GAS_MONITOR_SENSOR_PLUONIUM "pluonium_sensor"
```

2020-11-21 18:25 UTC, Moja10 commented on code/datums/components/crafting/recipes.dm
> +				// jamie - /obj/item/grenade/gas_crystal/proto_nitrate_crystal = 1,
```suggestion
				// jamie - /obj/item/grenade/gas_crystal/pluonium_crystal = 1,
```

2020-11-21 18:25 UTC, Moja10 commented on code/game/objects/items/grenades/atmos_grenades.dm
> +/obj/item/grenade/gas_crystal/proto_nitrate_crystal/prime(mob/living/lanced_by)
```suggestion
/obj/item/grenade/gas_crystal/pluonium_crystal/prime(mob/living/lanced_by)
```

2020-11-21 18:26 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_formation/init_reqs()
```suggestion
/datum/gas_reaction/pluonium_formation/init_reqs()
```

2020-11-21 18:26 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_formation/react(datum/gas_mixture/air, datum/holder)
```suggestion
/datum/gas_reaction/pluonium_formation/react(datum/gas_mixture/air, datum/holder)
```

2020-11-21 18:26 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	air.adjust_moles(/datum/gas/proto_nitrate, (heat_efficency * 2.2))
```suggestion
	air.adjust_moles(/datum/gas/pluonium, (heat_efficency * 2.2))
```

2020-11-21 18:27 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_bz_response
```suggestion
/datum/gas_reaction/pluonium_bz_response
```

2020-11-21 18:27 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	name = "Proto Nitrate bz response"
```suggestion
	name = "Pluonium bz response"
```

2020-11-21 18:27 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	id = "proto_nitrate_bz_response"
```suggestion
	id = "Pluonium_bz_response"
```

2020-11-21 18:28 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_bz_response/init_reqs()
```suggestion
/datum/gas_reaction/pluonium_bz_response/init_reqs()
```

2020-11-21 18:28 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +		/datum/gas/proto_nitrate = MINIMUM_MOLE_COUNT,
```suggestion
		/datum/gas/pluonium = MINIMUM_MOLE_COUNT,
```

2020-11-21 18:28 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_bz_response/react(datum/gas_mixture/air, datum/holder)
```suggestion
/datum/gas_reaction/pluonium_bz_response/react(datum/gas_mixture/air, datum/holder)
```

2020-11-21 18:28 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	var consumed_amount = min(5, air.get_moles(/datum/gas/bz), air.get_moles(/datum/gas/proto_nitrate))
```suggestion
	var consumed_amount = min(5, air.get_moles(/datum/gas/bz), air.get_moles(/datum/gas/pluonium))
```

2020-11-21 18:28 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_tritium_response
```suggestion
/datum/gas_reaction/pluonium_tritium_response
```

2020-11-21 18:29 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	id = "proto_nitrate_tritium_response"
```suggestion
	id = "pluonium_tritium_response"
```

2020-11-21 18:29 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_tritium_response/init_reqs()
```suggestion
/datum/gas_reaction/pluonium_tritium_response/init_reqs()
```

2020-11-21 18:29 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +		/datum/gas/proto_nitrate = MINIMUM_MOLE_COUNT,
```suggestion
		/datum/gas/pluonium = MINIMUM_MOLE_COUNT,
```

2020-11-21 18:29 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_tritium_response/react(datum/gas_mixture/air, datum/holder)
```suggestion
/datum/gas_reaction/pluonium_tritium_response/react(datum/gas_mixture/air, datum/holder)
```

2020-11-21 18:29 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	var produced_amount = min(5, air.get_moles(/datum/gas/tritium), air.get_moles(/datum/gas/proto_nitrate))
```suggestion
	var produced_amount = min(5, air.get_moles(/datum/gas/tritium), air.get_moles(/datum/gas/pluonium))
```

2020-11-21 18:29 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	if(air.get_moles(/datum/gas/tritium) - produced_amount < 0 || air.get_moles(/datum/gas/proto_nitrate) - produced_amount * 0.01 < 0)
```suggestion
	if(air.get_moles(/datum/gas/tritium) - produced_amount < 0 || air.get_moles(/datum/gas/pluonium) - produced_amount * 0.01 < 0)
```

2020-11-21 18:30 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	air.adjust_moles(/datum/gas/proto_nitrate, -(produced_amount * 0.01))
```suggestion
	air.adjust_moles(/datum/gas/pluonium, -(produced_amount * 0.01))
```

2020-11-21 18:30 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_hydrogen_response
```suggestion
/datum/gas_reaction/pluonium_hydrogen_response
```

2020-11-21 18:30 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	id = "proto_nitrate_hydrogen_response"
```suggestion
	id = "pluonium_hydrogen_response"
```

2020-11-21 18:30 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_hydrogen_response/init_reqs()
```suggestion
/datum/gas_reaction/pluonium_hydrogen_response/init_reqs()
```

2020-11-21 18:31 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +		/datum/gas/proto_nitrate = MINIMUM_MOLE_COUNT,
```suggestion
		/datum/gas/pluonium = MINIMUM_MOLE_COUNT,
```

2020-11-21 18:31 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/proto_nitrate_hydrogen_response/react(datum/gas_mixture/air, datum/holder)
```suggestion
/datum/gas_reaction/pluonium_hydrogen_response/react(datum/gas_mixture/air, datum/holder)
```

2020-11-21 18:31 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	var produced_amount = min(5, air.get_moles(/datum/gas/hydrogen), air.adjust_moles(/datum/gas/proto_nitrate))
```suggestion
	var produced_amount = min(5, air.get_moles(/datum/gas/hydrogen), air.adjust_moles(/datum/gas/pluonium))
```

2020-11-21 18:31 UTC, Moja10 commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	air.adjust_moles(/datum/gas/proto_nitrate, (produced_amount * 0.5))
```suggestion
	air.adjust_moles(/datum/gas/pluonium, (produced_amount * 0.5))
```

2020-11-21 18:32 UTC, Moja10 commented on code/modules/atmospherics/machinery/portable/canister.dm
> +/obj/machinery/portable_atmospherics/canister/proto_nitrate
```suggestion
/obj/machinery/portable_atmospherics/canister/pluonium
```

2020-11-21 18:32 UTC, Moja10 commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	name = "Proto Nitrate canister"
```suggestion
	name = "Pluonium canister"
```

2020-11-21 18:33 UTC, Moja10 commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	desc = "Proto Nitrate, react differently with various gases"
```suggestion
	desc = "Pluonium, react differently with various gases."
```

2020-11-21 18:33 UTC, Moja10 commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	icon_state = "proto_nitrate"
```suggestion
	icon_state = "proto_nitrate"
```

Too lazy to change the .dmi

2020-11-21 18:33 UTC, Moja10 commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	gas_type = /datum/gas/proto_nitrate
```suggestion
	gas_type = /datum/gas/pluonium
```

2020-11-21 18:34 UTC, Moja10 commented on code/modules/power/supermatter/supermatter.dm
> +#define PROTO_NITRATE_TRANSMIT_MODIFIER 15
```suggestion
#define PLUONIUM_TRANSMIT_MODIFIER 15
```

2020-11-21 18:34 UTC, Moja10 commented on code/modules/power/supermatter/supermatter.dm
> +#define PROTO_NITRATE_HEAT_RESISTANCE 5
```suggestion
#define PLUONIUM_HEAT_RESISTANCE 5
```

2020-11-21 18:36 UTC, Moja10 commented
My job here is done

2020-11-21 21:05 UTC, wejengin2 commented
Based Moja spamming pointless review :sunglasses:

2020-11-21 21:34 UTC, alexkar598 commented
Goddamit, deleting the spam causes spam, what genius thought that up?

2020-11-23 21:21 UTC, wejengin2 commented
r

2020-11-24 08:35 UTC, SomeguyManperson commented on code/modules/cargo/exports/materials.dm
> +	export_types = /obj/item/stack/sheet/hot_ice
Export types for both of these should be lists, metal hydrogen probsbly doesn't need an export_types list either

2020-11-26 20:52 UTC, JamieD1 commented
Will follow up with a patch pr, so maps can be merged again.

2020-11-26 20:54 UTC, merged

2020-12-02 21:57 UTC, Ghilker commented
Please properly mention the original PRs in your huge porting
Hydrogen tgstation/tgstation#50510
Freon tgstation/tgstation#49821
Temp Gate tgstation/tgstation#53632
Temp Pump tgstation/tgstation#53608
Pressure Valve tgstation/tgstation#53281
Five layer piping tgstation/tgstation#53278