Jamie Fixes bugs and closes loopholes and Pisses off the Players and the Admins at the same time!
yogstation13/Yogstation pull request #10502
Opened 2020-11-25 22:16 UTC by JamieD1

Fixes: Achievements not opening
Fixes: Missing Admin verbs
Fixes: Collectable kitty ears not using colour
Fixes: Icon sprites on arcade machines
Fixes: Can sprites for monkey energy and cranberry.
Removes: Mods ability to grab from centcom (council approved)
Removes: Ability to RPD on Reebe (FUCKING TRANSPORT PIPES)
Removes: Stupid fun ending ion law (SUICIDE NOW KEK)
Removes: Ling Checks (Lings now Fakedeath on brain removal, (hopefully))

#### Changelog

:cl:  
bugfix: Achievements not opening
bugfix: Missing Admin verbs
bugfix: Collectable kitty ears not using colour
bugfix: Icon sprites on arcade machines
bugfix: Can sprites for monkey energy and cranberry.
rscdel: Mods ability to grab from centcom (council approved)
rscdel: Ability to RPD on Reebe (FUCKING TRANSPORT PIPES)
rscdel: Stupid fun ending ion law (SUICIDE NOW KEK)
rscdel: Ling Checks (Lings now Fakedeath on brain removal, (hopefully))
/:cl:

2020-11-25 22:26 UTC, wejengin2 commented
Really impressed by that changelog

2020-11-25 22:32 UTC, monster860 requested changes

2020-11-25 22:32 UTC, monster860 commented on code/modules/admin/topic.dm
> +			if(AM.z == 1)
WOoP WOOP SHITCODE ALERT use `is_centcom_level(AM.z)` ree

also consider allowing teleporting from centcom to centcom.

2020-11-25 23:02 UTC, Hopekz commented
watch out jcat might think this is a meme PR because you forgot to type out 2 paragraphs on why your fixes are good for the game!

2020-11-26 08:31 UTC, Jarod1200 commented
Make rpds shit out uncooked spaghetti if used on reebe

2020-11-26 12:44 UTC, redmoogle approved these changes
Changes are fine, looked at code

2020-11-26 15:18 UTC, boba247 commented
Is there a way mods can retrieve people from the admin prison?

2020-11-26 16:06 UTC, wejengin2 commented
> Is there a way mods can retrieve people from the admin prison?

i think you just press the prison button again?

2020-11-26 19:12 UTC, Xoxeyos commented
> 
> 
> > Is there a way mods can retrieve people from the admin prison?
> 
> i think you just press the prison button again?

That doesn't work.

2020-11-26 20:46 UTC, merged