adds pea wine
yogstation13/Yogstation pull request #10554
Opened 2020-11-30 20:39 UTC by boodaliboo

you can now distill peas into pea wine
previously it didnt create anything
#### Changelog

:cl:  
rscadd: Added pea wine and a way to distill it
/:cl:

2020-12-01 14:21 UTC, wejengin2 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	taste_description = "rotting vegatables"
vegetables

2020-12-01 14:22 UTC, wejengin2 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "A freezing glass of pea wine."
Why is it cold

2020-12-01 16:35 UTC, boodaliboo commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "A freezing glass of pea wine."
i dunno

2020-12-01 17:47 UTC, wejengin2 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "A freezing glass of pea wine."
maybe its the peas

2020-12-04 20:51 UTC, jcatjmeow requested changes

2020-12-04 20:51 UTC, jcatjmeow commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	description = "An alcoholic beverage That is created through distilling pees."
```suggestion
	description = "An alcoholic beverage That is created through distilling peas."
```

2020-12-12 14:30 UTC, merged