five layer burrito description spelling
yogstation13/Yogstation pull request #10574
Opened 2020-12-03 13:56 UTC by Ktlwjec1

title

2020-12-03 14:20 UTC, jcatjmeow submitted a review, later dismissed
grammer

2020-12-03 14:20 UTC, jcatjmeow commented on code/modules/food_and_drinks/food/snacks_other.dm
> +	desc = "Five burritos stacked on top of each other, looks suspiciously like a layer manifold."
```suggestion
	desc = "Five burritos stacked on top of each other. It looks suspiciously like a layer manifold."
```

2020-12-03 21:05 UTC, Hopekz requested changes

2020-12-03 21:05 UTC, Hopekz commented on code/modules/food_and_drinks/food/snacks_other.dm
> +	desc = "Five burritos stacked on top of each other, looks suspiciously like a layer manifold."
```suggestion
	desc = "Five 🌯burritos 🌯 stacked 🔛on🔛🔛 ⬆️top⬆️ of each other. It looks👀 suspiciously like👍👍 a🅰️ layer manifold."
```

2020-12-04 21:23 UTC, redmoogle approved these changes
~~Oops~~ Goob pr 👍

2020-12-04 21:27 UTC, merged