Supermatter Autodoc + Code Cleanup
yogstation13/Yogstation pull request #10590
Opened 2020-12-05 18:08 UTC by redmoogle

### Intent of your Pull Request

Cleans the code up
Also adds autodoc for variables

### Why is this good for the game?

Clean code is good

#### Changelog

:cl:  
tweak: SM has cleaner code
/:cl:

2020-12-05 19:35 UTC, TheGamerdk requested changes
holy moly SM code was bad

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +// Higher == Bigger bonus to power generation.
```suggestion
/// Higher == Bigger bonus to power generation. 
```

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +// Higher == Bigger heat and waste penalty from having the crystal surrounded by this gas. Negative numbers reduce penalty.
```suggestion
/// Higher == Bigger heat and waste penalty from having the crystal surrounded by this gas. Negative numbers reduce penalty.
```

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +// How much energy before SM prints tesla warnings
```suggestion
/// How much energy before SM prints tesla warnings
```

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +// How much heat before SM prints warnings
```suggestion
/// How much heat before SM prints warnings
```

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +// All of these get divided by 10-bzcomp * 5 before having 1 added and being multiplied with power to determine rads
```suggestion
/// All of these get divided by 10-bzcomp * 5 before having 1 added and being multiplied with power to determine rads
```

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +// How much extra radioactivity to emit
```suggestion
/// How much extra radioactivity to emit
```

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +//Higher == Gas makes the crystal more resistant against heat damage.
```suggestion
/// Higher == Gas makes the crystal more resistant against heat damage.
```

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +	/// Strings for radio
Don't autodoc general comments, autodoc for individual variables

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +	/// Variables for calculating SM Health
Don't autodoc general comments, autodoc for individual variables

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +	/// Antinobilium related variables
Don't autodoc general comments, autodoc for individual variables

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +	/// Radio related variables
Don't autodoc general comments, autodoc for individual variables

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +	/// Logging
Don't autodoc general comments, autodoc for individual variables

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +	/// Hugbox Supermatter Variables
Don't autodoc general comments, autodoc for individual variables

2020-12-05 19:35 UTC, TheGamerdk commented on code/modules/power/supermatter/supermatter.dm
> +	/// Holder variables
Don't autodoc general comments, autodoc for individual variables

2020-12-06 14:46 UTC, JamieD1 approved these changes

2020-12-06 14:46 UTC, merged