adds the giga drill to mining vendor for 1 million mining points
yogstation13/Yogstation pull request #10618
Opened 2020-12-08 17:14 UTC by boodaliboo

gigadrill is incredibly overpowered but has no way currently to be spawned but by admins which wont likely ever happen as it isnt intresting outside of how good it mines. 1 million points is a insane ammount of mining points and if someone gets that much they deserve the drill
#### Changelog

:cl:  
rscadd: Added giga drill to mining vendor 
/:cl:

2020-12-08 17:26 UTC, AutisticFroggy commented on code/modules/mining/machine_vending.dm
> +
One more closing parentheses and you're good to go

2020-12-08 17:27 UTC, AutisticFroggy commented
50k mining points. At 1 million there will be nothing left to mine, at 50k points, there's enough material that mining any more extra won't make too much of a difference. If not 50, then whatever is a decently achievable but difficult amount of points.

2020-12-08 18:16 UTC, Mesalikepie commented
New objective once I leave LOA. Get this

2020-12-09 17:23 UTC, jcatjmeow requested changes

2020-12-09 17:23 UTC, jcatjmeow commented on code/modules/mining/machine_vending.dm
> +		)
```suggestion
	)
```

2020-12-09 17:40 UTC, alexkar598 commented
adding this will mark the end of getting xenoarch, sad pog but okay i guess as long as theres enough mats at that point that it doesnt matter

2020-12-09 17:57 UTC, boodaliboo commented
> adding this will mark the end of getting xenoarch, sad pog but okay i guess as long as theres enough mats at that point that it doesnt matter

that is a lie you stopped working on xenoarch years ago

2020-12-10 15:27 UTC, alexkar598 commented
yes

2020-12-12 14:53 UTC, JamieD1 approved these changes

2020-12-12 14:53 UTC, merged