(port) permabrig license plate press
yogstation13/Yogstation pull request #10637
Opened 2020-12-10 20:42 UTC by boodaliboo

original pr: https://github.com/tgstation/tgstation/pull/49452
"adds a license press prisoners can use to make license plates from empty ones. Makes a small profit"
#### Changelog

:cl:  
rscadd: Added a new kinda job for permabrig prisoners to make license plates
/:cl:

2020-12-10 20:48 UTC, boodaliboo commented
![image](https://user-images.githubusercontent.com/40642354/101828105-f8bd2800-3ae5-11eb-8bd7-39c7f7f1aa46.png)
 this needs defining

2020-12-10 20:59 UTC, UselessTheremin commented
....what are license plates for

2020-12-10 20:59 UTC, boodaliboo commented
> ....what are license plates for

selling

2020-12-10 21:00 UTC, UselessTheremin commented
> > ....what are license plates for
> 
> selling

ah ok cool

2020-12-10 21:10 UTC, Tipy1802 commented
very nice, would make more sense if it was a workcamp thing though. Maybe even have the blank plates be made from metal.
But even in this form this is very cool

2020-12-10 21:36 UTC, boodaliboo commented
i need to either define the var or find a new one

2020-12-11 09:30 UTC, wejengin2 requested changes
Don't place the machine in the pathway, you're preventing people from walking, try the left or right side of perma maybe?

2020-12-11 09:44 UTC, JamieD1 approved these changes
Approving ART ONLY for now.

2020-12-11 11:41 UTC, TheGamerdk commented on code/game/objects/items/stacks/license_plates.dm
> +/obj/item/stack/license_plates/filled/update_icon_state()
```suggestion
/obj/item/stack/license_plates/filled/update_icon()
```
pretty sure

2020-12-11 14:59 UTC, Marmio64 commented
once again, another broken PR by bood

2020-12-11 16:33 UTC, TheGamerdk commented
> once again, another broken PR by bood

shut the fuck up

2020-12-11 17:47 UTC, Xoxeyos commented
How do these perma prisoners turn in their cash? Their ID's aren't exactly with them in perma. TG has a prisoner role, and I don't believe this PR is necessary for our server. https://tgstation13.org/wiki/Prisoner

2020-12-11 17:49 UTC, boodaliboo commented
> How do these perma prisoners turn in their cash? Their ID's aren't exactly with them in perma. TG has a prisoner role, and I don't believe this PR is necessary for our server. https://tgstation13.org/wiki/Prisoner

cash is useless for prisoners but sec can sell them

2020-12-21 11:02 UTC, wejengin2 commented
Reminder this one is still waiting on a map change

2020-12-24 19:30 UTC, closed without merging