Fixes & Buffs Rotatium
yogstation13/Yogstation pull request #10739
Opened 2020-12-27 13:59 UTC by redmoogle

### Intent of your Pull Request

Turns rotatium into a warcrime while not making your screen rotate forever

Buffed metab rate just so it's a little 'fairer'

### Why is this good for the game?

Fixes a bug and makings rotatium a little more worthwhile

#### Changelog

:cl:  
bugfix: Rotatium no longer spins your screen forever
tweak: Rotatium is more powerful
/:cl:

2020-12-27 14:26 UTC, jcatjmeow requested changes
This is literally worse

2020-12-27 14:29 UTC, wejengin2 commented
Can you give us a gif of it in action

2020-12-27 14:31 UTC, redmoogle commented
> 
> 
> This is literally worse

Define, because thats the point


> 
> 
> Can you give us a gif of it in action

https://youtu.be/Qrf6rTwEDxs

2020-12-27 16:02 UTC, maxion12345 commented
>buff
ohno

2020-12-31 10:57 UTC, JamieD1 approved these changes

2020-12-31 10:59 UTC, merged