Ports IPCs from Beestation
yogstation13/Yogstation pull request #10756
Opened 2020-12-31 01:59 UTC by redmoogle

### Intent of your Pull Request

Credits to BeeStation(Credits would be a milelong if I listed each individual port)

Adds IPCs
![image](https://user-images.githubusercontent.com/20369082/103390196-1b3cd280-4ae1-11eb-9f6f-5c4c8130da15.png)

System Cleaner | 1 part Ethanol, 1 part Chlorine, 2 parts Phenol, 1 part Potassium | Quickly purges toxin damage in the rare case an IPC gets said damge.

Solder: | 1 part Ethanol, 1 part Copper, 1 part Silver, Temperature 374K | Quickly heals brain damage and traumas, but only for IPCs

_Still Testing_

- [x] Remove that liver runtime
- [ ] Test Mechfabs
- [x] Test Chemicals
- [x] Test Charging
- [x] Test ORGANIC/SYNTHETIC Chemicals
- [x] Fix Limb Issue
- [ ] Test Revival/Surgery     

### Why is this good for the game?

Is a very cool race and could easily have some cool interactions

#### Changelog

:cl:  
rscadd: Add IPCs from Beestation
/:cl:

2020-12-31 02:24 UTC, Moja10 commented
Hopefully Preternis and IPCs can coexist...

2020-12-31 02:25 UTC, redmoogle commented
> Hopefully Preternis and IPCs can coexist...

I mean I might give preternis some more uniqueness to differentiate them

2020-12-31 02:43 UTC, ynot01 commented
yo they look ugly asf

2020-12-31 02:48 UTC, redmoogle commented
> yo they look ugly asf 

Didnt really put effort into the picture. Will get to that tommorow

2020-12-31 02:51 UTC, jcatjmeow requested changes
1) they look ugly af

2) they are horribly unbalanced. Being able to heal from death is HUGELY a big deal, especially since it makes them basically immune to CMD.

2020-12-31 03:08 UTC, AdamElTablawy commented
They're also incredibly fragile, Jcat, and dealing with them permanently is as easy as an extra hit to the chest.

If it's such an issue, just give IPCs special CMD rules.

2020-12-31 03:11 UTC, UselessTheremin commented
i mean these are cool and all, but why do we need them other than "sure why not, another cool race?" i honestly dont know what positive contributions they will really bring to this server other than another race option to choose.

2020-12-31 03:11 UTC, redmoogle commented
> i mean these are cool and all, but why do we need them other than "sure why not, another cool race?" i honestly dont know what positive contributions they will really bring to this server other than another race option to choose. 

Whats the point of any race.

2020-12-31 04:17 UTC, AdamElTablawy commented
they'll contribute more than the fucking xenomorph race and snail race that was added for no reason that's for sure

or the fact that we have both podpeople and phytosians

2020-12-31 09:53 UTC, Tipy1802 commented
> i mean these are cool and all, but why do we need them other than "sure why not, another cool race?" i honestly dont know what positive contributions they will really bring to this server other than another race option to choose.

More content, more ways to play the game, more things to do, more fun

2020-12-31 12:01 UTC, TheLinuxOS commented
I disagree with the assessment they look ugly asf, and I feel that is more of an opinion than an issue that needs to be fixed. We have xenos and moths in the game and they both look ugly as hell in MY opinion.

2020-12-31 14:47 UTC, Moggram commented
Oh yes, please do add IPC's. This way everyone will stop crying about Preternis when they find out how broken this race is.

![1360894469767](https://user-images.githubusercontent.com/63105585/103414697-fe3de900-4b4c-11eb-8e7e-d1a71609fc31.png)


@redmoogle 
> 
> I mean I might give preternis some more uniqueness to differentiate them

No need for that. We are already so different as it is.

2020-12-31 14:51 UTC, redmoogle commented
> 
> 
> Oh yes, please do add IPC's. This way everyone will stop crying about Preternis when they find out how broken this race is.
> 
> ![1360894469767](https://user-images.githubusercontent.com/63105585/103414697-fe3de900-4b4c-11eb-8e7e-d1a71609fc31.png)
> 
> @redmoogle
> 
> > I mean I might give preternis some more uniqueness to differentiate them
> 
> No need for that. We are already so different as it is.

Good thing thats been completely addressed

2020-12-31 15:04 UTC, Moggram commented
@redmoogle 

Them being broken or the dissimilarity of ICP's and Preternis?

2020-12-31 15:06 UTC, redmoogle commented
> 
> 
> @redmoogle
> 
> Them being broken or the dissimilarity of ICP's and Preternis?

Both.

They die really quickly to an emp, a heavy one dealing 75 brain damage, 15 toxin, and causing other shitty effects

They take massive burn/heat damage, so lasers fuck them over

Self Revive? You can take their brain out in less than 30 seconds with makeshift tools

As for uniqueness, Their heads are changeable, they have unique limb reskins, Their brain is in the chest and is a posibrain.

So please STFU and get out :) because you cant read

2020-12-31 16:01 UTC, Moggram commented
@redmoogle 
Oh, the EMP is that bad. If you don't want to get knockdown, just remove your ears. You can't hear any more, but EMP is not death and you can still run away or dodge.

The 2x burn is a big draw back, I do give you that one. I cry when lasguns hit me and its only 1.5x
But some what makes up for it whit a toxin mod of 0 and bunt being 1.

I do have some questions about the chems you are adding.
Will system cleaner and liquid solder work on Preternis? 
Also I see that omnizine got the SYNTHETIC flag to, so maybe it will heal them to?

2020-12-31 16:08 UTC, redmoogle commented
> 
> 
> @redmoogle
> Oh, the EMP is that bad. If you don't want to get knockdown, just remove your ears. You can't hear any more, but EMP is not death and you can still run away or dodge.
> 
> The 2x burn is a big draw back, I do give you that one. I cry when lasguns hit me and its only 1.5x
> But some what makes up for it whit a toxin mod of 0 and bunt being 1.
> 
> I do have some questions about the chems you are adding.
> Will system cleaner and liquid solder work on Preternis?
> Also I see that omnizine got the SYNTHETIC flag to, so maybe it will heal them?

Well since IPCs are well, kinda all robotic of course they wont take toxin damage. They're basically cyborgs but lacking all the utility, I will be making them take slightly more brute 1.25-1.5 for being a little out there

As for system cleaner and liquid solder. as it stands in their lore and name it make sense it would really affect preternis. Maybe make it weaker for them?
And yes ozimine heals IPCs. Although I will have to flesh out more robotic chems for preternis

~~Also sorry for going nuclear on you, you kinda made me a _little_ mad~~

2020-12-31 18:21 UTC, Moggram commented
>
>Also sorry for going nuclear on you, you kinda made me a little mad

Hey, its cool. That's just normal internet talk to me. At lest I didn't just call them ugly and call it a day. (I don't think they are by the way.)

>
>Well since IPCs are well, kinda all robotic of course they wont take toxin damage. They're basically cyborgs but lacking all the
>utility, I will be making them take slightly more brute 1.25-1.5 for being a little out there

After thinking about it, I don't think a 1.25  bunt mod is needed. lore wise, (for bee and baystation) they are made alot better then Preternis and it dose not fit them. How about they can get ion laws like the AI and need to me be fix by reboot card from R&D? Its just an ideal.

2021-01-01 17:13 UTC, jcatjmeow approved these changes
I fucking hate IPCS

2021-01-02 01:57 UTC, Singularity69 commented
I fucking hate IPCS

2021-01-02 10:13 UTC, AdamElTablawy commented
@Moggram You're a dent.

IPCs are well balanced.

They trade off their easy revivability with ridiculous drawbacks and incredible fragility. They'll get bowled over by a single laser gun.

2021-03-05 11:24 UTC, Yogbot-13 commented
#### Test Merge Deployed

##### Server Instance
main

##### Revision
Origin: ef0db3a25ba81dee1c39ea8fc8162a7a4a752ce0
Pull Request: 4cce3216e06c35a14a2ddcfafbc0f01b912b3702
Server: aaf2a4de3a62a53112d314c3f9281454f06ce656

2021-03-05 12:26 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: 61be296c7775d9ea88e9b8a729456b211e4cc029
Pull Request: 4cce3216e06c35a14a2ddcfafbc0f01b912b3702
Server: 7556b2e6eebbdd8cd977546ea7280d0bb63bd23f

2021-03-05 22:36 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: 61be296c7775d9ea88e9b8a729456b211e4cc029
Pull Request: 26479838808cc46cd1173ec300e83992c50657f8
Server: 30cee7883419fedc2b14d05329f2362084d4a522

2021-03-06 00:19 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: 846b6d0591d4fdfa09eb9564a32ffc4691283565
Pull Request: 26479838808cc46cd1173ec300e83992c50657f8
Server: a3380909465cd8b2082b69723d93038188c356e5

2021-03-06 13:11 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: 846b6d0591d4fdfa09eb9564a32ffc4691283565
Pull Request: 9f9a48c67696edc8e6384718fd82043825b96401
Server: 952eb07ef4c61276755bc1d018d27c948afb0e36

2021-03-07 00:59 UTC, Mqiib commented
I noticed you still have the old polysmorph body parts in your human_parts.dmi. Might want to get rid of those, they aren't used any more.

2021-03-07 20:31 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: 846b6d0591d4fdfa09eb9564a32ffc4691283565
Pull Request: fbc171afdc22b1ce6cdb43eb535408f613980371
Server: 9a2ec9b6425c6d90690405f9c3b94f4666402c94

2021-03-08 00:25 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: dd1d7fc33764ab1f7a35cf63a176bb8ea99c5bb7
Pull Request: fbc171afdc22b1ce6cdb43eb535408f613980371
Server: 14cdaf78532bb345dde5558d0304548c1bc44f79

2021-03-08 01:30 UTC, Mqiib commented
*dab

2021-03-08 08:05 UTC, Cartlord commented
Yo, noticed one feature missing - Bee's IPCs can recharge from cyborg stations (such as the ones in Robotics, or the one in Restrooms) as well as APCs , while these can only use APCs.

2021-03-08 11:25 UTC, redmoogle commented
> Yo, noticed one feature missing - Bee's IPCs can recharge from cyborg stations (such as the ones in Robotics, or the one in Restrooms) as well as APCs , while these can only use APCs.

Probably missed it in one of 20 prs i ported

2021-03-08 12:17 UTC, Cartlord commented
> 
> 
> > Yo, noticed one feature missing - Bee's IPCs can recharge from cyborg stations (such as the ones in Robotics, or the one in Restrooms) as well as APCs , while these can only use APCs.
> 
> Probably missed it in one of 20 prs i ported

understandable have a nice day
TBH it might be better that that isn't here, because on Bee it's able to sometimes make an IPC fat, and honestly playing a fat IPC is awful.

2021-03-08 14:16 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: dd1d7fc33764ab1f7a35cf63a176bb8ea99c5bb7
Pull Request: 03c6e9d4369aee490fef2e3d675f5d4ed3a38e2a
Server: 38094ac42f2645436ff266e4acf28dbe0a1101bc

2021-03-08 18:21 UTC, Reed0506 commented
if you add a slight movespeed penalty like phytosian has, people will have even less to complain about in terms of balance, though thats probably not needed.

2021-03-09 00:24 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: a6e2415c469ba1af6e29b54aa239ed65b8c36ee7
Pull Request: 03c6e9d4369aee490fef2e3d675f5d4ed3a38e2a
Server: d24b215e0e8c6c5423888ae49e4f29a9cf171b3c

2021-03-09 02:06 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: 66b7150aeab900c3f31c14b1bd1e42b0bf923c18
Pull Request: 03c6e9d4369aee490fef2e3d675f5d4ed3a38e2a
Server: ef2e93fba57b1a0477b759c6d1a9a04f2aa0c565

2021-03-09 04:29 UTC, Cartlord commented
Unsure if this is a glitch or a feature, but I got ear damage (I think from an EMP), and even after a roboticist gave me a new pair of Auditory Sensors, the damage persisted.

2021-03-09 12:25 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: 158c00ddf79f3de3a5da5964b55ac17a89978863
Pull Request: 03c6e9d4369aee490fef2e3d675f5d4ed3a38e2a
Server: b8c32c664435221e3bc7144827e3654e90e4e6dc

2021-03-09 16:49 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: ca59602e0478d0927aad7a9b1fd4711bde1f9c82
Pull Request: 03c6e9d4369aee490fef2e3d675f5d4ed3a38e2a
Server: c2377bfb63991a30acd46b8f81123ed6b04133b5

2021-03-10 00:26 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: 39c610f599c05ab55c9551c8328eb9cd5b838117
Pull Request: 03c6e9d4369aee490fef2e3d675f5d4ed3a38e2a
Server: 576b980d7860d3a2d8af75956984af14a64580ef

2021-03-10 02:18 UTC, Yogbot-13 commented
#### Test Merge Updated

##### Server Instance
main

##### Revision
Origin: 39c610f599c05ab55c9551c8328eb9cd5b838117
Pull Request: 03c6e9d4369aee490fef2e3d675f5d4ed3a38e2a
Server: ce13dee3d6e20b89dc7daedfb859ee58550b7dcf

2021-03-18 02:32 UTC, SomeguyManperson commented on code/modules/mob/living/taste.dm
> +		if((text_output != last_taste_text || last_taste_time + 100 < world.time) && !NO_TASTE_SENSITIVITY)
this seems to stop anything from tasting stuff

2021-03-18 02:32 UTC, SomeguyManperson commented
also saw an IPC changeling and I'm pretty sure IPCs being selected as changeling objectives

2021-03-21 11:59 UTC, closed without merging

2021-03-21 15:15 UTC, swissloaf commented
Why!!!!!!!!

2021-03-22 01:21 UTC, LazennG commented
WHY NO MORE TVHEAD

2021-03-22 14:42 UTC, ChesterTheCheesy commented
brrrrrr