TEMPORARILY removes the stock exchange machines from cargo
yogstation13/Yogstation pull request #10785
Opened 2021-01-02 14:38 UTC by PrinceKirze

steals cargos money; makes them broke

### Intent of your Pull Request

Removing the stock exchange machines from the maps that they are on because the current stock system is shit and makes balancing cargo a pain in the rear. Gamer is gonna rework it and re-add it in, I promise. 

### Why is this change good for the game?

Cargo having some money is good. Cargo having three hundred thousand credits and buying a shuttle's worth of riot shotguns is not. 

# Wiki Documentation

Could alter/remove mentions of the stock machine but it's going to get re-added so probably just a note that says it's currently removed so we don't get 50 mhelps about where the stock machine went

### Briefly describe your PR and the impacts of it, in layman's terms. 
stock machine go sleepy time for a second

### What should players be aware of when it comes to the changes your PR is implementing?
no stocks

### What general grouping does this PR fall under? 
Cargo balancing

### Are there any aspects of the PR that you would like us not to mention on the Wiki?
no

### If there are any numerical values involved in your PR that will be relevant to a player, please note them here. 
no

# Changelog

:cl:  
rscdel: Temporarily removing stock machines from maps that have them
/:cl:

2021-01-02 14:39 UTC, PrinceKirze commented
sloppy pr cuz i forgot how to do this but it looks fiine

2021-01-02 14:52 UTC, Tipy1802 commented
Just how budget cards were temporaly removed :^)

2021-01-02 16:57 UTC, PrinceKirze commented
> Just how budget cards were temporaly removed :^)

And then the necessary one re-added

2021-01-02 18:16 UTC, wejengin2 requested changes
Pretty sure there are two of these in box cargo, also dont forget meta, delta, and omega.
This is a balance thing so I'll leave it up to HC after you do it properly

2021-01-02 18:24 UTC, PrinceKirze commented
> Pretty sure there are two of these in box cargo, also dont forget meta, delta, and omega.
> This is a balance thing so I'll leave it up to HC after you do it properly

couldn't find any on those three maps, but i think i did miss the second one in box.

2021-01-02 18:54 UTC, alexkar598 reviewed
You realize they are craftable?

2021-01-02 19:12 UTC, Hopekz commented
There is no reason to remove them round start now vs when a rework happens.
PR's based on someone else's future promise are lame

2021-01-02 23:25 UTC, PrinceKirze commented
I'll fix all the shit tomorrow. Forgot they were craftable and shit came up today. 

> There is no reason to remove them round start now vs when a rework happens.
> PR's based on someone else's future promises are lame

There's as much a reason to remove it as there is to remove anything else that is fucked beyond belief. The promise for a Gamer rework is more a reassurance that people who like the idea of stocks will get something else in a bit, but Gamer likes to try and meme this shit into bounties so I don't doubt this will take a little while; hence, the removal for now.

2021-01-02 23:58 UTC, AdamElTablawy commented
@Tipy1802 Good thing budget cards are being permanently removed

2021-01-03 07:39 UTC, maxion12345 commented
gamer is reworking stocks?

but...can we fix zombies first tho

2021-01-04 05:28 UTC, SomeguyManperson commented
this isn't based on future changes stocks are busted and either need to be reworked or removed
the only time stocks are actually useful due to the way their code functions is when they break entirely and skyrocket to the maximum price

2021-01-05 12:17 UTC, wejengin2 requested changes
Apparently these exist just on box and eclipse, so just remove the other one from box and this will be good from a map side of things

2021-01-07 14:11 UTC, wejengin2 approved these changes
Now it's fine mapwise

2021-01-07 18:24 UTC, JamieD1 commented
Now the design is gone too, it actually does something.

2021-01-07 18:25 UTC, JamieD1 commented
If something is not in place within a month this is being reverted.

07/02/2020

2021-01-07 18:26 UTC, merged

2021-01-08 03:08 UTC, PrinceKirze commented
> If something is not in place within a month this is being reverted.
> 
> 07/02/2020

imagine using this date format 0_o