Fixes deleted books actual not being 'deleted'
yogstation13/Yogstation pull request #10853
Opened 2021-01-10 18:28 UTC by redmoogle

#### Read our contributing.md if you haven't already: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# General Documentation

### Intent of your Pull Request

Explain what the purpose of your PR is. Mention if you tested your changes. If you changed a map, make sure you used the mapmerge tool. Mention if your PR is related to an issue.
You can type "Fixes issue #6" and issue 6 will be automatically closed when your pull request is merged.

### Why is this change good for the game?

# Wiki Documentation

### Briefly describe your PR and the impacts of it, in layman's terms. 
This will be the basis of the Wiki entry for your PR, and more information / detail is better for Wiki editors to integrate.

### What should players be aware of when it comes to the changes your PR is implementing?

### What general grouping does this PR fall under? 
For example, Engineering changes, Medical rebalancing, TEG tweaks, etc.?

### Are there any aspects of the PR that you would like us not to mention on the Wiki?

### If there are any numerical values involved in your PR that will be relevant to a player, please note them here. 
For example, "This new chem will heal X brute damage". 

# Changelog

Edit this changelog for changes that are noticeable by the players. Remove it if this isn't the case. If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name. Prefix the PR title with [admin] if it's something admin related. Prefix the PR title with [s] if you are fixing an exploit so it is not announced on discord and the server.

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images  
spellcheck: fixed a few typos  
experimental: This is experimental  
/:cl:

2021-01-10 21:33 UTC, TheGamerdk requested changes
NULL isn't actually a value in SQL, so you can't compare to it. Fun fact, NULL = NULL is FALSE in SQL.

2021-01-10 21:33 UTC, TheGamerdk commented on code/modules/library/lib_machines.dm
> +					WHERE deleted = NULL
```suggestion
					WHERE deleted IS NULL
```

2021-01-10 21:33 UTC, TheGamerdk commented on code/modules/library/lib_machines.dm
> +		SQLquery = "SELECT author, title, category, id FROM [format_table_name("library")] WHERE deleted = NULL AND "
```suggestion
		SQLquery = "SELECT author, title, category, id FROM [format_table_name("library")] WHERE deleted IS NULL AND "
```

2021-01-10 21:33 UTC, TheGamerdk commented on code/modules/library/lib_machines.dm
> +	var/datum/DBQuery/query_library_cache = SSdbcore.NewQuery("SELECT id, author, title, category FROM [format_table_name("library")] WHERE deleted = NULL")
```suggestion
	var/datum/DBQuery/query_library_cache = SSdbcore.NewQuery("SELECT id, author, title, category FROM [format_table_name("library")] WHERE deleted IS NULL")
```

2021-01-10 21:33 UTC, TheGamerdk commented on code/modules/library/lib_machines.dm
> +				"SELECT * FROM [format_table_name("library")] WHERE id=:id AND deleted = NULL",
```suggestion
				"SELECT * FROM [format_table_name("library")] WHERE id=:id AND deleted IS NULL",
```

2021-01-10 21:33 UTC, TheGamerdk commented on code/modules/library/random_books.dm
> +	"SELECT * FROM [format_table_name("library")] WHERE deleted = NULL AND :category IS NULL OR category = :category ORDER BY rand() LIMIT :limit",
```suggestion
	"SELECT * FROM [format_table_name("library")] WHERE deleted IS NULL AND :category IS NULL OR category = :category ORDER BY rand() LIMIT :limit",
```

2021-01-11 01:32 UTC, jcatjmeow approved these changes

2021-01-11 01:32 UTC, merged