Ubercharge
yogstation13/Yogstation pull request #10875
Opened 2021-01-14 04:26 UTC by ynot01

# General Documentation

### Intent of your Pull Request

Introduce a new type of medigun

- [x] Make ubermedigun
- [x] Make it ubercharge
- [ ] Make it twohanded so the medic can't scum it
- [ ] Test and make sure everything works
- [ ] Put it in nuke ops with a reasonable price and balanced numbers

### Why is this change good for the game?

# Wiki Documentation

### If there are any numerical values involved in your PR that will be relevant to a player, please note them here. 

Starts at 0% charge
When healing someone at full hp charges 1% per tick
When healing someone hurt charges 2% per tick

# Changelog

:cl:  
rscadd: Adds the ubercharged medigun
/:cl:

2021-01-14 12:17 UTC, TheGamerdk requested changes
Typecast target to a medbeam gun in Trigger()

Autodoc

2021-01-14 12:17 UTC, TheGamerdk commented on code/modules/projectiles/guns/misc/medbeam.dm
> +/obj/item/gun/medbeam/uber/proc/LoseTarget()
```suggestion
/obj/item/gun/medbeam/uber/LoseTarget()
```

2021-01-14 14:02 UTC, UselessTheremin commented
once this gets merged im making a tf2 medic syndi-kit and you cant stop me 🤩

2021-01-31 23:32 UTC, jcatjmeow commented
Very funny meme image but you have not actually justified how this is fun, balanced, or worth the space in the code it occupies

2021-01-31 23:35 UTC, jcatjmeow requested changes
See above comment; additionally, this does not convey to someone who has never seen this before what the fuck is going on. Why can't I shoot the glowy man??????? You should add some sort of message for when you hit or shoot the guy that the projectile/weapon does no damage, to make it clear.

2021-02-01 04:34 UTC, ynot01 commented
>  You should add some sort of message for when you hit or shoot the guy that the projectile/weapon does no damage

i disagree, tf2 has done fine without any such indication, you live and you learn, the weird glowy man should be great enough indication that at least something is off

> Very funny meme image but you have not actually justified how this is fun, balanced, or worth the space in the code it occupies

fun heal gun that is balanced rationally by numbers and reasonable contingent mechanics, as you can see by reactions many people agree, if you disagree you could be constructive and suggest better numbers

2021-02-02 03:25 UTC, jcatjmeow commented
> > You should add some sort of message for when you hit or shoot the guy that the projectile/weapon does no damage
> 
> i disagree, tf2 has done fine without any such indication, you live and you learn, the weird glowy man should be great enough indication that at least something is off

In tf2 the glowy man is a core feature of one of the 9 classes in the game. You'll see it once per side every round, plus there are a ton of voice lines and such related to it. 

Ss13 is not tf2. This is a niche item that does not see a lot of use right now and even then it's uncommon. You can't really apply tf2 logic to an entirely different game?? You honestly can't expect someone who sees this for the first or second time to understand what's going on, and given that it could be literal weeks before someone sees this item more than once, it's important to make it as unambiguous as possible.
> 
> > Very funny meme image but you have not actually justified how this is fun, balanced, or worth the space in the code it occupies
> 
> fun heal gun that is balanced rationally by numbers and reasonable contingent mechanics, as you can see by reactions many people agree, if you disagree you could be constructive and suggest better numbers

You have not actually justified how this is fun, balanced, or worth the space in the code it occupies. And no, saying that it's a "fun heal gun that is balanced" is not a justification. I'm not trying to be mean here, but you aren't selling me on this feature. This just looks like a reference for reference's sake with the balance being an afterthought. Why is this good for the game? Fill out the section properly, thank you.

2021-02-05 18:15 UTC, maxion12345 commented
jcat has never played tf2, prob sweaty overwatch main


Anyways, this is a fun twist on the usual "click teammate and wait" type of gameplay. It'll also enable nukies to push rapidly into chokepoints that would otherwise be near death due to shotguns or whatnot. War only would be a good restriction, and I am curious about holoparasite interaction. Does it also Uber the holo. Etc etc.

tl;dr it's gonna be fun and seems to be a great change

2021-02-06 07:10 UTC, ynot01 commented
> War only would be a good restriction

maybe, its hefty price takes up 25 of the 35TC you get from non war though and your teammates wont be able to capitalize as easy without a lot of TC/ammo (apart from the obvious minigun + ubermedic combo), so i think its at a good spot

> Does it also Uber the holo. Etc etc.

only ubers the mob you are aiming at, holo interaction would probably be crossing into OP bc there's an invincibility holo

2021-02-06 11:14 UTC, ynot01 commented
> See above comment; additionally, this does not convey to someone who has never seen this before what the fuck is going on. Why can't I shoot the glowy man??????? You should add some sort of message for when you hit or shoot the guy that the projectile/weapon does no damage, to make it clear.

addressed
![](https://i.imgur.com/i4srDXt.png)

2021-02-07 20:02 UTC, jcatjmeow approved these changes

2021-02-07 20:03 UTC, jcatjmeow commented
> jcat has never played tf2, prob sweaty overwatch main

I have around 500 hours in it, that wasn't the point. You cannot expect everyone to have played tf2, it's not reasonable to require that sort of knowledge in a completely unrelated game.

2021-02-08 14:39 UTC, Takahiru commented
> > jcat has never played tf2, prob sweaty overwatch main
> 
> I have around 500 hours in it, that wasn't the point. You cannot expect everyone to have played tf2, it's not reasonable to require that sort of knowledge in a completely unrelated game.

To be honest, I don't think a new player will understand many of the items currently present in the game just by looking at them with face value. It will only take them one round which is after seeing this to learn what it is. We also have many items that are present in other games with similar mechanics.

2021-02-13 16:18 UTC, merged