Removes Oak's Birthday from files.
yogstation13/Yogstation pull request #10905
Opened 2021-01-18 23:32 UTC by alao3alao3

#### Read our contributing.md if you haven't already: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# Intent of your Pull Request

Removes the most explicit reference to Oak, Oak's birthday, from game files.
Why did Altoids make Oak a holiday? See #6264 for the PR itself.

# Why is this change good for the game?

Oak is gone, and our files should reflect that. Altoids must've been invited to some sick tea parties with Oak in order to give him his own finnish holiday. 

# Wiki Documentation

https://wiki.yogstation.net/wiki/Holiday_events#Oak.27s_Birthday
Is to be deleted upon PR's merging.

### If there are any numerical values involved in your PR that will be relevant to a player, please note them here. 
For example, "This new chem will heal X brute damage". 

###################### Changelog

:cl:  
rscdel: Removes Oakday, and references to it in carp_migration  
/:cl:

i get theres a feature freeze just merge it after the feature freeze damnit

2021-01-18 23:34 UTC, swissloaf commented
Who cares mane its fine

2021-01-18 23:34 UTC, ynot01 commented
feature freeze bonk

2021-01-18 23:49 UTC, swissloaf requested changes

2021-01-18 23:49 UTC, swissloaf commented on yogstation/code/modules/holidays/holidays.dm
> -/datum/holiday/oakday
Just undelete it and rename it to Gondola day

2021-01-19 00:43 UTC, swissloaf requested changes
Keep the station names too

2021-01-19 00:43 UTC, swissloaf commented on yogstation/code/modules/holidays/holidays.dm
> -/datum/holiday/oakday/getStationPrefix()
/datum/holiday/gondoladay/getStationPrefix()
	return pick("Gondola","Finnish","Finland","Karelia","Perkele")
	
/datum/holiday/gondoladay/greet()
	return "Happy Gondola day!"

2021-01-19 00:44 UTC, swissloaf commented on yogstation/code/modules/holidays/holidays.dm
> -/datum/holiday/oakday/getStationPrefix()
I don't know how to make it suggest code changes but ye

2021-01-19 00:52 UTC, Moja10 commented
I agree with keeping the holiday, a gondola day would be very nice.

2021-01-23 11:42 UTC, JamieD1 approved these changes

2021-01-23 11:43 UTC, JamieD1 commented
Feature freeze grumble grumble

2021-01-23 11:43 UTC, merged