Adds headpats
yogstation13/Yogstation pull request #10934
Opened 2021-01-28 07:04 UTC by monster860

headpats are the lifeblood of ss13.

:cl: monster860
add: Adds headpats
/:cl:

2021-01-28 07:10 UTC, Hopekz commented on code/modules/mob/living/carbon/carbon_defense.dm
> +			emote("wag")
Epic

2021-01-28 07:29 UTC, ynot01 commented
does not compile

2021-01-28 08:12 UTC, maxion12345 commented
if this gets merged I'm making a PR to bring dabbing and tposing back.

2021-01-28 08:13 UTC, Mqiib commented
Please no

2021-01-28 08:34 UTC, ChesterTheCheesy commented
>forces target into wagging it's tail
bruh that's literally ERP

2021-01-28 08:34 UTC, Szyszkrzyneczka commented
Burn the heretic, Kill the mutant, Purge the unclean,

the fact that it has a (wag) action makes me vomit, just add pinball monster

2021-01-28 09:07 UTC, Hopekz commented
> if this gets merged I'm making a PR to bring dabbing and tposing back.

Tposing is lame dab good

2021-01-28 09:34 UTC, TheGamerdk requested changes
looks good just a few tiny changes

2021-01-28 09:34 UTC, TheGamerdk commented on code/modules/mob/living/carbon/carbon_defense.dm
> +	else if(check_zone(M.zone_selected) == BODY_ZONE_HEAD)
```suggestion
	
```

2021-01-28 09:34 UTC, TheGamerdk commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		var/datum/species/S
```suggestion
		
```

2021-01-28 09:34 UTC, TheGamerdk commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		if(ishuman(src))
```suggestion
		
```

2021-01-28 09:34 UTC, TheGamerdk commented on code/modules/mob/living/carbon/carbon_defense.dm
> +			S = dna.species
```suggestion
			
```

2021-01-28 09:34 UTC, TheGamerdk commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		M.visible_message("<span class='notice'>[M] gives [src] a pat on the head to make [p_them()] feel better!</span>", \
```suggestion
		
```

2021-01-28 09:34 UTC, TheGamerdk commented on code/modules/mob/living/carbon/carbon_defense.dm
> +					"<span class='notice'>You give [src] a pat on the head to make [p_them()] feel better!</span>", target = src,
```suggestion
					
```

2021-01-28 09:34 UTC, TheGamerdk commented on code/modules/mob/living/carbon/carbon_defense.dm
> +					target_message = "<span class='notice'>[M] gives you a pat on the head to make you feel better!</span>")
```suggestion
					
```

2021-01-28 09:34 UTC, TheGamerdk commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		if(S?.can_wag_tail(src) && !dna.species.is_wagging_tail())
```suggestion
		
```

2021-01-28 09:34 UTC, TheGamerdk commented on code/modules/mob/living/carbon/carbon_defense.dm
> +			emote("wag")
```suggestion
			
```

2021-01-28 12:30 UTC, ChesterTheCheesy commented
You can headpat a headless person, immersion destroyed.

2021-01-28 12:31 UTC, N3D6 commented
yeah no can we please not

2021-01-28 12:56 UTC, alexkar598 commented
I want this so I can be condescending in game, heading patting people.


There there, I fixed you up, dont get hurt again, it's bad for you, ok? *pats head*

2021-01-28 13:48 UTC, jcatjmeow commented
Doesn't pass linter.
We are under a feature freeze.
Bad changelog.
Missing rationale.
Did not fill out the pr template.
Abusing maint powers to add the bug label and remove feature label.

2021-01-28 19:44 UTC, monster860 commented
I have fixed the changelog and made it follow the PR template and hopefully it should compile, although I did have to remove the targeted message, something I could re-add if theres enough demand

2021-01-28 20:33 UTC, Mqiib commented
If this somehow gets merged I'm making a pr to remove the tail wag

2021-01-28 21:50 UTC, N3D6 commented
i'd dislike this pr a lot less if it didn't make you tailwag but this just seems like a shitpost if i'm being honest

2021-01-29 01:02 UTC, SomeguyManperson commented
https://user-images.githubusercontent.com/24857008/106217650-b047ef80-61a3-11eb-953a-8aa84c69a11e.mp4

2021-01-29 01:11 UTC, Jarod1200 commented
TheOS has once again saved yogstation from imminent destruction

2021-01-29 01:49 UTC, monster860 commented
![image](https://user-images.githubusercontent.com/3681297/106220787-4121c980-61aa-11eb-98af-5a830f5f3688.png)

2021-01-29 01:59 UTC, SomeguyManperson commented
the "damn good reason" is this is a meme pr stop trying to stir shit

2021-01-29 02:24 UTC, swissloaf commented
No

2021-01-29 02:29 UTC, jcatjmeow requested changes
Tested it personally. Works. This will be merged over my dead body (also feature freeze) but it's fine as a feature sooooooooooo yeah

Request re-review after the feature freeze or somethin idk

2021-01-29 15:21 UTC, JamieD1 commented
Line ------

Dont cross it. @yogstation13/maintainers

2021-01-29 15:21 UTC, closed without merging