Removes Adrenaline and changes Nervous cost to 20 volume per second.
yogstation13/Yogstation pull request #10944
Opened 2021-01-30 03:10 UTC by alao3alao3

# General Documentation

## Intent of your Pull Request

Remove adrenaline and changes the cost of the nervous nanite (passive stun resistance) to 20 per second.

## Why is this change good for the game?

The "Mbrain" reasoned that nanites were broken, most notably adrenaline and nervous given how strong the stun resistance is and how negligible it is (Equivalent of getting free meth upon saying QQ according to the discord).

I'm currently working off of this person's vision and they can defend the pr in front of the HCs, along with anyone else who wanted to try to change nanites.
![cpng](https://user-images.githubusercontent.com/62276730/106344393-b3141480-6277-11eb-91da-dabac129a0b9.png)

Adrenaline is apparently flat out broken giving standard crewman traitor/ling abilities and can only be resolved with it's full removal or the change of it's cost to 250 per second among other options. 

Raising nervous cost to 20 per second apparently seeks to have players be more careful with their stun resistance while also allowing for more unique player interactions (i.e baiting the nanite user into wasting his stun resistance). This change is taxing on nanites to reflect how it costs the most out of any nanite program.

Contact @Mqiib for further reasoning and defense, along with anyone else he should choose to mention.. Don't shoot the messenger.

# Wiki Documentation

Guide to Nanites is to be updated with the removal of Adrenaline and the VPS of the nervous nanites to be changed to 20 per second.

### Changelog

:cl:  
rscdel: Removed old things  
tweak: changed nervous nanites vps from 1.5 to 20.  
/:cl:

2021-01-30 03:17 UTC, AutisticFroggy commented
This is good and anyone who says otherwise is wrong
![image](https://user-images.githubusercontent.com/52133791/106345649-b2699580-62ec-11eb-80f7-20177e7511f1.png)

2021-01-30 10:25 UTC, ChesterTheCheesy commented
This would be fine if the delayed triggers would actually work xd

2021-01-30 11:08 UTC, JamieD1 commented
@SomeguyManperson

2021-02-10 09:36 UTC, SomeguyManperson requested changes
remove don't comment out

2021-02-11 18:40 UTC, alao3alao3 commented
should be good

2021-02-13 16:18 UTC, merged