removes the tinfoil hat because it's useless and bugged
yogstation13/Yogstation pull request #10941
Opened 2021-01-29 23:08 UTC by speenor

i mean, who wants to use the misc tab on an autolathe when it's hacked, right? the entire tab goes fucked over when you hack it and everything is replaced with tinfoil hats. it keeps growing in the list of hats and if you change tabs it crashes the autolathe and you have to reopen the autolathe menu.

:cl:  
rscdel: removes tinfoil hat from autolathe, fixing a bug
/:cl:

2021-01-29 23:11 UTC, redmoogle commented
did you test this, because there's a fairly high chance it's not the problem

2021-01-30 00:25 UTC, maxion12345 commented
>be tinfoil hat
>literally not changed for a very long time
>autolathe UI updates and shit come
>autolathe broken
>get removed because it's obviously the tinfoil hat

2021-01-30 11:06 UTC, JamieD1 requested changes
Not the source of the bug, will need to be looked into further.

2021-01-30 18:37 UTC, ChesterTheCheesy commented
https://github.com/yogstation13/Yogstation/pull/10945
you can close this PR

2021-01-31 23:37 UTC, jcatjmeow commented
> #10945
> you can close this PR

ok

2021-01-31 23:37 UTC, closed without merging