more department goals: medical edition
yogstation13/Yogstation pull request #11045
Opened 2021-02-23 00:18 UTC by ynot01

# General Documentation

### Intent of your Pull Request

adds 2 goals
60% surv rate
80% surv rate
if they cant get the 80% they can at least feel proud for the 60%

### Why is this change good for the game?

more goals more shit to do more motives for medical to do their job

# Changelog

:cl:  
rscadd: Added 2 medical department goals
/:cl:

2021-03-12 20:50 UTC, redmoogle requested changes
Heres some improvements

2021-03-12 20:50 UTC, redmoogle commented on code/modules/goals/department_goals/medical.dm
> +		else if(M.stat == CONSCIOUS || M.stat == UNCONSCIOUS || M.stat == SOFT_CRIT)
only needs to be else since thats the only 4 types of stats afaik

2021-03-12 20:50 UTC, redmoogle commented on code/modules/goals/department_goals/medical.dm
> +			return FALSE
```suggestion
	if(ided) // avoiding divide by zero
		if(survivors / ided >= 1.5) //for every dead person, there should be 1.5 alive people
			return TRUE
		return FALSE
	return TRUE
```

2021-03-12 20:50 UTC, redmoogle commented on code/modules/goals/department_goals/medical.dm
> +	if(ided == 0) // avoiding divide by zero
put into practice down here

2021-04-10 11:10 UTC, JamieD1 commented
@ynot01 Fix

2021-04-11 16:59 UTC, ynot01 commented
@JamieD1 done

2021-04-11 18:40 UTC, MegaEmpirical commented
Does cyroing count against this?

2021-04-11 19:21 UTC, ynot01 commented
> Does cyroing count against this?

depends if they're still in player list if they count at all, but it wont count against it since deleted mobs dont have a stat to check if theyre dead

2021-04-25 10:11 UTC, JamieD1 approved these changes

2021-04-25 10:11 UTC, merged