Simplifies the wiki portion of the PR template
yogstation13/Yogstation pull request #11120
Opened 2021-03-11 18:46 UTC by redmoogle

#### Read our contributing.md if you haven't already: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# General Documentation

### Intent of your Pull Request

Explain what the purpose of your PR is. Mention if you tested your changes. If you changed a map, make sure you used the mapmerge tool. Mention if your PR is related to an issue.
You can type "Fixes: #6" and issue 6 will be automatically closed when your pull request is merged.

### Why is this change good for the game?

# Wiki Documentation

Explain any impacts in here. Mention if you would wish for something to not be mentioned on the wiki, and please provide any numerical values for the wiki-men to intergrate.

# Changelog

Edit this changelog for changes that are noticeable by the players. Remove it if this isn't the case. If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name. Prefix the PR title with [admin] if it's something admin related. Prefix the PR title with [s] if you are fixing an exploit so it is not announced on discord and the server.

`Omitted changelog for sanity reasons`

2021-03-11 19:10 UTC, FLME commented
You can also just do:

Wiki Documentation
N/A

for stuff like fixes

2021-03-11 19:18 UTC, redmoogle commented
> 
> 
> You can also just do:
> 
> Wiki Documentation
> N/A
> 
> for stuff like fixes

wiki probably doesnt read it for one and this stops prs from being a mile long

2021-03-11 21:47 UTC, SomeguyManperson approved these changes
not like anyone reads the wiki portion anyways :^^^^^^^

2021-03-12 09:42 UTC, JamieD1 commented
You will need to get Anvils approval.

2021-03-12 09:42 UTC, JamieD1 requested changes
Anvil will need to approve as we took a while to come to this format.

2021-03-12 22:45 UTC, swissloaf commented
The current format sucks and is heavily redundant. This PR trims it down and is good

2021-03-25 12:01 UTC, closed without merging