Bring Drones Back Plz
yogstation13/Yogstation pull request #1114
Opened 2018-06-01 23:30 UTC by rhoemer22

### Intent of your Pull Request
Im trying to bring drones back.

Explain what the purpose of your PR is.
Dont know if i did this right, but my copy+paste skillz are unmatched!

Mention if your PR is related to an issue.
ThatLing is a douche

2018-06-02 00:09 UTC, ShadowDeath6 commented on code/modules/cargo/packs.dm
> +crate_name = "drone shell crate"
not lined up right

2018-06-02 00:57 UTC, rhoemer22 commented on code/modules/cargo/packs.dm
> +crate_name = "drone shell crate"
done

2018-06-02 07:21 UTC, ThatLing requested changes
![not modular](https://github.com/yogstation13/Yogstation-TG/blob/master/yogstation/README.md)

2018-06-02 18:35 UTC, rhoemer22 commented
I dont understand why i should modulize it. It appears that the first pull request to remove them, wasnt modulized neither.
Please elaborate

2018-06-02 19:36 UTC, ThatLing commented
That's because the removal PR came from /tg/

2018-06-15 11:52 UTC, ThatLing commented
It's been 14 days since the last update so I'm closing this. Feel free to reopen/make a new PR when you update this.

2018-06-15 11:52 UTC, closed without merging