(PORT) Tribal Claw a new lizard exclusive martial art
yogstation13/Yogstation pull request #11186
Opened 2021-03-22 01:29 UTC by boodaliboo

Original pr https://github.com/BeeStation/BeeStation-Hornet/pull/3011
race exclusive content good
"This PR adds a new race restricted martial art for lizards named "Tribal Claw".
It currently has 4 combos
Tail Sweep - Disarm Disarm Grab Harm - Similar to how a space dragon's tail sweep ability works but only has a range of 3x3 tiles.
Face Scratch - Harm Disarm - Blurs your vision, confuses you for a short time and deals 10 brute to the target's head.
Jugular Cut - Harm Harm Grab - Deals 15 brute to the target's head, causes them to rapidly lose blood, only works if target is in a tier 3 grab, in crit, or uncounscious.
Tail Grab - Disarm Harm Grab Grab - Instantly grabs your target by their neck (Tier 3 Grab) and makes them unable to talk for a short time."
:cl:  
rscadd: Adds a new race exclusive martial art for 14 tc 
/:cl:

2021-03-22 01:46 UTC, ynot01 commented
dont let big lizard fool you

2021-03-22 02:30 UTC, Mqiib commented
Lowercase "clamp" not CLAMP, and change the A.setGrabState to just A.grab_state =

2021-03-22 03:25 UTC, Marmio64 commented
why do those primitive beings need race exclusive content

2021-03-22 04:35 UTC, Mqiib commented
Test it to make sure the combos work properly, pretty please

2021-03-25 23:32 UTC, SomeguyManperson requested changes
the entire martial art file is tabbed with spaces instead of normal tabs

2021-04-03 17:54 UTC, closed without merging