Lets abductors buy more batons and pistols
yogstation13/Yogstation pull request #11241
Opened 2021-03-28 01:34 UTC by Marmio64

They can buy pretty much everything else they start with, so why not their baton and pistol? Allows abductors to continue to use only alien gear, and not have to make a stun prod if someone pushes them.

### Why is this change good for the game?
Lets abductors rebound from mistakes if they get enough patients.

### What should players be aware of when it comes to the changes your PR is implementing?
you can buy more batons and guns as abductor

### What general grouping does this PR fall under? 
For example, Engineering changes, Medical rebalancing, TEG tweaks, etc.?
antag changes

### Are there any aspects of the PR that you would like us not to mention on the Wiki?
no?

:cl:  
rscadd: Adds abductor batons and guns to their purchase menu
/:cl:

2021-03-28 03:53 UTC, Sniblet commented
Me: *buys a second pistol*
Also me: My name is not important. What matters is what I'm going to do.
xDDDD

2021-03-28 19:14 UTC, alexkar598 commented
Dual weilding the gun is concerning

2021-03-28 19:26 UTC, SomeguyManperson commented
would suggest not allowing them to buy more guns since they inherently don't tend to actually need the first one

2021-03-28 20:37 UTC, Marmio64 commented
you don't tend to need the first gun but if you lose it, you've lost your only means of defense against a hulk if you encounter one and you cant get out. I could double the price or something maybe, or perhaps they wouldn't be rechargeable, so you'd want to be conservative with their use even more. Otherwise I suppose it could stay out of the purchase menu since they don't see much use anyhow.

2021-03-29 00:52 UTC, alexkar598 commented
Also not 100% on board with the idea of the intentionally vulnerable scientist being given a stun baton

2021-03-29 01:27 UTC, Marmio64 commented
> Also not 100% on board with the idea of the intentionally vulnerable scientist being given a stun baton

they can already buy a full set of agent armor for themself and link it up to the console and enable combat mode, and getting a stunprod is easy enough, the abductor baton just makes everything easier

2021-03-30 11:44 UTC, Ratvar commented
If scientist and guard both teleport bot to alien stunprod everyone, they will not be able to teleport guard back in case of messing up. 
This also helps scientist keep abducting people if guard dies or is afk, being useless is boring

2021-04-03 18:05 UTC, JamieD1 commented
Theos and Myself do not think they should be able to get guns.

2021-04-03 18:05 UTC, SomeguyManperson requested changes
remove the gun and make the baton worth 2 points

2021-04-06 03:53 UTC, Marmio64 commented
> remove the gun and make the baton worth 2 points

done

2021-04-10 11:22 UTC, merged