Revert "makes science's greytide gun unobtainable" and makes it not pass tables or windows
yogstation13/Yogstation pull request #11260
Opened 2021-03-31 15:13 UTC by alexkar598

*sigh*

Why is the first reaction to everything to just remove it? It still has potential for neat stuff and greytiding is one component of it which can easily be severely nerfed without impacting the ability to do neat stuff too much

Haven't seen many complaints about the portal gun except for the greytiding part

Now for the questions:
### but why not table, i get that this pr is supposed to stop people breaking into like kitchen with portal gun but this is unrealistic!!!!
You are talking about a handheld device that can warp time and space and yet doesnt need a power source, realism has been thrown out the window a long time ago

### Now this is useless, i cant find any use for this
its not because your mind is restricted to greytiding with shit that noone else can make neat stuff with it, just dont print it if you cant find any use for it

### bruh
bruh

:cl:
rscadd: portal gun is back
tweak: portal gun can no longer fire through windows or tables
/:cl:

2021-03-31 15:20 UTC, ToasterBiome commented
how about a check that will instantly kill you if you attempt to print it while wearing a gray jumpsuit or mime/clown outfit

2021-03-31 15:26 UTC, UselessTheremin commented
also a problem is the instantaneous spacing while wearing a boh, if its not gonna be useful anymore that just turns it into a murder tool

2021-03-31 15:37 UTC, ChesterTheCheesy commented
Alexkar keep in mind this nerf also affects the portal gun gained from the "mad scientist" syndi-kit. For this reason alone i dislike this change.

2021-03-31 16:19 UTC, ynot01 commented
cool antag item but i dont want to spend tc on it

2021-03-31 17:21 UTC, UselessTheremin commented
> cool antag item but i dont want to spend tc on it or get valided for having it

its also able to be found in hilberts hotel ruin and i may add it to some other things sooooooooo

2021-03-31 17:22 UTC, UselessTheremin commented
the main problem is them being mass produced or whatever, i could get behind tjem being experimentor

2021-03-31 18:17 UTC, ChesterTheCheesy commented
> 
> 
> cool antag item but i dont want to spend tc on it or get valided for having it

The mad scientist kit is built around it. Making the portal gun shit will also make the whole kit even more shit than it is.
Want graytiders printing a portal gun? Make a new gun while leaving old one intact.

2021-04-01 01:10 UTC, burn1cycle commented
I love the portal gun I was very disappointed it was removed but we had good reasons to remove it. This fixes the issues with it. 

Only thing I might suggest is that it's emag-able and once done it would have it's old functionality restored?

2021-04-01 06:12 UTC, Cartlord commented
> 
> 
> I love the portal gun(probably in my top 5 items I enjoy in game) I was very disappointed it was removed but we had good reasons to remove it. This fixes the issues with it.
> 
> Only thing I might suggest is that it's emag-able and once done it would have it's old functionality restored?

This, I like this very much.

2021-04-01 17:54 UTC, ChesterTheCheesy commented
dude stop putting everything behind emag, not like it's bought by 70% traitors already

2021-04-03 18:14 UTC, SomeguyManperson requested changes
make sure the mad scientist kit's gun doesn't get nerfed by this and it's good

2021-04-10 11:26 UTC, SomeguyManperson approved these changes

2021-04-10 11:26 UTC, merged