(attempts to) Ports sec hailer dispatch system from NSV13
yogstation13/Yogstation pull request #11287
Opened 2021-04-06 04:29 UTC by maxion12345

# General Documentation

### Intent of your Pull Request

This adds a neat "dispatch" button to security hailers used on security masks / swat masks / cyborg hailers. This lets you quickly report crimes and a location with the click of a button to rapidly get backup. Mainly for immersion, it's just pretty neat. Currently only has four common crimes to report, and it /should/ put the location in there aswell. 

Currently a draft due to the area function being non-functional. If anyone wants to try to help, the error we keep getting is "undefined proc" on get_area(user.loc). It's been commented out for initial testing so you know what we're trying to get working.
### Why is this change good for the game?

Muh immersion. Also, sechailers aren't used much outside of "wirecut the restrictor, spam it to annoy people" so this will give another nice feature to em :)
# Wiki Documentation

### Briefly describe your PR and the impacts of it, in layman's terms. 
dont think we even have a wiki page for sechailers

### What should players be aware of when it comes to the changes your PR is implementing?
Sec hailers can now report location and crimes to other officers. 
### What general grouping does this PR fall under? 
Security tweak

### Are there any aspects of the PR that you would like us not to mention on the Wiki?

### If there are any numerical values involved in your PR that will be relevant to a player, please note them here. 

# Changelog

:cl:  
rscadd: Added sechailer dispatch system
/:cl:

2021-04-06 06:53 UTC, maxion12345 commented
Wait it compiled? What the hell I tried that earlier

I'll futz with it later, thanks for the help

2021-04-06 15:45 UTC, FLME requested changes
inconsistent space law crime codes

2021-04-06 15:45 UTC, FLME commented on yogstation/code/modules/clothing/masks/hailer.dm
> +	for(var/option in list("401 (murder)", "101 (resisting arrest)", "210 (breaking and entering)", "206 (riot)", "302 (assault on an officer)")) //Just hardcoded for now!
In our Space law it is:
601 (murder)
101 (res. arrest)
310 OR 410 (B&E or B&E Restricted)
306 (Rioting) OR 406 (Inc. Riot)
401 (Assault, Officer)

2021-04-06 16:02 UTC, maxion12345 commented
alright it complies in the checks, im guessing whatever the error is on my side, im pulling a cyberpunk and releasing this pr anyways

2021-04-07 18:58 UTC, grimm-hollowknight approved these changes

2021-04-10 11:38 UTC, merged

2021-04-10 13:12 UTC, 00aquir commented
can you make the HUD icon just one image? it's kinda disctracting.