Completely Revamps plasmaman outfit code
yogstation13/Yogstation pull request #11378
Opened 2021-04-16 15:27 UTC by Takahiru

### Intent of your Pull Request

Before this PR, there were different outfits for every plasmaman job. Problem is, the only differences between these outfits and the regular ones are the uniform and head. Someone didn't bother to make new boxes for the plasmamen either. 

This PR makes it so that the plasmaman outfit, head, and box are simply variables in datum/outfit/job which are equipped if the is a plasmaman.

### Why is this change good for the game?

It also fixes #11315 
Makes it so that changes to outfits also apply to plasmamen, with the exception of the helmet and uniform.

# Changelog
:cl:  
bugfix: Plasmamen now get their respective boxes for their jobs 
tweak: Changes up plasmamen outfit code
/:cl:

2021-05-17 14:54 UTC, alexkar598 requested changes

2021-05-17 14:54 UTC, alexkar598 commented on code/game/objects/items/storage/boxes.dm
> +/obj/item/storage/box/survival_mining/plasmaman/PopulateContents()
For the survival boxes, why not just call parent, delete all internal tanks in PopulateContents() and add the plasmaman one?

2021-05-17 14:54 UTC, alexkar598 commented on code/modules/jobs/job_types/_job.dm
> +		r_hand = /obj/item/tank/internals/plasmaman
They are meant to receive a `/obj/item/tank/internals/plasmaman/belt/full`

2021-05-17 14:54 UTC, alexkar598 commented on code/game/objects/items/storage/boxes.dm
> +	new /obj/item/tank/internals/plasmaman(src)
Meant to receive a `obj/item/tank/internals/plasmaman/belt/full`

2021-05-17 14:54 UTC, alexkar598 commented on code/game/objects/items/storage/boxes.dm
> +	new /obj/item/tank/internals/plasmaman(src)
Meant to receive a `obj/item/tank/internals/plasmaman/belt/full`

2021-05-17 14:54 UTC, alexkar598 commented on code/game/objects/items/storage/boxes.dm
> +	new /obj/item/tank/internals/plasmaman(src)
Meant to receive a `obj/item/tank/internals/plasmaman/belt/full`

2021-05-17 14:54 UTC, alexkar598 commented on code/modules/jobs/job_types/botanist.dm
>  	gloves  =/obj/item/clothing/gloves/botanic_leather
```suggestion
	gloves = /obj/item/clothing/gloves/botanic_leather
```

2021-05-17 14:54 UTC, alexkar598 commented on code/modules/jobs/job_types/warden.dm
> +	plasmaman_uniform = /obj/item/clothing/under/plasmaman/security
They are meant to receive a `/obj/item/clothing/under/plasmaman/security/warden`

2021-05-17 14:54 UTC, alexkar598 commented on code/modules/jobs/job_types/medical_doctor.dm
> +
They are meant to also receive a `/obj/item/clothing/head/helmet/space/plasmaman/blue`

2021-05-20 01:24 UTC, Takahiru commented on code/game/objects/items/storage/boxes.dm
> +/obj/item/storage/box/survival_mining/plasmaman/PopulateContents()
thanks for looking it over, i believe i made it how you recommend.

2021-05-24 12:21 UTC, adamsong commented
The assistant code has not been updated to give plasmaman outfits to assistants, so they now spawn with the regular outfits, and die

2021-05-26 19:37 UTC, RaiIsNotYourGuy commented
lawyer plasmaman do not spawn with envirosuit on. Happened to me on Round 35501.

2021-07-05 05:12 UTC, adamsong commented
This currently has merge conflicts and won't build. Please fix these issues, this PR is stale

2021-07-20 22:13 UTC, closed without merging