adds a cosmetic vampire coat to clowns vending machine
yogstation13/Yogstation pull request #11374
Opened 2021-04-16 04:59 UTC by boodaliboo

allows for clown to do more gimicks like pretend to be dracula and stuff 
:cl:  
rscadd: Added a cosmetic vampire coat to clowns vending machine
/:cl:

2021-04-16 05:00 UTC, FLME commented
also is secretly an attempt to give the vampire coat a sort of metashield by the fake one existing

use the template fuckface

2021-04-16 05:09 UTC, FLME requested changes

2021-04-16 05:09 UTC, FLME commented on code/modules/vending/autodrobe.dm
> +					/obj/item/clothing/suit/cosmeticvampirecoat,
make it have only one like all of the other autodrobe items

2021-04-16 05:09 UTC, FLME commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A Coat designed to mimic the coats of the vampires from translyvania"
this description isnt very good and it doesnt have proper grammar

2021-04-16 07:20 UTC, Tipy1802 commented
This can result in two situations:
a) whoever wears the cosmetic cloak gets killed by sec and sec gets banned
b) vampires are allowed to wear their cloak that gives them near infinite blood (its not infinite but blood regen is really good and just a few seconds will earn you enough to jaunt), a cloak that is also supposed to be their way of going loud

None of those are attractive situations, people getting killed and banned is not fun and vampires don't need to be made even more OP than they currently are

2021-04-16 07:52 UTC, boodaliboo commented
> This can result in two situations:
> a) whoever wears the cosmetic cloak gets killed by sec and sec gets banned
> b) vampires are allowed to wear their cloak that gives them near infinite blood (its not infinite but blood regen is really good and just a few seconds will earn you enough to jaunt), a cloak that is also supposed to be their way of going loud
> 
> None of those are attractive situations, people getting killed and banned is not fun and vampires don't need to be made even more OP than they currently are

that is a rules issue  sec doesnt just go kill clowns wearing wizard robes that is a frankly ridiculous criticism,
your second criticism makes no sense this doesnt give them blood regen

2021-04-16 08:08 UTC, ToasterBiome commented
Maybe change the name so it's obviously a fake so Tipy would be at least slightly happier with it?

2021-04-16 20:40 UTC, Marmio64 commented
buff the vampire coat instead so that its more worth going loud?  Also all fake antag clothing items have discernable differences from the real ones. Look at a fake wizard robe and real one, you can easily tell which is which, same for clockwork armor except even more so.

2021-04-17 13:44 UTC, Tipy1802 commented
> that is a rules issue sec doesnt just go kill clowns wearing wizard robes that is a frankly ridiculous criticism,

Except sec can easily tell when someone is wearing fake wizard clothing with a glance

>your second criticism makes no sense this doesnt give them blood regen

I am not saying that the fake one gives blood regen, I am saying that having a fake but identical looking cloak would mean that sec won't go after vampires using the actual cloak out of fear of killing an ''innocent'' by getting fooled. And yes the real vampire cloak is supposed to be an obvious tell that you are a vampire.

2021-04-29 18:56 UTC, Hopekz commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A Coat designed to mimic the coats of the vampires from Translyvania."
```suggestion
	desc = "A Coat designed to mimic the coats of the vampires from Transylvania."
```

2021-05-17 14:41 UTC, alexkar598 requested changes
dracula coat is already a thing

2021-06-01 16:42 UTC, closed without merging