you can no longer cryopod others
yogstation13/Yogstation pull request #11375
Opened 2021-04-16 05:40 UTC by ynot01

# General Documentation

### Intent of your Pull Request

cryoing other players is now impossible
admin-cryo will still work because it doesn't use the mousedrop-t proc

### Why is this change good for the game?

prevents players from griefing each other

# Wiki Documentation

### Briefly describe your PR and the impacts of it, in layman's terms. 
cryoing other players is now impossible

# Changelog

:cl:  
tweak: You can no longer put other players into cryopods
/:cl:

2021-04-16 07:51 UTC, boodaliboo commented
not against this but was this a issue

2021-04-16 10:29 UTC, ChesterTheCheesy commented
tfw can't cryo my ssd blood bro with no admin online anymore

2021-04-17 02:21 UTC, MegaEmpirical commented
> not against this but was this a issue

I've been cryoed when dealing with tickets and I've ahelped. This is supposedly fixed though, independent of this.

I also had a ticket a week or two ago where someone had to restart their internet and they came back to a different player being in their body because someone shoved them in.

Also, currently catatonic clone copies can be put in and get ghost.

So it has happened and can happened, the matter of which is the important one. We also get tickets about people saying they need to do x for 30 minutes and will be back, we as admins are aware  of this and can handle it correctly, players have no idea why someone is brain dread and don't have that context.

2021-04-19 20:44 UTC, Sniblet commented
Wait you mean I wasn't supposed to do that

2021-04-22 05:51 UTC, Cartlord commented
Fixes https://github.com/yogstation13/Yogstation/issues/10993 , no?

2021-04-25 01:34 UTC, burn1cycle commented
Against. 
I'm for tweaking it so people who get put into cryostorage get a 10 minute grace period to come back and AGhosts(admin ghosts) get a special "Do not store" status(this was always how it had been intended to function, I'm not sure what happened.), but(except for AGhosts) if they are going to be absent from the round for more than 10 minutes then it's problematic for every other player who is actively participating in the round.

-  Inactivity has a strong effect on our game.
-  Inactive players are taking up a role slot in some cases, 
- They get looted and since the player never returns to the game an admin is never asked to investigate and it's rare that I've seen an admin proactively open up a ticket on their own unless it was large scale grief. 
- Various antags can gain benefits from SSD persons(again going unreported)
- SSD persons don't stop being a target until cryo'd and lacking an active person to antag ruins an antag's round.
- Inactive players give an incorrect impression of what the crew can deal with
- Inactive players catch diseases that often go uncured.
 
  Basically, when you click "join" and enter the game we should expect you to commit to that role for the shift or else leave in an appropriate way, failing that we should be able to put you in cryo.

 Unfortunately **I lack faith in a coder decision effecting administrative policy**. I doubt we will have strict and uniform enforcement of what admins will do with SSD people or if some admins will even care at all and that's only if they are online at the time.

2021-05-17 14:39 UTC, alexkar598 reviewed
Verify that target is equal to user and remove references to user. Also clear out checks for clientless in close_machine() as the user will always have a client

2021-05-17 14:39 UTC, alexkar598 commented on code/game/machinery/cryopod.dm
> +		to_chat(user, "<span class='danger'>You are unable to cryo others.</span>")
Cryo is not a verb

2021-05-17 14:39 UTC, alexkar598 commented on code/game/machinery/cryopod.dm
>  	if(target == user)
Check will always return true

2021-05-17 14:39 UTC, alexkar598 requested changes
meant to be request changes

2021-05-18 12:53 UTC, burn1cycle commented
Even more against after some experience trying to tell admins players are SSD and need to be taken care of. Got the response "Dude? What's going on? Is this an admin issue?". Fix the admins first then fix cryopods.

2021-05-18 16:18 UTC, MegaEmpirical commented
> Even more against after some experience trying to tell admins players are SSD and need to be taken care of. Got the response "Dude? What's going on? Is this an admin issue?". Fix the admins first then fix cryopods.

The issue is the admin there. Who was it?

2021-05-22 16:34 UTC, burn1cycle commented
> > Even more against after some experience trying to tell admins players are SSD and need to be taken care of. Got the response "Dude? What's going on? Is this an admin issue?". Fix the admins first then fix cryopods.
> 
> The issue is the admin there. Who was it?

I can't remember and it doesn't matter. The only time you're caring to enforce it is when a PR is at stake. I'm not going to eat up my round time and tick off admins in forum complaints who will inevitably drop the excuse:

> limits to complexity that we can be effective on at once. The chaos is worse behind the scenes, and sometimes they cards land where they fall. Some things, simply, cannot be sorted in the exact moment they're happening. If you'd like to try yourself, staff applications are open.

and not be held responsible for anything they failed to do.

2021-07-05 05:09 UTC, adamsong commented
There are requested changes that have not been address in a while, and a pull request been merged since that attempts to address this issue in a different way. Some people still want this merged, so I won't close it now, but it is stale.

2021-07-09 13:48 UTC, Moja10 commented
All cryo needs is a long period of time where they can personally sit in the cryo pod, and if they don't come back in an alloted time then they are removed from the round. If you don't come back in 30 minutes you are out of the round, and if you need more time lock yourself in dorms. Solutions like this PR aren't the answer.

2021-07-09 14:28 UTC, MegaEmpirical commented
30 minutes would be way too high. 15 should be okay.

2021-07-13 18:23 UTC, alexkar598 commented
https://github.com/yogstation13/Yogstation/blob/master/code/game/machinery/cryopod.dm#L173-L174

2021-07-13 18:24 UTC, alexkar598 commented
That sounds like a great idea! Which is why its already been implemented.

2021-07-13 18:24 UTC, alexkar598 commented
Stale

2021-07-13 18:24 UTC, closed without merging