Revert TGUI Vore Panel
yogstation13/Yogstation pull request #11437
Opened 2021-04-30 12:54 UTC by UselessTheremin

### Intent of your Pull Request

fucking bibby broke map votes, i enjoy that we've been playing non-box maps fore a change but it's a bug. and i guess i should fix those or something. well, the easiest fix is to remove it since bibby obviously isnt gonna fix it. if someone steps up to fix the vote panel, i'll close this pr, but until then it's a pretty urgent issue.

Reverts #11170
Closes #11436

### Why is this change good for the game?

it's not, lesser of two evils

:cl:    
rscdel: removed tgui vote panel
/:cl:

2021-04-30 13:01 UTC, TheGamerdk commented
Improve don't remove

2021-04-30 13:02 UTC, TheGamerdk commented
Also don't re-line the wasp file and don't re-add the distributable js chunks

2021-04-30 13:12 UTC, UselessTheremin commented
> Also don't re-line the wasp file and don't re-add the distributable js chunks

i just reverted the commit i have no fucken clue how to do tgui code but its broken, can you at least fix it mate

2021-04-30 13:12 UTC, UselessTheremin commented
or at least revert it yourself

2021-05-01 06:36 UTC, monster860 commented
never trust code from a coder that isn't a femboy

2021-05-01 17:37 UTC, TheGamerdk commented
> never trust code from a coder that isn't a femboy

Is this why monstermos doesn’t work?

2021-05-01 19:07 UTC, MegaEmpirical commented
"Improve don't remove" only works if someone actually does so.

2021-05-02 16:46 UTC, TheGamerdk commented
> "Improve don't remove" only works if someone actually does so.

No, if you're capable of removing it you're capable of improving it

2021-05-02 19:44 UTC, UselessTheremin commented
> > "Improve don't remove" only works if someone actually does so.
> 
> No, if you're capable of removing it you're capable of improving it

i literally dont know how to code with tgui, do you want me to just learn an entire other type of code because what, the pr you made doesnt fucken work? fix you own pr for the love of god, if you do im closing this

2021-05-03 12:54 UTC, JamieD1 approved these changes

2021-05-04 12:48 UTC, TheGamerdk requested changes
no touchy jamie

2021-05-04 12:48 UTC, TheGamerdk commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/wasp.dm
> -/mob/living/simple_animal/hostile/asteroid/wasp
no touchy this file

2021-05-04 12:48 UTC, TheGamerdk commented on tgui/public/tgui-common.chunk.js
> +(window.webpackJsonp=window.webpackJsonp||[]).push([[0],[function(e,t,n){"use strict";t.__esModule=!0;var r=n(451);Object.keys(r).forEach((function(e){"default"!==e&&"__esModule"!==e&&(e in t&&t[e]==
no touchy

2021-05-04 12:48 UTC, TheGamerdk commented on tgui/public/tgui-panel.bundle.css
> +body,html{box-sizing:border-box;height:100%;margin:0;font-size:12px}html{overflow:hidden;cursor:default}body{overflow:auto;font-family:Verdana,Geneva,sans-serif}*,:after,:before{box-sizing:inherit}h1
no touchy

2021-05-04 12:48 UTC, TheGamerdk commented on tgui/public/tgui-panel.bundle.js
> +!function(e){function t(t){for(var o,i,c=t[0],s=t[1],d=t[2],u=0,g=[];u<c.length;u++)i=c[u],Object.prototype.hasOwnProperty.call(r,i)&&r[i]&&g.push(r[i][0]),r[i]=0;for(o in s)Object.prototype.hasOwnPr
no touchy

2021-05-04 12:48 UTC, TheGamerdk commented on tgui/public/tgui.bundle.css
> +body,html{box-sizing:border-box;height:100%;margin:0;font-size:12px}html{overflow:hidden;cursor:default}body{overflow:auto;font-family:Verdana,Geneva,sans-serif}*,:after,:before{box-sizing:inherit}h1
no touchy

2021-05-04 12:48 UTC, TheGamerdk commented on tgui/public/tgui.bundle.js
> +!function(e){function t(t){for(var o,c,i=t[0],l=t[1],d=t[2],s=0,m=[];s<i.length;s++)c=i[s],Object.prototype.hasOwnProperty.call(r,c)&&r[c]&&m.push(r[c][0]),r[c]=0;for(o in l)Object.prototype.hasOwnPr
no touchy

2021-05-09 17:35 UTC, UselessTheremin commented
whatever this pr is being fixed by theos who is more competent than i am, i'll save my spaghetti for the mothers day dinner

2021-05-09 17:35 UTC, closed without merging