this is why we can't have nice things
yogstation13/Yogstation pull request #11466
Opened 2021-05-13 03:42 UTC by SomeguyManperson

:cl:  
bugfix: you can no longer stack borg expander modules. You know what you did.
/:cl:

2021-05-13 03:43 UTC, ZombieNub commented
I know what I did but in my defense the borg wanted it and how was I gonna say no?

2021-05-13 03:51 UTC, ToasterBiome commented
delete this

2021-05-13 03:52 UTC, N3D6 commented
theos once again saves yog from fun

2021-05-13 04:28 UTC, ZombieNub commented
In my opinion expansion stacking should remain. It's funny and I'll let others have fun with it if they so please.

2021-05-13 04:44 UTC, SomeguyManperson commented
maybe stacking up to a limit but you can get so big right now you can obscure like the whole screen

2021-05-13 04:50 UTC, ToasterBiome commented
> maybe stacking up to a limit but you can get so big right now you can obscure like the whole screen

I would say like 2-3 would be good for "meme" but also not game breakingly annoying

2021-05-13 13:39 UTC, TheLinuxOS commented
I love how you say “theos saves yogs from fun” when people were literally exploiting it to be as big as the escape shuttle

2021-05-13 14:06 UTC, alexkar598 requested changes
1) Changelog is incorrect, its twice not once
2) Changelog is incorrect, it would be a tweak not a bugfix at this point since the intended behaviour is once not twice
3) `hasExpanded` needs to be changed from being a boolean to being a number at the following lines:
    - https://github.com/yogstation13/Yogstation/blob/master/code/game/objects/items/robot/robot_upgrades.dm#L708 (R.hasExpanded--)
    - https://github.com/yogstation13/Yogstation/blob/master/code/modules/mob/living/silicon/robot/robot.dm#L87 (`var/hasExpanded = 0`)
    - https://github.com/yogstation13/Yogstation/blob/master/code/modules/mob/living/silicon/robot/robot.dm#L1027 (`hasExpanded--`)
4) Ideally, `hasExpanded` should be renamed to something else so that its less confusing since its no longer a boolean. Perhaps `expansions`?

2021-05-17 14:20 UTC, alexkar598 commented on code/game/objects/items/robot/robot_upgrades.dm
>  			R.update_transform()
I'm not 100% a fan of using a while loop here as its technically not needed but I suppose it prevents bugs from turning borgs invisible by rounding their size down to 0

2021-05-17 14:20 UTC, alexkar598 approved these changes

2021-05-17 14:20 UTC, merged