Fix die of fate color
yogstation13/Yogstation pull request #11576
Opened 2021-06-11 03:46 UTC by Readystorm546

Die of fate color fix
:cl:  
bugfix: Fixed color for stealth die of fate 
/:cl:

2021-06-11 04:12 UTC, Hopekz commented
Is this a meme PR?

2021-06-11 05:32 UTC, ToasterBiome requested changes
wow im gonna feel like a fool if this is a meme pr

2021-06-11 05:32 UTC, ToasterBiome commented on code/modules/awaymissions/mission_code/Academy.dm
> +	color = NULL
if this isnt a meme pr then null should be lowercase iirc

2021-06-11 05:32 UTC, ToasterBiome commented on code/modules/awaymissions/mission_code/Academy.dm
> +	color = NULL
same here

2021-06-12 00:33 UTC, Readystorm546 commented
not a meme im just bad at code

2021-06-12 08:55 UTC, wejengin2 commented
what

2021-06-13 10:46 UTC, JamieD1 commented
Why?

2021-06-19 16:13 UTC, merged