Succumb Changes
yogstation13/Yogstation pull request #11590
Opened 2021-06-13 19:14 UTC by JamieD1

Succumb is now on a 180 second delay.

Argue with Lyis, not me.

Im just a code monkey.

2021-06-13 23:24 UTC, MegaEmpirical commented
The way this should work is: Initiating the command will start a timer, that can only be started while in crit. This will bring a confirmation prompt and after the timer has elapsed they will then die if they're in crit still. If they're healed but then drop back into crit before the timer has elapsed and then it elapses while they're in crit, they die. 

Using the verb will also alert those around them that they're giving up on life .

2021-06-14 16:12 UTC, Moggram commented
Seem like you would die most times long before 90 sec. Why not have it do more OxyLoss?

2021-06-14 16:16 UTC, MegaEmpirical commented
1) It can take a lot longer to die in soft crit
2) Time it takes takes for you to die isn't a factor for this change beyond it possibly taking a long time.

This change is to reduce abuse of the succumb mechanic and to provide an out for anyone stuck dying slowly in crit.

2021-06-14 16:22 UTC, Moggram commented
> 
> 
>     1. It can take a lot longer to die in soft crit
> 
>     2. Time it takes takes for you to die isn't a factor for this change beyond it possibly taking a long time.
> 
> 
> This change is to reduce abuse of the succumb mechanic and to provide an out for anyone stuck dying slowly in crit.

Ooohh ok then.

2021-06-21 04:36 UTC, alexkar598 commented
God no, I don't want to sit at a screen for 1.5 minutes, if this goes though, il just ghost instead

2021-06-22 18:34 UTC, Hopekz commented
> God no, I don't want to sit at a screen for 1.5 minutes, if this goes though, il just ghost instead

This ^

If someone succumbs it is because they don't want to control their character anymore otherwise they would just do nothing and wait

2021-06-27 08:57 UTC, Cartlord commented
I succumb solely because either A) I don't want to wait when death is inevitable or B) I _do not want_ whatever's about to happen to my character. If I Succumb while a cultie's dragging me to a rune, it's because I DO NOT WANT TO BE CONVERTED. This is exceedingly lame, and really seems to defeat the purpose of Succumbing.

2021-06-27 14:20 UTC, MegaEmpirical commented
> I succumb solely because either A) I don't want to wait when death is inevitable or B) I _do not want_ whatever's about to happen to my character. If I Succumb while a cultie's dragging me to a rune, it's because I DO NOT WANT TO BE CONVERTED. This is exceedingly lame, and really seems to defeat the purpose of Succumbing.

This is why we're making this change.

2021-06-27 19:12 UTC, Cartlord commented
To make Succumb useless?

2021-06-27 19:30 UTC, Hopekz commented
> To make Succumb useless?

 probably. 

The PR also seems to delay the whisper of the succomb so now you can't even really time your whisper so someone hears you. That and who knows if the information if even valid 90 seconds after you meant to say it.

If this gets implemented I'd rather see succomb removed tbh instead of being in this state

2021-06-27 20:01 UTC, Cartlord commented
I'm honestly with Alexkar, if this gets merged I'll probably just Ghost instead of dealing with this nonsense.

2021-06-30 20:39 UTC, boodaliboo commented
what is succomb i have ghosted every time

2021-06-30 21:10 UTC, MegaEmpirical commented
> what is succomb i have ghosted every time

It's a command that is similar to suicide. It would let you die instantly if you were in soft or hard crit but not prevent you being revived. Useful if you were dying slowly. This was being abused by people about to be converted.

2021-07-02 15:44 UTC, Marmio64 commented
this should be 30 seconds at the most, you're going to be killed/converted before you even hit the 15 second mark for most cases

2021-07-03 11:55 UTC, adamsong requested changes

2021-07-03 11:55 UTC, adamsong commented on code/modules/mob/living/living.dm
> +	var/list/bad_antags = list(
Forgot thralls

2021-07-06 17:51 UTC, Mqiib commented
> this should be 30 seconds at the most, you're going to be killed/converted before you even hit the 15 second mark for most cases

30 seconds is much more reasonable.

2021-07-07 11:16 UTC, JamieD1 commented on code/modules/mob/living/living.dm
> +	)
```suggestion
		/datum/antagonist/shadowling,
		/datum/antagonist/veil,
		/datum/antagonist/thrall
	)
```

2021-07-07 23:50 UTC, num1bamf commented
This is an amazing change. Let’s try it. Council bamf approved.

2021-07-07 23:52 UTC, adamsong approved these changes
Code looks functional, even if the change is bad

2021-07-08 00:14 UTC, MegaEmpirical commented
> Code looks functional, even if the change is bad

How so?

2021-07-08 00:32 UTC, adamsong commented
90 seconds is way to long, significantly longer than most conversions, the only outlier being thralling a mind-shielded person, and that still takes only 65 seconds. This should either be reduced to 30 seconds, or the better solution would be to restrict succumbing to hard crit. This would allow for crit to still be used as a mean of subduing your opponent, but means that someone doing so must be careful to keep the victim out of hard crit.

2021-07-08 00:38 UTC, MegaEmpirical commented
> 90 seconds is way to long, significantly longer than most conversions, the only outlier being thralling a mind-shielded person, and that still takes only 65 seconds. This should either be reduced to 30 seconds, or the better solution would be to restrict succumbing to hard crit. This would allow for crit to still be used as a mean of subduing your opponent, but means that someone doing so must be careful to keep the victim out of hard crit.

Length of conversion is not a factor here, it's the time leading up to it and the fact that succumb is currently instant.

90 seconds is Jamie's suggestion not mine. I suggested about a minute but I am willing to try 90 and adjust going forward. 

Dying in hard crit is significantly faster than soft crit, and can be accelerated by talking. 

Succumb is for when you're taking too long to die, and soft crit can be extremely slow.  I have crawled from the engine to medical in soft crit more than once.

I think 60 would be fine but I won't know until we've tested it. If your issue is the 90, that was Jamie's call.

I want sufficient time for the person handling the victim to be able to respond and do what is needed. 30 seconds would be plenty in ideal conditions, we're not always working in ideal conditions so I want some wiggle room.

2021-07-08 01:41 UTC, adamsong commented
Its called 'critical' for a reason, its not a state you should intend to keep someone in, because someone in that state is on the verge of dying. I still think no more than 30s, and restricting to hard critical is a better course of action

2021-07-08 02:32 UTC, MegaEmpirical commented
> Its called 'critical' for a reason, its not a state you should intend to keep someone in, because someone in that state is on the verge of dying. I still think no more than 30s, and restricting to hard critical is a better course of action

Doing this would remove the useful part of succumbing, not dying slowly in soft crit. That's where succumb actually matters.

2021-07-09 13:52 UTC, Moja10 commented
bitch PR

2021-07-10 21:30 UTC, N3D6 commented
this is godawful

2021-07-11 08:02 UTC, Cartlord commented
always remember that 'mins pushing bad changes brought down /tg/ and it _will_ bring down yog if/when it happens

2021-07-11 09:15 UTC, num1bamf commented
Y’all are very dramatic

2021-07-11 14:25 UTC, N3D6 commented
> Y’all are very dramatic

imo i think its just a bad change, just don't like the idea of this. when i succumb, i want to die, not wait a minute and a half for my slow death.

2021-07-11 17:41 UTC, Junkyshell commented
why is this testmerged this shit has 3 people in favor of it and 14 opposed. let's be honest this is just another example of the ebil and vile lyis trolling the community.

2021-07-11 18:20 UTC, num1bamf commented
I can ask for succumbing to be removed entirely if that’ll be better for you

2021-07-11 20:07 UTC, MegaEmpirical commented
https://user-images.githubusercontent.com/36208065/125208698-1c09aa80-e262-11eb-85e2-ea9f4704a6d2.mp4

2021-07-11 20:20 UTC, Hopekz commented
> I can ask for succumbing to be removed entirely if that’ll be better for you

Not sure if this is meant to be a joke or not but I'd personally be in favor of a full removal vs changing it to this if those are the only two options that exist

2021-07-11 20:37 UTC, Cartlord commented
IMO
Sometimes I wanna play Bloodcult, and sometimes I just don't
Sometimes I go into a round wanting to do really specific shit, and being converted can keep me from doing that
I don't want a bloodcult ban, because I do have fun with the role sometimes - like if I just arrived so they weren't interrupting much, or if I'm a Botanist who can mass-produce unholy water - and sometimes, I wanna show up and do weird Turbine shit, and being converted means I don't get to do Turbine shit and instead I need to do cult shit
So that's why I do succumb to avoid being converted, because sometimes I'm in the mood to do converson antag things and sometimes I am simply _not_.
Would it be better to be converted and then AHelp to be offered to Ghosts?
(Posted this in the Discord, it got buried/ignored, so posting here)

2021-07-15 01:57 UTC, maxion12345 commented
i fucking hate this change man. Getting hardcrit and having to wait 90 seconds (especially with lag) is just infuriating. Especially when you can use this to whisper numerous times in hardcrit to circumvent the "talking in hardcrit = your last words"

2021-07-16 23:22 UTC, Cartlord commented
I understand, after someone explained to me in Discord, that it's better to be converted and ask a 'min to Ghost you than it is to Succumb to dodge conversion.
That being said, people really seem to HATE this PR, and I don't think it's right to Merge it. Please don't force something that _people don't want_. As for where I'm getting my info, it's stuff I've seen in OOC chat.
I'm genuinely afraid of the path we'll be heading down, if 'mins start trying to force PRs that people don't want - that's what fucked /tg/ and it'll fuck us too.

2021-07-17 02:40 UTC, SomeguyManperson commented
just ban people for succumbing to draft dodge :^

2021-07-18 20:01 UTC, Bibby0110 commented on code/modules/mob/living/living.dm
> +		if(alert("Are you sure you want to Succumb? (This will take 90 Seconds)",, "Yes", "No") != "Yes")
```suggestion
		if(alert("Are you sure you want to succumb? (This will take 90 seconds)",, "Yes", "No") != "Yes")
```

2021-07-18 20:01 UTC, TheGamerdk commented on code/modules/mob/living/living.dm
> +		to_chat(src, "<span class='notice'>You have started to loosen the grip on this world you will die in about 90 seconds.</span>")
```suggestion
		to_chat(src, "<span class='notice'>You have started to loosen the grip on this world and you will die in about 90 seconds.</span>")
```

2021-07-18 20:01 UTC, TheGamerdk commented on code/modules/mob/living/living.dm
> +		return FALSE
Untab once

2021-07-26 13:26 UTC, SomeguyManperson commented
suggest one of two alternatives (or both i guess)
A: make certain antag stuns prevent succumbing for a decent timeframe, stuff like shadowling glare or bloodcult stun or whatever, like if you get hit by one you are prevented from succumbing for a few minutes outright otherwise succumbing works normally
B: ban people for succumbing to dodge conversion

2021-08-14 14:00 UTC, JamieD1 commented
Yeah.

2021-08-14 14:00 UTC, closed without merging