Removes deprecated security HUD comments
yogstation13/Yogstation pull request #11640
Opened 2021-06-27 16:25 UTC by TheGamerdk

Thanks for making me aware of this Lyis :3 

Comments aren't supported on Security consoles so these serve no real purpose.

# Changelog

:cl:  
bugfix: Removed un-used add comment and comment log from security hud glasses.
/:cl:

2021-06-27 16:26 UTC, alexkar598 requested changes
If you're removing it, remove it completly from the code

2021-06-27 16:26 UTC, TheGamerdk commented
> If you're removing it, remove it completly from the code

forget to mark it as a draft :)

2021-06-27 16:35 UTC, MegaEmpirical commented
You sick fuck, don't remove them fix your damn UI

2021-06-27 17:21 UTC, TheGamerdk commented
> You sick fuck, don't remove them, fix your damn UI or revert the UI

This is fixing the oversight

2021-06-27 17:53 UTC, maxion12345 commented
fix code plz

2021-06-27 18:00 UTC, TheGamerdk commented
> fix code plz

code is fixed?

2021-07-01 09:28 UTC, JamieD1 commented
Will add comments to the gui instead.

2021-07-06 13:10 UTC, adamsong commented
Unpopular PR, better solution in #11724

2021-07-06 13:10 UTC, closed without merging