You can now photocopy cat ass
yogstation13/Yogstation pull request #11670
Opened 2021-06-30 20:03 UTC by TheGamerdk

# General Documentation

### Intent of your Pull Request

Equality.

_Stolen from TG_

### Why is this change good for the game?

# Wiki Documentation

### Briefly describe your PR and the impacts of it, in layman's terms. 
Equality

# Changelog

:cl:  
rscadd: You may now photocopy cat ass
/:cl:

2021-06-30 20:07 UTC, TheGamerdk commented on code/modules/paperwork/photocopier.dm
>  						temp_img = icon(ass.gender == FEMALE ? 'icons/ass/assfemale.png' : 'icons/ass/assmale.png')
```suggestion
						temp_img = icon(ass.gender == FEMALE ? 'icons/ass/assfemale.png' : 'icons/ass/assmale.png')
						var/mob/living/carbon/human/H = ass
```

2021-06-30 20:07 UTC, TheGamerdk commented on code/modules/paperwork/photocopier.dm
> +						if(iscatperson(ass))
```suggestion
						if(iscatperson(H))
```

2021-06-30 20:14 UTC, alexkar598 requested changes

2021-06-30 20:14 UTC, alexkar598 commented on code/modules/paperwork/photocopier.dm
> +						var/mob/living/carbon/human/H = ass
Remove this and rebase onto master, I merged #11669

2021-06-30 20:20 UTC, Bibby0110 commented on code/modules/paperwork/photocopier.dm
> +						var/mob/living/carbon/human/H = ass
Never

2021-06-30 20:32 UTC, alexkar598 approved these changes

2021-07-01 00:24 UTC, Mqiib commented
Add the rest of the asses you coward

2021-07-01 10:31 UTC, JamieD1 commented
Sigh

2021-07-01 10:31 UTC, merged