Adds armory protolathe
yogstation13/Yogstation pull request #11696
Opened 2021-07-02 13:13 UTC by adamsong

# General Documentation

### Intent of your Pull Request
Adds an armory protolathe for printing lethal weapons and ammo, removing those items from the security protolathe.

### Why is this change good for the game?
It defeats the purpose of the warden for sec officers to just print guns, bypassing the need to have them issued by the warden.

# Wiki Documentation

### Briefly describe your PR and the impacts of it, in layman's terms. 
Lethal weapons and ammo are removed from the sec protolathe, and added to the armory protolathe, located in the back of the armory. The table of what items can be printed in which protolathe will need to be updated to reflect the addition of a new protolathe and the moving of some items to it.

### What general grouping does this PR fall under? 
Security changes

# Changelog

:cl:  
rscadd: Added armory protolathe
/:cl:

2021-07-02 13:15 UTC, TheGamerdk commented
Very good.

HoS probably needs both circuits.
Don’t forget the other maps.

2021-07-02 13:19 UTC, adamsong commented
Hos gets the armory one, the sec one is in the armory, forgot other maps again

2021-07-02 13:23 UTC, alexkar598 commented
Placement sucks ass, you can sit in space printing guns without sec being able to do anything except ruin their own printer, destroying the silo link

2021-07-02 13:31 UTC, adamsong commented
Where would you suggest it go?

2021-07-02 13:36 UTC, alexkar598 commented
By moving the implants next to the mindshield implants (where they make more sense to exist anyways), it opens up a spot next to the shotguns (which are used 80% of the time as a hyper lethal gun) where the protolathe can fit.

2021-07-02 13:36 UTC, alexkar598 commented
![https://i.imgur.com/OP2iaI1.png](https://i.imgur.com/OP2iaI1.png)

2021-07-04 20:23 UTC, wejengin2 requested changes
Omega is now lacking a regular sec lathe, does the armory one include items from it?

2021-07-04 21:53 UTC, adamsong commented
Yes, the armory lathe includes sec items, omega armory isn’t big enough to fit the lathe

2021-07-05 19:42 UTC, wejengin2 approved these changes
Alright map all good then

2021-07-07 11:05 UTC, merged