Revert "removes dab"
yogstation13/Yogstation pull request #11690
Opened 2021-07-01 22:46 UTC by maxion12345

Reverts yogstation13/Yogstation#9733

hopek showed me where this button is and told me I need to "make a good reason"

seeing as our transition to mrp has fallen flat on its face and the RP rules document is probably accessed less then the space inbetween a nun's thighs, I believe its time to bring back dabbing as a way for our players to express how fucking stupid they are. (mainly me)

2021-07-01 22:56 UTC, Cartlord commented
Is it still possible for them to *dab and get the "Voice of God" trauma? 'Cause it might be a good idea to change that!

2021-07-01 23:02 UTC, maxion12345 commented
> Is it still possible for them to *dab and get the "Voice of God" trauma? 'Cause it might be a good idea to change that!

nah they removed that

2021-07-02 01:21 UTC, Cartlord commented
based

2021-07-02 03:30 UTC, N3D6 commented
yeah

2021-07-02 04:39 UTC, maxion12345 commented
inb4 council vote to revert

2021-07-02 11:50 UTC, JamieD1 commented
As there was a council vote to remove it, there will need to be one to reinstate it.

2021-07-02 12:01 UTC, JamieD1 commented
Awaiting Vote 824.

2021-07-02 17:37 UTC, Hopekz commented
@wejengin2 where did the controversial tag come from?

There isn't a single thing posted here on why not to do it.

2021-07-02 18:44 UTC, wejengin2 commented
> There isn't a single thing posted here on why not to do it.

Yes but it has proven to be a controversial topic in the past, so much so that it needed a council vote to remove a simple feature.

2021-07-03 03:38 UTC, boba247 commented
The brain damage should be left out. If someone wants to dab fine. If someone wants to dab in hopes for a funny brain damage trauma not so fine.

2021-07-03 11:32 UTC, adamsong requested changes

2021-07-03 11:32 UTC, adamsong commented on yogstation/code/modules/mob/living/emote.dm
> +		H.adjustOrganLoss(ORGAN_SLOT_BRAIN, 5)
Remove the brain damage, we don't want people spamming for traumas

2021-07-05 02:22 UTC, adamsong approved these changes
Code looks fine, approving but don't merge pending council vote

2021-07-07 10:58 UTC, JamieD1 commented
824 Approved. 
https://forums.yogstation.net/threads/vote-824-reverts-council-vote-https-forums-yogstation-net-threads-vote-722-remove-dab-22271-with-pr-https-github-com-yogstation13-yogstat.23702/

2021-07-07 10:59 UTC, merged