Re-adds comments to the security records console, plus some other records changes
yogstation13/Yogstation pull request #11724
Opened 2021-07-06 13:08 UTC by adamsong

# General Documentation

### Intent of your Pull Request

Re-adds comments to the security records console that were not implemented with the last UI update, while also redoing the comment storage internally to work better.
Combined major and minor crime categories due to the lack of need for the distinction, and the need for UI space for the comments. 
Fixed the security filing cabinet and pAI security records not working properly.

<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/4607006/124605152-9fc63000-de39-11eb-8b8c-cd356fecda28.png)

</details>

### Why is this change good for the game?
A lot of people like comments, and wanted them added back, this does that.

# Changelog

Fixes #11723 
Fixes #11316 
Adds feature https://forums.yogstation.net/threads/if-security-records-do-not-get-comments-back-then-please-revert-the-ui-change.23664/

:cl:  
rscadd: Added security comments to security records console
bugfix: fixed security filing cabinet
bugfix: fixed pAI security records
tweak: tweaked how security comments are stored 
tweak: removed the distinction between major and minor crimes in the sec records
/:cl:

2021-07-06 14:04 UTC, TheGamerdk requested changes
Might want to look at reworking medical comments now that you've refactored the datacore to handle them properly.

2021-07-06 14:04 UTC, Bibby0110 commented on code/game/machinery/computer/security.dm
> +						var/t1 = stripped_multiline_input("Add Comment:", "Secure. records", null, null)
give this a proper and descriptive name?
Remove the two null statements at the end unless it's on purpose that you're removing the max message length (1024)
Add usr for consistency or just wipe it from the rest of the file. (It's mixed if consoles use the usr, but everything else does for some reason)
```suggestion
						var/t1 = stripped_multiline_input(usr, "Add Comment:", "Security Records")
```

2021-07-06 14:04 UTC, Bibby0110 commented on code/modules/mob/living/carbon/human/human.dm
> +										var/t1 = stripped_input("Please input crime names:", "Security HUD", "", null)
variable names, t1 and t2 are just plain confusing

2021-07-06 14:04 UTC, Bibby0110 commented on code/modules/mob/living/carbon/human/human.dm
> +										var/t1 = stripped_input("Please input crime names:", "Security HUD", "", null)
Remove trailing null if you want to enforce the max message length of 1024 characters

2021-07-06 14:04 UTC, Bibby0110 commented on code/modules/mob/living/carbon/human/human.dm
> +										var/t2 = stripped_multiline_input("Please input crime details:", "Security HUD", "", null)
see above about trailing null parameter

2021-07-06 14:04 UTC, Bibby0110 commented on code/datums/datacore.dm
> +	C.time = time != "" ? time : text("[] [], []", station_time_timestamp(), time2text(world.realtime, "MMM DD"), GLOB.year_integer+540)
```suggestion
	C.time = time ? time : text("[] [], []", station_time_timestamp(), time2text(world.realtime, "MMM DD"), GLOB.year_integer+540)
```

2021-07-06 14:04 UTC, Bibby0110 commented on code/game/machinery/computer/security.dm
> +						var/crime = GLOB.data_core.createCommentEntry(t1, logged_in)
wrong variable name

2021-07-06 14:04 UTC, Bibby0110 commented on code/modules/mob/living/carbon/human/human.dm
> +											var/comment = GLOB.data_core.createCommentEntry(t1, allowed_access)
change the t1 variable while you're at it

2021-07-06 14:04 UTC, TheGamerdk commented on code/game/machinery/computer/security.dm
> +				comment["time"] = C.time
shows full time + date unlike crimes

2021-07-07 02:43 UTC, SomeguyManperson approved these changes

2021-07-07 02:43 UTC, merged

2021-07-07 04:16 UTC, Cartlord commented
Based adam, bibby BTFO