Readds Cat emotes
yogstation13/Yogstation pull request #11739
Opened 2021-07-09 08:26 UTC by JamieD1

Fuck off alexkar, you cant just close and revert a PR within 14 minutes then use the excuse of a exploit to do it.

Made the sounds quieter and added 10 second cooldown to meow.

2021-07-09 08:37 UTC, adamsong requested changes

2021-07-09 08:37 UTC, adamsong commented on code/modules/mob/living/carbon/human/emote.dm
> +	if(!ishuman(user))
iscatperson already checks for human

2021-07-09 08:41 UTC, JamieD1 commented on code/modules/mob/living/carbon/human/emote.dm
> +		return FALSE
```suggestion
		return iscatperson(user)
```

2021-07-09 08:41 UTC, JamieD1 commented on code/modules/mob/living/carbon/human/emote.dm
> +		return iscatperson(user)
```suggestion
	return iscatperson(user)
```

2021-07-09 08:46 UTC, SomeguyManperson approved these changes
should work

2021-07-09 08:48 UTC, adamsong approved these changes
Code looks good

2021-07-09 08:50 UTC, JamieD1 commented
Waiting 24 HOURS as required by all maintainers.

2021-07-09 14:58 UTC, alexkar598 commented
"Waiting 24 hours"

immediately testmerges it

Doesnt need testmerging

Basically a speed merge in disguise. Nice one Jamie

2021-07-09 16:09 UTC, adamsong commented
This PR was open for more time before being test merged, than the other one which you full merged

2021-07-09 16:29 UTC, alexkar598 commented
![https://i.imgur.com/1wDpLxf.png](https://i.imgur.com/1wDpLxf.png)

2021-07-11 14:22 UTC, Marmio64 commented
even anime catgirls dont meow like a stray cat though

2021-07-19 17:22 UTC, Tipy1802 commented
Purrbation already makes a cat noise when triggered so cat sounds arent out of line

2021-08-07 11:38 UTC, merged