[EXPERIMENTAL] Traitors are assigned after 2 minutes
yogstation13/Yogstation pull request #11746
Opened 2021-07-10 12:24 UTC by TheGamerdk

# Github documenting your Pull Request

You're no longer safe from becoming a target if you latejoin.
Hopefully this helps increase the amount of people that ready up?

Untested and need to do other changes

- [ ] Verify how objectives are picked
- [ ] Testing everything

# Changelog

:cl:  
experimental: Traitors are only made aware of their traitor ways after approximately 2 minutes.
/:cl:

2021-07-10 12:27 UTC, adamsong commented
This would prevent people who roll jobs that can't be traitor from rolling traitor

2021-07-10 14:54 UTC, adamsong commented
Also, would this negate quiet mode?

2021-07-10 14:57 UTC, TheGamerdk commented
> This would prevent people who roll jobs that can't be traitor from rolling traitor

This works in the exact same way that we do traitors now, the timer is just 2 minutes instead of 1-10 seconds.
My code addition is to re-roll a traitor if they’ve disconnected/died before they’re told they’re a traitor

2021-07-10 18:50 UTC, Cartlord commented
But why?
If someone is latejoining so they don't roll tot, I'm pretty sure that means they _don't want to be tot_ - so why force them to be tot anyways? What's the gain?

2021-07-10 20:04 UTC, adamsong requested changes
Looks mostly good, just some small changes. Get this compiling and it can be test merged. I will definitely be interested to see how well it works.

As for the objectives, they are rolled when the datum is given, so in this case after the two minutes.

2021-07-10 20:04 UTC, adamsong commented on code/game/gamemodes/traitor/traitor.dm
>  		var/datum/antagonist/traitor/new_antag = new antag_datum()
This variable is now unused

2021-07-10 20:04 UTC, adamsong commented on code/game/gamemodes/traitor/traitor.dm
> +		if(applicant.mind.quiet_mode)
`quiet_round` is the variable you are looking for

2021-07-10 20:04 UTC, adamsong commented on code/game/gamemodes/traitor/traitor.dm
> +		if(!(role in applicant.client.prefs.be_special))
role should probably be `ROLE_TRAITOR`

2021-07-10 20:06 UTC, TheGamerdk commented on code/game/gamemodes/traitor/traitor.dm
> +		if(applicant.mind.quiet_mode)
```suggestion
		if(applicant.mind.quiet_round)
```

2021-07-10 20:06 UTC, TheGamerdk commented on code/game/gamemodes/traitor/traitor.dm
>  		var/datum/antagonist/traitor/new_antag = new antag_datum()
```suggestion
```

2021-07-10 20:06 UTC, TheGamerdk commented on code/game/gamemodes/traitor/traitor.dm
> +		if(!(role in applicant.client.prefs.be_special))
```suggestion
		if(!(antag_flag in applicant.client.prefs.be_special))
```

2021-07-10 20:18 UTC, adamsong commented
Does this apply to all traitor gamemodes, such as traitorlings, or just solo traitors?

2021-07-10 20:19 UTC, TheGamerdk commented
> Does this apply to all traitor gamemodes, such as traitorlings, or just solo traitors?

just sole traitor for now

2021-07-10 20:20 UTC, adamsong approved these changes, later dismissed

2021-07-11 16:40 UTC, adamsong reviewed
Add a greater variance to the start delay

2021-07-11 16:40 UTC, adamsong commented on code/game/gamemodes/traitor/traitor.dm
> +		addtimer(CALLBACK(src, /datum/game_mode/traitor.proc/add_traitor_delayed, traitor), rand(2 MINUTES, (2 MINUTES + 10 SECONDS)))
```suggestion
		addtimer(CALLBACK(src, /datum/game_mode/traitor.proc/add_traitor_delayed, traitor), rand(3 MINUTES, 5 MINUTES))
```

2021-07-11 17:57 UTC, TheGamerdk commented on code/game/gamemodes/traitor/traitor.dm
> +		addtimer(CALLBACK(src, /datum/game_mode/traitor.proc/add_traitor_delayed, traitor), rand(3 MINUTES, 5 MINUTES))
```suggestion
		addtimer(CALLBACK(src, /datum/game_mode/traitor.proc/add_traitor_delayed, traitor), rand(2 MINUTES, (2 MINUTES + 10 SECONDS)))
```

2021-07-11 17:58 UTC, adamsong commented on code/game/gamemodes/traitor/traitor.dm
> +	addtimer(VARSET_CALLBACK(src, gamemode_ready, TRUE), (2 MINUTES + 11 SECONDS))
```suggestion
	addtimer(VARSET_CALLBACK(src, gamemode_ready, TRUE), (5 MINUTES + 1 SECONDS))
```

2021-07-11 18:00 UTC, TheGamerdk commented on code/game/gamemodes/traitor/traitor.dm
> +		addtimer(CALLBACK(src, /datum/game_mode/traitor.proc/add_traitor_delayed, traitor), rand(2 MINUTES, (2 MINUTES + 10 SECONDS)))
```suggestion
		addtimer(CALLBACK(src, /datum/game_mode/traitor.proc/add_traitor_delayed, traitor), rand(3 MINUTES, (5 MINUTES + 10 SECONDS)))
```

2021-07-11 18:00 UTC, TheGamerdk commented on code/game/gamemodes/traitor/traitor.dm
> +	addtimer(VARSET_CALLBACK(src, gamemode_ready, TRUE), (2 MINUTES + 11 SECONDS))
```suggestion
	addtimer(VARSET_CALLBACK(src, gamemode_ready, TRUE), (5 MINUTES + 11 SECONDS))
```

2021-07-11 18:31 UTC, TheGamerdk commented on code/game/gamemodes/traitor/traitor.dm
> +	if(!traitor.current.client || (traitor.current.stat != CONSCIOUS))
```suggestion
	if(!traitor || !traitor.current || !traitor.current.client || (traitor.current.stat != CONSCIOUS) || istype(traitor.current.loc, /obj/machinery/cryopod))
```

2021-07-11 18:32 UTC, TheGamerdk commented on code/game/gamemodes/traitor/traitor.dm
> +		return
```suggestion
		message_admins("Failed to find new antag after original one left! Check the antag balance please.")
		return
```

2021-07-11 23:40 UTC, monster860 commented
Time to just wait 5 minutes after latejoining instead

2021-07-11 23:41 UTC, TheGamerdk commented
> Time to just wait 5 minutes after latejoining instead

most people probably won't do this so we're good

2021-07-13 16:29 UTC, adamsong commented
Seems to be working in test merge, need to do a bit more testing, and then add this to the combined modes

2021-07-13 20:08 UTC, MegaEmpirical commented
Nifty

2021-07-22 09:48 UTC, Cartlord commented
BRO THIS ROLLED A FREE MINER AS SYNDIE ROUND 36291

2021-07-24 21:07 UTC, adamsong commented
Seems to also work on traitorling rounds, possibly other combo rounds

2021-07-24 21:15 UTC, Cartlord commented
So uh, there doesn't seem to be anything in place that keeps Lifegivers, Free Miners, or Charlie Station folks from being antags. That seems like a bad thing - what's a Lifegiver meant to do if they get Hijack or something?

2021-07-31 18:10 UTC, adamsong commented
Add a check to make sure they are on the station z-level, so if a ghost role is on the station, such as free miners, they can get it, and it means they can get on the station for their objectives, otherwise they can't become traitor

2021-08-10 04:44 UTC, adamsong requested changes, later dismissed

2021-08-10 04:44 UTC, adamsong commented on code/game/gamemodes/traitor/traitor.dm
> +		if(!applicant.client)
```suggestion
		if(!is_station_level(applicant.z))
			continue
		if(!applicant.client)
```

2021-08-14 14:03 UTC, JamieD1 approved these changes

2021-08-14 14:04 UTC, merged