Adds helper to make teleportation into partially hazardous areas safer
yogstation13/Yogstation pull request #11747
Opened 2021-07-10 17:11 UTC by Lostlarry

fixes #5305

so added a new mapping helper 'teleportation_anchor'
if you teleport using scroll of teleportation into an area with teleportation anchor/s you will apear on a random teleportation unblocked anchor instead of any empty turf
added teleportation anchors for choice locations (for now only atmos_distro and Incinerator)

todo need to make better sprite for the teleport_anchor 
:cl:  
tweak: added teleportation_anchor mapping helper, add few of these into the safe parts of partialy hazardous areas 
bugfix: prevents teleportation into atmos distro on box to teleport player into unsafe areas
/:cl:

2021-07-10 18:31 UTC, adamsong commented
YogStation isn't mapmerged, also you may want to add these to the other maps

2021-07-10 18:40 UTC, TheGamerdk commented on code/game/area/areas.dm
> +		else
why

2021-07-10 18:42 UTC, TheGamerdk commented on code/game/objects/items/scrolls.dm
> +	var/list/achors = thearea.teleport_achors
achors 🤔

2021-07-10 18:42 UTC, TheGamerdk commented on code/game/area/areas.dm
> +	var/turf/teleport_achors = list()	//ist of tiles we prefer to teleport to. this is for areas that are partially hazardous like for instance atmos_distro
achors 🤔 🤔 🤔

2021-07-10 19:25 UTC, adamsong requested changes
Mapmerge yogstation

2021-07-10 20:11 UTC, Lostlarry commented
i tried to map merge but when i tried run it it just says press any key to continue and then closes

2021-07-13 14:59 UTC, adamsong commented
You could always just use strong dmm or fastdmm2 which automatically map merge

2021-07-14 16:56 UTC, Lostlarry commented
> You could always just use strong dmm or fastdmm2 which automatically map merge

thanks

2021-07-14 17:04 UTC, Lostlarry commented
note to self eclipse station may need a toxins chanber rework since the area is just merged with toxins area

2021-07-15 15:05 UTC, wejengin2 approved these changes
Map is fine now

2021-07-16 12:07 UTC, grimm-hollowknight approved these changes

2021-07-18 13:08 UTC, JamieD1 approved these changes

2021-07-18 13:08 UTC, merged