[Admin
yogstation13/Yogstation pull request #11803
Opened 2021-07-18 17:20 UTC by JamieD1

# If this is your first PR, or not, take the time to read our CONTRIBUTING.md file! You can see it here: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# Github documenting your Pull Request

Remove this text and explain what the purpose of your PR is.

Mention if you have tested your changes. If you changed a map, make sure you used the mapmerge tool.
If this is an Issue Correction, you can type "Fixes Issue #6" to link the PR to the corresponding Issue number #6.

Prefix the PR title with [admin] if it involves something admin related. 
Prefix the PR title with [s] if you are fixing an exploit, so that it is not announced on the Yogstation Discord and the server.

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying.

# Wiki Documentation

Remove this text and write all information regarding your changes that should be known and documented through the Yogstation Wiki. 
Important documentation information includes, but is not limited to: any numerical values that have been changed, any images that have to be updated, names of specific pages that will be impacted by your changes. 

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images  
spellcheck: fixed a few typos  
experimental: This is experimental  
/:cl:

2021-07-18 19:23 UTC, TheGamerdk requested changes, later dismissed
Good PR

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +/datum/admins/proc/change_laws(boopbeep in GLOB.silicon_mobs)
Is this argument ever passed? Does it ask you when you call the proc?

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +	if (istype(boopbeep, /mob/living/silicon))
So if you got the argument you... discard it and ask the user again?

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +/datum/admins/proc/change_laws(boopbeep in GLOB.silicon_mobs)
Consider a better variable name too maybe?

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +	if (!ispath(chosen))
Probably should just check if(!chosen) return so you're certain they passed in a path/selected one. Could do it in your statement below

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +		chosen = text2path(chosen)
Shouldn't be in the if statement, probably shouldn't be there in general, pick_closest_path returns a valid path or returns nothing

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +	if (chosen)
invert the if statement and make it an early return as per above

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +		board.install(beepboop.laws, src)
```suggestion
		board.install(beepboop.laws, usr)
```

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +		var/mob/living/silicon/beepboop = boopbeep
confusing variable names, especially since boopbeep is already a silicon?

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +		del(new_board)
qdel

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +		message_admins("[key_name_admin(src)] added [board] to [ADMIN_LOOKUPFLW(beepboop)].")
```suggestion
		message_admins("[key_name_admin(usr)] added [board] to [ADMIN_LOOKUPFLW(beepboop)].")
```

2021-07-18 19:23 UTC, TheGamerdk commented on code/modules/admin/verbs/borgpanel.dm
> +		log_admin("[key_name(src)] added [board] to [key_name(beepboop)].")
```suggestion
		log_admin("[key_name(usr)] added [board] to [key_name(beepboop)].")
```

2021-07-20 15:15 UTC, MegaEmpirical commented
Fucking thank you. Fixing this shit has always been annoying.

2021-07-24 12:11 UTC, JamieD1 commented
Better Code

2021-08-07 11:06 UTC, merged