Redoes the TEG calculation because it broke thermodynamics
yogstation13/Yogstation pull request #11864
Opened 2021-07-21 09:25 UTC by Lostlarry

so the TEG was doing some real nonsence with themal capacities so i redid it so it would actualy make some sort of sense physics wise

not sure if this is a nerf or buff

makes TEG graphics not freak out when it is completed with no connection to grid (i will do this separetly if this PR gets denied)
# Wiki Documentation
principle is the same just the numbers are different
# Changelog

:cl:  
tweak: changed TEG energy calculation so it doesnt break laws of thermodynamics
imageadd: adds new overlay for TEG for when it has no powergrid
/:cl:

2021-07-22 17:35 UTC, Xoxeyos requested changes
Spell check line 65 in /power/generator please. //Circulators decide how much air moves through

2021-07-22 22:32 UTC, Cartlord commented
I'd like to point out that, uh, a lot of shit in this game breaks the laws of physics already - why is the TEG suddenly a concern?

2021-07-23 06:45 UTC, Lostlarry commented
> I'd like to point out that, uh, a lot of shit in this game breaks the laws of physics already - why is the TEG suddenly a concern?

really its because I found it and the code looked like thrash
I am pretty sure that it was plausible to run TEG one only heaters coolers which makes no bloody sense

2021-07-23 19:20 UTC, Cartlord commented
I've run it well off _T4_ thermomachines, but I don't think I've ever seen people seriously run it with just roundstart heaters & freezers.

2021-07-26 16:35 UTC, grimm-hollowknight approved these changes

2021-07-31 19:26 UTC, adamsong commented on code/modules/power/generator.dm
> +		var/datum/gas_mixture/cold_air = cold_circ.return_transfer_air()		//circulators give us air that is moving trough
```suggestion
		var/datum/gas_mixture/cold_air = cold_circ.return_transfer_air()		//circulators give us air that is moving through
```

2021-08-17 05:33 UTC, Hopekz commented
> I'd like to point out that, uh, a lot of shit in this game breaks the laws of physics already - why is the TEG suddenly a concern?

You do realize this game is an ongoing volunteer project so those instances only really get fixed here and there when someone feels like it

2021-08-28 21:03 UTC, Cartlord commented
Another thing I wanna bring up relavant here (currently being discussed in Discord) is that the TEG is a massive pain in the ass, and running it on a heater is the only set-and-forget method we have; everything else requires either babysitting the damn thing, or funky construction using materials not present in the engine chamber.

2021-08-29 18:27 UTC, wejengin2 commented
Make sure this doesnt break the stock teg setup

2021-09-17 11:35 UTC, JamieD1 commented
Will review with darth in round after this is merged to dial the numbers in.

2021-09-17 11:35 UTC, merged

2021-09-18 01:43 UTC, ToasterBiome commented
Why was this merged with 6 thumbs down and no thumbs up?