Makes Weed Killer actually Hurt Venus Fly Traps
yogstation13/Yogstation pull request #11931
Opened 2021-07-31 20:18 UTC by JamieD1

Plants should B Gone.

10 Damage per tick I hope.

2021-07-31 20:35 UTC, adamsong requested changes, later dismissed

2021-07-31 20:35 UTC, adamsong commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +		if(istype(M, /mob/living/simple_animal/hostile/venus_human_trap)
```suggestion
		if(istype(M, /mob/living/simple_animal/hostile/venus_human_trap))
```
Do better

2021-07-31 20:56 UTC, Marmio64 commented
Too much dmg imo

2021-07-31 21:55 UTC, SomeguyManperson commented
do they even have reagents to process chemicals from

2021-08-01 17:02 UTC, alexkar598 submitted a review, later dismissed
template

2021-08-01 20:25 UTC, TheGamerdk requested changes, later dismissed
Template + please confirm that you intend any spray volume to cause 10 damage.

2021-08-14 12:19 UTC, JamieD1 commented
Need to make it actually work.

2021-08-30 11:12 UTC, JamieD1 commented
If someone could make this would, I would be appreciated.

2021-09-11 12:16 UTC, JamieD1 commented
SOMEONE FIX MY PR!

REEEEEEEEEEEEEEEEEEEEE

2021-09-20 10:52 UTC, JamieD1 commented
I fixed it, please review.

2021-09-21 22:29 UTC, alexkar598 reviewed
template

2021-10-17 09:43 UTC, merged