Adds some procs that are useful for bus
yogstation13/Yogstation pull request #11949
Opened 2021-08-03 20:34 UTC by adamsong

# Github documenting your Pull Request

Funny bus

Darkspawn ascend, but its moja
Chestburst, but its moja

2021-08-03 20:35 UTC, alexkar598 commented
Going to get real boring real fast

2021-08-03 21:05 UTC, TheGamerdk requested changes
All the times need changing to use the defines
New procs need autodoccing

2021-08-03 21:05 UTC, Bibby0110 commented on yogstation/code/modules/admin/moja.dm
> +/mob/living/carbon/human/moja
don't just have an empty type declaration. you don't need it, defining a proc on the type declares the type automatically

2021-08-03 21:05 UTC, Bibby0110 commented on yogstation/code/modules/admin/moja.dm
> +	var/mob/living/carbon/human/moja/moja = new /mob/living/carbon/human/moja(src.loc)
```suggestion
	var/mob/living/carbon/human/moja/moja = new /mob/living/carbon/human/moja(get_turf(loc))
```

2021-08-03 21:05 UTC, Bibby0110 commented on yogstation/code/modules/admin/moja.dm
> +		var/mob/living/carbon/human/moja/moja = new /mob/living/carbon/human/moja(src.loc)
```suggestion
		var/mob/living/carbon/human/moja/moja = new /mob/living/carbon/human/moja(get_turf(loc))
```

2021-08-03 21:05 UTC, Bibby0110 commented on yogstation/code/modules/admin/moja.dm
> +	for(var/mob/living/L in view(7, src))
could do oview and drop the self check at the expense of not stunning people standing on top of the moja

2021-08-03 21:05 UTC, TheGamerdk commented on yogstation/code/modules/admin/moja.dm
> +		new/obj/structure/psionic_barrier(T, 500)
```suggestion
		new/obj/structure/psionic_barrier(T)
```
default value

2021-08-03 21:05 UTC, TheGamerdk commented
personally think it's a weird bloaty way to include a moja reference

2021-08-04 19:37 UTC, SomeguyManperson commented
unfunny and bluepilled

2021-08-06 16:49 UTC, adamsong commented on yogstation/code/modules/admin/moja.dm
> +		new/obj/structure/psionic_barrier(T, 500)
Copied from darkspawn, will fix

2021-08-06 16:51 UTC, adamsong commented on yogstation/code/modules/admin/moja.dm
> +	for(var/mob/living/L in view(7, src))
Moja might stand on someone though

2021-08-06 16:52 UTC, adamsong commented on yogstation/code/modules/admin/moja.dm
> +		var/mob/living/carbon/human/moja/moja = new /mob/living/carbon/human/moja(src.loc)
I want them to show up in a locker if they are in a locker

2021-08-06 16:52 UTC, adamsong commented on yogstation/code/modules/admin/moja.dm
> +	var/mob/living/carbon/human/moja/moja = new /mob/living/carbon/human/moja(src.loc)
I want them to show up in a locker if they are in a locker

2021-08-12 22:10 UTC, JamieD1 approved these changes

2021-08-12 22:10 UTC, merged