admins but they get to make voice announcements too
yogstation13/Yogstation pull request #11967
Opened 2021-08-07 11:23 UTC by TheGamerdk

?

2021-08-07 15:12 UTC, alexkar598 commented
Ah yes I love to hear admin voice while getting abused with supply pods

2021-08-07 16:15 UTC, adamsong commented on code/game/machinery/computer/communications.dm
> +			if (!authenticated_as_non_silicon_captain(usr) || !IsAdminGhost(usr))
Not necessary, admin ghosts authenticate as non silicon captains.

2021-08-07 16:16 UTC, adamsong commented on code/game/machinery/computer/communications.dm
> +					data["canMakeVoiceAnnouncement"] = ishuman(user) || IsAdminGhost(user)
Why not move this up to the authenticated_as_non_silicon_captain block, and set it to true?

2021-08-11 22:56 UTC, adamsong requested changes
See two previous comments

2021-08-14 12:37 UTC, closed without merging