Removes all Quirks from Command and Sec
yogstation13/Yogstation pull request #11995
Opened 2021-08-10 14:33 UTC by JamieD1

Removes all Quirks from Command and Sec

2021-08-10 14:37 UTC, wejengin2 commented
hugbox

2021-08-10 14:37 UTC, TheGamerdk requested changes

2021-08-10 14:37 UTC, TheGamerdk commented on code/datums/traits/_quirk.dm
> +		return
You’ll have to qdel(src) before you return

2021-08-10 14:38 UTC, JamieD1 commented
> hugbox

So you want a no legged security officer with bad aim who is deaf, addicted to meth and is blind trying to arrest antags.

2021-08-10 14:39 UTC, TheGamerdk commented
> > hugbox
> 
> So you want a no legged security officer with bad aim who is deaf, addicted to meth and is blind trying to arrest antags.

Ye

2021-08-10 14:40 UTC, TheGamerdk requested changes
Also template

2021-08-10 14:45 UTC, JamieD1 commented
> hugbox

Opposite of hugbox.. this stops snowflakes..

2021-08-10 14:46 UTC, JamieD1 commented on code/datums/traits/_quirk.dm
> +		return
```suggestion
	if(IS_COMMAND(quirk_mob) | IS_SECURITY(quirk_mob))
	    qdel(src)
		return
```

2021-08-10 14:49 UTC, adamsong approved these changes

2021-08-10 14:49 UTC, adamsong commented on code/datums/traits/_quirk.dm
> +	if(IS_COMMAND(quirk_mob) | IS_SECURITY(quirk_mob))
```suggestion
	if(IS_COMMAND(quirk_mob) || IS_SECURITY(quirk_mob))
```

2021-08-10 14:49 UTC, adamsong requested changes
Last comment was supposed to request changes, please convert spaces to tabs thanks

2021-08-10 15:17 UTC, yacabo commented
I don't think this is a problem nearly enough to demand removing quirks outright

2021-08-10 15:19 UTC, adamsong commented
We could always just ban sec/command for incompetence if their quirks interfere with their role

2021-08-10 16:30 UTC, maxion12345 commented
jamie wants to remove officer wheels for being overpowered

2021-08-14 12:46 UTC, JamieD1 commented
11 downvotes. Oof

2021-08-17 23:12 UTC, adamsong commented
12 downvotes, no upvotes, no reason to fully remove all quirks

2021-08-17 23:12 UTC, closed without merging