Nerfs Sheltered (Understand Common)
yogstation13/Yogstation pull request #11994
Opened 2021-08-10 14:32 UTC by JamieD1

Nerfs Sheltered (Understand Common)

2021-08-10 14:36 UTC, wejengin2 commented
what's the point now

2021-08-10 14:36 UTC, TheGamerdk requested changes, later dismissed
Template

2021-08-11 06:19 UTC, maxion12345 commented
tf you mean nerf it's a buff

2021-08-11 17:45 UTC, wejengin2 commented
Nerf to being able to be an ass and powergame not speaking

2021-08-14 13:18 UTC, TheGamerdk commented on code/datums/traits/negative.dm
> +	H.remove_language(/datum/language/common, FALSE, TRUE)
```suggestion
	H.remove_language(/datum/language/common, TRUE, FALSE)
```

2021-08-14 13:18 UTC, TheGamerdk approved these changes

2021-08-14 13:42 UTC, TheGamerdk approved these changes

2021-08-14 13:42 UTC, TheGamerdk approved these changes

2021-08-14 13:42 UTC, merged