Adds Custom Mentor role, can Add Wiki and Stuff now
yogstation13/Yogstation pull request #12014
Opened 2021-08-12 20:29 UTC by JamieD1

Adds Custom Mentor role, can Add Wiki and Stuff now

2021-08-12 20:30 UTC, alexkar598 requested changes
Update SQL schema

2021-08-12 20:59 UTC, alexkar598 commented
For the record, storing the rank as a string across all rows is a stupid idea

2021-08-12 21:40 UTC, adamsong commented
How would you recommend storing it?

2021-08-12 22:15 UTC, alexkar598 commented
As an id which points to a rank

2021-08-13 01:28 UTC, adamsong commented
Admin tanks use a string

2021-08-13 04:26 UTC, alexkar598 commented
Whoever came up with that idea doesn't know how a relational database works

2021-08-14 13:31 UTC, TheGamerdk commented
> Whoever came up with that idea doesn't know how a relational database works

our codebase in a nutshell

2021-08-14 13:38 UTC, TheGamerdk commented on SQL/database_changelog.txt
> +version 5.5 14 August 2021, by JamieD1
add 
---------------------------------------------------- 
above

2021-08-17 02:25 UTC, N3D6 commented
Maybe needs a bug report but right now rementoring after dementoring makes your role show up as [] when you talk in OOC

2021-08-21 12:29 UTC, merged