Space dragon carp suit
yogstation13/Yogstation pull request #12021
Opened 2021-08-14 06:58 UTC by Marmio64

Space dragon now drops special space dragon scales when butchered. These scales can be used to create a space dragon suit that has no slowdown and will make carp friendly to you while in use. However, compared to the ash drake suit it has 20 less melee protection. Didn't quite make much sense to make a lavaland red and grey suit from a purple fish dragon.

:cl:  
rscadd: Adds the space dragon carp suit. It can be crafted with scales from a butchered space dragon.
/:cl:

2021-08-17 17:44 UTC, grimm-hollowknight requested changes
Other than the tiny details on the shoulders, this is identical to the carp suit. Needs to be more distinct. I recommend changing the colours or making it more "scaley".

2021-08-28 19:58 UTC, grimm-hollowknight commented
on hold until another sprite update

2021-08-30 20:40 UTC, Marmio64 commented
> on hold until another sprite update

done

2021-08-31 13:34 UTC, grimm-hollowknight approved these changes

2021-08-31 13:35 UTC, merged