[admin] Disconnect panel
yogstation13/Yogstation pull request #12047
Opened 2021-08-15 20:27 UTC by adamsong

# Github documenting your Pull Request
Adds a 'Disconnect Panel' which lists all players who have at some point disconnected, giving information about their connection history. This can be used to find players who have been disconnected for an extended period of time, and deal with them.

![image](https://user-images.githubusercontent.com/4607006/129491757-339a9b63-4d33-465a-ac57-fd5f5960c56d.png)

# Changelog

:cl:  
rscadd: Added a panel to show connection information about players.
/:cl:

2021-08-15 21:51 UTC, adamsong commented
It says they are not intended the same, but they are indented the same, anyone can help?

2021-08-17 22:34 UTC, Hopekz requested changes

2021-08-17 22:34 UTC, Hopekz commented on code/modules/admin/verbs/disconnectpanel.dm
> +	set desc = "Panel showing information about the currently disconneted players"
```suggestion
	set desc = "Panel showing information about the currently disconnected players"
```

2021-08-19 00:08 UTC, N3D6 commented
Really based PR, makes it a lot easier to see who is disconnected and for how long.

2021-08-19 09:17 UTC, JamieD1 approved these changes
Works well.

2021-08-19 09:17 UTC, merged