doubled piggyback mounting time
yogstation13/Yogstation pull request #12072
Opened 2021-08-18 01:56 UTC by Marmio64

piggyback combat is dumb and i was reminded to remove it by looking at mbrain

okay well it's not gone but its a lot harder to do since it takes 3 seconds instead of 1.5 seconds, and upgrading to a neck grab is also 3 seconds, so you have to be a lot faster if you want to pull it off.

:cl:  
tweak: doubled piggyback mounting time
/:cl:

2021-08-18 02:02 UTC, Mqiib commented
good balance tweak thank you mr marmimo

2021-08-21 11:49 UTC, TheGamerdk commented on code/modules/mob/living/carbon/human/human.dm
> +		if(do_after(target, 30, target = src))
```suggestion
		if(do_after(target, 3 SECONDS, target = src))
```

2021-08-21 11:50 UTC, TheGamerdk requested changes, later dismissed
meant to do this

2021-08-21 12:47 UTC, JamieD1 commented
Now make it so if the person you are carrying is fat they make you fall over.

2021-08-25 10:12 UTC, JamieD1 approved these changes

2021-08-25 10:13 UTC, merged