Re-adds drunkenness counting as a painkiller for surgery screwups
yogstation13/Yogstation pull request #12092
Opened 2021-08-21 03:24 UTC by SomeguyManperson

# Github documenting your Pull Request

this got killed off at some point probably because I couldn't be assed to properly fix it now I have though so it's fine :)
41 is the highest current effect range that won't cause vomiting or toxin damage so I think it's good

# Wiki Documentation

Drunkenness reaching 41 will remove the chance to screw up a surgery step and cause damage

# Changelog

:cl:  
tweak: Drunkenness reaching 41 will remove the chance to screw up a surgery step and cause damage
/:cl:

2021-08-21 11:53 UTC, TheGamerdk requested changes, later dismissed

2021-08-21 11:53 UTC, TheGamerdk commented on code/modules/mob/living/carbon/life.dm
> +	REMOVE_TRAIT_FROM(TRAIT_SURGERY_PREPARED, "drunk")
Probably meant REMOVE_TRAIT?

2021-08-21 11:53 UTC, TheGamerdk commented on code/modules/mob/living/carbon/life.dm
> +			ADD_TRAIT(TRAIT_SURGERY_PREPARED, "drunk")
```suggestion
			ADD_TRAIT(src, TRAIT_SURGERY_PREPARED, "drunk")
```

2021-08-24 09:41 UTC, JamieD1 approved these changes

2021-08-24 09:43 UTC, JamieD1 approved these changes

2021-08-24 09:43 UTC, merged