Makes cheese effect temporary, also change back on cheese mob death
yogstation13/Yogstation pull request #12098
Opened 2021-08-21 14:58 UTC by JamieD1

# Github documenting your Pull Request

Makes cheese effect temporary, also change back on cheese mob death

# Wiki Documentation

Makes cheese effect temporary, also change back on cheese mob death

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
tweak: Makes cheese effect temporary, also change back on cheese mob death
/:cl:

2021-08-21 17:49 UTC, N3D6 commented
this is the part where cheese staff gets added normally.............................

2021-08-24 09:39 UTC, JamieD1 commented
> this is the part where cheese staff gets added normally.............................

Soon

2021-08-25 23:19 UTC, adamsong requested changes

2021-08-25 23:19 UTC, adamsong commented on code/modules/mob/living/simple_animal/friendly/cheese.dm
> +	var/mob/living/carbon/human/stored_mob
cheesify takes a `mob/living`

2021-08-25 23:37 UTC, JamieD1 commented on code/modules/mob/living/simple_animal/friendly/cheese.dm
> +	var/mob/living/carbon/human/stored_mob
```suggestion
	var/mob/living/stored_mob
```

2021-08-25 23:44 UTC, adamsong approved these changes

2021-08-25 23:47 UTC, merged