Ports Turnstiles from NSV13 (or beestation no clue where they came from)
yogstation13/Yogstation pull request #12105
Opened 2021-08-22 20:30 UTC by maxion12345

# Github documenting your Pull Request
Adds turnstiles! These are more or less one-way doors that let people with no access pass in one direction, and block them in the other! if you have access, it'll let you pass both ways. Originally used for brig doors so prisoners can grab their shit and leave without needing someone to get the door. Only added them to HoP line because prisoner lockers are bugged and they need help to leave anyways.

# Wiki Documentation

Update HoP line photo

# Changelog
:cl:  
rscadd: Added turnstiles that allow people to pass only in one direction. If you have the set access, you can pass in both directions.
rscadd: Yogstation HoP now has turnstiles to keep the gray masses moving in one direction.
/:cl:

2021-08-22 20:30 UTC, maxion12345 commented
i don't know why it has "updating wheelchair.dm" on there it doesn't even change anything that was merged already

2021-08-22 20:31 UTC, Mqiib commented
we have this already, there are settings for doors that allow anyone to open them from one side.

2021-08-22 20:33 UTC, wejengin2 commented
yes but this only lets one person pass and only from one side

2021-08-22 21:18 UTC, maxion12345 commented
> we have this already, there are settings for doors that allow anyone to open them from one side.

this also looks nicer

that all being said i am not good coder so i don't know why lints is angry at me :(

2021-08-22 21:23 UTC, maxion12345 commented
fixed the map test now i gotta figure out why the proc isn't doing the stuff the proc should be doing

i don't know how to do this
it works
i tested it
can i paypal the headcoders 20 bucks to ignore the tests

2021-08-23 03:39 UTC, adamsong commented
`/obj/machinery/turnstile/proc/CanPass` is the wrong proc, you want `Cross`

`CanPass` is marked a pure, which means it should not change any state, simply return a value, https://toolz.readthedocs.io/en/latest/purity.html

2021-08-23 05:22 UTC, adamsong commented
I sad `Cross` not `CanCross`

2021-08-23 05:23 UTC, maxion12345 commented
> I sad `Cross` not `CanCross`

you right its late

2021-08-23 05:30 UTC, wejengin2 approved these changes
Map is good.

Also I'm not a spriteman but if those direction arrows are visible ingame and are not just helpers then it looks ass.

2021-08-23 05:30 UTC, maxion12345 commented
> Map is good.
> 
> Also I'm not a spriteman but if those direction arrows are visible ingame and are not just helpers then it looks ass.

helpers

2021-08-23 12:52 UTC, grimm-hollowknight approved these changes

2021-08-25 16:55 UTC, grimm-hollowknight reviewed
If this is a port, please put a link to the original PR in the description and credit the author.

2021-08-26 02:05 UTC, Sniblet commented
The hop turnstiles don't let people into the line
lemao

2021-08-26 03:26 UTC, adamsong requested changes

2021-08-26 03:26 UTC, adamsong commented on code/game/machinery/doors/turnstile.dm
> +	if(get_dir(loc, target) == dir || allowed) //Make sure looking at appropriate border
```suggestion
	if(get_dir(mover.loc, target) == dir || allowed) //Make sure looking at appropriate border
```

2021-08-26 05:30 UTC, Bibby0110 commented
You’ll need to fit in a parent call in Cross so the proper signals are sent too

2021-08-26 09:23 UTC, ToasterBiome commented on code/game/machinery/doors/turnstile.dm
> +	req_one_access = list(ACCESS_HEADS)
Why does the HOP turnstile have Head exclusive access to it? Regular players cant get into the line because of this

2021-08-26 14:34 UTC, adamsong commented on code/game/machinery/doors/turnstile.dm
> +	req_one_access = list(ACCESS_HEADS)
Read the PR

2021-08-26 15:17 UTC, adamsong approved these changes
Code works now

2021-08-26 16:23 UTC, ToasterBiome commented on code/game/machinery/doors/turnstile.dm
> +	req_one_access = list(ACCESS_HEADS)
misinterpreted what the access does, people without access still weren’t able to go in them from what i saw as of my first comment

2021-08-26 18:08 UTC, maxion12345 commented
> Code works now

thank you, no clue why they worked 100% fine in testing but instantly broke later on

2021-08-26 18:33 UTC, adamsong commented
You were testing with CanPass, Cross has a different signature.

2021-08-28 11:07 UTC, AnCopper commented
They're actually from Oracle Station.

2021-08-28 18:20 UTC, maxion12345 commented
> They're actually from Oracle Station.

thank
do you have a PR I can link by chance so I can put the author's name in there

2021-08-28 18:57 UTC, AnCopper commented
https://github.com/OracleStation/OracleStation/pull/419

2021-08-30 11:20 UTC, JamieD1 commented
Can you find some more noises which might be more suitable?

Also can you make a half tile option which is climb over able for less secure areas, I dont like the look of the fecking prison style ones.

2021-08-30 17:42 UTC, adamsong commented
Make medical ones for the main medbay areas

2021-08-31 01:26 UTC, maxion12345 commented
> Can you find some more noises which might be more suitable?
> 
> Also can you make a half tile option which is climb over able for less secure areas, I dont like the look of the fecking prison style ones.

not sure I can, these are meant for secure areas

or when you want people moving in one direction, like the HoP line. climbing over them would kinda defeat the purpose

2021-08-31 01:40 UTC, maxion12345 commented
> Make medical ones for the main medbay areas

Surgery, treatment area, and the medbay exit doors are now turnstiles. This will probably be reverted though, not sure they work well in medbay

2021-08-31 01:49 UTC, maxion12345 commented
git angy :(

2021-09-01 16:07 UTC, JamieD1 commented
Ones like this 
![image](https://user-images.githubusercontent.com/993128/131705586-2c35bb7c-891d-4cf4-b226-1a7e409920da.png)

2021-09-02 03:27 UTC, maxion12345 commented
> Ones like this
> ![image](https://user-images.githubusercontent.com/993128/131705586-2c35bb7c-891d-4cf4-b226-1a7e409920da.png)

aye I've got climbing half-working. if you don't have to access it'll just make you not climb it. I got work for the next few days so i'll find a workaround

2021-09-04 00:32 UTC, maxion12345 commented
@JamieD1 made a turnstile thats climbable, and one that isn't

2021-09-11 12:22 UTC, JamieD1 commented
> @JamieD1 made a turnstile thats climbable, and one that isn't

Did you really just cut the sprite in half...?

Much dissapoint.

2021-09-11 12:34 UTC, AnCopper commented
> > @JamieD1 made a turnstile thats climbable, and one that isn't
> 
> Did you really just cut the sprite in half...?
> 
> Much dissapoint.

Powermove tbh.

2021-09-12 18:29 UTC, maxion12345 commented
> > @JamieD1 made a turnstile thats climbable, and one that isn't
> 
> Did you really just cut the sprite in half...?
> 
> Much dissapoint.

listen you did not want to see the codersprite that I made for it
just trust me on this, this is the better choice

2021-09-17 11:39 UTC, JamieD1 commented
> > > @JamieD1 made a turnstile thats climbable, and one that isn't
> > 
> > 
> > Did you really just cut the sprite in half...?
> > Much dissapoint.
> 
> listen you did not want to see the codersprite that I made for it
> just trust me on this, this is the better choice
> we can replace it later with something not so cringe

"fix later"
"never fix"

2021-09-17 11:39 UTC, merged