Added Advance tools to engineering cyborg
yogstation13/Yogstation pull request #12120
Opened 2021-08-23 16:43 UTC by JayBaez

What is in this PR:
Added the ATMOS holofan into the techweb for researching. You can research and print the upgrade board for the engineering cyborg. Added a new techweb research node for advance tools. The advance tools are the experimental tools (jaws of life, hand drill, tricorder, NOT experimental welding tool) and the Bluespace RPED. 

Purpose of this PR:
The engineering cyborg already has tools for humans, as the Geiger counter or analyzer, the ATMOS is too OP to have at the start so it can be researched. 
The BSRPED and advance tools give the borg a useful upgrade as the round advances.

:cl:  
rscadd: Added advance tools/ BSRPED/ ATMOS holofan to engineering cyborg
/:cl:

2021-08-23 16:43 UTC, JamieD1 commented
Jamie helped

2021-08-23 16:44 UTC, JayBaez commented
ignore the various and redundant commits. I committed mistakes and was too lazy to make a new branch to remove it.

2021-08-23 16:44 UTC, Jarod1200 commented
borg powercreep moment

2021-08-23 17:17 UTC, UselessTheremin commented
you really sat down, looked at the engiborg, and thought to yourself... "this needs a buff"

lmao

2021-08-23 18:03 UTC, JayBaez commented
> you really sat down, looked at the engiborg, and thought to yourself... "this needs a buff"
> 
> lmao

It's just a quality of life

2021-08-23 20:09 UTC, Jarod1200 commented
Holofan and BRPED are too op for borgs period. There are literally 0 drawbacks to the engi borg with this PR.

2021-08-23 20:39 UTC, JayBaez commented
> Holofan and BRPED are too op for borgs period. There are literally 0 drawbacks to the engi borg with this PR.

What would be OP would be giving the engineering cyborg the experimental welder. The holofan goes with the whole "keep human alive" tools like the Geiger counter and analyzer. The BSRPED is later game research where most things would have already been upgraded.

2021-08-23 20:41 UTC, Jarod1200 commented
The atmos holofan is a weapon of station ending destruction. "Whoops I just released my fusion cloud into medbay after welding the firelocks open as malf ai"

2021-08-23 21:36 UTC, adamsong commented
> Whoops I just released my fusion cloud into medbay after welding the firelocks open as malf ai

Which of those steps used a holofan?

2021-08-26 22:22 UTC, ShatteredParadox commented
> > Whoops I just released my fusion cloud into medbay after welding the firelocks open as malf ai
> 
> Which of those steps used a holofan?

Holding back the toxic/intensely hot gas, and at a push of a button, releasing the hot deadly gas through all of the open firelocks. Basically being able to remotely trigger the attack.

2021-08-30 20:56 UTC, JamieD1 approved these changes
No experimental t ray

2021-08-30 20:56 UTC, JamieD1 commented on code/game/objects/items/robot/robot_upgrades.dm
> +			R.module.remove_module(TS, TRUE)
T ray needed
```suggestion
```

2021-08-30 20:56 UTC, JamieD1 commented on code/game/objects/items/robot/robot_upgrades.dm
> +		R.module.add_module(TS, FALSE, TRUE)
```suggestion
```

2021-08-30 21:32 UTC, JayBaez commented
You play a hard game Jamie. I’m all good with your recommendation

2021-09-01 13:56 UTC, JamieD1 commented
> You play a hard game Jamie. I’m all good with your recommendation

Its more the fact you remove the t ray and dont give a replacement with the advanced tools so you are basically deleting the t ray

2021-09-01 16:06 UTC, JamieD1 requested changes
Remove the BSRPED from its own node and unlock it on the normal BSRPED to prevent wasting of resources if "noone will ever use it"

Also disable the option for disabling the barriers remotely.

Shout if you need help with any of these.

2021-09-01 20:57 UTC, JayBaez commented
> > You play a hard game Jamie. I’m all good with your recommendation
> 
> Its more the fact you remove the t ray and dont give a replacement with the advanced tools so you are basically deleting the t ray

But doesn't the Tricorder have a T-ray scanner built in? along with power, atmos?

2021-09-01 21:01 UTC, Jarod1200 commented
Tricorder does not have a t ray

2021-09-02 00:29 UTC, JayBaez commented
> Tricorder does not have a t ray

Then I must be monkey brained

2021-09-02 00:30 UTC, JayBaez commented
> Remove the BSRPED from its own node and unlock it on the normal BSRPED to prevent wasting of resources if "noone will ever use it"
> 
> Also disable the option for disabling the barriers remotely.
> 
> Shout if you need help with any of these.

prob will cause my time to work on this has dropped since school started back up again.

2021-09-17 14:15 UTC, JamieD1 commented on code/modules/research/techweb/layout.dm
> +        ui_y = -896
```suggestion
        ui_y = -896
```

2021-09-23 15:37 UTC, wejengin2 requested changes
What is the point of the map change here? Looks like you're just doing changes from #12270 ?

2021-09-23 15:46 UTC, wejengin2 commented
Also I would like to state i think this pr is bad and i don't like it

2021-10-15 14:20 UTC, SomeguyManperson commented
![image](https://user-images.githubusercontent.com/24857008/137502685-b09c48a9-9f17-43b9-99e1-96802007887f.png)
wtf happened here

2021-10-29 11:06 UTC, patpol4 commented
@JayBaez is anything happening to this

2021-10-29 11:07 UTC, Bibby0110 commented
Fix merge conflicts + whatever jamie did.
Good luck with your school :)

2021-10-29 11:07 UTC, closed without merging

2023-08-01 14:51 UTC, JayBaez commented
> @JayBaez is anything happening to this

yea