Reduces the required strange reagent to revive from 10 to 2 because rezadone is already enough of a pain in the ass as is
yogstation13/Yogstation pull request #12155
Opened 2021-08-26 03:29 UTC by SomeguyManperson

# Github documenting your Pull Request

each carp fillet gives 2 units of carpotoxin, if someone is actually hunting space carp they'll get 4 per, and if cargo gives a damn and buys meat crates they have a decent but still rather low chance to get 2-6 units
If something is locked THIS far behind teamwork, and causes damage, the least it can be is attainable in a usable amount.
Effectively, with it requiring rezadone to mix currently, strange reagent with this change will give 6 revives per carp flesh, up from 1. If that's too much it can be changed to 4 units to only allow 3 revivals per carp flesh.

# Wiki Documentation

strange reagent requires 2 units to work down from 10

# Changelog

:cl:  
tweak: strange reagent requires 2 units to work down from 10
/:cl:

2021-08-26 08:50 UTC, JamieD1 commented
Was agreed by a few cmo mains, so you will need to talk to them

2021-08-27 03:30 UTC, SomeguyManperson commented
Did they agree on it alongside or without the change that made it use rezadone. If they did, they want strange reagent moreso removed than nerfed, if they didn't, what the fuck.

2021-09-01 13:51 UTC, JamieD1 requested changes
Ok well some people are clearly stupid,

Lets see how often its used now if we lower this

2021-09-01 13:51 UTC, JamieD1 approved these changes

2021-09-01 13:52 UTC, JamieD1 requested changes

2021-09-01 13:52 UTC, JamieD1 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +#define REQUIRED_STRANGE_REAGENT_FOR_REVIVAL 2 ///Adam Sucks
```suggestion
#define REQUIRED_STRANGE_REAGENT_FOR_REVIVAL 2
```

2021-09-01 13:52 UTC, merged