Sets security level to gamma when cult ascends
yogstation13/Yogstation pull request #12151
Opened 2021-08-25 23:48 UTC by ynot01

# Github documenting your Pull Request

Lets the crew know that they should start fighting the cult because 40% of the station is now cult

# Changelog

:cl:  
tweak: Security level is now set to gamma when cult have halos
/:cl:

2021-08-25 23:49 UTC, adamsong commented
40% cult just means a lot of cult, bloodstones if left unchecked causes Narsie summon

2021-08-26 20:00 UTC, Bibby0110 approved these changes

2021-08-30 11:37 UTC, JamieD1 requested changes
@ynot01 Change to the bloodstones not halos.

2021-09-01 15:59 UTC, JamieD1 commented
Bloodstones already make gamma. Halos not big enough.

2021-09-04 14:04 UTC, closed without merging