Revert "Adds a racial language for every xeno who doesn't have one"
yogstation13/Yogstation pull request #12160
Opened 2021-08-26 12:12 UTC by tattax

# Github documenting your Pull Request

Reverts yogstation13/Yogstation#12082 cause as again stated no race needs their own language as it creates a barrier beetween players and really pushes the ''i'll ignore you cause you're not my race / don't speak my tongue'' type of mentality players tend to have. also PR had a 1:2 like to dislike ratio and got merged anyways.

# Changelog

:cl:  
rscdel: removed languages from plasmaman, moth and etheral
imagedel: deleted language stuff
/:cl:

2021-08-26 17:26 UTC, nesisknesis commented
Added the documentation template for you, you'll need to fill the changelog out. Also I think you need a stronger argument if you want this merged since you're directly contesting the person who merged it's decision to merge the last pr.

2021-08-26 17:26 UTC, nesisknesis approved these changes

2021-08-30 11:43 UTC, JamieD1 requested changes
This literally just adds options for races that dont have a "sheltered" language to have one.

Humans have japanese
Lizards have draconic

So your argument is basically pointless as this just adds the unique sheltered languages for different races.

Do you expect a pod person to learn fecking japanese?

2021-09-11 12:23 UTC, JamieD1 commented
This has been merged a while and the " ''i'll ignore you cause you're not my race / don't speak my tongue'' type of mentality players tend to have." behaviour has not come about as of yet.

If this comes up in the future we can look back into this. For now it adds some nice additions to playing different species.

2021-09-11 12:23 UTC, closed without merging