Fixes failed Borg buckling giving you the weird buckle hands
yogstation13/Yogstation pull request #12183
Opened 2021-08-29 08:47 UTC by TheGamerdk

I deleted the template on accident. See title

:cl:    
bugfix: fixed a borg buckling issue    
/:cl:

2021-08-29 08:53 UTC, ToasterBiome requested changes
move dis

2021-08-29 08:53 UTC, ToasterBiome commented on code/modules/mob/living/silicon/robot/robot.dm
>  	M.visible_message("<span class='warning'>[M] begins to [M == usr ? "climb onto" : "be buckled to"] [src]...</span>")
```suggestion
```

2021-08-29 08:53 UTC, ToasterBiome commented on code/modules/mob/living/silicon/robot/robot.dm
> +
```suggestion
	M.visible_message("<span class='warning'>[M] begins to [M == usr ? "climb onto" : "be buckled to"] [src]...</span>")
```

2021-08-30 11:35 UTC, SomeguyManperson approved these changes

2021-08-30 12:21 UTC, merged