Fix floodlights not turning off when out of power, and fixes sling veil not working on them
yogstation13/Yogstation pull request #12222
Opened 2021-09-01 19:34 UTC by adamsong

# Github documenting your Pull Request

Fixes floodlights not turning off when power to them is cut
Fixes sling veil not working on floodlights

Fixes #12053 

# Changelog

:cl:  
bugfix: fixed floodlights not turning off
bugfix: fixed sling veil not working on floodlights
/:cl:

2021-09-01 19:47 UTC, Cartlord commented
I was under the impression the SLing thing was intentional, since the wiki actually advises setting floodlights everywhere in the event of confirmed SLings.

2021-09-04 14:25 UTC, JamieD1 commented
> I was under the impression the SLing thing was intentional, since the wiki actually advises setting floodlights everywhere in the event of confirmed SLings.

Pretty sure floodlights are not supposed to turn off if they are hard wired.

2021-09-11 12:29 UTC, JamieD1 requested changes
Please make it that if a floodlight is hardwired and the ling uses the ability it sets it to its lowest range instead, maybe also make it flash.

2021-09-11 14:37 UTC, adamsong commented on yogstation/code/modules/antagonists/shadowling/shadowling_abilities.dm
> +			FL.change_setting(1) // Turn off the floodlight
```suggestion
			FL.change_setting(2) // Set floodlight to lowest setting
```

2021-09-15 11:19 UTC, SomeguyManperson approved these changes
considering the current meta of putting floodlights under glass which is completely unaddressable by shadowlings having floodlights set to the lowest range (which is still quite large) should be enough
also floodlight code is old and jank and old

2021-09-17 11:45 UTC, JamieD1 approved these changes

2021-09-17 11:45 UTC, merged