gives nicotine free cigarettes a expanded description to make more sense
yogstation13/Yogstation pull request #12271
Opened 2021-09-08 23:07 UTC by boodaliboo

"A Tobacco-free cigarette, it contains Chamomile, Lemon Balm, and Catnip."
this is the new description as a cigarette with no nicotine and tobacco is impossible
:cl:  
tweak: tweaked nicotine free description
/:cl:

2021-09-08 23:52 UTC, boodaliboo commented
tell me if i did this wrong

2021-09-09 00:37 UTC, Marmio64 commented
contains chamomile, lemonbalm, and catnip, yet still only contains carbon reagents?  Maybe just keep it ambiguous or say it simply contains nicotine free tobacco.

2021-09-09 00:53 UTC, boodaliboo commented
> contains chamomile, lemonbalm, and catnip, yet still only contains carbon reagents? Maybe just keep it ambiguous or say it simply contains nicotine free tobacco.

nicotine free tobacco doesnt exist though, and there isnt really any reagents that would reflect the herbal taste

2021-09-09 00:57 UTC, ynot01 commented
uncapitalize the names they arent proper nouns please

2021-09-09 00:59 UTC, Marmio64 commented
> > contains chamomile, lemonbalm, and catnip, yet still only contains carbon reagents? Maybe just keep it ambiguous or say it simply contains nicotine free tobacco.
> 
> nicotine free tobacco doesnt exist though, and there isnt really any reagents that would reflect the herbal taste

nicotine free tobacco doesn't exist cause no ones added it yet, bruh. And it's not like it has to be an actual plant...
And, you can just like, you know, make a reagent that will reflect it.

2021-09-09 03:31 UTC, ToasterBiome requested changes

2021-09-09 03:31 UTC, ToasterBiome commented on code/game/objects/items/cigs_lighters.dm
> +	desc = "A Tobacco-free cigarette, it contains Chamomile, Lemon Balm, and Catnip."
```suggestion
	desc = "A tobacco-free cigarette, it contains chamomile, lemon balm, and catnip."
```

2021-09-09 03:32 UTC, ToasterBiome commented on code/game/objects/items/cigs_lighters.dm
> +	desc = "A Tobacco-free cigarette, it contains Chamomile, Lemon Balm, and Catnip."
i think the "ingredients" are fine, they literally don't have to mean anything. just don't capitalize them

2021-09-09 03:45 UTC, boodaliboo commented
> > > contains chamomile, lemonbalm, and catnip, yet still only contains carbon reagents? Maybe just keep it ambiguous or say it simply contains nicotine free tobacco.
> > 
> > 
> > nicotine free tobacco doesnt exist though, and there isnt really any reagents that would reflect the herbal taste
> 
> nicotine free tobacco doesn't exist cause no ones added it yet, bruh. And it's not like it has to be an actual plant...
> And, you can just like, you know, make a reagent that will reflect it.

im not making a reagent for this its fine as is it was just made to be a description change as those are common ingredients in herbal smoke mixes

2021-09-09 17:26 UTC, Hopekz commented
> nicotine free tobacco doesnt exist though, 

Imo it's funny to think that the company is just lying to their audience and telling them they have nicotine free tobacco just like companies in China that sell diet water

2021-09-11 12:37 UTC, JamieD1 commented on code/game/objects/items/cigs_lighters.dm
> +
```suggestion
```

2021-09-11 12:50 UTC, JamieD1 approved these changes

2021-09-11 12:50 UTC, merged