adds two new audible emotes and adds sound to others
yogstation13/Yogstation pull request #12412
Opened 2021-10-06 20:01 UTC by maxion12345

# Document the changes in your pull request

added two new emotes because I felt like coding all of a sudden
also I just wanted *lipsmack what a rotten way to die
also added sounds to other emotes

https://user-images.githubusercontent.com/23666142/136283001-4b6c5d51-4524-4fb8-b25c-aa40ff9dd835.mp4

(enable volume)

# Wiki Documentation
n/a

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added cringe 
rscadd: *sheesh
rscadd: *lipsmack
rscadd: the following emotes now have sound
rscadd: *whistle, *iwhistle, *eyebrow
/:cl:

2021-10-06 20:09 UTC, cuackles commented
please dont add sheeeesh it hurst me on a psycological level

2021-10-06 20:10 UTC, maxion12345 commented
> please dont add sheeeesh it hurst me on a psycological level

but what are greytiders if not edgy tiktok artists working at a minimum wage job

2021-10-06 20:19 UTC, ToasterBiome commented
I have no words

2021-10-07 01:13 UTC, Anvilman6 commented
![cursed land](https://user-images.githubusercontent.com/54463777/136304834-8a4af3fb-1242-4682-8bf1-045e8fa3d7fb.jpg)

2021-10-07 03:53 UTC, maxion12345 commented
*dab *sheesh *eyebrow *spin *roll *dab *eyebrow

2021-10-07 07:44 UTC, patpol4 commented
time to get those macros ready

2021-10-07 08:00 UTC, Tipy1802 commented
While the adition of sheesh is questionable giving sounds to the other emotes it really good

2021-10-07 14:51 UTC, Mqiib commented
No sheesh
please

2021-10-08 03:20 UTC, maxion12345 commented
> No sheesh please

new midround
time traveler
can *sheesh *dab *tpose *thud to cause brain damage to people nearby, eventually killing them
goals are to get to ian and scream what the dog doing

2021-10-09 00:23 UTC, Cartlord commented
I despise *eyebrow unironically

2021-10-10 18:20 UTC, adamsong requested changes

2021-10-10 18:20 UTC, adamsong commented on code/modules/mob/living/carbon/human/emote.dm
> +	sound = 'sound/voice/thud.ogg'
I've never heard a noise when raising my eybrows

2021-10-14 16:35 UTC, SomeguyManperson commented
I doagnose you with cringe

2021-10-14 16:35 UTC, closed without merging