Alternative to genpop PR, adds genpop interface to our current brig timer
yogstation13/Yogstation pull request #12422
Opened 2021-10-08 21:40 UTC by maxion12345

# Document the changes in your pull request
TODO:

- [x] Fix security hud not updating when you brig someone (Sets their record to incarcerated but HUD won't update until something forces it (removing mask, etc)

kinda realized that our current brig timer does 80% of the things the genpop one does

So, why merge this over the port?
No funky IDs to fuck around with
No turnstiles on brig doors to get yourself trapped in
[NEW] you can do automatic record-setting
[NEW] swipe prisoner ID to set their name automatically if you can't be fucked to type it
literally two button operation

Why merge genpop over this?
Easy to expand brig system
And you can stuff more then one prisoner into a cell

oh I had to remove the random brig cell variants because that broke the brig lockers automatically closing
and here's a photo of the UI

![](https://i.gyazo.com/7763f9883c11a80756df0c97ebc5696e.png)

# Wiki Documentation

add a note near brig procedures about swiping the prisoner's ID to automatically set the name for automatic record setting

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added preset crime buttons to brig timers
rscdel: Removed brig cell variations due to breaking automatic locker locking 
rscadd: Turnstiles to brig
/:cl:

2021-10-08 22:03 UTC, ToasterBiome commented
I liked the auto adding to ID's :'( Maybe let us put their ID in there and itll auto add the crime?

2021-10-09 00:00 UTC, maxion12345 commented
> I liked the auto adding to ID's :'( Maybe let us put their ID in there and itll auto add the crime?

I'll see if I can port the auto-record setting from genpop

2021-10-10 23:52 UTC, maxion12345 commented
ready for testmerge

2021-10-14 11:42 UTC, patpol4 approved these changes
This looks really bad on box with the half door but ok

2021-10-24 14:22 UTC, JamieD1 approved these changes

2021-10-24 19:26 UTC, adamsong submitted a review, later dismissed
Why is this touching rust_g?

2021-10-24 19:32 UTC, Bibby0110 requested changes
tgui lookover 2 seconds

2021-10-24 19:48 UTC, Bibby0110 approved these changes
can't be bothered to look at tgui nevermind, do this though

2021-10-24 19:48 UTC, Bibby0110 commented on code/game/machinery/doors/brigdoors.dm
> +	else
empty return?

2021-10-24 19:48 UTC, Bibby0110 commented on code/game/machinery/doors/brigdoors.dm
> +			 // open doors, reset timer, clear status screen
why

2021-10-24 19:48 UTC, Bibby0110 commented on code/game/machinery/doors/brigdoors.dm
> +		else if(desired_name == null)
```suggestion
		else if(!desired_name)
```

2021-10-24 19:48 UTC, Bibby0110 commented on code/game/machinery/doors/brigdoors.dm
> +			if(prisoner_name == null | !Adjacent(usr))
I doubt they care about short-circuiting logic here
```suggestion
			if(!prisoner_name || !Adjacent(usr))
```

2021-10-24 19:48 UTC, Bibby0110 commented on code/game/machinery/doors/brigdoors.dm
>  			timer_start()
```suggestion
			timer_start(usr)
```

2021-10-24 19:48 UTC, Bibby0110 commented on code/game/machinery/doors/brigdoors.dm
> +			var/preset_crime = params["crime"]
be aware this looks open to manipulating crime names clientside, and side this isn't filtered you can display random stuff in the crimes.
Should probably validate that this crime is one of the actual crimes

2021-10-24 19:48 UTC, Bibby0110 commented on code/game/machinery/doors/brigdoors.dm
> +			var/value = text2num(params["preset"])
open to manipulating but the timer is clamped so it doesn't matter

2021-10-26 06:46 UTC, patpol4 commented
So is this good to go?

2021-10-27 19:54 UTC, maxion12345 commented
> So is this good to go?

aye

2021-10-28 07:06 UTC, merged