Expands aux base construction to include a place for building shuttles
yogstation13/Yogstation pull request #12462
Opened 2021-10-15 05:00 UTC by nmajask

# Document the changes in your pull request

Expands Aux Base Construction to include a place to build shuttles. It has also been merged with port bow solars, so I had to mess with maints a bit to get it to work. The mining shuttle also docks to the open area instead of inside the base construction area. The amount of wires needed to wire the solar panels is still 40, tough it is a bit of a walk. There is also some supplies for building shuttles in a storage room next to the solars room. I have not tested this, so some things may break because of the scale of the changes and my lack of experience.

## Images
### New Aux Base Construction
![image](https://user-images.githubusercontent.com/14363906/137433634-b3bbf2a1-d3f3-4eb7-8133-07b9c661172f.png)

![image](https://user-images.githubusercontent.com/14363906/137433968-7d5af9b1-074f-4fd1-bb14-b0aadd6a0c1f.png)

![image](https://user-images.githubusercontent.com/14363906/137434067-2c7c062f-4ebb-4b1e-96b6-81098302817d.png)

### Starting Boards
![image](https://user-images.githubusercontent.com/14363906/137433734-815a79e9-4d37-48bc-bf73-41f800b30a93.png)
![image](https://user-images.githubusercontent.com/14363906/137433879-7af672c2-7e6e-4b3f-9c09-4d7d5ef37244.png)

# Wiki Documentation

Many images will need to be changed, and if there is a page for aux base construction that will need to be updated too. 

# Changelog

:cl:  
tweak: expanded aux base construction to include a place for building shuttles
/:cl:

2021-10-15 05:13 UTC, maxion12345 commented
Some of the items placed are items that require research to be completed, not sure if we'll want to bypass the shuttle research. It'd be the equivalent of putting space pod parts in the pod bay, I suppose.

2021-10-15 05:19 UTC, nmajask commented
> Some of the items placed are items that require research to be completed, not sure if we'll want to bypass the shuttle research. It'd be the equivalent of putting space pod parts in the pod bay, I suppose.

All you get is the parts to build a very small shuttle that doesnt have docking computer. You would need to research to be able to dock anywhere that isn't the whiteship dock.

2021-10-15 05:49 UTC, ToasterBiome commented
I wish the aux base construction area was moved more to the left and having a little 4x3 room or something so the room can be open to the public, doesn't seem anything in there besides the aux base stuff that would get yoinked.

2021-10-15 22:45 UTC, ToasterBiome commented
What about my ideas OwO

2021-10-22 19:39 UTC, patpol4 requested changes
1. Are these all just fuel ports? also check the indoor one, also they need dirs to connect to the pipes
![image](https://user-images.githubusercontent.com/48154165/138512175-f4de168e-8f7c-4329-b76e-df4ef228c109.png)
2.  is this supposed to cut off like that? seems weird, either do a corner or attach something to them
![image](https://user-images.githubusercontent.com/48154165/138512283-0a7f190b-e30d-407e-bf9a-e91a328daecc.png)
3. Some of the solar turfs have double cables on them, double check please
![image](https://user-images.githubusercontent.com/48154165/138512380-14101494-ff29-4ded-93c3-18c5ebc5431c.png)
4. The stripe decals won't be visible on catwalks so remove those
5. double decal and missing firelocks here, also remember to add them on the shutter and on the red airlock to the right
![image](https://user-images.githubusercontent.com/48154165/138512729-745ef77c-a96e-440c-8f59-ca78a2780b32.png)
6. this isn't engineering secure storage
![image](https://user-images.githubusercontent.com/48154165/138513051-01b13346-0ec4-4265-9481-deeab5b48f48.png)
7. This is an oversight right?
![image](https://user-images.githubusercontent.com/48154165/138513346-a67447ff-0feb-4910-a4ca-021807c09c2c.png)

I think this is it but i might have missed some, the rest will come out after merge probably

2021-10-23 02:12 UTC, nmajask commented
> 1. Are these all just fuel ports? also check the indoor one, also they need dirs to connect to the pipes

Fixed

> 2. is this supposed to cut off like that? seems weird, either do a corner or attach something to them

I made them cut off at the corner.

> 3. Some of the solar turfs have double cables on them, double check please

Double checked most of them, and fixed the ones I found.

> 4. The stripe decals won't be visible on catwalks so remove those

Done

> 5. double decal and missing firelocks here, also remember to add them on the shutter and on the red airlock to the right

I assume you mean the left one, in which case its fixed.

> 6. this isn't engineering secure storage

Fixed

> 7. This is an oversight right?

Fixed, though I had to do some code changes to allow the shuttles to dock with it. The original point of the two were to allow the mining shuttles to dock with it without code changes, but I guess its unavoidable at this point.

2021-10-23 11:45 UTC, patpol4 approved these changes
Yes, sorry I meant left

2021-10-23 11:46 UTC, merged