Alternative station announcers now almost never appear.
yogstation13/Yogstation pull request #12479
Opened 2021-10-19 19:00 UTC by Xoxeyos

This changes the weights of the alternative station announcers from 1 to 0, making them (almost) never appear.

# Changelog

Changes the weights for alternative station announcers from 1 to 0.

:cl:  Xoxeyos
tweak: Alternative station announcers now (almost) never appear. 
/:cl:

2021-10-19 19:15 UTC, adamsong commented
I like the intern

2021-10-19 19:43 UTC, Xoxeyos commented
> 
> 
> I like the intern

I don't like the intern

2021-10-19 20:13 UTC, Tipy1802 commented
Bad PR. Intern is great

2021-10-19 21:31 UTC, TheLinuxOS commented
Counter argument, do this but then add a button so admins can make a voice announcement so that we can be the intern

2021-10-19 22:24 UTC, Cartlord commented
I hate the intern, he's massively annoying when you hear the burger line for the third time in a round

2021-10-20 12:46 UTC, UselessTheremin commented
yeah intern isnt funny after a few rounds aaand it doesnt really make sense tbh with the normal announcer being a robot. i hate the intern

2021-10-24 14:33 UTC, JamieD1 commented
Can you just make them less likely instead?

Disabling is not really fun is it.

2021-10-31 15:23 UTC, TheGamerdk approved these changes

2021-10-31 15:23 UTC, TheGamerdk commented on code/datums/station_traits/neutral_traits.dm
> +	weight = 0
```suggestion
	weight = 0.01
```

2021-10-31 15:23 UTC, TheGamerdk commented on code/datums/station_traits/neutral_traits.dm
> +	weight = 0
```suggestion
	weight = 0.01
```

2021-10-31 15:26 UTC, TheGamerdk requested changes
see above

2021-11-05 02:08 UTC, Xoxeyos commented
> 
> 
> see above

Done, sorry it took a bit.

2021-11-14 17:44 UTC, JamieD1 approved these changes

2021-11-14 17:44 UTC, JamieD1 commented on code/datums/station_traits/neutral_traits.dm
> +	weight = 0.01
```suggestion
	weight = 0.2
```

2021-11-14 17:44 UTC, JamieD1 commented on code/datums/station_traits/neutral_traits.dm
> +	weight = 0.01
```suggestion
	weight = 0.2
```

2021-11-14 17:45 UTC, JamieD1 commented
Change to my values please. Making it 100 times less likely is stupid.

2021-12-03 22:39 UTC, TheGamerdk approved these changes

2021-12-03 22:40 UTC, merged