New goat just dropped, part 2
yogstation13/Yogstation pull request #12579
Opened 2021-11-02 01:08 UTC by cuackles

# Document the changes in your pull request

*new goat, suspicious goat, its like a normal goat but more red and more suspicous, they can also ventcrawl if i didnt fuck up the code
*add said goat to the exotic goat crates
*goat image 
![image](https://user-images.githubusercontent.com/68789204/139770506-7b482f6e-9e61-4bef-8739-aae0682bd81f.png)

# Wiki Documentation

add the sus goat to the goat list in the exotic crate

# Changelog
:cl:  
rscadd: Added new goat and puts it in the exotic goat crate
imageadd: added some icons for the new goat

/:cl:

2021-11-02 01:09 UTC, fluffe9911 commented
sus

2021-11-02 01:11 UTC, ToasterBiome commented
sus

2021-11-02 01:25 UTC, Jarod1200 commented
Ah yes  from the popular book by Dr. Sus: One Goat, Two Goat, Red Goat, Dead Goat

2021-11-02 02:43 UTC, Hopekz commented
sus

2021-11-02 02:44 UTC, Hopekz commented on yogstation/code/modules/mob/living/simple_animal/friendly/goats.dm
> +	desc = "A suspicious looking goat"
```suggestion
	desc = "A suspicious looking goat."
```

2021-11-02 10:21 UTC, wejengin2 commented
good execution

2021-11-08 19:44 UTC, grimm-hollowknight approved these changes

2021-11-08 19:47 UTC, grimm-hollowknight requested changes

2021-11-08 19:47 UTC, grimm-hollowknight commented on yogstation/code/modules/mob/living/simple_animal/friendly/goats.dm
> +	icon_dead = "suspiciusgoat_dead"
fix spelling in the icon file and here

```suggestion
	icon_state = "suspiciousgoat"
	icon_living = "suspiciousgoat"
	icon_dead = "suspiciousgoat_dead"
```

2021-11-08 20:23 UTC, grimm-hollowknight approved these changes

2021-11-10 18:39 UTC, merged