prevents borgs from self destructing while stunned
yogstation13/Yogstation pull request #12614
Opened 2021-11-07 03:51 UTC by SomeguyManperson

# Document the changes in your pull request

I had an argument with biome like a couple days ago about this and decided to not do anything but then I got redtexted because a borg self destructing got me killed due to the knockdown and have decided against not doing it because whatever argument can be come up with to give borgs which are already powerful in combat a way to cause more damage even if they lose is stupid and wrong

tldr self destructing when already stunned has no real downside since you're going to be dead/converted whether you do it or not and gives you one last chance to fuck over whoever has stunned you. Liberal use of the self destruct feature can prevent:
traitors from emagging you
clock cultists from converting you
anyone else from killing you if they don't have a gun to keep a safe distance with

# Changelog

:cl:  
rscdel: borgs can no longer self destruct while stunned
/:cl:

2021-11-07 03:52 UTC, Absolucy commented
I DED

2021-11-07 03:54 UTC, Jarod1200 commented
what a based PR

2021-11-07 04:11 UTC, Marmio64 commented
i hate silicon mains

2021-11-07 04:12 UTC, Mqiib commented
Hate borgs, good nerf, very excellent, tyhank you thoes

2021-11-07 04:36 UTC, maxion12345 commented
skill issue
honestly issue is that the borg can still scream like a bitch for help after destruction, that's what'll get you killed more then the actual knockdown

2021-11-09 00:13 UTC, adamsong requested changes, later dismissed
Otherwise looks fine codewise

2021-11-09 00:13 UTC, adamsong commented on yogstation/code/modules/mob/living/silicon/robot/robot.dm
>  		return //won't work if dead
```suggestion
		return //won't work if dead or incapacitated
```

2021-11-09 03:34 UTC, merged