Adds hawaiian shirt to the vending machine
yogstation13/Yogstation pull request #12622
Opened 2021-11-07 23:45 UTC by AlvCyktor

Title

:cl:  
rscadd: Hawaiian Shirt is now in the Clothesmate
/:cl:

2021-11-08 23:58 UTC, adamsong requested changes
Fix the indentation please

2021-11-10 18:44 UTC, SomeguyManperson commented
why  tf is th entire file indented with spaces what

2021-11-14 18:10 UTC, JamieD1 commented on code/modules/vending/clothesmate.dm
> +					/obj/item/clothing/under/yogs/tourist = 3,
```suggestion
		            /obj/item/clothing/under/yogs/tourist = 3,
```

2021-11-14 18:26 UTC, JamieD1 approved these changes

2021-11-14 18:26 UTC, merged