makes luxury shuttle windows unbreakable
yogstation13/Yogstation pull request #12648
Opened 2021-11-11 06:02 UTC by boodaliboo

makes luxury shuttle windows unbreakable so the poor can no longer interfere with the rich achievig point of shuttle
:cl:  
tweak: tweaked  fuck the poor
/:cl:

2021-11-11 06:03 UTC, ToasterBiome commented
rules were meant to be broken

2021-11-11 10:04 UTC, GoreDem commented
inb4 you can rcd these ones as well

2021-11-11 20:18 UTC, Xoxeyos commented
Which windows? The ones where all the poor people go, or the ones on the walls of the shuttle?

2021-11-14 18:26 UTC, JamieD1 approved these changes

2021-11-16 00:19 UTC, adamsong requested changes

2021-11-16 00:19 UTC, adamsong commented on _maps/shuttles/emergency_luxury.dmm
> -	desc = "A durable looking window made of an alloy of of plasma and titanium. Appears to have poor people tears smudged all over it.";
Where did this description go?

2021-11-16 07:56 UTC, wejengin2 commented
You replaced them with a closed transparent turf which means it will have space under it and look shit, I'm all for oppression of the poor but this just makes the window look bad. Would be better to use flags that make it indestructible and un rcd'able, if such exist.

2021-11-17 10:54 UTC, closed without merging