Adds some stuff to charlie station
yogstation13/Yogstation pull request #12659
Opened 2021-11-14 20:24 UTC by redmoogle

# Document the changes in your pull request

Adds a thing of cable coils by medical maint
stuffs the PA in a crate
Removes the transport pod for a bridge
Makes the science room *slighty* bigger

![image](https://user-images.githubusercontent.com/20369082/141697274-692934cf-b83f-4120-a7a9-8ed8e20b770a.png)

# Changelog

:cl:  
rscadd: Removes the pod from charlie and adds a bridge instead
tweak: Stuff the PA in charlie station into a crate
tweak: Adds another pack of cable coils to charlie station
/:cl:

2021-11-14 21:21 UTC, wejengin2 commented
Why, also include the wiki part

2021-11-14 21:24 UTC, redmoogle commented
> 
> 
> Why? Also include the wiki part

added one stack of cable coils because you kinda run out
added a bridge because pod is annoying and weird
PA just takes up alot of unneeded room
The rest is to make the alignment work

2021-11-15 09:36 UTC, Moggram commented
The AI core is now open to space.

2021-11-15 18:04 UTC, Chubbygummibear commented
Something important to note, I'm pretty sure you bulldozed through one of the 4 bluespace crystal spawns with the footbridge. I recently learned there are 4 distinct spawns, but you need 5 to make a functional teleporter. 

So if I may make a suggestion, re-add the bluespace crystal spawn, and maybe add a few diamonds to one of the bridge crates so it's feasible to make artificial bluespace crystals without hoping for a lucky diamond ore spawn for the 5th crystal. 

That aside, love to see ghost role love bless up

2021-11-15 23:05 UTC, redmoogle commented
> 
> 
> Something important to note, I'm pretty sure you bulldozed through one of the 4 bluespace crystal spawns with the footbridge. I recently learned there are 4 distinct spawns, but you need 5 to make a functional teleporter.
> 
> So if I may make a suggestion, re-add the bluespace crystal spawn, and maybe add a few diamonds to one of the bridge crates so it's feasible to make artificial bluespace crystals without hoping for a lucky diamond ore spawn for the 5th crystal.
> 
> That aside, love to see ghost role love bless up

Readded that one crystal and also put down an diamond asteroid tile

2021-11-16 08:42 UTC, wejengin2 commented on _maps/RandomRuins/SpaceRuins/oldstation.dmm
> +	name = "Electrical Maintanace"
maintanace

2021-11-16 08:42 UTC, wejengin2 commented on _maps/RandomRuins/SpaceRuins/oldstation.dmm
> +	name = "Electrical Maintanace"
maintanace

2021-11-16 08:47 UTC, wejengin2 requested changes
1. Plant is fine but what is the cobweb hanging onto?
![image](https://user-images.githubusercontent.com/48154165/141952166-7a496c5e-6889-4a17-a41e-3c66788c2067.png)

2. I don't get the point of this change
![image](https://user-images.githubusercontent.com/48154165/141952522-7b13d7c2-a3bb-44d8-a3f3-20333e13a36f.png)

Other than this and the maintanace stuff, this is very nice.

2021-11-16 12:05 UTC, redmoogle commented
> 1. Plant is fine but what is the cobweb hanging onto?
> ![image](https://user-images.githubusercontent.com/48154165/141952166-7a496c5e-6889-4a17-a41e-3c66788c2067.png)
> 
> 2. I don't get the point of this change
> ![image](https://user-images.githubusercontent.com/48154165/141952522-7b13d7c2-a3bb-44d8-a3f3-20333e13a36f.png)
> 
> Other than this and the maintanace stuff, this is very nice.

1 oop 

2 those were indestructible turfs and changed it to look like an actual maint/storage room

2021-11-17 10:54 UTC, wejengin2 commented
just the maint typos now and its good to go

2021-11-17 11:16 UTC, redmoogle commented
> 
> 
> just the maint typos now and its good to go

fixed

2021-11-17 11:23 UTC, wejengin2 approved these changes
Is good

2021-11-17 11:26 UTC, merged