Adds Remembrance Day as a holiday because JamieD12 is a fat plum
yogstation13/Yogstation pull request #12669
Opened 2021-11-15 18:28 UTC by grimm-hollowknight

# Document the changes in your pull request

 Adds remembrance day holiday which puts poppy pins in people's hand at roundstart on that day.

JamieD12 is a fat plum because he merged a PR where I had a review and merged a PR with the DO NOT MERGE label.

# Changelog

:cl:  Identification
rscadd: Adds Remembrance Day
/:cl:

2021-11-15 18:30 UTC, TheGamerdk requested changes

2021-11-15 18:30 UTC, TheGamerdk commented on code/modules/holiday/holidays.dm
> +    for(var/mob/living/carbon/human/H in GLOB.alive_mob_list)
```suggestion
    for(var/mob/living/carbon/human/H in GLOB.alive_player_list)
```

2021-11-15 18:31 UTC, nesisknesis commented on code/modules/holiday/holidays.dm
> +    for(var/mob/living/carbon/human/H in GLOB.alive_mob_list)
i see thank you

2021-11-16 00:05 UTC, adamsong commented on code/modules/holiday/holidays.dm
> +    for(var/mob/living/carbon/human/H in GLOB.alive_mob_list)
@TheGamerdk You sure that var exists?

2021-11-18 19:04 UTC, TheGamerdk commented on code/modules/holiday/holidays.dm
> +    for(var/mob/living/carbon/human/H in GLOB.alive_mob_list)
> @TheGamerdk You sure that var exists?

no

2021-11-18 19:05 UTC, TheGamerdk commented on code/modules/holiday/holidays.dm
> +    for(var/mob/living/carbon/human/H in GLOB.alive_player_list)
```suggestion
    for(var/mob/living/carbon/human/H in GLOB.player_list)
```
derp

2021-11-18 19:16 UTC, TheGamerdk approved these changes

2021-11-18 19:16 UTC, merged