makes sleeper stasis more intuitive
yogstation13/Yogstation pull request #12777
Opened 2021-11-28 19:05 UTC by SomeguyManperson

# Document the changes in your pull request

At the time I wanted to use stat alone but as it turns out there's no stat for being specifically in hardcrit and UNCONSCIOUS also shows up a myriad of other ways

Instead the sleeper will trigger stasis if either the occupant is dead or below 0 health

# Changelog

:cl:  
tweak: sleepers with the stasis upgrade will now put people into stasis under more specific circumstances
/:cl:

2021-11-29 14:59 UTC, adamsong requested changes

2021-11-29 14:59 UTC, adamsong commented on code/game/machinery/Sleeper.dm
> +		if(stasis && C.stat == DEAD || C.health < 0)
```suggestion
		if(stasis && (C.stat == DEAD || C.health < 0))
```
FALSE && FALSE || TRUE
```
Returns true

2021-12-01 01:20 UTC, Notamaniac commented
There needs to be some more feedback that the stasis is actually engaged, or better yet make it a button so if doctors need chems to metabolise while someone is in crit, they have the option to do so. Unless TGUI is literally that horrible.

2021-12-11 16:09 UTC, JamieD1 approved these changes

2021-12-11 16:09 UTC, merged