Fixed airlock painter
yogstation13/Yogstation pull request #12787
Opened 2021-11-30 01:05 UTC by adamsong

# Document the changes in your pull request

Airlock painters no longer break when painting between specific types of airlock.
Fixes #12786 
Fixes #12539 
Fixes #12135 

# Changelog

:cl:  
bugfix: fixed airlocks sometimes being invisible when painted
/:cl:

2021-11-30 01:12 UTC, redmoogle requested changes
remove this and the associated var if this is fixed

2021-11-30 15:10 UTC, UselessTheremin commented
good work, as always! it impresses me how competent a maint you remain even with your council duties

2021-12-01 17:00 UTC, alexkar598 commented
> you can now repaint cult and clock cult airlocks

brilliant

2021-12-01 17:00 UTC, alexkar598 commented
Time to do this guys, convert all airlocks to cult airlocks then repaint, whenever someone touches them it stuns them

2021-12-01 17:10 UTC, redmoogle commented
> Time to do this guys, convert all airlocks to cult airlocks then repaint, whenever someone touches them it stuns them


Did I fix a bug without trying

2021-12-11 16:12 UTC, JamieD1 approved these changes

2021-12-11 16:12 UTC, merged