Adds IC log file type, log viewer program, and door logging
yogstation13/Yogstation pull request #12861
Opened 2021-12-10 00:30 UTC by nmajask

# Document the changes in your pull request

Adds an IC log filetype to the game, which stores events and times and all that for IC events. Adds a program to view said file type, showing it in the same format as the robotact program. The point of these log files is to make machines have actual logs you can download, allowing for detectives to download and use them to figure out what happened. Currently the only machine with logging are airlocks, which log when someone opens/closes them and can be downloaded by hitting them with a mod pc when the panel is opened. Also includes some additional procs and stuff for files for use with other file types in the future.

![image](https://user-images.githubusercontent.com/14363906/145496638-d0ffd8e8-f8f8-450c-a66b-a12c0e919dc1.png)

# Wiki Documentation

At this point we should probably have a mod PC page. 

# Changelog
:cl:  
rscadd: Added a new log file type which is used to store events and a new program to view them
/:cl:

2021-12-10 02:12 UTC, ToasterBiome commented
surveillance state

2021-12-10 09:49 UTC, maxion12345 commented
sleeper logs would be epic after this, maybe I'll take a crack at it somehow

2021-12-10 16:18 UTC, nmajask commented
> sleeper logs would be epic after this, maybe I'll take a crack at it somehow

Logs arent too hard to add to machines, all you need to do is:

1. Set the has_logs var to true
2. Add a way to download logs, which is simple enough to do
3. Use the machinelog proc whenever you want something logged and using get_username to get the name of the user.

2021-12-12 12:05 UTC, adamsong requested changes

2021-12-12 12:05 UTC, adamsong commented on code/game/machinery/_machinery.dm
> +/obj/machinery/proc/machinelog(var/string = "", var/time_override = null, var/overwright = TRUE)
Overwrite is the variable name you are looking for

2021-12-12 12:05 UTC, adamsong commented on code/game/machinery/doors/airlock.dm
> +		machinelog(string = "Electrification enabled for [MACHINE_DEFAULT_ELECTRIFY_TIME][username ? " by [username]":""]")
Include units

2021-12-12 12:05 UTC, adamsong commented on code/game/machinery/doors/door.dm
> +	else if(!(I.item_flags & NOBLUDGEON) && user.a_intent != INTENT_HARM && I.GetID())
Went this interfere with opening AA doors?

2021-12-12 22:03 UTC, TheGamerdk reviewed
what adam said

2021-12-12 22:03 UTC, Bibby0110 commented on code/game/machinery/doors/airlock.dm
> +						addtimer(VARSET_CALLBACK(src, justzap, FALSE) , 10)
```suggestion
						addtimer(VARSET_CALLBACK(src, justzap, FALSE) , 1 SECONDS)
```

2021-12-12 22:03 UTC, Bibby0110 commented on code/modules/modular_computers/file_system/logs.dm
> +	if(isfull)
just do the check in the if statement

2021-12-12 22:03 UTC, Bibby0110 commented on code/modules/modular_computers/file_system/logs.dm
> +		if(overwright)
Negate the if statement and do the return if !overwright,
then you drop the else and just put the entries.Cut(1,2) outside of the if

2021-12-12 22:03 UTC, Bibby0110 commented on code/modules/modular_computers/file_system/logs.dm
> +	var/time
```suggestion
	var/time station_time_stamp()
```

2021-12-12 22:03 UTC, Bibby0110 commented on code/modules/modular_computers/file_system/logs.dm
> +	else
remove this and the below line

2021-12-12 22:03 UTC, Bibby0110 commented on code/modules/modular_computers/file_system/logs.dm
> +	if(log)
wouldn't you want to calculate_size no matter if you logged the clearing or not

2021-12-12 22:03 UTC, Bibby0110 commented on code/modules/modular_computers/file_system/logs.dm
> +	if(matches.len >= 0)
either you want just a > or you should just return it either way. can't get len < 0, and len = 0 is just empty

2021-12-12 22:03 UTC, Bibby0110 commented on code/modules/modular_computers/file_system/logs.dm
> +	else
no need for else

2021-12-12 22:03 UTC, TheGamerdk commented on code/game/machinery/doors/airlock.dm
> +	machinelog(string = "Power has been restored")
don't use named arguments for all of these.
(aka remove the string = )

2021-12-12 22:03 UTC, TheGamerdk commented on code/game/machinery/_machinery.dm
> +		username = "[id.registered_name] - [id.assignment] [id.originalassignment == id.assignment?"":"([id.originalassignment])"]"
```suggestion
		username = "[id.registered_name] - [id.assignment] [id.originalassignment == id.assignment ? "" : "([id.originalassignment])"]" 
```

2021-12-22 05:42 UTC, closed without merging