makes kittens have randomized names
yogstation13/Yogstation pull request #12887
Opened 2021-12-13 14:14 UTC by UselessTheremin

half these names are a crime against god what am i doing
all jokes aside just thought this could be interesting because whenever runtime makes a bunch of kittens you can't tell em apart, feel free to suggest other names if you want

:cl:  
rscadd: kittens now have randomized names
/:cl:

2021-12-13 14:27 UTC, Absolucy requested changes

2021-12-13 14:27 UTC, Absolucy commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +/mob/living/simple_animal/pet/cat/kitten/initialize()
```suggestion
/mob/living/simple_animal/pet/cat/kitten/Initialize()
```

2021-12-13 14:27 UTC, Absolucy commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	if(prob(5))
```suggestion
	. = ..()
	if(prob(5))
```

2021-12-13 14:27 UTC, Absolucy commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +			name = pick(rare_pet_kitten_names)
```suggestion
		name = pick(rare_pet_kitten_names)
```

2021-12-13 14:27 UTC, Absolucy commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +		else
```suggestion
	else
```

2021-12-13 14:27 UTC, Absolucy commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +			name = pick(pet_kitten_names)
```suggestion
		name = pick(pet_kitten_names)
```

2021-12-13 14:29 UTC, UselessTheremin commented
thank you lucy ❤️❤️❤️
sorry i cannot code lol
:^)

2021-12-13 16:51 UTC, Sniblet commented
Patches, Skippy, Teddy, Frank

2021-12-13 16:55 UTC, UselessTheremin commented
> Patches, Quilt, Skippy, Teddy, Frank Rare: Dumbass Cat

added!

2021-12-13 17:13 UTC, adamsong approved these changes
Will merge after 24 hours

2021-12-13 21:37 UTC, TheGamerdk approved these changes

2021-12-14 16:40 UTC, Hopekz commented
Sloppy PR since we usually use .txt files for name lists but if the maintainers are okay with it I can't really complain

2021-12-14 19:39 UTC, UselessTheremin commented
> Sloppy PR since we usually use .txt files for name lists but if the maintainers are okay with it I can't really complain

am lazy and didnt feel like making an entirely new file for that and also the names for punpun dont use a .txt file, if you want to do it be my guest lol

2021-12-15 16:23 UTC, merged