Armory access (Warden and HoS) can open brig infirmary
yogstation13/Yogstation pull request #12897
Opened 2021-12-14 02:25 UTC by bruhlookatthisdood

# Document the changes in your pull request

Changed variables so anyone with armory access can open the brig infirmary.
(HoS and warden round start)
((PS sorry for the sloppy code, it was rushed))
# Wiki Documentation

None needed

# Changelog

:cl:  
tweak: Changed brig infimary access so HoS and Warden can open them (anyone with armory access)
/:cl:

2021-12-14 16:37 UTC, Hopekz commented
Going to leave this here for people because it's basically the same PR so all discussion on #12209 would apply to this one 
---> #12209 <---

2021-12-14 20:57 UTC, bruhlookatthisdood commented
By the way, just want to point out the Chain of Command on the wiki says the warden has Control over the entire brig. The brig infirmary uses the brig APC and is labeled as brig, just a medical section. Therefore, the warden should be able to walk in there.

2021-12-19 05:57 UTC, adamsong requested changes

2021-12-19 05:57 UTC, adamsong commented on code/modules/jobs/job_types/warden.dm
> +	access = list(ACCESS_SECURITY, ACCESS_SEC_DOORS, ACCESS_BRIG, ACCESS_ARMORY, ACCESS_COURT, ACCESS_MECH_SECURITY, ACCESS_MAINT_TUNNELS, ACCESS_MORGUE, ACCESS_WEAPONS, ACCESS_FORENSICS_LOCKERS, ACCESS
The doors are ACCESS_MEDICAL not ACCESS_BRIG_PHYS, which is only the locker.

2021-12-19 13:32 UTC, JamieD1 commented
> By the way, just want to point out the Chain of Command on the wiki says the warden has Control over the entire brig. The brig infirmary uses the brig APC and is labeled as brig, just a medical section. Therefore, the warden should be able to walk in there.

With that argument the CMO should have access to the security checkpoint and everything inside it.

2021-12-19 14:40 UTC, JamieD1 commented
Alternative in progress.

2021-12-19 14:40 UTC, closed without merging