new sound effects for dropping, throwing, picking up, and equipping certain things!
yogstation13/Yogstation pull request #12901
Opened 2021-12-14 18:08 UTC by UselessTheremin

ports https://github.com/tgstation/tgstation/pull/46563
ports https://github.com/tgstation/tgstation/pull/46387
https://github.com/tgstation/tgstation/pull/46677

wip

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images  
spellcheck: fixed a few typos  
experimental: This is experimental  
/:cl:

2021-12-14 18:09 UTC, UselessTheremin commented
coommit wall moment

2021-12-15 16:13 UTC, Absolucy requested changes

2021-12-15 16:13 UTC, Absolucy commented on code/game/objects/items.dm
> +			playsound(src, pickup_sound, PICKUP_SOUND_VOLUME, ignore_walls = FALSE)
```suggestion
	if(!initial)
		if(equip_sound && !initial &&(slot_flags & slotdefine2slotbit(slot)))
			playsound(src, equip_sound, EQUIP_SOUND_VOLUME, TRUE, ignore_walls = FALSE)
		else if(slot == SLOT_HANDS)
			playsound(src, pickup_sound, PICKUP_SOUND_VOLUME, ignore_walls = FALSE)
```

2021-12-16 02:06 UTC, UselessTheremin commented
FUCK

2021-12-19 13:57 UTC, JamieD1 commented
Pretty cool, how loud are they compared to other things.

2021-12-26 12:04 UTC, JamieD1 approved these changes

2021-12-26 12:05 UTC, merged