Help settle the blood contract debate by making it expire properly
yogstation13/Yogstation pull request #12920
Opened 2021-12-17 22:27 UTC by adamsong

# Document the changes in your pull request

Currently the bloodlust ends for the victim, so it should end for everyone else as well

# Changelog

:cl:  
rscadd: Added a proper end to the blood contract bloodlust
/:cl:

2021-12-18 03:45 UTC, Absolucy requested changes

2021-12-18 03:45 UTC, Absolucy commented on code/modules/antagonists/blood_contract/blood_contract.dm
> +		to_chat(P, span_userdanger("You no longer have an overwhelming desire to kill [owner.currnt]."))
```suggestion
		to_chat(P, span_userdanger("You no longer have an overwhelming desire to kill [owner.current]."))
```

2021-12-20 21:20 UTC, adamsong commented on code/modules/antagonists/blood_contract/blood_contract.dm
> +	H.remove_atom_color("#FF0000", ADMIN_COLOUR_PRIORITY)
```suggestion
	owner.current.remove_atom_color("#FF0000", ADMIN_COLOUR_PRIORITY)
```

2021-12-26 12:07 UTC, JamieD1 approved these changes

2021-12-26 12:07 UTC, merged