Checks there are candidates for dynamic rulesets roundstart
yogstation13/Yogstation pull request #12938
Opened 2021-12-19 23:12 UTC by Xoxeyos

# Document the changes in your pull request

Ported over from https://github.com/tgstation/tgstation/pull/63305, made by [tf-4](https://github.com/tf-4)

Adds checks for candidates before applying the antag bits. It was on some, but not all, for some reason. Also updated to add it to Yogstation specific antagonists. Apparently it caused run-times otherwise, so that shouldn't happen.

# Changelog

Adds additional checks for candidates before applying the antag datums.

:cl: Xoxeyos, tf-4
rscadd: Adds additional checks for antagonist candidates before applying the datum.
/:cl:

2021-12-22 18:01 UTC, adamsong requested changes
Add a check to ensure at least a minimum number of people are selected, I don't want threat spent on a ruleset that rolls no people.

2022-01-01 21:55 UTC, Xoxeyos commented
> Add a check to ensure at least a minimum number of people are selected, I don't want threat spent on a ruleset that rolls no people.

Will do, apologies for the late response, I've been on vacation.

2022-01-07 23:36 UTC, Xoxeyos commented
> Add a check to ensure at least a minimum number of people are selected, I don't want threat spent on a ruleset that rolls no people.

After looking at the code once again, the pre_execute proc already takes care of this, as referenced in the readme; 

After all roundstart threats are chosen, /datum/dynamic_ruleset/proc/picking_roundstart_rule is called for each, passing in the ruleset and the number of times it is scaled.

    **In this stage, pre_execute is called, which is the function that will determine what players get what antagonists. If this function returns FALSE for whatever reason (in the case of an error), then its threat is refunded.**

2022-02-25 14:35 UTC, JamieD1 approved these changes

2022-02-25 14:35 UTC, merged