[Port] [WIP] Cargo mail for crew
yogstation13/Yogstation pull request #12948
Opened 2021-12-20 23:13 UTC by Inari-Whitebear

# WIP
* Tested a bit, but not fully yet.

## Todo
* Also still need to figure out all the gifts on YogStation or find replacements for things that do not exist.
* Maybe also have to see about adjusting the credit amount
* Maybe change junkmail messages
* Find/make better pamphlets

# Document the changes in your pull request

Ports https://github.com/tgstation/tgstation/pull/58146

* Mail boxes show up in cargo shuttle
* Mail has credits for the people addressed on the letter
* Mail can have job-dependent gifts too
* Cargo can deliver mail if they want or tell people to fetch it
* Some holidays are mail holidays, meaning no mail on them

# Wiki Documentation

Mail boxes show up on cargo shuttle
Cargo shuttle can't depart if mail is still on-board
Update Space Law to make opening other peoples' mail illegal?

# Changelog

:cl:  InariWhitebear, ArcaneMusic, Jaw-sh, Tralezab
rscadd: Mail for cargo
wip: This is work in progress  
imageadd: mail images and mail crate image
/:cl:

2021-12-20 23:14 UTC, Inari-Whitebear commented on code/controllers/subsystem/economy.dm
> +	mail_waiting += clamp(effective_mailcount, 1, MAX_MAIL_PER_MINUTE * 5)
Need to change this to MAX_MAIL_PER_MINUTE * 0.1

2021-12-20 23:27 UTC, Inari-Whitebear commented on code/game/objects/items/mail.dm
> +	update_icon_state()
change to update_icon

2021-12-20 23:28 UTC, Inari-Whitebear commented on code/game/objects/items/mail.dm
> +	update_overlays()
change to update_icon

2021-12-20 23:40 UTC, bruhlookatthisdood commented
I love this, always liked that system from TG and was sad when I moved to yog that it wasn't here.

2021-12-21 02:31 UTC, Marmio64 commented
some of the mail goodies look kind of insane, you can literally get a bolt action rifle as a cargo tech. Perhaps turn it down a little? For that specific example maybe an improvised shotgun instead.

2021-12-21 08:10 UTC, Inari-Whitebear commented
@Marmio64 
Yeah, for now I just copied the gifts. Balance is something to talk about though.

For that point, whether or not it changes your view, you should remember though, mail is a bit limited. The max amount of mail that should show up on the cargo shuttle is 3 per minute.

In addition the whole list for cargo tech is:
		/obj/item/stack/spacecash/c100 = 25,
		/obj/item/stack/spacecash/c200 = 15,
		/obj/item/stack/spacecash/c50 = 10,
		/obj/item/pizzabox = 10,
		/obj/item/stack/spacecash/c500 = 5,
		/obj/item/stack/sheet/mineral/gold = 5,
		/obj/item/stack/sheet/mineral/uranium = 4,
		/obj/item/stack/sheet/mineral/diamond = 3,
		/obj/item/stack/spacecash/c1000 = 1,
		/obj/item/gun/ballistic/rifle/boltaction = 1

For a normal mail one of those is picked, giving bolt action a 1.266% chance to be in the mail
Now there is a 30% chance that the specific mail spawns as an envelope, which has 2 items inside, so then it would be a little higher chance that at least one of them is the bolt action.
Not sure if that affects your view on the balancing of it, but just wanted to note it.

2021-12-21 09:51 UTC, Inari-Whitebear commented
Also not quite sure if to add a bunch of things from the gifts (such as bee cubes or caramel donuts) or find replacements

2021-12-22 00:32 UTC, bruhlookatthisdood commented
> Also not quite sure if to add a bunch of things from the gifts (such as bee cubes or caramel donuts) or find replacements

Give me my fucking donuts

2021-12-22 18:48 UTC, adamsong requested changes
Looks pretty good, a few minor comments. I would like to see this test merged to see how the playerbase handles it.

2021-12-22 18:48 UTC, adamsong commented on code/game/objects/items/mail.dm
> +		if(human.faction.Find("Station", 1, 0) != 0)
Not sure about wizards and nuke ops, but silicons don't have the Station faction, and therefore can be sent mail

2021-12-22 18:48 UTC, adamsong commented on code/game/objects/items/mail.dm
> +	SSeconomy.mail_waiting = 0
Do you intend for the mail to get reset to 0 even if the crate cannot hold the amount of waiting mail?

2021-12-22 18:48 UTC, adamsong commented on code/game/objects/items/mail.dm
> +		self_destruct.r_code = code
Confirm that the code isn't set first, this could really screw over nukies

2021-12-22 18:48 UTC, adamsong commented on code/game/objects/items/mail.dm
> +	info = "<i>You need to escape the simulation. Don't forget the numbers, they help you remember:</i> '[code[rand(1,5)]][code[rand(1,5)]]...'"
This gives 2 digits if the numbers are legit, and 3 if not, therefore allowing you to meta if your numbers are real. Is this intentional?

2021-12-22 20:50 UTC, Inari-Whitebear commented
Well since I can't seem to reply directly...
@adamsong 

"Not sure about wizards and nuke ops, but silicons don't have the Station faction, and therefore can be sent mail"
- Not sure what you mean here. "Don't have the Station faction and therefore can be sent mail", do you mean "can't be send mail"?
Also not sure about that either, I just saw code\modules\jobs\job_types\ai.dm listing faction = "Station"

2021-12-22 20:58 UTC, adamsong commented
Mail cannot be delivered to people with the Station faction, which according to the comment is supposed to be nukies, wizards, and silicons, however when I did VV on the AI, it did not have that faction. 
This is the factions on a borg:
![image](https://user-images.githubusercontent.com/4607006/147154333-e3403eb3-bae5-448f-b402-6c509ce91f0c.png)

2021-12-22 21:02 UTC, Inari-Whitebear commented
Oh, guess I screwed up the check anyway, should be "only deliver to Station faction"

2021-12-22 21:16 UTC, adamsong commented
Players are not the station faction though, you'll need to check the faction of the job

2021-12-23 05:50 UTC, adamsong commented
Also, I think you should re-enable SR for dead ian

2021-12-23 08:49 UTC, Inari-Whitebear commented
Yeah, thats currently disabled because it was like the other job gifts, still have to find the right paths and the like

2021-12-24 00:30 UTC, adamsong commented
Looking good, how ready is this for a test merge?

2021-12-24 08:48 UTC, Inari-Whitebear commented
Well it still lacks goodies for some of the jobs, and some of them are still commented out. Other than that it should be fairly ready... can only test it so much on a local server

Jobs without goodies:
* Artist
* Curator
* Head of Security
* Lawyer
* Shaft Miner

Jobs that don't have all their goodies yet:
* Security Officer
* Scientist
* Research Director
* Medical Doctor
* Detective
* Cook
* Clown
* Chief Engineer
* Chemist
* Captain
* Atmos Tech

2022-01-11 05:54 UTC, adamsong commented
Test merge went pretty good, some items spawn outside the crate, and there is a lot of mail

2022-01-11 11:00 UTC, ToasterBiome commented
1. Please let us send junk mail back, as eventually there's just crates full of junkmail. 
2. Boxstation disposals loop the envelopes, so they can't be disposaled. Not that I'd want to with 100+ spam envelopes i just want to jettison.
3. Parcels tagged with their departments send it to the actual disposals ejector... not  the departments.

2022-01-11 11:24 UTC, ToasterBiome commented on code/modules/clothing/head/hardhat.dm
> +/obj/item/clothing/head/hardhat/red/upgraded
This icon is missing

2022-01-11 19:24 UTC, adamsong commented
Fixed 2, which is a workaround for one, 3 fixed.

2022-01-11 20:10 UTC, adamsong requested changes
I fixed some of the major issues with the PR, here are some more minor ones though

2022-01-11 20:10 UTC, adamsong commented on code/modules/jobs/job_types/cargo_technician.dm
> +		/obj/item/pizzabox = 10,
This is empty

2022-01-11 20:10 UTC, adamsong commented on code/game/objects/items/mail.dm
> +		user.put_in_hands(contents[1])
Do you intend to just delete any other items in the mail (envelopes can spawn 2)

2022-01-11 20:10 UTC, adamsong commented on code/__DEFINES/economy.dm
> +#define MAX_MAIL_PER_MINUTE 3
315 mail per round is a lot

2022-01-12 01:34 UTC, ShattForte commented
Just played with this one.

I really like mail for cargo, it gives us something else to do. Although I do think the mailman needs a mailbag that can carry all mail.

Another thing that doesn't help is just how wonky and jank the mailing system is. Sometimes items just go straight through to the trash even though marked with a destination.

2022-01-14 03:15 UTC, ToasterBiome commented
I think mail bag and mailman clothes shouldn't be available in vending machines (not that mail bag is available now), and should exclusively be part of a cargo tech's loot items.

2022-01-21 09:15 UTC, Inari-Whitebear commented
Nice that people have been keeping this going a bit.

On mail routing: Hmm yeah, I didn't even know that was a thing when I started porting it, had only seen people deliver it manually. Will have to look into that.

Amount of mails: Can be adjusted. I think it has many mails since on some stations (or all?) I've seen that you don't actually get money automatically on your account. Instead all money you get is via mail. Making cargo a bit more important too.

2022-01-21 09:19 UTC, Inari-Whitebear commented
Empty pizzas: Hmm interesting, I don't really see why it would be non-empty on TGStation proper either. Maybe an oversight no one ever bothered to fix.
Should there be a chance that those pizzas are bombs?

2022-01-21 10:02 UTC, Inari-Whitebear commented
Not sure if this was due to the fix already made, but junk mail can be sent to actual disposals where the recycling machine takes care of it. Alternatively you can unwrap and burn it.
The crates can be turned into iron sheet with a welding tool.

2022-01-22 19:34 UTC, Inari-Whitebear commented
Another thing to look into is that I've seen some stations a TG base have disposals specifically more mail it appears.
So in Cargo you have a disposal chute for Security, for Science, etc, that just chucks the mail straight to that department.
Would that be desired here?

You can always tag mail instead too of course for the normal sorting.

2022-01-22 19:46 UTC, ShattForte commented
> 

I'd be more than willing to try it out and give my input. One issue with the mail system that a lot of people fail to understand (because it's borked) is when you have a bunch of mail sorted for different destinations occupying the same tile as it goes into disposals, they will all end up in the same location (have to put mail in one at a time).

2022-01-22 21:17 UTC, PotatoTomahto commented
I'm not too sure if I'm right, but it seems that each mail crate has mail for every crew member, which drastically increases the volume that cargo needs to deal with. It also seems unrealistic that the station is receiving that much mail. Perhaps you could a timer that generates mail for a random crew member so back-to-back shuttle calls don't just create a ton of mail?

2022-01-23 09:44 UTC, Inari-Whitebear commented
Amount of mail should be better now
I apparently did a dumb on the calculation for how much mail should be waiting....

As far as I understand this fires every 5 minutes... before it would take that in the wait time (5 MINUTES, which is 5 * 60 * 10 or 3000) and do 3000 * 0.2.. so it would add 600 waiting mails every 5 minutes

Fixed it to be accurate.. so now it should be 15 mails per 5 minutes

2022-02-21 23:58 UTC, ToasterBiome commented
Suggestions for mail (since getting credits is lame)

Engineering: Higher tier charged cells (not bluespace)
Science: Slime Mutation Potions/Slime Stability Potions, maybe some T3/T4 parts occasionally
Chemist/CMO: Small amounts of Lemoline
Cargo Tech: small amount of plastic

2022-02-22 07:45 UTC, Inari-Whitebear commented
Yeah, getting credits is a bit more useful when they are your only source of credits - like on some stations I've seen.

Goodies are definitely more exciting.

2022-04-01 02:17 UTC, ToasterBiome commented
@Inari-Whitebear any work on this?

2022-04-01 07:07 UTC, Inari-Whitebear commented
Well, I've asked questions. I've not gotten answers yet. So no work currently.
I like your suggestions too, but without any other input, no idea if they'd even be accepted balance-wise or the like.

2022-05-14 15:29 UTC, TheGamerdk commented
Feel free to open a new PR when you figure out the problems :)

2022-05-14 15:29 UTC, closed without merging