Adds lesser sentience potion as an uplink item (traitor)
yogstation13/Yogstation pull request #12966
Opened 2021-12-22 22:40 UTC by ToasterBiome

# Document the changes in your pull request

Funny things happen with sentient antagonist creatures

adds a lesser sentience potion to the uplink for normal traitors. 12 TC, no implant, no access card. It's so high so people play with the gimmick of "sentient creature will help with objectives" instead of a tc tax 

# Wiki Documentation

new uplink item

# Changelog

:cl:  
rscadd: lesser syndicate sentience potion added
/:cl:

2021-12-22 22:42 UTC, ynot01 commented
12 fucking TC??

2021-12-22 22:43 UTC, ToasterBiome commented
> 12 fucking TC??

yes. if you're buying this you better have a good idea what to use it on as this will be your gimmick for the round.

2021-12-22 22:44 UTC, Sniblet commented
Ah yes most of my budget today will go into buying a pet goliath that no ghost wants to play as and whose tentacles will not actually work and which will die permanently as soon as security finds out that light pinks haven't been bred yet

2021-12-22 22:50 UTC, ToasterBiome commented
> Ah yes most of my budget for this week's antag roll will go into buying a pet goliath that no ghost wants to play as and whose tentacles will not actually work and which will die permanently as soon as security finds out that light pinks haven't been bred yet

don't buy it if you're gonna use it on a goliath


reduced to 7 tc because ynot bullied me

2021-12-23 02:58 UTC, adamsong requested changes

2021-12-23 02:58 UTC, adamsong commented on code/modules/uplink/uplink_items.dm
> +	cost = 7
Reduce this

2021-12-24 04:16 UTC, KittyNoodle commented
7 tc is still way too much

2021-12-29 04:40 UTC, Marmio64 commented
should be 2 TC at most. the whole strength of using simple mobs to do your bidding is that they're weak alone but expendable and strong in numbers. A price of 7 TC with a limit of one makes them neither expendable or plentiful, and for the price of 7 TC you can just get a fuckin mindslave implant instead, which will get you something 5x as strong, someone who can pick up some weapons and kill people.

2022-02-02 22:07 UTC, JamieD1 approved these changes

2022-02-02 22:07 UTC, merged