more useless ashwalker crap, like candles and a bonecoat
yogstation13/Yogstation pull request #12991
Opened 2021-12-26 19:34 UTC by Marmio64

Adds tribal coat, medicinal pouch, and resin candles. Tribal coat and medicinal pouch sprites from fallout13 codebase.
Allows you to clean leather via the crafting menu with water. Adds hunter's belt to the crafting menu, made with 4 sinew. Goliath cloak armor values buffed to bone armor values.

Tribal coat armor values are bone armor but 10 less melee and doesn't protect against sharp objects touching the feet (like cacti), and costs 2 leather and 1 bone.
Resin candle is a normal candle but it lasts twice as long, is extra thick, and is orange.
Medicinal pouch can hold a lot of plants, pestles, resin, and poultices.
Hunter belt was already in the game but was uncraftable, it is the same as miner's webbing with one less slot, and costs 4 sinew.
Also adds info to the tome of herbal knowledge about leather, since some people might not know how the process works.

# Wiki Documentation

Tribal coat armor values are bone armor but 10 less melee and doesn't protect against sharp objects touching the feet (like cacti), and costs 2 leather and 1 bone.
Resin candle is a normal candle but it lasts twice as long, is extra thick, and is orange.
Medicinal pouch can hold a lot of plants, pestles, resin, and poultices.
Hunter belt was already in the game but was uncraftable, it is the same as miner's webbing with one less slot, and costs 4 sinew.

# Changelog

:cl:  
rscadd: Adds tribal coat, medicinal pouch, and resin candles. Tribal coat and medicinal pouch sprites from fallout13 codebase.
tweak: Allows you to clean leather via the crafting menu with water. Adds hunter's belt to the crafting menu, made with 4 sinew. Goliath cloak armor values buffed to bone armor values. New knowledge added to TOME OF HERBAL KNOWLEDGE.
/:cl:

2021-12-29 16:51 UTC, grimm-hollowknight requested changes
your object sprite has 4 states

2021-12-29 21:17 UTC, Marmio64 commented
> your object sprite has 4 states

fixed

2021-12-30 02:19 UTC, ToasterBiome requested changes

2021-12-30 02:19 UTC, ToasterBiome commented on code/game/objects/items/storage/bags.dm
> +/obj/item/storage/bag/chemistry/ComponentInitialize()
```suggestion
/obj/item/storage/bag/medpouch/ComponentInitialize()
```

i assume you want to initialize the medpouch and not a chemistry bag

2022-01-02 16:44 UTC, grimm-hollowknight approved these changes

2022-01-04 18:51 UTC, JamieD1 approved these changes

2022-01-04 18:51 UTC, merged