moves sci wardrobe vending machine from toxins room to experimentor room
yogstation13/Yogstation pull request #13049
Opened 2022-01-05 22:23 UTC by ToasterBiome

# Document the changes in your pull request

although experimentor room still has a higher than normal chance to explode, it will not in 70% of shifts while toxins will be spaced within the first 15 minutes on 70% of shifts. 

this of course comes with the removal of a single paper bin in experimentor which was vital to gameplay and thus changes the balance of the entire game

![image](https://user-images.githubusercontent.com/5091394/148297791-6f350ee3-73ed-4b82-8701-64c0a802b2b4.png)

also gives toxins another air pump (power creep) 

# Wiki Documentation

image has to be changed

# Changelog

:cl:  
rscadd: add an extra air pump to toxins
rscdel: remove table and paper bin (REQUIRED!!!!) from experimentor room
tweak: moved sci wardrobe vending machine to experimentor room
/:cl:

2022-01-09 20:42 UTC, wejengin2 requested changes
Please don't remove the paper bin, just move it to the tables that remain.

2022-01-10 16:35 UTC, Moja10 commented
Downright evil you would remove that paper bin

2022-01-12 17:47 UTC, JamieD1 commented
How dare you remove that paperbin

2022-01-13 12:06 UTC, ToasterBiome commented
![image](https://user-images.githubusercontent.com/5091394/149327418-67d3ea24-c107-4d93-91dc-8d402d1810fb.png)

readds paper bin below the JUNK ON THE TABLE

2022-01-14 11:55 UTC, wejengin2 approved these changes
The integrity of Yogstation mapping is safe now

2022-01-14 11:55 UTC, merged