Adds a ritual to summon a portal storm to the spellbook!
yogstation13/Yogstation pull request #13074
Opened 2022-01-10 03:33 UTC by Xoxeyos

# Document the changes in your pull request

You can now summon portal storms as a wizard! It's a single use, three point buy cost. Shocktroopers and constructs can be chosen to be spawned.

# Wiki Documentation

Wizards can now summon portal storms using their spell book, in the ritual section!

# Changelog

Wizards can now summon portal storms using their spell book, in the ritual section! It's a single use spell, and uses 3 spell points.

:cl:  Xoxeyos, Arcturus-Prime
rscadd: Wizards can now summon portal storms using their spell book, in the ritual section!
/:cl:

2022-01-10 08:24 UTC, ToasterBiome requested changes
Other than that looks good.

2022-01-10 08:24 UTC, ToasterBiome commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +    var/portaltype = pick(50;"port_shocktroop",50;"port_narsiespawn")
```suggestion
    var/portaltype = pick("port_shocktroop","port_narsiespawn")
```

NO WEIRD SYNTAX HERE

If you want to add more storms with altering chances if this PR gets merged then do so when you are making the new storms. [YAGNI](http://wiki.c2.com/?YouArentGonnaNeedIt).

2022-01-10 08:38 UTC, ToasterBiome approved these changes

2022-01-12 17:54 UTC, JamieD1 approved these changes
Will see if its abused.. raging maging.. oh god.

2022-01-12 17:54 UTC, merged