More cybernetic organs and additional organ functions
yogstation13/Yogstation pull request #13089
Opened 2022-01-13 11:58 UTC by SomeguyManperson

# Document the changes in your pull request

adds "organ efficiency", a modifier for how strong an organ is in generic organ-related activities (i.e. lung breath intervals, heart blood regen)
gives higher organ efficiency to several upgraded cybernetic organs, alongside with the generic organ-related activities it does stuff with
adds ghetto craftable organs, currently just the lungs and heart, which have lower max health and organ efficiency
adds cybernetic stomachs and ears
redoes the sprite for the cybernetic heart and makes it actually beat
switches the nanite heart to use the nanite organ icon because I'd really rather keep the xeno heart icon for stuff
halves the random deafness from ear damage since 8 seconds of deafness that can stack is stupid, likely to be replaced later if I can manage it

adds crobar lungs

new cybernetic heart and ghetto heart beating:

https://user-images.githubusercontent.com/24857008/149325020-22b1331c-1d0d-4add-87e9-94059c51dfad.mp4

alternatives for the cybernetic heart:

https://user-images.githubusercontent.com/24857008/149325159-7161dd58-e19a-4af8-9924-cbb3a7dbfaad.mp4

# Wiki Documentation

hearts now impact blood regeneration, with a more damaged heart regenerating less
lungs are now the sole impactor of breath speed, with damaged lungs reducing the time between breaths and decreasing oxygen regen from successful ones
upgraded cybernetic lungs and hearts are 50% more effective than baseline ones at the new things they do
lungs can be extended with a crowbar, this doubles the amount they need to breathe but also doubles their efficiency
cybernetic stomachs have been added
upgraded cybernetic stomachs can store up to 8 nutriment when well fed, this is returned if you get hungry
cybernetic ears have been added, they take 20% less damage from things cat ears take 100% more from (probably loud noises)

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: the heart and lungs now work slightly less well when damaged at regenerating blood and breathing respectively
rscadd: upgraded cybernetic hearts and lungs are now slightly better at doing ^
bugfix: cybernetic hearts now beat properly
rscadd: cybernetic stomachs and ears
rscadd: ghetto hearts and lungs crafted from stuff in maintenance, you aren't actually going to put that in yourself, are you?
rscadd: you can now give people lung extensions, or rather extend lungs, with a crowbar
rscdel: random deafness from ear damage has been cut in half
/:cl:

2022-01-13 21:50 UTC, KillerOrcaCora commented
This is pure insanity and I love it!

2022-01-13 22:50 UTC, Hopekz requested changes

2022-01-13 22:50 UTC, Hopekz commented on code/modules/surgery/organs/heart.dm
> +	desc = "An electronic device designed to mimic the functions of an organic human heart. Fitted with a blood synthesizer, it also holds an emergency epinepherine synthesizer that supplies a dosage if
```suggestion
	desc = "An electronic device designed to mimic the functions of an organic human heart. Fitted with a blood synthesizer, it also holds an emergency epinephrine synthesizer that supplies a dosage if the body is critically damaged."
```

2022-01-13 22:50 UTC, Hopekz commented on code/modules/surgery/organs/lungs.dm
> +	desc = "A pair of oxygen tanks which have been attached to a modular (oxygen) reciever. They are incapable of supplying air, but can work as a replacement for lungs."
```suggestion
	desc = "A pair of oxygen tanks which have been attached to a modular (oxygen) receiver. They are incapable of supplying air, but can work as a replacement for lungs."
```

2022-01-18 19:15 UTC, grimm-hollowknight approved these changes

2022-01-26 18:50 UTC, merged