footwraps now go tap tap tap
yogstation13/Yogstation pull request #13112
Opened 2022-01-16 01:10 UTC by cuackles

# Document the changes in your pull request

Footwraps now do the barefoot sound cus most of the feet that is touching the floor its not covered by the wrap done almost entirely by mqiib
# Changelog

footwraps now do the barefoot sound 

:cl:    
tweak: tweaked a few things  
/:cl:

2022-01-26 18:55 UTC, JamieD1 commented
I mean this doesnt make sense "Most of the foot is not touching the ground" then why does it stop tables and glass? You are opening a can of worms hear, however I will settle if the sound is half as loud as the bare foot one.

2022-02-03 21:16 UTC, Mqiib commented
> I mean this doesnt make sense "Most of the foot is not touching the ground" then why does it stop tables and glass? You are opening a can of worms hear, however I will settle if the sound is half as loud as the bare foot one.

Lizards actually have a different sound than humans when barefoot, being the claws hitting the floor rather than the whole foot slapping down. Footwraps don't totally cover the claws so it'd make sense that they would still be heard while walking. There's no reason for them to be muted at all, and the way it works currently wearing footwraps makes it sound like you're walking around in heavy boots which makes even less sense than what this pr does. As for the glass argument, the soft parts of the foot are still covered while the claws, which are hard and not particularly sensitive, are the only things that would come in contact with the glass.

2022-02-12 17:02 UTC, JamieD1 commented
> > I mean this doesnt make sense "Most of the foot is not touching the ground" then why does it stop tables and glass? You are opening a can of worms hear, however I will settle if the sound is half as loud as the bare foot one.
> 
> Lizards actually have a different sound than humans when barefoot, being the claws hitting the floor rather than the whole foot slapping down. Footwraps don't totally cover the claws so it'd make sense that they would still be heard while walking. There's no reason for them to be muted at all, and the way it works currently wearing footwraps makes it sound like you're walking around in heavy boots which makes even less sense than what this pr does. As for the glass argument, the soft parts of the foot are still covered while the claws, which are hard and not particularly sensitive, are the only things that would come in contact with the glass.

What about the other species, its not all about lizards you know?

2022-02-12 17:28 UTC, cuackles commented
> > > I mean this doesnt make sense "Most of the foot is not touching the ground" then why does it stop tables and glass? You are opening a can of worms hear, however I will settle if the sound is half as loud as the bare foot one.
> > 
> > Lizards actually have a different sound than humans when barefoot, being the claws hitting the floor rather than the whole foot slapping down. Footwraps don't totally cover the claws so it'd make sense that they would still be heard while walking. There's no reason for them to be muted at all, and the way it works currently wearing footwraps makes it sound like you're walking around in heavy boots which makes even less sense than what this pr does. As for the glass argument, the soft parts of the foot are still covered while the claws, which are hard and not particularly sensitive, are the only things that would come in contact with the glass.
> 
> What about the other species, its not all about lizards you know?

It also affects polys and anyone who uses footwraps that are usable by all species as far as I understand

2022-02-14 21:23 UTC, tattax commented
(ignore that)

2022-02-14 22:27 UTC, Mqiib commented
> > > I mean this doesnt make sense "Most of the foot is not touching the ground" then why does it stop tables and glass? You are opening a can of worms hear, however I will settle if the sound is half as loud as the bare foot one.
> > 
> > 
> > Lizards actually have a different sound than humans when barefoot, being the claws hitting the floor rather than the whole foot slapping down. Footwraps don't totally cover the claws so it'd make sense that they would still be heard while walking. There's no reason for them to be muted at all, and the way it works currently wearing footwraps makes it sound like you're walking around in heavy boots which makes even less sense than what this pr does. As for the glass argument, the soft parts of the foot are still covered while the claws, which are hard and not particularly sensitive, are the only things that would come in contact with the glass.
> 
> What about the other species, its not all about lizards you know?

Footwraps aren't heavy shoes so they shouldn't make heavy boot noises when you're walking around.

2022-02-16 23:52 UTC, JamieD1 approved these changes

2022-02-16 23:52 UTC, JamieD1 commented on code/datums/components/footstep.dm
> +
```suggestion
```

2022-02-18 08:54 UTC, Mqiib commented
![image](https://user-images.githubusercontent.com/43766432/154649808-18fc5f8d-89d6-4af1-9032-f2674b28ccc6.png)

Shouldn't it be like 
> if((H.shoes && !istype(yadda yadda)) || feetcover) 
since this would be "If shoes and they aren't footwraps OR feet are covered" instead of "If shoes or feet are covered AND shoes are not footwraps" and would avoid possible runtimes when they dont have shoes but have their feet covered?

2022-02-25 14:38 UTC, JamieD1 commented
> ![image](https://user-images.githubusercontent.com/43766432/154649808-18fc5f8d-89d6-4af1-9032-f2674b28ccc6.png)
> 
> Shouldn't it be like
> 
> > if((H.shoes && !istype(yadda yadda)) || feetcover)
> 
> since this would be "If shoes and they aren't footwraps OR feet are covered" instead of "If shoes or feet are covered AND shoes are not footwraps" and would avoid possible runtimes when they dont have shoes but have their feet covered?

You are correct.

2022-03-03 08:34 UTC, ToasterBiome requested changes
@JamieD1 Naughty jamie, now it doesn't build

2022-03-07 11:17 UTC, JamieD1 commented
> @JamieD1 Naughty jamie, now it doesn't build

Forgot a )

2022-03-10 00:31 UTC, ToasterBiome approved these changes

2022-03-10 00:32 UTC, ToasterBiome commented
if this doesn't work it's jamie's fault

2022-03-10 00:32 UTC, merged