Janitor maid dress resprite! ~Flowering Night edition~
yogstation13/Yogstation pull request #13190
Opened 2022-01-30 03:55 UTC by KillerOrcaCora

Resprites the janimaid uniform into a maid outfit inspired by the time-stopping knife-throwing head maid Sakuya Izayoi from Embodiment of Scarlet Devil.

# Wiki Documentation
Might have to switch a png

# Changelog

:cl:  
 
imageadd: Resprites Janimaid uniform 

https://user-images.githubusercontent.com/82983051/151686021-4fc15d68-0b38-4411-acd1-8320c52b5d5a.mp4

/:cl:

2022-01-30 04:02 UTC, cuackles commented
i would say delete the multiple acounts of janimaid dmi and png that arent in use

2022-01-30 17:01 UTC, cuackles requested changes
![image](https://user-images.githubusercontent.com/68789204/151709329-b4a68b6d-85c8-4f32-9a10-056340614cb7.png)
i bealive this files arent being used and probably should be deleted

2022-02-02 18:41 UTC, JamieD1 commented
@Ident

2022-02-04 19:01 UTC, grimm-hollowknight approved these changes

2022-02-04 19:01 UTC, merged