PORTS NSV POOLS FOR REALSIES THIS TIME
yogstation13/Yogstation pull request #13250
Opened 2022-02-09 20:56 UTC by maxion12345

had to just delete the other branch shit was turbofucked my man

todo
- [ ] snip
snip
- [x] Throw people into pools
currently the pool acts like an invisible wall and you will be stopped
# Document the changes in your pull request
Port of https://github.com/BeeStation/BeeStation-Hornet/pull/3160

Adds pools from NSV13, replacing the boxing rings on each station. The holodeck's boxing ring is bigger and more sexy looking anyways. 
# Wiki Documentation
update photo

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  PowerfulBacon, KMC, Cdey, Maxim
rscadd: Added pool to boxstation
/:cl:

2022-02-09 21:38 UTC, wejengin2 commented on code/modules/pool/pool_items.dm
> +	name = "inflateable ring"
inflateable? not inflatable?

2022-02-09 21:38 UTC, patpol4 commented on code/modules/pool/pool_items.dm
> +	desc = "An inflateable ring used for keeping people afloat. Throw at drowning people to save them."
here too

2022-02-09 21:41 UTC, wejengin2 requested changes
Double pipe on box here:
![firefox_719bX3f27k](https://user-images.githubusercontent.com/48154165/153294561-1293d843-5830-476c-822d-04d4bf3eb3b1.png)

For meta:
![firefox_nKx3GGclBE](https://user-images.githubusercontent.com/48154165/153294595-aa163ec6-f886-4e3f-8015-2cfe6b127895.png)
Fix the pointless T junction, 
check for duplicates, 
move the line one to the left so its not so close to the pool
move the table so it's not right next to the pool, also maybe chairs? idk might change those later if it's bad ingame

Also move assistant spawns on both maps a bit so they dont spawn right next to the pools and instantly fall in there by accident.

2022-02-10 02:23 UTC, maxion12345 commented
> Double pipe on box here: ![firefox_719bX3f27k](https://user-images.githubusercontent.com/48154165/153294561-1293d843-5830-476c-822d-04d4bf3eb3b1.png)
> 
> For meta: ![firefox_nKx3GGclBE](https://user-images.githubusercontent.com/48154165/153294595-aa163ec6-f886-4e3f-8015-2cfe6b127895.png) Fix the pointless T junction, check for duplicates, move the line one to the left so its not so close to the pool move the table so it's not right next to the pool, also maybe chairs? idk might change those later if it's bad ingame
> 
> Also move assistant spawns on both maps a bit so they dont spawn right next to the pools and instantly fall in there by accident.

done, I moved that uniform on the table over to where the cups used to be (you can get cups from the water machine idk why they had a table)

2022-02-10 10:56 UTC, wejengin2 approved these changes
Map is fine

2022-02-10 10:57 UTC, wejengin2 commented
previous PR https://github.com/yogstation13/Yogstation/pull/13114

2022-02-10 16:39 UTC, grimm-hollowknight approved these changes

2022-02-12 18:28 UTC, merged