PDA starts in ID slot
yogstation13/Yogstation pull request #13270
Opened 2022-02-13 01:06 UTC by SapphicOverload

# Document the changes in your pull request

Say goodbye to this minor inconvenience, and hours of my life.
The PDA will now start in the ID slot with the ID already inserted. Works with most playable jobs. Has been tested.

# Wiki Documentation

No changes needed.

# Changelog

:cl:  
tweak: pda now starts in the id slot with the id inserted for most playable jobs.
/:cl:

2022-02-13 06:21 UTC, KillerOrcaCora commented
Good Pr you are an angel.

2022-02-13 10:06 UTC, wejengin2 commented
Hugbox

2022-02-13 21:27 UTC, onepunchronan commented
Two clicks saved every round. That shit adds up.

2022-02-17 00:13 UTC, JamieD1 commented
Make it a preference, can help with it.

2022-02-17 15:28 UTC, bruhlookatthisdood commented
halelughija

2022-02-25 14:52 UTC, JamieD1 commented
You are forcing the ID slot to have the PDA on almost all the jobs, It would be alot easier if you just left it all as default and then ran the slot id into pda if the preference is there and then move the pda to the id slot.

2022-02-25 16:05 UTC, JamieD1 commented
Everyone with this enabled got an ID in a PDA, however no ID if the pref is disabled.

Please test and try again.

2022-03-08 00:56 UTC, adamsong commented
No one spawned with ids or pda

2022-03-08 02:06 UTC, nmajask requested changes

2022-03-08 02:06 UTC, nmajask commented on code/modules/jobs/job_types/_job.dm
> +		if (H.client.prefs.id_in_pda)
This won't work, clients are transferred after the client is equipped on round-start characters due to some messed up code. You can sidestep this by adding a var to the humans and assigning the value of that var for player's character equal to their preference. Basically, copy what skirt prefs did, as that works.

2022-03-08 02:44 UTC, nmajask requested changes
Revert the changes to yarn

2022-03-08 02:52 UTC, SapphicOverload commented
> No one spawned with ids or pda

@adamsong i fixed it

2022-03-14 00:37 UTC, ToasterBiome commented
Mining medic was missing their ID, fixed I think

2022-03-14 03:45 UTC, nmajask submitted a review, later dismissed
Revert the changes to the horror files

2022-03-18 02:17 UTC, ToasterBiome commented
Haven't seen any other bugs with it, @JamieD1 ready to merge?

2022-03-18 06:12 UTC, ToasterBiome requested changes
For some reason, IDs don't start with their modular access ie department engineers dont have access to their department, might be something about this PR

2022-03-21 05:21 UTC, nmajask reviewed
In the security officer and station engineer files on lines 109 and 82 respectively, you can either use GetID() on the item in the wear_id slot or use get_idcard() on the mob to get the actual ID which would fix ToasterBiome's issue

2022-03-27 11:39 UTC, JamieD1 approved these changes

2022-03-27 12:33 UTC, JamieD1 commented on code/modules/jobs/job_types/_job.dm
> +
```suggestion
```

2022-03-29 10:01 UTC, ToasterBiome submitted a review, later dismissed
People show up twice on PDA sometimes and I think this has something to do with it, will be looking in the coming days for anyone with dual-pda syndrome.

2022-04-03 12:15 UTC, JamieD1 commented
> People show up twice on PDA sometimes and I think this has something to do with it, will be looking in the coming days for anyone with dual-pda syndrome.

Find anything?

2022-04-03 12:16 UTC, JamieD1 approved these changes

2022-04-03 12:17 UTC, merged