Donator Preference for Valentines
yogstation13/Yogstation pull request #13276
Opened 2022-02-14 12:47 UTC by JamieD1

Donators can now opt out of Valentines events

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Opt out for Valentines for Donators

2022-02-14 12:49 UTC, wejengin2 commented
Literally just reject the date, this is a nonissue imo.
Might lead to people disabling this and skipping the forced player interaction thus reducing rp.

2022-02-14 12:49 UTC, JamieD1 commented
> 

"forced player interaction"

2022-02-14 12:52 UTC, patpol4 commented
hugbox

2022-02-14 13:17 UTC, TheGamerdk commented
Why the fuck is this only for donators?

2022-02-14 13:22 UTC, Tipy1802 commented
No fun allowed. The grinch is here to take away our holiday spirit because he has no valentine

2022-02-14 13:45 UTC, JamieD1 commented
Changed to All players

2022-02-14 13:47 UTC, bruhlookatthisdood commented
> Changed to All players

now i can be lonley in peace

2022-02-14 15:44 UTC, Darkstick commented
Hard no.
Forcing regulars out of their comfort zone is the fun part of the valentine's event.
You either deal with your valentine, or find something fun to do with your valentine. It does not matter if it disrupts your round, you should embrace unexpected happenings and find creative solutions, because that's what SS13 is all about.

2022-02-14 19:12 UTC, Xoxeyos commented
I could go either way with this, but I believe AIs and Cyborgs shouldn't have the ability to obtain the valentine antag datum.
As per usual, the AI/cyborg must prioritize their laws over any secondary objective, or so I've been told. It really doesn't leave much room for the actual what may be brief, interactions with your valentine. You could also say that AIs/Cyborgs are unfeeling machines, but that doesn't really hold up for some players, so this last sentence is just food for thought.

All in all, it's hard to interact with your valentine as a silicon unit during a busy round, where we usually have a sustained pop of 40 to 50 players per day, while juggling your law set, and this "Protect "X", your valentine!".

2022-02-15 20:51 UTC, Moja10 commented
There is literally no rule or code that says you have to do anything different during valentine's event, you can tell your date to pound sand. Why make a preference for something already ignorable, other than being miserly and seeing redtext instills deep trauma

2022-02-16 20:44 UTC, optimumtact commented
play 2 win

2022-02-16 23:11 UTC, TheGamerdk requested changes

2022-02-16 23:11 UTC, TheGamerdk commented on code/modules/client/preferences.dm
> +			dat += "<b>Toggle Valentines Events:</b> <a href='?_src_=prefs;preference=donor;task=valentines'>[valentines ? "Yes" : "No"]</a><BR>"
Ambiguous language.
Toggle it what? On? Off? Could be either with this wording

2022-02-16 23:11 UTC, TheGamerdk commented on code/modules/client/preferences.dm
> +				if("valentines")
hidden inside is_donator block.

2022-02-16 23:11 UTC, TheGamerdk commented on code/modules/events/holiday/vday.dm
> +			if(M.client.prefs.valentines == TRUE)
```suggestion
			if(!M.client.prefs.valentines)
```
Assume FALSE = not participating

2022-02-17 13:52 UTC, ghost commented
This should be merged. The ability to opt in or out optimizes which type of players are engaging in this RP concept, making the experience better for those who want RP. Furthermore, players should have the choice to play the game how they want to.

Moja puts it as “oh you can just tell them to pound sand”, but in this scenario the interaction ends there for the player who wants to RP.

Encouraging players to leave their comfort zone is horseshit. This is not how it works in reality. I believe people should be allowed to play as they want to so long as it is not interfering with the enjoyment of others. If anything, not having an opt out is detrimental to others enjoyment by reducing the likelihood of “good” RP.

I am always surprised by the urge of people who play quite infrequently to have players RP. The point of this game is to have fun. Fun does not necessarily mean you are engaging in roleplay, it can come in many forms. Furthermore, forcing players to engage in RP while still existing in a low to no rp environment is by no means enjoyable. We either go all the way with RP (which didn’t work, remember?) or stop these stupid antics and focus on bettering the experience of players by offering them a wide variety of ways to play the game.

To put it simply, you can’t have your cake and eat it too.

On a final note, this shouldn’t even be up to discussion. A button to decide whether or not to engage in an antagonist/irregular role is a familiar concept to SS13.

Forcing players to engage in anything is draconian and represents how militant some community members have gotten about their obsession with “roleplay”.

2022-02-17 19:46 UTC, optimumtact commented
you sound like fun at parties.

2022-02-18 16:03 UTC, Moja10 commented
Being rejected from a date is RP

2022-02-18 16:05 UTC, Moja10 commented
![1984](https://user-images.githubusercontent.com/17183762/154718483-1589f8b7-c71a-4c25-a203-d4f687f8267b.gif)
You will be banned for not engaging in Valentines date RP

2022-02-19 21:16 UTC, TheGamerdk commented
> you sound like fun at parties.

spoiler: he isn't

2022-02-21 23:33 UTC, SomeguyManperson commented
Wtf happened here

2022-02-22 03:34 UTC, onepunchronan commented
> Wtf happened here

just yogs tingz

2023-01-26 21:02 UTC, wejengin2 commented
Just wanted to say that after giving it some thought i fully support this now. This is not a joke, i actually think this should be merged.

2023-01-26 21:16 UTC, Moja10 commented
There is literally no rule or code that says you have to do anything different during valentine's event, you can tell your date to pound sand. Why make a preference for something already ignorable, other than being miserly and seeing redtext instills deep trauma

2023-01-26 23:57 UTC, JamieD1 commented
> There is literally no rule or code that says you have to do anything different during valentine's event, you can tell your date to pound sand. Why make a preference for something already ignorable, other than being miserly and seeing redtext instills deep trauma

Because people are not emotionless twats

2023-01-27 14:29 UTC, MajManatee commented
finally, legal erp

2023-01-27 15:54 UTC, MajManatee commented
or you know, dont play the game for 24 hours. Believe it or not the world wont end.

2023-01-27 15:56 UTC, Moltijoe commented
something like this being an option does seem preferrable

2023-01-28 04:20 UTC, optimumtact commented
add this, but it transfers you to tgstation terry with all the other humans afraid of talking to other people

2023-01-28 16:03 UTC, closed without merging

2023-01-28 16:06 UTC, wejengin2 commented
#17682