Ports TGs admin only supermatter spiders
yogstation13/Yogstation pull request #13288
Opened 2022-02-17 01:00 UTC by Xoxeyos

# Document the changes in your pull request

Created by [capsaicinz](https://github.com/capsaicinz); Adds little creatures that will aggressively hunt down a target and dust it, killing itself in the process. tend to enjoy hunting in swarms, for sport mostly.

# Changelog

Adds admin-spawn only Super Matter spiders. Horrifying, yet hilarious. Created by capsaicinz.

:cl: capsaicinz, Xoxeyos
rscadd: Adds supermatter spiders.
/:cl:

2022-02-17 01:34 UTC, KillerOrcaCora commented
Sponsored and brought to you by capsaicinz

2022-02-17 02:12 UTC, adamsong requested changes, later dismissed
Add a way to spawn them

2022-02-17 16:14 UTC, KittyNoodle commented
Adam you know you can just use the game panel’s spawn mob right

2022-02-18 12:04 UTC, grimm-hollowknight approved these changes

2022-02-19 08:39 UTC, Xoxeyos commented
> Add a way to spawn them

Going to start working on it now.

2022-02-25 15:05 UTC, JamieD1 commented
Dusting is one of the only ways you cant be revived from.

Im not sure if admins can control themselves, can test it.

2022-03-02 16:04 UTC, Xoxeyos commented
> Add a way to spawn them

Done, I guess I forgot to build it.

2022-03-07 11:13 UTC, JamieD1 commented
Add this to a smite, this should be used VERY rarely

2022-03-13 11:08 UTC, JamieD1 commented
> Add this to a smite, this should be used VERY rarely

You thumbs up'd it but didnt do what I suggested :D

2022-03-25 10:27 UTC, ToasterBiome commented
@Xoxeyos

2022-03-28 03:56 UTC, Xoxeyos commented
> @Xoxeyos

Finishing it up soon, I've been busy this past week.

2022-03-28 08:05 UTC, ToasterBiome approved these changes

2022-03-28 08:05 UTC, ToasterBiome commented on code/modules/admin/verbs/randomverbs.dm
> +			var/confirm = alert(usr, "Dust target with a spider?", "Confirm? There is no chance of revival!", "Yes", "No")
```suggestion
			var/confirm = alert(usr, "Dust target with a spider? There is no chance of revival!", "Supermatter Spider", "Yes", "No")
```

2nd argument is the question, third is the title of the window that pops up.

2022-03-28 08:05 UTC, ToasterBiome commented on code/modules/admin/verbs/randomverbs.dm
> +			var/list/FOVlist = oview(target,5)
```suggestion
			var/FOVlist = circleviewturfs(target,5)
```

2022-03-28 08:05 UTC, ToasterBiome commented on code/modules/admin/verbs/randomverbs.dm
> +			var/list/FOVTurflist = new/list()
```suggestion

```

2022-03-28 08:05 UTC, ToasterBiome commented on code/modules/admin/verbs/randomverbs.dm
> +			for(var/turf/open/item in FOVlist)
```suggestion

```

2022-03-28 08:05 UTC, ToasterBiome commented on code/modules/admin/verbs/randomverbs.dm
> +				FOVTurflist.Add(item)
```suggestion

```

2022-03-28 08:05 UTC, ToasterBiome commented on code/modules/admin/verbs/randomverbs.dm
> +			var/turf/open/OV = pick(FOVTurflist)
```suggestion

```

2022-03-28 08:05 UTC, ToasterBiome commented on code/modules/admin/verbs/randomverbs.dm
> +			var/mob/living/loser/ = new /mob/living/simple_animal/hostile/smspider(OV)
```suggestion
			var/mob/living/simple_animal/hostile/smspider/spider = new /mob/living/simple_animal/hostile/smspider(pick(FOVlist)
```

2022-03-28 08:05 UTC, ToasterBiome commented on code/modules/admin/verbs/randomverbs.dm
> +			loser.attack_animal(target)
```suggestion
			spider.GiveTarget(target)
```

2022-03-28 08:05 UTC, ToasterBiome requested changes
fuck i pressed the wrong button

2022-03-28 08:33 UTC, Xoxeyos commented
> Add a way to spawn them

done, the prioritize the target, ignore non-targets, and if stuck in  5x5 walls with a hole in the center they prioritize the center, then cardinals, and then diagonals

2022-03-28 08:34 UTC, ToasterBiome approved these changes

2022-03-28 15:07 UTC, Xoxeyos commented
@adamsong

2022-04-03 12:24 UTC, JamieD1 approved these changes

2022-04-03 12:27 UTC, JamieD1 approved these changes

2022-04-03 12:27 UTC, merged