makes marker beacons get turned off by veil
yogstation13/Yogstation pull request #13299
Opened 2022-02-18 18:24 UTC by UselessTheremin

fixes #13260
decided not to do spraypaint since you can also just pick em up to turn em off

:cl:  
bugfix: veil now darkens marker beacons  
/:cl:

2022-02-21 03:33 UTC, ToasterBiome approved these changes
looks good, seems unintended that they were left out

2022-02-21 22:54 UTC, SomeguyManperson commented
That appears to bethe item for the stack, not the structure version that emits light
Also veil's initial checks only kill lights that are effecting the tile the sling is standing on iirc so this would only cut adjacent marker beacons

2022-02-21 22:58 UTC, ToasterBiome requested changes

2022-02-21 22:58 UTC, ToasterBiome commented on yogstation/code/modules/antagonists/shadowling/shadowling_abilities.dm
> +		if(istype(LO, /obj/item/stack/marker_beacon))
```suggestion
		if(istype(LO, /obj/structure/marker_beacon))
```

2022-02-21 23:04 UTC, ToasterBiome commented on yogstation/code/modules/antagonists/shadowling/shadowling_abilities.dm
> +		if(istype(LO, /obj/item/stack/marker_beacon))
Also maybe turn this into a loop like glowshrooms as theos said if you want it to be bigger radius

2022-03-04 16:00 UTC, bruhlookatthisdood commented
so uhhhhh
hows it goooin?

2022-03-07 11:15 UTC, JamieD1 commented
> so uhhhhh hows it goooin?

Awaiting Author fix

2022-03-10 00:24 UTC, ToasterBiome commented
@UselessTheremin

2022-03-14 02:13 UTC, ToasterBiome commented
Theremin says they're done with yogs, closing

2022-03-14 02:13 UTC, closed without merging