[WIP] Adds an RGB upgrade project
yogstation13/Yogstation pull request #13301
Opened 2022-02-18 22:13 UTC by maxion12345

# If this is your first PR, or not, take the time to read our CONTRIBUTING.md file! You can see it here: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# Document the changes in your pull request

Remove this text and explain what the purpose of your PR is.

Mention if you have tested your changes. If you changed a map, make sure you used the mapmerge tool.
If this is an Issue Correction, you can type "Fixes Issue #6" to link the PR to the corresponding Issue number #6.

Prefix the PR title with [admin] if it involves something admin related. 
Prefix the PR title with [s] if you are fixing an exploit, so that it is not announced on the Yogstation Discord and the server.

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying.

# Wiki Documentation

Remove this text and write all information regarding your changes that should be known and documented through the Yogstation Wiki. 
Important documentation information includes, but is not limited to: any numerical values that have been changed, any images that have to be updated, names of specific pages that will be impacted by your changes. 

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images  
spellcheck: fixed a few typos  
experimental: This is experimental  
/:cl:

2022-02-18 22:16 UTC, bruhlookatthisdood commented
[Common] MAL-F-TI..N alarms, "IM HOSTING A RAD RAVE IN MY SAT!!"

2022-02-23 15:28 UTC, TheGamerdk requested changes

2022-02-23 15:28 UTC, TheGamerdk commented on code/modules/mob/living/silicon/ai/decentralized/ai_data_core.dm
> +	TimerID = addtimer(CALLBACK(src, .proc/partytime), 5, TIMER_STOPPABLE)
```suggestion
	TimerID = addtimer(CALLBACK(src, .proc/partytime), 0.5 SECONDS, TIMER_STOPPABLE)
```

2022-02-23 15:28 UTC, TheGamerdk commented on code/modules/mob/living/silicon/ai/decentralized/projects/rgb.dm
> +	var/current_color
unused

2022-02-23 15:28 UTC, TheGamerdk commented on code/modules/mob/living/silicon/ai/decentralized/projects/rgb.dm
> +
empty lines

2022-02-27 21:07 UTC, TheGamerdk requested changes

2022-02-27 21:07 UTC, TheGamerdk commented on code/modules/mob/living/silicon/ai/decentralized/ai_data_core.dm
> +	var/current_color = random_color()
check to see if we're already partying

2022-03-02 19:49 UTC, TheGamerdk commented on code/modules/mob/living/silicon/ai/decentralized/ai_data_core.dm
> +		return 0
```suggestion
		return FALSE
```

2022-03-02 19:50 UTC, TheGamerdk approved these changes

2022-03-02 19:56 UTC, merged