Update datum_traitor.dm
yogstation13/Yogstation pull request #13308
Opened 2022-02-20 06:15 UTC by Sniblet

# Document the changes in your pull request

https://forums.yogstation.net/threads/expand-on-the-last-line-of-the-traitor-alert.24591/
I don't know how to code but this is an attempt at that

# Changelog

:cl:  
rscadd: Traitors will now require a bit more than a small pay bonus to kill the entire station
/:cl:

2022-02-20 06:17 UTC, Mqiib commented
I like the flavor.

2022-02-20 06:51 UTC, voidGenAI commented
;Ironically I speak over the radio when I print in brain power.

2022-02-20 07:22 UTC, ToasterBiome requested changes

2022-02-20 07:22 UTC, ToasterBiome commented on code/modules/antagonists/traitor/datum_traitor.dm
> +	else if (obj_severity = 4)
```suggestion
	else if (obj_severity == 4)
```

2022-02-20 07:22 UTC, ToasterBiome commented on code/modules/antagonists/traitor/datum_traitor.dm
> +			obj_severity = obj_severity + 5
```suggestion
			obj_severity += 5
```

2022-02-20 07:22 UTC, ToasterBiome commented on code/modules/antagonists/traitor/datum_traitor.dm
> +		obj_severity = obj_severity + 5
```suggestion
		obj_severity += 5
```

2022-02-20 07:22 UTC, ToasterBiome commented on code/modules/antagonists/traitor/datum_traitor.dm
> +			obj_severity = obj_severity + 2
```suggestion
			obj_severity += 2
```

just do this for all of them

2022-02-20 07:26 UTC, ToasterBiome requested changes

2022-02-20 07:26 UTC, ToasterBiome commented on code/modules/antagonists/traitor/datum_traitor.dm
> +			obj_severity = obj_severity += 2
```suggestion
			obj_severity += 2
```
remove the first part if you're using the shorthand

2022-02-20 07:26 UTC, ToasterBiome commented on code/modules/antagonists/traitor/datum_traitor.dm
> +			obj_severity = obj_severity += 4
```suggestion
			obj_severity += 4
```

2022-02-20 07:26 UTC, ToasterBiome commented on code/modules/antagonists/traitor/datum_traitor.dm
> +			obj_severity = obj_severity += 1
```suggestion
			obj_severity += 1
```

2022-02-20 07:26 UTC, ToasterBiome commented on code/modules/antagonists/traitor/datum_traitor.dm
> +			obj_severity = obj_severity += 1
```suggestion
			obj_severity += 1
```

2022-02-20 07:31 UTC, ToasterBiome requested changes
change this stuff plz

2022-02-20 07:32 UTC, ToasterBiome commented
wait i might fucked it up

2022-02-21 03:32 UTC, ToasterBiome requested changes
more lore is good but it should still tell you your pay modifier.

2022-02-21 04:01 UTC, Sniblet commented
I went out of my way to keep these lore bits short, because antag greetings are big anyway and every bit of fluff is that little bit more annoying to those who don't care (almost everyone)
Keeping the pay mod doesn't add much and means that this addition will make the greeting a whole line longer.

2022-02-22 15:23 UTC, Absolucy commented
Honestly, I'd think something like "Your employers have promised you glory if you succeed" or something like that would work well.

2022-02-23 10:03 UTC, ToasterBiome commented
> I went out of my way to keep these lore bits short, because antag greetings are big anyway and every bit of fluff is that little bit more annoying to those who don't care (almost everyone, especially after they've seen it before) Keeping the bonus doesn't add much and means that this addition will make the greeting a whole line longer. Also if the Syndicate has your mom at gunpoint, they don't really have to pay you anything. Unless it's a gameplay thing? Do traitors get bigger paydays?

You get paid 1.5x every paycheck

2022-02-23 13:44 UTC, bruhlookatthisdood commented
what if the admins got an ability to set the objective severity when giving objectives.

2022-02-23 15:46 UTC, Sniblet commented
> You get paid 1.5x every paycheck

With that, I’ll close this.
It pushes a motive on people who care to RP traitor: those people can and will think of something better than “vaguely coerced” if they try even a little, and it’s not like all Syndicate agents are working against their will. They’re the antagonists, not the bad guys.
And it’s just useless clutter, where there wasn’t any before, to people who don’t care to RP.

2022-02-23 15:46 UTC, closed without merging