Refactors VV
yogstation13/Yogstation pull request #13312
Opened 2022-02-20 23:29 UTC by adamsong

# Document the changes in your pull request

Refactors VV to have two new procs, `vv_do_topic` and `vv_get_header`. `vv_do_topic` is called by the dropdowns, and `vv_get_header` allows adding to the vv header.

Also added a hiddenprints viewer in VV, because I liked it while stealing the rest of the code.

# Changelog

:cl:  
rscadd: Added show hiddenprints to VV
/:cl:

2022-02-20 23:30 UTC, TheGamerdk requested changes, later dismissed
theres a bug, fix it for merge

2022-02-25 15:14 UTC, JamieD1 commented
If this is a port please credit where from.

2022-03-06 08:21 UTC, adamsong commented
Experienced issues during test merge, will update if fixed

2022-03-13 11:22 UTC, JamieD1 approved these changes

2022-03-13 11:22 UTC, merged