Gives reactive tesla and repulse armors cooldowns
yogstation13/Yogstation pull request #13359
Opened 2022-03-01 00:08 UTC by ChesterTheCheesy

# Document the changes in your pull request
Extends #13251 to put cooldowns on other reactive armors (that already have defined to use them)

Since reactive tesla and repulse armors are more combat oriented than others (stealth and teleport), they have short cooldowns.
Tesla armor has a 3 second cooldown, repulse has 5 seconds.

This should make it so you don't simply ignore 50% of any hits put upon you. (hitting tesla armor with buckshot is suicide since every single pellet had 50% chance to create a zap (that deals ~40±5 damage to the first target) that ignores armor and shock immunity.

# Changelog

:cl:  
tweak: gives the rest of reactive armors respectible cooldowns
/:cl:

2022-03-01 00:21 UTC, ChesterTheCheesy commented
https://user-images.githubusercontent.com/71487903/156080969-61508b04-94b3-4db8-8baf-de364b8c3e6a.mp4

Some footage of me shooting a tesla armor with one buckshot

2022-03-02 19:47 UTC, TheGamerdk requested changes, later dismissed

2022-03-02 19:47 UTC, TheGamerdk commented on code/modules/clothing/suits/reactive_armour.dm
> +	reactivearmor_cooldown_duration = 30
```suggestion
	reactivearmor_cooldown_duration = 3 SECONDS
```

2022-03-02 19:47 UTC, TheGamerdk commented on code/modules/clothing/suits/reactive_armour.dm
> +	reactivearmor_cooldown_duration = 50
```suggestion
	reactivearmor_cooldown_duration = 5 SECONDS
```

2022-03-02 20:23 UTC, ChesterTheCheesy commented
dude the rest is like that and i'm not refactoring the entire file

2022-03-05 11:35 UTC, TheGamerdk commented
> dude the rest is like that and i'm not refactoring the entire file

These are the rules

2022-03-07 11:48 UTC, JamieD1 approved these changes

2022-03-07 11:48 UTC, merged