Adds justice to the world
yogstation13/Yogstation pull request #13363
Opened 2022-03-02 17:43 UTC by Sniblet

# Document the changes in your pull request

I think someone accidentally did the exact opposite of what an inoffensive QoL PR proposed to do yesterday. I can’t contact them right now so I’m just offering to correct it for them

Most people don’t try to wag all round and so don’t know how annoying this is. Let me solve my own problem. No one stuns people to make them stop wagging, because they can just start again after a second or two, so who is this hurting

If a tailed creature is paralyzed, they will still not be able to start wagging. If they are stunned, their tail is not paralyzed.
If a tailed creature is already wagging, stuns or paralysis will not end it.

I’d have it so only stuns didn’t stop it, but I don’t know how and I can’t get in contact with a better coder right now

see how I kept cats and felinids out of the title and embed description because that might keep the “I don’t like cats so pr sucks mumumu fetish content” squad away for a bit
just remove them if you want them gone

# Changelog

:cl:  
rscadd: added justice
bugfix: Things that don’t paralyze you don’t paralyze your tail
tweak: Tails now have immense inertia once they begin to wag and cannot be stopped by others as long as the owner is conscious
/:cl:

2022-03-02 19:46 UTC, Hopekz commented
Deceptive PR. Just write that it is a revert of #13343 instead of acting like this is something new

2022-03-02 20:15 UTC, Sniblet commented
It’s not a revert, it’s a compromise. I kept in the stun effect and am redoing #13341.

2022-03-02 20:47 UTC, Marmio64 commented
Get a proper pr name

2022-03-02 22:28 UTC, Hopekz commented
> It’s not a revert, it’s a compromise.

It's kind of a never ending cycle with the instant "react to a PR" PR's.
 Should we expect a compromise PR right after this one is merged to compromise on these changes too?

2022-03-02 23:11 UTC, Sniblet commented
Well, I'm sorry, Hopekz, but the PR was my idea and Baiomu closed it without saying anything to me. I felt safe in reproposing it at least until someone was able to coherently explain why making it easier for a character to keep their tail wagging throughout the round was bad for the game.

If anyone wants to go back on what this PR does, I will be completely shocked at the display of bad faith. To be clear, _stuns_ as opposed to paralyzes are where you character's movement and ability to use their hands are limited, but they don't fall down. You can count on your fingers the number of things in the entire game that do that: sigils of submission, neural shock, and vampire glare, and climbing tables are all I can call to mind. This PR, in its finished form, would only take away those things' abilities to grief waggers. You can still flash them so they have to stop for five seconds. Rejoice.

2022-03-02 23:38 UTC, Hopekz commented
> Well, I'm sorry, Hopekz

I forgive you

2022-03-03 00:02 UTC, Sniblet commented
Okay I think this does the original intended thing
I might have a way to also do this for slips, but I don't know if it will add an unintended amount of jank and I should probably do it separately so as not to push my luck because for some reason this is already controversial

2022-03-03 00:56 UTC, Sniblet commented
Works as described

2022-03-03 01:08 UTC, Sniblet commented
It does not do the intended

2022-03-03 02:25 UTC, Sniblet commented
"could add an arg that differentiates if its a stun or whatever and check that, or you could make a separate proc for each of them and copy the code for spec_stun"
someone translate

2022-03-03 02:51 UTC, nmajask commented on code/modules/mob/living/carbon/human/species.dm
> +/datum/species/proc/spec_paralyze(mob/living/carbon/human/H,amount)
```suggestion
```
Remove this if you're not going to use it

2022-03-03 03:26 UTC, Sniblet commented
Works as described

2022-03-13 01:48 UTC, ToasterBiome commented
> Well, I'm sorry, Hopekz, but the PR was my idea and Baiomu closed it without saying anything to me.

For the record, it was my PR and I closed it because I merged another PR that invalidates it. Feel free to PM me with any queries you might have instead of name dropping me

2022-03-13 03:17 UTC, nmajask requested changes

2022-03-13 03:17 UTC, nmajask commented on code/modules/mob/living/carbon/human/status_procs.dm
>  	amount = dna.species.spec_stun(src, amount)
```suggestion
	if(!dna || !dna.species)
		return ..()
	amount = dna.species.spec_stun(src, amount)
```
Add a check to make sure dna and dna.species aren't null

2022-03-13 11:12 UTC, JamieD1 commented
A stun is just as bad as a paralyze, I don't get this point of this PR. Tail wagging should be stopped with any sort of immobilize.

2022-03-13 11:12 UTC, closed without merging

2022-03-13 17:03 UTC, Sniblet commented
> A stun is just as bad as a paralyze, I don't get this point of this PR. Tail wagging should be stopped with any sort of immobilize.

I wrote paragraphs about why this was wrong
Why is it so hard to make my life a little easier without harming anyone else