Ports "fixes toggling flashlight removing bayonet overlay"
yogstation13/Yogstation pull request #13371
Opened 2022-03-03 17:49 UTC by nmajask

# Document the changes in your pull request

Fixes #13369.

Ports ["fixes toggling flashlight removing bayonet overlay" #47053](https://github.com/tgstation/tgstation/pull/47053) by [IradT/Kaffe-work](https://github.com/Kaffe-work) from TG, which fixes toggling gun flashlights removing bayonet. Is tested, does work.

![image](https://user-images.githubusercontent.com/14363906/156621888-5a4af4fb-09cb-401b-857c-8dc83e58b77b.png)

# Wiki Documentation

No changes needed.

# Changelog

:cl:  IradT
bugfix: fixed sprites on guns with both bayonet and toggle-able lights removing the bayonet when toggled.
/:cl:

2022-03-07 11:45 UTC, JamieD1 approved these changes

2022-03-07 11:47 UTC, JamieD1 commented
Have you tested turning the light on and off multiple times to see if the overlays just keep adding up? I see nothing to check if the overlay is there or to remove it first.

2022-03-07 11:47 UTC, JamieD1 requested changes
Have you tested turning the light on and off multiple times to see if the overlays just keep adding up? I see nothing to check if the overlay is there or to remove it first.

2022-03-08 09:13 UTC, nmajask commented
> Have you tested turning the light on and off multiple times to see if the overlays just keep adding up? I see nothing to check if the overlay is there or to remove it first.

It's fine, I tested it

2022-03-09 07:37 UTC, nmajask commented
#13394

2022-03-09 07:37 UTC, closed without merging