Rotatium buff
yogstation13/Yogstation pull request #13403
Opened 2022-03-10 08:13 UTC by adamsong

# Document the changes in your pull request
Buffs rotatium so it conter-rotates your player, making you appear upright t yourself, but only yourself.

# Changelog

https://user-images.githubusercontent.com/4607006/157617221-6613d99f-ddd8-4a3b-85c5-84957578ac52.mp4

:cl:  
tweak: rotatium has added rotating
/:cl:

2022-03-10 08:17 UTC, ToasterBiome commented
Love it, does it work with moving/turning properly? VV'd transforms reset over the weirdest things.

2022-03-10 14:36 UTC, Jarod1200 commented
Now this is some quality content

2022-03-13 01:41 UTC, ToasterBiome requested changes
ensure this works while moving

2022-03-25 10:28 UTC, ToasterBiome commented
@adamsong

2022-03-29 01:21 UTC, adamsong commented
> ensure this works while moving

It does

2022-03-29 01:22 UTC, ToasterBiome approved these changes

2022-03-29 01:22 UTC, merged