Makes dragon's blood turn you into a cooler lizard
yogstation13/Yogstation pull request #13427
Opened 2022-03-15 08:17 UTC by Mqiib

# Document the changes in your pull request

Adds a new subspecies of lizards: Draconids! They're just lizards with fire resistance, slight resistance to damage, and 2 more punch damage. They only come from the dragon's blood bottle from necropolis chests and are arguably still worse than just being a straight skeleton but hey it makes this roll actually give you something useful.

# Wiki Documentation

Perhaps some spooky cryptic mention of an ancient species of draconic humanoids on lavaland other than the askwalkers or something, I dunno.

# Changelog

:cl:  
rscadd: New rare species for powergaming lavalandists: Draconids!
tweak: Makes the lizard roll for dragon's blood bottles turn you into a draconid
experimental: WARNING: MINING BUFF
/:cl:

2022-03-15 08:18 UTC, ToasterBiome commented
i hate lizards

2022-03-15 08:33 UTC, Mqiib commented
> i hate lizards

same tbh

2022-03-15 12:06 UTC, Marmio64 commented
oh god, not going to lie, but miners really dont need extra armor when they can already get almost as much as xenobio. Also, i dont know about punishing miners with forced digitigrade legs. It definitely doesn't come out to being a powerful species or anything but i'm neutral on it.

2022-03-15 12:48 UTC, SomeguyManperson commented
> Also, i dont know about punishing miners with forced digitigrade legs.

Lol

2022-03-15 15:06 UTC, Cartlord commented
what if we turned ashies into these too

2022-03-15 19:08 UTC, cowbot92 commented
evil red lizard good

2022-03-15 20:54 UTC, ToasterBiome approved these changes
yeah ok

2022-03-15 23:06 UTC, Mqiib commented
> oh god, not going to lie, but miners really dont need extra armor when they can already get almost as much as xenobio. Also, i dont know about punishing miners with forced digitigrade legs. It definitely doesn't come out to being a powerful species or anything but i'm neutral on it.

The original already forced digitigrade legs

![image](https://user-images.githubusercontent.com/43766432/158486633-7d5ceda5-7f7f-41cf-aa7c-a00e11d49129.png)

2022-03-16 00:12 UTC, Marmio64 commented
> > oh god, not going to lie, but miners really dont need extra armor when they can already get almost as much as xenobio. Also, i dont know about punishing miners with forced digitigrade legs. It definitely doesn't come out to being a powerful species or anything but i'm neutral on it.
> 
> The original already forced digitigrade legs
> 
> ![image](https://user-images.githubusercontent.com/43766432/158486633-7d5ceda5-7f7f-41cf-aa7c-a00e11d49129.png)
> 
> The current version is literally just turning you into a red lizard with no benefits.

honestly i'd just say remove the digitigrade legs and keep it in as a 33% chance to not get blessed with overpowered shit. (Which you get along with some pretty good armor)

2022-03-17 22:00 UTC, ToasterBiome requested changes
dont know how i like the inherent armor, punch is fine because of how little it will be used

2022-03-17 22:01 UTC, ToasterBiome requested changes
fuck i forgor the button to add them

2022-03-17 22:01 UTC, ToasterBiome commented on code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
> +	burnmod = 0.8
```suggestion

```

2022-03-17 22:01 UTC, ToasterBiome commented on code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
> +	brutemod = 0.9 //something something dragon scales
```suggestion

```

2022-03-19 20:10 UTC, Smudged commented
> dont know how i like the inherent armor, punch is fine because of how little it will be used

I don't think the extra armour is anything to worry about, considering it's a award from killing the ashdrake to turn you into a drachanoid anyways. 

Would rather keep all the changes and test them, The fire resistance is nice and flavourful.

2022-03-20 02:04 UTC, Mqiib commented
> dont know how i like the inherent armor, punch is fine because of how little it will be used

The damage resistance is one of the main draws and is actually useful on lavaland if you're going around fighting bosses. Getting rid of it would basically make turning into a mini dragon person equivalent to just getting heat adaptation from genetics, which you can do every round. It would also once again make it basically objectively worse than the skeletonize option which _also_ makes you completely immune to all atmospherics, radiation, and disease for the low low price of looking spooky.

2022-03-21 02:51 UTC, ToasterBiome commented
> > dont know how i like the inherent armor, punch is fine because of how little it will be used
> 
> The damage resistance is one of the main draws and is actually useful on lavaland if you're going around fighting bosses. Getting rid of it would basically make turning into a mini dragon person equivalent to just getting heat adaptation from genetics, which you can do every round. It would also once again make it basically objectively worse than the skeletonize option which _also_ makes you completely immune to all atmospherics, radiation, and disease for the low low price of looking spooky.

Yes but also go fight antag because armor resist

2022-03-21 21:45 UTC, Mqiib commented
> > > dont know how i like the inherent armor, punch is fine because of how little it will be used
> > 
> > 
> > The damage resistance is one of the main draws and is actually useful on lavaland if you're going around fighting bosses. Getting rid of it would basically make turning into a mini dragon person equivalent to just getting heat adaptation from genetics, which you can do every round. It would also once again make it basically objectively worse than the skeletonize option which _also_ makes you completely immune to all atmospherics, radiation, and disease for the low low price of looking spooky.
> 
> Yes but also go fight antag because armor resist

This "valid the antags with it" argument can be made for almost every single piece of loot on lavaland, many of which don't even have a use in terms of actual mining and megafauna killing. Try again.

2022-03-21 21:50 UTC, ToasterBiome commented
> > > > dont know how i like the inherent armor, punch is fine because of how little it will be used
> > > 
> > > 
> > > The damage resistance is one of the main draws and is actually useful on lavaland if you're going around fighting bosses. Getting rid of it would basically make turning into a mini dragon person equivalent to just getting heat adaptation from genetics, which you can do every round. It would also once again make it basically objectively worse than the skeletonize option which _also_ makes you completely immune to all atmospherics, radiation, and disease for the low low price of looking spooky.
> > 
> > 
> > Yes but also go fight antag because armor resist
> 
> This "valid the antags with it" argument can be made for almost every single piece of loot on lavaland, many of which don't even have a use in terms of actual mining and megafauna killing. Try again.

I do not believe this PR is worth maintaining from a code standpoint so unfortunately, I will be closing this now. Try again.

2022-03-21 21:50 UTC, ToasterBiome approved these changes

2022-03-25 07:32 UTC, merged