fixes borgs hugging not unresting + makes the lying down message actually work
yogstation13/Yogstation pull request #13423
Opened 2022-03-15 01:13 UTC by tattax

this doesn't affect any effects' cooldown only voluntary resting

:cl:  
bugfix: fixed a bug that made borgs not unrest people and the message when clicking on a resting person
/:cl:

2022-03-15 01:20 UTC, Runian commented
so borg hugging intended not to reduce the effects?

2022-03-15 01:36 UTC, ToasterBiome commented
> so borg hugging aren't suppose to reduce the effects that [carbon hugging](https://github.com/yogstation13/Yogstation/blob/b70a425912d2f5985312e3ec65f156b90e435765/code/modules/mob/living/carbon/carbon_defense.dm#L330) has?

probably not

2022-03-15 02:04 UTC, tattax commented
^^

2022-03-15 21:32 UTC, Runian commented
alright. if that is so, then flavor text like this should be removed or changed. its misleading because it doesn't actually help whoever they're shaking up. though, tg has a pr for this if that helps argue that borgs should get the same effects for hugging https://github.com/tgstation/tgstation/pull/62468

2022-03-22 10:13 UTC, ToasterBiome requested changes

2022-03-22 10:13 UTC, ToasterBiome commented on code/game/objects/items/robot/robot_items.dm
> +				M.set_resting(FALSE)
this lets you shake non-humans, move set_resting back, also it can be silent

2022-03-29 09:57 UTC, ToasterBiome approved these changes

2022-03-29 09:58 UTC, ToasterBiome commented
> alright. if that is so, then flavor text like [this ](https://github.com/yogstation13/Yogstation/blob/31096555bda7e82ced6e62b86b307c0655f1c755/code/game/objects/items/robot/robot_items.dm#L106)should be removed or changed. its misleading because it doesn't actually help whoever they're shaking up. though, tg has a pr for this if that helps argue that borgs should get the same effects for hugging [tgstation/tgstation#62468](https://github.com/tgstation/tgstation/pull/62468)

up to @tattax if they want to make a separate PR, this is a bugfix

2022-03-29 09:59 UTC, merged