only slipping and climbing tables do not stop tail wagging
yogstation13/Yogstation pull request #13443
Opened 2022-03-17 02:23 UTC by Sniblet

here we go again

# Document the changes in your pull request

Not tested:
Climbing tables does not stop tail wagging.

Not implemented:
Slipping does not stop tail wagging.

# Changelog

:cl:  
bugfix: slipping and climbing tables don't stop tail wagging
tweak: felinids can now oppress other species
/:cl:

2022-03-17 02:26 UTC, tattax requested changes
define H by using var/mob/living/carbon/human/H

2022-03-17 02:31 UTC, Sniblet commented
I don't know what that means

2022-03-17 22:25 UTC, Sniblet commented
Okay I have no idea what to do about the slip thing
I think I'll just go back on that and pretend I'm "atomizing" or something similarly responsible until I come up with a fix

2022-03-18 22:16 UTC, ToasterBiome requested changes, later dismissed
this is a weird way to do it, also you better check if they are indeed a living/carbon/human for safety™

2022-03-18 22:16 UTC, ToasterBiome commented on code/game/machinery/_machinery.dm
> +					if(H.dna.species.is_wagging_tail())
```suggestion
					if(H && H.dna.species.is_wagging_tail())
```

2022-03-18 22:16 UTC, ToasterBiome commented on code/game/objects/structures.dm
> +					if(H.dna.species.is_wagging_tail())
```suggestion
					if(H && H.dna.species.is_wagging_tail())
```

2022-03-19 06:28 UTC, KittyNoodle commented
Not a fix :P

2022-03-19 07:40 UTC, Sniblet commented
If you know a better way you’re welcome to overwrite everything, none of this is my own work I just make the PRs

2022-03-19 11:18 UTC, adamsong approved these changes

2022-03-19 13:44 UTC, JamieD1 approved these changes

2022-03-19 13:44 UTC, merged

2022-03-19 14:59 UTC, Cartlord commented
Why are you merging furry shit?