Buffs TRAC rounds and allows dets to use the tracking program
yogstation13/Yogstation pull request #13448
Opened 2022-03-17 05:12 UTC by nmajask

# Document the changes in your pull request

Changes an underused ammunition type to be more useful and tweaks some modular computer stuff. Is tested.

- TRAC implant now lasts 5 minutes
- Detectives now start with a modular PDA
- Radar programs (Lifeline, Fission360, and of course the Implant Tracker program) now work on PDAs
- Implant Tracking program now only requires brig access (can just give det a disk with the program instead if preferred)

# Wiki Documentation

If it is mentioned what detectives start with, it would be a good idea to update that with the PDA.

# Changelog

:cl:  
tweak: TRAC implant now lasts 5 minutes 
tweak:  Detectives now start with a modular PDA
tweak: Radar programs now work on PDAs and the implant tracking program now only requires brig access
/:cl:

2022-03-17 21:57 UTC, ToasterBiome requested changes, later dismissed

2022-03-17 21:57 UTC, ToasterBiome commented on code/game/objects/items/implants/implant_track.dm
> +	var/lifespan_postmortem = 10 MINUTES //for how many deciseconds after user death will the implant work?
update comment

2022-03-17 21:57 UTC, ToasterBiome commented on code/game/objects/items/implants/implant_track.dm
> +	var/lifespan = 15 MINUTES //how many deciseconds does the implant last?
update comment

2022-03-18 02:28 UTC, ToasterBiome commented
Has this been tested? Also, allowing it on PDAs.. hm....

2022-03-18 04:41 UTC, nmajask commented
> Has this been tested?

I did, said so in the PR

2022-03-19 13:45 UTC, JamieD1 approved these changes
Lets give it a go

2022-03-19 13:45 UTC, merged