Fixes being able to steal AIs out of other intellicards if you're both trying to download it
yogstation13/Yogstation pull request #13455
Opened 2022-03-18 08:39 UTC by TheGamerdk

# Document the changes in your pull request

Fixes #13422

# Wiki Documentation

# Changelog

:cl:  
tweak: Fixes issue where you could end up downloading an AI out of an intellicard
/:cl:

2022-03-18 22:07 UTC, ToasterBiome commented
Is this tested

2022-03-19 11:03 UTC, adamsong requested changes, later dismissed

2022-03-19 11:03 UTC, adamsong commented on code/modules/mob/living/silicon/ai/decentralized/management/ai_controlpanel.dm
> +		if(!isaicore(get_turf(downloading)))
```suggestion
		if(!isaicore(downloading.loc))
```
Turfs can't  be AI cores

2022-03-19 11:37 UTC, TheGamerdk commented on code/modules/mob/living/silicon/ai/decentralized/management/ai_controlpanel.dm
> +		if(!isaicore(get_turf(downloading)))
get_turf returns loc

2022-03-24 12:15 UTC, TheGamerdk commented
> Is this tested

why would i do such a thing?

2022-03-25 10:40 UTC, ToasterBiome approved these changes

2022-03-26 06:43 UTC, merged