gives darkspawn a hint
yogstation13/Yogstation pull request #13454
Opened 2022-03-18 04:27 UTC by Sniblet

PSST!! PRESS THIS BUTTON TO WIN!!

# Document the changes in your pull request

Slightly extends the pass ability's tooltip

# Changelog
:cl:  
tweak: slightly expanded the tooltip for pass
/:cl:

2022-03-18 22:05 UTC, ToasterBiome requested changes
what's "them"? reading this, I do not know what to examine, just that I have to examine something. Do I examine the tendrils? My active arm? Shift click the action in the top left?

2022-03-19 07:31 UTC, Sniblet commented
Tendrils is the direct object of the sentence, if someone can’t infer that it’s referring to the tendrils I don’t think I can help them

2022-03-19 11:05 UTC, adamsong approved these changes
Should be fine

2022-03-19 13:49 UTC, JamieD1 approved these changes

2022-03-20 10:47 UTC, TheGamerdk requested changes, later dismissed
I have to agree with baimou. This can be confusing

2022-03-20 10:47 UTC, TheGamerdk commented on yogstation/code/modules/antagonists/darkspawn/darkspawn_abilities/pass.dm
> +	desc = "Twists an active arm into tendrils with many important uses, examine them to see a list."
```suggestion
	desc = "Twists an active arm into tendrils with many important uses. Examine the tendrils to see a list."
```

2022-03-20 18:04 UTC, SomeguyManperson approved these changes
Honestly should have added this at the start since its slightly more lilely to be rewd here than in the chat

2022-03-21 02:47 UTC, ToasterBiome approved these changes

2022-03-21 02:47 UTC, merged