Phytosian "hair"
yogstation13/Yogstation pull request #13505
Opened 2022-03-24 23:52 UTC by Chubbygummibear

I could have said podperson but i like their real name
# Document the changes in your pull request
AFTER LIKE 2 MONTHS IT'S FINALLY READY (PROBABLY)

Phytosians now have 10 different hairstyles that they're free to color as they please, along with some hairstyles having flower accents that can be colored separately
Cabbage and Fig
![image](https://user-images.githubusercontent.com/46236974/160025944-dcc2ccb6-04fe-4600-ae7e-6ade8d41860b.png)![image](https://user-images.githubusercontent.com/46236974/160025874-23eaaf8f-698f-4f46-9faa-aa119b267899.png)
Hibiscus and Ivy
![image](https://user-images.githubusercontent.com/46236974/160026076-b4e5e073-8723-4ee4-98d4-4c2df3e41256.png)![image](https://user-images.githubusercontent.com/46236974/160026930-1ee3d4c7-903d-4218-be9c-2d3c55ed148f.png)
Orchid and Prayer
![image](https://user-images.githubusercontent.com/46236974/160027190-0d3427a4-4370-4030-a2ea-4aeb05843d35.png)![image](https://user-images.githubusercontent.com/46236974/160027251-d1a47c40-310a-4949-ae93-7a5810faccb7.png)
Rose and Shrub
![image](https://user-images.githubusercontent.com/46236974/160027330-495b8dd6-d9a8-4c20-89b5-3165005ebba0.png)![image](https://user-images.githubusercontent.com/46236974/160027367-56a247b4-d1d7-4771-a5c1-ea9990618ce5.png)
Spinach and Vine
![image](https://user-images.githubusercontent.com/46236974/160027433-b018263d-6db3-4936-8ecc-21df91d798ff.png)![image](https://user-images.githubusercontent.com/46236974/160027476-37d91d4e-9010-4224-8364-88abadb794e3.png)

In game:
![image](https://user-images.githubusercontent.com/46236974/160027649-241fc21b-ece1-416e-8b42-9420b98d2ccd.png)
![image](https://user-images.githubusercontent.com/46236974/160027951-bbf0c03c-cf56-4c55-b052-27ec4a2d55a2.png)

The hair isn't actually "hair" and you can't interact with it through a mirror (maybe something for later), but it will react to radiation and other feature scrambling effects in game. I also recognize that it interacts a bit awkwardly with hats, mostly that they are large hairstyles that don't fully get covered, so I will mention this to the original sprite artist to see if they are able to do something about this
# Wiki Documentation

maybe just change the Phytosian pictures to reflect the new hairstyles or something. or just leave it, since bush heads are still a valid hair choice

# Changelog

:cl:  code by Chubbygummibear, sprites by Sheets 
rscadd: pod hairstyles  
imageadd: hair sprites for pods
imagedel: Phytosians no longer have brush built into their heads
/:cl:

2022-03-24 23:59 UTC, KillerOrcaCora commented
Very cute sprites, Now ADD IT TO DONORRRRRRRRRRRRRRRRRRRRR!!!!!!!!!!!!!!!! ***SLAM*** ***SLAM*** ***SLAM***

2022-03-25 00:01 UTC, Chubbygummibear commented
> Very cute sprites, Now ADD IT TO DONORRRRRRRRRRRRRRRRRRRRR!!!!!!!!!!!!!!!! _**SLAM**_ _**SLAM**_ _**SLAM**_

i'll make floor length bedhead a donor only plant hair if you become a plant main

2022-03-25 00:01 UTC, Sheits commented
epic

2022-03-25 01:26 UTC, Marmio64 commented
i feel like having hair colors that arent the same as the rest of the plantperson makes the fake hair look too much like real hair and humanizes them more than they were already, otherwise the sprites look good.

2022-03-25 09:25 UTC, wejengin2 commented
Having the hair be different color than the rest of the plang is very bad and stupid because i think it is

2022-03-25 16:54 UTC, Simplehorror commented
I also agree that the hair colour should remain the same

2022-03-25 19:43 UTC, ynot01 commented
i hate it

it looks awesome tho

2022-03-26 10:12 UTC, missatessatessy commented
Plants irl have different colours and flowers, it's part of what makes them pretty. I don't see why phytosians can't be as beautiful as their inspiration.
Good pr and sprites

2022-03-26 12:57 UTC, grimm-hollowknight reviewed
Varying quality but they look good. My only gripe is that they're all very wavy and long like human hair. The only pure plant-like one is the sunflower.

2022-03-26 21:43 UTC, Chubbygummibear commented
> Varying quality but they look good. My only gripe is that they're all very wavy and long like human hair. The only pure plant-like one is the sunflower.

I could try to lock them to being lighter colors and maybe more plantlike?, but i don't think i'll be able to get much out of the original sprite artist because they became quite busy with work and school after finishing this set unfortunately :(

2022-03-29 15:22 UTC, Tipy1802 commented
This is legally epic

2022-03-29 16:58 UTC, nesisknesis approved these changes
Why is it all womanly hair too

2022-04-02 22:55 UTC, JamieD1 requested changes

2022-04-02 22:55 UTC, JamieD1 commented on code/__HELPERS/mobs.dm
> +		"pod_hair" = pick(GLOB.pod_hair_list),
```suggestion
		"pod_hair" = pick(GLOB.pod_hair_list)
```

2022-04-02 22:55 UTC, JamieD1 commented on code/_globalvars/lists/flavor_misc.dm
> +
```suggestion
```

2022-04-02 22:55 UTC, JamieD1 commented on code/modules/admin/create_mob.dm
> +
```suggestion
```

2022-04-02 22:55 UTC, JamieD1 commented on code/modules/client/preferences.dm
> +
```suggestion
```

2022-04-02 22:55 UTC, JamieD1 commented on code/modules/client/preferences.dm
> +
```suggestion
```

2022-04-02 22:55 UTC, JamieD1 commented on yogstation/code/modules/mob/living/carbon/human/species_types/plantpeople.dm
> +	default_features = list("mcolor" = "0F0", "pod_hair" = "Cabbage", "pod_flower" = "Cabbage", )
```suggestion
	default_features = list("mcolor" = "0F0", "pod_hair" = "Cabbage", "pod_flower" = "Cabbage")
```

2022-04-02 23:13 UTC, JamieD1 approved these changes

2022-04-02 23:14 UTC, merged