Gives syndie surgery duffel tools speed boost like toolbox tools
yogstation13/Yogstation pull request #13523
Opened 2022-03-26 06:42 UTC by SomeguyManperson

# Document the changes in your pull request

This kit does effectively nothing you cant already do with an emag and autolathe

Unlike the syndie toolbox, which gets slightly higher damage, a smaller size so it can be hidden, and faster tools, the syndie surgery duffel gets.... a bunch of tools you can already make on station and a 0 slowdown duffel which granted can be useful is also extremely obviously a syndicate duffel bag

So i take the 0.5 toolspeed modifier from the syndie toolbox and apply it to the syndie surgery tools as well, making them objectively better than normal (and potentially upgraded) surgical tools so it can be less of a noob trap/meme item

# Wiki Documentation

Syndie surgery duffel's tools have doubled speed

# Changelog

:cl:  theos buffing something he uses again
tweak: syndicate surgery duffel surgery tools are now twice as fast as normal tools because you are buying a syndicate surgical kit inside a duffel bag not just a syndicate duffel bag that happens to be occupied
/:cl:

2022-03-26 06:45 UTC, ToasterBiome commented
god this is such a stupid ass way to do this oml

2022-03-26 06:48 UTC, SomeguyManperson commented
> god this is such a stupid ass way to do this oml

Blame toolboz code i ctrl c ctrl v

2022-03-26 06:53 UTC, ToasterBiome approved these changes

2022-03-27 12:40 UTC, JamieD1 requested changes, later dismissed
Populate the contents.. then do a For( loop instead, this is very messy

2022-03-27 23:01 UTC, SomeguyManperson commented
fixed + syndie toolbox also given objectively better code

2022-04-01 02:12 UTC, ToasterBiome approved these changes

2022-04-01 23:02 UTC, merged