Garys cooler rock
yogstation13/Yogstation pull request #13599
Opened 2022-04-05 15:12 UTC by Altoids1

![image](https://user-images.githubusercontent.com/29939414/161778747-5afd21ce-fda7-4a8e-a3aa-03e021b6f9c5.png)

## Summary
This does some polishing of how the Station Charter works. Most notably, apostrophes and so on are no longer destroyed by ``html_encode()``. It is also now possible for admins to manually approve station names.

## Changelog
:cl:  Altoids
bugfix: You can no longer name the space station your favourite ethnic slur.
bugfix: Apostrophes, etc. within custom station names are no longer clobbered into nonsense.
tweak: The Captain now has ten minutes to rename the station, up from five minutes.
spellcheck: The admin dialog for station renaming is now a bit clearer and allows you to manually approve a station name.
/:cl:

2022-04-05 15:13 UTC, Altoids1 commented
Guess who figured out how to clean their merge commits

2022-04-05 15:16 UTC, Hopekz commented
> Guess who figured out how to clean their merge commits

Super pretty!!

2022-04-05 20:11 UTC, adamsong requested changes, later dismissed

2022-04-05 20:11 UTC, adamsong commented on code/game/objects/items/charter.dm
> +#define STATION_RENAME_TIME_LIMIT 6000 // Deciseconds
```suggestion
#define STATION_RENAME_TIME_LIMIT (10 MINUTES)
```

2022-04-07 18:46 UTC, JamieD1 approved these changes
Cheers then

2022-04-07 18:46 UTC, merged