Fixes a null override
yogstation13/Yogstation pull request #13616
Opened 2022-04-06 16:19 UTC by ike709

See https://github.com/ParadiseSS13/Paradise/pull/17581

2022-04-06 16:23 UTC, adamsong commented
Does this not cause all the references to `AI` in the code point to the wrong variable?

2022-04-06 16:26 UTC, AffectedArc07 requested changes

2022-04-06 16:26 UTC, AffectedArc07 commented on code/game/mecha/mecha_wreckage.dm
> +/obj/structure/mecha_wreckage/transfer_ai(interaction, mob/user, mob/living/silicon/ai/AI, obj/item/aicard/card)
```suggestion
/obj/structure/mecha_wreckage/transfer_ai(interaction, mob/user, mob/living/silicon/ai/the_ai, obj/item/aicard/card)
```
`AI` is a local var on this type itself and I am worried about fuckups with this.

2022-04-06 16:27 UTC, AffectedArc07 commented on code/game/mecha/mecha_wreckage.dm
> +/obj/structure/mecha_wreckage/transfer_ai(interaction, mob/user, mob/living/silicon/ai/AI, obj/item/aicard/card)
Wait this isnt my fucking codebase

2022-04-06 17:12 UTC, ike709 commented
The fact that `AI` is both the name of a positional arg in the proc def and an arg in the parent proc def pains me.

2022-04-07 05:44 UTC, ToasterBiome commented
Duplicate of https://github.com/yogstation13/Yogstation/pull/13581

Will merge whichever has a less stupid name for the variable sooneset

2022-04-07 18:30 UTC, closed without merging