Replaces ashy spellblade with new item: bloody knuckles
yogstation13/Yogstation pull request #13623
Opened 2022-04-06 22:46 UTC by LazennG

# Document the changes in your pull request
![vampiric_nuckles](https://user-images.githubusercontent.com/58535870/162080002-4b55cc49-d057-4f95-bc20-3d8d0822f25f.gif)
lazenn makes another stupid blood themed item. Bloody knuckles are a melee item that mark targets after impact. Marked targets can be hit again to root them in place; people for 1 second and everything else for 6. Marking targets this way puts it on a cooldown for 10 seconds if the last marked target was a human and 6 seconds otherwise. Additionally, the knuckles grant 2 abilities with a cooldown of 15 seconds. One ability marks people within 7 tiles of sight if they're standing on blood and the other roots marked targets within 8 spaces.

Came up with this idea after thinking about what could help miners in lavaland and what would still be somewhat thematic with the boss whose drops are all combat-oriented.

spellblade was always a shit drop and ashy spellblade was lame coping

# Wiki Documentation

at https://wiki.yogstation.net/wiki/Megafauna#Loot_3
replace the line about the spellblade with something like
bloody knuckles that can root victims in place and do 50 damage to nonhumanoids.

# Changelog

:cl:  @Chubbygummibear, @ToasterBiome, @cuackles 
rscadd: Added new item: bloody knuckles 
rscdel: Removes ashy spellblade from bg loot pool
imageadd: sprites for knuckles, the mark, and root effect 
/:cl:
thanks chubbygummibear and baiomu for coding everything functional and cuackles for sprites

2022-04-06 22:47 UTC, SomeguyManperson commented
![image](https://user-images.githubusercontent.com/24857008/162085041-af00469f-126d-48c5-9c86-ba7231bdff9e.png)

2022-04-06 22:47 UTC, SomeguyManperson commented on code/datums/action.dm
> +	name = "Vise Grip"
```suggestion
	name = "Vice Grip"
```

2022-04-06 22:47 UTC, LazennG commented
> ![image](https://user-images.githubusercontent.com/24857008/162085041-af00469f-126d-48c5-9c86-ba7231bdff9e.png)

i have 0 clue how to get airshoe commits out of the fucking list

2022-04-06 22:49 UTC, LazennG commented on code/datums/action.dm
> +	name = "Vise Grip"
![image](https://user-images.githubusercontent.com/58535870/162085360-24770aaa-ac7b-4dc1-8050-94280a68a3d5.png)
bri'ish?

2022-04-06 22:49 UTC, Marmio64 commented
spellblade was a shit drop until you wanted to validhunt/do antag shit and insta delimb people when RNG blesses you (rip zombies)

2022-04-06 22:53 UTC, tattax commented on code/datums/status_effects/knuckleroot.dm
> +		to_chat(owner, "Your bindings are gone!")
```suggestion
		to_chat(owner, span_notice("Your bindings are gone!"))
```

i like my colored chat texts

2022-04-06 22:55 UTC, tattax commented on code/datums/status_effects/knuckleroot.dm
> +		to_chat(owner, "Your bindings are gone!")
could add some italics tbh

2022-04-06 23:13 UTC, tattax commented on code/modules/mining/lavaland/necropolis_chests.dm
> +/obj/item/melee/knuckles
```suggestion
#define COOLDOWN 150
#define COOLDOWN_HUMAN 100
#define COOLDOWN_ANIMAL 60
/obj/item/melee/knuckles
```

2022-04-06 23:13 UTC, tattax commented on code/modules/mining/lavaland/necropolis_chests.dm
> +	var/cda = 60
```suggestion
```

2022-04-06 23:13 UTC, tattax commented on code/modules/mining/lavaland/necropolis_chests.dm
> +		next_reach = world.time + cooldown
```suggestion
		next_reach = world.time + COOLDOWN
```

2022-04-06 23:13 UTC, tattax commented on code/modules/mining/lavaland/necropolis_chests.dm
> +		next_grip = world.time + cooldown
```suggestion
		next_grip = world.time + COOLDOWN
		#undef COOLDOWN
		#undef COOLDOWN_HUMAN
		#undef COOLDOWN_ANIMAL
```

2022-04-06 23:13 UTC, tattax commented on code/modules/mining/lavaland/necropolis_chests.dm
> +				next_knuckle = world.time + cda
```suggestion
			if(ishuman(L))
				next_knuckle = world.time + COOLDOWN_HUMAN
				return
			next_knuckle = world.time + COOLDOWN_ANIMAL
```

2022-04-07 06:00 UTC, ToasterBiome requested changes, later dismissed

2022-04-07 06:00 UTC, ToasterBiome commented on code/datums/status_effects/knuckleroot.dm
> +	duration = 10
```suggestion
	duration = 1 SECONDS
```

2022-04-07 06:00 UTC, ToasterBiome commented on code/datums/status_effects/debuffs.dm
> +    duration = 100
```suggestion
    duration = 10 SECONDS
```

2022-04-07 06:00 UTC, ToasterBiome commented on code/datums/status_effects/knuckleroot.dm
> +		duration = 60
```suggestion
		duration = 6 SECONDS
```

2022-04-07 22:46 UTC, KillerOrcaCora commented
Doing gods work amen.

2022-04-10 12:17 UTC, JamieD1 commented
@grimm-hollowknight

2022-04-10 20:40 UTC, grimm-hollowknight approved these changes

2022-04-11 17:11 UTC, merged