Ports "Tribal crafting expansion" and "Adds bamboo walls, stools, benches, recolours and resprites existing bamboo items"
yogstation13/Yogstation pull request #13634
Opened 2022-04-08 03:04 UTC by nmajask

# Document the changes in your pull request

Ports a few PRs from Bee, and adds a few new things as well:

- ["Tribal crafting expansion" #1802](https://github.com/BeeStation/BeeStation-Hornet/pull/1802) by [Flakkyboo](https://github.com/Flakkyboo)
- ["Tribal crafting expansion" #1802](https://github.com/BeeStation/BeeStation-Hornet/pull/1802) by [Pirill](https://github.com/Pirill)

# Wiki Documentation

Probably a lot of stuff. 

# Changelog

:cl:  Flakkyboo, Pirill
rscadd: Added a new Watcher bola, quiver, wood bow, pipe bow, bone bow, energy bow, clockwork bow, heavy bone armor, bamboo walls, mats, benches, stools and a headspike variant.
rscadd: Added many new arrow types.
imageadd: added some new icons and for may tribal and bamboo items 
/:cl:

2022-04-08 03:13 UTC, Marmio64 commented
watcher bolas sound like a terrible idea that will make it even easier for ashwalkers to oneshot miners if they are good
we already have a 'heavy' version of bone armor, its called chitin armor. Chitin armor even requires bone armor to be made.

Lastly, this holds no sway but any higher tier items perhaps could be restricted behind ashy resin to add more value to making it?

2022-04-08 03:47 UTC, maxion12345 commented
> watcher bolas sound like a terrible idea that will make it even easier for ashwalkers to oneshot miners if they are good we already have a 'heavy' version of bone armor, its called chitin armor. Chitin armor even requires bone armor to be made.
> 
> Lastly, this holds no sway but any higher tier items perhaps could be restricted behind ashy resin to add more value to making it?

me when the miners two-shot my ashwalker character with dual wield max damage kpa's before throwing gibonite at the tendril and tanking the damage with their box full of legion cores before summoning an ash storm with the lava staff and surviving thanks to their enviro bag

2022-04-08 04:11 UTC, Marmio64 commented
> > watcher bolas sound like a terrible idea that will make it even easier for ashwalkers to oneshot miners if they are good we already have a 'heavy' version of bone armor, its called chitin armor. Chitin armor even requires bone armor to be made.
> > Lastly, this holds no sway but any higher tier items perhaps could be restricted behind ashy resin to add more value to making it?
> 
> me when the miners two-shot my ashwalker character with dual wield max damage kpa's before throwing gibonite at the tendril and tanking the damage with their box full of legion cores before summoning an ash storm with the lava staff and surviving thanks to their enviro bag

counterpoint: the miner would have to spend half an hour crafting, mining, and killing shit to get to such a point while an ashwalker would spear one random watcher and have the means to game end you in one click in combination with some spear throws. In addition, if an ashwalker kills a miner it is more often than not perma death for that miner, if a miner kills an ashwalker they can just respawn. Final point, the miners have space age tech and are highly trained explorers, they SHOULD have a big advantage. Ashwalkers are on the defensive and need to ambush miners and set up traps to get the edge over them. Making it be a snare trap bola would be much more reasonable.

2022-04-08 04:17 UTC, nmajask commented
> counterpoint: the miner would have to spend half an hour crafting, mining, and killing shit to get to such a point while an ashwalker would spear one random watcher and have the means to game end you in one click in combination with some spear throws. In addition, if an ashwalker kills a miner it is more often than not perma death for that miner, if a miner kills an ashwalker they can just respawn. Final point, the miners have space age tech and are highly trained explorers, they SHOULD have a big advantage. Ashwalkers are on the defensive and need to ambush miners and set up traps to get the edge over them. Making it be a snare trap bola would be much more reasonable.

It also costs two goliath plates and its for an item that can easily be missed and/or taken from you on use. Also, its intended to be used to fight fauna as well.

2022-04-08 04:43 UTC, Marmio64 commented
> > counterpoint: the miner would have to spend half an hour crafting, mining, and killing shit to get to such a point while an ashwalker would spear one random watcher and have the means to game end you in one click in combination with some spear throws. In addition, if an ashwalker kills a miner it is more often than not perma death for that miner, if a miner kills an ashwalker they can just respawn. Final point, the miners have space age tech and are highly trained explorers, they SHOULD have a big advantage. Ashwalkers are on the defensive and need to ambush miners and set up traps to get the edge over them. Making it be a snare trap bola would be much more reasonable.
> 
> It also costs two goliath plates and its for an item that can easily be missed and/or taken from you on use. Also, its intended to be used to fight fauna as well.

still of the opinion that some things should be locked behind having to find needed resources, like bolas being locked behind having to find somewhere that has cable. Both because it regulates their power and 

> > counterpoint: the miner would have to spend half an hour crafting, mining, and killing shit to get to such a point while an ashwalker would spear one random watcher and have the means to game end you in one click in combination with some spear throws. In addition, if an ashwalker kills a miner it is more often than not perma death for that miner, if a miner kills an ashwalker they can just respawn. Final point, the miners have space age tech and are highly trained explorers, they SHOULD have a big advantage. Ashwalkers are on the defensive and need to ambush miners and set up traps to get the edge over them. Making it be a snare trap bola would be much more reasonable.
> 
> It also costs two goliath plates and its for an item that can easily be missed and/or taken from you on use. Also, its intended to be used to fight fauna as well.

still of the opinion that encouraging bola combat will be unfun. also it seems like they're rather expensive then, they can be really powerful but you can also make bolas from cable coil (which at least is limited on lavaland) and metal so if you make them too expensive they'll only be used by robust players to destroy miners and then be unable to be used well by lower end players.

2022-04-08 04:46 UTC, Marmio64 commented
> > counterpoint: the miner would have to spend half an hour crafting, mining, and killing shit to get to such a point while an ashwalker would spear one random watcher and have the means to game end you in one click in combination with some spear throws. In addition, if an ashwalker kills a miner it is more often than not perma death for that miner, if a miner kills an ashwalker they can just respawn. Final point, the miners have space age tech and are highly trained explorers, they SHOULD have a big advantage. Ashwalkers are on the defensive and need to ambush miners and set up traps to get the edge over them. Making it be a snare trap bola would be much more reasonable.
> 
> It also costs two goliath plates and its for an item that can easily be missed and/or taken from you on use. Also, its intended to be used to fight fauna as well.

still of the opinion that bola combat is unfun and encouraging it by making it more accessible isn't a good idea.

2022-04-08 05:42 UTC, TymurShatillo approved these changes
CLOCKWORK BOW

2022-04-08 13:39 UTC, SomeguyManperson commented
Ashwalkers can already make bolas you clowns

2022-04-08 17:31 UTC, TymurShatillo commented
Okay i actually love this, but making kindle work only on not mindshielded people is bad.

2022-04-08 19:55 UTC, Marmio64 commented
> Ashwalkers can already make bolas you clowns

Yes but you need to find cable coil, which can be troublesome to find on lavaland which at least places a restriction on them.

2022-04-14 04:47 UTC, SomeguyManperson commented
> > Ashwalkers can already make bolas you clowns
> 
> Yes but you need to find cable coil, which can be troublesome to find on lavaland which at least places a restriction on them.

Uses cable cuffs which watcher sinew cuffs are conveniently a subtype of
The hardest part is getting 6 metal but that just requires finding an iron vein and throwing ores into lava

2022-04-16 13:42 UTC, TymurShatillo commented
Why

2022-05-12 17:00 UTC, Anvilman6 requested changes
Initial pass syntax and grammar updates

2022-05-12 17:00 UTC, Anvilman6 commented on code/datums/components/crafting/crafting.dm
> +		// Check we have the appropriate ammount avalible in the contents list
Beestation illiteracy in the comments section

2022-05-12 17:00 UTC, Anvilman6 commented on code/datums/components/crafting/guncrafting.dm
> +	desc = "A long piece of Silk that looks like a cable coil."
```suggestion
	desc = "A long piece of silk, which looks like a cable coil."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/datums/status_effects/debuffs.dm
> +		owner.visible_message(span_warning("[owner] easily brakes out of \the [original_legcuffs]"), span_warning("You easily brake out of \the [original_legcuffs]"))
```suggestion
		owner.visible_message(span_warning("[owner] easily breaks out of \the [original_legcuffs]"), span_warning("You easily break out of \the [original_legcuffs]"))
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/game/objects/items/handcuffs.dm
> +	name = "watcher Bola"
```suggestion
	name = "watcher bola"
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/game/objects/items/handcuffs.dm
> +	desc = "A Bola made from the stretchy sinew of fallen watchers."
```suggestion
	desc = "A bola made from the stretchy sinew of fallen watchers."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/clothing/shoes/miscellaneous.dm
> +	desc = "These make your feet feel snug and secure, while still being breathable and light."
```suggestion
	desc = "These make your feet feel well protected and plated."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/clothing/shoes/miscellaneous.dm
> +	desc = "These make your feet feel snug and secure, while still being breathable and light."
```suggestion
	desc = "These make your feet feel like they're wrapped in sandpaper. Positively draconian!"
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/clothing/shoes/miscellaneous.dm
> +	desc = "These make your feet feel snug and secure, while still being breathable and light."
```suggestion
	desc = "These make your feet feel like they're wrapped in wet oily sandpaper. Disgusting, but oddly comfortable."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/clothing/suits/armor.dm
> +	desc = "A staunch, practical cape made out of numerous monster materials, it is coveted amongst exiles & hermits."
```suggestion
	desc = "A staunch, practical cape made out of numerous monster materials. It is coveted amongst exiles and hermits."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/clothing/suits/armor.dm
> +	desc = "A protective & concealing hood."
```suggestion
	desc = "A protective, concealing hood."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/clothing/suits/armor.dm
> +	desc = "An intimidating tribal helmet, it doesn't look very comfortable."
```suggestion
	desc = "An intimidating tribal helmet! It doesn't look very comfortable."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/clothing/under/accessories.dm
> +	desc = "For the last time. IT'S A KILT not a skirt."
```suggestion
	desc = "A revolting piece of clothing made from sinew. Arguably, it is a kilt, not a skirt."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/projectiles/ammunition/caseless/arrow.dm
> +	desc = "An arrow made from wood. a bola is wrapped around it."
```suggestion
	desc = "An arrow made from wood, with a bola wrapped around it."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/projectiles/ammunition/caseless/arrow.dm
> +	desc = "An arrow made from wood. an explosive is attached to it."
```suggestion
	desc = "An arrow made from wood. An explosive is attached to it."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/projectiles/ammunition/caseless/arrow.dm
> +	desc = "An arrow made from hardlight."
```suggestion
	desc = "A hardlight arrow."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/projectiles/ammunition/caseless/arrow.dm
> +	desc = "An arrow made from hardlight. This one stuns the victim in a non-lethal way."
```suggestion
	desc = "A modified hardlight arrow. This one stuns the victim non-lethally."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/projectiles/ammunition/caseless/arrow.dm
> +	desc = "An arrow made from hardlight. This one can destroy most obstructions in one hit."
```suggestion
	desc = "A modified hardlight arrow. This one is extremely powerful, and can destroy most obstructions in a single shot."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/projectiles/ammunition/caseless/arrow.dm
> +	desc = "An arrow made from hardlight. This one can pass through obstructions."
```suggestion
	desc = "A modified hardlight arrow. This one can pass right through obstructions."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/projectiles/guns/ballistic/bow.dm
> +	desc = "A modern bow that can fabricate hardlight arrows using an internal energy. This one is designed for silent takedowns of targets by the syndicate."
```suggestion
	desc = "A modern bow that can fabricate hardlight arrows using internal energy. This one is designed by the Syndicate for silent takedowns."
```

2022-05-12 17:00 UTC, Anvilman6 commented on code/modules/projectiles/guns/ballistic/bow.dm
> +	desc = "A modern bow that can fabricate hardlight arrows using an internal energy."
```suggestion
	desc = "A modern bow that can fabricate hardlight arrows using internal energy."
```

2022-05-15 15:53 UTC, SomeguyManperson commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	loom_result = /obj/item/stack/sheet/silk
```suggestion
	is_fabric = TRUE
	pull_effort = 2 SECONDS
	loom_result = /obj/item/stack/sheet/silk
```

2022-05-16 12:50 UTC, grimm-hollowknight approved these changes

2022-05-16 13:29 UTC, SomeguyManperson commented on code/modules/antagonists/clockcult/clock_scriptures/scripture_scripts.dm
> +	quickbind_desc = "Creates a Judicial Visor, which can smite an area, applying Belligerent and briefly stunning."
a

2022-05-16 13:48 UTC, SomeguyManperson commented on code/modules/clothing/under/accessories.dm
> +	above_suit = TRUE
```suggestion
```

2022-05-16 15:00 UTC, SomeguyManperson commented on code/datums/components/crafting/tailoring.dm
> +	result = /obj/effect/spawner/lootdrop/lizardboots
a

2022-05-16 15:00 UTC, SomeguyManperson commented on code/datums/components/crafting/tailoring.dm
> +	result = /obj/effect/spawner/lootdrop/lizardboots
also a

2022-05-18 00:42 UTC, Georgeur commented
the normal arrows and fire hardened arrows use the same path so the recipe for fire hardened arrows turns them into normal arrows 
/obj/item/projectile/bullet/reusable/arrow/ash

2022-05-18 06:09 UTC, j8uj8u commented
Thoughts on poison tipped arrows?

Dipping an arrow in a beaker coats the arrow tip with whatever was in the beaker.
Getting shot by the arrow will transfer some of that fluid to you. (5u maybe 10u)

2022-05-19 15:35 UTC, Skrem7 commented
> Thoughts on poison tipped arrows?
> 
> Dipping an arrow in a beaker coats the arrow tip with whatever was in the beaker. Getting shot by the arrow will transfer some of that fluid to you. (5u maybe 10u)

Should be a specific type of crafted arrow that significantly reduces its force, AP, and embed chance, what have you. If you're able to throw reagents onto a chitin arrow which is 20 force + 30 AP + 0.8 embed and you put some real dangerous stuff on that arrow you've basically won the fight by landing one ranged attack.

Chemists already have syringe guns and botanists get to throw their prickly shit at people, I don't want to enable the latter to shoot un-catchable projectiles that have a good chance of simply removing me from the round with zero counterplay. Make it a ghetto syringe gun and I'd be a lot more fine with it, would be in-character and cool to be able to rub plants on your arrows before firing them. Shotgun darts are a good example of this in that they don't really work against armor.

I have zero desire to see something added that gives even more powercreep to chemistry/botany as they currently stand, unless, as I said, it were more of a ghetto syringe gun.

2022-05-20 15:36 UTC, Skrem7 reviewed
Terrible terrible balancing ideas.

Tries to give each arrow more of a specific niche while trying to make some things less of a straight upgrade. 100% subject to feedback and change.

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	var/fauna_damage_bonus = 0
```suggestion
	var/fauna_damage_bonus = 20
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	var/break_chance = 0
```suggestion
	var/break_chance = 10
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	damage = 30
```suggestion
	damage = 25
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	embed_chance = 0.6
```suggestion
	embed_chance = 0.3
	break_chance = 0
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	embed_chance = 0.2
```suggestion
	embed_chance = 0.4
	break_chance = 0
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	armour_penetration = 20
```suggestion
	armour_penetration = 15
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	fauna_damage_bonus = 20
```suggestion
	fauna_damage_bonus = 30
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	embed_chance = 0.2
```suggestion
	embed_chance = 0.6
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	break_chance = 20
```suggestion
	break_chance = 50
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	embed_chance = 0.8
```suggestion
	embed_chance = 0.5
	break_chance = 0
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	damage = 10
```suggestion
	damage = 8
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	fauna_damage_bonus = 25
```suggestion
	fauna_damage_bonus = 27
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	embed_chance = 0.5
```suggestion
	embed_chance = 0.7
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	break_chance = 30
```suggestion
	break_chance = 67
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	embed_chance = 0.3
```suggestion
	embed_chance = 0.3
	break_chance = 10
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	armour_penetration = 10
```suggestion
	armour_penetration = 40
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	embed_chance = 0.3
```suggestion
	embed_chance = 0.5
```

2022-05-20 15:36 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	embed_chance = 0.3
```suggestion
	embed_chance = 0.5
```

2022-05-20 15:37 UTC, Skrem7 commented
> Terrible terrible balancing ideas.
> 
> Tries to give each arrow more of a specific niche while trying to make some things less of a straight upgrade. 100% subject to feedback and change.

I think I did not realize I could highlight overall changes so fucking lmao time for a wall of text

2022-05-20 17:05 UTC, AffectedArc07 commented
Put `[IDB IGNORE]` in your PR title or the repo will be blacklisted.

You crashed the bot 4 times.
![image](https://user-images.githubusercontent.com/25063394/169577980-b33a8851-6413-41ea-bd49-9e005869368c.png)

2022-05-20 17:10 UTC, nmajask commented
That good? I'll atomize this down when I get home.

2022-05-20 17:10 UTC, AffectedArc07 commented
> That good? I'll atomize this down when I get home.

Perfect

2022-05-21 20:22 UTC, Marmio64 commented
The bikini starter suit looks really dumb and more like Skyrim or some shit than ss13. Unlike argonians our lizards don't need a bikini. A long loin cloth seems far more fitting though honestly I loved the old gladiator outfit a lot and would just prefer that for most outfits. Many of the new clothes look too pompous and tame to be fitting with ashwalker, who just like shiny stones and gnarly bone suits

2022-05-22 23:43 UTC, Marmio64 commented
also this seems to give them a bunch of free bone spears, bows/arrows, and a helmet right off the bat, kind of nullifying a big piece of progression, along with making marrow weavers a joke right off the bat (though the +1 range update for spears also kind of helped to do that already).

2022-05-23 02:53 UTC, Skrem7 reviewed
Second round of balance changes

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	damage = 10
```suggestion
	damage = 15
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	damage = 20
```suggestion
	damage = 45
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	damage = 20
```suggestion
	damage = 25
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	damage = 10
```suggestion
	damage = 15
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	damage = 8
```suggestion
	damage = 10
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	fauna_damage_bonus = 27
```suggestion

```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	damage = 20
```suggestion
	damage = 25
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	damage = 10
```suggestion
	damage = 15
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow/bone_tipped //AP for ashwalkers
```suggestion
/obj/item/projectile/bullet/reusable/arrow/bone_tipped //Highest damage; fully upgraded normal arrow, simply well-crafted
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow/bone
```suggestion
/obj/item/projectile/bullet/reusable/arrow/bone //Cheap, easy to make in bulk but mostly capable of being used to hunt fauna
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow/chitin
```suggestion
/obj/item/projectile/bullet/reusable/arrow/chitin //Most expensive arrow, but powerful for those who put in the time. Greater AP alternative to bone-tipped. Very robust against fauna.
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow/ash
```suggestion
/obj/item/projectile/bullet/reusable/arrow/ash //Fire-tempered head makes it tougher; more damage, but less likely to shatter and embed
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow
```suggestion
/obj/item/projectile/bullet/reusable/arrow //Base arrow. Good against fauna, not perfect, but well-rounded.
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow/bamboo
```suggestion
/obj/item/projectile/bullet/reusable/arrow/bamboo //Very brittle, very fragile, but very potent at splintering into targets assuming it isn't broken on impact
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow/bronze
```suggestion
/obj/item/projectile/bullet/reusable/arrow/bronze //Inferior metal. Slightly better than ashen
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	break_chance = 20
```suggestion
	break_chance = 33
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow/glass
```suggestion
/obj/item/projectile/bullet/reusable/arrow/glass //Fragile, but sharp and light. Not as effective as metal but cheaper.
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow/glass/plasma
```suggestion
/obj/item/projectile/bullet/reusable/arrow/glass/plasma //Immensely capable of puncturing through materials; plasma is a robust material, more capable of slicing through protection
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	armour_penetration = 40
```suggestion
	armour_penetration = 50
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	break_chance = 50
```suggestion
	break_chance = 10
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	armour_penetration = 30
```suggestion
	armour_penetration = 35
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	armour_penetration = 15
```suggestion
	armour_penetration = 20
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	embed_chance = 0.6
```suggestion
	embed_chance = 0.33
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	break_chance = 10
```suggestion
	break_chance = 0
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow/bola
```suggestion
/obj/item/projectile/bullet/reusable/arrow/bola //More of a blunt impact of the bola, still an arrow. Only able to be crafted with makeshift weaponry
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/bullet/reusable/arrow/flaming
```suggestion
/obj/item/projectile/bullet/reusable/arrow/flaming //Normal arrow, but it also sets people on fire. Simple
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/energy/arrow
```suggestion
/obj/item/projectile/energy/arrow //Hardlight projectile. Slightly more robust than a standard laser. Capable of hardening in target's flesh
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/energy/arrow/disabler
```suggestion
/obj/item/projectile/energy/arrow/disabler //Hardlight projectile. Forceful impact makes the impact more draining than a standard disabler. Needs to be competitive in DPS
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +/obj/item/projectile/energy/arrow/xray
```suggestion
/obj/item/projectile/energy/arrow/xray //Slightly weakened arrow capable of passing through material; also irradiates targets moderately
```

2022-05-23 02:53 UTC, Skrem7 commented on code/datums/components/crafting/weapons.dm
> +				/obj/item/stack/sheet/sinew = 2,
```suggestion
				/obj/item/stack/sheet/sinew = 1,
```

2022-05-23 02:53 UTC, Skrem7 commented on code/datums/components/crafting/weapons.dm
> +				/obj/item/stack/sheet/animalhide/weaver_chitin = 3)
```suggestion
				/obj/item/stack/sheet/animalhide/weaver_chitin = 2)
```

2022-05-23 02:53 UTC, Skrem7 commented on code/datums/components/crafting/weapons.dm
> +				/obj/item/stack/sheet/silk = 1,
```suggestion
				/obj/item/stack/sheet/cloth = 1,
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +		var/mob/living/carbon/M = target
```suggestion
		var/mob/living/carbon/M = target
		M.apply_damage(10, BURN)
```

2022-05-23 02:53 UTC, Skrem7 commented on code/modules/projectiles/projectile/reusable/arrow.dm
> +	fauna_damage_bonus = 30
```suggestion
	fauna_damage_bonus = 35
```

2022-05-28 23:32 UTC, JamieD1 commented on code/modules/projectiles/boxes_magazines/_box_magazine.dm
>  		return b
```suggestion
		stored_ammo -= b
		if (keep)
			stored_ammo.Insert(1,b)
		return b
```

2022-06-11 13:58 UTC, JamieD1 approved these changes
Can add fixes after merge if required

2022-06-11 13:58 UTC, merged