Combat mechs now punch you across the room instead of winning in one click
yogstation13/Yogstation pull request #13635
Opened 2022-04-08 03:59 UTC by Sniblet

# Document the changes in your pull request

Literally abductor batons but faster and they do 40 brute
This copypastes the home-run bat's flinging code onto the mecha punch, replaces the sleep with a knockdown, and halves said knockdown's duration. If you pin someone against a wall with this you still just win, but we're closer to a good place.

- [ ] tested
- [ ] works

# Wiki Documentation

If the wiki even mentions the incredible power of mech melee, that will need an update

# Changelog

:cl:   
tweak: In response to complaints, combat mecha punching arms now have reduced respect for Newtonian physics.
tweak: the above means that combat mechs now fling and knockdown you instead of sleeping you
/:cl:

2022-04-08 04:01 UTC, maxion12345 commented
on one hand, you got close to the massive combat mech chief you should get punched to death
on the other hand, it's a pretty bullshit way to die. maybe keep it for some of the expensive, slow mechs?

2022-04-08 04:04 UTC, Sniblet commented
> on one hand, you got close to the massive combat mech chief you should get punched to death

Every xeno queen would like to speak to you
You can still get punched to death because the fist still does _40 brute damage_ but it should not win in one click under any circumstances, which it does

2022-04-08 05:06 UTC, Sniblet commented
I think the throw might require me building infrastructure that I don't know how to build
I'm looking at all these throw_at things we have and they all seem to require me doing some serious indenting action and maybe the mech punch also needs to be an obj or a datum or something? And none of them are in living_defense why is this in living_defense
uuuuu

2022-04-08 05:30 UTC, Sniblet commented
What do you mean it was that easy
I'll test it tomorrow afternoon or so

2022-04-09 08:58 UTC, TheGamerdk requested changes, later dismissed

2022-04-09 08:58 UTC, TheGamerdk commented on code/modules/mob/living/living_defense.dm
> +/mob/living/mech_melee_attack(obj/mecha/M, mob/living/A)
not how this works, 
```suggestion
/mob/living/mech_melee_attack(obj/mecha/M)
```

2022-04-09 08:58 UTC, TheGamerdk commented on code/modules/mob/living/living_defense.dm
> +			var/throwtarget = get_edge_target_turf(A, get_dir(A, get_step_away(M, A)))
replace all mention of A with src

2022-04-09 16:40 UTC, Sniblet commented
It still just knocks them back one tile
Even with the step_away line removed
hmm

2022-04-10 12:30 UTC, JamieD1 commented
@SomeguyManperson

2022-04-13 09:18 UTC, TymurShatillo approved these changes

2022-04-16 22:28 UTC, SomeguyManperson commented on code/modules/mob/living/carbon/human/human_defense.dm
> +						Knockdown(15)//the victim could get up before getting hit again
```suggestion
						Knockdown(1.5 SECONDS)//the victim could get up before getting hit again
```

2022-04-16 22:28 UTC, SomeguyManperson approved these changes

2022-04-16 23:17 UTC, merged