Podperson passive healing nerf and light feeding tweaks
yogstation13/Yogstation pull request #13675
Opened 2022-04-11 01:03 UTC by Chubbygummibear

Any amount of free passive healing is strong, so i'm cutting it in half. I've seen the Phytosian passive healing get complained about a number of times but no one ever does anything about it (also Truz asked me to nicely so i'm doing it), so i'm shooting myself and my people in the foot to hopefully put an end to it. The other change is that feeding from light is reduced from full to fed. and lower light levels drain your nutrition more. This is just a ~~buff~~ tweak.

# Wiki Documentation

I don't think wiki had the actual healing values or feeding values, so nothing if that's the case.

# Changelog

:cl:  
tweak: podperson healing cut by 50% across the board  
tweak: podperson feeding off light is also reduced, so we can finally eat and not suffer heart failure and obesity for existing
/:cl:

2022-04-11 03:55 UTC, ShatteredParadox commented
Imagine nerfing a species that gets husked in like 6 strikes of a welder.

2022-04-11 21:46 UTC, JamieD1 commented
@SomeguyManperson

2022-04-12 03:44 UTC, Marmio64 commented
only time i've ever had a problem when going up against a podperson is when im in a floor tile throwing or punching contest with one. If you genuinely want to kill a podperson  you can just use a welder, lasergun, or light them on fire to kill them fast. Considering they're also slower than other roundstart races and can be outran, i'd say the decent passive healing is fine. The hunger changes do sound nice though (albeit they remove a quirk of them and an easy way to troll them), i've not played podperson very many times but it can be annoying to not be able to eat anything.

2022-04-12 14:29 UTC, Simplehorror commented
The only time this healing comes into play is if they were crit by environmental forces, and the healing does not even fix wounds. How about making it so they need CO2 to heal?

2022-04-15 05:55 UTC, neeshacark commented
please god don't merge this.

plantpeople have SEVERE weakness to burn and I've never seen anyone who's been playing for longer than a month complain about this because it's so easy to kill a pod if you burn them and make sure they're in hardcrit or dead.

podperson healing does not need a nerf, the downsides of podpeople easily make up for this strength.

2022-04-15 20:39 UTC, Reed0506 commented
While I dont think needing to use sugar to heal at a decent rate is a bad thing, I do think just slashing the already extremely situational weak healing could be used to implement a small buff. Pod nutrition on the other hand being toned down is great, and might alleviate the negative moodlets that being """fat""" by happen by existing. Also, if this healing nerf makes pods unable to fully resist the toxin damage of romerol tumors, that really sucks, as it is one of the only upsides of playing pod.

2022-04-16 22:32 UTC, SomeguyManperson commented
atomize this into a pr for nutrition and one for the healing

2022-04-16 23:07 UTC, Chubbygummibear commented
> atomize this into a pr for nutrition and one for the healing

should i close this one and open two, or take the nutrition out of this and make just 1 new pr for that?

2022-04-17 00:50 UTC, Chubbygummibear commented
This is now just about the healing nerf and the light feeding tweaks are in #13756

2022-04-17 02:45 UTC, adamsong requested changes
First, I hate this change
Second, if you are going to do it, make sure you set it back properly when sugar wears off

2022-04-17 03:56 UTC, Chubbygummibear commented
> First, I hate this change Second, if you are going to do it, make sure you set it back properly when sugar wears off

should be taken care of since theos made me use a more dynamic method of setting it back to the initial multiplier in the sugar bugfix here #13748. i didn't want to touch it here because i didn't want this pr doing like the same thing with sugar

2022-04-17 18:53 UTC, SomeguyManperson commented
Pods are already weaker+slower than other races so having passive healing isnt particularly powerful, especially considering the ease of access to weapons that can deal burn damage

2022-04-17 18:53 UTC, closed without merging