Adds Nmajask to the game
yogstation13/Yogstation pull request #13721
Opened 2022-04-13 20:55 UTC by ToasterBiome

# Document the changes in your pull request

He's been maintainer for uhh idk 

# Wiki Documentation

we have a list of maintainers on wiki

:cl:  
rscadd: Nmajask is in the game now
/:cl:

2022-04-13 21:01 UTC, nmajask commented
Bad PR

2022-04-13 21:49 UTC, Chubbygummibear commented
next i want a nmajask plush in the modular console vendor that you can only get by inserting a coin for the premium items

2022-04-14 10:20 UTC, adamsong requested changes, later dismissed

2022-04-14 10:20 UTC, adamsong commented on html/changelog.html
> +			<font size='2'><b>Maintainers:</b> AshCorr, Identification, Monster860, Partheo, Asd, TheGamerdk, adamsogm, baiomu, Nmajask<br></font>
This is overwritten by header.html

2022-04-14 16:22 UTC, JamieD1 approved these changes

2022-04-14 16:22 UTC, merged

2022-04-14 16:28 UTC, Moja10 commented
> Bad PR

Can we unmerge? They don't want it. Do not lecture me about the word unmerge

2022-04-14 19:35 UTC, ToasterBiome commented on html/changelog.html
> +			<font size='2'><b>Maintainers:</b> AshCorr, Identification, Monster860, Partheo, Asd, TheGamerdk, adamsogm, baiomu, Nmajask<br></font>
> This is overwritten by header.html

should it be removed?

2022-04-14 23:43 UTC, ToasterBiome commented
> > Bad PR
> 
> Can we unmerge? They don't want it. Do not lecture me about the word unmerge

i do believe this is what someone calls a joke