Fixes Janitor tile not being correct (Fixes #13743)
yogstation13/Yogstation pull request #13744
Opened 2022-04-15 16:45 UTC by Readystorm546

Fixes #13743

:cl:   
bugfix: Janitor closet turf was no in the janitor closet.
/:cl:

2022-04-15 17:25 UTC, adamsong requested changes, later dismissed
Not map merged

2022-04-15 17:43 UTC, Readystorm546 commented
> Not map merged

Sorry im a boomer

2022-04-15 17:46 UTC, adamsong requested changes

2022-04-15 17:46 UTC, adamsong commented on _maps/map_files/Yogsmeta/Yogsmeta.dmm
> +/mob/living/simple_animal/bot/secbot/pingsky,
Undocumented change

2022-04-16 22:34 UTC, JamieD1 approved these changes

2022-04-16 22:35 UTC, merged