Adds a xenobio wiki book
yogstation13/Yogstation pull request #13757
Opened 2022-04-17 02:43 UTC by MajManatee

# Document the changes in your pull request

Adds a book to xenobiology, allowing you to not have to spend a year and a half trying to type out "feed slime" but in much more complex terms.

# Wiki Documentation

The book needs to be added somewhere.

# Changelog

:cl:  
rscadd: Adds a wiki book to xenobio, to help teach new people.
/:cl:

2022-04-17 03:11 UTC, alexkar598 commented
Watching in order to move protect the page on merge

2022-04-17 03:30 UTC, MajManatee commented
idk what that means, but... thanks?

2022-04-18 15:55 UTC, JamieD1 commented
@grimm-hollowknight

2022-04-18 18:16 UTC, grimm-hollowknight approved these changes

2022-04-18 18:29 UTC, alexkar598 commented
> idk what that means, but... thanks?

It means flagging the page in sort that noone can delete or rename it without my approval to prevent the book from breaking

2022-04-19 17:58 UTC, Anvilman6 requested changes
Title change suggestion, make sure that the name and title fields are unified in either case

2022-04-19 17:58 UTC, Anvilman6 commented on yogstation/code/game/objects/items/manuals.dm
> +	name = "Crossbreeding: A Simpletons guide to slimey stuff."
name = "Crossbreeding: The Definitive Guide to Slimy Stuff"

2022-04-19 17:58 UTC, Anvilman6 commented on yogstation/code/game/objects/items/manuals.dm
> +	title = "Crossbreeding: A simpletons guide to slimey stuff."
title = "Crossbreeding: The Definitive Guide to Slimy Stuff"

2022-04-23 06:40 UTC, ToasterBiome requested changes
merge conflict

2022-04-23 06:55 UTC, MajManatee commented
i HATE merge conflicts

2022-04-23 06:55 UTC, closed without merging