AI can now use vending machines
yogstation13/Yogstation pull request #13810
Opened 2022-04-20 14:51 UTC by Simplehorror

# Document the changes in your pull request

It feels strange that the ship computer can't dispense a cola. Now you can ask the AI to dispense that life saving medical spray instead of waiting for your paycheck. Wonder if this could be integrated with corporate? :P

# Changelog

:cl:  
tweak: The AI has finally finished reverse engineering the vending machine subsystems
/:cl:

2022-04-20 14:52 UTC, Bibby0110 commented
Make it an AI upgrade

2022-04-20 14:53 UTC, Simplehorror commented
> Make it an AI upgrade

Good idea, gimmie a second

For anyone concerned about the AI being abused to dispense items for free; it's no different than the AI being abused for access and is mostly a security issue. It's also an indication that the economy is unbalanced if the AI is constantly being used to dispense, and I was never a big fan of it.

2022-04-20 14:53 UTC, bruhlookatthisdood commented
Hear me out (have fun trying to make this work)
If AI dispenses from med vendor, subtracts the cost from med budget
Dispensing from science vendors, Sci budget, ect.
Seems like a better solution than to just make everything free for them, especcialy things like the advanced medkits in medical lockers
If you dont I see a possible abuse of the corprat lawset where they will just dispense everything from the vendors round start to "save costs" so no one has to waste money.

2022-04-20 14:54 UTC, Simplehorror commented
> Hear me out (have fun trying to make this work) If AI dispenses from med vendor, subtracts the cost from med budget Dispensing from science vendors, Sci budget, ect.

If I do this it might be in another PR because I'll have to edit tgui because the AI doesn't have a card and vending machines stupidly want you to have a card

2022-04-20 15:00 UTC, LoliconSlayer commented
Who?

2022-04-20 15:10 UTC, Bibby0110 requested changes
This turns it into a passive upgrade (No RAM usage) which seems more fair.
If you don't want it to be passive just do the name change

2022-04-20 15:10 UTC, Bibby0110 commented on code/modules/mob/living/silicon/ai/decentralized/projects/vending_machine.dm
> +	ram_required = 1
```suggestion
	can_be_run = FALSE
```

2022-04-20 15:10 UTC, TheGamerdk commented on code/modules/mob/living/silicon/ai/decentralized/projects/vending_machine.dm
> +	name = "Unlock vending machines"
Vending Machine Control

2022-04-20 15:10 UTC, Bibby0110 commented on code/modules/mob/living/silicon/ai/decentralized/projects/vending_machine.dm
> +/datum/ai_project/vending_machine/run_project(force_run = FALSE)
```suggestion
/datum/ai_project/vending_machine/finish()
```

2022-04-20 15:10 UTC, TheGamerdk commented on code/modules/mob/living/silicon/ai/decentralized/projects/vending_machine.dm
> +/datum/ai_project/vending_machine/stop()
remove this

2022-04-20 15:10 UTC, Bibby0110 commented on code/modules/mob/living/silicon/ai/decentralized/projects/vending_machine.dm
> +	. = ..()
remove everything but ai.ignores_capitalism = TRUE

2022-04-20 15:56 UTC, Simplehorror commented
Done

2022-04-20 17:19 UTC, TheGamerdk approved these changes

2022-04-20 19:59 UTC, SomeguyManperson requested changes
At the very least make sure this won't allow the AI to buy premium items since those are generally balanced around the people who need them actually needing to spend money on them
Otherwise people will roundstart "law 2 ai dump the expensive shit out of the sec/med vendor"

2022-04-21 18:07 UTC, Simplehorror commented
> At the very least make sure this won't allow the AI to buy premium items since those are generally balanced around the people who need them actually needing to spend money on them Otherwise people will roundstart "law 2 ai dump the expensive shit out of the sec/med vendor"

security/admin issue, same issue with AI LAW 2 OPEN TO SPARE

2022-04-22 23:24 UTC, ToasterBiome commented
> > At the very least make sure this won't allow the AI to buy premium items since those are generally balanced around the people who need them actually needing to spend money on them Otherwise people will roundstart "law 2 ai dump the expensive shit out of the sec/med vendor"
> 
> security/admin issue, same issue with AI LAW 2 OPEN TO SPARE

why would we want to code more security/admin issues into the game?

2022-04-23 14:13 UTC, bruhlookatthisdood commented
still suggesting the "anything the ai buys will be taken from the department's budget" idea

2022-04-23 19:09 UTC, Simplehorror commented
> > > At the very least make sure this won't allow the AI to buy premium items since those are generally balanced around the people who need them actually needing to spend money on them Otherwise people will roundstart "law 2 ai dump the expensive shit out of the sec/med vendor"
> > 
> > 
> > security/admin issue, same issue with AI LAW 2 OPEN TO SPARE
> 
> why would we want to code more security/admin issues into the game?

every line of code in this game is an admin issue its the reason we have so many, people will find a way to abuse anything. this will give more benefits to the crew than negatives

2022-04-24 12:40 UTC, JamieD1 commented
> At the very least make sure this won't allow the AI to buy premium items since those are generally balanced around the people who need them actually needing to spend money on them Otherwise people will roundstart "law 2 ai dump the expensive shit out of the sec/med vendor"

Do this

2022-04-24 12:40 UTC, JamieD1 commented
> still suggesting the "anything the ai buys will be taken from the department's budget" idea

Also do this.

2022-04-24 13:13 UTC, bruhlookatthisdood commented
maybe there can be two upgrades?
one is basic vendors and the other is advanced vendors, basic vendors giving access to the smoking machines, soda vendors, ect. and advanced vendors giving access to medical, security, ect.

2022-04-24 13:20 UTC, TheGamerdk commented
> > still suggesting the "anything the ai buys will be taken from the department's budget" idea
> 
> Also do this.

Doesn't actually matter
Budgets will always have enough money

2022-04-24 13:20 UTC, bruhlookatthisdood commented
> > > still suggesting the "anything the ai buys will be taken from the department's budget" idea
> > 
> > 
> > Also do this.
> 
> Doesn't actually matter Budgets will always have enough money (Bar maybe the sec budget on revs/clockies)

give the AI it's own personal bank account

2022-04-24 14:34 UTC, Simplehorror commented
> > At the very least make sure this won't allow the AI to buy premium items since those are generally balanced around the people who need them actually needing to spend money on them Otherwise people will roundstart "law 2 ai dump the expensive shit out of the sec/med vendor"
> 
> Do this
premium items being the ones that cost money even for department members?

2022-04-24 14:37 UTC, Simplehorror commented
> > > > still suggesting the "anything the ai buys will be taken from the department's budget" idea
> > > 
> > > 
> > > Also do this.
> > 
> > 
> > Doesn't actually matter Budgets will always have enough money (Bar maybe the sec budget on revs/clockies)
> 
> give the AI it's own personal bank account

could be funny and incentivise AI as well as giving them a new lawset (maximise your bank)

2022-04-24 17:41 UTC, bruhlookatthisdood commented
> > > > > still suggesting the "anything the ai buys will be taken from the department's budget" idea
> > > > 
> > > > 
> > > > Also do this.
> > > 
> > > 
> > > Doesn't actually matter Budgets will always have enough money (Bar maybe the sec budget on revs/clockies)
> > 
> > 
> > give the AI it's own personal bank account
> 
> could be funny and incentivise AI as well as giving them a new lawset (maximise your bank)

Corporate Greed lawset

2022-04-30 13:10 UTC, JamieD1 commented
How we coming along with this?

2022-05-10 16:23 UTC, closed without merging