Admin fax - Adam fix please
yogstation13/Yogstation pull request #13827
Opened 2022-04-21 14:05 UTC by JamieD1

:cl:  
rscadd: Adds Admin Fax  
/:cl:

2022-04-21 14:10 UTC, Moja10 reviewed
what does flick do

2022-04-21 15:41 UTC, adamsong commented
Works, except for the right clicking

2022-04-21 20:20 UTC, TheGamerdk requested changes
do it for all of them

2022-04-21 20:20 UTC, TheGamerdk commented on code/modules/admin/topic.dm
> +	if(!check_rights(R_ADMIN)) return
```suggestion
	if(!check_rights(R_ADMIN)) 
		return
```

2022-04-21 22:49 UTC, Simplehorror commented on code/modules/admin/topic.dm
> +	minor_announce("Central command has sent a Fax message, this will be printed out at [istype(F) ? F : "all fax machines"]")
```suggestion
	minor_announce("Central command has sent a fax message, this will be printed out at [istype(F) ? F : "all fax machines"].")
```

2022-04-24 13:15 UTC, TheGamerdk requested changes

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/admin/topic.dm
> +	send_admin_fax(null)
```suggestion
	send_admin_fax()
```

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/admin/topic.dm
> +	var/inputsubject = input(src, "Please enter a Subject", "Outgoing message from Centcom", "") as text|null
```suggestion
	var/inputsubject = input(src, "Please enter a subject", "Outgoing message from CentCom", "") as text|null
```

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/admin/topic.dm
> +	if(!inputmessage)	return
break the line

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/admin/topic.dm
> +	var/inputmessage = input(src, "Please enter a message send to [istype(F) ? F : "all fax machines"] via secure connection. Supports pen markdown.", "Outgoing message from Centcom", "") as message|nul
```suggestion
	var/inputmessage = input(src, "Please enter the message sent to [istype(F) ? F : "all fax machines"] via secure connection. Supports pen markdown.", "Outgoing message from CentCom", "") as message|null
```

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/admin/topic.dm
> +	if(!inputsubject)	return
break line

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/admin/topic.dm
> +	if(!inputsigned)	return
break line

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/admin/topic.dm
> +	var/inputsigned = input(src, "Please enter Centcom Offical name.", "Outgoing message from Centcom", usr?.client?.holder?.admin_signature || "") as text|null
```suggestion
	var/inputsigned = input(src, "Please enter CentCom Official name.", "Outgoing message from CentCom", usr?.client?.holder?.admin_signature || "") as text|null
```

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/admin/topic.dm
> +		minor_announce("Central command has sent a fax message, this will be printed out at all fax machines")
```suggestion
		minor_announce("Central Command has sent a fax message, it will be printed out at all fax machines.")
```

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/paperwork/faxmachine.dm
> +				sendcooldown = world.time + 1 MINUTES
we really should start using the COOLDOWN system for these

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/paperwork/faxmachine.dm
> +	if(!check_rights(R_ADMIN)) return
break the line

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/paperwork/faxmachine.dm
> +	if(! (stat & (BROKEN|NOPOWER) ) )
```suggestion
	if(stat & (BROKEN|NOPOWER))
		return
```
early return

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/paperwork/faxmachine.dm
> +/obj/machinery/photocopier/faxmachine/proc/sendFax(var/obj/machinery/photocopier/faxmachine/fax in GLOB.allfaxes)
this didn't work did it?

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/paperwork/faxmachine.dm
> +			P.name = "[command_name()]- [customname]"
```suggestion
			P.name = "[command_name()] - [customname]"
```

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/paperwork/faxmachine.dm
> +			P.stamps += "<br><i>This paper has been stamped by the Central Command Quantum Relay.</i><br>"
```suggestion
			P.stamps += "<br><i>This paper has been verified by the Central Command Quantum Relay.</i><br>"
```
maybe?

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/paperwork/faxmachine.dm
> +	if(IsAdminGhost(user))
only works if you have ai interact on

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/paperwork/faxmachine.dm
> +	if(IsAdminGhost(user))
see above

2022-04-24 13:15 UTC, TheGamerdk commented on code/modules/paperwork/faxmachine.dm
> +		.+= "You can send admin faxes via AltClick to this specific Fax Machine."
```suggestion
		.+= span_notice("You can send admin faxes via Alt-Click to this specific fax machine.")
```

2022-04-30 14:02 UTC, JamieD1 commented on code/modules/admin/topic.dm
> +	if(!inputsubject)	return
```suggestion
	if(!inputsubject)	
		return
```

2022-04-30 14:02 UTC, JamieD1 commented on code/modules/admin/topic.dm
> +	if(!inputmessage)	return
```suggestion
	if(!inputmessage)
		return
```

2022-04-30 14:02 UTC, JamieD1 commented on code/modules/admin/topic.dm
> +	if(!inputsigned)	return
```suggestion
	if(!inputsigned)
		return
```

2022-04-30 14:02 UTC, JamieD1 commented on code/modules/paperwork/faxmachine.dm
> +	if(!check_rights(R_ADMIN)) return
```suggestion
	if(!check_rights(R_ADMIN))
		return
```

2022-05-22 20:55 UTC, JamieD1 commented
@adamsong

2022-06-02 11:19 UTC, merged