Tank dispensers can now have their tanks crowbarred out not needing UI
yogstation13/Yogstation pull request #13844
Opened 2022-04-22 18:52 UTC by JamieD1

Tank dispensers can now have their tanks crowbarred out not needing UI
:cl:  
rscadd: Tank dispensers can now have their tanks crowbarred out not needing UI
/:cl:

2022-04-23 06:38 UTC, ToasterBiome commented
Why?

2022-04-24 12:47 UTC, JamieD1 commented
Will change this later

2022-04-24 20:29 UTC, ToasterBiome commented
> Will change this later

What is point of PR

2022-04-25 22:47 UTC, JamieD1 commented
https://user-images.githubusercontent.com/993128/165186974-74819c09-ab26-446c-9dc2-454c47ba6253.mp4

2022-04-25 22:51 UTC, ToasterBiome requested changes
them dropping under the silicon is annoying, make them drop from the dispenser (like a vending machine)

2022-04-25 22:51 UTC, ToasterBiome commented on code/game/objects/structures/tank_dispenser.dm
> +					usr.dropItemToGround(tank)
```suggestion
					usr.transferItemToLoc(tank, src.loc)
```

2022-04-25 22:51 UTC, ToasterBiome commented on code/game/objects/structures/tank_dispenser.dm
> +					usr.dropItemToGround(tank)
```suggestion
					usr.transferItemToLoc(tank,src.loc)
```

2022-04-30 13:19 UTC, merged