Fuck tape - Silicons can now go under tape
yogstation13/Yogstation pull request #13841
Opened 2022-04-22 17:07 UTC by JamieD1

Fuck tape

Silicons can now go under tape

:cl:  
rscadd: Silicons can now go under tape
/:cl:

2022-04-22 17:29 UTC, adamsong requested changes

2022-04-22 17:29 UTC, adamsong commented on code/game/objects/items/barriertape.dm
> +		return 1
```suggestion
		return TRUE
```

2022-04-22 17:45 UTC, maxion12345 commented
combat mechs cannot pass tape either and have to smash it :(

2022-04-23 03:03 UTC, stwordcitizen commented
Jamie engineering tape is currently the best way to get away from someone bar an instant rcd, maybe make tape have a limited number of uses?

2022-04-24 12:46 UTC, JamieD1 commented
> Jamie engineering tape is currently the best way to get away from someone bar an instant rcd, maybe make tape have a limited number of uses?

Yeah Ill do some nerfs later today.

2022-04-24 12:46 UTC, merged