A smite for dealing with slow thinkers
yogstation13/Yogstation pull request #13857
Opened 2022-04-23 08:48 UTC by MajManatee

# Document the changes in your pull request

Adds a new admin smite, playing "Think Fast, Chucklenuts!" and then flash banging the user.

# Changelog

:cl:  
rscadd: Adds a new admin smite
soundadd: Adds a new sound for said smite, Think fast! 
/:cl:

2022-04-23 08:49 UTC, ToasterBiome requested changes, later dismissed

2022-04-23 08:49 UTC, ToasterBiome commented on code/modules/admin/verbs/randomverbs.dm
> +				to_chat(usr,span_warning("This must be used on a carbon mob."), confidential = TRUE)
i wanna use it on borgs too

2022-04-23 08:53 UTC, MajManatee commented on code/modules/admin/verbs/randomverbs.dm
> +				to_chat(usr,span_warning("This must be used on a carbon mob."), confidential = TRUE)
yeah yeah fine

2022-04-24 12:48 UTC, JamieD1 approved these changes
Stupid, but sure.

2022-04-24 12:49 UTC, merged