Give objectives with assassinate targets the name of the species
yogstation13/Yogstation pull request #13863
Opened 2022-04-23 20:01 UTC by Simplehorror

# Document the changes in your pull request

Give objectives with assassinate targets the name of the species. Hopefully this will lead to more species specific killing (preternis EMP for example, plantperson fire)
# Changelog

:cl:  
tweak: The Syndicate realized it was dumb that they didn't tell you the species of your target.
/:cl:

2022-04-23 20:30 UTC, 00ze-cyclone commented
Now I'll know when my target is a phytosian so that I can buy incendiary bullets.

2022-04-23 20:32 UTC, Simplehorror commented
> Now I'll know when my target is a phytosian so that I can buy incendiary bullets.

Exactly

2022-04-23 21:04 UTC, ynot01 commented
most will be able to figure out what species they are from their name but hopefully this will help it click for those that ignore it

2022-04-23 21:11 UTC, LazennG commented
> most will be able to figure out what species they are from their name but hopefully this will help it click for those that ignore it

sometimes not an option if they're a mime or clown or a new player named 'boom boom' (moth)

2022-04-23 21:56 UTC, Simplehorror commented
> most will be able to figure out what species they are from their name but hopefully this will help it click for those that ignore it

what naming standards do preternis have

2022-04-24 12:52 UTC, JamieD1 requested changes

2022-04-24 12:52 UTC, JamieD1 commented on code/game/gamemodes/objective.dm
> +		if (ishuman(target.current))
```suggestion
		if(ishuman(target.current))
```

2022-04-24 12:52 UTC, JamieD1 commented on code/game/gamemodes/objective.dm
> +		if (ishuman(target.current))
```suggestion
		if(ishuman(target.current))
```

2022-04-24 12:52 UTC, JamieD1 commented on code/game/gamemodes/objective.dm
> +		if (ishuman(target.current))
```suggestion
		if(ishuman(target.current))
```

2022-04-24 12:52 UTC, JamieD1 commented on code/game/gamemodes/objective.dm
> +		if (ishuman(target.current))
```suggestion
		if(ishuman(target.current))
```

2022-04-24 13:18 UTC, JamieD1 approved these changes

2022-04-24 13:18 UTC, merged