You can no longer use camera consoles with the Bluespace Rapid Part Exchange Device
yogstation13/Yogstation pull request #13877
Opened 2022-04-24 14:15 UTC by JamieD1

No longer use camera consoles with the Bluespace Rapid Part Exchange Device

Fed up of lazy scientists using the console, go out and do something, go interreact with departments instead of just clicking in a dark room.

:cl:  
tweak: You no longer use camera consoles with the Bluespace Rapid Part Exchange Device
/:cl:

2022-04-24 14:17 UTC, SomeguyManperson commented
>  just clicking in a dark room.

But... thats how science works...

2022-04-24 14:20 UTC, TheGamerdk requested changes, later dismissed

2022-04-24 14:20 UTC, TheGamerdk commented on code/modules/research/stock_parts.dm
> +				to_chat("Out of range!")
```suggestion
				to_chat(user, span_warning("Out of range!"))
```

2022-04-24 16:44 UTC, Cartlord commented
Do you really think people will have any R.P. with the Scientists coming to upgrade their shit other than strangling them?

2022-04-24 20:46 UTC, Sniblet commented
leaving the science department is not the same as rp, all this does is make scientists break into places and get brigged for 15 minutes (counting processing time) in a vain effort to make things better for the players around them

2022-04-24 21:03 UTC, Runian commented
I don't think this promotes departmental interaction that much. Without having to talk to anyone or having to enter any access-restricted area as a scientist, you upgrade all the important areas: all of science, chemistry, medical's sleeper, cargo's auto/proto/ORM, and engineering's imprinter/lathe. When the round gets busy, you can just straight up walk into medical without having to talk to anyone and then upgrade the rest of medical's protolathe, all of genetics, etc. If a machine isn't easy to get to (i.e security protolathes), then don't bother upgrading it. If someone from a department doesn't want their stuff upgraded by not letting you in, then don't bother upgrading their stuff too.

Instead of this, maybe remove the security camera board from tech storage? It would make science have to ask security for the board instead (or to break into security checkpoint for that camera console) instead of just having to walk into tech storage for it.

2022-04-24 21:43 UTC, Chubbygummibear commented
would this set a precedent that bluespace doesn't work through cameras and something like the bluespace emag shouldn't either?

2022-04-25 03:26 UTC, Simplehorror commented
make it work on same z level

2022-04-25 08:41 UTC, JamieD1 commented
> leaving the science department is not the same as rp, all this does is make scientists break into places and get brigged for 15 minutes (counting processing time) in a vain effort to make things better for the players around them

No it doesnt, what universe are you living on which means you need to break into somewhere to upgrade it. If they dont let you in then dont upgrade it. Holy crap. Also its still within view range. Just not camera range.

2022-04-25 08:42 UTC, JamieD1 commented
> would this set a precedent that bluespace doesn't work through cameras and something like the bluespace emag shouldn't either?

Considering the bluespace emag is so rare, No.

2022-04-25 11:37 UTC, neeshacark commented
but why?

this literally does nothing but make it an annoyance to run around station with the brped and hope someone opens their department instead of screaming at you (or hoping the ai is on a lawset to where it'll give a shit)

this is literally the primary feature of the brped outside of it having extra space, there is NO reason to remove this. it won't increase RP, the majority of scientists don't even know about this feature and they just walk around soullessly with the damn thing and click.

all this does is take away from the competent scientists who are now obligated to run around with their brped to upgrade the station so people don't lynch them before they can do any fun gimmick or any other science stuff that's actually fun.

2022-04-25 22:05 UTC, JamieD1 commented
> but why?
> 
> this literally does nothing but make it an annoyance to run around station with the brped and hope someone opens their department instead of screaming at you (or hoping the ai is on a lawset to where it'll give a shit)
> 
> this is literally the primary feature of the brped outside of it having extra space, there is NO reason to remove this. it won't increase RP, the majority of scientists don't even know about this feature and they just walk around soullessly with the damn thing and click.
> 
> all this does is take away from the competent scientists who are now obligated to run around with their brped to upgrade the station so people don't lynch them before they can do any fun gimmick or any other science stuff that's actually fun.

Good. Get off your lazy ass and go upgrade like a usual helpful scientist.

2022-04-29 04:53 UTC, Sniblet commented
Still don’t get the interact with departments thing, is that what you consider fun
Best case scenario, I ask to come into the medbay and after making me wait and hit the door for 30 seconds a doctor says “ok”
And then doesn’t and makes me wait another 2 minutes before the clown leaves and I run in behind him and slip because he lubed the entire medbay while I was outside crying
I’m not having a character moment here I’m about to have a stroke there is a difference

2022-04-30 13:12 UTC, merged

2022-04-30 18:59 UTC, Altoids1 commented
Jamie is right