Nuggeted people can be dunked into deep fryers and turned into nuggets.
yogstation13/Yogstation pull request #13884
Opened 2022-04-24 21:54 UTC by TheGamerdk

# Document the changes in your pull request

Seems fitting with the quickfire vote

# Wiki Documentation

# Changelog

:cl:  
rscadd: If you remove all the limbs off of a human and dunk them in a deep fryer, they turn into nuggets! Yummy! 
/:cl:

2022-04-24 22:04 UTC, NCRLouTenant commented
As stated in the discord, said nuggets should remain sentient.

(Okay but hear me out, nugget nuggets become isolated sentient diseases once eaten that only effect the person who eats it and no one else. Am I making things needlessly complex? Absolutely!)

2022-04-24 22:06 UTC, SomeguyManperson commented on code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
>  	if(user.pulling && user.a_intent == INTENT_GRAB && iscarbon(user.pulling) && reagents.total_volume && isliving(user.pulling))
fun fact this exists

2022-04-25 01:38 UTC, KillerOrcaCora commented
Finally another way to execute people in the kitchen !

2022-04-25 02:59 UTC, Readystorm546 commented
THis might be the best PR ever made

2022-04-25 05:06 UTC, TymurShatillo commented
Based

2022-04-26 05:38 UTC, TymurShatillo approved these changes

2022-04-28 08:46 UTC, JamieD1 requested changes

2022-04-28 08:46 UTC, JamieD1 commented on code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
> +
```suggestion
```

2022-04-28 08:48 UTC, JamieD1 submitted a review, later dismissed

2022-04-28 08:48 UTC, JamieD1 commented on code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
> +
```suggestion
```

2022-04-30 13:15 UTC, JamieD1 approved these changes

2022-04-30 13:15 UTC, merged