Removes lich, you can now be a weak skeleton with magic mirrors
yogstation13/Yogstation pull request #13886
Opened 2022-04-24 23:00 UTC by Marmio64

Comments out the lich spell from the spellbook, meaning it cannot be normally obtained anymore. Badmins can still give it to people if they really want to for some reason.

This spell is literally just a crutch for wizards who can't handle not dying despite having a bunch of incredibly powerful spells at their disposal. If you still want to roleplay as a necromancer with necromantic stones and such, you can become a weak skeleton by using your magic mirror. Weak skeletons are normal skeletons but they take 50% extra brute damage and don't punch as hard.

# Changelog

:cl:  
rscadd: You can turn into a weak skeleton from magic mirrors
rscdel: Lich can no longer be bought from the spellbook
/:cl:

2022-04-24 23:30 UTC, tattax commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +	//category = "Defensive"
```suggestion
/*datum/spellbook_entry/lichdom
	name = "Bind Soul"
	spell_type = /obj/effect/proc_holder/spell/targeted/lichdom
	category = "Defensive"*/
```

also works

2022-04-25 03:23 UTC, Simplehorror commented
Increase the cost instead, we need more features not less

2022-04-25 03:57 UTC, Marmio64 commented
> Increase the cost instead, we need more features not less

upping the price isnt going to fix the problem that it is a crutch spell designed to give people who cant survive as the most OP antag extra chances. Even if the price is a whopping 4 points you can still get jaunt, rodform, and fireball and have the meta loadout and force a shuttle call since the crew cant find your cigarette butt phylactory that you placed inside a book inside a plant pot in the most remote corner of maint possible.

2022-04-25 04:38 UTC, Simplehorror commented
> > Increase the cost instead, we need more features not less
> 
> upping the price isnt going to fix the problem that it is a crutch spell designed to give people who cant survive as the most OP antag extra chances. Even if the price is a whopping 4 points you can still get jaunt, rodform, and fireball and have the meta loadout and force a shuttle call since the crew cant find your cigarette butt phylactory that you placed inside a book inside a plant pot in the most remote corner of maint possible.

finding a phylactery is extremely easy and if you can't do it is because you suck

2022-04-25 05:38 UTC, maxion12345 commented
ided????

2022-04-25 09:33 UTC, Spacemanspark commented
Wizard rounds already end too quickly imo, most wizards get whacked really quickly. At least lich allows shenanigans to keep going for a bit.

2022-04-25 11:27 UTC, neeshacark commented
we are not TG
we are not TG
we are not TG
we are not TG

please stop removing all the features that give variety

2022-04-25 14:59 UTC, Marmio64 commented
> ided????

No, I've just hated lich for a long time.

> Wizard rounds already end too quickly imo, most wizards get whacked really quickly. At least lich allows shenanigans to keep going for a bit.

Shuttle call generally ends it early regardless since dealing with liches suck, and if the lich is captured they get perma n2o'd and the game becomes extended except a few unlucky people got gibbed or exploded by the wizard.

> we are not TG we are not TG we are not TG we are not TG
> 
> please stop removing all the features that give variety

Removing one feature that is a crutch and is unfun to deal with as the crew (oh, the wizard that deleted half the station finally got killed? Well he'll be back in 3 minutes, undoing your progress.) won't all of a sudden make yogs unhabitable. Anyhow, If the crew is good enough to find the phylactery right away then it is just unfun for the wizard since they spent a fifth of their kit on this only for it to be cremated by a maint rat right away.

2022-04-25 19:33 UTC, KillerOrcaCora commented
I know this might actually require work but can we just fix the tracker effect or better yet overhaul it so you can actually track the wizard's item before they respawn?

2022-04-25 22:26 UTC, JamieD1 commented
@SomeguyManperson

2022-05-01 00:21 UTC, SomeguyManperson requested changes
increase cost to 4 instead, maybe 5

2022-05-07 10:30 UTC, Marmio64 commented
> increase cost to 4 instead, maybe 5

#14034 Done

2022-05-07 10:30 UTC, closed without merging