Fixes broken "? canister" bug
yogstation13/Yogstation pull request #13900
Opened 2022-04-26 05:25 UTC by ToasterBiome

# Document the changes in your pull request

if you update the icon of a broken canister after it's already been updated after breaking, it will try to change it to the "broke" version of the canister sprite, which already is a broken version of the canister sprite, so the sprite breaks. 

# Changelog

:cl:  
bugfix: broken canisters no longer want to become more broken and break their sprite
/:cl:

2022-04-28 14:30 UTC, Altoids1 requested changes

2022-04-28 14:30 UTC, Altoids1 commented on code/modules/atmospherics/machinery/portable/canister.dm
> +		if(!findtext(icon_state,"-1")) //a wise man always if it already broke, don't break it more.
Typo in the comment

2022-04-30 13:20 UTC, JamieD1 commented on code/modules/atmospherics/machinery/portable/canister.dm
> +		if(!findtext(icon_state,"-1")) //a wise man always if it already broke, don't break it more.
```suggestion
		if(!findtext(icon_state,"-1")) //A wise man always said, if it already broke, don't break it more.
```

2022-04-30 13:31 UTC, JamieD1 approved these changes

2022-04-30 13:31 UTC, merged