Bloodsucker fixes + balance + new clan + ports some stuff
yogstation13/Yogstation pull request #13918
Opened 2022-04-28 04:27 UTC by tattax

https://github.com/fulpstation/fulpstation/pull/588
https://github.com/fulpstation/fulpstation/pull/529
https://github.com/fulpstation/fulpstation/pull/617

# Document the changes in your pull request

- [ ] Add new objectives
- [ ] Change stuff with initial feedback from github
- [ ] Finish un-placeholding and documenting stuff properly

New bloodsucker stuff + trying to fix some thing that the community complained about.

# **NEW**

Clan Lasombra: Interaction with a new Resting Place structure to spend ranks in order to be able to ascend normal abilities to a higher level and gain some attributes, they can also see heretic influences and harvest things from them. Fav. Vassal gets shadowwalk and minor glare.

Shadow Abilities: Upgraded versions of normal abilities limited to the previous clan.

Possessed armor trap for Lasombra Bloodsuckers that trigger when passerbys get too close and personal.

Gangrel Clan when entering frenzy goes wolf mode, which depending on your current powers gives you certain powers, always have feast so you can have a way of getting out of frenzy. Some unexpected things can happen when leaving frenzy though...

# **TWEAKED**

Gangrel Clan can now stack transforms if you can't level up to the next level, making it so you don't waste 100 blood and get refunded about 3/4 and 1/4 on level 1 and 2 respectively, giving you minor buffs if you are transformed.

Tweaked how werewolf form acted to fit the new style i'm trying to give the Gangrel Clan since it was previously kind of lackluster

Bloodsuckers now enter frenzy at a higher blood level to encourage blood drinking.

Night cycle changed from 10 mins -> 15 mins and Day 1 min -> 45 secs (Day might be changed back but i'm not sure) due to having too much back and in, also reducing rank gain to encourage usage of the blood altar. (Which had it's construction price reduced).

Bloodsuckers should now be immune to brute when in torpor, might need some testing.

Tweaked feed objective's amount as that was made before i made 2/3 objectives per  sucker.

Powers now also show cooldowns.

# **FIXES**

Should fix most bugs related to objectives and possibly the gamemode (don't quote me on this) also tries to resolve some of the monsterhunter objectives issues and makes them respect quiet round.

# Wiki Documentation

New clan + gangrel changes + probably want to apply structures there

# Changelog
:cl:  JohnFulpWillard, Tatax
rscadd: New bloodsucker clan, Gangrel Clan's wolf form actual implementation
bugfix: Maybe possibly fixed some bloodsucker bugs 
tweak: Gangrel Clan now has a refund system if you transform on the same blood level, also Day and Night Cycle's time and frenzy rebalances
imageadd: New sprite for powers and traps!
spellcheck: fixed the forck
/:cl:

2022-04-28 05:09 UTC, TymurShatillo commented
Can you also make that when you suck blood as a bloodsucker there will be a progress bar like normal vampires have, because it is confusing, and hard to understand are you sucking blood or not

2022-04-28 22:24 UTC, tattax commented
> Can you also make that when you suck blood as a bloodsucker there will be a progress bar like normal vampires have, because it is confusing, and hard to understand are you sucking blood or not

it gives the prog bar when you are starting the suck, after that you're always draining blood, vampire does it in waves

2022-04-28 23:36 UTC, NCRLouTenant commented
As a VtM fan I am always excited for Bloodsucker improvements and additions.

2022-04-29 15:04 UTC, TymurShatillo commented
Also what effect's do heretic influences give to bloodsuckers?

2022-04-29 21:03 UTC, tattax commented
> Also what effect's do heretic influences give to bloodsuckers?

new item to activate the structure

2022-04-30 01:37 UTC, bruhlookatthisdood commented
You can suck blood from an xenomorph and get blood out of it
its literaly acid
wtf

2022-05-01 00:20 UTC, SomeguyManperson commented
> You can suck blood from an xenomorph and get blood out of it its literaly acid wtf (me asking you to fix this)

skill issue

2022-05-01 07:05 UTC, TymurShatillo commented
> You can suck blood from an xenomorph and get blood out of it
> 
> its literaly acid
> 
> wtf
> 
> (me asking you to fix this)

https://user-images.githubusercontent.com/91609255/166135858-8fffc670-c901-4ff1-a46c-6c4c5e72c3f1.MOV

2022-05-01 17:57 UTC, SomeguyManperson commented on code/modules/antagonists/bloodsuckers/bloodsucker_mobs.dm
> +	target.gib()
might want to do the thing marrow weavers do where they eat all your organs instead since gibs are nasty

2022-05-03 00:05 UTC, SomeguyManperson commented on code/modules/antagonists/bloodsuckers/bloodsucker_mobs.dm
> +					B.dismember()
```suggestion
	for(var/obj/item/organ/O in H.internal_organs)
		if(O.zone == "chest")
			foundorgans++
			qdel(O)
	if(foundorgans)
		if(istype(src, /mob/living/simple_animal/hostile/bloodsucker/werewolf))
			var/mob/living/simple_animal/hostile/bloodsucker/werewolf/ww = src
			ww.satiation++
			src.visible_message(span_danger("[src] devours [target]'s organs!"), \
			span_userdanger("As you devour [target]'s organs you feel as if the beast inside you has calmed itself down, you'll need to feast [3 - ww.satiation] more times to become human again."))
	for(var/obj/item/bodypart/B in H.bodyparts)
		if(B.body_zone == "chest")
			B.dismember()
```

2022-05-03 06:22 UTC, ToasterBiome requested changes, later dismissed

2022-05-03 06:22 UTC, ToasterBiome commented on code/modules/events/tzimisce.dm
> +	weight = 2000
```suggestion
	weight = 5
```

holy fuck what

2022-05-03 06:38 UTC, TymurShatillo commented
So now gibbed but not final death'ed bloodsuckers will be able to revive?

2022-05-03 13:40 UTC, tattax commented
> So now gibbed but not final death'ed bloodsuckers will be able to revive?

yes

2022-05-03 13:47 UTC, TymurShatillo commented
> > So now gibbed but not final death'ed bloodsuckers will be able to revive?
> 
> 
> 
> yes

🥳

2022-05-05 04:54 UTC, SomeguyManperson commented on code/modules/antagonists/bloodsuckers/powers/gangrel.dm
> +				user_species.punchdamagelow += 2
Do something else here if not giving a flat refund I dont think its a good idea to give MASSIVE innate armor and punch damage if it doesnt cost anything else

2022-05-09 13:59 UTC, UselessTheremin commented
btw heres this tatax #14002

2022-05-09 14:03 UTC, JamieD1 requested changes
People throwing a fit

2022-05-09 14:03 UTC, JamieD1 commented on config/game_options.txt
> +PROBABILITY TRAITORSUCKER 4
3

2022-05-09 14:03 UTC, JamieD1 commented on config/game_options.txt
> +PROBABILITY BLOODSUCKER 5
4

2022-05-09 14:04 UTC, JamieD1 requested changes

2022-05-09 14:04 UTC, JamieD1 commented on config/game_options.txt
> +PROBABILITY BLOODSUCKER 5
```suggestion
PROBABILITY BLOODSUCKER 4
```

2022-05-09 14:04 UTC, JamieD1 commented on config/game_options.txt
> +PROBABILITY TRAITORSUCKER 4
```suggestion
PROBABILITY TRAITORSUCKER 3
```

2022-05-09 19:16 UTC, tattax commented
> btw heres this tatax #14002

it's solved (should be)

2022-05-10 21:06 UTC, JamieD1 approved these changes

2022-05-10 21:07 UTC, merged

2023-01-29 06:30 UTC, JohnFulpWillard commented
> You can suck blood from an xenomorph and get blood out of it

intentional, blood is blood

2023-01-29 07:21 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/tzimisce.dm
> +	desc = "I'm pretty sure it's owner needed this to live."
its*

2023-01-29 07:21 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/tzimisce.dm
> +/obj/item/muscle/attackby(obj/item/I, mob/user, params) // handles muscle crafting
single letter var

2023-01-29 07:26 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/structures/bloodsucker_crypt.dm
> +	var/answer = input(user, "We have the chance to mutate our Vassal, how should we mutilate their corpse? This will cost us blood.", "What do we do with our Vassal?") in options
tgui_input

2023-01-29 07:34 UTC, tattax commented on code/modules/antagonists/bloodsuckers/structures/bloodsucker_crypt.dm
> +	var/answer = input(user, "We have the chance to mutate our Vassal, how should we mutilate their corpse? This will cost us blood.", "What do we do with our Vassal?") in options
![image](https://user-images.githubusercontent.com/71668564/215312096-4a09f0f9-44c0-4ce4-b465-cc1237554c08.png)

2023-01-29 07:36 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/structures/bloodsucker_crypt.dm
> +	var/answer = input(user, "We have the chance to mutate our Vassal, how should we mutilate their corpse? This will cost us blood.", "What do we do with our Vassal?") in options
throwing

2023-01-29 07:38 UTC, tattax commented on code/modules/antagonists/bloodsuckers/structures/bloodsucker_crypt.dm
> +	var/answer = input(user, "We have the chance to mutate our Vassal, how should we mutilate their corpse? This will cost us blood.", "What do we do with our Vassal?") in options
```suggestion

```