removes engitape from utility belts
yogstation13/Yogstation pull request #13926
Opened 2022-04-29 01:01 UTC by bruhlookatthisdood

# If this is your first PR, or not, take the time to read our CONTRIBUTING.md file! You can see it here: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# Document the changes in your pull request

now before you panic, this removes it from /obj/item/storage/belt/utility/full. engineer's belts they spawn with will still have the engi tape in them by default, this removes it from the toolbelts of roboticists (also from sigtech and normal alert ert engineers but we dont talk about them)

# Wiki Documentation
no
# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
bugfix: roboticists no longer get tape in their toolbelts (cope, mald, seeth, sadge.)
/:cl:

2022-04-29 15:55 UTC, Spacemanspark commented
Unneeded nerf, now I can't grief Malice by surrounding them with tape >:(

2022-04-29 19:40 UTC, bruhlookatthisdood commented
> Unneeded nerf, now I can't grief Malice by surrounding them with tape >:(

Science Tape?

2022-04-30 13:34 UTC, JamieD1 requested changes
I would prefer you made an engineering subtype instead and moved the tape to that.

2022-04-30 13:34 UTC, JamieD1 commented on code/game/objects/items/storage/belt.dm
> +
```suggestion
```

2022-05-02 10:18 UTC, JamieD1 approved these changes

2022-05-02 10:18 UTC, merged