Monkey sentience caps from TG
yogstation13/Yogstation pull request #13970
Opened 2022-05-02 15:42 UTC by YouCanBeBetterThanThat

# Document the changes in your pull request
ports https://github.com/tgstation/tgstation/pull/51621 from TG

# Wiki Documentation
document the crate about monkey sentience

# Changelog

:cl:  tralezab
rscadd: monkey sentience caps
/:cl:

2022-05-02 15:58 UTC, TymurShatillo commented
Monke

2022-05-02 16:13 UTC, tattax commented on code/modules/clothing/head/helmet.dm
> +	visible_message("<span class='warning'>[src] powers up!</span>")
```suggestion
	visible_message(span_warning("[src] powers up!"))
```

2022-05-02 16:13 UTC, tattax commented on code/modules/clothing/head/helmet.dm
> +		to_chat(something, "<span class='boldnotice'>You feel a stabbing pain in the back of your head for a moment.</span>")
```suggestion
		to_chat(something, span_boldnotice("You feel a stabbing pain in the back of your head for a moment."))
```

2022-05-02 16:13 UTC, tattax commented on code/modules/clothing/head/helmet.dm
> +		visible_message("<span class='notice'>[src] falls silent. Maybe you should try again later?</span>")
```suggestion
		visible_message(span_notice("[src] falls silent. Maybe you should try again later?"))
```

2022-05-02 16:13 UTC, tattax commented on code/modules/clothing/head/helmet.dm
> +	to_chat(magnification, "<span class='notice'>You're a mind magnified monkey! Protect your helmet with your life- if you lose it, your sentience goes with it!</span>")
```suggestion
	to_chat(magnification, span_notice("You're a mind magnified monkey! Protect your helmet with your life- if you lose it, your sentience goes with it!"))
```

2022-05-02 16:13 UTC, tattax commented on code/modules/clothing/head/helmet.dm
> +			to_chat(magnification, "<span class='userdanger'>You feel your flicker of sentience ripped away from you, as everything becomes dim...</span>")
```suggestion
			to_chat(magnification, span_userdanger("You feel your flicker of sentience ripped away from you, as everything becomes dim..."))
```

2022-05-02 16:13 UTC, tattax commented on code/modules/clothing/head/helmet.dm
> +	visible_message("<span class='warning'>[src] fizzles and breaks apart!</span>")
```suggestion
	visible_message(span_warning("[src] fizzles and breaks apart!"))
```

2022-05-02 16:13 UTC, tattax commented on code/modules/clothing/head/helmet.dm
> +	. += "<span class='boldnotice'>Ask your CMO if mind magnification is right for you.</span>"
```suggestion
	. += span_boldwarning("---WARNING: REMOVAL OF HELMET ON SUBJECT MAY LEAD TO:---")
	. += span_warning("BLOOD RAGE")
	. +=  span_warning("BRAIN DEATH")
	. += span_warning("PRIMAL GENE ACTIVATION")
	. +=  span_warning("GENETIC MAKEUP MASS SUSCEPTIBILITY")
	. += span_boldnotice("Ask your CMO if mind magnification is right for you.")
```

idk but you probavbly could do . += the entire thing and add <br> to the end and \ or \n\ to switch lines

2022-05-02 16:28 UTC, grimm-hollowknight requested changes
Find an existing helmet and edit it to be the new sprite. ANYTHING would be better than the current sprite.

2022-05-02 16:34 UTC, YouCanBeBetterThanThat commented
> Find an existing helmet and edit it to be the new sprite. ANYTHING would be better than the current sprite.

any suggestions for an existing one?

2022-05-02 16:36 UTC, TymurShatillo commented
> > Find an existing helmet and edit it to be the new sprite. ANYTHING would be better than the current sprite.
> 
> any suggestions for an existing one?

Cockcult helmet!

2022-05-04 03:44 UTC, tattax commented on code/modules/clothing/head/helmet.dm
> +	icon_state = "[icon_state][rand(1,3)]"
you set it here to rand(1,3) but checks shows you added only the 1st sprite of monkeymind

2022-05-12 20:18 UTC, closed without merging