Expands perma, adds license plate presses
yogstation13/Yogstation pull request #14017
Opened 2022-05-05 22:49 UTC by bruhlookatthisdood

# Document the changes in your pull request

I gave perma an expansion
I also gave it license plates
Cope?
![image](https://user-images.githubusercontent.com/89947174/167037591-f09602eb-3c0b-4640-9fd8-828d20c39ef0.png)
![image](https://user-images.githubusercontent.com/89947174/167037608-d36460c5-7d8f-46df-b9ee-e08bf9b8b66a.png)
Warden has a.. delivery system now. Used "only for license plates"

# Wiki Documentation

New picture

# Changelog

:cl:  Spookydonut and bruhlookatthisdood
rscadd: Perma has been given a make-over
rscadd: Perma has been given license palte presses to give them something to work on in prison.
/:cl:

2022-05-06 01:29 UTC, Cartlord commented
your changelog has a typo
shame

2022-05-06 03:35 UTC, KillerOrcaCora commented
Based PR

2022-05-06 05:12 UTC, adamsong commented
I like the part where perma prisoners are given access to the warden's office

2022-05-06 10:48 UTC, jjpark-kb commented on code/game/machinery/prisonlabor.dm
> +		plate.use(1)
maybe put this as an if statement. "If you cannot use, early return."

2022-05-06 10:50 UTC, jjpark-kb commented on code/game/machinery/prisonlabor.dm
> +		work_press(user)
early return might be good here.
```suggestion
	if(pressing || !current_plate)
		return
	work_press(user)
```

2022-05-06 12:22 UTC, bruhlookatthisdood commented
> I like the part where perma prisoners are given access to the warden's office

how? its a outlet.

2022-05-06 18:32 UTC, maxion12345 commented
Expansion seems a bit too large to justify another a few machines. This also ruins the whole "openness" of Perma that really solidified the whole "this is jail, the cameras watch your every move, there is no privacy outside of your cell and the bathroom".

Also disposal pipes through walls bad

2022-05-06 20:01 UTC, bruhlookatthisdood commented on code/game/machinery/prisonlabor.dm
> +		plate.use(1)
dont see why it would be neccesary.

2022-05-07 11:35 UTC, JamieD1 commented
Comments in DMs

2022-05-08 16:59 UTC, TheGamerdk requested changes, later dismissed

2022-05-08 16:59 UTC, TheGamerdk commented on code/game/machinery/prisonlabor.dm
> +	if(istype(I, /obj/item/stack/license_plates/empty))
```suggestion
	if(!istype(I, /obj/item/stack/license_plates/empty))
		return ..()
```

2022-05-08 16:59 UTC, TheGamerdk commented on code/game/machinery/prisonlabor.dm
> +
```suggestion
```

2022-05-08 16:59 UTC, TheGamerdk commented on code/modules/cargo/packs.dm
> +	cost = 1000  // 50 * 25 + 700 - 1000 = 950 credits profit
+700?

2022-05-09 12:17 UTC, nesisknesis approved these changes

2022-05-09 16:46 UTC, bruhlookatthisdood commented
only thing im worried about right now is the warden throwing things in the license plate disposal chute, that are not license plates.

the prisoners must mald.

2022-05-10 22:37 UTC, JamieD1 approved these changes

2022-05-10 22:37 UTC, merged

2022-05-11 00:39 UTC, Cartlord commented
But what do you DO with license plates?

2022-05-12 01:40 UTC, bruhlookatthisdood commented
> But what do you DO with license plates?

sell them to cargo

2022-05-12 06:34 UTC, TymurShatillo commented
Actually it conflicts with https://github.com/yogstation13/Yogstation/pull/13893

2022-05-12 12:30 UTC, bruhlookatthisdood commented
> Actually it conflicts with #13893

uhoh