Reduce vent lag
yogstation13/Yogstation pull request #14044
Opened 2022-05-07 19:31 UTC by YouCanBeBetterThanThat

Reduces the lag from the foam in vents event.

                                                     Profile results (total time)
Proc Name                                                                               Self CPU    Total CPU    Real Time     Overtime        Calls
-----------------------------------------------------------------------------------    ---------    ---------    ---------    ---------    ---------
/atom/proc/wash                                                                            1.871        3.078        3.523        0.000      1060766
/datum/reagents/proc/reaction                                                              1.509        7.616        7.819        0.000       448512
/turf/open/return_air                                                                      0.731        0.735        0.846        0.000       280707
/obj/effect/particle_effect/foam/process                                                   5.006       16.536       16.649        0.000       275251
/datum/gas_mixture/react                                                                   0.875        0.881        0.993        0.000       263893
/atom/movable/lighting_object/wash                                                         0.083        0.085        0.116        0.000       221146
/datum/reagent/space_cleaner/reaction_turf                                                 0.802        4.406        4.515        0.000       221146
/turf/wash                                                                                 1.496        3.603        3.684        0.000       221146
/datum/reagent/space_cleaner/reaction_obj                                                  0.345        1.597        1.682        0.000       200199

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images  
spellcheck: fixed a few typos  
experimental: This is experimental  
/:cl:

2022-05-07 19:44 UTC, YouCanBeBetterThanThat commented
Yeah this isn't working as well as I thought it would. The main issue is that foam constantly calls the reagent reaction on every object it is touching for every tick it runs, which causes a lot of clean procs which are heavy in the first place.

2022-05-07 19:54 UTC, YouCanBeBetterThanThat commented
I can fix foam but it'll be in the form of a nerf, so I'll restrict it to the events only. They will only apply their chemicals to objects and turfs once, but I'll give a healthy dose.

2022-05-10 21:54 UTC, JamieD1 commented
Can you post the profiling before and after?

2022-05-16 19:12 UTC, JamieD1 commented
Check in 1 - Please update.

2022-05-16 19:43 UTC, TheGamerdk requested changes

2022-05-16 19:43 UTC, TheGamerdk commented on code/game/objects/effects/effect_system/effects_foam.dm
> +	LAZYINITLIST(applied_atoms)
not how you should use lazy lists
just do applied_atoms = list()

2022-05-16 19:43 UTC, TheGamerdk commented on code/game/objects/effects/effect_system/effects_foam.dm
> +		if(O in applied_atoms && one_apply_per_object)
```suggestion
		if(one_apply_per_object && (O in applied_atoms))
```
short circuit to avoid list lookup when not one_apply_per_object

2022-05-16 19:43 UTC, TheGamerdk commented on code/game/objects/effects/effect_system/effects_foam.dm
> +	if(!(T in applied_atoms && one_apply_per_object))
```suggestion
	if(!(one_apply_per_object && (T in applied_atoms)))
```

2022-05-16 19:43 UTC, TheGamerdk commented on code/game/objects/effects/effect_system/effects_foam.dm
> +			applied_atoms += T
check if one_apply_per_object before doing this, no need to drag a list if we have one_apply_per_object = FALSE

2022-05-16 19:43 UTC, TheGamerdk commented on code/game/objects/effects/effect_system/effects_foam.dm
> +			applied_atoms += O
see other comment

2022-05-16 19:43 UTC, TheGamerdk commented on code/game/objects/effects/effect_system/effects_foam.dm
> +	var/list/applied_atoms
clear your list on destroy please, don't drag around a list of references to this many objects

2022-05-21 13:30 UTC, YouCanBeBetterThanThat commented
will work on this in a bit

2022-05-30 19:37 UTC, JamieD1 commented
> will work on this in a bit

Can you post profiling before and after?

2022-06-06 15:51 UTC, TheGamerdk commented on code/game/objects/effects/effect_system/effects_foam.dm
> +	LAZYINITLIST(applied_atoms)
```suggestion
	applied_atoms = list()
```

2022-06-06 15:51 UTC, TheGamerdk approved these changes

2022-06-06 15:59 UTC, merged