[TESTING ONLY] Adds lots of ways to mess with batons for +DEV
yogstation13/Yogstation pull request #14061
Opened 2022-05-08 12:17 UTC by JamieD1

[TESTING ONLY] Adds lots of ways to mess with batons for +DEV

DO NOT MERGE

2022-05-08 23:27 UTC, adamsong requested changes

2022-05-08 23:27 UTC, adamsong commented on code/game/objects/items/stunbaton.dm
> +	var/obj/item/firing_pin/implant/mindshield/pin = /obj/item/firing_pin/implant/mindshield //standard firing pin for most guns
This should probably default to an electronic pin, at the very least make the typepath of the pin var allow for it.

2022-05-08 23:27 UTC, adamsong commented on code/game/objects/items/stunbaton.dm
> +	if(GLOB.batons_seconly)
```suggestion
	if(GLOB.batons_seconly && !GLOB.batons_normal)
```

2022-05-08 23:27 UTC, adamsong commented on code/game/objects/items/stunbaton.dm
> +			if(GLOB.batons_normal && GLOB.batons_cooldown)
```suggestion
			if(GLOB.batons_normal || GLOB.batons_cooldown)
```

2022-05-08 23:27 UTC, adamsong commented on code/game/objects/items/stunbaton.dm
> +			if(GLOB.batons_normal && GLOB.batons_cooldown)
```suggestion
			if(GLOB.batons_normal || GLOB.batons_cooldown)
```

2022-05-08 23:27 UTC, adamsong commented on code/game/objects/items/stunbaton.dm
> +	set name = "Toggle Batons Cooldown"
Why is this just disable cooldowns? I thought we wanted to test different amounts of cooldown

2022-05-09 14:32 UTC, JamieD1 commented on code/game/objects/items/stunbaton.dm
> +	var/obj/item/firing_pin/implant/mindshield/pin = /obj/item/firing_pin/implant/mindshield //standard firing pin for most guns
```suggestion
	var/obj/item/firing_pin/pin = /obj/item/firing_pin/implant/mindshield //mindshield implant
```

2022-05-21 12:14 UTC, JamieD1 commented on code/game/objects/items/stunbaton.dm
> +	GLOB.batons_normal = !GLOB.batons_normal
```suggestion
```

2022-06-11 12:48 UTC, closed without merging