New makeshift item: Makeshift id
yogstation13/Yogstation pull request #14071
Opened 2022-05-08 23:59 UTC by cuackles

# Document the changes in your pull request

Are you tired of only being able to have fake names with the agent ID ? well wait no more, with this new item, the makeshift id you will be able to change your shown name at will, this ID allowes you to forge a new identity, being able to forge it to give yourself a new name, the diferences with the agent ID is that this one does not allow you to fake a job or steal access

Its recipe is cardboard, a pen and some tape, using the wirecutters as a tool to cut it, its on the misc crafting tab

![image](https://user-images.githubusercontent.com/68789204/167321132-7f940941-5706-45f9-a2ba-30a98adf6f2e.png)

# Changelog

:cl:  
rscadd: Added new makeshift item: makeshift ID    
imageadd: added some icons for the makeshift ID 
/:cl:

2022-05-09 00:00 UTC, maxion12345 commented
why not cardboard

also does this fit inside of a pda

2022-05-09 00:01 UTC, cuackles commented
> why not cardboard
> 
> also does this fit inside of a pda

<i did not think of it, maybe i will change it eventualy
<its a subtype of an ID so it will probably fit

2022-05-09 00:04 UTC, maxion12345 commented
> > why not cardboard
> > also does this fit inside of a pda
> 
> <i did not think of it, maybe i will change it eventualy <its a subtype of an ID so it will probably fit

bet 
Is this meant to be used as a normal ID w/o access?

2022-05-09 00:08 UTC, cuackles commented
> > > why not cardboard
> > > also does this fit inside of a pda
> > 
> > 
> > <i did not think of it, maybe i will change it eventualy <its a subtype of an ID so it will probably fit
> 
> bet Is this meant to be used as a normal ID w/o access?

< uuuuuuuuuuuuuhhhhhhhhhh, it is not meant to do that but how the code works it is able to be given acces with the hops console, but as it spawns it has no access , its meant to be used as camo to pass of as other poeple , or to be a dumbass

2022-05-09 13:02 UTC, grimm-hollowknight approved these changes

2022-05-10 16:22 UTC, Tipy1802 commented
Far too cheap for the immense power it provides. Forging IDs should be a traitor only thing anyways

2022-05-10 22:25 UTC, JamieD1 commented
I dont like all of the crew having this, it makes the hop basically less relevant and we will have a bunch of idiots just running round with different names and jobs.

2022-05-10 22:30 UTC, cuackles commented
> I dont like all of the crew having this, it makes the hop basically less relevant and we will have a bunch of idiots just running round with different names and jobs.

The makeshift ID is only capable of changing your name, it won't let you change your job, and it will not have any access assigned, idealy it would only be used if someone is already covering their identify with masks and not wearing ID's

2022-05-10 22:31 UTC, cuackles commented
I won't deny tho that yes there will be an increase of idiots running around with stupid names, hopefully for gimmicks i wish

2022-05-13 21:06 UTC, Anvilman6 requested changes

2022-05-13 21:06 UTC, Anvilman6 commented on code/game/objects/items/cards_ids.dm
> +	desc = "a humble piece of cardboard with a name writen on it, will probably never fool anyone"
```suggestion
	desc = "A humble piece of cardboard with a name written on it. This will probably never fool anyone."
```

2022-05-13 21:06 UTC, Anvilman6 commented on code/game/objects/items/cards_ids.dm
> +			var/input_name = stripped_input(user, "What name would you like to put on this card? Leave blank to randomise.", "Agent card name", registered_name ? registered_name : (ishuman(user) ? user.real_n
```suggestion
			var/input_name = stripped_input(user, "What name would you like to write on this card? Leave blank to randomize.", "Agent card name", registered_name ? registered_name : (ishuman(user) ? user.real_name : user.name), MAX_NAME_LEN)
```

2022-05-13 21:06 UTC, Anvilman6 commented on code/game/objects/items/cards_ids.dm
> +			to_chat(user, span_notice("You scrible a new name into the makeshift ID."))
```suggestion
			to_chat(user, span_notice("You scribble a new name onto the makeshift ID."))
```

2022-05-13 21:06 UTC, Anvilman6 commented on code/game/objects/items/cards_ids.dm
> +			var/newAge = input(user, "Choose the ID's age:\n([AGE_MIN]-[AGE_MAX])", "Agent card age") as num|null
```suggestion
			var/newAge = input(user, "Choose an age to display:\n([AGE_MIN]-[AGE_MAX])", "Agent card age") as num|null
```

2022-05-16 19:24 UTC, merged