makes goat king loot worth something
yogstation13/Yogstation pull request #14098
Opened 2022-05-11 00:52 UTC by LazennG

# Document the changes in your pull request
people thought meteor gun was ok for some reason so i feel i can get away with this.
Adds new item to goat king's drops called 'goat king's scanner,' a mineral scanner that detects ores a bit more often than an advanced scanner and guarantees high potency when defusing gibtonite regardless of timing.

# Wiki Documentation
under the loot section of goat king https://wiki.yogstation.net/wiki/Megafauna#King_of_Goats

![goat_scaner](https://user-images.githubusercontent.com/58535870/167745120-c757d0da-bf64-479d-9488-026a22881107.png)
![goat_scaner](https://user-images.githubusercontent.com/58535870/167745384-2122cf9a-ff14-468a-a820-d8f2fa0297d2.gif)

goat king's scanner- a mineral scanner that detects ores a bit more often than an advanced scanner and guarantees high potency when defusing gibtonite regardless of timing.

# Changelog
:cl:  @cuackles 
rscadd: Added goat king loot
imageadd: added sprite for scanner  
/:cl:
thanks to @cuackles for whipping up a better sprite for the goat scanner than me in like 5 minutes

2022-05-11 01:04 UTC, ToasterBiome requested changes

2022-05-11 01:04 UTC, ToasterBiome commented on code/game/turfs/simulated/minerals.dm
> +/turf/closed/mineral/gibtonite/proc/defuses()
merge this proc into defuse() and make defuse take a value force_perfect, don't need two procs that do the same thing

2022-05-11 01:04 UTC, ToasterBiome commented on code/modules/mining/equipment/mineral_scanner.dm
> +
move this to right after lesser

2022-05-11 01:04 UTC, ToasterBiome commented on yogstation/code/modules/mob/living/simple_animal/hostile/retaliate/king_of_goats.dm
> +		new /obj/item/t_scanner/adv_mining_scanner/goat_scanner
```suggestion
		new /obj/item/t_scanner/adv_mining_scanner/goat_scanner(loc)
```

2022-05-11 01:04 UTC, ToasterBiome commented on code/modules/mining/equipment/mineral_scanner.dm
> +
(the definition for the scanner)

2022-05-11 06:55 UTC, Cartlord commented
oh jesus christ this is going to make lazenn even more powerful

2022-05-11 22:27 UTC, LazennG commented
for clarification by 'high potency' i mean the most pwoerful gibtonite possible consistently

2022-05-12 01:07 UTC, ilikesaying commented
> for clarification by 'high potency' i mean the most pwoerful gibtonite possible

oh dear god the destructive potential

2022-05-14 01:48 UTC, ToasterBiome requested changes

2022-05-14 01:48 UTC, ToasterBiome commented on code/game/turfs/simulated/minerals.dm
> +	var/forceperfect = FALSE
```suggestion
```

never used

2022-05-14 01:48 UTC, ToasterBiome commented on code/game/turfs/simulated/minerals.dm
> +		defuse(forceperfect = FALSE)
```suggestion
		defuse(force_perfect = FALSE)
```

2022-05-14 01:48 UTC, ToasterBiome commented on code/game/turfs/simulated/minerals.dm
> +/turf/closed/mineral/gibtonite/proc/defuse(forceperfect = FALSE)
```suggestion
/turf/closed/mineral/gibtonite/proc/defuse(force_perfect = FALSE)
```

2022-05-14 01:48 UTC, ToasterBiome commented on code/game/turfs/simulated/minerals.dm
> +		if(det_time < 0 && !forceperfect)
```suggestion
		if(det_time < 0 && !force_perfect)
```

2022-05-14 01:48 UTC, ToasterBiome commented on code/game/turfs/simulated/minerals.dm
> +		if(forceperfect)
```suggestion
		if(force_perfect)
```

2022-05-14 01:48 UTC, ToasterBiome commented on code/game/turfs/simulated/minerals.dm
You are missing something here for if the det_time is > 0 and it's not forced perfect, using a normal mineral scanner here that you didn't get perfect will result in no message.

2022-05-14 01:48 UTC, ToasterBiome commented on code/game/turfs/simulated/minerals.dm
> +	if(istype(I, /obj/item/t_scanner/adv_mining_scanner/goat_scanner))
needs a stage check like the next if statement, looks like you can defuse one that isn't going off...

2022-05-14 01:48 UTC, ToasterBiome commented on code/game/turfs/simulated/minerals.dm
> +		defuse(forceperfect = TRUE)
```suggestion
		defuse(force_perfect = TRUE)
```

2022-05-15 10:46 UTC, LazennG commented
remembered to add a feature @Chubbygummibear suggested where upon defusing a piece of gibtonite ore for the second time with the goat scanner, the ore's potency is raised if it isn't already high

2022-05-16 12:23 UTC, grimm-hollowknight approved these changes

2022-05-16 19:40 UTC, JamieD1 approved these changes

2022-05-16 19:40 UTC, JamieD1 commented
Cornflakes

2022-05-21 03:54 UTC, ToasterBiome submitted a review, later dismissed
remove shoes.dmi

2022-05-21 12:20 UTC, JamieD1 approved these changes

2022-05-21 12:20 UTC, merged