Adds auto tail wagging when happy
yogstation13/Yogstation pull request #14124
Opened 2022-05-12 22:56 UTC by nmajask

# Document the changes in your pull request

Adds a small chance for felinids/liznerd to wag their tail when they are happy and if they aren't doing so already. It uses visable_mood, so its wont cause antags to wag because of their mood buff. Also adds human subtypes to a few species because I can.

# Wiki Documentation

Maybe add it to the mood wiki page. 

# Changelog

:cl:  
rscadd: Added chance for felinids and lizards to wag their tail when they are happy and if they aren't doing so already
rscadd: Added human subtypes for some species that were missing them, making it posable to spawn them in with spawn
/:cl:

2022-05-12 23:02 UTC, ToasterBiome commented
can we also have a base chance for non-mood head felinids????

2022-05-12 23:02 UTC, nmajask commented
> can we also have a base chance for non-mood head felinids????

Yes we can, when you code it

2022-05-12 23:03 UTC, ToasterBiome requested changes
a

2022-05-12 23:21 UTC, Anvilman6 commented
Too cute to exist

What if being sad made you _stop_ wagging, as an inverted addition to this?

2022-05-13 00:22 UTC, Chubbygummibear commented
> can we also have a base chance for non-mood head felinids????

moodless people don't deserve expressive wagging.

2022-05-13 04:27 UTC, NCRLouTenant commented
This is a fun one, thanks for putting this together!

2022-05-13 16:18 UTC, SomeguyManperson commented
should be a (higher) chance on entering top 2 mood tiers rather than a constant rolling thing

2022-05-16 21:51 UTC, nmajask commented
> should be a (higher) chance on entering top 2 mood tiers rather than a constant rolling thing

Im not too sure how i would do that, as the best way i can think of is to add a snowflake proc to when mood is changed and i would prefer to avoid that.

2022-05-16 22:01 UTC, JamieD1 approved these changes

2022-05-16 22:21 UTC, JamieD1 approved these changes

2022-05-16 22:21 UTC, merged