Cleaning up/fixing a lot of bad "send to world" code
yogstation13/Yogstation pull request #14134
Opened 2022-05-13 22:51 UTC by ynot01

# Document the changes in your pull request

Well this started out as a simple bugfix and I realized this was all over the damn place.

A lot of places used `to_chat(world` which sends a message to ALL CONNECTED PLAYERS including ones in the lobby. This has been substituted with the proper `send_to_playing_players`.

Other places would SEND_SOUND to all players, and this was changed to the proper `sound_to_playing_players`.

Along the way I found some debug messages that were left in `to_chat(world` so in the off chance that something went wrong and they actually PLAYED, all players would get `lover != Brutus` or `uh oh, stinky!!` in their chat. Very cool.

Some places were intentionally left out, particularly the Blob and Malf victory messages. As this ends the round instantly, and Jamie says not to touch it, it seems reasonable to me to keep it there and let lobby players know what happened. Until a maintainer says that shitting up the lobby chat is a bad idea, of course.
`to_chat(world, "<B>[real_name] consumed the station in an unstoppable tide!</B>")`
`to_chat(world, "<B>The AI cleansed the station of life with the doomsday device!</B>")`

There's a lot of other debug stuff in here but it seems pretty technical like savefile stuff so I'm not going to touch it until someone says to.

Closes #14133

# Changelog

:cl:  
bugfix: Fixed darkspawn force divulge being shown to lobby players
bugfix: Fixed darkspawn sacrament noise being heard by lobby players
bugfix: Fixed shadowling ascendant death being shown to lobby players
bugfix: Fixed shadowling ascend message being shown to lobby players
bugfix: Fixed shadowling ascend noise being heard by lobby players
bugfix: Fixed a particular cult god fight being shown to lobby players
bugfix: Fixed Gamma & Epsilon alerts being heard by lobby players
bugfix: Fixed Epsilon alert giving lobby players a bad feeling
/:cl:

2022-05-16 19:30 UTC, TheGamerdk requested changes

2022-05-16 19:30 UTC, TheGamerdk commented on yogstation/code/modules/antagonists/darkspawn/darkspawn.dm
> +		if(M.stat != DEAD && isdarkspawn(M))
won't you get double messages this way?

2022-05-20 16:50 UTC, bruhlookatthisdood commented
will this change people off the Z level getting station announcments?
like the old crew hearing about the shuttle, or announcments, or nar nar rising up?

2022-05-20 20:29 UTC, ynot01 commented
> will this change people off the Z level getting station announcements

No

2022-05-21 12:47 UTC, JamieD1 approved these changes

2022-05-21 22:58 UTC, ynot01 commented on yogstation/code/modules/antagonists/darkspawn/darkspawn.dm
> +		if(M.stat != DEAD && isdarkspawn(M))
no

2022-05-22 20:17 UTC, merged