Re-arranges the Captains office a bit
yogstation13/Yogstation pull request #14158
Opened 2022-05-17 01:29 UTC by MajManatee

# Document the changes in your pull request

Puts the paper shredder where the filing cabinet is
Puts the filing cabinet where the armor storage is
Puts the armor storage where the paper shredder is

# Changelog

:cl:  
tweak: Makes the captain not have to be Elastigirl to use the paper shredder
/:cl:

2022-05-17 01:32 UTC, ToasterBiome commented
What map?

2022-05-17 01:33 UTC, MajManatee commented
main yogstation map.

2022-05-17 01:34 UTC, ToasterBiome requested changes
changelog to specify map

2022-05-17 01:38 UTC, ToasterBiome requested changes
more descriptive changelog please

2022-05-17 01:39 UTC, MajManatee commented
grrr

2022-05-17 21:33 UTC, ToasterBiome approved these changes
Yogstation is a box confusing since that's our server name, can you change it to "box"?

2022-05-17 23:26 UTC, MajManatee commented
@ToasterBiome done

2022-05-17 23:28 UTC, ToasterBiome commented
3 seconds easier to steal the cap's jetpack

2022-05-17 23:28 UTC, ToasterBiome approved these changes

2022-05-17 23:29 UTC, MajManatee commented
you got me, that was my plan all along!

2022-05-21 13:00 UTC, JamieD1 approved these changes

2022-05-21 13:00 UTC, merged