moves atom/target in do_after() forward
yogstation13/Yogstation pull request #14161
Opened 2022-05-17 03:48 UTC by tattax

# Document the changes in your pull request

Remove this text and explain what the purpose of your PR is.

why would needhands be in front of the literal other essential arg for the proc to work properly

:cl:  
bugfix: fixed prog bars for TG ported stuff such as regal rats and other things that were supposed to have prog bars
tweak: moves target in do_after so it can now be typed without target=
spellcheck: cleans up unused args in do_after()s and code cleaning
/:cl:

2022-05-18 06:29 UTC, monster860 requested changes

2022-05-18 06:29 UTC, monster860 commented on code/game/objects/items/robot/robot_items.dm
> +		while(do_after(user, 1.5 SECONDS, target, progress = 0))
Since you did it for the above two, do it to this one too

```suggestion
		while(do_after(user, 1.5 SECONDS, target, progress = FALSE))
```

2022-05-18 06:29 UTC, monster860 commented on code/modules/antagonists/cult/blood_magic.dm
> +	if(do_after(owner, 10 SECONDS - rune*60, owner))
Aaa you're mixing the macro with no the macro!

Either do this:
```suggestion
	if(do_after(owner, (10 - rune*6) SECONDS, owner))
```

Or this:
```suggestion
	if(do_after(owner, 10 SECONDS - rune*(6 SECONDS), owner))
```

2022-05-19 23:54 UTC, monster860 approved these changes

2022-05-30 19:43 UTC, JamieD1 commented
This is going to break lots.. I can tell..

2022-05-30 20:25 UTC, merged