New wizard item: Demonic chainsaw
yogstation13/Yogstation pull request #14165
Opened 2022-05-17 23:32 UTC by cuackles

# Document the changes in your pull request
Adds a new item to the wizard spellbook, a demonic chainsaw based on pochita from chainsaw man, this chainsaw gives you lifesteal and does 30 damage each hit with no armor penetration, cost 3 wizard points like mjolmir or however its spelled

![2022-05-17 19_11_07-Space station 13_ MacRagge Object Sierra](https://user-images.githubusercontent.com/68789204/168928531-285572a1-d97b-4d4a-8ea1-49275d0826de.png)

# Wiki Documentation

add to the wizard items page the chainsaw, noting that it has lifesteal and a price of 3 points

# Changelog
:cl:  
rscadd: Added new wizard item: demon chainsaw
imageadd: added some icons for demon chainsaw
/:cl:

2022-05-17 23:35 UTC, ynot01 commented
3 points and no armor pen? yeesh

2022-05-17 23:39 UTC, cuackles commented
> 3 points and no armor pen? yeesh

From my testing the health Regen worked pretty well so i didn't want to give it to much, but if it shows to be to weak i can give it a bit of AP or reduce the cost

2022-05-17 23:55 UTC, tattax commented on code/game/objects/items/twohanded.dm
> +/obj/item/twohanded/required/chainsaw/attack_self(mob/user)
```suggestion
/obj/item/twohanded/required/chainsaw/demon/attack_self(mob/user)
```

2022-05-18 05:13 UTC, adamsong submitted a review, later dismissed

2022-05-18 05:13 UTC, adamsong commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +	desc = "A demon with the form of a chainsaw,this demon desires to see you fufill your wishes, so they shall give you ethernal life as long as you feed them blood."
```suggestion
	desc = "A demon with the form of a chainsaw, this demon desires to see you fulfill your wishes, so they shall give you eternal life as long as you feed them blood."
```

2022-05-18 11:58 UTC, TymurShatillo commented
It is spelled mjolnir

2022-05-18 14:01 UTC, ghost commented
I suggest moving this item code to code/modules/antagonist/wizard/equipment/artifacts

2022-05-20 00:50 UTC, Anvilman6 requested changes
Small changes

2022-05-20 00:50 UTC, Anvilman6 commented on code/game/objects/items/twohanded.dm
> +	to_chat(user, "As you pull the starting cord dangling from [src], [on ? "it begins to whirr." : "the chain stops moving."]")
You don't typically pull the starting cord to _stop_ a chainsaw, but this one is also magic, so maybe this is a who cares moment

2022-05-20 00:50 UTC, Anvilman6 commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +	desc = "A demon with the form of a chainsaw, this demon desires to see you fulfill your wishes, so they shall give you eternal life as long as you feed them blood."
```suggestion
	desc = "A demon that has taken the form of a chainsaw! This demon will grant you eternal life, so long as you feed it blood!"
```

2022-05-30 19:43 UTC, JamieD1 approved these changes

2022-05-30 19:44 UTC, merged