Adds APC and different areas for the multiple air alarms.. why could you siphon interrogation from perma..
yogstation13/Yogstation pull request #14163
Opened 2022-05-17 17:22 UTC by JamieD1

:cl:  
tweak: Fixes a couple air alarms and missing apc in brig
/:cl:

2022-05-18 02:14 UTC, ToasterBiome requested changes
Bad areastrings

2022-05-22 10:53 UTC, ToasterBiome requested changes
can you look on our other maps in rotation to see if they could also benefit from these new areas?

2022-05-22 21:02 UTC, JamieD1 commented on code/game/area/Space_Station_13_areas.dm
> +
```suggestion
```

2022-05-22 21:08 UTC, ToasterBiome requested changes
Box's prison hallway APC has the same name as the prison wing APC (for power inside perma)

Meta is missing the area + apc for prison hallway, despite being around the same size as box's

Delta does not have the prison hallway area + apc, despite being bigger than box's

Kilo does not have the prison hallway area + apc, despite being a shit map

2022-05-22 21:22 UTC, ToasterBiome approved these changes
ye looks good

2022-05-22 21:56 UTC, merged