Firesuit back-slot can hold full sized oxygen tanks  (like the one that comes in the fire closet)
yogstation13/Yogstation pull request #14185
Opened 2022-05-19 22:03 UTC by Chubbygummibear

Funny story you can't actually back slot equip the oxygen tank that spawns in the fire cabinet with the emergency fire suit

# Changelog

:cl:  
tweak: emergency firesuit can fit full sized oxygen tanks in its suit slot 
/:cl:

2022-05-19 23:06 UTC, ToasterBiome commented
fix title and changelog to have correct slot

2022-05-19 23:07 UTC, Chubbygummibear commented
> fix title and changelog to have correct slot

fixed

2022-05-19 23:10 UTC, ToasterBiome requested changes
suit storage slot changelog!!!!!!!!!!!!!!!!!!

2022-05-19 23:43 UTC, ToasterBiome approved these changes

2022-05-19 23:43 UTC, ToasterBiome approved these changes
yeah

2022-05-21 06:36 UTC, Cartlord commented
Can it still hold the small tanks?

2022-05-21 11:29 UTC, Chubbygummibear commented
> Can it still hold the small tanks?

yuh

2022-05-21 14:00 UTC, JamieD1 commented
You are supposed to wear it on your back
![image](https://user-images.githubusercontent.com/993128/169655025-d682cd5f-4480-4c4a-bbdd-22f93c6ed9e9.png)

2022-05-21 18:26 UTC, Chubbygummibear commented
> You are supposed to wear it on your back ![image](https://user-images.githubusercontent.com/993128/169655025-d682cd5f-4480-4c4a-bbdd-22f93c6ed9e9.png)

When I looked at the images of firefighters with the tank on their back I kinda felt like the rigging for it was more the suit doing the work than wearing an oxygen tank backpack. That's why I thought suit storage was adequate for it. Ultimately up to you, Jams

2022-05-22 20:38 UTC, JamieD1 approved these changes

2022-05-22 20:38 UTC, merged

2022-05-23 01:14 UTC, Firewolf34 commented
This is something we've needed for so long