round actually ends on narsie
yogstation13/Yogstation pull request #14207
Opened 2022-05-21 23:53 UTC by ynot01

# Document the changes in your pull request

better than #11030

times tweaked so the cinematic has just enough time to play before the game closes at 1m30s (90s)

round ends (not real code just approx)
`sleep(50)` 5s
An acausal dimensional event has been detecte...
`sleep(300)` 30s
Simulations on acausal dimensional event complete. Deploying ...
`sleep(50)` 5s
`set_security_level("delta")`
`sleep(250)` 25s
`addtimer(CALLBACK(GLOBAL_PROC, .proc/cult_ending_helper), 120)` 12s

this takes 77 seconds to trigger the actual cinematic

cinematic plays:

`flick("intro_cult",screen)`
`sleep(25)` 2.5s
`cinematic_sound(sound('sound/magic/enter_blood.ogg'))`
`sleep(28)` 2.8s
`cinematic_sound(sound('sound/machines/terminal_off.ogg'))`
`sleep(20)` 2.0s
`flick("station_corrupted",screen)`
`cinematic_sound(sound('sound/effects/ghost.ogg'))`
`sleep(70)` 7.0s
`special()`

this totals out to be 91.3s 
so at exactly 91.3 seconds after round ends, `special()` triggers

`special()` actually doesn't do anything anymore but it's a good signifier of when the cinematic probably ends if not a little sooner

it's fine

# Changelog

:cl:  
tweak: Round now ends on Nar-sie summon for real this time
/:cl:

2022-05-22 15:48 UTC, TheGamerdk commented
Use time defines

2022-05-22 17:27 UTC, ynot01 commented
> Use time defines

i hate you

2022-05-22 19:41 UTC, tattax reviewed
now do spawns

2022-05-22 19:41 UTC, tattax commented on code/game/objects/items/toys.dm
>  		spawn(0)
```suggestion
		spawn(0 SECONDS)
```

2022-05-22 19:55 UTC, ynot01 commented on code/game/objects/items/toys.dm
>  		spawn(0)
ill add it to the list

2022-05-22 20:13 UTC, TheGamerdk commented
atomize the time changes

2022-05-22 20:42 UTC, ynot01 commented
> atomize the time changes

no

2022-05-23 13:13 UTC, TheGamerdk requested changes
atomize the time commits into a separate PR :)

2022-05-23 20:47 UTC, ynot01 commented
no

2022-05-23 20:52 UTC, ynot01 commented
ok fine

2022-05-25 15:47 UTC, TheGamerdk commented
yay

2022-05-28 21:56 UTC, JamieD1 approved these changes

2022-05-28 21:56 UTC, merged