Alert & delay when swarmer dismantling ore silo
yogstation13/Yogstation pull request #14293
Opened 2022-05-31 20:41 UTC by ynot01

# Document the changes in your pull request

Dismantling the ore silo can cripple the entire round and should not be as easy as popping into the vault vent and dismantling it as you would any other machine

Makes prio announcement & takes 30 seconds as opposed to 10 seconds

30 seconds seems reasonable, crew by then will either respond with proper access or they won't at all

# Changelog

:cl:  
tweak: Swarmers dismantling the ore silo now alerts the station and takes 30 seconds
/:cl:

2022-06-01 00:19 UTC, ToasterBiome commented
vent upgrade that you print from the protolathe and ventcrawlers can't pop up out of it

make only one spawn on the entire map (vault)

fixed it

2022-06-01 02:11 UTC, SomeguyManperson commented
this is a HUGBOX CHANGE and you should SIMPLY PLAY BETTER to stop swarmers from SNEAKING INTO THE VAULT

2022-06-01 15:14 UTC, Hopekz commented
> this is a HUGBOX CHANGE and you should SIMPLY PLAY BETTER to stop swarmers from SNEAKING INTO THE VAULT

Isn't it metagaming to immediately know the intricacies of an antag to the point where you build exact preventative measures against them before they do whatever they're going to do?

Your argument doesn't work for everyone because other people might get banned for trying to implement your suggestion.

2022-06-02 17:07 UTC, Anvilman6 requested changes
Changes for consideration

2022-06-02 17:07 UTC, Anvilman6 commented on code/modules/swarmers/swarmer.dm
> +			priority_announce("Connection encryption violation in machine: [target]. Deconstruction ETA: 30 SECONDS")
```suggestion
			priority_announce("Connection encryption violation in machine: [target]! Deconstruction projected to complete in: 30 SECONDS")
```

2022-06-02 17:07 UTC, Anvilman6 commented on code/modules/swarmers/swarmer.dm
>  	to_chat(src, span_info("We begin to dismantle this machine. We will need to be uninterrupted."))
```suggestion
	to_chat(src, span_info("We begin to dismantle this machine. We will need to be uninterrupted for some time."))
```

2022-06-04 15:13 UTC, JamieD1 approved these changes

2022-06-04 15:13 UTC, merged