[PORT] Adds even more foods! [SHITTY NAME]
yogstation13/Yogstation pull request #14294
Opened 2022-06-01 03:09 UTC by ToasterBiome

# Document the changes in your pull request

https://github.com/tgstation/tgstation/pull/66380

![image](https://user-images.githubusercontent.com/5091394/171320010-20a76578-c77c-4545-921d-a978ee076fa5.png)

Changes for yogs: 

French Toast now comes raw, requires different things, reagents are now halfway between yogs' and tg's
we dont have cornchips for chips and salsa so it requires a bag of chips instead (yup)

wildly untested but compiles yep

# Wiki Documentation

French Toast recipe different, new recipes/items.

# Changelog

:cl:  MidoriWroth, ToasterBiome
rscadd: Adds 7 new foods! The power of chefs continues to grow.
/:cl:

2022-06-02 17:04 UTC, Anvilman6 requested changes
First pass review

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_bread.dm
> +	desc = "A slice of bread soaked in a beaten egg mixture. Put it on a griddle to start cooking!."
```suggestion
	desc = "A slice of bread soaked in a beaten egg mixture. Put it on a griddle to start cooking!"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_meat.dm
> +	desc = "A roll of simple vegetarian sushi with rice, carrots, and potatoes. Sliceable into pieces!"
```suggestion
	desc = "A roll of simple vegetarian sushi, made with rice, carrots, and potatoes. Able to be sliced into pieces!"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_meat.dm
> +	desc = "A roll of tasty, spicy sushi made with fish and vegetables. Sliceable into pieces!"
```suggestion
	desc = "A roll of tasty, spicy sushi, made with fish and vegetables. Able to be sliced into pieces!"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_meat.dm
> +	desc = "A slice of tasty, spicy sushi made with fish and vegetables. Don't eat it too fast!."
```suggestion
	desc = "A slice of tasty, spicy sushi, made with fish and vegetables. Don't eat it too fast!"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_meat.dm
> +	desc = "A slice of simple vegetarian sushi with rice, carrots, and potatoes."
```suggestion
	desc = "A slice of simple vegetarian sushi, made with rice, carrots, and potatoes."
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_meat.dm
> +	desc = "Some tortilla chips with a cup of zesty salsa. Highly addictive!"
```suggestion
	desc = "A handful of tortilla chips, paired with a cup of zesty salsa. Highly addictive!"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_meat.dm
> +	desc = "Some tortilla chips with a cup of zesty salsa. Highly addictive!"
Salsa OD effect when

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +	desc = "A decadent pie made of a creamy chocolate mousse filling topped with a layer of whipped cream and chocolate shavings. Sliceable."
```suggestion
	desc = "A decadent pie made of a creamy chocolate mousse filling, topped with a layer of whipped cream and chocolate shavings. Able to be sliced!"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +	desc = "A slice of french silk pie, filled with a chocolate mousse and topped with a layer of whipped cream and chocolate shavings. Delicious enough to make you cry."
```suggestion
	desc = "A slice of French silk pie, filled with a chocolate mousse, and topped with a layer of whipped cream and chocolate shavings. Decadent and delectable!"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +	name = "french silk pie slice"
```suggestion
	name = "French silk pie slice"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +	foodtype = GRAIN | DAIRY | SUGAR
Do we not have a chocolate type? Thought we did for Felinid poisoning

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +	foodtype = GRAIN | DAIRY | SUGAR
Chocolate?

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
> +	name = "Raw French Toast"
```suggestion
	name = "raw French toast"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_bread.dm
> +	name = "raw french toast"
```suggestion
	name = "raw French toast"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_bread.dm
>  	name = "french toast"
```suggestion
	name = "French toast"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_bread.dm
> +	desc = "A slice of bread soaked in an egg mixture and grilled until golden-brown. Drizzled with syrup!."
```suggestion
	desc = "A slice of bread soaked in an egg mixture and grilled until golden-brown. Drizzled with syrup!"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
> +	name = "Chips and Salsa"
```suggestion
	name = "Chips and salsa"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
> +	name = "French Silk Pie"
```suggestion
	name = "French silk pie"
```

2022-06-02 17:04 UTC, Anvilman6 commented on code/modules/research/designs/biogenerator_designs.dm
> +	name = "Seaweed Sheet"
```suggestion
	name = "Seaweed sheet"
```

2022-06-05 21:46 UTC, ToasterBiome commented on code/modules/food_and_drinks/food/snacks_bread.dm
>  	name = "french toast"
Nope, these are not capitalized

2022-06-05 21:47 UTC, ToasterBiome commented on code/modules/food_and_drinks/food/snacks_bread.dm
>  	name = "french toast"
Fuck french is a proper noun (i hate the french)

2022-06-05 21:47 UTC, ToasterBiome commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +	foodtype = GRAIN | DAIRY | SUGAR
shrug

2022-06-05 21:47 UTC, ToasterBiome commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +	foodtype = GRAIN | DAIRY | SUGAR
we do

2022-06-05 21:48 UTC, ToasterBiome commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
> +	name = "Chips and Salsa"
Crafting recipe names are capitalized like that

2022-06-06 11:52 UTC, KillerOrcaCora requested changes
Some of these sprites can use touching up on, will modify them and have a list of downloads done by 3 days from now.

2022-06-06 14:53 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +	foodtype = GRAIN | DAIRY | SUGAR
Should be applied to the silk pies then, since their taste is quite directly "smooth chocolate"

2022-06-06 14:53 UTC, Anvilman6 commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +	foodtype = GRAIN | DAIRY | SUGAR
Mirror above

2022-06-06 14:55 UTC, Anvilman6 commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
> +	name = "Chips and Salsa"
Noted, that's fine for conforming to the standard, even though the standard is wrong

2022-06-07 00:11 UTC, KillerOrcaCora approved these changes
Alrighty, everything else is fine.

2022-06-07 09:29 UTC, merged