Ports "Revives "Adds sound effects to surgeries"" and others
yogstation13/Yogstation pull request #14390
Opened 2022-06-12 02:31 UTC by nmajask

# Document the changes in your pull request

Ports some surgery sound PRs and tweaks a few other surgery/sound related things. The PRs that this ports are:

-  ["Revives "Adds sound effects to surgeries"" #65578](https://github.com/tgstation/tgstation/pull/65578) by [maxspells](https://github.com/maxspells) and [nmajask](https://github.com/nmajask)
-  ["Surgery sound fix attempt 2" #66018](https://github.com/tgstation/tgstation/pull/66018) by [TheBoondock](https://github.com/TheBoondock)
-  ["Makes cautery a lot quieter" #66330](https://github.com/tgstation/tgstation/pull/66330) by [maxspells](https://github.com/maxspells)
-  ["Fixes a copy+paste issue with "open the hatch" surgery step sound" #66441](https://github.com/tgstation/tgstation/pull/66441) by [MrMelbert](https://github.com/MrMelbert)

# Spriting
No new sprites.

# Wiki Documentation

No changes needed. 

# Changelog

:cl:  maxspells, TheBoondock, MrMelbert, nmajask
soundadd: added sounds to surgery steps
bugfix: fixed medical sounds for wounds, rad laser, and PDA health scan
tweak: doctors now say "Clear!" during revive surgery 
spellcheck: fixed revive surgery saying "shock body" instead of "shock brain"  
/:cl:

2022-06-14 17:20 UTC, JamieD1 requested changes

2022-06-14 17:20 UTC, JamieD1 commented on code/game/objects/items/devices/PDA/PDA.dm
> +					beep_cooldown = world.time+40
```suggestion
				if(beep_cooldown < world.time)
					playsound(src, 'sound/effects/fastbeep.ogg', 20)
					beep_cooldown = world.time + 40
```

2022-06-14 17:20 UTC, JamieD1 commented on code/game/objects/items/devices/traitordevices.dm
> +			beep_cooldown = world.time+40
```suggestion
		if(beep_cooldown < world.time)
			playsound(src, 'sound/effects/fastbeep.ogg', 20)
			beep_cooldown = world.time + 40
```

2022-06-14 17:20 UTC, JamieD1 commented on code/modules/surgery/mechanic_steps.dm
```suggestion
			preop_sound = tool.usesound
```

2022-06-14 17:20 UTC, JamieD1 commented on code/modules/surgery/mechanic_steps.dm
> +
```suggestion
	return TRUE

```

2022-06-14 17:20 UTC, JamieD1 commented on code/modules/surgery/mechanic_steps.dm
> +	return TRUE
```suggestion
	return TRUE
```

2022-06-14 17:20 UTC, JamieD1 commented on code/modules/surgery/mechanic_steps.dm
> +	return TRUE
```suggestion
	return TRUE
```

2022-06-14 17:20 UTC, JamieD1 commented on code/modules/surgery/surgery_step.dm
> +
```suggestion
```

2022-06-14 17:31 UTC, JamieD1 approved these changes

2022-06-14 17:31 UTC, merged

2022-06-15 06:14 UTC, GalacticRuler commented
hey about this, the sounds are like, excessively loud for what they are; and all seem to be right-speaker only?