Nukies Minigun is now more... Minigun-like
yogstation13/Yogstation pull request #14446
Opened 2022-06-15 01:03 UTC by MajManatee

# Document the changes in your pull request

Changes the standard burst to be 5rnds, and adds a 10rnd burst option.
What sort of LAME ASS MINIGUN fires in 3 round bursts? NOT THIS ONE ANYMORE BABY!!

# Changelog

:cl:  
rscadd: Minigun go BRRRRRRRRRRRRRRRT
/:cl:

2022-06-15 01:10 UTC, VaelophisNyx commented
why not add an emag mode that lets you click in a direction and, until you move, mag-dump?

2022-06-15 01:12 UTC, tattax commented on code/modules/projectiles/guns/ballistic/minigun.dm
> +	var/mob/living/carbon/human/user = usr
```suggestion
	var/mob/living/carbon/user = usr
```

2022-06-15 01:12 UTC, tattax commented on code/modules/projectiles/guns/ballistic/minigun.dm
> +	playsound(user, 'sound/weapons/empty.ogg', 100, 1)
```suggestion
		if(!select)
			select = TRUE
			burst_size = initial(burst_size)
			to_chat(user, span_notice("You switch to [burst_size]-rnd burst."))
		else
			select = FALSE
			burst_size = 10
			to_chat(user, span_notice("You switch to [burst_size]-rnd burst. BRRRRRRRT."))
	playsound(user, 'sound/weapons/empty.ogg', 100, TRUE)
```

2022-06-15 01:12 UTC, tattax commented on code/modules/projectiles/guns/ballistic/minigun.dm
> +	switch(select)
```suggestion

```

2022-06-15 01:12 UTC, tattax commented on code/modules/projectiles/guns/ballistic/minigun.dm
> +		..()
```suggestion
	. = ..()
```

2022-06-15 01:12 UTC, tattax commented on code/modules/projectiles/guns/ballistic/minigun.dm
> +		..()
burst select always returns so you don't need an else

2022-06-15 01:12 UTC, tattax commented on code/modules/projectiles/guns/ballistic/minigun.dm
> +	var/select = 1
```suggestion
	var/select = FALSE
```

2022-06-15 01:13 UTC, tattax commented on code/modules/projectiles/guns/ballistic/minigun.dm
> +	var/mob/living/carbon/human/user = usr
also why is this defined in the first place it doesn't change anything cause you'll need to have the action to activate it anyways

2022-06-15 03:28 UTC, Hopekz commented
> why not add an emag mode that lets you click in a direction and, until you move, mag-dump?

I don't think it would be consistent to be able to emag ballistic guns, so if this feature gets added I'd say toss it in to what the minigun is able to do from the start.

If this becomes a thing I'd like to mimic how miniguns in video games have a wind-up. Something like a heavy from Tf2 minigun windup before firing

2022-06-15 03:40 UTC, maxion12345 commented
oh good the nukie minigun needs a permit 
phew

2022-06-21 21:27 UTC, JamieD1 requested changes
Change spread to 30 and max burst to 5. Tested this and its a good compromise.

2022-06-26 11:48 UTC, JamieD1 approved these changes

2022-06-26 11:48 UTC, merged