Adds winter coats for department heads
yogstation13/Yogstation pull request #14468
Opened 2022-06-16 05:46 UTC by SapphicOverload

# Document the changes in your pull request

Ports winter coats for department heads from tg.

# Spriting

![image](https://user-images.githubusercontent.com/93578146/173999904-7ee01fb3-2dc0-4599-a13a-14879970a600.png)

# Changelog

:cl:  
rscadd: adds winter coats for department heads
/:cl:

2022-06-16 05:49 UTC, KillerOrcaCora commented
Where are the in-hand sprites?

2022-06-16 05:57 UTC, ynot01 commented
adorable

2022-06-16 06:09 UTC, Mqiib commented
RD's coat needs to have some ridiculous name like "Research Director's Advanced External Thermal Insulator" because science

2022-06-16 07:10 UTC, tattax requested changes

2022-06-16 07:10 UTC, tattax commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(MELEE = 35, BULLET = 25, LASER = 40, ENERGY = 50, BOMB = 35, BIO = 0, FIRE = 0, ACID = 55)
```suggestion
	armor = list(MELEE = 35, BULLET = 25, LASER = 40, ENERGY = 50, BOMB = 35, BIO = 0, RAD = 0, FIRE = 0, ACID = 55)
```

2022-06-16 07:10 UTC, tattax commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 50, FIRE = 20, ACID = 30)
```suggestion
	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 50, RAD = 0, FIRE = 20, ACID = 30)
```

2022-06-16 07:10 UTC, tattax commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 50, FIRE = 20, ACID = 30)
```suggestion
	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 50, RAD = 0, FIRE = 20, ACID = 30)
```

2022-06-16 07:10 UTC, tattax commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 20, BIO = 0, FIRE = 30, ACID = 0)
```suggestion
	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 20, BIO = 0, RAD = 0, FIRE = 30, ACID = 0)
```

2022-06-16 07:10 UTC, tattax commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 20, BIO = 0, FIRE = 30, ACID = 0)
```suggestion
	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 20, BIO = 0, RAD = 0, FIRE = 30, ACID = 0)
```

2022-06-16 07:10 UTC, tattax commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 0, FIRE = 30, ACID = 10)
```suggestion
	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 0, RAD = 30, FIRE = 30, ACID = 10)
```

2022-06-16 07:10 UTC, tattax commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 0, FIRE = 30, ACID = 10)
```suggestion
	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 0, RAD = 0, FIRE = 30, ACID = 10)
```

2022-06-16 20:28 UTC, tattax commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 0, RAD = 15, FIRE = 30, ACID = 10)
```suggestion
	armor = list(MELEE = 0, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 0, RAD = 15, FIRE = 30, ACID = 10)
```

tbh if you're gonna add armor to the CE hood add it to the normal engie hood aswell

2022-06-17 00:58 UTC, tattax commented
can you link the original PR and author btw?

2022-06-17 01:11 UTC, SapphicOverload commented
> can you link the original PR and author btw?
https://github.com/tgstation/tgstation/pull/56854

2022-06-17 05:03 UTC, TheRyeGuyWhoWillNowDie commented
> head of security coat with 50 energy armor

that value seems incorrect

2022-06-17 07:07 UTC, KillerOrcaCora requested changes
Winter coat themselves need some form of in-hand sprites done.

2022-06-18 22:03 UTC, SapphicOverload commented
> Winter coat themselves need some form of in-hand sprites done.

done

2022-06-19 10:33 UTC, JamieD1 approved these changes

2022-06-21 21:30 UTC, KillerOrcaCora reviewed
Alright, this is fine now.

2022-06-21 21:30 UTC, KillerOrcaCora approved these changes

2022-06-26 11:56 UTC, merged