Blob buff: double blob passive point gen
yogstation13/Yogstation pull request #14487
Opened 2022-06-18 04:40 UTC by GalacticRuler

blobs struggle to keep up with crew attacking on all sides with late-late game weapons like Particle accelerators and Phazons. This buff should help with that a little.

# Document the changes in your pull request

Blob default passive resource generation (ie: not from resource blobs) increased from 2 to 4

Changes UNTESTED. Requires testing that is practically impossible in a local-host environment.

this change is made to help blobs counter 6-10 crew members/borgs, emitters, heavily armed combat mechs, particle accelerators, all hammering away at it from many directions at once. The moment a blob is spotted, you have mere moments before you will be engaged in the passive resource drain of being forced to replace blob tiles faster than you generate points, even with resource blobs.

This does not make any changes to blob resource cap, nor the speed at which resource-blobs generate resources, nor the slowdown from placing more resource blobs

# Wiki Documentation

Blob wiki might need a tweak to match? Unsure if resource rate is mentioned there.

# Changelog

:cl:  
tweak: blob base resource generation up to 4, from 2
/:cl:

2022-06-18 04:41 UTC, GalacticRuler commented
HEAVILY desire input from others on this, as while I think this would help, I want to hear from others. This is based on my experiences playing blob, others might have different experiences.

2022-06-18 04:44 UTC, GalacticRuler commented
Also I'm not even sure I've changed this in the right place; or if random blobs even occur, which if that is the case, this change does nothing as admin spawned blobs have custom resource generation rates

2022-06-18 19:20 UTC, maxion12345 commented
I uh
what about blobs that get lucky and spawn before crew get midround stuff?@ a buff like this could turn this into "very difficult fight while rushing tech/Mecha" to "why even bother just set the self destruct"

2022-06-18 22:22 UTC, GalacticRuler commented
I won't lie, I can't ultimately test that solo. But also I have never seen a blob spawn when the crew didn't already have 10+ ways of dealing with it laying around or ready to print

2022-06-19 10:04 UTC, TheGamerdk requested changes
This var doesn’t do anything

Also you can definitely test this change locally

2022-06-19 12:30 UTC, JamieD1 commented
How about you make the point gen scale with round duration

2022-06-20 01:00 UTC, GalacticRuler commented
Well Jamie, I would; however. I have no idea how to do that

2022-06-20 01:58 UTC, GalacticRuler commented
I don't have enough experience to do this right now.

2022-06-20 01:58 UTC, closed without merging