sabo borgs have emags now what
yogstation13/Yogstation pull request #14517
Opened 2022-06-20 19:16 UTC by TheRyeGuyWhoWillNowDie

??? why dont they have an emag
even the fucking mediborg gets an emag lmao
sabo is supposed to sabotage, but they dont get an emag??

# Wiki Documentation

cyborg modules page

# Changelog

:cl:  
rscadd: syndie sabo borgs now have emags
/:cl:

2022-06-20 19:20 UTC, redmoogle requested changes

2022-06-20 19:20 UTC, redmoogle commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		/obj/item/card/emag
Add a comma to the end of it

2022-06-20 19:24 UTC, redmoogle approved these changes
,

2022-06-21 22:02 UTC, JamieD1 approved these changes

2022-06-21 22:03 UTC, merged