Research now requires Toxins/Robotics Access and now has Doors
yogstation13/Yogstation pull request #14559
Opened 2022-06-22 21:46 UTC by JamieD1

Research now requires Toxins/Robotics Access and now has Doors
Also updates some windows and fixes access on a couple doors.

:cl:  
rscadd: Research now requires Toxins/Robotics Access and now has Doors
/:cl:

2022-06-22 21:48 UTC, N3D6 commented
Which option did you go with? Can we get a screenshot?

2022-06-22 21:49 UTC, maxion12345 commented
![XiEA4oq](https://user-images.githubusercontent.com/23666142/175144862-182be841-be17-4cb3-b3b5-c920d6ed6a2e.png)
>not even glass airlocks

2022-06-22 21:58 UTC, JamieD1 commented
> ![XiEA4oq](https://user-images.githubusercontent.com/23666142/175144862-182be841-be17-4cb3-b3b5-c920d6ed6a2e.png)
> 
> > not even glass airlocks

Fixed

2022-06-22 21:59 UTC, Bibby0110 requested changes

2022-06-22 21:59 UTC, Bibby0110 commented on code/game/objects/items/circuitboards/computer_circuitboards.dm
> +		if(build_path == /obj/machinery/computer/rdconsole/production)
Undocumented change

2022-06-22 21:59 UTC, Bibby0110 commented on code/modules/research/rdconsole.dm
> +	if(locked == FALSE)
```suggestion
	if(!locked)
```
Consoles are by default unlocked. You can’t research if it’s locked IIRC

2022-06-22 21:59 UTC, Bibby0110 commented on code/modules/research/rdconsole.dm
> +	var/obj/item/card/id/C = user.get_idcard(TRUE)
Just check allowed(user)

2022-06-22 22:03 UTC, JamieD1 commented on code/modules/research/rdconsole.dm
> +	if(locked == FALSE)
Its for an emag check

2022-06-22 22:04 UTC, JamieD1 commented on code/game/objects/items/circuitboards/computer_circuitboards.dm
> +		if(build_path == /obj/machinery/computer/rdconsole/production)
Bugfix

2022-06-22 22:10 UTC, ToasterBiome commented
Why though?

2022-06-22 23:07 UTC, Cartlord commented
Why not use the large airlock? It's not a Clerk-only thing, ruins use it too.

2022-06-23 03:33 UTC, Runian commented
What's this suppose to stop? You can walk into the experiment room for the research console and you can go to the testing lab to access the secondary protolathe unless the airlock access has been changed.

2022-06-23 05:45 UTC, ToasterBiome requested changes
honestly jst do the machinery one the map change sucks ass

2022-06-23 11:10 UTC, TheGamerdk commented on code/game/objects/items/circuitboards/computer_circuitboards.dm
> +		if(build_path == /obj/machinery/computer/rdconsole/production)
What bug?

2022-06-23 13:48 UTC, N3D6 commented
> Why not use the large airlock? It's not a Clerk-only thing, ruins use it too.

It’s ugly and buggy

2022-06-23 18:15 UTC, SomeguyManperson commented
super ultra hugbox extreme 2

2022-06-23 18:36 UTC, SomeguyManperson commented on code/game/objects/items/circuitboards/computer_circuitboards.dm
> +		if(build_path == /obj/machinery/computer/rdconsole/production)
if you're going to be making a bugfix atomize it don't shove it into another pr

2022-06-25 22:19 UTC, maxion12345 commented
> > Why not use the large airlock? It's not a Clerk-only thing, ruins use it too.
> 
> It’s ugly and buggy

everyone out here says it buggy yet I can't find a single mf to tell me how

2022-06-25 22:19 UTC, maxion12345 commented
> super ultra hugbox extreme 2

TFW xantam has you fix the """"bug""""" with the engineering console

2022-06-28 19:33 UTC, merged