Blinking with bluespace crystals is 233% more unpleasant
yogstation13/Yogstation pull request #14579
Opened 2022-06-24 02:59 UTC by Mqiib

This should cull the bluespace crystal smashing spam that is really annoying to deal with, at least partially because antags will drain ALL the crystals from the silo. Use them sparingly, or pay the price!

One crystal won't be an issue, but two consecutive will put you in the danger zone. Waiting about 20 seconds will make you mostly safe from vomiting after smashing one, but using a third will really make your tummy frowny face :((((

# Wiki Documentation

Smashing a bluespace crystal makes you nauseous.

# Changelog

:cl:  

tweak: Smashing a bluespace crystal now makes you nauseous and slightly confused

/:cl:

2022-06-24 03:02 UTC, applepineapplepizza commented
does this apply to blue space tomatoes?

2022-06-24 04:15 UTC, Marmio64 commented
this may encourage going to drink vendors or the bartender to get sol dry, which helps reduce nasuea, which is nice.

2022-06-24 16:26 UTC, nmajask commented on code/game/objects/items/stacks/bscrystal.dm
> +		H.confused += 7
May want to put this in blink_mob() instead

2022-06-24 20:54 UTC, Georgeur commented
Good change they’re meta bullshit.

2022-06-26 10:09 UTC, TheGamerdk commented on code/game/objects/items/stacks/bscrystal.dm
> +		H.confused += 7
Move to blink_mob if you want it to effect people hit by thrown crystals

2022-06-26 10:10 UTC, TheGamerdk commented on code/game/objects/items/stacks/bscrystal.dm
> +	if(ishuman(user))
Move to just carbon, they have disgust + confused too

2022-06-26 13:50 UTC, JamieD1 requested changes

2022-06-26 13:50 UTC, JamieD1 commented on code/game/objects/items/stacks/bscrystal.dm
> +	if(ishuman(user))
```suggestion
	if(iscarbon(user))
```

2022-06-26 13:50 UTC, JamieD1 commented on code/game/objects/items/stacks/bscrystal.dm
> +		var/mob/living/carbon/human/H = user
```suggestion
		var/mob/living/carbon/C = user
```

2022-06-26 13:50 UTC, JamieD1 commented on code/game/objects/items/stacks/bscrystal.dm
> +		H.confused += 7
```suggestion
		C.adjust_disgust(30)	//Won't immediately make you vomit, just dont use more than one or two at a time
		C.confused += 7
```

2022-06-26 14:12 UTC, JamieD1 approved these changes

2022-06-26 14:12 UTC, merged