Switching to another computer
yogstation13/Yogstation pull request #14582
Opened 2022-06-24 11:17 UTC by redmoogle

# Document the changes in your pull request

# Still WIP just putting this up for now

Credits to BeeStation(Credits would be a milelong if I listed each individual port)

Adds IPCs
They're a synthetic race **different** from preternis, mainly with chassis customization and TV screens. They have a high burn mod
also they cant be cloned because they're robots. so you can use a cyborg rebooter in place of that.
They lose limbs easily but can be attached easily, Head is stored in the _chest_ and _can_ live without a head

Wiki Documentation:

There a race. They are robotic (they already have been given pictures needed, and from what I've heard are already working on the page)

System Cleaner | 1 part Ethanol, 1 part Chlorine, 2 parts Phenol, 1 part Potassium | Quickly purges toxin damage in the rare case an IPC gets said damge.

Solder: | 1 part Ethanol, 1 part Copper, 1 part Silver, Temperature 374K | Quickly heals brain damage and traumas, but only for IPCs

# Spriting

Not available Yet WIP

# Changelog

:cl:  Redmoogle, BeeStation
rscadd: Add IPCs from Beestation
/:cl:

2022-06-24 11:21 UTC, ynot01 commented
dejavu

2022-06-24 12:03 UTC, Moggram commented
We have been over this before and it was shot down.

2022-06-24 12:05 UTC, redmoogle commented
> We have been over this before and it was shot down.

It wasnt shot down. I just stopped working on it

2022-06-24 12:05 UTC, Spacemanspark commented
@Moggram for bad code and bugs from what I've heard, not for the feature itself.

Now, I'm curious; what's the extent of bee IPC customization?

And I might need a bigger breakdown of how bee IPCs work. If they really explode on death or some of the other things I've heard... ehhhh.

2022-06-24 14:40 UTC, Anvilman6 reviewed
Quick partial review

2022-06-24 14:40 UTC, Anvilman6 commented on code/modules/mob/living/carbon/human/species_types/IPC.dm
> +	siemens_coeff = 1.5
```suggestion
	siemens_coeff = 1.75 //Matches Preternis
	payday_modifier = 0.6 //Clunky robots are valued less
```

2022-06-24 14:40 UTC, Anvilman6 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +		if(prob(30) && C.has_trauma_type(BRAIN_TRAUMA_SPECIAL))
Higher chance to fix special traumas over minor?

2022-06-24 14:40 UTC, Anvilman6 commented on code/modules/reagents/chemistry/recipes/medicine.dm
> +	results = list(/datum/reagent/medicine/system_cleaner = 4)
5 components : 4 products is kind of an odd ratio

2022-06-24 17:12 UTC, Spacemanspark commented
Glory to Synthetica

2022-06-24 17:13 UTC, AlvCyktor commented
ayo???? AYO?????

2022-06-24 19:12 UTC, HisaHoshimo commented
I love this and I really hope it comes in the game~ I did notice on a private server that the special organs that IPCs have such as the cell don't have sprites when I take them out of the body however.

2022-06-24 20:11 UTC, redmoogle commented
> I love this and I really hope it comes in the game~ I did notice on a private server that the special organs that IPCs have such as the cell don't have sprites when I take them out of the body however.

Fixed it

2022-06-24 21:45 UTC, HisaHoshimo commented
Are the brain surgeries supposed to be on the head, or moved to the chest? Brain Surgery, Brainwashing, Lobotomy and Pacification are still surgeries when aimed at the head

2022-06-24 21:52 UTC, Spacemanspark commented
Should any of those even work on IPCs given that they're robots and not imbued with inferior flesh brains

2022-06-24 21:56 UTC, HisaHoshimo commented
> Should any of those even work on IPCs given that they're robots and not imbued with inferior flesh brains

That is true, Solder is supposed to be the go to for all the brain shiz, so I guess they shouldnt even be there. Idk what people would think of not being able to brainwash/pacify them. Maybe make it use an Law upload board for a step in brainwashing?

2022-06-25 12:11 UTC, redmoogle commented
> Are the brain surgeries supposed to be on the head, or moved to the chest? Brain Surgery, Brainwashing, Lobotomy and Pacification are still surgeries when aimed at the head

I can always make some additions to surgery to make it better

2022-06-25 12:46 UTC, HisaHoshimo commented
> > Are the brain surgeries supposed to be on the head, or moved to the chest? Brain Surgery, Brainwashing, Lobotomy and Pacification are still surgeries when aimed at the head
> 
> I can always make some additions to surgery to make it be able to do certain surgery for other than the _normal_ slots

Up to you at the end of the day, either way its looking good~

2022-06-30 18:53 UTC, Kapu1178 commented
oh you poor soul.

This code is extremely cursed and really not worth porting. It has so many issues and hacky work arounds to this day, and introduces alot of tech debt. I am responsible for fixing up a large part of it but I'd still recommend just remaking them from scratch, it's unsalvagable.

2022-06-30 19:00 UTC, redmoogle commented
> oh you poor soul.
> 
> This code is extremely cursed and really not worth porting. It has so many issues and hacky work arounds to this day, and introduces alot of tech debt. I am responsible for fixing up a large part of it but I'd still recommend just remaking them from scratch, it's unsalvagable.

that would likely rewrite a large amount of organ/surgery code which I would rather do after this

2022-06-30 19:09 UTC, Kapu1178 commented
> > oh you poor soul.
> > This code is extremely cursed and really not worth porting. It has so many issues and hacky work arounds to this day, and introduces alot of tech debt. I am responsible for fixing up a large part of it but I'd still recommend just remaking them from scratch, it's unsalvagable.
> 
> that would likely rewrite a large amount of organ/surgery code which I would rather do after this

as the guy who *did* that, I really, really suggest against it. I also took a peek at the code and it looks like you're using an outdated version which lacks my optimizations and bugfixes. Especially the one to reagent processing.

2022-07-09 17:58 UTC, Anvilman6 requested changes
Payday Modifier

2022-07-09 17:58 UTC, Anvilman6 commented on code/modules/mob/living/carbon/human/species_types/IPC.dm
> +	limbs_id = "synth"
```suggestion
	limbs_id = "synth"
	payday_modifier = 0.6 //Mass producible labor
```

2022-07-09 17:58 UTC, Anvilman6 commented on code/modules/mob/living/carbon/human/species_types/IPC.dm
> +	limbs_id = "synth"
Adds payday modifier for consistency with other species

2022-07-09 18:04 UTC, Anvilman6 commented on code/modules/mob/living/carbon/human/species_types/IPC.dm
> +	limbs_id = "synth"
I'll do a full look through at some point soon

2022-07-10 19:20 UTC, MegaEmpirical commented
If you cut their head off and examine, it's as if you're examining their body and it'll say head missing and everything they're wearing.

2022-07-10 19:24 UTC, Spacemanspark commented
@MegaEmpirical

The _brain_ is in the torso. IPCs can survive without a head, as the positronic is seated in the torso.

2022-07-10 19:34 UTC, MegaEmpirical commented
> @MegaEmpirical
> 
> The _brain_ is in the torso. IPCs can survive without a head, as the positronic is seated in the torso.

So they're cyborgs not robots?

2022-07-10 20:30 UTC, redmoogle commented
> > @MegaEmpirical
> > The _brain_ is in the torso. IPCs can survive without a head, as the positronic is seated in the torso.
> 
> So they're cyborgs not robots?

what dictates robots not having brains in their torso

2022-07-10 21:13 UTC, MegaEmpirical commented
> > > @MegaEmpirical
> > > The _brain_ is in the torso. IPCs can survive without a head, as the positronic is seated in the torso.
> > 
> > 
> > So they're cyborgs not robots?
> 
> what dictates robots not having brains in their torso

Biology. Language.

2022-07-10 21:24 UTC, redmoogle commented
> > > > @MegaEmpirical
> > > > The _brain_ is in the torso. IPCs can survive without a head, as the positronic is seated in the torso.
> > > 
> > > 
> > > So they're cyborgs not robots?
> > 
> > 
> > what dictates robots not having brains in their torso
> 
> Biology. Language.

A cyborg would be a mix of humans and robotics (preternis) IPCs are exclusively robotic and so none of that applies

2022-07-10 21:50 UTC, MegaEmpirical commented
> > > > > @MegaEmpirical
> > > > > The _brain_ is in the torso. IPCs can survive without a head, as the positronic is seated in the torso.
> > > > 
> > > > 
> > > > So they're cyborgs not robots?
> > > 
> > > 
> > > what dictates robots not having brains in their torso
> > 
> > 
> > Biology. Language.
> 
> A cyborg would be a mix of humans and robotics (preternis) IPCs are exclusively robotic and so none of that applies

Thank you, that's what I needed to know.

2022-07-11 00:35 UTC, adamsong commented
Emotes work, but say they don't

2022-07-11 01:36 UTC, redmoogle commented
> Emotes work, but say they don't

What

2022-07-11 02:17 UTC, adamsong commented
![image](https://user-images.githubusercontent.com/4607006/178176390-863e7f75-a361-4d7e-94ba-aca2f2590cb7.png)
But the emote works
Also, defibs work

2022-07-27 23:25 UTC, MegaEmpirical commented
How do IPCs interact with zombies?

2022-07-27 23:41 UTC, redmoogle commented
> How do IPCs interact with zombies?

they die

2022-07-28 01:46 UTC, ynot01 commented
IPCs do not have their name properly set when roundstart nukie, and when brought in as a spare operative, are spawned in as a naked IPC without an antag datum or any equipment

2022-07-28 01:46 UTC, ynot01 requested changes
IPCs do not have their name properly set when roundstart nukie, and when brought in as a spare operative, are spawned in as a naked IPC without an antag datum or any equipment

2022-07-28 10:47 UTC, redmoogle commented
> IPCs do not have their name properly set when roundstart nukie, and when brought in as a spare operative, are spawned in as a naked IPC without an antag datum or any equipment

I dont think IPCs should be spawning as nukies

2022-07-29 08:30 UTC, ynot01 commented
IPC bloodsuckers when dead will spawn a power cord implant on their turf every tick and can't revive

2022-07-29 08:31 UTC, ynot01 commented
> I dont think IPCs should be spawning as nukies

yeah probably not but they are

2022-07-30 01:16 UTC, redmoogle commented
> IPC bloodsuckers when dead will spawn a power cord implant on their turf every tick and can't revive

that **should not** happen because that means its regenerating organs every tick (as in qdeling and respawning them)

2022-07-30 12:45 UTC, Spacemanspark commented
Should IPCs even be spawning as bloodsuckers to begin with?

2022-07-30 13:00 UTC, redmoogle commented
> Should IPCs even be spawning as bloodsuckers to begin with?

well we have no system in place to really blacklist a species other than forcing them to another

2022-07-30 16:35 UTC, MegaEmpirical commented
I'd support the implementation of an antag racial blacklist or of forcing human when such an antag is rolled.

Similarly, plasmamen should not be vampires, or at the very least be unable to drink blood while wearing a helmet and mask.

Can changelings eat IPCs?

2022-07-30 16:39 UTC, redmoogle commented
> I'd support the implementation of an antag racial blacklist or of forcing human when such an antag is rolled.
> 
> Similarly, plasmamen should not be vampires, or at the very least be unable to drink blood while wearing a helmet and mask.
> 
> Can changelings eat IPCs?

This PR is already starting to go out of scope so a later PR

and also No

2022-08-05 12:12 UTC, JamieD1 approved these changes

2022-08-05 12:13 UTC, merged

2022-08-05 12:34 UTC, Spacemanspark commented
The glorious Synthetica regime will spread across all of SS13

2022-11-12 21:02 UTC, ReddicusDragon reviewed
pog