Lizards, by virtue of being 2.4 meters tall, cannot enter mechs.
yogstation13/Yogstation pull request #14599
Opened 2022-06-26 13:37 UTC by TheGamerdk

# Document the changes in your pull request

the ceiling is only 2.5 meters tall, that leaves the mech with 0.1 meters of padding for height, which simply isn't enough in my eyes for a lizard to be able to fit

# Wiki Documentation

# Changelog

:cl:  
tweak: Lizards are too tall to enter mechs
/:cl:

2022-06-26 13:40 UTC, TymurShatillo commented
Yeah fuck lizards

2022-06-26 18:35 UTC, Anvilman6 commented
This is just encouraging more lizard players to live their fantasy of having Dwarfism and being a kobold - fetish code at the core
Bold PR

2022-06-27 07:23 UTC, ToasterBiome requested changes

2022-06-27 07:23 UTC, ToasterBiome commented on code/game/mecha/mecha.dm
> +	if(islizard(user) && !H.dna.check_mutation(DWARFISM))
What if they're a bloodsucker? No DNA. runtime.

2022-06-27 09:38 UTC, TheGamerdk commented on code/game/mecha/mecha.dm
> +	if(islizard(user) && !H.dna.check_mutation(DWARFISM))
islizard checks for that

2022-06-27 18:55 UTC, N3D6 commented
W

2022-06-27 19:13 UTC, adamsong approved these changes
Code should work, awaiting review from hc

2022-07-03 00:41 UTC, Smudged commented
This is just a silly change, that's a nerf.

2022-07-03 04:29 UTC, Runian commented
lizards can be either be good dunkers or they can enter mechs. they made their choice https://github.com/yogstation13/Yogstation/pull/14519 :)

2022-07-09 12:08 UTC, JamieD1 commented
Cringe

2022-07-09 12:08 UTC, closed without merging