Adds plasmaman helmet welding screen + clothing buffs
yogstation13/Yogstation pull request #14679
Opened 2022-07-02 15:33 UTC by Skrem7

# Document the changes in your pull request

The primary purpose of this PR was to enable plasmamen to exist without welding goggles for using tools and to semi-give them back their previous enjoyed benefit of having a built-in welding screen without the tint. This makes it so it can simply be toggled as welding goggles are unable to be printed at an autolathe and are otherwise quite limited in their supply outside of Engineering.

While traveling through clothing code I also noticed that several armor values were inconsistent or otherwise undertweaked, so most of those have been moped up.

Also buffs certain plasmaman helmet armor designs with the idea that they would *probably* be better reinforced and capable for their position. Effectively, it just means that their increased damage from all sources might be tweaked down a little. Most importantly is the helmet armor for security envirohelmets, because being able to negate any form of armor a security plasmaman might have by just targeting the head is a nasty blow to anyone trying to be a plasmaman. They'll still take increased damage relative to other officers, but it shouldn't be AS notable now.

# Wiki Documentation

The EVA plasma envirosuit now also gives 50 rad armor
The standard plasmaman helmet can now toggle an effect identical to a welding helmet
The engineering plasmaman helmet now has armor values akin to the hard hat: MELEE = 15, BULLET = 5, LASER = 20, ENERGY = 10, BOMB = 20, BIO = 100, RAD = 20, FIRE = 100, ACID = 75, WOUND = 10
The security plasmaman helmet now has armor values akin to the helmet: MELEE = 35, BULLET = 30, LASER = 30, ENERGY = 10, BOMB = 25, BIO = 100, RAD = 0, FIRE = 100, ACID = 75, WOUND = 10
All engineering plasmaman jumpsuits have properly been given the +10 rad armor of engineering jumpsuits
The RD plasmaman jumpsuit has had its weird undertweaked values fixed to be a normal plasmaman jump with +10 bomb armor
The security/warden plasmaman jumpsuits now also give 10 wound armor

# Changelog

:cl:  
rscadd: All plasmaman helmets should (hopefully) have a functional, toggleable welding screen now
bugfix: Fixes RD plasmaman jumpsuit having unintentionally undertweaked values
bugfix: Fixes atmos plasmaman jumpsuit not sharing rad armor of other jumpsuits
tweak: Gives the EVA-proof plasmaman exosuit rad armor to be in line with the normal space suit
tweak: The engineering plasmaman helmet has had its armor buffed to hard hat levels
tweak: The security plasmaman helmet has had its armor buffed to standard helmet levels
/:cl:

2022-07-03 00:58 UTC, Smudged commented
Many of these were needed, and the added Fire-proof suit will make treating plasma-men in medbay not so impossible.

2022-07-03 18:11 UTC, tattax commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	actions_types = list(/datum/action/item_action/toggle_helmet_light, /datum/action/item_action/toggle_welding_screen)
```suggestion
	actions_types = list(/datum/action/item_action/toggle_helmet_light, /datum/action/item_action/toggle_welding_screen)
```

make sure you change the var in the proc to also work on helmets if you're gonna put it here

2022-07-03 18:11 UTC, tattax commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	actions_types = list(/datum/action/item_action/toggle_helmet_light, /datum/action/item_action/toggle_welding_screen)
```suggestion
	actions_types = list(/datum/action/item_action/toggle_helmet_light, /datum/action/item_action/toggle_welding_screen)
	visor_vars_to_toggle = VISOR_FLASHPROTECT | VISOR_TINT
```

2022-07-03 18:11 UTC, tattax commented on code/modules/clothing/spacesuits/plasmamen.dm
> +		playsound(src, 'sound/mecha/mechmove03.ogg', 50, 1) //Sound of the welding screen sliding down, maybe
```suggestion
		playsound(src, 'sound/mecha/mechmove03.ogg', 50, TRUE) //Sound of the welding screen sliding down, maybe
```
this isn't called anywhere unless the action is actually set to the helmet

2022-07-03 18:11 UTC, tattax commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	weldingvisortoggle(user)
```suggestion
/obj/item/clothing/head/helmet/space/plasmaman/AltClick(mob/user)
	toggle_welding_screen(user)
```

2022-07-03 18:14 UTC, Skrem7 commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	actions_types = list(/datum/action/item_action/toggle_helmet_light, /datum/action/item_action/toggle_welding_screen)
Will be able to check it further later when I'm off work

2022-07-08 01:46 UTC, tattax commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	actions_types = list(/datum/action/item_action/toggle_helmet_light, /datum/action/item_action/toggle_welding_screen)
@Skrem7 

> make sure you change the var in the proc to also work on helmets if you're gonna put it here

2022-07-08 01:52 UTC, Skrem7 commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	actions_types = list(/datum/action/item_action/toggle_helmet_light, /datum/action/item_action/toggle_welding_screen)
Check welding hard hat code, it should work perfectly fine

2022-07-08 03:04 UTC, Skrem7 commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	actions_types = list(/datum/action/item_action/toggle_helmet_light, /datum/action/item_action/toggle_welding_screen)
Cancel, I'll figure it out

2022-07-08 05:18 UTC, Skrem7 commented
So good news

I fixed it
The actions works

The problem is that I need to make new sprites for the welding mask going down namely probably an overlay which I can set similar to the welding hard hat.

I'll get on this later I am only mildly mentally present at the moment

2022-07-08 21:45 UTC, Skrem7 commented
Should be all set now.

I just need to fix up some weird item descriptions once I get back from work.

2022-07-09 00:44 UTC, ynot01 commented
do not buff the roundstart EVA race

2022-07-09 13:27 UTC, JamieD1 commented
> Should be all set now.
> 
> I just need to fix up some weird item descriptions once I get back from work.

Do not give them flash protection.

2022-07-09 13:27 UTC, JamieD1 requested changes
Do not give them flash protection. We had loads of issues with powergaming twits using it to avoid sec/heads.

2022-07-11 19:41 UTC, Skrem7 commented
> Do not give them flash protection. We had loads of issues with powergaming twits using it to avoid sec/heads.

Welding shield is bye-bye now

2022-07-15 09:00 UTC, tattax commented
> Welding shield is bye-bye now

https://wiki.teamfortress.com/w/images/e/e5/Heavy_jeers05.wav

2022-07-16 12:54 UTC, JamieD1 approved these changes

2022-07-16 12:54 UTC, merged