Improves SM consumption code
yogstation13/Yogstation pull request #14739
Opened 2022-07-07 14:20 UTC by redmoogle

# Document the changes in your pull request

Better code compared to the other PRs
Doesnt iterate over the same stuff twice
Catches more edgecases
and moves some repeated code into the proc it gets called with

# Changelog
:cl:  
tweak: SM eats more things on top of it
/:cl:

2022-07-07 15:34 UTC, warface1234455 commented
Why is putting SM in a box glass not realistic, you put SM in a Container Box!!!

2022-07-07 15:41 UTC, redmoogle commented
> Why is putting SM in a box glass not realistic, you put SM in a Container Box!!!

Hypernobium coated.

Also downvoting is pointless its just a code cleanup

2022-07-07 19:10 UTC, ToasterBiome requested changes
check for density

2022-07-08 21:32 UTC, ToasterBiome approved these changes

2022-07-08 21:32 UTC, merged