Adds dwarfism injector to the necropolis loot pool
yogstation13/Yogstation pull request #14730
Opened 2022-07-06 18:29 UTC by ynot01

# Document the changes in your pull request

We're rich

# Wiki Documentation

Title

# Changelog

:cl:  
tweak: Added dwarfism injector to the necropolis loot pool
/:cl:

2022-07-06 18:35 UTC, Marmio64 commented
a hidden miner <s>nerf</s> buff

2022-07-06 20:01 UTC, Chubbygummibear commented
as a bit of spice it could maybe be like a dwarf loadout. hardhat with light, diamond tipped drill, dwarfism injector, and a mug of ale, or something to that effect?

2022-07-06 21:20 UTC, ToasterBiome requested changes
either remove a shitty loot item or add more stuff for funny

2022-07-06 22:18 UTC, Marmio64 commented on code/modules/mining/lavaland/necropolis_chests.dm
> +
```suggestion
/obj/item/grenade/plastic/miningcharge/mega
/obj/item/grenade/plastic/miningcharge/mega

```
dwarves like big booms
also to stop the miner mains from crying (they're very ungrateful)

2022-07-06 22:51 UTC, VaelophisNyx commented on code/modules/mining/lavaland/necropolis_chests.dm
> +
Can Miners use this to get mega mining charges faster by deconstructing it

2022-07-07 00:07 UTC, Marmio64 commented on code/modules/mining/lavaland/necropolis_chests.dm
> +
if they could do that it's still around a 4% chance to even get this from a chest, let alone that you first need to get a chest, and also that you need to disrupt your mining grindset to go topside to get the bombs deconstructed and researched

2022-07-07 14:24 UTC, ynot01 commented
> either remove a shitty loot item or add more stuff for funny

~~this was not meant to be a mining buff~~

im diversifying the loot pool

2022-07-07 17:59 UTC, Smudged commented
Make it so only this injector gives you a permanent beard as per - 14719

Since I'm against ALL dwarfism giving you a beard already.

2022-07-07 21:37 UTC, ynot01 commented
> Make it so only this injector gives you a permanent beard as per - 14719
> 
> Since I'm against ALL dwarfism giving you a beard already.

if that gets closed maybe

2022-07-16 13:03 UTC, JamieD1 approved these changes

2022-07-16 13:12 UTC, merged