Lightbulbs have a small chance to burn out
yogstation13/Yogstation pull request #14743
Opened 2022-07-07 23:58 UTC by redmoogle

# Document the changes in your pull request

Makes lightbulbs have a rare chance to burn out ~~Janitor Nerf~~
On average they last about ~40 minutes

# Wiki Documentation

Lights can burn out now

# Changelog

:cl:  
rscadd: Lights now have a small chance to burn out randomly
/:cl:

2022-07-08 00:09 UTC, Marmio64 commented
it sounds like a headache to deal with the fact that the majority of the lights on the station are going to statistically burn out at least once during the short duration of your stay on the station, on top of the already existing electrical storms that can destroy an entire department's lights in one go.

2022-07-08 00:11 UTC, redmoogle commented
> it sounds like a headache to deal with the fact that the majority of the lights on the station are going to statistically burn out at least once during the short duration of your stay on the station, on top of the already existing electrical storms that can destroy an entire department's lights in one go.

Statistically 3 times during a normal full length round. I can change this to 2 or 1 as well. I just want janitors to be more relevant overall

2022-07-08 00:44 UTC, Marmio64 commented
> Statistically 3 times during a normal full length round. I can change this to 2 or 1 as well. I just want janitors to be more relevant overall

i dont feel like making lights always be burning out is the way to go, especially since it'll be really annoying whenever there is not a janitor, or a janitor who is slower or less competent and cant keep up with both messes and lights, even if you can make janiborgs. Should be lowered to a max of 0.01% chance per tick honestly, so it'd just be something around half the station's lights going out over the course of an hour and a half

2022-07-08 02:32 UTC, ToasterBiome requested changes
Me when 99% of the station is dark because janitor doesn't have access to these areas

2022-07-08 02:32 UTC, ToasterBiome commented on code/modules/power/lighting.dm
> +	// 0.04% Chance to burn out each tick
```suggestion
	// 0.02% Chance to burn out each tick
```

2022-07-08 12:05 UTC, Moggram commented
going to get myself broged if can't get AA to fix lights....

2022-07-08 22:03 UTC, FatalEYES commented
Yeah, this won't cause people to break into the service lathe to just print a light replacer, that'd be absurd.

2022-07-09 11:40 UTC, JamieD1 commented
Sorry, enough lights break and they dont get replaced at current, dont want to make it worse.

2022-07-09 11:40 UTC, closed without merging