Cryogenics new gasses
yogstation13/Yogstation pull request #14766
Opened 2022-07-09 17:45 UTC by Darthkill

# If this is your first PR.
First coding PR, intention is to make pluoxium function as an oxygen substitute and has healium function as an assistance to healing in cryo.

# Document the changes in your pull request

Pluoxium is consumed over oxygen at a reduced rate to due it being super oxygen.
Ordinarily pluoxium is taken in at 1/8th oxygen, but this takes in pluoxium at a more inefficient rate of 1/4 oxygen.
Healium heals the occupant of the tube by the same amount as intaking healium.

Hasn't been tested yet, Ill look into figuring out a test server to test it working.

# Spriting
No spiriting, pink cryo tube sprites would be awesome though.

# Wiki Documentation

Include that pluoxium and healium can be used with cryotubes. for the maths nerds healium does:
7 Heat damage, 5 Brute damage, 5 Toxins damage

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added new things  
tweak: tweaked a few things  
/:cl:

2022-07-16 14:39 UTC, JamieD1 requested changes

2022-07-16 14:39 UTC, JamieD1 commented on code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
> +				if(  air1.get_moles(/datum/gas/pluoxium) > 5 )//Use pluoxium over oxygen
```suggestion
				if(air1.get_moles(/datum/gas/pluoxium) > 5 )//Use pluoxium over oxygen
```

2022-07-16 14:39 UTC, JamieD1 commented on code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
> +		else air1.set_moles(/datum/gas/oxygen, max(0,air1.get_moles(/datum/gas/oxygen) - 0.5 / efficiency)) // Magically consume gas? Why not, we run on cryo magic.
```suggestion
		else 
			air1.set_moles(/datum/gas/oxygen, max(0,air1.get_moles(/datum/gas/oxygen) - 0.5 / efficiency)) // Magically consume gas? Why not, we run on cryo magic.
```

2022-07-16 14:48 UTC, JamieD1 approved these changes

2022-07-16 14:49 UTC, merged

2022-07-17 02:47 UTC, Darthkill commented
Appears to be borked, ill defiantly need to make a test server to find out what's causing it.