Cult of the Honkmother - The Clown Sect
yogstation13/Yogstation pull request #14788
Opened 2022-07-10 20:25 UTC by Alagoinha

Special thanks to Theos, Gus, and Redmoogle for helping this code potato

# Wiki Documentation

Rites
Holy Pie - Creates a cream pie  (50 favor)
Honk a Bot - Summons a honkbot (150 favor)
Banana Blessing - Creates a sheet of bananium (1000)

# Changelog
:cl:  
rscadd: Added Honkmother sect
/:cl:

2022-07-10 20:35 UTC, ynot01 commented
please write somewhere that it wants bananas

2022-07-10 21:30 UTC, Hopekz requested changes

2022-07-10 21:30 UTC, Hopekz commented on code/modules/religion/religion_sects.dm
> +	desired_items = list(/obj/item/reagent_containers/food/snacks/grown/banana)
```suggestion
	desired_items = list(obj/item/reagent_containers/food/snacks/grown/banana)
```
will fix this error probably

2022-07-11 06:03 UTC, TymurShatillo commented
I think that creating a honkbot should be more expensive then 150 flavour

2022-07-16 14:59 UTC, JamieD1 commented
Please fix compile

2022-07-16 16:49 UTC, Alagoinha commented
> Please fix compile

trying to find out how to
at one point it will work

2022-07-23 11:22 UTC, JamieD1 submitted a review, later dismissed

2022-07-23 11:22 UTC, JamieD1 commented on code/modules/religion/religion_sects.dm
> +/**** The Honkmother sect, sacrifice bananas to feed your prank power. ****/
```suggestion
/// The Honkmother sect, sacrifice bananas to feed your prank power. 
```

2022-07-23 11:22 UTC, JamieD1 commented on code/modules/religion/religion_sects.dm
> +	desired_items = list(obj/item/reagent_containers/food/snacks/grown/banana)
```suggestion
	desired_items = list(/obj/item/reagent_containers/food/snacks/grown/banana)
```

2022-07-23 12:28 UTC, JamieD1 commented on code/modules/religion/religion_sects.dm
> +	desired_items = list(/obj/item/reagent_containers/food/snacks/grown/banana)
```suggestion
	desired_items = list(/obj/item/reagent_containers/food/snacks/grown/banana)
```

2022-07-24 11:25 UTC, JamieD1 commented on code/modules/religion/religion_sects.dm
> +	desired_items = list(/obj/item/reagent_containers/food/snacks/grown/banana)
```suggestion
```

2022-07-28 10:39 UTC, TheGamerdk approved these changes

2022-07-28 10:47 UTC, merged

2022-07-28 21:07 UTC, Alagoinha commented
thanks everyone for the help fixing this mess, it will help me a lot with the other sects I want to try and code