[Box] Changes the glass on the sing engine from reinforced plasma glass to normal reinforced glass
yogstation13/Yogstation pull request #14821
Opened 2022-07-12 21:48 UTC by N3D6

# Document the changes in your pull request

Changes the glass on the singulo/tesla engine to normal reinforced glass. Reinforced glass has heavy rad insulation, meaning the singulo is now less likely to make the entire engineering bay unhospitable due to rads.

In the long run, this is better than a buff to plasma glass, as buffing rad insulation on plasma glass is also a subtle SM nerf

# Spriting

# Wiki Documentation
Screenshot of the new tesla area

# Changelog

:cl:  
tweak: box sing/tesla now has reinforced glass instead of reinforced plasma glass
/:cl:

2022-07-12 21:51 UTC, ShadowDeath6 commented
Please do me a solid and replace the first 2 rows of floor tiles next to the windows with reinforced flooring as well, since the singulo (at size 3, which is generally considered the goal size) will rip the tiles off of the ground and force engi to constantly repair them or replace them with reinforced floor themselves if they don't want floor tiles sitting around and causing annoying clutter.

2022-07-12 21:51 UTC, N3D6 commented
> Please do me a solid and replace the first 2 rows of floor tiles next to the windows with reinforced flooring as well, since the singulo (at size 3, which is generally considered the goal size) will rip the tiles off of the ground and force engi to constantly repair them or replace them with reinforced floor themselves if they don't want floor tiles sitting around and causing annoying clutter.

will do

2022-07-13 08:34 UTC, ToasterBiome requested changes
![image](https://user-images.githubusercontent.com/5091394/178688836-cae0a3d6-38ad-4770-b69d-5219ea77e759.png)
Unfuck these corners

2022-07-13 14:16 UTC, N3D6 commented
@ToasterBiome Unfucked the corners

2022-07-13 21:28 UTC, ToasterBiome approved these changes

2022-07-13 21:28 UTC, merged