Bloodsuckers objective tweaks and added epilogues
yogstation13/Yogstation pull request #14837
Opened 2022-07-13 21:23 UTC by Chubbygummibear

# Document the changes in your pull request

Since Bloodsucker mechanics kinda force them out of hiding by using blood as a timer it's actually a bit of an ask to survive the whole round without alerting people. i think this is why fulp has "make a lair" and "survive" as primary objectives and everything else as optional. i have implemented this **HOWEVER** i don't think you should get a big greentext for surviving, so you get a special marooned text that's more neutral if you do the bare minimum. 

Additionally everyone gets a little epilogue lore blurb in the credits screen based on how you did as a sucker. this takes into account if you did primary objectives, optional objectives, broke the masquerade or not, and even evac'd on the shuttle. Evacing is kinda a big risk due to the sol cycle so getting an evac ending is pretty impressive and hopefully your epilogue reflects that.

Epilogue text color is also dynamic based on how i gauged the outcomes. i also set it up to be easy to add more blurbs if people want to contribute by adding some messages to the list.

Tattax also asked me to reduce the objectives assigned on spawn from 2 to 1.

![image](https://user-images.githubusercontent.com/46236974/178837694-f11f8213-8ece-41c8-8705-86a410fc9f0c.png)
![image](https://user-images.githubusercontent.com/46236974/178837708-161d1bec-c772-4cda-a682-118a0b1ea0ee.png)
![image](https://user-images.githubusercontent.com/46236974/178837729-4e5315b6-f19a-455c-8586-8923a0c83bdf.png)

# Wiki Documentation

Bloodsucker assigned objectives down to 1
spawn objectives that aren't lair and survive are "optional"
objectives you get from joining a clan ARE NOT optional
to get the epic greentext you need to complete both primary and optional objectives. otherwise you get a minor neutral ending

# Changelog

:cl:  @tattax, Truzkawa, Chubbygummibear
rscadd: added code that supports optional objectives
rscadd: bloodsucker round-end report comes with epilogue blurbs based on how you did
tweak: bloodsucker assigned objectives at spawn are "optional" 
tweak: objectives you get for joining a clan through ranking up are NOT optional
tweak: epic greentext is only achieved through finishing both primary and optional. only primary will net you a neutral ending
/:cl:

2022-07-13 23:17 UTC, tattax commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +	else if(objectives_complete && optional_objectives_complete && !broke_masquerade && !escaped)
```suggestion
	else if(objectives_complete && optional_objectives_complete && !broke_masquerade || !escaped)
```

2022-07-13 23:17 UTC, tattax commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +	else if(objectives_complete && optional_objectives_complete && !broke_masquerade && escaped)
```suggestion
	else if(objectives_complete && optional_objectives_complete && !broke_masquerade || escaped)
```

2022-07-13 23:17 UTC, tattax commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +	else if(objectives_complete && !optional_objectives_complete && broke_masquerade && escaped)
```suggestion
	else if(objectives_complete && !optional_objectives_complete || broke_masquerade && escaped)
```

2022-07-13 23:17 UTC, tattax commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +	else if(objectives_complete && !optional_objectives_complete && broke_masquerade && !escaped)
```suggestion
	else if(objectives_complete && !optional_objectives_complete || broke_masquerade && !escaped)
```

2022-07-13 23:17 UTC, tattax commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +	else if(objectives_complete && !optional_objectives_complete && !broke_masquerade && escaped)
```suggestion
	else if(objectives_complete && !optional_objectives_complete || !broke_masquerade || escaped)
```

2022-07-13 23:17 UTC, tattax commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +	else if(objectives_complete && !optional_objectives_complete && !broke_masquerade && !escaped)
```suggestion
	else if(objectives_complete && !optional_objectives_complete || !broke_masquerade || !escaped)
```

2022-07-13 23:26 UTC, Skrem7 reviewed
Hi I'm a writer I like to write things

2022-07-13 23:26 UTC, Skrem7 commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +			"Thus ends the story of [ReturnFullName(TRUE)]. Hopefully future generations will look back on your legacy and reflect on the lessons of the past."
```suggestion
			"Thus ends the story of [ReturnFullName(TRUE)]. No doubt future generations will look back on your legacy and reflect on the lessons of the past. If they remember you at all."
```

2022-07-13 23:26 UTC, Skrem7 commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +			"That station didn't suit you anyway, and so now it's time to find a new locale. Maybe your next haunt will prove more comfortable."
```suggestion
			"A low profile has always suited you best, conspiring enough to satiate the clan and keep your head low. It's not luxorious living, though death is a less kind alternative. On to the next station."
```

2022-07-13 23:26 UTC, Skrem7 commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +			"A low profile has always suited you best. Just enough to get by, don't make waves, and keep your head low. It's not luxorious living, but it beats being dead."
```suggestion
			"You completed your mission and kept your identity free of heresy, though your mark here is not strong enough to lay a claim. Best stow away when the next shuttle comes around."
```

2022-07-13 23:26 UTC, Skrem7 commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +			"You survived, but you broke the masquerade, and both monster hunters and bloodsuckers are going to know where to find you... Perhaps it's time to see what's so about special this Sol the cattle k
```suggestion
			"You survived, but you broke the Masquerade, your blood-stained presence clear and your power limited. No doubt death in the form of claw or stake hails its approach. Perhaps it's time to understand the cattles' fascinations with the suns."
```

2022-07-13 23:26 UTC, Skrem7 commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +			"You may have completed what was asked of you, but that doesn't change the fact that you violated the masqerade. Good thing you got off the station, because it's time to disappear."
```suggestion
			"Your mission accomplished, you step off the spacecraft, feeling the mark of exile on your neck. Your allies gone, your veins thrum with a singular purpose: survival."
```

2022-07-13 23:26 UTC, Skrem7 commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +			"This station is your own slice of paradise. Each batch of crew is ripe for the picking of vassals and food. At this rate you might even start your own clan here."
```suggestion
			"This station has become your own slice of paradise. Your mission completed, you turn on the others who were stranded, ripe for your purposes. Who knows? If they prove to elevate your power enough, perhaps a new clan might be founded here."
```

2022-07-13 23:26 UTC, Skrem7 commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +			"You've proven your skills, you even managed to escape the station. Upon arriving back at Centom, an unassuming assistant hands you an invitation stamped with the Camerilla seal. High society is w
```suggestion
			"You step off the spacecraft with a mark of pride at a superbly completed mission. Upon arriving back at CentCom, an unassuming assistant palms you an invitation stamped with the Camarilla seal. High society awaits: a delicacy you have earned."
```

2022-07-13 23:26 UTC, Skrem7 commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +			"You ran amok of the station, completed every task set before you, and killed any who opposed you. The Camarilla dare not risk a move against you for breaking the Masquerade."
```suggestion
			"Blood still pumps in your veins as you lay stranded on the station. No doubt the wake of chaos left in your path will attract danger, but greater power than you've ever felt courses through your body. Let the Camarilla and the witchers come. You will be waiting."
```

2022-07-13 23:26 UTC, Skrem7 commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +			"Describing you as a tyrant is a disservice to your abilities. You're a god amongst Bloodsuckers, and a demon in the eyes of everyone else. That station was just the beginning for you."
```suggestion
			"What matters of the Masquerade to you? Let it crumble into dust as your tyranny whips forward to dine on more stations. News of your butchering exploits will quickly spread, and you know what will encompass the minds of mortals and undead alike. Fear."
```

2022-07-15 08:21 UTC, ToasterBiome requested changes, later dismissed

2022-07-15 08:21 UTC, ToasterBiome commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +/datum/antagonist/bloodsucker/proc/get_Flavor(objectives_complete, optional_objectives_complete)
This is the worst casing I have ever seen

2022-07-15 08:36 UTC, Chubbygummibear commented on code/modules/antagonists/bloodsuckers/bloodsuckers.dm
> +/datum/antagonist/bloodsucker/proc/get_Flavor(objectives_complete, optional_objectives_complete)
there

2022-07-16 15:21 UTC, JamieD1 approved these changes

2022-07-16 15:23 UTC, JamieD1 approved these changes

2022-07-21 07:28 UTC, Chubbygummibear commented
this needs to wait to be merged until #14648 is fixed or reverted, unless you want me to add a fix to this pr

2022-07-23 11:39 UTC, JamieD1 approved these changes

2022-07-23 11:39 UTC, merged