[Box] Adjusts Janitor Closet, Part of Atmos, And Janitorial/Atmos Maint
yogstation13/Yogstation pull request #14834
Opened 2022-07-13 07:33 UTC by VaelophisNyx

# Document the changes in your pull request

Before:
![ss (2022-07-13 at 01 48 21)](https://user-images.githubusercontent.com/1534478/178674216-7fa7b497-a86e-4cee-b75c-2b094b091ebf.png)

After
![ss (2022-07-13 at 01 47 52)](https://user-images.githubusercontent.com/1534478/178674199-6bdec3be-3b96-4617-812d-afc9d5415cc0.png)

Adjusts the janitorial closet to account for there being, shocker, more than one janitor!
Adds a second janicart, and space cleaner bottle
swaps the water tank for a high capacity water tank
shifts the disposal and table/rack combo down a tile
deletes the water vapor can (just ask atmos if you need your grief can pls)
moves atmos' disposal down a tile and deletes the two pipe dispensers because...RPDs exist and atmos is swimming in them? If you need a pipe dispenser you can just...go build one.
adjusts the airlocks in the engineering hallway entrance because they were spaced out 1 tile for seemingly no reason
adds white trim to the janitorial closet
adds a modular PC vendor to atmos because why not

# Changelog

:cl:  
rsc:add: adds trims to the janitorial closet
rscadd: Adds a second janicart, and space cleaner bottle to the janitor closet
rscadd: adds a modular PC vendor to atmos
rscdel: deletes the two pipe dispensers in atmos
rscdel: deletes the water vapor can in the janitor closet
tweak: changes the water tank in the janitorial closet into a high capacity variant
tweak: moves engineering hallway northern firelocks
tweak: shifts janitorial/atmos maint hallway so nothing is too far from where it was, to make room for the janitorial closet changes
tweak: moves atmos' disposal down a tile
tweak: shifts the janitor closet disposal and table/rack combo down a tile
/:cl:

2022-07-13 08:32 UTC, ToasterBiome requested changes
fit the water vapor canister back in

2022-07-13 16:03 UTC, redmoogle commented
The modular PC vendor in atmos is kinda weird. Why not place that in engineering instead?

2022-07-13 21:22 UTC, VaelophisNyx commented
specifically because I wasn't touching engineering with this PR

2022-07-13 21:25 UTC, ToasterBiome requested changes
move vendor, you can touch engi with this

2022-07-13 21:29 UTC, VaelophisNyx commented
Ok, I'll get that done

2022-07-13 21:58 UTC, VaelophisNyx commented
It is done

2022-07-14 06:05 UTC, ToasterBiome approved these changes

2022-07-14 06:05 UTC, merged