Moves most punch damage modifiers to physiology + bloodsucker punch damage tweaks
yogstation13/Yogstation pull request #14843
Opened 2022-07-14 06:18 UTC by Mqiib

Since species changing completely fucks up punch damage modifier stuff and resets them and then you get boned after the bonuses are removed I added an extra bit to the pysiology datum so that THAT bit can be changed independant of your species and you should retain your increased punchies. I added three new procs that just return the total physiology + species punch damage values, one each for the max damage, min damage, and stun threshold.

Also messes around with bloodsucker punch stuff because it was all over the goddamn place and didn't have stun threshold stuff so you could just get soap bar hands in certain situations. PRETTY SURE it all works because it compiles and I ran through the math like at least four times in my head. Maybe three. I don't remember any more, it's 2 am.

Please tell me if I missed any mentions of punch damage. I know I specifically skipped over some bloodsucker ones because they mess with species as well and didn't feel like buggering around with that.

# Wiki Documentation

I dunno if there's any mention of the physiology datum but it includes punch damage bonuses now. This shouldn't ACTUALLY affect anything mechanically besides making bloodsuckers not so prone to slapping people to the ground with every swing.

# Changelog

:cl:  
rscadd: Adds punch damage mods to the physiology datum
rscadd: Also adds three new human procs to get the total punch damage values
bugfix: Makes punch damage modifiers more consistent after species changes
bugfix: Bloodsucker punch damage (re)calculations changed to be more consistent
tweak: Bloodsuckers no longer get insane knockdown chance on hit
tweak: Martial arts now use the new procs instead of just species damage
experimental: I promise I'll test this code tomorrow, assuming I don't forget like I do everything else 😢 
/:cl:

2022-07-14 20:15 UTC, Mqiib commented
Ok I have tested it and it seems to work fine so we're good, probably!

2022-07-19 07:14 UTC, ToasterBiome approved these changes

2022-07-19 07:15 UTC, ToasterBiome commented
You change bloodsuccker stuff so this is balance stuf............... sorry.................

2022-07-23 11:58 UTC, JamieD1 approved these changes

2022-07-23 12:22 UTC, JamieD1 requested changes

2022-07-23 12:22 UTC, JamieD1 commented on code/datums/mutations/body.dm
> +  ADD_TRAIT(owner, TRAIT_QUICKER_CARRY, src)
```suggestion
		ADD_TRAIT(owner, TRAIT_QUICKER_CARRY, src)	
```

2022-07-23 12:22 UTC, JamieD1 commented on code/datums/mutations/body.dm
> +  REMOVE_TRAIT(owner, TRAIT_QUICKER_CARRY, src)
```suggestion
		REMOVE_TRAIT(owner, TRAIT_QUICKER_CARRY, src)	
```

2022-07-23 12:23 UTC, JamieD1 commented on code/datums/mutations/body.dm
> +  ADD_TRAIT(owner, TRAIT_QUICKER_CARRY, src)
```suggestion
		ADD_TRAIT(owner, TRAIT_QUICKER_CARRY, src)	
```

2022-07-23 12:23 UTC, JamieD1 commented on code/datums/mutations/body.dm
> +  REMOVE_TRAIT(owner, TRAIT_QUICKER_CARRY, src)
```suggestion
		REMOVE_TRAIT(owner, TRAIT_QUICKER_CARRY, src)	
```

2022-07-23 12:24 UTC, JamieD1 requested changes

2022-07-23 12:24 UTC, JamieD1 commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +
```suggestion
```

2022-07-23 12:24 UTC, JamieD1 commented on code/datums/mutations/body.dm
> +		REMOVE_TRAIT(owner, TRAIT_QUICKER_CARRY, src)
```suggestion
	REMOVE_TRAIT(owner, TRAIT_QUICKER_CARRY, src)	
```

2022-07-23 12:24 UTC, JamieD1 commented on code/datums/mutations/body.dm
> +		ADD_TRAIT(owner, TRAIT_QUICKER_CARRY, src)
```suggestion
	ADD_TRAIT(owner, TRAIT_QUICKER_CARRY, src)	
```

2022-07-23 12:33 UTC, JamieD1 approved these changes

2022-07-23 12:33 UTC, merged