add mech kinetic accelerator
yogstation13/Yogstation pull request #14856
Opened 2022-07-15 05:46 UTC by pyronie

# Document the changes in your pull request
adds a mech Kinetic accelerator and adds it to the vendor for 10k points. I tested this and it seems to work fine as far as i could tell. it is locked to the vendor so that roboticists can't powergame with it, and added to all vendors so that golems and freeminers can also use it. also fixed some of the formatting in mining vendor and added an admin only version that has no damage reduction in pressurized environments and fits all mechs.

# Spriting
![image_2022-07-15_004533109](https://user-images.githubusercontent.com/30361472/179158860-58cb9ee3-802b-4be6-a9e0-a630e1717fb3.png)

# Wiki Documentation
Mech Kinetic accelerator, only attachable to mining mechs and does 100 damage in depressurized environments, 20 in pressurized environments, had a range of 5 and has a 1 second cooldown. costs 10000 points in the mining vendor and is available in all mining vendors. note that you can achieve similar results without a mech in lavaland with dual wielding two kinetic accelerators with a range, damage, and cooldown modkit.

# Changelog
:cl:  
rscadd: mining mech KA, only in mining vendors for 10k points
imageadd: sprite for the mech KA
spellcheck: fixed mining vendors code formatting
/:cl:

2022-07-15 06:02 UTC, pyronie commented
if anyone thinks this is too strong and needs to be made weaker, please remember you can make a pair of kinetic accelerators that are essentially better than this, with two ka's with 2 damage upgrades and 1 cooldown upgrade each, they deal more damage than this at a negligibly slower rate.

2022-07-15 06:07 UTC, ShadowDeath6 commented
What's the point of this? Just to give ripley mechs a ranged option? I don't really mind, but I thought that the plasma cutter already did fairly solid damage.

2022-07-15 06:29 UTC, TymurShatillo commented
If i would want to powergame as a roboticist, i would build a Durand. No need to lock it to miners only, because mostly KA is useless on station, since it deals small amounts of damage in low pressure.

2022-07-15 06:30 UTC, ghost commented
Also, is the mech KA upgradeable?

2022-07-15 06:49 UTC, ToasterBiome requested changes
You messed up the line endings, please fix

2022-07-15 06:51 UTC, pyronie commented
> If i would want to powergame as a roboticist, i would build a Durand. No need to lock it to miners only, because mostly KA is useless on station, since it deals small amounts of damage in low pressure.

does 20 dps on station and would be equippable on util mechs

2022-07-15 06:56 UTC, pyronie commented
> You messed up the line endings, please fix

i would but its due to how github processes my upload so idk how to fix

2022-07-15 06:56 UTC, ToasterBiome reviewed
same amount of damage as a backstab crusher while being 7 tiles away... holy shit.........

2022-07-15 06:56 UTC, ToasterBiome commented on code/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	damage = 100
Hell no

2022-07-15 06:57 UTC, ToasterBiome commented
> > You messed up the line endings, please fix
> 
> i would but its due to how github processes my upload so idk how to fix

use github desktop or sourcetree or any other programs to do it properly

2022-07-15 07:04 UTC, pyronie commented on code/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	damage = 100
thats 5 tiles away, can be easily be surpassed by dualies set up right, and is on something less mobile than a player

2022-07-15 07:20 UTC, pyronie reviewed
reduced range and increased cooldown

2022-07-15 07:23 UTC, pyronie commented
pretty sure i can only fix the line end is by closing this pr and starting a new one because of how i made the change

2022-07-15 07:53 UTC, pyronie commented
> Also, is the mech KA upgradeable?

no

2022-07-15 09:21 UTC, TymurShatillo commented
> does 20 dps on station and would be equippable on util mechs

It has short range, long cooldown, and isn't upgradeable. Roboticists have more powerfull weapons in their disposal, so i don't think that locking it to mining vendors and making it cost fucking 10k points is a good idea.

2022-07-15 12:42 UTC, TymurShatillo commented
Ah stop it isn't a standart KA. But actually 100 damage is a fucking enormous value, are you sure about it?

2022-07-15 13:08 UTC, KillerOrcaCora commented
https://youtu.be/GjXVUTPTKdU now I can finally beat mega funna with my ass blast gg from 7 tiles away

2022-07-15 20:38 UTC, pyronie commented
> Ah stop it isn't a standart KA. But actually 100 damage is a fucking enormous value, are you sure about it?

specifically 100 damage so that it can oneshot legions. note that this is supposedly a completed KA so it can't be modified. also is locked from roboticists because it does 20 damage on station, which while isnt as much, it isnt a weapon and can be fitted on the utility mechs. it would suddenly be the best weapon on utility mechs by far especially because it actually is usable.

> https://youtu.be/GjXVUTPTKdU now I can finally beat mega funna with my ass blast gg from 7 tiles away

the range and firing speed has been reduced, and it doesnt have 7 range. also note despite it having 5 range in that clip(it now has 4) i still sometimes am too far away to hit the colossus.

2022-07-15 20:39 UTC, pyronie commented on code/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	damage = 100
was reduced to 4 range and increased cd

2022-07-15 21:03 UTC, pyronie commented
me killing colossus with range 4 and increased cd mech ka 
https://youtu.be/8WXXVSv5qtQ

2022-07-15 21:34 UTC, pyronie commented
also @TymurShatillo @ToasterBiome a mega KA can exceed the current dps of the mech ka. currently it has 62.5 dps, while a mega ka with 3 cd reductions and 1 damage upgrade has a dps of around 75. this is why i said when you are complaining about this being strong you are really just complaining about ka's being strong.

2022-07-15 23:37 UTC, ToasterBiome commented
> also @TymurShatillo @ToasterBiome a mega KA can exceed the current dps of the mech ka. currently it has 62.5 dps, while a mega ka with 3 cd reductions and 1 damage upgrade has a dps of around 75. this is why i said when you are complaining about this being strong you are really just complaining about ka's being strong.

Getting a mega KA involves finding basalt, getting plasma magmite, finding the world anvil, and forging it with a piece of gibtonite

On the other hand, you AFK request a ripley from robotics and then spend 10K on it and you get a free colossus kill

2022-07-15 23:52 UTC, pyronie commented
the first one is easier

2022-07-16 05:13 UTC, TymurShatillo commented
Basicaly if the mech KA has the same range and cooldown as the normall one it is less strong then just going 2 KA with two damage upgrades plus range, because it will be 120 damage from one attack cycle, so maybe it is OK

2022-07-16 10:12 UTC, KillerOrcaCora commented
Here is a super fun idea I came up with while eating garbage. Just make it do no damage to megas!!!

2022-07-16 10:17 UTC, TymurShatillo commented
bad

2022-07-23 12:04 UTC, JamieD1 commented
Looks way too easy from that video, the monsters are balanced around people not mechs

2022-07-26 01:43 UTC, githubuser4141 commented
> What's the point of this? Just to give ripley mechs a ranged option? I don't really mind, but I thought that the plasma cutter already did fairly solid damage.

It does [10 damage](https://github.com/yogstation13/Yogstation/blob/707c6a724d5e03ad7fd3d0b94506f1ded916b506/code/modules/projectiles/projectile/special/plasma.dm) in pressurized or unpressurized areas

2022-07-26 07:06 UTC, KillerOrcaCora approved these changes
Sprites fine good luck on that balance though

2022-08-05 12:18 UTC, JamieD1 commented
Will bring up with the new balance council

2022-08-11 12:09 UTC, redmoogle requested changes
Add an exemption for the PKA in the combat design at `code/game/mecha/mech_fabricator.dm:505` since it falls under the /weapon subtype

2022-08-28 12:22 UTC, JamieD1 commented
This is being declined because it is basically free megafauna if you know what you are doing, you either need to have a downside and not be just better then everything else or this is being declined, sorry. Reopen it if you change it.

2022-08-28 12:22 UTC, closed without merging