Adds more Botany Cargo Bounties, Adjusts Mining Progression Bounties, Adjusts Appendix Bounty, Adjusts Drink Bounty
yogstation13/Yogstation pull request #14973
Opened 2022-07-24 00:53 UTC by VaelophisNyx

# Document the changes in your pull request

Adds new bounties for tower cap logs, steel cap logs, destroying angels, walking mushroom meat, and killer tomato meat
adjusts the appendix bounty so it's 3,000 instead of 2,200.
increases Omega Weed bounty's payout because getting it to mutate is a special RNG hell since weed mutates into like 4 other variants.
Metal Hydrogen Axe bounty now mentions it wants multiple axes in the description.
Bar drink bounties now pay more or less depending on if it wants a basic or advanced drink

# Changelog

:cl:  
rscadd: Added new botany bounties!
tweak: Appendix bounty now pays more.
tweak: Mining Progression Bounties now pay considerably more instead of a pittance.
tweak: Omega Weed bounty now pays a lot more.
tweak: adjusts payout of basic and advanced bar drink bounties, to reflect the difficulty differences in making them
spellcheck: fixed Metal Hydrogen Axe bounty description.
/:cl:

2022-07-24 11:57 UTC, JamieD1 requested changes
Lets not make the already bad comments worse

2022-07-24 11:57 UTC, JamieD1 commented on code/modules/cargo/bounties/botany.dm
> +	multiplier = 10 //omega weed is ACTUAL CBT to get to mutate.
```suggestion
	multiplier = 10
```

2022-07-24 11:57 UTC, JamieD1 commented on code/modules/cargo/bounties/medical.dm
> +	reward = 3000 //there are no synthetic appendixes //so about that....
```suggestion
	reward = 3000
```

2022-07-25 05:51 UTC, NCRLouTenant commented
Big thanks for this one.  Always felt like getting paid the same for a B-52 as a coffee that I added ice too was weird.

2022-07-30 14:53 UTC, JamieD1 approved these changes

2022-07-30 14:53 UTC, merged