Modernizes Toxins Testing Lab Layout
yogstation13/Yogstation pull request #15079
Opened 2022-07-31 03:15 UTC by Xantam-13

Amended the map to reflect the current method of toxins testing so you don't have to set up each and every round. 

Old: 
https://i.imgur.com/aosgkDU.png

New:
https://i.imgur.com/NJPawFl.png

:cl:  
tweak: renovated Toxins Test Lab to reflect current method of bomb making  
/:cl:

2022-07-31 03:18 UTC, ToasterBiome commented
Why no heater? It's used in some beginner bombs.

2022-07-31 03:20 UTC, Xantam-13 commented
> Why no heater? It's used in some beginner bombs.

Can just screw-driver the cooler right?

2022-07-31 03:20 UTC, ToasterBiome commented
> > Why no heater? It's used in some beginner bombs.
> 
> Can just screw-driver the cooler right?

I'd prefer if you had both also you only need one anyway

2022-07-31 03:21 UTC, Xantam-13 commented
> 

Can put it back easy enough if youd prefer?

2022-07-31 03:21 UTC, ToasterBiome commented
Yes

2022-07-31 03:25 UTC, Xantam-13 commented
https://i.imgur.com/4VLyLko.png 

Replaced back with a heater

2022-08-01 00:02 UTC, SynnGraffkin commented
As someone who used to do a lot of Toxins a few years back on other sources, I think changing the starting layout like this is excessive and can be confusing to those learning it. Part of the beauty with Toxins, for those who take the time to make their own methods and mixes, is making your own pipe methods. I used to always ask for the RD suit, be it from the RD or AI, to do additional chamber piping and have it scrubbed into space piping for colder cooling before parts were done. Was this excessive for what you need in Toxins? Yes, but I enjoyed it.

While a piping setup you posted may be optimal for some players, I still think the old / default is a better starting point for new players or those who want to learn toxins.

2022-08-10 21:10 UTC, ToasterBiome commented
in regards to this I think it's a little bit too optimized that you're functionally making it the only method of doing toxins. The default setup doesn't lend well into _anything_ and I think that's part of the beauty of it. 

I would be more inclined to merge it if these were blank and the simple design of the room and the empty space _suggested_ these instead of forced it

![image](https://user-images.githubusercontent.com/5091394/184020654-65dd984b-a6f6-4635-bfc2-bcba7fc8b00c.png)

2022-08-10 21:10 UTC, ToasterBiome requested changes
oh need to press this button

2022-08-11 12:24 UTC, redmoogle commented
something that might be neet is to have the supplies behind a windoor closet like the one in medbay

2022-08-11 21:23 UTC, Xantam-13 commented
> oh need to press this button

I reject your change request, I won't be doing that. Just because you give someone a carrot does not mean they have to eat it.

The problem as it stands right now is that the wiki isn't informative or clear enough on how to do toxins, and the current layout was designed exactly and intentionally for old toxins. All this change does is bring the lab up to par with how toxins is now. 
Of which, I have no stake in, I still don't know toxins, this PR was made at the feedback of 3 or 4 toxins users. 

The new proposed layout would greatly assist those who did wish to learn toxins, who could then tailor the pipes freely to learn alternative methods. 

In doing this, we could also discourage griefers. Right now, we get bombed quite a bit by griefers, but if they log in and see the lab already in use, they might be tempted to find less destructive methods of grief. But if they see an abandoned lab (which they often do, due to the complexity of the wiki and the poor pre-design), they are more inclined to just crack on and make juicy boom booms. 

So again, I reject your change request. I'll leave it to Jamie whether he wishes to merge this, trial this, or reject this, thank you.

2022-08-14 16:05 UTC, JamieD1 commented
Looking over with Baiomu to find a solution

2022-08-20 11:40 UTC, JamieD1 commented
Sorry for the delay with this, I had a brainwave on how we can redesign all of south east science because of this PR, will try get the ball rolling

2022-09-10 18:03 UTC, TheGamerdk commented
Conflcited + Dev Conflict + Stale + Stale devs

2022-09-10 18:12 UTC, TheGamerdk commented
Our good friends Jamie and Baiomu are redoing this with Xantams input

2022-09-10 18:12 UTC, closed without merging