Adds the ability to hide tiny items in vents
yogstation13/Yogstation pull request #1514
Opened 2018-06-29 15:09 UTC by nichlas0010

[This, but it works](https://github.com/HippieStation/HippieStation/pull/7960)

#### Changelog

:cl:  YoYoBatty
rscadd: Adds ability to crowbar and hide tiny items in vent pumps
/:cl:

2018-06-29 15:12 UTC, Nickvr628 commented
So the captain can hide the nuke disk in a vent under a table under an RCD'ed wall.

Nice

2018-06-29 15:23 UTC, yoyobatty commented
Except not really because vents by default appear ontop of walls.

2018-06-30 04:36 UTC, yoyobatty commented
Alright, update the code to sync with the original pr and it should be good to go.

2018-07-02 08:16 UTC, ThatLing requested changes

2018-07-02 08:16 UTC, ThatLing commented on yogstation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +		if(W.w_class == WEIGHT_CLASS_TINY && istype(W,/obj/item) && user.a_intent != INTENT_HARM)
Switch the class and istype checks around.

2018-07-02 16:52 UTC, merged