adds the Improvised Cryptographic Sequencer
yogstation13/Yogstation pull request #15141
Opened 2022-08-04 00:53 UTC by TheRyeGuyWhoWillNowDie

Blood brothers need a bit of help still, they're certainly better, but they're still not exactly good. This will hopefully help with that a little.

The improvised emag works differently from the normal emag, it can be crafted with syndicate crafting (aka traitors and blood brothers) instead of being instant like the normal emag, it takes between 5 and 10 seconds to use, has a 40% chance to fail, and a 5% chance to succeed but light you on fire. It also has only five uses that must be manually recharged. Failing to succeed will still charge you a use of the emag. You can recharge it by hitting it with uranium sheets. To build it, you need a subspace amplifier, an ID card, firelock electronics, and ten cablecoil.

**This cannot emag supply consoles. Blood brothers with null crates would be very bad.**

# Spriting
i know it looks pretty shitty but its my first time spriting and i had to do it myself
![image](https://user-images.githubusercontent.com/70169560/182739806-3e4c8f42-675e-4ef1-8796-762b09f8de09.png)

# Wiki Documentation

Syndicate items page for Makeshift Weapons 101

# Changelog

:cl:  
rscadd: improvised cryptographic sequencer
/:cl:

2022-08-04 00:58 UTC, Cartlord commented
whaaat the fuck

2022-08-04 01:44 UTC, Marmio64 commented
The tc cost for improvised weapons may need to be raised at this rate

2022-08-04 02:00 UTC, tattax commented on code/game/objects/items/cards_ids.dm
> +			var/atom/A = target
```suggestion
	if(charges > 0)
		if(!proximity && prox_check) //left in for badmins
			return
		if(do_after(user, rand(5, 10) SECONDS, src))
			var/atom/A = target
```
you could early return and target is already an atom, so i don't know why the var here

2022-08-04 02:01 UTC, Mqiib commented
![image](https://user-images.githubusercontent.com/43766432/182746663-5752c33c-76de-431a-930b-394da9841fd0.png)
![image](https://user-images.githubusercontent.com/43766432/182746691-cc6762d6-d9ef-4f9c-a423-8515971b3d07.png)

Check the warning text for consistency. Generally we omit "the" because the game automagically slaps it on if it's an improper noun (read: doesn't start with a capital). Also if you changed the fail text to something more interesting than "you failed!" such as "[src] sparks and fails to affect [A]" or something that'd be cool beans.

2022-08-04 02:01 UTC, tattax commented on code/datums/components/crafting/makeshift.dm
> +        			/obj/item/card/id = 1,
```suggestion
        		/obj/item/card/id = 1,
```

2022-08-04 02:03 UTC, tattax commented on code/game/objects/items/cards_ids.dm
> +	var/can_bluespace = TRUE //can this become a bluespace emag?
you could just call istype instead of making a var for this

2022-08-04 02:06 UTC, tattax commented on code/game/objects/items/cards_ids.dm
> +	. += span_notice("The charge meter indicates that it has [charges] charges remaining out of [max_charges].")
```suggestion
	. += span_notice("The charge meter indicates that it has [charges] charge[charges == 1 ? "" : "s"] remaining out of [max_charges].")
```

2022-08-04 02:06 UTC, tattax commented on code/game/objects/items/cards_ids.dm
> +			to_chat(user, span_notice("You add another charge to the [src]. It now has [charges] uses remaining."))
```suggestion
			to_chat(user, span_notice("You add another charge to the [src]. It now has [charges] use[charges == 1 ? "" : "s"] remaining."))
```

2022-08-04 02:06 UTC, tattax commented on code/game/objects/items/cards_ids.dm
> +				var/mob/living/M = loc
```suggestion
				var/mob/living/M = user
```

2022-08-04 02:23 UTC, TheRyeGuyWhoWillNowDie commented
> ![image](https://user-images.githubusercontent.com/43766432/182746663-5752c33c-76de-431a-930b-394da9841fd0.png) ![image](https://user-images.githubusercontent.com/43766432/182746691-cc6762d6-d9ef-4f9c-a423-8515971b3d07.png)
> 
> Check the warning text for consistency. Generally we omit "the" because the game automagically slaps it on if it's an improper noun (read: doesn't start with a capital). Also if you changed the fail text to something more interesting than "you failed!" such as "[src] sparks and fails to affect [A]" or something that'd be cool beans.

yeah i just didnt know what to put for fail text, gimme a second

2022-08-04 20:09 UTC, KillerOrcaCora requested changes
Gonna modfiey sprite

2022-08-05 22:59 UTC, MusselMain commented
I hate to be the negative one, but miners and scientists can get around recharging it pretty easily.

2022-08-06 06:52 UTC, 00ze-cyclone commented
> I hate to be the negative one, but miners and scientists can get around recharging it pretty easily.

Literally every job with access to a techfab (so anyone with a real job in a department) can just take sheets of uranium out of the silo. For 70% of the jobs recharging that emag will be trivial, not just miners and scientists.

2022-08-07 20:20 UTC, KillerOrcaCora approved these changes
Bless us, oh Lord, and these thy gifts, which we are about to receive from thy bounty, through Christ, our Lord. Amen.

2022-08-14 16:36 UTC, JamieD1 commented
Balance Council Say Yes

2022-08-14 16:36 UTC, merged