[ADMIN] TGUI Check Antagonists panel
yogstation13/Yogstation pull request #15182
Opened 2022-08-06 00:46 UTC by ynot01

# Document the changes in your pull request

Tested thoroughly, has all of the features that old check antags panel had, with some extra (VV button)

![](https://i.imgur.com/C7njIq3.png)

2022-08-06 07:45 UTC, TheGamerdk requested changes
DNM until I review and help fix this

2022-08-06 09:07 UTC, SuperSlayer0 commented
Looks cool

2022-08-20 11:53 UTC, JamieD1 commented
> DNM until I review and help fix this

Get on with it

2022-08-28 17:31 UTC, TheGamerdk requested changes

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/antagonists/nukeop/nukeop.dm
> +	// [0: "TeamName", 1:[AntagConstructor, AntagConstructor], 2:[Name of Tracked, [ [Name, TRACK_REF], [Name, TRACK_REF] ] ] ]
Construct these as associative lists

list(list("TeamName" = the_team_name, and so on))

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/antagonists/revolution/revolution.dm
> +	var/list/team_construct = list(antag_listing_name(), list(), list(FALSE,list()))
associative please

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/admin/check_antagonists.dm
> +	if(owner.current) // [0:"Traitor", 1:"Joe Schmoe", 2:"(DEAD)", 3:"[0x2100b3a5]", 4:MOB?, 5:CLIENT?, 6:Antag/Datum]
associative list

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/admin/check_antagonists.dm
> +	// [0: "TeamName", 1:[AntagConstructor, AntagConstructor], 2:[Name of Tracked, [[Name, TRACK_REF], [Name, TRACK_REF]]]]
associative list

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/admin/check_antagonists.dm
> +	var/datum/tgui_check_antags/tgui = new(usr)//create the datum
is there a specific reason we can't keep the datum around?

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/admin/check_antagonists.dm
> +		var/client/user_client = user
there's no need to typecast

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/admin/check_antagonists.dm
> +	spawn(5 SECONDS)
avoid using SPAWN, use a timer or similar

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/admin/check_antagonists.dm
> +	var/client/rights = holder
stop using these unnecessary variables? holder is already a /client, just use that

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/admin/check_antagonists.dm
> +			return 1
TRUE/FALSE in this proc

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/admin/check_antagonists.dm
> +	if(mob_user != usr) // If the holder has been edited, this will catch it before any badness can be done
tbh if you already do this i don't see why you even need the holder var on the datum? can't you just use usr all the way through?

2022-08-28 17:31 UTC, Bibby0110 commented on code/modules/admin/check_antagonists.dm
> +			if(!check_rights(R_SERVER))
weird that this is R_SERVER when calling the shuttle is R_ADMIN, no?

2022-08-28 17:31 UTC, TheGamerdk commented on code/modules/admin/check_antagonists.dm
> +				SSshuttle.emergency.setTimer(timer*10)
```suggestion
				SSshuttle.emergency.setTimer(timer SECONDS)
```

2022-08-28 17:31 UTC, TheGamerdk commented on code/modules/admin/check_antagonists.dm
> +				minor_announce("The emergency shuttle will reach its destination in [round(SSshuttle.emergency.timeLeft(600))] minutes.")
```suggestion
				minor_announce("The emergency shuttle will reach its destination in [round(SSshuttle.emergency.timeLeft(1 MINUTES))] minutes.") //timeLeft variable is divisor, aka we show in minutes remaining
```

2022-08-28 17:31 UTC, TheGamerdk commented on code/modules/admin/check_antagonists.dm
> +/datum/tgui_check_antags/ui_act(action, params)
block proccalls

2022-08-28 17:31 UTC, TheGamerdk commented on code/modules/admin/check_antagonists.dm
> +					SSticker.force_ending = 1 //Yeah there we go APC destroyed mission accomplished
TRUE

2022-08-28 17:31 UTC, TheGamerdk commented on code/modules/admin/check_antagonists.dm
> +				if(isnull(SSticker.admin_delay_notice))
Ignore if you intend for ""/empty string to be valid
```suggestion
				if(!SSticker.admin_delay_notice)
```

2022-08-28 17:31 UTC, TheGamerdk commented on code/modules/admin/check_antagonists.dm
> +			var/msg = "[SSticker.delay_end ? "delayed" : "undelayed"] the round end [reason]"
```suggestion
			var/msg = "[SSticker.delay_end ? "delayed" : "undelayed"] the round end[reason]"
```

2022-08-28 17:31 UTC, TheGamerdk commented on code/modules/admin/check_antagonists.dm
> +			var/reason = SSticker.delay_end ? "for reason: [SSticker.admin_delay_notice]" : "."//laziness
```suggestion
			var/reason = SSticker.delay_end ? " for reason: [SSticker.admin_delay_notice]" : "."//laziness
```

2022-08-28 17:31 UTC, TheGamerdk commented on code/modules/admin/check_antagonists.dm
> +			if(confirm == "No")
redundant

2022-08-28 17:31 UTC, TheGamerdk commented on tgui/packages/tgui/interfaces/CheckAntags.js
> +              <br />
can't you get rid of these brs and use some padding/margin

2022-08-28 17:31 UTC, TheGamerdk commented on tgui/packages/tgui/interfaces/CheckAntags.js
> +              Round Duration:
Not a box?

2022-08-28 17:31 UTC, TheGamerdk commented on tgui/packages/tgui/interfaces/CheckAntags.js
> +              {shuttlecalled ? '' : <Input
syntax probably not correct, but something like this. don't use a ternary for this
```suggestion
              {shuttlecalled && (<Input
```

2022-08-28 17:31 UTC, TheGamerdk commented on tgui/packages/tgui/interfaces/CheckAntags.js
> +                })} />}
```suggestion
                })} />)}
```

2022-08-28 17:31 UTC, TheGamerdk commented on tgui/packages/tgui/interfaces/CheckAntags.js
> +              {continue1 ? <Button
see above with regards to ternary

2022-08-28 17:31 UTC, TheGamerdk commented on tgui/packages/tgui/interfaces/CheckAntags.js
> +              <br />
bad br

2022-08-28 17:31 UTC, TheGamerdk commented on tgui/packages/tgui/interfaces/CheckAntags.js
> +              {continue1 && continue2 ? 'Time limit: ' : ''}
you get it by now

2022-08-28 17:31 UTC, TheGamerdk commented on tgui/packages/tgui/interfaces/CheckAntags.js
> +                    {teamdata[1].map((antagdata, idx) =>
when you've redone the DM side as associative lists these will function like objects

2022-09-06 22:48 UTC, TheGamerdk commented
Stale, reopen when work on it

2022-09-06 22:48 UTC, closed without merging