[ADMIN] Chganges auth backend to use the forums instead of the DB
yogstation13/Yogstation pull request #15195
Opened 2022-08-07 00:13 UTC by adamsong

# Document the changes in your pull request
Uses the forums to manage permissions instead of the database. Needs a small update to the endpoint to get rank names. 

Still working on testing, will need much test merging to make sure is not broken.

# Changelog

:cl:  
tweak: Moved from db to forums as admin permissions backend.
/:cl:

2022-08-07 00:21 UTC, alexkar598 commented on config/secret.txt
> +XENFORO_KEY wTh6g8RUe7GKuoVAv0QFwK2nFBdBFUlD
:^)

2022-08-09 20:01 UTC, adamsong commented
Ah fuck, forgot about tgui linter

2022-08-11 00:47 UTC, alexkar598 commented on code/__HELPERS/roundend.dm
> -	var/datum/DBQuery/query_admin_rank_update = SSdbcore.NewQuery("UPDATE [format_table_name("player")] p INNER JOIN [format_table_name("admin")] a ON p.ckey = a.ckey SET p.lastadminrank = a.rank")
lastadminrank seems to be deprecated without a proper db bump + removal. I believe this field is used in external tooling too

2022-08-11 00:53 UTC, alexkar598 requested changes

2022-08-11 00:53 UTC, alexkar598 commented on code/modules/admin/permissions/forums.dm
> +	req.prepare(RUSTG_HTTP_METHOD_GET, "[CONFIG_GET(string/apiurl)]/linking/byond/[ckey]", "", list("XF-Api-Key" = CONFIG_GET(string/xenforo_key)))
Sanitize ckey

2022-08-11 02:59 UTC, adamsong commented
Ready for review, just need a heads up before merge because I've not quite locked it down so I can debug the test merge.

2022-08-14 16:52 UTC, JamieD1 commented
This ready @alexkar598 @adamsong

2022-08-14 17:26 UTC, adamsong commented
I'd like alexkar's approval first, and it will need modiifying admins.txt and admin_ranks.txt

2022-08-14 20:49 UTC, alexkar598 commented
I looked at the bits I was concerned about ie external interactions with the forums

2022-08-16 00:25 UTC, adamsong commented
Ready to be merged @JamieD1 Don't forget to update admins.txt and admin_ranks.txt when merged

2022-08-28 13:25 UTC, JamieD1 approved these changes

2022-08-28 13:26 UTC, JamieD1 approved these changes

2022-08-28 13:26 UTC, merged