Comms console has smaller antenna
yogstation13/Yogstation pull request #15215
Opened 2022-08-08 01:08 UTC by adamsong

# Document the changes in your pull request

Built comms consoles now only work on station.
Mapped consoles, using the /unlocked subtype, can be used anywhere, if they are destroyed and rebuilt, they will no longer work anywhere.

# Changelog

:cl:  
tweak: Comms consoles built during the round only work on the station z-level
/:cl:

2022-08-08 08:43 UTC, TheGamerdk commented
Move the check so you can’t just log in and move the console off z-level
Make admin ghosts ignore the z level requirement

2022-08-08 11:58 UTC, redmoogle commented
> Move the check so you can’t just log in and move the console off z-level Make admin ghosts ignore the z level requirement

Admins have the call shuttle button

2022-08-08 14:21 UTC, adamsong commented
> Move the check so you can’t just log in and move the console off z-level

You cannot unanchor the console, so you would need some what to move it, and there aren't many of those

2022-08-10 16:59 UTC, TheGamerdk commented
> > Move the check so you can’t just log in and move the console off z-level
> 
> You cannot unanchor the console, so you would need some what to move it, and there aren't many of those

you can put the console on a modular shuttle and just leave

2022-08-10 17:00 UTC, TheGamerdk commented
> > Move the check so you can’t just log in and move the console off z-level Make admin ghosts ignore the z level requirement
> 
> Admins have the call shuttle button

There's a bunch of the buttons they don't have

2022-08-13 20:50 UTC, ToasterBiome requested changes
fix as bibby says

2022-08-14 17:06 UTC, JamieD1 approved these changes

2022-08-14 21:08 UTC, ToasterBiome approved these changes

2022-08-14 21:08 UTC, merged