Move Mining Satchel of Holding to Mining Designs
yogstation13/Yogstation pull request #1531
Opened 2018-06-30 17:51 UTC by Apologistic

### Intent of your Pull Request

Mining Satchel of Holding seems like it ought to be better categorized in the mining designs, rather than bluespace.

#### Changelog

:cl:  
tweak: Moved mining satchel of holding to mining designs from bluespace
/:cl:

2018-06-30 18:01 UTC, GuppyLaxx reviewed
if you need a hand with this feel free to ping me on discord or something, :B1:

2018-06-30 18:01 UTC, GuppyLaxx commented on code/modules/research/designs/bluespace_designs.dm
> -/datum/design/miningsatchel_holding
Comment this out from here to the bottom instead with a /*

2018-06-30 18:01 UTC, GuppyLaxx commented on code/modules/research/designs/bluespace_designs.dm
> -	departmental_flags = DEPARTMENTAL_FLAG_CARGO
*/

2018-06-30 18:01 UTC, GuppyLaxx commented on code/modules/research/designs/mining_designs.dm
> +/datum/design/miningsatchel_holding
you can also modularize this by making a respective file in the yogs folder and all.

2018-06-30 21:21 UTC, ThatLing requested changes
```
/datum/design/miningsatchel_holding
    category = list("Bluespace Designs", "Mining Designs")
```
in ``yogstation/code/modules/research/designs/bluespace_designs.dm ``

2018-07-14 09:41 UTC, ThatLing commented
Stale, feel free to re-open or make a new PR when you are working on this again.

2018-07-14 09:41 UTC, closed without merging