slightly reduces the hugboxxing on the RnD lab doors
yogstation13/Yogstation pull request #15325
Opened 2022-08-15 17:55 UTC by TheRyeGuyWhoWillNowDie

Now roboticists can walk in. Wow!

thank you PISSNER for telling me about this this is so fucking stupid

this part of the three part science hugbox doesnt even DO ANYTHING because there is... GET THIS... A SECOND SCIENCE PROTOLATHE IN A ROOM THAT JUST NEEDS SCIENCE FRONT DOOR ACCESS. WOW!

# Changelog
:cl:  
bugfix: now roboticists can walk into the RnD lab on boxstation! wow!
/:cl:

2022-08-15 17:56 UTC, JamieD1 commented
req one access

2022-08-15 17:57 UTC, TheRyeGuyWhoWillNowDie commented
> req one access

sorry im bad at mapping gimme a second hnngh

2022-08-16 03:43 UTC, SynnGraffkin commented
Could probably add it resolves #15302

2022-08-18 09:19 UTC, ToasterBiome approved these changes

2022-08-18 09:23 UTC, ToasterBiome requested changes
Shouldn't the door access be 47 (shared by robos and scientists)?

2022-08-18 20:29 UTC, Xantam-13 commented
If you do this, then give science personnel access to the Robo lab. 

Right now, you're making robotics 100% more powerful and desirable than science.

2022-08-18 20:33 UTC, ToasterBiome commented
> If you do this, then give science personnel access to the Robo lab.
> 
> Right now, you're making robotics 100% more powerful and desirable than science.

All sub departments in a department should have access to the departmental protolathe. All medical personnel get access to the medical one, all engineering get access to the engineering one,all of science should get access to the science one. Service too.

2022-08-20 12:42 UTC, JamieD1 commented
> Shouldn't the door access be 47 (shared by robos and scientists)?

Problem is that gives heads access to, (I think)

2022-08-20 13:48 UTC, TheRyeGuyWhoWillNowDie commented
> If you do this, then give science personnel access to the Robo lab.
> 
> Right now, you're making robotics 100% more powerful and desirable than science.

Nope this doesn't actually chance anything except make Science more intuitive for new players. No other map except box has a strange RnD lab that requires toxins access. It doesn't even matter on box because in the misc. testing lab there's, what a shocker, a second Science protolathe. This is really just QoL for scientists and reduces some unnecessary hugboxxing

2022-08-20 13:57 UTC, ynot01 commented
I disagree with this change because it lets security research again which was an initial motivator for the door

2022-08-21 10:48 UTC, SynnGraffkin commented
> I disagree with this change because it lets security research again which was an initial motivator for the door

and yet Roboticists are denied usage of the front desk protolathe, unlike every other map. 

> If you do this, then give science personnel access to the Robo lab.
> 
> Right now, you're making robotics 100% more powerful and desirable than science.

Scientists DO get robotics access on low pop AKA Skeleton crew. All this PR does is make things consistent across maps.

2022-08-28 14:09 UTC, JamieD1 commented
> > req one access
> 
> sorry im bad at mapping gimme a second hnngh

You didnt do my request of doing req_one_access and instead adding an access shared which we didnt want to begin with. Please just do req_one_access of robotics and the correct R&D it was before.

2022-08-31 22:58 UTC, closed without merging