[PORT] Vault bank machine checks for vault access before alerting
yogstation13/Yogstation pull request #15359
Opened 2022-08-18 11:14 UTC by warface1234455

# About pr

- ports: https://github.com/tgstation/tgstation/pull/68832

# Document the changes in your pull request
Vault bank now checks for access for alerting

# Wiki Documentation

Vault bank now checks for access for alerting

# Changelog

:cl:  
rscadd: Vault bank now check for access for alerting
/:cl:

2022-08-19 13:11 UTC, redmoogle requested changes

2022-08-19 13:11 UTC, redmoogle commented on code/game/machinery/bank_machine.dm
> +			start_siphon(ui.user)
```suggestion
			if(iscarbon(usr))
				var/mob/living/carbon/C = usr
				start_siphon(C)
```

2022-08-19 13:11 UTC, redmoogle commented on code/game/machinery/bank_machine.dm
> +			start_siphon(ui.user)
Other code uses this, likely a better choice as I see no example of yours besides in slime people

2022-08-28 14:44 UTC, JamieD1 commented
Noone should be taking money anyway, so alerting on everyone is fine.

2022-08-28 14:44 UTC, closed without merging

2022-08-28 14:47 UTC, warface1234455 commented
> Noone should be taking money anyway, so alerting on everyone is fine.

It still alert people tho, radio scream for unauthorized people and no scream for authorized people

2022-08-28 19:30 UTC, JamieD1 commented
> > Noone should be taking money anyway, so alerting on everyone is fine.
> 
> It still alert people tho, radio scream for unauthorized people and no scream for authorized people

I want the captain to be screamed at, he shouldn't be taking money from the vault