turnstiles block atmos
yogstation13/Yogstation pull request #15365
Opened 2022-08-18 17:06 UTC by TheGamerdk

# If this is your first PR, or not, take the time to read our CONTRIBUTING.md file! You can see it here: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md
You can remove all headers (Document the changes, Spriting and Wiki documentation) if there is no wiki documentation required but you must still explain what the pr is and why it needs to be added to the game. Directors+ Are immune from this rule in exceptional circumstances.

# Document the changes in your pull request

Remove this text and explain what the purpose of your PR is.

Mention if you have tested your changes. If you changed a map, make sure you used the mapmerge tool.
If this is an Issue Correction, you can type "Fixes Issue #6" to link the PR to the corresponding Issue number #6.

Prefix the PR title with [admin] if it involves something admin related. 
Prefix the PR title with [s] if you are fixing an exploit, so that it is not announced on the Yogstation Discord and the server.

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying.

# Spriting
If you are adding new sprites to the game please add a picture of the sprite in its relative context, ie. Clothing on a mob.

# Wiki Documentation

Remove this text and write all information regarding your changes that should be known and documented through the Yogstation Wiki. 
Important documentation information includes, but is not limited to: any numerical values that have been changed, any images that have to be updated, names of specific pages that will be impacted by your changes. 

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images  
spellcheck: fixed a few typos  
experimental: This is experimental  
/:cl:

2022-08-18 20:26 UTC, Xantam-13 commented
@TheGamerdk Fix the content of your PR please... even if you just remove the content barring the changelog...

2022-08-20 08:38 UTC, ToasterBiome requested changes, later dismissed
changelog

2022-08-20 13:09 UTC, JamieD1 commented
Fixed Changelog

2022-08-20 13:09 UTC, JamieD1 commented on code/game/machinery/doors/turnstile.dm
> +
```suggestion
```

2022-08-20 13:09 UTC, JamieD1 commented on code/game/machinery/doors/turnstile.dm
> +
```suggestion
	CanAtmosPass = ATMOS_PASS_NO
```

2022-08-20 13:09 UTC, JamieD1 approved these changes

2022-08-20 13:26 UTC, merged