Makes paydays no longer pull form department budgets
yogstation13/Yogstation pull request #15431
Opened 2022-08-22 22:40 UTC by nmajask

# Document the changes in your pull request

Removes paydays pulling from department budgets, fixing the budgets getting drained by them alone. I was under the impression that this was already the case when I reduced the amount budgets start with, but I guess I was wrong.

# Spriting
None.

# Wiki Documentation

Don't think paydays are mentioned on the wiki, if they are then maybe include this. 

# Changelog

:cl:  
tweak: paydays no longer pull from department budgets
/:cl:

2022-08-22 23:45 UTC, Cartlord commented
Then why have department budgets?

2022-08-23 00:58 UTC, nmajask commented
> Then why have department budgets?

so heads can buy stuff with it using nirn

2022-08-23 00:58 UTC, VaelophisNyx commented
thank god

2022-08-23 01:13 UTC, TheGamerdk requested changes
Increase the amount of money the budgets make, or give them more to start with

2022-08-23 03:29 UTC, closed without merging