Syndicate Objective Manifestation System (SOMS)
yogstation13/Yogstation pull request #15579
Opened 2022-09-02 19:08 UTC by ynot01

# Document the changes in your pull request

Adds a new category to the uplink with 4 options:

- Request Objective (RANDOM)
- Request Objective (EASY)
- Request Objective (MEDIUM)
- Request Objective (HARD)

Easy objectives will reward 2-3 TC
Medium objectives will reward 3-5 TC
Hard objectives will reward 5-7 TC

Each option has a 50% chance of appearing/not appearing and only have one use.

"Purchasing" one of these will notify online admins and start a 1 minute timer.

If an admin is online, they will have the option to override your objective with their own custom objective, and they will be able to choose their own difficulty rating.

Once the 1 minute timer expires or an admin creates an objective, you will be notified.

Your objective will come in form of a folder of a random color on a random safe turf in the station where no one can currently see it. It is up to you to get to it.

You will be told where and what color the folder is.

If another syndicate gets ahold of your folder, they will be able to complete the objective just as you would have. You can use this to steal or cooperate with others.

Once you have completed the objective, you should hit the Check Completion button. 

If the objective is complete, the folder will give you your reward.

If the objective is incomplete, the folder will scold you.

If the objective is admin-handled, admins will be notified of your request and either confirm or deny the action. You will be alerted to their action by a beep and if they confirm, the objective will be marked as complete and you will be able to redeem the objective as normal.

## Visual Aid

![](https://i.imgur.com/X2r1aRW.png)

![](https://i.imgur.com/Dc3tGIX.png)

1 minute later...

![](https://i.imgur.com/ay14LzG.png)

![](https://i.imgur.com/qYLjULF.png)

![](https://i.imgur.com/bhY3y7r.png)

![](https://i.imgur.com/gpFnNuc.png)

# Changelog

:cl:  
experimental: Added objective requesting system for Syndicates
spellcheck: assasinate -> assassinate pets
bugfix: Fixed a bunch of objectives runtiming if they couldn't find what they wanted
tweak: Made caplaser objective 10 difficulty from 5
tweak: Made captain's jetpack objective 10 difficulty from 5
tweak: Made nuke disk objective 15 difficulty from 5
/:cl:

2022-09-02 19:09 UTC, ToasterBiome commented
oooo

2022-09-02 19:39 UTC, 00ze-cyclone commented
This sound interesting.

2022-09-02 19:49 UTC, SuperSlayer0 commented
Assasination should count as a medium objective

2022-09-03 03:13 UTC, Marmio64 commented
this is a cool idea but im not so sure on the balance implications. Doing 1 medium/hard mission can allow you to easily cross the TC threshold for a lot of things that are otherwise very difficult to get. You'd need to be an IAA and kill some targets, gamble all your TC on being a contractor, or manage to link up and borrow TC from another traitor (or steal it). This however seems to have virtually no risk and if the given objective is an easy one to get for you in the current round, it can be very powerful. If you don't like the objective, as far as I know you can just choose to completely ignore it. Even though you wont get any extra TC you wont specifically lose anything from not going with it. I think a better idea would be to integrate this with the contractor stuff thats already in place since it has much of the same idea anyways and would keep it so that you actually risk stuff for extra TC.

TL;DR
you should just integrate this with the contractor system instead

2022-09-03 15:13 UTC, redmoogle commented on code/modules/uplink/uplink_items.dm
> +	message_admins("[ADMIN_LOOKUPFLW(user)] has requested an objective ([diff_txt]). (<A HREF='?_src_=holder;[HrefToken()];uplink_custom_obj=[REF(src)];requester=[REF(user)]'>FORGE CUSTOM OBJECTIVE?</A>
What about a deny button for when the round is already too chaotic

2022-10-01 08:21 UTC, ynot01 commented
> you should just integrate this with the contractor system instead

2024-02-20 05:21 UTC, GDRdev commented
**### this surely will effect the tc economy**

Though imagine the anoumts of tc you could get in one game...
Contactor, syndie bounties, and now THIS?

2024-02-20 05:22 UTC, ToasterBiome requested changes
can you make the button in the uplink say "REQUEST" instead of 0 tc?

2024-02-20 05:26 UTC, GDRdev commented
There is also reason to not get a extra hard objective. Since it doesnt effect your _greentext_ failling it would just mean you dont get the **extra** tc. If I had to suggest a change it would probably make it soo you have to spend like a down payment of tc to get these objectives soo you do lose out on something when you fail it instead of it being extra tc for free.

2024-02-20 05:29 UTC, ynot01 commented
> Since it doesnt effect your _greentext_ failling

If you complete the objective (and receive your reward TC) the objective is added to your objectives list to prevent fraud

2024-02-20 05:29 UTC, GDRdev commented
also how is the "Steal a reflective jacket" a medium objective when - nvm you can just raid cargo-

Though there is no reason why the blueprints is a **"hard"** objective considering its just as hard as the boots if not easier since CE normally doesnt carry around the blueprints unlike the boots.

2024-02-20 05:30 UTC, GDRdev commented
> > Since it doesnt effect your _greentext_ failling
> 
> If you complete the objective (and receive your reward TC) the objective is added to your objectives list to prevent fraud

You know what would be better than that? If you were given a certain amount of time to complete the objective and if you fail a single IIA would spawn with the only objective to kill you.

2024-02-20 05:31 UTC, ynot01 commented
> also how is the "Steal a reflective jacket" a medium objective when - nvm you can just raid cargo-

The easy objectives are *incredibly* easy and I do not believe the reflective jacket is on the same level.

2024-02-20 05:31 UTC, GDRdev commented
> > Since it doesnt effect your _greentext_ failling
> 
> If you complete the objective (and receive your reward TC) the objective is added to your objectives list to prevent fraud

This also doesnt change my point of you could just garb a extra hard objective and if its too hard you can just leave it and ignore the extra tc

2024-02-20 05:32 UTC, ynot01 commented
> This also doesnt change my point of you could just garb a extra hard objective and if its too hard you can just leave it and ignore the extra tc

I don't see an issue with allowing players to turn down objectives if they deem them too difficult

2024-02-20 05:32 UTC, GDRdev commented
> > also how is the "Steal a reflective jacket" a medium objective when - nvm you can just raid cargo-
> 
> The easy objectives are _incredibly_ easy and I do not believe the reflective jacket is on the same level.

I was talking about moving it up to hard since you would normally have to raid armory (and assuming this is on high pop) is very hard to do but I remembered you can just order it

2024-02-20 05:34 UTC, GDRdev commented
> > This also doesnt change my point of you could just garb a extra hard objective and if its too hard you can just leave it and ignore the extra tc
> 
> I don't see an issue with allowing players to turn down objectives if they deem them too difficult

*shrug I guess the only issue is that it could be too free of a objective which allows you to start with 27 tc instead of the normal 20. Sorta like syndie bounties on low pop

2024-02-20 05:36 UTC, ynot01 commented
> *shrug I guess the only issue is that it could be too free of a objective which allows you to start with 27 tc instead of the normal 20.

That's why the objectives are sorted by difficulty. All of the 'hard' objectives are very respectably difficult objectives.

2024-02-20 05:48 UTC, GDRdev commented
> > *shrug I guess the only issue is that it could be too free of a objective which allows you to start with 27 tc instead of the normal 20.
> 
> That's why the objectives are sorted by difficulty. All of the 'hard' objectives are very respectably difficult objectives.

still dont get blueprints as hard ngl

2024-02-20 14:31 UTC, MajManatee commented
Seems like too much TC imo

2024-02-21 19:12 UTC, cowbot92 commented
I like this

2024-02-22 00:12 UTC, Therandomhoboo commented
If I'm reading this right, a potential 12-15 tc added on if you get all folders with good rng.
This just looks like bounties but instead of having to use an emag you just have to gamble but everyone has it. At least with bounties it was locked behind cargo or you needed to build a console to do it and use the supply shuttle to send it off so they had to be stuck to one area. 

I'm just not a fan of it because bounties exist currently and that the risk seems kinda small unless you roll extremely bad.

2024-02-23 06:52 UTC, ToasterBiome approved these changes

2024-03-08 06:33 UTC, Moltijoe commented
Balance Council:
>We do not currently want a system like this in the game

2024-03-08 07:14 UTC, ToasterBiome commented
HD reopen, testmerging

2024-03-09 09:03 UTC, Majkl-J commented
No way yog progtot

2024-03-10 00:43 UTC, LassiH commented
overpowered free tc reskinned syndicate bounties for free no emag purchase required

2024-03-12 01:48 UTC, Mqiib commented
Folders can spawn in non-station areas like the syndicate research outpost on icemoon. It happened twice in one round to @Yarinoi 

![image](https://github.com/yogstation13/Yogstation/assets/43766432/4107a361-df58-4136-9054-7f5e5e2f7c4e)
![image](https://github.com/yogstation13/Yogstation/assets/43766432/d025b9d2-f5cc-4b05-af29-189e53bbb796)

2024-03-12 01:53 UTC, Yarinoi commented
can confirm it happened to me
![image](https://github.com/yogstation13/Yogstation/assets/122653864/2be192e8-5ef9-4b31-9198-e00fbb6436cf)
![image](https://github.com/yogstation13/Yogstation/assets/122653864/a5e741ce-5ce5-4f8c-b736-f9fc361cdfc6)

2024-03-12 06:44 UTC, Majkl-J requested changes
Spawns should be limited to `/area/station` subtypes

2024-04-06 05:27 UTC, ynot01 commented
to be completed at a later date

2024-04-06 05:27 UTC, closed without merging