Gives Revolution Heads Makeshift Weapons (Including Promoted Heads)
yogstation13/Yogstation pull request #15603
Opened 2022-09-04 01:01 UTC by VaelophisNyx

# Document the changes in your pull request

![RF_Logo](https://user-images.githubusercontent.com/1534478/188292687-701f3282-d8af-4ce6-88e2-caf6e5230290.png)
Viva La Revolution!

HeadRevs are granted Makeshift Weapons crafting knowledge.
this applies to promotion as well.

# Wiki Documentation

Will require a mention on the Revolutionary page

# Changelog

:cl:  
tweak: HeadRevs now get makeshift weapon crafting
/:cl:

2022-09-04 02:41 UTC, TheRyeGuyWhoWillNowDie commented
REV EMAG REV EMAG

2022-09-04 04:18 UTC, RG4ORDR commented
The gentle laborer shall no longer suffer from the noxious greed of Mr. Krabs! We will dismantle oppression board by board! We'll saw the foundation of big business in half, even if it takes an eternity! With your support, we will send the hammer of the people's will crashing through the windows of Mr. Krabs' house of servitude!

2022-09-04 04:26 UTC, NCRLouTenant commented
So I had been thinking about ways for a pacifist Rev Head to work and them handing out makeshift weapons is definitely a fun gimmick for it. Good PR!

2022-09-10 18:38 UTC, TheGamerdk commented on code/modules/antagonists/revolution/revolution.dm
> +	var/obj/item/book/granter/crafting_recipe/weapons/W = new
redundant since you have on_gain?

2022-09-10 18:38 UTC, TheGamerdk requested changes

2022-09-10 18:38 UTC, TheGamerdk commented on code/modules/antagonists/revolution/revolution.dm
> +	W.on_reading_finished(owner.current)
see above

2022-09-10 19:26 UTC, TheGamerdk approved these changes

2022-09-10 19:28 UTC, merged