Locks the warden's krav maga gloves to security-related areas.
yogstation13/Yogstation pull request #15649
Opened 2022-09-06 19:29 UTC by TheRyeGuyWhoWillNowDie

Warden's krav maga gloves are currently the ultimate powergamer item, because with them you can instantly, undisarmably melee stun somebody and then spam quickchoke on them to kill them with essentially no counterplay. Krav maga is intended to be used for unruly prisoners, not to run out of the brig, gamer stun somebody, and then KO them in ~20 seconds with quickchoke spam. This should help with wardens running out of the brig to arrest people, because wardens won't want to lose their martial art. The range that krav maga retains is very generous, including all of the brig and prison wing, the HoS's office, the courtroom, and the gulag. This should also help warden players since the krav maga gloves will be a much less desirable powergamer item, so it won't get stolen from the warden's locker in the case of latejoiner wardens.

# Changelog

:cl:  
tweak: warden's krav maga gloves are now restricted to security related areas
/:cl:

2022-09-06 19:29 UTC, redmoogle commented
what do you mean I cant beat the living hell out of my soon to be prisoners?!!

2022-09-06 19:43 UTC, TheRyeGuyWhoWillNowDie commented
why did turdis break

2022-09-06 19:52 UTC, redmoogle requested changes
This is why

2022-09-06 19:52 UTC, redmoogle commented on code/datums/martial/krav_maga.dm
> +/obj/item/clothing/gloves/krav_maga/sec/equipped(mob/user, slot)
```suggestion
/obj/item/clothing/gloves/krav_maga/sec/equipped(mob/user, slot)
	. = ..()
```

2022-09-06 19:52 UTC, redmoogle commented on code/datums/martial/krav_maga.dm
> +/obj/item/clothing/gloves/krav_maga/sec/dropped(mob/user, slot)
```suggestion
/obj/item/clothing/gloves/krav_maga/sec/dropped(mob/user, slot)
	. = ..()
```

2022-09-06 19:55 UTC, TheRyeGuyWhoWillNowDie commented
holy jesus how did i get merge conflicts in the fucking changelog

2022-09-06 21:16 UTC, boodaliboo commented
> holy jesus how did i get merge conflicts in the fucking changelog

emag to allow its old feature back

2022-09-06 23:59 UTC, TheRyeGuyWhoWillNowDie commented
> > holy jesus how did i get merge conflicts in the fucking changelog
> 
> emag to allow its old feature back

how about you buy a martial art instead (traitor) or use the weapons that you spawn with the ability to craft (BB) instead of relying on instastun crutches

2022-09-07 04:51 UTC, SuperSlayer0 commented
Blessed PR

2022-09-07 13:45 UTC, Skrem7 commented
Will combat gloves plus still function with this PR

2022-09-07 17:54 UTC, SuperSlayer0 commented
> Will combat gloves plus still function with this PR

From what I saw in the code - yes

2022-09-07 18:03 UTC, TheRyeGuyWhoWillNowDie commented
> Will combat gloves plus still function with this PR

Combat Gloves Plus and any other method of obtaining krav maga are not affected. ONLY the warden's krav maga gloves.

2022-09-17 11:32 UTC, JamieD1 approved these changes

2022-09-17 11:32 UTC, merged