The Ballistics Expansion
yogstation13/Yogstation pull request #15675
Opened 2022-09-08 04:41 UTC by Skrem7

# Document the changes in your pull request

For the sake of conciseness, and because it would take a literal essay to explain these changes, I'm just going to list what's done. This also actually utilizes all the shit done in #14486

- Adds LWT-650 DMR to the NT uplink for 10 WC. It fires .308.
- .308 magazines standardize to 15 bullets and do 42 damage with -40 wound bonus. They have no wound_drop_tile value. An additional magazine costs 2 WC.
- .308 Penetrator acts as DU slugs, penetrating through all mobs. It does 38 damage with 30 AP. Costs 4 WC.
- .308 Heavy Laser fires a heavy laser, of the same projectile as the Solaris, I believe (40 damage, ignite, good wound chance). Can also recharge like a laser rifle magazine. Costs 7 WC.
- Sprites and sounds for the LWT-650 DMR and all of its ammunition have been added
- Adds 5.56 AP, which does 31 damage with 40 AP. It costs 6 TC/WC.
- Adds 5.56 Incendiary, which 23 damage with 2 fire stacks. It costs the standard 4 TC/WC.
- Adds 5.56 Rubber, which does 10/45 damage/stamina. It costs the standard 4 WC.
- 5.56 toploader magazines have progressive sprites
- Makes it so M-90gl and NT ARG use different magazine types and adds respective sprites for the differing magazines and their alternative ammunitions
- As a statement, the main difference between .45 and 10mm is that .45 has a -10 wound bonus. 10mm has none.
- Adds .45 AP, which does 27 damage with 40 AP. Cost is 4 TC for nukies.
- Adds .45 HP, which does 45 damage with -45 AP. It is also SHARP_EDGED, possessing a -20 wound bonus with a +10 bare_wound_bonus. 10mm HP has also received the SHARP_EDGED, though its wound/bare bonuses are -10/+10. Cost for the .45 variant is the standard 3 TC for nukies.
- Adds .45 Venom, which does 20 damage while injecting 8 units of venom to carbon targets hit. Cost is 4 TC for nukies.
- Adds new sprites for all these .45 variants
- Adds 10mm EMP which does 20 damage and a one-tile EMP. A single mag costs 1 TC. Adds its sprites too.
- Re-introduces Frag-12 rounds for the Bulldog. They do 25 damage on hit, no longer paralyze, but emit a light explosion at a radius of 2. They cost 3 TC for nukies.
- HP Buckshot has been removed. In its place is Syndicate buckshot, which deals 18 damage per pellet with 2/2 wound/bare bonuses, as opposed to the new 12 damage per pellet with 5/5 of new standard buckshot, up from 11 damage per pellet. Any 12g magazine unless otherwise stated costs 2 TC, as before.
- Rubber shot now deals 14.5 stamina damage per pellet instead of 13.
- Flechette has had its wound chance brought up overall, it also possesses less value falloff from range. It costs 3 TC.
- DU slugs now deal 26 damage from 30, but wound bonus has been increased slightly
- Cryo shot temperature adjustment now ignores armor
- Improv slugs, assuming they hit at range, will suck less
- .32 TRAC implant only lasts 3 minutes now, down from 15
- EMPs now remove tracking implants
- Caldwell Revolver and its ammo can no longer be researched and printed
- Removes TRAC speedloaders from Tracking Implant crate
- Adds new Tracking Revolver crate for 4000 which contains 1 Caldwell and 2 speedloaders for it
- Magazines that go into rechargers such as the laser rifle's now charge faster if the recharger is upgraded
- Occupying Force WT no longer has a contradicting description nor a unique name, just spawns with rubber rounds. This means the item could be used as a roundstart armory WT, if so desired in a future PR.
- .357 and .50ae fire delays have been doubled to 8 and 10 respectively. Special .357 revolvers remain unaffected. Nagant revolver retains 4 fire_delay. Caldwell now has a fire_delay of 12. All others have a fire_delay of 0.
- .38 reinforcement now make the fire_delay 12 (as opposed to 8 of standard .357), but no longer has a chance to blow up in your hand
- .357 Metalshock now properly does a tesla arc, instead of doing an internal shock and confusion
- .357 Wallstake now costs 3 TC
- Adjusts code to be shorter and include inherits all around regarding ammunition, including spriting code which means several redundant sprites have been removed
- Bulldog has had its gun sprite reworked, now gives a visual indicator of ammo left rather than a snowflake color if you load an alternative mag
- Pre-existing bulldog alternative magazines that lacked sprites now have them
- Adds new load, unload, rack, and fire sounds to accompany the LWT-650 DMR. All but the fire sound could potentially be utilized for other rifles.
- Every single ballistic magazine name and description has received a passover to make sure a specific examine actually existed. Several names and descriptions overall relating to guns have been adjusted, including WT-550 Rifle -> WT-550 Carbine, M-90gl Carbine -> M-90gl Rifle, and Surplus Rifle -> Surplus Carbine

# Spriting
New LWT-650 with mag:
![image](https://user-images.githubusercontent.com/98909416/189034091-d1391b5f-c62c-471d-b252-84f8ba5c160b.png)

New bulldog progressive sprites:
Capacity = 100% -> 61%
![image](https://user-images.githubusercontent.com/98909416/189034301-2f24219c-e202-4e0b-8c06-af31aabf0ad8.png)
Capacity = 60% -> 21%
![image](https://user-images.githubusercontent.com/98909416/189034401-feee448b-b109-4016-ad82-096386e10a0c.png)
Capacity = 20% -> 1%
![image](https://user-images.githubusercontent.com/98909416/189034443-e3389eb4-1edb-42ee-b7a8-b9777a6d1455.png)
Capacity = 0% (The light is blinking)
![image](https://user-images.githubusercontent.com/98909416/189034510-160fb833-1f4d-4a30-b8cd-01f071e5ee6c.png)

10mm EMP:
![image](https://user-images.githubusercontent.com/98909416/189034567-77dcf59b-0eee-4063-9fe4-9bef5b8808e6.png)

.45 AP:
![image](https://user-images.githubusercontent.com/98909416/189034591-9def7222-df8a-4a2a-84c9-7e2c846da779.png)

.45 HP:
![image](https://user-images.githubusercontent.com/98909416/189034617-4c580b11-3caf-45d6-aa26-b07ccfa34ee5.png)

.45 Venom:
![image](https://user-images.githubusercontent.com/98909416/189034640-57ef1504-ff65-4b4c-afeb-9eb7f0d68ca7.png)

5.56 Casing: 
![image](https://user-images.githubusercontent.com/98909416/189035043-a30a2d5b-3cf5-4d19-9b93-31f24dce273b.png)

5.56 (Toploader) AP:
![image](https://user-images.githubusercontent.com/98909416/189034761-4d8ec01e-f565-4659-a899-cc5396584bc6.png)

5.56 AP Casing: 
![image](https://user-images.githubusercontent.com/98909416/189035064-7fc51079-17c0-4890-b866-b707d7130ab1.png)

5.56 (Toploader) Incend:
![image](https://user-images.githubusercontent.com/98909416/189034791-a5979f45-e2d2-48e0-8f62-c6dd6e7cde68.png)

5.56 Incend Casing: 
![image](https://user-images.githubusercontent.com/98909416/189035093-901179fb-1a81-4601-be0e-b8c5741cf366.png)

5.56 (ARG) Standard:
![image](https://user-images.githubusercontent.com/98909416/189034828-30cfcaf1-2a7f-446f-bc4b-90edbea34347.png)

5.56 (ARG) AP: 
![image](https://user-images.githubusercontent.com/98909416/189034979-42c004cf-d412-46b4-bfda-91b7a6a829f3.png)

5.56 (ARG) Incend:
![image](https://user-images.githubusercontent.com/98909416/189034997-b60ce126-9935-43e3-a966-1ea452f2df2a.png)

5.56 (ARG) Rubber:
![image](https://user-images.githubusercontent.com/98909416/189035013-958082f7-67fb-4217-a48b-900e532507de.png)

5.56 Rubber Casing: 
![image](https://user-images.githubusercontent.com/98909416/189035102-ebdc1353-8b7b-4aac-927e-3ee93d55483c.png)

.308 Standard: 
![image](https://user-images.githubusercontent.com/98909416/189035126-7e990faa-c92d-4516-9fa6-1edfe2d1488c.png)

.308 Penetrator: 
![image](https://user-images.githubusercontent.com/98909416/189035155-745431f4-ddd2-44b7-a761-815fe7d5b6f5.png)

.308 Penetrator Casing: 
![image](https://user-images.githubusercontent.com/98909416/189035173-b465e662-ec57-415e-b808-411b2ab89d13.png)

.308 Heavy Laser (Red lines flash when empty): 
![image](https://user-images.githubusercontent.com/98909416/189035187-98f851c5-0090-4b6c-ac0b-7c9b005bae55.png)

.308 Heavy Laser Casing: 
![image](https://user-images.githubusercont [...]

2022-09-09 01:53 UTC, KillerOrcaCora requested changes, later dismissed
Remove sprites from this PR for a review into smaller digestible sizes based on gun+ammo.

2022-09-09 04:03 UTC, cuackles commented
> Remove sprites from this PR for a review into smaller digestible sizes based on gun+ammo.

is is illogical, the sprites are needed to add the new items, removing them would just delay everything, the sprites are displayed correctly and by my review they are all acceptable, ammo sprites are correctly designated and each one of them is recognizable, gun sprites are acceptable though i find a bit odd that the LWT which is a CC gun is red, but if i consider it a big issue i will fix it in the future, but apart from that, they are good, same for inhand sprites, adding to that your sprites are in this pr so you shouldn't  be approving or denying it in any case, anyway sprites good so it gets art approval and I'm dismissing orcas change request cus it aint making much sense

2022-09-09 04:03 UTC, cuackles approved these changes

2022-09-10 23:09 UTC, Marmio64 commented
way too much stuff for a single PR, mostly i dont like EMPs being even more stupidly easy for traitors to use by giving them ammo to EMP people in one shot without need for an EMP nade that takes time to pin and can also disable your own equipment if you brought any.

2022-09-10 23:20 UTC, Skrem7 commented
> way too much stuff for a single PR, mostly i dont like EMPs being even more stupidly easy for traitors to use by giving them ammo to EMP people in one shot without need for an EMP nade that takes time to pin and can also disable your own equipment if you brought any.

![image](https://user-images.githubusercontent.com/98909416/189504941-0c86d0ee-5527-4aa5-81a8-e3fa6d89f82f.png)
Yes, this is melee but this is re-usable, metashielded, camouflaged, instant, and silent.

2022-09-10 23:22 UTC, Mqiib commented
> way too much stuff for a single PR, mostly i dont like EMPs being even more stupidly easy for traitors to use by giving them ammo to EMP people in one shot without need for an EMP nade that takes time to pin and can also disable your own equipment if you brought any.

There is literally no way to give them "easier" EMPs, they get an implant that can be activated while stunned with a massive AOE for 2 tc PLUS a box of EMP grenades. It's not a big deal.

2022-09-17 11:37 UTC, JamieD1 commented
Jesus christ.

2022-09-17 14:51 UTC, Skrem7 commented
> Jesus christ.

If you desperately want me to I could split it into the following PRs, but merging one after the other is going to cause a shitton of conflicts and I wouldn't be happy doing it, but I also understand trying to maintain and review a PR of this size is absolute misery. If it's of any gracious aid, most of these changes I was actively in a voice call with Mqiib going over and testing.

1) Add the LWT-650 and its respective ammo/sounds/images, also make 7.76 slightly faster
2) Alternative 5.56 and its new sprites for the Boarder, too
2.1 or 3) Alternative .45 and its new sprites
4) Revolver passovers (basically firerate, .357 ammos, and .38 modified)
5) Shotgun ammo and sprite passovers, including its speed
6) TRAC nerf/adjustment
7) All-around description, name, or whatever additions/tweaks
8) WT incend AP
9) Surplus rifle fire rate up

2022-09-17 22:40 UTC, Mqiib commented
Can confirm, most of these changes were run by me, they SHOULD be okay unless anyone sees anything particularly egregious. only thing I'm a little concerned about is the balance of the 650 since it has really high damage but it shouldn't be too much of a problem, probably.

2022-09-23 15:33 UTC, Skrem7 commented on code/modules/projectiles/boxes_magazines/external/smg.dm
> +	desc = "A 24-round magazine for the C-20r SMG that contains AP .45 rounds. \
```suggestion
	desc = "A 24-round magazine for the C-20r SMG that contains HP .45 rounds. \
```

2022-09-23 15:34 UTC, Skrem7 commented on code/modules/projectiles/boxes_magazines/external/smg.dm
> +	desc = "A 24-round magazine for the C-20r SMG that contains AP .45 rounds. \
```suggestion
	desc = "A 24-round magazine for the C-20r SMG that contains Venom .45 rounds. \
```

2022-10-01 11:34 UTC, JamieD1 approved these changes

2022-10-01 11:37 UTC, merged