[PORT] Adds in Alligators from Shiptest and adds in a Gator Crate
yogstation13/Yogstation pull request #15770
Opened 2022-09-15 05:56 UTC by GraveHat

Snapping turtles.

# Document the changes in your pull request

Adds in alligators from Shiptest, as well as the "pets" and the iguana found in shiptest-ss13/Shiptest#747. Also adds in a gator crate that can be bought for 3000 credits after the supply console has been emagged. Also adds Alligators to the fishing loot pool.
![image](https://user-images.githubusercontent.com/107460718/190322572-3c6618a6-da5b-4f57-b2d3-7585d7538d8c.png)

The gators have been adjusted to randomly decide to eat you like the goats and also drop 4 lizard meat and 1 lizard tail. They can be spawned as hostile mobs from gold extracts however their pet versions cannot.

# Spriting

![image](https://user-images.githubusercontent.com/107460718/190323978-8823cf7d-b5c7-4cc6-a887-e3cb37832ee6.png)
![image](https://user-images.githubusercontent.com/107460718/190323994-eb22a7b7-acba-4eb1-b9de-914fe6a85768.png)

![image](https://user-images.githubusercontent.com/107460718/190324018-6a2870f6-aff3-40a5-b7e8-4ab818a84cb2.png)
![image](https://user-images.githubusercontent.com/107460718/190324030-29cdf6e7-8f59-43a2-b68d-39abcb998e42.png)

# Wiki Documentation

Alligators Exist

# Changelog Gravehat, @swifterjack

:cl:  
rscadd: Adds alligators to the game
rscadd: Adds alligators to the fishing loot pool as a rare drop
tweak: Alligators behave like goats and drop loot on butcher, can be spawned through gold slimes
imageadd: Adds gator sprites
/:cl:

2022-09-15 21:22 UTC, RG4ORDR commented
gator hat gator hat gator hat gator hat gator hat gator hat gator hat gator hat gator hat gator hat gator hat

2022-09-17 13:55 UTC, JamieD1 commented
Why are there two different sizes in your pictures

2022-09-17 13:59 UTC, cuackles approved these changes

2022-09-17 21:44 UTC, GraveHat commented
> Why are there two different sizes in your pictures

I used a fugu gland so we can see the sprites better.

2022-09-30 16:46 UTC, Bibby0110 requested changes

2022-09-30 16:46 UTC, TheGamerdk commented on code/modules/mob/living/simple_animal/friendly/gator.dm
> +/mob/living/simple_animal/hostile/retaliate/gator/steppy
remove the duplicate declarations

2022-09-30 16:46 UTC, TheGamerdk commented on code/modules/mob/living/simple_animal/friendly/gator.dm
> +/mob/living/simple_animal/hostile/retaliate/gator/steppy/iguana
here too

2022-09-30 21:15 UTC, ToasterBiome requested changes, later dismissed
loot conflicts with https://github.com/yogstation13/Yogstation/pull/15486 can be added there instead

2022-09-30 21:15 UTC, TheGamerdk approved these changes

2022-09-30 21:16 UTC, merged