REVERT #12677; Emergency Spare ID Can Be Used For ID Modification Again
yogstation13/Yogstation pull request #15780
Opened 2022-09-16 04:54 UTC by VaelophisNyx

# Document the changes in your pull request

Reverts https://github.com/yogstation13/Yogstation/pull/12677

The amount of times I or another Head has been locked out of ID modification when there are NO OTHER HEADS, and is NO CAPTAIN, not a dead captain, **NO** captain, but it's just high enough pop to prevent skeleton crew access, and/or the true spare is already stolen, is infuriating.

The comms console already requires you to have a head's ID authorized at minimum to print it, and not be a silicon. This step was one too far and cripples acting captain function.

# Changelog

:cl:  
tweak: You may once again use the emergency spare to give yourself AA
/:cl:

2022-09-16 05:04 UTC, VaelophisNyx commented
going to look into maybe tying this to there being no captain on crew manifest

2022-09-16 11:06 UTC, warface1234455 commented
pog

2022-09-17 13:59 UTC, JamieD1 commented
No, this makes it way too easy. Also maybe the Staff shouldnt lose the spare.

2022-09-17 17:14 UTC, VaelophisNyx commented
>the staff shouldnt lose the spare
Jamie I joined the round, the spare was gone, and there was no sign of who had it. Atop that as CMO I had no way to get it back safely, and there was no security officers to deal with it
This change has made lowpop abysmal for when a traitor just instantly rushes the spare

2022-09-17 17:26 UTC, VaelophisNyx commented
all-in-all your command staff should NEVER have their hands tied because they dared...to be late by like 2 minutes. I spent the entire round that caused this barraged by requests for ID changes, by calls for help, that I could not answer because despite being acting captain, I had no access, and no way to get that access. I also couldn't secure the damned disk.

2022-09-30 16:47 UTC, TheGamerdk requested changes
See what Jamie said

2022-09-30 20:58 UTC, VaelophisNyx commented
Jamie is wrong.

2022-09-30 20:59 UTC, VaelophisNyx commented
like the issue isnt even "just dont lose the spare" it was "I joined and the spare had already been stolen in the first minute of the game because it was lowpop so noone was around to stop them or care", thus permanently barring the only head from actually doing their job

2022-10-01 11:41 UTC, JamieD1 commented
> like the issue isnt even "just dont lose the spare" it was "I joined and the spare had already been stolen in the first minute of the game because it was lowpop so noone was around to stop them or care", thus permanently barring the only head from actually doing their job

I dont follow, if you join as CMO you should have plenty of access to be CMO, if the traitor has stolen the spare already, obviously its to prevent people like yourself getting the access to stop them. Please explain how this is not intended.

2022-10-01 15:38 UTC, VaelophisNyx commented
> > like the issue isnt even "just dont lose the spare" it was "I joined and the spare had already been stolen in the first minute of the game because it was lowpop so noone was around to stop them or care", thus permanently barring the only head from actually doing their job
> 
> I dont follow, if you join as CMO you should have plenty of access to be CMO, if the traitor has stolen the spare already, obviously its to prevent people like yourself getting the access to stop them. Please explain how this is not intended.

because when there are no other heads, and no sec, you as the solo head are expected to fill in for just about everyone. Failure to do so for things as simple as even securing the nuke disk is a problem, and being barred from it because some asshole BB bumrushed the spare before there was anyone on station to do anything about it is infuriating. This revert solves a lot of painful situations that occur when there aren't other round-start heads, which is a very frequent occurrence of late.

Couldn't do HOP duties if needed (they were)
Couldn't get access to other departments to do paramedic duties (was needed)
Couldn't get access to security if I had actually been able to figure out which fucker stole the spare
Couldn't secure the nuke disk (a greytiding scientist gave it to me later in the round)

If you are the ONLY head you should not have your hands tied by poor coding decisions

2022-10-08 13:33 UTC, JamieD1 commented
> Reference in new

But we added this feature to begin with, when this was not a thing this situation happened, why do you want to make it easier when you are using an unintended feature and now are saying its required and crucial for rounds.

2022-10-08 18:03 UTC, VaelophisNyx commented
Because it is expected of you as a head to do stuff like secure the disk
there's a transitional population where skeleton crew does not get set, so a head could be locked out of the captain's office, unable to secure the disk, when there's no captain or hop. This is a **frequent** occurrence lately. And in some cases even is occurring in higher pops as head players are rare.
The ID-mod lock on the emergency spare makes no goddamn sense and again, *ALREADY REQUIRES A HEAD'S ID TO PRINT ONE*
If an antag kills a head and prints the spare, whoopie they did it, let them have their reward.
If a head needs more access for an *emergency situation* then let them have it
stop tying player agency's hands up

2022-10-08 18:35 UTC, GraveHat commented
The purpose of this pr is to make it so that during low population, a joining head isn't completely screwed when one of the crew decides it is time for them to be the acting captain, but surprise, surprise, the acting captain was the antagonist of the round, and now you are locked out of doing what is expected of you by the rest of the crew. 

The problem this solves is making the joining head have some form of making the round more interesting because, during low-pop, it is a requirement for them as the only head to be the acting captain. 

Even though this overshoots the purpose of the Emergency Spare ID back when it first got added, I think that roles like the CMO and the RD should have all access during these types of rounds without the need for hacking. 

Even if this does give any antagonist the ability to gain AA without the need for killing AC, Actual Captain, and HoP as they could just lock the bridge, print a spare, then give them access through the captain's office that way like how any other head with that sort of access can do but would also report their position and original intent to the whole station in the first place.

2022-10-20 20:02 UTC, Bibby0110 commented
The original intent was not for this to be a way to give yourself AA.
This isn't the correct solution for low-pop, figure something else out. (Pop-locking the limit is the most simple (and worst?))

2022-10-20 20:02 UTC, closed without merging