cream, cilk and, soymilk now work to heal skeletons better
yogstation13/Yogstation pull request #15802
Opened 2022-09-17 06:08 UTC by boodaliboo

these reagents arent subtypes of milk so they didnt apply to skeletons calcium healing

:cl:  
rscadd: Added more milky reagents to calcium healing
/:cl:

2022-09-17 06:16 UTC, Cartlord commented
make cilk fucking kill them

2022-09-17 07:00 UTC, boodaliboo commented
> make cilk fucking kill them

i can do that if others think thats a good idea

2022-09-17 14:01 UTC, JamieD1 commented
Remove Cilk and Bilk and any fucking derivative of milk for snowflakes. I'll give you £5.

2022-09-17 14:30 UTC, boodaliboo commented
> Remove Cilk and Bilk and any fucking derivative of milk for snowflakes. I'll give you £5.
will you actually pay me

2022-09-30 17:00 UTC, TheGamerdk requested changes
do it for all 3

2022-09-30 17:00 UTC, TheGamerdk commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +		if(M.getBruteLoss() && prob(20))
move the getBruteLoss to the outside if

2022-09-30 17:00 UTC, TheGamerdk commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +		. = 1
Use TRUE/FALSE

2022-09-30 17:00 UTC, TheGamerdk commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +		M.heal_bodypart_damage(1.5,0, 0)
```suggestion
		M.heal_bodypart_damage(1.5)
```

2022-09-30 17:00 UTC, TheGamerdk commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	..()
return ..()  || .

2022-10-01 11:45 UTC, JamieD1 commented
> > Remove Cilk and Bilk and any fucking derivative of milk for snowflakes. I'll give you £5.
> > will you actually pay me

Yes.

2022-10-03 06:26 UTC, VaelophisNyx commented
beer milk should stick around since its the closest we can get to an actual mix drink used for frat-party hazing, which we **cant** use the name of

2022-10-20 20:02 UTC, Bibby0110 commented
Stale, reopen when changes completed.

2022-10-20 20:02 UTC, closed without merging