makes snakes milkable for venom
yogstation13/Yogstation pull request #15803
Opened 2022-09-17 07:24 UTC by boodaliboo

gives snakes a cool reason to be bought
:cl:  
rscadd: Added milking snakes for venom
/:cl:

2022-09-17 07:25 UTC, TheGamerdk commented
We’re not milking snakes

2022-09-17 07:26 UTC, ToasterBiome commented
maybe we can have a little snake milking?

2022-09-17 07:27 UTC, boodaliboo commented
> maybe we can have a little snake milking?

i can milk it a different chemical

2022-09-17 07:28 UTC, TheGamerdk requested changes
Reflavor to extracting

2022-09-17 07:41 UTC, boodaliboo commented
> Reflavor to extracting



> Reflavor to extracting
but you can milk snakes

2022-09-17 10:33 UTC, TheGamerdk commented
> > Reflavor to extracting
> 
> > Reflavor to extracting
> > but you can milk snakes

The professional terminology is “extracting venom” so that’s the one we’ll be using

2022-09-17 14:02 UTC, JamieD1 commented
Do not call it milking. Jesus christ man.

2022-09-17 14:22 UTC, Marmio64 commented
ive heard it called milking before a lot

2022-09-17 19:45 UTC, VaelophisNyx commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +	description = "A potent poison gotten from milking a snakes venom."
"A potent venom extracted from a live snake."

2022-09-18 02:09 UTC, boodaliboo commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +	description = "A potent poison gotten from milking a snakes venom."
fine

2022-09-18 18:46 UTC, boodaliboo commented
its extracting now

2022-09-30 17:00 UTC, Bibby0110 requested changes
Make custom text output for the udder, since we're extracting and not milking.

2022-10-20 20:03 UTC, Bibby0110 commented
Stale + conflicts. Reopen when ready to merge

2022-10-20 20:03 UTC, closed without merging