Reworks the poor aim quirk and all sources of poor aim to be able to stack
yogstation13/Yogstation pull request #15847
Opened 2022-09-19 04:44 UTC by Moltijoe

As the title says, before they all just piggy backed off applying and removing the poor aim quirk
Now there's a species variable that can be increased and decreased,
this allows for:
Species with innate poor aim
Variable amounts of poor aim (rather than just 25 from all sources)
Stacking poor aim

This is an indirect buff to flying fang which applied a poor aim debuff as this allows it to affect people with the poor aim quirk
It could also allow for future adjustment to the strength of the flying fang poor aim

:cl:  
bugfix: sources of spread increase stack
/:cl:

2022-09-30 17:20 UTC, TheGamerdk commented on code/modules/clothing/head/helmet.dm
> +	if(ishuman(user) && S == SLOT_HANDS)
helmet in your hands?

2022-09-30 17:20 UTC, TheGamerdk commented on code/modules/clothing/head/helmet.dm
> +		to_chat(world, H.dna.species.aiminginaccuracy)
...

2022-09-30 17:21 UTC, TheGamerdk requested changes
..

2022-09-30 21:45 UTC, Moltijoe commented on code/modules/clothing/head/helmet.dm
> +		to_chat(world, H.dna.species.aiminginaccuracy)
oopsie

2022-10-01 11:50 UTC, JamieD1 approved these changes

2022-10-01 11:50 UTC, merged