EMT berets
yogstation13/Yogstation pull request #15863
Opened 2022-09-19 23:02 UTC by SapphicOverload

# Document the changes in your pull request

Adds EMT berets, plus green and mining medic variants. Also gives mining medic beret and cap a little bit of armor to match their jacket.

# Spriting

![emt_berets](https://user-images.githubusercontent.com/93578146/191133681-39403561-3bbd-4f70-bf89-cdd745be5984.png)
![emt_berets_items](https://user-images.githubusercontent.com/93578146/191133687-00884d64-100d-419c-8457-093ad3e0151c.png)

# Changelog

:cl:  
rscadd: adds EMT and mining medic berets
tweak: gives mining medic hat the same protections as their jacket
/:cl:

2022-09-19 23:06 UTC, KillerOrcaCora approved these changes
now make it the strongest armour piece lie true beret fashion

2022-09-30 17:29 UTC, TheGamerdk commented on yogstation/code/modules/clothing/head/jobs.dm
> +	armor = list(melee = 10, bullet = 10, laser = 0,energy = 0, bomb = 0, bio = 50, rad = 0, fire = 50, acid = 50)
```suggestion
	armor = list(MELEE= 10, BULLET= 10, LASER = 0,ENERGY= 0, BOMB= 0, BIO= 50, RAD= 0, FIRE= 50, ACID= 50)
```

2022-09-30 17:29 UTC, TheGamerdk requested changes

2022-09-30 17:29 UTC, TheGamerdk commented on yogstation/code/modules/clothing/head/jobs.dm
> +	armor = list(melee = 10, bullet = 10, laser = 0,energy = 0, bomb = 0, bio = 50, rad = 0, fire = 50, acid = 50)
```suggestion
	armor = list(MELEE= 10, BULLET= 10, LASER = 0,ENERGY= 0, BOMB= 0, BIO= 50, RAD= 0, FIRE= 50, ACID= 50)
```

2022-10-01 11:53 UTC, JamieD1 approved these changes

2022-10-01 11:53 UTC, merged