Leg implants
yogstation13/Yogstation pull request #15864
Opened 2022-09-19 23:14 UTC by Moltijoe

Adds leg implants
Lets you do organ manipulation on the legs

Adds two type of leg implants:
Water slip immunity
Complete slip immunity

Neither are currently obtainable

Ones to make:
Maglock implant
Clown shoes squeak implant
other walk sound implants?
Table climb speed implant?
Movement speed implant?

:cl:  
rscadd: Added leg implants
/:cl:

2022-09-19 23:16 UTC, Moggram commented
Rocket jump implants when?

2022-09-20 15:47 UTC, Moltijoe commented
Done with this PR, will probably make more implants down the road though

2022-09-21 04:18 UTC, VaelophisNyx commented
total slip immunity would make for a good traitor implant briefcase; ~8tc for total slip immunity?

2022-09-21 15:01 UTC, Moltijoe commented
> total slip immunity would make for a good traitor implant briefcase; ~8tc for total slip immunity?

I considered it, but couldn't think of any good number for balancing since it seems like it could either be super op, or far less useful than it seems

2022-09-30 17:31 UTC, TheGamerdk requested changes
e

2022-09-30 17:31 UTC, TheGamerdk commented on code/modules/mob/living/carbon/human/human_movement.dm
> +		return 0
TRUE/FALSE

2022-09-30 17:31 UTC, TheGamerdk commented on code/modules/surgery/organs/augments_legs.dm
> +		return TRUE
```suggestion
		return .
```

2022-09-30 17:31 UTC, TheGamerdk commented on code/modules/surgery/organs/augments_legs.dm
> +/obj/item/organ/cyberimp/leg/Remove(mob/living/carbon/M, special = 0)
unneeded

2022-09-30 17:31 UTC, TheGamerdk commented on code/modules/surgery/organs/augments_legs.dm
> +	..()
```suggestion
	. = ..()
```

2022-09-30 17:31 UTC, TheGamerdk commented on code/modules/surgery/organs/augments_legs.dm
> +// /obj/item/organ/cyberimp/leg/clown
remove this if youre keeping it commented

2022-09-30 22:43 UTC, KillerOrcaCora approved these changes

2022-10-01 11:55 UTC, JamieD1 commented
Kinda feels a bit op

2022-10-01 14:08 UTC, Skrem7 commented
> Kinda feels a bit op

I think it would be more fitting if you had to double-up on the same type, one for each leg, otherwise, it doesn't work. Not seeing anything like that at the moment. Magboot implant is 100% fine, it's the no-slips that are a bit more questionable, but there's already plenty of researched implants and organs to make things like thermal goggles or the CNS autosurgeon redundant. Certainly on the scarier side with the no-slips, but it could probably be surveyed for a while, make sure Sec isn't using it to too much of an advantage.

2022-10-01 19:01 UTC, Moltijoe commented
> Kinda feels a bit op

Aside from what skrem said, i cant really think of anything to make them less op. The requiring doubles thing will definitely take some time to get working.

Having maglocking without needing the boots seems rather niche in use. I will agree i did think the nowaterslip was a bit more powerful so i locked it behind combat implants just like antidrop is, which it seemed a side grade to.

2022-10-01 20:06 UTC, Skrem7 commented
> The requiring doubles thing will definitely take some time to get working.

Not too much of an issue in my opinion. I can do it later if I have to. Just consider how awkward it might be for preterni if they get one magboot implant per leg and get two action buttons (though I'm pretty sure that's not how it works).

> Having maglocking without needing the boots seems rather niche in use. I will agree i did think the nowaterslip was a bit more powerful so i locked it behind combat implants just like antidrop is, which it seemed a side grade to. 

Completely agree here. It feels good to get upgraded. Augmentation has its place in the game and EMPs are a solid counter to it. This just expands the list of options.

2022-10-01 21:05 UTC, Moltijoe commented
> 
> Not too much of an issue in my opinion. I can do it later if I have to. Just consider how awkward it might be for preterni if they get one magboot implant per leg and get two action buttons (though I'm pretty sure that's not how it works).
> 
 
I can always just update the preternis code to be nicer instead if these implants dont get in. Also id probably just have it grant the ability once there is two of the same implant in both legs, and remove it when even one gets removed

2022-10-01 22:31 UTC, Moltijoe commented
Might re-open this in the future, definitely needs more work before it's worth putting in

2022-10-01 22:31 UTC, closed without merging