Adds Microplastics
yogstation13/Yogstation pull request #15880
Opened 2022-09-21 05:45 UTC by VaelophisNyx

# Document the changes in your pull request

Adds Microplastics, a reagent acquired by grinding plastic sheets
it's a very, painfully, slow to metabolize reagent, that causes extremely weak organ damage.

# Wiki Documentation

Would be required to add it to the Guide to Chemistry
Exact damage values are absurdly low, taking between 12 and 15 minutes to be fatal

# Changelog

:cl:  
rscadd: Added Microplastics
/:cl:

2022-09-21 05:47 UTC, Cartlord commented
lame-ass "joke" p.r., people will forget this exists in a month because we've cultivated a playerbase that doesn't care about anything but gimmicks & powergame and this can't be implemented into a good gimmick or used to win a fight

2022-09-21 05:48 UTC, VaelophisNyx commented
this is...not a joke? Like....what says Joke to you about this

2022-09-21 05:48 UTC, Cartlord commented
The utter uselessness of the chemical, plus I've been seeing way more people posting about microplastics over the last few weeks - I assumed this was just part of that _weird_ trend.

2022-09-21 05:49 UTC, VaelophisNyx commented
yeah no its unrelated to that, lol

but it's still useful, it's a raw organ damage chem for a broad sweep of organs
sure it's slow, but it's effective since so many people miss the early organ damage notifications

2022-09-21 06:52 UTC, yacabo commented
Why is this good for the game?

2022-09-21 07:00 UTC, 00ze-cyclone commented
Make it a toxin since its only purpose is poisoning people.

2022-09-21 07:48 UTC, VaelophisNyx commented
> Make it a toxin since its only purpose is poisoning people.

problem was as a toxin it absolutely fucking body-slams your liver and it makes it INFINITELY more deadly than intended.

2022-09-21 07:48 UTC, VaelophisNyx commented
> Why is this good for the game?

because funny
also slow organ-only poison good

2022-09-21 10:40 UTC, N3D6 commented
Wow people love complaining about nothing. This is funny and a good pr

2022-09-21 12:11 UTC, CMOisLing commented
> Wow people love complaining about nothing. This is funny and a good pr

Double standard

2022-09-21 14:22 UTC, N3D6 commented
> > Wow people love complaining about nothing. This is funny and a good pr
> 
> Double standard

Bro mad because I didn’t like his nerf of a balanced donator species

2022-09-21 15:38 UTC, CMOisLing commented
> > > Wow people love complaining about nothing. This is funny and a good pr
> > 
> > 
> > Double standard
> 
> nerf

2022-09-21 15:42 UTC, CMOisLing commented
> > > Wow people love complaining about nothing. This is funny and a good pr
> > 
> > 
> > Double standard
> 
> Bro mad because I didn’t like his nerf of a balanced donator species

Will felinid players ever recover?

2022-09-21 15:59 UTC, Addust commented
i can see great potential in this, like get a syringe gun and a buncha syringes full of good ol' microplastics and boom, 25 minutes in organ transplants are going on stationwide

2022-09-21 16:49 UTC, Moggram commented
This can be used for new PR chem recipes. (or drinks) I don't get all the dislike for this PR.

2022-09-22 01:03 UTC, SomeguyManperson commented
> This can be used for new PR chem recipes. (or drinks) I don't get all the dislike for this PR.

"can be" has a tendency to mean "added then nobody does anything with it because it's a one-off meme pr"

2022-09-22 01:54 UTC, VaelophisNyx commented
in this case it was not meant to be a meme. Microplastics are a real present danger IRL and it'd be reasonable that they should be game to. Even if for nothing other than a grinding result for plastic sheets

2022-09-22 01:55 UTC, VaelophisNyx commented
and yeah this can be built on in the future

2022-09-25 02:30 UTC, Cartlord commented
On further thought, this seems like it's best suited as a food-poisoning chemical, and I like that  - we don't have many things that you could feasibly put in food without getting bwoinked for fucking up people's rounds or outright murderbone, but the killing potential of this is low enough that that's not really a concern.

2022-10-05 07:29 UTC, VaelophisNyx commented
if this gets closed for being bloat I'mma just stop making new stuff since it'd clear that despite there being a general desire for new stuff, there isn't actually a want for it.

2022-10-08 13:41 UTC, JamieD1 approved these changes

2022-10-08 13:42 UTC, JamieD1 commented
Says conflicts.. dont see conflicts..?

2022-10-08 17:59 UTC, VaelophisNyx commented
> Says conflicts.. dont see conflicts..?

chemical conflicts with the adrenaline nerf

2022-10-08 19:11 UTC, Rdrazga commented
If I just did my math right this will kill you in less then 5 minutes, cause traumas long before that, and be deadly at extremely low unit counts.

2022-10-08 19:12 UTC, Rdrazga commented
Granted this depends on how many chem ticks there are a second/minute

2022-10-08 19:13 UTC, Rdrazga commented
But for what is essentially an invisible killer that is very easy to make, this seems excessively deadly especially to the brain

2022-10-08 19:28 UTC, VaelophisNyx commented
PR mentions time to kill based on actual in-game testing
Your math sounds wrong; possible you forgot the mild organ healing you get for being alive? Trust me tho, this stuff is incredibly non-lethal unless you just ignore it entirely

2022-10-08 19:33 UTC, TheGamerdk requested changes

2022-10-08 19:33 UTC, TheGamerdk commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	metabolization_rate = 0.05
```suggestion
	metabolization_rate = 0.05 * REAGENTS_METABOLISM
```
might have to adjust your math

2022-10-08 19:41 UTC, VaelophisNyx commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	metabolization_rate = 0.05
Doesn't that work out to just...One?

2022-10-10 23:52 UTC, Sniblet commented
I believe taste_description = "nothing" tells the player "You can taste nothing" which only really makes sense when they're drinking Nothing

2022-10-11 01:11 UTC, VaelophisNyx commented
well the idea was if you ingest it at like, the kitchen with dosed food, you aren't IMMEDIATELY told you just ate a slow organ poison. Also unsure if I could even use Null there

2022-10-11 07:13 UTC, Sniblet commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	taste_description = "nothing"
taste_mult = 0

2022-10-15 22:16 UTC, VaelophisNyx commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	taste_description = "nothing"
hmm, forgot about that

2022-10-20 20:04 UTC, TheGamerdk approved these changes
dumb

2022-10-20 20:04 UTC, merged