(probably a really bad idea) ipcs can now be emagged to give them a random ion law
yogstation13/Yogstation pull request #15904
Opened 2022-09-23 22:17 UTC by TheRyeGuyWhoWillNowDie

ipcs now get a random ion law (reskinned hypnosis trauma) when emagged. the trauma is absolute, so it can't normally be removed. it picks from the AI ion law pool for laws, so any ion laws an AI can get an IPC can get. emagging somebody like this also knocks them asleep for 10 seconds so you have time to get away and they can't start instantly attacking you, although i'm iffy on it and it can be removed if needed

# Changelog

:cl:  
rscadd: emagging an ipc will now give them a random ion law 🙂
/:cl:

2022-09-23 23:13 UTC, Xoxeyos commented
Make it so you can't emag yourself, please.

2022-09-24 03:19 UTC, boodaliboo commented
yes

2022-09-27 11:33 UTC, TheGamerdk commented
i hate this code

2022-10-04 15:20 UTC, bruhlookatthisdood commented
maybe using an ai reset board on them (either via brain surgery(do ipcs have brain surgery?) or just using the board on them and waiting for an amount of time before the board is fully uploaded and the ion law is removed?)

2022-10-12 11:12 UTC, TheGamerdk requested changes

2022-10-12 11:12 UTC, TheGamerdk commented on code/datums/brain_damage/hypnosis.dm
> +/datum/brain_trauma/hypnosis/ipc/New()
```suggestion
/datum/brain_trauma/hypnosis/ipc/New(phrase)
		. = ..(generate_ion_law())
```

2022-10-12 11:12 UTC, TheGamerdk commented on code/datums/brain_damage/hypnosis.dm
> +	if(!phrase && !istype(src, /datum/brain_trauma/hypnosis/ipc))
remove all of this

2022-10-12 11:12 UTC, TheGamerdk commented on code/datums/brain_damage/hypnosis.dm
> +	if(istype(src, /datum/brain_trauma/hypnosis/ipc))
make a new proc and call that for all the text + flavor, then override it for the IPC trauma

2022-10-19 20:53 UTC, TheRyeGuyWhoWillNowDie commented
No

2022-10-19 20:53 UTC, closed without merging