Adds New 10x10 Maint Ruin: The Wizard Supply Closet
yogstation13/Yogstation pull request #15922
Opened 2022-09-25 02:57 UTC by VaelophisNyx

# Document the changes in your pull request

![ss (2022-09-24 at 09 53 04)](https://user-images.githubusercontent.com/1534478/192126152-dbda9204-9437-493a-b8dc-0653b57abdc1.png)

Adds a new 10x10 ruin themed around wizards, providing:
1. Wizard Action Figure
2. Gloves of Hugging
3. 3x Donk Pocket Box Spawners
4. Microwave
5. Red Wizard Clothes + Staff + Yalp Enor Mask
6. Greentext Book (Quiet)
7. Wizard Bedsheet
8. Dice Bag
9. Triple-Random-Book spawner

# Wiki Documentation

There is currently no mention of maint-ruins on the wiki, however, mayhap we should add a tab on the Ruins page?

# Changelog

:cl:  
rscadd: Added new 10x10 Wizard-Themed Maint Ruin
/:cl:

2022-09-25 02:59 UTC, GraveHat commented
Are those indestructible walls?

2022-09-25 02:59 UTC, VaelophisNyx commented
Nay

2022-09-25 18:44 UTC, ToasterBiome commented
are those windows correct

2022-09-25 18:55 UTC, VaelophisNyx commented
they're not spawners, but if I wanted them green, I can't *use* a spawner. So they're manually placed grilles and windows, so I could set the color flag on them.

2022-09-26 20:57 UTC, ToasterBiome approved these changes

2022-09-26 20:57 UTC, ToasterBiome requested changes

2022-09-26 20:57 UTC, ToasterBiome commented on yogstation/code/datums/ruins/station.dm
> +	id= "wizard"
```suggestion
	id = "wizard"
```

2022-09-27 19:43 UTC, ToasterBiome approved these changes

2022-09-27 19:43 UTC, merged