removes printable bags of holding, instead the RD gets one as a grand theft item
yogstation13/Yogstation pull request #15957
Opened 2022-09-29 02:54 UTC by TheRyeGuyWhoWillNowDie

Removes BoH from the techweb. RD gets one instead, as a grand theft objective.

Why?
Bags of holding completely neutralize any storage woes you can ever have. Combat shotguns, which are designed to be unwieldy boomsticks capable of outputting massive power? Have 5 of them in your backpack lol. Hardsuits, which are supposed to be a bulky, sluggish suit that you bring when you want to go into space? Have it with you at all times, just in case. Items that are intentionally designed to be bulky, like stunprod? Carry 10 of them for all I care, nobody will ever know.

This issue is compounded by the fact that scientists love to rush them for infinite storage space, causing powergamers to break into the science lab or AI OPEN the windoor and print bags of holding for themselves. They're not expensive, they're not rare, they're fucking everywhere and they need to die. 

Also our coders have an issue where they go "I refuse to balance around bags of holding!" despite them being so commonplace, this is like refusing to balance around fucking upgraded parts which is ridiculous but this is a solution that doesn't require breaking even more of everything

# Changelog

:cl:  
rscadd: the research director's locker now contains a bag of holding, and the bag of holding is a grand theft item
rscdel: bags of holding can no longer be printed
/:cl:

2022-09-29 03:18 UTC, warface1234455 commented
Maybe make it craftable thar requires any anomaly core, 5bs crystals, 10 diamond, any bag

2022-09-29 03:47 UTC, VaelophisNyx commented
good pr

2022-09-29 04:12 UTC, Moltijoe commented
Just taking it away from people is bound to make a lot of people annoyed. If you also added some other alternative storage upgrade i'm sure there'd at least be a chance this would get in.

2022-09-29 04:14 UTC, VaelophisNyx commented
honestly better bags that cant hold LARGER items would be kinda sick

2022-09-29 04:27 UTC, Cartlord commented
This would require at least one other change, that being Miners no longer having so much shit they're expected to carry around (scanner, tank, accelerator, cutter, plunger, satchel, shovel, landing field designator, G.P.S. unit, mining charge, medipen, plant bag) - I understand that one Miner isn't expected to take all of them, and that they're meant to be spread around the team (e.g. one guy having a plunger & designator, second guy having plant bag, third having shovel), but nobody does that - you end up with two people carrying nothing non-essential and one guy with everything in his backpack.
And no, I'm not joking about the plunger - you get them from autolathes, and their _only use_ is to activate Lavaland geysers.

2022-09-29 04:45 UTC, Hopekz commented
I do not think this PR is good for game direction and in my opinion should be closed without a compromise being made.

In my opinion even making a compromise that goes closer to this game direction would be a real yogdev moment.

2022-09-29 04:46 UTC, VaelophisNyx commented
why is it bad, Hopek

2022-09-29 04:47 UTC, Hopekz commented
> why is it bad, Hopek

I think it is bad because all the reasons listed for this change are the exact reasons why this item exists in the first place.

These aren't oversights or exploits they are intentional reasons why the bag of holding was added to ss13 in the first place.

2022-09-29 04:49 UTC, VaelophisNyx commented
yes well, the direction has changed. The listed reasons are valid concerns

2022-09-29 04:54 UTC, Hopekz commented
> yes well, the direction has changed. The listed reasons are valid concerns

That is fine.
I'm only here to drop my opinion and I understand that we do not hold the same opinion on game direction.

Both your view and mine aren't wrong we just want the codebase to be in a different place at the end (:

2022-09-29 14:15 UTC, Majkl-J commented
> This would be best with at least one other change, that being a culling of Miner item bloat (scanner, tank, accelerator, cutter, plunger, satchel, shovel, landing field designator, G.P.S. unit, mining charge, medipen, plant bag) - I understand that one Miner isn't expected to take all of them, and that they're meant to be spread around the team (e.g. one guy having a plunger & designator, second guy having plant bag, third having shovel), but nobody does that - you end up with two people carrying nothing non-essential and one guy with everything in his backpack. And no, I'm not joking about the plunger - you get them from autolathes, and their _only use_ is to activate Lavaland geysers.

This. The only people who actively search out BoHs are miners and some science personnel (Usually the xenobiologists for obvious reasons). If the bloat was to be cut for the miners, I think they would not care about this change. Xenobiologists can live without it.
Alternatively, give the RD his own lathe/something (Like the warden's, who gets the armory one), limiting the BoH to a secure location. Cutting it directly to one exclusive feels too harsh

2022-09-29 23:36 UTC, Sniblet commented
I don't use bags of holding so this is good :)
Except as a miner so cartlord is right :0
Lavaland has so much cool loot and the miners need to carry so many small to normal-sized items anyway, nevermind if they can't put a hierophant club in their backpack, they can't even carry enough stimpens half the time

But yeah having 12 shotguns in your bag is cheating and I never liked that it was possible

2022-09-29 23:38 UTC, Hopekz commented
> I don't use bags of holding so this is good :)

"This doesn't apply to me so let's change it for everyone else"

2022-09-30 07:23 UTC, prisoner12349 commented
This is just removing another fun thing to have from the game. Like, its FUN to be able to throw a hardsuit in your backpack. Its FUN to just go eh, fuck it, and shove the armory in your backpack. Make it cost more mats? Sure do that. But just making it a "RD only, go steal it" is kinda bs. 

Are we just nerfing/removing everything?

2022-09-30 18:01 UTC, TheRyeGuyWhoWillNowDie commented
> This is just removing another fun thing from the game. Like, its FUN to be able to throw a hardsuit in your backpack. Its FUN to just go eh, fuck it, and shove the armory in your backpack. Make it cost more mats? Sure do that. But just making it a "RD only, go steal it" is kinda bs.
> 
> Are we just nerfing/removing everything?

as a coder, i can confirm that i hate fun and am specifically removing all of the fun from the game

2022-09-30 19:24 UTC, prisoner12349 commented
> as a coder, i can confirm that i hate fun and am specifically removing all of the fun from the game

I knew it!

2022-09-30 20:48 UTC, TheRyeGuyWhoWillNowDie commented
> Just taking it away from people is bound to make a lot of people annoyed. If you also added some other alternative storage upgrade i'm sure there'd at least be a chance this would get in.

duffel bag

2022-09-30 22:29 UTC, Lichton commented
> > This would be best with at least one other change, that being a culling of Miner item bloat (scanner, tank, accelerator, cutter, plunger, satchel, shovel, landing field designator, G.P.S. unit, mining charge, medipen, plant bag) - I understand that one Miner isn't expected to take all of them, and that they're meant to be spread around the team (e.g. one guy having a plunger & designator, second guy having plant bag, third having shovel), but nobody does that - you end up with two people carrying nothing non-essential and one guy with everything in his backpack. And no, I'm not joking about the plunger - you get them from autolathes, and their _only use_ is to activate Lavaland geysers.
> 
> This. The only people who actively search out BoHs are miners and some science personnel (Usually the xenobiologists for obvious reasons). If the bloat was to be cut for the miners, I think they would not care about this change. Xenobiologists can live without the boh.
> 
> Alternatively, give the RD his own lathe/something (Like the warden's, who gets the armory one), limiting the BoH to a secure location. Cutting it directly to one exclusive feels too harsh

wrong. Powergamers and antags get this to be able to hold fireaxes and other large unstorable items like shotguns, ion rifles, swords, etc. Security also will sometimes get them for this reason.

2022-10-01 12:18 UTC, JamieD1 requested changes, later dismissed
Make it require anomaly cores.

2022-10-01 12:34 UTC, warface1234455 commented
> Make it require anomaly cores.

yes thats good idea

2022-10-01 14:15 UTC, TheRyeGuyWhoWillNowDie commented
> Make it require anomaly cores.

done

2022-10-01 14:18 UTC, warface1234455 commented
> > Make it require anomaly cores.
> 
> done

you realize bluespace anomaly core is rare as fuck right

2022-10-01 14:22 UTC, Majkl-J commented
> yes thats good idea

Imo it just makes it extremely RnG based, which for a item the miners physically need currently feels a bit too harsh


> wrong. Powergamers and antags get this to be able to hold fireaxes and other large unstorable items like shotguns, ion rifles, swords, etc. Security also will sometimes get them for this reason.

Ok well in my time of maining science the only people who come ringing on my front desk have always been miners, once it was the HoS asking for like 10 of them for his boys due to a active thread. As for the people who dont ask, the issue here is simple: There is only a windoor stopping them. If there was more than that (For example the RD office door) between it's manufacturing location, it would make powergamers and antags easier to spot, same as breaking into the armory isnt the top of stealth.

2022-10-01 14:24 UTC, warface1234455 commented
> > yes thats good idea
> 
> Imo it just makes it extremely RnG based, which for a item the miners physically need currently feels a bit too harsh

Make megafauna drops boh shell then

2022-10-01 14:28 UTC, warface1234455 commented
Also remember to remove the grand theft item thingy

2022-10-01 14:30 UTC, TheRyeGuyWhoWillNowDie commented
> you realize bluespace anomaly core is rare as fuck right make it can use any anomaly to make the shell
 yes i do and that's why its a grand theft item, like how its possible to make more reactive teleport armor with a bluespace anomaly core

2022-10-01 14:32 UTC, warface1234455 commented
> > you realize bluespace anomaly core is rare as fuck right make it can use any anomaly to make the shell
> 
> yes i do and that's why its a grand theft item, like how its possible to make more reactive teleport armor with a bluespace anomaly core

so what if someone able to make one and the sec just arrest them for having the boh

2022-10-01 14:38 UTC, Marmio64 commented
making it require bluespace anomaly core might as well be removing it from being able to be crafted. Needs to be any type of anomaly core so people can still actually get it.

2022-10-01 15:00 UTC, Majkl-J commented
> Make megafauna drops boh shell then
That wont fix the issue because the boh would still rely on anomalies both spawning and being neutered

2022-10-01 15:30 UTC, VaelophisNyx commented
> so what if someone able to make one and the shitsec just arrest them for having the boh as a grand theft item

sucks to suck

2022-10-01 15:49 UTC, Hopekz commented
End of an era until this gets reverted months from now.

This removes other unstated gameplay elements too because now that a second bag is essentially uncraftable BoH bombing was removed.

Not only that bag of holding bombing was balanced around the way it was obtained right now so that whole PR to make it less impactful would probably have to be reverted as well now that it shows up as often as that anomaly core mech that robotics makes (probably once every 1000 shifts)

2022-10-01 17:59 UTC, VaelophisNyx commented
I mean this the nicest way possible

fuck bags of holding

2022-10-02 08:57 UTC, Majkl-J commented
> fuck bags of holding

Someone didnt play miner lately

2022-10-02 18:55 UTC, VaelophisNyx commented
> Someone didnt play miner lately

I have never gotten bags of holding for any reason
They aren't needed.

2022-10-02 20:26 UTC, Hopekz commented
> I have never gotten bags of holding for any reason

"This doesn't apply to me so let's change it for everyone else" part 2

2022-10-02 20:34 UTC, Hopekz commented
Every single person that is for this change except the PR author has unironically admitted to never using bags of holding in their arguments.

The pro removal people don't understand how bags of holding fit in the game because they never interact with the feature.

The clues were there when they brought up unrealistic examples such as putting 10 combat shotguns in their bag when there aren't even ten shotguns on the station at any one time (much less in a single person's backpack)

2022-10-02 22:18 UTC, TheRyeGuyWhoWillNowDie commented
> The clues were there when they brought up unrealistic examples such as putting 10 combat shotguns in their bag when there aren't even ten shotguns on the station at any one time (much less in a single person's backpack)

nobody tell him about cargo

2022-10-02 22:22 UTC, Hopekz commented
> nobody tell him about cargo

These are all theoretical unrealistic examples and nobody actually does this. If you can pull up a single real example using replays within the last year or two I'll fully concede.

2022-10-03 07:14 UTC, Sniblet commented
We say we don’t use bags of holding to prove that we don’t need them
They are only necessary for carrying in your backpack things that are designed to not be carried in backpacks
I don’t care how many shotguns you have, honestly, you never need more than one, two if you’re crazy
It’s just pretty sucky to play against a traitor who has the entire armory (oops, sorry for exaggerating, what I meant was one shotgun) in concealment

2022-10-04 03:09 UTC, Cartlord commented
What if we left them at the same level of accessibility, and didn't change the quantity of items held, but made them only able to hold the same individual items a backpack can, meaning that anything that can't go in a backpack can't go in a B.O.H.?

2022-10-05 17:16 UTC, Maia-J commented
> What if we left them at the same level of accessibility, and didn't change the quantity of items held, but made them only able to hold the same individual items a backpack can, meaning that anything that can't go in a backpack can't go in a B.O.H.? It'd let people deal with item creep, while also reducing the amount of bullshit you can get up to, and indirectly providing a MASSIVE reduction to their capacity by making you unable to keep backpacks in them.

Hmmm I am thinking of this: Lesser bag of holding. Same mat cost as current one, exactly this description and purpose. If that was to exist, I wouldnt care that this PR gets merged.

2022-10-08 13:45 UTC, JamieD1 commented
Should be all anomaly cores not just bluespace as they are rare enough as it is.

2022-10-16 09:56 UTC, TheGamerdk commented on code/game/objects/items/storage/backpack.dm
> +		var/obj/item/assembly/signaler/anomaly/A = I
```suggestion
```

2022-10-16 09:57 UTC, TheGamerdk approved these changes

2022-10-16 10:04 UTC, merged