Gems now orovide their mining points when sold at cargo, and are claimed with the id card rather than mining scanner
yogstation13/Yogstation pull request #15964
Opened 2022-09-29 18:05 UTC by SomeguyManperson

# Document the changes in your pull request

Gems are meant to be sold not scanned then left onnthe ground, to remwdy this i have forced miners to drop the shits off and sell them for their free points

If a gem is shipped as part of a bounty you get 10% bonus points for doing a bounty even though i hate them with a passion

# Wiki Documentation

Gems are now claimed by hitting them with an id, and only provide points to that id when they are sold on the cargo shuttle

# Changelog

:cl:  
tweak: Gems are now claimed by hitting them with an id, and only provide points to that id when they are sold on the cargo shuttle
/:cl:

2022-10-01 08:21 UTC, ToasterBiome approved these changes
i fucksingg hat e uuuuuuuuuuuuuuuuuuu...

2022-10-01 08:21 UTC, ToasterBiome requested changes

2022-10-01 08:21 UTC, ToasterBiome commented on code/game/objects/items/gems.dm
> +	var/obj/item/card/id/claimed_by = FALSE
sus

2022-10-08 00:22 UTC, ToasterBiome approved these changes

2022-10-08 00:22 UTC, merged

2022-11-20 09:33 UTC, Kmla2 commented
#16617