Raises Minimum Pop for Blob, Xenos, Spiders; Removes Blob-Infection (Unused) Dynamic; Adjusts Related Dynamic Enemy Role Requirements & More
yogstation13/Yogstation pull request #15976
Opened 2022-09-30 10:17 UTC by VaelophisNyx

# Document the changes in your pull request

1. Raises minimum pop for Xenos, Spiders, and Blob for dynamic and non-dynamic (Spiders only non-dynamic as I cant locate their dynamic ruleset) to 30 (25 for spiders)
   Xenos, Blob, and Spiders spawning as low as they were on non-dynamic, and dynamic, is a bit....Much? What exactly are...10 players meant to do against Xenos? You just lose. Blob is pretty much the same. Spiders are less of an issue but can still be a problem when you don't have the manpower to take it on.

2. Removes Unused Dynamic Blob Infection
   Removes an unused Blob Infection event spawn from dynamic, because we haven't had blob-infection enabled for years and it should stay dead.

3. Dynamic Xenos and Blob have had their required "enemy players" adjusted so that they need more sec and such at higher pop, and shouldn't spawn at *lower* pops if there is no sec or such. I probably have these numbers backwards so if you know better, say something.

4. Adjusts threat cost of blob and xenos
   Dynamic blob and Xenos cost a lot more to spawn because of how hard they impact a round. These are game enders, they should not be spawning extremely frequently.
   
5. Makes blob and Xenos in dynamic NOT repeat
   Always fun winning against xenos for once....only for A SECOND XENO INFESTATION EVENT TO HAPPEN.
these, again, are ROUND ENDING EVENTS. They should not happen more than once per round without admin intervention

# Changelog

:cl:  
tweak: Xenos, Blob, and Spiders should happen less frequently and cant happen below 30 pop (25 for spiders)
tweak: Dynamic Blob and Xenos no longer can repeat in a round
tweak: Removed unused Blob Infection dynamic ruleset
/:cl:

2022-09-30 10:23 UTC, VaelophisNyx commented
"ided" yeah I dont care though
blob/spiders/xenos shouldn't be happening on lowpop.

2022-09-30 10:23 UTC, VaelophisNyx commented
and lowpop being lowvariety is an issue we can solve later when lowpop isn't being curb stomped by antags meant for stations with serviceable populations of people

2022-09-30 10:48 UTC, 00ze-cyclone commented
Lowpop spiders are probably the least threatening event, half the spiderlings just get immediately crushed and the few remaining spiders can be dealt with by a single secoff/acting cap/random who took a laser gun.
Blob could stay at 30 pop (maybe 35 pop if you really want to make it need more pop). Xenos murder everything and go everywhere, blob somewhat stay where it appeared so you can deal with it more easily than xenos because most pf the station will be still functional enough to help.

More pop for xenos is fine I guess.

2022-09-30 10:51 UTC, Majkl-J commented
> "ided" yeah I dont care though blob/spiders/xenos shouldn't be happening on lowpop.

I mean xenos literally win against 10 people so I get it. But spiders are little squishy bastards a assistant will beat alone

2022-09-30 10:54 UTC, VaelophisNyx commented
people when they forget I made spiders an actual threat because they inject acid or tirizene now-

2022-10-01 12:31 UTC, JamieD1 requested changes, later dismissed
Too much.

2022-10-01 12:31 UTC, JamieD1 commented on code/modules/events/alien_infestation.dm
> +	min_players = 40
```suggestion
	min_players = 30
```

2022-10-01 12:31 UTC, JamieD1 commented on code/modules/events/blob.dm
> +	min_players = 40
```suggestion
	min_players = 30
```

2022-10-01 12:31 UTC, JamieD1 commented on code/modules/events/spider_infestation.dm
> +	min_players = 30
```suggestion
	min_players = 25
```

2022-10-01 12:31 UTC, JamieD1 commented on code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
> +	minimum_players = 40
```suggestion
	minimum_players = 35
```

2022-10-01 15:20 UTC, VaelophisNyx commented
at least it something to stem the tide of Xenos

2022-10-01 22:08 UTC, 00ze-cyclone commented
> people when they forget I made spiders an actual threat because they inject acid or tirizene now-

The acid is nowhere as threatening as the venom they used to inject, even then it’s still a melee only simplemob meaning you can kill it by throwing potted plants at it.

2022-10-08 13:47 UTC, JamieD1 commented
> at least it something to stem the tide of Xenos

You already have unless im missing something, you made required enemies higher and cost higher.

2022-10-08 17:59 UTC, VaelophisNyx commented
ye, was just mentioning that it at least wasn't shot down
I did merge all your suggestions so

2022-10-20 20:06 UTC, TheGamerdk approved these changes

2022-10-20 20:07 UTC, merged