Updates and "modernizes" tactical syndikits
yogstation13/Yogstation pull request #15980
Opened 2022-09-30 17:00 UTC by Skrem7

# Document the changes in your pull request

Passes over the existing Tactical Syndikits to actually comment in their total TC value and maybe adjust those that were too crazy or too worthless.

Comprehensive List of Changes:
- Recon: Unchanged (Cost of ~28 TC)
- Bloodyspai: Has received an EMAG (Cost of ~31 TC)
- Stealth: Has lost syndicate soap and radioactive microlaser (Cost of 32 TC)
- Guns: Has received another .357, two stechkin pistols, two more .357 speedloaders, four 10mm magazines, a syndicate shoulder holster (empty shoulder holster that can hold 4 instead of 3), but has lost EMAG and C4 (Cost of 31 TC)
- Screwed: Unchanged (Cost of 31 TC)
- Murder: Unchanged (Cost of 28 TC)
- Implant: Unchanged (Cost of 28 TC, and you get 10 TC to spend)
- Hacker: Lost thermal goggles, but EMAG is replaced with a **bluespace EMAG** (Lowball cost of ~31 TC)
- Lord Singulo: **Gone.** Didn't have weight anyway, but it remained for whatever reason.
- Sabotage: Unchanged (Cost of ~29 TC)
- Sniper: Has received a .357 revolver and a .357 Heartpiercer speedloader (Cost of 30 TC)
- Metaops: Unchanged (Cost of 30 TC)

Also throws the TC cost onto the Radio Implant in code as a comment because it's not obvious to those who do not seek, not even worth putting on the changelog

# Wiki Documentation

All of the above will have to be updated under the tactical syndikit lists in Syndicate Items page

# Changelog

:cl:  
rscadd: Adds the syndicate shoulder holster, which can hold one additional thing (four guns, FOUR GUNS)
rscdel: Removes leftovers of the Lord Singulo bundle
tweak: Passes over and modernizes most of the Tactical Syndikits
/:cl:

2022-09-30 18:08 UTC, TheGamerdk commented
bluespace emag...

2022-10-01 12:37 UTC, JamieD1 approved these changes

2022-10-01 12:39 UTC, JamieD1 requested changes
Bluespace emag?

2022-10-01 13:15 UTC, Skrem7 commented
> Bluespace emag?

I'll see what else I can stir up for it

2022-10-08 13:49 UTC, JamieD1 approved these changes

2022-10-08 13:49 UTC, merged