Lets you vote for Asteroid; Bumps Asteroid min pop to 40
yogstation13/Yogstation pull request #15989
Opened 2022-09-30 23:10 UTC by VaelophisNyx

# Document the changes in your pull request

Map should be votable; it's a good map and also people liked it

also 25 is too low for a map like Asteroid

# Changelog

:cl:  
tweak: You can now Vote on Asteroid Station above 40 pop
/:cl:

2022-10-01 08:34 UTC, VaelophisNyx commented
should also note that its VERY hard to get feedback and bug reports on maps that basically never see the light of day due to box voters

2022-10-01 12:43 UTC, JamieD1 requested changes

2022-10-01 12:43 UTC, JamieD1 commented on config/maps.txt
> +	minplayers 40
```suggestion
	minplayers 34
```

2022-10-07 23:06 UTC, MenacingManatee commented
:eyes:

2022-10-08 13:50 UTC, JamieD1 approved these changes

2022-10-08 13:50 UTC, merged