Halves default cargo shuttle transit time
yogstation13/Yogstation pull request #16062
Opened 2022-10-05 08:01 UTC by SomeguyManperson

# Document the changes in your pull request

Cargo shuttle taking 2 minutes for a round trip plus loading/unloading/ordering time is a pain in the ass for anyone who wants to get stuff on it. Whether or nit its worth the dramatic tension of not having proper gear for a minute is debatable and im here to bring that debate

# Wiki Documentation

Cargo shuttle transit time default 30 seconds from 1 minute

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
tweak: Cargo shuttle transit time default 30 seconds from 1 minute
/:cl:

2022-10-05 17:58 UTC, TheRyeGuyWhoWillNowDie commented
we should probably make it more clear that express console exists too since it erases the waiting period for ordering stuff except nulls/russian surplus

2022-10-05 23:08 UTC, redmoogle requested changes
update the express supply console description smh

2022-10-06 05:03 UTC, Cartlord commented
I feel like just reminding people the express supply console exists is fine here, since that can act as an upgrade to Cargo if they really don't want to have to wait for their shit

2022-10-08 14:19 UTC, JamieD1 commented
Maybe 45 seconds?

2022-10-16 09:59 UTC, TheGamerdk approved these changes

2022-10-16 09:59 UTC, merged