Updates And Partially Redesigns Free Miner Ship
yogstation13/Yogstation pull request #16070
Opened 2022-10-06 01:42 UTC by VaelophisNyx

# Document the changes in your pull request

Freeminers have had the same stuffy dusty old shitty ship for a long time now. This PR modernizes it, and remodels the internals a lot.

Biggest notable changes:
Freeminers now get an Exosuit fabricator that requires **FREEMINER** access instead of robotics, as well as an R&D computer and circuit imprinter that is only capable of making mech boards; R&D comp has had R&D control stripped.

Hydroponics has been gutted completely and replaced with a proper atmospherics/engineering room
the Engineer spawner has been moved here.

The Cargo, EVA storage, and Mech Bay have all been made Open Plan, and the aielocks in & out of the ship now are actual airlocks with no tiny fans, but proper controllers and vents.

The whole ship now features a functional atmos setup as well, though no fire or air alarms. I can add these if requested.

Floors ship-wide have been largely replaced, and are no longer titanium floors.

Replaced the Ripley wreck with a Clarke wreck. Note, as deconstructing broken map-spawned mechs is not working, this serves as flavor for the moment.

The freeminer ship now features a seed extractor, soil plots, and a garden variant seed vendor, and a nutrivendor; this is in an attempt to preserve their ability to make food, slightly expanding options.

Added Frank, the MoonRat pet.

the bridge now features a crew suit sensors monitor.

![ss (2022-10-05 at 08 35 16)](https://user-images.githubusercontent.com/1534478/194195521-6bd389b2-d31e-444d-96ef-8e49cdd22601.png)

# Changelog

:cl:  
tweak: Massively updates the Freeminer ship
mapping: Massively updates the Freeminer ship
/:cl:

2022-10-06 01:43 UTC, KillerOrcaCora commented
![](https://media.tenor.com/MdFWK2f_vV8AAAAC/pepe-hmmm.gif)

2022-10-06 01:43 UTC, VaelophisNyx commented
that was fast

2022-10-06 01:44 UTC, KillerOrcaCora commented
Part of my job

2022-10-06 01:45 UTC, GraveHat commented
Not so old and dusty now eh?

2022-10-06 01:48 UTC, ToasterBiome requested changes
Off the top of my head

Glass is weird:
![image](https://user-images.githubusercontent.com/5091394/194195927-308286bb-cede-49d1-ae57-19481021a2d4.png)

Weird to have this room have dirt mounds (why not hydro basins anyway):
![image](https://user-images.githubusercontent.com/5091394/194195974-ecb79c9f-fe84-4343-bc51-e051d8119ab0.png)


This room does nothing on a ship with limited space:
![image](https://user-images.githubusercontent.com/5091394/194196018-057f59dc-7fd8-4778-95b1-2ba28a867c69.png)

2022-10-06 01:50 UTC, VaelophisNyx commented
glass was to prevent a weird line of firelocks, but alright

fair

wasnt sure what to do with it; it previously was just "place you throw shit to forget it"

2022-10-06 02:07 UTC, VaelophisNyx commented
changes made

2022-10-06 02:08 UTC, TheRyeGuyWhoWillNowDie commented
> glass was to prevent a weird line of firelocks, but alright

make the airlock 1 tile longer so you can avoid weird firelocks while still having the ship look nice i think

2022-10-09 08:45 UTC, Cartlord commented
The lack of a biogenerator is because Free Miners are expected to actually build one with tech, right?

2022-10-09 19:01 UTC, VaelophisNyx commented
freeminers aren't...technically supposed to use it, but that kinda
also no idea where t shove one that isn't weird
and they're not supposed to be up-to-snuff with Nanotrasen's highest tech space station. They're just random guys with a self-bought ship barely etching out an existence among the asteroids

in theory

2022-10-13 02:45 UTC, ToasterBiome commented
Really dont know what to do about it, weird that botany vendor is outside the room, will have to think on it

2022-10-13 03:24 UTC, VaelophisNyx commented
I could just..make the ship wider
this would have no affect on any map other than maybe Asteroid, where it'd just be half off-zlevel

2022-10-13 03:54 UTC, VaelophisNyx commented
figured it out

2022-10-14 20:54 UTC, ToasterBiome approved these changes
yum

2022-10-20 20:17 UTC, merged