Getting Shocked by Wires/Grilles/Machines Hurts Significantly More
yogstation13/Yogstation pull request #16080
Opened 2022-10-07 00:05 UTC by VaelophisNyx

# Document the changes in your pull request

Causes being shocked by a wire, grille, hacking machines and such, to do MUCH more damage, so its actually a present danger when someone wires a 10Mw engine to the grid, instead of a mild annoyance at worst.

# Changelog

:cl:  
tweak: Shocks from wires, grilles, and machines should be over twice as dangerous now
/:cl:

2022-10-07 00:09 UTC, Sniblet commented
PR: Grief is now 2.3x as damaging

2022-10-07 00:44 UTC, Moltijoe commented
both ipc and preternis have a shock coefficient of 1.75, this is just going to make them get instacritted isnt it?

2022-10-07 00:50 UTC, VaelophisNyx commented
technically yeah, probably will
Use insuls

2022-10-07 01:00 UTC, Moltijoe commented
> technically yeah, probably will Use insuls

bruh

2022-10-07 01:58 UTC, VaelophisNyx commented
> > technically yeah, probably will Use insuls
> 
> bruh
> 
> the dark souls of hacking minigames

keep in mind this should only matter for when atmos wires both engines to the grid

2022-10-07 02:32 UTC, Marmio64 commented
its so easy for borgs and the AI to shock shit i dont think a damage buff for doing it would be good

2022-10-07 02:33 UTC, VaelophisNyx commented
well currently electrified stuff is harmless, like genuinely not a concern. It's a slowdown to hacking at best.

2022-10-07 03:12 UTC, Lichton commented
I'd disagree. It chips a lot of damage off you for a single time, and you can get shocked multiple times from different sources with tons of shocked things, or accidentally walk into it a separate time, or be pushed into it multiple times. Shocks aren't really MEANT to be a mega instakill, and you definitely aren't supposed to have insuls be a requirement just to hack.

2022-10-07 03:22 UTC, Lichton commented
Not even mentioning that APCs and vendors and other shit requiring wirecutters to be used twice. I like the idea, but 2x damage is a bit much, maybe 1.5x~ since this would basically make you require insulated gloves to do any real hacking, which sucks if you need to do it once only and have to go through so much agony to get it done.

2022-10-07 03:26 UTC, VaelophisNyx commented
hacking absolutely should require insuls for safety. that's what they exist for. Wire cutting too.
Current damage taken when hacking or cutting wires anywhere is minimal enough to be ignored. This makes hacking dangerous to try without prior knowledge or proper tools. Even budget insuls work.

2022-10-07 04:10 UTC, TheGamerdk requested changes
Modify get_electrocute_damage instead

2022-10-07 04:11 UTC, VaelophisNyx commented
any particular reason to do it there instead?

2022-10-07 04:12 UTC, TheGamerdk commented
> any particular reason to do it there instead?

It’s the proper way to do it?

2022-10-07 04:50 UTC, VaelophisNyx commented
given that this way worked...idk how its any more proper

2022-10-07 08:19 UTC, 00ze-cyclone commented
What is the current damage and what will it be with that change?

2022-10-07 09:31 UTC, ilikesaying commented
can't wait to see someone suddenly spike to 500 burn damage on crew monitor

2022-10-07 11:50 UTC, TheGamerdk commented
> given that this way worked...idk how its any more proper

Just do it

2022-10-07 16:46 UTC, VaelophisNyx commented
bibby once again refusing to be cordial at all and explain to a newer coder why to do something :|

2022-10-07 16:46 UTC, VaelophisNyx commented
> can't wait to see someone suddenly spike to 500 burn damage on crew monitor

its only ~100 damage to a human.

2022-10-07 16:47 UTC, VaelophisNyx commented
> What is the current damage and what will it be with that change?

current damage is something like 50-70? this is, as mentioned above, about 100 per shock at **3.6Mw** wired to the grid

2022-10-07 16:52 UTC, VaelophisNyx commented
> Just do it

![ss (2022-10-07 at 11 51 49)](https://user-images.githubusercontent.com/1534478/194607511-d80a7c39-d559-4fe1-bc5f-a07af3508e36.png)

I will when you tell me why touching this is any better than just multiplying the value directly?

2022-10-07 18:21 UTC, TheGamerdk commented
> 

1. You multiplied only 1 value out of 2
2. It's the OOP way

2022-10-07 18:50 UTC, VaelophisNyx commented
so looking at it, would that even achieve what this PR is meant to? I want wires/grilles/etc all more dangerous, not...power cells?

2022-10-07 19:50 UTC, ToasterBiome commented
> so looking at it, would that even achieve what this PR is meant to? I want wires/grilles/etc all more dangerous, not...power cells?

Change /datum/powernet/proc/get_electrocute_damage() instead, which is what you want anyway

2022-10-07 19:53 UTC, VaelophisNyx commented
my testing showed that this modification was working, tho...so

2022-10-07 19:54 UTC, ToasterBiome commented
> my testing showed that this modification was working, tho...so

ok then it only shocks when connected the other way, you're still missing half

2022-10-07 22:57 UTC, VaelophisNyx commented
better solution is being worked on

2022-10-07 22:57 UTC, closed without merging

2022-11-03 16:22 UTC, reddsnotdead commented
thank god this was closed