[Asteroid] Fixes stacked intercomms and missing netmin access to secondary AI core
yogstation13/Yogstation pull request #16108
Opened 2022-10-08 22:26 UTC by MenacingManatee

# Changelog

:cl:  
mapping: Adds netmin access to secondary AI core
mapping: Fixes stacked tcomms intercoms
/:cl:

2022-10-08 23:56 UTC, ToasterBiome requested changes
![image](https://user-images.githubusercontent.com/5091394/194731577-2d8fdd30-80ae-426c-9de5-633fa66d412a.png)

Fix this decal while you're at it

2022-10-09 02:50 UTC, MenacingManatee commented
> ![image](https://user-images.githubusercontent.com/5091394/194731577-2d8fdd30-80ae-426c-9de5-633fa66d412a.png)
> 
> Fix this decal while you're at it

fixed!

2022-10-11 04:13 UTC, ToasterBiome approved these changes

2022-10-11 04:13 UTC, ToasterBiome commented
surely this will not break anything

2022-10-11 04:14 UTC, merged