reworking borg combat to be less reliant on 1 click instant kills for both sides
yogstation13/Yogstation pull request #16110
Opened 2022-10-08 23:36 UTC by TheRyeGuyWhoWillNowDie

**Not done by any stretch of the imagination, this is just for feedback while I work on this**

borg combat is currently 1 click wins on both sides which is fucking awful 2011 combat that we got rid of for humans a couple years ago, this changes a bunch of borg stuff to be less binary

Flashes:
Immobilize and blur the cyborg's vision for the same time as old flashes. They can still act. Down from instantly locking them in an inescapable chainstun. Locked borgs are affected the same way they previously were

Lockdown:
Locked down borgs can now move and act instead of being trapped forever, HOWEVER, locked borgs move 4x slower, have 2 of their module slots disabled, and their remaining module breaks at the same damage threshold as the third module on unlocked cyborgs. They can only interact with stuff they're next to, and borgs with guns cannot shoot. This is down from lockdown being an instant inescapable GBJ button

EMPS:
Emps do double damage against borgs (40 on heavy, 20 on light) and their ability to pulse internal wires has been restored as lockdown is no longer a stupid infinite stun. EMPs now only disable the borg's modules (16 seconds heavy like how it was before, jesus christ, 6 seconds light) Down from being an instant kill on hit.

Stun arm:
Now has a 1.2 second cooldown between attacks, and only does 60 stamina damage.

Harm alarm:
Knocks down instead of being a fucking paralyze because ranged stuns are stupid

Hugging module:
Shock hugs now respect insulation when electrocuting people. This is down from it being an instant inescapable chainstun for humans.

# Changelog

:cl:  
tweak: borg combat has been reworked to be a lot less binary
/:cl:

2022-10-08 23:39 UTC, KillerOrcaCora commented
Hope this PR does not undo https://github.com/yogstation13/Yogstation/pull/12614

2022-10-08 23:39 UTC, Sniblet commented
Nerfing lockdowns incentivizes blowing borgs more

2022-10-08 23:45 UTC, KillerOrcaCora commented
"Overall, I don't like that almost all the ways to deal with borgs are getting lesser (its already a problem now where they are at) just over so they can't instant stun me with hacked module and hug module"

Maybe just nerf the 2 things that are doing the 1 click combat for borgs but I think it's fair to say things are pretty fair-wise for borgs when you consider all the literal power, tools, and mechanics they outright ignore.

2022-10-08 23:51 UTC, TheRyeGuyWhoWillNowDie commented
> Nerfing lockdowns incentivizes blowing borgs more

i was on the fence about removing detonating cyborgs with robotics control (excluding master AIs)

2022-10-08 23:54 UTC, TheRyeGuyWhoWillNowDie commented
> Hope this PR does not undo #12614

cyborgs that are completely stunned still can't self detonate (xenos, Kindle, etc) and i made sure to make it so that LOCKED borgs cant do it either

2022-10-09 00:20 UTC, TheRyeGuyWhoWillNowDie commented
> pretty fair-wise for borgs side of the dime when you consider all the literal power, tools, and respawn capability and mechanics they outright ignore.

"its fair to instantly get cucked into an infinite chainstun and killed/emagged because you can remotely open doors" 
yes cyborgs are strong but i am not exclusively nerfing them while keeping in their shitty get clicked once by an item literally anyone can have and you won't know (flashes are fucking everywhere) until it's too late combat scheme, because it's objectively unfun to eat shit because you were helping someone that just so happened to have a hate boner for silicons like everyone who plays this accursed game

2022-10-09 01:21 UTC, KillerOrcaCora commented
That's only one boon from a very long list and these standards for borgs where put in place for a reason.

2022-10-10 01:26 UTC, RG4ORDR commented
I'm 100% in favor of removing any instant-stun weapons or mechanics.

2022-10-10 23:39 UTC, SapphicOverload commented
geniunely good pr, though my biggest issue is that flashes are still an instant hardstun against humans

2022-10-20 20:26 UTC, TheGamerdk requested changes
didnt review all

2022-10-20 20:26 UTC, Bibby0110 commented on code/game/objects/items/robot/robot_items.dm
> +	if(cooldown + 1.2 SECONDS > world.time)
Use cooldown defines

2022-10-20 20:26 UTC, TheGamerdk commented on code/game/machinery/computer/robot.dm
> +				if(R.connected_ai != usr)
redundant as of can_control

2022-10-20 20:26 UTC, TheGamerdk commented on code/game/objects/items/robot/robot_items.dm
> +	cooldown = world.time
see above

2022-10-22 19:38 UTC, Mqiib commented
A lot of my gripes with this have been addressed so i think it might be a good idea to test merge it for a bit just to see how the meta changes around. Also, can't wait to have an excuse to shotgun borgs more because I can't stun them :))))

2022-10-29 13:31 UTC, JamieD1 commented
I honestly dont like it, but ill look at it with a couple people

2022-11-13 11:33 UTC, JamieD1 commented
Not against something like this in the future, but not currently.

2022-11-13 11:33 UTC, closed without merging