Add a new advanced decontamination suit storage unit
yogstation13/Yogstation pull request #16112
Opened 2022-10-09 04:56 UTC by warface1234455

An upgraded version of the normal suit storage unit
# Document the changes in your pull request
Adds a new decontamination unit that can clear mob radiation and clearing contamination (Requires advanced engineering tech), also requires 2 cables, 5 manipulators, 5 lasers.
Suit storage unit can no longer clear mob radiation
Fixes being able to open machine with alt click while panel is open for suit storage unit

# Spriting
![image](https://user-images.githubusercontent.com/89688125/194738528-6c691d78-99b6-4efc-8bd1-5fbb6d5b2386.png)

# Wiki Documentation
Adds a new decontamination unit that can clear mob radiation and clearing contamination (Requires advanced engineering tech), also requires 2 cables, 5 manipulators, 5 lasers.
Suit storage unit can no longer clear mob radiation
Fixes being able to open suit storage unit with alt click while panel is open

# Changelog

:cl:  
rscadd: Added a new decontamination unit that can clear mob radiation and clearing contamination (Requires advanced engineering tech), also requires 2 cables, 5 manipulators, 5 lasers.
rscdel: Suit storage unit can no longer clear mob radiation. 
bugfix: Fixed being able to open machine with alt click while panel is open for suit storage unit
/:cl:

2022-10-09 06:28 UTC, Mqiib commented
Ok but can you still microwave people in them even if it doesn't clear the rads?

2022-10-09 06:41 UTC, warface1234455 commented
> Ok but can you still microwave people in them even if it doesn't clear the rads?

Yes

2022-10-09 08:43 UTC, Cartlord commented
The sprite seems really unfitting.

2022-10-10 07:04 UTC, warface1234455 commented
> The sprite seems really unfitting.

you got better sprite then?

2022-10-12 06:05 UTC, VaelophisNyx commented
I'm curious why we need this & why we need to make normal storage units NOT scrub rads?

2022-10-12 06:23 UTC, warface1234455 commented
> I'm curious why we need this & why we need to make normal storage units NOT scrub rads?

Read the pr smh

2022-10-12 06:55 UTC, warface1234455 commented
> I'm curious why we need this & why we need to make normal storage units NOT scrub rads?

I'm only removing the ability for the normal storage unit to clear mob radiation not the whole contamination clearing, the advanced one instead gets the ability to clear mob radiation

2022-10-22 12:36 UTC, JamieD1 commented
> > I'm curious why we need this & why we need to make normal storage units NOT scrub rads?
> 
> I'm only removing the ability for the normal storage unit to clear mob radiation not the whole contamination clearing, the advanced one instead gets the ability to clear mob radiation

But why? You are inventing the problem for your solution.

2022-10-22 13:36 UTC, warface1234455 commented
> But why? You are inventing the problem for your solution.

The normal suit storage unit tech is insufficient to do the mob radiation clearing, the advanced one is more advanced and well developed so it is capable of doing so

2022-10-22 13:41 UTC, warface1234455 commented
Cornflakes

2022-10-25 16:59 UTC, warface1234455 commented
CORNFLAKE AGAIN

2022-10-28 13:33 UTC, warface1234455 commented
Removed map changes

2022-10-29 13:33 UTC, JamieD1 commented
> > But why? You are inventing the problem for your solution.
> 
> The normal suit storage unit tech is insufficient to do the mob radiation clearing, the advanced one is more advanced and well developed so it is capable of doing so @JamieD1

Yeah but the normal one can scrub radiation right now, and the sprite does look out of place.

2022-10-29 13:53 UTC, warface1234455 commented
> > > But why? You are inventing the problem for your solution.
> > 
> > 
> > The normal suit storage unit tech is insufficient to do the mob radiation clearing, the advanced one is more advanced and well developed so it is capable of doing so @JamieD1
> 
> Yeah but the normal one can scrub radiation right now, and the sprite does look out of place.

Just an upgrade for it @JamieD1, the sprite does be fitting imo, Cuackless finds it the same

2022-10-29 14:12 UTC, cuackles commented
The old 3/4 sprite looked out of place cus it was 3/4, the current one should fit better

2022-10-29 14:24 UTC, cuackles commented
![unknown-35.png](https://user-images.githubusercontent.com/68789204/198836663-d6ee3872-316e-4927-a4b0-452d5d355c8a.png) that's how the new one looks with the new perspective Wich makes it fit more, if you still have an issue with it the coloring could also be changed to a duller boring color so it pops less into view

2022-10-29 14:28 UTC, warface1234455 commented
@JamieD1 ^^^

2022-10-31 12:05 UTC, warface1234455 commented
welp Jamie said it's a different art style and still does look out of place, i will have to remove it now :(

2022-11-07 19:52 UTC, ReddicusDragon requested changes
I dislike some of the design choices here. There is also some other general issues I've noticed, highlighted by comments.

2022-11-07 19:52 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +	var/safeties = FALSE
why are the safeties set to FALSE when it is first built?

2022-11-07 19:52 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +				playsound(src, 'sound/machines/oven/oven_open.ogg', 75, TRUE)
Oven sounds really don't work here I feel

2022-11-07 19:52 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +					say("ERROR: Decontamination process is going over safety limit!!")
This flavor text would probably work best as "ERROR: Decontamination Process Failure" or something "Decontamination is going over safety limit!!" feels... half baked? I guess

2022-11-07 19:52 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +					say("Please wait untill the decontamination process is completed.")
**Typo:** change `untill` to `until`

2022-11-07 19:52 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +		playsound(src, 'sound/machines/oven/oven_close.ogg', 75, TRUE)
Once again, oven sounds feel out of place here.

2022-11-07 19:52 UTC, ReddicusDragon commented on code/modules/research/designs/machine_designs.dm
> +/datum/design/board/decontamination
why is this renamed to `/datum/design/board/decontamination` from `/datum/design/board/crystallizer`?

2022-11-07 19:52 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +			say("The decontamination process is completed, thank you for your patient.")
**Typo:** change `patient` to `patience`

2022-11-07 20:00 UTC, ReddicusDragon commented
> > > But why? You are inventing the problem for your solution.
> > 
> > 
> > The normal suit storage unit tech is insufficient to do the mob radiation clearing, the advanced one is more advanced and well developed so it is capable of doing so @JamieD1
> 
> Yeah but the normal one can scrub radiation right now, and the sprite does look out of place.

This still doesn't scrub radiation from mobs, does it?

2022-11-08 01:39 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +	var/safeties = FALSE
Accidentally left it when i was reverting other shits

2022-11-08 01:40 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +				playsound(src, 'sound/machines/oven/oven_open.ogg', 75, TRUE)
It does

2022-11-08 01:40 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +		playsound(src, 'sound/machines/oven/oven_close.ogg', 75, TRUE)
It does once again

2022-11-08 01:42 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +					say("Please wait untill the decontamination process is completed.")
Ok

2022-11-08 01:42 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +			say("The decontamination process is completed, thank you for your patient.")
Yep

2022-11-08 01:42 UTC, warface1234455 commented
> > > > But why? You are inventing the problem for your solution.
> > > 
> > > 
> > > The normal suit storage unit tech is insufficient to do the mob radiation clearing, the advanced one is more advanced and well developed so it is capable of doing so @JamieD1
> > 
> > 
> > Yeah but the normal one can scrub radiation right now, and the sprite does look out of place.
> 
> This still doesn't scrub radiation from mobs, does it?

Yep

2022-11-08 01:43 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +					say("ERROR: Decontamination process is going over safety limit!!")
How is it a failure when its frying someone

2022-11-08 01:49 UTC, warface1234455 commented on code/modules/research/designs/machine_designs.dm
> +/datum/design/board/decontamination
Thanks for letting me know

2022-11-08 01:51 UTC, KillerOrcaCora commented
I’m a bit confused here can someone help me out, we are removing the ability to scrub rads from the normal one? But there will be a advance one to cover up for it?

2022-11-08 01:52 UTC, warface1234455 commented
> I’m a bit confused here can someone help me out, we are removing the ability to scrub rads from the normal one? But there will be a advance one to cover up for it?

No, its still the same i removed the advanced one because the sprite is unfitting

2022-11-08 01:53 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +				playsound(src, 'sound/machines/oven/oven_open.ogg', 75, TRUE)
It doesn't.

2022-11-08 01:54 UTC, KillerOrcaCora commented
DM me the png of the sprite Jamie and cuackles said was out of place, if you still want to go that route that is and I could make you something better

2022-11-08 01:58 UTC, ReddicusDragon requested changes

2022-11-08 01:58 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +	desc = "An industrial unit made to hold and decontaminate irradiated equipment as well as organic. It comes with a built-in UV cauterization mechanism. A small warning label advises that UV bulb lig
I enjoy this description

2022-11-08 01:58 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +			say("ERROR: PLEASE CONTACT SUPPORT!!")
Recommend 1 exclamation instead of 2

2022-11-08 01:58 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +				playsound(src, 'sound/machines/oven/oven_close.ogg', 75, TRUE)
oven_close and oven_open simply do not work here, though oven sounds work for baking the organic

2022-11-08 01:58 UTC, ReddicusDragon commented on code/game/machinery/suit_storage_unit.dm
> +					say("ERROR: Decontamination process is going over safety limit!!")
"ERROR: Decontamination Process exceeds safety limit" feels more proper, for example.

2022-11-08 02:14 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +				playsound(src, 'sound/machines/oven/oven_close.ogg', 75, TRUE)
Sigh

2022-11-08 02:44 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +	desc = "An industrial unit made to hold and decontaminate irradiated equipment as well as organic. It comes with a built-in UV cauterization mechanism. A small warning label advises that UV bulb lig
Aigh

2022-11-08 02:44 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +			say("ERROR: PLEASE CONTACT SUPPORT!!")
K

2022-11-08 02:45 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +				playsound(src, 'sound/machines/oven/oven_close.ogg', 75, TRUE)
Guh ok ill find a replacement

2022-11-08 06:25 UTC, warface1234455 commented on code/game/machinery/suit_storage_unit.dm
> +					say("ERROR: Decontamination process is going over safety limit!!")
I like this one

2022-11-08 06:36 UTC, warface1234455 commented
> DM me the png of the sprite Jamie and cuackles said was out of place, if you still want to go that route that is and I could make you something better

Drafted untill @KillerOrcaCora makes better sprite

2022-11-08 17:20 UTC, TheGamerdk commented
Can you reopen this when orca makes a better sprite, puts it further up the queue

2022-11-08 17:20 UTC, closed without merging

2022-11-09 00:00 UTC, ShoziOffical commented
ya