Makes vial boxes printable and lets them go in the medical belt
yogstation13/Yogstation pull request #16125
Opened 2022-10-10 04:52 UTC by Moltijoe

With the addition of hyposprays trying to hold all the vials for the chemicals became difficult
it usually just became a matter of using a bluespace beaker and refilling the syringes
This just lets you carry a bunch of filled vials instead of a beaker if you want.

:cl:  
rscadd: Can now print vial boxes after researching them
tweak: Vial box can now go in the medical toolbelt
/:cl:

2022-10-16 06:53 UTC, Cartlord commented
In favor of printing, against making them fit in belts.

2022-10-16 10:34 UTC, Moltijoe commented
> In favor of printing, against making them fit in belts.

Should beakers be removed from belt too? Because thats currently what happens instead of this

2022-10-22 12:54 UTC, JamieD1 commented
Dont like how they can fit in belts, they would not fit.

2022-10-22 20:21 UTC, Moltijoe commented
> Dont like how they can fit in belts, they would not fit.

I thought of the vial boxes having a sort of clip that would latch on to the belt.
The main goal i had was to replace the "just have a beaker of the drugs in your belt".
If youre against the vial box for balancing reasons, i could either reduce its size.

2022-10-23 03:17 UTC, Moltijoe commented
I'm also considering removing beakers from the medical belt, probably only if this PR gets merged though

2022-10-29 13:35 UTC, JamieD1 commented
Make them printable but not able to go in belts, also clip onto the belt with lots of glass, that would be very very awkward weight wise maybe but im not sure to be honest.

2022-10-29 22:34 UTC, Moltijoe commented
> Make them printable but not able to go in belts

okay, easy fix

2022-11-07 20:02 UTC, ReddicusDragon requested changes
Just remove the unused variable or point out where you use it and I'd say you're good to go

2022-11-07 20:02 UTC, ReddicusDragon commented on code/game/objects/items/storage/lockbox.dm
> +	var/registered_name = null
registered_name seems to be an unused variable.

2022-11-08 00:20 UTC, Moltijoe commented on code/game/objects/items/storage/lockbox.dm
> +	var/registered_name = null
ah, right

2022-11-08 00:27 UTC, ReddicusDragon approved these changes

2022-11-08 17:18 UTC, Bibby0110 approved these changes

2022-11-08 17:19 UTC, merged