[Admin] Offer Rename Update 1
yogstation13/Yogstation pull request #16122
Opened 2022-10-09 23:58 UTC by VaelophisNyx

# Document the changes in your pull request

Using a proc built to handle this that went unnoticed

updates your ID now!

you can now back-out of offering a rename!

# Known Issues:
Sadly I cant get it to update your PDA name, however, just cycling your ID out and back in updates it

# Changelog

:cl:  
tweak: Offer Rename admin verb now properly renames someone's ID and employee record, and can be cancelled early
/:cl:

2022-10-12 20:05 UTC, ToasterBiome requested changes
Please fix the known issue

2022-10-12 21:11 UTC, VaelophisNyx commented
I told you, I tried. A lot.
I'm stumped and it's a super easy thing to just tell them to cycle their ID in and out of the PDA

2022-10-22 12:43 UTC, JamieD1 approved these changes

2022-10-22 12:43 UTC, merged

2022-10-22 12:43 UTC, JamieD1 commented
Whoops, @ToasterBiome can you help fix it :D

2022-10-22 19:20 UTC, ToasterBiome commented
> Whoops, @ToasterBiome can you help fix it :D

no