Organs, Implants, and Limbs now check for EMP_PROTECT_SELF
yogstation13/Yogstation pull request #16165
Opened 2022-10-14 00:17 UTC by Moltijoe

Why wasn't it this way from the start?
There was no way to have the body be emp immune without making all items carried emp immune also

:cl:  
tweak: Organs, Implants, and Limbs now check for EMP_PROTECT_SELF
/:cl:

2022-10-16 07:32 UTC, TheGamerdk requested changes
Can you explain to me how changing it from PROTECT_CONTENTS to PROTECT_SELF  changes anything when organs are contents?
In addition do we have any sources of either for mobs?

2022-10-16 07:32 UTC, TheGamerdk approved these changes

2022-10-16 07:35 UTC, TheGamerdk requested changes
I can’t check right now but if organs are stored in contents this is probably going to EMP them without PROTECT_CONTENTS still

2022-10-16 10:37 UTC, Moltijoe commented
> I can’t check right now but if organs are stored in contents this is probably going to EMP them without PROTECT_CONTENTS still

I tested by giving a preternis empproof, im fairly certain their eyes normally get hurt by emps, but i was unaffected.

2022-10-17 08:44 UTC, TheGamerdk approved these changes

2022-10-29 13:53 UTC, merged