(ided) Significantly reduces the weight of the floor cluwne event
yogstation13/Yogstation pull request #16194
Opened 2022-10-18 00:32 UTC by Skrem7

# Document the changes in your pull request

Today I will have my antag round ruined by a funny little trickster

I have seen this deadass almost every single round lately because it has weight 10 (other neat funny events have a weight of like 2). Should still happen every now and then

# Wiki Documentation

Weight will have to be updated on random events page

# Changelog

:cl:  
tweak: Floor cluwne weight to 2 instead of 10
/:cl:

2022-10-18 01:04 UTC, TheRyeGuyWhoWillNowDie commented
just make it so it cant target gamemode objectives (like sac objective on bloodcult) antags or command

2022-10-18 17:59 UTC, 00ze-cyclone commented
> just make it so it cant target gamemode objectives (like sac objective on bloodcult) antags or command

It’s not funny when it happen constantly but I still want it to happen from times to times, random fuckery should happen and you shouldn’t be immune to it because you are captain or the objective of a blood cult.

I prefer the weight being decreased to it being hugboxed.

2022-10-18 19:35 UTC, TheGamerdk requested changes
don’t decrease it that much

2022-10-19 20:50 UTC, Skrem7 commented
> don’t decrease it that much

Is 5 acceptable?

2022-10-19 20:53 UTC, TheGamerdk commented
> > don’t decrease it that much
> 
> Is 5 acceptable?

yes

2022-10-22 13:18 UTC, JamieD1 approved these changes

2022-10-22 13:19 UTC, merged