Make pump up useful
yogstation13/Yogstation pull request #16218
Opened 2022-10-21 17:57 UTC by 00ze-cyclone

# Document the changes in your pull request

Currently Pump up is a completely useless drug that damage you  while providing a resistance against stunbatonsthat is irrelevant now that they do stamina damage. You can find it maintenance rarely to serve no purpose other than denying you something that could be useful or cool.

Now Pump up will give a 0.85 stammod when in your system, letting you take one additional disabler shot so you have another option against the stamina machinegun in an attempt to make a step toward removing the EMP tax (don't worry you will still have to pay it because of everything else existing, just with that you can maybe flee without needing an EMP when the secborg is shooting down the hallway the blue beams of pain).

Since the stun resistancetrait is no longer obtainable withthat PR (and was useless anyway) it has been deleted entirely so it's doesn't stay for millenias to bloat our code.

This also make the maintenance pump up autoinjectors craftable and refillable like epinephrine and atropine.

# Wiki Documentation

Pump up now reduce stamina damage taken by 15% when in your system.
You can craft maintenance pump-up using a pen, a syringe, 15u of pump up and a screwdriver,you can also refill them with a spent injector and 15u of pump up.

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added craftable pump up autoinjectors and refill
tweak: Pump up now reduce stamina damage by 15%
spellcheck: maintenance pump-up
/:cl:

2022-10-21 18:07 UTC, ynot01 requested changes

2022-10-21 18:07 UTC, ynot01 commented on code/datums/components/crafting/recipes.dm
> +	name = "Refill Maintenance Pump_Up"
```suggestion
	name = "Refill Maintenance Pump-Up"
```

2022-10-21 18:07 UTC, ynot01 commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	L.physiology.stamina_mod *= 0.85
```suggestion
	if(istype(L, /mob/living/carbon/human))
		var/mob/living/carbon/human/HM = L
		HM.physiology.stamina_mod *= 0.85
```

2022-10-21 18:07 UTC, ynot01 commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	L.physiology.stamina_mod /= 0.85
```suggestion
	if(istype(L, /mob/living/carbon/human))
		var/mob/living/carbon/human/HM = L
		HM.physiology.stamina_mod /= 0.85
```

2022-10-21 18:07 UTC, ynot01 commented on code/game/objects/items/robot/robot_items.dm
>  			to_chat(M, span_warning("You muscles seize, making you collapse[trait_check ? ", but your body quickly recovers..." : "!"]"))
```suggestion
			to_chat(M, span_warning("You muscles seize, making you collapse!"))
```

2022-10-21 18:07 UTC, ynot01 commented on code/game/objects/items/stunbaton.dm
>  			to_chat(L, span_warning("You muscles seize, making you collapse[trait_check ? ", but your body quickly recovers..." : "!"]"))
```suggestion
			to_chat(L, span_warning("You muscles seize, making you collapse!"))
```

2022-10-29 14:18 UTC, JamieD1 approved these changes

2022-10-29 14:19 UTC, merged