Remove vent clog (scrubber overflow) events from rotation
yogstation13/Yogstation pull request #16221
Opened 2022-10-22 00:09 UTC by ynot01

# Document the changes in your pull request

The performance impact of these scrubbers are wholly unsanitary and I believe they are the reason for a recent crash (43458)

Nanotrasen has since improved their scrubber cleaning systems which somehow get chemicals in them despite being atmos ports

# Changelog

:cl:  
rscdel: Removed vent clog events from rotation
/:cl:

2022-10-22 00:22 UTC, ToasterBiome approved these changes

2022-10-22 00:25 UTC, alexkar598 commented
Remove dont disable

2022-10-22 01:26 UTC, warface1234455 commented
> Remove dont disable

Delete, erase it don't disable

2022-10-22 01:27 UTC, warface1234455 commented
Also the meteor event is also laggy as hell

2022-10-22 01:37 UTC, Cartlord commented
honestly, lag or no lag, i think these suck enough to go anyway - they aren't fun to play around, they just put everyone outside maints on pause for a while and sometimes fuck you up with acid

2022-10-22 01:38 UTC, VaelophisNyx commented
> Also the meteor event is also laggy as hell

meteors however dont have PERSISTENT lag that hangs around >10m post event

2022-10-22 13:40 UTC, JamieD1 commented
How about we just merge the fixes instead rip my tg pr.

2022-11-07 13:27 UTC, ynot01 commented
i trust jamie that this is not the core of the issue

2022-11-28 22:05 UTC, ynot01 commented
this is once again relevant

2022-11-28 22:05 UTC, RG4ORDR commented
Remove it

2022-11-28 22:22 UTC, Simplehorror commented
tg hasn't even fixed this

2022-11-28 22:36 UTC, ynot01 commented
Jamie wants to test the scrubber events when the server gets an upgrade so the code stays until then

2022-11-29 22:27 UTC, TheGamerdk commented
> Jamie wants to test the scrubber events when the server gets an upgrade so the code stays until then

just improve performance

2022-12-02 11:49 UTC, BurgerLUA commented
I'm wondering what the profiler looks like when the scrubber event runs.

2023-01-01 13:10 UTC, JamieD1 requested changes
Wait for all backend changes first before considering this

2023-01-08 21:35 UTC, neeshacark commented
Seems like gus fixed the lag with #17263

2023-01-12 11:04 UTC, closed without merging