Make firing pins actually serve their intended purpose
yogstation13/Yogstation pull request #16236
Opened 2022-10-23 10:16 UTC by 00ze-cyclone

# Document the changes in your pull request

Alternative to #16232

The mindshield firing pin has always been a problem in tha it completely invalidated the purpose of firing pins while being necessary for scci to research beforeany of the good weapons. You a strictly better firing pin and it was always unlocked when you had the possibility to print advanced eguns, xray, decloner, temp gun and hardlight bow

So now mindshield firing pins are obtained by crafting them using a regular pin and an mindshield detector which design replace the mindshield firing pin in the protolathe.
The firing pin section in the protolathe has been removed because there was literally only one item that mattered in it, the pins have been moved to be in the weapon category like attachments.

This mean you get 10 mindshield pins with what's at roundstart in the brig, this limit both expanding the arsenal of the armory and making your guns unuseable against you while not just making all the research weapons that aren't the xray gun or aegun worthless because they are very niche compared to lasers and make pins actually matter.

The price of the firing pin crate also has been increased to 6000 credits andonly contain one box of 5 pins now, making crafting a new gun cost 1200 credits after the ressources of the brig have been depleted. The crate is also sec access now so officers can still get pins for a temp gun if there's no warden or HoS, the real roadblock for obtening the guns as a secoff is access to the armory, not to a crate you can force open easily.

# Wiki Documentation

Mindshield pins can no longer be printed, instead you print a mindshield detector. The design is at the same place as the old mindshield pin in the techweb.
Mindshield pin can now be crafted with a firing pin and a mindshield detector, it's in the weapon category of the crafting menu, no tools required.
Firing pin crate now cost 6000 credits, contain only one box of 5 firing pins and is security access.

# Changelog

:cl:  
rscadd: Added mindshield upgrade for firing pins, the mindshield detector
rscdel: Removed printable mindshield pins, instead you print the mindshield detector
tweak: Firing pin crate cost 6000 credits from 2000, contain only 5 firing pins and require basic security access instead of armory access
/:cl:

2022-10-23 10:50 UTC, Cartlord commented
Firing pins are destroyed when removed, so people still need to print new pins anyway. I'm not sure what this accomplishes.

2022-10-23 10:57 UTC, 00ze-cyclone commented
> Firing pins are destroyed when removed, so people still need to print new pins anyway. I'm not sure what this accomplishes.

There’s 10 firing pins in the brig at roundstart so you can equip 10 guns with mindshield pins, those can be new you printed or those you started with like the shotgun of the warden, the egun of captain and HoS and the X-01. The idea is exactly the same as gunkits, not being able to print 666 guns with just a techfab. Except in that case I use a system we already had for this purpose and make it functional instead of adding bullshit that make every R&D gun beside aegun and xray never been made. You can still print guns, you can still put mindshield pins in your, just not to obscene levels without a trip to cargo.

2022-10-23 12:20 UTC, Cartlord commented
But... you can still print firing pins, and you can print mindshield detectors. How is that any different than being able to print mindshield firing pins?

2022-10-23 12:31 UTC, 00ze-cyclone commented
You can't print regular firing pins, only the test range firing pins that am I not even sure have any use now. You can still obtain mindshield firing pins however right now you have 10 firing pins + the virtually infinite amount of mindshield pin you can print once researched, with that PR you have 10 pins that you can maake into mindshield ones after it's been researched.

Only way to get regular electronic firing pins is cargo.

2022-10-23 13:26 UTC, Marmio64 commented
i believe that mindshield pins discourage antags from just using station equipment to win rather than antag equipment, which is kind of boring and I disagree with it, so i'd like mindshield pins to remain printable directly, without having to be another upgrade for sec that only cargo can grant.

2022-10-23 13:56 UTC, TheRyeGuyWhoWillNowDie commented
> i believe that mindshield pins discourage antags from just using station equipment to win rather than antag equipment, which is kind of boring

maybe the gear security gets for free in an unlimited amount shouldnt be worse than antag gear 🤔

2022-10-23 14:00 UTC, TheRyeGuyWhoWillNowDie commented on code/modules/projectiles/pins.dm
> +	desc = "A small circuit compatible with electronic firing pins to make them check for mindshiel implant in their user."
you forgot a d

2022-11-08 00:38 UTC, ReddicusDragon requested changes

2022-11-08 00:38 UTC, ReddicusDragon commented on code/modules/cargo/packs.dm
> +	name = "Standard Firing Pins Pack"
Switch this back and you'll singlehandedly increase your chances of getting this merged. I disagree with upping the price.

2022-11-26 11:55 UTC, JamieD1 commented
Literally just anti qol

2022-11-26 11:55 UTC, closed without merging