swaps out soulstone tendril loot for a new one called seismic right arm
yogstation13/Yogstation pull request #16247
Opened 2022-10-24 10:28 UTC by LazennG

# Document the changes in your pull request
takes soulshard out of the tendril loot pool and throws it in the dumpster while introducing a new item called seismic arm.
Seismic right arm is a mechanical right arm that gives the user 4 abilities
Lariat:
![dreamseeker_72hlQ1qnKP](https://user-images.githubusercontent.com/58535870/197498105-66112686-8955-409d-a75f-9f7c70088a8d.gif)
Move ahead 5 spaces and deal 50 damage to whatever animal you hit and 10 to people, has a 7 second cooldown.

Mop the floor:
![dreamseeker_dvtCdklNFp](https://user-images.githubusercontent.com/58535870/197500222-ece4cbdc-c450-4c47-9579-f08d0ccdf73c.gif)

Similar to lariat, this move sends the user ahead 5 spaces, but if they connect with an animal they start dealing 20 damage per tile travelled together and the user gets the blood-drunk miner trophy effect to help negate damage because of guaranteed prolonged exposure and because fauna can pile up if they're lined up closely. Dead fauna get gibbed. People hit by this take 4 damage per tile and the user doesn't get the blood drunk effect. The cooldown for this move is also 7 seconds

Suplex:
![dreamseeker_YsTq9JNIgk](https://user-images.githubusercontent.com/58535870/197501226-9411f18b-530c-41f1-af87-ff6447dfc3c3.gif)

This move targets a single target right in front of the user and puts them behind the user. If the target is an animal they'll take 20 damage and if the target is a person they'll take 6. If an animal is right behind the user when the move is used successfully, they'll take 20 damage, and if a person is there they'll take 10. This move also gibs dead animals and has a 3 second cooldown.

Right Hook:
![dreamseeker_2CdJxqZevo](https://user-images.githubusercontent.com/58535870/197502068-3cbbffea-0353-4bf2-bb5c-da59450fd487.gif)
The user channels the ability for 2 seconds to get an inhand item called 'overcharged emitter' which lasts 5 seconds. On hitting a target, the user's right arm is disabled for 15 seconds and none of the abilities of the arm can be used until it's functional. Targets hit will be knocked back 8 spaces. Animals take 100 damage on impact and people take 15. Anybody caught in the flight path of the initial target will also be knocked backwards and take 10 damage. 

'Suplex, 'mop the floor,' and 'right hook' will dig through rocks if the target is sent into them and deal an additional 5 damage per rock.

Like most lavaland bodyparts, the arm needs to be attached surgically unless the user is an IPC, and because it's a mechanical limb it shares the same weaknesses and needs the same upkeep.

# Spriting
Sprite for the arm as an item:
![r_arm_item_seismic](https://user-images.githubusercontent.com/58535870/197496895-b85ac024-6cc8-4000-90f2-61b65f357eea.png)
Sprites for the arm when attached to a moja
![image](https://user-images.githubusercontent.com/58535870/197497130-b88d423f-6d32-4fd9-92fe-80ffbd8a5946.png)
Action button sprites by @thegoldencat413
![image](https://user-images.githubusercontent.com/58535870/197496719-2a5698f6-eb42-4fd0-8b05-05a1a0db2d15.png)
# Wiki Documentation

https://wiki.yogstation.net/wiki/Shaft_Miner#Necropolis_Chest_Loot
under the loot section, replace the soulstone with the seismic right arm. 
For the description, something like: A mechanical right arm that gives the user 4 abilities when surgically attached
-Lariat: The user dashes 5 spaces ahead and hits fauna for 50 damage while hitting people for 10
-Mop the floor: The user dashes 5 spaces ahead and pushes whoever it hits, dealing 20 damage per traveled tile to animals and 4 to people. Dead animals get gibbed by this move
-Suplex: The user slams the target behind them, dealing 20 damage to fauna and 6 to people. If there's somebody in the landing zone, they'll take 20 damage if they're an animal and 10 if they're a person. Dead animals get gibbed by this move 
-Right Hook: The user channels the ability for 2 seconds before getting an item that lasts 5 seconds in their right hand. Hitting somebody with this move sends them flying 8 spaces. Animals take 100 damage on hit and people take 15. If anybody is in the flight path, they get taken along with the original target and take 10 damage.

Mop the floor, suplex, and right hook deal an additional 5 damage for every rock the target hits.

# Changelog

:cl: @LazennG   @thegoldencat413 @ToasterBiome @Chubbygummibear 
rscadd: Added seismic right arm 
rscdel: Removes soulstone from tendril loot pool 
imageadd: added sprites for the arm and its abilities
/:cl:
Big thanks to @thegoldencat413 for extensive testing and feedback, along with the actionbutton sprites, and to baiomu and chubby for code help

2022-10-24 10:59 UTC, thegoldencat413 commented
holy shit... this is the best thing ive ever seen... this cured my cancer... speed merge this now ............

2022-10-24 14:56 UTC, Mqiib commented
This is super cool for two reasons.
1: It's super cool mining loot that looks like it'll be pretty useful against fauna, or at least fun to play with
2: I can steal code from it for my own nefarious plans

2022-10-24 15:12 UTC, Moltijoe commented
Very cool, i appreciate anything that makes being an ipc/preternis miner worthwhile considering the lack of medipens

2022-10-25 22:49 UTC, LazennG commented
![dreamseeker_cyoeHE7r1P](https://user-images.githubusercontent.com/58535870/197893385-c8126c69-b56c-4847-ad96-3ca528c8e577.gif)
Suplex tweaked a bit so it turns targets on their head now, borg damage for lariat, mop, suplex, and righthook is now 12,5,8, and 18 respectively.
Also, now if an animal caught in righthook is sent flying into a solid object and is dead, they explode into gibs.
Damage for people caught in right hook has been tweaked as well. If the target flies into a person, the person takes 10 damage. Borgs would take 11 damage, and animals take 30.
![dreamseeker_7euEpE338m](https://user-images.githubusercontent.com/58535870/197896209-4b9a819c-885f-4950-850e-9226aa36a82d.gif)
![dreamseeker_c3kSCS7DIX](https://user-images.githubusercontent.com/58535870/197896220-5366af31-f0c8-43c4-83d1-6cb933a89a61.gif)
![dreamseeker_GZxBPSPzNx](https://user-images.githubusercontent.com/58535870/197896291-aba8c60d-3141-4f27-8ccd-6ae920f245a3.gif)

2022-10-28 15:33 UTC, warface1234455 commented
NOT AXOLOTLS

2022-10-29 14:36 UTC, JamieD1 approved these changes
Hope all this only works on simple mobs, if it doesnt no way is this being added. Cant be instagibbing humans.

2022-10-29 14:36 UTC, JamieD1 requested changes, later dismissed
Hope all this only works on simple mobs, if it doesnt no way is this being added. Cant be instagibbing humans.

2022-10-30 00:29 UTC, LazennG commented
> Hope all this only works on simple mobs, if it doesnt no way is this being added. Cant be instagibbing humans.

None of the moves gib carbons or borgs and the moves deal largely reduced damage to both like stated before dw

2022-10-30 01:25 UTC, LazennG commented
item sprite for the arm has been updated with one by @cuackles :
![THEHANDO](https://user-images.githubusercontent.com/58535870/198858453-9e6ea8d1-eec1-4b67-86a0-ae883d91b320.png)
![image](https://user-images.githubusercontent.com/58535870/198858429-c07c5a0c-5b9b-4637-9f74-d6d2d2ceaa48.png)
![image](https://user-images.githubusercontent.com/58535870/198858439-999436fc-86aa-48d4-b072-fbcd89d9d744.png)

2022-11-02 05:12 UTC, LazennG commented
> item sprite for the arm has been updated with one by @cuackles : ![THEHANDO](https://user-images.githubusercontent.com/58535870/198858453-9e6ea8d1-eec1-4b67-86a0-ae883d91b320.png) ![image](https://user-images.githubusercontent.com/58535870/198858429-c07c5a0c-5b9b-4637-9f74-d6d2d2ceaa48.png) ![image](https://user-images.githubusercontent.com/58535870/198858439-999436fc-86aa-48d4-b072-fbcd89d9d744.png)

belaying the change for now since it's not vital and i dont want to keep delaying

2022-11-03 14:54 UTC, KillerOrcaCora commented
@JamieD1 can use another review or testmerge, PR never did what was asked to be changed in request

2022-11-04 09:46 UTC, TheGamerdk requested changes
An attempt should probably be made to reduce the amount of copy-paste by making the abilities share a parent

2022-11-04 09:46 UTC, TheGamerdk commented on code/modules/mining/lavaland/seismicarm.dm
> +	var/flightdist = 8
Should probably be a var on the item

2022-11-06 17:51 UTC, cuackles approved these changes
Art

2022-11-07 23:45 UTC, ReddicusDragon commented
I worry about this potentially being powergamey being an antag miner, other than that it's really freaking cool

2022-11-08 16:32 UTC, thegoldencat413 commented
> I worry about this potentially being powergamey being an antag miner, other than that it's really freaking cool

disagree because the highest damage attack is 10 brute, which is less than a toolbox, and that puts all the abilities on a long cooldown. The most spammable attack has a 1 second cooldown and does 6 damage, which is less than a punch deals on average, on a longer cooldown.

EMP weakness is also a massive liability

im super biased though because i think this item is cool as hell

2022-11-08 17:13 UTC, Bibby0110 approved these changes

2022-11-08 17:13 UTC, merged