Hepatectomy
yogstation13/Yogstation pull request #16304
Opened 2022-10-30 03:36 UTC by Moltijoe

It's weird that all the other vital organs (brain, lungs, heart) have a one time surgery to fix them from being fucked.
But when it comes to the liver, replacement is the only option. This fixes that.
Surgery is done in the exact same way as the lobectomy.

:cl:  
rscadd: Adds a new surgery to fix dead livers
/:cl:

2022-11-08 00:30 UTC, ReddicusDragon requested changes
Update that comment then approved

2022-11-08 00:30 UTC, ReddicusDragon commented on code/modules/surgery/hepatectomy.dm
> +//lobectomy, removes the most damaged lung lobe with a 95% base success chance
update comment please

2022-11-08 18:07 UTC, Moltijoe commented on code/modules/surgery/hepatectomy.dm
> +//lobectomy, removes the most damaged lung lobe with a 95% base success chance
no

2022-11-08 18:08 UTC, ReddicusDragon commented on code/modules/surgery/hepatectomy.dm
> +//lobectomy, removes the most damaged lung lobe with a 95% base success chance
Fair

2022-11-08 18:09 UTC, ReddicusDragon approved these changes

2022-11-13 12:00 UTC, JamieD1 approved these changes

2022-11-13 12:00 UTC, merged