Changes the Monochromacy quirk to be worth -2
yogstation13/Yogstation pull request #16322
Opened 2022-10-31 21:45 UTC by Moltijoe

Unlike other neutral quirks, this one actually has a negative gameplay effect, that of putting an annoying filter on the screen
No reason it shouldn't give some points

:cl:  
tweak: Monochromacy is now considered a negative quirk
/:cl:

2022-11-08 00:25 UTC, ReddicusDragon requested changes
I would make it a -1, as the gameplay effect isn't too horribly negative.

2022-11-08 18:09 UTC, Moltijoe commented
> I would make it a -1, as the gameplay effect isn't too horribly negative.

not being able to see colours is a bigger gameplay effect than "being able to drink slightly less" or any of the prosthetic limb quirks

2022-11-08 18:13 UTC, ReddicusDragon commented
> > I would make it a -1, as the gameplay effect isn't too horribly negative.
> 
> not being able to see colours is a bigger gameplay effect than "being able to drink slightly less" or any of the prosthetic limb quirks

I would disagree with the prosthetic limb one. Prosthetic limbs are weaker and harder to repair, especially if the wiring in said prosthetic gets damaged. Prosthetic limbs also stun you if you are hit with an EMP blast. Please provide details on how it would provide a bigger gameplay effect than that.

2022-11-08 18:23 UTC, Moltijoe commented
> I would disagree with the prosthetic limb one. Prosthetic limbs are weaker and harder to repair, especially if the wiring in said prosthetic gets damaged. Prosthetic limbs also stun you if you are hit with an EMP blast. Please provide details on how it would provide a bigger gameplay effect than that.

Assuming [#16114] gets in, which it very much seems like it will, having prosthetic limbs won't be a death sentence to emps anymore. also, i'd argue repairing prosthetics is easier than getting hurt normally, welding tools and wires are everywhere. not to mention that a lot of people with prosthetics usually swap them out round start for proper cyborg ones in robotics, which are significantly more durable than fleshy ones.

perhaps if prosthetics conferred some sort of movespeed or action speed penalty i'd agree with you, but they don't as of yet.

Being unable to tell the colours of things apart is both a constant annoyance, as well as can be detrimental if you need to identify someone at a glance via colour, which is far faster to be recognized by the brain than shapes are.

2022-11-08 18:36 UTC, ReddicusDragon commented
> > I would disagree with the prosthetic limb one. Prosthetic limbs are weaker and harder to repair, especially if the wiring in said prosthetic gets damaged. Prosthetic limbs also stun you if you are hit with an EMP blast. Please provide details on how it would provide a bigger gameplay effect than that.
> 
> Assuming [#16114] gets in, which it very much seems like it will, having prosthetic limbs won't be a death sentence to emps anymore. also, i'd argue repairing prosthetics is easier than getting hurt normally, welding tools and wires are everywhere. not to mention that a lot of people with prosthetics usually swap them out round start for proper cyborg ones in robotics, which are significantly more durable than fleshy ones.
> 
> perhaps if prosthetics conferred some sort of movespeed or action speed penalty i'd agree with you, but they don't as of yet.
> 
> Being unable to tell the colours of things apart is both a constant annoyance, as well as can be detrimental if you need to identify someone at a glance via colour, which is far faster to be recognized by the brain than shapes are.

A constant annoyance is not a more profound effect on gameplay than what I laid out for prosthetics. As for the brain being unable to recognize, that's why we have the examine verb. Not to mention that in the lower left hand of the byond client, character names are displayed. You do, however, raise valid points about prosthetics and how they aren't really a negative as is. On that note, I'm fine with this being a negative two, at least until someone makes prosthetics more of a negative.

2022-11-08 18:37 UTC, ReddicusDragon approved these changes
On account of the argument laid out by Molti, I believe a -2 is proper

2022-11-13 12:22 UTC, JamieD1 approved these changes

2022-11-13 12:22 UTC, merged