TGUI Typescript support [port]
yogstation13/Yogstation pull request #16349
Opened 2022-11-03 18:58 UTC by TheGamerdk

# Document the changes in your pull request

Ports https://github.com/BeeStation/BeeStation-Hornet/pull/4219
See that PR for full list of changes

Major changes:
Typescript support
other stuff

# Spriting

# Wiki Documentation

# Changelog

:cl:  Sinestia for Bee port, TheGamerdk for Yogs port, Stylemistake, Cyberboss, SpaceManiac, other TG coders,
experimental: Updated TGUI. Please report any bugs/regressions
/:cl:

2022-11-03 19:23 UTC, TheGamerdk commented
reminder to self: need to check why ExosuitFabricator is crashing the linter

2022-12-31 17:06 UTC, JamieD1 approved these changes

2022-12-31 23:48 UTC, ToasterBiome requested changes
![image](https://user-images.githubusercontent.com/5091394/210157750-bcdbca0a-fdfe-4558-9969-6b1a6c0aad2d.png)
This section is way too tall now

2022-12-31 23:49 UTC, ToasterBiome commented
Also there's a script error when pressing the gear for the chat window.

2023-01-02 14:03 UTC, merged