Adds more job specific mail items
yogstation13/Yogstation pull request #16342
Opened 2022-11-03 04:24 UTC by Moltijoe

I love whoever coded mail, its super easy to add more job specific items.
I added some more
If anyone has more ideas for job specific items, just let me know and i'll add them in this PR.

:cl:  
rscadd: Adds more job specific mail items
/:cl:

2022-11-08 00:14 UTC, ReddicusDragon requested changes
Get back to me about captain needing a sharpener, other than that I'll approve it

2022-11-08 00:14 UTC, ReddicusDragon commented on code/modules/jobs/job_types/captain.dm
> +		/obj/item/sharpener = 1
why does the captain need a sharpener

2022-11-08 00:14 UTC, ReddicusDragon commented on code/modules/jobs/job_types/shaft_miner.dm
> +		/obj/item/card/mining_point_card/fivethousand = 1
I think adding mining point cards is kind of unnecessary and balance upsetting, although most yogs players could use the extra buff

2022-11-08 00:19 UTC, Moltijoe commented on code/modules/jobs/job_types/captain.dm
> +		/obj/item/sharpener = 1
someone told me it would be funny for them to sharpen their sword, so i did. not any more busted than chaplain getting holy hand grenades

2022-11-08 00:20 UTC, Moltijoe commented on code/modules/jobs/job_types/shaft_miner.dm
> +		/obj/item/card/mining_point_card/fivethousand = 1
the weights are rather low, i can always remove them if it's really that much of a problem

2022-11-08 00:21 UTC, ReddicusDragon commented on code/modules/jobs/job_types/shaft_miner.dm
> +		/obj/item/card/mining_point_card/fivethousand = 1
As I said, I find it unnecessary but I'm not going to say no. Resolve this bit please

EDIT: I'm dumb and it HAS been marked as resolved

2022-11-08 00:22 UTC, ReddicusDragon commented on code/modules/jobs/job_types/captain.dm
> +		/obj/item/sharpener = 1
Fair enough.

2022-11-08 00:22 UTC, ReddicusDragon approved these changes

2022-11-13 12:36 UTC, JamieD1 commented
Captain doesnt need a sharpener, we do not want to promote this.

2022-11-13 21:16 UTC, Moltijoe commented
> Captain doesnt need a sharpener, we do not want to promote this.

done

2022-11-19 14:16 UTC, JamieD1 approved these changes

2022-11-19 14:16 UTC, merged