Remove noob bait
yogstation13/Yogstation pull request #16365
Opened 2022-11-04 21:34 UTC by Simplehorror

# Document the changes in your pull request
Warping if you haven't camoflauged your jumpsuit asks if you're sure

# Changelog

:cl: 
rscadd: Warping if you haven't camoflauged your jumpsuit asks if you're sure
/:cl:

2022-11-06 19:32 UTC, Sniblet commented
camoflauging
camouflaging

2022-11-07 23:55 UTC, ReddicusDragon approved these changes
Low effort but valid PR, recommend changing pull request name from "Remove noob bait" as it is ambiguous.

2022-11-08 17:09 UTC, TheGamerdk requested changes

2022-11-08 17:09 UTC, TheGamerdk commented on code/game/machinery/computer/camera_advanced.dm
> +	if (user.w_uniform && user.w_uniform.name == "ratvarian engineer's jumpsuit")
```suggestion
	if (user.w_uniform && user.w_uniform.name == initial(user.w_uniform.name))
```

2022-11-13 14:21 UTC, JamieD1 approved these changes
Do bibby's changes

2022-11-19 14:22 UTC, JamieD1 approved these changes

2022-11-19 14:22 UTC, merged