Fix oversight in clockwork cult
yogstation13/Yogstation pull request #16384
Opened 2022-11-06 09:31 UTC by Simplehorror

# Document the changes in your pull request

Clockwork cultists now appear on the manifest and have their metatells stored in their bag instead of being noob bait

# Changelog

:cl:  
bugfix: Clockwork cultists now appear on the manifest and have their metatells stored in their bag instead of being noob bait
/:cl:

2022-11-06 10:15 UTC, TheGamerdk commented
Why are they on the manifest?

2022-11-06 10:22 UTC, Simplehorror commented
> Why are they on the manifest?

because every metahunter will just see some assistant with insulated gloves and a belt and check their manifest and surprise surprise they're not there and then they're valid because they're not crew

2022-11-06 12:09 UTC, warface1234455 commented
that's admin issue

2022-11-06 12:11 UTC, TheGamerdk commented
> > Why are they on the manifest?
> 
> because every metahunter will just see some assistant with insulated gloves and a belt and check their manifest and surprise surprise they're not there and then they're valid because they're not crew
> 
> have you played before?

That's an admin issue, in addition you're not valid due to not being on the manifest.

2022-11-11 19:44 UTC, Sniblet commented
However you can be arrested, searched, and that will make you valid

2022-11-11 20:48 UTC, TheGamerdk commented
> However you can be arrested, searched, and that will make you valid

Yes but that goes for every antag

2022-11-12 08:26 UTC, Sniblet commented
However, most antags are on the manifest
Question answered

2022-11-13 13:36 UTC, TheGamerdk requested changes
Please change your title and changelog to be less misleading. This is not a bugfix

2022-11-13 14:52 UTC, JamieD1 approved these changes

2022-11-19 14:27 UTC, merged