Increases wounding chances when doing surgery without anesthetic
yogstation13/Yogstation pull request #16460
Opened 2022-11-11 04:29 UTC by SomeguyManperson

# Document the changes in your pull request

I want people to suffer. That is all.

# Wiki Documentation

Surgeries done without anesthetic have a much higher chance to cause wounds if they roll to deal damage

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
tweak: Surgeries done without anesthetic have a much higher chance to cause wounds if they roll to deal damage
/:cl:

2022-11-11 04:32 UTC, Moltijoe commented
Guts ashwalker surgery
Also, this makes the holobed even more useless than it already is

2022-11-11 04:53 UTC, Hopekz commented
> Guts ashwalker surgery
> Also, this makes the holobed even more useless than it already is
> Honestly, this makes surgery in ghetto situations almost non viable
> 
> Also, it buffs the stasis bed and nerfs the surgery table

I'd imagine this is the first change of many. More of a PR to get us moving in the right direction with surgeries

2022-11-11 05:34 UTC, Moltijoe commented
> I'd imagine this is the first change of many. More of a PR to get us moving in the right direction with surgeries

I can only hope, fixing wounds is already annoying enough as it is

2022-11-11 05:53 UTC, Sniblet commented
I will sooner kill my patient to prep them for surgery than go to the trouble of putting anesthetic on them

2022-11-11 15:37 UTC, CMOisLing commented
> Also, it buffs the stasis bed and nerfs the surgery table
Stasis bed should slow down surgery speed. You trade time for safety would make it more of tool for treating dying people with major injuries instead of just being surgery table 2.0

2022-11-11 20:38 UTC, HisaHoshimo commented
Anesthetic is a stupid mechanic. Thats all I need to say.

2022-11-11 22:23 UTC, Moltijoe commented
> Stasis bed should slow down surgery speed. You trade time for safety would make it more of tool for treating dying people with major injuries instead of just being surgery table 2.0

I'd argue it should be the other way around, surgery tables speed up surgery

2022-11-13 18:01 UTC, ReddicusDragon requested changes

2022-11-13 18:01 UTC, ReddicusDragon commented on code/modules/surgery/surgery_step.dm
> +	if(BP?.get_mangled_state() <= MANGLED_FLESH )
MANGLED_FLESH should be BODYPART_MANGLED_FLESH

2022-11-13 21:04 UTC, closed without merging