you can no longer noclip others with seismic arm
yogstation13/Yogstation pull request #16462
Opened 2022-11-11 06:34 UTC by LazennG

# Document the changes in your pull request

i got slammed into the backrooms morty i'm backrooms riiick

# Changelog

:cl:  
bugfix: no more noclipping others into walls with the suplex  
/:cl:

2022-11-11 07:17 UTC, warface1234455 reviewed
Tab in

2022-11-11 07:46 UTC, warface1234455 reviewed
> `Sus``

2022-11-11 07:49 UTC, warface1234455 requested changes

2022-11-11 07:49 UTC, warface1234455 commented on code/modules/mining/lavaland/seismicarm.dm
> +		to_chat(user, span_warning("There's no room to do this!"))
Tab this

2022-11-13 15:39 UTC, JamieD1 approved these changes

2022-11-13 15:39 UTC, merged