No more Xenomorph strippers
yogstation13/Yogstation pull request #16476
Opened 2022-11-12 05:49 UTC by Moltijoe

Xenomorphs full stripping is boring, it makes recovering people from xeno nests pointless unless all xenos are dead.
This removes their ability to strip, but also lets them manually apply facehuggers to forcefully remove the target's helmet.

This should make it more possible for those that escape to survive as they still have most of their gear (oxygen tank most importantly)
This also helps people locate victims by not letting xenos from just removing suit sensors.

It also makes the xeno loop of Neurotoxin > strip > facehugger less tedious because it cuts out a step

:cl:  
tweak: Xenos can no longer strip
tweak: Xenos can now apply facehuggers by hand, removing any helmets in the way
/:cl:

2022-11-12 06:16 UTC, Simplehorror commented
new meta: 5 meth grenades in my bag to detonate on death when i get dragged into the xenobase

2022-11-12 06:18 UTC, Moltijoe commented
> new meta: 5 meth grenades in my bag to detonate on death when i get dragged into the xenobase

any different than just cavity implanting them?
or bombing them prior to death?
or just suicide verbing while the queen is next to you?
or just using a maxcap from literally anywhere within a decent radius?

That just sounds like problems with bombs being unfun

2022-11-12 06:20 UTC, Simplehorror commented
> > new meta: 5 meth grenades in my bag to detonate on death when i get dragged into the xenobase
> 
> any different than just cavity implanting them? or bombing them prior to death? or just suicide verbing with the bombs while the queen is next to you? or just using a maxcap from literally anywhere within a decent radius?
> 
> That just sounds like problems with bombs being unfun

you can't do any of these without this PR aside the first one

2022-11-12 06:26 UTC, Moltijoe commented
> you can't do any of these without this PR aside the first one

you can though? bombs are all over the bloody place. people ALREADY suicide bomb xenos, this doesn't change enough to incentivize people into doing it if they weren't already planning to

2022-11-12 06:35 UTC, Moltijoe commented
Reducing the time it takes for larvas to burst from bodies is currently my favourite idea for buffing, gets people back in the game faster, lets xenos scale up faster, lets them recover from losses faster.
I'm also disappointed by how rarely someone gets bursted during surgery, i kinda want that to happen more.

2022-11-12 06:48 UTC, Mqiib commented
Ok so important note, xenos HAVE to strip people because otherwise they can just use tools and other random items to smash the resin bed and any unfortunate xenos around them, and you cant crit them because they'll just succumb and ruin the embryo when they die. This would be acceptable if resin beds also handcuffed you while you were in it, but they don't.

2022-11-12 06:51 UTC, Moltijoe commented
> Ok so important note, xenos HAVE to strip people because otherwise they can just use tools and other random items to smash the resin bed and any unfortunate xenos around them, and you cant crit them because they'll just succumb and ruin the embryo when they die. This would be acceptable if resin beds also handcuffed you while you were in it, but they don't.

don't they? wasn't that a pr made within the past few months?
ah, nevermind, it was part of #15794 which had other bad takes
lemme add that real quick

2022-11-12 07:13 UTC, Sniblet commented
Given that this necessitates that all xeno caps now be killed lest they pull any of an incredible variety of hilariously cheesy nonsense to both free themselves and annihilate the Queen faster than anyone can react, I guess the suit sensors are the biggest issue
And it's a big one because we love having twenty borgs storm the nest about five minutes after xenomorph infestation triggers

I like the burst time, because it's always obnoxiously slow for early game xenos, and never oppressively fast for humans

2022-11-12 07:18 UTC, Moltijoe commented
> A) radio or B) pull any of an incredible variety of hilariously cheesy nonsense to both free themselves and annihilate the Queen faster than anyone can react

Facehuggers still prevent speaking so radios won't be an issue.
Also with the bed bucklecuffing that means that someone will need to break out of the bed and then the handcuffs in order to do anything cheesy

> I like the burst time, because it's always obnoxiously slow for xenos (with unremovable suit sensors being added, even more so, because lizbay guarantees that the nest will be stormed), and never oppressively fast for humans

You like the burst time being as slow it is? or buffing burst time?

2022-11-12 07:24 UTC, Sniblet commented
> Facehuggers still prevent speaking so radios won't be an issue.

Uhhh... are you sure? I don't think I've ever seen that and I can't find it in the code.

> You like the burst time being as slow as it is? or buffing burst time?

Buffing it

2022-11-12 07:26 UTC, Moltijoe commented
> Uhhh... are you sure? I don't think I've ever seen that and I can't find it in the code.

Maybe it's just the super long sleep it applies, lemme check, if it doesn't i can make it do that

> Buffing it

Sounds good, it's an each change

2022-11-12 07:39 UTC, Sniblet commented
Little concerned that 3:20 might be too fast, but we'll find out won't we? If nothing else, bursting leaves the head intact
If it does turn out to be too oppressive, the TDM servers like(d, in TGMC's case) to use mechanics where larva growth is faster under nest conditions

2022-11-12 07:42 UTC, Moltijoe commented
> Little concerned that 200 seconds might be too fast, but we'll find out won't we? If nothing else, bursting leaves the head intact If it does turn out to be too oppressive, the TDM servers like(d, in TGMC's case) to use mechanics where larva growth is faster under nest conditions

either that or stasis preventing growth

2022-11-14 09:03 UTC, Moltijoe commented
This is a very divisive pr, id appreciate those downvoting to state whether they thing the idea or the execution is flawed

2022-11-15 16:51 UTC, TheGamerdk requested changes
Atomize or update your title to be less misleading

2022-11-26 12:05 UTC, JamieD1 commented
I dont like the idea of people being able to insta pull out an armoury of guns to shoot aliens with, kinda dumb.

2022-11-26 22:25 UTC, Moltijoe commented
> 

yeah, that's always a problem, how to make something more interactive without letting people with experience just stomp
I can always just close this, but i don't currently feel like xenos are in a fun position for either side

2022-11-27 18:51 UTC, Moltijoe commented
Is it worth test merging?

2022-12-25 19:48 UTC, Moja10 commented
do not like, there are many things that xenon have to worry about people carrying, and if they are stripped on the same tile, they could still get to a backpack to open a bomb or something, so it's not like people are totally helpless 100% of time.

2022-12-26 23:55 UTC, Moltijoe commented
i still think xenos need some amount of changes, but even a 50/50 split isn't good enough to warrant adding

2022-12-26 23:55 UTC, closed without merging