Dark spirit now only lets you move 7 tiles away
yogstation13/Yogstation pull request #16553
Opened 2022-11-15 23:00 UTC by Simplehorror

# Document the changes in your pull request

Dark spirit is one of the most OP items in the game because it gives you information, which is key to winning games. If you had perfect information every game, you'd win every game. Let's nerf it now before people realise how powerful information is.
# Spriting

# Wiki Documentation

Dark spirit now only lets you move 7 tiles away
# Changelog

:cl:  
tweak: Dark spirit now only lets you move 7 tiles away
/:cl:

2022-11-16 00:05 UTC, Tempolx commented
So this just makes it basically incredibly useless except for niche cases like spotted people outside a base or just hearing deadchat

2022-11-16 02:22 UTC, ReddicusDragon requested changes
I'd understand like, 20-25 tiles, but 7 feels too small

2022-11-16 14:05 UTC, UltraBigRat commented
Literally makes it worthless you might aswell just grab a zealots blindfold at this point and look at people with thermals

2022-11-19 15:38 UTC, JamieD1 commented
Too much of a nerf, dial it back

2022-11-19 16:08 UTC, Simplehorror commented
@jamied1 done to 21, keep in mind you can browse other z-levels since +1 z only acts as 1 more in get_dist iirc

2022-11-26 12:25 UTC, JamieD1 commented on code/modules/antagonists/cult/runes.dm
> +
```suggestion
```

2022-11-26 12:25 UTC, JamieD1 commented on code/modules/antagonists/cult/runes.dm
> +			if (get_dist(G, affecting) > 21)
```suggestion
			if(get_dist(G, affecting) > 21)
```

2022-11-26 12:26 UTC, JamieD1 approved these changes

2022-11-26 12:43 UTC, merged