reduces the heck suit's armor while on the station
yogstation13/Yogstation pull request #16606
Opened 2022-11-19 01:32 UTC by TheRyeGuyWhoWillNowDie

why do miners get the highest source of energy armor in the game (better than the ablative vest since it covers all your limbs and head)
why do miners get 100 rad armor, there's never radiation on lavaland outside of a bug (which is why they get to keep it while on lavaland)

now the HECK suit is just good instead of the best piece of clothing on the entire station since previously it was plasma fire proof (a side effect of it being storm proof) and had 100 rad armor, making it the best engineering suit, zero slowdown and insane armor (it still has zero slowdown) which made it the best suit for fighting. it takes pretty much 0 effort to get this consistently round after round once you've beaten bubblegum once, anyone who says otherwise is being disingenuous at best and lying to your face at worst. also this follows the principle of making miners less good at everything on the space station

stats while on the station are reduced to
MELEE = 40, BULLET = 20, LASER = 10, ENERGY = 10, BOMB = 50, BIO = 100 RAD = 60, FIRE = 100, ACID = 100

# Changelog

:cl:  
tweak: the heck suit's armor is now reduced while on the station
/:cl:

2022-11-19 01:34 UTC, Cartlord commented
just fucking nerf the whole thing, making the armor values inconsistent is stupid

2022-11-19 01:41 UTC, KillerOrcaCora commented
Balance council is gonna have fun with this one…

2022-11-19 02:08 UTC, Mqiib commented
Nah see, fuck miners bringing powergame gear to the station. It's MINING gear, it's to help you MINE on the MINING PLANET and also kill MONSTERS. People are not (usually) monsters, and the heck suit has consistently been shown to be one of the most powerful pieces of equipment miners can bring to the station due to its extremely high armor values and zero slowdown.

2022-11-19 02:57 UTC, N3D6 commented
Gus good take challenge (IMPOSSIBLE)

2022-11-19 08:33 UTC, Sniblet commented
No you see the miner NEEDS to have spaceproof all-purpose riot armor with no slowdown on the station so that he can kill anta-
I mean kill anta-
I mean kill anta-
I mean for cosmetics?

2022-11-19 10:05 UTC, 00ze-cyclone commented
Just delete the absurd energy, bullet and laser armor everywhere instead of snowflaking the armor to certain places, also the rad armor a little since why should we have an armor for when shit is bugged anyway?

2022-11-26 13:20 UTC, JamieD1 commented
Why dont we add a new armour value called Lavaland or some shit and then make this have a high value then reduce the rest of the stats to a more shit version.

2022-11-30 15:22 UTC, TheGamerdk requested changes
You can't change armor outside of the initial properties unless you use getArmor

2022-12-02 23:38 UTC, LazennG commented
know it's shilling but think this pr should be closed as #16766 was already merged as a heck suit nerf

2022-12-03 00:48 UTC, chemistrymain2 commented
> No you see the miner NEEDS to have a spaceproof up-armored full-body upgrade of Mk. IV titanium plating put together with the CE hardsuit with no slowdown 20 minutes into the round on the station so that they can kill antags- I mean kill antags- I mean kill antags- I mean so they can defend themself at their... workplace. ...no, yeah, this checks out to me.
> 
> It's a reward for competent play, after all; practicing and memorizing, and being rewarded with the ability to quickly and consistently overthrow the gamemode as a job that should theoretically be interacting with antagonists even less than any other. Basically on par with atmos.
> 
> ```
> /obj/item/clothing/suit/space/hardsuit/elder_atmosian
> 	name = "Elder Atmosian Hardsuit"
> 	desc = "A special suit that protects against hazardous, low pressure environments. Has thermal shielding. This one is made with the toughest and rarest materials available to man."
> 	...
> 	armor = list(MELEE = 40, BULLET = 35, LASER = 25, ENERGY = 30, BOMB = 100, BIO = 100, RAD = 100, FIRE = 100, ACID = 100, WOUND = 20)
> ```
> 
> Like, if you ignore all of the combat armor stats, they're almost identical! And that's a good thing!
> 
> ```
> /obj/item/clothing/suit/space/hardsuit/syndi/elite
> 	name = "elite syndicate hardsuit"
> 	desc = "An elite version of the syndicate hardsuit, with improved armour and fireproofing. It is in travel mode."
> 	 ...
> 	armor = list(MELEE = 60, BULLET = 60, LASER = 50, ENERGY = 25, BOMB = 90, BIO = 100, RAD = 70, FIRE = 100, ACID = 100, WOUND = 25)
> ```
> 
> I don't see what this has to do with anything?
> 
> What is it with you guys and nerfing mining. You guys just have it out for miners. Atmos has [never](https://github.com/yogstation13/Yogstation/pull/15333) been [nerfed](https://github.com/yogstation13/Yogstation/pull/15295) for its validhunting potential. Haha try not to nerf miners challenge. Heehoo skill issue. Lol. Lmao. This but unironically.

people overreact to mining's balance issues because they keep balancing antagonists to deal with security and _only_ security, so any time another job gets powerful content or weapons, antagonists are incapable of dealing with the sudden outside context problem

of all the things to worry about, mining _armor_ is one of mining's least problematic issues because armor is meaningless and stuns are king, and miners have always had some of the best armor in the game regardless. on paper, the heck suit's stats are scary as fuck-in practice, whoever lands the first stun wins, and most antagonist abilities worth a damn ignore armor or penetrate armor, since armor is something most antags are balanced around and take into account

the issue is that it's _mining_ and people are used to seeing miners pull shit out of their ass to steamroll and so anything mining related gets the stink eye, as compared to seemingly harmless jobs like the janitor or the bartender

2022-12-04 07:46 UTC, Mqiib commented
> know it's shilling but think this pr should be closed as #16766 was already merged as a heck suit nerf

yeah you can probably close this one @TheRyeGuyWhoWillNowDie

2022-12-05 00:08 UTC, TheRyeGuyWhoWillNowDie commented
k

2022-12-05 00:08 UTC, closed without merging