Changes hierophant crusher trophy's effect and makes colossus a bit more approachable.
yogstation13/Yogstation pull request #16600
Opened 2022-11-18 18:55 UTC by LazennG

# Document the changes in your pull request

Don't like the vortex talisman walls because it turns crusher gameplay more into ka gameplay, so now it shoots out a hierophant chaser on mark detonation aimed at the target. Also colossus is a bit more approachable with the crusher with a half second delay on some of its attacks. (initially this was gonna be a port of the beestation change but i realized i didnt like most of it).

![dreamseeker_PxIfVkgrNJ](https://user-images.githubusercontent.com/58535870/202781276-6688f26c-786d-4804-b9c1-f7dc816945e2.gif)

Thanks to beestation's Rukofamicom for making the original pr i based this one off of.

# Wiki Documentation
https://wiki.yogstation.net/wiki/Shaft_Miner#Crusher_Trophies
For the vortex talisman bit, change the description to like 'sends out a hierophant chaser on mark detonation which does 10 damage on crossing a target.'

# Changelog

:cl:  @LazennG @Rukofamicom
tweak: tweaked vortex talisman and colossus
/:cl:

2022-11-18 18:56 UTC, Simplehorror commented
nice

2022-11-19 01:48 UTC, ToasterBiome approved these changes

2022-11-19 01:48 UTC, ToasterBiome commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +			sleep( 0.5 SECONDS)
```suggestion
			sleep(0.5 SECONDS)
```

2022-11-19 01:48 UTC, ToasterBiome requested changes
am bald

2022-11-19 08:13 UTC, LazennG commented
> am bald

bald as hell

2022-11-20 23:50 UTC, Rukofamicom commented
I made a mining PR that everyone doesn't hate :')

2022-11-21 03:20 UTC, ToasterBiome approved these changes

2022-11-26 13:10 UTC, merged