fix railing rod exploit
yogstation13/Yogstation pull request #16639
Opened 2022-11-21 03:37 UTC by Simplehorror

# Document the changes in your pull request

# Spriting

![image](https://user-images.githubusercontent.com/101573582/202960492-ec8fbdca-e620-42ba-b4e5-a55d6abd5e9d.png)

# Wiki Documentation

# Changelog

:cl:  
bugfix: Immovable rod is now immovable again, according to leading railing experts
/:cl:

2022-11-21 03:39 UTC, Simplehorror commented
YOU CANT DOWNVOTE A BUGFIX BOYS

2022-11-21 03:44 UTC, Ethan4303 commented
> YOU CANT DOWNVOTE A BUGFIX BOYS

YOU CANT TELL ME WHAT TO DO I HATE YOUR BUGFIX I WANT FUNNY ROD

2022-11-21 03:47 UTC, Simplehorror commented
^ THIS GUY FORKED CITADEL STATION

2022-11-21 03:47 UTC, Simplehorror commented
> > YOU CANT DOWNVOTE A BUGFIX BOYS
> 
> YOU CANT TELL ME WHAT TO DO I HATE YOUR BUGFIX I WANT FUNNY ROD

NO RODS

2022-11-21 10:20 UTC, TheGamerdk requested changes
What a bad fix, make it better

2022-11-21 20:59 UTC, MajManatee commented
terrible PR, frankly the worst one so far

2022-11-21 22:51 UTC, TheGamerdk requested changes
just port the TG fix

2022-11-21 23:03 UTC, Simplehorror commented
> just port the TG fix

what fucking TG fix

2022-11-21 23:05 UTC, Simplehorror commented
you clearly do not seem to understand that tg's railing is different to ours so i cant "port" the fix

2022-11-22 10:16 UTC, Bibby0110 commented
I’ll do it myself

2022-11-22 10:16 UTC, closed without merging