Security record and radio hot fix
yogstation13/Yogstation pull request #16631
Opened 2022-11-20 12:35 UTC by warface1234455

# Document the changes in your pull request
Fix changing rank button in record console disappear when pressing cancel button
Fix radio being funky

# Wiki Documentation

Fix changing rank button in record console disappear when pressing cancel button
Fix radio being funky

# Changelog

:cl:  
bugfix: Fix changing rank button in record console disappear when pressing cancel button
bugfix: Fix radio being funky
/:cl:

2022-11-20 12:43 UTC, TheGamerdk requested changes

2022-11-20 12:43 UTC, TheGamerdk commented on code/game/machinery/computer/security.dm
> +					if(active_general_record && changed_rank != null)
```suggestion
					if(active_general_record && changed_rank)
```

2022-11-20 14:27 UTC, warface1234455 commented
Alright, the radio in your active will overwrite other radios. Then ears, Then storages

2022-11-20 14:28 UTC, warface1234455 commented
IF you want to switch between ears and pockets, reEQuip the radio in ears slot and it will switch to pockets one

2022-11-26 14:04 UTC, JamieD1 approved these changes

2022-11-26 14:04 UTC, merged