make syndicate elite hardsuits immune to bombs
yogstation13/Yogstation pull request #16635
Opened 2022-11-21 01:31 UTC by Simplehorror

# Document the changes in your pull request

crew members outnumber nukies
crewmembers can maxcap all nukies in a 1 for 5 trade to win

# Spriting

# Wiki Documentation

made syndicate elite hardsuits immune to bombs
# Changelog

:cl:  
tweak: made syndicate elite hardsuits immune to bombs
/:cl:

2022-11-21 01:32 UTC, BurgerLUA requested changes

2022-11-21 01:32 UTC, BurgerLUA commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	armor = list(MELEE = 60, BULLET = 60, LASER = 50, ENERGY = 25, BOMB = 1000, BIO = 100, RAD = 70, FIRE = 100, ACID = 100, WOUND = 25)
Should be 1200 bomb resist, its more balanced that way.

2022-11-21 01:32 UTC, BurgerLUA commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	armor = list(MELEE = 60, BULLET = 60, LASER = 50, ENERGY = 25, BOMB = 1000, BIO = 100, RAD = 70, FIRE = 100, ACID = 100, WOUND = 25)
here too, maybe make this one have 35 wound resist too to also improve the balance

2022-11-21 01:41 UTC, Moltijoe commented
My god no, this isnt immunity, this turns bombs into an Aheal on them

2022-11-21 01:53 UTC, Simplehorror commented
> My god no, this isnt immunity, this turns bombs into an Aheal on them

100 doesn't block devestation

2022-11-21 02:38 UTC, Moltijoe commented
> 100 doesn't block devestation

100 bomb armour turns devastation from a gib into a total of 100 damage
going above 100 starts to breath the damage formula, anything above 120 bomb armour will make them heal
in order for bomb armour to actually just be immunity, it needs to be exactly 120

2022-11-21 02:45 UTC, Simplehorror commented
cant we just multiply it by 1.2 or some shit

2022-11-21 02:46 UTC, Moltijoe commented
> cant we just multiply it by 1.2 or some shit

what? all i'm saying is that setting bomb armour to be 120 gives them immunity like you want, where as giving them 1000 like this pr currently has makes bombs heal them

2022-11-21 18:34 UTC, Sniblet commented
Is there a compromise somewhere between preventing some scientist with a valve being the scariest living entity on the station, and allowing syndies to walk through their own grenades

2022-11-21 20:28 UTC, Moltijoe commented
> Is there a compromise somewhere between preventing some scientist with a valve being the scariest living entity on the station, and allowing syndies to walk through their own grenades

not without redoing how explosion damage is calculated or adding a snowflake check

2022-11-22 05:25 UTC, chemistrymain2 commented
> > cant we just multiply it by 1.2 or some shit
> 
> what? all i'm saying is that setting bomb armour to be 120 gives them immunity like you want, where as giving them 1000 like this pr currently has makes bombs heal them

this is incorrect, it won't heal them

2022-11-22 12:05 UTC, Moltijoe commented
> this is incorrect, it won't heal them

i suppose i've not tried it, but with how the damage calculates, you'd end up with a negative number
and at no point is there a check to make sure a negative number won't heal them

2022-11-22 20:30 UTC, chemistrymain2 commented
> > this is incorrect, it won't heal them
> 
> i suppose i've not tried it, but with how the damage calculates, you'd end up with a negative number and at no point is there a check to make sure a negative number won't heal them
> 
> either way, 120 is perfect to make bombs deal exactly 0 damage without potentially causing other problems

with how damage is calculated, it'd just hit zero

you can't get a negative value ever

if you actually wanted to make bomb proof suits you'll have to redo explosion code on human defense, as they're hardcoded to do various effects even accounting for armor

2022-11-22 21:26 UTC, Moltijoe commented
> with how damage is calculated, it'd just hit zero
> 
> you can't get a negative value ever

ah, yeah, looking at it i somehow missed this line in take_overall_damage
![image](https://user-images.githubusercontent.com/108117184/203423621-6a235513-94f5-4319-ac9c-36b4e3d770e0.png)


> if you actually wanted to make bomb proof suits you'll have to redo explosion code on human defense, as they're hardcoded to do various effects even accounting for armor
 
true, but it seemed like jamie wasn't keen on that seeing as he merged the pr that made bomb armour more effective rather than a proper percentage. currently the only bomb immune thing seems to be an ascended ash heretic, and even that might not be coded correctly to grant it.

2022-11-26 14:25 UTC, JamieD1 commented
lol

2022-11-26 14:25 UTC, closed without merging