New null rod variant: Golden crucifix
yogstation13/Yogstation pull request #16672
Opened 2022-11-23 22:55 UTC by ynot01

# Document the changes in your pull request

Has 0 force and 0 throw force

When used in hand, every mob in a short area in front of you will be constantly damaged

Damage is ~5 burn and ~15 stamina per second

Unholy creatures (cult, wizard, vampire, heretic, etc) will be damaged for ~10 burn and ~10 stamina per second

Numbers to be tweaked

# Spriting

![](https://i.imgur.com/Kk21lxN.png)
![](https://i.imgur.com/NinNQpd.png)

# Changelog

:cl:  
rscadd: Added the golden crucifix null rod variant
/:cl:

2022-11-23 23:41 UTC, Rdrazga commented
Now we just need to give the chaplain an exorcism ritual that they can do using this that deconverts rather then just filling people full of holy water

2022-11-23 23:47 UTC, Simplehorror commented
add garlic from vampire survivors

2022-11-23 23:48 UTC, Simplehorror commented
also i love this

2022-11-24 03:24 UTC, cowbot92 commented
Have FAITH

2022-11-24 06:36 UTC, Moltijoe commented
make dying with it in your hand play the mortis sound effect

2022-11-25 03:30 UTC, Moltijoe commented
does this let chaplain attack through walls?

2022-11-25 04:21 UTC, ynot01 commented
> does this let chaplain attack through walls?

Shouldn't

2022-11-25 05:28 UTC, ToasterBiome requested changes

2022-11-25 05:28 UTC, ToasterBiome commented on code/game/objects/items/holy_weapons.dm
> +/obj/item/nullrod/cross/dropped(mob/user)
we have a signal for this, COMSIG_ITEM_DROPPED

2022-11-25 05:28 UTC, ToasterBiome commented on code/modules/spells/spell_types/cone_spells.dm
> +// Global ver
unused

2022-11-25 07:08 UTC, Xoxeyos commented on code/game/objects/items/holy_weapons.dm
> +		if(!L.mind?.holy_role && (L in chapview)) // Priests are unaffeted, trying to use it as a non-priest will harm you
unaffeted to unaffected

2022-11-25 20:13 UTC, cuackles requested changes
orca and i bealive the item needs the outline a bit more notable/harsher, apart from that all good

2022-11-25 21:05 UTC, ynot01 commented
> orca and i bealive the item needs the outline a bit more notable/harsher, apart from that all good

on the inhand or the object sprite? and by outline do you mean shadow?

2022-11-25 21:08 UTC, cuackles commented
> > orca and i bealive the item needs the outline a bit more notable/harsher, apart from that all good
> 
> on the inhand or the object sprite? and by outline do you mean shadow?

Object, also i didn't interpret it as a shadow Wich it actually makes a lot more sense , in that case it would need an actual outline around it, the inhand is good and can stay as it is

2022-11-25 21:11 UTC, KillerOrcaCora commented
What shadow? There is only 2 colors and shadow is determined by light which is nowhere, you can’t have your outline be your light and your outline at the same time if it’s one primary color or else it just leaks out like it’s doing now. If you want to keep the games look just slap a more noticeable outline and make sure to fully cover it.

2022-11-25 21:14 UTC, cuackles commented
> What shadow? There is only 2 colors and shadow is determined by light which is nowhere, you can’t have your outline be your light and your outline at the same time if it’s one primary color or else it just leaks out like it’s doing now. If you want to keep the games look just slap a more noticeable outline and make sure to fully cover it.

Orca the darker color is the shadow, it shows thickness in the cross

2022-11-25 21:15 UTC, KillerOrcaCora commented
The darker color is the outline, not the shadow.

2022-11-25 21:16 UTC, cuackles commented
It's not an outline, it's the shadow, there was never an outline we where lied to, the outline was capitalistic propaganda

2022-11-25 21:17 UTC, KillerOrcaCora commented
God damnit! AGAIN!

2022-11-25 21:19 UTC, cuackles commented
Our spriting team everybody, there are 0 braincells between us

2022-11-25 21:20 UTC, KillerOrcaCora commented
OMG THERE IS NO OUTLINE AT ALL IT REALLY WAS THE SHADOW REEEEEEE

2022-11-25 21:23 UTC, ynot01 commented
I'm going to be honest I don't want to toss a million screenshots back and forth in this PR but given this is the most response I've ever seen from spriting maintainers I'm going to anyways

Tell me if you're satisfied with this (enlarged for clarity)
![image](https://user-images.githubusercontent.com/28408322/204056449-8b790547-3bb2-40f6-aad7-3b0b9bf3afc8.png)

2022-11-25 21:24 UTC, KillerOrcaCora commented
Come to #spriting

2022-11-26 12:16 UTC, cuackles approved these changes
✝️

2022-11-26 14:47 UTC, merged