Events are now split into 3 different severities, each with their own timer
yogstation13/Yogstation pull request #16675
Opened 2022-11-24 01:32 UTC by Simplehorror

# Document the changes in your pull request

Love it when I get stray cargo pod or high priority bounty for the 10th time in a row - this way severe events are guaranteed to happen on a timed basis as opposed to having a high chance of not actually happening. This way, mild events happen more often allowing for more interesting stuff to happen with them, and severe events are guaranteed to happen at some point in the round to introduce fun.

# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: Events are now split into 3 different severities, each with their own timer
/:cl:

2022-11-24 01:35 UTC, Sniblet commented
why are flutes catastrophic and not blob

2022-11-24 01:36 UTC, Simplehorror commented
> why are flutes catastrophic and not blob

when was the last time you saw a blob win

2022-11-24 01:37 UTC, MajManatee commented
like yesterday

2022-11-24 01:42 UTC, Simplehorror commented
> like yesterday

fine

2022-11-24 02:13 UTC, Simplehorror commented
@Xoxeyos EXPLAIN YOURSELF

2022-11-24 02:32 UTC, Marmio64 commented
honestly don't know if 3 categories are needed, seems like too much of a guarantee for bad shit to always happen. I'd like to see it be just 2 categories, one for nuisance/flavor events like pool chem spill, aurora, and minor space dust, then one for anything that can cause real problems even if small: meteors, ninjas, blob, major space dust, mice, etc.

2022-11-24 02:34 UTC, ReddicusDragon commented
what are the performance implications of this

2022-11-24 03:19 UTC, Simplehorror commented
> what are the performance implications of this

none

2022-11-24 07:14 UTC, TheGamerdk commented
Not a big fan, events are supposed to be random.

2022-11-24 07:23 UTC, TheGamerdk commented
DNM so Jamie doesn’t break events by not reviewing the code

2022-11-24 15:21 UTC, Simplehorror commented
> Not a big fan, events are supposed to be random.

events are random, my events are shuffle

2022-11-24 23:18 UTC, ReddicusDragon commented
I kinda want to see this as a test merge

2022-11-26 14:48 UTC, JamieD1 commented
I hope this respects player counts and minimum times

2022-11-26 15:37 UTC, ReddicusDragon requested changes

2022-11-26 15:37 UTC, ReddicusDragon commented on code/controllers/subsystem/events.dm
> -	message_admins("Summon Events has been [wizardmode ? "enabled, events will occur every [SSevents.frequency_lower / 600] to [SSevents.frequency_upper / 600] minutes" : "disabled"]!")
??? Will the event not occur every x to y minutes now?

2022-11-26 15:37 UTC, ReddicusDragon commented on code/game/gamemodes/wizard/wizard.dm
> -	if(SSevents.wizardmode) //If summon events was active, turn it off
why remove this?

2022-11-27 01:57 UTC, Simplehorror commented on code/game/gamemodes/wizard/wizard.dm
> -	if(SSevents.wizardmode) //If summon events was active, turn it off
was dumb

2022-11-27 01:57 UTC, Simplehorror commented on code/controllers/subsystem/events.dm
> -	message_admins("Summon Events has been [wizardmode ? "enabled, events will occur every [SSevents.frequency_lower / 600] to [SSevents.frequency_upper / 600] minutes" : "disabled"]!")
no, it just doesn't message admins since it doesn't have a meaning anymore

2022-11-27 02:01 UTC, Simplehorror commented
> I hope this respects player counts and minimum times

yes

2022-12-10 09:38 UTC, TheGamerdk commented
Kinda defeats the point of random events

2022-12-10 09:38 UTC, closed without merging