Regen gene
yogstation13/Yogstation pull request #16697
Opened 2022-11-24 17:59 UTC by Simplehorror

# Document the changes in your pull request

# Spriting

Adds a gene that makes the user slowly regenerate.
More genes = more better since you need to actually pick instead of taking the 5 meta genes.
# Wiki Documentation

Adds a gene that makes the user slowly regenerate.
# Changelog

:cl:  
rscadd: Adds a gene that makes the user slowly regenerate.
/:cl:

2022-11-24 19:14 UTC, Marmio64 commented
podperson healing for only 15 instability sounds terrible balance wise. Make it only heal if you have 10 or less damage or something, so it is only usable for chip damage and has a neat niche, or make it cost way more instability.

2022-11-24 19:21 UTC, Simplehorror commented
> podperson healing for only 15 instability sounds terrible balance wise. Make it only heal if you have 10 or less damage or something, so it is only usable for chip damage and has a neat niche, or make it cost way more instability.

sir have you heard of our lord and savior nanites

2022-11-24 19:29 UTC, Marmio64 commented
> > podperson healing for only 15 instability sounds terrible balance wise. Make it only heal if you have 10 or less damage or something, so it is only usable for chip damage and has a neat niche, or make it cost way more instability.
> 
> sir have you heard of our lord and savior nanites

Little known fact is that EMPs actually counter nanites, has some risk of sabotage, and has a Regen cooldown period if you're using them too often. If you give this a resistance chromosome there's nothing to do about it but put them in the DNA modifier, and it's cost is really cheap for the value.

2022-11-24 19:51 UTC, Simplehorror commented
> > > podperson healing for only 15 instability sounds terrible balance wise. Make it only heal if you have 10 or less damage or something, so it is only usable for chip damage and has a neat niche, or make it cost way more instability.
> > 
> > 
> > sir have you heard of our lord and savior nanites
> 
> Little known fact is that EMPs actually counter nanites, has some risk of sabotage, and has a Regen cooldown period if you're using them too often. If you give this a resistance chromosome there's nothing to do about it but put them in the DNA modifier, and it's cost is really cheap for the value.

never seen anyone specifically counter nanites with an EMP, also cloud controller just fixes it anyway

2022-11-24 20:50 UTC, CMOisLing commented
I agree nanite passive healing is basically free but that doesnt mean we should add more of it. How about have it be a unique conditional regen. Or how about you take 20% more damage overall but you have a passive 2 brute/burn heal, 1 toxin heal

2022-11-24 20:51 UTC, Simplehorror commented
> I agree nanite passive healing is basically free but that doesnt mean we should add more of it. How about have it be a unique conditional regen. Or how about you take 20% more damage overall but you have a passive 2 brute/burn heal, 1 toxin heal

i like that

2022-11-28 07:40 UTC, ilikesaying commented
>sir have you heard of our lord and savior nanites

Accelerated Regeneration deals stamina damage when repairing.
Bio-Reconstruction consumes nanites at a rapid rate when on, even if there is no damage to repair.
Nanites can be countered by some guy walking into the nanite lab and deleting all the programs/replacing them with weaponized or suppression programs or just destroying the nanite server.

2022-12-03 06:10 UTC, boodaliboo commented
MAKE THIS A POD PERSON ONLY MUTATION LIKE HOW FIRE BREATH IS FOUND

2022-12-03 06:47 UTC, Simplehorror commented
do humans have any race specific mutations ever since hulk got removed

2022-12-06 04:29 UTC, Moltijoe requested changes

2022-12-06 04:29 UTC, Moltijoe commented on code/datums/mutations/regeneration.dm
> +	instability = 15
15 instability is too little for constant healing like this

2022-12-06 04:29 UTC, Moltijoe commented on code/datums/mutations/regeneration.dm
> +	owner.take_overall_damage(-1, -1)
should use heal_overall_damage()

2022-12-06 04:38 UTC, Simplehorror commented
@Moltijoe done

2022-12-06 05:05 UTC, Moltijoe approved these changes
More in line with balance, probably still fucked, gonna wait on someone else to actually merge it

2022-12-09 17:52 UTC, Moltijoe requested changes
after reviewing other mutations, this is still too powerful
cerebral neuroplasticity is 70 instability, this mutation is probably more powerful than that
Either it needs to heal for less or have even higher instability

you could possibly let it be powered if you want to make it possible to have the same strength

Also, the name, description, and gain indicator are all lacking flavour
also it's lacking a text_lose_indication

2022-12-09 17:55 UTC, Simplehorror commented
cerebral neuroplasticity is dogshit and I would not use it for 30 instability

2022-12-10 12:51 UTC, JamieD1 commented
*opens pr to nerf healing per second*
*opens pr to add regen*

2022-12-10 12:51 UTC, closed without merging

2022-12-10 18:30 UTC, CMOisLing commented
> > I agree nanite passive healing is basically free but that doesnt mean we should add more of it. How about have it be a unique conditional regen. Or how about you take 20% more damage overall but you have a passive 2 brute/burn heal, 1 toxin heal
> 
> i like that, let me do it

Damn Guess he never did it

2022-12-10 21:11 UTC, Simplehorror commented
why would I do something when the PR is going to be closed