Shadowlings get a spell that extinguishes them on a 5 second cooldown
yogstation13/Yogstation pull request #16712
Opened 2022-11-24 21:19 UTC by Simplehorror

# Document the changes in your pull request

remove cheese tactic. They insta-die to dragonsbreath rounds if they get caught which is a notorious cheese tactic, and it makes shadowlings very hard to balance when it exists. They also have no existing way to remove fire outside of an extinguisher, which is just impossible to carry around anymore.

Sister PR to #16598
# Spriting

# Wiki Documentation

New shadowling spell: extinguish. 5 second cooldown
# Changelog

:cl:  
tweak: Shadowlings get a spell that extinguishes them on a 5 second cooldown
/:cl:

2022-11-24 21:28 UTC, ynot01 commented
carry a mini fire extinguisher

2022-11-24 21:30 UTC, Simplehorror commented
> carry a mini fire extinguisher

this is like if i removed emags and everyone complained but then i said "carry a toolbox"

noobs aren't gonna do this and it's another station item you're going to need for something that you should really have as a spell

2022-11-24 21:45 UTC, Cartlord commented
Where the fuck do you even GET mini extinguishers?

2022-11-24 21:47 UTC, MajManatee commented
> Where the fuck do you even GET mini extinguishers?

any autolaithe makes them

2022-11-24 21:49 UTC, ynot01 commented
> this is like if i removed emags and everyone complained but then i said "carry a toolbox"

emags cost resources and are not innate, if it had no value over a toolbox then everyone would simply carry a toolbox

> noobs aren't gonna do this and it's another station item you're going to need for something that you should really have as a spell

if there is a line for hugbox i would think this crosses it, something as simple as carrying a fire extinguisher because you are vulnerable to something like fire is simple and not by any means arcane knowledge

i would focus fire on something else in shadowling's kit

if you're looking for suggestions:

- their ability to cross walls and move at ludicrous speeds; moving at such high speed is disorienting for new players, as strong as it is, it is hard to control. i would review this and their two jaunts, condensing it all down into one mechanic that is more in the player's face so that they are forced to acknowledge it rather than an off button, as well as being more fair to fight against (the original jaunt had a stamina damage system where you would take more damage in lit areas but it was basically inconsequential, and if you stamcrit the ability wouldn't go on cooldown)
- conversion is a pain in the ass, the spell sucks to use and it being nerfed does no favors, more experienced players work around this by crafting stun weapons but a new player would never think of this.

2022-11-24 22:43 UTC, Sniblet commented
Integrating this into veil and icy veins helps to negate button bloat, and most of the time when you're on fire it's in a situation when you'd want to turn off some lights anyway

I don't agree that forcing slings to do a quick chore at the start of every round or else die contributes to the game in a positive way

2022-11-24 23:03 UTC, KillerOrcaCora requested changes
Good suggestion, mix this with the icy vines ability, that way we don’t have to have 2 icons that are probably gonna look very similar anyways

2022-11-24 23:28 UTC, Simplehorror commented
ok will do tmrw have migraine

2022-11-27 01:52 UTC, Simplehorror commented
ok not interested in this anymore

2022-11-27 01:52 UTC, closed without merging