makes shielded hardsuits not shit ass awful
yogstation13/Yogstation pull request #16719
Opened 2022-11-25 03:46 UTC by TheRyeGuyWhoWillNowDie

in times of old this thing was probably useful since it could absorb 3 taser shots, but we dont live in a world with 1 click wins anymore so being able to eat 3 hits every 20 seconds is terrible and a waste of 30tc for operatives.

# Wiki Documentation

ok so shielded hardsuits now work like this:

instead of having a number of predefined shield charges, their shields have HP. in the case of the syndicate shielded hardsuit, it's 75 HP. Instead of taking 20 seconds to recharge after last getting shot, it's 5 seconds unless the shield was completely destroyed, in which case it's still 20 seconds to start recharging. every charge cycle, the shielded hardsuits will recover 15HP

# Changelog

:cl:  
tweak: shielded syndicate hardsuit is now not a waste of tc for nukeops
/:cl:

2022-11-25 04:09 UTC, Rdrazga commented
Dats alota extra HP

2022-11-25 04:10 UTC, Sniblet commented
I'd have just given it the same armor as the elite hardsuit, what is this effort

2022-11-25 04:10 UTC, Rdrazga commented
Granted for balance reasons I don't think you can go much lower can you :/

2022-11-25 04:10 UTC, TheRyeGuyWhoWillNowDie commented
> Dats alota extra HP

its 30tc

2022-11-25 04:11 UTC, Rdrazga commented
> > Dats alota extra HP
> 
> its 30tc

I have a new vision in my mind of this combined with a desword, the augment part implanter, and the speedup implant. Totally won't be unbalanced I am sure.

2022-11-25 05:23 UTC, Skrem7 commented
> I have a new vision in my mind of this combined with a desword, the augment part implanter, and the speedup implant. Totally won't be unbalanced I am sure.

Well hopefully the full augment kit price is shot up bcuz it's kinda a gimmick being unkillable

2022-11-25 18:09 UTC, tattax commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	var/recharge_rate = 15 //How much HP the shield recharges per cycle
tbh i would rather have it be a component to apply it on other things that aren't hardsuits

2022-11-25 18:09 UTC, tattax commented on code/modules/clothing/spacesuits/hardsuit.dm
>  	var/recharge_cooldown = 0 //Time since we've last been shot
```suggestion
	var/shield_hp = 75
	var/shield_max_hp = 75 //Health until shield is depleted
	var/recharge_delay = 5 SECONDS //How long after we've been shot before we can start recharging. 5 seconds here
	var/recharge_delay_busted = 20 SECONDS //delay until shield can recharge when fully depleted
	COOLDOWN_DECLARE(recharge_cooldown) //Time since we've last been shot
```

2022-11-25 18:09 UTC, tattax commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	if(world.time > recharge_cooldown && shield_hp < shield_max_hp)
```suggestion
	if(COOLDOWN_FINISHED(src, recharge_cooldown) && shield_hp < shield_max_hp)
```

2022-11-25 18:09 UTC, tattax commented on code/modules/clothing/spacesuits/hardsuit.dm
>  		owner.visible_message(span_danger("[owner]'s shields deflect [attack_text] in a shower of sparks!"))
```suggestion
    shield_hp -= damage //receive damage
	if(shield_hp) //evaluate if we still have a shield, if so, deflect and start normal cooldown
		var/datum/effect_system/spark_spread/s = new
		s.set_up(2, 1, src)
		s.start()
		owner.visible_message(span_danger("[owner]'s shields deflect [attack_text] in a shower of sparks!"))
		COOLDOWN_START(src, recharge_cooldown, recharge_delay)
```

2022-11-25 18:09 UTC, tattax commented on code/modules/clothing/spacesuits/hardsuit.dm
>  			START_PROCESSING(SSobj, src)
better move this around cause it is quite confusing

2022-11-25 18:09 UTC, tattax commented on code/modules/clothing/spacesuits/hardsuit.dm
>  	return 0
```suggestion
	else //if shield has no health left after damage
		owner.visible_message("[owner]'s shield overloads!")
		shield_state = "broken"
		owner.update_inv_wear_suit()
		COOLDOWN_START(src, recharge_cooldown, recharge_delay_busted) //Long cooldown if the shield gets depleted
	if(recharge_rate)
			START_PROCESSING(SSobj, src)
	return TRUE
```

2022-11-25 18:31 UTC, Simplehorror commented
this thing was never useful

2022-11-27 14:36 UTC, Marmio64 commented
i thought that shields having uses instead of health was better since then it's really good but has a counter, ie buckshot and disabler, and would rather see that the number of shield uses just get increased to like 5 or something.

2022-12-06 07:39 UTC, K4rlox commented
enjoyable rework, shields were always pure ass and everybody always chooses elite suit for that reason

2022-12-07 22:08 UTC, Moltijoe requested changes
Stale

2022-12-08 01:19 UTC, closed without merging