[AsteroidStation] Adds an Autolathe to Service Hall
yogstation13/Yogstation pull request #16739
Opened 2022-11-26 00:22 UTC by Aquizit

# Document the changes in your pull request

Adds an Autolathe to the Service Hall in Asteroid Station. I did have to remove a table to get it to fit, and I moved the rolling pin to the other cooking items table, and the bucket to the table with the key on it. This makes it equal to box as it has both types of lathes.

:cl:  
rscadd: Adds autolathe to Asteroid Station Service Hall
rscdel: Removes a table to make it fit.
tweak: Moves the items on the deleted table to other tables.
mapping: This is a mapping change
/:cl:

2022-11-26 00:34 UTC, ToasterBiome requested changes
use the mapping tag in the changelog, all of this can be 1 line with the mapping tag

also i approve this change

2022-11-26 00:37 UTC, Aquizit commented
Like so?

2022-11-28 06:32 UTC, ToasterBiome commented
Yes but now map conflicts

2022-11-28 15:37 UTC, Aquizit commented
Ok I think I got it. Maybe not in the neatest way since I closed it but.

2022-11-30 01:33 UTC, ToasterBiome approved these changes

2022-11-30 01:33 UTC, merged