Rad collector is now upgradable
yogstation13/Yogstation pull request #16753
Opened 2022-11-26 15:06 UTC by warface1234455

Yeah you heard it right

# Document the changes in your pull request
Rad collector is now upgradable:

1. Better manipulator, lower gas drain
2. Better capacitor, more output
3. Better bin, more stored power

# Wiki Documentation

Rad collector is now upgradable:

1. Better manipulator, lower gas drain
2. Better capacitor, more output
3. Better bin, more stored power

# Changelog

:cl:  
tweak: Rad collector is now upgradable

/:cl:

2022-11-26 16:17 UTC, TheGamerdk requested changes

2022-11-26 16:17 UTC, TheGamerdk commented on code/modules/power/singularity/collector.dm
> +		stored_power *= bin.rating
this makes no sense, this would just make it a one-time thing

2022-11-26 16:17 UTC, TheGamerdk commented on code/modules/power/singularity/collector.dm
> +		drain /= lator.rating
should probably work based on drainratio

2022-11-26 16:17 UTC, TheGamerdk commented on code/modules/power/singularity/collector.dm
> +		last_output *= cap.rating
this doesn't actually do anything

2022-11-26 17:05 UTC, warface1234455 commented
yep imma fixt tmr

2022-11-27 09:27 UTC, TheGamerdk requested changes
Still doesn’t do anything

2022-11-27 14:20 UTC, warface1234455 commented
nvm let it be normal

2022-11-29 10:55 UTC, warface1234455 commented
no

2022-11-29 10:56 UTC, SapphicOverload commented
good pr

2022-12-02 13:21 UTC, JamieD1 approved these changes

2022-12-02 13:21 UTC, JamieD1 commented
This might be way too overpowered

2022-12-02 13:21 UTC, JamieD1 commented
@TheGamerdk

2022-12-02 13:23 UTC, warface1234455 commented
> This might be way too overpowered

nah it will just be slightly better

2022-12-15 22:59 UTC, TheGamerdk approved these changes

2022-12-15 22:59 UTC, merged