fixes yogstation github guidelines outlined in contributing.md
yogstation13/Yogstation pull request #16768
Opened 2022-11-27 00:24 UTC by ReddicusDragon

[changes the yogstation github guidelines in the readme.md as a link s…](https://github.com/yogstation13/Yogstation/commit/e783e5319f1ded7a437c96fec790957677f39e7c)

2022-11-27 00:42 UTC, TheGamerdk requested changes

2022-11-27 00:42 UTC, TheGamerdk commented on README.md
> +[**Yogstation GitHub Guidelines**](https://docs.google.com/document/d/1DNGBnkMQAWrNHs-wgR5AkxSrigPUMB9KbH_SJGkbv7I/edit?usp=sharing)
```suggestion
[**Yogstation GitHub Guidelines**](https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md#yogstation-github-guidelines)
```

2022-11-27 01:14 UTC, ReddicusDragon commented on README.md
> +[**Yogstation GitHub Guidelines**](https://docs.google.com/document/d/1DNGBnkMQAWrNHs-wgR5AkxSrigPUMB9KbH_SJGkbv7I/edit?usp=sharing)
this is more common sense, thank you bibby

2022-12-02 13:33 UTC, JamieD1 approved these changes

2022-12-02 13:35 UTC, merged