Overhauls Malf AI Objectives and updates win condition.
yogstation13/Yogstation pull request #16784
Opened 2022-11-27 16:17 UTC by BurgerLUA

# What was changed

## AI objectives now have more variety.  ##

The way it works:

- 1 random murderbone objective is rolled. It is either "Ensure no organics on the shuttle escape." or "Ensure no non-humans on the shuttle escape.". There is a higher chance to roll the former.
- 1 protect crewmember objective is rolled. 1 randomly chosen crewmember will be set as the AI's protect target. They must survive until the end.
- There is a 20% chance to choose a protect a station pet objective. If that check fails and there is a decent playerpop (Above 20), it will have a [Playerpop x 2]% chance to roll a "Convert 8 organics into cyborgs." objective.
- Of course, the stay alive to the end is 

## There are now 4 different victories for MALF. ##

- Condition 1: AI completes all their objectives. AI Major Victory.
- Condition 2: AI uses the nuke. AI Minor Victory.
- Condition 3: AI does not complete their objectives nor uses the nuke, but is still alive. Crew Minor Victory.
- Condition 4: AI dies and does not use the nuke nor complete their objectives. Crew Major Victory.

# Why this should be added to the game.

MALF is currently a really repetitive gamemode. The MALF usually stealths it way to the nuke and then plasmafloods the station, which isn't really fun. To make things more interesting, MALF AIs will be given a protect objective, and a "Convert 8 people into borgs" or a protect pet objective, depending on playercount and chance.

The new objective changes should prevent indiscriminate murderboning usually reserved for wizard, hijack, or nuke ops while at the same time making the AI actually think about how they're going to complete their protect objectives or convert people into cyborgs.

# Changelog

:cl:  BurgerBB
experimental: Malfunctioning AIs now have new objectives. Remember to read them carefully!
tweak: Changes the completely cosmetic win message conditions for the MALF gamemode.
/:cl:

2022-11-27 16:20 UTC, BurgerLUA commented
Note: You can still plasmaflood as AI. You just need to be smart about it now, such as moving your protect objective to a safe place before doing this.

2022-11-27 16:21 UTC, 00ze-cyclone commented
Add an objective to only let no humans escape but allow non humans

2022-11-27 16:23 UTC, CMOisLing commented
There could be a version to ensure x race doesnt make it onto the shuttle

2022-11-27 16:24 UTC, BurgerLUA commented
> There could be a version to ensure x race doesnt make it onto the shuttle

> Add an objective to only let no humans escape but allow non humans

I could add this, yes.

2022-11-27 17:29 UTC, Simplehorror commented
malf murderbone rules are gonna have to change because everyone's just gonna do doomsday anyway because it's fun for the malf

2022-11-27 18:50 UTC, BurgerLUA commented
> malf murderbone rules are gonna have to change because everyone's just gonna do doomsday anyway because it's fun for the malf

I thought there were already rules where you are required to at least attempt your objectives as an antagonist.

2022-11-27 19:49 UTC, Sniblet commented
The protect person objective works fine for heretics who can ignore it completely, less so for malf whose only methods of killing are indiscriminate
What do you do to keep someone alive in a plasmafire as an AI? You take them out of it, and force them to stay out of it
Which means you take them into maint and wall them off, and so that they don't commit suicide out of spite, you fill their 1x1 closet with N2O
That's, you know, fun

2022-11-27 22:25 UTC, Simplehorror commented
> The protect person objective works fine for heretics who can ignore it completely, less so for malf whose only methods of killing are indiscriminate What do you do to keep someone alive in a plasmafire as an AI? You take them out of it, and force them to stay out of it Which means you take them into maint and wall them off, and so that they don't commit suicide out of spite, you fill their 1x1 closet with N2O That's, you know, fun

we could do a SELF Hacker type thing here where we make them an antag, but only inorganics so they don't die to doomsday or something

2022-11-27 22:25 UTC, Simplehorror commented
also suiciding in this situation is probably against the rules same as suiciding if you were about to be converted

2022-11-30 15:27 UTC, TheGamerdk requested changes
remove the pet objective

2022-11-30 18:08 UTC, BurgerLUA commented
> remove the pet objective

done

2022-12-02 13:55 UTC, JamieD1 commented
Good idea, but unfortunately I dont think it fits.

2022-12-02 14:05 UTC, BurgerLUA commented
> Good idea, but unfortunately I dont think it fits.

What do you mean? How could I make it fit?

2022-12-07 14:26 UTC, BurgerLUA commented
@TheGamerdk pet objective was removed

2022-12-09 18:01 UTC, Moltijoe commented
Malf AI needs a significant rework, tweaking objectives won't be enough

The objectives don't really mesh well either
Murderbone requires them to either kill or borg as many people as possible, which incentivizes them to fuck up the station so no one can escape
Protect basically makes one person either the "protagonist" that gets left alone, or they get abducted and held hostage for the entire around
Have enough borgs is reliant on either a roboticist building a fuckoff amount of borgs, or using the borg factory and hoping it doesn't get destroyed, otherwise you auto redtext the objective

It's probably just best to wait on bibby getting around to reworking malf ai

2022-12-09 18:01 UTC, closed without merging

2022-12-09 18:03 UTC, Moltijoe commented
if i'm deeply mistaken in my beliefs, please feel free to argue your point and i'll reopen the PR