Make mulligan more interesting
yogstation13/Yogstation pull request #16790
Opened 2022-11-27 17:50 UTC by Simplehorror

# Document the changes in your pull request

imagine the wizard dying 10 minutes in so you have to sit through a fucking 1h45m bloodsucker round. 
this should make mulligan more interesting
# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: Added cult, nuclear, revolution, wizard, zombie to the mulligan list
rscdel: Bloodsuckers, traitorsuckers, heretics, traitorvamp removed from mulligan list.
/:cl:

2022-11-27 18:15 UTC, TheGamerdk requested changes

2022-11-27 18:15 UTC, TheGamerdk commented on code/game/gamemodes/zombie/zombie.dm
>  	enemy_minimum_age = 14
no

2022-11-27 20:44 UTC, Simplehorror commented on code/game/gamemodes/zombie/zombie.dm
>  	enemy_minimum_age = 14
ok

2022-11-28 04:37 UTC, neeshacark commented
i love this, except nukie which i dont think would work very well but yeah mulligans generally suck

2022-11-28 22:19 UTC, TheGamerdk requested changes
these should be TRUE/FALSE

2022-11-30 06:07 UTC, Simplehorror commented
> these should be TRUE/FALSE

this is how the rest of the code does it

2022-12-02 14:00 UTC, JamieD1 commented
Unfortunately those gamemodes are not always valid when wizard can spawn.

2022-12-02 14:00 UTC, closed without merging