speed potion now speeds up simplemobs rather than items
yogstation13/Yogstation pull request #16810
Opened 2022-11-27 22:53 UTC by Moltijoe

Mewsy hitlist

-=Speed Potion=-
im told that this can be paired with stable red to somehow give a permanent speed boost- tho i havent tested this yet
-=Possible Solutions to it=-
*a rework of the item = makes simplemobs human speed when applied
*make it an actual drinkable small speed potion, giving like 15% speed boost for a time with some negative attached to it

too much overlap with stabilized red, now it makes the gimmick of making a bunch of sentient simplemobs actually kinda fun

:cl:  
tweak: speed potion now speeds up simplemobs rather than items
/:cl:

2022-11-27 23:00 UTC, Simplehorror commented
honestly just make it a bottle of meth or ephedrine

2022-11-27 23:09 UTC, drderp3635 commented
meth goliaths?

2022-11-27 23:26 UTC, tattax commented on code/modules/research/xenobiology/xenobiology.dm
> +	if(!istype(target, /mob/living/simple_animal))
```suggestion
	if(!isanimal(target))
```

2022-12-01 19:00 UTC, MajManatee commented
guaranteed this will never be used again.

2022-12-01 23:54 UTC, ReddicusDragon requested changes
can I become a monkey, have this used on me, then be switched back to a human and run around faster?

2022-12-02 00:36 UTC, Moltijoe commented
> can I become a monkey, have this used on me, then be switched back to a human and run around faster?

contrary to popular belief monkeys aren't simple mobs, they're one of the very few carbon mobs that isn't a human subclass

2022-12-02 09:10 UTC, Simplehorror commented
> guaranteed this will never be used again.

yah

2022-12-02 13:16 UTC, ReddicusDragon commented
> > can I become a monkey, have this used on me, then be switched back to a human and run around faster?
> 
> 
> 
> contrary to popular belief monkeys aren't simple mobs, they're one of the very few carbon mobs that isn't a human subclass

Hmm ok

2022-12-02 14:05 UTC, JamieD1 approved these changes

2022-12-02 14:05 UTC, merged