Remove the fireball wand from the toy shop
yogstation13/Yogstation pull request #16828
Opened 2022-11-28 19:17 UTC by Simplehorror

# Document the changes in your pull request

Wow, this was actually really well hidden. I don't know if they were trying to hide it from maintainers or players. Maybe could replace with a one use door wand or something since a fireball is pretty good
# Spriting

# Wiki Documentation

None needed, this wasn't on the wiki.
# Changelog

:cl:  
mapping: Remove the fireball wand from the toy shop
/:cl:

2022-11-28 20:04 UTC, UltraBigRat commented
yeah replacing it with a shoddy door or tele wand could be neat,

2022-11-28 21:27 UTC, MajManatee commented
my secret fireball :(

2022-11-29 01:54 UTC, ToasterBiome requested changes
replace don't remove

2022-11-29 07:32 UTC, Reed0506 commented
could just make it into a real wand of nothing

2022-11-30 06:07 UTC, Simplehorror commented
replace it with WHAAAAAt

2022-11-30 17:02 UTC, MajManatee commented
3 use healing wand

2022-12-01 03:26 UTC, Simplehorror commented
> 3 use healing wand

lol

2022-12-01 23:32 UTC, ReddicusDragon commented
why would the coders name it fireball/inert inert to me means it wouldn't fuckin work

2022-12-01 23:33 UTC, ReddicusDragon approved these changes

2022-12-01 23:33 UTC, ReddicusDragon requested changes
upon looking at this again, replace it with something instead

2022-12-02 09:11 UTC, Simplehorror commented
stop backseat maintaining

2022-12-02 09:11 UTC, Simplehorror commented
also im not messing around with the map editor again

2022-12-02 09:11 UTC, closed without merging

2022-12-02 13:17 UTC, ReddicusDragon commented
> stop backseat maintaining

Bibby told me a while ago to go review PRs kekw