Majestic Manatee donor item changes & dog tag addition
yogstation13/Yogstation pull request #16826
Opened 2022-11-28 17:38 UTC by MajManatee

# Document the changes in your pull request
Changes my donor item from a hat to be a box with a had and my brand new dog tags

also adds a space where orca forgot to put one like a nerd

# Spriting

Ill do this when i get home from work

# Changelog

:cl:  
rscadd: Dope ass dog tags for myself
experimental: Snowflake items
/:cl:

2022-12-01 00:30 UTC, cuackles commented
show how the worn sprite looks ingame on a suit

2022-12-01 23:37 UTC, ReddicusDragon requested changes

2022-12-01 23:37 UTC, ReddicusDragon commented on code/modules/clothing/under/accessories.dm
> +	desc = "Two small metal tags, connected with a thin piece of chain that hold important health infomration. And everything needed for a tombstone..."
```suggestion
	desc = "Two small metal tags, connected with a thin piece of chain that hold important health information. And everything needed for a tombstone..."
```

2022-12-02 01:32 UTC, cuackles approved these changes

2022-12-02 14:10 UTC, merged