remove steam vent table exploit
yogstation13/Yogstation pull request #16835
Opened 2022-11-28 22:26 UTC by Simplehorror

# Document the changes in your pull request

fixes exploit where you can stack these to make them impassable
# Spriting

# Wiki Documentation

# Changelog

:cl:  
bugfix: remove steam vent table exploit
/:cl:

2022-11-28 22:26 UTC, ynot01 commented
break the vent

2022-11-28 22:28 UTC, TheGamerdk requested changes
use one_per_turf on the recipe instead

2022-11-28 22:28 UTC, Moltijoe commented
> break the vent

they're not supposed to be walls, they're supposed to be line of sight blockers

2022-11-28 22:31 UTC, Simplehorror commented
> use one_per_turf on the recipe instead

tables are not a recipe

2022-11-28 22:45 UTC, TheGamerdk commented
> > use one_per_turf on the recipe instead
> 
> tables are not a recipe

what?

2022-11-28 22:45 UTC, Rdrazga commented
Tbf it’s only an exploit because people can’t figure out how to climb over tables, also the vent takes like 3 hits to break. (Don’t remove this please I just discovered it and I like how fun it is to do)

2022-11-28 22:45 UTC, Simplehorror commented
> > > use one_per_turf on the recipe instead
> > 
> > 
> > tables are not a recipe
> 
> what?

someone build steam vent.
steam vent not dense
someone build table on top of steam vent

2022-11-28 22:46 UTC, Simplehorror commented
i should just make it so the table appears on top

2022-11-28 22:46 UTC, Simplehorror commented
> Tbf it’s only an exploit because people can’t figure out how to climb over tables, also the vent takes like 3 hits to break. (Don’t remove this please I just discovered it and I like how fun it is to do)

this is an old one i remember doing this llol

2022-11-28 22:46 UTC, Rdrazga commented
> 

fair trade

2022-11-28 22:48 UTC, Rdrazga commented
Now if you want to look at something that does actually need fixing is that the vents even when not on hide pressure plates and skewers

2022-11-28 22:50 UTC, Rdrazga commented
The tables are also prob a bit too hard to break which is what makes this good to begin with. Even without the vents the tables are just a great ‘screw you’ to crew trying to get in

2022-11-28 23:04 UTC, Firewolf34 commented
>someone build steam vent.
>steam vent not dense
>someone build table on top of steam vent

This should be in the PR description, would be more clear

2022-11-29 20:18 UTC, TheGamerdk commented
> > > > use one_per_turf on the recipe instead
> > > 
> > > 
> > > tables are not a recipe
> > 
> > 
> > what?
> 
> someone build steam vent. steam vent not dense someone build table on top of steam vent

i misread

2022-11-29 20:19 UTC, TheGamerdk requested changes
do this without fastprocess

2022-11-29 21:37 UTC, Simplehorror commented
cant

2022-11-29 21:37 UTC, closed without merging