makes the vxtvul hammer as deadly as i wanted to make it, but i was too scared to do it before
yogstation13/Yogstation pull request #16832
Opened 2022-11-28 21:45 UTC by Skrem7

# Document the changes in your pull request

Two things

1) The Vxtvul Hammer now has a block chance of 30 that exclusively works in melee IF it's wielded because otherwise unlike every other competitive melee weapon it has zero defense against stun batons which is SUPER SCARY and icky when you really should be able to use its handle to block stuff because that's fucking BADASS

2) A charged hit now has 100 AP and does a total of 50 damage, instead of just throwing and paralyzing people. The throw and paralyze have stuck around, because the throw can really save someone by sending them very far from the person who clearly intends to kill them. Also, it does a lot more damage to everything else, so why doesn't it do a shitton of damage to people?

For some context, the wielded force of the weapon normally is 28 force with 50 AP.

# Wiki Documentation

Numbers and description will require adjusting on Guide to Combat

# Changelog

:cl:  
tweak: The force and AP of the Vxtvul Hammer have been significantly increased while it's supercharged
tweak: The Vxtvul Hammer offers 30 block chance against melee ONLY IF it's being held in both hands
/:cl:

2022-11-28 21:57 UTC, Moltijoe commented
I'm not biased i swear

2022-11-28 22:00 UTC, UltraBigRat commented
based now pirates can bash kneecaps in

2022-11-28 22:00 UTC, ynot01 commented
reduce by 10 damage, 50 is ridiculous

2022-11-28 22:00 UTC, TheRyeGuyWhoWillNowDie commented
Hugbox

2022-11-28 22:06 UTC, Moltijoe commented
> Hugbox

i'm gonna hug your face with my hammer

2022-11-29 00:09 UTC, Moltijoe commented on code/game/objects/items/twohanded.dm
>  		armour_penetration = 50
could be initial(armour_penetration) 
that way if base armour pen gets changed in the future this doesn't need to get updated

2022-12-01 23:30 UTC, ReddicusDragon commented on code/game/objects/items/twohanded.dm
>  		armour_penetration = 50
I concur

2022-12-01 23:30 UTC, ReddicusDragon requested changes
code looks fine besides the suggestion Moltijoe made

2022-12-02 00:03 UTC, ReddicusDragon approved these changes

2022-12-02 14:15 UTC, JamieD1 approved these changes

2022-12-02 14:15 UTC, merged