The Grimdark Arsenal
yogstation13/Yogstation pull request #16843
Opened 2022-11-29 01:38 UTC by MajManatee

# Document the changes in your pull request
In the grim darkness of the far future...
...There is only war.

Adds an assortment of 40k Themed weapons, a new ERT to make use of them, and uniforms. 

TASK LIST
Weaponry:
- [ ] Lasgun
- [ ] Longlas
- [ ] Las Pistol
- [ ] Hotshot Lasgun
- [ ] Bolt Pistol
- [ ] Flamer
- [ ] Plasma Rifle
- [ ] Plasma Pistol

Other:
- [ ] Guardsman Uniform & Armor
- [ ] Sergeant Uniform & Armor
- [ ] ERT
- [ ] Crate for admin spawning (Request)

Optional:
- [ ] Better sounds?
- [ ] Orderable through cargo?

# Spriting

Sprites are mostly final, bar the plasma rifle which has been requested changes already.
That being said, nothing can't be changed, and I'm open to opinions.

Additional in-game pictures will be provided closer to project completion

![image](https://user-images.githubusercontent.com/74586965/204415937-ed6a976d-6b52-46c8-9261-770f1ba850fa.png)

# Wiki Documentation

Addition of all weapons and gear to uh a page with weapons? idk what yall do on the wiki.

# Changelog

:cl:  
rscadd: Adds 40k weapons, ERT, and assorted gear.
soundadd: New weapon SFX for guns
imageadd: Guns, Armor, Uniforms, Etc. 
wip: This is work in progress
/:cl:

2022-11-29 21:18 UTC, Potototatoh commented
bloat

2022-11-29 21:37 UTC, Moja10 commented
Amazing shit! Just needs a Bolt-gun

2022-11-30 21:51 UTC, MajManatee commented
Ready, Bar that one sprite. Currently being worked on.

2022-11-30 23:24 UTC, MajManatee commented
ok its ready :)

2022-12-01 02:09 UTC, Marmio64 commented
this is neat and all but yeah, all this bloat and it'll probably only be used once when it's merged and probably one or two more times every year at most. I'd probably cut out the weapons asides from bolter and one lasgun. We also already have a chainsaw sword sprite that chap and inquisitor ert get.

2022-12-01 02:16 UTC, LoliconSlayer commented
Make an actual attempt at filling out the wiki documentation section for this PR.

> Addition of all weapons and gear to uh a page with weapons? idk what yall do on the wiki.

This is not acceptable.

2022-12-01 03:34 UTC, Anvilman6 requested changes
Please provide proper wiki document for these changes

2022-12-01 04:04 UTC, ReddicusDragon commented
games workshop lawsuit when

2022-12-01 04:13 UTC, ReddicusDragon requested changes
Please fix the english mistakes when you have a moment!

2022-12-01 04:13 UTC, ReddicusDragon commented on code/modules/clothing/outfits/imperial.dm
> +	desc = "Cuts through Flesh, Bone, and most types of metal as if it wasnt there."
flesh and bone should probably be lowercase

2022-12-01 04:13 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A relic of a weapon. Despite being immesnsely powerful, its aquired a reputation of being essentially a flashlight."
immensely is misspelled here, as is acquired! Please fix it when you get a moment

2022-12-01 04:13 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A Sniper variant of the lasgun. Despite being immesnsely powerful, its aquired a reputation of being essentially a flashlight. "
Sniper should be lowercase in the description as it is not a proper noun nor the starting word in the sentence. Once again, immensely is misspelled and acquired is misspelled.

2022-12-01 04:13 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A smaller, pistol sized version of the lasgun. Despite being immesnsely powerful, its aquired a reputation of being essentially a flashlight."
immensely is misspelled here, as is acquired! Please fix it when you get a moment

2022-12-01 04:13 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "An amped-up version of the lasgun. One of the few models to not be regarded as completley useless by its users."
completely is misspelled here! Please fix it when you have a moment. "by its users" should be "by it's users." Possessive here, as we're referring to the gun's users.

2022-12-01 04:17 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A relic of a weapon. Despite being immesnsely powerful, its aquired a reputation of being essentially a flashlight."
change "its acquired" to "it has acquired" to clear up ambiguous speech as well, please

2022-12-01 04:18 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A Sniper variant of the lasgun. Despite being immesnsely powerful, its aquired a reputation of being essentially a flashlight. "
change "its acquired" to "it has acquired" to clear up ambiguous speech as well, please

2022-12-01 04:18 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A smaller, pistol sized version of the lasgun. Despite being immesnsely powerful, its aquired a reputation of being essentially a flashlight."
change "its acquired" to "it has acquired" to clear up ambiguous speech as well, please

2022-12-01 04:29 UTC, MajManatee commented on code/modules/clothing/outfits/imperial.dm
> +	desc = "Cuts through Flesh, Bone, and most types of metal as if it wasnt there."
Ya it should
😏

2022-12-01 16:15 UTC, MajManatee commented
Wiki Documentation updated, Spelling fixed

2022-12-01 16:16 UTC, ReddicusDragon commented
Thank, will review asap

On Thu, Dec 1, 2022 at 11:16 AM Manatee ***@***.***> wrote:

> Wiki Documentation updated, Spelling fixed
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yogstation13/Yogstation/pull/16843#issuecomment-1334014280>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIYLPDZWSSQLM3GEA6EGSQLWLDFMHANCNFSM6AAAAAASN6EOLY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-12-01 16:20 UTC, ReddicusDragon commented
Looks good to go English wise, w coder

2022-12-01 22:53 UTC, ReddicusDragon requested changes
should be good after this round

2022-12-01 22:53 UTC, ReddicusDragon commented on code/modules/clothing/outfits/imperial.dm
> +	name = "imperial Belt"
imperial should be Imperial
```suggestion
	name = "Imperial Belt"
```

2022-12-01 22:53 UTC, ReddicusDragon commented on code/modules/clothing/outfits/imperial.dm
> +	desc = "A set of standard issue flak armor for Imperial guardsmen. Protects you fairly well from most threats. This one feels lighter for some reason..." // No, you cant order ERT strength armor
```suggestion
	desc = "A set of standard issue flak armor for Imperial Guardsmen. Protects you fairly well from most threats. This one feels lighter for some reason..." // No, you cant order ERT strength armor
```

2022-12-01 22:53 UTC, ReddicusDragon commented on code/modules/clothing/outfits/imperial.dm
> +	desc = "A set of standard issue flak armor for Imperial guardsmen. Protects you fairly well from most threats."
```suggestion
	desc = "A set of standard issue flak armor for Imperial Guardsmen. Protects you fairly well from most threats."
```

2022-12-01 22:53 UTC, ReddicusDragon commented on code/modules/clothing/outfits/imperial.dm
> +	desc = "A set of kahki fatigues. Standard issue for imperial guardsmen"
```suggestion
	desc = "A set of khaki fatigues. Standard issue for Imperial Guardsmen"
```

2022-12-01 22:53 UTC, ReddicusDragon commented on code/modules/clothing/outfits/imperial.dm
> +	name = "flak Boots"
```suggestion
	name = "flak boots"
```

2022-12-01 22:53 UTC, ReddicusDragon commented on code/modules/cargo/packs.dm
> +	desc = "The might of the Emperor is at your command! Contains spare magazines for imperial weponry. Requires Armory access to open."
```suggestion
	desc = "The might of the Emperor is at your command! Contains spare magazines for Imperial weaponry. Requires Armory access to open."
```

2022-12-01 22:53 UTC, ReddicusDragon commented on code/modules/clothing/outfits/imperial.dm
> +	desc = "Cuts through flesh, bone, and most types of metal as if it wasnt there."
```suggestion
	desc = "Cuts through flesh, bone, and most types of metal as if it wasn't there."
```

2022-12-01 22:53 UTC, ReddicusDragon commented on code/modules/projectiles/boxes_magazines/external/rechargable.dm
> +	desc = "A standard power-pack for las weaponry, this one expending more power into focusing shots so they land on far-away targets."
this one is non-issue, but what about a desc of "A standard power-pack for las weaponry, this one pouring more power into focusing shots so that they reach far-away targets."

2022-12-05 05:45 UTC, UltraBigRat commented
Seems like a neat thing for traitors to buy for guns instead of just null crates all the time. Although the pool does seem a little bloated, with the lasgun  and its variants seeming quite a bit weaker then the other stuff.

2022-12-07 16:01 UTC, MajManatee commented
thank goodness for the spell check bot named redd

2022-12-07 16:02 UTC, ReddicusDragon commented
👀

2022-12-07 22:13 UTC, Moltijoe requested changes

2022-12-07 22:13 UTC, Moltijoe commented on code/modules/projectiles/guns/energy/special.dm
> +			to_chat(user, span_warning("The gun begins to heat up in your hands! Careful!"))
instead of having a probability based notice, should probably just have a guaranteed notice with a cooldown to how often it is printed

2022-12-07 22:13 UTC, Moltijoe commented on code/modules/projectiles/guns/energy/special.dm
> +			M.fire_stacks += 3
please use adjust_fire_stacks

2022-12-09 17:50 UTC, ReddicusDragon submitted a review, later dismissed
I am very tired

2022-12-09 17:50 UTC, ReddicusDragon commented on code/modules/clothing/outfits/imperial.dm
> +	desc = "A well worn belt, standard issue among imperial guard forces."
```suggestion
	desc = "A well worn belt, standard issue among Imperial Guard forces."
```
Capitalization consistency

2022-12-09 17:50 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A sniper variant of the lasgun. Despite being immensely powerful, it has acquired  a reputation of being essentially a flashlight. "
```suggestion
	desc = "A sniper variant of the lasgun. Despite being immensely powerful, it has acquired  a reputation of being essentially a flashlight."
```

2022-12-09 17:50 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "An amped-up version of the lasgun. One of the few models to not be regarded as completely useless by it's users."
```suggestion
	desc = "An amped-up version of the lasgun. One of the few models to not be regarded as completely useless by its users."
```
I fucked up

2022-12-09 17:50 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic/pistol.dm
> +	desc = "A smaller, sidearm variant of the Bolter. Typically blowing people into chunks with every shot. Fires .75 caliber rounds."
```suggestion
	desc = "A smaller, sidearm variant of the Bolter. Typically blows people into chunks with every shot. Fires .75 caliber rounds."
```
Grammar is hard

2022-12-09 17:50 UTC, ReddicusDragon commented on code/modules/projectiles/guns/energy/special.dm
> +	desc = "A very deadly weapon used by high ranking members of the Imperium."
```suggestion
	desc = "A very deadly weapon used by high-ranking members of the Imperium."
```
Missed this

2022-12-09 17:50 UTC, ReddicusDragon commented on code/modules/projectiles/guns/energy/special.dm
> +	desc = "A very deadly weapon used by high ranking members of the Imperium."
```suggestion
	desc = "A very deadly weapon used by high-ranking members of the Imperium."
```

2022-12-09 18:40 UTC, MajManatee commented on code/modules/projectiles/guns/energy/special.dm
> +			to_chat(user, span_warning("The gun begins to heat up in your hands! Careful!"))
guess i gotta figure out how to do cooldowns

2022-12-09 18:50 UTC, MajManatee commented on code/modules/projectiles/guns/energy/special.dm
> +			M.fire_stacks += 3
ok fire guy

2022-12-09 18:51 UTC, Moltijoe commented on code/modules/projectiles/guns/energy/special.dm
> +			to_chat(user, span_warning("The gun begins to heat up in your hands! Careful!"))
COOLDOWN_DECLARE(name) as a variable
COOLDOWN_START(src, name, duration) to start the cooldown
COOLDOWN_FINISHED(src, name) to check if it's completed

2022-12-09 18:51 UTC, MajManatee commented
> I am very tired

you are gonna be fired at this rate

2022-12-09 18:58 UTC, MajManatee commented on code/modules/projectiles/guns/energy/special.dm
> +			to_chat(user, span_warning("The gun begins to heat up in your hands! Careful!"))
ill pretend that makes sense, ok

2022-12-10 07:20 UTC, Moltijoe approved these changes

2022-12-17 14:36 UTC, JamieD1 commented
Beg your pardon, plasma rifles in crates orderable from cargo,
Hope you are joking.

2022-12-17 15:31 UTC, Skrem7 commented
> Beg your pardon, plasma rifles in crates orderable from cargo,
> 
> Hope you are joking.

Working on it

2022-12-20 00:01 UTC, Skrem7 commented
> > Beg your pardon, plasma rifles in crates orderable from cargo,
> > Hope you are joking.
> 
> Working on it

I am no longer working on it (I'm tired of spending time on this and I don't think it's worth the return)

2023-01-01 13:12 UTC, JamieD1 commented
> > > Beg your pardon, plasma rifles in crates orderable from cargo,
> > > Hope you are joking.
> > 
> > 
> > Working on it
> 
> I am no longer working on it (I'm tired of spending time on this and I don't think it's worth the return)

:[

2023-01-07 01:13 UTC, KillerOrcaCora commented
Many of these sprites are very poor in quality and the volume of them is bloat, neither I nor cuackles should have to go through that much work when in reality you only should be porting maybe 2 or 1 Guns since we aren't Warhammer 4K themed server. I suggest making a new PR lowering the amount of stuff you're adding after the freeze so we can work with this better.

2023-01-07 01:14 UTC, MajManatee commented
ill re open this once you are banned again

2023-01-07 01:58 UTC, KillerOrcaCora commented
Suck my fat

2023-03-26 06:48 UTC, MajManatee commented
Hisa said "I want it" so i am re-opening it. Now no longer orderable through cargo :)

2023-03-26 06:51 UTC, Hislyna commented
Gamma ERT Gamma ERT

2023-03-26 17:38 UTC, solwashere commented
Manatee is a nerd

2023-03-26 20:50 UTC, cuackles commented
Christ that's a lot of sprites

2023-03-27 00:39 UTC, MajManatee commented
a couple
i added pictures

2023-03-27 01:15 UTC, Moltijoe approved these changes
can't find anything wrong with the code
and while it could be considered bloat, if that ever becomes a problem it can just be removed in the future

2023-03-27 13:29 UTC, MajManatee commented
shut yo goofy ass up about the b word

2023-03-28 01:38 UTC, kooarbiter commented
most of that stuff (at least the lasgun sprites) are ported directly from the old arch angel server. It was a good time, but maybe flooding yogs with 40k references is a bad idea (we dont even have that much stuff from dead space and alien, but chap has a hardsuit, techpriest robe, servo skull, and chainsword. I would be okay with giving secoffs the ability to reskin laser rifles for lasrifles though.

2023-03-28 03:57 UTC, MajManatee commented
this is purely admin spawn, and an ERT (also admin spawn)

2023-03-29 03:31 UTC, Moltijoe commented
![image](https://user-images.githubusercontent.com/108117184/228419600-d2f180ea-b589-479c-ac0a-c44ac9023258.png)

is it? also conflicts

2023-03-30 01:06 UTC, cuackles requested changes, later dismissed
ok so, the guard shoes when worn, are to heavily shaded, don't know if it counts as banding but it still doesn't look correct, it could be toned down a bit, the guard neck piece side sprites doesn't match with the front, side its only 2 pixels long but front has 5 pixels long, guard armor worn has the same issues as the boots, the shoulder pads and chesplate are to heavily shaded, rib parts are ok tho, the guard belt item is to dark and muddy, its hard to clearly see what it is,
guard shoes item has the same issue as the worn sprite, heavily shaded, the las pistol item sprite also the same issue, and last is the flamer mag item sprite that's shaded oddly where the light is at the center, that's the only issues i see the rest is from ok to very good, specially the commissar coat that one looks sick

2023-03-30 13:32 UTC, MajManatee commented
Biome has said he would work on making the requested changes

2023-04-02 20:19 UTC, Moltijoe commented
So, after starting to work on the battle royale, i want this added so i can add these items

2023-04-11 12:59 UTC, MajManatee commented
still waiting for biome to fix the issues

2023-04-13 14:28 UTC, MajManatee commented
maybe i should just get a different spriter...

2023-04-17 13:55 UTC, MajManatee commented
Ive been informed ill get the sprites in 2-3 weeks

2023-05-12 13:04 UTC, MajManatee commented
😭

2023-05-29 03:39 UTC, ToasterBiome approved these changes
will fix sprites in separate pr

2023-05-29 03:40 UTC, merged