removes the printable traitor items from the medlathe
yogstation13/Yogstation pull request #16844
Opened 2022-11-29 02:33 UTC by TheRyeGuyWhoWillNowDie

what if we stopped powercreeping implants?

these two are literally traitor items except they can't be pulled off of you and the wheelie implant is missing the one thing that makes it situational (the fact that it's VERY visible) and enabling more medliz/roboticist powergaming is not actually a good thing

# Changelog

:cl:  
rscdel: you cant print no slip implants and wheelie implants any more
/:cl:

2022-11-29 02:34 UTC, neeshacark commented
lock them under illegal tech instead

2022-11-29 02:39 UTC, Moltijoe commented
wheelies are traitor? they come from medbot amputation arcade machine

airshoes are the traitor item, the implant for that is in the uplink

> lock them under illegal tech instead

the noslip water one IS under illegal tech
it's literally just galosh implants

2022-11-29 02:47 UTC, TheRyeGuyWhoWillNowDie commented
printing zero slowdown galoshes that also prevent ice slipping is not a thing that medbay players need (outside of powergaming)
getting wheelie shoes requires getting lucky with an arcade machine (and being good at arcade games) while pressing a button to get them for free does not

2022-11-29 02:55 UTC, Moltijoe commented
> printing zero slowdown galoshes that also prevent ice slipping is not a thing that medbay players need (outside of powergaming) getting wheelie shoes requires getting lucky with an arcade machine (and being good at arcade games) while pressing a button to get them for free does not

the noslip implant being behind illegal is already enough of a restriction if you ask me
wheelie shoes being more restricted than where they are seems fair, but removing them entirely is overkill

2022-11-29 09:44 UTC, neeshacark commented
> printing zero slowdown galoshes that also prevent ice slipping is not a thing that medbay players need (outside of powergaming) getting wheelie shoes requires getting lucky with an arcade machine (and being good at arcade games) while pressing a button to get them for free does not

nor are most other implants, wtf is a md going to do with a cns rebooter or welding shield eyes? they get them because other jobs can get use of them. also n3d made ice not slip you when you wear mining boots/winter boots so I hardly think that's an issue. that being said apparently they ARE locked behind illegal tech anyway so i fail to see how this is at all a problem

2022-11-29 16:07 UTC, UltraBigRat commented
OH NO WHATEVER WILL WE DO, THE POWERGAMER PARAMEDIC IS IMMUNE TO THE JANITORS MOPPED FLOOR DEATH TRAP! AND THEY CAN UNCONTROLLABLY RUN INTO WALLS AT HIGH SPEEDS AND BREAK THEIR LEGS!

2022-11-29 17:29 UTC, Simplehorror commented
this is fun removal

2022-11-30 14:42 UTC, Moja10 commented
When I read the title, I was expecting something like "oh no did the dentcoders add an arm implant with a 40 damage scalpel or something" but instead its slippy willies and go fast. This is a nonissue, chemists can make all their speed chems and no one cares about slipping, slipping protection really is a relic from when slips hard stunned. I say these implants are fine

2022-12-01 22:41 UTC, ReddicusDragon reviewed
non-issue

2022-12-02 09:14 UTC, Simplehorror commented
we should probably remove soap from station seeing as it is a traitor item

2022-12-02 14:44 UTC, JamieD1 commented
> lock them under illegal tech instead

Do this

2022-12-06 20:59 UTC, MajManatee requested changes
see above

2022-12-08 01:19 UTC, closed without merging