Adds bikehorn "suppressor"
yogstation13/Yogstation pull request #16847
Opened 2022-11-29 04:04 UTC by Moltijoe

https://forums.yogstation.net/threads/7-bikehorn-suppressors-for-the-stechkin-ss13-server.25595/

making them attainable wasn't part of the bounty

the item
![item](https://user-images.githubusercontent.com/108117184/204435805-4f92390d-2bb9-42a5-86fc-b8eb8df22cd6.png)

when attached
![attached](https://user-images.githubusercontent.com/108117184/204435823-619cc02e-5a07-465a-b326-9dda79fecc64.png)

:cl:  
rscadd: Adds bikehorn suppressor
imageadd: adds icon for the bikehorn suppressor item and an overlay version for all existing suppressor variants
/:cl:

2022-11-29 04:11 UTC, cuackles commented
Sprite has a lot of banding and no outlines, i would recommend reducing the pallet to like 3 maybe 4 shades of reds, using the darker for the outline and using, you can probably just edit the actually honk horn using parts of the silencer to make it look attachable, the attached icon also seems a bit off, but i do not remember how the clasic silencer looks on the new sketching sprite so i would have to see that tomorrow to be able to give consice help

2022-11-29 04:13 UTC, cuackles commented
Actually maybe just flip the attached sprite upside down and add a slight outline and should be good, cus you can see that the sketching is illuminated at the top but the attached item is illuminated on the bottom and that breaks the something something look of it

2022-11-29 04:23 UTC, Moltijoe commented
> Sprite has a lot of banding and no outlines, i would recommend reducing the pallet to like 3 maybe 4 shades of reds, using the darker for the outline and using, you can probably just edit the actually honk horn using parts of the silencer to make it look attachable, the attached icon also seems a bit off, but i do not remember how the clasic silencer looks on the new sketching sprite so i would have to see that tomorrow to be able to give consice help

clown horn has a one direction shading
![image](https://user-images.githubusercontent.com/108117184/204438477-a9711a1c-2c2f-42f2-a29f-f7c7de9036e4.png)
suppressor has, pillow shading was it?

2022-11-29 04:27 UTC, Moltijoe commented
swapped it to pillot shading and reduced the number of reds used, how's this?
![image](https://user-images.githubusercontent.com/108117184/204438848-2e3a0c34-405f-455e-b6f7-f7de74cc862e.png)

2022-11-29 04:31 UTC, Moltijoe commented
new in-game images

![image](https://user-images.githubusercontent.com/108117184/204439362-1d015f59-cf03-49d9-bc60-e6f4d7f96153.png)

![image](https://user-images.githubusercontent.com/108117184/204439408-c3bf75c3-81cb-4466-9c41-b55ad426bd92.png)

2022-11-29 04:32 UTC, cuackles commented
> swapped it to pillow shading and reduced the number of reds used, how's this?
> ![image](https://user-images.githubusercontent.com/108117184/204438848-2e3a0c34-405f-455e-b6f7-f7de74cc862e.png)

Ok yeah i will probably never be able to unsee the banding and shading of the silencer now, ok so the new one, it does look better yes, but you should not be using pillow shading as, hhhhhhhhmmmmm i don't really know how to put it but it's not good practice, try to imagine it has a light source and according to that place lighter points near the light and darker where the imaginary light woundnt reach as easily, preferably make it follow the shading the sketching has to it's kept consistent while attached

2022-11-29 04:35 UTC, cuackles commented
> new in-game images
> 
> ![image](https://user-images.githubusercontent.com/108117184/204439362-1d015f59-cf03-49d9-bc60-e6f4d7f96153.png)
> 
> ![image](https://user-images.githubusercontent.com/108117184/204439408-c3bf75c3-81cb-4466-9c41-b55ad426bd92.png)
> 

Overlay looks better, me sleep now continue helping tomorrow but it's really close to where it has to be to be to be to be accepted

2022-11-29 04:51 UTC, Moltijoe commented
new has a border, but also shading

![image](https://user-images.githubusercontent.com/108117184/204441823-f1429889-8be7-49d6-9d69-9f2e2672b658.png)

2022-11-29 10:47 UTC, cuackles commented
Lots lots better, give me a few hours to finish all my human responsibilities and i will take a good look at it to see if there is anything that can be improved

2022-11-30 00:21 UTC, cuackles commented
ok after seeing the current icon files, I think the item is good and can be accepted but i would like to see if you are able to give the same shading and color correcting treatment that you gave to the item to the attachment sprite, mostly a noticeable outline and make the lips of the attachments be similar to each other, mainly the pistol one that looks like it was mushed and the lips go a bit to outwards

2022-11-30 02:59 UTC, Moltijoe commented
> ok after seeing the current icon files, I think the item is good and can be accepted but i would like to see if you are able to give the same shading and color correcting treatment that you gave to the item to the attachment sprite, mostly a noticeable outline and make the lips of the attachments be similar to each other, mainly the pistol one that looks like it was mushed and the lips go a bit to outwards

there's very little room to work with for the pistol one

2022-11-30 03:03 UTC, Moltijoe commented
![image](https://user-images.githubusercontent.com/108117184/204697630-c4983d46-7822-404d-9414-927de51bd05d.png)
fixed it up, but it still seems to connect weirdly, gonna make it 1 pixel shorter and shift it up by 1

2022-11-30 03:06 UTC, Moltijoe commented
![image](https://user-images.githubusercontent.com/108117184/204698060-72656031-fbb3-4bc9-a190-b5d84a893397.png)
i think this looks nicer

2022-11-30 23:41 UTC, cuackles approved these changes
honk

2022-12-01 03:02 UTC, ReddicusDragon requested changes

2022-12-01 03:02 UTC, ReddicusDragon commented on code/modules/projectiles/guns/ballistic.dm
> +	desc = "Advanced clown research has found that guns that honk shoot harder, faster and more accurately. (they don't)"
Please capitalize the T in "They"

2022-12-01 22:05 UTC, ReddicusDragon approved these changes
spelling wise, looks good. Have not checked the actual code in this PR itself.

2022-12-02 14:47 UTC, merged

2022-12-02 14:47 UTC, JamieD1 commented
god help us