Replaces sleep() with addtimer() in decon unit, and minor tweak
yogstation13/Yogstation pull request #16867
Opened 2022-11-30 12:12 UTC by warface1234455

Addtimer() is better

# Document the changes in your pull request
Replaces sleep() with addtimer() in decon unit
Adds missing opening sound

# Changelog

:cl:  
tweak: Replaces sleep() with addtimer() in decon unit
soundadd: Adds missing opening sound
/:cl:

2022-12-01 02:52 UTC, ReddicusDragon requested changes

2022-12-01 02:52 UTC, ReddicusDragon commented on code/game/machinery/decontamination.dm
> +	say("The decontamination process is completed, thank you for your patient.")
please update "patient" to "patience"

2022-12-01 03:26 UTC, warface1234455 commented on code/game/machinery/decontamination.dm
> +	say("The decontamination process is completed, thank you for your patient.")
I will put this in my other pr

2022-12-01 21:28 UTC, ReddicusDragon commented on code/game/machinery/decontamination.dm
> +	say("The decontamination process is completed, thank you for your patient.")
link me this pr when you submit it, brother

2022-12-01 21:33 UTC, ReddicusDragon requested changes

2022-12-01 21:33 UTC, ReddicusDragon commented on code/game/machinery/decontamination.dm
> +/obj/machinery/decontamination_unit/proc/decon_eject1()
recommend renaming this proc decon_eject_emag

2022-12-01 21:33 UTC, ReddicusDragon commented on code/game/machinery/decontamination.dm
> +/obj/machinery/decontamination_unit/proc/decon_eject2()
recommend renaming this proc just decon_eject

2022-12-02 00:20 UTC, warface1234455 commented on code/game/machinery/decontamination.dm
> +/obj/machinery/decontamination_unit/proc/decon_eject1()
I thought so yeah

2022-12-02 00:24 UTC, warface1234455 commented on code/game/machinery/decontamination.dm
> +	say("The decontamination process is completed, thank you for your patient.")
#16755

2022-12-02 12:48 UTC, ReddicusDragon approved these changes

2022-12-02 15:00 UTC, JamieD1 approved these changes

2022-12-02 15:00 UTC, JamieD1 commented
Conflicts

2022-12-02 15:02 UTC, warface1234455 commented
wha

2022-12-02 15:09 UTC, warface1234455 commented
fixed cornflake

2022-12-02 15:11 UTC, warface1234455 commented
@JamieD1

2022-12-05 02:51 UTC, merged