Grue antag/gamemode/thing
yogstation13/Yogstation pull request #16864
Opened 2022-11-30 06:04 UTC by Simplehorror

# Document the changes in your pull request

New antag stolen from vgstation
Most of the code is mine because vgstation has shoddy code
Sprites are not

A grue is spawned, the grue eats people to grow up and lay eggs. The more they eat, the stronger they become. They heal very quickly in the dark, and have darksight vision.

# Spriting

# Wiki Documentation

WIP

# Changelog

:cl:  
tweak: It is pitch black. You are likely to be eaten by a grue
/:cl:

## Opened for feedback and to see the reception of the concept so I don't work on something that gets closed instantly by bibble

2022-11-30 06:09 UTC, ToasterBiome commented
Aw I thought this was like Gru. From the Minions.

2022-11-30 06:10 UTC, Simplehorror commented
gru is from despicable me not minions

2022-11-30 06:12 UTC, Annoying-plant commented
I am getting flash backs to the RL craft modpack on minecraft

2022-11-30 06:13 UTC, Simplehorror commented
ive only played tekkit classic

2022-11-30 06:17 UTC, Rdrazga commented
NGL I really want this to just be sprited as Gru from Despicable Me now

2022-11-30 06:18 UTC, K4rlox commented
this seems like an alternative to shadowling, althru i whould like to try this out and how others whould enjoy this antag during a testmerge

2022-11-30 06:18 UTC, Cartlord commented
Grues on /vg/station fucking suck, though, so they could probably use some alterations - something that makes them less worthless as juveniles or less powerful as adults.
also please no we don't need a fourth darkness antag

2022-11-30 06:19 UTC, Simplehorror commented
> this seems like an alternative to shadowling, althru i whould like to try this out and how others whould enjoy this antag during a testmerge

I'd like to replace shadowlings with these

2022-11-30 06:20 UTC, Simplehorror commented
> Grues on /vg/station fucking suck, though, so they could probably use some alterations - something that makes them less worthless as juveniles or less powerful as adults. also please no we don't need a fourth darkness antag

Will look into it but do note that yogstation has more players than VG and they are on average worse at the game

2022-11-30 06:34 UTC, ynot01 commented
I like it, at a glance it's like a mix of xenos and slings; hp might need to be toned down a bit, id rather these be a lot weaker than xenos

2022-11-30 06:34 UTC, Simplehorror commented
xenos will be 100x better because they have a ranged hard stun

2022-11-30 07:10 UTC, Moltijoe commented
Always love more variety

2022-11-30 12:58 UTC, Marmio64 commented
We already have 3 darkness antags, this is just a self replicating nightmare that does the same thing: kill everyone.

2022-11-30 13:49 UTC, cuackles commented
I honestly like the idea, but i think they could fit more as a midround spawn, also the sprites are okish but if it proceeds with test merging or merging i will probably do something about it

2022-11-30 16:08 UTC, CMOisLing commented
Im for it, despite being another darkness antag I think they are unique enough to be interesting.

2022-11-30 17:54 UTC, Simplehorror commented
nightmare barely counts as an antag since they just die in maints as soon as a security officer glares at them

2022-11-30 18:36 UTC, chemistrymain2 commented
> We already have 3 darkness antags, this is just a self replicating nightmare that does the same thing: kill everyone.

i know i'm not supposed to be here but honestly shadowling has a lot of design flaws that grue doesn't

you can take grue and expand on it to become a full antagonist proper and avoid the main issues of sling being linear in terms of design and a steamroll conversion antag, and a lot of the mechanics from both can be integrated into it

oh also their darksight is badass

2022-11-30 20:17 UTC, Sniblet commented
Keeping the pressure vulnerability seems like a bad idea, and it sounds like they take light damage SUPER fast
Can't judge it beyond that until I've seen it

2022-12-01 02:56 UTC, ReddicusDragon requested changes
other than my gripes with spelling, looks pretty promising SimpleHorror

2022-12-01 02:56 UTC, ReddicusDragon commented on yogstation/code/modules/antagonists/grue/grue.dm
> +	to_chat(owner?.current?.client, span_warning("Bask in shadows to prepare to moult. The more sentient beings you eat, the more powerful you will become."))
this may be a Queens English vs American English issue, but moult my entire life has been molt

2022-12-01 02:56 UTC, ReddicusDragon commented on yogstation/code/modules/mob/living/simple_animal/hostile/grue/grue.dm
> +	to_chat(src, span_notice("You begin moulting."))
see other comment about spelling of molt

2022-12-01 03:25 UTC, Simplehorror commented on yogstation/code/modules/antagonists/grue/grue.dm
> +	to_chat(owner?.current?.client, span_warning("Bask in shadows to prepare to moult. The more sentient beings you eat, the more powerful you will become."))
yes

2022-12-01 03:25 UTC, Simplehorror commented on yogstation/code/modules/mob/living/simple_animal/hostile/grue/grue.dm
> +	to_chat(src, span_notice("You begin moulting."))
yep

2022-12-01 04:10 UTC, Marmio64 commented
> > We already have 3 darkness antags, this is just a self replicating nightmare that does the same thing: kill everyone.
> 
> i know i'm not supposed to be here but honestly shadowling has a lot of design flaws that grue doesn't
> 
> you can take grue and expand on it to become a full antagonist proper and avoid the main issues of sling being linear in terms of design and a steamroll conversion antag, and a lot of the mechanics from both can be integrated into it
> 
> oh also their darksight is badass

we already have darkspawn too though, which isn't linear with it's upgrades and while it can be a steamroll conversion antag it's optional for them and expensive. I don't think another darkness antag is needed unless this one is going to be made straight up superior to one of the existing ones, covers the role the previous one had, and is also unique enough to warrant not just changing darkspawn/nightmare/shadowling to be better.

2022-12-01 05:24 UTC, Simplehorror commented
time to remove nightmare in exchange for grue and then shadowling

2022-12-01 09:57 UTC, Simplehorror commented
OK this is ready for test merge I think

2022-12-01 18:12 UTC, ReddicusDragon commented
> OK this is ready for test merge I think

Switch this from draft if it is ready. I'm for a testmerge, won't hurt anything. Unless a maint takes a look and sees an issue

2022-12-01 20:49 UTC, The-Sun-In-Splendour commented
> nightmare barely counts as an antag since they just die in maints as soon as a security officer glares at them

he got a point though

2022-12-16 14:18 UTC, closed without merging