Show all antagonists (including traitor) in ghost orbit list
yogstation13/Yogstation pull request #16889
Opened 2022-12-01 10:33 UTC by Simplehorror

# Document the changes in your pull request

Easier for ghosts to find entertainment, metagamers aren't prohibited by this and will just check peoples bags or scan security, or so forth.

This also made no sense on shadowling because the first thing every shadowling does is talk to each other which outs them to ghosts instantly.

# Spriting

# Wiki Documentation

# Changelog

:cl:   
tweak: Show all antagonists (including traitor) in ghost orbit list
/:cl:

2022-12-01 18:35 UTC, UltraBigRat commented
Honestly pretty fair, would make being a ghost alot more entertaining. Only real downside is people would receive metaknowledge on all antags upon death, even very stealthy ones.

2022-12-01 20:10 UTC, Annoying-plant commented
Personally as someone who like to go stealth a lot as antag I feel like this could ruin rounds due to players who want to "win" using meta knowledge they receive while dead

2022-12-01 20:12 UTC, Sniblet commented
Ahelp those people. They can already find out if they put in some work, this just cuts out the work

2022-12-01 20:54 UTC, ReddicusDragon requested changes
update relevant antagonist files to not define show_to_ghosts as it's redundant if we set it to true by default

2022-12-01 21:57 UTC, cowbot92 commented
I'm okay with this, as a player I never really had felt like not knowing the antags would change whom I watch but if people feel like that they want to be able to watch the action happen directly then this would be a good feature. If people metagame then it's relatively easy to catch

2022-12-02 00:58 UTC, Tempolx commented
I like this. You can find out 99% of antags with observe, so this doesnt do anything but cut out work

2022-12-05 03:55 UTC, Moltijoe requested changes
Specifically stealth heavy antagonists like traitor and blood brother should probably remain as FALSE

2022-12-05 04:18 UTC, Simplehorror commented
> Specifically stealth heavy antagonists like traitor and blood brother should probably remain as FALSE Putting more strain on admins to handle ahelps isn't ideal

it's pretty easy to figure out who the traitors adn blood brothers are. especially blood brothers since they just start talking to eachother at round start

2022-12-05 04:22 UTC, Moltijoe commented
> it's pretty easy to figure out who the traitors adn blood brothers are. especially blood brothers since they just start talking to eachother at round start

it's not always immediately obvious and it just threatens to let people metagame
outside of those two antags i approve this pr
I will wait for someone else's opinion on the matter, see if they can change my mind

2022-12-05 05:36 UTC, Simplehorror commented
i meant this as a ghost, it's easy to figure out the antags as a ghost it just makes it less tedious, metagamers gonna metagame anyway

2022-12-05 16:18 UTC, Loldaddy5676 commented
can it be made so that you have to toggle the ability to see them and in return you cant join back in the round? there should always be a price.

2022-12-14 13:27 UTC, TheGamerdk commented
The Lord Emperor of Yogstation already shut this down once

2022-12-14 13:27 UTC, closed without merging