genetics power that lets you fire a bullet by throwing it
yogstation13/Yogstation pull request #16891
Opened 2022-12-01 10:49 UTC by Simplehorror

# Document the changes in your pull request

because it's cool
# Spriting

# Wiki Documentation

name: trigger finger
desc: This mutation lets you fire bullets simply by flicking them.
instability: 20
positive
# Changelog

:cl:  
rscadd: genetics power that lets you fire a bullet by throwing it
/:cl:

2022-12-01 10:54 UTC, ToasterBiome reviewed
make it break your arm unless you reinforce it

2022-12-01 11:00 UTC, Simplehorror commented
reinforcements are being removed soon

2022-12-01 11:11 UTC, TheGamerdk commented
> reinforcements are being removed soon

no they aren’t

2022-12-01 11:15 UTC, Simplehorror commented
#16773

2022-12-01 14:58 UTC, UltraBigRat commented
> make it break your arm unless you reinforce it

Would be a pretty sucky way of balancing it, if you want to balance it itd be better to just make it deal brute to the arm depending on the caliber (so things like chucking 38 does barely any harm while) while shotgun shells will deal high damage to your arm. I feel with that itd be pretty good for antags, theres alot of validhunting potential there though. With shit like geneticists running around  with a box of buckshot and shotgun hands

2022-12-01 20:37 UTC, ReddicusDragon commented
holy shit this is actually funny

2022-12-01 20:46 UTC, ReddicusDragon commented on code/datums/mutations/body.dm
> -		if (casing.BB)
can you please show me where BB is defined I am having a dumb moment

2022-12-01 20:47 UTC, ReddicusDragon commented on code/datums/mutations/body.dm
> -		if (casing.BB)
found it

2022-12-01 20:50 UTC, ReddicusDragon approved these changes
Code looks good

2022-12-01 21:05 UTC, MajManatee commented
cant wait to make pulse slugs and shoot them at antags with nothing but my hands

2022-12-01 21:30 UTC, ToasterBiome commented
> > make it break your arm unless you reinforce it
> 
> Would be a pretty sucky way of balancing it, if you want to balance it itd be better to just make it deal brute to the arm depending on the caliber (so things like chucking 38 does barely any harm while) while shotgun shells will deal high damage to your arm. I feel with that itd be pretty good for antags, theres alot of validhunting potential there though. With shit like geneticists running around with a box of buckshot and shotgun hands

who cares about balance (not me)

2022-12-01 21:53 UTC, Simplehorror commented on code/datums/mutations/body.dm
> -		if (casing.BB)
jeez how did you get to this

2022-12-01 21:53 UTC, Simplehorror commented
it should hurt your index finger

2022-12-01 23:06 UTC, Sniblet commented
I put the meteorshot in my mouth and bite down

2022-12-02 04:39 UTC, kooarbiter commented
literally catch these hands

2022-12-02 07:54 UTC, 00ze-cyclone commented
Absolutely no way lizbay will abuse the fuck out of this by printing mosin bullets with the autolathe they build at the start of every round yes yes.
Very useful mutation for me the non antag geneticists/MD/scientist/assistant because yeah I definitely need an undroppable gun and it’ll certainly not be used to validhunt.
Let’s give everyone a makeshift gauss rifle except concealable, or a makeshift shotgun with no jam chances, what could go wrong, nothing of course.
Excellent PR and will greatly improve the game.

2022-12-02 13:12 UTC, ReddicusDragon requested changes
Upon re-examining this PR, I suggest making a chance to fail and or a chance to just completely break your arm.

2022-12-02 18:41 UTC, MajManatee commented on code/datums/mutations/body.dm
> +	instability = 20
Should probably be increased, at least in its current state.

2022-12-03 00:39 UTC, chemistrymain2 commented
> Absolutely no way lizbay will abuse the fuck out of this by printing mosin bullets with the autolathe they build at the start of every round yes yes. Very useful mutation for me the non antag geneticists/MD/scientist/assistant because yeah I definitely need an undroppable gun and it’ll certainly not be used to validhunt. Let’s give everyone a makeshift gauss rifle except concealable, or a makeshift shotgun with no jam chances, what could go wrong, nothing of course. Excellent PR and will greatly improve the game.

honestly, while all of these are genuine concerns dude i doubt this is a very effective powergamey power due to how slow it is to pull a bullet out and then throw it, and how rapidly full your inventory would become

i'd personally say give it a downside like damaging your arm or costing stamina to do so per bullet, but if you're looking for powergame, 'guy throwing one bullet at a time at me' isn't significantly that powerful when literally anyone can get their hands on roughly equivalent bullshit with minimal effort themselves if they so choose to

obviously, it becomes more problematic with things like shotgun shells or mosin rounds, as you've pointed out, as that does hit very hard, so another alternative is to simply have increasing penalties the more powerful the bullet is-a single 10mm being less of an issue to propel than, say, a pulse round or mosin shot, which are very strong

the core idea is a cool concept, it just needs balancing

2022-12-03 00:42 UTC, chemistrymain2 commented
> Upon re-examining this PR, I suggest making a chance to fail and or a chance to just completely break your arm.

personally i'd say either there be a hard cap on the strength of the allowed projectile, a maximum damage for the allowed projectile, or just outright costing stamina and brute to use said projectiles in combination with the other two (or you could indeed go the whole mile and have sufficiently powerful projectiles outright break your arm)

an RNG chance is the least pleasant balancing method there is and ideally RNG goes away from combat, so a random chance to just break your arm makes it annoying for both user and victim,whereas if someone _knows_ they can't get away with using a buckshot shell without breaking their arm and knocking themselves down, that absolutely balances it out

2022-12-06 04:28 UTC, Moltijoe requested changes
Needs a drawback, 20 instability to basically get all ballistic guns (assuming you can get the ammo) is too strong since autolathes exist

Self Damage if not powered
limit on certain bullets it doesn't work for
Thank kinda stuff

2022-12-06 04:38 UTC, Simplehorror commented
what kinda bullets

2022-12-06 05:08 UTC, Moltijoe commented
> what kinda bullets

figure it out

2022-12-07 06:05 UTC, isotope436 commented
https://www.youtube.com/watch?v=1K17tnZ9S6Y

2022-12-07 16:33 UTC, MajManatee commented
Increase the instability, and maybe give it a cooldown. This is basically the balistic version of lizard firebreath

2022-12-08 07:37 UTC, Simplehorror commented
well humans dont have a race specific thing anymore, it is literally more advantageous to play lizard right now

2022-12-09 21:08 UTC, UltraBigRat commented
> well humans dont have a race specific thing anymore, it is literally more advantageous to play lizard right now

They do, its called asimov ai

2022-12-15 22:56 UTC, TheGamerdk commented
stale

2022-12-15 22:56 UTC, closed without merging