Blood brothers no longer need their entire team to escape, just one
yogstation13/Yogstation pull request #16896
Opened 2022-12-01 21:39 UTC by Simplehorror

# Document the changes in your pull request

In the end, blood brothers are just human tools. And I don't remember losing my emag and then the Syndicate saying I didn't win because I lost my emag or my emag went AFK in a locker.
This also opens up new avenues for blood brothers to explore, such as one suicidebombing brig (which he knows he can still win with)

# Spriting

# Wiki Documentation

Blood brothers no longer need their entire team to escape, just one
# Changelog

:cl:  
tweak: Blood brothers no longer need their entire team to escape, just one
/:cl:

2022-12-01 21:41 UTC, ynot01 commented
Should make sure the brother that escapes has all of the objectives completed (steal objs being forefront in my mind)

2022-12-01 21:42 UTC, Simplehorror commented
> Should make sure the brother that escapes has all of the objectives completed (steal objs being forefront in my mind)

steal objectives are only accomplished if you're on the shuttle iirc

2022-12-01 21:47 UTC, Simplehorror commented
for anyone against this PR: please tell me how TC-less traitor, except I have to babysit some 10 hour player who can barely move to get to the shuttle is fun. hijack BB is easier because I don't have to deal with that

2022-12-01 21:53 UTC, ReddicusDragon commented
while it may not be fun to you, it may be fun to others. Additionally, it basically removes the purpose of BB. You are supposed to take care of your brother. If you red-text because your brother is a 10 hour player, oh well, next time you're antag maybe you can do something different

2022-12-01 21:57 UTC, ReddicusDragon requested changes
overall a bad pr

2022-12-01 21:57 UTC, ReddicusDragon commented on code/game/gamemodes/objective.dm
> +	for(var/datum/mind/M in owners)
this loop literally returns this objective as complete if anyone in the owners list is considered escape. This is the epitome of shitcode.

2022-12-01 21:57 UTC, ReddicusDragon commented on code/game/gamemodes/objective.dm
> +		if (!considered_escaped(M))
what is this check for? You don't check in this proc if they're considered escaped to begin with

2022-12-01 22:01 UTC, Simplehorror commented on code/game/gamemodes/objective.dm
> +	for(var/datum/mind/M in owners)
yes thats the point

2022-12-01 22:01 UTC, Simplehorror commented on code/game/gamemodes/objective.dm
> +		if (!considered_escaped(M))
read the commit name

2022-12-01 22:02 UTC, Simplehorror commented
> while it may not be fun to you, it may be fun to others. Additionally, it basically removes the purpose of BB. You are supposed to take care of your brother. If you red-text because your brother is a 10 hour player, oh well, next time you're antag maybe you can do something different

i like how you literally admit i'm just fucked if i get a 10 hour player because there is 0 chance that he will be escaping alive. how is that fun?

2022-12-01 22:03 UTC, ReddicusDragon commented on code/game/gamemodes/objective.dm
> +		if (!considered_escaped(M))
Okay I see what you're doing here

2022-12-01 22:04 UTC, ReddicusDragon commented
> i like how you literally admit i'm just fucked if i get a 10 hour player because there is 0 chance that he will be escaping alive. how is that fun?

The point of blood brother is to collaborate. You try your best. Your blood brother dying is outside of your control. Just because you are antag does not mean you will greentext every time, bud.

2022-12-01 22:04 UTC, ReddicusDragon commented
Plus BB has communication implants now

2022-12-01 22:04 UTC, Simplehorror commented
> > i like how you literally admit i'm just fucked if i get a 10 hour player because there is 0 chance that he will be escaping alive. how is that fun?
> 
> The point of blood brother is to collaborate. You try your best. Your blood brother dying is outside of your control. Just because you are antag does not mean you will greentext every time, bud.

yes it's out of my control so why should I be punished

2022-12-01 22:07 UTC, ReddicusDragon commented
> > > i like how you literally admit i'm just fucked if i get a 10 hour player because there is 0 chance that he will be escaping alive. how is that fun?
> > 
> > 
> > The point of blood brother is to collaborate. You try your best. Your blood brother dying is outside of your control. Just because you are antag does not mean you will greentext every time, bud.
> 
> yes it's out of my control so why should I be punished

Your issue is you viewing a blood brother who is new to being blood brother as a punishment. They're a new player, they are learning. If you want them to improve you should be helping them. If you don't try to teach them, they won't improve and will be just as bad as a 200 hr blood brother

2022-12-01 22:34 UTC, Therandomhoboo commented
This kinda defeats the point of a BB, the point is teamwork and to leave together. If you leave without your BB then whats the point in having them? Might as well just be Blood Son instead of Blood Brothers at that point

2022-12-01 22:45 UTC, Simplehorror commented
blood brothers' point is not teamwork exactly, it just replaces the currency of TC with another guy which can be useful or it can be detrimental. this removes the detrimental part.

2022-12-02 18:47 UTC, MajManatee commented
the point of BB is 100% teamwork.
This PR basically just makes it so you are a solo traitor with no TC, and have someone else to talk to about it.
Turn off BB if you dont like working together.

2022-12-02 20:13 UTC, Simplehorror commented
> the point of BB is 100% teamwork. This PR basically just makes it so you are a solo traitor with no TC, and have someone else to talk to about it. Turn off BB if you dont like working together.

that's awesome. i'm going to turn on blood brother and if I get it with you I'm going to act completely clueless and randomly die to some environment hazard half way through the round, and we'll see if you turn it off or not

2022-12-02 22:14 UTC, TheGamerdk commented
Blood brothers is meant to be cooperative. This includes escaping. We’re open to alternative ideas though, keep doing what you’re doing simplehorror :)

2022-12-02 22:14 UTC, closed without merging