Some devil fixes for bugs I noticed when I forced the gamemode and ruined a round
yogstation13/Yogstation pull request #16900
Opened 2022-12-01 23:41 UTC by TheRyeGuyWhoWillNowDie

Fixes some bugs
Makes it substantially more obvious that you are not an antagonist after selling your soul

# Changelog

:cl:  
tweak: Some devil features have received QoL
bugfix: Some devil bugs have been fixed
/:cl:

2022-12-01 23:43 UTC, Simplehorror approved these changes

2022-12-02 23:32 UTC, ToasterBiome requested changes

2022-12-02 23:32 UTC, ToasterBiome commented on code/modules/antagonists/devil/devil.dm
> +		H.equip_to_slot_or_del(new /obj/item/clothing/glasses/sunglasses(H), SLOT_GLASSES)
I'm sussing among us

2022-12-02 23:34 UTC, TheRyeGuyWhoWillNowDie commented on code/modules/antagonists/devil/devil.dm
> +		H.equip_to_slot_or_del(new /obj/item/clothing/glasses/sunglasses(H), SLOT_GLASSES)
QoL

2022-12-04 00:53 UTC, ToasterBiome requested changes
no sunglasses

2022-12-04 00:58 UTC, TheRyeGuyWhoWillNowDie commented
ok

2022-12-04 01:02 UTC, ToasterBiome approved these changes

2022-12-04 01:05 UTC, merged