Bloodsucker buffs and spellchecks (again)
yogstation13/Yogstation pull request #16904
Opened 2022-12-02 04:51 UTC by Sniblet

I'll atomize the spellchecks if this is unpopular

# Document the changes in your pull request

This antag is SO SAD.

- Blood altars are less demanding early on and candelabra are less demanding, candelabra removes mindshields in 20 seconds instead of 60 seconds.
- Frenzy now removes damage slowdown instead of reducing(?) it (I don't know if that even worked).
- Should mute the victim of an aggressive feeding for the duration of the feeding, because you have fangs in your throat. **(This is my own code so it probably doesn't work, will have to test it)**
- Toreador don't get a humanity hit for trying to bite rats, because bloodsuckers can't even try to eat rats anyway because code.
- Lunge is instant at rank 2 instead of 3, mesmerize mutes at rank 1 instead of 2 (abilities start at rank 0).
- Changelings, cultists, heretics, and obsessed(?!) can be vassalized, because we don't have dynamic every round and them meeting should be as cool as it sounds.
- Spellchecks all over. Truly, truly baffling errors in here.

# Wiki Documentation

- Aggressive feed mutes the target
- Lunge is instant at rank 2 instead of 3, mesmerize mutes at rank 1 instead of 2
- Spellcheck the wiki page, you spelled subservient wrong

# Changelog

:cl:   
Tons of bloodsucker tweaks:
tweak: Blood altars require less blood and fewer hearts before rank 8
tweak: Candelabra costs 50 blood from 150 to start de-shielding, takes 20 seconds to finish
tweak: Frenzy removes damage slowdown instead of decreasing it
tweak: Aggressive feeding mutes the victim for the duration
tweak: Predatory Lunge is instant at rank 2 instead of 3, Mesmerize mutes at 1 instead of 2
tweak: Changelings, cultists, heretics, and obsessed can be vassalized
spellcheck: Spellchecked even more in this catastrophe of a gamemode
/:cl:

2022-12-02 05:40 UTC, Simplehorror commented
this antag is bad because the core mechanics are bad and it cannot be fixed with number changing

2022-12-02 06:16 UTC, Moltijoe commented
> * Frenzy now removes damage slowdown instead of reducing(?) it (I don't know if that even worked).

it worked, reducing damage slowdown isn't what you'd think though, it just let you get lower health before applying the slowdown rather than reducing the slowdown itself

2022-12-02 06:43 UTC, Sniblet commented
> this antag is bad because the core mechanics are bad and it cannot be fixed with number changing

It can be improved

2022-12-02 07:40 UTC, SomeguyManperson commented
> > * Frenzy now removes damage slowdown instead of reducing(?) it (I don't know if that even worked).
> 
> it worked, reducing damage slowdown isn't what you'd think though, it just let you get lower health before applying the slowdown rather than reducing the slowdown itself

This may not have been noticable as blood is used to determine nutriment and anyone with mood disabled would therefore be getting hunger slowdown while in frenzy

2022-12-02 08:01 UTC, Sniblet commented
Under VtM lore I can't think of any reason why blood should dictate nutriment, it's not an actual need so much as an addiction
Every day I ask myself what clowns coded this antag

2022-12-03 00:25 UTC, chemistrymain2 commented
> > this antag is bad because the core mechanics are bad and it cannot be fixed with number changing
> 
> It can be improved

true

i personally feel like bloodsucker has to go the way of the dinosaur-heretic does everything it does but better-but it might as well be made not dogshit

2022-12-07 00:11 UTC, Moltijoe requested changes

2022-12-07 00:11 UTC, Moltijoe commented on code/modules/antagonists/bloodsuckers/powers/targeted/lunge.dm
> +		If below level 2, you will have to charge your lunge for a while. During this time you'll have to stand still for lunge to work.\n\
should this say 2 both times?

2022-12-07 08:33 UTC, Sniblet commented on code/modules/antagonists/bloodsuckers/powers/targeted/lunge.dm
> +		If below level 2, you will have to charge your lunge for a while. During this time you'll have to stand still for lunge to work.\n\
.>1 = 2, <2 =/ 2
It shouldn’t

2022-12-08 03:28 UTC, Moltijoe commented on code/modules/antagonists/bloodsuckers/powers/targeted/lunge.dm
> +		If below level 2, you will have to charge your lunge for a while. During this time you'll have to stand still for lunge to work.\n\
could it be rephrased so both numbers are the same then
if i mixed it up at a glance, others certainly will too

2022-12-08 04:04 UTC, Sniblet commented on code/modules/antagonists/bloodsuckers/powers/targeted/lunge.dm
> +		If below level 2, you will have to charge your lunge for a while. During this time you'll have to stand still for lunge to work.\n\
tried to do it lazily with as little change as possible, not registering that the gamemode's typical godawful communication skills would make me look the fool

2022-12-08 04:08 UTC, Sniblet commented
Oh what do you mean it's been DNC for 4 days
Well if Github doesn't tell me the problem in language I understand I'll probably just be removing the mute on bite

2022-12-08 04:39 UTC, Sniblet commented
I concede
It is no longer in this PR
I'll think about aggressive bite muting some other day, and it'll get nuked for making bloodsuckers OP/not modular/some other thing I can't understand

2022-12-08 19:13 UTC, Moltijoe commented
> I concede It is no longer in this PR I'll think about aggressive bite muting some other day, and it'll get nuked for making bloodsuckers OP/not modular/some other thing I can't understand

ah whoops, musta missed that
just change it to
ADD_TRAIT(target, TRAIT_MUTE, BLOODSUCKER_TRAIT);
and
REMOVE_TRAIT(target, TRAIT_MUTE, BLOODSUCKER_TRAIT);

target. isn't required because the proc is a universal proc that gets the target from it's parameters

2022-12-08 23:59 UTC, Moltijoe requested changes
Please atomize this

2022-12-09 08:53 UTC, Sniblet commented
Frick that’s gonna be a lot of feature-frozen PRs
Give me a bit

2022-12-09 16:45 UTC, Moltijoe commented
> Frick that’s gonna be a lot of feature-frozen PRs Give me a bit

just the spell checks from the buffs, not each one

2022-12-10 07:15 UTC, Moltijoe approved these changes
everything checks out

2022-12-15 23:06 UTC, merged