Lets overcharging Ethereals transfer power into APCs + eating buff
yogstation13/Yogstation pull request #16905
Opened 2022-12-02 06:10 UTC by Moltijoe

Closes: #16901

When they overcharge they're force to just suffer for a while
Now they can use grab intent on an APC to channel extra power into it

Also, recharging using lights is super tedious since it only give 5 charge per channel
for reference, it takes 2000 charge to become full from starved

:cl:  
rscadd: Lets overcharging Ethereals transfer power into APCs
tweak: Ethereals get more nutrition from feeding on lights
/:cl:

2022-12-04 03:10 UTC, Firewolf34 commented
love all the wonderful Ethereal-related PRs lately :) They are a cool race! 

How does this impact #16901 if it gets merged?

2022-12-04 03:25 UTC, Moltijoe commented
> love all the wonderful Ethereal-related PRs lately :) They are a cool race!

They don't get enough love, if preternis and ipc didn't exist i'd definitely main ethereal

2022-12-05 05:53 UTC, MajManatee approved these changes
etherials need the love

2022-12-09 00:01 UTC, ReddicusDragon requested changes
please atomize this

2022-12-09 00:28 UTC, Moltijoe commented
> please atomize this

don't make me atomize your face

2022-12-12 20:06 UTC, MajManatee commented
atomization not requred

2022-12-12 20:42 UTC, Moltijoe commented
> atomization not requred

too late

2022-12-15 22:55 UTC, merged