Changes Asteroid Station Botany,Service hall, and Kitchen.
yogstation13/Yogstation pull request #16922
Opened 2022-12-04 01:59 UTC by RG4ORDR

I thought the Service Hall and Botany were really weirdly designed, with 2 entrances into botany, and two long very long walks for Bartender,Chef, and Botanist needing to undertake to access their department lathe. Now it's much easier all three to gain access to their lathes, and botany has had its layout cleaned up, and shrunk by 1 tile. Kitchen gained 1 tile to offset the more snugger druglab. Pushed the tables up to make the hallway the actual 3 tiles it deserves. 

Only issue I know is that I don't know how to assign the access to doors. So the newly added airlocks to my knowledge have no access restrictions.

2022-12-04 03:16 UTC, Moltijoe commented
pictures?

2022-12-04 03:31 UTC, warface1234455 commented
Man you didn't even move the axolotl, it's clipping through the smartfridge between botany and kitchen

2022-12-04 03:56 UTC, RG4ORDR commented
> Man you didn't even move the axolotl, it's clipping through the smartfridge between botany and kitchen

Wallaxolotl

2022-12-04 04:00 UTC, RG4ORDR commented
> pictures?

![image](https://user-images.githubusercontent.com/10237741/205473620-ba2bae08-d1c7-429e-8e2e-90a0b30e8f50.png)
![image](https://user-images.githubusercontent.com/10237741/205473636-d80f2456-1c85-41f2-ba32-92c17592d4c2.png)
![image](https://user-images.githubusercontent.com/10237741/205473640-87f9dd77-c21e-43ed-9156-914be125ed34.png)

2022-12-04 04:59 UTC, warface1234455 commented
> > Man you didn't even move the axolotl, it's clipping through the smartfridge between botany and kitchen
> 
> Wallaxolotl. Also it wasn't on the fastdmm2 editor AFAIK.

what do you mean it's not on fastdmm2, did you update your code, did you check the axolotl below the smartfridge?

2022-12-04 05:01 UTC, warface1234455 commented
![image](https://user-images.githubusercontent.com/89688125/205475362-10233de9-b458-40dc-90f2-eefcebf03cc0.png)

2022-12-06 02:28 UTC, ToasterBiome requested changes
1) move holopad in botany
2) move camera that's attached to the railing in botany
3) move the axolotl

2022-12-06 02:31 UTC, ToasterBiome commented
![image](https://user-images.githubusercontent.com/5091394/205794021-10694537-97be-4ef6-bb76-f020a13118d5.png)
4) plating under the windows, not floor tiles
5) move (or delete) the lightswitch on the right. closer to the floor if you're keeping it
6) there's a light on the window, move that
7) add kitchen shutters to the window

![image](https://user-images.githubusercontent.com/5091394/205794175-1c381bcb-5d10-4953-95fa-964cab6cc1ac.png)
8) fix this area, make it the hallway area jutting out

2022-12-06 02:32 UTC, ToasterBiome commented
![image](https://user-images.githubusercontent.com/5091394/205794319-ba93bbc1-a4b4-4daf-9f56-d33b0f8d5c8a.png)
This top door in botany is missing firelocks

![image](https://user-images.githubusercontent.com/5091394/205794346-cd219107-1aac-4f51-bb52-928b5ee03411.png)
plating below the tables instead of flooring

![image](https://user-images.githubusercontent.com/5091394/205794422-017fc6d4-633e-4251-9b1e-b9cda69141ec.png)

This light is backwards

2022-12-06 02:33 UTC, ToasterBiome commented
![image](https://user-images.githubusercontent.com/5091394/205794483-9be48a82-fc34-4504-9fcb-9f49c84802f2.png)
Light in hallway

![image](https://user-images.githubusercontent.com/5091394/205794497-0dbc8ea3-5b34-413c-9fcf-b46aa6ec5a51.png)

Beacon under wall here, should be moved

2022-12-06 03:59 UTC, warface1234455 commented
Damn that's a lot to fix lol

2022-12-06 04:00 UTC, warface1234455 commented
> ![image](https://user-images.githubusercontent.com/89688125/205475362-10233de9-b458-40dc-90f2-eefcebf03cc0.png)
 Also the light is backward top left corner, fix that too

2022-12-06 07:40 UTC, RG4ORDR commented
> Damn that's a lot to fix lol

Hey it was my first time actually pushing this and some of the things got hidden, Bip wasn't even on the screen when I was editing

2022-12-07 00:19 UTC, ToasterBiome requested changes
![image](https://user-images.githubusercontent.com/5091394/206053972-adc3c323-f8ee-4e0a-acb7-d2968dcba8dd.png)
Too many plants

![image](https://user-images.githubusercontent.com/5091394/206054009-8bbcf634-aa81-4cc7-8472-ac0dca40ad95.png)
regular floor under 2 tables but then dining floor under 4 of them

![image](https://user-images.githubusercontent.com/5091394/206054062-964fd6b9-7931-413a-a1b0-576ad1ce9a49.png)
replace the floor with a wall under the smartfridge so it's air tight

![image](https://user-images.githubusercontent.com/5091394/206054106-cab5ec2f-3eeb-4211-a2e1-a53417385b66.png)
stacked decals

![image](https://user-images.githubusercontent.com/5091394/206054204-9835192a-1066-4213-8665-9878daff2a04.png)
how about the holopad moved to the right 2 tiles 

![image](https://user-images.githubusercontent.com/5091394/206054264-ca1b6232-c7d8-429f-8774-99d74a57dc40.png)
No firelocks + incorrect area on the door

![image](https://user-images.githubusercontent.com/5091394/206054313-8d8207d4-c377-4cdd-9917-df9c51e1e15a.png)
Back room has no APC, no atmos pipes, no air alarm, no fire alarm. The APC for it is still above hydro backroom.

![image](https://user-images.githubusercontent.com/5091394/206054444-82cb12c2-e38c-4f48-84ec-5f3b187bb2f4.png)
Pipes through walls + wall blocking maint

![image](https://user-images.githubusercontent.com/5091394/206054533-9446bf83-f284-4972-816c-86d654fb1590.png)
attack of the wrench

![image](https://user-images.githubusercontent.com/5091394/206054581-2ba78c47-0064-4d7b-bfd6-3b4a3dda7740.png)
air alarm blocked by sink

![image](https://user-images.githubusercontent.com/5091394/206054744-033adf54-be2b-44dd-893b-1013cc284e87.png)
wire through wall

![image](https://user-images.githubusercontent.com/5091394/206054833-50c48a93-d55e-4f9c-a702-4d49d2a2777c.png)
pipe through railing

2022-12-08 23:54 UTC, ToasterBiome requested changes
REMOVE THE WALL WRENCH

2022-12-09 21:34 UTC, ToasterBiome requested changes
![image](https://user-images.githubusercontent.com/5091394/206799657-bd9a1222-b052-4dd5-b1ce-44653d9f5a00.png)

This APC isnt supposed to be here anymore since there's a copy of it in the service backroom.

2022-12-28 00:42 UTC, ToasterBiome approved these changes

2022-12-28 00:49 UTC, merged