Revert "Removes mindswap from the spellbook (only)"
yogstation13/Yogstation pull request #16939
Opened 2022-12-04 14:39 UTC by Simplehorror

Reverts yogstation13/Yogstation#15785

since when is "it gets a bit confusing for admins" a reason to remove something? if it is confusing to admins, then tooling needs to be fixed and not this innocent spell

2022-12-04 14:40 UTC, TheGamerdk commented
fix the tooling then

2022-12-04 14:53 UTC, Simplehorror commented
there's nothing wrong with it aside admins being whiny

2022-12-04 19:09 UTC, neeshacark commented
staff are perfectly capable of seeing who occupied a body at any given time, we literally have replays and logs also show ckeys and we can see all the people who occupied a body. i don't understand the mindswap removal

2022-12-04 20:22 UTC, HisaHoshimo commented
As stated before, it causes confusion which ends up in rule breaks. It was removed for a reason and we do not need spells which can be used as a means for accidental or intentional grief.

2022-12-04 22:09 UTC, Moja10 commented
No, it is legitimately one of the worst admin headaches caused by in-game items/abilities, the problem is not whether admins can track who swapped who, when, where. What the headache is is keeping track of PLAYERS knowing who swapped who, when, where. There could be numerous witnesses, numerous swaps, swaps missed by players, missing information all the time in these events. It is not reasonable at all to track who is keeping track of what swaps, what swaps they missed, what actions they saw per swap, all for numerous different people involved in the shenanigans. It routinely leads to people committing wrong actions on wrong information, which in some circumstances could be totally fine and SS13 classic experience, in other circumstances, the wrong people get beat to death on a witchhunt because someone swore on their mum that he really really was the wizard and needed to be beat to death. 

I would say on average, confusing for admins isn't a solid reason on its own to remove something, but in this circumstance, I think it is gone for good reason.

2022-12-05 04:15 UTC, Simplehorror commented
> As stated before, it causes confusion which ends up in rule breaks. It was removed for a reason and we do not need spells which can be used as a means for accidental or intentional grief.

right, that's the point of the spell

2022-12-05 20:15 UTC, Moltijoe requested changes
It was removed because of it being unfun for victims and more so for causing admin headaches, neither of these problems have been addressed

2022-12-06 03:11 UTC, Simplehorror commented
fighting a wizard isn't always going to be fun?

2022-12-06 03:34 UTC, Moltijoe commented
> fighting a wizard isn't always going to be fun?

https://www.youtube.com/watch?v=FdxEUL18ySY

2022-12-06 03:42 UTC, Simplehorror commented
in that vein we should also remove fireball, the traps, spacetime distortion because it's not fun for the victim

2022-12-06 04:05 UTC, Moltijoe commented
> in that vein we should also remove fireball, the traps, spacetime distortion because it's not fun for the victim

different sort of unfun, those are temporary, body swap is permanent and can leave you permanently crippled for the round
a better comparison would be the staff of change

2022-12-06 04:14 UTC, Moltijoe commented
> different sort of unfun, those are temporary, body swap is permanent and can leave you permanently crippled for the round a better comparison would be the staff of change

or changeling transformation sting, which i specifically coded to be temporary

2022-12-08 07:58 UTC, Simplehorror commented
ok so make mindswap revert after so much time (this kills the spell and any fun you could have had by turning into the captain)

2022-12-08 19:10 UTC, Moltijoe commented
> ok so make mindswap revert after so much time (this kills the spell and any fun you could have had by turning into the captain)

wizard isn't the role-steal antag, that's changeling

2022-12-08 19:36 UTC, Simplehorror commented
wizard is the do whatever the fuck he wants antag until admins get mad that an antagonist is being antagonistic apparently

2022-12-15 22:54 UTC, TheGamerdk commented
stale

2022-12-15 22:54 UTC, closed without merging