Emp immunity implant overloads if emped too often
yogstation13/Yogstation pull request #16967
Opened 2022-12-05 22:24 UTC by Moltijoe

Currently this is the main culprit of the nukie bundle being too strong
Augmentation is incredibly powerful with a downside of emp weakness, the implant completely removed that

They can take 5 emps total within a 10 second period, getting hit by an emp refreshes the 10 second period
After 5 emps, the implant will shut off for 10 seconds, getting hit by an emp during this time will reset the cooldown timer

:cl:  
tweak: Emp immunity implant overloads if emped too often
/:cl:

2022-12-07 16:15 UTC, MajManatee approved these changes
Codewise its fine, but i dont like the idea

2022-12-07 16:43 UTC, Moltijoe commented
> Codewise its fine, but i dont like the idea

it's mainly because of how strong the implant is alongside the augmentation bundle

2022-12-09 00:09 UTC, ReddicusDragon requested changes
English fixes, please

2022-12-09 00:09 UTC, ReddicusDragon commented on code/game/objects/items/implants/implant_misc.dm
> +	desc = "An implant that completely protects from electro magnetic pulses. It will shut down briefly if triggered too often."
```suggestion
	desc = "An implant that completely protects from electro-magnetic pulses. It will shut down briefly if triggered too often."
```

2022-12-09 00:09 UTC, ReddicusDragon commented on code/modules/uplink/uplink_items.dm
> +			Finally, it includes an implant to render the subject and their innards immune to EMP, however, it will shut down briefly if triggered too often. Repair of body will still require a welder and wir
```suggestion
			Finally, it includes an implant to render the subject and their innards immune to EMP; however, it will shut down briefly if triggered too often. Repair of the body will still require a welder and wires."
```

2022-12-15 22:51 UTC, merged