You can now buy an ERT from the communications console
yogstation13/Yogstation pull request #16975
Opened 2022-12-06 04:32 UTC by Simplehorror

# Document the changes in your pull request

You can now buy an ERT from the comms console. 
Red ERT = 100000 credits
Blue = 30000
Amber = 10000
Janitor = 20000
Holy = 50000

Admins are VERY RELUCTANT to spawn ERTs even when everything has gone to shit, so making it a code-based thing makes it more consistent which is more fun to the players, because you know when to expect it, and it makes it easier to balance since it's not admin-only anymore.

# Spriting

# Wiki Documentation

todo

# Changelog

:cl:  
tweak: You can now buy an ERT from the communications console
/:cl:

2022-12-06 04:34 UTC, MajManatee commented
you realize that 100k is made in like...30 seconds?

2022-12-06 04:34 UTC, Simplehorror commented
Limitations I want to add:

- You can only order after so many security officers have died/became antagonists
- You can only order an ERT once
- You can only order certain ERTs if there is station destruction > 20%

2022-12-06 04:34 UTC, Moltijoe requested changes
Should probably cap it at 1 ERT per shift

2022-12-06 04:34 UTC, Simplehorror commented
> you realize that 100k is made in like...30 seconds?

blame jungleland

2022-12-06 04:34 UTC, Simplehorror commented
yeah that's the plan

2022-12-06 04:35 UTC, MajManatee commented
> > you realize that 100k is made in like...30 seconds?
> 
> blame jungleland

I make 3-400k EVERY SHIFT on lava land.

2022-12-06 04:36 UTC, Rdrazga commented
Why not WC ert instead of regular, also where my peacekeepers at?

2022-12-06 04:36 UTC, Simplehorror commented
> > > you realize that 100k is made in like...30 seconds?
> > 
> > 
> > blame jungleland
> 
> I make 3-400k EVERY SHIFT on lava land.

it takes you 1h45m to get 400k, which means this seems pretty balanced to me seeing as if you need a red ert you won't be making that much money

2022-12-06 04:36 UTC, Simplehorror commented
> Why not WC ert instead of regular, also where my peacekeepers at?

this is WC ert, and peacekeepers looked sucky

2022-12-06 04:36 UTC, Rdrazga commented
Also only allow it if red alert is on

2022-12-06 04:37 UTC, Simplehorror commented
> Also only allow it if red alert is on

yeah fair point

2022-12-06 04:37 UTC, Rdrazga commented
> > Why not WC ert instead of regular, also where my peacekeepers at?
> 
> this is WC ert, and peacekeepers looked sucky

Yeah they are sucky but are basically more police focused then amber, if you are missing a sec team being able to order 2-3 peacekeepers to replace them would be good

2022-12-06 04:38 UTC, Rdrazga commented
Also would be very fun if emmaged comms console could order clowns

2022-12-06 04:39 UTC, Simplehorror commented
i was thinking about it letting you order a lone op

2022-12-06 04:40 UTC, MajManatee commented
> > > > you realize that 100k is made in like...30 seconds?
> > > 
> > > 
> > > blame jungleland
> > 
> > 
> > I make 3-400k EVERY SHIFT on lava land.
> 
> it takes you 1h45m to get 400k, which means this seems pretty balanced to me seeing as if you need a red ert you won't be making that much money

have you played cargo? ever?
I get to 400k by the 30 minute mark, pretty consistently

2022-12-06 04:40 UTC, Rdrazga commented
> i was thinking about it letting you order a lone op

Maybe an extra traitor buddy with objectives to help you and no (or low) tc not a full on line op

2022-12-06 04:41 UTC, Simplehorror commented
> > > > > you realize that 100k is made in like...30 seconds?
> > > > 
> > > > 
> > > > blame jungleland
> > > 
> > > 
> > > I make 3-400k EVERY SHIFT on lava land.
> > 
> > 
> > it takes you 1h45m to get 400k, which means this seems pretty balanced to me seeing as if you need a red ert you won't be making that much money
> 
> have you played cargo? ever? I get to 400k by the 30 minute mark, pretty consistently

i have, unless cargo got buffed in the last year or so i don't remember getting that much outside of stocks

2022-12-06 04:42 UTC, Rdrazga commented
> > > > > > you realize that 100k is made in like...30 seconds?
> > > > > 
> > > > > 
> > > > > blame jungleland
> > > > 
> > > > 
> > > > I make 3-400k EVERY SHIFT on lava land.
> > > 
> > > 
> > > it takes you 1h45m to get 400k, which means this seems pretty balanced to me seeing as if you need a red ert you won't be making that much money
> > 
> > 
> > have you played cargo? ever? I get to 400k by the 30 minute mark, pretty consistently
> 
> i have, unless cargo got buffed in the last year or so i don't remember getting that much outside of stocks

Selling plasma, engineering rad collectors

2022-12-06 04:43 UTC, Simplehorror commented
> > > > > > > you realize that 100k is made in like...30 seconds?
> > > > > > 
> > > > > > 
> > > > > > blame jungleland
> > > > > 
> > > > > 
> > > > > I make 3-400k EVERY SHIFT on lava land.
> > > > 
> > > > 
> > > > it takes you 1h45m to get 400k, which means this seems pretty balanced to me seeing as if you need a red ert you won't be making that much money
> > > 
> > > 
> > > have you played cargo? ever? I get to 400k by the 30 minute mark, pretty consistently
> > 
> > 
> > i have, unless cargo got buffed in the last year or so i don't remember getting that much outside of stocks
> 
> Selling plasma, engineering rad collectors

i sold all the mats and i never got close to 400k

2022-12-06 04:46 UTC, Rdrazga commented
Depends on mining team but it is possible, for a normal cargo team though when you also take into account that they are likely buying stuff throughout a shift 100k or less is fairly common point for a station to be around. This does not include mass selling matts for emergencies or breaking into the cargo budget

2022-12-06 04:47 UTC, Rdrazga commented
If an atmos tech does set up a proper money rad collector though cargo will have multiple millions by shift end

2022-12-06 04:48 UTC, Simplehorror commented
and you'll get one red ert congrats

2022-12-06 05:21 UTC, Sniblet commented
.s CULT CONFIRMED
.e MONEY COLLECTORS NOW
.u SELL PLASMA
20 minutes pass, cult gets wiped in a fair and exciting battle involving tactical energy guns

2022-12-06 05:25 UTC, Simplehorror commented
sounds like cargo was powercreeped while I was away if they can get 100k this easy

2022-12-06 06:14 UTC, Hopekz commented
I think this PR can be good by only allowing the purchase of the weaker ERT's just to replenish security like peacekeepers then saving the rest for admins 

Also remember that the shutter on centcom for ERT's used to start  closed so if that still happens you'd have to find a solution for that so the bought ERT's can get down without admin intervention 

Ideally if I was making this PR I'd just allow peacekeepers for now because they are sec reinforcements and you said you wanted to make it to where people can call these after sec is dying. That way the station can only replenish their sec for a large-ish credit cost.

2022-12-06 06:23 UTC, Simplehorror commented
peacekeepers are dogshit and all they're good for is stopping the clown being a menace

2022-12-06 06:24 UTC, Moltijoe commented
> peacekeepers are dogshit and all they're good for is stopping the clown being a menace, and will die to any intelligent antag

PERFECT! so they'll fit right in with the rest of sec

2022-12-06 06:27 UTC, Hopekz commented
> peacekeepers are dogshit 

I made peacekeepers so I know they're just basically reskinned security officers to replace a dead sec.

They have security officer access to re-arm in sec and if they can't re-arm they have a basic security officer loadout with disabler (wt with rubber rounds) stun baton (stun prod) and cuffs.

2022-12-06 06:33 UTC, Simplehorror commented
right but nobody needs these. if all of security is wiped out you don't need more redshirts, you need something to kill the guys killing security. it's a solution without a problem

2022-12-06 06:40 UTC, Hopekz commented
> right but nobody needs these. if all of security is wiped out you don't need more redshirts, you need something to kill the guys killing security. it's a solution without a problem. giving antags more fodder to kill isn't going to solve anything

You can try your way but I have a feeling they won't merge it if you can spawn all the ERT's vs just the ones to replenish sec.

Remember it's okay for antagonists to win the round. The "solution" shouldn't be to actually provide a guaranteed dub for the station but rather to reintroduce more people into the round.

Either way I think this is a good idea for a PR even if I don't 100% believe in the current execution.

2022-12-06 06:53 UTC, Simplehorror commented
this isn't getting merged no matter what I do

2022-12-06 07:23 UTC, K4rlox commented
like this PR, on my way to spawn 10 red ERTs to replace entire station

2022-12-06 07:26 UTC, Moltijoe requested changes
Money based respawns, probably needs the balance council to look at this
Regardless, should cost more, have less ERT selection, and be limited to one per shift
Should also make sure that the ERT can actually get to the station once they spawn
not to mention the mission breifing is kind of a big part of ERTs

2022-12-06 08:38 UTC, RG4ORDR commented
This both a stupid and interesting idea that I wanna see how it'd work out test merged.

2022-12-07 13:29 UTC, Marmio64 commented
Should only allow peacekeeper erts to be bought, with a per alive player limit on ert numbers (more ert the more dead people), and they should be relatively expensive. Money can often be no object and antags can be quickly swamped by powerful erts, so they should def be very weak. Also make sure admins can deny purchases.

2022-12-07 16:18 UTC, Simplehorror commented
> Should only allow peacekeeper erts to be bought, with a per alive player limit on ert numbers (more ert the more dead people), and they should be relatively expensive. Money can often be no object and antags can be quickly swamped by powerful erts, so they should def be very weak. Also make sure admins can deny purchases.

that defeats the whole point of the pr

2022-12-08 05:43 UTC, boba247 commented
I think this could be good to try, currently, the station's only recourse to major emergencies is to call the shuttle. I do think Holy, Blue, and Red are too OP to start. We should start with Amber, peacekeeper, janitor, and clowns. Can revisit balance once the lesser-powered teams are tried out.

2022-12-08 23:48 UTC, ReddicusDragon commented
If this isn't done, would you consider switching it to a draft please, SimpleHorror?

2022-12-08 23:50 UTC, Moltijoe commented
> Limitations I want to add:
> 
> * You can only order after so many security officers have died/became antagonists
> * You can only order an ERT once
> * You can only order certain ERTs if there is station destruction > 20%
> * You can only order after a fair amount of time

make this a draft PR

2022-12-09 00:21 UTC, ReddicusDragon commented on code/datums/ert.dm
> +			//log_game("[key_name(ERTOperative)] has been selected as an [ert_antag.name]") | yogs - redundant
how is this redundant, or am I missing something here

2022-12-09 05:09 UTC, Simplehorror commented on code/datums/ert.dm
> +			//log_game("[key_name(ERTOperative)] has been selected as an [ert_antag.name]") | yogs - redundant
came from the code i pasted

2022-12-09 05:09 UTC, Simplehorror commented
idk how to draft a pr after you open it

2022-12-09 05:13 UTC, Moltijoe commented
> idk how to draft a pr after you open it

![image](https://user-images.githubusercontent.com/108117184/206628935-457f2151-cf24-4f7f-8a08-f82629c99f5d.png)

2022-12-10 09:28 UTC, TheGamerdk commented
ERTs are specifically meant to be only spawned based on admin judgement

2022-12-10 09:28 UTC, closed without merging