Rad particles no longer deal burn damage to mob that has 100 rad armor, minor rad particles tweak
yogstation13/Yogstation pull request #16978
Opened 2022-12-06 09:15 UTC by warface1234455

Radsuit stops irradiation from rad particles but not burn damage?? Silly!

# Document the changes in your pull request
- Rad particles no longer deal burn damage to mob that has 100 rad armo
- Rad particles from rad anomaly is higher than standard rad particles by 100 (500)

# Wiki Documentation
In doc of changes

# Changelog

:cl:  
tweak: Rad particles no longer deal burn damage to mob that has 100 rad armo
tweak: Rad particles from rad anomaly is higher than standard rad particles by 100 (500)
/:cl:

2022-12-07 16:17 UTC, MajManatee requested changes
Atmomize the rad goat changes

2022-12-07 16:20 UTC, warface1234455 commented
> Atmomize the rad goat changes

What else

2022-12-07 17:49 UTC, MajManatee commented
do not have a rad goat nerf stuf with with the rad particle changes. Put it in a seperate PR

2022-12-08 00:54 UTC, ShoziOffical commented
> do not have a rad goat nerf stuf with with the rad particle changes. Put it in a seperate PR

alr

2022-12-08 23:31 UTC, Moltijoe approved these changes

2022-12-08 23:38 UTC, MajManatee approved these changes
nice thanks

2022-12-08 23:38 UTC, merged