darkspawn get trolled less from incendiary rounds
yogstation13/Yogstation pull request #16988
Opened 2022-12-06 22:23 UTC by TheRyeGuyWhoWillNowDie

who is the clown ass who created this glorified rock paper scissors gamemode

# Changelog

:cl:  
tweak: darkspawn heatmod down to 1.25 from 1.5
tweak: lightward sigil now removes fire stacks over time
/:cl:

2022-12-06 22:23 UTC, LoliconSlayer commented
i ded

2022-12-06 22:24 UTC, Moltijoe requested changes

2022-12-06 22:24 UTC, Moltijoe commented on yogstation/code/modules/mob/living/carbon/human/species_types/darkspawn.dm
> +			H.fire_stacks--
please use adjust_fire_stacks

2022-12-06 22:24 UTC, TheRyeGuyWhoWillNowDie commented on yogstation/code/modules/mob/living/carbon/human/species_types/darkspawn.dm
> +			H.fire_stacks--
☝🤓

2022-12-07 02:17 UTC, Simplehorror commented
ok how do i kill them now

2022-12-07 04:45 UTC, Simplehorror commented on yogstation/code/modules/mob/living/carbon/human/species_types/darkspawn.dm
> +			H.fire_stacks--
lmfao

2022-12-07 19:37 UTC, TheRyeGuyWhoWillNowDie commented
> ok how do i kill them now

attack them until their hit points fall to 0 while keeping your hit points above 0

2022-12-08 01:20 UTC, closed without merging