THE GREAT AIRSOFT COSPLAY BUFF
yogstation13/Yogstation pull request #17002
Opened 2022-12-07 23:28 UTC by Skrem7

# Document the changes in your pull request

RIGHT NOW THESE ARE WORTHLESS WHAT IF THEY WEREN'T??

Cool applications include:
- Doing... surgery faster?
- Cuffing faster!
- Strangling people faster!
- Building faster!
- I THINK standing up faster!
- And MORE

Also makes the tactical fingerless gloves a lot cooler considering you are spending TWO HARD EARNED TC on something that denies you insuls (AI valid go brrr) AND will have sec call you out in a flash

# Wiki Documentation

Fingerless gloves should probably mention they let you do stuff faster now

# Changelog

:cl:  
tweak: Fingerless gloves now make your do_after coefficient 0.8 what it normally is (do stuff 20% faster!)
tweak: do_after coefficient on the tactical fingerless gloves has been lowered to 0.5 from 0.8 (because they aren't metashielded)
/:cl:

2022-12-07 23:46 UTC, ynot01 commented
sure lets try it

2022-12-07 23:50 UTC, Mqiib commented
cant wait to stack do_after buffs and debrain someone on the floor on 0.2 seconds

2022-12-08 03:07 UTC, Moltijoe approved these changes
0.8 and 0.5 might end up being too strong, but why not
i like the removal of shock protection since they're literally the least resistant gloves

2022-12-08 03:10 UTC, Moltijoe requested changes
scratch that, these are just the regular fingerless gloves? 
the kind that you can find all over the place?
no way it can be 0.8, that makes them better for surgery than surgical gloves

bigboss version i'm fine with

2022-12-08 03:56 UTC, Skrem7 commented
> scratch that, these are just the regular fingerless gloves? the kind that you can find all over the place? no way it can be 0.8, that makes them better for surgery than surgical gloves

Do you want NO coefficient on fingerless then because I'm seeing absolutely no benefits for doing surgery with... surgery gloves (which is dumb)

2022-12-08 18:13 UTC, Moltijoe commented
> Do you want NO coefficient on fingerless then because I'm seeing absolutely no benefits for doing surgery with... surgery gloves (which is dumb)

if someone ends up adding surgery speed to latex gloves, then these can be added

2022-12-08 18:51 UTC, Moltijoe commented
> if someone ends up adding surgery speed to latex gloves, then these can be added

#17019

2022-12-08 19:20 UTC, Skrem7 commented
> > if someone ends up adding surgery speed to latex gloves, then these can be added
> 
> 
> 
> #17019 

With values nerfed, are they fine then

2022-12-08 21:48 UTC, K4rlox commented
tactical fingerless gloves are just lesser gloves of the north star
why not change gloves of the north star too?

2022-12-08 22:56 UTC, Moltijoe approved these changes

2022-12-09 00:22 UTC, Marmio64 commented
they're just decorative fashion gloves that dont need a random 'buff' especially since they're not very hard to get

2022-12-09 00:30 UTC, Skrem7 commented
> they're just decorative fashion gloves that dont need a random 'buff' especially since they're not very hard to get

I would 100% agree but for some reason you can use wirecutters on black gloves to make them more useless so I was like "huh what if there were a reason to do it for sec or something"

2022-12-09 00:32 UTC, Skrem7 commented
> tactical fingerless gloves are just lesser gloves of the north star why not change gloves of the north star too?

they aren't: gloves of the north star ONLY apply to harm, whereas tactical applies to every intent

2022-12-15 22:48 UTC, merged