Shadowling veil nullifies glowy for SOME TIME and enthrall removes it for ALL TIME
yogstation13/Yogstation pull request #17004
Opened 2022-12-08 01:39 UTC by Sniblet

# Document the changes in your pull request

Veil turns off glowy's light for 120 seconds. If someone is enthralled, their glowy is removed

# Changelog

:cl:  
tweak: Veil turns off glowy's light for 120 seconds. If someone is enthralled, their glowy is removed
/:cl:

2022-12-08 01:40 UTC, RG4ORDR commented
Finally the glowy genetics monopoly is being torn down.

2022-12-08 02:18 UTC, GraveHat commented
You should close that other PR since this is objectively better.

2022-12-08 02:35 UTC, MajManatee commented
120 is an AWFULLY long time
surely 60 is more reasonable

2022-12-08 03:02 UTC, Sniblet commented
60 is shorter than thralling a mindshielded person
70 means you have to get that mindshielded person to a safe area very fast
80 is alright...
But I mean, if you're smart at all you have other lights. What does it matter?

2022-12-08 03:06 UTC, Moltijoe approved these changes
2 minutes seems good, it might end up being too long, but it can always be changed in a later pr if that is found to be the case

2022-12-08 03:18 UTC, Therandomhoboo commented
2 minutes is too long, considering veil takes 20 seconds to refresh... you might as well just remove glowy at this point.

Make it literately 5 seconds shorter than the veil cd or just make a PR to remove glowy.

2022-12-08 03:25 UTC, Moltijoe commented
> 60 is shorter than thralling a mindshielded person 70 means you have to get that mindshielded person to a safe area very fast 80 is alright... But I mean, if you're smart at all you have other lights. What does it matter?

could always tag team a mindshielded person, one thralls, the other veils

2022-12-08 03:35 UTC, Therandomhoboo commented
> > 60 is shorter than thralling a mindshielded person 70 means you have to get that mindshielded person to a safe area very fast 80 is alright... But I mean, if you're smart at all you have other lights. What does it matter?
> 
> could always tag team a mindshielded person, one thralls, the other veils

The main problem I find with this PR is that it ignores the fact that you have two other teammates that you work with. Yeah they can suck, but its a teamwork round. You can also convert whilst also glaring/veiling without breaking conversion I think (Or it works with glare at least)
If this gets bumped up to 120 seconds it just tilts it too heavily in the lings favour and makes glowy completely useless.

2022-12-08 03:42 UTC, Sniblet commented
Fuck you for phrasing your point in a way I could understand
Slings may have to use veil twice for non-mindshielded glowies, and will have to for mindshielded glowies
I'm not going to make them tag-team every glowy they want to convert, that's a psychotic take and does not improve the gamemode

2022-12-08 03:43 UTC, CMOisLing commented
Make the thralling process refresh the timer

2022-12-08 03:50 UTC, Therandomhoboo commented
I would argue 40 seconds is still high, but this is significantly better and I would be fine at least trying it out.

2022-12-08 03:58 UTC, Sniblet commented
Bearing in mind that Veil's cooldown is 12 seconds, I could theoretically go lower without infringing my moral responsibility to not make shadowling miserable to play, but I will not go lower

2022-12-08 04:07 UTC, Therandomhoboo commented
> Bearing in mind that Veil's cooldown is 12 seconds, I could theoretically go lower without infringing my moral responsibility to not make shadowling miserable to play, but I will not go lower

Sorry to keep posting/replying. I would say 25 seconds minimum maybe but 40 is far better in my eyes to see how it works out.

2022-12-08 07:28 UTC, Simplehorror commented
this makes glowy useless in shadowling rounds, you may as well remove it. your other PR was less of a nerf than this, because you could inject it back

2022-12-08 07:28 UTC, Simplehorror commented
also this is powercreep after the 5 seconds removal

2022-12-08 07:40 UTC, Simplehorror commented on yogstation/code/modules/antagonists/shadowling/shadowling_abilities.dm
> +		if(iscarbon(target))
this is going to let people know who thralls are

2022-12-08 07:57 UTC, Simplehorror requested changes

2022-12-08 07:57 UTC, Simplehorror commented on yogstation/code/modules/antagonists/shadowling/shadowling_abilities.dm
> +		if(iscarbon(target))
this is going to let people know who thralls are (you accidentally resolved this)

2022-12-08 21:14 UTC, Simplehorror requested changes
this is going to let people know who thralls are (you accidentally resolved this) (AGAIN)

2022-12-08 23:40 UTC, ReddicusDragon commented on yogstation/code/modules/antagonists/shadowling/shadowling_abilities.dm
> +		if(iscarbon(target))
it IS going to reveal who the thralls are if they all had glowy, but the issue also is, without removing glowy, we fuck over the slings

2022-12-09 05:08 UTC, Simplehorror commented on yogstation/code/modules/antagonists/shadowling/shadowling_abilities.dm
> +		if(iscarbon(target))
if i was a sling i'd rather them keep glowy and just not interact with them honestly

2022-12-09 08:50 UTC, Sniblet commented
Glowy can be replaced. There are other ways to identify thralls. I don’t care.

2022-12-09 12:37 UTC, Therandomhoboo commented
> this is going to let people know who thralls are (you accidentally resolved this) (AGAIN)

Like no one checks for the eyes as soon as lings are called. Honestly, its just minor at this point

2022-12-09 17:50 UTC, Simplehorror commented
it should be blatantly obvious who is a fucking thrall or not I think, I'll make a PR for that

2022-12-10 09:19 UTC, TheGamerdk approved these changes

2022-12-10 09:19 UTC, merged