Thralls now get anti-glowy
yogstation13/Yogstation pull request #17028
Opened 2022-12-09 17:54 UTC by Simplehorror

# Document the changes in your pull request

This way, it serves to make thralls more obvious to security instead of just doing xenobio as they used to and being not worse off for it. Nobody actually inspects eyes to check for thrall anymore because it is just so time consuming.
Also, this helps counter glowy by making it so thralls can just walk up to a glowy person and counteract their glowy.

# Spriting

# Wiki Documentation

Thralls now get anti-glowy in shadowlign enthrall power
# Changelog

:cl:  
tweak: Thralls now get anti-glowy
/:cl:

2022-12-09 17:56 UTC, Therandomhoboo commented
Play a round of slings man, everyone checks eyes.

2022-12-09 17:57 UTC, Simplehorror commented
i've played it as a sling and as security, never seen anyone checking eyes. more often than not thralls get caught out because they're mass breaking lights or cloning slings or some shit, and the guy who got thralled in toxins never gets found out

2022-12-09 17:59 UTC, Therandomhoboo commented
> i've played it as a sling and as security, never seen anyone checking eyes. more often than not thralls get caught out because they're mass breaking lights or cloning slings or some shit, and the guy who got thralled in toxins never gets found out

Everyone checks eyes, i got shot down for not showing my eyes. Stop huffing drugs.

2022-12-09 17:59 UTC, Simplehorror commented
by which fucking sec officer

2022-12-09 18:01 UTC, Therandomhoboo commented
> by which fucking sec officer. i've died and i'll watch a thrall go around breaking apcs and they never get eyechecked

Literally by all sec, med, anyone that isn't thrall, command, captain you name it. I don't know what copium you're pounding atm but it is effecting your eyesight/memory. Everyone checks eyes, this is a moot pr

2022-12-09 18:02 UTC, Simplehorror commented
> > by which fucking sec officer. i've died and i'll watch a thrall go around breaking apcs and they never get eyechecked
> 
> Literally by all sec, med, anyone that isn't thrall, command, captain you name it. I don't know what copium you're pounding atm but it is effecting your eyesight/memory. Everyone checks eyes, this is a moot pr

show me the replay, you're chatting shit

2022-12-09 18:03 UTC, Therandomhoboo commented
> > > by which fucking sec officer. i've died and i'll watch a thrall go around breaking apcs and they never get eyechecked
> > 
> > 
> > Literally by all sec, med, anyone that isn't thrall, command, captain you name it. I don't know what copium you're pounding atm but it is effecting your eyesight/memory. Everyone checks eyes, this is a moot pr
> 
> show me the replay, you're chatting shit

Go through literally all the darkspawn events

2022-12-09 18:22 UTC, LazennG commented
> Nobody actually inspects eyes to check for thrall anymore because it is just so time consuming. 

lol

2022-12-09 23:36 UTC, Notamaniac commented
Most sec officers I come across usually say "Mask off", then shoot if the thrall delays or runs away.

2022-12-13 22:51 UTC, MajManatee commented
this has to be a meme pr

2022-12-15 10:30 UTC, Moltijoe requested changes
should only grant antiglowy to people that previously had glowy

2022-12-15 12:09 UTC, closed without merging