Small hemophilia fix
yogstation13/Yogstation pull request #17051
Opened 2022-12-12 08:03 UTC by Mqiib

# Document the changes in your pull request

Stops TRAIT_BLOOD_MESS from increasing bleeding rate while you're dead.
I'll make a bigger change to this that doesn't count as a bug fix once the feature freeze is done that makes it REASONABLE and not "paper cuts turn you into a raisin"

# Changelog

:cl:  

bugfix: Hemophilia/heparin no longer making bleeding worse when you're already dead

/:cl:

2022-12-13 07:20 UTC, Moltijoe requested changes, later dismissed

2022-12-13 07:20 UTC, Moltijoe commented on code/datums/wounds/slash.dm
> +	if(HAS_TRAIT(victim, TRAIT_BLOODY_MESS) && (victim.stat !+ DEAD))
gotta let go of shift
it's != not !+

2022-12-14 22:12 UTC, Mqiib commented on code/datums/wounds/slash.dm
> +	if(HAS_TRAIT(victim, TRAIT_BLOODY_MESS) && (victim.stat !+ DEAD))
oops

2022-12-15 22:43 UTC, TheGamerdk approved these changes

2022-12-15 22:43 UTC, merged