FIx preternis, IPC getting toxin by drinking welding fuel
yogstation13/Yogstation pull request #17061
Opened 2022-12-13 06:20 UTC by warface1234455

Welding fuel was made to tox every mob that drinks it including preternis and IPC themselves which is bad because preternis organ could process welding fuel to heal them so it shouldn't get toxin from it, for IPC they are inorganic so they shouldn't get tox from it

# Document the changes in your pull request

FIx preternis, IPC getting toxin by drinking welding fuel

# Changelog

:cl:  

bugfix: FIx preternis, IPC getting toxin by drinking welding fuel
/:cl:

2022-12-13 06:26 UTC, warface1234455 commented
People think that it's not a bug but it's actually is, people don't notice this because they most of the times use wires to heal burn instead of drinking welding fuel to heal

2022-12-13 06:30 UTC, 00ze-cyclone commented
First thing preternis aren’t a port, second at best you could call that an oversight but it’s definitely not a bug for preternis

2022-12-13 06:34 UTC, warface1234455 commented
> First thing preternis aren’t a port, second at best you could call that an oversight but it’s definitely not a bug for preternis

Well it isnt a port but whatever still oversight still needs to be changed

2022-12-13 06:48 UTC, warface1234455 commented
Also people would use wires instead of getting tox just for a few burn heals, i do what i need to do. If this get disapproved it's fine people will still use wires

2022-12-13 06:50 UTC, Moltijoe requested changes

2022-12-13 06:50 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	if(!ispreternis(M) || !isipc(M))
you want !(ispreternis(M) || isipc(M))

2022-12-13 07:04 UTC, KillerOrcaCora requested changes, later dismissed
Not a fix, can go under the freeze.

2022-12-13 07:04 UTC, Moltijoe approved these changes
code works

2022-12-13 07:35 UTC, Hopekz commented
> First thing preternis aren’t a port, second at best you could call that an oversight but it’s definitely not a bug for preternis

This is a bug because preterni didn't get tox damage from welding fuel before IPC's

2022-12-13 07:40 UTC, LazennG commented
> > you could call that an oversight but it’s definitely not a bug for preternis
> 
> This is a bug because preterni didn't get tox damage from welding fuel before IPC's

this is wrong. they always used to get toxin damage from welding fuel, it was drinking oil that didn't do that

2022-12-13 07:41 UTC, warface1234455 commented
> > you could call that an oversight but it’s definitely not a bug for preternis
> 
> This is a bug because preterni didn't get tox damage from welding fuel before IPC's

Yeah it has been like this for years now

2022-12-13 07:45 UTC, Hopekz commented
> Nah, it has been like this for years now

Congratulations! You're now fighting for this oversight PR being closed because it isn't a fix just to be right about this not being a fix.

2022-12-13 07:47 UTC, warface1234455 commented
> > Nah, it has been like this for years now
> 
> Congratulations! You're now fighting for this oversight PR being closed because it isn't a fix just to be right about this not being a fix.

ok

2022-12-13 20:40 UTC, Moltijoe commented
> Congratulations! You're now fighting for this oversight PR being closed because it isn't a fix just to be right about this not being a fix.

it's not a fix, that doesn't mean it will be closed, it just won't be merged until January

2022-12-14 17:15 UTC, Simplehorror commented
reckon my computer would be fucked if I started pouring welding fuel in it

2022-12-14 17:18 UTC, warface1234455 commented
> reckon my computer would be fucked if I started pouring welding fuel in it

Yeah cuz ur pc can't heal itself with welding fuel

2022-12-14 17:57 UTC, Hopekz commented
>  that doesn't mean it will be closed, it just won't be merged until January 

Neat does that mean we can see how large we can get the open PR number to go?

2022-12-15 04:03 UTC, warface1234455 commented
> > that doesn't mean it will be closed, it just won't be merged until January
> 
> Neat does that mean we can see how large we can get the open PR number to go?

Bet

2022-12-15 22:44 UTC, TheGamerdk approved these changes

2022-12-15 22:44 UTC, merged