Donators can now choose a plushie on TOP of the donor item
yogstation13/Yogstation pull request #17223
Opened 2022-12-29 23:28 UTC by ReddicusDragon

# Document the changes in your pull request
Donators can now choose a donor item and a plushie

# Changelog

:cl:  
rscadd: Plushies can now be taken with donor items
/:cl:

2022-12-30 01:08 UTC, Marmio64 commented
only if every map also comes with a plushie-destroyer 9000 that quickly disposes of all the excess lizard plushies everyone's going to fuckin toss around.

2022-12-30 03:45 UTC, ReddicusDragon commented
> only if every map also comes with a plushie-destroyer 9000 that quickly disposes of all the excess lizard plushies everyone's going to fuckin toss around.

This was a Xantam idea

2022-12-30 17:45 UTC, TheGamerdk requested changes
I’m not sure why slicerv has what seems like a generic plushie

2022-12-30 17:45 UTC, TheGamerdk commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		if(myplush.name == "coder plush") //DON'T GIVE THE PLAYERS THE CODER PLUSH
You don’t need this check

2022-12-30 17:45 UTC, TheGamerdk commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		var/obj/item/toy/plush/myplush = new Plushtype
Don’t spawn a plushie, use initial() to access vars

2022-12-30 17:45 UTC, TheGamerdk commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		if(!P.unlock_path)
This error doesn’t make sense, you’d runtime before getting here

2022-12-30 17:45 UTC, TheGamerdk commented on yogstation/code/modules/donor/unique_donator_items.dm
> +	else if (plushie == TRUE)
```suggestion
	else if (plushie)
```

2022-12-30 17:45 UTC, TheGamerdk commented on code/modules/client/preferences_savefile.dm
> +#define SAVEFILE_VERSION_MAX	39
You don’t need to update the savefile

2022-12-30 17:46 UTC, ReddicusDragon commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		if(myplush.name == "coder plush") //DON'T GIVE THE PLAYERS THE CODER PLUSH
I do otherwise it allows them to select it as a donor item. I've tested this, Bibby

2022-12-30 17:47 UTC, ReddicusDragon commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		var/obj/item/toy/plush/myplush = new Plushtype
Good point. Will correct.

2022-12-30 17:48 UTC, ReddicusDragon commented on code/modules/client/preferences_savefile.dm
> +#define SAVEFILE_VERSION_MAX	39
I do, because two donors had plushies as donor items.

2022-12-30 17:49 UTC, ReddicusDragon commented
> I’m not sure why slicerv has what seems like a generic plushie 

Ask him, it was his donor item locked to hisself.

2022-12-30 18:04 UTC, ReddicusDragon commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		var/obj/item/toy/plush/myplush = new Plushtype
Just tried this. Throws undefined variables. Can't change var/Plushtype to var/obj/item/toy/plush/Plushtype either, or else the for loop doesn't process. I was dealing with this issue last night.

2022-12-31 00:59 UTC, CMOisLing commented
Donor powercreep

2022-12-31 01:01 UTC, Xantam-13 commented
> Donor powercreep

Absolutely!! :)

2022-12-31 17:04 UTC, ReddicusDragon commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		if(!P.unlock_path)
I realized my mistake with this, and fixed it btw

2022-12-31 18:16 UTC, TheGamerdk requested changes

2022-12-31 18:16 UTC, TheGamerdk commented on code/modules/client/preferences_savefile.dm
> +#define SAVEFILE_VERSION_MAX	39
In that case limit the update to only changing those

2022-12-31 18:16 UTC, TheGamerdk commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		var/obj/item/toy/plush/myplush = new Plushtype
You’re doing it wrong then

2022-12-31 18:16 UTC, TheGamerdk commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		if(myplush.name == "coder plush") //DON'T GIVE THE PLAYERS THE CODER PLUSH
subtypesof wont include the parent type if you’ve done it correctly. And even if it included the parent type this should be checked using the path and not a magic string

2022-12-31 18:16 UTC, TheGamerdk commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		if(!P.unlock_path)
You don’t need this check is what I’m saying

2023-01-02 04:41 UTC, ReddicusDragon commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		var/obj/item/toy/plush/myplush = new Plushtype
I have tried it every which way I know how, Bibby. I spent four hours trying to figure out why it wouldn't work and have tried numerous methods to get it to work and it only works so far in the way I've implemented. You're welcome to fix it after this gets merged but I'm not spending 5 more hours figuring out why the funny for loop doesn't run.

2023-01-02 04:41 UTC, ReddicusDragon commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		if(!P.unlock_path)
Gotcha. Will fix.

2023-01-02 04:41 UTC, ReddicusDragon commented on code/modules/client/preferences_savefile.dm
> +#define SAVEFILE_VERSION_MAX	39
Single line removal. Will fix.

2023-01-02 04:43 UTC, ReddicusDragon commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		if(myplush.name == "coder plush") //DON'T GIVE THE PLAYERS THE CODER PLUSH
Tried checking the path using the type path and couldn't get it working. This change, while hacky, works. If you can demonstrate to me how to properly check an object's path then by all means

2023-01-02 04:47 UTC, ReddicusDragon commented
Actually you know what, Bibby can steal this code and fix it because quite frankly I dislike being told that I'm doing something wrong when I thoroughly have tested every possible way it could process. I've apparently taken up a project way bigger than I thought that my dumbass couldn't possibly handle. PR closed.

2023-01-02 05:01 UTC, ReddicusDragon commented
I'm reopening this in the morning I think I can fix part of this

2023-01-02 19:55 UTC, ReddicusDragon commented
it just works if you don't like my snowflake coder plush check fix it yourself, I am genuinely not spending 80 hours figuring that one out

2023-01-02 20:06 UTC, TheGamerdk commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		if(myplush.name == "coder plush") //DON'T GIVE THE PLAYERS THE CODER PLUSH
I'm going to emphasize that you don't need this check.
subtypesof won't grab the parent type.
I'd be happy to get you a code example if you don't believe me

2023-01-02 20:07 UTC, TheGamerdk commented
> it just works if you don't like my snowflake coder plush check fix it yourself, I am genuinely not spending 80 hours figuring that one out

Nothing to figure out, just remove the check

2023-01-02 20:07 UTC, TheGamerdk commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		var/obj/item/toy/plush/myplush = new Plushtype
Change
var/obj/item/toy/plush/myplush = new Plushtype
to var/obj/item/toy/plush/myplush = Plushtype

Change all mentions of myplush.variable to initial(myplush.variable)

2023-01-02 20:08 UTC, ReddicusDragon commented
> > it just works if you don't like my snowflake coder plush check fix it yourself, I am genuinely not spending 80 hours figuring that one out
> 
> Nothing to figure out, just remove the check

If I do, coder plushie is available for donors to pick. Once again, I've tested this, bibby. You're welcome to utilize the branch to run your own tests, but without the snowflake name = coder plush check coder plush is available to donors.

2023-01-02 20:47 UTC, ReddicusDragon commented on yogstation/code/modules/donor/unique_donator_items.dm
> +		var/obj/item/toy/plush/myplush = new Plushtype
I realized this last night, it's fixed now

2023-01-02 20:49 UTC, ReddicusDragon commented
IT COMPILES

2023-01-06 02:42 UTC, ToasterBiome approved these changes
this is a map review this is a map review this is a map review this is a map review this is a map review this is a map review this is a map review

2023-01-07 16:43 UTC, ReddicusDragon commented
Jamie called this snowflake code, it works it's tested and Xantam wanted this change. Thought I'd be helping Jamie with his workload by doing this but c'est la vie.

2023-01-07 16:43 UTC, closed without merging