Flips Boxstation Cloning and Genetics
yogstation13/Yogstation pull request #17262
Opened 2023-01-02 02:47 UTC by ToasterBiome

# Document the changes in your pull request

![image](https://user-images.githubusercontent.com/5091394/210191866-e3c9b2b3-7721-4cca-9e0c-80d5aec8deec.png)

![image](https://user-images.githubusercontent.com/5091394/210191798-f89d8d6f-acaf-457b-b08a-85fa052d4ed2.png)

The hallway inclusion that leads to xenobio did one extra thing: it made genetics a fortress, lacking maint access.

Every other map has maint access to genetics/cloning, but box was lacking now. 

Flips them so genetics is in a better position to be accessed from maintenance (and more susceptible to sabotage)
Also buffs cloning by making it closer to treatment and having it's "EMP cloner in maint" be the little area above it instead.

# Wiki Documentation

Genetics lab and cloning on BoxStation are flipped.

# Changelog

:cl:  
mapping: Flips genetics and cloning on BoxStation
/:cl:

2023-01-03 15:49 UTC, wejengin2 requested changes
1. double wire 
![image](https://user-images.githubusercontent.com/48154165/210391139-9dc4327f-24f2-44df-9141-e660e2b234d3.png)
2. All the doors except the one leading to rnd corridor have a lot of different accesses that will only cause confusion when someone wants to give access to this area, keep just the proper ones for the proper door. So cloning for cloning and genetics for genetics: https://github.com/yogstation13/Yogstation/blob/master/code/__DEFINES/access.dm
3. as an addition, maybe add an rd c_tag for the genetics camera?
4. considering maybe removing this thindow, it looks weird next to a wall: 
![image](https://user-images.githubusercontent.com/48154165/210392961-e76ab4e2-305c-4e86-b91e-163e1104e5b8.png)



Aside from these I think this is fine

2023-01-03 22:23 UTC, ToasterBiome commented
> 1. double wire
> 2. All the doors except the one leading to rnd corridor have a lot of different accesses that will only cause confusion when someone wants to give access to this area, keep just the proper ones for the proper door. So cloning for cloning and genetics for genetics: https://github.com/yogstation13/Yogstation/blob/master/code/__DEFINES/access.dm
> 3. as an addition, maybe add an rd c_tag for the genetics camera?
> 4. considering maybe removing this thindow, it looks weird next to a wall:
> 
> Aside from these I think this is fine

1. Fixed
2. These match the same doors as were on there previously. Most importantly, the 3 different accesses on the door between them is for the weird situation where someone has access to gene but not cloning. Working as intended
3. Genetics camera already has a c_tag, unless you mean adding it the RD network, then I will do that.
4. 
![image](https://user-images.githubusercontent.com/5091394/210451136-81e24495-a42f-4015-9734-2c48c539f3b2.png)
Flipped this so that the glass can be outside.

2023-01-05 01:41 UTC, Hopekz commented
@wejengin2 🐐

2023-01-05 21:48 UTC, patpol4 approved these changes
i guess

2023-01-06 02:40 UTC, merged