Makes Borg Army Actually Scale with Player Count
yogstation13/Yogstation pull request #17273
Opened 2023-01-03 01:29 UTC by JamieD1

8 Borgs on 25 pop is kinda stupid lol

:cl:  
tweak: Makes Borg Army Actually Scale with Player Count
/:cl:

2023-01-03 01:30 UTC, HisaHoshimo commented
Me and the boys on 5 pop needing 8 borgs

2023-01-03 01:45 UTC, JamieD1 commented on code/game/gamemodes/objective.dm
> +	number_of_borgs = ceil((GLOB.joined_player_list.len / 10) + 2)
```suggestion
	number_of_borgs = CEILING((GLOB.joined_player_list.len / 10) + 2)
```

2023-01-03 01:51 UTC, JamieD1 commented on code/game/gamemodes/objective.dm
> +	number_of_borgs = CEILING((GLOB.joined_player_list.len / 10) + 2)
```suggestion
	number_of_borgs = ROUND_UP((GLOB.joined_player_list.len / 10) + 2)
```

2023-01-03 01:51 UTC, ToasterBiome requested changes, later dismissed

2023-01-03 01:51 UTC, ToasterBiome commented on code/game/gamemodes/objective.dm
> +	number_of_borgs = CEILING((GLOB.joined_player_list.len / 10) + 2)
```suggestion
	number_of_borgs = CEILING((length(GLOB.joined_player_list) / 10) + 2)
```

length(x) is faster than x.len

2023-01-03 01:53 UTC, JamieD1 commented on code/game/gamemodes/objective.dm
> +	number_of_borgs = ROUND_UP((GLOB.joined_player_list.len / 10) + 2)
```suggestion
	number_of_borgs = ROUND_UP((length(GLOB.joined_player_list) / 10) + 2)
```

2023-01-03 02:51 UTC, JamieD1 commented on code/game/gamemodes/objective.dm
> +	return counter >= number of borgs
```suggestion
	return counter >= number_of_borgs
```

2023-01-04 15:39 UTC, ReddicusDragon commented
ah yes, me singlehandedly cranking out 8 bazillion borgs because the other roboticist vanished

2023-01-09 20:32 UTC, Moltijoe approved these changes

2023-01-09 20:56 UTC, merged