bring back the lawyer office on Gax
yogstation13/Yogstation pull request #17280
Opened 2023-01-03 09:39 UTC by 00ze-cyclone

# Document the changes in your pull request

Ok the lawyer is an RP job that pretty much nobody gives a fuck about but straight up removing them from a map won't improve that, let's not go the omegastation route.
Replace the evidence room that was never going to be used with no lawyers on lowpop with the law office, this result in the lawyer being in the middle of sec so maybe that'll make them and sec interact a little bit more.

# Wiki Documentation

law office on gax is back

# Changelog

:cl:  
mapping: Add back the law office to gax
/:cl:

2023-01-03 09:43 UTC, ToasterBiome requested changes
Sure, I'm willing to ball with this.

Few things:

- There still needs to be an evidence area, with evidence lockers, SOMEWHERE.
- You need to remove the GaxStationChanges() proc from the lawyer's job datum, and remove "GaxStation" from the list of changed_maps on the lawyer's job datum, or else nobody will have the option to spawn.

2023-01-03 09:44 UTC, ToasterBiome requested changes
![image](https://user-images.githubusercontent.com/5091394/210332950-cc1b691b-77df-487c-9583-8eed45c12716.png)

Also while you're here, move this camera off of this glass. Thanks.

2023-01-03 10:08 UTC, 00ze-cyclone commented
> Sure, I'm willing to ball with this.
> 
> Few things:
> 
>     * There still needs to be an evidence area, with evidence lockers, SOMEWHERE.
> 
>     * You need to remove the GaxStationChanges() proc from the lawyer's job datum, and remove "GaxStation" from the list of changed_maps on the lawyer's job datum, or else nobody will have the option to spawn.

I put the lockers in the interrogation room.

> ![image](https://user-images.githubusercontent.com/5091394/210332950-cc1b691b-77df-487c-9583-8eed45c12716.png)
> 
> Also while you're here, move this camera off of this glass. Thanks.

Done

2023-01-03 23:55 UTC, ToasterBiome requested changes
![image](https://user-images.githubusercontent.com/5091394/210460650-494b9a07-8d44-479a-a4f2-1454611deb2f.png)
this is now here in the hallway

2023-01-04 11:59 UTC, 00ze-cyclone commented
> ![image](https://user-images.githubusercontent.com/5091394/210460650-494b9a07-8d44-479a-a4f2-1454611deb2f.png) this is now here in the hallway

fixed

2023-01-04 22:45 UTC, ToasterBiome approved these changes

2023-01-04 22:46 UTC, merged