Ports RCD menu to TGUI
yogstation13/Yogstation pull request #17313
Opened 2023-01-04 18:01 UTC by ThatLing

# Document the changes in your pull request

Ports https://github.com/tgstation/tgstation/pull/71710. It removes the old radial menu for the RCD which sucks and replaces it with a modern TGUI window.

![image](https://user-images.githubusercontent.com/24573384/210619580-9e9f9b3e-51c1-40d6-8cc5-acede1366114.png)
![image](https://user-images.githubusercontent.com/24573384/210619594-ce9c8dd1-94ac-44f8-8138-a2a80d17a240.png)
![image](https://user-images.githubusercontent.com/24573384/210619609-33e117bb-4be2-4a82-95b0-83ddf2553b87.png)

# Changelog

:cl: Synclt21
add: TGUI for RCD Just like Rapid Pipe Dispenser
code: silo link upgrades for both RLD & Plumbing RCD
del: Switch Mode, Window Glass, Airlock action icons for construction console
/:cl:

2023-01-04 18:35 UTC, ToasterBiome commented
radial menu was popping off though, seems like a downgrade

2023-01-04 18:36 UTC, ThatLing commented
Radial menus suck, I sure love cycling through 7 menus to make a single airlock with correct access

2023-01-04 18:41 UTC, ToasterBiome requested changes
if we’re gonna do this:
put deconstruct back on top, it was a separate action from construction

also can we get a tooltip on hover of what things cost?

2023-01-04 18:41 UTC, ToasterBiome commented on _maps/_basemap.dm
> +#define LOWMEMORYMODE //uncomment this to load centcom and runtime station and thats it.
society

2023-01-04 18:42 UTC, ToasterBiome commented
> if we’re gonna do this: put deconstruct back on top, it was a separate action from construction
> 
> also can we get a tooltip on hover of what things cost? deconstruct might be variously but airlocks and stuff should be workable

2023-01-05 07:42 UTC, ThatLing commented
> if we’re gonna do this: put deconstruct back on top, it was a separate action from construction
> 
> also can we get a tooltip on hover of what things cost?

Making a seperate category with just "Deconstruct" is ugly

There is no easy way to get the cost atm, it would require a refactor which is out-of-scope for this PR

2023-01-08 00:36 UTC, ReddicusDragon reviewed
Only thing I have a possible issue with is the possibility of having a silo link. I can foresee this becoming an issue with everyone trying to run around with silo link'd rcds

2023-01-08 00:36 UTC, ReddicusDragon commented on code/game/machinery/doors/airlock_electronics.dm
> +	log_world("do_action: [action]")
Do we really need log_world here?

2023-01-16 17:14 UTC, MajManatee commented
I actually really like the little circle for RCDing. Quick and easy, this seems like it becomes a whole ordeal.

2023-01-19 12:20 UTC, ThatLing commented
> I actually really like the little circle for RCDing. Quick and easy, this seems like it becomes a whole ordeal.

You think you do, but you don't

2023-01-24 09:17 UTC, iamthesilly commented
I like the radial menu a lot better since it's simple and you can actually continue moving around and stuff in game while you're using it, though a tgui menu for selecting airlock style and access would be nice.

2023-01-25 22:53 UTC, TheGamerdk commented
would be cool if it was a preference :)

2023-01-28 16:04 UTC, closed without merging