Nerfs and Reworks Ninja because I died once FUCK YOU NINJA YOU PIECE OF SHIT I HATE YOU I HATE YOU I HATE YOU
yogstation13/Yogstation pull request #17326
Opened 2023-01-05 08:55 UTC by BurgerLUA

# Justification

To me it doesn't really make sense that a mid-round ghost role can have so much power over affecting the round while being nearly untouchable. 
- Most players are uneasy about hunting Ninjas because it has a chance to be NanoTrasen aligned. While it really isn't against the rules to kill a NanoTrasen ninja because it's a ninja, people are still hesitant to do so anyways like they're hesitant to toolbox a Delta Station engineer who stumbles upon the station.
- Ninjas are super fast and incredibly stealthy. It is absurdly hard to catch one and is very close to wizard in terms of evasion. This is fine for a ninja, but it is really strong for a mid-round ghost role.
- Not only do Ninjas (potentially) have objectives to kill or protect heads, but they (potentially) have objectives to kill or protect antagonists, effectively outing them or shutting down their round. No mid-round ghost role should have a license to validhunt.
- Ninjas have a license to capture people and effectively keep them from the round entirely unless they die. This is pretty anti-fun and is honestly no different than round-removing random people.

# Document the changes in your pull request

- Ninjas no longer have an alliance (NanoTrasen aligned, Syndicate Aligned) and will always be Neutral.
- Ninjas can have up to 4 objectives chosen from a pool of objectives (See below).
- Ninja suit stats are no longer randomized.
- Energy nets no longer teleport players to GBJ (shoutout to SimpleFlips!), but rather trap them for 30 seconds.
- Stealth mode require less than 0.5 lumens (0 is completely dark, 1 is completely fullbright) to work.
- Increases the battery cell of the suit from a cell that gives 9000 energy to a cell that gives 20000 energy.
- Increases the energy cost of EMP from 2500 to 5000.
- Increases the energy cost of Adrenaline from 0 to 250.
- Decreases the energy cost of Nets from 2500 to 1000.
- Increases the energy cost of Smoke Bombs from 0 to 100.
- Increases the energy cost of Shuriken from 300 to 500.
- Increases the energy cost of Sword Recall from 100 per turf to 200 per turf.
- Increases the suit passive energy cost from 5 per tick to 10 per tick.
- Increases the suit stealth energy cost from 25 per tick to 50 per tick.
- Increases the amount of adrenal boosters from 3 to 5.

Current Ninja objectives (4 randomly chosen, can have duplicates).
- Steal research nodes.
- Steal important item.
- Kill (anyone, previously it was limited to heads/antags). Has a 20% chance to additionally add an "extract with a photo of the body" objective.
- Protect (anyone, previously it was limited to heads/antags). Has a 20% chance to additionally add a "prevent the target from escaping" objective.
With a gaurenteed.
- Escape on the shuttle alive OR Die a glorious death.

# Wiki Documentation

https://wiki.yogstation.net/wiki/Space_Ninja Needs to be updated.

# Changelog

:cl:  BurgerBB
tweak: Rebalances Ninja and their objectives.
/:cl:

2023-01-05 08:59 UTC, BurgerLUA commented
Forgot to convert to draft because none of this is tested (or even compiled)

2023-01-05 16:44 UTC, Moja10 commented
Lol it doesn't make any sense for a ninja to go on the shuttle. It was perfectly fine with them staying on the station, they are not affiliated for or against Nanotrasen, so why would they go to CC? 

GBJ has always been a key feature of ninjas, I would suggest just adding a method for them to return, ala contractor. 

Alliances are a neat addition, I wish alliances were added to more antags, not less. If anything, the core objectives should just change to better distinguish. Maybe more protects/captures for NT Ninja, more kill, steal for Syndie Ninjas.

2023-01-05 20:14 UTC, RG4ORDR commented
Gonna address some of your points.
>Players valid hunt the ninja
Yeah this happens because AFAIK ninjas have no rules protecting them, they're still an antag.
>Ninja are very fast and stealthy 
Yes because ninjas are a glass cannon and require constant upkeep of their resources. They need to plan ahead for everything such as keeping their suit powered so they can maintain their high speed,stealth, throwing stars,nets,shockgloves, their teleports are tied to their katana. Not to mention if they get hit/get hungry they HAVE to turn their suit off unless they got piercing syringes, and hyposprays. Wizards aren't remotely as restricted as this.
>Ninja objectives are stupid.
Yeah true lol.
>Ninjas round remove people.
Controversial but true. Capturing people isn't as easy as players can break the net with relatively no effort, ninja has to be right next to the player to make sure the capture will go through. Granted when the Ninja dies everyone gets returned to the station, though adding a timer like contractors would be pretty good.

Otherwise all your changes are just not good and are conducive of someone whose never played ninja.
Ninja doesn't need die a glorious death otherwise there wouldn't be many ninjas to hire.

2023-01-05 20:48 UTC, BurgerLUA commented
The only thing I agree with changing is the shuttle thing because I misread the code but other than that I disagree with the feedback.

2023-01-05 23:07 UTC, RG4ORDR commented
> The only thing I agree with changing is the shuttle thing because I misread the code but other than that I disagree with the feedback.

I highly encourage you to play ninja.
Lemme give you a few counters to ninjas in no specific order.

- Temp Guns - hit them with freeze and they lose all that speed.
- Syringe guns - Not anymore after some bad PR
- Lasers - Ninja armor isn't strong
- Bullets - A shotgun can GG a ninja no problem, anything else can handle it very easily.
- Circular saw - Ninja armor isn't that strong you can cause bleed wounds VERY easily on ninjas.
- Knives - Ninja armor isn't that strong.
- Null rod and Nullrod variants - Ninja armor isn't that strong
- Riot suit and shield 
- Batons of any variety beat ninja.
- Ion gun - Bye bye power
- Emp grenades - Bye bye power.
- Throwing stars - Oh you thought if you missed you're fine? Boom, brute damage + bleeding + embed chance.
- Anything that can embed actually
- Xray or thermal eyes - Kinda hard to heal and eat when you're being hunted constantly.

Ninja is HIGHLY dependent on an individual players own skill and game knowledge. All it's abilities have some trade off, cool down, and you need to manage several other functions. Your adrenaline burst irradiates you and gives you toxins, and can knock you out. Your suit cannot beat on when you heal or eat except if you get hyposprays and medipens. I've seen good and bad players take ninja and the difference between a Ninja actually cause massive problems and dying within 5 minutes is the response of the security team and the valid hunters/people defending themselves from the ninja.

2023-01-05 23:13 UTC, Sniblet commented
Asking a ninja to escape on the shuttle, especially when stealth mode doesn't work in shuttle lighting, effectively means they have hijack 50% of the time

2023-01-06 00:10 UTC, BurgerLUA commented
The survive objective was re-added and the shuttle/die objective was removed.

Mid round antagonist ghost roles are supposed to be hard. Playing Blob is supposed to be hard. Playing a sentient virus is supposed to be hard. Playing vine spawns are supposed to be hard. Playing ninja is supposed to be hard, but honestly it feels like it belongs in the "wizard" category in terms of "hahaha you can't touch me, I remove you from the round!" when it comes to their insane evasion, their ability to send people to GBJ, and the fact that they usually have objectives that tell them to steal the brains of active players or to decap them for no raisin and space their head.

2023-01-08 00:31 UTC, ReddicusDragon requested changes
I've read enough, what is this pr why are we removing station ninja

2023-01-08 00:31 UTC, ReddicusDragon commented on code/modules/antagonists/ninja/ninja.dm
> -	var/helping_station = FALSE
restore this line

2023-01-08 00:31 UTC, ReddicusDragon commented on code/modules/antagonists/ninja/ninja.dm
> -	name = "[helping_station?"Nanotrasen Ninja":"Syndicate Ninja"]" // yogs - ninja disposition
why are you removing station ninja???

2023-01-08 00:31 UTC, ReddicusDragon commented on code/modules/antagonists/ninja/ninja.dm
> -	to_chat(owner.current, "Officially, [helping_station?"Nanotrasen":"The Syndicate"] are my employer.")
once again... why?

2023-01-08 00:32 UTC, ReddicusDragon commented on code/modules/antagonists/ninja/ninja.dm
> -	var/helping_station = FALSE
restoring this line should probably solve lints

2023-01-08 01:02 UTC, BurgerLUA commented
> I've read enough, what is this pr why are we removing station ninja

Station ninja was basically a license to validhunt antags which really isn't fair to the antags.

2023-01-09 18:17 UTC, ReddicusDragon commented
> > I've read enough, what is this pr why are we removing station ninja
> 
> Station ninja was basically a license to validhunt antags which really isn't fair to the antags.

I'm requesting a review from Jamie, as I am not experienced nor knowledgeable to properly review this.

2023-01-09 18:18 UTC, ReddicusDragon commented
seems like the kind of thing a headcoder should weigh in on

2023-01-09 21:04 UTC, BurgerLUA commented
> seems like the kind of thing a headcoder should weigh in on

Hence the draft.

Needs a lot of input on what to change and what to keep.

2023-01-11 14:49 UTC, UltraBigRat commented
honestly looks pretty good as the power cap increase balances out. Since you're reworking it could maybe give em a nutriment pump while yer at it? eating is very painful as ninja as you have to go through the long reboot sequence, which usually just leads to ninjas teleporting into space to do it. Or just let em eat through their mask and make helmet toggleable?

2023-01-12 15:35 UTC, Moja10 commented
still think this is a wonky PR, remember, this isn't competitive legends league, it's okay to have some midrounds be stronger than others, just like in chess. its not a game of "oh sentient virus is weak therefore ninja must be weak too"

2023-01-15 19:21 UTC, ReddicusDragon commented
this is still a draft. Don't know why the ART maintainer is closing a CODE PR

2023-01-15 19:49 UTC, solwashere commented
Don't like ninja objectives being reworked to have standard traitor objectives
I think reworking some of the already existing objectives would be much better, and making it so that Ninjail is more like contractor jail instead of straight up round removal until the ninja maybe dies 
I do agree that the NT ninja can suck for antags if they become a target, but I do think there could be some sort of workaround for that, for example, the ninja can only have antags that have hit targets on head or sec as targets, and said traitor's  get some sort of heads up message and maybe extra TC to compensate and prepare upon ninja spawn
Regarding the heads as target objective for the syndie ninja, as someone who mains a command role it is mildly unfair at times, especially when there lack of sec or competent sec, but I don't think it's a big enough frustration to warrant removing it considering that you can counter ninja with temp gun and iron + uranium 
As for the claim that people are too scared to validhunt the ninja, this is almost entirely false in all of the times that I've seen a ninja as a lot of people tend to be scared of the risk of the ninja round removing them regardless of which side they are on
tldr: I don't think we should whitewash the ninja and make it just traitor with cool sword + armor and we should have more unique objectives for antags

2023-01-18 14:03 UTC, BurgerLUA commented on code/modules/antagonists/ninja/ninja.dm
> -	var/helping_station = FALSE
I did the opposite and just removed it as it is obsolete.

2023-01-19 15:38 UTC, BurgerLUA commented on code/modules/antagonists/ninja/ninja.dm
> -	name = "[helping_station?"Nanotrasen Ninja":"Syndicate Ninja"]" // yogs - ninja disposition
Station ninja was just validhunting antags and thus bad.

2023-01-25 19:09 UTC, BurgerLUA commented
I might get more forum feedback or something. I don't know what I can do to make ninja not shit that people won't hate.

2023-01-30 15:20 UTC, MajManatee commented
Open for a month, no pushes for 1 week. Please re-open when work is continuing.

2023-01-30 15:20 UTC, closed without merging