Moves things around, adds things to make seafood themed items to Fishing Biodome
yogstation13/Yogstation pull request #17382
Opened 2023-01-07 11:03 UTC by GraveHat

Fishy Fish

# Document the changes in your pull request

- Adds Fish crate freezer filled with 2 Bass, 2 Salmons, a Squid, a Shrimp, a Pufferfish, and a Tuna
- Adds 2 Nettle Seeds
- Moves the Food Processor, Cook Book, and Condimaster to make the more useful one more noticeable

I know this technically gives the Fishermen access to Death Nettles but it's either that or an entire Chem Dispenser that doesn't fit in well at all. This is all in order to make Soysauce which needs Sulfuric Acid for some reason. Oh, and the rarer fish would make good loot for hungry people.

# Wiki Documentation

Image Outdated, Documentation of above.

# Changelog

:cl:  
mapping: Adds 2 Nettle Seeds to Fishing Biodome
mapping: Adds Fish Freezer to Fishing Biodome
mapping: Swapped the Grinder and Condimaster, moved the Cook Book
/:cl:

2023-01-07 11:42 UTC, Burger1998 commented
sir you have to harass jamie in his dm's right now before making a pr

2023-01-17 13:00 UTC, GraveHat commented
It has been done

2023-01-17 21:50 UTC, ToasterBiome requested changes, later dismissed
I dont think that's how the airlock helpers work, only one set is needed

2023-01-22 13:59 UTC, wejengin2 approved these changes
looks fine

2023-01-22 14:03 UTC, merged