Fixes air shoes implant exploit using boost while hardcrit or dead
yogstation13/Yogstation pull request #17410
Opened 2023-01-08 22:06 UTC by ynot01

# Document the changes in your pull request

Can no longer use it in hardcrit
Can still use it in softcrit bc im nice

# Changelog

:cl:  
bugfix: Can no longer use air shoes jump boost in hardcrit or death
/:cl:

2023-01-08 22:15 UTC, Moltijoe commented
Hold up, isnt that what the ability check flags do?

2023-01-08 22:42 UTC, Moltijoe commented
> Edit: Oh, probably because im overwriting the original isavailable proc. 

Exactly what happened

2023-01-08 22:46 UTC, Moltijoe requested changes

2023-01-08 22:46 UTC, Moltijoe commented on code/modules/surgery/organs/augment_legs.dm
> -	if(COOLDOWN_FINISHED(src, dash_cooldown))
just add 
`. = ..()`
above this line

2023-01-09 02:07 UTC, Moltijoe approved these changes

2023-01-09 02:14 UTC, ynot01 commented
sir if you write . = ..() and then return a value after that it's going to return the value not ..()

2023-01-09 23:17 UTC, merged