Farewell Syringe Guns
yogstation13/Yogstation pull request #17466
Opened 2023-01-12 19:59 UTC by TheRyeGuyWhoWillNowDie

Fuck off instant wins. Jamie approved!

Jamie has already taken them out of the armory, this is the last step.

Maintainer rationale:
one click wins bad, syringe guns will never be balanced

# Changelog

:cl:  
tweak: syringe gun armor piercing restrictions have been removed
tweak: printing syringe guns now needs illegal tech
tweak: printed rapid syringe guns replaced with normal syringe guns
tweak: chem gun in uplink has been replaced with rapid syringe gun (8tc) because the reagent gun is just really bad
/:cl:

2023-01-12 20:19 UTC, Moltijoe commented
#17342 
Will this one remain?

2023-01-12 20:19 UTC, TheRyeGuyWhoWillNowDie commented
> #17342 Will this one remain?

sorry i didn't see you buffed medlizards, one second

2023-01-12 20:29 UTC, Moltijoe commented
The nice thing about syringe guns being illegal/antag only is that we no longer need to constantly balance chemistry exclusively around them, letting us make more interesting dangerous chemicals.

2023-01-12 20:50 UTC, Moja10 commented
Kind of omega cringe, there's plenty of other roundtypes that syringe guns should be present in, more than just the ones with TC. Illegal items requirement pretty much seals that they will never be seen ever. Ya'll need to actually get a grip

2023-01-12 21:12 UTC, Moltijoe commented
> Kind of omega cringe, there's plenty of other roundtypes that syringe guns should be present in, more than just the ones with TC. Illegal items requirement pretty much seals that they will never be seen ever. Ya'll need to actually get a grip

I was personally considering doing something like this, but with key differences that sorta allows them to still exist.
Medical Weaponry not locked behind illegal tech
CMO starts with one

That way they still exist, but are far more restricted

2023-01-12 21:14 UTC, Moltijoe requested changes

2023-01-12 21:14 UTC, Moltijoe commented on code/modules/research/techweb/all_nodes.dm
>  	design_ids = list("rapidsyringe", "dartsyringe")
```suggestion
	design_ids = list("syringegun", "dartsyringe")
```

2023-01-12 21:17 UTC, TheRyeGuyWhoWillNowDie commented on code/modules/research/techweb/all_nodes.dm
>  	design_ids = list("rapidsyringe", "dartsyringe")
yea

2023-01-12 21:19 UTC, TheRyeGuyWhoWillNowDie commented
> Kind of omega cringe, there's plenty of other roundtypes that syringe guns should be present in, more than just the ones with TC. Illegal items requirement pretty much seals that they will never be seen ever. Ya'll need to actually get a grip

yeah them never being seen again is kind of the point

2023-01-13 02:31 UTC, LoliconSlayer commented
i ded

2023-01-13 02:33 UTC, RG4ORDR commented
Lmao, once again we have an issue that some how no other server has. Even more LRP and HRP servers don't have an issue with syringe guns.
Bravo, I'm impressed.

2023-01-13 04:27 UTC, Moltijoe commented
> Lmao, once again we have an issue that some how no other server has. Even more LRP and HRP servers don't have an issue with syringe guns. Bravo, I'm impressed.

probably because on HRP servers people spend more time chatting than killing, and on other LRP, people die instantly in so many ways that syringe guns are just a drop in the bucket.

2023-01-13 07:52 UTC, UltraBigRat commented
could be nice to add a kind of syringe gun to makeshift weapons, so at least bb's can make em

2023-01-13 09:28 UTC, 00ze-cyclone commented
> could be nice to add a kind of syringe gun to makeshift weapons, so at least bb's can make em

There’s already a makeshift syringe gun, it’s the blow gun.

2023-01-13 13:03 UTC, UltraBigRat commented
> > could be nice to add a kind of syringe gun to makeshift weapons, so at least bb's can make em
> 
> There’s already a makeshift syringe gun, it’s the blow gun.

the blowgun sucks a bit too much, to be worth it for an antag.

2023-01-13 16:16 UTC, Moltijoe approved these changes
Whether or not this is wanted is up for debate. 
At the very least, I can't find any problems with the code.

2023-01-13 21:15 UTC, Moja10 commented
You are obviously extremely biased and clouded in your judgement on how much of a problem syringe guns are and i'm afraid of the fact that all you need is one other extremely biased maintainer to slap the merge button in order to just have this garbage hugbox shit plague our server til the end of time.

2023-01-13 21:26 UTC, ReddicusDragon commented
> You are obviously extremely biased and clouded in your judgement on how much of a problem syringe guns are and i'm afraid of the fact that all you need is one other extremely biased maintainer to slap the merge button in order to just have this garbage hugbox shit plague our server til the end of time.

i heard a call for a biased maintainer
![okman](https://user-images.githubusercontent.com/36747151/212422324-ef661ec3-d611-4809-a47c-11e02bd90a45.png)

2023-01-13 21:28 UTC, ReddicusDragon commented
I extremely dislike the idea of just removing syringe guns

2023-01-13 21:29 UTC, TheRyeGuyWhoWillNowDie commented
> I extremely dislike the idea of just removing syringe guns

Not removed, this just secborgs them

2023-01-13 22:30 UTC, merged

2023-01-13 22:58 UTC, RG4ORDR commented
Disappointing.
There needs to be some actual oversight if features keep getting soft-removals