Sole survivor gets hijack items
yogstation13/Yogstation pull request #17461
Opened 2023-01-12 16:19 UTC by ReddicusDragon

# Document the changes in your pull request
i hate council

closes #17442 
# Wiki Documentation
Romerol, roburger, singulo beacon and sm delaminator are given to sole survivor
# Changelog
:cl:  
tweak: sole survivor now has access to hijack items  
/:cl:

2023-01-12 16:53 UTC, ynot01 commented
sole survivor ought to be a subtype of hijack methinks

2023-01-12 16:55 UTC, ReddicusDragon commented
> sole survivor ought to be a subtype of hijack methinks

I just fix issues man 😔

2023-01-12 21:11 UTC, JamieD1 commented
The fuck is sole survivor

2023-01-12 21:12 UTC, ReddicusDragon commented
Jamie moment

2023-01-12 21:17 UTC, Moltijoe requested changes
should probably make it just pretend hijack also counts as sole survivor
I can't think of any reason we'd want an item that can go to one but not the other

2023-01-13 20:39 UTC, Moltijoe requested changes

2023-01-13 20:39 UTC, Moltijoe commented on yogstation/code/game/gamemodes/objective.dm
> -		return TRUE
Have it be
`if(completed) return TRUE`
to allow for admin override

2023-01-13 20:44 UTC, Moltijoe approved these changes
I don't like your tone young man

2023-01-13 21:11 UTC, merged