1-Handed Crusher
yogstation13/Yogstation pull request #17496
Opened 2023-01-15 18:22 UTC by Xander3359

# Document the changes in your pull request
Changes /obj/item/twohanded/required/kinetic_crusher to /obj/item/twohanded/kinetic_crusher .
Attempting to use the crusher 1-handed makes the player fumble and drop everything they are holding.

# Changelog

:cl:  
tweak: crusher can now be held in 1 hand, wield it to properly use it.
/:cl:

2023-01-15 18:29 UTC, TheGamerdk commented
PR freeze

2023-01-15 18:54 UTC, Moltijoe commented
All two handed weapons have both a wielded and unwielded sprite, i assume this will cause sprite issues since there isnt an unwielded crusher sprite

2023-01-16 07:02 UTC, UltraBigRat commented
this change could honestly be given to alot of two handed weapons, theyre such a pain to use as the only way to  do anything other then bonk things with them is dropping it, which may make you lose it.

2023-01-16 12:27 UTC, Xander3359 commented
Yeah the sprites are fucky since there's no 1 hand, if this goes through I'd like to PR porting over the TG sprites, or requesting a spriter to help me out with this since I have 0 spriting experience.

2023-01-16 14:38 UTC, MajManatee requested changes
definitely needs a sprite before being merged

2023-01-16 14:38 UTC, MajManatee commented
@KillerOrcaCora @cuackles

2023-01-16 15:01 UTC, cuackles commented
I would like to see the Tg sprites first, if they are not adequate for the server then a spriter could make a replacement

2023-01-16 15:55 UTC, Xander3359 commented
> I would like to see the Tg sprites first

![Crusher Sprite](https://user-images.githubusercontent.com/66163761/212719730-8bb78fb7-d7ee-4c68-8fd9-85ef3cbb1d57.png)
Dunno how to best display it but I gave it a solid attempt.

2023-01-16 21:19 UTC, MajManatee commented
You would have to replace our current crusher, but i like it

2023-01-26 18:32 UTC, MajManatee commented
ok next step actually add the sprite to the PR @Xander3359

2023-02-03 16:48 UTC, MajManatee commented
No activity, PR unfinished. Please re-open when work continues.

2023-02-03 16:48 UTC, closed without merging