Nerfs jelly people slightly and makes them roundstart available
yogstation13/Yogstation pull request #17505
Opened 2023-01-16 06:43 UTC by Moltijoe

More round start races that aren't lizards is always good.
I removed the 0.5 burn mod so they aren't busted (slime, luminescent and stargazers still get it)
The only fancy things they have are the limb loss on low blood / limb regrow ability
and the inverted toxin damage

:cl:  
rscadd: Jelly people can be played at round start
/:cl:

2023-01-16 06:44 UTC, cowbot92 commented
Solid PR, think more round start races are always good and jelly people are unique enough (rip skrem have fun with the lore)

2023-01-16 07:23 UTC, Burger1998 commented
xenobio nerf in a trenchcoat. good.

2023-01-16 10:54 UTC, ThatLing commented
This conflicts with the preferences rework, so this PR will be on-hold until then. You will have add additional things if you want them to be available roundstart

2023-01-16 16:07 UTC, Moltijoe commented
> This conflicts with the preferences rework, so this PR will be on-hold until then. You will have add additional things if you want them to be available roundstart

assumed it would happen 👍

2023-01-17 00:03 UTC, Marmio64 commented
i feel like they're still an upgrade to being a human, where the other races have upsides but yet are clearly designed as a sidegrade/downgrade. In addition I feel like they just dont need to be another race, we have a bunch already, why not just keep slimepeople to xenobio.

2023-01-17 09:03 UTC, Moltijoe commented
> i feel like they're still an upgrade to being a human, where the other races have upsides but yet are clearly designed as a sidegrade/downgrade. In addition I feel like they just dont need to be another race, we have a bunch already, why not just keep slimepeople to xenobio.

these aren't slimepeople, they're jelly people and they most certainly are not a direct upgrade to humans. being put into a cryotube kills them faster than it heals, charcoal kills them, they die ridiculously quickly if they spend even slightly too long in a spaced room.

2023-01-18 01:48 UTC, Marmio64 commented
> > i feel like they're still an upgrade to being a human, where the other races have upsides but yet are clearly designed as a sidegrade/downgrade. In addition I feel like they just dont need to be another race, we have a bunch already, why not just keep slimepeople to xenobio.
> 
> these aren't slimepeople, they're jelly people they don't have the body split thing and they most certainly are not a direct upgrade to humans. being put into a cryotube kills them faster than it heals, charcoal kills them, they die ridiculously quickly if they spend even slightly too long in a spaced room.

I know precisely what they are. They also barely worry about limb loss, don't worry about many conventional toxins, and have very high heat resistance.

2023-01-18 05:26 UTC, Moltijoe commented
> I know precisely what they are. They also barely worry about limb loss, don't worry about many conventional toxins, and have very high heat resistance.

IPC, plasmeme, and preternis don't really need to worry about limb loss either
toxins are neither all that prevalent nor are they hard to counter, all it takes is one charcoal pill to counter most poisons
not to mention, if you're trying to kill a jellyperson, just used charcoal as your poison of choice.
also, heat mod of 0.5 isn't nearly that powerful and it's more than outweighed by the cold mod of 6,

2023-01-18 21:22 UTC, Marmio64 commented
> > I know precisely what they are. They also barely worry about limb loss, don't worry about many conventional toxins, and have very high heat resistance.
> 
> IPC, plasmeme, and preternis don't really need to worry about limb loss either (probably poly too, not sure how much their wound armour factors in) toxins are neither all that prevalent nor are they hard to counter, all it takes is one charcoal pill to counter most poisons not to mention, if you're trying to kill a jellyperson, just used charcoal as your poison of choice. also, heat mod of 0.5 isn't nearly that powerful and it's more than outweighed by the cold mod of 6,

even if they're balanced i still see no point in adding more races, especially if they're supposed to be xenobio exclusive.  Next we'll be adding super weak golems that can wear clothes as roundstart species, which like 1 person will play and confuse everyone because they'll all think it's a servant golem.

2023-01-18 23:18 UTC, Moltijoe commented
> even if they're balanced i still see no point in adding more races, especially if they're supposed to be xenobio exclusive. Next we'll be adding super weak golems that can wear clothes as roundstart species, which like 1 person will play and confuse everyone because they'll all think it's a servant golem.

Theres no reason not to add more species if they fit, even if only one person plays them, that's still one person playing the species they enjoy. 
Jellypeople aren't xenobio exclusive, they just don't exist, all the upgraded jellyperson species will still be exclusively xenobio.
Also, likening this to golems isn't that reasonable as they have so many differences from other species that they shouldn't ever be considered for proper crewmates. That would be like me saying shadowpeople should be round start.

2023-01-28 15:45 UTC, ThatLing requested changes
This will need changes to work with the preferences. Message me on discord if you need help

2023-01-30 16:11 UTC, Moltijoe commented
> This will need changes to work with the preferences. Message me on discord if you need help

ah, didn't notice prefs were full merged, assumed they were just test merged still

2023-01-30 17:09 UTC, ThatLing requested changes

2023-01-30 17:09 UTC, ThatLing commented on code/modules/mob/living/carbon/human/species_types/jellypeople.dm
> +/datum/species/jelly/get_features()//they currently have no special features
Remove this if they don't

2023-01-30 17:09 UTC, ThatLing commented on code/modules/mob/living/carbon/human/species_types/jellypeople.dm
> +// They may not be roundstart but in the unlikely event they become one might as well not leave a glaring issue open. <- yeah, i'm trying to add them as roundstart
Remove this useless comment

2023-02-06 12:50 UTC, ThatLing commented
@Moltijoe Is this still a draft?

2023-02-06 21:30 UTC, Moltijoe commented
> @Moltijoe Is this still a draft?

Yes until someone tells me how to chance the species icon, since it still just shows an ethereal rather than jellyperson

2023-02-07 01:10 UTC, ThatLing approved these changes

2023-02-11 16:15 UTC, JamieD1 commented
> > @Moltijoe Is this still a draft?
> 
> Yes until someone tells me how to change the species icon, since it still just shows an ethereal rather than jellyperson

this done?

2023-02-11 16:36 UTC, Moltijoe commented
> > > @Moltijoe Is this still a draft?
> > 
> > 
> > Yes until someone tells me how to change the species icon, since it still just shows an ethereal rather than jellyperson
> 
> this done?

Yeah

2023-02-26 12:06 UTC, JamieD1 commented
Lets see how we go shall we

2023-02-26 12:06 UTC, JamieD1 approved these changes

2023-02-26 12:06 UTC, merged