Removes the bluespace bodybag stun
yogstation13/Yogstation pull request #17509
Opened 2023-01-16 07:23 UTC by Majkl-J

# Document the changes in your pull request

Removes the ability of SOME people to surprise bodybag people to easily take them out of fights.

The bluespace bodybag is effectively a 20 second stun, and dropping it resets the breakout timer, so lowering this number (What I previously attempted) just wouldnt work.

Yes this is an ided, tag it.

# Changelog

:cl:  
rscdel: Removed the timer on breaking out of the bluespace bodybag
/:cl:

2023-01-16 07:27 UTC, ToasterBiome requested changes
look at the proc definition of do_after and you can utilize the stayStill variable to make it so dropping it wont cancel.

2023-01-16 17:34 UTC, ReddicusDragon commented on code/game/objects/items/bodybag.dm
> +	if(!do_after(user, 5 SECONDS, src, stayStill = FALSE))
```suggestion
	if(!do_after(user, 10 SECONDS, src, stayStill = FALSE))
```
5 feels too low.

2023-01-16 20:13 UTC, Majkl-J commented on code/game/objects/items/bodybag.dm
> +	if(!do_after(user, 5 SECONDS, src, stayStill = FALSE))
That would make it as long as the stunbaton, too much for a "weapon" any med staff can print 20 mins in.

2023-01-17 16:31 UTC, ReddicusDragon commented on code/game/objects/items/bodybag.dm
> +	if(!do_after(user, 5 SECONDS, src, stayStill = FALSE))
> That would make it as long as the stunbaton, too much for a "weapon" any med staff can print 20 mins in.

I refuse to give thumbs up unless it is 10 seconds. 5 is way too short.

2023-01-18 16:22 UTC, JamieD1 commented
the whole point of the body bag is that you keep corpses fresh, annoying its being used to gamer shit which was not intended at all

2023-01-18 16:23 UTC, JamieD1 approved these changes

2023-01-18 16:24 UTC, merged