Veil mind is now a real ability that darkspawn can take once more
yogstation13/Yogstation pull request #17514
Opened 2023-01-16 08:04 UTC by ynot01

# Document the changes in your pull request

Veil mind is now 2 points from the "let's just make it borderline unobtainable and call it a day" 6 point cost

Veils are now capped at 35 max health, making them significantly weaker and less of an effective offensive or defensive tool

Veils when deconverted will then have 70 max health

# Changelog

:cl:  
tweak: Veil mind is now cheaper, but darkspawn thralls are significantly weakened
/:cl:

2023-01-16 08:30 UTC, Moltijoe commented
Not super keen on the health fuckery since it seems so easily metagamed

2023-01-16 10:53 UTC, ynot01 commented
> Not super keen on the health fuckery since it seems so easily metagamed

i dont consider this unintended or metagame, veils should play better and not get fucked or suffer being veils (supposed to be weak anyways by this PR)

veil mind is primarily invaluable for not being spotted and no one is going to be checking for veils when dspawn isnt spotted yet

2023-01-16 13:02 UTC, Burger1998 commented
> > Not super keen on the health fuckery since it seems so easily metagamed
> 
> i dont consider this unintended or metagame, veils should play better and not get fucked or suffer being veils (supposed to be weak anyways by this PR)
> 
> if someone wants to line up the med doctors and punch them as a thrall check be my guest, the solution is to simply flee or slip out unnoticed, try crafting weapons or something and be useful instead of being AFK in medbay
> 
> veil mind is primarily invaluable for not being spotted and no one is going to be checking for veils when dspawn isnt spotted yet

darkspawn usually are noticed very quick due to their nature whereas slings can just hide in walls and move at light speed to the other side of maint along with their abilitys making VERY distinct sounds

2023-01-16 15:54 UTC, MajManatee approved these changes
Cant wait to hit someone once with a pulse slug and they literally just die instantly.

2023-01-16 17:07 UTC, ReddicusDragon requested changes

2023-01-16 17:07 UTC, ReddicusDragon commented on yogstation/code/game/gamemodes/darkspawn/veil.dm
> +	to_chat(owner, span_danger("Your drained will has left you feeble and weak! You will go down in many fewer hits!"))
```suggestion
	to_chat(owner, span_danger("Your drained will has left you feeble and weak! You will go down with many fewer hits!"))
```

2023-01-16 17:07 UTC, ReddicusDragon commented on yogstation/code/game/gamemodes/darkspawn/veil.dm
> +	to_chat(owner, span_danger("Your drained will has left you feeble and weak! You will go down in many fewer hits!"))
it should honestly be with fewer hits but meh. The thing here is "You will go down in fewer hits" doesn't make much sense to me.

2023-01-22 13:52 UTC, merged

2023-02-10 02:00 UTC, Mqiib commented
Holy shit how did i never see this pr this is fucking awful