Bluespace locker no longer has infinite power
yogstation13/Yogstation pull request #17517
Opened 2023-01-16 11:28 UTC by ThatLing

# Document the changes in your pull request
It's stupid that the bluespace locker gives you an area with infinite power for free. You will now have to provide an external power source (e.g. P.A.C.M.A.N generator) if you want to use machines inside.

I added an APC inside the locker and removed the ``requires_power = FALSE`` flag so stuff actually requires power. The APC spawns with 90% charge like default, however the 2 lights inside will use some of it over time.

# Changelog

:cl:  
tweak: Bluespace locker no longer has infinite power, it's powered by an APC now.
/:cl:

2023-01-16 13:02 UTC, wejengin2 requested changes
We don't use the autoname apc's, please use one of the manual ones to set the area and name by hand.

2023-01-16 13:05 UTC, wejengin2 commented
My personal opinion is that this is needlesly limiting, bluespace locker is supposed to be this magical fun place where you can make crazy projects without having to worry about things such as no power for your machines.

2023-01-16 16:00 UTC, MajManatee commented
I agree with Wej

2023-01-16 16:47 UTC, ReddicusDragon commented
this is stupid. Why ruin player fun? People love using the bluespace locker as a place to bullshit and build funny small projects

2023-01-16 20:53 UTC, TheRyeGuyWhoWillNowDie commented
Mid

2023-01-17 01:32 UTC, RG4ORDR commented
Absolutely not.
I wont even give an explanation. Just bad all round.

2023-01-17 10:20 UTC, ThatLing commented
> My personal opinion is that this is needlesly limiting, bluespace locker is supposed to be this magical fun place where you can make crazy projects without having to worry about things such as no power for your machines.

Why should BS locker be "magical" and have infinite power? If you want to build crazy projects without worrying about power, we have both aux base construction and normal construction area on Yogstation, with the former even giving you your own solar for power.


> this is stupid. Why ruin player fun? People love using the bluespace locker as a place to bullshit and build funny small projects

God forbid people have to actually put in a little effort to get power inside the locker. You're acting like this will make the locker useless when in reality there's a dozen ways to power it, such as a PACMAN or simply changing out the power cell.

2023-01-17 12:29 UTC, JamieD1 approved these changes

2023-01-18 00:20 UTC, Moltijoe commented
Would be nice if the APC inside the locker could charge from the APC of the room the locker is in.

2023-01-18 02:34 UTC, TheLinuxOS commented
This is a horrible change, not only does it detract from the magic of the bluespace locker- It also removes 1 of the precious tiles by making you build a generator in there that could go completely against the aesthetic.

2023-01-18 05:44 UTC, adamsong commented
If you are going to make it draw power, make it draw from the area in which the outside is

2023-01-18 07:36 UTC, ThatLing commented
> This is a horrible change, not only does it detract from the magic of the bluespace locker- It also removes 1 of the precious tiles by making you build a generator in there that could go completely against the aesthetic.

Or you can just replace the power cell in the APC and still use all of the tiles, crazy right? I hope you realize that the bluespacer having infinite power because "magic" is an insanely lame excuse.

2023-01-18 07:52 UTC, wejengin2 approved these changes
map fine

2023-01-18 20:55 UTC, TheLinuxOS commented
> > This is a horrible change, not only does it detract from the magic of the bluespace locker- It also removes 1 of the precious tiles by making you build a generator in there that could go completely against the aesthetic.
> 
> 
> 
> Or you can just replace the power cell in the APC and still use all of the tiles, crazy right? I hope you realize that the bluespacer having infinite power because "magic" is an insanely lame excuse.

and I hope you realize how insanely lame it is to try to limit the bluespace locker

2023-01-18 21:31 UTC, ThatLing commented
> > > This is a horrible change, not only does it detract from the magic of the bluespace locker- It also removes 1 of the precious tiles by making you build a generator in there that could go completely against the aesthetic.
> > 
> > 
> > Or you can just replace the power cell in the APC and still use all of the tiles, crazy right? I hope you realize that the bluespacer having infinite power because "magic" is an insanely lame excuse.
> 
> and I hope you realize how insanely lame it is to try to limit the bluespace locker

What a cope reply

2023-01-18 23:42 UTC, Moltijoe commented
why are people trying to balance around the bluespace locker? it's tedious as hell to find it, if someone finds it only to figure out all the fun gimmicks were killed, that's kinda cringe.

2023-01-19 12:07 UTC, JamieD1 commented
> why are people trying to balance around the bluespace locker? it's tedious as hell to find it, if someone finds it only to figure out all the fun gimmicks were killed, that's kinda cringe.

Its hardly tedious to find, people go assistant just to find the locker and they find it before like 20-30 mins. If anything it needs to be made harder to find.

2023-01-19 12:09 UTC, ThatLing commented
> why are people trying to balance around the bluespace locker? it's tedious as hell to find it, if someone finds it only to figure out all the fun gimmicks were killed, that's kinda cringe.

You're legitimately delusional if you think this "kills" all fun gimmicks you can do

2023-01-22 08:48 UTC, UltraBigRat commented
Biggest question here, why? whats the reasoning here other then bluespess locker bad i nerf? i really dont see how this is good for the game whatsoever.

2023-01-22 13:28 UTC, merged

2023-01-23 22:03 UTC, CrazyDrakkon commented
The APC power/status stays the same when the locker is destroyed.