The ReWallening: Remaps most of the reinforced walls on Yogstation.
yogstation13/Yogstation pull request #17525
Opened 2023-01-16 17:30 UTC by BurgerLUA

# Document the changes in your pull request

Here is basically what I did. I mass replaced every rwall with a regular war, and then manually placed reinforced walls based on an arbitrary checklist (below).

> Reinforced walls must encase:
> - Anything that contains expensive objects, such as Head equipment and the AI core.
> - Anything that contains dangerous objects or people, such as gas, chemicals, prisoners, the command console, or science experiments.
> - Anything that will be used for general EVA construction

Areas that are reinforced:
- All Head offices.
- All of engineering and atmos (Except the lobby).
- All of command.
- Anything that involves the AI.
- Secure Tech Storage
- Anything that contains prisoners.
- The Armory (except the warden's office).
- Toxins.
- All Xenobiology containment cells.
- The experimentor room.
- Cloning (but not genetics).
- Chemistry.
- Aux Base construction area.
- Space Pod construction area.
- Execution Area/Transfer Center.

I also removed the near-redundant reinforced walls outside the secondary AI core because they made no sense.

# Wiki Documentation

Wiki slaves will need to take screenshots of all the areas affect lol lmao.

# Changelog

:cl:  BurgerBB
mapping: Removes and adds reinforced walls to some areas on Yogstation.
mapping: Removes the near-redundant reinforced walls outside the secondary AI core.
/:cl:

2023-01-16 17:33 UTC, MajManatee commented
secretly an AI nerf, smh

2023-01-16 18:45 UTC, 00ze-cyclone commented
I don't think taking away sec Rwalls to give them to the spacepod bay is a good change

2023-01-16 22:49 UTC, wejengin2 commented
bold

2023-01-16 23:15 UTC, BurgerLUA commented
If people don't like a specific change then I can easily reverse it.

2023-01-17 09:47 UTC, wejengin2 requested changes
Let me be honest with you, this is too much. Too chaotic, and seems random at some points even though you followed the rules you laid out for yourself. 
If you really want to do this, atomize.
What i mean is make pr's for each department or general related station area, this way it will be easier to tweak and get input on. Not to mention the map conflicts.

2023-01-17 09:48 UTC, closed without merging