Laser scalpel no longer makes you look like a spessman-shaped nuclear fuel rod
yogstation13/Yogstation pull request #17529
Opened 2023-01-16 22:49 UTC by Mqiib

Changed the base power from 1 to 0.2 so now you don't glow weirdly

![image](https://user-images.githubusercontent.com/43766432/212776298-53e37433-729f-489f-b418-a590a79f8536.png)
![image](https://user-images.githubusercontent.com/43766432/212776329-c3497529-3cc8-40d1-8df5-ed365758cc97.png)

# Changelog

:cl:  

tweak: Scalpel mode for the laser scalpel now significantly less bright

/:cl:

2023-01-16 23:56 UTC, Moltijoe commented
Yeah, with the new lighting system most things feel a lot brighter than before

2023-01-17 12:11 UTC, ThatLing commented on code/modules/surgery/tools.dm
> +	light_power = = 0.2	//Barely glows on low power
```suggestion
	light_power = 0.2 //Barely glows on low power
```

2023-01-17 12:12 UTC, ThatLing commented
> Yeah, with the new lighting system most things feel a lot brighter than before

I kept the same range for all light sources, it just feels larger because it looks different. However, feel free to make a PR to change the numbers

2023-01-17 15:34 UTC, MajManatee commented
is that not what hes doing?

2023-01-17 18:07 UTC, Moltijoe approved these changes
SlingBuff

2023-01-18 07:43 UTC, Moltijoe requested changes
you reverted the fix

2023-01-18 07:43 UTC, Moltijoe commented on code/modules/surgery/tools.dm
> +	light_power = = 0.2	//Barely glows on low power
```suggestion
	light_power = 0.2	//Barely glows on low power
```

2023-01-18 15:41 UTC, ThatLing commented
> is that not what hes doing?

I was replying to Molti, who isn't the author of this PR

2023-01-18 23:04 UTC, Moltijoe approved these changes
is less glowy, it works

2023-01-18 23:05 UTC, merged

2023-01-19 00:03 UTC, Mqiib commented on code/modules/surgery/tools.dm
> +	light_power = = 0.2	//Barely glows on low power
oops lmao