[Box] Fixes Brig Phys camera to not be a copy-paste of Interrogation camera
yogstation13/Yogstation pull request #17562
Opened 2023-01-18 23:54 UTC by Aquizit

# Document the changes in your pull request

As the title says. Replaced the camera in brig phys area, which was a copy-paste of the one in Interrogation, which was causing it to show up incorrectly when trying to monitor Interrogation. (Used the version from yogsmeta, just with a different dir so it's on the wal properly.)

Fixes issue #17561 

# Changelog

:cl:  
bugfix: The monitor outside interrogation now shows the correct view again
bugfix: Brig - Infirmary camera now shows up correctly on the standard camera console
/:cl:

2023-01-18 23:58 UTC, wejengin2 commented
to be merged after trims

2023-01-19 00:11 UTC, wejengin2 requested changes
I would probably name it 'Brig Infirmary' without the '-' for consistency.
![image](https://user-images.githubusercontent.com/48154165/213325301-235daa8c-9e8a-469d-9b52-fb960dadbdad.png)

2023-01-19 12:30 UTC, ThatLing commented
@wejengin2 Trims got trimmed

2023-01-19 13:46 UTC, Aquizit commented
To be redone after work with less merge conflict

2023-01-19 13:46 UTC, closed without merging