(port) adds disfiguration
yogstation13/Yogstation pull request #17577
Opened 2023-01-20 12:23 UTC by boodaliboo

original pr:https://github.com/tgstation/tgstation/pull/45297
"Disfiguration: Makes the host disfigured, causing them to appear as Unknown. (I originally said prosopagnosia but it turns out that trait doesn't affect what you see while mousing over mobs, so it is kind of pointless as a symptom.)"
:cl:  
rscadd: Added new viro symptom Disfiguration: Makes the host disfigured, causing them to appear as Unknown. (I originally said prosopagnosia but it turns out that trait doesn't affect what you see while mousing over mobs, so it is kind of pointless as a symptom.)
/:cl:

2023-01-20 14:17 UTC, ThatLing requested changes
Have you tested this? Seems like you have to actually add the symptom in other places to actually use it. From quickly at the original PR, seems like ``code/modules/antagonists/disease/disease_abilities.dm`` is the approriate file.

2023-01-20 15:49 UTC, boodaliboo commented
> Have you tested this? Seems like you have to actually add the symptom in other places to actually use it. From quickly at the original PR, seems like `code/modules/antagonists/disease/disease_abilities.dm` is the approriate file.

fuck let me check my other branches and see if i changed that shit their

2023-01-22 00:16 UTC, ThatLing requested changes

2023-01-22 00:16 UTC, ThatLing commented on code/datums/diseases/advance/symptoms/disfiguration.dm
> +	if(A.affected_mob)
You're missing a part of your file mate

2023-01-26 16:34 UTC, MajManatee commented
Does not seem to intend to fix issues, nor make functional. Re-open when fixed.

2023-01-26 16:34 UTC, closed without merging