Uranium eating aegun, second try
yogstation13/Yogstation pull request #17582
Opened 2023-01-20 17:31 UTC by 00ze-cyclone

# Document the changes in your pull request

Aegun being just egun+ is boring and it being printable by the billion make it the absolute no brainer pick once it is researched.
There an entire system to make it give you 80 rads after being EMPed 73720372 times which unsurprisingly never fucking happen so that whole code is pretty much useless.

Now aegun is recharged with uranium instead of passively charging, the overloading bullshit that didn't matter ever got yeeted.
You use a sheet of uranium on the aegun and wait one second to refill it by 50%, doing so give you 150 rads so you have to worry about that (also with the uranium you are carrying I guess but you can carry a stack of 50 sheet so you'll never really run out). 
This mean that you now have to think about your ammo and get briefly to cover to reload as moving while reloading cancel it and give you more rads and some toxin damage immediately.

A cool thing about energy weapons is switching firemodes on the go, I gave it two additional firemode to make it a little bit more unique compared to regular egun and also enable greater warcrimes: irradiate and suffocate
-irradiate shoot an xray laser like the xray gun, 10 shots (xray gun is 14 so if you only want the xray and without fear of cancer then you tkae it over the aegun)
-suffocate bring once again my latest warcrime beams: anoxia rays! 8 oxygen damage, 20 shots

# Spriting
disable
![aegun disable](https://user-images.githubusercontent.com/96987868/213764127-ad0ea152-ab24-4fb1-9572-ba9f18f95e90.png)

kill
![aegun kill](https://user-images.githubusercontent.com/96987868/213764154-5e0ec8e2-0ec0-45e5-9b00-7409ad140852.png)

irradiate
![aegun irradiate](https://user-images.githubusercontent.com/96987868/213764191-ea6691b8-adc7-4afd-9e76-becab5c4dfeb.png)

suffocate
![aegun suffocate](https://user-images.githubusercontent.com/96987868/213764213-37eaec3c-1f5d-4f6d-a45c-7713c2d4ff8e.png)

# Wiki Documentation
Advanced energy gun now use uranium sheets and ores to be reloaded, can't be recharged otherwise, ore is 50% less effective than sheets.

Moving while recharging cancel the action and give you 5 toxin damage and 100 rads if you used uranium ore, 10 toxin and 200 rads if you used an uranium sheet.

-20 disable: 30 stamina disabler beam
-10 kill: 20 burn laser
-10 irradiate: 10 burn and 300 rads xray lasers
-20 suffocate: 8 oxygen anoxia rays

# Changelog

:cl:  
rscadd: Aegun can now shoot xray lasers and anoxia rays
tweak: Aegun now use uranium to recharge, doesn't self charge anymore and still do not fit in rechargers
/:cl:

2023-01-20 17:33 UTC, ynot01 commented
very cool

2023-01-20 22:18 UTC, cuackles commented
could you show them ingame please, preferably all of them next to each other on the ground

2023-01-21 09:43 UTC, 00ze-cyclone commented
> could you show them ingame please, preferably all of them next to each other on the ground

done

2023-01-21 19:32 UTC, cuackles commented
could you lower the saturarion on the green and red one to make them just slightly darker

2023-01-21 22:41 UTC, 00ze-cyclone commented
> could you lower the saturarion on the green and red one to make them just slightly darker

I'll try

2023-01-25 23:51 UTC, Moltijoe requested changes

2023-01-25 23:51 UTC, Moltijoe commented on code/modules/projectiles/guns/energy/energy_gun.dm
> +obj/item/gun/energy/e_gun/nuclear
```suggestion
/obj/item/gun/energy/e_gun/nuclear
```

2023-01-27 19:41 UTC, MajManatee commented
cool as it is, i cannot see anyone using a weapon that deliberately kills themselves.

2023-01-27 20:59 UTC, 00ze-cyclone commented
> cool as it is, i cannot see anyone using a weapon that deliberately kills themselves.

There are people who play plasmaman to remove their helmet and set people on fire, we have TTV suicide bombers, I'm sure a lot of people would actually use a gun that kill the user slowly.

2023-01-28 07:10 UTC, Majkl-J commented
Preternis is the new sec race now it seems

2023-01-28 12:03 UTC, 00ze-cyclone commented
let's see if those conflicts are fixed now

2023-01-31 16:22 UTC, cuackles approved these changes

2023-02-06 11:59 UTC, ThatLing commented
Balance council approved

2023-02-06 15:50 UTC, Moltijoe approved these changes
completely forgot i had reviewed this

2023-02-06 15:52 UTC, merged