A couple hardlight changes
yogstation13/Yogstation pull request #17584
Opened 2023-01-20 18:27 UTC by 00ze-cyclone

# Document the changes in your pull request
rn the hardlight bow are very underwhelming because you spend a lot of ressources for them (illegal tech for sec one, 8 TC for syndie one) and it's just a kinda mid weapon even if pretty cool.

I could powercreep them but I prefer adjusting the prices instead, less chances to break the balance.

For the sec hardlight bow I'm taking it out of illegal tech and instead put it in a new node called hardlight weaponry that need basic weapon tech and T4 microlaser tech. I put the nt usp conversion kit along in it so it doesn't feel lonely and also because it doesn't feel right for sec to be able to make laser sidegrades with their disablers at roundstart (realistically it'll get researched fairly fast since it only need basic weapon tech instead of advanced one).

For the syndicate hardlight bow the cost in the uplink go from 8 TC to 6 like the other small guns that traitors get.

# Wiki Documentation

syndicate hardlight bow is now 6 TC

Hardlight weaponry tech node:
cost 2500 points
unlock security hardlight bow and nt usp conversion kit
require basic weapon tech and quantum electromagnetic technology

# Changelog

:cl:  
rscadd: Added hardlight weaponry tech node unlocking the sec hardlight bow and nt usp conversion kit
tweak: syndicate hardlight bow cost 6 TC from 8 previously
/:cl:

2023-01-20 18:35 UTC, ynot01 approved these changes
the code does what is documented

2023-01-26 15:37 UTC, Moltijoe requested changes
add a location for the research node to layout.dm

2023-01-28 12:28 UTC, 00ze-cyclone commented
> add a location for the research node to layout.dm

done, I though I had done it but I must have lost the commit somewhere while making the PR

2023-01-29 02:41 UTC, Moltijoe approved these changes
can't find anything else wrong with the code

2023-01-30 14:35 UTC, merged