Increase nuke op from 27 to 37 so its not syndicate station 3 (the third one)
yogstation13/Yogstation pull request #17610
Opened 2023-01-22 08:37 UTC by BurgerLUA

# Document the changes in your pull request

Increase Nuke Op pop requirements from 30 to 37.
Increases the minimum amount of nuke ops from 2 to 3.

30 players is lowpop, even when you consider adjusted TC + operatives for playercounts. This change was done to compensate for a previous PR that made lobby idlers partially count as players.

# Changelog

:cl:  BurgerBB
tweak: Increase Nuke Op pop requirements from 30 to 37.
tweak: Increases the minimum amount of nuke ops from 2 to 3.
/:cl:

2023-01-23 18:58 UTC, TheRyeGuyWhoWillNowDie commented
war mode can't be enabled unless there's 40 players (iirc) so this is a non-issue as only 2 operatives will spawn and they'll be too broke to get the really overpowered stuff

2023-01-24 14:58 UTC, MajManatee requested changes
At least adjust the inline documentation to reflect your changes

2023-01-28 12:19 UTC, JamieD1 commented
Change dynamic too, Make it 35, also 30 is not low pop lol

2023-01-30 18:30 UTC, MajManatee approved these changes
i dont think the aditional 5 players should warrant an extra nuke op. 

but the code is fine

2023-02-11 15:50 UTC, merged

2023-02-11 15:54 UTC, ReddicusDragon commented
IM FUCKING STUPID