Fixes mood healing being comically large
yogstation13/Yogstation pull request #17622
Opened 2023-01-23 09:48 UTC by SomeguyManperson

# Document the changes in your pull request

bad argument pass

:cl:  
bugfix: mood is no longer the strongest healing chemical in the game
/:cl:

2023-01-23 10:48 UTC, TheGamerdk requested changes, later dismissed
To restore pre-bug numbers

2023-01-23 10:48 UTC, TheGamerdk commented on code/modules/mob/living/carbon/human/life.dm
> +					heal_bodypart_damage(0.2, 0, 0, TRUE, BODYPART_ORGANIC)
```suggestion
					heal_bodypart_damage(0.2*2, 0, 0, TRUE, BODYPART_ORGANIC)
```

2023-01-23 10:48 UTC, TheGamerdk commented on code/modules/mob/living/carbon/human/life.dm
> +					heal_bodypart_damage(0, 0.2, 0, TRUE, BODYPART_ORGANIC)
```suggestion
					heal_bodypart_damage(0, 0.2*2, 0, TRUE, BODYPART_ORGANIC)
```

2023-01-23 13:44 UTC, ThatLing requested changes
Implement delta_time properly in ``/datum/controller/subsystem/mobs/fire`` instead

2023-01-23 18:59 UTC, TheGamerdk commented
> Implement delta_time properly in `/datum/controller/subsystem/mobs/fire` instead

Not needed, delta time is just * 2

2023-01-24 21:12 UTC, ynot01 approved these changes

2023-01-25 01:01 UTC, ThatLing approved these changes
I will port the ``delta_time`` for mobs at a later point

2023-01-25 01:02 UTC, merged