remove kinetic accelerator recoil
yogstation13/Yogstation pull request #17655
Opened 2023-01-26 00:59 UTC by TheRyeGuyWhoWillNowDie

who merged this garbage

:cl:  
tweak: kinetic accelerators have no recoil
/:cl:

2023-01-26 01:00 UTC, ToasterBiome requested changes
remove the inaccuracy too

2023-01-26 02:43 UTC, ynot01 commented
-1 miners should be dusted on spawn and not allowed to take any ghost roles

2023-01-26 16:35 UTC, MajManatee commented
I think because all guns were given recoil, it also applied to the KA.

2023-01-27 21:48 UTC, ToasterBiome approved these changes

2023-01-27 21:48 UTC, merged