Science Security & HoS can now enter robotics
yogstation13/Yogstation pull request #17663
Opened 2023-01-26 20:24 UTC by ynot01

# Document the changes in your pull request

The scientist officer exists for 2 reasons

1. Look after robotics and make sure they aren't building giga mechs
2. Look after toxins and make sure they aren't destroying the station
3. Look after xenobiology and make sure they aren't idk powergaming too hard

HOWEVER they don't have access to robotics or xenobiology, so they can't actually do anything besides yell and bang on the door (or ask the captain, RD, or AI to open it, if there is any and they are cooperative), especially if the shutters are closed and they can't see if anything is happening inside.

Problem: Officers will start making mechs and blowing borgs

Solution: Only let them use the airlocks, which is implemented here in ACCESS_ROBO_DOORS

# Changelog

:cl:  
tweak: The security department has been granted robotics access
/:cl:

2023-01-26 20:28 UTC, ToasterBiome requested changes
the way that this works is backwards. Make the generic robo access give you access to robo (inside) and then the new access splits off for things like blowing borgs and making mechs. Yes this is slightly more involved with work but that’s the way we have it already with science access and actually researching

2023-01-26 20:56 UTC, MajManatee commented
Willing to give them xenobio access too? Or are we leaving them screwed over there?

2023-01-26 21:02 UTC, ynot01 commented
> 

Xenobio access not needed, as an officer it is very low priority and dangerous situations are less urgent and distinct as a robo making a combat mech. The point of having robo access is a preventative measure to stop the roboticist before they finish their ultradeath machine

2023-01-26 21:04 UTC, MajManatee commented
Ill remember this when im listening to someone scream "Help xenobio" for the morbillionth time and i cant get in

2023-01-26 21:52 UTC, JamieD1 commented
> Xenobio access not needed, as an officer it is very low priority and dangerous situations are less urgent and distinct as a robo making a combat mech. The point of having robo access is a preventative measure to stop the roboticist before they finish their ultradeath machine. In xenobio, it will almost always be "wtf" but that is their job and you can't bust down their door and make arrests because that is the norm. You will, most of the time, only know a xenobiologist is bad when it is too late.

Probably useful to stop them releasing idiot monsters or aliens or helping kill slimes that escaped

2023-01-27 16:06 UTC, MajManatee approved these changes
idk what biome is on about. Seems like if sec is printing mechs then thats an admin issue to me.

2023-01-27 18:50 UTC, Majkl-J commented
> idk what biome is on about. Seems like if sec is printing mechs then thats an admin issue to me.

Not that this disalows them from doing it so I guess its fine

2023-01-27 21:49 UTC, ToasterBiome approved these changes
maps fine

2023-01-28 00:18 UTC, ReddicusDragon commented
coder and mapping approved, merging this

2023-01-28 00:19 UTC, merged

2023-01-28 07:05 UTC, Maia-J commented on code/game/mecha/mech_fabricator.dm
> +	req_access = list(ACCESS_ROBO_CONTROL)
This does nothing, you need to re-add the lines removed from ui_interact some time back.

	if(!allowed(user) && !combat_parts_allowed && !isobserver(user) && !hacked)
		to_chat(user, span_warning("You do not have the proper credentials to operate this device!"))
		return

2023-01-28 07:05 UTC, Maia-J commented on code/game/mecha/mecha_control_console.dm
> +	req_access = list(ACCESS_ROBO_CONTROL)
This probably does nothing too for about the same reason, but unlike the mechfab I didn't test it and am too lazy to launch my testing server again