adds a new reagent called juggernog that increases your total health temporarily
yogstation13/Yogstation pull request #17679
Opened 2023-01-28 14:47 UTC by boodaliboo

adds a new chemical thats a subtype of brave bull thats none alcoholic
it increases your total health by 50 while in your system
but be warned if your only kept alive by the 50 extra health points given you can be put into crit or die
i put this at 8tc as i give a combat hypospray filled with it 2 vials and 2 bottles of it
im intrested in all of your opinions

:cl:  
rscadd: Adds a new traitor chemical that increases your total health temporarily
/:cl:

2023-01-28 14:49 UTC, boodaliboo commented
of course it fails oh well ill check it tommorow

2023-01-28 14:54 UTC, boodaliboo commented
1 error yay

2023-01-29 12:23 UTC, Burger1998 commented
wouldn't nukies use this better as their against pure damage when usually a traitor is fucked by stamina damage not raw damage.

2023-01-29 21:33 UTC, Moltijoe requested changes

2023-01-29 21:33 UTC, Moltijoe commented on code/modules/uplink/uplink_items.dm
> +		The box contains a hypospray with our juggernog and stimulant mix ™, 2 more vials of the mix, and two bottles of it.
```suggestion
		The box contains a hypospray with our juggernog and stimulant mix ™, 2 more vials of the mix, and two bottles of it."
```

2023-01-29 21:33 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	M.health += 50
change it so that this is a variable rather than hard coded

2023-01-29 21:33 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	M.health = min(M.health - 50, M.maxHealth) //This can indeed crit you if you're alive solely based on alchol ingestion
variable here too

2023-01-30 05:52 UTC, boodaliboo commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	M.health = min(M.health - 50, M.maxHealth) //This can indeed crit you if you're alive solely based on alchol ingestion
why it works

2023-01-30 06:10 UTC, SapphicOverload commented
> wouldn't nukies use this better as their against pure damage when usually a traitor is fucked by stamina damage not raw damage.

stamina crit is based on max health, so this will let you take 50 more stamina damage before crit

2023-01-30 06:15 UTC, boodaliboo commented
> wouldn't nukies use this better as their against pure damage when usually a traitor is fucked by stamina damage not raw damage.

yes

2023-01-30 14:19 UTC, MajManatee commented
ok but is this one ALSO gonna sit idle for a week and not work?

2023-01-30 14:53 UTC, Burger1998 commented
> > wouldn't nukies use this better as their against pure damage when usually a traitor is fucked by stamina damage not raw damage.
> 
> stamina crit is based on max health just like normal crit, so this will let you take 50 more stamina damage before crit

but by then your slowed down anyways and the next 3 disabler bolts are STILL going to ruin your day because stamina slowdown is a fair and balanced thing (:

2023-01-30 21:24 UTC, MajManatee requested changes
Missing the DMI files. Also, is it just a hypospray? Couldnt you make it a drink like its supposed to be?

2023-02-01 09:53 UTC, TheGamerdk commented
On the basis of discussion amongst the balance council this would likely make nukies too tanky.

If you can find a different niche for it we'd be happy to look it over again.

2023-02-01 09:53 UTC, closed without merging