Slipping now bypasses knockdown/stun immunity.
yogstation13/Yogstation pull request #17708
Opened 2023-01-30 15:53 UTC by BurgerLUA

# Document the changes in your pull request

Slipping now bypasses knockdown/stun immunity. Mobs/whatever that were stun immune would have the slip sound play but wouldn't actually slip because they were stun and knockdown immune. I can't tell if this was a bug or a balance decision so I'm just going to label this change as a tweak.

Species/items with slip immunity still work.

# Changelog

:cl:  BurgerBB
tweak: Slipping now bypasses knockdown/stun immunity.
/:cl:

2023-01-30 16:05 UTC, Moltijoe requested changes
just remove the sound rather than let it bypass
stun immunity is rare enough that having banana peels or a wet floor being able to bypass it makes little sense

2023-01-30 16:05 UTC, iamthesilly commented
RIP pretty much every anti-stun effect

2023-01-30 16:09 UTC, BurgerLUA commented
> just remove the sound rather than let it bypass stun immunity is rare enough that having banana peels or a wet floor being able to bypass it makes little sense

Stun immunity is for things like getting hit by a baton. It makes no sense that being stun immune somehow manages to make you immune to lube.

2023-01-30 16:15 UTC, MajManatee commented
I mean it makes sense...

2023-01-30 16:42 UTC, Moltijoe commented
> I mean it makes sense...

i'd accept them falling down, but not getting stunned

2023-01-30 16:48 UTC, BurgerLUA commented
> > I mean it makes sense...
> 
> i'd accept them falling down, but not it keeping them down or getting stunned

I can remove the stun portion so it only does the 2 second knockdown.

2023-01-30 17:55 UTC, Moltijoe commented
> I can remove the stun portion so it only does the 2 second knockdown.

that's better than "stunning" a stun immune person

2023-01-30 18:07 UTC, Burger1998 commented
for anyone not knowing the context of this pr its to nerf zombies slipping people.

2023-01-30 18:24 UTC, MajManatee commented
coulda just made zombies no immune to slipping my themselves.

2023-01-30 18:31 UTC, Moltijoe commented
or remove stun immunity from zombies and give them a 0 stamina mod

2023-01-30 20:52 UTC, BurgerLUA commented
> for anyone not knowing the context of this pr its to nerf zombies slipping people.

It was semi-requested. I was told to do something about zombies dragging things like watertanks so this would solve it.

2023-01-31 02:13 UTC, Moltijoe commented
> It was semi-requested. I was told to do something about zombies dragging things like watertanks so this would solve it.

this is an unneeded nerf to far more than just zombies. 
If the problem is with zombies, nerf zombies.

2023-01-31 04:06 UTC, Marmio64 commented
dragging water tanks and slipping people is like one the very few strategical things a zombie can do and is outright necessary for the midround zombie to be able to have a chance at winning.

2023-01-31 04:22 UTC, Moltijoe commented
> dragging water tanks and slipping people is like one the very few strategical things a zombie can do and is outright necessary for the midround zombie to be able to have a chance at winning.

this is just my opinion, but zombies shouldn't win unless the crew is incompetent.
They should be a constant threat and even take over the station, but there should almost always be a handful of survivors

2023-01-31 05:35 UTC, BurgerLUA commented
If traitors want to be immune to slips, they should buy noslip equipment.

It makes zero sense that stimulants make you immune to slips.

2023-01-31 05:55 UTC, Moltijoe commented
> It makes zero sense that stimulants make you immune to slips.

stims would be unaffected by this change, they don't give stun immunity, they just rapidly regen stamina and remove CC from the metabolizing mob

2023-01-31 06:52 UTC, BurgerLUA commented
> > It makes zero sense that stimulants make you immune to slips.
> 
> stims would be unaffected by this change, they don't give stun immunity, they just rapidly regen stamina and remove CC from the metabolizing mob

I swear while looking in code it gave you actual stun immunity, but that might've been just bath salts and a gas.

2023-01-31 08:02 UTC, Moltijoe commented
> I swear while looking in code it gave you actual stun immunity, but that might've been just bath salts and a gas.

Yeah. Pretty sure its bath salts and stimulum.

2023-01-31 11:54 UTC, neeshacark commented
> > for anyone not knowing the context of this pr its to nerf zombies slipping people.
> 
> It was semi-requested. I was told to do something about zombies dragging things like watertanks so this would solve it.



> > dragging water tanks and slipping people is like one the very few strategical things a zombie can do and is outright necessary for the midround zombie to be able to have a chance at winning.
> 
> this is just my opinion, but zombies shouldn't win unless the crew is incompetent. They should be a constant threat and even take over the station, but there should almost always be a handful of survivors

zombies suck already, i haven't seen a proper zombie takeover or even anything close to it for months

2023-01-31 14:21 UTC, MajManatee commented
literally yesterday

2023-01-31 18:25 UTC, Moltijoe commented
one of the last few shifts i've played was a zombie takeover, only reason people survived was because an engiborg was rcding walls everywhere (zombies can't break walls)

2023-02-01 09:05 UTC, TheGamerdk commented
Doesn't make sense that slips bypass stun immunity.

Comments seem to suggest the actual problem is zombies, so do something about those.

2023-02-01 09:05 UTC, closed without merging

2023-02-01 17:44 UTC, BurgerLUA commented
> Doesn't make sense that slips bypass stun immunity.
> 
> Comments seem to suggest the actual problem is zombies, so do something about those.

It was changed to knockdown immunity.