Shimmyjimmies ion bolts to be less "why are they like that" and more "hey that kinda makes sense"
yogstation13/Yogstation pull request #17707
Opened 2023-01-30 08:41 UTC by Mqiib

OLD ION PROJECTILES:
hos gun/ion shotgun shells: 50/50 of heavy or light on target
literally everything else: heavy EMP on target, 50/50 heavy/light on surrounding tiles

ION PROJECTILES NOW:
Standard bulky ion gun: fires 0.5/1 bolts (heavy EMP in the epicenter, light surrounding)
ion carbines: fires 0/1 bolts (light in a 1 tile radius, no heavy)
hos gun: same as standard bulky ion rifle (upgraded from weak bolts)
ion shotgun shell: no longer 50% chance of heavy EMP on hit
mech ion cannon: 2/2 EMP bolt (1 radius heavy, 50/50 of heavy or light in 2 tile radius)
stechkin EMP rounds: now guarantee a heavy EMP on the target

EMP blasts will now only apply a heavy EMP on the epicenter if the heavy radius is greater than 0. This won't affect large EMP effects like EMP grenades, mostly only makes an impact with small EMPs.

# Wiki Documentation

weak bolts: 0/0, used by ion shotgun
light bolts: 0/1, used by ion carbines
standard bolts: 0.5/1, standard EMP bolt used by hos gun and ion rifle
heavy bolts: 2/2, used by heavy ion cannon on mechs

# Changelog

:cl:  
rscadd: Added heavy and light EMP energy projectiles
tweak: Hos gun now shoots REAL ion bolts instead of crappy ones
tweak: Mech ion cannon shoots big boy ion bolts
tweak: Ion shotgun shells can no longer apply heavy EMP effects
tweak: Ion carbines fire weaker ion bolts that can't apply heavy EMP effects
tweak: Stechkin EMP rounds guarantee a heavy EMP on the target
/:cl:

2023-01-30 08:44 UTC, SapphicOverload commented
personally i think the HoS ion should be the same as the ion carbine but not cost as much energy to fire, since it fits inside a bag or armor slot

2023-01-30 09:07 UTC, Mqiib commented
> Personally I think the HoS ion should be the same as the ion carbine but have 5 or more shots instead of 3, since it fits inside a bag or armor slot and is available roundstart.

Reasonable and good suggestion, 5 shots of light bolts is now what it gets.

2023-01-30 15:24 UTC, MajManatee requested changes
makes TOO MUCH sense. please add more nonsense.

2023-01-30 15:24 UTC, MajManatee approved these changes

2023-01-30 18:23 UTC, MajManatee commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +	empulse(target, 0.5, 1) //Heavy EMP on target, light EMP in tiles around
is this comment still accurate then?

2023-01-30 23:10 UTC, Mqiib commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +	empulse(target, 0.5, 1) //Heavy EMP on target, light EMP in tiles around
Yes that's why I changed the number.

2023-02-06 11:37 UTC, ThatLing commented
Balance council approved

2023-02-06 11:38 UTC, merged