Fixes disabler bolts embedding into targets
yogstation13/Yogstation pull request #17718
Opened 2023-01-31 12:42 UTC by SapphicOverload

# Document the changes in your pull request

Pretty sure they aren't supposed to do that

# Changelog

:cl:  
bugfix: fixes disabler bolts embedding into targets
/:cl:

2023-01-31 12:57 UTC, TheGamerdk requested changes, later dismissed
Intended behavior. Not a bugfix, please change to tweak or similar

2023-01-31 12:59 UTC, SapphicOverload commented
> Intended behavior. Not a bugfix, please change to tweak or similar

are you sure it was intended for non-lethal projectiles to cause bleeding and damage from embedding?

2023-01-31 14:35 UTC, SapphicOverload commented
alright i fixed the main issue, embed chance is back but no longer causes bleeding and brute damage

2023-01-31 14:36 UTC, MajManatee commented
yeah the embedding IS intended. idk WHY but it is.

2023-01-31 14:40 UTC, SapphicOverload commented
> yeah the embedding IS intended. idk WHY but it is.

they cause stamina damage over time while embedded, but it wasn't intended that they caused bleeding and stuff

2023-01-31 19:04 UTC, MajManatee commented
i like the idea that ripping a taped object does like 1 brute damage

2023-01-31 21:37 UTC, Moltijoe commented
> i like the idea that ripping a taped object does like 1 brute damage

don't give shitsec a reason to arrest a clown doing something funny

2023-02-05 01:39 UTC, TheGamerdk approved these changes

2023-02-05 01:39 UTC, merged