Gax Arrivals Redesign
yogstation13/Yogstation pull request #17740
Opened 2023-02-01 15:52 UTC by Aquizit

# Document the changes in your pull request

Arranged Gax Arrivals to allow Freeminer Ship to have a docking port. Needed to basically do a full redesign to do so.

![image](https://user-images.githubusercontent.com/70451213/216093785-bb398557-fbc8-46d6-912c-1ee269991aa4.png)

# Wiki Documentation

New map image will need to be put on wiki.

# Changelog

:cl:  
mapping: Adds freeminer docking port to Gax
mapping: Redesign of Gax Arrivals so freeminer ship can fit
/:cl:

2023-02-01 20:10 UTC, ToasterBiome requested changes
lattices look odd between arrivals and the centcom one, and readd the catwalks partially around the shuttle.

Looks good

2023-02-02 09:27 UTC, wejengin2 commented
Some lattices dont have the nearspace area

2023-02-02 14:53 UTC, wejengin2 approved these changes
leaving merge up to biome, already did some of the review on discord

2023-02-03 03:25 UTC, ToasterBiome commented
This is a lot of extra space that will not be used, which I'm a bit hesitant of. Floated you a different idea in the Discord.

2023-02-03 23:23 UTC, Aquizit commented
#17776

2023-02-03 23:23 UTC, closed without merging