buster arm patch
yogstation13/Yogstation pull request #17779
Opened 2023-02-04 12:15 UTC by LazennG

# Document the changes in your pull request

tweaks the buster arm a bit after feedback
-Megabuster no longer disables the arm after use
-former users of the arm should be able to wear gloves again
-mega buster now switches the user's active hand to the appropriate arm when used
-grapple no longer disables the arm when throwing mechs
-all the moves are now actions and hopefully don't stay red forever like they used to
-adds buster arm to one of the centcomm toy rooms
-grappling wire should no longer recharge shots

# Changelog

:cl:  @Chubbygummibear 
bugfix: fixed a few buster arm bugs  
tweak: tweaked buster arm moves 
/:cl:
thanks to chubbygummybear for doing the backbreaking work of showing me how to make the moves into actions

2023-02-04 12:18 UTC, ynot01 commented
Did you test it locally? Also make sure to add yourself in the changelog if you contributed

2023-02-04 12:22 UTC, LazennG commented
> Did you test it locally? 

Yeah

2023-02-04 19:37 UTC, wejengin2 approved these changes
map ok

2023-02-05 05:34 UTC, LazennG commented
few more updates:
-megabuster has a 20 second cd 
-made checks more particular so now the moves of a buster arm are still usable even if a second equipped one is disabled- if you have two buster arms and one gets disabled, you can still use the moves of the other one

2023-02-05 13:10 UTC, ynot01 requested changes
Make it unable to be used when pacifist

2023-02-05 15:55 UTC, ynot01 approved these changes
Code works

2023-02-05 17:14 UTC, merged