Gunlights are back (probably)
yogstation13/Yogstation pull request #17773
Opened 2023-02-03 18:29 UTC by MajManatee

# Document the changes in your pull request

Not gonna lie, I have no idea if this works right now, I am just guessing, but it seems like this was the issue.
a certain SOMEONE, not naming names (ling) might have removed our gunlight overlay sytem when updating our lighting to be not shit.
Anyways, hopefully this fixes that.

# Changelog

:cl:  
bugfix: Gunlight overlay icons fixed??? 🙀 
/:cl:

2023-02-03 18:29 UTC, MajManatee commented
ill be able to test this when im not at my real job.

2023-02-03 18:47 UTC, ThatLing requested changes

2023-02-03 18:47 UTC, ThatLing commented on code/modules/projectiles/gun.dm
> +		if(gun_light.on)
```suggestion
		set_light_on(gun_light.on)
```

2023-02-03 18:47 UTC, ThatLing commented on code/modules/projectiles/gun.dm
> +		if(gun_light.on)
Might have to add ``light_system = MOVABLE_LIGHT`` in ``/obj/item/gun``, as well as ``light_range`` and ``light_power``

2023-02-03 18:47 UTC, ThatLing commented on code/modules/projectiles/gun.dm
> +		set_light(0)
set_light_on(FALSE)

2023-02-03 18:47 UTC, ThatLing commented on code/modules/projectiles/gun.dm
> +		cut_overlay(flashlight_overlay, TRUE)
Delete all this overlay crap

2023-02-03 18:50 UTC, ThatLing commented on code/modules/projectiles/gun.dm
> +		cut_overlay(flashlight_overlay, TRUE)
I have no clue what this overlay is for, if it's for lighting you should remove it. Otherwise keep it

2023-02-03 19:01 UTC, MajManatee commented
I think the code ALSO handled the light movement itself, and I just forgot to remove that bit since its handled elsewhere

2023-02-03 19:08 UTC, ThatLing requested changes
You removed the ``set_light_on`` and didn't add the vars

2023-02-03 20:02 UTC, MajManatee commented
I reckon thats all thats needed

2023-02-03 20:06 UTC, MajManatee commented
The light is handled elsewhere, all this is doing is handling the item overlay, so i removed the set_light_on stuff completley

2023-02-03 20:12 UTC, ThatLing approved these changes

2023-02-05 01:07 UTC, Moltijoe commented
don't think knife is shown on the PKA either, but that can be a different PR

2023-02-05 01:07 UTC, merged