if the round is delayed and you resolve the last ticket you will now be asked to confirm to reboot twice BOXTA
yogstation13/Yogstation pull request #17783
Opened 2023-02-04 17:24 UTC by TheGamerdk

boxta moment smh

2023-02-04 17:25 UTC, Tempolx commented
Bibby moment SMH

2023-02-06 12:41 UTC, ThatLing requested changes

2023-02-06 12:41 UTC, ThatLing commented on yogstation/code/modules/admin/verbs/adminhelp.dm
> +				if(alert(usr,"Restart has been delayed, restart anyways?","Round restart","Yes","No") != "Yes")
Use tgui_alert

2023-02-06 12:41 UTC, TheGamerdk commented on yogstation/code/modules/admin/verbs/adminhelp.dm
> +				if(alert(usr,"Restart has been delayed, restart anyways?","Round restart","Yes","No") != "Yes")
no

2023-02-08 00:56 UTC, JamieD1 approved these changes

2023-02-08 00:56 UTC, merged