Adds a chemical that purges nanites
yogstation13/Yogstation pull request #17812
Opened 2023-02-06 20:46 UTC by Moltijoe

Currently, removing nanites once you have them is almost impossible since it can only be done using a chamber linked to a console.
This adds a chemical that's pretty easy to make that rapidly purges nanites from the host.
Can either be used as an "OH SHIT" in case the nanites start killing you (doesn't help with the instant negative programs)
or as a weapon to remove healing nanites from someone using them to become nigh unkillable.
Carrying around a pill of this is definitely powergaming unless you're a scientist messing around with nanites.

### Wiki documentation
Just say what it is, and how it's made
![image](https://user-images.githubusercontent.com/108117184/217080824-fda7c2e8-5ba7-4d18-a328-34c704ed986e.png)

:cl:  
rscadd: Added a chemical that purges nanites
/:cl:

2023-02-06 21:30 UTC, TheBombMakerJL commented
nanite remover is such a boring name!!!
how about nanolysis?

2023-02-06 21:34 UTC, Moltijoe commented
> nanite remover is such a boring name!!! how about nanolysis?

Nanolysis sounds more like a process, how about Nanolytic Agent?

2023-02-07 09:19 UTC, Uristthedorf commented
Shouldn't this be classified as a toxin? Your liver and selective blood purification should both try to filter this out, especially considering how fast this will kill someone with a nanite heart.
Also, -50 nanite volume will quickly purge someone with full nanite volume in about 11 ticks. Would it be better if this would only completely remove nanites from someone who's already had their volume significantly drained by another source. Or by using multiple doses of the chem to drain someone with full volume?
(I hope I'm reading the code right)

2023-02-07 14:44 UTC, ReddicusDragon approved these changes
Seems good, probably needs balance considerations

2023-02-10 14:42 UTC, ThatLing commented
Balance council said yes

2023-02-10 14:43 UTC, ThatLing requested changes

2023-02-10 14:43 UTC, ThatLing commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	..()
```suggestion
	return ..()
```

2023-02-10 17:29 UTC, ThatLing approved these changes

2023-02-10 17:29 UTC, merged