Snail Race Roundstart
yogstation13/Yogstation pull request #17821
Opened 2023-02-07 10:26 UTC by ynot01

# Document the changes in your pull request

Snails are now roundstart

Can choose from 2 backpacks

Intended to be donator race

## Pros

- 0.5x cold modifier
- Nodrop backpack (Will be emptied on the floor on strip attempt)
- No slowdown on crawling and briefly lubes tiles when crawling
- Always clean
- Space Lube blood

## Cons

- 2x burn modifier
- Crawl-speed run-speed
- Half punch damage
- Nearly incomprehensible
- 2x shock damage
- Takes burn damage from salt

# Changelog

:cl:  
rscadd: Added snails to the list of roundstart races
tweak: Snail backpacks can now be emptied on strip
tweak: Snails now drop their backpacks when thrown in the gibber
/:cl:

2023-02-07 10:26 UTC, JamieD1 commented
Luuuuuuuuuuuuuuuuuuuuuuuubbbbbbbbbbbbeeeeeeeeeeeeeeeeeeee

2023-02-07 10:46 UTC, UltraBigRat commented
could use a rebalance if its being made a roundstart race, considering this is an absolute meme race.

2023-02-07 10:50 UTC, ThatLing commented
Aside from the whole snail fetish thing, donor-only races are a big yikes that I won't support

2023-02-07 11:06 UTC, TheGamerdk commented
I don't support this as a donator-only race either.

I'll consider it as a regular race if the above is dropped I guess

2023-02-07 14:20 UTC, MajManatee commented
Not a fan. Freaky fetish content, no drop bag is basically power gaming, and donors shouldn't be able to pay for an advantage, no matter how small.

2023-02-07 18:40 UTC, ReddicusDragon commented
who the fuck added a closing after 24 hours tag it's a draft not a pr

2023-02-07 18:40 UTC, ReddicusDragon commented
anyways, bad pr make it a non-donor race

2023-02-07 21:56 UTC, Moltijoe requested changes
missing traits details

2023-02-07 21:57 UTC, ynot01 commented
> missing traits details

Which

2023-02-08 19:11 UTC, MajManatee commented
Now that felinids have lost their unique language, it feels even weirder to add this

2023-02-08 19:34 UTC, TheGamerdk commented
I'm of the opinion that paywalling features in an open-source game is horrible.
I don't know any other mainstream server that sells premium benefits like Yogs does, sure they might take donations, but they don't outright sell cosmetics like we do.
Adding this takes us squarely into selling unique game mechanics in my eyes. 
An extra big dick move since this is someone elses code that you're going to be selling access to.

2023-02-08 19:54 UTC, AshCorr commented
I think we already have enough perks for donors that provide ingame benefits. I'd rather this just be a race everyone can play if we're going down the route of making it a roundstart race.

2023-02-09 19:26 UTC, Moja10 commented
snails were literally made to be a donor race years ago, just literally no one PRed it, ynot finally PRs it years later, and suddenly we are against? its literally a garbage meme race that is awful to play, who cares if it's donor only, it is a race of almost entirely negatives

2023-02-09 20:48 UTC, Moja10 commented
> I think we already have enough perks for donors that provide ingame benefits. I'd rather this just be a race everyone can play if we're going down the route of making it a roundstart race.

there is absolutely no benefit from making this purposefully bad race a roundstart race for the general public, it is explicitly designed to be absolutely terrible to play, and offers very little benefit to playing this race. It would be an actual problem if random people could just sit and be useless as a snail, versus limited number of donors being a snail.

2023-02-10 17:29 UTC, wejengin2 commented
Shouldnt be donator only

2023-02-10 18:45 UTC, MajManatee commented
remove the no-drop backpack, and I would support it as donor only.

2023-02-10 21:50 UTC, wejengin2 commented
> remove the no-drop backpack, and I would support it as donor only.

low iq response

2023-02-13 21:46 UTC, JamieD1 commented
As per Vote 961 - Denied.

2023-02-13 21:46 UTC, closed without merging