Darkspawn is now a midround instead of a gamemode
yogstation13/Yogstation pull request #17833
Opened 2023-02-07 22:09 UTC by ynot01

# Document the changes in your pull request

Unfortunately darkspawn rounds go way too quick. Rounds are decided in minutes to either side. Lumping them into other gamemodes should make their flow go a little smoother instead of everyone realizing it's a darkspawn round and spamming lights and validhunting.

If there is 5 or more security members present, 2 darkspawn will spawn, otherwise only 1 will spawn

# Changelog

:cl:  
tweak: Darkspawn has been moved to a midround event instead of a gamemode
/:cl:

2023-02-07 22:10 UTC, SapphicOverload commented
agreed

2023-02-07 22:20 UTC, JamieD1 commented
I mean sure, we can try this.

2023-02-07 22:20 UTC, JamieD1 approved these changes

2023-02-07 22:21 UTC, JamieD1 commented
I mean they are kinda just nightmare now though, maybe remove that?

2023-02-07 22:28 UTC, ynot01 commented
Disabled nightmare at request

2023-02-07 22:58 UTC, Cartlord commented
If memory serves, a Darkspawn victory is a round-ender, so I don't suppot them as a midround - because then everyone's round still gets derailed into dealing with their shit.

2023-02-07 23:13 UTC, MajManatee commented
it doesnt end the round, but it might as well, since I don't think you are killable.

2023-02-08 07:34 UTC, UltraBigRat commented
five sec sounds a bit absurdly high, although i guess for a midround i suppose its meant to be harder?

2023-02-08 10:34 UTC, ThatLing requested changes
Use more descriptive and obvious variable names, who uses ``S`` for a human mob???

2023-02-08 11:38 UTC, ynot01 commented
> Use more descriptive and obvious variable names, who uses `S` for a human mob???

https://github.com/yogstation13/Yogstation/blob/master/code/modules/events/nightmare.dm

2023-02-08 22:48 UTC, neeshacark commented
why disable nightmare? the only similarity they share is that they  both dont like light.

2023-02-11 17:57 UTC, ReddicusDragon commented
![image](https://user-images.githubusercontent.com/36747151/218273435-8182af4f-3308-465b-9f88-b4540ec57b48.png)

2023-02-11 17:59 UTC, ReddicusDragon approved these changes
idk why ling has an issue

2023-02-11 18:37 UTC, ThatLing approved these changes

2023-02-11 18:38 UTC, merged

2023-02-12 03:02 UTC, Lichton commented
'midrounds shouldnt make everyone drop their shit to fight them'
blob.