Adds barricading of airlocks and doors
yogstation13/Yogstation pull request #17848
Opened 2023-02-08 17:46 UTC by Majkl-J

# Document the changes in your pull request

Allows barricading of airlocks and doors, same as with windows. I believe this is fairly reasonable seeing as a few ruins already have that as a thing and putting a few planks across a door is a thing that should be possible.

# Changelog
:cl:  
rscadd: Airlocks and doors can now be barricaded
/:cl:

2023-02-08 18:54 UTC, MajManatee requested changes
as funny as it would be, please add a check to see if there is already a baracade there. 

I can imagine the rage when someone tries to break into cargo only to right click on the door and see 
baracade
baracade
baracade
baracade
baracade
baracade
baracade
baracade
baracade
baracade
baracade
baracade
baracade
baracade
Airlock

2023-02-08 18:59 UTC, Majkl-J commented
> as funny as it would be, please add a check to see if there is already a baracade there.
> 
> I can imagine the rage when someone tries to break into cargo only to right click on the door and see baracade baracade baracade baracade baracade baracade baracade baracade baracade baracade baracade baracade baracade baracade Airlock

The glorious shitcode of the barricade actually seems to already allow this on windows for some reason, fixing time

2023-02-08 18:59 UTC, MajManatee requested changes

2023-02-08 18:59 UTC, MajManatee commented on code/game/machinery/doors/airlock.dm
> +			to_chat(user, span_warning("You need at least five wooden planks to barricade the airlock!"))
```suggestion
			to_chat(user, span_warning("You need at least five wooden planks to barricade the window!"))
```

2023-02-08 19:00 UTC, MajManatee commented on code/game/machinery/doors/airlock.dm
> +			to_chat(user, span_warning("You need at least five wooden planks to barricade the airlock!"))
im dumb

2023-02-08 19:01 UTC, MajManatee commented
did you test on windows too??

2023-02-08 19:02 UTC, Majkl-J commented
> did you test on windows too??

Windows can already be barricaded, and yes, they have that issue on live

2023-02-08 20:21 UTC, MajManatee commented
💀 
halves the removal time...

2023-02-08 20:23 UTC, Majkl-J commented
> 💀 halves the removal time...

That makes it about 20% faster than hitting them with the crowbar on harm and I am not snowflaking that part of code nor giving them more durability

2023-02-08 21:22 UTC, MajManatee approved these changes
should be fine

2023-02-10 09:32 UTC, Moltijoe requested changes

2023-02-10 09:32 UTC, Moltijoe commented on code/game/machinery/deployable.dm
> +		if(I.use_tool(src, user, 100, volume=50))
```suggestion
		if(I.use_tool(src, user, 10 SECONDS, volume=50))
```

2023-02-10 09:32 UTC, Moltijoe commented on code/game/machinery/deployable.dm
> +		if(I.use_tool(src, user, 100, volume=50))
might as well update it to use the defines

2023-02-10 09:59 UTC, Moltijoe approved these changes
❤️

2023-02-10 10:01 UTC, merged