Unfucks darkspawn veils but they're still weaker
yogstation13/Yogstation pull request #17866
Opened 2023-02-10 02:33 UTC by Mqiib

Darkspawn thralls now get -40 max hp. This means they take effectively ~167% damage from all sources. Also you are no longer screwed over after being dethralled with -30 max hp. Finally, makes the effect apply when it's supposed to apply (cloning would entirely circumvent the health increase/loss.)

# Wiki Documentation

Darkspawn thralls lose 40 max hp. Deconversion reverses this.

# Changelog

:cl:  

bugfix: Cloning no longer circumvents darkspawn veil health loss
tweak: Darkspawn veils now lose 40 max hp rather than 65 and get it ALL back upon deconversion  

/:cl:

2023-02-10 02:35 UTC, ynot01 commented
but it's so funny though

2023-02-10 09:10 UTC, Moltijoe requested changes

2023-02-10 09:10 UTC, Moltijoe commented on yogstation/code/game/gamemodes/darkspawn/veil.dm
> +/datum/antagonist/veil/apply_innate_effects(mob/living/mob_override)
```suggestion
/datum/antagonist/veil/remove_innate_effects(mob/living/mob_override)
```

2023-02-10 15:00 UTC, MajManatee commented
thrall them twice and just kill them instantly

2023-02-11 01:42 UTC, Moltijoe approved these changes

2023-02-11 01:43 UTC, merged