Clarifies contributing guidelines
yogstation13/Yogstation pull request #17884
Opened 2023-02-10 20:37 UTC by wejengin2

# Document the changes in your pull request

Removes the word 'draft' from the guidelines in some spots, these rules should apply to all pr's.

![image](https://user-images.githubusercontent.com/48154165/218192742-29486d85-c0be-47d3-afdf-f75df3f05772.png)

# Wiki Documentation

probably not on the wiki

# Changelog

:cl:  
tweak: adjusted contributing guidelines
/:cl:

2023-02-10 20:39 UTC, ToasterBiome requested changes
Some of these should only apply to drafts, the last one (the important one) should not apply and should be in a different area.

2023-02-10 20:39 UTC, ReddicusDragon requested changes

2023-02-10 20:39 UTC, ReddicusDragon commented on .github/CONTRIBUTING.md
>  * A contributor has more than 2 draft Pull Requests open, in which the oldest draft Pull Request should be closed until the author closes another.
Find a different spot for this then because this becomes confusing if you remove draft PR from everything but this sentence

2023-02-10 20:55 UTC, wejengin2 commented
> Some of these should only apply to drafts, the last one (the important one) should not apply and should be in a different area.

im changing it mainly because i think it should apply to all of them, lets just let @JamieD1 decide this. We should have the ability to close pr's of a user that notoriously doesnt fill out the template.

2023-02-10 20:58 UTC, ReddicusDragon requested changes
There

2023-02-10 20:58 UTC, ReddicusDragon commented on .github/CONTRIBUTING.md
> +**All maintainers should encourage discourse and collaboration.** As such, maintainers should only close Pull Requests if:
```suggestion
**All maintainers should encourage discourse and collaboration.** As such, maintainers should only close something if:
```

2023-02-10 20:58 UTC, ReddicusDragon commented on .github/CONTRIBUTING.md
>  * A contributor has more than 2 draft Pull Requests open, in which the oldest draft Pull Request should be closed until the author closes another.
```suggestion
* It is a draft Pull Request and the contributor has more than 2 draft Pull Requests open, in which the oldest draft Pull Request should be closed until the author closes another.
```

2023-02-10 20:58 UTC, ReddicusDragon commented on .github/CONTRIBUTING.md
> +* A contributor has opened a Pull Request that has no changes present in it after the initial 24 hours.
```suggestion
* It is a Pull Request in which the contributor has not implemented any changes in the first 24 hours since it was opened. 
```

2023-02-10 20:58 UTC, ReddicusDragon commented on .github/CONTRIBUTING.md
> +* A contributor has not contributed to their Pull Request in a week’s time.
```suggestion
* It is a pull request in which the author has not contributed to in a week’s time.
* It is an issue that is resolved or an issue that 'won't fix.'
```

2023-02-10 20:58 UTC, ReddicusDragon commented on .github/CONTRIBUTING.md
>  * The Pull Request was opened with inadequate rationale or is lacking naming or following existing guidelines.
```suggestion
* It is a Pull Request that was opened with inadequate rationale or is lacking proper naming or violates existing guidelines in some way.
```

2023-02-10 21:35 UTC, MajManatee commented
law 0 jamie is a maintainer when it comes to these rules

2023-02-10 21:44 UTC, MajManatee commented
Id also like to see some sort of rationale behind PRs with overwhelming negative support, to prevent majorly disliked things from being forcefully added by certain people

2023-02-10 21:47 UTC, ReddicusDragon commented
> Id also like to see some sort of rationale behind PRs with overwhelming negative support, to prevent majorly disliked things from being forcefully added by certain people

Outside the scope of this PR, but I agree

2023-02-10 22:38 UTC, MajManatee commented
bruh how is that outside the scope?

2023-02-26 12:36 UTC, JamieD1 approved these changes

2023-02-26 12:37 UTC, merged