[BOUNTY] Holy Light sect, dedicated to healing
yogstation13/Yogstation pull request #17924
Opened 2023-02-14 00:26 UTC by ynot01

# Document the changes in your pull request

This is a privately paid bounty

Adds a new sect, Holy Light, dedicated to healing

Heals twice as much as normal, but imposes a 12 second cooldown

Has a 20% chance to inflict brain damage instead of 40%

Favor is earned by healing. For each point of damage healed with the bible, you earn favor.

## Rites

### Angelic Assistance

- Creates a medibot called "Holy Medibot"
- Costs 150 favor
- Takes 15 seconds

### Holy Sight

- Creates a one-use medhud implant autosurgeon
- Costs 250 favor
- Takes 15 seconds

### The White

- Creates a Rod of the White which acts as a rod of asclepius but cooler and heals at half the rate
- Costs 400 favor
- Takes 20 seconds

### Rebirth

- Fully heals a buckled mob. If they were dead, also inflicts 75 clone damage. Also applies a white color to them. Healed mob is told that they "forget all that had previously harmed them".
- Costs 650 favor
- Takes 60 seconds

![](https://i.imgur.com/vgM5uwA.png)

# Spriting
![](https://thumbs.gfycat.com/FancyPhonyDragon-max-1mb.gif)

# Changelog

:cl:  
rscadd: Added the Holy Light sect
/:cl:

2023-02-14 00:27 UTC, HisaHoshimo commented
Absolute legend

2023-02-14 00:33 UTC, ToasterBiome commented
cool, rebirth effect might be a bit cringe

2023-02-14 00:35 UTC, HisaHoshimo commented
> cool, rebirth effect might be a bit cringe

Im gonna make sure you get that effect every round

2023-02-14 00:39 UTC, Moltijoe commented
this might actually make me play chaplain

2023-02-16 17:25 UTC, Moltijoe requested changes

2023-02-16 17:25 UTC, Moltijoe commented on code/modules/religion/religion_sects.dm
> +	for(var/obj/item/storage/book/bible/da_bible in L.get_contents())
```suggestion
	for(var/obj/item/storage/book/bible/da_bible in L.GetAllContents())
```

2023-02-16 17:25 UTC, Moltijoe commented on code/modules/religion/religion_sects.dm
> +	for(var/obj/item/storage/book/bible/da_bible in L.get_contents())
in case they shove it in a box inside their backpack or something

2023-02-17 18:03 UTC, cuackles approved these changes
few notes but nothing negative, first thing is that you gave the altar an unique logo icon thingy sing whateverthefuck its called, the cross thingy, so like, good cus 3 of the other religions use the same but diferent color, the staff very good it has the same desing of the other so u can easely tell at a glance that it should do the same or similar stuff, and the white overlay on poeple also looks good i worry that maybe on some characters it will look odd but that can be revised or changed if thats the case and its nothing really to worry about, so anyway yeah good stuff

2023-02-17 20:41 UTC, Moltijoe approved these changes

2023-02-17 20:41 UTC, merged