resolves an admin issue
yogstation13/Yogstation pull request #17957
Opened 2023-02-16 23:39 UTC by TheRyeGuyWhoWillNowDie

people can't fucking restrain themselves from powergaming so instead of making admins police this shit it can be fixed through code

tl;dr autolathes can only be made by departments that get them (service, science, cargo) instead of everyone because sec and medbay making their own autolathes is stupid

# Changelog

:cl:  
tweak: autolathe boards are limited to the the departments that start with them
/:cl:

2023-02-17 00:33 UTC, wonderinghost commented
Well why

2023-02-17 02:25 UTC, warface1234455 commented
Where engineering department

2023-02-17 02:31 UTC, TheRyeGuyWhoWillNowDie commented
> Where engineering department

they don't have an autolathe

2023-02-17 02:38 UTC, warface1234455 commented
> > Where engineering department
> 
> they don't have an autolathe

But there are some parts they need from autolathe for engineering purposes

2023-02-17 03:20 UTC, wonderinghost commented
It isn't really power gaming. If medical was too dumb to grab a welder then they can get a welder to weld the one preterni. And don't say robotics cause preternis still gets revived in medbay

2023-02-17 06:29 UTC, Moltijoe commented
name was misleading

2023-02-18 17:28 UTC, RG4ORDR commented
This was literally tried months ago and it wasn't merged. Same reason too, same result is to be expected.  
Otherwise remove departmental lathes and return to science having the only lathe capable of making anything.

2023-02-26 16:07 UTC, MegaEmpirical commented
Do it. We have a cargo department, people can walk or order shit.

2023-02-26 20:06 UTC, Yogbot-13 commented
#### Test Merge Deployed

##### Server Instance
main

##### Merged By
Alexkar598

##### Revision
Origin: c2e07f090b9608064208668a656da6a54247ae86
Pull Request: 19baca9cccb72b29012ca0ba3da5acb41d303107
Server: e944462d50085599eae1b418e8d9c62b74e26fd1
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

2023-02-26 20:17 UTC, Yogbot-13 commented
#### Test Merge Removed

2023-02-27 14:20 UTC, MajManatee commented
Admin issue not a code issue. Should be closed imo.

2023-02-27 14:23 UTC, MegaEmpirical commented
> Admin issue not a code issue. Should be closed imo.

You shut your trap!

It is generally better to resolve issues by code if doing so makes sense and is viable. In this case, these savages can go deal with Cargo like normal crew.

2023-02-27 16:27 UTC, MajManatee requested changes
and engineering

2023-02-27 17:45 UTC, wonderinghost commented
How funny would it be if engineering can't be engineering. They can't print anything but their department equipment and nothing else

2023-02-27 18:50 UTC, MegaEmpirical commented
Oh? I hadn't considered engineering, I think it should go to to engi and cargo.

2023-02-27 20:00 UTC, wonderinghost commented
Don't forget service. They got one too

2023-03-05 08:00 UTC, TheGamerdk commented
Admin issue

2023-03-05 08:00 UTC, closed without merging