Updates Null Rod menu to TGui
yogstation13/Yogstation pull request #17963
Opened 2023-02-17 06:50 UTC by Moltijoe

with how many null rods we have, selecting is annoying and tedious

:cl:  
tweak: Null Rod selection uses TGui
/:cl:

2023-02-17 13:52 UTC, wejengin2 commented
masochism

2023-02-17 22:59 UTC, Moltijoe commented
> masochism

honestly

2023-03-15 02:18 UTC, ToasterBiome requested changes
The capitalization on these is kinda whack

2023-03-16 08:28 UTC, ThatLing requested changes

2023-03-16 08:28 UTC, ThatLing commented on code/game/objects/items/holy_weapons.dm
> +			var/rodPath = text2path(params["rodPath"])
```suggestion
			var/rodPath = text2path(params["rodPath"])
			if(!ispath(rodPath))
				return FALSE
```

2023-03-17 04:16 UTC, ToasterBiome approved these changes

2023-03-17 08:06 UTC, ThatLing approved these changes

2023-03-17 08:06 UTC, merged