slightly expands box maint
yogstation13/Yogstation pull request #18037
Opened 2023-02-22 23:13 UTC by Marmio64

this just adds a couple extra maint rooms to box, really minor, just to slightly expand it and give a few more places to hide/build evil things in. Some space (such as specifically the extra room in arrivals maint) doesn't have a door so you can weld it open+hide it's entrance and hide things in it without it looking out of place.

This is kind of rushed+ugly and all, but I personally think box could just use with a few extra hiding spots and whatever, so these are just some small things I came up with.

![hiding3](https://user-images.githubusercontent.com/60946370/220783343-3c28395f-9c5b-4de8-ae96-a6cec453e6f4.png)
![hiding2](https://user-images.githubusercontent.com/60946370/220783351-0a0a33fd-24b2-417c-9763-42c5573dc35e.png)
![hiding1](https://user-images.githubusercontent.com/60946370/220783357-12af15e1-e640-4fd3-9d14-bb258330ecb0.png)

# Changelog

:cl:  
rscadd: Adds a little bit more box maint room.
/:cl:

2023-02-22 23:54 UTC, ToasterBiome requested changes, later dismissed
I like the ideas presented, but some concerns:

- The biggest concern is that Asteroid may have implied approval of making maint rooms accessible from weird angles that aren't just pure cardinal directions. In the first image, at the very least the doors should be centered, will have to take a bit more planning. 
- We don't do sectioned off pieces of maint like the middle picture, don't know how I like the sectioned off sectioned off piece of maint either.
- Some indication that there's a room or something would be nice for the last picture instead of it being a closed off box. Below science maint we have tinted walls to imply there's something there instead of "Oops guess you'll never know".
I like the idea of adding more maint and this doesn't add too much bloat.

2023-02-23 01:13 UTC, Marmio64 commented
> I like the ideas presented, but some concerns:
> 
> * The biggest concern is that Asteroid may have implied approval of making maint rooms accessible from weird angles that aren't just pure cardinal directions. In the first image, at the very least the doors should be centered, will have to take a bit more planning.
> * We don't do sectioned off pieces of maint like the middle picture, don't know how I like the sectioned off sectioned off piece of maint either.
> * Some indication that there's a room or something would be nice for the last picture instead of it being a closed off box. Below science maint we have tinted walls to imply there's something there instead of "Oops guess you'll never know".
>   I like the idea of adding more maint and this doesn't add too much bloat.

i can do the other things but i'm not sure why we couldnt have some sectioned off maints, as it helps a great deal with random maint goers just accidently stumbling into antag lairs

2023-02-23 01:33 UTC, Marmio64 commented
adjusted the new maint areas

less sectioned off and centered doors
![hiding1](https://user-images.githubusercontent.com/60946370/220802263-44398b45-8adc-4ac1-9927-fc53b650e21b.png)

centered doors and marginally more space
![hiding2](https://user-images.githubusercontent.com/60946370/220802274-67ea666a-2eca-4b31-ae39-5f5e94b58bc2.png)

adds tinted window to cue the existence of the maint box
![hiding3](https://user-images.githubusercontent.com/60946370/220802277-7077d590-4dee-407b-ad9e-c71ed77f0756.png)

2023-02-23 13:54 UTC, wejengin2 requested changes
this one has no entry
![image](https://user-images.githubusercontent.com/48154165/220927202-03f5c303-30d5-41bf-873d-04f923aa478d.png)

bottom circle has a space turf on it, upper one need to be moved to the right position
![image](https://user-images.githubusercontent.com/48154165/220927715-236d6f5b-ca78-4add-b62b-3c1fe244b0e3.png)
also maybe add a lattice or two on the space side so it doesnt look as blocky

2023-02-23 21:39 UTC, Marmio64 commented
> The sectioned off parts are ok i guess even though they look a bit stupid, its nice to have a path everywhere but we'll see how it goes However: this one has no entry ![image](https://user-images.githubusercontent.com/48154165/220927202-03f5c303-30d5-41bf-873d-04f923aa478d.png)
> 
> bottom circle has a space turf on it, upper one need to be moved to the right position ![image](https://user-images.githubusercontent.com/48154165/220927715-236d6f5b-ca78-4add-b62b-3c1fe244b0e3.png) also maybe add a lattice or two on the space side so it doesnt look as blocky

fixed the space tile and stuff
![Screenshot 2023-02-23 153707](https://user-images.githubusercontent.com/60946370/221036068-ee1ae95c-fee9-4459-9a35-eaa428dd8ba7.png)

but uh, the no entry area has been like that, and i didn't change that. I'm of the opinion that it is fine since it's still pretty obvious something is inside and that it's really not in the 'scope' of this PR which is just expanding it, so I am going to leave it unless you really want it changed in this PR?

2023-02-24 01:06 UTC, wejengin2 approved these changes
Ah ok its fine

2023-02-24 10:05 UTC, merged