Revert "Nerfs Preternis because I want to be the only one that plays them"
yogstation13/Yogstation pull request #18060
Opened 2023-02-24 11:56 UTC by Burger1998

Reverts https://github.com/yogstation13/Yogstation/pull/17810
2 esword hits to fucking take out someones leg while they already deal with getting hardstunned by a water bottle is just a **𝘣𝘪𝘵** much they really didn't need this kinda nerf not everything needs to be a hardmode race.
Changelog 
🆑
tweak: Preternis returned to former glory
/🆑

2023-02-24 18:55 UTC, TheBombMakerJL commented
one disabler shot to leg to fully disable leg
renders antag preternis unviable

2023-02-24 18:57 UTC, Moltijoe commented
Fair

2023-02-24 19:00 UTC, Moltijoe commented
> 2 esword hits to fucking take out someones leg 

Thats literally everyone, esword does 30, limbs have 50

2023-02-24 22:30 UTC, Moltijoe requested changes

2023-02-24 22:30 UTC, Moltijoe commented on yogstation/code/modules/mob/living/carbon/human/species_types/preternis/preternis.dm
> +		user.next_move += 2 //adds 0.2 second delay to combat
if your only problem is the limbs change, leave this part out of the revert

2023-03-05 14:48 UTC, 00ze-cyclone commented
if disabler nerf get merged we can keep the legs as they are.

2023-03-05 22:16 UTC, Moltijoe commented
> if disabler nerf get merged we can keep the legs as they are.

it's approved by balance council, so unless something happens, it probably will

2023-03-07 20:52 UTC, MajManatee commented
Two weeks no pushes / changes not addressed. Reopen when work continues

2023-03-07 20:52 UTC, closed without merging