Adds a magboot multisurgeon to the CE locker
yogstation13/Yogstation pull request #18087
Opened 2023-02-26 01:16 UTC by Skrem7

# Document the changes in your pull request

Not actually a bugfix for magboot implants (they're broken right now), but this multisurgeon works perfectly fine

# Changelog

:cl:  
rscadd: Adds a single-use multisurgeon to the CE locker to grant magboots, in case the CE's legs aren't compatible with the advanced magboots (much like how the CMO gets the MEDhud autosurgeon in-case they're nearsighted)
/:cl:

2023-02-26 01:20 UTC, Moltijoe commented
> Not actually a bugfix for magboot implants (they're broken right now), but this multisurgeon works perfectly fine

PR to fix them has been open for over a week now

2023-02-26 01:20 UTC, Skrem7 commented
> > Not actually a bugfix for magboot implants (they're broken right now), but this multisurgeon works perfectly fine
> 
> PR to fix them has been open for over a week now the absolute state of yogdev

Didn't even notice it was opened lmao

2023-02-26 01:24 UTC, TheGamerdk requested changes, later dismissed
Should only spawn if relevant for the CE

2023-02-26 01:26 UTC, Skrem7 commented
> Should only spawn if relevant for the CE

Impossible to do considering midround joining, unless you want to have the autosurgeon on the CE themselves (bad design)

2023-02-26 01:54 UTC, TheGamerdk commented
> > Should only spawn if relevant for the CE
> 
> Impossible to do considering midround joining, unless you want to have the autosurgeon on the CE themselves (bad design)

Have the auto surgeon spawn on the CE in case of them being a dumb species.
Nothing bad about that

2023-02-26 01:55 UTC, Skrem7 commented
> Have the auto surgeon spawn on the CE in case of them being a dumb species. Nothing bad about that

if you say so

2023-02-26 02:07 UTC, Skrem7 commented
@TheGamerdk there you go

2023-02-26 02:39 UTC, Cartlord commented
why do you keep buffing nonhumans

2023-02-26 02:43 UTC, Skrem7 commented
> why do you keep buffing nonhumans

Could you please illustrate as many reasons as you can why you care?

2023-02-26 03:10 UTC, Cartlord commented
Why do you care so much about removing every meaningful downside from nonhumans? Is it because you play them?

2023-02-26 03:21 UTC, Skrem7 commented
> Why do you care so much about removing every meaningful downside from nonhumans? Is it because you play them?

You're correct, once polysmorph CE's have a vulnerability to EMP roundstart, I plan to move on to actually giving non-humans more upsides. First, I'm going to make lizards do more damage with their fists, move faster, and have innate species armor (lore-accurate).

Next, I'm going to make it so moths can't have their wings burnt off. This way, they won't have downsides, too, so that makes three species (lizard, polysmorph, and moth) have zero total downsides (as they're just better than humans in every way). Not sure yet what I'm going to do for the rest.

And all of these terrible changes that threaten the playerbase catastrophically? It's because of me. My PRs. My lore. My terrible infatuation with non-humans. The same non-human characters that I play the game with (just like you play the game too, right?)

2023-02-26 05:16 UTC, Moja10 commented
>coders add in snowflake feet that don't fit any shoes
>now we have to debate whether to add magboot autosurgeons because otherwise how can a person choose snowflake feet and not have their cake and eat it too

the yogswest has fallen

2023-02-26 08:43 UTC, SapphicOverload commented
having them start in the locker was probably better, the CMO gets a medical HUD autosurgeon in their locker in case they're nearsighted so i don't see why the CE magboot implant should work any differently

2023-02-26 08:57 UTC, Moltijoe commented
> having them start in the locker was probably better, the CMO gets a medical HUD autosurgeon in their locker in case they're nearsighted so i don't see why the CE magboot implant should work any differently

and it'll end up used exactly like the CMO medhud, just given to a random engineer if not needed, and i think that's quite all right. it would also let a considerate CE give magboots to either a poly or lizard engineer that has digitigrade

2023-02-26 10:28 UTC, SapphicOverload commented
alternatively, instead of adding an implant you could make it so you could adjust the advanced magboots to a digitigrade configuration and back with a wrench or screwdriver, though new sprites would be needed for it

2023-02-27 04:55 UTC, Moltijoe requested changes
please change it back to the locker

2023-02-27 20:19 UTC, Skrem7 commented
> please change it back to the locker, this is no different than the CMO's medhud

done

2023-02-27 21:43 UTC, Moltijoe approved these changes

2023-02-27 21:43 UTC, merged