nerfs welding shield eyes
yogstation13/Yogstation pull request #18107
Opened 2023-02-26 23:19 UTC by TheRyeGuyWhoWillNowDie

passive immunity to all forms of eye damage and instant win bulbs while being impossible to tell it's there is bad
changes it from passive to active, gives it a welding helmet effect when active
also removes it's emp immunity?

:cl:  
tweak: welding shield eyes have been nerfed
/:cl:

2023-02-26 23:21 UTC, Mqiib commented
is this welding HELMET or welding GOGGLES effect?

2023-02-26 23:35 UTC, ynot01 requested changes

2023-02-26 23:35 UTC, ynot01 commented on code/modules/surgery/organs/eyes.dm
>  	desc = "These reactive micro-shields will protect you from welders and flashes without obscuring your vision."
This is no longer true in your PR

2023-02-27 00:21 UTC, HisaHoshimo commented
Sounds like making an item thats decent into a useless item that may as well be removed *shrug

2023-02-27 00:25 UTC, ynot01 submitted a review, later dismissed

2023-02-27 00:25 UTC, ynot01 commented on code/modules/surgery/organs/eyes.dm
> +	desc = "These reactive micro-shields will protect you from welders and flashes."
They are not reactive anymore, you have to turn them on yourself

2023-02-27 00:31 UTC, RG4ORDR commented
I don't understand.
Can you explain more in depth why? This simply just seems like a nerf to an item that doesn't get a lot of usage.

2023-02-27 00:34 UTC, TheRyeGuyWhoWillNowDie commented
> I don't understand. Can you explain more in depth why? This simply just seems like a nerf to an item that doesn't get a lot of usage.

medlizard nerf

2023-02-27 00:35 UTC, TheRyeGuyWhoWillNowDie commented
> Sounds like making an item thats decent into a useless item that may as well be removed *shrug

not having to give up your eye or head slot for flash shielding pretty good i think

2023-02-27 00:41 UTC, HisaHoshimo commented
> > Sounds like making an item thats decent into a useless item that may as well be removed *shrug
> 
> not having to give up your eye or head slot for flash shielding pretty good i think

Not value when you get screwed from EMP too, this item is barely used as is and will now be used less.

2023-02-27 00:53 UTC, TheRyeGuyWhoWillNowDie commented
> this item is barely used as is and will now be used less.

Good

2023-02-27 00:57 UTC, HisaHoshimo commented
I feel theres alot better options than this
EMP Protected but activatable
No EMP Protected but passive
Stays as passive but no longer gives flash protection

2023-02-27 05:15 UTC, Uristthedorf commented
At this point, why bother with becoming EMP vulnerable and having to get surgery when you can get a welding shield mask from a lathe, which functions just the same but with no downsides.
Seriously welding shield masks are great, no EMP, can eat while wearing food, functions as a gas mask, takes up the mask slot which isn't too valuable, and is fireproof.
Only reason to get nerfed welding shield eyes over welding gas mask is that you can't have it stripped from you.

2023-02-27 05:57 UTC, Uristthedorf commented
Changelings and anyone wearing a mask can hide their flash protection with no way to find out besides stripping or flashing them. Why is it bad for welding shield eyes in particular to be hard to see and not anything else?

2023-02-27 06:59 UTC, ynot01 commented
> Changelings and anyone wearing a mask can hide their flash protection with no way to find out besides stripping or flashing them. Why is it bad for welding shield eyes in particular to be hard to see and not anything else?

Changeling ≠ preternis or surgery-capable metafriend

2023-02-27 07:04 UTC, Uristthedorf commented
> > Changelings and anyone wearing a mask can hide their flash protection with no way to find out besides stripping or flashing them. Why is it bad for welding shield eyes in particular to be hard to see and not anything else?
> 
> Changeling ≠ preternis or surgery-capable metafriend

I guess changelings are antag and deserve it, but gas masks (or any other eye covering mask) are an easy way to hide sunglasses.

2023-02-27 08:13 UTC, 00ze-cyclone commented
> > I don't understand. Can you explain more in depth why? This simply just seems like a nerf to an item that doesn't get a lot of usage.
> 
> medlizard nerf

Why not just put implants only in robotic if we want to stop that? Only give medbay the organs and robotic are the only ones able to print implants.

2023-02-27 14:46 UTC, RG4ORDR commented
Yeah I aint seeing anything to justify this.

Welding shield eyes are aren't used cause sunglasses,welding masks/gasmask,space helmets, and goggles all provide this benefit. All of the above are easy enough to obtain.

2023-03-05 08:09 UTC, TheGamerdk commented
No need for this nerf. See above comments

2023-03-05 08:09 UTC, closed without merging