Revert "Reverts #15069 properly this time because im a stupid idiot commiting to master"
yogstation13/Yogstation pull request #18149
Opened 2023-03-01 04:50 UTC by jachlompsky

# Document the changes in your pull request

Disablers go from 30 damage -> 25 damage

Someone else made a PR to do this a while ago but it got closed due to feature freeze, so:
The reasoning behind the most recent 25 -> 30 change was "the amount needed to down someone before was way too high."
I saw people mentioning a bug causing a delay before stamcrit stun around that time, which is likely the cause, because 30 to 25 is virtually unnoticeable. Unarmored people still take 4 shots, and there are only 5 armors in the entire game (that I counted) that require more than 5 disabler shots, WITH the 25 damage change:
-Mk IV Sec vests (6 shots)
-Elite Syndicate Hardsuit (6 shots)
-Heretic Robes (6 shots)
-Reflective Jacket (7 Shots, more if beams get reflected)
-ERT Hardsuits (7 shots)

Considering disablers resolve against energy armor, nearly always the lowest armor value, this isn't even that much of a change. Unless you have the equipment above, any armor is going to let you take only one extra hit. By comparison shotgun slugs, fired point blank, crit someone in an elite hardsuit in the same number of shots as a 25 damage disabler. 30 damage disablers take LESS shots than slugs. There is no reason security should be able to do this much effective damage, 20 times before recharging, at long distance. Regardless I'm only going to push for 25 damage right now so that this has a chance of being merged.

Images for reference, against elite syndicate hardsuit, with shotgun slugs (46 damage, point-blank) and 30 damage disabler.
![image](https://user-images.githubusercontent.com/74697056/222043995-e767e64c-0a18-4877-a30f-18eb8a49c2f8.png)
![image](https://user-images.githubusercontent.com/74697056/222046375-56a6712f-1f31-464e-9823-aeca06847c84.png)

# Changelog

:cl:  
tweak: disablers do 25 damage again
/:cl:

2023-03-01 04:52 UTC, ynot01 commented
Not that I agree with any of this, but you'll want to modify the NT-USP aswell

2023-03-01 05:02 UTC, jachlompsky commented
> Not that I agree with any of this, but you'll want to modify the NT-USP aswell

thought the USP was 20 stamina cause thats what the PR for it said, but looks like even in that initial PR the code said 25. Just changed that too.

2023-03-01 06:00 UTC, Mqiib commented
Note that stamina damage and regular damage don't really stack, so the USP does effectively just 20 damage or 2 damage, not 22.

2023-03-01 12:42 UTC, MegaEmpirical commented
You monster

2023-03-04 14:53 UTC, ynot01 commented
Reverts must go through HD

2023-03-04 20:16 UTC, ynot01 requested changes
Balance council says make NT-USP damage 22

2023-03-04 20:33 UTC, jachlompsky commented
> Balance council says make NT-USP damage 22

Changed

2023-03-04 20:44 UTC, ynot01 approved these changes

2023-03-30 08:22 UTC, JamieD1 commented
Just going to say if you are saying "its not even that much of a change" then why are you needing to change it?

2023-03-30 16:23 UTC, jachlompsky commented
> Just going to say if you are saying "its not even that much of a change" then why are you needing to change it?

Because having 25 damage means that it does its job the same against typical crew, but it takes 1-2 more shots against someone armored or using stamina chems, so their armor isnt just useless. Besides, it would never get merged if it was a bigger change, and the previous 25-damage-disabler PR must've been enough change cause it was reverted.

2023-03-30 20:47 UTC, ToasterBiome commented
HDs don't feel this is needed. Balancing sec vs antagonists is a delicate balance and the added 1-2 hits gives a bit too much extra advantage to antagonists in the current state of the game.

This is something that can be looked towards in the future once we fix some blatant problems that are currently occurring with sec vs antagonist balancing.

2023-03-30 20:47 UTC, closed without merging