adds a visual tell to veils
yogstation13/Yogstation pull request #18148
Opened 2023-03-01 04:02 UTC by tattax

# Document the changes in your pull request

veils are basically thralls but better cause they have no tells DESPITE being almost made passively by the veil mind ability, they can be deconned with mindshields but at that point if you don't run immediately to cargo and order a shitton of them and start mindshielding literally everyone you'll not be able to tell them apart. Veils have significantly less value than thralls since they literally take 1/60 of the time to make but are still considerably better.

Aside from all of this, you can still conceal your sigils if you dress tighly, which should indicate players that you are on the dspawn's side.

# Spriting

<details>
<summary> Sprites</summary>

![image](https://user-images.githubusercontent.com/71668564/222041077-c39078fe-8956-478d-b88d-9354c388cb78.png)

![image](https://user-images.githubusercontent.com/71668564/222041092-3ed328be-eaeb-468e-b88a-dad9d5e84bba.png)

![image](https://user-images.githubusercontent.com/71668564/222041113-fb488a5f-b84f-4eed-aff8-6dcad0d0b17c.png)

![image](https://user-images.githubusercontent.com/71668564/222041122-fd195e09-6c3a-4f28-b1ac-e3c1a3dad67c.png)

  
![e2AVbhYkRo](https://user-images.githubusercontent.com/71668564/222041478-450c97fd-6961-4831-9419-f7953f985cc9.gif)

![ME6yUYVf8W](https://user-images.githubusercontent.com/71668564/222041486-89925af3-b45b-4169-bae4-c142cb1d6d32.gif)

</details>

# Changelog
:cl:  
rscadd: veils get a visible tell that can be hidden with clothing
rscdel: veils are no longer capped at max health
/:cl:

2023-03-01 04:03 UTC, ynot01 commented
I'm for the visual tell

Max HP cap however should've stayed at 30, veils are way too effective at steamrolling and should not be combat capable

2023-03-01 13:57 UTC, MajManatee commented
yeah knock their HP back down

2023-03-01 19:37 UTC, tattax reviewed
sure

2023-03-01 19:37 UTC, tattax commented on yogstation/code/game/gamemodes/darkspawn/veil.dm
> +	veil_sigils = mutable_appearance('yogstation/icons/mob/actions/actions_darkspawn.dmi', "veil_sigils", -UNDER_SUIT_LAYER) //show them sigils
```suggestion
	mob_override.maxHealth -= 40
	veil_sigils = mutable_appearance('yogstation/icons/mob/actions/actions_darkspawn.dmi', "veil_sigils", -UNDER_SUIT_LAYER) //show them sigils
```

2023-03-01 19:37 UTC, tattax commented on yogstation/code/game/gamemodes/darkspawn/veil.dm
>  	SEND_SOUND(owner.current, sound ('yogstation/sound/ambience/antag/become_veil.ogg', volume = 50))
```suggestion
	to_chat(owner, span_danger("Your drained will has left you feeble and weak! You will go down with many fewer hits!"))
	SEND_SOUND(owner.current, sound ('yogstation/sound/ambience/antag/become_veil.ogg', volume = 50))
```

2023-03-01 19:37 UTC, tattax commented on yogstation/code/game/gamemodes/darkspawn/veil.dm
> +	mob_override.cut_overlay(veil_sigils)
```suggestion
	mob_override.maxHealth += 40
	mob_override.cut_overlay(veil_sigils)
```

2023-03-02 00:58 UTC, ynot01 requested changes
update changelog

2023-03-02 21:28 UTC, tattax commented
done @ynot01

2023-03-03 02:41 UTC, ynot01 approved these changes

2023-03-05 08:25 UTC, TheGamerdk commented on code/modules/mob/living/carbon/human/examine.dm
> +	if(!glasses || !wear_suit && mind?.has_antag_datum(ANTAG_DATUM_VEIL))
```suggestion
	if((!glasses || !wear_suit) && mind?.has_antag_datum(ANTAG_DATUM_VEIL))
```

2023-03-05 08:26 UTC, TheGamerdk approved these changes

2023-03-05 21:30 UTC, cuackles requested changes
talking with baiomu about it, we came to the agreement that they are good but the size its to big, also the sprite from the front torso does look a bit like a slash, so maybe change it a bit so it looks a bit more runic like the others or make the others look a bit more like wounds , also u deleted a stray pixel on the paper wizard so thats cool

2023-03-13 13:57 UTC, cuackles commented
@tattax u also gotta update the sides so they match with the front

2023-03-15 19:45 UTC, tattax commented
@cuackles

2023-03-15 20:03 UTC, cuackles approved these changes

2023-03-16 08:23 UTC, ThatLing approved these changes

2023-03-16 08:24 UTC, merged