Add 4 quick action hotkeys to game preferences
yogstation13/Yogstation pull request #18174
Opened 2023-03-03 21:28 UTC by Chubbygummibear

# Document the changes in your pull request

adds 4 hotkey options for quickly activating actions to the game preferences. prime a spell, activate an item like airshoes, use a power with a button press.

good luck figuring out which keys you can assign that are easy to reach and aren't already integral to this god forsaken game. Spacebar is the only one i found easy to use

Items and spells
https://user-images.githubusercontent.com/46236974/222831819-db91a50f-3f73-4923-a028-cd9046ca1a04.mp4

simple mobs
https://user-images.githubusercontent.com/46236974/222831836-4435e961-3051-4373-ad67-41261effa7ae.mp4

benos
https://user-images.githubusercontent.com/46236974/222831853-1871a26c-69a7-4c76-9aa6-e7f0e8cef409.mp4

Arm
https://user-images.githubusercontent.com/46236974/222831924-d9fb4ece-8258-4927-ab2a-d292c39f8ad0.mp4

# Wiki Documentation

Don't think any

# Changelog

:cl:  
rscadd: 4 Hotkey options for actions to the carbon tab of keybinds
/:cl:

2023-03-03 21:28 UTC, ToasterBiome commented
your moms a hoe

2023-03-03 21:31 UTC, Mqiib commented
limited to 4, seems fine to me

2023-03-03 21:42 UTC, MajManatee commented
based as hell

2023-03-03 23:13 UTC, Chubbygummibear commented
> based as hell People with a morbillion mouse buttons rejoice

not quite. byong refused to recognize m3, back button and forward button on my mouse. it only seems to be able to interpret left and right "clicks"

2023-03-04 11:08 UTC, Burger1998 commented
buster arm buff

2023-03-05 15:34 UTC, ToasterBiome commented on code/datums/keybinding/mob_actions.dm
> +	return user?.mob?.actions?.len>=action_num && ..()
i hate this

2023-03-05 15:34 UTC, ToasterBiome requested changes

2023-03-05 15:34 UTC, ToasterBiome commented on code/datums/keybinding/mob_actions.dm
> +	// hotkey_keys = list("Shift!")
remove

2023-03-05 19:52 UTC, Chubbygummibear commented on code/datums/keybinding/mob_actions.dm
> +	// hotkey_keys = list("Shift!")
ok

2023-03-05 19:53 UTC, Chubbygummibear commented on code/datums/keybinding/mob_actions.dm
> +	return user?.mob?.actions?.len>=action_num && ..()
i'm open to suggestions lmao

2023-03-06 14:16 UTC, MajManatee commented
> > based as hell People with a morbillion mouse buttons rejoice
> 
> not quite. byong refused to recognize m3, back button and forward button on my mouse. it only seems to be able to interpret left and right "clicks"

Most, if not all, mouse software's can rebind keys to anything. My mouse buttons are bound to random things like "Unikey 263" or something. 

not that im complaining, its gonna be great.

2023-03-10 18:47 UTC, ToasterBiome approved these changes

2023-03-10 21:55 UTC, merged