makes the sec esword less boring and overpowered
yogstation13/Yogstation pull request #18178
Opened 2023-03-04 20:08 UTC by TheRyeGuyWhoWillNowDie

this powercreep stick is better than fireaxes (which there are only two of) the captain's sabre (which there is only one of) and combat knives (which have to be ordered from cargo)
also they can be mass printed for free and fit in backpacks

now they use power cells when attacking (high-cap by default, ten hits) when out of battery they lose their sharpness and a lot of damage
damage also reduced to 18 from 23 because mass printing the best melee weapon is fucking idiotic

# Changelog

:cl:  
tweak: sec esword now operates off of a battery
tweak: sec esword's damage reduced to 18
/:cl:

2023-03-04 20:09 UTC, ToasterBiome commented
lol

2023-03-04 20:11 UTC, cowbot92 commented
sword is kinda strong

2023-03-05 11:52 UTC, UltraBigRat commented
Me when a coder self merges giving sec roundstart+printable compact onehanded fireaxes (Who could have known itd be overpowered!)

2023-03-05 15:37 UTC, MajManatee commented
making it worse than a combat knife

2023-03-05 15:59 UTC, TheRyeGuyWhoWillNowDie commented
> making it worse than a combat knife

hey shitass these are in the armory roundstart, now go ahead and slap your 'SIGNIFICANT OPPOSITION' and 'CONTROVERSIAL' tags on this pr

2023-03-05 22:32 UTC, Mqiib commented
We've (balance council) have had a long talk about this and some of us still don't think it NEEDS nerfed but are willing to compromise on just reducing its force to 20. Giving it charges makes it nigh worthless, so get rid of that.

2023-03-06 17:40 UTC, MajManatee requested changes
Remove the charge mechanic as per request

2023-03-06 18:42 UTC, Cartlord commented
I think the balance council are radically out of touch with the game if they think items needing recharged makes them "nigh-useless", on the grounds that most Sec gear needs recharged - making these require a charge just brings them to be on a similar tier as other Security gear, such as **the stun baton** and **the disabler**.

2023-03-06 20:26 UTC, TheRyeGuyWhoWillNowDie commented
> Giving it charges makes it nigh worthless, so get rid of that.

True, I can't see any possible way that anything with limited charge could be useful. Lowering the damage by one so it's still a better, infinitely printable combat knife that you can get without ever having to be near cargo sounds good.

2023-03-06 22:20 UTC, Mqiib commented
> I think the balance council are radically out of touch with the game if they think items needing recharged makes them "nigh-useless", on the grounds that most Sec gear needs recharged - making these require a charge just brings them to be on a similar tier as other Security gear, such as **the stun baton** and **the disabler**.

Stun baton: deals (effectively) **70** damage in most circumstances, blocked by energy armor, one of the rarest armor types, requires melee range (you're in danger)
Disablers: deal (effectively) **25** damage in most circumstances, also blocked by energy armor, has range and can fire through windows, fires twice as fast as you can swing a sword (0.4s click cooldown vs 0.8s)
Vibration blade: deals 20 real damage, blocked by melee armor, the most common armor type in the game, requires you to be in melee range
Laser gun: deals 20 burn damage (many species take increased burn damage), easily causes wounds on unarmored opponents, fires twice as fast as you can swing a sword, has range, shoots through windows

Stun baton power cells can be upgraded, disablers have what 20 shots? and laser guns have like 12. Yes, all of these are rechargeable but they're all also _better_ than the sword. Giving the sword charges means you are better off taking a laser gun or printing literally any other ranged weapon that can deal direct damage because they all have comparable numbers but with numerous other advantages (like being ranged)

2023-03-06 22:52 UTC, Cartlord commented
-Laser guns can be disabled by E.M.P. and I don't think they're printable (I may be wrong)
-Stims exist to hard-counter stunbatons and disablers, and neither of those can wound
-Vibration blade literally deals more damage than a wielded fire axe, is printable, can be carried in a backpack (meaning nothing stops you from carrying a spare, or even four if you're willing to forgo other weaponry), and delimbs motherfuckers

2023-03-06 23:17 UTC, Mqiib commented
> -Laser guns can be disabled by E.M.P. and I don't think they're printable (I may be wrong) -Stims exist to hard-counter stunbatons and disablers, and neither of those can wound -Vibration blade literally deals more damage than a wielded fire axe, is printable, can be carried in a backpack (meaning nothing stops you from carrying a spare, or even four if you're willing to forgo other weaponry), and delimbs motherfuckers

Giving it charges makes it drain from EMPs, stims are not that common save for changlings and the occasional traitor that buys them, and it does not do more damage than a fire axe (24). They're normal sized, so carrying around a bunch of vibro blades is not as effective as, say, carrying around a bunch of lasers which are just better in this case. yeah sure it's good at delimbing but by the time you're able to cut an arm or a leg off the person is usually in crit anyways, and once again lasers are just as good at delimbing with their burn wounds.

2023-03-06 23:22 UTC, Cartlord commented
Okay, so this is still an item that deals one fewer point of damage than a wielded fire axe (0+23=23 versus  5+19=24) and can be printed. I'm willing to bet that one point of damage makes extremely little difference for hits-to-kill in this case, and therefore this is still a fire-axe-tier weapon that you can distribute to the entire Security force if Sci and Mining are both mildly competent.
There are only two axes on-station for a REASON, and I fail to see why these should be treated differently.

2023-03-07 00:52 UTC, Mqiib commented
> Okay, so this is still an item that deals one fewer point of damage than a wielded fire axe (0+23=23 versus 5+19=24) and can be printed. I'm willing to bet that one point of damage makes extremely little difference for hits-to-kill in this case, and therefore this is still a fire-axe-tier weapon that you can distribute to the entire Security force if Sci and Mining are both mildly competent. There are only two axes on-station for a REASON, and I fail to see why these should be treated differently.

The force is being reduced to 20.

2023-03-07 07:05 UTC, Cartlord commented
So it's going from a weapon that fits in backpacks, wounds & delimbs, can be mass-printed, seemingly has no counter, and crits in five hits to a weapon that fits in backpacks, wounds & delimbs, can be mass-printed, seemingly has no counter, and crits in six hits. I don't know enough about the combat meta to say how important that change is, since I do know one hit CAN mean a lot.

2023-03-07 14:13 UTC, MajManatee commented
Nerf it enough and it will be unused noob bait

2023-03-07 15:16 UTC, DeadlyBag commented
I do think 23 damage is quite high with the additional 25 AP.
Currently the spot i see for the vibroblade is a lethal melee option that is EMP proof.
Making the vibroblade run off batteries would just make it an overall worse option than the baton.
Tweaking damage & AP would result in it still fitting into the niche as an EMP proof melee option but would make it less of a gamer blade.

2023-03-07 15:28 UTC, MajManatee commented
Could also just... not have them in the armory shift start, and move them further back in the tech tree.

2023-03-07 20:51 UTC, cowbot92 commented
let me tape two of them together for DEvibrosword

2023-03-08 20:00 UTC, TheRyeGuyWhoWillNowDie commented
Not 70 damage, so it's balanced

2023-03-08 20:00 UTC, closed without merging

2023-03-09 05:39 UTC, stwordcitizen commented
> So it's going from a weapon that fits in backpacks, wounds & delimbs, can be mass-printed, seemingly has no counter, and crits in five hits to a weapon that fits in backpacks, wounds & delimbs, can be mass-printed, seemingly has no counter, and crits in six hits. I don't know enough about the combat meta to say how important that change is, since I do know one hit CAN mean a lot.

![image](https://user-images.githubusercontent.com/84217619/223930278-1184f742-c181-4103-b591-be6ded2c8208.png)