manatee is fucking cringe as shit: mimes can now get the mech that was designed for them
yogstation13/Yogstation pull request #18191
Opened 2023-03-06 02:49 UTC by TheRyeGuyWhoWillNowDie

Pretty cool item for a role that unfortunately has next to no exclusive items, which is pretty sad. The things the mech comes equipped with aren't terribly overpowered, so this is probably balanced for 20tc. 

# Changelog

:cl:  
rscadd: traitor mimes can buy the mime mech for 20tc
/:cl:

2023-03-06 02:50 UTC, HisaHoshimo commented
Gus redemption arc?

2023-03-06 02:57 UTC, Moltijoe commented
i had no clue the reticence was even in the codebase, why wasn't it available before?

2023-03-06 03:00 UTC, TheRyeGuyWhoWillNowDie commented
> why wasn't it available before?

idk dawg i aint a coder

2023-03-06 03:42 UTC, Moltijoe commented
> idk dawg i aint a coder

says the guy that just did a coding

2023-03-06 06:38 UTC, K4rlox commented
it is fair since clown gets a shit ton of cool gear
plus mime mech was unused

also what weapons does the mime mech have?

2023-03-07 04:31 UTC, Mqiib commented
I think there's a loaded subtype of mechs that start with equipment. Might want to see if that exists and use it or, if it doesn't, make it. That is, assuming it's supposed to come with the equipment the wiki says it does.

2023-03-07 05:25 UTC, K4rlox commented
i have several issues from testing the mech
1. power issues, too low power, silenced gun and RCD both use power, along with moving, runs out too fat
2. the "silenced" pistol makes a syringe gun noise therefore its not even silent
3. 100 integrity low armor, we can say this is a glass cannon but come on its 20 tc it needs more.
4. punches and RCD are not silent either


if we wanna keep this as a glass cannon please at least make everything actually silenced instead of saying "silenced" and being able to be heard thru walls

2023-03-07 05:27 UTC, K4rlox commented
> I think there's a loaded subtype of mechs that start with equipment. Might want to see if that exists and use it or, if it doesn't, make it. That is, assuming it's supposed to come with the equipment the wiki says it does.

it DOES have a loaded subtype which is not the one that spawns at CC

2023-03-07 14:16 UTC, MajManatee requested changes
make the above mentioned equipment actually silent and sure

2023-03-07 22:03 UTC, K4rlox commented
> make the above mentioned equipment actually silent and sure

you forgot to use the loaded subtype, this spawns a mech with no equipment.

2023-03-11 01:19 UTC, Moltijoe approved these changes

2023-03-12 19:13 UTC, K4rlox commented
from testing: due to how lights work

the mech has a natural green glow, which makes it easily be able to seen, whould be appriciated if you can try removing that glow

2023-03-12 22:39 UTC, ReddicusDragon commented on code/modules/uplink/uplink_items.dm
> +	item = /obj/mecha/combat/reticence/loaded
does it actually have the weapons?

2023-03-12 22:42 UTC, ReddicusDragon approved these changes

2023-03-12 22:43 UTC, ReddicusDragon approved these changes

2023-03-12 22:49 UTC, ReddicusDragon requested changes
I am fucking stupid this still needs to be silent, the punch needs to be silent, the move needs to be silent, and the RCD needs to be silent. According to manatee.

2023-03-13 06:25 UTC, K4rlox commented
> I am fucking stupid this still needs to be silent, the punch needs to be silent, the move needs to be silent, and the RCD needs to be silent. According to manatee.

and the green light needs to be removed for actual invisiblity.

2023-03-16 18:53 UTC, TheRyeGuyWhoWillNowDie commented
eh

2023-03-16 18:53 UTC, closed without merging

2023-03-17 00:49 UTC, K4rlox commented
> eh

why