Wym/ Wdym added to filter
yogstation13/Yogstation pull request #18214
Opened 2023-03-08 18:24 UTC by MajManatee

# Document the changes in your pull request
I said it the other day and people got mad.
Never again.

# Changelog

:cl:  
spellcheck: Wym / Wdym added to filter.
/:cl:

2023-03-08 18:25 UTC, ToasterBiome commented
wym

2023-03-08 18:31 UTC, solwashere commented
it was me I got mad

2023-03-08 19:07 UTC, TheRyeGuyWhoWillNowDie commented
Zero thumbs-up emojis. Why is this even being considered?

2023-03-08 19:55 UTC, Moltijoe commented
Gonna conflict with the pls/plz one

2023-03-08 20:03 UTC, MajManatee commented
yeah i figured, but for time reasons ill fix it after

2023-03-15 02:22 UTC, ToasterBiome commented
Cornflakes

2023-03-15 19:31 UTC, ToasterBiome requested changes, later dismissed
spellcheck is the incorrect changelog to use here

2023-03-26 01:58 UTC, Moltijoe requested changes
probably isn't needed for wdym because i don't think any word uses those letters in that order

2023-03-26 01:58 UTC, Moltijoe commented on config/minor_filter.txt
> +tf=the fuck
```suggestion
\btf\b=the fuck
```

2023-03-26 01:58 UTC, Moltijoe commented on config/minor_filter.txt
> +wym=what do you mean
```suggestion
\bwym\b=what do you mean
```

2023-03-29 16:39 UTC, Moltijoe approved these changes

2023-04-20 23:11 UTC, ToasterBiome approved these changes

2023-04-20 23:11 UTC, merged