dumb lizards (what's new?)
yogstation13/Yogstation pull request #18233
Opened 2023-03-09 19:30 UTC by Moltijoe

![image](https://user-images.githubusercontent.com/108117184/224133906-c32a4bb8-0a3b-4542-b012-ab79e4cfadd8.png)

:cl:  
tweak: Regular ashwalkers can't speak or understand common
/:cl:

2023-03-09 19:32 UTC, solwashere commented
good pr

2023-03-09 19:59 UTC, Moja10 commented
Ashwalkers used to not understand common in the past, then got common speech back, seeing both sides of what this looks like, I'd say its better for RP for all Ashwalkers to speak common. Miner smoothbrains will just KOS Ashwalkers on sight more if they have nothing at all to communicate to them, besides one singular representative, who might not be there or might be dead. 

If you want ashwalkers to interact with miners/lavaland residents, give them common, if you want them to be more on the hostile native side, don't give them common. IMO, they work better with common.

2023-03-09 20:04 UTC, Moltijoe commented
> besides one singular representative, who might not be there or might be dead.

if they're dead, the next egg to spawn will be a shaman egg

2023-03-09 20:16 UTC, wonderinghost commented
Got it so find a exploit that turns all eggs into shaman eggs. 

Also I think this is a bad idea. Ashwalkers normally aren't assholes in most experiences I've been in or watch... Even on jungleland it was the same with the phytosians. It's just miner's being dicks that cause the problems (ie miner's use the rcd that ashwalkers have and lock them in their temple)

Also ashwalkers are kinda the few ghost spawns that don't really suck. Strange how we have 5 different doctors on lavaland but 1 actually has a pickaxe

2023-03-09 20:41 UTC, Moltijoe commented
> Got it so find a exploit that turns all eggs into shaman eggs.

shouldn't be possible, but even then, you'd just have a bunch of squishy ashwalkers

2023-03-09 20:55 UTC, solwashere commented
I'd argue that having the majority of ashies be able to only speak draconic while only having a sort of leader figure to function as a translator offers for much more compelling rp

2023-03-09 21:53 UTC, MajManatee commented
none of them should speak common.

2023-03-10 01:43 UTC, Skrem7 commented
current state of ashwalkers means only real actual feasible goal is kill things and throw them into the tendril, would maybe be cool if ashwalkers could offer something to miners other than being in the way of rcd + gamer toolbox, which would maybe incentivize trade

it makes zero sense for ashwalkers to have common and it goes entirely against their design as a player-controlled, hostile aspect of lavaland

sure you can do fun stuff and it can be cool but like, damn dude, ashwalkers just need to man up and go remind miners why they should fear the spear

2023-03-10 02:29 UTC, solwashere commented
Overall I'd prefer if ashwalkers were considered neutral until proven otherwise because that's kinda how they act in game 
I think it should be more of a tossup over whether or not ashies are gonna try to spear you to death or if they'll trade with you, both of which are instances that I've had happen
Inherently there will be some distrust between miners and ashwalkers and I think the mystery of it is great, and having that communication barrier will help it even more

2023-03-10 14:15 UTC, MajManatee commented
Ashwalkers have absolutely nothing a miner wants that they are willing to trade for. Any man worth his salt can walk into a village and single handedly massacre them all if he wants the toolbox, ai upgrade, or the RCD.

I get it you weird people want to hold hands and talk all cutesie to each other or whatever y'all consider "rp", but you weren't given a big ass room full of weapons coded JUST FOR YOU to not use them. You are part of the whole "Planet wants to kill you" aspect of lava land. if you want to go start a family you should probably be playing splurt or some shit.

in short, man the hell up and kill people on the tribal warrior job. Nobody should speak common.

2023-03-10 20:16 UTC, solwashere commented
>they have nothing that a miner wants that they are willing to trade for
I've traded like 3 survival pens and a brute kit for plasma magmite and  some sinew and goliath plates, which saved me a LOT of time grinding for pathfinder drip
Just because they have not much roundstart in terms of trading potential doesn't mean that they aren't capable of it, there is always the possibility that they have something that you want/need

2023-03-10 23:24 UTC, wonderinghost commented
> Ashwalkers have absolutely nothing a miner wants that they are willing to trade for. Any man worth his salt can walk into a village and single handedly massacre them all if he wants the toolbox, ai upgrade, or the RCD.
> 
> I get it you weird people want to hold hands and talk all cutesie to each other or whatever y'all consider "rp", but you weren't given a big ass room full of weapons coded JUST FOR YOU to not use them. You are part of the whole "Planet wants to kill you" aspect of lava land. if you want to go start a family you should probably be playing splurt or some shit.
> 
> in short, man the hell up and kill people on the tribal warrior job. Nobody should speak common.

Well wtf would the ashwalkers want. Any tool a miner has (kpa or plasma cutter) doesn't work unless they got a hand guard mod on. Maybe medical tools and surgery because ghetto surgery has been broken (even on the operating table with a loaded console it won't work)

2023-03-11 20:46 UTC, Moja10 commented
you say that ashwalkers are meant to stab miners and be hostile but they can still do that while speaking common. In fact, it could lead to better communication with an ashwalker saying "I will kill you" to a miner

2023-03-11 23:27 UTC, Moltijoe commented
> you say that ashwalkers are meant to stab miners and be hostile but they can still do that while speaking common. In fact, it could lead to better communication with an ashwalker saying "I will kill you" to a miner

there's no better way to say "i will kill you" than actively trying to stab them, and that transcends language barriers

2023-03-12 00:51 UTC, wonderinghost commented
Well what is a missclick

2023-03-12 00:51 UTC, wonderinghost commented
Then what

2023-03-13 00:06 UTC, Marmio64 commented
i think they shouldn't even speak normal draconic either, giving more purpose to curators, pais, and the book of babel item would be cooler since a pretty good chunk of lizards play miner anyways and this change would mean nothing to them. Besides, its a little weird that station 'civilized' lizards would speak the same language as an isolated entirely different subspecies of savage ones.

2023-04-03 17:44 UTC, MajManatee approved these changes
fuck the lizards...



wait

2023-04-03 17:46 UTC, MajManatee commented on code/modules/language/language_holder.dm
> +	selected_language = /datum/language/draconic
wait wtf is this line? ?

2023-04-03 17:47 UTC, MajManatee requested changes
that line doesnt do nothin i can see

2023-04-03 17:49 UTC, Moltijoe commented on code/modules/language/language_holder.dm
> +	selected_language = /datum/language/draconic
i suppose it's redundant, but not really a problem for it to be there

2023-04-03 17:49 UTC, Moltijoe commented on code/modules/language/language_holder.dm
> +	selected_language = /datum/language/draconic
```suggestion
```

2023-04-04 14:08 UTC, MajManatee commented on code/modules/language/language_holder.dm
>  	selected_language = /datum/language/draconic
I don't understand, selected language is used NOWHERE else.
Ash walker "Shaman"s are just normal lizards. Just give them that.

2023-04-04 19:27 UTC, Moltijoe commented on code/modules/language/language_holder.dm
>  	selected_language = /datum/language/draconic
this makes them spawn with draconic selected, so they aren't forced to swap
that's literally how it works for current ashwalkers my dude

2023-04-07 16:07 UTC, MajManatee approved these changes
whatever. i still think its dumb that one can speak common.

2023-04-07 16:08 UTC, merged

2023-04-07 20:10 UTC, KingSuperBOB commented
I wouldve preferred something along the lines of how mice work with them understanding common but being confined to speaking draconic but I guess this is fine