Gives posibrains a time requirement just like the cyborg job
yogstation13/Yogstation pull request #18241
Opened 2023-03-10 17:19 UTC by Moltijoe

![image](https://user-images.githubusercontent.com/108117184/224380978-3d303128-089f-40b5-b479-753b437aae25.png)

:cl:  
rscadd: Time requirement to posibrains
/:cl:

2023-03-10 18:38 UTC, MajManatee commented
Possibly out of scope, but would it be good to have a seperate timer for posi brains specifically, and the ability to ban from the job?

2023-03-10 19:02 UTC, ThatLing requested changes

2023-03-10 19:02 UTC, ThatLing commented on code/modules/mob/living/brain/posibrain.dm
> +	if(user.client.get_exp_living(TRUE) < SSjob.GetJob("Cyborg").exp_requirements && !(CONFIG_GET(flag/use_exp_restrictions_admin_bypass) && check_rights_for(user.client, R_ADMIN)))
Use ``/datum/job/proc/required_playtime_remaining``

2023-03-10 19:02 UTC, ThatLing commented on code/modules/mob/living/brain/posibrain.dm
> +		to_chat(user, span_warning("Positron brains are beyond your knowledge to control."))
```suggestion
		to_chat(user, span_warning("Positronic brains are beyond your knowledge to control."))
```

2023-03-10 19:02 UTC, ThatLing commented on code/modules/mob/living/brain/posibrain.dm
> +		to_chat(user, span_warning("In order to play as a positron brain, you require [SSjob.GetJob("Cyborg").exp_requirements - user.client.get_exp_living(TRUE)] more minutes of experience on-board the st
Use returned value from ``/datum/job/proc/required_playtime_remaining``

2023-03-10 19:36 UTC, ThatLing requested changes

2023-03-10 19:36 UTC, ThatLing commented on code/modules/mob/living/brain/posibrain.dm
> +	if(SSjob.GetJob("Cyborg").required_playtime_remaining(user.client) && !(CONFIG_GET(flag/use_exp_restrictions_admin_bypass) && check_rights_for(user.client, R_ADMIN)))
The additional checks are already performed in ``required_playtime_remaining``

2023-03-10 19:36 UTC, ThatLing commented on code/modules/mob/living/brain/posibrain.dm
> +		to_chat(user, span_warning("In order to play as a positron brain, you require [SSjob.GetJob("Cyborg").required_playtime_remaining(user.client)] more minutes of experience on-board the station."))
Cache the return value

2023-03-10 19:39 UTC, ThatLing approved these changes

2023-03-12 19:49 UTC, ThatLing approved these changes

2023-03-12 21:50 UTC, ThatLing approved these changes

2023-03-13 07:07 UTC, merged