removes sus
yogstation13/Yogstation pull request #18256
Opened 2023-03-13 02:56 UTC by Skrem7

# Document the changes in your pull request

I forgor to remove the placeholder description (there were many things I had to keep track of)

# Changelog

:cl:  
spellcheck: CMO plasmaman envirosuit is now significantly less sus
/:cl:

2023-03-13 02:59 UTC, tattax reviewed
hello

2023-03-13 02:59 UTC, tattax commented on code/modules/clothing/under/jobs/Plasmaman/medsci.dm
> +	desc = "A white-blue envirosuit to denote a plasmaman of the high rank of \"Chief Medical OFficer\". Quite comfortable."
```suggestion
	desc = "A white-blue envirosuit to denote a plasmaman of the high rank of \"Chief Medical Officer\". Quite comfortable."
```

2023-03-13 03:21 UTC, TheRyeGuyWhoWillNowDie requested changes
close this pr

2023-03-13 04:40 UTC, MajManatee commented
gus is right

2023-03-14 10:12 UTC, ynot01 approved these changes
OFficer

2023-03-14 13:49 UTC, merged