Makes mechs not broken #1 - MMIs can go mine again
yogstation13/Yogstation pull request #18340
Opened 2023-03-21 22:04 UTC by Majkl-J

# Document the changes in your pull request

The mmi pacifist trait is now removed when put in non-combat mechs. Why ynot didnt think of this when solving a Admin issue with code is beyond me.
(Yes I know they can be given combat parts but that actually costs tc and its viability is questionable)

# Changelog

:cl:  
tweak: MMIs in mechs can now mine again
/:cl:

2023-03-21 22:10 UTC, MajManatee commented
Hmm time to mass produce an army of validhunting brains. Great idea.

2023-03-21 22:29 UTC, Majkl-J commented
> Hmm time to mass produce an army of validhunting brains. Great idea.

I wanna see you validhunt in noncombat mechs

2023-03-21 22:51 UTC, ynot01 commented
awful

2023-03-22 02:42 UTC, namjay1170 commented
> > Hmm time to mass produce an army of validhunting brains. Great idea.
> 
> I wanna see you validhunt in noncombat mechs

rcd an area into low atmos then shoot them with KA. Robo having an army of stun baton wielding ripleys would be devastating the bay only costs 3 tc that lets them have like 7 mechs up with weapons I'd say thats well worth the TC, if you can actually manage to get the ghosts to go posi.

2023-03-22 06:17 UTC, Majkl-J commented
> > > Hmm time to mass produce an army of validhunting brains. Great idea.
> > 
> > 
> > I wanna see you validhunt in noncombat mechs
> 
> rcd an area into low atmos then shoot them with KA. Robo having an army of stun baton wielding ripleys would be devastating the bay only costs 3 tc that lets them have like 7 mechs up with weapons I'd say thats well worth the TC, if you can actually manage to get the ghosts to go posi.
> 
> Though posi laws should still stop them from that.

I don't think that would be exactly practical, besides, if it is as good as you say, why has nobody done it before? Oh yes, the time to kill and movement speed on them is abysmal

2023-03-22 19:14 UTC, 00ze-cyclone commented
So for validhunting mechs, basic ripley with RCD, KA or plasmacutter would be a fucking menace because not only are those mechs dirt cheap, they are fast and get even faster in low pressure, slap a diamond drill and make a squad of that and you have now a squad able to inflict an incredible amount of pain.

For poismech of tator robo it’s just scattershot CLARKE, hello goodbye eat that 96 brute shotgun but there’s 5 of them and they can shoot behind themselves.

2023-03-23 07:03 UTC, Majkl-J commented
> So for validhunting mechs, basic ripley with RCD, KA or plasmacutter would be a fucking menace because not only are those mechs dirt cheap, they are fast and get even faster in low pressure, slap a diamond drill and make a squad of that and you have now a squad able to inflict an incredible amount of pain.
> 
> For poismech of tator robo it’s just scattershot CLARKE, hello goodbye eat that 96 brute shotgun but there’s 5 of them and they can shoot behind themselves.

Before they rcd a single room you can very easily move to the next one, there are firedoors every 5-10 tiles and there is only so many rooms they can space before it would make the crew and admins hunt the mechs too.
As for the poismech, if it was so viable, why did nobody ever use it? Well, it is because there is literally a thing that tells the MMI that they have to help the station, so the traitor cannot do that.

My point is, out of the 10 MMIs you will put into the mechs with the purpose of mining, like 1 would actually go validhunt. The noncombat mechs' primary purpose simply isn't validhunting, nor are they good at it.

2023-03-23 11:39 UTC, namjay1170 commented
> > So for validhunting mechs, basic ripley with RCD, KA or plasmacutter would be a fucking menace because not only are those mechs dirt cheap, they are fast and get even faster in low pressure, slap a diamond drill and make a squad of that and you have now a squad able to inflict an incredible amount of pain.
> > For poismech of tator robo it’s just scattershot CLARKE, hello goodbye eat that 96 brute shotgun but there’s 5 of them and they can shoot behind themselves.
> 
> Before they rcd a single room you can very easily move to the next one, there are firedoors every 5-10 tiles and there is only so many rooms they can space before it would make the crew and admins hunt the mechs too. As for the poismech, if it was so viable, why did nobody ever use it? Well, it is because there is literally a thing that tells the MMI that they have to help the station, so the traitor cannot do that.
> 
> ```
> 		to_chat(brainmob, "<b>As a synthetic intelligence, you answer to all crewmembers and the AI.\n\
> 		Remember, the purpose of your existence is to serve the crew and the station. Above all else, do no harm.</b>")
> ```
> 
> My point is, out of the 10 MMIs you will put into the mechs with the purpose of mining, like 1 would actually go validhunt. The noncombat mechs' primary purpose simply isn't validhunting, nor are they good at it.

Source: I made it up

clicking on an mmi/posi shows its laws it has more than that flavor text

besides being a posi/mmi in a mech sucks you cant even examine people

2023-03-23 15:09 UTC, Majkl-J commented
> > > So for validhunting mechs, basic ripley with RCD, KA or plasmacutter would be a fucking menace because not only are those mechs dirt cheap, they are fast and get even faster in low pressure, slap a diamond drill and make a squad of that and you have now a squad able to inflict an incredible amount of pain.
> > > For poismech of tator robo it’s just scattershot CLARKE, hello goodbye eat that 96 brute shotgun but there’s 5 of them and they can shoot behind themselves.
> > 
> > 
> > Before they rcd a single room you can very easily move to the next one, there are firedoors every 5-10 tiles and there is only so many rooms they can space before it would make the crew and admins hunt the mechs too. As for the poismech, if it was so viable, why did nobody ever use it? Well, it is because there is literally a thing that tells the MMI that they have to help the station, so the traitor cannot do that.
> > ```
> > 		to_chat(brainmob, "<b>As a synthetic intelligence, you answer to all crewmembers and the AI.\n\
> > 		Remember, the purpose of your existence is to serve the crew and the station. Above all else, do no harm.</b>")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My point is, out of the 10 MMIs you will put into the mechs with the purpose of mining, like 1 would actually go validhunt. The noncombat mechs' primary purpose simply isn't validhunting, nor are they good at it.
> 
> Source: I made it up
> 
> clicking on an mmi/posi shows its laws it has more than that flavor text
> 
> besides being a posi/mmi in a mech sucks you cant even examine people

The mech laws override the mmi ones. The mech laws prevent you from working against the station. Thus it becomes an admin issue.

2023-03-26 01:52 UTC, Moltijoe approved these changes

2023-03-30 04:10 UTC, ynot01 requested changes
Whitelist mining equipment on pacifism checks instead of checking for a combat design and removing pacifism

2023-03-30 10:33 UTC, Majkl-J commented
> Whitelist mining equipment on pacifism checks instead of checking for a combat design and removing pacifism

This is the most dumb way ever but oh well

2023-03-30 12:44 UTC, ynot01 approved these changes

2023-04-02 05:26 UTC, Moltijoe approved these changes

2023-04-02 05:26 UTC, merged