Give CE access to the bridge fireaxe cabinet
yogstation13/Yogstation pull request #18359
Opened 2023-03-23 17:13 UTC by hedgehog1029

# Changes

Prior art: https://github.com/yogstation13/Yogstation/pull/11984

Changes the fireaxe cabinet in the Bridge to give the Chief Engineer access. They already have access to the Atmospherics one, and the bridge itself, so seems a bit weird that they don't have access to this.

### wait but why

Obviously in most cases the CE can just ask the captain to unlock the cabinet for them.
But say for the sake of argument, there's nobody with captain access, and:

- Atmos is currently filled with space vines/fire/giant spiders/wizards, and therefore that fireaxe is not reachable
- The other fireaxe is in space in the hands of some poor atmos tech
- etc.

I don't think any other heads need access - HoS and RD likely have better options, CMO should probably be healing rather than hurting, HoP could give themselves all access anyway and probably will take over if there's no captain. The CE has legitimate reasons to hold a fireaxe (i.e. firefighting) wheras the other heads don't.

I'm told this will need a balance council review.

# Wiki Documentation

The access isn't currently documented on the wiki as far as I can see, but maybe it should be?

# Changelog

:cl:  
tweak: Gave the CE access to the bridge fireaxe cabinet
/:cl:

2023-03-23 18:04 UTC, Aquizit commented
Ah I was going to make it all heads, not just CE. But I mean that can be decided before merging.

I was the one who suggested it needed Balance Council review, by the by, since the original PR of locking the bridge fire axe to Captain only seemed intentional and it was written by a council member for whatever weight that's worth (I'm not sure if it's worth any). #11984

2023-03-25 04:06 UTC, Moltijoe requested changes

2023-03-25 04:06 UTC, Moltijoe commented on yogstation/code/game/objects/structures/fireaxe.dm
> +	req_access = list(ACCESS_CAPTAIN, ACCESS_CE)
```suggestion
	req_one_access = list(ACCESS_CAPTAIN, ACCESS_CE)
```

2023-03-26 01:51 UTC, Moltijoe approved these changes

2023-03-26 05:55 UTC, merged