Stops the Lizard Monopoly of getting rid of pie from their face, try using your HANDS.
yogstation13/Yogstation pull request #18357
Opened 2023-03-23 02:48 UTC by Marmio64

We've done it, a logical way to remove pie from your face that can't be refuted!

If you're a lizard, you'll lick pie off your face. Otherwise you'll use your hands (you cant do it if you don't have any) to wipe it off. Since you're not eating the cream you won't get the 1 unit of banana reagent like lizards do.

Would replace #18354

# Changelog

:cl:  
tweak: You can wipe pie off your face with help intent, just like how a lizard can lick it off.
/:cl:

2023-03-23 02:51 UTC, Mqiib commented
Makes sense

2023-03-23 03:03 UTC, Cartlord commented
>not wiping the pie into your mouth to eat the cream

2023-03-23 11:42 UTC, namjay1170 commented
just steal a lizards tongue and get it implanted you non lizard shmuck

2023-03-23 11:49 UTC, Marmio64 commented
> just steal a lizards tongue and get it implanted you non lizard shmuck

I would never willingly make myself part lizard!

2023-03-23 12:01 UTC, namjay1170 commented
> > just steal a lizards tongue and get it implanted you non lizard shmuck
> 
> I would never willingly make myself part lizard!

except making a lizard feature a part of everyone, you're all lizard now. Fool.

2023-03-23 18:02 UTC, MajManatee commented
if only we had sinks or something

2023-03-23 20:45 UTC, Marmio64 commented
> > > just steal a lizards tongue and get it implanted you non lizard shmuck
> > 
> > 
> > I would never willingly make myself part lizard!
> 
> except making a lizard feature a part of everyone, you're all lizard now. Fool.

not true, the lizard feature is still lizard only, other people just have a separate one

2023-03-25 01:53 UTC, tattax commented on code/modules/mob/living/carbon/human/human_defense.dm
> +								"<span class='notice'>You wipe the pie off your face with your hand.")
```suggestion
			if(istype(getorganslot(ORGAN_SLOT_TONGUE), /obj/item/organ/tongue/lizard))
				visible_message(span_notice("[src] eats the pie off [p_their()] face with [p_their()] forked tongue."), 
								span_notice("You eat the pie off your face with your forked tongue."))
				reagents.add_reagent(/datum/reagent/consumable/banana, 1)

			else if(M.get_num_arms()) //make sure you have arms with which to wipe
				visible_message(span_notice("[src] wipes the pie off [p_their()] face with [p_their()] hand."), 
								span_notice(You wipe the pie off your face with your hand."))
```

if your arms are equal to zero you don't have arms

2023-03-25 14:08 UTC, Marmio64 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +								"<span class='notice'>You wipe the pie off your face with your hand.")
true, i've also realized a while ago that it's actually a redundant check anyways since you cant self check if you dont have any arms, but we will keep a fixed sanity check i suppose

2023-03-26 01:49 UTC, Moltijoe requested changes

2023-03-26 01:49 UTC, Moltijoe commented on code/modules/mob/living/carbon/human/human_defense.dm
> +								span_notice(You wipe the pie off your face with your hand."))
```suggestion
								span_notice("You wipe the pie off your face with your hand."))
```

2023-03-27 00:58 UTC, Moltijoe requested changes

2023-03-27 00:58 UTC, Moltijoe commented on code/modules/mob/living/carbon/human/human_defense.dm
>  			wash_cream()
this would let people without arms wash cream off their face without any chat message

2023-03-27 21:58 UTC, Marmio64 commented on code/modules/mob/living/carbon/human/human_defense.dm
>  			wash_cream()
you cant click yourself without any arms in the first place, i mentioned in the other comment its ultimately a redundant check that i just didnt remove.

2023-03-27 22:33 UTC, Moltijoe commented on code/modules/mob/living/carbon/human/human_defense.dm
>  			wash_cream()
fair enough, didn't read the resolved conversation

2023-03-27 22:33 UTC, Moltijoe approved these changes
should be fine

2023-04-01 01:09 UTC, Moltijoe approved these changes

2023-04-01 01:10 UTC, merged

2023-04-01 14:03 UTC, aaqe commented
I hate this, there should always be a walk of shame to the nearest sink.