Fixes some inventory stuff
yogstation13/Yogstation pull request #18445
Opened 2023-04-02 13:13 UTC by SapphicOverload

# Document the changes in your pull request

When taking off a jumpsuit, items will no longer fall off of you if you're able to equip them without said jumpsuit.

Also fixes internals not updating when you drop your tank which made it possible to breathe from a tank on the other side of the station.

# Changelog

:cl:  
bugfix: fixes internals not updating when dropped
bugfix: fixes items falling off when removing a jumpsuit when you're still able to equip them in their current slot without one
/:cl:

2023-04-03 05:26 UTC, MortimerTMorose commented
this is the single best PR I've ever seen

2023-04-03 17:41 UTC, ReddicusDragon commented on code/modules/mob/living/carbon/inventory.dm
> +			update_internals() // no more "bluespace" internals tanks
```suggestion
```
As of #18301, tanks will now close if they are dropped

2023-04-03 17:42 UTC, ReddicusDragon submitted a review, later dismissed
See above comment

2023-04-03 21:18 UTC, SapphicOverload commented
fixed

2023-04-03 23:46 UTC, Moltijoe requested changes
please update changelog

2023-04-05 09:46 UTC, SapphicOverload commented
> please update changelog

Done

2023-04-06 00:24 UTC, Moltijoe approved these changes

2023-04-07 01:11 UTC, SapphicOverload commented
@ReddicusDragon

2023-04-12 18:53 UTC, merged