Disable Lavaland Beach Dome Ruin
yogstation13/Yogstation pull request #18457
Opened 2023-04-03 20:46 UTC by Aquizit

# Document the changes in your pull request

Every time this ruin spawns currently it's glitched out with large areas just pitch black. Right clicking on the tile says it's what it is supposed to be, but the tile just isn't appearing.

:cl:  
tweak: Disables Lavaland Beach Dome ruin until the visual glitches on it can be fixed.
/:cl:

2023-04-05 00:34 UTC, namjay1170 commented
Would you kindly delete the snow dome too? originaly it had an antique laser but someone removed that and replaced it with NOTHING, its just a waste of lavaland budget (same with that dogshit one with only a combat knife like why would anyone map and pr that wtf)

2023-05-02 05:55 UTC, ToasterBiome requested changes
could u see why this happens instead maybe uwu

2023-05-02 08:49 UTC, Aquizit commented
I do not know how to do that. I don't even know how to begin figuring that out

2023-05-08 08:09 UTC, Aquizit commented
Alright well if this is gonna languish I'll just close it. I dunno how to fix it as I dunno what's going wrong otherwise I would have tried for the record.

2023-05-08 08:09 UTC, closed without merging