Adds new Viro symptoms
yogstation13/Yogstation pull request #1845
Opened 2018-07-22 03:31 UTC by CMOisLing

###Intent of your Pull Request
I like the idea of double edged sword viro symptoms, they can either be extremely robust, or your doom depending on the application. Work in progress right now extremely unbalanced. Ill write more about it later promise, I can sleep easy knowing my master fork is clean now

Changelog
🆑
rscadd: New high level viro symptoms
wip: Putting this up so code bois can help me
/🆑

2018-07-22 09:44 UTC, ThatLing commented
I like this but muh modular.

2018-07-22 16:07 UTC, AdamElTablawy commented
no more fucking heal symptoms i swear to god i will choke you

2018-07-22 17:26 UTC, CMOisLing commented
I would say it’s more useful for killing people than healing currently

2018-07-22 18:18 UTC, CMOisLing commented
What do you mean by modular, should I add some checks for non humans and animals

2018-07-22 18:47 UTC, morrowwolf commented
https://github.com/yogstation13/Yogstation-TG/blob/master/yogstation/README.md

Modularization.  Use the yogstation13 folder in there to add new procs etc.  If you need more help with it PM me on discord.

2018-07-23 00:17 UTC, CMOisLing commented
For my "confusion" changes should I just put "Nerve Block" in a new file. Or do I have to do something else in that case. Im not gonna add anymore symptoms till I get my formating correct.

2018-07-23 02:57 UTC, CMOisLing commented
I think I figured it out I’ll update it tomorrow

2018-07-23 18:44 UTC, Kmc2000 reviewed
Good work, few things I can see though

2018-07-23 18:44 UTC, Kmc2000 commented on code/datums/diseases/advance/symptoms/confusion.dm
> +/datum/symptom/confusion/confusion/Start(datum/disease/advance/A)
Wha

2018-07-23 18:44 UTC, Kmc2000 commented on code/datums/diseases/advance/symptoms/confusion.dm
> +/datum/symptom/confusion/confusion/Activate(datum/disease/advance/A)
Seriously what's with this

2018-07-23 18:44 UTC, Kmc2000 commented on code/datums/diseases/advance/symptoms/heal.dm
> +	return 1
return TRUE please

2018-07-23 18:44 UTC, Kmc2000 commented on yogstation/code/datums/diseases/advance/symptoms/confusion.dm
> +	desc = "The virus interferes with the proper function of the neural system, leading to bouts of confusion and erratic movement."
Wouldn't it be the nervous system that gets fucked up?

2018-07-23 18:44 UTC, Kmc2000 commented on yogstation/code/datums/diseases/advance/symptoms/heal.dm
> +	return 1
return TRUE (housekeeping)

2018-07-23 19:06 UTC, CMOisLing commented
Thanks for prettying up my shitcode kmc. The changes to the tree where because nerve block and confusion where in the same file called confusion. I’m not sure if that was the right solution.

2018-07-24 11:25 UTC, ThatLing commented on code/datums/diseases/advance/symptoms/heal.dm
> +	return 1
Just delete the changes in this file

2018-07-28 08:54 UTC, ThatLing commented
Delete the changes in the non-yogs files and this is good to go.

2018-07-28 22:59 UTC, CMOisLing commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> -	.=..()
WHAT AM I DOING WRONG I CANT REMOVE THIS SHIT

2018-07-28 23:06 UTC, CMOisLing commented
It keeps readding the new line ive removed whats with that?

2018-07-29 00:51 UTC, CMOisLing commented
The bot says im good? I guess its good to merge?

2018-07-29 01:30 UTC, morrowwolf commented
Huh it doesn't seem to pick up the removal of the newline change.

2018-07-29 04:28 UTC, CMOisLing commented
I’ve tried copying it straight from the master branch and it still says I added a line

2018-07-29 16:06 UTC, morrowwolf commented
Well best bet IMO is to delete the whole file, push that, then re-add it without the space straight from master.  Essentially reset what's not picking up the newline change.

2018-07-29 20:14 UTC, CMOisLing commented
YES

2018-07-29 20:15 UTC, CMOisLing commented
Alright ready to merge

2018-07-30 18:30 UTC, CMOisLing commented
Need to change the levels to 6 and 5 I’ll do it when I get off work

2018-07-30 22:21 UTC, CMOisLing commented
merge dat shit

2018-07-31 11:02 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b requested changes

2018-07-31 11:02 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on yogstation/code/datums/diseases/advance/symptoms/confusion.dm
> +	desc = "The virus strengthens nerve connections decreasing interference to nerve connections, as a side effect the nervous system no longer reacts to pain."
Change this to be less stupid and it's good to go

2018-07-31 12:08 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b requested changes
Actually scratch that there's more things

2018-07-31 12:08 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on yogstation/code/datums/diseases/advance/symptoms/confusion.dm
> +				to_chat(M, "<span class='notice'>[pick("You feel better.")]</span>")
Picking from a list with a single element

2018-07-31 12:08 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on yogstation/code/datums/diseases/advance/symptoms/heal.dm
> +		M.adjustToxLoss(-2)
This HEALS toxin damage, is this what you wanted?

2018-07-31 12:08 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on yogstation/code/datums/diseases/advance/symptoms/heal.dm
> +	if(Toxin_damage)
This is never set to true anywhere

2018-08-01 12:44 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on yogstation/code/datums/diseases/advance/symptoms/heal.dm
> +		Toxin_damage = True
TRUE, this ain't Python

2018-08-02 10:07 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b approved these changes

2018-08-02 10:07 UTC, merged

2018-11-23 02:44 UTC, ATH1909 commented on yogstation/code/datums/diseases/advance/symptoms/heal.dm
> +			to_chat(M, "<span class='warning'>You dont feel so well.</span>")
*don't