Energy Fire Axe
yogstation13/Yogstation pull request #18477
Opened 2023-04-06 07:02 UTC by SapphicOverload

# Document the changes in your pull request

Adds a new weapon to the uplink for 10 TC, available to nuclear operatives and traitor atmospheric technicians: the energy fire axe.

A stronger version of the fireaxe that when wielded, does the same damage as an energy sword, has the same block chance and slightly higher armor penetration (50 > 35), and deals twice as much damage to inanimate objects such as machines, structures and mechs. However unlike an energy sword it cannot fit in a pocket, box or chest rig while inactive and requires both hands to use, meaning you cannot use another item alongside it to further increase block chance unlike an energy sword. It can also be used as a lighter and will ignite anyone you hit that happens to be covered in flammable materials. Fits in the suit storage slot of syndicate hardsuits.

Uses the magnetic cleaver sprite from shiptest-ss13/Shiptest#464

# Spriting

Wielded:
![image](https://user-images.githubusercontent.com/93578146/230295179-36253664-863d-4160-8820-195eed0c6593.png)
![image](https://user-images.githubusercontent.com/93578146/230295213-72c60549-ff51-4583-a433-66afcd08950d.png)
![image](https://user-images.githubusercontent.com/93578146/230295233-a236b3b0-9f61-4d64-b760-9864749c464c.png)
![image](https://user-images.githubusercontent.com/93578146/230295287-cac6e32a-d86d-491f-913e-304c646d17d3.png)

One-handed:
![image](https://user-images.githubusercontent.com/93578146/230295488-05deaa03-4f4d-4020-a79a-21aae6e3a924.png)
![image](https://user-images.githubusercontent.com/93578146/230295709-a1159ead-865b-4b20-b458-4c96b77ba7ac.png)
![image](https://user-images.githubusercontent.com/93578146/230295801-7a4d4ad0-f4e2-4459-b3b7-65212312374c.png)
![image](https://user-images.githubusercontent.com/93578146/230296015-c89c2495-61dc-4649-ade0-4b2ab16fe647.png)

Back/Storage:
![image](https://user-images.githubusercontent.com/93578146/230296140-7ef448ab-dbb3-45ba-a0fa-c971a9699751.png)
![image](https://user-images.githubusercontent.com/93578146/230296212-b0fa8024-f79d-48ee-a4a1-79bbc506ba28.png)
![image](https://user-images.githubusercontent.com/93578146/230296267-d3f2c973-0fbb-45de-a471-3c8e110b2748.png)
![image](https://user-images.githubusercontent.com/93578146/230296358-72d414e8-595e-4ba1-a470-3e22edc817a2.png)

Item:
![image](https://user-images.githubusercontent.com/93578146/230296609-fe281e0b-c54b-4df1-9bb5-0097c2ad8981.png)
![image](https://user-images.githubusercontent.com/93578146/230296725-405de9ad-9ec3-4d1e-868c-87be6d07d875.png)

# Wiki Documentation

If there's a list of stuff you can get in the uplink, this will need to be added to it.

# Changelog

:cl:  SapphicOverload, MemedHams
rscadd: adds energy fire axe
imageadd: adds energy fire axe sprites
tweak: adds "axed" to the list of attack verbs for axes
bugfix: fixes windows and grilles not respecting armor penetration
/:cl:

2023-04-06 11:22 UTC, isotope436 commented
why did you have to make it a nukie item instead of just making it a ruin spawn item thats a fancy syndi mag crusher like it actually is on tg 😢

2023-04-06 13:15 UTC, tattax commented on code/game/objects/items/twohanded.dm
> +		START_PROCESSING(SSobj, src)
?

2023-04-06 13:16 UTC, tattax commented on code/game/objects/items/twohanded.dm
> +		if(istype(A, /obj) && !istype(A, /obj/item))
```suggestion
		if(isobj(A) && !isitem(A))
```

2023-04-06 23:16 UTC, Cartlord commented
Considering that the existing fire axe is quite strong and a tantalizing target for theft, I don't see the reason for a stronger version.

2023-04-11 18:50 UTC, Moltijoe approved these changes

2023-04-11 19:19 UTC, MajManatee commented
i didn't realize it was an antag item, this is kinda za za'd

2023-04-12 14:40 UTC, cuackles requested changes
![image](https://user-images.githubusercontent.com/68789204/231492352-f9107e0e-c974-47cd-b1da-a47214fbff00.png)
think the hand is offset by one pixel, also the on back sprite strap has a bit of banding, could that be edited out so it looks more simple ?

2023-04-24 08:39 UTC, K4rlox commented
it increases the heat of the people hit by it
this isnt documented

2023-04-24 19:23 UTC, SapphicOverload commented
> it increases the heat of the people hit by it
> this isnt documented

No it doesn't, what part of the code are you looking at?

2023-04-24 21:31 UTC, iamthesilly commented
> ![image](https://user-images.githubusercontent.com/68789204/231492352-f9107e0e-c974-47cd-b1da-a47214fbff00.png) think the hand is offset by one pixel, also the on back sprite strap has a bit of banding, could that be edited out so it looks more simple ?

![image](https://user-images.githubusercontent.com/93578146/234121317-6f70be05-307c-4f07-9c9d-03fd560bcf89.png)
is this better?

2023-04-30 14:00 UTC, cuackles approved these changes

2023-05-01 11:22 UTC, merged