Using a holoparasite injector now also creates a randomly placed single-use stand arrow on the station that anyone can use.
yogstation13/Yogstation pull request #18482
Opened 2023-04-06 23:11 UTC by BurgerLUA

# Document the changes in your pull request

Using a holoparasite injector now also creates a randomly placed single-use stand arrow on the station that anyone can use.

# Justification

Traitor buff because you can use the stand arrow to requiem, and the traitor will know that an arrow spawned before anyone else.
Traitor nerf because it means that a non-crew can actually have a stand that can fight you.
Observer buff because it means that someone can be a stand.
Everyone buff because it is entirely entertaining to watch two stands fight eachother.
Gambling addiction nerf because the arrow has a 50% chance to dust you on use.

# Wiki Documentation

https://wiki.yogstation.net/wiki/Holoparasite
https://wiki.yogstation.net/wiki/Syndicate_Items

# Changelog

:cl: BurgerBB
rscadd: Using a holoparasite injector now also creates a randomly placed single-use stand arrow on the station that anyone can use.
/:cl:

2023-04-06 23:12 UTC, Moltijoe commented
this probably shouldn't be a 100% spawn chance

2023-04-06 23:13 UTC, BurgerLUA commented
> this probably shouldn't be a 100% spawn chance

I am fine with lowering it to 75% or maybe 50%.

2023-04-06 23:15 UTC, LazennG commented
what a burger pr

2023-04-06 23:15 UTC, Moltijoe commented
> I am fine with lowering it to 75% or maybe 50%.

idk, holopara shouldn't come with the risk of making someone a powerful validhunter
it really should be a funny flavour thing with like a 1% chance or something

2023-04-06 23:20 UTC, BurgerLUA commented
> what a burger pr

not sure what you mean by this but ok

2023-04-06 23:46 UTC, wonderinghost commented
I think it should be a event where it might spawn 4. If it detects a holo para active then some time during the round it will trigger the event that spawns more stand arrows. Only once though as I can see it being stupid broken if multiple people triggered it

2023-04-06 23:49 UTC, Moltijoe commented
world's fastest smackdown

2023-04-06 23:51 UTC, Moltijoe commented
general consensus was that this is a bad idea all around
either traitors farm for requiem, or validhunters in maints get holoparas
it is only compounded in rounds with multiple holopara buyers

2023-04-06 23:56 UTC, wonderinghost commented
Damn. I miss my healing punches. But that is valid because there are a lot of shitters

2023-04-07 00:35 UTC, BurgerLUA commented
> world's fastest smackdown

balance council weighs in instantly on this pr but haven't touched my other two prs that are awaiting their feedback

2023-04-07 00:55 UTC, Moltijoe commented
> balance council weighs in instantly on this pr but haven't touched my other two prs that are awaiting their feedback
> 
> society

honestly

2023-04-07 01:11 UTC, Moja10 commented
> general consensus was that this is a bad idea all around either traitors farm for requiem, or validhunters in maints get holoparas it is only compounded in rounds with multiple holopara buyers

I don't know what you mean general consensus is this is a bad idea, this is one of the most badass ideas i've seen in a long time. 10/10 fuck the consequences, I approve it from admin perspective

2023-04-07 01:12 UTC, Moja10 commented
balance council should have better things to do than insta deny a PR based on what, 1 hour of discussion? I say keep it open and fuck the consequences. Everything described in the PR description sounds perfect

2023-04-07 02:13 UTC, Moltijoe commented
it IS cool, which is why i wanted it added at a 1% chance, but pretty much everyone else in the balance council dunked on it

2023-04-07 04:57 UTC, BurgerLUA commented
Well is there any way, other than making it obscenely rare, that I can implement this feature?

2023-04-07 05:01 UTC, namjay1170 commented
each stand present could increase the weight of a stand arrow midround that spawns it, 1 is unlikely to cause the event but have 4 and it becomes a decent chance. should this apply to wizard and admin spawn carp-sie stands too?

2023-04-07 05:02 UTC, namjay1170 commented
also the balance council must not know meteors straight up spawn stand arrows. . .

2023-04-07 05:46 UTC, Moltijoe commented
> Well is there any way, other than making it obscenely rare, that I can implement this feature?

i'll bring it back up with the balance council

2023-04-07 06:02 UTC, ynot01 commented
> Well is there any way, other than making it obscenely rare, that I can implement this feature?

- nerf requiem
- make requiem obtainable by 2 holoparasite injectors
- giving random crew tools to validhunt with is a shitty idea. if you want to make, say, a dedicated antagonist midround role that is given to a random crew member or is spawned in via shuttle that fights other stand users (and has a steal objective like monster hunter) that would be much better

2023-04-07 06:16 UTC, Moltijoe commented
if it involves nerfing requiem, i'm against it

2023-04-07 09:04 UTC, BurgerLUA commented
Would an alternative solution to be so that the maximum stat you can get in any skill is 1 less than the maximum possible, requiring requiem to increase it?

2023-04-07 14:28 UTC, MajManatee requested changes
Holoparasite injector stands cannot be requiumed, so this lacks a foundation.

2023-04-07 23:59 UTC, Moltijoe commented
the more it gets talked about in balance council, the more people dislike the idea, sorry

2023-04-07 23:59 UTC, closed without merging

2023-04-08 00:01 UTC, ToasterBiome commented
> > Well is there any way, other than making it obscenely rare, that I can implement this feature?
> * giving random crew tools to validhunt with is a shitty idea. if you want to make, say, a dedicated antagonist midround role that is given to a random crew member or is spawned in via shuttle that fights other stand users (and has a steal objective like monster hunter) that would be much better

this idea is cool @BurgerLUA