[Bounty] Adds the CVS recipient injector
yogstation13/Yogstation pull request #18502
Opened 2023-04-09 19:53 UTC by BurgerLUA

# Notice

WIP and untested. Don't give me money yet until I know it works and the payee is satisfied.

# Document the changes in your pull request

Adds the CVS recipient injector, a 20TC Hijack only Virologist traitor item that silently injects someone with a disease and makes the mentioned disease sentient.

# Why is this good for the game.

![image](https://user-images.githubusercontent.com/8602857/230793751-b79e7911-9338-438d-94ac-ef412689224d.png)

# Changelog

:cl:  
rscadd: Adds the CVS recipient injector, a 20TC Hijack only Virologist traitor item that silently injects someone with a disease and makes the mentioned disease sentient.
/:cl:

2023-04-09 20:30 UTC, tattax commented on code/game/objects/items/sentient_disease_injector.dm
> +	if(!proximity || !istype(target,/mob/living/carbon))
```suggestion
	if(!proximity || !icarbon(target))
```

2023-04-09 20:30 UTC, tattax commented on code/game/objects/items/sentient_disease_injector.dm
> +	if(!used)
you mean (used)

2023-04-09 20:30 UTC, tattax commented on code/game/objects/items/sentient_disease_injector.dm
> +			var/datum/reagent/R = k
```suggestion
```

2023-04-09 20:30 UTC, tattax commented on code/game/objects/items/sentient_disease_injector.dm
> +		for(var/k in stored_vial.reagents)
```suggestion
		for(var/datum/reagent/R as anything in stored_vial.reagents)
```

2023-04-09 20:30 UTC, tattax commented on code/game/objects/items/sentient_disease_injector.dm
> +		INVOKE_ASYNC(src, .proc/create_sentient_virus, target, user)
```suggestion
		INVOKE_ASYNC(src, PROC_REF(create_sentient_virus), target, user)
```

2023-04-09 20:30 UTC, tattax commented on code/game/objects/items/sentient_disease_injector.dm
> +		var/datum/disease/D = k
```suggestion
	for(var/datum/disease/D as anything in target.diseases)
```

2023-04-09 20:30 UTC, tattax commented on code/game/objects/items/sentient_disease_injector.dm
> +		var/datum/disease/D = k
could use better var names all around

2023-04-09 20:30 UTC, tattax commented on code/game/objects/items/sentient_disease_injector.dm
> +		var/datum/disease/D = k
```suggestion
	for(var/datum/disease/D as anything in C.diseases) //Cure all existing diseases
```

2023-04-09 20:30 UTC, tattax commented
could you link the bounty pretty please

2023-04-09 21:09 UTC, BurgerLUA commented
> could you link the bounty pretty please

Bounty is linked in the OP.

2023-04-09 21:24 UTC, tattax commented on code/game/objects/items/sentient_disease_injector.dm
> +	desc = "It doesn't look like it prints recipts."
```suggestion
	desc = "It doesn't look like it prints receipts."
```

2023-04-09 21:36 UTC, Rdrazga commented
I struggle to understand the bounty this is for and why it would be better then just giving the virologist a traitor item that lets them break the normal 6 symptom limit without having to rely on a ghost who likely never played virology to not just instantly ruin the virus

2023-04-09 21:36 UTC, Rdrazga commented
Or how insanely unbalanced this would be if said ghost did know virology due to having access to symptoms sentient viruses normally don’t get for balance reasons

2023-04-09 22:21 UTC, ehj236 commented
> Or how insanely unbalanced this would be if said ghost did know virology due to having access to symptoms sentient viruses normally don’t get for balance reasons

I could reverse it instead but I would like to expand upon Sentient disease so that future devs may take a look at it in the future as something that can eventually be fixed, besides viros with access to infinite symptoms by themselves would be literally gamebreaking in every regard, take note of APN(autophagocytosis necrosis) or ARDS(Acute respiratory distress syndrome) even Tumors while by themselves in 6 symptom restrictions. I would rather it be a two person job than someone who becomes a actual god with access to one of the most powerful systems in the entire game apart that rivals both xenobiology, nanites, robotics and even trumps the great works of genetics.

2023-04-11 16:36 UTC, MajManatee requested changes, later dismissed
Please don't have a sprite that's unused. Especially if its just to show what it looks like

2023-04-12 13:38 UTC, BurgerLUA commented
> Please don't have a sprite that's unused. Especially if its just to show what it looks like

There are no unused sprites. The sprite (what it looks like) is not actually inside the .dmi file.

2023-04-14 12:26 UTC, BurgerLUA commented
I have no way to test this since I have no friend, but it should work.

It compiles, so it works.

2023-04-14 12:29 UTC, BurgerLUA commented on code/game/objects/items/sentient_disease_injector.dm
> +		for(var/k in stored_vial.reagents)
This causes travis errors

2023-04-15 22:28 UTC, cuackles approved these changes
aproved

2023-04-16 11:17 UTC, BurgerLUA commented
Okay so requesting a testmerge on this since I have no way to test it. Here are case scenarios of what would happen during a round with this in terms of shit breaking.

**Average Case Scenario**
The virus that the virologist made doesn't get properly merged with the sentient virus and you just have a sentient viruses injector with the sentient disease starting cough.

**Best Case Scenario**
It actually works flawlessly.

**Worst Case Scenario**
Runtime errors occur every time the sentient disease infects someone or tries to open a menu because it has symptoms that a sentient disease never actually is supposed to get.

2023-06-01 10:42 UTC, UltraBigRat commented
why is this 20tc?

2023-06-04 19:15 UTC, tattax commented on code/game/objects/items/sentient_disease_injector.dm
> +	icon = 'yogstation/icons/obj/syringe.dmi'
if you're making the icon file modularized why not the dm file aswell?

2023-07-24 00:27 UTC, ynot01 requested changes
On round 48350, Alexander Crawford was able to spawn 2 separate sentient diseases with 1 injector. The first disease was spawned with this runtime, which may have halted the "use" of the single charge.
```
[2023-07-23 23:50:34.801] [00:48:47] runtime error: Cannot modify null.appearance.
 - proc name: add infection (/mob/camera/disease/proc/add_infection)
 -   source file: disease_mob.dm,230
 -   usr: Alexander Crawford (/mob/living/carbon/human)
 -   src: Sentient Disease (/mob/camera/disease)
 -   usr.loc: the floor (86,151,2) (/turf/open/floor/plasteel)
 -   src.loc: the floor (75,155,2) (/turf/open/floor/plasteel)
 -   call stack:
 - Sentient Disease (/mob/camera/disease): add infection(Sentient Virus (/datum/disease/advance/sentient_disease))
 - Sentient Virus (/datum/disease/advance/sentient_disease): after add()
 - Sentient Virus (/datum/disease/advance/sentient_disease): infect(the monkey (796) (/mob/living/carbon/monkey), 0)
 - Sentient Virus (/datum/disease/advance/sentient_disease): infect(the monkey (796) (/mob/living/carbon/monkey), 0)
 - Sentient Virus (/datum/disease/advance/sentient_disease): try infect(the monkey (796) (/mob/living/carbon/monkey), 0)
 - the monkey (796) (/mob/living/carbon/monkey): ForceContractDisease(Sentient Virus (/datum/disease/advance/sentient_disease), 0, 1)
 - Sentient Disease (/mob/camera/disease): force infect(the monkey (796) (/mob/living/carbon/monkey))
 - the CVS recipient injector (/obj/item/sentient_disease_injector): create sentient virus(the monkey (796) (/mob/living/carbon/monkey), Alexander Crawford (/mob/living/carbon/human))
 - world: ImmediateInvokeAsync(the CVS recipient injector (/obj/item/sentient_disease_injector), /obj/item/sentient_disease_inj... (/obj/item/sentient_disease_injector/proc/create_sentient_virus), the monkey (796) (/mob/living/carbon/monkey), Alexander Crawford (/mob/living/carbon/human))
```

2023-07-24 00:27 UTC, ynot01 commented on code/game/objects/items/sentient_disease_injector.dm
> +				icon_state = "[icon_state]_vial]"
does this dangling ] need to be here?

2023-07-24 00:27 UTC, ynot01 commented on code/game/objects/items/sentient_disease_injector.dm
> +
Allow the sentient disease to pick a name via 	INVOKE_ASYNC(virus, TYPE_PROC_REF(/mob/camera/disease, pick_name))

2023-08-26 22:09 UTC, TheGamerdk commented
Very stale.

2023-08-26 22:09 UTC, closed without merging