adds antagonists to the game
yogstation13/Yogstation pull request #18514
Opened 2023-04-11 02:25 UTC by tattax

i'll fill this out later while i test stuff but i need this out to see merge conflicts

# Document the changes in your pull request

# Spriting

:cl:  
/:cl:

2023-04-11 02:29 UTC, tattax commented
bold are the travelers that open files changed without further warning

2023-04-11 02:29 UTC, Moltijoe commented
wow

2023-04-11 03:29 UTC, Cartlord commented
unatomic, wow

2023-04-12 13:42 UTC, MajManatee commented
wow who coulda guessed that an unfinished draft PR has merge conflicts. Crazy.

2023-04-14 17:54 UTC, JohnFulpWillard commented on code/modules/spells/spell_types/touch/_touch.dm
> +	remove_hand(reset_cooldown_after = TRUE)
```suggestion
	INVOKE_ASYNC(src, PROC_REF(remove_hand), null, TRUE)
```

2023-04-15 23:00 UTC, cuackles requested changes
- talking sword mob sprite got deleted in mob.dmi, recover it
- deletes show and hide from mob/actions, dont see any replacement to them, either recover them or inform me where the replacement is
- the icon for bite_target is the icon for lilith pact, havent read what the file does but if its not the pointer for lilith pact then change
- need to see how the new lightning icon looks on game 
- need to see high frecuenzy blade onhand ingame

2023-04-16 23:05 UTC, cuackles approved these changes

2023-04-16 23:18 UTC, Moltijoe commented
conflicts

2023-04-17 00:04 UTC, tattax commented
@Moltijoe

2023-04-26 05:00 UTC, TerraTheUnwise commented
yo thanks bro I really wanted antags in this game adds that scare factor. 👍

2023-04-27 02:24 UTC, ToasterBiome requested changes
bugs sent on disc for you to fix

2023-05-01 13:45 UTC, MajManatee commented
the DMI conflicts in question

2023-05-26 00:53 UTC, ToasterBiome approved these changes

2023-05-26 00:54 UTC, merged

2023-06-04 02:11 UTC, DylonBR commented
this is the worst PR to have ever been merged

2023-06-04 04:29 UTC, tattax commented
> this is the worst PR to have ever been merged

![image](https://github.com/yogstation13/Yogstation/assets/71668564/0a896010-552b-4863-bf0e-edf6a72feb5e)