Autolathes can now be EMAG'd
yogstation13/Yogstation pull request #18559
Opened 2023-04-14 01:34 UTC by Skrem7

# Document the changes in your pull request

You can now EMAG autolathes (even if you don't use harm intent, it'll work and it won't eat the EMAG). This permanently hacks the autolathe (which is indicated by the blue light rapidly flickering in the hack menu), as well as unlocking some emagged-specific designs.

For now the only emagged designs are:
For 45000 metal:
- 10mm AP Ammo Box
- 10mm HP Ammo Box
- 10mm Incendiary Ammo Box
- 10mm EMP Ammo Box

For 60000 metal:
- .357 Nutcracker Ammo Box 
- .357 Metalshock Ammo Box
- .357 Heartpiercer Ammo Box
- .357 Wallstake Ammo Box

In addition, the following hacked designs have been added (no emag required: just the blue light on):
- .357 Ironfeather bullet, 2000 metal (same cost as the individual .357 one)
- .357 Ironfeather Ammo Box, 40000 metal (same cost as the normal .357 ammo box)
- 10mm Soporific Ammo Box, 30000 metal (same cost as the normal 10mm ammo box)

Considering ironfeather/soporific are the same TC cost as the default bullet, and they shouldn't be *too detrimental to give to crew* (one can only go to an already powergaming detective gun, the other would only slot in a surplus carbine if you find one), I don't think this should be too much of an issue.

# Wiki Documentation

EMAG functionality should be documented on the Emag page
Autolathe designs should go on the Designs... page? I forgot what it's called, but I know it exists

# Changelog

:cl:  
rscadd: You can now EMAG autolathes to render them permanently hacked and able to print 10mm AP, HP, Incendiary, and EMP ammo boxes, in addition to .357 Nutcracker, Metalshock, Heartpiercer, and Wallstake ammo boxes
rscadd: Hacked autolathes can now print individual .357 Ironfeather bullets, as well as 10mm soporific and .357 Ironfeather ammo boxes
/:cl:

2023-04-14 01:52 UTC, tattax commented on code/datums/wires/autolathe.dm
> +				addtimer(CALLBACK(A, /obj/machinery/autolathe.proc/reset, wire), 60)
```suggestion
				addtimer(CALLBACK(A, TYPE_PROC_REF(/obj/machinery/autolathe, reset), wire), 6 SECONDS)
```

2023-04-14 02:01 UTC, wonderinghost commented
Oh bo

2023-04-14 02:49 UTC, Skrem7 commented on code/datums/wires/autolathe.dm
> +				addtimer(CALLBACK(A, /obj/machinery/autolathe.proc/reset, wire), 60)
sure

2023-04-14 06:57 UTC, Rdrazga commented
I would prob not have incen or emp be printable since they normally take rare resources to make

2023-04-14 13:19 UTC, MajManatee commented
uranium and water, and a special kind of rock that sparks. not really rare or expensive.
anyways this would be dope

2023-04-14 15:22 UTC, RG4ORDR commented
This is an extremely dangerous idea that I'd rather not even be a emag tax, but something else like emagging a protolathe after unlocking illegal tech.

2023-04-19 03:10 UTC, ReddicusDragon requested changes
Please consider @Rdrazga 's comment on removing incendiary and emp rounds. If you decide they are fine, let me know and I will push this through.

2023-04-19 03:11 UTC, ReddicusDragon approved these changes
I am stupid.

2023-04-19 03:11 UTC, merged