Changes the vxtvul hammer sounds to be more impact
yogstation13/Yogstation pull request #18553
Opened 2023-04-13 22:36 UTC by solwashere

# Document the changes in your pull request

Changes the vxtvul hammer sounds to sound more impactful and like you are swinging a heavy chunk of metal designed to kill people.

for some reason github doesnt like OGGs 
https://www.mediafire.com/file/hupc4tlz81lo4r1/hammerhitbasic.ogg/file
https://www.mediafire.com/file/gnpf10s0bmj08xo/powerhammerhit.ogg/file

# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: Adds a dedicated hit sound for the unpowered hammer
tweak: changed the charged up attack hit sound
soundadd: adds powerhammerhit.ogg and hammerhitbasic.ogg

/:cl:

2023-04-13 22:42 UTC, cuackles commented
https://user-images.githubusercontent.com/68789204/231898492-fb31b700-2cfe-49fd-8816-95e4fc0d1df9.mp4


https://user-images.githubusercontent.com/68789204/231898495-301700b2-999c-4893-ba34-2c07c0476b0c.mp4
gonna put em here on mp4 so its easier to hear
also dear god they are loud

2023-04-13 22:53 UTC, Moltijoe commented
> gonna put em here on mp4 so its easier to hear also dear god they are loud

i assume the first one is the charged one?
also, is that from something? i vaguely feel like i recognize it

2023-04-13 22:55 UTC, cuackles commented
> > gonna put em here on mp4 so its easier to hear also dear god they are loud
> 
> i assume the first one is the charged one? also, is that from something? i vaguely feel like i recognize it

my bet by the style is the sound is fire force anime

2023-04-13 22:58 UTC, Moltijoe commented
> my bet by the style is the sound is fire force anime

oh, maybe, i'm sure sol would know though

2023-04-13 23:02 UTC, solwashere commented
https://user-images.githubusercontent.com/119529668/231901203-7ef2c96e-7c99-45b6-b8f5-2772970fd8a6.mp4

video demonstration

2023-04-13 23:02 UTC, solwashere commented
> > my bet by the style is the sound is fire force anime
> 
> oh, maybe, i'm sure sol would know though

Risk of Rain 2

2023-04-13 23:06 UTC, solwashere commented
basic spelling error L

2023-04-13 23:06 UTC, Moltijoe commented
> Risk of Rain 2

mithrix sound effect i'm pretty sure

2023-04-13 23:08 UTC, Moltijoe commented
> video demonstration

hmm, i feel like the sound varience should probably be removed from the new charged sound effect
it just feels wrong pitched up or down

2023-04-13 23:11 UTC, solwashere commented
> > video demonstration
> 
> hmm, i feel like the sound varience should probably be removed from the new charged sound effect it just feels wrong pitched up or down

by that do you mean the explosion sound that plays alongside the current one?

2023-04-13 23:20 UTC, Moltijoe commented on code/game/objects/items/twohanded.dm
> +		playsound(loc, 'sound/effects/powerhammerhit.ogg', 80, TRUE) //Mainly this sound
```suggestion
		playsound(loc, 'sound/effects/powerhammerhit.ogg', 80, FALSE) //Mainly this sound
```

> by that do you mean the explosion sound that plays alongside the current one?

i mean do this

2023-04-15 20:40 UTC, Moltijoe approved these changes
shrimple changes

2023-04-15 20:41 UTC, Moltijoe commented
what's with the electruichum.ogg?

2023-04-15 21:23 UTC, solwashere commented
Right yeah, that's a leftover from what I was working on (a charge sound effect) but scrapped due to what I was trying to achieve not really being possible from what I was told

2023-04-16 23:16 UTC, Moltijoe commented
> Right yeah, that's a leftover from what I was working on (a charge sound effect) but scrapped due to what I was trying to achieve not really being possible from what I was told

if you don't plan to use it, it's probably best to just remove it

2023-04-22 00:08 UTC, ReddicusDragon requested changes

2023-04-22 00:08 UTC, ReddicusDragon commented on sound/effects/electrichum.ogg
DELETE THIS IF IT IS UNUSED please and thank you sol

2023-04-22 00:17 UTC, ReddicusDragon approved these changes

2023-04-22 00:27 UTC, ToasterBiome commented
Copywritten Sounds...

2023-05-01 11:21 UTC, Moltijoe commented
> Copywritten sounds... 💀

no they aren't what are you talking about, they're completely original, or from creative commons, or under fair use

2023-05-15 09:37 UTC, neeshacark commented
even if they are copyrighted... that's never stopped ya'll before. we have shittons of stuff like that

2023-05-28 03:50 UTC, ToasterBiome approved these changes

2023-05-28 03:51 UTC, merged