Fixes changelings being able to absorb and ling husk you if you can't be husked
yogstation13/Yogstation pull request #18584
Opened 2023-04-17 05:41 UTC by SapphicOverload

# Document the changes in your pull request

Changelings will no longer be able to absorb you if you can't be husked due to it breaking things and sometimes making you unrevivable.

# Changelog

:cl:  
bugfix: you can no longer be absorbed and ling husked if you can't be husked
/:cl:

2023-04-17 05:59 UTC, Moltijoe commented
just make it not apply the baddna trait to those with husk if you want to take this route

2023-04-18 14:25 UTC, MajManatee commented
someone got trolled as preternis and is mad about it

2023-04-19 04:07 UTC, Moltijoe requested changes
they're technically not applied as traits despite being called species traits

2023-04-19 04:07 UTC, Moltijoe commented on code/game/gamemodes/objective.dm
> +		if(!istype(T) || HAS_TRAIT(T.current, NOHUSK) || HAS_TRAIT(T.current, NO_DNA_COPY)) // if you can't absorb them you shouldn't have an objective to do so
```suggestion
		if(!istype(T) || (NOHUSK in t.current.dna.species.species_traits) || (NO_DNA_COPY in t.current.dna.species.species_traits)) // if you can't absorb them you shouldn't have an objective to do so
```

2023-04-19 14:48 UTC, 00ze-cyclone commented
Preternis have DNA, they should be ling suckable, problem is husk being unfixable

2023-04-24 04:41 UTC, ToasterBiome approved these changes

2023-04-24 04:45 UTC, Moltijoe approved these changes

2023-04-24 04:45 UTC, merged