Nitrium rework
yogstation13/Yogstation pull request #18590
Opened 2023-04-17 11:56 UTC by ynot01

# Document the changes in your pull request

Nitrium now adds an organ that allows you to "overclock" your adrenal glands to gain antistun and speed

Very similar to changeling adrenals

Applies jitter when removing stamina damage and also has glowing red veins like a shadowling, so security can tell you apart from a changeling

# Wiki Documentation

Still removes 10 stamina per tick passively

10 second cooldown

applies 10 burn and 5 toxin damage and 35 disgust stacks on use

removes stuns and removes 75 stam on use

cannot be used while unconscious

adds 10 units of /datum/reagent/medicine/changelingadrenaline (called nitrium adrenaline now) and 4 units of /datum/reagent/medicine/nitriumhaste

nitrium haste is identical to changeling haste but has -0.55 slowdown instead of -2.0

# Changelog

:cl:  
tweak: Nitrium has been reworked into an active effect rather than a passive one
/:cl:

2023-04-17 12:04 UTC, ThatLing requested changes

2023-04-17 12:04 UTC, ThatLing commented on code/modules/surgery/organs/nitrium.dm
> +/obj/item/organ/nitrium_tumor/Insert(mob/living/carbon/M)
```suggestion
/obj/item/organ/nitrium_tumor/Insert(mob/living/carbon/M, special = 0, drop_if_replaced = TRUE)
```

2023-04-17 12:04 UTC, ThatLing commented on code/modules/surgery/organs/nitrium.dm
> +/obj/item/organ/nitrium_tumor/Remove(mob/living/carbon/M)
```suggestion
/obj/item/organ/nitrium_tumor/Remove(mob/living/carbon/M, special = 0)
```

2023-04-17 12:05 UTC, ThatLing commented on code/modules/surgery/organs/nitrium.dm
> +/obj/item/organ/nitrium_tumor/Insert(mob/living/carbon/M, special = 0, drop_if_replaced = TRUE)
```suggestion
/obj/item/organ/nitrium_tumor/Insert(mob/living/carbon/M, special = 0, drop_if_replaced = FALSE)
```
oh wait you prob dont wanna drop this

2023-04-21 21:30 UTC, closed without merging

2023-04-21 21:30 UTC, Moltijoe commented
https://github.com/yogstation13/Yogstation/pull/18591 was approved instead