adds some start icons for engines
yogstation13/Yogstation pull request #18632
Opened 2023-04-23 18:55 UTC by void5402

# Document the changes in your pull request
adds some new icons for supermatter, tesla generator and singularity generator.
super matter will now have a inactive state before getting activated
singlu and tesla gen now have some icons showing how much close they are to becoming a singlu/tesla

# Spriting
sadly github loves giving me 451 and 401 error please check the icondiffbot.

# Changelog

:cl:  
imageadd: added some icons for singularity generator
imageadd: added some icons for tesla generator
imageadd: added inactive and start icon state to supermatter
/:cl:

2023-04-29 20:39 UTC, cuackles requested changes
need you to find out a way to put the sprites in the pr has to follow the format sorry

2023-05-05 22:43 UTC, cuackles requested changes
singulo and tesla look good, but the SM looks to odd and not great, that the sm is just a image scaled down to sprite size doesnt help, either find a way to make it less jarring or remove it

2023-05-08 10:00 UTC, void5402 commented
done.

2023-05-09 02:35 UTC, cuackles approved these changes

2023-05-09 02:50 UTC, Moltijoe approved these changes

2023-05-09 03:50 UTC, merged