Changeling armblade door pry takes 3 seconds instead of 10
yogstation13/Yogstation pull request #18641
Opened 2023-04-24 01:59 UTC by Moltijoe

This makes it on-par with dual mantis blades instead of literally 2x the time of jaws of life

:cl:  
tweak: Changeling armblade door pry takes 3 seconds instead of 10
/:cl:

2023-04-25 13:49 UTC, githubuser4141 commented
I think it makes sense that a purpose built steel tool that's designed to force doors is actually superior at this then a makeshift bone that -technically- can be used. Realistically if a armblade can be used, that means -any- item could be used dependant on the user's strength and if they could get it around the airlock creases.

2023-04-25 17:22 UTC, Moltijoe commented
> I think it makes sense that a purpose built steel tool that's designed to force doors is actually superior at this then a makeshift bone that -technically- can be used. Realistically if a armblade can be used, that means -any- item could be used dependant on the user's strength and if they could get it around the airlock creases.

consider this however, one is an easily printable tool that anyone can get
the other is a specialized antag weapon
also, most people don't even use jaws of life, they just figure out which wires do what and hack it in 2 seconds

2023-05-02 06:00 UTC, ToasterBiome requested changes
too long make it 6

2023-05-02 06:07 UTC, ToasterBiome approved these changes

2023-05-02 06:07 UTC, merged