Adds spraycans to yogsmeta art storage
yogstation13/Yogstation pull request #18661
Opened 2023-04-25 18:59 UTC by DearLacy

There were exactly zero spraycans ANYWHERE on yogsmeta. This remedies this by adding two cans directly opposite of the artist's coven door.
![image](https://user-images.githubusercontent.com/131717681/234376289-170d0ddf-5f36-46c5-99b7-6a96fa692307.png)

# Changelog
:cl:  
mapping: Adds two spraycans to yogsmeta artist's coven.
/:cl:

2023-04-25 20:07 UTC, Ethan4303 approved these changes
Aspiring artists on meta can thrive once again

2023-04-27 17:00 UTC, Ethan4303 approved these changes

2023-04-27 21:43 UTC, Ethan4303 requested changes
Use pixel_x and pixel_y instead of step vars, they break things big time

2023-04-29 01:21 UTC, DearLacy commented
Gonna fix it in fastddm instead of strong, strong is a pain in the ass to make small changes.

2023-04-29 01:21 UTC, closed without merging