[Box] AI Secondary Core Expansion (from AI Rework)
yogstation13/Yogstation pull request #18670
Opened 2023-04-26 16:11 UTC by Aquizit

# Document the changes in your pull request

This takes the current room layout from Bibby's AI Rework project and brings them to box now. Current Secondary AI Core sucks balls, it's tiny, hard to upgrade in, and when you do the room is too hard to keep cold. This brings over what he's mostly got with a few changes:

VR system is not here. Nor is the modular network admin computers, luckily without the VR stuff there room for all the computers is found. Catwalks aren't in, nor are ethernet cables or the like so the floor in the actual core room is visually the same floor tiles as current.

I tried to copy over the stuff from Bibby's PR map piece for piece, but I had to cobble some stuff together via limitations I had from other things not coded yet or whatever. The only code I did bring over is the Public Lounge area for the old tcomms office.

![image](https://user-images.githubusercontent.com/70451213/234636100-fa820304-6b9a-441d-842f-d9540912faa7.png)

![image](https://user-images.githubusercontent.com/70451213/234636163-94d089df-ff21-44fa-b818-db2ae42de966.png)

![image](https://user-images.githubusercontent.com/70451213/234636245-3381cc99-0946-4ef8-b4f8-daab066658ad.png)

![image](https://user-images.githubusercontent.com/70451213/234636305-2e360ed3-257c-486c-842b-6c930f9adc8d.png)

# Wiki Documentation

# Changelog

:cl:  
mapping: Brings over most of the Box mapping changes from Bibby's AI Rework
/:cl:

2023-04-26 16:41 UTC, neeshacark commented
according to your screencaps, this removes the small maint expansion sci maint got, can you readd it?

2023-04-26 17:24 UTC, Aquizit commented
I'm not sure I follow. Like I said I basically copied over the maint layout as exactly as I could. One maint ruins room is lost to this PR -- but it was lost in all the prior test merges anyway, and the tiles that made it up end up going to fill in elsewhere.
![image](https://user-images.githubusercontent.com/70451213/234654613-f91cd4b9-0615-469e-bcec-5ec362c0b19b.png)

2023-04-28 20:48 UTC, Ethan4303 commented
would you or any one be opposed to firelocks on the lounge around the entrance to it?
![image](https://user-images.githubusercontent.com/39889035/235251529-2811804f-a52c-4cbf-9452-29d938e1adcb.png)

2023-04-28 20:49 UTC, Ethan4303 requested changes
Both south side windows on the lounge are missing hull tiles
![image](https://user-images.githubusercontent.com/39889035/235251747-77667b1d-f86d-4b83-ad43-7b3fb8f7e3df.png)

2023-04-28 20:52 UTC, Aquizit commented
yeah just one of the other million things I forgot

2023-05-03 21:25 UTC, closed without merging