What does the r above my head mean?
yogstation13/Yogstation pull request #18717
Opened 2023-05-01 19:55 UTC by N3D6

# Document the changes in your pull request

Funny new brain trauma, "What dose r above my hed mean?"

# Changelog

:cl:  
tweak: new brain trauma line
/:cl:

2023-05-01 19:58 UTC, N3D6 commented
how the fuck are the checks failing it's literally one line of code

2023-05-01 21:32 UTC, Moltijoe requested changes

2023-05-01 21:32 UTC, Moltijoe commented on strings/traumas.json
>  		"@pick(semicolon)Who is Gus??? Tell me right now or else I'm about to get ugly"
```suggestion
		"@pick(semicolon)Who is Gus??? Tell me right now or else I'm about to get ugly",
```

2023-05-03 01:08 UTC, N3D6 commented on strings/traumas.json
>  		"@pick(semicolon)Who is Gus??? Tell me right now or else I'm about to get ugly"
fixed

2023-05-03 03:49 UTC, Moltijoe commented
not a clue what's causing the bot error

2023-05-09 02:04 UTC, Moltijoe approved these changes

2023-05-09 02:04 UTC, merged