replaces nullies with a more interractive mechanic
yogstation13/Yogstation pull request #18791
Opened 2023-05-04 21:41 UTC by TheRyeGuyWhoWillNowDie

people whine about null crates every time they pop up, and with good reason. a single traitor (or every traitor on the station) can rush down cargo and, for the price of one six tc emag, can synthesize infinite numbers of traitor goods. this is very bad.

Replaces null crates with syndicate bounties. Emagging a bounty console will now give you a list of special syndicate bounties you can do in order to make some TC. These are limited, and give considerably less TC in value than null crates, however the benefit is you can pick what you want instead of getting a bunch of items you'll be banned for using.

Screenshot of a few of the bounties:
![image](https://user-images.githubusercontent.com/70169560/236335812-064ad11c-14bd-4442-aa9f-b8beec76d317.png)

# Wiki Documentation

TBD

# Changelog

:cl:  
rscadd: Syndicate Bounties
rscdel: Null crates
tweak: Makeshift emags now work on cargo consoles, if you really want the special ops crate
/:cl:

2023-05-04 21:42 UTC, solwashere commented
Gus redemption arc??

2023-05-04 21:42 UTC, TheRyeGuyWhoWillNowDie commented
> Gus redemption arc??

monkey typewriter analogy

2023-05-04 21:43 UTC, TheBombMakerJL commented
There should be a way of reverting it like emagging the comms console or else it’ll be a big big tell

2023-05-04 21:43 UTC, Therandomhoboo commented
Based Gus PR

2023-05-04 21:47 UTC, milk-is-cool commented
me ordering 10 spec ops crates as a blood brother.

2023-05-04 22:24 UTC, Therandomhoboo commented
I really like them, I would say some of the TC needs tweaking cause I feel like some give out a lower input of TC despite how difficult it is to obtain them, like 3 AEGS for 4tc but AI upload & Control console boards are 5/6 TC and you only need one. 

However, I don't know really how easy they can be obtained so really I have Faith in Gus/Sus and the balance peeps to hash it out.

2023-05-04 22:25 UTC, thegoldencat413 commented
Common Gus W

2023-05-04 23:19 UTC, DylonBR commented
can you like hide the syndi menu or something so you don't get outed while out doing the bounties?

2023-05-05 00:30 UTC, Moja10 commented
I don't see why a nerfed null crate, maybe one with limits, and this PR can't coexist at the same time? I like this a lot, I don't like the outright removal of null crates. They should be nerfed, not outright removed. It was always a unique mechanic that rewarded a traitor cargonian with the ability to converts lots of money into syndicate items, and this PR doesn't satisfy that; it insteads replaces it with a scavenger hunt. 

Not to mention, this has the unintended effect of making things traitors already do into more rewarding endevours. If you had to kill the Captain to get the nuke disk, now you get a bonus 5 TC for doing so. People could argue that they are justified in something like murderboning the RD because they had a bounty for his BoH on his back. Ability to meta when the Captain approves a Phazon construction and then it suddenly goofy ahh disappears, and then he blames the roboticist for doing so. 

More unintended effects like how before the only way to get romerol (25 TC) would be to cooperate with another traitor for their TC, or the ultra syndicate crate for 40 TC. Now a traitor who satisfies a single 5 TC bounty can get romerol (I think the hijack only restriction is still there, but still). 

I think the fundamental principle of the null crate is that traitors, and especially cargo traitors can convert money into syndicate items, and I don't want to see the null crate removed just because cargo has a problem with sometimes generating 500000000000 credits which translates into 400 null crates. Cargo always, always for the past 5 years had some (near) infinite money glitch or method and its clear that when a method like this is discovered, eventually a traitor will go in and buy 400 null crates for infinite meme items. There would be literally no problem at all with null crates if they were just hard capped at 10, for example. 

I think there should still be a method for a traitor in cargo to convert money into syndicate items and I stand by current null crates over this PR's removal of them.

2023-05-05 01:29 UTC, ynot01 commented
randomly generate special characters instead of having it be "!&@#" every time

2023-05-05 01:36 UTC, ynot01 submitted a review, later dismissed
Take off the data core and gygax boards, they are free compared to everything else which has to be stolen or is very hard to make (doesnt require 500 glass)

2023-05-05 02:40 UTC, SapphicOverload commented
Why are the CE and RD hardsuits bounties?

2023-05-05 02:50 UTC, TheRyeGuyWhoWillNowDie commented
> Why are the CE and RD hardsuits bounties?

There's one of them
They're a department head unique item, without being grand theft
For lore reasons, they both have a high stat (CE: radiation, RD: bomb) that the syndicate would want to study

2023-05-05 03:02 UTC, SapphicOverload commented
> There's one of them They're a department head unique item, without being grand theft For lore reasons, they both have a high stat (CE: radiation, RD: bomb) that the syndicate would want to study

The CE is normally wearing their suit which means you'll have to kill them for it and I don't think we should encourage killing people that aren't targets or sec just to get a bit more tc. Also because there's only one of them, if they don't get killed for it they still won't be able to do their job anymore. For the RD hardsuit it's not as big of an issue because they don't really need it for their job and it almost always stays in their office.

2023-05-05 07:49 UTC, Therandomhoboo commented
> I don't see why a nerfed null crate, maybe one with limits, and this PR can't coexist at the same time? I like this a lot, I don't like the outright removal of null crates. They should be nerfed, not outright removed. It was always a unique mechanic that rewarded a traitor cargonian with the ability to converts lots of money into syndicate items, and this PR doesn't satisfy that; it insteads replaces it with a scavenger hunt.

So the problem that I saw, is that you say a Traitor can get romerol easily after doing one 5TC bounty which isn't true. It would have to be a 6 or multiple since you need 6TC to get an emag to hack the console and this comes at a cost. If you're not cargo then you either have to build your own cargobay or be able to stealth in and out multiple times without getting sus af which I find is a nice balance to the higher tc items and shit since it is basically a risk. 

I don't think it would be the best idea to have this and the null-crates and it should either be to nerf nullcrates and close this or have this and remove nullcrates.

Cause if you got both up, you basically have a free TC farm. You spam nullcrates (hell lets say 10 for fun) for 300TC worth of shit and find the good syndie items. Then you can complete your bounties with ease despite even going loud so you can get what you want. Which in my opinion isn't good.

All in all, I think its a good PR that can basically reward Traitors for doing extra objectives but not be a point of churning out constant random syndie items that can range from 1 tc to 30tc.

That said, the idea around it was to limit nullcrates to 2-3. Its still 60-90TC worth of shit overall but this stops traitors/cargo antags holding up in cargobay and turning the station into syndie station.

2023-05-05 11:39 UTC, azzzertyy commented
> 

#5917

2023-05-05 11:51 UTC, SapphicOverload commented
> #5917

Contractors aren't supposed to kill their capture targets

2023-05-05 12:43 UTC, Therandomhoboo commented
> The CE is normally wearing their suit which means you'll have to kill them for it and I don't think we should encourage killing people that aren't targets or sec just to get a bit more tc. Also because there's only one of them, if they somehow lose it without getting killed for it they still won't be able to do their job anymore. For the RD hardsuit it's not as big of an issue because they don't really need it for their job and it almost always stays in their office.

I agree we shouldn't kill people that aren't targets but I think thefting it from them is fine, considering it fulfils two things
1) Antag bounty
2) Antag causing antag situations

It would be a massive hinderance to the CE sure, but there are other lesser suits really they have to choose so its like a small punishment for them losing their Head item, but I get where you're coming from

2023-05-05 15:37 UTC, Moja10 commented
> > The CE is normally wearing their suit which means you'll have to kill them for it and I don't think we should encourage killing people that aren't targets or sec just to get a bit more tc. Also because there's only one of them, if they somehow lose it without getting killed for it they still won't be able to do their job anymore. For the RD hardsuit it's not as big of an issue because they don't really need it for their job and it almost always stays in their office.
> 
> I agree we shouldn't kill people that aren't targets but I think thefting it from them is fine, considering it fulfils two things
> 
> 1. Antag bounty
> 2. Antag causing antag situations
> 
> It would be a massive hinderance to the CE sure, but there are other lesser suits really they have to choose so its like a small punishment for them losing their Head item, but I get where you're coming from

People don't just rob important objects from others, there's really two majority outcomes: it is stolen quietly without the Head knowing, or it is taken from them after they are killed. Killing is more simple since they can't do anything about it. Stealing it off their active use just invites you to be targeted by that player and have them assist sec in making sure that you are arrested (perma'd) and they get their shit back. God help you if this invites them to validhunt you. 

What this change will do is make it so people who already have 2ish targets per their normal objectives will now have potentially 4 - 5 targets total. Multiply that across multiple traitors and you have a recipe where a lot of additional people die for the sake of a handful amount of TC. Whereas with null crates, they do not add new valid targets to traitors, they simply reward traitors for being able to convert cash into TC items.

2023-05-05 15:45 UTC, ynot01 requested changes

2023-05-05 15:45 UTC, ynot01 commented on code/modules/cargo/bounties/syndicate.dm
> +/datum/bounty/item/syndicate/aicore
balance council said to remove this

2023-05-05 15:45 UTC, ynot01 commented on code/modules/cargo/bounties/syndicate.dm
> +	wanted_types = list(/obj/item/circuitboard/machine/ai_data_core)
```suggestion
	wanted_types = list(/obj/item/circuitboard/computer/ai_upload_download)
```

2023-05-05 15:45 UTC, ynot01 commented on code/modules/cargo/bounties/syndicate.dm
> +	wanted_types = list(/obj/item/circuitboard/machine/ai_data_core)
```suggestion
	wanted_types = list(/obj/item/clothing/suit/space/hardsuit/rd)
```

2023-05-05 19:45 UTC, solwashere commented
> > > The CE is normally wearing their suit which means you'll have to kill them for it and I don't think we should encourage killing people that aren't targets or sec just to get a bit more tc. Also because there's only one of them, if they somehow lose it without getting killed for it they still won't be able to do their job anymore. For the RD hardsuit it's not as big of an issue because they don't really need it for their job and it almost always stays in their office.
> > 
> > I agree we shouldn't kill people that aren't targets but I think thefting it from them is fine, considering it fulfils two things
> > 
> > 1. Antag bounty
> > 2. Antag causing antag situations
> > 
> > It would be a massive hinderance to the CE sure, but there are other lesser suits really they have to choose so its like a small punishment for them losing their Head item, but I get where you're coming from
> 
> People don't just rob important objects from others, there's really two majority outcomes: it is stolen quietly without the Head knowing, or it is taken from them after they are killed. Killing is more simple since they can't do anything about it. Stealing it off their active use just invites you to be targeted by that player and have them assist sec in making sure that you are arrested (perma'd) and they get their shit back. God help you if this invites them to validhunt you. 
> 
> What this change will do is make it so people who already have 2ish targets per their normal objectives will now have potentially 4 - 5 targets total. Multiply that across multiple traitors and you have a recipe where a lot of additional people die for the sake of a handful amount of TC. Whereas with null crates, they do not add new valid targets to traitors, they simply reward traitors for being able to convert cash into TC items. 
> 
> 

Doesn't the PR say 5 bounties spawn, ever?
I'd assume that means it's the total amount that can spawn for everyone, if that is the case it's a bit disingenuous to say that it multiplies across all traitors.
 I like this even if it means that I'm a bigger target because it gives antags more potential to interact with people outside of stealing the hand teleporter and killing some assistant

2023-05-05 21:56 UTC, Therandomhoboo commented
> > > The CE is normally wearing their suit which means you'll have to kill them for it and I don't think we should encourage killing people that aren't targets or sec just to get a bit more tc. Also because there's only one of them, if they somehow lose it without getting killed for it they still won't be able to do their job anymore. For the RD hardsuit it's not as big of an issue because they don't really need it for their job and it almost always stays in their office.
> > 
> > 
> > I agree we shouldn't kill people that aren't targets but I think thefting it from them is fine, considering it fulfils two things
> > 
> > 1. Antag bounty
> > 2. Antag causing antag situations
> > 
> > It would be a massive hinderance to the CE sure, but there are other lesser suits really they have to choose so its like a small punishment for them losing their Head item, but I get where you're coming from
> 
> People don't just rob important objects from others, there's really two majority outcomes: it is stolen quietly without the Head knowing, or it is taken from them after they are killed. Killing is more simple since they can't do anything about it. Stealing it off their active use just invites you to be targeted by that player and have them assist sec in making sure that you are arrested (perma'd) and they get their shit back. God help you if this invites them to validhunt you.
> 
> What this change will do is make it so people who already have 2ish targets per their normal objectives will now have potentially 4 - 5 targets total. Multiply that across multiple traitors and you have a recipe where a lot of additional people die for the sake of a handful amount of TC. Whereas with null crates, they do not add new valid targets to traitors, they simply reward traitors for being able to convert cash into TC items.

To be fair going off what Sol said, I'm sure Sus/Gus will put in a limit to how manyt and it won't be each individual antag that gets their own bounty list. If not, then it should be in place to stop the murder spree and so it invites a little rivaly between tators.

2023-05-07 20:44 UTC, ynot01 reviewed
Is the special ops crate accessible anymore?

2023-05-07 23:57 UTC, TheRyeGuyWhoWillNowDie commented
> Is the special ops crate accessible anymore?

Yes

2023-05-08 02:26 UTC, ynot01 approved these changes

2023-05-08 02:48 UTC, merged