Fixes nanites bypassing EMP protection
yogstation13/Yogstation pull request #18801
Opened 2023-05-06 05:27 UTC by SapphicOverload

# Document the changes in your pull request

Exactly what the title says, makes nanites actually care whether the host mob has protection against EMPs or not.

# Changelog

:cl:  
bugfix: fixes nanites bypassing EMP protection
/:cl:

2023-05-06 05:31 UTC, 00ze-cyclone commented
No, armor stacking + healing of nanites is already cancerous, the fact it is in the same department as the one giving augments just make it even worse.

2023-05-06 05:31 UTC, Moltijoe requested changes
only emp_protect_self should cover nanites

2023-05-06 05:31 UTC, SapphicOverload commented
> No, armor stacking + healing of nanites is already cancerous, the fact it is in the same department as the one giving augments just make it even worse.

Nanites got nerfed into the ground 2 months ago, they're barely worth it now

2023-05-06 05:40 UTC, 00ze-cyclone commented
> > No, armor stacking + healing of nanites is already cancerous, the fact it is in the same department as the one giving augments just make it even worse.
> 
> Nanites got nerfed into the ground 2 months ago, they're barely worth it now

They got lightly nerfed, real nerfs were on their ability to kill and stun, they still provide an noteworthy amount of armor and regeneration, saying they aren’t worth it is just bad faith

2023-05-06 05:46 UTC, SapphicOverload commented
> only emp_protect_self should cover nanites

Done

2023-05-06 06:40 UTC, SapphicOverload commented
> They got lightly nerfed, real nerfs were on their ability to kill and stun, they still provide an noteworthy amount of armor and regeneration, saying they aren’t worth it is just bad faith

Lightly nerfed is a massive understatement, bio-reconstruction consumes so much it's almost never worth it and accelerated regeneration heals too slowly to make a difference in a fight (example: takes almost a full minute to heal the damage of a single laser hit)

2023-05-06 22:11 UTC, Moltijoe requested changes

2023-05-06 22:11 UTC, Moltijoe commented on code/datums/components/nanites.dm
> +	if(empproof && (empproof.flags & EMP_PROTECT_SELF))
```suggestion
	if(empproof && (empproof.getEmpFlags() & EMP_PROTECT_SELF))
```

2023-05-07 09:50 UTC, Moltijoe approved these changes
Code looks fine

2023-05-08 21:12 UTC, merged