Adds gravitational lensing to the Ark
yogstation13/Yogstation pull request #18809
Opened 2023-05-06 20:06 UTC by azzzertyy

# Document the changes in your pull request

Whenever the Ark is shot now, it will give a gravitational lensing affect based entierly on its damage, (0.1 + damage_amount/80)
It will then shrink back down as it recovers.
It also adds a lens effect to the ark once its destroyed, as well as when its completed. Currently this is unfinished, as I have yet to add a check for damaging it, meaning the lensing will get reset once you shoot it again.
Makes shooting the ark way more interesting, and has the potential to cause a little bit more chaos in the Ark room.

https://user-images.githubusercontent.com/42524344/236644511-439b1e12-4331-4181-a686-18cb10258966.mp4

# Changelog
:cl:  
rscadd: Added Gravitation Lensing to the Ark
/:cl:

2023-05-06 22:35 UTC, Moltijoe commented
looks far too harsh, try messing with the alpha of the effect

2023-05-06 23:33 UTC, cuackles requested changes
this is kinda visual so i asume i have a say in this as the art director but i think it would look better if when damaged it did a similar effect to the when dead , so like every hit make a wave or make it so just the dying one

2023-05-07 21:19 UTC, azzzertyy commented
Will take a further look into this one a bit later.

2023-05-17 16:04 UTC, ynot01 commented
> it would look better if when damaged it did a similar effect to the when dead , so like every hit make a wave or make it so just the dying one

agreed

2023-05-23 12:05 UTC, closed without merging