Heretic drip and toys
yogstation13/Yogstation pull request #18832
Opened 2023-05-08 21:10 UTC by airlines7

### TL;DR
Adds toy heretic sickles to donksoft vending
Adds a "fashionable robe" to the costume autodrobe, the costume version of the ominous armor.

# Description

### The drippy robe
After all these years the heretic drip now for the common man. I've made sure that it does not decrease damage and people can be identified with it on as it is just a "fashionable" hood and robe. Has some silly flavor text about a massacre at a Nanotrasen fashion show.
Video proof  https://user-images.githubusercontent.com/98609667/236930600-580c9b00-b6a2-4f16-9b83-41228e526487.mp4

![image](https://user-images.githubusercontent.com/98609667/236932658-7718c17a-a962-4a9e-a0a7-33b3e9a79bc8.png)

![image](https://user-images.githubusercontent.com/98609667/236931230-d275fbef-f838-4179-b266-5c85a44c64fd.png)

![image](https://user-images.githubusercontent.com/98609667/236931111-6ea9a5b2-efc4-4f9d-90f1-a79047c9fac1.png)

### The toy blades
I've made sure the toys do no damage and do not paralyze with the hook, I don't know why the sickles show up as random icons. I'll (probably not) figure it out and fix it at some point.

Video Proof  https://user-images.githubusercontent.com/98609667/236933452-6903479e-464e-4732-810a-f2aad86edb14.mp4

![image](https://user-images.githubusercontent.com/98609667/236931013-6eb8c289-912a-4147-965a-389a2c3039d3.png)

![image](https://user-images.githubusercontent.com/98609667/236931789-bc3c20d6-4ae6-48b3-8a7a-d2552eefda52.png)

I see the "metalicr" its already fixed, too lazy to upload another photo demo.
The sickles also don't do the honk I coded in, but that just makes it more tolerable as a toy. Feel free to remove or fix.

# Changelog

:cl:  Airlines7
rscadd: Heretic costumes for the comedic clown and cynical mime.
wip: Toy Heretic blades, brought to you by Donksoft.

/:cl:

2023-05-08 21:23 UTC, TerraTheUnwise commented
this is good, I like this.

2023-05-08 21:48 UTC, DylonBR commented
![image](https://user-images.githubusercontent.com/95513530/236943647-3d4be431-3bb8-4d63-bb7e-964e6a7d5bee.png)
theres no way this is gramatically correct, close this PR immediately and ban this individual from ever making PRs again. Yog has fallen

2023-05-08 22:39 UTC, airlines7 commented
Noticed it does conceal one's identity without an id, like the normal heretic robe. Should I keep it that way or have the robes make you always identifiable?

2023-05-10 09:09 UTC, K4rlox commented
amazing PR 
now i can paint my shock hand green and watch as sec think its heretic hand and cremates me

2023-05-16 22:49 UTC, Therandomhoboo commented
Don't get why the thumbs down. As long as the grammatical errors are cleared up and the code works sure its funny to see sec shit their pants thinking its a certain gamemode.

2023-05-19 01:23 UTC, TerraTheUnwise commented
Please merge this, too long have I had to illegally steal heretic blades from security.

2023-06-02 13:32 UTC, MajManatee requested changes
Fix gramatical issues, fix the icon being a cup.

2023-06-02 18:27 UTC, airlines7 commented
> Fix gramatical issues, fix the icon being a cup.

Will do.

2023-06-02 22:30 UTC, airlines7 commented
So good news, grammar is fixed. bad news, the icons being cups is a way larger issue than the scope of the pr and out of my ability
Best example of my findings: the chefdrobe, seen live in round 47479
![image](https://github.com/yogstation13/Yogstation/assets/98609667/dfbdf46d-139d-47cf-8192-b8bf5d01d581)
I spent 5 hours messing around finding a solution and can't. 
What I did notice is the robe has an icon, I can remove the toy blades if not having icons is that big a deal.

2023-06-03 02:24 UTC, airlines7 commented
Balance council request to remove hook

2023-06-06 01:54 UTC, airlines7 commented
Forgot to point out, the only changes to the map is pictured below.
![image](https://github.com/yogstation13/Yogstation/assets/98609667/6f6117dc-86a4-429a-9352-165fd36a0fa6)

2023-06-06 03:04 UTC, ynot01 requested changes

2023-06-06 03:04 UTC, ynot01 commented on code/game/objects/items/toys.dm
> +
Remove this empty line and put an empty line between the type definition and this proc

2023-06-10 18:34 UTC, ynot01 requested changes

2023-06-10 18:34 UTC, ynot01 commented on code/game/objects/items/toys.dm
> +/obj/item/gun/magic/hook/sickly_blade/attack(mob/living/M, mob/living/user)
wrong path

2023-06-10 18:34 UTC, ynot01 commented on code/game/objects/items/toys.dm
> +	attack_verb = list("attacks", "slashes", "stabs", "slices", "tears", "lacerates", "rips", "dices", "rends")
the projectile is not overrided so it does 40 damage 😓

2023-06-10 21:15 UTC, ynot01 commented on code/game/objects/items/toys.dm
> +	ammo_type = null // Hook remover (tm)
this might runtime

2023-06-11 10:24 UTC, ynot01 commented on code/game/objects/items/toys.dm
> +	if(ismovable(target) && blocked != 100)
Not calling /obj/item/projectile/proc/on_hit() could have adverse effects but I'm not sure

2023-06-11 14:32 UTC, airlines7 commented
FastDMM2 defaulted to CRLF, reconverted back to LF. Also added bardrobe because that too had the icon problem.
![image](https://github.com/yogstation13/Yogstation/assets/98609667/905ce28f-118c-489d-8fde-1c587dc0e274)


> Not calling /obj/item/projectile/proc/on_hit() could have adverse effects but I'm not sure

The Original Heretic blade did this so I'm assuming nothing bad will happen. I'll test with your change and see what happens though.

2023-06-11 14:36 UTC, ynot01 commented
> > Not calling /obj/item/projectile/proc/on_hit() could have adverse effects but I'm not sure
> 
> The Original Heretic blade did this so I'm assuming nothing bad will happen. I'll test with your change and see what happens though.

The heretic blade calls the parent proc as shown here
```
/obj/item/projectile/hook/sickly_blade/on_hit(atom/target, blocked)
	. = ..() // Calls parent proc
	if(iscarbon(target) && blocked != 100)
		var/mob/living/carbon/C = target
		for(var/obj/item/shield/riot/R in C.get_all_gear())
			R.shatter() // Shield :b:roke
			qdel(R)
```

2023-06-11 14:44 UTC, airlines7 commented
> > > Not calling /obj/item/projectile/proc/on_hit() could have adverse effects but I'm not sure
> > 
> > 
> > The Original Heretic blade did this so I'm assuming nothing bad will happen. I'll test with your change and see what happens though.
> 
> The heretic blade calls the parent proc as shown here
> 
> ```
> /obj/item/projectile/hook/sickly_blade/on_hit(atom/target, blocked)
> 	. = ..() // Calls parent proc
> 	if(iscarbon(target) && blocked != 100)
> 		var/mob/living/carbon/C = target
> 		for(var/obj/item/shield/riot/R in C.get_all_gear())
> 			R.shatter() // Shield :b:roke
> 			qdel(R)
> ```

Calling for parent proc makes the hook have you bring people to the user. Thats why its not there

2023-06-11 17:43 UTC, ynot01 commented
> Calling for parent proc makes the hook have you bring people to the user. Thats why its not there.

Correct

2023-06-11 19:55 UTC, airlines7 commented
After fiddling with the sickles I can assure that not calling the proc for the hook does nothing. If for some reason it does it can be altered in the future. If something does happen, know that the attack log keep who shot the hook still.

2023-06-15 19:20 UTC, airlines7 commented
I will be splitting the PR into two, one for the robes, and one for the toys, the toys are obviously taking a lot longer to deal with and the robes are in a working state.

2023-06-15 19:20 UTC, closed without merging