replaces the spellbook in the lavaland wizard den with 3 construct shells
yogstation13/Yogstation pull request #18839
Opened 2023-05-09 13:00 UTC by SomeguyManperson

# Document the changes in your pull request

Spellbook only has grief/validhunt spells in it, all of which are robeless because of course they are
Instead I will replace it with construct shells (soulstone not included)

FOR REFERENCE, the spells the book can give are
fireball
sacred flame
smoke
blind
mindswap
forcewall
knock
barnyard
charge
summon item
lightningbolt

# Wiki Documentation

update wizard den map if it's present, 3 tables in the wizard room have construct shells instead of a random spellbook

# Changelog

:cl:  
rscdel: no more spellbook in the wizard den on lavaland because I hate miners
rscadd: construct shells in the wizard den on lavaland
/:cl:

2023-05-09 13:11 UTC, MajManatee commented
lame

2023-05-09 13:19 UTC, Majkl-J commented
I see some of these being useful for miners, 
_**Summon item**_ being one of those.
Most reasonable people with less skill will put that on their PKA, which they might lose if they happen to get, idk, stunned by goliaths (This drops the weapon) or knocked by gibtonite (This also drops the weapon)

_**Forcewall**_ can be used as a get out of shit situation wildcard
(Low on hp, in tight corridor)

2023-05-09 22:17 UTC, Reed0506 commented
maybe replace it with an instant summons book, out of all the possible spells its probably the most useful and least problematic.

2023-05-10 09:02 UTC, K4rlox commented
replace.spellbooks with a soul shard belt and 1 construct shell.

2023-05-11 06:54 UTC, Cartlord commented
I support removing the spellbook, but the three construct shells are effectively useless to a miner, so this is a pretty bad change.

2023-05-11 16:31 UTC, neeshacark commented
i like the idea of just nuking most of the spells and leaving just instant summons and forcewall, maybe charge and adding repulse

2023-05-11 17:06 UTC, SomeguyManperson commented
The ruin already has two other more useful and less griefy items it doesnt need the spellbook thrown in on top of that

2023-05-11 17:07 UTC, neeshacark commented
> The ruin already has two other more useful and less griefy items it doesnt need the spellbook thrown in on top of that

fair
shells still useless tho

2023-05-11 17:29 UTC, LazennG commented
FUCK READING BOOKS

2023-05-12 03:00 UTC, ynot01 requested changes

2023-05-12 03:00 UTC, ynot01 commented on _maps/RandomRuins/LavaRuins/lavaland_surface_wizardden.dmm
> +/obj/structure/constructshell,
3? i only see one

2023-05-12 03:03 UTC, ynot01 commented on _maps/RandomRuins/LavaRuins/lavaland_surface_wizardden.dmm
> +/obj/structure/constructshell,
nevermind i see map diff bot

2023-05-12 03:03 UTC, ynot01 approved these changes

2023-05-15 03:43 UTC, ToasterBiome approved these changes

2023-05-15 03:43 UTC, merged

2023-05-15 21:16 UTC, tattax commented
yogstation has fallen