New Chem, Frigorific Mixture
yogstation13/Yogstation pull request #18887
Opened 2023-05-14 22:33 UTC by LaOubliette

Allows ghetto chemists to cool mixtures with salty ice water. 

Currently, Cryostylane allows you to also do this but is practically useless as it is only easily made in a lab setting where heating/cooling mixtures is done by a roundstart machine. 

# Wiki Documentation
Frigorific Mixture is made with 1 part sodium-chloride and 1 part ice. It reacts with water rather than oxygen, but most other variables from cryostylane can be put in its description. 

# Changelog
:cl:  
rscadd: Added salty ice water that makes mixtures cold

/:cl:

2023-05-15 01:14 UTC, Moltijoe requested changes

2023-05-15 01:14 UTC, Moltijoe commented on code/modules/reagents/chemistry/recipes/pyrotechnics.dm
> +/datum/chemical_reaction/cryostylane/on_reaction(datum/reagents/holder, created_volume)
cryostlane?

2023-05-15 02:01 UTC, LaOubliette commented on code/modules/reagents/chemistry/recipes/pyrotechnics.dm
> +/datum/chemical_reaction/cryostylane/on_reaction(datum/reagents/holder, created_volume)
ah i missed one mb

2023-05-17 02:04 UTC, LaOubliette commented on code/modules/reagents/chemistry/recipes/pyrotechnics.dm
> +/datum/chemical_reaction/cryostylane/on_reaction(datum/reagents/holder, created_volume)
should be fine now

2023-05-17 02:49 UTC, Moltijoe requested changes
sql, bruh what?

2023-05-17 16:45 UTC, ynot01 requested changes

2023-05-17 16:45 UTC, ynot01 commented on SQL/tgstation_schema_prefixed.sql
remove changes

2023-06-02 13:45 UTC, MajManatee commented
Reopen when work continutes

2023-06-02 13:45 UTC, closed without merging