IPC Defibrillation & Cult Eyes text changes.
yogstation13/Yogstation pull request #18882
Opened 2023-05-13 20:10 UTC by Code611

# Document the changes in your pull request
**Adds two new dialogues for the defibrillator to alert newbie medics that box head people can't be defibbed or surgically repaired.**

1. **The first one reflects the initial message for whatever is making them unrevivable, but mostly hints the user that surgery can't help an IPC repair damage.** 
![toomuchdmg](https://github.com/yogstation13/Yogstation/assets/44381232/8e82f5cb-f197-4912-9b2d-10936133e0a4)

2. **The second one refers to if the player tries to defib a revivable IPC**
![ressuscitation](https://github.com/yogstation13/Yogstation/assets/44381232/41c6793f-d1b7-4db0-a48a-3528941c4443)

While yes this may not come into play OFTEN, and the new player might not even care enough to try defibbing them again, hopefully this will stop those rare situations where a player just assumed they must be cloned ((only to find out icpcs

**Additionally, IPCs now have a unique cult_eyes flavor text to compensate for having a big screen instead of eyes.**
![culteyesipc](https://github.com/yogstation13/Yogstation/assets/44381232/287515a1-5634-4d41-9b2a-caefdd550baa)

Everything has been tested, most importantly that the code for hiding cult eyes wasn't botched. 

# Wiki Documentation
Wiki should denote IPC's have a different cult eyes text, even if "BLOOD-RED SWIRLS" isn't obvious enough.
# Changelog
:cl:  
tweak: IPC's now have 2 new unique defibrillation messages.
tweak: IPC's cult "eyes" now detail a monitor as opposed to eyes.
/:cl:

2023-05-13 20:38 UTC, tattax commented on code/game/objects/items/defib.dm
>  					failed = span_boldnotice("[req_defib ? "[defib]" : "[src]"] buzzes: Resuscitation failed - Severe tissue damage makes recovery of patient impossible via defibrillator. Surgical repair may allow
```suggestion
				else if(total_burn >= MAX_REVIVE_FIRE_DAMAGE || total_brute >= MAX_REVIVE_BRUTE_DAMAGE)
					failed = span_boldnotice("[req_defib ? "[defib]" : "[src]"] buzzes: Resuscitation failed -  Severe [isipc(H) ? "chassis" : "tissue"] damage makes recovery of patient impossible via defibrillator [isipc(H) ? "or reboot board. Mechanical repairs via tools may result in successful operation." : ". Surgical repair may allow for successful resuscitation.")
```

2023-05-13 20:38 UTC, tattax commented on code/game/objects/items/defib.dm
> +				else if (HAS_TRAIT(H, TRAIT_NODEFIB) & isipc(H))
just a heads up, & is for checking flags, && is for the and conditonal

2023-05-13 20:38 UTC, tattax commented on code/game/objects/items/defib.dm
>  					failed = span_boldnotice("[req_defib ? "[defib]" : "[src]"] buzzes: Resuscitation failed - Biology incompatible.")
```suggestion
				else if (HAS_TRAIT(H, TRAIT_NODEFIB))
					failed = span_boldnotice("[req_defib ? "[defib]" : "[src]"] buzzes: Resuscitation failed - [isipc(H) ? "Patient's biology is a positronic chassis. Reboot board usage as opposed to defibrillating shocks may prove successful." : "Biology incompatible."]")
```

2023-05-13 22:19 UTC, Code611 commented
Turns out that the last commit was final; everything works.

2023-05-15 00:36 UTC, ilikesaying commented
![image](https://github.com/yogstation13/Yogstation/assets/65475697/02389717-ab67-4649-8fdc-9bdab45d3ffc)

2023-05-15 22:07 UTC, Code611 commented
> ![image](https://user-images.githubusercontent.com/65475697/238217797-02389717-ab67-4649-8fdc-9bdab45d3ffc.png)

erm whoops that was meant to say that ipcs cant be cloned
So not only does the new player see "huh. unrevivable.. I put in big green tube" and then take them to cloner and see they are also unclonable.

2023-05-18 13:33 UTC, MajManatee requested changes
Please atomize these changes, then sure.

2023-05-20 14:00 UTC, Code611 commented
I'll get on it.

2023-05-20 14:00 UTC, closed without merging