Plasmamen heal slightly from drinking plasma instead of it poisoning them
yogstation13/Yogstation pull request #18888
Opened 2023-05-15 02:29 UTC by SapphicOverload

# Document the changes in your pull request

Doesn't make sense that it would poison them, so it now heals 1 toxin damage, 0.5 brute damage, and 0.5 burn damage each reagent processing tick.

# Changelog

:cl:  
tweak: liquid plasma heals plasmamen instead of poisoning them
/:cl:

2023-05-16 01:57 UTC, Marmio64 commented
No downsides and it heals toxin, brute, AND burn? Plasma isn't that hard to get, and even if this has lowish healing it has zero downsides for filling yourself with it for extra healing. Should probably not have plasmaman-omnizine, and should instead have it just heal a smaller amount of brute and burn at the most.

2023-05-16 09:29 UTC, Necrosium commented
Good addition, and it adds a challenge: "Stay alive for 5 minutes while you drink plasma and hide in maints"

2023-05-16 14:14 UTC, Moja10 commented
Good idea, bad stats, like Marmio mentioned you just made gigaomnizine that they can fill themselves with 3000u of. One of those stats should go, since plasma is everywhere and they can just ask the chemist or chef to grind it

2023-05-18 02:57 UTC, ToasterBiome requested changes
too strong, nerf plz

2023-05-25 02:03 UTC, SapphicOverload commented
> too strong, nerf plz

okay made it heal half as much

2023-05-26 02:20 UTC, ToasterBiome approved these changes

2023-05-26 02:20 UTC, merged