Makes Miner Armor progression make more sense.
yogstation13/Yogstation pull request #18912
Opened 2023-05-18 04:41 UTC by solwashere

# Document the changes in your pull request

Tweaks the Pathfinder, HECK and Drake suit values to make them more in line with progression
also murders Pathfinder and Goliath Cloak a bit

Goliath Cloak: (MELEE = 35, BULLET = 10, LASER = 5, ENERGY = 5, BOMB = 50, BIO = 0, RAD = 0, FIRE = 30, ACID = 30, WOUND = 10)
Pathfinder fully upgraded: MELEE = 60, BULLET = 15, LASER = 15, ENERGY = 15, BOMB = 65, BIO = 0, RAD = 0, FIRE = 50, ACID = 50, WOUND = 15
Drake Armor: MELEE = 70, BULLET = 20, LASER = 20, ENERGY = 20, BOMB = 70, BIO = 60, RAD = 50, FIRE = 100, ACID = 100
HECK Suit: MELEE = 75, BULLET = 25, LASER = 25, ENERGY = 25, BOMB = 50, BIO = 100, RAD = 60, FIRE = 100, ACID = 100)

# REASONING:
The Pathfinder set and Goliath Cloak is fairly easy to get as a miner if you get lucky and farm a goliath tendril, and a minor annoyance at best if you cannot find one, so it makes no sense as to why it is so much better at station-side combat than HECK and Drake sets. I buffed the bomb resist a bit to make it more effective for Ashwalkers against Miners, as Miner weapons tend to do boom damage and it's harder to harvest several goliaths as an Ashie just to get one set of a cloak.

HECK and Drake: HECK suit is arguably harder to get than Drake armor, so I raised the HECK suit values a bit in terms of bullet, laser, bomb and lowered some of the Drake numbers a bit. It isn't a huge difference, but it makes the HECK suit more tangible than Drake Armor, which is overall better considering that it is harder to get.
Overall numbers are negotiable as I feel the numbers may be one tier too high and I'd appreciate any other opinions, however I would like to keep the progression of Goliath -> Pathfinder -> Drake -> HECK in terms of armor increase.

# Wiki Documentation

Change any mentions of the aforementioned armor in the wiki if values are listed.

# Changelog

:cl:  

tweak: HECK Suit, Drake Armor, Goliath Cloak, and Pathfinder gear armor has all been tweaked.

/:cl:

2023-05-18 16:42 UTC, MajManatee commented
yuck, no thanks

2023-05-18 16:43 UTC, solwashere commented
Literally who?

2023-05-27 20:20 UTC, solwashere commented
@Moltijoe I was literally just told about the balance council changes wanted, I'll get to doing that when I get home

2023-05-28 05:59 UTC, Moltijoe commented
> @Moltijoe I was literally just told about the balance council changes wanted, I'll get to doing that when I get home

funny, since i wasn't told that you were told, i was about to tell you about them now since no one was responding to me

2023-05-28 06:26 UTC, solwashere commented
lowered bullet, laser and energy resist and rearranged the bomb resist for Drake and HECK

2023-05-31 04:24 UTC, Moltijoe requested changes
i'd appreciate if you made the changelog more specific as to what changed

2023-05-31 14:27 UTC, solwashere commented
> i'd appreciate if you made the changelog more specific as to what changed

That better?

2023-06-01 05:22 UTC, Moltijoe approved these changes

2023-06-01 05:23 UTC, merged