Deletes male polysmorphs
yogstation13/Yogstation pull request #18946
Opened 2023-05-20 17:51 UTC by Mqiib

Polysmorphs are now even more forced to be female (and other forced gender races are fixed probably, not that they exist) because I CANNOT for the life of me figure out the cursed fucking tgui character preferences menu to fix it but this works well enough. It no longer matters what gender you select roundstart.

Also I could have made some questionable jokes with this pr but had to hold myself back, so just think of them yourself.

# Changelog

:cl:  

bugfix: Forced-gender species (polys) no longer can spawn as the wrong gender

/:cl:

2023-05-20 21:02 UTC, Moja10 commented
but how is babby formed?

2023-05-21 03:53 UTC, Mqiib commented
> but how is babby formed?

no

2023-05-22 20:09 UTC, K4rlox commented
> but how is babby formed?

egg

2023-05-22 20:19 UTC, TheGamerdk requested changes, later dismissed
fix tgui

2023-05-22 20:26 UTC, Mqiib commented
> fix tgui

![image](https://github.com/yogstation13/Yogstation/assets/43766432/a07e3f93-59a6-4661-9cd1-398ecb52c18f)

2023-05-31 23:30 UTC, ToasterBiome requested changes
fix tgui

2023-06-01 23:21 UTC, Mqiib commented
> fix tgui

![image](https://github.com/yogstation13/Yogstation/assets/43766432/1a8779c6-a698-42b9-82a7-d4f475ddaa9e)

2023-06-02 13:14 UTC, MajManatee submitted a review, later dismissed
fix tgui

2023-06-02 19:48 UTC, MajManatee commented
2+ weeks to progress :) re-open when you can fix tgui :)

2023-06-02 23:17 UTC, Mqiib commented
> 2+ weeks to progress :) re-open when you can fix tgui :)

"Unfortunately your PR only fixes some of the problem and we here prefer that our code is 100% broken rather than 50% broken"

Motherfucker I SAID I didn't know how to fix the tgui issue, I made this pr because NOBODY ELSE was fixing it despite me asking around. This isn't a feature, there's no downside to this pr. It fixes a problem. If making prs that fix bugs somehow isn't good enough because I don't go out of my way to fix bugs that _other people caused_ then I'm not going to bother making any more prs. Go fuck yourself.

2023-06-05 19:22 UTC, ToasterBiome approved these changes
> > 2+ weeks to progress :) re-open when you can fix tgui :)
> 
> "Unfortunately your PR only fixes some of the problem and we here prefer that our code is 100% broken rather than 50% broken"
> 
> Motherfucker I SAID I didn't know how to fix the tgui issue, I made this pr because NOBODY ELSE was fixing it despite me asking around. This isn't a feature, there's no downside to this pr. It fixes a problem. If making prs that fix bugs somehow isn't good enough because I don't go out of my way to fix bugs that _other people caused_ then I'm not going to bother making any more prs. Go fuck yourself.

lol

2023-06-05 19:24 UTC, ToasterBiome commented
merging this on the promise you'll fix tgui

2023-06-05 19:24 UTC, merged