Entirely redesigns the Listening Post
yogstation13/Yogstation pull request #18948
Opened 2023-05-20 20:56 UTC by Addust

i've left an impact on the syndicate ghostrole experience in /tg/station and voidcrew, time to leave my impact here

# Document the changes in your pull request

Entirely redesigns the Listening Post, making it much, much larger and giving it multiple agents, as well as a few special features.
New Shit:
**Two Showcases!**
The Syndicate found an old Mauler and Gygax and bolted them to a stand in the showcase room where the bomb is.
**Two Comms Agents!**
Due to the much larger nature of the base, it has been decided to equip it with two comms agents. _As a sidenote, please do not use the multiple agent spawns to try and ghetto space explore. I know you want to do it, but no._
**Two Camera Desks!**
We've got two comms agents.
**Two Docks!**
One for the Syndicate Dropship, and one for the Syndicate Fighter.
**New Warehouse!**
A brand-new warehouse (may need changes) has been added to the listening post!
**Proper Atmospherics!**
It's meant to be a long-term base, so proper life support has been installed.
**Fax Machine and Photocopier!**
_[Common] Generic Head of Security says "Some Syndicate comms agents are repeatedly faxing me their ass. What the fuck"_ Be an absolute fucking nuisance! Get your base bombed! Ask Robotics for a mech and get bombed again!
**Holopad Parts!**
I'd have pre-dismantled the fax machine too but uhh... No real way to build it. _I SWEAR TO FUCKING GOD IF YOU METAGAME WITH THE FAX MACHINE I WILL KILL YOU_
**Cayenne 2!**
Because the original one died in a suicide bombing.
**More Syndicate uniforms!**
Includes berets, camo fatigues, and caps.
**Probably more as well!**
Including a chameleon stamp!

Map:
<img width="206" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/ab470aa6-f1db-4648-a33d-1ee7446a6aa0">
Engi/Atmos:
<img width="225" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/38c4a762-7a3f-4bc3-9a7d-c87b1ed501f8">
Telecomms:
<img width="153" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/6972f1f5-7eb7-49ce-a6dd-dea91bd3b670">
Conference Table:
<img width="383" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/2c117938-b220-4507-897d-df96dc502378">
Dormitory Atrium:
<img width="283" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/f418ad05-236d-45be-8471-469937c2a36e">
Dormitories and Dorms Maintenance:
<img width="346" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/53c4c27c-c3e6-4281-b43d-99aa77374867">
Warehouse:
<img width="251" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/75e65542-f903-411b-b4ac-401b93ebfada">
Arrivals:
<img width="330" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/49c0013e-0e34-4574-9df9-ccf338889642">

# Wiki Documentation

Change the ruins page's mention of the listening post to account for the new base.

# Changelog

:cl:  
rscadd: Literally entirely reworks the Syndicate listening post.
/:cl:

2023-05-20 23:12 UTC, Marmio64 commented
base seems unnecessarily large, made so seemingly just because? Old listening station felt very cozy, yet without feeling cramped. I feel like parts of this could be stripped away and some things edited, which I personally would like since it fit into the theme of it being a very minimalist station designed to be very well hidden.

2023-05-21 07:30 UTC, Addust commented
> base seems unnecessarily large, made so seemingly just because?
i can probably trim away some things or add extra things to make the post feel cozier, one moment

i personally don't want the listening post to be too minimalist since it needs to in lore be able to survive quite a while without being active, hence the dedicated atmos processing.

2023-05-21 07:34 UTC, Addust commented
which parts do you think could be lessened best?

2023-05-21 21:20 UTC, Marmio64 commented
> which parts do you think could be lessened best?

Conference table and warehouse have a lot of space. There's a small bit of unnecessary tiles in the tcomms area and engi Atmos area but removing them would probably not change much. Lastly would be arrivals, which only really needs one door for docking. Removing the hallway leading to and including the left door would remove a lot of extra space.

2023-05-21 21:22 UTC, Addust commented
The Arrivals multi-airlocks is because two ships can join, the Syndicate Dropship and Syndicate Fighter from the Traderoute. Warehouse will be fattened up with extra crates. I'll see about doing something to make it work.

2023-05-21 21:35 UTC, Addust commented
<img width="224" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/9d82d9f8-4812-4215-946c-cbfa7f28cfd6">

2023-05-22 15:15 UTC, Addust commented
i'd say everything's ready, cant really shrink the meeting room without some major changes

2023-05-22 19:57 UTC, solwashere commented
I like these changes
Giving the comms agent a buddy is a neat idea

2023-05-22 20:11 UTC, Addust commented
<img width="265" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/04f6d6a9-cc1b-4a61-a87c-c11bd94daf07">

2023-05-22 20:58 UTC, Addust commented
<img width="165" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/adea1a48-1caf-4c8d-b65d-2b41b33b5252">
I'M KEEPING THIS since it's a good syndicate monitoring tool

2023-05-25 07:05 UTC, Addust commented
fiddled with decals a bit
<img width="291" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/f2c936f9-7195-41b9-877a-44790b6c919f">

2023-06-01 05:37 UTC, Aquizit requested changes
Let's talk fire alarms:

WAY TOO MANY. Take out 4 of these ones.

![image](https://github.com/yogstation13/Yogstation/assets/70451213/aa1934f4-d5ed-40a8-b2b6-d6577bd2a535)

This may be nitpicky but you ever try to reach a wall behind a vending machine?

![image](https://github.com/yogstation13/Yogstation/assets/70451213/ec1d9f28-2c6d-4aa4-8f3f-66b90fb0bf61)

Unnecessary to have 2 here so close together without really any obstacles in the way, unlike the comms room which I can understand the two in proximity since they're supposed to be one for each agent.

![image](https://github.com/yogstation13/Yogstation/assets/70451213/c1e77e88-d743-4b81-af4b-e6fc32a98ef6)

Missing one completely.

![image](https://github.com/yogstation13/Yogstation/assets/70451213/78ba9f85-7d79-4d27-aad2-2a63bed98b89)

2023-06-01 11:23 UTC, Addust commented
> Let's talk fire alarms:

i've removed all the ones in dorms except for the ones at each of the 'end' areas, so the cayenne area and the microwave room. engi now also has a fire alarm and the two in the dock have been trimmed down. the wall alarm will stay.

2023-06-01 11:25 UTC, Addust commented
<img width="333" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/6da40957-2893-4cd6-8df7-eeddc37c0e52">
<img width="202" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/564f2aab-8349-4b91-ab09-a189493284ae">
<img width="225" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/e2b8f5a7-6f0d-4006-b591-11a844ad6e68">

2023-06-01 14:17 UTC, Aquizit approved these changes

2023-06-01 14:17 UTC, Aquizit commented
Map looks fine, just needs the code review.

2023-06-01 14:18 UTC, Addust commented
the code's just changing the destination, should probs be fine

2023-06-01 14:19 UTC, Addust commented
PUTTING ON DRAFT TO MAKE AN EMAGGED VERSION OF THE FAX MACHINE

2023-06-01 14:21 UTC, Addust commented
nvm got bamboozled

2023-06-01 14:21 UTC, Aquizit commented
> the code's just changing the destination, should probs be fine

Sure I just can't review that I mean. I'm just mapping stuff.

2023-06-01 14:21 UTC, Addust commented
understandable

2023-06-01 17:26 UTC, hedgehog1029 approved these changes
code looks fine to me fwiw

2023-06-01 18:21 UTC, Addust commented
time to wait for maintainers

2023-06-02 04:59 UTC, Moltijoe approved these changes
code approval

2023-06-02 05:00 UTC, merged