2 new Sinful Demon powers
yogstation13/Yogstation pull request #18954
Opened 2023-05-21 18:11 UTC by Marmio64

Not very big or especially interesting powers, but they are in dire need of something.

Wrath and Envy get the ability Torment
Empowers your hand to allow you to strike someone to inflict a wide variety of debilitating effects. Blurs vision, inflicts hallucinations and disgust, causes minor brain damage, very short immobilization and stun, and confusion. Most useful for torture as Wrath or to inflict and then run for either. 20 second cooldown

Pride gets the Mend ability
Also empowers your hand, but instead with healing powers to recover 20 brute and 20 burn on a target (but not yourself). Pride is meant to be pseudo helpful to the crew (and sometimes other antagonists) so this fits in with them helping others. 12 second cooldown

also a few bug fixes that i noticed how to fix while working on this

# Changelog

:cl:  
rscadd: New Sinful demon abilities. Torment for Wrath and Envy. Mend for Pride.  
bugfix: Demon form works again. Touch attacks work properly. Icon borders fixed, and ignite works again.
/:cl:

2023-05-27 19:49 UTC, Marmio64 commented
I'll see about fixing conflicts later tonight or tomorrow.

2023-05-30 06:07 UTC, JohnFulpWillard commented on code/modules/antagonists/demon/general_powers.dm
> +	var/mob/living/M = victim
Why not just path ``victim`` to ``/mob/living`` in args then?

2023-05-30 06:08 UTC, JohnFulpWillard commented on code/modules/antagonists/demon/sins/pride.dm
> +	var/mob/living/M = victim
Ditto

2023-05-30 06:08 UTC, JohnFulpWillard commented on code/modules/antagonists/demon/demons.dm
> +		/datum/action/cooldown/spell/touch/torment
```suggestion
		/datum/action/cooldown/spell/touch/torment,
```

2023-06-01 06:09 UTC, Moltijoe requested changes

2023-06-01 06:09 UTC, Moltijoe commented on code/modules/antagonists/demon/general_powers.dm
> +	victim.Stun(10)
```suggestion
	victim.Immobilize(3 SECONDS)
	victim.Stun(1 SECONDS)
```

2023-06-06 05:32 UTC, Moltijoe approved these changes
looks to be fine

2023-06-06 05:32 UTC, merged