[BOUNTY] Hecata Bloodsucker Clan (retry)
yogstation13/Yogstation pull request #18971
Opened 2023-05-23 22:56 UTC by Marmio64

I really don't know what the problem was with the last one but nothing i tried would keep it fixed so hopefully just me transferring all the code to a new PR will fix it, and will also get rid of all the bloat commits of me trying to update the branch.
Same thing as #18506

# Document the changes in your pull request

Adds the Hecata clan as a bloodsucker clan.

Link to bounty: https://forums.yogstation.net/threads/15-add-a-new-bloodsucker-clan-ss13-server.26337/

Upsides-
Necromancy: The prime ability of the clan. Hefty blood cost, but lets you quickly convert the dead into temporary zombie vassals. They last 2 minutes at level 0, and up to 17 minutes at level 5 ability level (+3 minutes per level). It can also be used on dead vassals you already own in order to resurrect them permanently. Either way, the victim becomes a Sanguine Zombie, which is like a mix between a non infectious zombie and a infectious one. It can't use guns, and has some slowdown, takes slightly more damage, has soft crit resistance, and high punch damage. Note: Can't be used to farm blood due to Sanguine Zombies not having any. Also doesn't work on Monster Hunters or other Bloodsuckers.

Spirit Call: Summons temporary wraiths which attack nearby non dead. They will attack your vassals too if they aren't zombified! They are weak though and primarily good as distractions for escapes or bolstering your horde...

Deathly Communion: On a cooldown you can send messages to all your vassals, allowing you to coordinate your zombie horde.

Favorite vassal ability: Spirit Call. Favorite vassal is also turned into a Sanguine Zombie if they weren't one already.

Downsides-
Painful Bite: Feeding is painful enough to the victim that the bloodsucker is incapable of stealthily feeding on people, meaning it has to be done while aggressively grabbing them.
No Blood Altar: Using the altar is no longer of interest to you: Thus you can't do tasks for it and level up via it.

Unique Clan Goal: Necromance X amount of people.

Overall, Hecata focuses on a louder approach and on their vassals, similar to the Tzimisce clan. However, rather than a focus on having a few high power vassals, they make hordes of disposable ones. 

# Spriting
https://github.com/yogstation13/Yogstation/assets/60946370/e639ace2-39a7-450e-a1a6-b116f673443e

https://github.com/yogstation13/Yogstation/assets/60946370/95115c14-b588-4098-83c1-4968b17a0a48

the icons are animated, give the first one a while.

# Wiki Documentation

Hecata

The unified clan of death. The Hecata utilize the art of Oblivion to raise the dead, summon hostile ghosts, and communicate with their vassals from afar.

Joining the clan has the following side effects
-You gain 3 abilities.
--Necromancy: Raise dead people as temporary zombie vassals loyal to you, or revive existing vassals permanently.
--Spirit Call: Summon angry wraiths which attack nearby people who aren't zombies (includes non zombified vassals!)
--Deathly Communion: Sends a message to all your vassals no matter their location.

-You can no longer silently feed. Feeding must be done with an aggressive grab.
-You can't interact with blood altars to do tasks or gain ranks.

# Changelog

:cl:  
rscadd: Adds the clan of death to the bloodsuckers, The Hecata Clan! Avid necromancers whose feeding is too painful to be stealthy.
/:cl:

2023-05-25 22:36 UTC, cuackles approved these changes

2023-05-26 04:13 UTC, Marmio64 commented
updated and ready for the bloodsucker changes. Hecata clan 'skull symbol' sprite included in pr description.

2023-05-27 15:35 UTC, JohnFulpWillard requested changes
Please replace instance of ``usr`` with ``owner`` and remove the single letter vars

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/bloodsucker_mobs.dm
> +	deathmessage = "withers away into nothing."
Can't this be set on the mob's declarations?

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/bloodsucker_mobs.dm
> +	if(!src)
Why would src never exist?

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/bloodsucker_mobs.dm
> +	if(src.stat != DEAD) //Wraith loses 1 health every 2 seconds, which means it will disperse after 60 seconds if not damaged.
```suggestion
	if(stat != DEAD) //Wraith loses 1 health every 2 seconds, which means it will disperse after 60 seconds if not damaged.
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/bloodsucker_mobs.dm
> +		adjustHealth(1)
This could very likely be an Element instead

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/feed.dm
> +	var/suppressible = 1
You should instead be using ``blood_drink_type`` on Clans

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/targeted/hecata/necromancy/CheckCanTarget(atom/target_atom)
```suggestion
	return isliving(target_atom)

/datum/action/cooldown/bloodsucker/targeted/hecata/necromancy/CheckCanTarget(atom/target_atom)
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/targeted/hecata/necromancy/CheckCanTarget(atom/target_atom)
If you know this is Carbon (commented by in the proc), you can just path it ``mob/living/carbon/target_atom``.

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/targeted/hecata/necromancy/FireTargetedPower(atom/target_atom)
```suggestion
	return TRUE

/datum/action/cooldown/bloodsucker/targeted/hecata/necromancy/FireTargetedPower(atom/target_atom)
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +		to_chat(owner, "[current_target] is still alive.")
There's no span here

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +			to_chat(user, span_warning("We revive [target]!"))
Balloon alerts here too? For consistency.

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +			to_chat(target, span_notice("Their body refuses to react..."))
Ditto

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +			SEND_SIGNAL(src, BLOODSUCKER_MADE_VASSAL, user, target)
Doesn't ``make_vassal`` call this signal already?

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +			living_time = 17 MINUTES //in general, they don't last long, make the most of them.
Can you at least use a switch here?

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +		owner.balloon_alert(owner, "Target is out of range or not dead yet.")
This is very long for a balloon alert, and it shouldn't be using capital letters.
"out of range/not dead" would be better

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/targeted/hecata/necromancy/proc/zombify(mob/living/user)
```suggestion
	user.death()

/datum/action/cooldown/bloodsucker/targeted/hecata/necromancy/proc/zombify(mob/living/user)
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +//summon wraiths (weakened shades) to attack anyone who isn't a zombie. This includes non-zombified vassals. However, you can get around this by zombifying your vassals.
```suggestion
	base_background_icon_state = "hecata_power_off"

//summon wraiths (weakened shades) to attack anyone who isn't a zombie. This includes non-zombified vassals. However, you can get around this by zombifying your vassals.
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/hecata/spiritcall/vassal //this variant has to exist, as hecata favorite vassals are technically in 'torpor'
```suggestion
	var/num_spirits = 2

/datum/action/cooldown/bloodsucker/hecata/spiritcall/vassal //this variant has to exist, as hecata favorite vassals are technically in 'torpor'
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/hecata/spiritcall/ActivatePower(mob/user = usr)
```suggestion
	check_flags = BP_CANT_USE_WHILE_INCAPACITATED|BP_CANT_USE_WHILE_UNCONSCIOUS

/datum/action/cooldown/bloodsucker/hecata/spiritcall/ActivatePower(mob/user = usr)
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/hecata/spiritcall/ActivatePower(mob/user = usr)
Why are you using mob/user = usr?
You should be using ``owner`` instead.

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +		num_spirits = 4
Switch here

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +	var/list/turf/locs = new
```suggestion
	var/list/turf/locs = list()
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +	summonWraiths(locs, user = user)
Snake case instead please

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +	summonWraiths(locs, user = user)
```suggestion
	summonWraiths(locs, user = owner)
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/hecata/spiritcall/proc/summonWraiths(list/targets, mob/user = usr)
```suggestion
/datum/action/cooldown/bloodsucker/hecata/spiritcall/proc/summonWraiths(list/targets, mob/living/user)
```
the arg is already set when you're setting user when calling it.

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/hecata/spiritcall/proc/cast_effect() //same as veil of many faces, makes smoke and stuff when casted
```suggestion
		new /mob/living/simple_animal/hostile/bloodsucker/wraith(T)

/datum/action/cooldown/bloodsucker/hecata/spiritcall/proc/cast_effect() //same as veil of many faces, makes smoke and stuff when casted
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +	playsound(get_turf(owner), 'sound/magic/smoke.ogg', 20, 1)
Use ``TRUE`` instead of 1 since it's boolean

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +	var/datum/effect_system/steam_spread/puff = new /datum/effect_system/steam_spread/()
```suggestion
	var/datum/effect_system/steam_spread/puff = new /datum/effect_system/steam_spread/bloodsucker()
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/hecata/communion
```suggestion
	owner.spin(8, 1) //Spin around like a loon.

/datum/action/cooldown/bloodsucker/hecata/communion
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/hecata/communion/ActivatePower()
```suggestion
	cooldown_time = 30 SECONDS

/datum/action/cooldown/bloodsucker/hecata/communion/ActivatePower()
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/hecata/communion/proc/deathly_commune(mob/living/user, message) //code from Fulpstation
```suggestion
	deathly_commune(usr, input)

/datum/action/cooldown/bloodsucker/hecata/communion/proc/deathly_commune(mob/living/user, message) //code from Fulpstation
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +	var/input = stripped_input(usr, "Choose a message to tell your vassals.", "Voice of Blood", "")
Can you use ``tgui_input_text`` instead
And sanitize it please

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +	inherent_traits = list(TRAIT_STABLELIVER, TRAIT_STABLEHEART, TRAIT_RESISTCOLD ,TRAIT_RESISTHIGHPRESSURE,TRAIT_RESISTLOWPRESSURE,TRAIT_RADIMMUNE,TRAIT_EASYDISMEMBER,TRAIT_EASILY_WOUNDED,TRAIT_LIMBATT
Multi-line this please

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +	. = ..()
This does nothing, why is it here?
Is it supposed to remove faction on species loss?

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +/datum/species/zombie/hecata/on_species_gain(mob/living/carbon/C, datum/species/old_species)
```suggestion
	changesource_flags = MIRROR_BADMIN | WABBAJACK | ERT_SPAWN

/datum/species/zombie/hecata/on_species_gain(mob/living/carbon/C, datum/species/old_species)
```

2023-05-27 15:35 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +/datum/species/zombie/hecata/on_species_loss(mob/living/carbon/C)
```suggestion
	C.faction |= "bloodhungry"

/datum/species/zombie/hecata/on_species_loss(mob/living/carbon/C)
```

2023-05-27 19:47 UTC, Marmio64 commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +/datum/species/zombie/hecata/on_species_loss(mob/living/carbon/C)
I'm not able to reply/work on all these right now but thank you for going through the code. I'm still not a good coder so pretty much any seemingly nonsensical or documentation/readability errors are likely to be an issue of my skill rather than purposeful stuff and I can go about fixing them.

2023-05-30 06:06 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/feed.dm
> +		to_chat(owner, span_warning("Feeding as a Hecata would cause enough pain to the victim to make silent feeding like this impossible."))
```suggestion
		owner.balloon_alert(owner, "can't silent feed!")
```

2023-05-30 06:06 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +//They are pseudo zombies, which have high punch damage and special resistances, but aren't infectious nor can they use guns.
```suggestion
/**
 * Hecata, the unified clan of death.
 * Focuses more on their vassals than other clans.
 * Has to rely more on vassals for ranks and blood, as they cannot use the blood altar for leveling up and cannot silent feed.
 * In exchange, they can raise the dead as temporary vassals to do their bidding, or permanently revive dead existing vassals.
 * In addition, they can summon Wraiths (shades) around them for both offense and defense
 * And can send messages to vassals anywhere globally via Dark Communion.
 * In addition, raising the dead with Necromancy turns them into Sanguine Zombies
 * They are pseudo zombies, which have high punch damage and special resistances, but aren't infectious nor can they use guns.
 */
```
That way it's autodoc'ed

2023-06-02 14:04 UTC, MajManatee commented
we have so many single letter vars...

2023-06-07 21:39 UTC, Marmio64 commented
still  going to be trying to get the last suggestions done, just been busy and haven't been able to do so

2023-07-02 10:37 UTC, ynot01 commented
is this ready?

2023-07-04 14:16 UTC, Marmio64 commented
> is this ready?

It works, a few non essential code cleanup things aren't implemented both because I've been busy and because I don't really know what some of them mean or how to do them.

2023-07-04 16:23 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/bloodsucker_mobs.dm
> +	response_harm   = "punches"
```suggestion
	response_help = "puts their hand through"
	response_disarm = "flails at"
	response_harm = "punches"
```

2023-07-04 16:23 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +//to do this, you can make someone your favorite vassal, or you can kill them and then revive them with necromancy.
```suggestion
///summon wraiths (weakened shades) to attack anyone who isn't a zombie. This includes non-zombified vassals. However, you can get around this by zombifying your vassals.
///to do this, you can make someone your favorite vassal, or you can kill them and then revive them with necromancy.
```

2023-07-04 16:23 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +	var/num_spirits = 2
Autodoc this please

2023-07-04 16:24 UTC, JohnFulpWillard commented
> I don't really know what some of them mean or how to do them.

Let me know what you're having trouble with on the discord and I'll try to help

2023-07-09 22:42 UTC, Marmio64 commented
everything done except making life drain on wraiths an element. I've been at it for a long and i really don't know why its not working. In it's non element form everything here works fine but i guess i can keep trying to look into it until hopefully this is finally merged.

2023-07-24 16:54 UTC, Marmio64 commented
lifedrain element by willard implemented

2023-07-31 05:57 UTC, JohnFulpWillard approved these changes
Sorry for taking so long on this. This is my final remarks

2023-07-31 05:57 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +	inherent_traits = list(TRAIT_STABLELIVER, TRAIT_STABLEHEART, TRAIT_RESISTCOLD ,TRAIT_RESISTHIGHPRESSURE,TRAIT_RESISTLOWPRESSURE,TRAIT_RADIMMUNE,
```suggestion
	inherent_traits = list(
		TRAIT_STABLELIVER,
		TRAIT_STABLEHEART,
		TRAIT_RESISTCOLD,
		TRAIT_RESISTHIGHPRESSURE,
		TRAIT_RESISTLOWPRESSURE,
		TRAIT_RADIMMUNE,
```

2023-07-31 05:57 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +	C.faction |= "bloodhungry"
```suggestion
/datum/species/zombie/hecata/on_species_gain(mob/living/carbon/mob_changing_species, datum/species/old_species)
	. = ..()
	mob_changing_species.faction |= "bloodhungry"
```

2023-07-31 05:57 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +	C.faction -= "bloodhungry"
```suggestion
/datum/species/zombie/hecata/on_species_loss(mob/living/carbon/mob_changing_species)
	. = ..()
	mob_changing_species.faction -= "bloodhungry"
```

2023-07-31 05:57 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +	summon_Wraiths(locs, user = owner)
```suggestion
	summon_wraiths(locs, user = owner)
```

2023-07-31 05:57 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/hecata/spiritcall/proc/summon_Wraiths(list/targets, mob/living/user)
```suggestion
/datum/action/cooldown/bloodsucker/hecata/spiritcall/proc/summon_wraiths(list/targets, mob/living/user)
```

2023-08-03 17:20 UTC, JohnFulpWillard commented on code/datums/elements/life_drain.dm
> +	if(!isliving(target))\
```suggestion
	if(!isliving(target))
```

2023-08-03 17:21 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/bloodsucker_objectives.dm
> +	explanation_text = "Using Necromancy, revive people [target_amount] times."
```suggestion
	explanation_text = "Using Necromancy, revive [target_amount] people."
```

2023-08-03 17:23 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +			DeactivatePower()
```suggestion
```
power_activated_successfully above already calls this

2023-08-03 17:23 UTC, JohnFulpWillard commented on code/modules/antagonists/bloodsuckers/powers/targeted/hecata.dm
> +/datum/action/cooldown/bloodsucker/targeted/hecata
Hecata spells should follow what Tremere spells did and be in their own folder, but not in the same file

2023-08-03 17:24 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +	TRAIT_EASYDISMEMBER,TRAIT_EASILY_WOUNDED,TRAIT_LIMBATTACHMENT,TRAIT_NOBREATH,TRAIT_NODEATH,TRAIT_FAKEDEATH, TRAIT_NOGUNS, TRAIT_NOSOFTCRIT) //no guns or soft crit
```suggestion
		TRAIT_EASYDISMEMBER,
		TRAIT_EASILY_WOUNDED,
		TRAIT_LIMBATTACHMENT,
		TRAIT_NOBREATH,
		TRAIT_NODEATH,
		TRAIT_FAKEDEATH,
		TRAIT_NOGUNS,
		TRAIT_NOSOFTCRIT,
	)
```

2023-08-03 17:24 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +	inherent_traits = list(
```suggestion
	///no guns or soft crit
	inherent_traits = list(
```

2023-08-03 17:25 UTC, JohnFulpWillard commented
every time I try to review the PR I keep getting more and more nitpicky sorry

2023-08-09 20:28 UTC, JohnFulpWillard approved these changes

2023-08-09 20:29 UTC, merged