Makes the experimentor and secondary data core of Asteroid not utterly braindead
yogstation13/Yogstation pull request #18987
Opened 2023-05-25 00:38 UTC by azzzertyy

# Document the changes in your pull request
I seriously have no idea how any of this ever got past any eyes. It had overlapping APCS for christ sakes
Expands the experimentor room down one so that it doesnt have a weird doorway inbetween two rooms for secondary data core, also makes the tcomms admin's area bigger overall by removing a maint ruin so that the NA doesnt have to literally move the datacores N2 supply just to access a damn freezer.

![image](https://github.com/yogstation13/Yogstation/assets/42524344/9165007a-e47e-4189-a525-6d7479ea21cd)

# Changelog
:cl:  
mapping: Made asteroidstation secondary data core not horrific
mapping: Made asteroidstation experimentor not horrific
/:cl:

2023-05-25 09:12 UTC, hedgehog1029 commented
![image](https://github.com/yogstation13/Yogstation/assets/3532945/a22cb79a-e7f9-4ca1-adda-85cd74060c02)
hello hand labelers

2023-05-25 09:29 UTC, azzzertyy commented
> ![image](https://user-images.githubusercontent.com/3532945/240864040-a22cb79a-e7f9-4ca1-adda-85cd74060c02.png) hello hand labelers

woops lmao

2023-05-26 16:36 UTC, azzzertyy commented
fixed

2023-05-26 22:07 UTC, hedgehog1029 commented
great! wait

![hello again](https://github.com/yogstation13/Yogstation/assets/3532945/01c8b3f3-3eac-4b1e-8490-bfbd040e68f1)

![engineers HATE her](https://github.com/yogstation13/Yogstation/assets/3532945/2d597931-6b54-423d-8870-da5cfcff8b87)

2023-05-26 23:09 UTC, azzzertyy commented
fixed

2023-06-01 05:50 UTC, Aquizit requested changes
![image](https://github.com/yogstation13/Yogstation/assets/70451213/fcae05d3-2b4a-405b-b923-0d1d304b9c92)

So the other experimentor rooms don't have a door, why should this one? They generally have just the hazard decals and firelocks. If you want to rationale why the door should remain, it at least needs renaming.

2023-06-01 11:20 UTC, azzzertyy commented
> ![image](https://user-images.githubusercontent.com/70451213/242492386-fcae05d3-2b4a-405b-b923-0d1d304b9c92.png)
> 
> So the other experimentor rooms don't have a door, why should this one? They generally have just the hazard decals and firelocks. If you want to rationale why the door should remain, it at least needs renaming.

just thought it looked better with one, forgot to rename it
if its not liked here then ill remove it

2023-06-01 14:16 UTC, Aquizit commented
Well, we can keep the door -- a bit of visual distinction between stations is fine. However, do add the hazard decals for it, as well as the two fire doors. Along with the door's rename.

2023-06-19 06:45 UTC, ToasterBiome commented
Reopen when complete

2023-06-19 06:45 UTC, closed without merging