adds the grinch's ultimatum to lobby music
yogstation13/Yogstation pull request #19001
Opened 2023-05-26 01:38 UTC by TheRyeGuyWhoWillNowDie

Have I truly become a spaceman?

:cl:  
rscadd: the grinch's ultimatum 
/:cl:

2023-05-26 01:40 UTC, BurgerLUA approved these changes

2023-05-26 01:40 UTC, Moltijoe requested changes, later dismissed

2023-05-26 01:40 UTC, Moltijoe commented on yogstation/code/controllers/subsystem/ticker.dm
>  		"https://www.youtube.com/watch?v=4JkIs37a2JE"						// Jamiroquai - Virtual Insanity
```suggestion
		"https://www.youtube.com/watch?v=4JkIs37a2JE",						// Jamiroquai - Virtual Insanity
```

2023-05-26 01:40 UTC, BurgerLUA commented on yogstation/code/controllers/subsystem/ticker.dm
>  		"https://www.youtube.com/watch?v=4JkIs37a2JE"						// Jamiroquai - Virtual Insanity
you fucked up no comma holy shit holy fuck

2023-05-26 01:40 UTC, Moltijoe commented
bro can't even do a code

2023-05-27 15:20 UTC, JohnFulpWillard commented
This is such a terrible way of handling roundstart music:

1- It will break if the youtube video is deleted
2- It relies on YouTube as a third party
3- It can still somewhat fall under copyright? Probably?

This really should be a config so admins can add whatever ogg sounds they want in the folder and it'll appear in-game, nothing being held in code.

2023-05-28 03:44 UTC, ToasterBiome approved these changes

2023-05-28 03:45 UTC, ToasterBiome commented
> This is such a terrible way of handling roundstart music:
> 
> 1- It will break if the youtube video is deleted 2- It relies on YouTube as a third party 3- It can still somewhat fall under copyright? Probably?
> 
> This really should be a config so admins can add whatever ogg sounds they want in the folder and it'll appear in-game, nothing being held in code.

Unrelated to PR

2023-05-28 03:45 UTC, merged