All Heads of Staff can set Blue/Green Alert and Emergency Maint Access
yogstation13/Yogstation pull request #19111
Opened 2023-06-03 07:14 UTC by Aquizit

# Document the changes in your pull request

As stated in title. Also added an error text for if someone attempts to change the alert level while it's on cooldown.

Reason for this is for the no auto-blue at round start, it's needed for rounds without Captains. Emergency Maint is just QoL if no AI or Cap for rad storm/blob/etc.

# Changelog

:cl:  
tweak: Heads of Staff can use Communications Console to change security level and emergency maint access.
/:cl:

2023-06-03 18:21 UTC, JohnFulpWillard commented
Does this remove silicon from being able to use it?

2023-06-03 18:43 UTC, Aquizit commented
No they're still able to. I assume since even though I took out the first check of silicon_or_captain there's another separate issilicon check later down the condition checks

2023-06-04 02:47 UTC, TheRyeGuyWhoWillNowDie requested changes
Emergency maintenance access is a keycard authenticator action, so I'd suggest getting rid of the keycard authenticator action or not making it available for every heard

2023-06-04 18:34 UTC, Aquizit commented
It has always been on the comms console as well. Why is having it in both places bad?

2023-06-10 03:22 UTC, ToasterBiome approved these changes

2023-06-12 03:50 UTC, merged