Spaceland - BACK TO THE ASTEROID
yogstation13/Yogstation pull request #19126
Opened 2023-06-05 05:53 UTC by ToasterBiome

# Document the changes in your pull request

![image](https://github.com/yogstation13/Yogstation/assets/5091394/51c1995c-ed89-4a1c-8f56-ee73e6c61726)

asteroid. reminiscent of the old style, with a new mining base in the south.

no special bosses (yet)
no ruins (yet)
requires spaceland minetype (might just make it randomly choose)

WIP

# Wiki Documentation

Spaceland added to yogstation

# Changelog

:cl:  
mapping: Adds spaceland (the old asteroid)
/:cl:

2023-06-05 06:25 UTC, RG4ORDR commented
YES.
APPROVE.
MERGE.
NOW.

2023-06-05 07:58 UTC, neeshacark commented
YES.
APPROVE.
MERGE.
NOW.

2023-06-05 08:37 UTC, azzzertyy commented
keep it without bosses.

2023-06-05 14:22 UTC, Aquizit commented
> keep it without bosses.

"Guy McMiner has signed up as Shaft Miner."
Miner learns it's asteroid.
"Guy McMiner has been moved to cryogenic storage."

2023-06-05 14:33 UTC, MajManatee commented
pogging rn just a little.
Interested to see what kind of bosses you come up with. In the meantime why not just reuse the lava land ones? Ruins too.

2023-06-05 15:11 UTC, Addust commented
_happy imperialism noises_
<img width="74" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/86192f28-852a-4a71-8309-a7b64940ce7e">

2023-06-06 03:55 UTC, TerraTheUnwise commented
wait I just noticed why is the UK there.

also is this a ghost spawn or an alternate place that the mining shuttle can go?

2023-06-07 14:29 UTC, azzzertyy commented
> > keep it without bosses.
> 
> "Guy McMiner has signed up as Shaft Miner." Miner learns it's asteroid. "Guy McMiner has been moved to cryogenic storage."

dont see the problem here :)

2023-06-09 08:09 UTC, UltraBigRat commented
> > > keep it without bosses.
> > 
> > 
> > "Guy McMiner has signed up as Shaft Miner." Miner learns it's asteroid. "Guy McMiner has been moved to cryogenic storage."
> 
> dont see the problem here :)

No mats for you today

2023-06-10 03:23 UTC, N3D6 commented
I love this but I have one problems

Slowdown will be an issue because mining with a slowdown is actual cock and nuts torture

I can make ruins if you want :3333

2023-06-10 04:17 UTC, Moltijoe commented
> > keep it without bosses.
> 
> "Guy McMiner has signed up as Shaft Miner." Miner learns it's asteroid. "Guy McMiner has been moved to cryogenic storage."

Dont call out john miner like that

2023-07-02 10:38 UTC, ynot01 commented
still wip?

2023-07-12 19:59 UTC, ynot01 requested changes

2023-07-12 19:59 UTC, ynot01 commented on code/controllers/subsystem/mapping.dm
> +			LoadGroup(FailedZs, "Spaceland", "map_files/mining", "Spaceland.dmm", default_traits = ZTRAITS_SPACE)
`ZTRAIT_SPACE` lacks `ZTRAIT_MINING`

2023-07-12 20:02 UTC, TheGamerdk requested changes
Make it not spawn randomly or finish it

2023-07-26 01:54 UTC, ToasterBiome commented
later

2023-07-26 01:54 UTC, closed without merging