Permeability fixes/tweaks
yogstation13/Yogstation pull request #19130
Opened 2023-06-05 23:34 UTC by SapphicOverload

# Document the changes in your pull request

- Fixes permeability being 0 by default instead of 1: patches now work as intended
- Thick material (injection-proof) clothing is no longer permeable
- Permeability protection now protects preternis from water damage

# Changelog

:cl:  
bugfix: patches work again
tweak: injection-proof clothes are impermeable
tweak: preternis water damage is now affected by permeability protection
/:cl:

2023-06-06 00:27 UTC, Moltijoe commented
Absolutely insane preternis buff

2023-06-06 01:57 UTC, SapphicOverload commented
> Absolutely insane preternis buff

I don't see how it's that big of a problem

2023-06-06 02:22 UTC, Moltijoe commented
> I don't see how it's that big of a buff

It was a joke

2023-06-12 04:11 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/carbon.dm
> +/mob/living/carbon/get_permeability(def_zone, linear = FALSE)
This ``linear`` arg isn't in the other cases of ``get_permeability`` which will cause problems in the future.

2023-06-12 04:11 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/carbon.dm
> +		var/permeability = linear ? (100 - getarmor(def_zone)) / 100 : 1 / (2**(getarmor(def_zone, BIO) / 15))
Uh.. does this work?
``checkarmor()``, called in ``getarmor()`` on Human, will early return if ``type`` is not provided but ``def_zone`` is, so linear shouldn't be working here, no?

2023-06-12 04:34 UTC, JohnFulpWillard commented
We really should unit test for this.

2023-06-12 04:35 UTC, JohnFulpWillard approved these changes

2023-06-12 19:12 UTC, JohnFulpWillard requested changes
See https://github.com/yogstation13/Yogstation/pull/19203 for why

2023-06-12 19:12 UTC, JohnFulpWillard commented on code/modules/mob/living/carbon/alien/humanoid/queen.dm
> +/mob/living/carbon/alien/humanoid/royal/can_inject(mob/user, error_msg, target_zone, var/penetrate_thick = 0)
```suggestion
/mob/living/carbon/alien/humanoid/royal/can_inject(mob/user, error_msg, target_zone, penetrate_thick = 0)
```

2023-06-12 19:12 UTC, JohnFulpWillard commented on code/modules/mob/living/living.dm
> +/mob/living/proc/can_inject(mob/user, error_msg, target_zone, var/penetrate_thick = 0)
```suggestion
/mob/living/proc/can_inject(mob/user, error_msg, target_zone, penetrate_thick = 0)
```

2023-06-12 19:18 UTC, SapphicOverload commented
Alright, done

2023-06-12 19:18 UTC, JohnFulpWillard approved these changes

2023-06-12 19:24 UTC, merged