Gives CE unique HUD glasses like all the other heads
yogstation13/Yogstation pull request #19143
Opened 2023-06-06 22:00 UTC by SapphicOverload

# Document the changes in your pull request

Captain and HoP get personnel HUD, HoS gets security and medical HUD, RD gets a diagnostic and reagent HUD, CMO gets medical and reagent HUD, CE gets..... ?????

This gives the CE special HUD glasses like all the other heads do: meson sunglasses with a diagnostic HUD.

# Changelog

:cl:  
tweak: CE sunglasses have diagnostic HUD now
/:cl:

2023-06-06 23:17 UTC, wonderinghost commented
What if mason+tray+radscan

2023-06-07 17:46 UTC, MajManatee approved these changes
Welding proof poggers

2023-06-08 18:02 UTC, MajManatee requested changes
Please put them in code/modules/clothing/glasses/hud.dm with the other advanced HUD glasses

2023-06-13 05:36 UTC, SapphicOverload commented
> Please put them in code/modules/clothing/glasses/hud.dm with the other advanced HUD glasses

These aren't a subtype of obj/item/glasses/hud like the other ones are, but okay

2023-06-13 05:45 UTC, SapphicOverload commented
> Please put them in code/modules/clothing/glasses/hud.dm with the other advanced HUD glasses

These are a subtype of item/clothing/glasses/meson instead of item/clothing/glasses/hud so I put it in _glasses.dm with the other mesons and meson sunglasses instead of hud.dm with the hud subtypes. I could rework them to be a subtype of hud but that would cause conflicts with another PR I have open (the one that refactors clothing traits) and this pr already works just fine as it currently is, so unless that PR gets merged first I'd rather not change this for now.

2023-06-14 01:09 UTC, MajManatee approved these changes
i mean it WORKS

2023-06-14 01:10 UTC, merged