Determination is stronger for humans
yogstation13/Yogstation pull request #19169
Opened 2023-06-08 03:12 UTC by Moltijoe

# Why is this good for the game?

![image](https://github.com/yogstation13/Yogstation/assets/108117184/fa90b0f5-0bab-424a-a1db-06245f72993d)

:cl:  
tweak: Determination heals twice as much to wounded bodyparts for humans
/:cl:

2023-06-08 03:13 UTC, ToasterBiome requested changes
by how much

2023-06-08 03:16 UTC, Moltijoe commented
> by how much

![image](https://github.com/yogstation13/Yogstation/assets/108117184/a072d9cc-fa94-463d-af7a-edf5f08aef7b)

2023-06-08 03:18 UTC, DylonBR commented
good change, humans need an actual reason to be played rn.

2023-06-08 03:20 UTC, RG4ORDR commented
Alien species realizing that human will is strong than any modifier and special ability.

2023-06-08 04:50 UTC, JohnFulpWillard commented
SO FUCKING TRUE BESTIE

2023-06-09 00:12 UTC, Marmio64 commented
wtf, a human buff? Hasn't been one of those since the last chess update.
This will probably get reverted 2 months down the line though like anything that buffs humans in particular or nerfs another species in particular. ([partially]pay changes)

2023-06-09 07:17 UTC, Hislyna commented
Is this a lowkey felinid nerf?

2023-06-09 08:23 UTC, Moltijoe commented
> Is this a lowkey felinid nerf?

Nah, looks like they would get it too

2023-06-19 04:03 UTC, ToasterBiome approved these changes

2023-06-19 04:03 UTC, merged