Adds insuls and telecommunication parts to gax tech storage
yogstation13/Yogstation pull request #19214
Opened 2023-06-10 09:48 UTC by Lovebird-Frungy

fixes  #19119

Puts gax in line with other stations by adding tcomm parts and a pair of insuls in the tech storage.
I would have liked to expand it a bit more but given how gax is layed out its nearly impossible.
This will do for now.

has been tested

:cl:  
bugfix: fixed a few things  
mapping: This is a mapping change
/:cl:

2023-06-10 09:50 UTC, UltraBigRat commented
would be good if tools and power cells were also added but   understandable considering how small gax storage is

2023-06-10 09:51 UTC, Lovebird-Frungy commented
> would be good if tools and power cells were also added but understandable considering how small gax storage is

yeah, i've considered expanding tech storage to add the vendor, tools and more stuff
but it would require expanding all of gax engineering

hence why i said this will do for now
maybe when i get the determination to do such an endeavour

2023-06-11 03:24 UTC, ToasterBiome requested changes
You reverted a large amount of changes.

Also all the tcomms equipment is in the [AI Whale](https://wiki.yogstation.net/wiki/AI_Satellite).

Also if you're doing this you might as well mirror it and add some extra space to CE room.

2023-06-11 09:39 UTC, Lovebird-Frungy commented
> You reverted a large amount of changes.
> 
> Also all the tcomms equipment is in the [AI Whale](https://wiki.yogstation.net/wiki/AI_Satellite).
> 
> Also if you're doing this you might as well mirror it and add some extra space to CE room.

oh dang, i did? the change diff seemed fine.
honestly i just decided to answer the first mapping issue i saw and it was this one, i didn’t really check if it was really an issue.
adding stuff to ce room would require to do the whole expanding gax engineering thing, and i’m not sure i have enough commitment towards gax to do such a thing.

2023-06-11 13:32 UTC, Lovebird-Frungy commented
Yeah, there are enough insuls and the tcomms parts are there.
This issue would require a total overhaul of gax engineering.
I'm not ready to do that now.
Also i guess i did break the symmetry of the corners.
And i forgot areas. I'm rusty.

I also still have no idea how i managed to work on an old map.
The diff of the file changing seemed fine but the diffbot is screaming at me.
Its confusing.
And i don't have the will to try to fix it for this pr which is unnecessary anyways.

Closing this now.

2023-06-11 13:32 UTC, closed without merging