lets photogeists heal non plants (at a far reduced rate)
yogstation13/Yogstation pull request #19222
Opened 2023-06-10 18:29 UTC by Marmio64

# Document the changes in your pull request

Photogeists from the kudzu chaplain sect can now heal non plantlike creatures at a 6x reduced rate (0.5 healing per click). Previously they couldn't, so if there were no podpeople or anything (most of the time, there is like 3 pod people mains) they were pretty useless. The healing they can give to non plants is useless for any combat stuff but gives them more stuff to do.

# Changelog

:cl:  
tweak: photogeists can now heal non plantlike creatures, though at a far reduced rate.
/:cl:

2023-06-13 04:14 UTC, Moltijoe requested changes

2023-06-13 04:14 UTC, Moltijoe commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
>  	. = ..()
probably remove this, otherwise it'll heal twice

2023-06-13 12:51 UTC, Marmio64 commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
>  	. = ..()
remove what specifically? The whole else statement and it's contents, or the . = ..()

2023-06-14 09:17 UTC, Moltijoe commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
>  	. = ..()
the . = ..()

2023-07-02 02:18 UTC, Moltijoe approved these changes

2023-07-02 02:18 UTC, merged