Makes Clerk Office Better
yogstation13/Yogstation pull request #19265
Opened 2023-06-13 21:52 UTC by Moja10

# Document the changes in your pull request
![image](https://github.com/yogstation13/Yogstation/assets/17183762/3c368247-d87e-459a-976e-f93d13f03d29)

Ever notice how current Clerk office has a bungus layout where majority of the places to put items are in FRONT of the counter, not behind the counter? Doesn't make any sense to me. If the goal is to sell items to people, then they should be behind the counter, where they can't just take things and then run off with them. Clerk has no means of defending their stuffs so its just entirely good will that if you put things there, no one will steal them. 

Instead, Clerk should have more room behind the counter to put things, that way the crew can view them, then say "Give me the pulse rifle" and the Clerk can proceed with the 200 credit transaction, then the pulse rifle can be handed over. Not a free pulse rifle sitting on a rack.

Also, racks are dogshit for displaying items, tables are much better. Clerks can use the pixel placement like chefs do on the back tables to display their treasure hoard better. 

# Changelog

:cl:  
tweak: Clerk Office Layout shifted around, Clerks will find that their items on display are more secure.
/:cl:

2023-06-15 01:50 UTC, ToasterBiome approved these changes

2023-06-15 01:50 UTC, ToasterBiome requested changes
reverted a PR in here (ai display ones)

2023-07-24 16:26 UTC, Aquizit commented
Is this still being worked on? Closing it tomorrow if not.

2023-07-26 20:42 UTC, Aquizit commented
Stale. Can just ask to reopen when you want to finish working on it.

2023-07-26 20:42 UTC, closed without merging