Memory loss after death pt 2, because manatee doesnt know how to maintain
yogstation13/Yogstation pull request #19273
Opened 2023-06-14 01:20 UTC by solwashere

# Document the changes in your pull request

redone because manatee is dumb

Makes it so that if someone is dead for (currently) 5 minutes, upon revival a message will play telling the player that they have memory loss, either 5 or 10 minutes would likely be good, I'll let council decide that.
Message is tied to brain decay, so switching brains wouldn't work, and it should let you preserve the brain in order to preserve someone's "memories".

This will need a council vote.

# Why this is good for the game
This makes hiding targets a lot more viable, especially witnesses, while not removing the risk entirely of someone yelling your name. In theory this will mean that less people will get round removed if they don't need to be

# Wiki Documentation

Likely will need to be mentioned in any sort of rule guidelines on the wiki if there are any.
# Changelog

:cl:  

tweak: being dead for a while will make your memory of said death go bye bye 

/:cl:

2023-06-14 01:26 UTC, MajManatee commented
its that easy...

2023-06-14 22:26 UTC, Therandomhoboo commented
IPC/Pretenis buff

2023-06-16 14:26 UTC, neeshacark commented
why do ipcs entirely lose their memory? not only does it complicate this but it makes ipc even weaker

2023-06-16 17:37 UTC, Marmio64 commented
> why do ipcs entirely lose their memory? not only does it complicate this but it makes ipc even weaker

likely because of IPC's unique brains not decaying and because this PR would tie memory loss to brain decay. And it doesn't really make them 'weaker', it mostly would just stop them from spilling the beans on an antag who killed them.

2023-06-16 18:03 UTC, adamsong approved these changes

2023-06-16 18:03 UTC, adamsong commented on code/modules/hydroponics/grown/replicapod.dm
> +		to_chat(podman, span_userdanger("You do not remember your death, how you died, or who killed you. <a href='https://forums.yogstation.net/help/rules/#rule-1_6'>See rule 1.6</a>.")) //yogs
No combat log

2023-06-16 18:03 UTC, adamsong commented on code/modules/mob/living/brain/brain_item.dm
> +	if(!((organ_flags & ORGAN_SYNTHETIC) || (owner && (owner.stat < DEAD || HAS_TRAIT(owner, TRAIT_PRESERVED_ORGANS)))))
This ignores stasis entirely

2023-06-16 18:03 UTC, adamsong requested changes
See previous comment

2023-06-16 18:04 UTC, solwashere commented
> See previous comment

I'll look at it when I'm off work

2023-06-16 18:54 UTC, solwashere commented
> > 
why do ipcs entirely lose their memory? not only does it complicate this but it makes ipc even weaker
> 
> likely because of IPC's unique brains not decaying and because this PR would tie memory loss to brain decay. And it doesn't really make them 'weaker', it mostly would just stop them from spilling the beans on an antag who killed them.

Too real
People are acting like this is a "buff" or "nerf" when it is too complex of an issue to qualify it as either. At most it'd probably be annoying for IPCs

2023-06-18 14:24 UTC, neeshacark commented
in practice it adds another thing that makes them less of a viable choice over any other race.  they have very few benefits and every pr seems to make them weaker

2023-06-18 18:30 UTC, solwashere commented
> in practice it adds another thing that makes them less of a viable choice over any other race.  they have very few benefits and every pr seems to make them weaker

"Less viable choice" I'm fairly certain this is honestly better as it makes it so that you can reliably kill an IPC and not have to RR them, or at least you don't have an excuse to do so

2023-06-19 18:59 UTC, ToasterBiome approved these changes

2023-06-19 19:00 UTC, ToasterBiome requested changes
combat log + adam changes

2023-06-19 22:11 UTC, Marmio64 commented
> in practice it adds another thing that makes them less of a viable choice over any other race. they have very few benefits and every pr seems to make them weaker

ipcs just got 3 separate buff PRs in the past 2 weeks

2023-06-20 03:58 UTC, solwashere commented
done

2023-06-20 16:35 UTC, adamsong approved these changes

2023-06-21 16:39 UTC, adamsong requested changes
Fix build errors

2023-06-21 17:58 UTC, solwashere commented
Changed to SHOULD_LIFETICK due to https://github.com/yogstation13/Yogstation/pull/19341

2023-06-21 19:40 UTC, adamsong approved these changes
lgtm

2023-06-22 17:58 UTC, ToasterBiome approved these changes

2023-06-22 17:58 UTC, merged