Some minor changes to space syndicate base.
yogstation13/Yogstation pull request #19282
Opened 2023-06-14 08:20 UTC by neeshacark

# Document the changes in your pull request

Removes basic stock parts from their storage and replaces them with deluxe stock parts to bring it in line with what lavaland syndies have access to. Also gave them a bluespace RPED and two bluespace cells, things lavaland syndies also have.

Improved their kitchen, supplying an oven and a grinder as well as a stocked fridge. Also added two wheat seeds to the small botany closet so they can make more flour if they run out.

Space comms agent can get pretty boring sometimes, this should shake it up and make them capable of doing more which means more fun during downtime.

# Wiki Documentation

Likely changes to the page on space ruins.

# Changelog

:cl:  cark
mapping: space syndicate have a better kitchen and more useful items in their storage.
/:cl:

2023-06-14 21:59 UTC, Addust commented
merge conflict, but your suggestions have been taken into account! you may now safely close this PR knowing that your changes will be stolen for my own listening post update PR

2023-06-14 22:00 UTC, Addust commented
nevermind

2023-06-14 22:01 UTC, Addust commented
there WILL be merge conflicts with my tweaks pr

2023-06-14 22:01 UTC, Addust commented
wait nevermind uhh

2023-06-18 23:41 UTC, Aquizit requested changes
Airlock thingy shifted somehow:

![image](https://github.com/yogstation13/Yogstation/assets/70451213/81ff9f07-eac7-4cec-a36f-d83eb62ae495)

2023-06-22 02:23 UTC, neeshacark commented
eek ook aak

2023-06-22 02:31 UTC, neeshacark commented
wasnt me but its fixed

2023-06-24 20:53 UTC, Aquizit requested changes
Still here

![image](https://github.com/yogstation13/Yogstation/assets/70451213/c3319544-121c-4e15-b328-96095d5f72bc)

---

And this one should be "facing" east not south

![image](https://github.com/yogstation13/Yogstation/assets/70451213/ef2d7d21-3994-4454-b349-c4cdc69216ac)

2023-06-26 03:24 UTC, neeshacark commented
AAAAAAAAAA

2023-06-26 03:28 UTC, neeshacark commented
im going to murder these things if they keep running

2023-06-26 04:17 UTC, Aquizit approved these changes

2023-06-26 04:17 UTC, merged