the sickles™
yogstation13/Yogstation pull request #19295
Opened 2023-06-15 22:45 UTC by airlines7

This is the Toy Sickle part of #18832 

# Description
### TL;DR
Adds toy heretic sickles to donksoft vending
![image](https://github.com/yogstation13/Yogstation/assets/98609667/bd274fd5-3863-47bc-8764-5f3fe3ad83be)
### Video of the sickles in use
[](https://github.com/yogstation13/Yogstation/assets/98609667/e442549a-49c9-4b8e-be3a-f95523bdea27)

:cl:  Airlines7
rscadd: Toy Heretic blades, brought to you by Donksoft.
/:cl:

2023-06-16 01:13 UTC, airlines7 commented
I was told by ynot to reference parent proc on discord. I will do that soon™

2023-06-18 23:32 UTC, ynot01 requested changes

2023-06-18 23:32 UTC, ynot01 commented on code/game/objects/items/toys.dm
> +
```suggestion
	harmful = FALSE
```

2023-06-18 23:32 UTC, ynot01 approved these changes

2023-06-18 23:38 UTC, merged