ports update_appearance
yogstation13/Yogstation pull request #19297
Opened 2023-06-16 01:02 UTC by tattax

just makes it easier to update things, murders update_icon

main pr: https://github.com/tgstation/tgstation/pull/55468

this is more brute force so nothing is fully updated to properly use update_desc, icon, name, but it doesn't really break anything

just encourages people to change it if they find it set up improperly (please)

:cl:  
imageadd: adds sus airlocks
/:cl:

2023-06-16 01:23 UTC, JohnFulpWillard commented on code/_onclick/hud/lavaland_elite.dm
> +	pull_icon.update_appearance(updates = ALL)
``updates=ALL`` is the default so I think the args should just be empty when you do so. But this is update_icon so it should be ``update_appearance(UPDATE_ICON)``

2023-06-16 01:23 UTC, JohnFulpWillard requested changes
You have all instances of update_icon set to ``update_appearance(ALL)``, which is wrong, it should be UPDATE_ICON

2023-06-16 01:24 UTC, JohnFulpWillard commented on code/_onclick/hud/screen_objects.dm
> +/atom/movable/screen/inventory/update_appearance(updates = ALL)
We should never be overwriting update_appearance at all, this should still be update_icon

2023-06-16 01:24 UTC, tattax commented
> You have all instances of update_icon set to `update_appearance(ALL)`, which is wrong, it should be UPDATE_ICON

not necessarily, no

many items configure overlays and whatnot in update_appearance

2023-06-16 01:27 UTC, JohnFulpWillard commented
> many items configure overlays and whatnot in update_appearance

That's wrong, it should be in ``update_overlays()``, which is part of UPDATE_ICON

2023-06-16 01:27 UTC, tattax commented
> That's wrong, it should be in `update_overlays()`, which is part of UPDATE_ICON

exactly

2023-06-18 23:45 UTC, cuackles approved these changes

2023-06-19 03:14 UTC, JohnFulpWillard commented on code/__DEFINES/layers.dm
> +#define GAS_PIPE_HIDDEN_LAYER 2.35 //layer = initial(layer) + piping_layer / 1000 in atmospherics/update_appearance(updates = ALL) to determine order of pipe overlap
this comment seems done accidentally

2023-06-19 03:14 UTC, JohnFulpWillard commented on code/_onclick/hud/alert.dm
> +	if(length(GLOB.roundstart_station_borgcharger_areas))
Is this feature already in or are you adding it here?
Also remove the text from the desc since it's replaced with this.

Same for the other cell alerts

2023-06-19 03:27 UTC, tattax commented on code/__DEFINES/layers.dm
> +#define GAS_PIPE_HIDDEN_LAYER 2.35 //layer = initial(layer) + piping_layer / 1000 in atmospherics/update_appearance(updates = ALL) to determine order of pipe overlap
i mean it works as a link since it got updated anyways

2023-06-19 03:28 UTC, tattax commented on code/_onclick/hud/alert.dm
> +	if(length(GLOB.roundstart_station_borgcharger_areas))
good call

2023-06-30 04:30 UTC, JohnFulpWillard commented on code/_onclick/hud/lavaland_elite.dm
> +	pull_icon.update_appearance(updates = ALL)
erhm this should still be updating just icon

2023-07-13 04:03 UTC, closed without merging

2023-07-16 17:39 UTC, ktlwjec0 commented
i think it broke pancake stacking but id have to double check, i put a cinnamon pancake on another earlier and it just acted as if the second one never existed