Mirage drive buff
yogstation13/Yogstation pull request #19325
Opened 2023-06-18 07:33 UTC by LazennG

# Document the changes in your pull request

mirage drive felt shitty for its price so i decided to buff it a bit to what i felt was more worth it.
- the cooldown you get from landing near others is done differently now, halving it per nearby person to encourage crowd diving
- maximum cooldown is checked before applying the normal cooldown reduction from landing near people now
- oriented windows don't fuck with the drive anymore so using it on the shuttle is possible 
- people in-between you and the destination get dizzy for 5 seconds and spin
- if there's somebody on the destination turf, an attack on them will happen dealing 3 times the travel distance in brute damage with 10 AP, with the minimum base damage being 15 and cap being 30. the attack has a cooldown of 5 seconds
- users can now bring people with them in conga fashion

https://github.com/yogstation13/Yogstation/assets/58535870/bfa4453d-3518-4711-a8e7-75e011b3edb6

# Wiki Documentation
https://wiki.yogstation.net/wiki/Syndicate_Items
For the mirage drive just add a part to the description about being able to inflict an attack to somebody on the destination that gets more powerful with the distance traveled. oh also about how the attack has a 5 second cooldown.

# Changelog

:cl:  
rscadd: Added mirage drive attack
tweak: tweaked mirage drive cd stuff
/:cl:

2023-06-24 18:19 UTC, solwashere commented on code/modules/uplink/uplink_items.dm
>  	desc = "An experimental device created in an attempt to replicate the properties of bluespace. Utilizing coils with unique properties, the mirage drive is able to generate \
```suggestion
	desc = "An experimental device created as a byproduct of research into faster than light travel. Utilizing magnetic coils, the mirage drive is able to generate \
```

2023-06-24 18:19 UTC, solwashere commented on code/modules/uplink/uplink_items.dm
> +	kinetic energy and use it in a way that moves the user to their destination at a speed comparable to teleportation, so long as an unobstructed path between the two exists."
```suggestion
	kinetic energy and use it in a way that moves the user to their destination at a speed comparable to teleportation, so long as an unobstructed path between user and the target exists."
```

2023-06-27 21:35 UTC, azzzertyy commented
should it not be "the user and the target" instead of "user and the target"

2023-06-28 06:31 UTC, Moltijoe requested changes

2023-06-28 06:31 UTC, Moltijoe commented on code/game/objects/items/devices/miragedrive.dm
> +			sleep(0.1 SECONDS)
sorry, i'm supposed to kill you if you put sleep inside of a loop
you're gonna need to split it into procs and use addtimer

2023-06-28 06:31 UTC, Moltijoe commented on code/game/objects/items/devices/miragedrive.dm
> +		sleep(0.2 SECONDS)
here too

2023-06-28 06:31 UTC, Moltijoe commented on code/game/objects/items/devices/miragedrive.dm
> +		sleep(0.1 SECONDS)
and here, though this one shouldn't be so hard

2023-07-01 06:32 UTC, Moltijoe approved these changes

2023-07-01 06:32 UTC, merged