Taking mats out of lathes requires ORM access, which most jobs have anyways
yogstation13/Yogstation pull request #19336
Opened 2023-06-19 10:45 UTC by ynot01

# Document the changes in your pull request

ORM can no longer be raided by unauthorized hoodlums

Jobs that have **do not** have access:
- Artist
- Assistant
- Brig Physician
- Chaplain
- Clerk
- Clown
- Curator
- Lawyer
- Mime
- Network Admin
- Paramedic
- Psychiatrist
- Tourist

# Changelog

:cl:  
tweak: ORM access now applies to protolathe mineral access as well. Lower tier jobs are now forbidden from taking minerals out.
/:cl:

2023-06-19 11:18 UTC, neeshacark commented
time to add ORM access to my access request as assistant.

can you give everyone skeleton crew orm access at least?

also rip pirates

2023-06-19 12:20 UTC, Aquizit commented
From this list the ones I can see getting access them are as such:

Brig phys/paramedic - if doctors have it then why not these two?

Chaplain/clerk/clown - These players build things often enough for chapel/shop/pranks.

Network admin - has been said already

Overall this feels unnecessary.

2023-06-19 14:25 UTC, UltraBigRat commented
I see no real point in this? unless theyre already an antag theres no real reson to take out random mats, unless you are actually doing something, this feels more like   arbitrary restrictions on jobs that could actually use the mats. Alot of the rp jobs like artist could use  mats to build stuff, along with other jobs like chaplain and curator performing renovations. And network admin often will be building stuff aswell.

This seems only useful for preventing pirates and to a lesser extent wizards and nukies emptying mats. Which at that point just make it so you need a crew id to take them out, instead of adding arbitrary id locks to a bunch of jobs for no reason.

2023-06-19 16:30 UTC, Addust commented
no

2023-06-19 17:54 UTC, tattax commented on code/game/mecha/mech_fabricator.dm
> +			balloon_alert(usr, "No access!")
balloon alerts use lowercase
```suggestion
			balloon_alert(usr, "no access!")
```

2023-06-19 18:08 UTC, TheRyeGuyWhoWillNowDie commented
???
If this is supposed to make the pirate ore yoink less viable, there's a button on the ORM interface that the AI can push to do this already, all this does is screw over 13 jobs that often times do need materials to build stuff. Adding ID locking to protolathes is like the pinnacle of hugbox.

2023-06-19 21:01 UTC, JohnFulpWillard requested changes
Any job that has access to a Techfab should also have access to the ORM

2023-06-19 21:01 UTC, JohnFulpWillard commented on code/modules/research/machinery/_production.dm
> +			return 0
```suggestion
			balloon_alert(usr, "no access!")
			return FALSE
```

2023-06-20 00:14 UTC, ynot01 commented
> Any job that has access to a Techfab should also have access to the ORM

out of scope or something c:

2023-06-20 08:48 UTC, KingSuperBOB commented
This feels more like an ided because someone went and stole mats

2023-06-20 11:23 UTC, JohnFulpWillard commented
> out of scope or something c:

It isn't, you're fixing the ORM access so you should fix the jobs who are supposed to have it too. Any job with techfab access should have ORM access since they both allow you to pull mats out.

2023-06-20 11:36 UTC, closed without merging