[BOX] Ports permabrig from Citadel who ported it from TG (i think).  Some minor changes.
yogstation13/Yogstation pull request #19404
Opened 2023-06-25 05:34 UTC by neeshacark

# Document the changes in your pull request

Today for his first big project, Cark drags permabrig kicking and screaming from Citadel, who I believe ported it from TG before TG changed theirs again (to multiz which haha no).  Bends a portion of the overhauled port bow maint airlock to allow for space.  Expands brig phys and interrogation room slightly to take up some extra space.  Thanks to GenericDM for doing some of the atmos piping for my lazy ass.

![image_2023-06-24_223443255](https://github.com/yogstation13/Yogstation/assets/44718209/4bd346f4-0b18-4086-81a8-e15fb8381d97)

# Wiki Documentation

permabrig page will likely need an image update

# Changelog

:cl:  cark, genericdm
mapping: ports permabrig from citadel/tg for box
/:cl:

2023-06-25 05:38 UTC, neeshacark commented
FUUUUUUUUUUUUUUUUUUUU

2023-06-25 05:55 UTC, neeshacark commented
ok it compiles now

2023-06-25 11:51 UTC, ktlwjec0 commented
shuttered windows around the outside?

2023-06-25 15:54 UTC, neeshacark commented
> shuttered windows around the outside?

im not sure what you mean by this

2023-06-25 22:20 UTC, ktlwjec0 commented
> > shuttered windows around the outside?
> 
> im not sure what you mean by this

check the windows around the rest of the station, they are shuttered as they are next to space

2023-06-26 01:13 UTC, neeshacark commented
> > > shuttered windows around the outside?
> > 
> > 
> > im not sure what you mean by this
> 
> check the windows around the rest of the station, they are shuttered as they are next to space

if you mean the clear emergency shutters that deploy when windows are broken, as far as I can tell those are included as part of the window spawner

2023-06-26 03:16 UTC, neeshacark commented
wait fuck i used the wrong kind of window spawner aaaaaaaaaaaaaa

2023-06-26 03:18 UTC, neeshacark commented
i blame genericDM

2023-06-27 16:45 UTC, Aquizit requested changes
Looks solid, don't see any major mistakes.

![image](https://github.com/yogstation13/Yogstation/assets/70451213/0efd2c2f-c53f-4272-9677-039acf3d8ad7)
These need to be changed to just space though and not nearstation -- we only use that for tiles with lattice in it here

2023-06-27 17:07 UTC, neeshacark commented
> Looks solid, don't see any major mistakes.
> 
> ![image](https://user-images.githubusercontent.com/70451213/249224860-0efd2c2f-c53f-4272-9677-039acf3d8ad7.png) These need to be changed to just space though and not nearstation -- we only use that for tiles with lattice in it here

leftovers from when I was originally messing with putting lattices n catwalks out there in a few different ways, didnt remove them after. will fix

2023-06-27 17:31 UTC, Aquizit approved these changes

2023-06-27 17:31 UTC, merged