Nerfs ranged holoparasites into the GROUND (I said I would do it!) (Mqiib hates fun!!!)
yogstation13/Yogstation pull request #19401
Opened 2023-06-25 04:14 UTC by Mqiib

Ok lets be real, infinite ammo guns are stupid. Infinite ammo guns that do decent damage are also stupid. Infinite ammo guns that do decent damage, are fired by an auto-turret attached to your ass, and have really high AP all while leaving your hands free to do whatever else you want are extra special stupid. As such, they no longer have quite as infinite ammo. Also now they need to care about potential too hahaha

Each shot uses 5 ammo. Maximum ammo is determined by potential (5 + 5*potential, max 30). Charge rate is determined by speed ([1,3,4,6,7] per ~2 seconds). This means the holoparasite at max speed can, when out of ammo, fire at about .7 shot per second, or 1 shot per 1.4 seconds. This is a 3.5x increase in fire delay when out of ammo. Goodbye infinite super high DPS, so long spraying down a hallway constantly forever. Hopefully.

This is clearly an ided pr and not something that has been talked about for a while.
# Document the changes in your pull request

Ranged holoparasites now have a regenerating magazine of ammo. Max ammo based on potential, regen speed based on speed.

# Wiki Documentation

Ranged holoparas have ammo. See breakdown above.

# Changelog

:cl:  

tweak: Ranged holoparasites now have a regenerating magazine to draw upon for firing their stupid crystals
tweak: Ranged holoparasites now actually care about potential
/:cl:

2023-06-25 13:08 UTC, ynot01 commented
consider https://github.com/yogstation13/Yogstation/pull/19324

2023-06-25 13:13 UTC, ynot01 requested changes
Status updates very slowly (~every 5 seconds) there needs to be a better indicator of such a crucial and rapidly changing stat

2023-07-09 18:02 UTC, Therandomhoboo commented
Ranged holoparsite already makes the user not be able to used ranged. This is just genuinely the most ided thing

2023-07-10 01:51 UTC, Mqiib commented
Closing till I can figure out how to do overlay stuffs because codering is hard :(((((

2023-07-10 01:51 UTC, closed without merging