3 new and cool escape shuttles
yogstation13/Yogstation pull request #19430
Opened 2023-06-26 20:11 UTC by airlines7

# Document the changes in your pull request
Tired of always seeing the same 5 shuttles? Well now you can see 7 of the same shuttle!
I made 3 new escape shuttles to spice up the boredom of seeing the box shuttle (our beloved).

##Octa Prototype Shuttle
A cool doughnut shaped shuttle with (perceived) larger size
In reality its a little smaller than the box shuttle, 130~ walk-able tiles.
![image](https://github.com/yogstation13/Yogstation/assets/98609667/afcce0f9-cfaf-4ac1-b799-330e3ee50fe6)

##O.C.K. Emergency Shuttle
Maints on steroids as a shuttle. OSHA approved spacecraft. 250~ walk-able tiles not taking the crates into account.
![image](https://github.com/yogstation13/Yogstation/assets/98609667/b6032f2e-cba9-4972-b785-3c1e1b207c89)

##Droni Fedora
###The drone mafia's flagship 
180~ walk-able tiles
the drones are player controlled and have the lawset of the following. There is also a bardrone and barmaid also.
1. Be loyal to members of the organization.
2. Be rational.
3. Be a member of the team. 
4. Have class. Show hospitality to others unless they don't show class.

![image](https://github.com/yogstation13/Yogstation/assets/98609667/fd31e06e-7380-4c09-b097-e0e6baf8b877)

There is also a cat named Booze with 45000 hp, she's the toughest "mob" out there.
![image](https://github.com/yogstation13/Yogstation/assets/98609667/c2c33c22-7730-46db-abf6-ae2b235fc43d)

# Wiki Documentation

Drone mafia lore
Backstories of the escape shuttles if we do that IDK.

# Changelog

:cl:  Airlines7
rscadd: The drone mafia is now a thing
rscadd: 3 new emergency shuttles.

/:cl:

2023-06-26 23:07 UTC, ynot01 commented
> Octa Prototype Shuttle

Not a mapper but having lights inside of windows is a big 👎

2023-06-26 23:09 UTC, ynot01 commented
> Droni Fedora

This is going to be an admin nightmare, no thank you

2023-06-27 05:57 UTC, airlines7 commented
> This is going to be an admin nightmare, no thank you
 Fine, I'll make my OWN mafia with Tommy guns and fedoras!

2023-06-28 02:50 UTC, ynot01 commented
I would much rather have an emag shuttle that just spawns random guns for the crew to have than have neutral-antags that will invariably gun down the crew every round with OP weapons

2023-07-01 01:24 UTC, Aquizit requested changes
Couple things:

![image](https://github.com/yogstation13/Yogstation/assets/70451213/c3641818-30d3-4bac-a112-01eb21004aab)
This just does not look good. Would prefer walls to be continuous and not just tiles that touch diagonally.

![image](https://github.com/yogstation13/Yogstation/assets/70451213/5bfe519f-5660-4c42-9628-740e26d537b3)
This is going to kill a lot of people.

![image](https://github.com/yogstation13/Yogstation/assets/70451213/bd695235-0d4c-4304-980c-e14e2319dc01)
Assuming the Cargo Airlock button is supposed to open the blast doors in the main area, it doesn't work. 

Receiving advice about the mafia shuttle, emag shuttles are dangerous -- but it is the nature of the shuttle itself that is dangerous, not necessarily items on it. I'd say the drones are fine with a lawset that they can mess with those who break the rules, but having guns lying around isn't necessarily a good feel.

2023-07-01 23:26 UTC, airlines7 commented
![image](https://github.com/yogstation13/Yogstation/assets/98609667/e063754e-1951-4c07-8173-c8ebc78a2691)
Octa more rectangular now.

![image](https://github.com/yogstation13/Yogstation/assets/98609667/c3eacc6e-0abb-47d4-b675-846a7595020b)
Don't know if you want me to add doors to these, but I'll figure something out if you want me to, walled off one door.

- Fixed the Cargo doors not working, my B on missing an underscore on the id.
- Drone mafia is snowlfaked and pacified, guns are removed. They are currently invincible, but that can easily be changed if desired.
- their laws require assailants of them to be heckled, they shouldn't do any violence. The also now have the drone rule set text when spawned in.
![image](https://github.com/yogstation13/Yogstation/assets/98609667/b686baf8-77b1-421f-a7c2-e7d349590891)

2023-07-08 16:46 UTC, Aquizit commented
Since it's an emag shuttle, the drones can do a little harm if you want them to -- maybe like stun prods for people who break the rules or some shit I dunno. But they don't need to be completely harmless *if* you want to keep the shuttle emagged. If you want to keep them pacified we can remove the emag requirement if no other dangerous stuff is involved with that shuttle.

2023-07-10 04:24 UTC, airlines7 commented
I guess I can unpacify them, just not give them guns or anything. I'll also add they should not enter CC until end of round so they don't b-line to the test area.

2023-07-10 12:09 UTC, Aquizit commented
Yeah something like that does a bunch of stam damage or just to beat people with who break the rules. Stuff that couldn't kill too fast.

As for the CC thing shouldn't be an issue as I think if it's like the bar shuttle it doesn't pop the balloon until the shuttle is in transit.

2023-07-10 12:35 UTC, ynot01 commented
> I'll also add they should not enter CC until end of round so they don't b-line to the test area.

All IC rules are abandoned the moment the round ends, this makes no difference

2023-07-10 13:29 UTC, airlines7 commented
nah the shuttle sentience balloon pops like 2 minute before it goes to the station, they have a chance to go to the testing area and steal a pulse rifle or something. I'll figure out what weapon to give them in a few.

2023-07-10 14:11 UTC, airlines7 commented
found out pacified drones can stun time to do that

2023-07-11 00:16 UTC, Aquizit requested changes
![image](https://github.com/yogstation13/Yogstation/assets/70451213/151a5563-e7a9-4f1e-8015-42c97ea7d9ce)
Buttons are in the wall, should be on an adjacent tile and pixel shifted into the wall.
---
![image](https://github.com/yogstation13/Yogstation/assets/70451213/f6281e37-c510-4fda-8830-cd4ed1fc834b)
Missing a flash in the brig at least. Up to you if you want to also have one outside the bridge as is common in most shuttles.
---
Mafia shuttle overall needs an Emergency Shuttle Console somewhere, as every shuttle has it so a hijacker can emag/early launch. Plus if crew actually wants/needs to.

2023-07-11 02:18 UTC, airlines7 commented
> Buttons are in the wall, should be on an adjacent tile and pixel shifted into the wall.
👌

> Missing a flash in the brig at least. Up to you if you want to also have one outside the bridge as is common in most shuttles.
👌

> Mafia shuttle overall needs an Emergency Shuttle Console somewhere, as every shuttle has it so a hijacker can emag/early launch. Plus if crew actually wants/needs to.
Has one, it just looks stupid is all, I can change it to a normal computer if you'd like.
![image](https://github.com/yogstation13/Yogstation/assets/98609667/dc32cb7a-6836-4de9-a6a8-931f619cf7f7)

2023-07-11 03:32 UTC, Aquizit approved these changes

2023-07-11 03:32 UTC, Aquizit commented
Maps are fine.

2023-07-11 03:47 UTC, JohnFulpWillard commented on code/datums/shuttles.dm
> +	 Just be careful, if you don't show class they might heckle you. Canoli not incuded."
```suggestion
	description = "I'm gonna make you an offer you can't refuse, the drone mafia has offered their 'services' to shuttle the crew. \
		Just be careful, if you don't show class they might heckle you. Canoli not incuded."
```

2023-07-11 03:47 UTC, JohnFulpWillard commented on code/datums/shuttles.dm
> +	The higher ups complain this shuttle is very \"\ meta\"\ and \"\ increases greytide levels\"\ whatever that means."
```suggestion
	description = "The Overnight Cargo-transport K-Class is an OSHA compliant shuttle complete with rails and warning lines to protect her crew from the cargo they are transporting. \
		Seats and a brig space have been retrofitted to help on its current mission of saving you from the station. \
		The higher ups complain this shuttle is very \"\ meta\"\ and \"\ increases greytide levels\"\ whatever that means."
```

2023-07-11 03:47 UTC, JohnFulpWillard commented on code/datums/shuttles.dm
> +	While experimental, it offers great views of outside and decently stocked emergency and medical supplies."
```suggestion
	description = "Nanotrasen's experimental shuttle utilizing a unique shape to manipulate reality for a percieved larger shuttle in a smaller package. \
		While experimental, it offers great views of outside and decently stocked emergency and medical supplies."
```

2023-07-21 21:06 UTC, JohnFulpWillard approved these changes

2023-07-21 21:07 UTC, merged