adds a couple new emotes that i wish we had
yogstation13/Yogstation pull request #19486
Opened 2023-07-01 15:04 UTC by thegoldencat413

# Document the changes in your pull request
adds an emote for tilting your head confusedly, a growl emote for being angry, and a throwing up emote for when you're sick, i guess. The vomit one seems kind of abusable but i made it so that it stuns you and doesnt affect your hunger level or purge chemicals, so maybe it's okay.

thanks a bunch to waterpig and sapphicoverload for the help
# Wiki Documentation
N/A
# Changelog

:cl:  
rscadd: Added three new emotes.

/:cl:

2023-07-01 15:08 UTC, Majkl-J requested changes

2023-07-01 15:08 UTC, Majkl-J commented on code/modules/mob/living/carbon/emote.dm
> +		L.vomit(0, FALSE, FALSE, 1, FALSE, VOMIT_TOXIC, TRUE, FALSE, 0)
This is prettier and easier to read

```suggestion
		L.vomit(lost_nutrition = 0, stun = FALSE, message = FALSE, purge_ratio = 0)
```

2023-07-05 02:58 UTC, ynot01 requested changes
The furry bait emotes should be restricted to simple animals

2023-07-07 16:44 UTC, thegoldencat413 commented
was originally gonna be polys only but then I realized that anyone can do those emotes

also the tilting your head thing doesn’t have anything to do with animals I believe Tg has it and it’s one of the things I appreciated

2023-07-08 00:04 UTC, Moltijoe requested changes

2023-07-08 00:04 UTC, Moltijoe commented on code/modules/mob/living/emote.dm
> +
i'm gonna be real with you chief, if someone growled at me in real life, i'd think they're either a bit touched in the head, or a furry.

2023-07-10 12:09 UTC, closed without merging