clerk can now access service protolathe on all maps
yogstation13/Yogstation pull request #19494
Opened 2023-07-02 11:31 UTC by azzzertyy

# Document the changes in your pull request
as title

# Changelog
:cl:  
tweak: Clerk can now access service lathe
/:cl:

2023-07-02 14:48 UTC, Aquizit approved these changes
I thought that stupid space thing between strong/fastdmm was fixed grrrr...

Anyway it's fine just wait the 24hr hold period.

2023-07-02 14:52 UTC, azzzertyy commented
> I thought that stupid space thing between strong/fastdmm was fixed grrrr...
> 
> Anyway it's fine just wait the 24hr hold period.

i wouldnt know i dont update software

2023-07-04 18:20 UTC, ToasterBiome requested changes
revert spaces

2023-07-04 18:42 UTC, ToasterBiome approved these changes

2023-07-08 16:47 UTC, merged