Makes fishing less cbt
yogstation13/Yogstation pull request #19518
Opened 2023-07-03 21:08 UTC by ToasterBiome

# Document the changes in your pull request

- You have a static 14.29% chance to lose whatever was on the line.
- You can no longer fish up "nothing" 
- Bait is now consumed at a 1 / 2 + bait power / 6 rate.

# Changelog

:cl:  
tweak: you now have a 14.29% chance to lose whatever was on the line while fishing
tweak: you can no longer fish up "nothing"
tweak: bait is consumed at a slower rate
/:cl:

2023-07-03 23:23 UTC, ynot01 requested changes

2023-07-03 23:23 UTC, ynot01 commented on yogstation/code/game/objects/items/fishing/rods.dm
> +	fishing_turf.cut_overlay(bobber_down)
Use truthy logic like you did above

2023-07-03 23:44 UTC, azzzertyy commented
THE FISH IS REAL!!!!!

2023-07-08 01:43 UTC, cuackles approved these changes

2023-07-08 03:54 UTC, YashinHak commented
The PR we need but don't deserve.

2023-07-08 11:28 UTC, ynot01 approved these changes

2023-07-08 11:28 UTC, merged