Removes some incorrect capitalization where I saw them
yogstation13/Yogstation pull request #19530
Opened 2023-07-05 01:02 UTC by JohnFulpWillard

# Document the changes in your pull request

names of objs aren't supposed to be capitalized because they look weird when examining them.
Ex: ``They are wearing a Head of Security's Belt``.

There's a lot of wrong varedits that do this and it's a shame, but this is mostly just what I found in code.

# Changelog

:cl:  
spellcheck: Removed a lot of incorrectly capitalized names in things.
/:cl:

2023-07-07 13:58 UTC, Marmio64 commented on code/game/objects/items/holy_armours.dm
> +	name = "black Ttmplar chaplain battle armor"
accidental spelling error addition

2023-07-08 16:54 UTC, Aquizit approved these changes
The very limited map stuff in this is fine.

2023-07-10 22:54 UTC, ToasterBiome requested changes
proper names and abbreviations should at least stay capitalized

2023-07-24 16:27 UTC, Aquizit approved these changes, later dismissed
I mean yeah there's no real map shit going on here it's just A -> a

2023-07-27 23:35 UTC, closed without merging