Upgraded Borg Snack Dispenser
yogstation13/Yogstation pull request #19557
Opened 2023-07-07 06:04 UTC by Runian

# Document the changes in your pull request
[This is a port from Skyrat.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11941)

Upgrades or gives medical, peacekeeper, and service cyborgs the ability to give better snacks. This replaces their medical's lollipop/icecream dispenser and peacekeeper's cookie dispenser. Snacks include: bacon, cloth cookies, normal cookies, and lollipops.

This has zero emag/hacked functionality.

This upgrade can be printed for 1-sheet worth of glass and 1-sheet worth of metal at an exosuit fabricator and can be given to medical, peacekeeper, and service cyborgs. Costs 50 power per use.

Throwing:
![thrower](https://github.com/yogstation13/Yogstation/assets/30399783/a7bb9d90-7156-42cd-b981-3655703772bc)

# Spriting
"odd cookie" (left) and "strip of bacon" (right)
![image](https://github.com/yogstation13/Yogstation/assets/30399783/59d672ea-bb46-4af8-9a46-b54dfc6b510e)

# Wiki Documentation
Add this to [Cyborg Upgrades](https://wiki.yogstation.net/wiki/Guide_to_robotics#Cyborg_Upgrades) at guide to robotics.
# Changelog

:cl:  
rscadd: A cyborg upgrade can printed to give medical, peacekeeper, and service cyborgs the ability to dispense or throw a higher variety of foods to accommodate the dietary needs of other species.
/:cl:

2023-07-07 20:12 UTC, ToasterBiome requested changes
spelling error + add a cooldown to this. Cant wait for 50,000 items on the ground to be annoying.

2023-07-07 20:12 UTC, ToasterBiome commented on code/game/objects/items/robot/robot_items.dm
> +	desc = "Has the ability to automatically print many differnt forms of snacks. Now Lizard approved!"
differnt

2023-07-07 21:59 UTC, Runian commented on code/game/objects/items/robot/robot_items.dm
> +	desc = "Has the ability to automatically print many differnt forms of snacks. Now Lizard approved!"
Donezo.

2023-07-08 00:01 UTC, ToasterBiome requested changes
use actual cooldowns, look for COOLDOWN_DECLARE to see how it's used

2023-07-08 01:29 UTC, ToasterBiome approved these changes

2023-07-15 00:02 UTC, ynot01 requested changes
Remove the old treat fabricator (/obj/item/borg/lollipop, /obj/item/rsf/cookiesynth) and replace it with this one but limiting options for snacks (by proc or by subtype). Also add gumballs. No sense in having 3 different types of snack dispensers.

2023-07-17 00:27 UTC, ynot01 approved these changes

2023-07-17 04:19 UTC, ynot01 commented on code/game/objects/items/robot/robot_items.dm
> +	if(snack && istype(snack, /obj/item/reagent_containers/food/snacks/icecream))
why twice?

2023-07-17 04:34 UTC, Runian commented on code/game/objects/items/robot/robot_items.dm
> +	if(snack && istype(snack, /obj/item/reagent_containers/food/snacks/icecream))
Forgot to remove.

2023-07-17 05:45 UTC, ynot01 approved these changes

2023-07-24 03:54 UTC, merged