You can now change the freezer/heater mode on the thermomachine interface
yogstation13/Yogstation pull request #19574
Opened 2023-07-08 11:02 UTC by warface1234455

* port https://github.com/tgstation/tgstation/pull/55345
You can now change the freezer/heater mode on the thermomachine interface instead decontrust and screwdriver it

https://github.com/yogstation13/Yogstation/assets/89688125/5396ee37-83cb-463c-baa7-1c6f1daa6bc8

# Document the changes in your pull request
You can now change the freezer/heater mode on the thermomachine interface

# Wiki Documentation
You can now change the freezer/heater mode on the thermomachine interface

# Changelog

:cl:  
rscadd: You can now change the freezer/heater mode on the thermomachine interface
rscdel: You can no longer use screwdriver on freezer/heater board to change mode
/:cl:

2023-07-08 11:03 UTC, athena413 commented
atmos techs should be forced to suffer with trial and error (or mhelp) when trying to figure out how to make a heater

2023-07-08 11:10 UTC, warface1234455 commented
> atmos techs should be forced to suffer with trial and error (or mhelp) when trying to figure out how to make a heater

lol

2023-07-08 16:59 UTC, Aquizit approved these changes
Singular map change thing fine

2023-07-12 19:56 UTC, ToasterBiome requested changes
make the button not have all that weird spacing

2023-07-12 20:00 UTC, ShoziOffical commented
> make the button not have all that weird spacing

that was old video i forgot to update i already fixed it lemme get the pic

2023-07-12 20:18 UTC, warface1234455 commented
![image](https://github.com/yogstation13/Yogstation/assets/89688125/809cac23-344a-41f0-824b-2707d1160885)

![image](https://github.com/yogstation13/Yogstation/assets/89688125/ba69419a-5343-42a4-a44f-ec8170321440)

2023-07-12 20:21 UTC, ToasterBiome approved these changes

2023-07-12 20:21 UTC, merged