New Steal Objective: AI Upload board
yogstation13/Yogstation pull request #19604
Opened 2023-07-10 01:00 UTC by Runian

# Document the changes in your pull request
The AI Upload board is now a steal objective. Considering that they aren't mass printable due to #6764 and that this is an important board, it makes sense for this to be a steal objective. It has a difficulty of 3 which is on-par with reflective vest.

:cl:  
rscadd: The AI Upload board is now something that the Syndicate wants to steal.
/:cl:

2023-07-10 01:11 UTC, athena413 commented
Holy shit yes.

Suggestion: Increase difficulty to 5 (its very valuable)

Also

Restrict AT LEAST netmin from getting the objective, and probably Station Engineer as well since they are able to get very very close to the board with a lot more ease

2023-07-10 01:51 UTC, Runian commented
I've upped the difficulty to 5. I also restricted it so that the Chief Engineer and the Research Director can't get it since the former has the access (to the airlock) and the latter has the authority (as the caretaker of the AI). 

> Holy shit yes.
> 
> Suggestion: Increase difficulty to 5 (its very valuable)
> 
> Also
> 
> Restrict AT LEAST netmin from getting the objective, and probably Station Engineer as well since they are able to get very very close to the board with a lot more ease. Atmos tech, maybe, as well, but they don't have access to tech storage outside of lowpop.

I'd have to restrict 6 jobs total if I wanted to follow that which is kind of much: Network Admin, Station Engineer, Atmospheric Technician (lowpop), Roboticist, Scientist (lowpop), and Geneticist (lowpop). I am more-or-less matching it to how other theft objectives decide who can get it. For example, full plasma tank excludes everyone that can directly access a plasma tank and can essentially legally carry it. The same goes for slime extract objective, though it does not exclude the Roboticist (who is locked behind a normal glass window).

2023-07-10 01:56 UTC, athena413 commented
> I'd have to restrict 6 jobs total if I wanted to follow that which is kind of much: Network Admin, Station Engineer, Atmospheric Technician (lowpop), Roboticist, Scientist (lowpop), and Geneticist (lowpop). I am more-or-less matching it to how other theft objectives decide who can get it. For example, full plasma tank excludes everyone that can directly access a plasma tank and can essentially legally carry it. The same goes for slime extract objective, though it does not exclude the Roboticist (who is locked behind a normal glass window).

Scientist roboticist and geneticist would have trouble accessing it quietly most rounds. I say netmin because they have a minor amount of authority over the AI, station engineer because they have direct access to tech storage with little suspicion _on top of_ ready access to hardsuits to break in via space. Atmos tech the same, but with more trouble since they don't have direct access to tech storage, but do have a fire axe to break the window in. Honestly though, it's probably fine, just an easier objective (but still not _literally free_).

2023-07-10 02:47 UTC, Runian commented
I'll exclude the Signal Admin as the compromise. I think a different PR should be opened to adjust all the excluded jobs for the steal objectives at the same time so it is all consistent.

2023-07-10 05:44 UTC, neeshacark commented
im pretty positive you can still print them, i recall doing it a couple months ago

2023-07-10 08:12 UTC, Runian commented
> im pretty positive you can still print them, i recall doing it a couple months ago

#6764

2023-07-11 21:13 UTC, neeshacark commented
> > im pretty positive you can still print them, i recall doing it a couple months ago
> 
> #6764

yes im aware that pr exists and im telling you that im pretty confident i printed them literally months ago and thats from 2019

2023-07-11 21:53 UTC, Runian commented
> > > im pretty positive you can still print them, i recall doing it a couple months ago
> > 
> > 
> > #6764
> 
> yes im aware that pr exists and im telling you that im pretty confident i printed them literally months ago and thats from 2019

Please show proof that you can currently print out AI Upload boards (and Cyborg Upload boards) as I am also confident that these boards cannot be printed.

2023-07-12 19:50 UTC, ToasterBiome approved these changes

2023-07-12 19:50 UTC, ToasterBiome requested changes

2023-07-12 19:50 UTC, ToasterBiome commented on code/game/gamemodes/objective_items.dm
> +	name = "an AI Upload board."
```suggestion
	name = "an AI upload board."
```

2023-07-12 19:58 UTC, ToasterBiome approved these changes

2023-07-12 19:58 UTC, merged