[BOX] Completely overhauls lawyer and detective offices, moves detective office to the other side of EVA.
yogstation13/Yogstation pull request #19651
Opened 2023-07-13 17:51 UTC by neeshacark

# Document the changes in your pull request

This PR completely overhauls both the law and detective offices, moving detective office a bit to allow him to have a backroom for his gear and surgeries.  Makes his office cozy and adds a fireplace.  Lawyers get individual offices for themselves.  Maint behind eva is adjusted to allow for these changes.

This is good because detective is not *technically* full security, and in its current location the detective office is rarely trafficked by anyone except criminals and security.  This means that in the majority of rounds, the detective is left alone unless someone needs him to click on something with a scanner once (assuming the hos doesnt just steal the dets spare scanner and do it themself).

By moving it to a highly trafficked hall, my hope is that more people will interact and roleplay with the detective, and also in hopes that the new location serve to make people think of detective less as a 'secoff but with a ballistic gun'

Lawyers get their own space, with a curtain between their offices they may open or close at their choosing.  This will allow some space, and let lawyers choose whether or not they want to have a conjoined law firm or work individually as prosecution and defense (i had this happen a few rounds ago and it was lovely and part of the reason for this pr)

# Wiki Documentation

Map image updates required

# Changelog

:cl:  cark
mapping: This is a mapping change
/:cl:

2023-07-13 17:52 UTC, neeshacark commented
forgot to do image here you go
![image_2023-07-13_105213823](https://github.com/yogstation13/Yogstation/assets/44718209/c05bf4c4-3fbf-40ff-b8e0-ebc3cfeab3c2)

2023-07-13 21:05 UTC, neeshacark commented
redid law offices because people complained
![Uploading image_2023-07-13_140549759.png…]()

2023-07-19 20:01 UTC, neeshacark commented
grrrr stop disliking and not saying why

2023-07-19 21:24 UTC, Aquizit requested changes
Not sure how I feel about this overall, as removing 3 maint rooms feels fairly significant. That little area of maint can be fairly busy so taking so much of it out might be an issue, not sure.

But, I still need to review so:
![image](https://github.com/yogstation13/Yogstation/assets/70451213/38fb6ee7-f1ea-45d4-95f6-2237ef0e522b)
This button seems shifted too far.

![image](https://github.com/yogstation13/Yogstation/assets/70451213/6754252c-183f-4f22-869b-41d9171357da)
Trim from old det door into maint.

new det office needs a fire alarm

2023-07-19 21:53 UTC, neeshacark commented
> Not sure how I feel about this overall, as removing 3 maint rooms feels fairly significant. That little area of maint can be fairly busy so taking so much of it out might be an issue, not sure.
> 
> But, I still need to review so: ![image](https://user-images.githubusercontent.com/70451213/254714465-38fb6ee7-f1ea-45d4-95f6-2237ef0e522b.png) This button seems shifted too far.
> 
> ![image](https://user-images.githubusercontent.com/70451213/254714548-6754252c-183f-4f22-869b-41d9171357da.png) Trim from old det door into maint.
> 
> new det office needs a fire alarm

This spot used to be the psych office, I think over that we only lost one more room and it was a 3x3.  Will fix issues.

2023-07-21 21:12 UTC, Aquizit approved these changes

2023-07-21 21:12 UTC, merged