[dnm] SSMetrics
yogstation13/Yogstation pull request #19719
Opened 2023-07-18 02:54 UTC by alexkar598

# Document the changes in your pull request

Records performance data on the game
Heavily inspired by @AffectedArc07's code in ParadiseSS13/Paradise#16549

2023-07-18 02:54 UTC, alexkar598 commented
![image](https://github.com/yogstation13/Yogstation/assets/25136265/5358fdca-1590-4eb2-b8f8-dae0ba8ba8ff)
![image](https://github.com/yogstation13/Yogstation/assets/25136265/3cfed997-1a56-45c2-a846-61407f82e184)

2023-07-20 01:36 UTC, adamsong requested changes
Pls no spam message_admins

2023-07-20 01:36 UTC, adamsong commented on code/controllers/subsystem/metrics.dm
> +		message_admins(data)
```suggestion
```

2023-07-26 16:43 UTC, adamsong requested changes, later dismissed
Update rust_g.dll

2023-07-27 04:46 UTC, adamsong approved these changes

2023-07-27 04:47 UTC, adamsong commented
"all should be good now" - alexkar

2023-07-28 04:51 UTC, ToasterBiome approved these changes

2023-07-28 05:16 UTC, merged