Clockwork Weapons Tweak
yogstation13/Yogstation pull request #19714
Opened 2023-07-17 03:59 UTC by RG4ORDR

Clockies are in need of some love, this love is something I've been antagonizing over for weeks to do.
All clockie weapons received some form of a buff, these buffs are relatively minor but they should put them on parity with other weapons that the crew can obtain as many clockie weapons simply did not deal the same amount of damage nor wound fairly.

:cl:  
tweak: Clockie weapons
**Spear**
- Wound Bonus of 10 
Sharp pointy stick but it doesn't wound people?  Already has decent damage and is defacto Clockie mainweapon

**Longsword:**
- 18 from 15 damage
- EMP cooldown reduced from 20 to 10 seconds
Extra damage for some added punch, EMP reduced down to 10 seconds so the weapon can be used in fights in a more reliable manner. It's one of it not their own defense against mechs.

**Battlehammer**
- 18 from 15 damage
- Wound bonus of 10
Wound bonus was added because despite this weapon being able the most useful, it only knocked people back to which they'd just rush you again and again spamming disarm til you lost the hammer. No more, getting hit by this will send you back but now your legs my be broken or arms dislocated

**Clockwork Bow**
-30 from 20
I wasn't gonna really touch this but it was asked to be beefed up. It now on parity with other bow weapons including the 40 damage infinite ammo hardlight power.

/:cl:

2023-07-17 04:01 UTC, Moltijoe requested changes, later dismissed
that's not how the changelog works

2023-07-18 03:36 UTC, RG4ORDR commented
With some discussion.
**Battlehammer**
- removed the wound bonus
- Given -20 AP
- Damaged increased from 18 to 23
The hammer should be a formidable weapon, however you shouldn't be able to try and mindlessly throw yourself at a hammer user.

**Clockwork Bow**
- Damaged reduced from 30 to 20.
Rational is that even I thought this was too much. I only intended originally to give it 20 damage as it has a fast draw time,wound bonus and infinite ammo.

2023-07-18 10:14 UTC, Moltijoe requested changes
Please update the changelog

2023-07-21 04:59 UTC, Moltijoe requested changes
don't mention something in the changelog if it's being left alone
(hammer wound bonus)

2023-07-23 03:15 UTC, Moltijoe requested changes
changelog still not correct, hammer is going from 15 to 23, not 18 to 23

2023-07-23 03:24 UTC, Moltijoe commented
Balance Council:
>Leave the hammer alone for now, once the two-handed component PR gets merged it can be given that and balanced accordingly

for your reference #19365 is the PR in question

2023-07-23 15:41 UTC, RG4ORDR commented
> 

Didn't think there was a PR for this.

2023-07-24 04:26 UTC, JohnFulpWillard commented
Ok twohanded component is merged
It also doesn't really change anything since it's not a twohanded weapon
balance council can do whatever

2023-07-26 04:54 UTC, Moltijoe approved these changes

2023-07-26 04:54 UTC, merged