Removes safety straps from batons
yogstation13/Yogstation pull request #19740
Opened 2023-07-19 16:25 UTC by azzzertyy

# Document the changes in your pull request
Was made when jamie thought 1 hit batons were a good idea, now those batons no longer 1 hit, but this remains.
Removes it, probably one of the single stupidest features for everyone, antags and sec both.

# Changelog
:cl:  
rscdel: Removed safety straps
/:cl:

2023-07-19 18:16 UTC, Hislyna commented
Wasn't this a council vote? Pretty sure thisll need another council vote to revert.

2023-07-19 18:43 UTC, azzzertyy commented
> Wasn't this a council vote? Pretty sure thisll need another council vote to revert.

Dont believe so.
If it was it never would've been added, original PR was WIDELY disliked.

2023-07-19 18:45 UTC, Hislyna commented
> > Wasn't this a council vote? Pretty sure thisll need another council vote to revert.
> 
> Dont believe so. If it was it never would've been added, original PR was WIDELY disliked.

https://forums.yogstation.net/threads/vote-909-test-the-baton-changes-and-hold-a-server-vote-to-dictate-the-path-forward.25377/

2023-07-19 18:46 UTC, azzzertyy commented
> > > Wasn't this a council vote? Pretty sure thisll need another council vote to revert.
> > 
> > 
> > Dont believe so. If it was it never would've been added, original PR was WIDELY disliked.
> 
> https://forums.yogstation.net/threads/vote-909-test-the-baton-changes-and-hold-a-server-vote-to-dictate-the-path-forward.25377/

Can you find the poll that was apparently done after this?
This is a vote to test it for one week too, not a vote to keep it.

2023-07-19 18:49 UTC, Hislyna commented
> > > > Wasn't this a council vote? Pretty sure thisll need another council vote to revert.
> > > 
> > > 
> > > Dont believe so. If it was it never would've been added, original PR was WIDELY disliked.
> > 
> > 
> > https://forums.yogstation.net/threads/vote-909-test-the-baton-changes-and-hold-a-server-vote-to-dictate-the-path-forward.25377/
> 
> Can you find the poll that was apparently done after this? This is a vote to test it for one week too, not a vote to keep it.

"Test the new baton changes for 1 week (ending next tuesday evening), then release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes. The poll creation will be discussed with Mqiib in staff-council chat to ensure it's worded fairly."

It is a vote to keep it. I will try to look for the vote however.

2023-07-19 18:50 UTC, azzzertyy commented
Actually, think i've found it.
https://discord.com/channels/134720091576205312/729454483805044786/975861232370319370
It refers to something completely different.
This was not council voted on at all.

> > > > > Wasn't this a council vote? Pretty sure thisll need another council vote to revert.
> > > > 
> > > > 
> > > > Dont believe so. If it was it never would've been added, original PR was WIDELY disliked.
> > > 
> > > 
> > > https://forums.yogstation.net/threads/vote-909-test-the-baton-changes-and-hold-a-server-vote-to-dictate-the-path-forward.25377/
> > 
> > 
> > Can you find the poll that was apparently done after this? This is a vote to test it for one week too, not a vote to keep it.
> 
> "Test the new baton changes for 1 week (ending next tuesday evening), then release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes. The poll creation will be discussed with Mqiib in staff-council chat to ensure it's worded fairly."
> 
> It is a vote to keep it. I will try to look for the vote however.

I meant that the council vote was a vote to test it, not the poll.

2023-07-19 18:53 UTC, Hislyna commented
> > > > > > Wasn't this a council vote? Pretty sure thisll need another council vote to revert.
> > > > > 
> > > > > 
> > > > > Dont believe so. If it was it never would've been added, original PR was WIDELY disliked.
> > > > 
> > > > 
> > > > https://forums.yogstation.net/threads/vote-909-test-the-baton-changes-and-hold-a-server-vote-to-dictate-the-path-forward.25377/
> > > 
> > > 
> > > Can you find the poll that was apparently done after this? This is a vote to test it for one week too, not a vote to keep it.
> > 
> > 
> > "Test the new baton changes for 1 week (ending next tuesday evening), then release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes. The poll creation will be discussed with Mqiib in staff-council chat to ensure it's worded fairly."
> > It is a vote to keep it. I will try to look for the vote however.
> 
> I meant that the council vote was a vote to test it, not the poll.

" release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes."

That part of the council vote means that they made a vote which is binding under this council vote, so it will still fall under council.

2023-07-19 18:55 UTC, azzzertyy commented
> > > > > > > Wasn't this a council vote? Pretty sure thisll need another council vote to revert.
> > > > > > 
> > > > > > 
> > > > > > Dont believe so. If it was it never would've been added, original PR was WIDELY disliked.
> > > > > 
> > > > > 
> > > > > https://forums.yogstation.net/threads/vote-909-test-the-baton-changes-and-hold-a-server-vote-to-dictate-the-path-forward.25377/
> > > > 
> > > > 
> > > > Can you find the poll that was apparently done after this? This is a vote to test it for one week too, not a vote to keep it.
> > > 
> > > 
> > > "Test the new baton changes for 1 week (ending next tuesday evening), then release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes. The poll creation will be discussed with Mqiib in staff-council chat to ensure it's worded fairly."
> > > It is a vote to keep it. I will try to look for the vote however.
> > 
> > 
> > I meant that the council vote was a vote to test it, not the poll.
> 
> " release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes."
> 
> That part of the council vote means that they made a vote which is binding under this council vote, so it will still fall under council.

Yes. But i cant find any evidence that this public vote... ever happened, closest i've found is a baton change vote thats dated 2 months prior to this council vote.
Which means it should happen now, and i propose a quickfire vote for it.

2023-07-19 18:56 UTC, Hislyna commented
> > > > > > > > Wasn't this a council vote? Pretty sure thisll need another council vote to revert.
> > > > > > > 
> > > > > > > 
> > > > > > > Dont believe so. If it was it never would've been added, original PR was WIDELY disliked.
> > > > > > 
> > > > > > 
> > > > > > https://forums.yogstation.net/threads/vote-909-test-the-baton-changes-and-hold-a-server-vote-to-dictate-the-path-forward.25377/
> > > > > 
> > > > > 
> > > > > Can you find the poll that was apparently done after this? This is a vote to test it for one week too, not a vote to keep it.
> > > > 
> > > > 
> > > > "Test the new baton changes for 1 week (ending next tuesday evening), then release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes. The poll creation will be discussed with Mqiib in staff-council chat to ensure it's worded fairly."
> > > > It is a vote to keep it. I will try to look for the vote however.
> > > 
> > > 
> > > I meant that the council vote was a vote to test it, not the poll.
> > 
> > 
> > " release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes."
> > That part of the council vote means that they made a vote which is binding under this council vote, so it will still fall under council.
> 
> Yes. But i cant find any evidence that this public vote... ever happened, closest i've found is a baton change vote thats dated 2 months prior to this council vote. Which means it should happen now, and i propose a quickfire vote for it.

Sadly as per the codex, you cannot change anything that is council rulled without a council vote.

2023-07-19 18:57 UTC, azzzertyy commented
> > > > > > > > > Wasn't this a council vote? Pretty sure thisll need another council vote to revert.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Dont believe so. If it was it never would've been added, original PR was WIDELY disliked.
> > > > > > > 
> > > > > > > 
> > > > > > > https://forums.yogstation.net/threads/vote-909-test-the-baton-changes-and-hold-a-server-vote-to-dictate-the-path-forward.25377/
> > > > > > 
> > > > > > 
> > > > > > Can you find the poll that was apparently done after this? This is a vote to test it for one week too, not a vote to keep it.
> > > > > 
> > > > > 
> > > > > "Test the new baton changes for 1 week (ending next tuesday evening), then release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes. The poll creation will be discussed with Mqiib in staff-council chat to ensure it's worded fairly."
> > > > > It is a vote to keep it. I will try to look for the vote however.
> > > > 
> > > > 
> > > > I meant that the council vote was a vote to test it, not the poll.
> > > 
> > > 
> > > " release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes."
> > > That part of the council vote means that they made a vote which is binding under this council vote, so it will still fall under council.
> > 
> > 
> > Yes. But i cant find any evidence that this public vote... ever happened, closest i've found is a baton change vote thats dated 2 months prior to this council vote. Which means it should happen now, and i propose a quickfire vote for it.
> 
> Sadly as per the codex, you cannot change anything that is council rulled without a council vote.

I dont think you understand what im saying.
This council vote suggests that it would be tested for one week, and then a public vote would be held as to whether or not the change should remain.
As far as i can tell, this second vote NEVER happened.
Council did not do what they were supposed to, and the change has now remained until now, with no public vote being made.
My suggestion is to remedy this failure to comply with councils own votes by making a quickfire vote.

2023-07-19 19:00 UTC, azzzertyy commented
Council never ruled on this staying in the game.
Council ruled that a public vote will be held as to whether this should stay in the game.
This was never done.

2023-07-19 19:00 UTC, Hislyna commented
> > > > > > > > > > Wasn't this a council vote? Pretty sure thisll need another council vote to revert.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Dont believe so. If it was it never would've been added, original PR was WIDELY disliked.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://forums.yogstation.net/threads/vote-909-test-the-baton-changes-and-hold-a-server-vote-to-dictate-the-path-forward.25377/
> > > > > > > 
> > > > > > > 
> > > > > > > Can you find the poll that was apparently done after this? This is a vote to test it for one week too, not a vote to keep it.
> > > > > > 
> > > > > > 
> > > > > > "Test the new baton changes for 1 week (ending next tuesday evening), then release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes. The poll creation will be discussed with Mqiib in staff-council chat to ensure it's worded fairly."
> > > > > > It is a vote to keep it. I will try to look for the vote however.
> > > > > 
> > > > > 
> > > > > I meant that the council vote was a vote to test it, not the poll.
> > > > 
> > > > 
> > > > " release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes."
> > > > That part of the council vote means that they made a vote which is binding under this council vote, so it will still fall under council.
> > > 
> > > 
> > > Yes. But i cant find any evidence that this public vote... ever happened, closest i've found is a baton change vote thats dated 2 months prior to this council vote. Which means it should happen now, and i propose a quickfire vote for it.
> > 
> > 
> > Sadly as per the codex, you cannot change anything that is council rulled without a council vote.
> 
> I dont think you understand what im saying. This council vote suggests that it would be tested for one week, and then a public vote would be held as to whether or not the change should remain. As far as i can tell, this second vote NEVER happened. Council did not do what they were supposed to, and the change has now remained until now, with no public vote being made. My suggestion is to remedy this failure to comply with councils own votes by making a quickfire vote.

The vote was on the server itself, not the discord. I remember voting on it myself (trust me bro), but nonetheless it /should/ be archived somewhere, in which council can drag it out and confirm/deny whatever was on there. Otherwise yes, a vote should be made if it was not.

2023-07-19 19:00 UTC, azzzertyy commented
> > > > > > > > > > > Wasn't this a council vote? Pretty sure thisll need another council vote to revert.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Dont believe so. If it was it never would've been added, original PR was WIDELY disliked.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > https://forums.yogstation.net/threads/vote-909-test-the-baton-changes-and-hold-a-server-vote-to-dictate-the-path-forward.25377/
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Can you find the poll that was apparently done after this? This is a vote to test it for one week too, not a vote to keep it.
> > > > > > > 
> > > > > > > 
> > > > > > > "Test the new baton changes for 1 week (ending next tuesday evening), then release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes. The poll creation will be discussed with Mqiib in staff-council chat to ensure it's worded fairly."
> > > > > > > It is a vote to keep it. I will try to look for the vote however.
> > > > > > 
> > > > > > 
> > > > > > I meant that the council vote was a vote to test it, not the poll.
> > > > > 
> > > > > 
> > > > > " release a server poll for 1 week to gather feedback on the change, the result of which will be binding whether we keep or revert the changes."
> > > > > That part of the council vote means that they made a vote which is binding under this council vote, so it will still fall under council.
> > > > 
> > > > 
> > > > Yes. But i cant find any evidence that this public vote... ever happened, closest i've found is a baton change vote thats dated 2 months prior to this council vote. Which means it should happen now, and i propose a quickfire vote for it.
> > > 
> > > 
> > > Sadly as per the codex, you cannot change anything that is council rulled without a council vote.
> > 
> > 
> > I dont think you understand what im saying. This council vote suggests that it would be tested for one week, and then a public vote would be held as to whether or not the change should remain. As far as i can tell, this second vote NEVER happened. Council did not do what they were supposed to, and the change has now remained until now, with no public vote being made. My suggestion is to remedy this failure to comply with councils own votes by making a quickfire vote.
> 
> The vote was on the server itself, not the discord. I remember voting on it myself (trust me bro), but nonetheless it /should/ be archived somewhere, in which council can drag it out and confirm/deny whatever was on there. Otherwise yes, a vote should be made if it was not.

What? Why is a public vote being done on the game?

2023-07-19 19:03 UTC, Hislyna commented
> > The vote was on the server itself, not the discord. I remember voting on it myself (trust me bro), but nonetheless it /should/ be archived somewhere, in which council can drag it out and confirm/deny whatever was on there. Otherwise yes, a vote should be made if it was not.
> 
> What? Why is a public vote being done on the game?

Probably to get the most reach, idk I aint council

2023-07-19 19:05 UTC, azzzertyy commented
> > > The vote was on the server itself, not the discord. I remember voting on it myself (trust me bro), but nonetheless it /should/ be archived somewhere, in which council can drag it out and confirm/deny whatever was on there. Otherwise yes, a vote should be made if it was not.
> > 
> > 
> > What? Why is a public vote being done on the game?
> 
> Probably to get the most reach, idk I aint council

If anything I would argue that does the exact opposite of that. It limits the voting population to whoever is on the game currently rather than the wider playerbase. If this is true, council was being stupid in their decision making here. If so, I will still argue it should be a quickfire, but a council vote will be acceptable to, its just utterly insane that they would hold a vote on a small subset of the playerbase instead of the playerbase at large.

2023-07-19 19:15 UTC, adamsong commented
The poll has not occurred, and even if it had occurred, it would not have included this, the strap was added by the dev team independent of the council votes surrounding batons

2023-07-19 19:17 UTC, azzzertyy commented
> The poll has not occurred, and even if it had occurred, it would not have included this, the strap was added by the dev team independent of the council votes surrounding batons

![so-im-right-logan-nelson](https://github.com/yogstation13/Yogstation/assets/42524344/e4849712-8046-4da5-ac22-37d79acad48b)

2023-07-19 19:37 UTC, Hislyna commented
> > The poll has not occurred, and even if it had occurred, it would not have included this, the strap was added by the dev team independent of the council votes surrounding batons
> 
> ![so-im-right-logan-nelson](https://user-images.githubusercontent.com/42524344/254687763-e4849712-8046-4da5-ac22-37d79acad48b.gif)

Yeah poll didn't occur when it shoud've, and instead dev team did their own shiz to balance batons sooooooooooooooooooooooooooo, fun!

2023-07-19 22:16 UTC, tattax commented on code/__DEFINES/dcs/signals/signals_atom/signals_atom_movable.dm
> -#define COMSIG_MOVABLE_PRE_DROPTHROW "movable_pre_dropthrow"
why remove the signal?

2023-07-19 22:17 UTC, azzzertyy commented on code/__DEFINES/dcs/signals/signals_atom/signals_atom_movable.dm
> -#define COMSIG_MOVABLE_PRE_DROPTHROW "movable_pre_dropthrow"
not needed i dont think

2023-07-19 23:19 UTC, tattax commented on code/__DEFINES/dcs/signals/signals_atom/signals_atom_movable.dm
> -#define COMSIG_MOVABLE_PRE_DROPTHROW "movable_pre_dropthrow"
don't think it should be removed anyhow

2023-07-19 23:19 UTC, azzzertyy commented on code/__DEFINES/dcs/signals/signals_atom/signals_atom_movable.dm
> -#define COMSIG_MOVABLE_PRE_DROPTHROW "movable_pre_dropthrow"
ill add it back

2023-07-20 03:11 UTC, adamsong requested changes

2023-07-20 03:11 UTC, adamsong commented on code/modules/mob/living/carbon/carbon.dm
> -		SEND_SIGNAL(thrown_thing, COMSIG_MOVABLE_PRE_DROPTHROW, src)
why remove the signal?

2023-07-24 06:45 UTC, adamsong approved these changes
Code does as described

Awaiting HD for merge

2023-07-26 01:52 UTC, merged