[box] reinforces engineering by putting another door between the hall and the R&d consoles and lathes (plus some other stuff in there i guess)
yogstation13/Yogstation pull request #19747
Opened 2023-07-20 03:07 UTC by athena413

# Document the changes in your pull request

i am at war with the engineering greytide

foyer has been split into foyer and storage room (same area definition and apc tho)

adds a civilian console because i liked it from meta and a cyborg recharger and theres shutters inside

ce also has shutter button in their office for the storage room

moves the position of some firelocks in the engineering hallway

yeag

nothing has been removed from the foyer just moved

before

![image](https://github.com/yogstation13/Yogstation/assets/15719834/2f08bf1b-c34f-4c4e-8f9b-5496a717b755)

after

![image](https://github.com/yogstation13/Yogstation/assets/15719834/fc75ea8e-c226-4f78-8dd1-a03094069cbe)

# Spriting

n/a

# Wiki Documentation

idk one of the map location pages probably (i cant find the exact one it'd affect)

# Changelog

:cl:  
tweak: Engineering techfab and circuit printer now harder to access now in storage room inside engi foyer (cool) theres also a civilian console and borg charger to fill the space
/:cl:

2023-07-20 03:48 UTC, ToasterBiome commented
not a fan

2023-07-20 03:51 UTC, athena413 commented
> not a fan

why

2023-07-20 03:58 UTC, ToasterBiome commented
Placement is a bit odd, and it doesn’t solve the problem (you still need to beat the shit out of people and make them leave). Making atmos AND sec run through a second room is just odd. 

May I suggest killing people insyead?

2023-07-20 04:05 UTC, athena413 commented
> Placement is a bit odd, and it doesn’t solve the problem (you still need to beat the shit out of people and make them leave). Making atmos AND sec run through a second room is just odd.
> 
> May I suggest killing people instead?

unless the foyer gets expanded to encroach on the hallway and block off tech storage (i WANT to do this but like i dont think that would be merged or be good for the game) im not sure if there _is_ a better placement for the lathe

moving it deeper into engineering into like, the engine room, doesnt help much since there's still that single maint door that people can just run in and print jaws from and then leave. cant move it into atmos because yeag

unless we want to gut engineering and remove all of their tools and fancy insuls people can and will tide into engineering and you will have to beat the shit out of people and make them leave. only alternative is admins enforce higher roleplay restrictions and start banning people for it (we tried this 3 years ago it didnt work)

dont worry you still can kill people you'll have a longer window of opportunity to do it while they hack the second door

2023-07-20 04:10 UTC, GenericDM commented
extremely long window looks bad
![image](https://github.com/yogstation13/Yogstation/assets/34109002/3d0e23af-4ebb-4cc5-a707-1261b6f27f1e)

2023-07-20 04:13 UTC, athena413 commented
> extremely long window looks bad ![image](https://user-images.githubusercontent.com/34109002/254768695-3d0e23af-4ebb-4cc5-a707-1261b6f27f1e.png)

could maybe make the sec window looking down be a wall. idk i want to maintain the uhhhhhhhhhhhhhhhhhhhh visibility

2023-07-20 04:38 UTC, neeshacark commented
could do what most engis do and just put it in the hall right below and or above the tech storage

2023-07-20 04:55 UTC, athena413 commented
> could do what most engis do and just put it in the hall right below and or above the tech storage

i could put the storage area at the end of aft primary hallway and move the door to the top of the foyer but then what about maint because if i put it where the maint door is we have the same problem, but worse: from maint

2023-07-20 17:22 UTC, athena413 commented
![image](https://github.com/yogstation13/Yogstation/assets/15719834/a08ec570-bdf3-41a1-ae06-12fb0c84816e)
possible alternative

the issue with this one is that it doesnt solve the problem it just moves it to maint (where its worse because theres no rwindows to watch the tider hack in, which is faster because they WILL know the wires (they already hacked into maint to get there) and the lathe is even closer)

if i want to make this work i'd have to remove the maint below it by shoving tech storage and the lathe room down and i think that'd just kinda suck

2023-07-21 14:53 UTC, SapphicOverload commented
> ![image](https://user-images.githubusercontent.com/15719834/254959611-a08ec570-bdf3-41a1-ae06-12fb0c84816e.png) possible alternative
> 
> the issue with this one is that it doesnt solve the problem it just moves it to maint (where its worse because theres no rwindows to watch the tider hack in, which is faster because they WILL know the wires (they already hacked into maint to get there) and the lathe is even closer)
> 
> if i want to make this work i'd have to remove the maint below it by shoving tech storage and the lathe room down and i think that'd just kinda suck

Could swap the sec outpost and lathe room

2023-07-21 21:22 UTC, Aquizit requested changes
![image](https://github.com/yogstation13/Yogstation/assets/70451213/492a16a6-ce1c-4979-90ab-8b6652d4a7fb)
Too much window. I'd say since the doors are glass you can make them all walls with just a single window in the sec office to look south into that room. If you go that route (you should) add a camera into the lathe room.

Those are the only structural issues I'm seeing currently.

2023-07-21 22:07 UTC, athena413 commented
#19769 goes harder

2023-07-21 22:07 UTC, closed without merging