Fixes the canister UI
yogstation13/Yogstation pull request #19840
Opened 2023-07-24 16:26 UTC by JohnFulpWillard

# Document the changes in your pull request

New UI

![image](https://github.com/yogstation13/Yogstation/assets/53777086/3bb69045-7cb1-49c7-b4cf-0065f91e7e62)
![image](https://github.com/yogstation13/Yogstation/assets/53777086/d1349bb4-30d8-44b1-a05a-0b0f6928bfc6)

There has always had a port button on canister UIs but it was always hidden because of the pressure/Regulator/valve button, and you'd have to resize the window horizontally to find it.
This makes it actually visible to players in-game.

# Changelog

:cl:  
bugfix: Canister UIs no longer have their port hidden.
/:cl:

2023-07-24 17:39 UTC, ToasterBiome requested changes
looks a bit like shit, can you at least make the 4 even?

alternate solution is making the original one wider instead

2023-07-27 05:24 UTC, JohnFulpWillard commented
I made them all centered i thought that was good, can you give more explanation what you think is wrong w/ it?

2023-07-31 04:11 UTC, ToasterBiome commented
> I made them all centered i thought that was good, can you give more explanation what you think is wrong w/ it?

if the ui was a 2x2 grid each of those elements should be centered in their individual grids, looks weird rn

2023-08-09 20:24 UTC, MajManatee commented
I think it looks fine.

2023-08-17 01:32 UTC, ToasterBiome approved these changes

2023-08-17 01:35 UTC, merged