[Fix] Terminated ID still appear original assignment icon on sechud
yogstation13/Yogstation pull request #19857
Opened 2023-07-25 18:54 UTC by warface1234455

An assistant got ID terminated but when they wear the ID it still appear as an assistant on sechud same for other jobs

# Document the changes in your pull request
Fix terminated ID still appear original assignment icon on sechud now it will appear as unknown instead
# Spriting

# Changelog

:cl:  

bugfix: Fix terminated ID still appear original assignment icon on sechud now it will appear as unknown instead

/:cl:

2023-07-31 04:02 UTC, Moltijoe requested changes

2023-07-31 04:02 UTC, Moltijoe commented on yogstation/code/game/objects/items/cards_ids.dm
> +	else if(job == null)
```suggestion
	else if(!job)
```

2023-08-07 08:29 UTC, warface1234455 commented
@Moltijoe

2023-08-09 07:04 UTC, Moltijoe approved these changes

2023-08-09 07:05 UTC, merged