[port] instant pipe unwrench
yogstation13/Yogstation pull request #19860
Opened 2023-07-25 19:24 UTC by warface1234455

*port https://github.com/tgstation/tgstation/pull/74617

no longer have to wait 1000000000000000000000 years to remove a misplaced pipe

ps only instantly remove empty pipe

# Document the changes in your pull request
instant pipe unwrench

# Wiki Documentation

instant pipe unwrench

# Changelog

:cl:  

tweak: instant pipe unwrench
/:cl:

2023-07-25 19:49 UTC, Moltijoe requested changes

2023-07-25 19:49 UTC, Moltijoe commented on code/modules/atmospherics/machinery/atmosmachinery.dm
> +	var/time_taken = empty_pipe ? 0 : 20
Please use time defines

2023-07-26 04:56 UTC, Moltijoe approved these changes

2023-08-03 17:11 UTC, JohnFulpWillard requested changes
https://github.com/tgstation/tgstation/pull/74659

2023-08-07 08:29 UTC, warface1234455 commented
@JohnFulpWillard

2023-08-09 20:26 UTC, JohnFulpWillard approved these changes

2023-08-09 20:26 UTC, merged