Map votes can no longer be triggered after map rotation.
yogstation13/Yogstation pull request #19900
Opened 2023-07-27 23:54 UTC by N3D6

# Document the changes in your pull request

Revival of #12904. 
There is absolutely no point in having 4 maps, Box, Gax, Meta, and Asteroid if everytime a map that's not box is picked, players bitch about it and make a map vote. Not gonna argue with any boxtards on this PR

# Spriting

# Wiki Documentation

:cl:  Absolucy, stolen and revived by N3D6
tweak: mapvotes can't be triggered after map rotation
/:cl:

2023-07-28 00:11 UTC, Aquizit commented
Mixed feelings. There's typically a significant drop in players when a not-box map rolls around and a vote doesn't happen/fails.

So if they're *already* not playing when it's not box, why make it so it happens more often?

2023-07-28 00:14 UTC, N3D6 commented
> Mixed feelings. There's typically a significant drop in players when a not-box map rolls around and a vote doesn't happen/fails.
> 
> So if they're _already_ not playing when it's not box, why make it so it happens more often?

Because we as a server and a mapping team shouldn't have to cater to people who refuse to play other maps. We have the other maps for a reason. It's for them to be played, not ignored. If they don't like it, they can play somewhere else.

2023-07-28 00:18 UTC, Hislyna commented
Imagine voting for maps

2023-07-28 00:23 UTC, SomeguyManperson commented
> Mixed feelings. There's typically a significant drop in players when a not-box map rolls around and a vote doesn't happen/fails.

source?

2023-07-28 00:24 UTC, Aquizit commented
> source?

Tessa's asleep I think but I can get that data to confirm tomorrow probably.

2023-07-28 00:39 UTC, iloveloopers commented
how does this change anything? people are just gonna start map votes before shuttle leaves

2023-07-28 00:40 UTC, N3D6 commented
> how does this change anything? people are just gonna start map votes before shuttle leaves

When we ported tgui voting panel map votes were admin only for a few weeks and I hardly noticed a difference. The bad thing about that was, we still had abhorrent maps like Delta

2023-07-28 00:44 UTC, iloveloopers commented
idea: make map votes admin only and the server automatically starts a map vote after shuttle leaves station

2023-07-28 00:44 UTC, N3D6 commented
> idea: make map votes admin only and the server automatically starts a map vote after shuttle leaves station

that doesn't even solve the problem. the problem is map votes making it to where box wins all the time and no maps are picked

2023-07-28 00:45 UTC, neeshacark commented
bless

2023-07-28 00:49 UTC, iloveloopers commented
> that doesn't even solve the problem. the problem is map votes making it to where box wins all the time and no other maps are picked

if the majority wants to play box, then people shall play box, democracy

2023-07-28 00:50 UTC, N3D6 commented
> > that doesn't even solve the problem. the problem is map votes making it to where box wins all the time and no other maps are picked
> 
> if the majority wants to play box, then people shall play box, democracy

Fuck democracy. The same map being picked 11 times in a row is ridiculous. It's bland, and it's boring. If it's just gonna be box all the time we might as well just kill the other maps

2023-07-28 23:50 UTC, SomeguyManperson commented
We had a long period in the past where map votes were literally impossible and playercount did not raise or drop substantially before or after it started and was fixed

People love playing their boxxies because it lets them valid antags easier (they know where every secret antagonist base is)

2023-07-29 00:33 UTC, Reed0506 commented
if people are so set in their ways that they cannot fathom playing on a map with a different layout than box, thats their problem. i doubt most players care that much about being slightly inconvenienced. source : trust me bro

2023-07-29 04:39 UTC, Moltijoe approved these changes

2023-07-29 04:40 UTC, ToasterBiome requested changes
gonna discuss with jamie bout this

2023-07-29 05:37 UTC, athena413 commented
I'm writing this at midnight, in bed, so if this is a little incomprehensible, cry hard about it.

Here's what's going to happen if this PR gets merged:
-Many people won't see a difference.
-A vocal minority will bitch about it.
-The rest will like the change.
-And after a month or so, people stop caring.

Just like nearly every other PR ever submitted to this codebase.

The reason why people hate maps outside Box is because they aren't familiar with it, and as they are made to play the other maps, they will end up learning them.

Just because the other maps are "less maintained" **(they're NOT)** does not mean they do not have value. If you, as a head dev or lead mapper, are saying that the other maps aren't maintained and therefore don't have value, you're a fucking idiot. Just because it is less maintained does not mean it does not value to the codebase - and these new maps ARE just as maintained, due to MOST of the developers being it still are here. If it's less maintained, you FUCKING MAINTAIN IT. You TELL people to include other maps in their pull request. There are STANDARDS for a reason. Make them and enforce  them. 

Question for anyone reading to think about:
If a mapper looks at yogstation, and sees this incredible hate brigade form around ANY map that isn't box, are you then going to make a map? Why put the effort in? And if you do continue, as your map takes shape, or as your contributions to another map grow, why continue when all the talk around that map and others outside Box continue to get hate, and continue to get players and ADMINS doing EVERYTHING in their power, including outright admin abuse, in order to STAY on Box? And when the map is done, or you've reworked the entirety of, say, Meta, and you get players on your map, and the response from everybody is the SAME SHIT of people doing EVERYTHING in their power to NOT PLAY the map just because they arent familiar with it, and you can't even MAKE PEOPLE PLAY on that map, at that point, why contribute? Why do anything? What's the point?

It's not that any of these maps are bad. There was nothing wrong with playing on Pubby. Delta. Omega. Kilo. Eclipse. People don't like maps outside of Box because they hate the idea of learning, of having to adapt to something that is just slightly unfamiliar, or because they do not possess the miniscule amount of brain cells it requires to navigate a central hallway or read their map, or simply because it slows down their powergaming and validhunting. Pandering to these types of people is not worth burning out every single mapper that contributes to this codebase, and every single player who has to deal with Box Round #1000.

I think if the average 1000+ hour player can learn 15 different antags, how to best play and how to kill each and every single one of them, how to make a toxins bomb that completes all the research at once, the perfect gas mix ratio for atmospheric gas synthesis, 18 surgeries by heart, and the optimal ways to kill every single megafauna on lavaland, these players can bear to learn three extra maps. If they simply cannot fucking bear to set foot on a new station that they somehow have never seen before, the cryo sleepers are always available.

2023-07-29 13:47 UTC, TheGamerdk approved these changes

2023-08-10 18:09 UTC, MajManatee commented
> I'm writing this at midnight, in bed, so if this is a little incomprehensible, cry hard about it.
> 
> Here's what's going to happen if this PR gets merged: -Many people won't see a difference. -A vocal minority will bitch about it. -The rest will like the change. -And after a month or so, people stop caring.
> 
> Just like nearly every other PR ever submitted to this codebase.
> 
> The reason why people hate maps outside Box is because they aren't familiar with it, and as they are made to play the other maps, they will end up learning them.
> 
> Just because the other maps are "less maintained" **(they're NOT)** does not mean they do not have value. If you, as a head dev or lead mapper, are saying that the other maps aren't maintained and therefore don't have value, you're a fucking idiot. Just because it is less maintained does not mean it does not value to the codebase - and these new maps ARE just as maintained, due to MOST of the developers being it still are here. If it's less maintained, you FUCKING MAINTAIN IT. You TELL people to include other maps in their pull request. There are STANDARDS for a reason. Make them and enforce them.
> 
> Question for anyone reading to think about: If a mapper looks at yogstation, and sees this incredible hate brigade form around ANY map that isn't box, are you then going to make a map? Why put the effort in? And if you do continue, as your map takes shape, or as your contributions to another map grow, why continue when all the talk around that map and others outside Box continue to get hate, and continue to get players and ADMINS doing EVERYTHING in their power, including outright admin abuse, in order to STAY on Box? And when the map is done, or you've reworked the entirety of, say, Meta, and you get players on your map, and the response from everybody is the SAME SHIT of people doing EVERYTHING in their power to NOT PLAY the map just because they arent familiar with it, and you can't even MAKE PEOPLE PLAY on that map, at that point, why contribute? Why do anything? What's the point?
> 
> It's not that any of these maps are bad. There was nothing wrong with playing on Pubby. Delta. Omega. Kilo. Eclipse. People don't like maps outside of Box because they hate the idea of learning, of having to adapt to something that is just slightly unfamiliar, or because they do not possess the miniscule amount of brain cells it requires to navigate a central hallway or read their map, or simply because it slows down their powergaming and validhunting. Pandering to these types of people is not worth burning out every single mapper that contributes to this codebase, and every single player who has to deal with Box Round #1000.
> 
> I think if the average 1000+ hour player can learn 15 different antags, how to best play and how to kill each and every single one of them, how to make a toxins bomb that completes all the research at once, the perfect gas mix ratio for atmospheric gas synthesis, 18 surgeries by heart, and the optimal ways to kill every single megafauna on lavaland, these players can bear to learn three extra maps. If they simply cannot fucking bear to set foot on a new station that they somehow have never seen before, the cryo sleepers are always available.

far too many words. I just hate the playerbase so ya im down.

2023-08-12 19:27 UTC, ToasterBiome commented
Going with one of the other options

2023-08-12 19:27 UTC, closed without merging