Condenses syndi attachments into one kit - for 1TC or 10TC for nukies
yogstation13/Yogstation pull request #19958
Opened 2023-08-01 12:09 UTC by ynot01

# Document the changes in your pull request

It's clear to me that nukies get way more out of this than tots do, so instead of making it mega expensive for both, it will just be expensive for nukies who can afford it, while making the regular kit super affordable- Having attachments is not exactly game-winning for traitors, but there is value in the lack of camera shake and the laser sight is very cool to use.

# Changelog

:cl:  
tweak: Condensed all purchasable syndicate attachments into one kit, which is more expensive for nukies than it is for traitors.
/:cl:

2023-08-01 18:00 UTC, Marmio64 commented
10 tc is a lot for these attachments. That is the same price of a nukie buying a SMG in the first place, or just over buying 3 SMG magazines. Given a choice between 72 extra bullets (and a savings of 1 TC) or a couple of attachments that will slightly reduce recoil, I would definitely take the bullets every single time. There is also the elite hardsuit, which is 8 TC for better protection at a cheaper price, and much more. Needs a cheaper price to be a competitive option for nukies to take.

2023-08-03 15:05 UTC, MajManatee commented
I don't see why they shouldn't be 1tc for everyone.

2023-08-05 09:54 UTC, azzzertyy commented
if its 1tc for nukies itl just be an auto-buy for everyone, theres no reason not to have it in such a case, 10tc is a fair price and makes nukies weigh the value of it more, with traitors 1tc seems a LITTLE too cheap to me, id say 2 was more fair, but its not a major deal

2023-08-09 07:09 UTC, Moltijoe requested changes

2023-08-09 07:09 UTC, Moltijoe commented on code/modules/uplink/uplink_items.dm
> +	include_modes = list(/datum/game_mode/nuclear, /datum/game_mode/nuclear/clown_ops)
might wanna also return exclude_modes to null, otherwise it'll try to include and exclude the modes at the same time

2023-09-13 05:20 UTC, Moltijoe commented
reopen when you plan to continue work

2023-09-13 05:20 UTC, closed without merging