[ASTEROID] R&D Changes (RD is no longer locked in or out by their lockdown shutters)
yogstation13/Yogstation pull request #20019
Opened 2023-08-10 00:17 UTC by athena413

# Document the changes in your pull request

R&D

disposals pipes are spaghetti now though

![image](https://github.com/yogstation13/Yogstation/assets/15719834/56bd0e8b-1bd9-4bf9-b1b6-bc5641ae5f8e)

# Spriting

no

# Wiki Documentation

map images

# Changelog

:cl:  
tweak: R&D on Asteroid sucks less for the RD now
/:cl:

2023-08-10 14:44 UTC, Aquizit requested changes
New RD door needs correct trimming. Will make a deeper review later. Curious about your reasoning why move the disposals at all?

2023-08-10 15:52 UTC, athena413 commented
> New RD door needs correct trimming. Will make a deeper review later.

what even is the correct trimming

> Curious about your reasoning why move the disposals at all?

having disposals go through a wall would get me yelled at

2023-08-10 17:18 UTC, Aquizit commented
> what even is the correct trimming

Using box as the reference here this:
![image](https://github.com/yogstation13/Yogstation/assets/70451213/86ae38e3-b894-4dd1-be09-6055dfe4aad2)

instead of this
![image](https://github.com/yogstation13/Yogstation/assets/70451213/24cac186-4807-4320-a2a1-d2b953fa5871)

> having disposals go through a wall would get me yelled at

Ah, and because of the stupid mail flipper it's not something you can just hook up directly. Lame.

2023-08-10 17:35 UTC, MajManatee commented
what kinda loser RD would be in their office anyways.
(me)

2023-08-29 20:37 UTC, Aquizit commented
Stale. Will reopen upon request by the author.

2023-08-29 20:37 UTC, closed without merging