48641shuttle
yogstation13/Yogstation pull request #20030
Opened 2023-08-11 06:21 UTC by maxion12345

# Document the changes in your pull request

<!-- Remove this text and explain what the purpose of your PR is.

Adds a new emergency shuttle.

This shuttle was the one built during round 48641:
![9k2J6ac](https://github.com/yogstation13/Yogstation/assets/23666142/1fa86092-d399-44a4-8d52-97422f1e6b65)

This shuttle features a rage cage (with a generator to electrify it), a medical area, and a fully functional cargo bay. 
# Spriting
n/a
# Wiki Documentation
n/a
# Changelog

:cl:  
rscadd: Added the Crowd-Sourced Shuttle. This shuttle was built from the BYOS on round 48641
/:cl:

2023-08-11 06:24 UTC, ynot01 commented on code/datums/shuttles.dm
> +	credit_cost = 1
![image](https://github.com/yogstation13/Yogstation/assets/28408322/4de1df18-1d04-49c3-9112-b6a24696724c)

2023-08-11 06:25 UTC, maxion12345 commented on code/datums/shuttles.dm
> +	credit_cost = 1
its late ok

2023-08-11 07:16 UTC, athena413 commented
I wasnt there for it but the look of this shuttle makes me happy in a way that I cant describe

Maybe take out the spear or circular saw though, and if that console is an express supply console consider swapping it out for something else. Im fine with it but im not a maintainer or a reviewer of any kind

2023-08-11 07:32 UTC, Hislyna commented
Should make an emagged ver of it with all the cool original shiz on it too

2023-08-11 09:24 UTC, maxion12345 commented
Just realized there's no brig in this. Might need to look into further modification. If anyone has suggestions, please let me know.

2023-08-11 13:11 UTC, MajManatee commented
Not all shuttles need a brig. See: Roller dome

2023-08-11 16:59 UTC, N3D6 commented
This is epic

2023-08-11 18:08 UTC, maxion12345 commented
> Not all shuttles need a brig. See: Roller dome

Good point.

2023-08-11 18:09 UTC, maxion12345 commented
Wait did linter actually fail because I put an extra m in centcom? lmaooo

2023-08-14 04:14 UTC, JohnFulpWillard commented
Why are we adding BYOS shuttles as purchaseable shuttles doesn't that take away from the building aspect of it

2023-08-14 09:06 UTC, maxion12345 commented
> Why are we adding BYOS shuttles as purchaseable shuttles doesn't that take away from the building aspect of it

Huh? No. You are free to construct other shuttles. 

 The amount of effort put into the construction of a decent shuttle is difficult to pull off, especially if your construction efforts are hampered by antagonists or an early shuttle call. It's rare for something like this to ever actually be constructed, and it has its own unique organic construction that comes from building in-game with resources collected by you instead of being mapped out with perfect geometry on the map editor.

So, no. Adding this does not take away from the building aspect, no more then being able to buy any shuttle does. If anything, I'd hope to encourage people to attempt to replicate these rare moments where a crew pulls together to construct something unique.

2023-08-14 22:25 UTC, ynot01 approved these changes

2023-08-19 13:00 UTC, Ethan4303 requested changes
everythings good, but i'd like to see the buttons, shutters, and the blastdoor to have their ID changed instead of BYOS(shutter)/BYOS(blastdoor), but i like it

2023-08-22 20:04 UTC, Ethan4303 approved these changes
looks good

2023-08-22 20:09 UTC, merged