Radiation Anomaly: Revengeance
yogstation13/Yogstation pull request #20031
Opened 2023-08-11 13:40 UTC by warface1234455

bring back rad anomaly (Without rad goat) 

# Document the changes in your pull request
readd radiation that shoots radballs and emits radiation

# Spriting
![rad](https://github.com/yogstation13/Yogstation/assets/89688125/e26dbf77-0c01-4e40-8812-0ed060831ef7)

# Wiki Documentation
readd radiation that shoots radballs and emits radiation

# Changelog

:cl:  
rscadd: readd radiation that shoots radballs and emits radiation
/:cl:

2023-08-11 16:10 UTC, ShoziOffical commented
require test merge because my private server is no longer working

2023-08-19 12:50 UTC, Ethan4303 approved these changes
Mappings good

2023-08-20 03:48 UTC, SapphicOverload requested changes
Should probably document the map changes, and that the exotic goat crate can have radioactive goats now. Otherwise mostly fine.

2023-08-20 03:48 UTC, iamthesilly commented on code/game/objects/structures/crates_lockers/crates.dm
> +			new /mob/living/simple_animal/hostile/retaliate/goat/radioactive(loc)
Please document this

2023-08-20 03:48 UTC, iamthesilly commented on code/modules/spells/spell_types/conjure/rad_goat.dm
> +	owner.visible_message(span_notice("You see \the radiation anomaly emerges from \the [owner]."), span_notice("\The radiation anomaly emerges from your body."))
'\the' is only used where you have a variable in square brackets immediately after, otherwise just use 'the'

2023-08-22 06:44 UTC, warface1234455 commented on code/game/objects/structures/crates_lockers/crates.dm
> +			new /mob/living/simple_animal/hostile/retaliate/goat/radioactive(loc)
it wasnt documented in the previous pr anyway

2023-08-22 16:41 UTC, SapphicOverload approved these changes
Looks fine, still waiting on balance council

2023-08-23 20:03 UTC, merged