you can now normally sell sm silver to cargo instead having to wait for the bounty
yogstation13/Yogstation pull request #20060
Opened 2023-08-16 10:23 UTC by warface1234455

sm silvers take times and efforts to make and pretty dangerous to handle without care so would be a nice way to make money for cargo as you all wanted cargo dependency

# Document the changes in your pull request
you can now normally sell sm silvers to cargo
sm silvers bounty is no more

# Wiki Documentation
you can now normally sell sm silvers to cargo
sm silvers bounty is no more

# Changelog

:cl:  
tweak: you can now normally sell sm silvers to cargo
rscdel: sm silvers bounty is no more
/:cl:

2023-08-16 10:27 UTC, Majkl-J commented
Isnt it meant to be sliver?

2023-08-16 10:34 UTC, warface1234455 commented
> Isnt it meant to be sliver?

well its called by that way idk

2023-08-16 10:52 UTC, Majkl-J commented
The item is literally called (/obj/item/nuke_core/supermatter_sliver)

2023-08-16 10:54 UTC, warface1234455 commented
> The item is literally called (/obj/item/nuke_core/supermatter_sliver)

yeah

2023-08-16 11:59 UTC, Therandomhoboo commented
hugbox

2023-08-18 01:54 UTC, Moltijoe requested changes
please fix the typo

2023-08-18 15:49 UTC, SomeguyManperson commented
>adds an item specifically for the purpose of avoiding needing to interact with cargo
>makes the item interact with cargo more 
?????? make up your mind????????

2023-08-19 00:43 UTC, Moltijoe requested changes

2023-08-19 00:43 UTC, Moltijoe commented on code/modules/cargo/exports/tools.dm
> +/datum/export/supermatter_silver
Typo here too

2023-09-04 21:24 UTC, Moltijoe commented
Balance Council:
>Something of this rarity should probably stay as a bounty rather than a regular sell

2023-09-04 21:24 UTC, closed without merging