I am an agent of chaos
yogstation13/Yogstation pull request #20130
Opened 2023-08-28 02:50 UTC by Moltijoe

# Why is this good for the game
it adds a layer of mechanics that can be further developed and iterated upon
when it's disabled by everyone, there's no reason to make it better

:cl:  
rscdel: removes mood preference
/:cl:

2023-08-28 03:08 UTC, MajManatee commented
No reason not to have it.

2023-08-28 03:30 UTC, neeshacark commented
the reason not to have it is because its not a system that appeals to everyone,

2023-08-28 03:32 UTC, ToasterBiome requested changes
pretty sure there's just a config option to enable it for everyone

2023-08-28 03:40 UTC, ToasterBiome commented
> the reason not to have it is because its not a system that appeals to everyone,
> 
> 
> 
> if everyone has it off, forcing it on is a good way to just piss people off. people having it off clearly shows that the majority of people are not interested in having it - even from a roleplaying standard I don't like the idea of a system that tells me how i feel (but we aren't a roleplay server, despite what people try to insist)

Eating is not a system that appeals to everyone. Cargo is not a system that appeals to everyone. These are not good reasons to not have them in the game. In fact, with these being "forced" upon you, it creates more interesting gameplay systems by playing AROUND them in an effort to circumvent them. Don't like eating? You're drawn more towards a race that uses electricity instead. Don't like interacting with Cargo? Whoops, time to ask the bartender for Lemoline. 

With mood enabled for EVERYONE, this opens the opportunity for devs to be able to give actual bonuses, differentiate species in how they handle mood, and give complexity to a feature that sorely deserves attention.

"We are not an RP server." That's okay! We're not trying to be, and mood- enabled or not, will not change that at all. Being "told" how you feel is exactly the same as the game "tells" you you're hungry, that it "tells" you you're bleeding. These are meaningful abstractions of real life- completely independent of "role play" that enhance the game mechanically. 

Anyway my thoughts on this: I've been wanting to do this for a while. People will complain. People will shit their pants, and literally nothing will happen. They will see a little face on their UI, do almost nothing differently, and they will be okay playing the game the exact same way they have been before. Everyone else that takes care of their mood can have their benefits and their roleplay moments, but without it "globally" enabled for everyone, it's just simply not feasible to further this feature (because of "muh advantage" or something).

2023-08-28 03:55 UTC, neeshacark commented
the difference is nobody cares about eating, it takes two seconds and doesnt sometimes utterly go batshit because you did some super niche thing that makes you super depressed and now you have super slowdown. cargo isn't forced on anyone, so that's not even comparable.  and yes, with eating you can just play a race that doesnt deal with nutrition - goodie.  that's not how it'll be with mood, literally every race is affected by mood in lore - even the actual robot race.  i can't avoid the mechanic i don't like and that is bad.

i don't think it is likely that many people will contribute to mood because it is forced, because most people dont like it and nobody is going to put effort into a feature that they actively dislike.  if we want bonuses and differentiation based on species that is something that should be done before or in the same pr as forcing mood on - because doing it this way is just "it'll happen we promise" and then nobody touches it EVER and we are stuck with a crappy system that makes rounds actively less fun if you don't like the system.

i do not want a system that gives me debuffs because i ate without a table or slipped on some water, i tried mood and i absolutely hated it because all that happened was i walked around for 10 minutes and instantly became slow because it seemed every little thing i did impacted my mood negatively so I need to be smoking cigarettes or drinking alcohol (both of which will end up killing me if i do it too much)

saying that the little face on the ui is all you get is wrong when low mood slows you down. i have to actively manage this annoying ass system and if i get too sad then i go insane.  what if im in a situation where I can't maintain my mood? oh god help me theres zombies oh no i slipped let me go and cry and walk all slow because im sad :( - mood literally turns any code red situation into a nightmare because slow = dead and in a code red you are probably going to be too busy trying not to die to risk drinking a shitton of alcohol (and now you're drunk good job and good luck fighting at all) as well as smoke something and eat specific foods because raising mood seems to be nigh-impossible in most cases

2023-08-28 03:59 UTC, dcxgame commented
If you'd like mood to be contributed to, contribute to it, or use your status as a long-time coder to encourage people. If this somehow gets through it would just encourage people to revert it, or get rid of any debuffs and make it a non-issue, so that they can continue worrying about as little as possible in their round.

2023-08-28 04:34 UTC, SomeguyManperson commented
I vote we remove ate without table

2023-08-28 05:03 UTC, solwashere commented
> the difference is nobody cares about eating, it takes two seconds and doesnt sometimes utterly go batshit because you did some super niche thing that makes you super depressed and now you have super slowdown. cargo isn't forced on anyone, so that's not even comparable. and yes, with eating you can just play a race that doesnt deal with nutrition - goodie. that's not how it'll be with mood, literally every race is affected by mood in lore - even the actual robot race. i can't avoid the mechanic i don't like and that is bad.
> 
> i don't think it is likely that many people will contribute to mood because it is forced, because most people dont like it and nobody is going to put effort into a feature that they actively dislike. if we want bonuses and differentiation based on species that is something that should be done before or in the same pr as forcing mood on - because doing it this way is just "it'll happen we promise" and then nobody touches it EVER and we are stuck with a crappy system that makes rounds actively less fun if you don't like the system.
> 
> i do not want a system that gives me debuffs because i ate without a table or slipped on some water, i tried mood and i absolutely hated it because all that happened was i walked around for 10 minutes and instantly became slow because it seemed every little thing i did impacted my mood negatively so I need to be smoking cigarettes or drinking alcohol (both of which will end up killing me if i do it too much)
> 
> saying that the little face on the ui is all you get is wrong when low mood slows you down. i have to actively manage this annoying ass system and if i get too sad then i go insane. what if im in a situation where I can't maintain my mood? oh god help me theres zombies oh no i slipped let me go and cry and walk all slow because im sad :( - mood literally turns any code red situation into a nightmare because slow = dead and in a code red you are probably going to be too busy trying not to die to risk drinking a shitton of alcohol (and now you're drunk good job and good luck fighting at all) as well as smoke something and eat specific foods because raising mood seems to be nigh-impossible in most cases

idk what youre talking about, I play depressed/unstable and can get through the round just fine

2023-08-28 06:05 UTC, MajManatee commented
im consistently sad or very sad and it has zero noticable downsides

2023-08-28 08:00 UTC, DeadlyBag commented
> With mood enabled for EVERYONE, this opens the opportunity for devs to be able to give actual bonuses, differentiate species in how they handle mood, and give complexity to a feature that sorely deserves attention.

And this is exactly why i dont want mood enabled.
Its going to be turned into a minmaxxing powergame mechanic where i get a ton of bonuses for doing trivial shit like eating food, petting dogs and drinking something. Are any of the "actual bonuses" going to be anything other than statboosts?
(Hint: Its only going to be stat boosts)

Atleast we are over the delusion that mood is a RP mechanic or going to be one.
Its going to be a mechanic that will give you benefits for doing trivial and easy shit

2023-08-28 08:43 UTC, Necrosium commented
I like this, we're going to suffer together as sisters and brothers. 👍

2023-08-28 08:53 UTC, ToasterBiome commented
> > With mood enabled for EVERYONE, this opens the opportunity for devs to be able to give actual bonuses, differentiate species in how they handle mood, and give complexity to a feature that sorely deserves attention.
> 
> 
> 
> And this is exactly why i dont want mood enabled.
> 
> Its going to be turned into a minmaxxing powergame mechanic where i get a ton of bonuses for doing trivial shit like eating food, petting dogs and drinking something. Are any of the "actual bonuses" going to be anything other than statboosts?
> 
> (Hint: Its only going to be stat boosts)
> 
> 
> 
> Atleast we are over the delusion that mood is a RP mechanic or going to be one.
> 
> Its going to be a mechanic that will give you benefits for doing trivial and easy shit

Drinking a bar drink that gives you a stat bonus is exactly the same. A lot of the game can be boiled down into boosts and advantages. I honestly don't see the difference between something like "eating food another player made for a 45 second mood boost" being heresy and people NOT shitting themselves over equipping armor by pressing E (that gives a stat boost too).

Frankly I'm over the negativity about mood. Can you guys just try it and see what we have to offer for more interesting gameplay with this? Is that too much to ask? It seems like some people get off to being the most insufferable respondents to any change ever and then wonder why nobody wants to contribute to the game.

2023-08-28 09:21 UTC, TheGamerdk commented
So, I assume you’ll be taking full responsibility for maintaining and improving mood from now on?

This preferably needs work BEFORE it’s enabled for everyone.

This is also a good candidate for a server poll

2023-08-28 13:23 UTC, N3D6 commented
Not as opposed to this as I used to be but I still don’t really want it, I’d understand tming for a while though to see how people like it

2023-08-28 14:23 UTC, ThatLing commented
I spent so long getting that stupid mood enabled thing to work with new prefs

2023-08-28 15:09 UTC, Moltijoe commented
> So, I assume you’ll be taking full responsibility for maintaining and improving mood from now on?

hell no

2023-08-28 18:43 UTC, RG4ORDR commented
Hahaha.No.
Mood is optional.

I've been played many many many little RP style games over the years. Wanna know why all them either turned off food/water requirements,removed a survival systems or never used them in the first place? Because they aren't fun, they aren't good for gameplay, they dont do anything but put a system designed to inhibit players. Solo experience is different - but when you're playing with 30-50 other people it gets extremely tedious. It's never been a good mechanic in SS13 because it is designed to make players start seeking out moodlet buffs - IE high mood letting you move slightly faster, letting you heal for like 10 damage while in softcrit or even leave being critted if you dont take additional damage. It adds another cluttered object to my UI that I have to maintain.

2023-08-28 19:46 UTC, solwashere commented
Mood encourages players to leave their baby caves in order to take care of their character by doing simple tasks such as going to the bar to get a drink, talking to other people, especially those with the "friendly" trait or hanging around people who play music, or just other various small things to hopefully help get people to at least interact each other in one way or another.
While the mood system is far from perfect and is flawed, there are ways that it can be improved, and should be improved, although nobody is going to want to contribute to or fix something that only a small portion of individuals have turned on unless it's for their own benefit.

2023-08-28 20:00 UTC, TheGamerdk commented
> > So, I assume you’ll be taking full responsibility for maintaining and improving mood from now on?
> 
> hell no

Then maybe you shouldn't be forcing it on people.

2023-08-28 20:07 UTC, Moltijoe commented
> Then maybe you shouldn't be forcing it on people.

i make PRs that people are asking for, whether i support them or not is unrelated

2023-08-28 20:27 UTC, TheGamerdk commented
> > Then maybe you shouldn't be forcing it on people.
> 
> i make PRs that people are asking for, whether i support them or not is unrelated

If you don't want to support a feature, you shouldn't be promoting it. And the end of the day this is your PR, even if someone else asked you to make it.

2023-08-28 21:21 UTC, Moltijoe commented
> If you don't want to support a feature, you shouldn't be promoting it. And the end of the day this is your PR, even if someone else asked you to make it.

i never said i wouldn't support it, just that i don't plan to take full responsibility for maintaining it

2023-08-29 01:14 UTC, Moltijoe commented
![image](https://github.com/yogstation13/Yogstation/assets/108117184/d3958d11-cc65-4ab5-ba59-2a54537868b0)
so this still holds true then

2023-08-29 01:14 UTC, closed without merging