Nerfs bluespace harvester
yogstation13/Yogstation pull request #20187
Opened 2023-08-31 23:16 UTC by adamsong

# Document the changes in your pull request

Building a small room in space to farm points while flooding space with hostile mobs is likely not intended, so spawning an anomaly triggers a cooldown.

# Changelog

:cl:  
tweak: bluespace harvester now has a 10 minute cooldown after spawning a portal when not emagged
/:cl:

2023-08-31 23:24 UTC, iloveloopers commented
Can the safe levels be increased then? Or point production?

2023-09-01 06:17 UTC, warface1234455 commented
> Can the safe levels be increased then? Or point production?

I was planning on this

2023-09-02 00:49 UTC, ToasterBiome approved these changes

2023-09-02 00:50 UTC, ToasterBiome requested changes
remove the cooldown if it's emagged :)

2023-09-07 03:21 UTC, adamsong commented
> remove the cooldown if it's emagged :)

https://github.com/yogstation13/Yogstation/pull/20187/files#diff-21cb5efc1442f6844d0b0cdbb83f96d3be69a08c45708bf735e39431eb3b499aR430

2023-09-07 03:23 UTC, ToasterBiome approved these changes

2023-09-07 03:23 UTC, merged