Disables the Beach Biodome
yogstation13/Yogstation pull request #20214
Opened 2023-09-02 22:08 UTC by neeshacark

# Document the changes in your pull request

Disables the beach biodome from being spawned on Lavaland, as per title.

# Why is this good for the game?
Nobody ever uses the ghost roles here, and it takes up far too much space for a unused spot.  I seriously haven't seen anyone spawn here since like 2020.  I toyed briefly with reducing its size but it's honestly far too much of a hassle for a feature nobody will use.

# Wiki Documentation

note that it is disabled on the ruins page

# Changelog

:cl:  cark
mapping: the beach biodome no longer spawns on lavaland
/:cl:

2023-09-02 22:09 UTC, LassiH commented
isnt the biodome like broken where half the floor is just a white void

2023-09-02 22:10 UTC, neeshacark commented
> isnt the biodome like broken where half the floor is just a white void

Seems to have been fixed at some point, but it might be a one off coincidence.  If it is still a feature, that too because I have no clue how to fix it and nobody seems to care enough who does have the knowledge.

2023-09-02 22:10 UTC, azzzertyy commented
this spawner sucks and theres no interesting things that happen because of it, if this was replaced 100% by ashspawn i would be happy. its just not fun, theres nothing to do at all

2023-09-03 15:48 UTC, N3D6 commented
I wouldn’t be opposed to murdering all of the biodomes, they’re all pretty fucking useless

2023-09-04 04:18 UTC, ToasterBiome requested changes
use the ruin blacklist

2023-09-09 21:53 UTC, ToasterBiome approved these changes

2023-09-09 21:54 UTC, merged