sliding (click dragging) my way (plasma) into her dms (portable generator)
yogstation13/Yogstation pull request #20254
Opened 2023-09-06 20:26 UTC by MajManatee

# Document the changes in your pull request
Allows click dragging of fuel into generators so a borg can power generators.
as you can see this is very unique code that I didn't just steal from molti

# Why is this good for the game?
Generators are used in two situations. One, Everything is fucked and we need power now (so it would improve QOL for everyone affected) and two, we are being silly and doing shenanigans (Same reason, allowing people to be silly is a good thing).

There's no reason to lock QOL stuff arbitrarily.

# Changelog

:cl:   
tweak: generator fuel can be dragged into the generator now.
/:cl:

2023-09-06 20:33 UTC, SapphicOverload requested changes

2023-09-06 20:33 UTC, SapphicOverload commented on code/modules/power/port_gen.dm
> +	if(is_type_in_typecache(dropping, sheet_path))
You should be using istype() here since sheet_path is a typepath and not a list or cache.

2023-09-06 20:43 UTC, SapphicOverload approved these changes
Neat

2023-09-06 20:45 UTC, SapphicOverload requested changes

2023-09-06 20:45 UTC, SapphicOverload commented on code/modules/power/port_gen.dm
> +	if(istype(dropping, sheet_path))
You forgor to add an Adjacent() check

2023-09-06 20:52 UTC, MajManatee commented on code/modules/power/port_gen.dm
> +	if(istype(dropping, sheet_path))
jesus make up your mind woman

2023-09-08 15:29 UTC, SapphicOverload approved these changes

2023-09-08 15:29 UTC, merged