Cyborgs Can Be Given Pets Again
yogstation13/Yogstation pull request #20253
Opened 2023-09-06 19:10 UTC by Runian

# Document the changes in your pull request
Cyborgs can be given pet again, especially after they have buckled someone to them at least once in their existence.

# Changelog
:cl:  
bugfix: Having buckled a mob once as a cyborg no longer prevents you from getting petted ever again.
/:cl:

2023-09-06 19:59 UTC, MajManatee commented
borg mains rejoice

2023-09-07 13:50 UTC, ju45he commented
Now all we need is a cargo Borg module and we will (maybe) stop power creeping with PRs

2023-09-09 21:50 UTC, ToasterBiome requested changes
use length(bucked_mobs) instead

2023-09-13 04:23 UTC, ToasterBiome approved these changes

2023-09-13 04:23 UTC, merged