You can now point while handcuffed
yogstation13/Yogstation pull request #20259
Opened 2023-09-07 16:25 UTC by azzzertyy

# Document the changes in your pull request
as title

# Why is this good for the game?
we have all wanted this

# Changelog
:cl:  
tweak: You can now point while handcuffed
/:cl:

2023-09-07 16:26 UTC, SomeguyManperson commented
mime mains when they can't spam point

2023-09-07 16:26 UTC, azzzertyy commented
> mime mains when they can't spam point

idk how a handcuff can magically cuff your fingers together man

2023-09-07 16:30 UTC, SapphicOverload requested changes
"Why is this good for the game" section should contain an actual reason for why you think it's good for the game, also does this work with straight jackets too?

2023-09-07 16:32 UTC, azzzertyy commented
> "Why is this good for the game" section should contain an actual reason for why you think it's good for the game, also does this work with straight jackets too?

probably
do i really have to make a write up for why this is good for the game?
i'd much prefer people had their own opinions rather than i tried to convince them

2023-09-07 16:32 UTC, SapphicOverload commented
> probably do i really have to make a write up for why this is good for the game? i'd much prefer people had their own opinions rather than i tried to convince them

It can be really short, just has to be any reason at all.

2023-09-07 16:35 UTC, SapphicOverload reviewed
Good enough

2023-09-07 16:36 UTC, Therandomhoboo commented
No

2023-09-07 16:48 UTC, azzzertyy commented
> Good enough

straightjackets now prevent pointing again

2023-09-07 16:56 UTC, cuackles commented
Make it fuck up a bit the direction of the pointing cus hands tied to close

2023-09-07 17:00 UTC, azzzertyy commented
> Make it fuck up a bit the direction of the pointing cus hands tied to close

way too much effort sadly

2023-09-07 17:06 UTC, cuackles commented
> > Make it fuck up a bit the direction of the pointing cus hands tied to close
> 
> way too much effort sadly

Time to abuse my director powers to close this then  😔

2023-09-07 18:39 UTC, Hopekz commented
> > probably do i really have to make a write up for why this is good for the game? i'd much prefer people had their own opinions rather than i tried to convince them
> 
> It can be like one sentence or something, just has to be any reason at all.

You're really sounding like a secretary vs a maintainer

2023-09-08 01:53 UTC, SomeguyManperson commented
Because our playerbase clearly needs yet more ways to draw attention to themselves while handcuffed, as if scream spamming isnt enough already (and at least you can muzzle them to stop that)

2023-09-12 14:21 UTC, Moltijoe requested changes

2023-09-12 14:21 UTC, Moltijoe commented on code/modules/mob/living/living.dm
> +	var/obj/item/clothing/suit/straightjacket = src.get_item_by_slot(ITEM_SLOT_OCLOTHING)
gotta give the variable an actual name, currently it's a /obj/item/clothing/suit variable that's named straightjacket
meaning literally any /suit item will prevent pointing

2023-09-18 19:44 UTC, closed without merging

2023-09-18 19:44 UTC, azzzertyy commented
Something came up. Cant finish working on this right now.