Completely revamps Metas service, taking inspiration from /TG/
yogstation13/Yogstation pull request #20280
Opened 2023-09-09 13:01 UTC by azzzertyy

# Document the changes in your pull request
Mainly touches kitchen, parts of bar, botany, service hall and clerk's shop.

Main differences:
Clerks Shop is flipped, now it no longer faces the Least Used Corridor Ever
![image](https://github.com/yogstation13/Yogstation/assets/42524344/76af8971-7900-4920-824e-e2d92fc46832)

Kitchens design completely altered, now it no longer is a complete mess.
![image](https://github.com/yogstation13/Yogstation/assets/42524344/07ae712d-427e-4d20-bcb8-21f98bd92d17)

Service hallway moved slightly, extended and beautifed:
![image](https://github.com/yogstation13/Yogstation/assets/42524344/7c69352c-3e6a-4d13-bf4e-e0f8c386928d)

Botany has a slightly different layout, makes it more uniform:
![image](https://github.com/yogstation13/Yogstation/assets/42524344/707fbcd4-bcbc-4d0e-a554-a55725c1dac0)

# Why is this good for the game?
Before, clerks would serve directly onto one of the least used corridors on the station, meaning theyre completely out of the way and able to serve no one, The vacant office has more foot-traffic, now thats reduced.
All of kitchen was a complete nightmare of a layout, completely incomprehensible, should be easier now.
Service hallway is now nice to be in and not a weird mess.

# Changelog
:cl:  
mapping: Clerk's shop on IceMeta has been flipped
mapping: Kitchen on IceMeta has a new layout
mapping: Service Hallway on IceMeta is longer
/:cl:

2023-09-09 13:04 UTC, azzzertyy commented
oh this also fixes custodial not being connected to the grid somehow

2023-09-09 14:42 UTC, N3D6 commented
Good stuff

2023-09-09 17:15 UTC, ToasterBiome requested changes
the 2x looong hallway in service was explicitly not added because the 2xwhatever hallway looks like shit. Also the walk between botany and kitchen (for putting and getting ingredients) was also intentionally removed when we took inspiration from tg the first time. 

also warning decals should have the corners on them and they should come from the other side of the maint door too (referring to clerk office).

Overall I see the service changes as a net negative.

2023-09-09 17:26 UTC, azzzertyy commented
> the 2x looong hallway in service was explicitly not added because the 2xwhatever hallway looks like shit. Also the walk between botany and kitchen (for putting and getting ingredients) was also intentionally removed when we took inspiration from tg the first time.
> 
> also warning decals should have the corners on them and they should come from the other side of the maint door too (referring to clerk office).
> 
> Overall I see the service changes as a net negative.

idk what youre on about with the warning decals, are you talking about the image on the pr? because its out of date look at map diff

I added the service hallway because the kitchen is a weird open space without it, its ugly and annoying to work with.
I also disagree that it looks like shit, looks fine to me, TGs verison i think DOES look like shit though, but this is a very different execution.

Mapping diversity is good, we dont HAVE to have kitchen connect to botany in every map

2023-09-13 04:25 UTC, ToasterBiome requested changes
Kill all the hydro/service/kitchen changes except the kitchen layout stuff, feels like a regression. Kitchen design is nice though.

2023-09-18 19:43 UTC, azzzertyy commented
Something came up. Cant finish working on this right now.

2023-09-18 19:43 UTC, closed without merging