Clerk Shop preference & new shop
yogstation13/Yogstation pull request #20281
Opened 2023-09-09 15:12 UTC by azzzertyy

# Document the changes in your pull request
Adds a preference for clerks to choose which shop they want, just like bar (ill add this for chapel soon too)
Also adds Clerk Pod
![image](https://github.com/yogstation13/Yogstation/assets/42524344/48b1e97b-4e52-4f5e-8355-23885489b046)

# Why is this good for the game?
More variety in station layouts

# Changelog
:cl:  
rscadd: Clerks have a shop preference now
mapping New clerk shop: Clerk Pod
/:cl:

2023-09-09 21:48 UTC, ToasterBiome requested changes
can you make the red trim by the backroom door have a break in it like every other airlock with that trim

2023-09-09 22:10 UTC, azzzertyy commented
> can you make the red trim by the backroom door have a break in it like every other airlock with that trim

i guess but its not supposed to be like a regular trim but im not bothered

2023-09-10 13:43 UTC, azzzertyy commented
> can you make the red trim by the backroom door have a break in it like every other airlock with that trim

should be fine now

2023-09-10 22:31 UTC, azzzertyy commented
closed. mayswell just use other pr

2023-09-10 22:31 UTC, closed without merging