fixes some bugs the seventh iteration
yogstation13/Yogstation pull request #20293
Opened 2023-09-10 19:33 UTC by tattax

# Testing
 tested everything, working as intended

closes: https://github.com/yogstation13/Yogstation/issues/20232
closes: https://github.com/yogstation13/Yogstation/issues/20231
closes: https://github.com/yogstation13/Yogstation/issues/20260
closes: https://github.com/yogstation13/Yogstation/issues/20277

:cl:  
bugfix: fixed some bugs
/:cl:

2023-09-10 20:10 UTC, cuackles requested changes
this pr touches hats dmi, but iconbot doesnt find any changes and looking at them by hand i cannot find anything notable either, is any actual changes on that dmi? if not please remove it

2023-09-11 04:27 UTC, tattax commented
> this pr touches hats dmi, but iconbot doesnt find any changes and looking at them [...]

it got reverted in the second commit it's nothing to wrory about

2023-09-13 18:17 UTC, cuackles approved these changes

2023-09-14 07:11 UTC, SapphicOverload approved these changes

2023-09-14 07:11 UTC, merged