Redspace Thermite, thermite for traitors
yogstation13/Yogstation pull request #20348
Opened 2023-09-16 03:39 UTC by neeshacark

# Document the changes in your pull request

i don't know what im doing lol

thermite but it can melt rwalls, submitted as a draft so molti can help me work out how tf to code

# Why is this good for the game?
gives traitors more options for breaking into places other than just emagging every door

# Testing
soon

# Wiki Documentation

will need listing on the guide to chemistry

# Changelog

:cl:  cark
rscadd: redspace thermite, a thermite developed by traitors using redspace dust
/:cl:

2023-09-16 03:54 UTC, Moltijoe requested changes

2023-09-16 03:54 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
> +/datum/reagent/thermite/reaction_turf(turf/T, reac_volume)
```suggestion
/datum/reagent/thermite/redspace/reaction_turf(turf/T, reac_volume)
```

2023-09-16 03:54 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
> +
delete this entirely, it'll just take the functionality from regular thermite so there's no need to change this

2023-09-16 03:54 UTC, Moltijoe commented on code/modules/reagents/chemistry/recipes/pyrotechnics.dm
> +	results = list(/datum/reagent/redspace_thermite = 1)
```suggestion
	results = list(/datum/reagent/thermite/redspace = 1)
```

2023-09-16 04:02 UTC, Moltijoe requested changes

2023-09-16 04:02 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
> +		T.AddComponent(/datum/component/thermite, reac_volume)
```suggestion
		T.AddComponent(/datum/component/thermite, reac_volume, TRUE)
```

2023-09-16 04:23 UTC, neeshacark commented
i am the worlds most intellectual coder

2023-09-16 04:57 UTC, Moltijoe commented on code/datums/components/thermite.dm
> +		immunelist |= typecacheof(/turf/closed/wall/r_wall)
```suggestion
	if(powerful)
		resistlist |= typecacheof(/turf/closed/wall/r_wall)
	else
		immunelist |= typecacheof(/turf/closed/wall/r_wall)
```

2023-09-16 04:58 UTC, Moltijoe commented on code/datums/components/thermite.dm
> +		immunelist |= typecacheof(/turf/closed/wall/r_wall)
this is an idea that could be used for balance if needed

2023-09-16 07:11 UTC, Therandomhoboo commented
So my gripes about making stuff specifically for antags with TC (because who cares about BB's) aside I don't massively dislike it however, my concern is that for using up actual TC it feels a bit lackluster. I can buy an emag or just hack the doors open quicker and without having to wait for the wall to come down which can get myself caught. 

I think the red thermite should act faster than normal thermite because of the effects red dust does in general (increases click speed and what not for people who huff it). I think this will make Red Thermite a bit more viable to use.

2023-09-16 20:04 UTC, Marmio64 commented
> So my gripes about making stuff specifically for antags with TC (because who cares about BB's) aside I don't massively dislike it however, my concern is that for using up actual TC it feels a bit lackluster. I can buy an emag or just hack the doors open quicker and without having to wait for the wall to come down which can get myself caught.
> 
> I think the red thermite should act faster than normal thermite because of the effects red dust does in general (increases click speed and what not for people who huff it). I think this will make Red Thermite a bit more viable to use.

the redspace dust is listed as a catalyst so it only takes 1 TC to turn however much thermite you want into red thermite. Doesn't need to be any stronger, especially because after you're done making however much red thermite you want you can also extract the redspace dust to use for something else.

2023-09-20 21:22 UTC, solwashere commented
Redspace dust in lore: has properties that allows for the alteration of chemical bonds to be able to produce alternative means of already existing recipes so that agents in the field may use it to procure poisons not previously possible to make on NT made chem machines.
Redspace dust here: lol this makes explosion, funny.
I'd rather normal thermite be reworked anyways to allow for the destruction of rwalls but it is harder to make safely and takes forever to do so, longer than it'd take to just blow up a wall or deconstruct it.

2023-09-20 21:31 UTC, neeshacark commented
> Redspace dust in lore: has properties that allows for the alteration of chemical bonds to be able to produce alternative means of already existing recipes so that agents in the field may use it to procure poisons not previously possible to make on NT made chem machines. Redspace dust here: lol this makes explosion, funny. I'd rather normal thermite be reworked anyways to allow for the destruction of rwalls but it is harder to make safely and takes forever to do so, longer than it'd take to just blow up a wall or deconstruct it.

we've been using redspace dust for traitor chemistry for some time now, so...

2023-09-21 23:10 UTC, Therandomhoboo commented
> Redspace dust in lore: has properties that allows for the alteration of chemical bonds to be able to produce alternative means of already existing recipes so that agents in the field may use it to procure poisons not previously possible to make on NT made chem machines. Redspace dust here: lol this makes explosion, funny. I'd rather normal thermite be reworked anyways to allow for the destruction of rwalls but it is harder to make safely and takes forever to do so, longer than it'd take to just blow up a wall or deconstruct it.

"Gateway to traitor chemistry, want a drug to be traitor only? use this" How AZZZZ implemented this it was mainly for anything chemistry related and not just for poisons if how I'm reading what you put is correct. Plus redspace dust can make red-eye which isn't defo not a poison either so either red-eye needs reworking or the lore does.

2023-09-22 00:33 UTC, SomeguyManperson commented
Why should I buy c-4 instead of using this, since it seems like easily (and significantly cheaper) producable c-4 variant usable on _slightly_ less important stuff

2023-09-23 23:40 UTC, neeshacark commented
Honestly, this PR has been so much more trouble that it was worth.  I did it mostly to dip my toes into coding a bit and it turned into this massive situation with people complaining over stuff and having inappropriate expectations for what people should do when making PRs that can in anyway be considered to 'not make sense within lore' (any pr that adds new chems/items i guess since this PR is somehow an issue)

There will be balance changes requested of me for this PR (fair enough) but I really don't care enough to apply them when the result will still complaints over how this doesn't make sense in lore.  If this is what happens when a new feature is created that doesn't make sense to someone's perception of how this fictional world with literal wizards works - then I'm not going to bother with coding and will happily stick to mapping where there is literally almost zero way for lore to be infringed upon

2023-09-23 23:40 UTC, closed without merging