Icemoon: Seed Vault
yogstation13/Yogstation pull request #20360
Opened 2023-09-17 16:49 UTC by neeshacark

# Document the changes in your pull request

seed vault for icemoon, ripped from lavaland.

# Why is this good for the game?
more ruin for ice

# Wiki Documentation

ruin page documentation

# Changelog

:cl:  cark
mapping: icemoon seed vault is now added
/:cl:

2023-09-17 17:44 UTC, N3D6 commented
add it to the blacklist people haven’t been doing that for some reason

2023-09-22 13:08 UTC, MajManatee commented
no picture?

2023-09-23 16:40 UTC, Aquizit requested changes
![image](https://github.com/yogstation13/Yogstation/assets/70451213/cbbd7370-9d24-4ff5-b375-8851a61837f1)

Although I don't think it *needs* one I'd feel better with an outlet here instead of just the open pipe.

Also I would say put the area on the engines too instead of the mining one just as they are part of the building more or less.

2023-09-24 21:13 UTC, Aquizit approved these changes

2023-09-24 21:13 UTC, merged