Nerfs wizard taser (mjolnir)
yogstation13/Yogstation pull request #20371
Opened 2023-09-19 01:18 UTC by iloveloopers

# Document the changes in your pull request
mjolnir now only stuns for 2 seconds and has a 5 second knockdown
mjolnir now only applies a 5 second knockdown on throw hits

# Why is this good for the game?
its straight up a taser for 2 points. this thing is way too strong and unfun to play against. now you need to get in close to deal your stunlocks and has more leeway for the person receiving punishment

# Testing

worked fine on my testing

# Wiki Documentation

wiki doesn't state stun times on the hammer

# Changelog

:cl:  
tweak: Mjolnir now applies a 2 second stun and 5 second knockdown
tweak: Mjolnir no longer stuns on throw
/:cl:

2023-09-19 01:33 UTC, Marmio64 commented
mjolnir is supposed to cost 3 spellpoints and i believe it was in a pretty good state like that while keeping the same stats. It costs 2  sp because the antags PR changed all the spellbook stuff and reverted the price change back to 2.

2023-09-19 02:06 UTC, iloveloopers commented
> mjolnir is supposed to cost 3 spellpoints and i believe it was in a pretty good state like that while keeping the same stats. It costs 2 sp because the antags PR changed all the spellbook stuff and reverted the price change back to 2.

even being 3 points its insanely unfun to play against. same as smite touch. instawin buttons

2023-09-19 02:13 UTC, milk-is-cool commented
have you tested it yet

2023-09-19 02:15 UTC, iloveloopers commented
> have you tested it yet

yeah I tested it on local. works fine

2023-09-19 02:15 UTC, iloveloopers commented
can we get the balance council tag

2023-09-19 14:09 UTC, Moltijoe requested changes
instead of creating an identical proc, just add a parameter to the proc to modify it's behavior

2023-09-19 14:37 UTC, MajManatee commented
wizards aren't supposed to be fair
just shoot him

2023-09-19 14:45 UTC, iloveloopers commented
> wizards aren't supposed to be fair just shoot him

they should still be somewhat fun to play against

2023-09-19 18:38 UTC, Moltijoe requested changes
please use time defines

2023-09-20 03:09 UTC, Moltijoe requested changes
Missed one

2023-09-20 04:04 UTC, iloveloopers commented
Let people enjoy shitcode

2023-09-20 04:37 UTC, Moltijoe requested changes
Codes fine

2023-09-20 04:38 UTC, Moltijoe approved these changes
I mean this

2023-09-20 04:39 UTC, Moltijoe commented
Balance Council:
>Ided

2023-09-20 04:39 UTC, closed without merging