No more getting stuck in a Dizzy Mushroom-Hole
yogstation13/Yogstation pull request #20409
Opened 2023-09-22 21:32 UTC by Therandomhoboo

# Document the changes in your pull request

Whoever put in Hallucinogen Mushrooms & Hippie's delight without sorting out the code should be burned at a stake. I've become fully grey and aged fifty years. However, it is now fixed. I am finally a coder.

# Why is this good for the game?
Gives admins less of an headache, gives players the ability to not throw up from having a constant dizzy effect and makes me happy because I don't have to fix this anymore.

# Testing

Yes, I tested this by drinking a ton of Hippie's delight & Halluc-Mushroom and waiting for it to run out. You're welcome.

# Changelog

:cl:  

bugfix: Hallucinogen Mushroom & Hippie's delight no longer perma dizzy you

/:cl:

2023-09-22 22:20 UTC, Moltijoe requested changes

2023-09-22 22:20 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +			M.set_drugginess_if_lower(30 SECONDS)
```suggestion
			M.set_dizzy_if_lower(1 SECONDS)
			M.set_drugginess_if_lower(3 SECONDS)
```

2023-09-22 22:20 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +			M.set_drugginess_if_lower(30 SECONDS)
undocumented change otherwise

2023-09-22 22:21 UTC, Moltijoe requested changes
these too

2023-09-22 22:21 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +			M.set_drugginess_if_lower(45 SECONDS)
```suggestion
			M.set_dizzy_if_lower(2 SECONDS)
			M.set_drugginess_if_lower(4.5 SECONDS)
```

2023-09-22 22:21 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +			M.set_drugginess_if_lower(60 SECONDS)
```suggestion
			M.set_dizzy_if_lower(4 SECONDS)
			M.set_drugginess_if_lower(6 SECONDS)
```

2023-09-22 22:21 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +			M.set_drugginess_if_lower(75 SECONDS)
```suggestion
			M.set_dizzy_if_lower(6 SECONDS)
			M.set_drugginess_if_lower(7.5 SECONDS)
```

2023-09-22 22:24 UTC, Therandomhoboo commented
> these too

Done, thank you.

2023-09-24 19:51 UTC, Moltijoe approved these changes

2023-09-24 19:52 UTC, merged