Slight rewrite of gemstone flavortext
yogstation13/Yogstation pull request #20411
Opened 2023-09-23 00:15 UTC by SomeguyManperson

# Document the changes in your pull request

I said I'd do this like 2-3 times and finally got around to it, might be better might be worse

# Why is this good for the game?
It's not

# Changelog

:cl:  
tweak: stuff nobody will read has been written
/:cl:

2023-09-23 00:29 UTC, ToasterBiome requested changes

2023-09-23 00:29 UTC, ToasterBiome commented on code/game/objects/items/gems.dm
> +	desc = "A shard of crystallized stellar energy. These strange objects rarely appear spontaneously in areas of massive bluespace instaiblity. Its surface gives a light jolt to those who touch it. Des
instaiblity

2023-09-23 00:29 UTC, ToasterBiome commented on code/game/objects/items/gems.dm
> +	desc = "A brittle, strange mineral that forms from the rapidly cooling blood of a dying ash drake. Cherished by gemcutters for its faint glow and unique, soft warmth. Rumors within some mining crews
```suggestion
	desc = "A brittle, strange mineral that forms from the rapidly cooling blood of a dying ash drake. Cherished by gemcutters for its faint glow and unique, soft warmth. Rumors among some mining crews whisper of the dragon's strength being bestowed to one that wears a necklace of this amber."
```

among us reference

2023-09-23 04:54 UTC, ilikesaying commented on code/game/objects/items/gems.dm
> +	desc = "A radioactive, crystalline compound rarely found in the goldgrubs. Its soft humming is prized by ethereal musicians, and it is commonly encorporated into their gem-encrusted instruments. Wit
In material despeiration ->  In material desperation

2023-09-25 03:51 UTC, ToasterBiome approved these changes

2023-09-25 03:51 UTC, merged