Buffs all of Detective's clothing so that they have the armor values they should
yogstation13/Yogstation pull request #20472
Opened 2023-09-27 23:51 UTC by neeshacark

# Document the changes in your pull request

Buffs all the detective's under items to have the same armor as the hard-worn suit (generic det suit, same armor as sec clothes) because they didn't.

Buffs all of det's coats to have the same armor as his vest so he need not choose function over fasion

# Why is this good for the game?
being able to customize your look without having to worry about being less armored good

# Changelog

:cl:  cark
tweak: buffed detective's armor to be the values it rightfully should be
/:cl:

2023-09-27 23:56 UTC, Mqiib commented
buffs fashion

2023-09-28 00:16 UTC, iloveloopers commented
antag buff

2023-09-28 00:36 UTC, Moltijoe requested changes
remove /yogs/ from the type path and instead make them proper subtypes of the regular hat instead

2023-09-28 04:42 UTC, neeshacark commented
> remove /yogs/ from the type path and instead make them proper subtypes of the regular hat instead

this doesnt touch hats at all my good bitch

2023-09-28 17:22 UTC, Marmio64 commented
The trenchcoat seems to cover limbs as well as chest, so I don't think it should have sec vest identical values as it'd be a direct upgrade.

2023-09-29 05:34 UTC, neeshacark commented
molti offered to do it later

2023-09-29 05:34 UTC, closed without merging