adds new acid spit genetics mutation obtainable through polysmorphs
yogstation13/Yogstation pull request #20474
Opened 2023-09-28 06:32 UTC by iloveloopers

# Document the changes in your pull request

adds the new acid spit mutation obtainable only from polysmorphs, similarly to fire breath
lets you spit acid that will slowly corrode objects and clothing on players
its weak but annoying
instabillity of 70
cooldown of 18 seconds

# Why is this good for the game?
more species specific mutations is good
the mutation is really only useful for melting stuff, its impractical to use it in combat unless your enemy is naked

# Testing

tested it, works. destroys a common object in 2 shots and clothing depends on the acid armor.

# Wiki Documentation

mutation name: Acid Spit
description: "An ancient mutation derived from xenomorphs that forces the salivary glands to produce acid"
indicators: none
message: "Your saliva burns your mouth!"
how to obtain: polysmorph species
imcompatible with: none
instabillity: 70
compatible chromosomes: reinforcement, stabilizier

# Changelog

:cl:  
rscadd: New Acid Spit mutation obtainable from Polysmorphs
/:cl:

2023-09-28 06:35 UTC, neeshacark commented
instability seems a bit high for what this does tbh, isnt fire breath lower?

2023-09-28 12:34 UTC, ju45he commented
> instability seems a bit high for what this does tbh, isnt fire breath lower?

You could use this for SO fucking much. Fire breath lights em up a bit but fire extinguishers make it obsolete. Spitting corrosive acid at someone would eventually make their uniform corrode, anything in pockets belt slot ID allow are all for the taking with simple timing and with low risk should you simply use something to outrun them for a bit while you wait for their stuff to corrode.

2023-09-28 13:03 UTC, Tenn0x commented
seems a little expensive but stabilizer can be used so idk

2023-09-28 13:36 UTC, Moltijoe requested changes

2023-09-28 13:36 UTC, Moltijoe commented on code/modules/projectiles/projectile/special/neurotoxin.dm
> +		target.acid_act(acidpwr = 18, acid_volume = 25) // balanced
```suggestion
	else if(iscarbon(target))
		target.acid_act(acidpwr = 18, acid_volume = 25) // balanced
	else if(!isopenturf(target)
		target.acid_act(acidpwr = 50, acid_volume = 25) // does good damage to objects and structures
```

2023-09-28 13:36 UTC, Moltijoe commented on code/modules/projectiles/projectile/special/neurotoxin.dm
> +		target.acid_act(acidpwr = 18, acid_volume = 25) // balanced
no reason to restrict it so arbitrarily, all it needs to do is not be able to melt through the floor

2023-09-28 13:37 UTC, MajManatee commented
local man doesnt know you can use an extingusher on acid

2023-09-28 15:43 UTC, iloveloopers commented
this will probably needs buffs, it takes multiple shots to completely break a jumpsuit or door. but better weaker than overpowered

2023-09-28 16:54 UTC, Moltijoe requested changes

2023-09-28 16:54 UTC, Moltijoe commented on code/datums/mutations/fire_breath.dm
> +	projectile_type = /obj/item/projectile/bullet/acid
what is this doing in the firebreath file

2023-09-28 16:54 UTC, Moltijoe commented on code/modules/projectiles/projectile/special/neurotoxin.dm
> +	return ..()
why is this with the neurotoxin projectile rather than the acid spit projectile

2023-09-28 16:54 UTC, Moltijoe requested changes
undocumented sound addition

2023-09-28 16:55 UTC, Moltijoe requested changes

2023-09-28 16:55 UTC, Moltijoe commented on code/modules/projectiles/projectile/special/neurotoxin.dm
> +		target.acid_act(acidpwr = 50, acid_volume = 25) // does good damage to objects and structures
```suggestion
		target.acid_act( 18, 25) // balanced
	else if(!isopenturf(target))
		target.acid_act( 50, 25) // does good damage to objects and structures
```

2023-09-28 18:34 UTC, iloveloopers commented
theres no way the code isn't good now

2023-09-28 19:57 UTC, Moltijoe approved these changes
good enough

2023-09-29 01:23 UTC, iloveloopers commented
come on balance council approve my PR already!!!

2023-09-29 17:43 UTC, Moltijoe commented
Balance council:
>Reduce stability to 50 and reduce acid volume to 15
also, add a check making sure the user's mouth isn't covered when using it

2023-09-29 23:56 UTC, Moltijoe requested changes

2023-09-29 23:56 UTC, Moltijoe commented on code/datums/mutations/acid_spit.dm
> +		return FALSE
```suggestion
	if(!get_location_accessible(owner, BODY_ZONE_PRECISE_MOUTH))
		to_chat(owner, span_notice("Something is covering your mouth!"))
		return FALSE
```

2023-09-29 23:56 UTC, Moltijoe commented on code/datums/mutations/acid_spit.dm
> +	var/mob/living/carbon/spitter = owner
```suggestion
```

2023-09-30 01:38 UTC, Moltijoe requested changes
please provide a screenshot or video of it working

2023-09-30 04:05 UTC, Moltijoe requested changes

2023-09-30 04:05 UTC, Moltijoe commented on code/datums/mutations/acid_spit.dm
> +	spell_requirements = NONE
you have this line twice
```suggestion
```

2023-09-30 20:13 UTC, iloveloopers commented
https://github.com/yogstation13/Yogstation/assets/140007537/b944295b-6ba0-44a5-871a-c74cb8f815c3

2023-10-01 03:31 UTC, Moltijoe approved these changes

2023-10-08 05:21 UTC, ToasterBiome approved these changes

2023-10-08 05:21 UTC, merged