Marrow weavers and gutlunches can no longer eat robotic organs
yogstation13/Yogstation pull request #20494
Opened 2023-09-30 01:13 UTC by Moltijoe

# Why is this good for the game?
Marrow weavers can round remove ipcs because the brain is in the chest and they eat all chest organs
rather than adding a check to make sure they ignore brains, they just won't eat robotic organs, which makes more sense

:cl:  
tweak: Marrow weavers and gutlunches can no longer eat robotic organs
/:cl:

2023-10-08 05:23 UTC, ToasterBiome requested changes
pretty sure that this will make it so they infinitely try to slurp up robotic organs then stop.

2023-10-16 03:47 UTC, ToasterBiome requested changes
now test it and show me that it works properly

2023-10-16 04:04 UTC, Moltijoe commented
![image](https://github.com/yogstation13/Yogstation/assets/108117184/5ddd299f-8ea3-43c4-9284-264d936c459d)
![image](https://github.com/yogstation13/Yogstation/assets/108117184/0c94bea0-64dc-4e5a-8911-b2d09cef2123)

![image](https://github.com/yogstation13/Yogstation/assets/108117184/618cb4b0-8585-4aae-9621-251f37c6ca27)

2023-10-16 04:05 UTC, ToasterBiome approved these changes

2023-10-16 04:05 UTC, merged