You can now point while handcuffed (No one can yell at me edition)
yogstation13/Yogstation pull request #20549
Opened 2023-10-05 22:08 UTC by azzzertyy

# Document the changes in your pull request
as title

# Why is this good for the game?
small quality of life change which makes sense because cuffs dont magically prevent you from pressing E and typing "points at the airlock"
# Changelog
:cl:  
tweak: You can now point while handcuffed
/:cl:

2023-10-05 22:23 UTC, SapphicOverload requested changes

2023-10-05 22:23 UTC, SapphicOverload commented on code/modules/mob/living/living.dm
> +	var/obj/item/clothing/suit/straightjacket = src.get_item_by_slot(ITEM_SLOT_OCLOTHING)
```suggestion
	var/obj/item/clothing/suit/straightjacket/straightjacket = src.get_item_by_slot(ITEM_SLOT_OCLOTHING)
```

2023-10-05 22:36 UTC, SapphicOverload requested changes, later dismissed

2023-10-05 22:36 UTC, SapphicOverload commented on code/modules/mob/living/living.dm
> +	var/obj/item/clothing/suit/straightjacket/straightjacket = src.get_item_by_slot(ITEM_SLOT_OCLOTHING)
My bad, spelling error
```suggestion
	var/obj/item/clothing/suit/straight_jacket/straightjacket = src.get_item_by_slot(ITEM_SLOT_OCLOTHING)
```

2023-10-05 23:00 UTC, Yarinoi commented
ggrgrgrgr HOW DARE YOU this gives a NEW AVENUE FOR PRISONERS TO MESS WITH SECURITY this will destroy sec you MONSTER WHAT NEXT ARE PERMA PRISONERS GOING TO HAVE AN ARMORY FULL OF PULSE RIFLES IN PERMA

2023-10-05 23:00 UTC, azzzertyy commented
> ggrgrgrgr HOW DARE YOU this gives a NEW AVENUE FOR PRISONERS TO MESS WITH SECURITY this will destroy sec you MONSTER WHAT NEXT ARE PERMA PRISONERS GOING TO HAVE AN ARMORY FULL OF PULSE RIFLES IN PERMA

no yelling! read the title! no yelling at me edition!

2023-10-05 23:02 UTC, Yarinoi commented
> > ggrgrgrgr HOW DARE YOU this gives a NEW AVENUE FOR PRISONERS TO MESS WITH SECURITY this will destroy sec you MONSTER WHAT NEXT ARE PERMA PRISONERS GOING TO HAVE AN ARMORY FULL OF PULSE RIFLES IN PERMA
> 
> no yelling! read the title! no yelling at me edition!

oh ok sorry

ᵍᵍʳᵍʳᵍʳᵍʳ ʰᵒʷ ᵈᵃʳᵉ ʸᵒᵘ ᵗʰᶦˢ ᵍᶦᵛᵉˢ ᵃ ⁿᵉʷ ᵃᵛᵉⁿᵘᵉ ᶠᵒʳ ᵖʳᶦˢᵒⁿᵉʳˢ ᵗᵒ ᵐᵉˢˢ ʷᶦᵗʰ ˢᵉᶜᵘʳᶦᵗʸ ᵗʰᶦˢ ʷᶦˡˡ ᵈᵉˢᵗʳᵒʸ ˢᵉᶜ ʸᵒᵘ ᵐᵒⁿˢᵗᵉʳ ʷʰᵃᵗ ⁿᵉˣᵗ ᵃʳᵉ ᵖᵉʳᵐᵃ ᵖʳᶦˢᵒⁿᵉʳˢ ᵍᵒᶦⁿᵍ ᵗᵒ ʰᵃᵛᵉ ᵃⁿ ᵃʳᵐᵒʳʸ ᶠᵘˡˡ ᵒᶠ ᵖᵘˡˢᵉ ʳᶦᶠˡᵉˢ ᶦⁿ ᵖᵉʳᵐᵃ

2023-10-06 13:34 UTC, MajManatee commented
nice

2023-10-06 15:56 UTC, Moja10 commented
I agree, prisoners should be able to point, even if the handcuffs are behind them
![image](https://github.com/yogstation13/Yogstation/assets/17183762/7e5b437d-fec7-4aca-a71d-f8e328ec9785)

2023-10-06 18:31 UTC, MajManatee commented
I work in a prison and I can confirm that people can use their fingers and arms while cuffed

2023-10-15 09:28 UTC, SomeguyManperson commented
Only people this will benefit are people who have managed to get handcuffed, with the added bonus that it is "countered" by something that will get you as much flak as handcuffed shoes (which a substantial amount of people want removed)

I also don't see why we want to make not killing people as an antagonist harder, but I guess anything is worth having another tool to be an annoying shit with after being arrested

2023-10-15 11:07 UTC, Yarinoi commented
if you ask me, i dont see how pointing is any more annoying then prisoners constantly hurling the worst things that are still allowed by the server at anyone around them, plus pointing is a decently useful tool

2023-10-16 13:26 UTC, MajManatee commented
option to alt click cuffs to allow pointing by "adjusting their fit" before cuffing someone?

2023-10-24 19:04 UTC, SomeguyManperson commented
> if you ask me, i dont see how pointing is any more annoying then prisoners constantly hurling the worst things that are still allowed by the server at anyone around them,

this primarily effects mimes in terms of security, it's more harmful to antagonists who have to/want to transport a non-dead and non-unconscious person since pointing is fast, easy, and nearly impossible to prevent

> plus pointing is a decently useful tool

cuffs exist to remove tools from people. They also prevent opening access-locked doors (so someone with access to an area but is cuffed can't simply run through a few doors), and prevent climbing over tables (there IS actually framing for climbing tables while cuffed, with it penalizing your climbing speed, it just doesn't work since you can't do any channels period)

What this does is give handcuffed people a useful tool which is even harder to remove than other tools they retain i.e. speech which is countered by mute toxin and a myriad of antagonist abilities. Your only option is the strait jacket, which is awful. And no, I tested, mime's bane does not work on pointing

2023-11-13 04:36 UTC, ToasterBiome commented
Now draw her being tested

2023-11-18 03:30 UTC, JohnFulpWillard commented on code/modules/mob/living/living.dm
> +	var/obj/item/clothing/suit/straight_jacket/straightjacket = src.get_item_by_slot(ITEM_SLOT_OCLOTHING)
```suggestion
	var/obj/item/clothing/suit/straight_jacket/straightjacket = get_item_by_slot(ITEM_SLOT_OCLOTHING)
```

2023-11-28 14:30 UTC, MajManatee commented
No activity. Reopen when work continues

2023-12-01 07:43 UTC, JohnFulpWillard approved these changes

2023-12-01 07:44 UTC, merged