All lights turn red in emergency procedures
yogstation13/Yogstation pull request #20588
Opened 2023-10-10 11:57 UTC by warface1234455

# Document the changes in your pull request
Delta, Gamma and *@&!#&EPSILON*#%@ alert now make all lights turn red

# Why is this good for the game?
For immersion and make the station seems like its on actual emergency procedure

# Testing
Tested,
switched to delta/epsilon alert level, all lights turned red
switched back to normal alert level, all lights went back to normal

Tried to use fire alarm to turn off red lights on delta, didnt do that and instead it triggered firelocks, then hit the fire alarm again It opened all the firelocks and the lights still stayed red as intended

![image](https://github.com/yogstation13/Yogstation/assets/89688125/10cec3d4-8a51-4842-b2c4-0ddd2ea65849)

Shouldnt make shuttle lights go red

# Changelog

:cl:  
tweak: Delta, Gamma and *@&!#&EPSILON*#%@ alert now make all lights turn red
/:cl:

2023-10-10 12:01 UTC, solwashere commented
It would be best to test this to ensure that it doesn't break the lighting

2023-10-10 12:03 UTC, warface1234455 commented
> It would be best to test this to ensure that it doesn't break the lighting

no it doesnt break it

2023-10-10 12:07 UTC, solwashere commented
> > It would be best to test this to ensure that it doesn't break the lighting
> 
> no it doesnt break it

It would be nice to know that before it's merged

2023-10-10 12:07 UTC, warface1234455 commented
> > > It would be best to test this to ensure that it doesn't break the lighting
> > 
> > 
> > no it doesnt break it
> 
> It would be nice to know that before it's merged

mhm

2023-10-10 14:02 UTC, MajManatee commented
now we need dramatic music to play

2023-10-10 14:37 UTC, solwashere commented
> now we need dramatic music to play

https://youtu.be/XoUfsbU-wfA?si=OehmATHMuhLYgjmg

2023-10-10 15:07 UTC, warface1234455 commented
> now we need dramatic music to play

would do that if custom timer didnt exist-

2023-10-10 15:24 UTC, MajManatee commented
I was thinkin the SCP: SL music when the nuke goes off

2023-10-10 15:56 UTC, ShoziOffical commented
> I was thinkin the SCP: SL music when the nuke goes off

well yeahhhhh if the timer sync with it

2023-10-10 16:44 UTC, N3D6 commented
> > It would be best to test this to ensure that it doesn't break the lighting
> 
> no it doesnt break it

local hosting isn’t conclusive enough for these types of things

2023-10-10 16:46 UTC, warface1234455 commented
> > > It would be best to test this to ensure that it doesn't break the lighting
> > 
> > 
> > no it doesnt break it
> 
> local hosting isn’t conclusive enough for these types of things

how is it breaking lights if im using the same fire alarm proc

2023-10-10 20:48 UTC, ToasterBiome commented
> > > It would be best to test this to ensure that it doesn't break the lighting
> > 
> > 
> > no it doesnt break it
> 
> local hosting isn’t conclusive enough for these types of things

false

2023-10-10 20:49 UTC, N3D6 commented
> > > > It would be best to test this to ensure that it doesn't break the lighting
> > > 
> > > 
> > > no it doesnt break it
> > 
> > 
> > local hosting isn’t conclusive enough for these types of things
> 
> false

my source was: trust me bro
i feel like every light changing at once would probably not be light on the server

2023-10-11 07:44 UTC, azzzertyy commented
> > > > > It would be best to test this to ensure that it doesn't break the lighting
> > > > 
> > > > 
> > > > no it doesnt break it
> > > 
> > > 
> > > local hosting isn’t conclusive enough for these types of things
> > 
> > 
> > false
> 
> my source was: trust me bro i feel like every light changing at once would probably not be light on the server

Circardian Rhythm
We literally already do this ned

2023-10-11 08:18 UTC, Majkl-J commented
> > > > > > It would be best to test this to ensure that it doesn't break the lighting
> > > > > 
> > > > > 
> > > > > no it doesnt break it
> > > > 
> > > > 
> > > > local hosting isn’t conclusive enough for these types of things
> > > 
> > > 
> > > false
> > 
> > 
> > my source was: trust me bro i feel like every light changing at once would probably not be light on the server
> 
> Circardian Rhythm We literally already do this ned

And power shutdowns

2023-10-11 08:25 UTC, warface1234455 commented
> > > > > > > It would be best to test this to ensure that it doesn't break the lighting
> > > > > > 
> > > > > > 
> > > > > > no it doesnt break it
> > > > > 
> > > > > 
> > > > > local hosting isn’t conclusive enough for these types of things
> > > > 
> > > > 
> > > > false
> > > 
> > > 
> > > my source was: trust me bro i feel like every light changing at once would probably not be light on the server
> > 
> > 
> > Circardian Rhythm We literally already do this ned
> 
> And power shutdowns

yeah blackout does this just fine

2023-10-12 21:14 UTC, Addust commented
are ruins affected?

2023-10-12 23:38 UTC, warface1234455 commented
> are ruins affected?

No

2023-10-15 01:53 UTC, Moltijoe requested changes
please remove the "shuttle call during red alert" part

2023-10-15 02:52 UTC, warface1234455 commented
> please remove the "shuttle call during red alert" part

till i get a reason why

2023-10-19 06:12 UTC, warface1234455 commented on code/modules/shuttle/emergency.dm
> +
welp

2023-10-22 01:35 UTC, Moltijoe approved these changes

2023-10-22 01:35 UTC, merged