[ASTEROID] moves evac up, removes petting zoo
yogstation13/Yogstation pull request #20599
Opened 2023-10-12 03:13 UTC by ToasterBiome

# Document the changes in your pull request

Moves evac up, and gives a little garden area.

![image](https://github.com/yogstation13/Yogstation/assets/5091394/ed75fb81-fc87-4de8-acb4-b5a4d4cc38ef)

Maint is redone and arcade is moved.
![image](https://github.com/yogstation13/Yogstation/assets/5091394/d46e084d-f1f5-426d-b0f8-feb06fbce5f4)

Petting zoo is unfortunately gone, because it was way too big for it's usage (nobody used it)

This will prevent the big ass shuttles from destroying atmos, killing everyone

# Changelog

:cl:  
mapping: Moves evac up on AsteroidStation, removes petting zoo and adds small garden where evac used to be.
/:cl:

2023-10-12 04:26 UTC, neeshacark commented
idea theft smh

2023-10-12 05:04 UTC, neeshacark requested changes
![image_2023-10-11_220104938](https://github.com/yogstation13/Yogstation/assets/44718209/844f55c1-9164-4906-848f-2644d0f7b6a3)
the area here is escaping into space

![image_2023-10-11_220132351](https://github.com/yogstation13/Yogstation/assets/44718209/4532ff45-225e-409a-96ec-036f32b4e195)
the windows here should probably not be reinforced, doesnt make much sense

![image_2023-10-11_220212783](https://github.com/yogstation13/Yogstation/assets/44718209/fd6da416-bbc5-4e28-8121-fa636da71525)
the entire garden area + the small hall area lacks vents+scrubbers making repressurizing them annoying to do

![image_2023-10-11_220259542](https://github.com/yogstation13/Yogstation/assets/44718209/379108da-dfe8-485c-8a43-e4d1fb2bafa2)
this is probably leftover from me missing them when i removed a bunch but since you're editing this area anyway - nuke these firelocks under the windows here since we dont do that no more

theres also some more firelock windows over here by the vacant office though you don't have to do those for me to approve this it'd just be nice of you :)
![image_2023-10-11_220409699](https://github.com/yogstation13/Yogstation/assets/44718209/1b1da255-28cf-4394-b6b1-2cad62d8ee47)

2023-10-12 17:43 UTC, azzzertyy commented
i actually loathe this change and think the new evac is incredibly ugly and badly placed.

2023-10-12 19:02 UTC, ToasterBiome commented
> i actually loathe this change and think the new evac is incredibly ugly and badly placed.

I'd rather have evac moved up than all of engineering moved down like 15 tiles. Feel free to take a crack at it yourself and move it if you'd like.

2023-10-13 01:10 UTC, neeshacark commented
> i actually loathe this change and think the new evac is incredibly ugly and badly placed.

it looks fine and fixes the issue so

2023-10-24 02:18 UTC, neeshacark requested changes
![image_2023-10-23_191737120](https://github.com/yogstation13/Yogstation/assets/44718209/68407b4f-3649-4d60-b2c9-199f8a4745dc)
this portion still lacks vent+scrubber

![image_2023-10-23_191807959](https://github.com/yogstation13/Yogstation/assets/44718209/0e01fd9c-5586-4cf1-9760-d3d8d8bef2ac)
podbay area here is scuffed im not sure if i missed this or if its new

2023-10-28 17:24 UTC, neeshacark approved these changes

2023-10-28 17:24 UTC, merged