Gambling Hall Clerk Template
yogstation13/Yogstation pull request #20613
Opened 2023-10-13 21:59 UTC by ToasterBiome

# Document the changes in your pull request

Adds a new clerk template that's a gambling hall. Deck of cards under the shutters, Poker table under that. Some coins spawn on the table in a stack for you to use as a little boost for gambling money.

Excludes any slot machines as the interaction within should be with the Clerk, but there are some places to add some.

![image](https://github.com/yogstation13/Yogstation/assets/5091394/1fa8d8fc-0bd0-424d-bb7c-8c85b116c18c)

# Why is this good for the game?
Some more gameplay for Clerk, I've seen this transformation done multiple times to instead make Clerk a job that takes other's money through gambling (the house always wins) compared to greytiding into various places, stealing stuff, and then trying to sell it.

# Changelog

:cl:  
mapping: Gives Clerk a new template where instead of a giftshop it's a gambling hall.
rscadd: Gives coinstacks the ability to be maploaded in. 
/:cl:

2023-10-13 22:03 UTC, azzzertyy commented
nice

2023-10-14 00:06 UTC, cowbot92 commented
this is all I've ever wanted

2023-10-18 17:04 UTC, Aquizit requested changes
I think there should be at least one air alarm in the gambling hall, there's enough room on the walls for one.

Also while you're here....
![image](https://github.com/yogstation13/Yogstation/assets/70451213/d14c2e80-6be0-40b7-8a51-ae1f37f083a1)
wanna fix this? :) it's clerk_meta

2023-10-19 00:38 UTC, azzzertyy commented
> I think there should be at least one air alarm in the gambling hall, there's enough room on the walls for one.
> 
> Also while you're here.... ![image](https://user-images.githubusercontent.com/70451213/276337094-d14c2e80-6be0-40b7-8a51-ae1f37f083a1.png) wanna fix this? :) it's clerk_meta

wtf

2023-10-21 16:29 UTC, Aquizit approved these changes
map gud

2023-10-22 01:34 UTC, Moltijoe approved these changes

2023-10-22 01:34 UTC, merged