Adds shadows to gax's stairs
yogstation13/Yogstation pull request #20760
Opened 2023-10-26 20:31 UTC by azzzertyy

# Document the changes in your pull request
In line with how i've been creating stairs on other maps, looks better and more interesting with shadows on the stairs to add depth
Also adds some wideplating to showcase height.
![image](https://github.com/yogstation13/Yogstation/assets/42524344/556ad41c-6e1e-4503-8b83-21efed97a321)
![image](https://github.com/yogstation13/Yogstation/assets/42524344/b352ea67-9b96-43fd-b267-2c82aab40808)
![image](https://github.com/yogstation13/Yogstation/assets/42524344/e6a769dc-3373-4a69-b678-c1357c6f7f65)

# Why is this good for the game?
More in-line with other maps

# Testing
Doesn't need it.

# Changelog
:cl:  
mapping: Gax stairs have shadows now
/:cl:

2023-10-26 20:32 UTC, azzzertyy commented
im working on a resprite for the corner sprite because it doesnt match the gradient properly so ignore it for now

2023-11-01 03:28 UTC, ToasterBiome requested changes
Undraft when you get a new corner

2023-11-01 03:32 UTC, azzzertyy commented
> Undraft when you get a new corner

no thatl be a while

2023-11-03 02:50 UTC, ToasterBiome commented
Reopen when you get a new corner

2023-11-03 02:50 UTC, closed without merging