[PORT] Crate shelf from shiptest
yogstation13/Yogstation pull request #20809
Opened 2023-11-01 11:51 UTC by warface1234455

* port https://github.com/shiptest-ss13/Shiptest/pull/2374
You can now make crate shelf and put crates on it

# Document the changes in your pull request
You can now make crate shelf and put crates on it

# Why is this good for the game?
I believe that adding more options for organization is a good thing.
Specifically, this will ideally make players more likely to sort items into crates, rather than just dumping everything in.
# Testing
![crate](https://github.com/yogstation13/Yogstation/assets/89688125/b1532247-d1c6-457b-8137-b5274e9a0476)

# Spriting
![image](https://github.com/yogstation13/Yogstation/assets/89688125/972cfcc7-9fb7-4535-825b-634fc4a16b0f)

# Wiki Documentation
Crate shelf, can be made using 1 metal, can store 3 crates maximum

# Changelog

:cl:  
rscadd: You can now make crate shelf and put crates on it
/:cl:

2023-11-01 12:58 UTC, SapphicOverload requested changes

2023-11-01 12:58 UTC, iamthesilly commented on code/game/objects/structures/crateshelf.dm
> +/obj/structure/crate_shelf/Initialize()
```suggestion
/obj/structure/crate_shelf/Initialize(mapload)
```

2023-11-01 18:29 UTC, neeshacark commented
generic left us and made shelf :(

2023-11-01 18:41 UTC, warface1234455 commented
> generic left us and made shelf :(

Yog sad

2023-11-07 02:14 UTC, cuackles approved these changes

2023-11-11 03:05 UTC, SapphicOverload requested changes

2023-11-11 03:05 UTC, SapphicOverload commented on code/game/objects/structures/tables_racks.dm
> +	to_chat(user, "<span class='notice'>You start assembling [src]...</span>")
```suggestion
	to_chat(user, span_notice("You start assembling [src]..."))
```

2023-11-11 14:03 UTC, SapphicOverload approved these changes

2023-11-13 04:35 UTC, merged