We are past the era of Tasty Crayons (Crayon eating nerf)
yogstation13/Yogstation pull request #20813
Opened 2023-11-01 18:25 UTC by Therandomhoboo

# Document the changes in your pull request

Thanks Drake. Joking aside, it was pointed out that crayons give nutriments of 5-6u's and rainbows give 15-20u's. Which is a very good food staple that is a tiny item which can be easily stacked/stored. We shouldn't be fostering this meta and so to combat this, I've given crayons a disgust stack. Taking bites out of them gives you disgust so if you binge on them. You end up vomitting.

# Why is this good for the game?

Stops ~~drake~~ players from bypassing eating actual food by giving disgust per bite. Crayons are nasty anyway.

# Testing

Eating a full crayon usually makes the player puke, but it applies disgust per bite they take properly.

# Changelog

:cl:  

rscadd: Made taking bites of crayon give you stacks of disgust because you're eating wax and shit.

/:cl:

2023-11-01 18:28 UTC, LaOubliette commented
I will weaponize this, fool. You cant stop chemistry.

2023-11-01 18:35 UTC, 00ze-cyclone commented
Can’t you just grind it anyway? This solve pretty much nothing if so.

2023-11-01 18:36 UTC, cowbot92 commented
this dude has never eaten a delicious crayon irl

2023-11-01 18:37 UTC, Therandomhoboo commented
> I will weaponize this, fool. You cant stop chemistry.


> Can’t you just grind it anyway? This solve pretty much nothing if so.

Then they can carry it in a beaker and chug it instead of having 12 packs of 6 crayons. This just stops them stacking it more so with no effort, if they want to take time and grind them all up crack on.

2023-11-01 19:15 UTC, LassiH commented
> [EDIT] Also want to point out that as well, you're not always near a grinder or got the stuff to make one. So it means if people want to grind it instead then they have to do it beforehand or have the right materials to make a grinder. So yeah, its a win-win.

said mortar and pestle in players bag

2023-11-01 19:17 UTC, Therandomhoboo commented
> > [EDIT] Also want to point out that as well, you're not always near a grinder or got the stuff to make one. So it means if people want to grind it instead then they have to do it beforehand or have the right materials to make a grinder. So yeah, its a win-win.
> 
> said mortar and pestle in players bag

....fuck

2023-11-01 19:21 UTC, RG4ORDR commented
Im a Marine, you cannot do this.
Cultural erasure.

2023-11-01 19:24 UTC, Therandomhoboo commented
YOU CAN STILL EAT THE GOD DAMN CRAYON GUYS, I WANT TO MAKE THIS **ABUNDANTLY** CLEAR

2023-11-01 19:50 UTC, UltraBigRat commented
Remove the disgust for sec, crayoncurity meta.

2023-11-01 23:11 UTC, JohnFulpWillard reviewed
this is discouraging crayon-eaters from eating their god-given food.
security should be exempt

2023-11-01 23:28 UTC, Therandomhoboo commented
> this is discouraging crayon-eaters from eating their god-given food. security should be exempt

If balance council says sec should be exempt i'll exempt those mf-ers

2023-11-02 14:22 UTC, ThatGuyPhil commented
Maybe give them less nutriment? You can get fat from eating less than half a pack of crayons.

2023-11-02 19:26 UTC, RG4ORDR commented
Mime,Clown,Sec, and Captain should all get benefits from eating crayons.
simple as.

2023-11-05 11:09 UTC, ynot01 approved these changes

2023-11-06 20:30 UTC, Therandomhoboo commented
I am putting this on hold, for the time being until a quirk is done for the fucking marines.

2023-11-06 22:59 UTC, Therandomhoboo commented
There you fucking go, its in the works.

2023-11-07 00:51 UTC, Therandomhoboo commented
It is all finished, it all works.

2023-11-07 00:53 UTC, Moltijoe requested changes

2023-11-07 00:53 UTC, Moltijoe commented on code/__DEFINES/traits.dm
> +///You become Marine!!!
please say what the trait actually does

2023-11-07 00:54 UTC, Therandomhoboo commented on code/__DEFINES/traits.dm
> +///You become Marine!!!
Amended

2023-11-07 01:00 UTC, Moltijoe approved these changes
good enough

2023-11-07 02:42 UTC, Yarinoi commented
yes we are

2023-11-08 07:30 UTC, Runian commented
Crayon disgust 👍 Marine quirk 👎

2023-11-08 09:25 UTC, Therandomhoboo commented
> Crayon disgust 👍 Marine quirk 👎

I had to do this to sate the Marines that were encroaching quickly on my location

2023-11-10 22:39 UTC, RG4ORDR commented
Merge this on the USMC Birthday please.

2023-11-11 02:34 UTC, merged