Give HFR gas monitoring bar a consumption rate
yogstation13/Yogstation pull request #20836
Opened 2023-11-05 18:39 UTC by warface1234455

# Document the changes in your pull request
HFR gas monitoring bar has a consumption rate for how much gas being removed per tick

# Why is this good for the game?
You get to know how much gas is being removed from the HFR, pretty convenient

# Testing
![image](https://github.com/yogstation13/Yogstation/assets/89688125/f4b40aa7-99a8-4b02-b7aa-bce0a51b5404)

# Wiki Documentation
no wiki

# Changelog

:cl:  
rscadd: Give HFR gas monitoring bar a consumption rate
/:cl:

2023-11-08 01:12 UTC, MajManatee commented
"Ready for review" 5 more comits

2023-11-08 22:12 UTC, iloveloopers commented
Average coder

2023-11-09 18:22 UTC, warface1234455 commented
> "Ready for review" 5 more comits

slight tweak lol

2023-12-06 14:17 UTC, SapphicOverload requested changes

2023-12-06 14:17 UTC, SapphicOverload commented on code/modules/atmospherics/machinery/components/fusion/hfr_main_processes.dm
> +				heat_output *= 1.
```suggestion
				heat_output *= 1.025
```

2023-12-06 14:17 UTC, iamthesilly commented on code/modules/atmospherics/machinery/components/fusion/hfr_main_processes.dm
> +					delta_mod_removed_list[GAS_PLASMA] = -remove_amount
```suggestion
					delta_mod_removed_list[GAS_HEALIUM] = -remove_amount
```

2023-12-06 14:31 UTC, warface1234455 commented on code/modules/atmospherics/machinery/components/fusion/hfr_main_processes.dm
> +				heat_output *= 1.
oh shi

2023-12-06 14:31 UTC, warface1234455 commented on code/modules/atmospherics/machinery/components/fusion/hfr_main_processes.dm
> +					delta_mod_removed_list[GAS_PLASMA] = -remove_amount
i swear i rechecked

2023-12-14 00:40 UTC, ToasterBiome commented
Reopen when done

2023-12-14 00:40 UTC, closed without merging