Revert "Makes the jetpack slower"
yogstation13/Yogstation pull request #20868
Opened 2023-11-11 04:17 UTC by neeshacark

Reverts #9397 

# Why is this good for the game?

I hated this change so much because space exploration is such an unholy pain in the ass and the potential rewards from doing it really aren't that good the vast majority of the time.  Jetpacks are useless to the point where nobody will use them and instead use alternative, faster methods which get removed when spotted with the justification of essentially "unintended, use jetpack"

This makes them useful again, because it's stupid to restrict space travel when there's literally next to nothing out there most rounds - and the ruins where there are loot are mostly large to the point where you'll always bump into them regardless.  Having fast jetpacks makes finding the smaller ruins more likely instead of wandering aimlessly for 40 minutes in the most unengaging place in the whole game despite this being a fucking space game.

I would lock this to not give the insane meth speed on station z-level but I don't have the knowledge to do that so this is what we get. 

:cl:  cark
tweak: Reverts #9397 - making jetpacks useful for space exploration again.
/:cl:

2023-11-11 04:21 UTC, wonderinghost commented
jetpacks are still useful. sucks that they are only teathered to hardsuits or have to break into eva to access. if anything i think the eva lock on the spacesuit crate would be a better investment if you want people to make space exploration more accessible

2023-11-11 04:26 UTC, RG4ORDR commented
Back in the days of yaxty-sax - which many of the yogglets and yoggites scantily remember.
Jetpacks were insanely fast and offered immense movement ability and they were worthy of it due to only 3 of them existing.

Engineers,CE,Miners,Security,EVA,Captain all have access to a jetpack or inbuilt suit jetpack.
We can craft a makeshift one now as well, functionally speaking we do not need to turn into a meta where breaking the grav engine and using a jetpack is the go to thing.

2023-11-11 04:39 UTC, Mqiib commented
I really don't miss meth speed jetpacks in space combat, no thank you

2023-11-11 06:53 UTC, Moltijoe requested changes
rather than reverting it, just change the jetspeed variable

2023-11-11 22:13 UTC, Moltijoe commented
Balance council:
>If you want space travel to be accessible, make a new item or buff existing items that are DESIGNED for space travel

2023-11-12 15:14 UTC, neeshacark commented
> Balance council:
> 
> > If you want space travel to be accessible, make a new item or buff existing items that are DESIGNED for space travel

this literally buffs an item designed for space travel?

2023-11-12 21:02 UTC, Moltijoe commented
> > Balance council:
> > > If you want space travel to be accessible, make a new item or buff existing items that are DESIGNED for space travel
> 
> this literally buffs an item designed for space travel?

oh, whoops, thought this was a different pr for some reason
lemme look at what they said for this one

2023-11-12 21:13 UTC, Moltijoe commented
Balance Council:
>If it was reduced station side then that'd be fine, but since you said you don't know how

2023-11-14 14:15 UTC, MajManatee commented
"...the potential rewards from doing it really aren't that good..."
lol good one

2023-11-15 23:49 UTC, neeshacark commented
> "...the potential rewards from doing it really aren't that good..." lol good one

name one good reward

2023-11-17 14:04 UTC, MajManatee commented
denied + no activity

2023-11-17 14:47 UTC, TheGamerdk commented
Revert = HDs only.

2023-11-19 22:34 UTC, neeshacark commented
im not wasting biomes time with this

2023-11-19 22:35 UTC, TheGamerdk commented
Them's da rules.

2023-11-19 22:37 UTC, neeshacark commented
this is my pr i can close it myself that is how prs work bibby

2023-11-19 22:37 UTC, alexkar598 commented
can i be in the screenshot

2023-11-19 22:37 UTC, TheGamerdk commented
it is not.

2023-11-19 22:38 UTC, TheGamerdk commented
oh nvm it only applies to merging.

2023-11-19 22:38 UTC, closed without merging