Ports Dolphins
yogstation13/Yogstation pull request #2087
Opened 2018-08-07 23:23 UTC by Altoids1

### Fuck yeah dolphins
The most requested port by far for sure
![dolphin2](https://user-images.githubusercontent.com/29939414/43812425-de3dc4f0-9a86-11e8-90f2-f15fb378a78c.png)

#### Changelog

:cl:  
rscadd: Dolphins are back!!
/:cl:

2018-08-07 23:36 UTC, GuppyLaxx requested changes

2018-08-07 23:36 UTC, GuppyLaxx commented on yogstation/code/modules/mob/living/simple_animal/hostile/retaliate/dolphin.dm
> +	speak_emote = list("Chitters", "Squeeks", "Clicks")
This shouldn't be capitalized

2018-08-08 07:41 UTC, Time-Green commented on yogstation/code/modules/mob/living/simple_animal/hostile/retaliate/dolphin.dm
> +	return 1	//No drifting in space for space dolphins!	//original comments do not steal //Too late.
youre fucking dead kiddo

2018-08-08 08:32 UTC, ThatLing commented on yogstation/code/modules/mob/living/simple_animal/hostile/retaliate/dolphin.dm
> +	return 1	//No drifting in space for space dolphins!	//original comments do not steal //Too late.
return TRUE

2018-08-08 08:32 UTC, ThatLing commented on yogstation/code/modules/events/dolphin_migration.dm
> +		new /mob/living/simple_animal/hostile/retaliate/dolphin(C.loc)
Spawn a dolphin on every carpspawn landmark? That's a lot of dolphins.

2018-08-08 15:07 UTC, Altoids1 commented on yogstation/code/modules/events/dolphin_migration.dm
> +		new /mob/living/simple_animal/hostile/retaliate/dolphin(C.loc)
Compare that to what the carp_migration event does:
```dm
/datum/round_event/carp_migration/start()
	for(var/obj/effect/landmark/carpspawn/C in GLOB.landmarks_list)
		if(prob(95))
			new /mob/living/simple_animal/hostile/carp(C.loc)
		else
			new /mob/living/simple_animal/hostile/carp/megacarp(C.loc)
```

2018-08-08 18:11 UTC, Altoids1 commented
So I recently received some new dolphin sprites from Bawhoppen over on Discord.
![dolphin5](https://user-images.githubusercontent.com/29939414/43855848-7aa8c2ba-9b0c-11e8-8272-ad9843f38015.png)
![dolphin4](https://user-images.githubusercontent.com/29939414/43855866-869ae56c-9b0c-11e8-8ca9-6bddee55b6fe.png)
Do y'all think these are better? Should I swap the old sprites for these ones?

2018-08-10 08:56 UTC, ThatLing commented on yogstation/code/modules/events/dolphin_migration.dm
> +		new /mob/living/simple_animal/hostile/retaliate/dolphin(C.loc)
Fair enough

2018-08-10 08:57 UTC, ThatLing commented
@Altoids1 Ready for merge or nah?

2018-08-10 09:00 UTC, Altoids1 commented
@ThatLing Ya ❤️

2018-08-10 09:00 UTC, merged