[PORT] Wood Floor Tile Resprite from TG
yogstation13/Yogstation pull request #20919
Opened 2023-11-18 23:18 UTC by neeshacark

# Document the changes in your pull request

Replaces our old wood floortile sprites with newer, nicer sprites from TG that match our tiles. https://github.com/tgstation/tgstation/pull/69088

# Why is this good for the game?
They look nice, and match out new tiles well

# Spriting
![image](https://github.com/yogstation13/Yogstation/assets/44718209/4225ce2d-d25d-4fd0-98bf-406ac560abe5)
![image](https://github.com/yogstation13/Yogstation/assets/44718209/a296f5db-7a3f-46ed-9247-3af693897110)

# Changelog

:cl:  PositiveEntropy, Kryson, Cark
imageadd: new wood tile and siding sprites from tg
imagedel: replaces old wood tile sprites
/:cl:

2023-11-19 22:23 UTC, Moltijoe requested changes

2023-11-19 22:23 UTC, Moltijoe commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new/datum/stack_recipe("tiled wood floor tile", /obj/item/stack/tile/wood/tile, 1, 4, 20), \
please indent all these for clarity

2023-11-19 22:23 UTC, Moltijoe commented on code/game/turfs/simulated/floor/fancy_floor.dm
> +	broken_states = list("wood-large-broken", "wood-large-broken2", "wood-large-broken3")
make sure to set floor_tile to the type of tile object used to place these, or when they're pulled up they're turn back into regular wood tiles

2023-11-20 00:18 UTC, Moltijoe requested changes

2023-11-20 00:18 UTC, Moltijoe commented on code/game/turfs/simulated/floor/fancy_floor.dm
> +	icon_state = "wood-tile-broken"
```suggestion
	icon_state = "wood-tile-broken"
	broken = TRUE
```

2023-11-20 00:18 UTC, Moltijoe commented on code/game/turfs/simulated/floor/fancy_floor.dm
> +	icon_state = "wood-parquet-broken"
```suggestion
	icon_state = "wood-parquet-broken"
	broken = TRUE
```

2023-11-20 00:18 UTC, Moltijoe commented on code/game/turfs/simulated/floor/fancy_floor.dm
> +	icon_state = "wood-large-broken"
```suggestion
	icon_state = "wood-large-broken"
	broken = TRUE
```

2023-11-20 00:43 UTC, Moltijoe approved these changes
code looks fine now

2023-11-22 21:11 UTC, ToasterBiome approved these changes

2023-11-22 21:11 UTC, merged