actually adds slugcat to the vendor and donator items because i forgot to hit "push" last time
yogstation13/Yogstation pull request #20923
Opened 2023-11-19 09:41 UTC by thegoldencat413

# Document the changes in your pull request
i feel like an idiot

this fixes blahaj sprites and makes the slugcat sprites better
also adds them to donator items and to the vendor becuase i messed up last time

# Why is this good for the game?
uhh not really relevant becuase this is a direct copy paste of changes that i didnt push
# Testing
![image](https://github.com/yogstation13/Yogstation/assets/42217660/f30e0389-a064-4148-bfbc-b59a0edeac56)
![image](https://github.com/yogstation13/Yogstation/assets/42217660/39a0d398-5ae5-4269-8335-3e55c46afd83)

# Spriting

new:
![image](https://github.com/yogstation13/Yogstation/assets/42217660/d1817cfb-074d-4129-85bd-cc65f01f9fb0)
![image](https://github.com/yogstation13/Yogstation/assets/42217660/ab4ecaf3-a308-485d-96f2-fe88a745b136)
![image](https://github.com/yogstation13/Yogstation/assets/42217660/54bb3396-54c1-48ba-b966-e60bc351eaad)
![image](https://github.com/yogstation13/Yogstation/assets/42217660/06961a4b-b6bd-4143-9bbd-536298870e65)

# Wiki Documentation

# Changelog

:cl:  
rscadd: Added slugcat to the vendor and donator items

/:cl:

2023-11-19 16:03 UTC, Majkl-J approved these changes
Looks good to me

2023-11-25 07:18 UTC, Moltijoe commented
update to master

2023-11-29 21:53 UTC, ToasterBiome requested changes

2023-11-29 21:53 UTC, ToasterBiome commented on code/game/objects/items/plushes.dm
> +/obj/item/toy/plush/slugcat
why

2023-12-04 14:26 UTC, MajManatee commented
Inactive 2+ weeks. Reopen when updated and requests addressed.

2023-12-04 14:26 UTC, closed without merging

2023-12-05 05:02 UTC, Majkl-J commented
Saying why isn't a request