[BOX] Captain's Office Redesign: New Tiles Edition!
yogstation13/Yogstation pull request #20962
Opened 2023-11-24 00:41 UTC by neeshacark

# Document the changes in your pull request

redesigns captain's office with newly added tiles, complete with features such as an elevated office area for the captain - so that anyone visiting him will literally have to look up to him.

# Why is this good for the game?
look v nice 👍 

# Wiki Documentation

Map image update technically (nobody does this)

# Changelog

:cl:  cark
mapping: Redesigns captain's office on box
/:cl:

2023-11-28 15:38 UTC, MajManatee commented
it says "elevated" but it looks like he's working in a stone pit imo. otherwise looks nice and doesn't really seem to affect balance much (disk and hand tele still accessible w/o going through the windoors)

2023-11-28 23:40 UTC, neeshacark commented
> it says "elevated" but it looks like he's working in a stone pit imo. Look at Gax and see how the thick shadow on the bridge stairs is at the lower end (left), giving the effect that light is coming from above and its blocked by the stairs. Try flipping the stair sprite, could make it work. Otherwise looks nice and doesn't really seem to affect balance much (disk and hand tele still accessible w/o going through the windoors)

the stairs are pointing in the correct direction, idk what to tell you

2023-11-29 15:33 UTC, MajManatee commented
idk what else to say it looks like the office is in a pit

2023-11-29 20:10 UTC, AMyriad commented
Snazzy redesign. Bit worried about the glass doors and especially the windows, as Rwindows are MUCH easier to break than Rwalls, especially with traitor gear. Time will tell though.

2023-11-29 21:54 UTC, ToasterBiome requested changes, later dismissed
can we have the wood trim around the carpet like library has

2023-12-01 09:35 UTC, neeshacark commented
> Snazzy redesign. Bit worried about the glass doors and especially the windows, as Rwindows are MUCH easier to break than Rwalls, even with shutters, and especially with traitor gear. Time will tell though.

it has blast doors, you would be better off going through the walls if they're closed

2023-12-02 09:48 UTC, azzzertyy commented
how its layed out here doesnt make sense and is kinda weird, this should fix it with this design.
![image](https://github.com/yogstation13/Yogstation/assets/42524344/6aa1a40a-90dc-429c-8f3b-624bf0361890)

but i think this is better
![image](https://github.com/yogstation13/Yogstation/assets/42524344/748c2876-f613-497b-a9fc-e2c2adbafce4)

2023-12-04 14:24 UTC, MajManatee commented
> how its layed out here doesnt make sense and is kinda weird, this should fix it with this design. ![image](https://private-user-images.githubusercontent.com/42524344/287435477-6aa1a40a-90dc-429c-8f3b-624bf0361890.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDAwNjMsIm5iZiI6MTcwMTY5OTc2MywicGF0aCI6Ii80MjUyNDM0NC8yODc0MzU0NzctNmFhMWE0MGEtOTBkYy00MjljLThmM2ItNjI0YmYwMzYxODkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE0MjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NDY4ZGMyM2U1NjU5NmYyNGY4ZDMyMTY3ZjhmYjEzYTEwODA1MTFhZTM4ZDU1ZjcyZjM3YmU0MDI1Y2QxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u9JDZvBUq_2ul4hP0MTna9qcFJ2G1E6LZkOr-a_U9yA)
> 
> but i think this is better (i forgot windoors) ![image](https://private-user-images.githubusercontent.com/42524344/287435617-748c2876-f613-497b-a9fc-e2c2adbafce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDAwNjMsIm5iZiI6MTcwMTY5OTc2MywicGF0aCI6Ii80MjUyNDM0NC8yODc0MzU2MTctNzQ4YzI4NzYtZjYxMy00OTdiLWE5ZmMtZTJjMmFkYmFmY2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE0MjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ODk1NDZiZjM3OGFjZTJmZGYzY2NjOGIyNmJiOWViNjE5ZTNlYjU0OGNkMzQwODk5NDUzMDhhOGQ4YjkxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zJSBt_ObxUv0zFrqafbv5WR8-bMXATjyEaLGMUKQW0Q)

I like this second one a lot, except for the fact that it removes the windoors. otherwise perfect imo.

2023-12-09 19:38 UTC, ToasterBiome approved these changes

2023-12-09 19:38 UTC, merged