[BOX] Allows people to exit through the left door in medbay in addition to the right one.
yogstation13/Yogstation pull request #21122
Opened 2023-12-17 03:16 UTC by neeshacark

# Document the changes in your pull request
title

# Why is this good for the game?
no reason for it to be this way, and its really convenient to have it this way instead

# Changelog

:cl:  cark
mapping: the western medbay doors on medbay now have noaccess from the south
/:cl:

2023-12-17 05:08 UTC, Aquizit submitted a review, later dismissed

2023-12-18 03:21 UTC, bruhlookatthisdood commented
It was supposed to be that way, one entrance, one exit. The arrows are now misleading people.

2023-12-18 11:31 UTC, Aquizit requested changes
They bring up a good point. If you're gonna do this remove the arrow decals on the floor.

2023-12-18 20:42 UTC, azzzertyy commented
> It was supposed to be that way, one entrance, one exit. The arrows are now misleading people. If people are too dumb to follow the arrows then that is on them.

Except that aint how it works. Entry from both. So doesnt make sense, remove arrows

2023-12-19 16:41 UTC, neeshacark commented
> They bring up a good point. If you're gonna do this remove the arrow decals on the floor.

i would say thats a bit of a silly requirement. nice to have them there, just because a door is marked enter doesnt mean you can use it to exit

2023-12-19 16:41 UTC, closed without merging