Yet another update to new bar... Paystand edition
yogstation13/Yogstation pull request #21139
Opened 2023-12-19 17:34 UTC by azzzertyy

# Document the changes in your pull request
Updates the new bar, gives both barkeep and chefs a paystand, decreases the wideness of the kitchen and adds wideplating to add 3d depth to the heightened section because it looks stupid without it.

![image](https://github.com/yogstation13/Yogstation/assets/42524344/7f96c0e8-ec85-406b-b46e-d3a21c3836ae)

# Why is this good for the game?
Better visually. Barkeep can now charge for drinks easier. Barkeep has a little more room too work with on construction projects and the like.

# Testing
None.

# Changelog
:cl:  
mapping: Added paystand to bar and kitchen, decreased wideness of kitchen, made the raised section look logical.
/:cl:

2023-12-19 17:36 UTC, neeshacark requested changes
remove the 3 by the christmas tree and shift the tree to the right by a tiles

2023-12-19 17:37 UTC, azzzertyy commented
> remove the 3 tables by the christmas tree and shift the tree to the right by a tiles

i forgot it was there tbh

2023-12-19 17:38 UTC, MommaDragon commented
Why is the kitchen massive anyways?

2023-12-19 17:39 UTC, neeshacark commented
> Why is the kitchen massive anyways?

2 chefs = more space

2023-12-19 17:44 UTC, Therandomhoboo commented
Can you give barkeeps a way to get to maints quicker please? And can we get a clothing vendor in our backroom for more diverse barkeep clothing changes ;)

2023-12-19 17:46 UTC, azzzertyy commented
> Can you give barkeeps a way to get to maints quicker please? And can we get a clothing vendor in our backroom for more diverse barkeep clothing changes ;)

you have a bar clothing vendor dude

2023-12-19 17:48 UTC, Therandomhoboo commented
> > Can you give barkeeps a way to get to maints quicker please? And can we get a clothing vendor in our backroom for more diverse barkeep clothing changes ;)
> 
> you have a bar clothing vendor dude, and look, this is all a compromise here. ive given you more space, i cant really give any maint room, ive tried to see if itl work and it just wont.

just remove the poopy entrance to the pool area and connect that off pls for the love of god i will pay you anytrhing

2023-12-19 17:49 UTC, azzzertyy commented
> > Can you give barkeeps a way to get to maints quicker please? And can we get a clothing vendor in our backroom for more diverse barkeep clothing changes ;)
> 
> you have a bar clothing vendor dude


> > > Can you give barkeeps a way to get to maints quicker please? And can we get a clothing vendor in our backroom for more diverse barkeep clothing changes ;)
> > 
> > 
> > you have a bar clothing vendor dude, and look, this is all a compromise here. ive given you more space, i cant really give any maint room, ive tried to see if itl work and it just wont.
> 
> just remove the poopy entrance to the pool area and connect that off pls for the love of god i will pay you anytrhing

no

2023-12-19 17:50 UTC, Therandomhoboo commented
> > > Can you give barkeeps a way to get to maints quicker please? And can we get a clothing vendor in our backroom for more diverse barkeep clothing changes ;)
> > 
> > 
> > you have a bar clothing vendor dude
> 
> > > > Can you give barkeeps a way to get to maints quicker please? And can we get a clothing vendor in our backroom for more diverse barkeep clothing changes ;)
> > > 
> > > 
> > > you have a bar clothing vendor dude, and look, this is all a compromise here. ive given you more space, i cant really give any maint room, ive tried to see if itl work and it just wont.
> > 
> > 
> > just remove the poopy entrance to the pool area and connect that off pls for the love of god i will pay you anytrhing
> 
> no

please

2023-12-19 18:16 UTC, neeshacark approved these changes
map is fine, im not sure about giving the chef a paystand that might not turn out well if people try to force people to pay for food

would like a second maptainer opinion

2023-12-19 18:32 UTC, azzzertyy commented
> map is fine, im not sure about giving the chef a paystand that might not turn out well if people try to force people to pay for food
> 
> would like a second maptainer opinion

literally just dont be poor, plus theres other food sources.

2023-12-19 20:16 UTC, ToasterBiome approved these changes

2023-12-21 09:51 UTC, merged

2023-12-21 17:34 UTC, dcxgame commented
> map is fine, im not sure about giving the chef a paystand that might not turn out well if people try to force people to pay for food
> 
> would like a second maptainer opinion

The chef being beat up (or having to beat people up) for trying to force everyone to pay is a fun player interaction