Reworks AI MiniSat on box to have two more easy to access server rooms.
yogstation13/Yogstation pull request #21140
Opened 2023-12-19 18:28 UTC by azzzertyy

# Document the changes in your pull request
![image](https://github.com/yogstation13/Yogstation/assets/42524344/bec782b0-e424-4303-aee3-041b0be28985)

# Why is this good for the game?
Network admins will be able to work on the AI core without the AI screaming about the potential of human harm or whatever. Makes it possible for them to work on their servers, also has failsafes to disconnect the servers incase the air is being sapped through the pipes.

# Testing
None yet.

# Changelog
:cl:  
mapping: AI Sattelite has server rooms for easier access now.
/:cl:

2023-12-19 19:33 UTC, bruhlookatthisdood commented
How will those secondary rooms with the machine frames work? How will the air not leak out every time you go in?

2023-12-19 19:49 UTC, azzzertyy commented
> How will those secondary rooms with the machine frames work? How will the air not leak out every time you go in?

because the rooms are the exact same pressure as the other rooms, very slowly the air will normalize in temperature, but if you just close the door in after you its fine.

2023-12-19 20:17 UTC, ToasterBiome requested changes
Too many 1 tile wide hallways here

2023-12-19 20:18 UTC, azzzertyy commented
> Too many 1 tile wide hallways here

its the ai sattelite at most one person is ever there

2023-12-19 20:19 UTC, ToasterBiome commented
> > Too many 1 tile wide hallways here
> 
> its the ai sattelite at most one person is ever there

the entire sec team in question:

2023-12-19 20:20 UTC, azzzertyy commented
> > > Too many 1 tile wide hallways here
> > 
> > 
> > its the ai sattelite at most one person is ever there
> 
> the entire sec team in question:



> > > Too many 1 tile wide hallways here
> > 
> > 
> > its the ai sattelite at most one person is ever there
> 
> the entire sec team in question:

ok but the place with actual fighting is nowhere near the 1 tile "hallway" its at the entrance and further on, which are completely unchanged. plus if youre actually trying to kill the AI through going through that way thats an L bozo on your part because youre not gonna win anyway, plus this makes the ai download more accessible, since its right next to the teleporter.

2023-12-20 02:40 UTC, bruhlookatthisdood commented
> > How will those secondary rooms with the machine frames work? How will the air not leak out every time you go in?
> 
> because the rooms are the exact same pressure as the other rooms, very slowly the air will normalize in temperature, but if you just close the door in after you its fine.

i mean technically yeah, but still seems like should be some sort of airlock there, like tcomms, ai core, secondary core, ect ect

2023-12-23 06:19 UTC, ToasterBiome requested changes
These server rooms are too small, I don't really like the lack of space in them. I do not believe the changes adequately fulfill my requested changes.

2024-01-04 21:33 UTC, ToasterBiome commented
Reopen with requested changes

2024-01-04 21:33 UTC, closed without merging