fixes fire extinguisher icons
yogstation13/Yogstation pull request #21153
Opened 2023-12-20 20:24 UTC by cuackles

# Document the changes in your pull request

flips the icons so when the safery is on it actually looks on 

![image](https://github.com/yogstation13/Yogstation/assets/68789204/a8ceddc8-b629-43b8-86c2-124398675915)
![image](https://github.com/yogstation13/Yogstation/assets/68789204/af24ac3f-c631-40e7-8929-2b0500495dd3)

# Changelog

:cl:    
tweak: flips the on and off state of the extinguisher so they correspond to the correct states

2023-12-21 03:20 UTC, SapphicOverload commented
forgor advanced extinguisher

2023-12-24 02:47 UTC, ToasterBiome approved these changes

2023-12-24 02:47 UTC, ToasterBiome requested changes
advanced extingiushejr

2024-01-02 03:39 UTC, ToasterBiome approved these changes

2024-01-02 03:39 UTC, merged