Fixes every problem with the icemoon (makes the liquid plasma not replace limbs)
yogstation13/Yogstation pull request #21173
Opened 2023-12-25 21:28 UTC by Addust

# Document the changes in your pull request

Comments out a few lines of code and leaves a warning, while also changing variables to avoid it becoming the weakest source of burn damage in the whole game

# Why is this good for the game?

The plasmaman limbs that it melts your regular limbs into **PHYSICALLY CANNOT BE HEALED**, even worse if it replaces your head or chest. If someone were to FIX this healing issue, this PR would not have to exist, but the state of Yogs is the state of Yogs.

# Testing
i loaded up yogstation, spawned a /turf/open/lava/plasma, and confirmed it did burn and mild toxin without making my limbs useless

# Spriting
what

# Wiki Documentation

is this shit even on the wiki

# Changelog

:cl:  
bugfix: Because the resulting limbs can't be healed, your limbs will no longer be melted by liquid plasma.
/:cl:

feel free to revert once the issue is fixed

2023-12-26 01:54 UTC, Moltijoe requested changes
Dont call it a bugfix if you're sweeping the bug under the rug rather than fixing it

2023-12-26 12:17 UTC, Addust commented
> Dont call it a bugfix if you're sweeping the bug under the rug rather than fixing it

switched to a deletion

2024-01-31 08:29 UTC, Moltijoe requested changes

2024-01-31 08:29 UTC, Moltijoe commented on code/modules/awaymissions/mission_code/snowdin.dm
> +//							PP.visible_message(span_warning("[L] screams in pain as [L.p_their()] [NB] melts down to the bone!"), \
fix these lint errors

2024-02-09 14:48 UTC, MajManatee commented
1 Week + no activity. Re-open when work continutes

2024-02-09 14:48 UTC, closed without merging