Moonshine is too good for the eyes
yogstation13/Yogstation pull request #21206
Opened 2024-01-03 16:15 UTC by Therandomhoboo

# Document the changes in your pull request

Moonshine does nothing to the eyes? What in tarnation is this? Amurica perfected cheap ethanol enthused alcohol and by my freedom to bare alcohol we will give it an effect.

Moonshine now makes you temp blind unless you're an assistant. Why assistants? Because they are lousy alcoholics anyway.

# Why is this good for the game?

Gives some funny booze effects

# Testing

No

# Wiki Documentation

Change the moonshine description to include anyone that isn't assistant will be temp blind.

# Changelog

:cl:  

rscadd: Moonshine now makes you temp blind, long live getting BLIND drunk 🤌 

/:cl:

2024-01-03 18:20 UTC, MajManatee commented
idk about assistant immunity, they seem like the people most likely to drink it. The best moonshiners are blind right?

2024-01-03 19:50 UTC, SapphicOverload commented
Mmmm tasty methanol

2024-01-04 23:31 UTC, ToasterBiome requested changes
it should simply do eye damage or eye blur instead of make you straight up blind

2024-01-05 20:23 UTC, Therandomhoboo commented
> it should simply do eye damage or eye blur instead of make you straight up blind

Pah its only temp blind, I aint CRUEL but if the HD wishes it I can make it do eye blur instead. would of been funnier though

2024-01-05 20:56 UTC, MajManatee commented
Blur + damage so you still can go blind

2024-01-06 00:09 UTC, Therandomhoboo commented
> Blur + damage so you still can go blind

I'll do blur, I put in temp blind just for the funny. I don't want it to actually perma-blind peeps even though it would be funny.

2024-01-06 04:10 UTC, Moltijoe commented
> I'll do blur, I put in temp blind just for the funny. I don't want it to actually perma-blind peeps even though it would be funny.

instant blind, even temporary, makes it too easy to weaponize

2024-01-06 21:11 UTC, Therandomhoboo commented
> it should simply do eye damage or eye blur instead of make you straight up blind

There, your will is done mi'lord

2024-01-06 22:04 UTC, ToasterBiome requested changes
remove emoticon from changelog it breaks

2024-01-08 05:23 UTC, ToasterBiome approved these changes

2024-01-08 05:24 UTC, merged