Airalarm can now turn on/off vent space detection
yogstation13/Yogstation pull request #21254
Opened 2024-01-14 18:57 UTC by warface1234455

# Document the changes in your pull request
Airalarm can now turn on/off vent space detection

# Why is this good for the game?
Allow unary vent to pump gas into space, a good feature i guess. Probally help pump gas out faster into space

This one is faster than injector and be remotely controlled which makes it the best way to dump waste into space

# Testing
tested, was able to pump gas into space after multitooling the vent

# Changelog

:cl:  

tweak: Airalarm can now turn on/off vent space detection
/:cl:

2024-01-14 19:32 UTC, SapphicOverload commented
Does this need to exist? Why not just use an injector?

2024-01-14 19:33 UTC, warface1234455 commented
> Does this need to exist? Why not just use an injector?

yes, if you want faster gas ejection

2024-01-14 19:33 UTC, warface1234455 commented
if you dont have an airalarm nearby then you can just use injector

2024-01-14 19:34 UTC, wonderinghost commented
I think it be nice if we could with air scrubbers. However biggest pain is zoning because you can't claim areas outside of a contained room

2024-01-14 19:40 UTC, warface1234455 commented
Injector also has cons that you have to get near it to turn it on/off. While vent can be remotely controlled via airalarm

2024-01-14 19:46 UTC, warface1234455 commented
> I think it be nice if we could with air scrubbers. However biggest pain is zoning because you can't claim areas outside of a contained room

Honestly, scrubbers are slow at sucking gas. The vent external 0kpa on scrubbing mode can do this job far more faster

2024-01-31 08:08 UTC, Moltijoe requested changes
if injectors aren't fast enough, just make them faster

2024-02-01 02:17 UTC, warface1234455 commented
Guess ill buff the injector in the other pr then

2024-02-01 02:17 UTC, closed without merging