[BOX] Partial revert of #21214 - just doesn't give corners back.  Also fixes pipes on bridge
yogstation13/Yogstation pull request #21253
Opened 2024-01-14 00:52 UTC by neeshacark

# Document the changes in your pull request

the reason i did this is because it seemed to be that after the railings were flipped by azzzerty, people started rendering over them.  in reality, another PR did this by breaking code and it wasn't their fault at all.  this pr keeps the sidings that aquizit wanted but also removes a set of railing corners that looked bad that azzzerty added. hopefully someone will fix the code soon

This also fixes a missing pipe in bridge that the first bar PR fixed until azzzerty caused merge conflicts and it got nuked.

:cl:  cark
mapping: fixes a missing pipe on box bridge and flips railings in the bar
/:cl:

2024-01-15 12:26 UTC, azzzertyy commented
only added those corners because i was told they were the standard back on chapel2 pr i think they look bad too

2024-01-16 22:55 UTC, Aquizit requested changes
I know it is the most minor of things but can you get these looking better on the tables there?

![image](https://github.com/yogstation13/Yogstation/assets/70451213/43d4409a-a408-4f86-a87b-f4f84499195d)

---

I am also not sure if you mean for the bartender to have 2 rags

![image](https://github.com/yogstation13/Yogstation/assets/70451213/ca24f6ea-a102-4ab1-8515-c30aca86e2cd)

2024-01-28 15:03 UTC, Aquizit commented
Aside from the changes requested just throwing up a do not merge as Bibby requested no map changes while AI is TM'd.

2024-02-03 05:17 UTC, neeshacark commented
ill do this later

2024-02-03 05:17 UTC, closed without merging