Remove's Borgs from BR
yogstation13/Yogstation pull request #21292
Opened 2024-01-21 23:24 UTC by RG4ORDR

# Document the changes in your pull request

Removes Borgs from BR

# Why is this good for the game?
No reason for these to be in the BR loot pool. They either functionally do not help the player that spawns them or will kill the player that spawned them in. Not very fun to be punished for playing the game, so they're getting removed. Rejoice.
# Changelog
:cl:  
rscdel: Syndie Borgs Spawners removed from BR loot pool.
 
/:cl:

2024-01-22 01:31 UTC, bruhlookatthisdood commented
maybe instead of removing it make it so they have to obey whoever spawned them in like being emagged

2024-01-22 02:52 UTC, RG4ORDR commented
> maybe instead of removing it make it so they have to obey whoever spawned them in like being emagged

Im not going through the effort to do that.
Besides summonable allies in BR is cringe.

2024-01-22 08:11 UTC, Moltijoe requested changes
Please also remove the changes that let the borg summoning items be used by battle royalers

2024-01-31 08:34 UTC, Moltijoe approved these changes
whatever, i guess that's scope creep

2024-01-31 08:34 UTC, merged