Anti megafauna ert
yogstation13/Yogstation pull request #21304
Opened 2024-01-24 00:52 UTC by Loiosh42

This PR adds an additional ERT for admin spawn, equipped with OP mining kit for killing megafauna that have breached onto the station.

It has been tested on a local server.

# Why is this good for the game?
None of the other ERT's are equipped for dealing with megafauna, except for perhaps deathsquad. They are simply balanced differently. Hisakaki requested it.

# Testing
Booted local server, spawned an ERT.

# Wiki Documentation
Nil(probably)

# Changelog

:cl:  
rscadd: Adds Miner ERT
/:cl:

2024-01-24 00:53 UTC, Yarinoi commented
lmao yes

2024-01-24 00:53 UTC, Beeper-Skeeper commented
finally

2024-01-24 08:22 UTC, AMyriad commented on code/datums/ert.dm
> +	polldesc = "A merry band of Megafauna-hunting dwarves"
BASED

2024-01-24 14:24 UTC, bruhlookatthisdood commented
make them all have dwarfism mutator for max rock and stone

2024-01-24 18:35 UTC, AMyriad commented
btw is the lack of mindshielding intentional here?

2024-01-24 20:03 UTC, Loiosh42 commented
> make them all have dwarfism mutator for max rock and stone

![image](https://github.com/yogstation13/Yogstation/assets/129321455/1660904d-1a6b-470b-be15-0f75a525d295)

2024-01-24 20:04 UTC, Loiosh42 commented
> btw is the lack of implants intentional here?

Dusting implants? No, but that can be set upon spawning the ERT.

2024-01-24 20:31 UTC, AMyriad commented
> Dusting implants? No, but that can be set upon spawning the ERT. (If you want it enabled on default, that is easy too.)

no I was referring to mindshields and biosignallers, which all other ERTs have

2024-01-24 20:57 UTC, Loiosh42 commented
> > Dusting implants? No, but that can be set upon spawning the ERT. (If you want it enabled on default, that is easy too.)
> 
> no I was referring to mindshields and biosignallers, which all other ERTs have

That...should be inherited I think? If not, I don't think it really matters for an anti-megafauna ERT anyway, they should not be fighting anything other than mining mobs usually. And if you could convert them, you have a chance to steal their stuff anyhow.

2024-01-31 08:36 UTC, Moltijoe requested changes

2024-01-31 08:36 UTC, Moltijoe commented on code/modules/clothing/outfits/ert.dm
> +		/obj/item/dnainjector/dwarf=1,
rather than giving them an injector, force the mutation on them directly in post_equip

2024-02-09 14:38 UTC, MajManatee commented
1 Week no activity, Please re-open and make requested changes, then show proof of testing when work continues.

2024-02-09 14:38 UTC, closed without merging