Live xeno aliens on station level now generate research
yogstation13/Yogstation pull request #21303
Opened 2024-01-23 20:03 UTC by ynot01

# Document the changes in your pull request
Shenanigans

# Why is this good for the game?
Incentive (besides grief) to have xenos in xenobiology containment

# Testing
Pending

# Wiki Documentation
5 research per second per alien
Default passive research is ~60/s
Would need 12 aliens on station to double research rate

# Changelog

:cl:  
tweak: Live xeno aliens on station level now passively generate research points
/:cl:

2024-01-23 20:56 UTC, MajManatee commented
the station may be completely overrun but boy can we research quickly :)

2024-01-24 14:26 UTC, bruhlookatthisdood commented
shouldn't they only generate research while in xenobiology containment? or crew could see a spike in research and possibly know what is happening.

2024-01-25 01:15 UTC, Yarinoi commented
agreed, plus it doesnt make any sense to be able to get research from them while they're escaped, and might lead to even faster mech response
other then that, great idea!

2024-01-25 01:17 UTC, ToasterBiome requested changes
show testing

2024-01-29 20:13 UTC, ToasterBiome approved these changes

2024-01-29 20:13 UTC, merged