Adjusts the costs of several changeling abilities
yogstation13/Yogstation pull request #21322
Opened 2024-01-28 20:02 UTC by cowbot92

# Document the changes in your pull request

Adjusts the chemical cost of Changeling Tentacle from 10 -> 5
Adjusts the DNA cost of Tentacle from 2 -> 1

Adjusts the cost of Dissonant Shriek from 40 -> 30

Adjusts the cost of False Armblade Sting from 20 -> 5

Adjusts the cost of Blind Sting from 40 -> 20

Adjusts thee cost of Hallucination Sting from 10 -> 30

Adjusts the cost of Cryogenic Sting from 30 -> 25

# Why is this good for the game?

Makes some underused/purchased abilities a bit more favourable to get, while adjusting one in particular that should cost more

# Testing

Numbers changes.

# Wiki Documentation

adjust all the costs as listed above

# Changelog

:cl:  

tweak: adjusts the cost of several changeling abilities

/:cl:

2024-01-31 08:14 UTC, SapphicOverload requested changes

2024-01-31 08:14 UTC, SapphicOverload commented on code/modules/antagonists/changeling/powers/shriek.dm
>  	desc = "We shift our vocal cords to release a high-frequency sound that overloads nearby electronics. Costs 40 chemicals."
Stop spreading misinformation!!!!
```suggestion
	desc = "We shift our vocal cords to release a high-frequency sound that overloads nearby electronics. Costs 30 chemicals."
```

2024-01-31 14:06 UTC, MajManatee commented
>Adjusts the chemical cost of Hallucination Sting from 10 -> 30

why? its garbage?

2024-02-02 16:41 UTC, cowbot92 commented
Actually I like changeling the way it is

2024-02-02 16:41 UTC, closed without merging

2024-02-02 16:43 UTC, MajManatee commented
neat