Atom-level integrity + wall destruction rework
yogstation13/Yogstation pull request #21336
Opened 2024-01-30 18:05 UTC by SapphicOverload

# Document the changes in your pull request

Moves integrity to the atom level (ported from tgstation/tgstation#61183), and allows turfs to be destroyed in the same way objects can.

Many things which destroy walls have been reworked to use the integrity system instead, and walls can now be destroyed through conventional means like hitting them with something strong. They can also be repaired with welding tools while not on harm intent. Reinforced walls are still very strong and require powerful tools or weapons to damage.

Standard wall - 300 integrity, 20 damage deflection, 60 melee/bullet/laser armor

Reinforced wall - 400 integrity, 75 damage deflection, 80 melee/bullet armor, 60 laser armor

# Why is this good for the game?

Walls being able to use the integrity system means destroying them in a way that isn't instantaneous no longer needs to rely on long progress bars (space dragons, mech drills), the explosion subsystem (pulse rifles, blast cannons), or just random chance (too many to list here)

It also means they aren't totally invincible to damage, which I think could allow for some fun interactions.

# Testing
Tested pretty much everything I could think of, works just fine.

# Changelog

:cl:  
tweak: walls are now destructible
/:cl:

2024-01-30 19:55 UTC, Mqiib commented
It also means that some things like space dust aren't even more dangerous against solid walls than they are against windows

2024-02-04 06:09 UTC, Moltijoe commented
show testing please

2024-02-04 08:14 UTC, SapphicOverload commented
> show testing please

Done

2024-02-08 04:37 UTC, warface1234455 commented
We're going to break into cap office with this one

2024-02-09 05:17 UTC, warface1234455 commented
That one atmos tech not realizing particles break wall and leaked fusion gas on station

2024-02-09 05:18 UTC, warface1234455 commented
Maybe give walls 100 energy armor

2024-02-10 13:42 UTC, SapphicOverload commented
> That one atmos tech not realizing particles break wall and leaked fusion gas on station

They don't break walls because the damage deflection is much higher than the damage particles can do

2024-02-10 13:57 UTC, SapphicOverload commented
@MajManatee this doesn't change the maps at all, it just removes the obj_integrity variable from a few things

2024-02-11 17:09 UTC, JamieD1 approved these changes

2024-02-25 18:55 UTC, Aquizit approved these changes

2024-02-25 18:55 UTC, Aquizit commented
oh whoops jamie did it for map already

2024-02-27 00:40 UTC, JohnFulpWillard commented on code/__DEFINES/dcs/signals/signals_atom/signals_atom_attack.dm
> +#define COMSIG_ATOM_ATTACKBY_SECONDARY "atom_attackby_secondary"
This isn't used anywhere right? Since it requires combat mode?

2024-02-27 00:42 UTC, JohnFulpWillard commented on code/game/atom/_atom.dm
> +		return take_damage(punch_force, mech_damtype, MELEE, play_soundeffect, get_dir(src, M)) // multiplied by 3 so we can hit objs hard but not be overpowered against mobs.
This is the exact same thing
```suggestion
	return take_damage(punch_force, mech_damtype, MELEE, play_soundeffect, get_dir(src, M)) // multiplied by 3 so we can hit objs hard but not be overpowered against mobs.
```

2024-02-27 00:58 UTC, JohnFulpWillard requested changes

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/game/objects/objs.dm
>  	var/damage_deflection = 0
Can you delete these?

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/game/objects/structures.dm
>  /obj/structure/proc/examine_status(mob/user) //An overridable proc, mostly for falsewalls.
What's the point in keeping this proc around instead of using ``examine``?

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/game/turfs/open/floor/plating/asteroid.dm
> +				SEND_SIGNAL(W, COMSIG_ATOM_ATTACKBY, O)
Why is this calling the signal instead of just calling attackby?

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/modules/antagonists/clockcult/clock_structures/traps/brass_skewer.dm
> +	desc = "A vicious brass spike protruding from the ground like a stala[pick("gm", "ct")]ite. It makes you sick to look at." //is stalagmite the ground one? or the ceiling one? who can ever remember?
the icon state and desc should be part of ``update_icon_state`` and ``update_desc``

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/game/mecha/mecha_defense.dm
> +					atom_integrity += min(10, max_integrity-atom_integrity)
Use ``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/modules/vehicles/cars/clowncar.dm
> +		atom_integrity += min(banana.seed.potency, max_integrity-atom_integrity)
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/modules/vehicles/secway.dm
> +		atom_integrity = min(max_integrity, atom_integrity + 20)
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on yogstation/code/modules/ruins/ivymen_den.dm
> +			atom_integrity = min(atom_integrity + max_integrity*0.05, max_integrity) //restores 5% hp of tree
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on yogstation/code/modules/spacepods/spacepod.dm
> +					atom_integrity = min(max_integrity, atom_integrity + 10)
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on yogstation/code/modules/spacepods/spacepod.dm
> +	atom_integrity = max_integrity - integrity_failure + atom_integrity
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on yogstation/code/modules/spacepods/spacepod.dm
> +		atom_integrity = min(integrity_failure, atom_integrity)
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/game/objects/structures/mineral_doors.dm
> +			atom_integrity = min(atom_integrity+4,max_integrity)
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/game/objects/structures/window.dm
> +			atom_integrity = min(atom_integrity+4,max_integrity)
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/modules/antagonists/cult/cult_structures.dm
> +			atom_integrity = min(max_integrity, atom_integrity + 5)
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/modules/modular_computers/hardware/_hardware.dm
> +			atom_integrity = min(atom_integrity + 10, max_integrity)
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on code/modules/ruins/objects_and_mobs/ash_walker_den.dm
> +			atom_integrity = min(atom_integrity + max_integrity*0.05,max_integrity)//restores 5% hp of tendril
``update_integrity``

2024-02-27 00:58 UTC, JohnFulpWillard commented on yogstation/code/modules/spacepods/prebuilt.dm
> +	atom_integrity = rand(100, max_integrity)
``update_integrity``

2024-03-04 04:56 UTC, JohnFulpWillard approved these changes

2024-03-04 04:56 UTC, merged

2024-03-04 05:03 UTC, GDRdev commented
:yoggers:

2024-03-04 06:13 UTC, GDRdev commented
![MANIFESTING](https://github.com/yogstation13/Yogstation/assets/62126495/234ffe88-291e-49f9-ace5-8efa9b51b668)