Shock Touch No Longer Confuses
yogstation13/Yogstation pull request #21366
Opened 2024-02-07 08:23 UTC by Runian

# Document the changes in your pull request
Shock touch (along with the ranged variant) no longer causes any confusion.

# Why is this good for the game?
Shock touch is a genetics power/spell that that has three characteristics that make it a really good power: easy to spam (10 second cooldown), safe to use (can be upgraded to be used at range), forced disarm of the target, and the long lasting confusion (15 seconds which is longer than the cooldown). Given the buff to this spell from [#21002], it makes sense that this power gets toned down as the only counter to this is: wearing a hardsuit, insulated genetics power, or anything that gives full-body protection.

# Testing
No more confusion, yes. Working and moving good.

# Wiki Documentation
Shock touch no longer confuses.

# Changelog
:cl:  
tweak: The genetics power, Shock Touch, no longer causes confusion to the shocked target.
/:cl:

2024-02-09 01:10 UTC, warface1234455 commented
Saved yogs

2024-02-09 06:41 UTC, ToasterBiome requested changes
people have electricity armor now can you make the duration based on that

2024-02-09 15:06 UTC, MajManatee requested changes
Please include a gif, picture, or other proof of testing

2024-02-10 05:54 UTC, MajManatee approved these changes
seems fine to me. balance idk.

2024-02-10 05:59 UTC, ToasterBiome approved these changes
looks good

2024-02-10 06:52 UTC, merged