Mechs no longer deflect ion bolts
yogstation13/Yogstation pull request #21369
Opened 2024-02-08 01:58 UTC by Mqiib

Here's your ion buff/mech nerf. Go ham.

# Why is this good for the game?
Ions are now CONSISTENTLY effective vs mechs rather than just more effective.

# Testing
I probably should but this is simple literally 2 lines of easy code

# Changelog

:cl:  

tweak: Mechs don't deflect ion bolts any more

/:cl:

2024-02-08 02:02 UTC, SapphicOverload requested changes

2024-02-08 02:02 UTC, SapphicOverload commented on code/game/mecha/mecha_defense.dm
> +		return BULLET_ACT_HIT
This needs to call parent or it won't do `on_hit()` effects.
```suggestion
		return ..()
```

2024-02-08 03:35 UTC, wonderinghost commented
https://github.com/yogstation13/Yogstation/pull/21184 

wanted to advertise this before people forget

2024-02-08 14:24 UTC, ThePissGuy commented
why would you stealthnerf shadowlings

2024-02-08 19:38 UTC, MajManatee commented
big props for stealth nerfing slings. Hate those guys.

2024-02-11 17:21 UTC, JamieD1 approved these changes

2024-02-11 17:21 UTC, merged