Here we go again, now with implants and inherent dwarfism!
yogstation13/Yogstation pull request #21378
Opened 2024-02-09 19:34 UTC by Loiosh42

Attempt 2 of an anti-megafauna mining ERT.
(New PR instead of reopening old due to fresh branch to bypass version conflicts.)

# Why is this good for the game?
None of the other ERT's are equipped for dealing with megafauna, except for perhaps deathsquad. They are simply balanced differently. Hisakaki requested it.

# Testing
Booted local server, spawned an ERT.

# Wiki Documentation

Nil

# Changelog

:cl:  
rscadd: Adds an Anti-megafauna ERT, mk2
/:cl:

2024-02-10 07:18 UTC, MajManatee requested changes
Please include pictures, gifs, or videos of testing, and properly fill out the wiki section.

2024-02-10 15:57 UTC, Loiosh42 commented
> Please include pictures, gifs, or videos of testing, and properly fill out the wiki section.

![image](https://github.com/yogstation13/Yogstation/assets/129321455/6feef976-a1c1-464c-ab20-3d8832ee95a3)

![image](https://github.com/yogstation13/Yogstation/assets/129321455/867b64e0-754e-4207-9692-15454c6402d2)

![image](https://github.com/yogstation13/Yogstation/assets/129321455/d0e365e0-63c2-4356-9ecb-c71fcbb12c56)

2024-02-10 16:00 UTC, Loiosh42 commented
I don't believe there is anything to add to the wiki, thus nil.

2024-02-11 17:23 UTC, JamieD1 approved these changes

2024-02-11 17:23 UTC, merged