[Admin] Cryoing as a Valentine no longer tells you to ahelp
yogstation13/Yogstation pull request #21405
Opened 2024-02-13 16:06 UTC by Aquizit

# Document the changes in your pull request

As the title states, you not longer get a warning message before cryoing if you are a Valentine.

# Why is this good for the game?

Valentine's aren't *real* antags. If they wanna go they should be able to go.

# Testing

I tested it, it works in that it doesn't compel you to ahelp, but you still need to enter cryo twice as the first one still does the stupid check and I cannot seem to figure out how to bypass it without making valentine not an antag datum in the first place.

If someone knows how to make it not do the check at all just for valentines that'd be cool.

# Changelog

:cl:  
tweak: No longer told to ahelp when cryoing as a valentine
experimental: Due to how valentine works (it's an antag datum) it still has to do the check I just made it not tell you to ahelp, you'll still need to "enter" cryo twice.
/:cl:

2024-02-13 16:17 UTC, Hislyna commented
Every year. Every damn year something pops up with valentines.

2024-02-13 18:00 UTC, SapphicOverload requested changes

2024-02-13 18:00 UTC, SapphicOverload commented on code/game/machinery/cryopod.dm
> +			if(A.name == "valentine")
You should really add a variable on `/datum/antagonist` for whether the cryo message shows up and check for that.

2024-02-13 18:00 UTC, SapphicOverload commented on code/game/machinery/cryopod.dm
> +				caught = TRUE
You don't want this to be set to true here, or it'll still block from using cryo once without telling you why.

2024-02-14 12:35 UTC, Aquizit commented
tested, works

2024-02-14 23:44 UTC, JamieD1 commented
Shitty Valentines mode. needs to die its dumb, boring and should be opt in

2024-02-14 23:44 UTC, merged