attack visual effect is based on species instead of attack verb text
yogstation13/Yogstation pull request #21537
Opened 2024-02-26 13:42 UTC by 13spacemen

# Document the changes in your pull request
partial port of an old tg pr

# Why is this good for the game?
this is more modular and allows you to have wildly different attack verb text without affecting the visual effect

# Changelog

:cl:  
tweak: Human unarmed attack visual effects are based on species instead of the attack verb text
/:cl:

2024-02-26 15:04 UTC, AMyriad commented
but what does it actually do

2024-02-26 15:29 UTC, 13spacemen commented
@AMyriad when you attach someone as a human, it determines what attack effect (like "claws") to show you based on what the attack verb is (like "slashes")
now these 2 things are separate, your attack verb can be "wildly thrashes" and you can show whatever attack effect you want independent of the verb text

2024-02-28 16:06 UTC, MajManatee requested changes, later dismissed
![image](https://github.com/yogstation13/Yogstation/assets/74586965/8ef9272d-5009-4a6b-811b-836529cfc605)

2024-03-01 13:51 UTC, 13spacemen commented
@MajManatee 
![Screenshot 2024-03-01 184843](https://github.com/yogstation13/Yogstation/assets/46101244/88355f6a-5ec6-4e33-b444-43ca94819304)
![Screenshot 2024-03-01 185028](https://github.com/yogstation13/Yogstation/assets/46101244/3d0e6231-b966-4306-9f2e-a3925eea776f)
![Screenshot 2024-03-01 185055](https://github.com/yogstation13/Yogstation/assets/46101244/116eff6c-ce6d-4853-be54-8ab418a268af)

2024-03-05 15:04 UTC, JohnFulpWillard approved these changes

2024-03-05 15:06 UTC, merged