New wizard spell, scrunch
yogstation13/Yogstation pull request #21562
Opened 2024-02-28 00:31 UTC by Moltijoe

scrunches the target
Does 60 brute damage with a huge wound bonus
30 second cooldown, reduced by 4 seconds per rank

# Why is this good for the game?
Another silly wizard spell, this one slightly more intimidating than the last

# Testing
https://github.com/yogstation13/Yogstation/assets/108117184/f8e79412-9dff-442e-9d3a-c18c620469ae

# Spriting
cuackles said they'd handle the sprite

:cl:  
rscadd: Adds new wizard spell, scrunch
/:cl:

2024-02-28 00:32 UTC, cowbot92 commented
now make the higher levels flatten them more

2024-02-28 00:48 UTC, ThePissGuy commented
it should drop a random vending machine on them

2024-02-28 02:04 UTC, ToasterBiome requested changes
can you make a mouse icon like vampire spells do?

2024-03-01 01:45 UTC, ToasterBiome approved these changes
code review not balance review

2024-03-04 17:08 UTC, ToasterBiome approved these changes

2024-03-04 17:08 UTC, ToasterBiome commented
shit

2024-03-08 06:26 UTC, merged