lava fishin'
yogstation13/Yogstation pull request #21584
Opened 2024-03-02 02:21 UTC by enkidienne

we fishin' today boys!

# Document the changes in your pull request

# Why is this good for the game?

# Testing

# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images
mapping: This is a mapping change
spellcheck: fixed a few typos  
experimental: This is experimental
/:cl:

2024-03-04 19:21 UTC, Hislyna commented
Having a Living goliath as a Common is probably going to make this feature barely used

2024-03-06 23:43 UTC, Tempolx commented
> Having a Living goliath as a Common is probably going to make this feature barely used

On the contrary, it allows miners or otherwise to easily farm goliaths; they are a melee only enemy, easy to kill for ashies with arrows or pkas, and provide a semirare and useful material; also pairs with rune scrimmy for farming

2024-03-08 09:33 UTC, Moltijoe commented
> On the contrary, it allows miners or otherwise to easily farm goliaths; they are a melee only enemy, easy to kill for ashies with arrows or pkas, and provide a semirare and useful material; also pairs with rune scrimmy for farming

Nah, it'll be DoA if goliaths are common
Miners can just use a tendril if they want to farm, sitting around fishing doest suit them
The only person who might fish is the medic, but theyre not entirely equipped to handle goliaths and it'll be more of a nuisance than anything

2024-03-08 18:53 UTC, Yarinoi commented
i think you put the wrong claymore, the regular obj/item/claymore is a 40 force item :skull:

2024-03-08 21:09 UTC, Moltijoe requested changes

2024-03-08 21:09 UTC, Moltijoe commented on yogstation/code/datums/components/fishable.dm
> +		/obj/item/stack/sheet/animalhide/goliath_hide
```suggestion
		/obj/item/stack/sheet/animalhide/goliath_hide,
```

2024-03-08 21:09 UTC, Moltijoe commented on yogstation/code/datums/components/fishable.dm
> +		/obj/item/stack/sheet/mineral/sandstone
```suggestion
		/obj/item/stack/sheet/mineral/sandstone,
```

2024-03-12 18:59 UTC, Moltijoe commented
Balance Council:
>Make the living goliath spawn rare, swap the 40 force claymore for the 18 force nullrod claymore, add a full necropolis chest as rare, move the empty necropolis chest to uncommon

2024-03-12 21:12 UTC, enkidienne commented
2 things:
The nullrod claymore comes with antimagic, fairly sure, so do yall really want a ''reliable'' way to gain antimagic?
A full necropolis chest makes it so miners can get more than what spawns, is that the intend?

2024-03-14 04:52 UTC, Cartlord commented
I feel like adding all these useful-for-shit-other-than-Mining items to the pool is bringing us back to Mining being the "Play a different game than everyone else, then come back to the station with loot that makes Antagonists cry" job, and I don't like that!

2024-03-15 16:37 UTC, MajManatee requested changes
rule of cool. 
Please include proof of testing as per guidelines (Pictures, videos, gifs, etc) and update the changes documentation to reflect what you changed for the balance council.

2024-03-15 21:56 UTC, enkidienne commented
> rule of cool. Please include proof of testing as per guidelines (Pictures, videos, gifs, etc) and update the changes documentation to reflect what you changed for the balance council.

Updated description, a screenshot was added.

2024-03-16 08:54 UTC, Moltijoe approved these changes

2024-03-17 04:43 UTC, Cartlord commented
I don't see what Miners are meant to do with Syndicate magboots, a nullrod claymore, or a bluespace anomaly core - besides powergaming.

2024-03-18 13:20 UTC, MajManatee approved these changes
I am satisfied.

2024-03-18 20:36 UTC, merged