Infinity gauntlet or whatever for Jazz's bus maybe I'll also put the gems in fishing.
yogstation13/Yogstation pull request #21593
Opened 2024-03-03 06:51 UTC by cowbot92

Full credit for all sprites and original idea go to the original PR https://github.com/yogstation13/Yogstation/pull/6619

# Document the changes in your pull request

This PR will add the infinity gauntlet and 6 stones, with corresponding spells.

Mind
Soul
Power
Space
Time
Reality

once collecting all the stones you'll gain access to the "snap" spell, killing half of all existing life in the universe.

# Why is this good for the game?

something for an event.

# Testing

will post a vid once done

# Spriting

refer to https://github.com/yogstation13/Yogstation/pull/6619

# Changelog

:cl:  
rscadd: Adds the dated marvel reference

/:cl:

2024-03-04 05:24 UTC, neeshacark commented
https://youtu.be/jF0E2wnZ-A8

2024-03-09 13:27 UTC, Addust commented
remember to undefine lowmemorymode once this is out of draft

2024-04-07 04:55 UTC, ToasterBiome commented
reopen when you work on this

2024-04-07 04:58 UTC, cowbot92 commented
this is done

2024-04-07 05:17 UTC, GDRdev commented
*stare

2024-04-07 05:48 UTC, Moltijoe requested changes, later dismissed

2024-04-07 05:48 UTC, Moltijoe commented on _maps/_basemap.dm
> +#define LOWMEMORYMODE //uncomment this to load centcom and runtime station and thats it.
don't forget this

2024-04-10 16:31 UTC, cowbot92 commented on _maps/_basemap.dm
> +#define LOWMEMORYMODE //uncomment this to load centcom and runtime station and thats it.
Haha im dumb

2024-04-10 20:31 UTC, cuackles approved these changes

2024-04-16 18:54 UTC, closed without merging