Updates Hub Information as per Council Vote 1052
yogstation13/Yogstation pull request #21606
Opened 2024-03-06 17:26 UTC by JamieD1

:cl:  
tweak: Changes Hub Text
/:cl:

2024-03-06 18:17 UTC, ToasterBiome requested changes
Revert the change from adventure to fun, this is not part of the council vote and will require another one.

2024-03-06 18:28 UTC, JamieD1 commented
Done your Majesty

2024-03-06 23:09 UTC, TheGamerdk requested changes, later dismissed

2024-03-06 23:09 UTC, TheGamerdk commented on yogstation/code/game/world.dm
> +	s += "<br>99% Lag-Free <b>Regular Events!!</b> Join the Adventure!"
The council vote specified only 1 !, the second ! will require another vote

2024-03-06 23:17 UTC, ToasterBiome requested changes
The council votes

2024-03-06 23:17 UTC, ToasterBiome commented on yogstation/code/game/world.dm
> +	s += "<br>99% Lag-Free <b>Regular Events!!</b> Join the Adventure!"
```suggestion
	s += "<br>99% Lag-Free <b>Regular Events!</b> Experience! Join the Adventure!"
```

The council vote states Remove the MRP tag on BYOND, and instead replace it with "Regular Events!". This change removes the phrase "MRP" and replaces it with "Regular Events!". Removal of other words requires a separate council vote.

2024-03-07 02:03 UTC, Hislyna commented
Considering that we stated the MRP tag, and experiance being apart of that tag, experiance is to be removed.

2024-03-07 02:11 UTC, ToasterBiome commented
> Considering that we stated the MRP tag, and experience being apart of that tag, experience is to be removed.

The vote doesn't state that.

2024-03-07 02:11 UTC, Hislyna commented
> > Considering that we stated the MRP tag, and experience being apart of that tag, experience is to be removed.
> 
> The vote doesn't state that.

Doesn't need to, its apart of the tag

2024-03-07 02:15 UTC, ToasterBiome commented
> > > Considering that we stated the MRP tag, and experience being apart of that tag, experience is to be removed.
> > 
> > 
> > The vote doesn't state that.
> 
> Doesn't need to, its apart of the tag. It did not state remove MRP, it stated remove the MRP tag.

There is no scoping for this clarification. The MRP tag is "MRP". That's the entire tag. Unless you're also implying `99% Lag-Free` is also part of the tag?

2024-03-07 02:16 UTC, Hislyna commented
> > > > Considering that we stated the MRP tag, and experience being apart of that tag, experience is to be removed.
> > > 
> > > 
> > > The vote doesn't state that.
> > 
> > 
> > Doesn't need to, its apart of the tag. It did not state remove MRP, it stated remove the MRP tag.
> 
> There is no scoping for this clarification. The MRP tag is "MRP". That's the entire tag. Unless you're also implying `99% Lag-Free` is also part of the tag?

Don't bring the 99% Lag-Free into this. Thats our main selling point of free lag!

2024-03-07 02:17 UTC, ToasterBiome commented
> > > > > Considering that we stated the MRP tag, and experience being apart of that tag, experience is to be removed.
> > > > 
> > > > 
> > > > The vote doesn't state that.
> > > 
> > > 
> > > Doesn't need to, its apart of the tag. It did not state remove MRP, it stated remove the MRP tag.
> > 
> > 
> > There is no scoping for this clarification. The MRP tag is "MRP". That's the entire tag. Unless you're also implying `99% Lag-Free` is also part of the tag?
> 
> Don't bring the 99% Lag-Free into this. Thats our main selling point of free lag!

Come back with a warrant then.

2024-03-08 02:54 UTC, neeshacark commented
this is the most petty thing to get caught up over guys please this is why people make fun of us

2024-03-08 03:57 UTC, ToasterBiome approved these changes
looks like shit mate

2024-03-08 03:58 UTC, merged

2024-03-08 05:42 UTC, wonderinghost commented
> > > > > Considering that we stated the MRP tag, and experience being apart of that tag, experience is to be removed.
> > > > 
> > > > 
> > > > The vote doesn't state that.
> > > 
> > > 
> > > Doesn't need to, its apart of the tag. It did not state remove MRP, it stated remove the MRP tag.
> > 
> > 
> > There is no scoping for this clarification. The MRP tag is "MRP". That's the entire tag. Unless you're also implying `99% Lag-Free` is also part of the tag?
> 
> Don't bring the 99% Lag-Free into this. Thats our main selling point of free lag!

relatively, however with higher pops you get problems of constant reconnection issues. sometimes stacked after the moment of reconnection or during the game