Replaces Medical Cyborg Surgery Tools with Surgical Omni-Toolset
yogstation13/Yogstation pull request #21799
Opened 2024-04-04 20:35 UTC by Runian

# Document the changes in your pull request
Ports the medical cyborg's half of https://github.com/tgstation/tgstation/pull/82425

Adds a surgical omni-toolset which is only obtainable by being a medical cyborg.

Items can be selected by using it in-hand. Radical menu appears:
![image](https://github.com/yogstation13/Yogstation/assets/30399783/0f80afd1-f03d-4e0b-b8bd-4246c030dddd)

Replaces most/all surgery tools for medical cyborgs (and the syndicate variant) with the surgical omni-tool.

Condenses/declutters the medical cyborg's inventory from three rows to two rows.
![image](https://github.com/yogstation13/Yogstation/assets/30399783/fd7b112c-cf34-4d5b-80c6-9a4c73eb8b7c)

Removes the medical cyborg upgrade which upgraded their basic tools to advanced tools.
Adds a medical cyborg upgrade that boosts the tool speed of the omni-toolset to 0.7.

# Why is this good for the game?
Very annoying to keep the inventory up 24/7 which also takes up a ton of the screen. No longer have to do that with this.

# Testing
Items can be selected in the radical menu and properly swapped to.
Did an entire organ manipulation surgery on a human and it worked without issue.
Butchered a carp fine.

# Spriting
Deactivated omnitool as selected item:
![image](https://github.com/yogstation13/Yogstation/assets/30399783/6420a5dc-d899-4ef9-910d-857666b3d8d6)

Appearance of the omnitool in various states:
![image](https://github.com/yogstation13/Yogstation/assets/30399783/2bb49491-41e6-4149-b2e8-45e679026ff8)

# Wiki Documentation
Update cyborgs upgrades for medical cyborgs. Only need to change name and description. Mats are unchanged.

# Changelog
:cl:  
rscadd: Surgical omni-toolset. Can swap between six medical/surgery tools with a radical menu.
rscadd: Medical cyborg surgical omni-tool upgrade. Boosts the tool speed of a cyborg's omni-toolset to 0.7.
rscdel: Medical cyborg advanced surgical kit upgrade.
tweak: The cyborg medical module has their six medical/surgery tools replaced with a surgical omni-toolset.
imageadd: Omni-toolset sprites.
/:cl:

2024-04-05 09:12 UTC, neeshacark commented
i've been wanting something like this for the extreme engiborg clutter for ages now

2024-04-10 20:36 UTC, cuackles requested changes
love the idea but some of the sprites are scuffed, mostly the drill being tilts slightly and looking crunchy and the saw just being backwards compared to the others, also they look different to the standard ones, need the sprite to look a bit cleaner

2024-04-22 09:20 UTC, AMyriad commented
oh wow you got those sprites to work, nice
I forgot to suggest just doing what the toolset implant does and skip the whole "overlay on robot arm" thing

2024-04-24 19:31 UTC, cuackles approved these changes

2024-04-27 05:31 UTC, Moltijoe approved these changes

2024-04-27 05:31 UTC, merged