Fixes non-human species in VR
yogstation13/Yogstation pull request #21850
Opened 2024-04-10 16:54 UTC by TheGamerdk

# Document the changes in your pull request

Forces your species to human unless you're a synth.

Fixes ##21843

# Why is this good for the game?

Every VR mission is designed based on you being either a human or a synthetic.

# Testing

# Spriting

# Wiki Documentation

# Changelog

:cl:  
bugfix: Non-human species can now use VR without combusting
/:cl:

2024-04-11 05:36 UTC, Moltijoe requested changes
just have it change the offending species rather than all of them

2024-04-11 05:36 UTC, Moltijoe commented on code/modules/VR/vr_sleeper.dm
> +		if(!is_synth(vr_human) || !ishumanbasic(vr_human))
this would transform everyone, including synths and humans
a synth isn't a human
and a human isn't a synth

2024-04-11 12:05 UTC, MommaDragon commented
Honestly just make it do the "outfit character" command based on species and not just default. Turning everyone into humans/synths may or may not be offensive.

2024-04-15 16:24 UTC, TheGamerdk commented
> just have it change the offending species rather than all of them

All of them except human and synthetic are offending.

2024-04-17 04:05 UTC, closed without merging

2024-04-17 04:05 UTC, Moltijoe commented
no need for this pr with the other one