Adds more traitor backstories
yogstation13/Yogstation pull request #21937
Opened 2024-04-24 22:24 UTC by cowbot92

# Document the changes in your pull request

This is phase 2/4 of updating traitors to be a little more RP focused. 
Removes "The syndicate" & "The black market" factions
Adds all our current factions as choices, these are -
"Donk Co."
"Waffle Co."
"Cybersun Industries"
"Vahlen Pharmaceuticals"
"Gorlex Marauders"

# Why is this good for the game?

If we're going to be playing traitor 95% of the time, may as well spice it up a little bit, themes are pending.

# Testing

![image](https://github.com/yogstation13/Yogstation/assets/75333826/4ff3210a-e51c-462d-977f-38032e196e83)
![image](https://github.com/yogstation13/Yogstation/assets/75333826/9797dd5a-6866-4b67-b221-0e1b3f73df1d)
![image](https://github.com/yogstation13/Yogstation/assets/75333826/efdf3273-aea1-4618-b61a-bd386b4ca9c4)
![image](https://github.com/yogstation13/Yogstation/assets/75333826/a417358f-1935-4a6e-ad2e-ab8b677dc41c)
![image](https://github.com/yogstation13/Yogstation/assets/75333826/582e2c7e-46d0-4cda-bbd2-6bb6fc8ea4d0)
![image](https://github.com/yogstation13/Yogstation/assets/75333826/9599ff56-dc4c-4bfb-a976-bc84b30f289a)

# Changelog

:cl:  
rscadd: Adds new syndicate factions to select for your backstory
rscdel: Removed some syndicate factions for your backstory  

/:cl:

2024-04-26 06:56 UTC, Firewolf34 commented
This is fantastic and the flavour text is wonderful and immersive. Great idea!! Gives one a lot of inspiration on fun gameplay ideas too :)

2024-04-27 03:17 UTC, cuackles requested changes
made me look at a pr without sprites so cowbots gets canceled

2024-04-27 03:17 UTC, cuackles submitted a review, later dismissed

2024-04-29 19:54 UTC, Moltijoe approved these changes

2024-04-29 19:55 UTC, merged