Replaces book of babel tendril loot with ominous mirror
yogstation13/Yogstation pull request #21936
Opened 2024-04-24 22:07 UTC by LazennG

# Document the changes in your pull request

adds ominous mirror to the game, a new item that summons a ghost role helper akin to holoparasites.
-can move around within 20 spaces of the mirror 
-has 20 hp, does 14 brute melee damage to nonfauna enemies, which take 50. 
-can fire a projectile every couple seconds that does 5 damage to nonfauna and 20 to fauna
-can swap positions with whoever is holding the mirror every 15 seconds
-can mine basalt that it walks into similar to concussive gauntlets

-Upon 'dying,' the reflection is locked in the mirror for 20 seconds where they slowly heal
-When the user isn't conscious, the reflection can't leave the mirror
-the reflection can't pull living things
-the reflection can't manifest itself outside the mirror if it's not being held

The mirror holder can: 
-call the reflection back to the mirror 
-swap the reflection out for a different ghost for circumstances similar to where you'd do the same for a holopara

# Why is this good for the game?
book of babel sucks and i dont like a lot of ghost roles being unable to do anything without being an antag so i think this is nice.

# Testing
the entering/exiting of the mirror and the swap
![dreamseeker_O7KokzW6GM](https://github.com/yogstation13/Yogstation/assets/58535870/fb9c560b-f32c-4ebc-91b7-13c0c4dbcfbd)

being banished back to the mirror after 'dying'
![dreamseeker_PIu3rEJuL7](https://github.com/yogstation13/Yogstation/assets/58535870/e65a502e-da14-490d-9573-8fe345c595bb)

# Spriting

![mirrorcrack](https://github.com/yogstation13/Yogstation/assets/58535870/bbcbf06e-e675-43d0-9149-c7055a846b8d)
![mirrorcrackedreal](https://github.com/yogstation13/Yogstation/assets/58535870/9c13bbcc-e54d-4613-a49c-7a9d9458add0)

# Wiki Documentation

https://wiki.yogstation.net/wiki/Shaft_Miner#Necropolis_Chest_Loot
replace book of babel section with:
 A mirror that summons a fragile companion that can assist in mining and fighting, as well as swap locations with the holder. When defeated, they're returned back to the mirror for 20 seconds, and they can't exit the mirror while the holder is unconscious or when the mirror isn't held.

# Changelog

:cl:  @thegoldencat413 @Chubbygummibear @LazennG 
rscadd: Added ominous mirror
rscdel: Removed book of babel from tendril loot pool 
bugfix: fixed a few things    
imageadd: added ominous mirror sprites
/:cl:
 thanks goldencat for spriting this and helping me develop it a freaking year ago

2024-04-24 22:11 UTC, Mqiib approved these changes
I like spooky mirror sprite

2024-04-24 22:11 UTC, GDRdev commented
you know- this seems... kinda op? sorta like a budget jaunt holo

2024-04-25 00:33 UTC, LazennG commented
new changes: 
-the mirror buddy is no longer dense
-bullets pass through and do 1/4th of the damage to the buddy

2024-04-25 13:32 UTC, thegoldencat413 commented
why do the sprites suck? is the spriter stupid

2024-04-26 01:33 UTC, cowbot92 commented
im looking for the man in the mirror

2024-04-26 02:32 UTC, Chubbygummibear commented
the maid in the mirror

2024-04-27 03:04 UTC, Moltijoe requested changes

2024-04-27 03:04 UTC, Moltijoe commented on yogstation/code/modules/mining/lavaland/doppelmirror.dm
> +
add a check to prevent spamming the attack_self

2024-04-27 04:46 UTC, Moltijoe requested changes

2024-04-27 04:46 UTC, Moltijoe commented on yogstation/code/modules/mining/lavaland/doppelmirror.dm
> +
use th ecooldown system

2024-04-30 00:39 UTC, Moltijoe requested changes

2024-04-30 00:39 UTC, Moltijoe commented on yogstation/code/modules/mining/lavaland/doppelmirror.dm
> +	var/datum/action/innate/swap/swap
make sure to delete these when the mob is destroyed

2024-05-04 02:00 UTC, Moltijoe requested changes

2024-05-04 02:00 UTC, Moltijoe commented on yogstation/code/modules/mining/lavaland/doppelmirror.dm
> +	reflected.swap.Remove(reflected)
put these instead on the destroy proc of the mob itself
and make sure to qdel them after removing

2024-05-05 20:11 UTC, Moltijoe approved these changes

2024-05-05 20:11 UTC, merged