makes tar king more bearable
yogstation13/Yogstation pull request #21953
Opened 2024-04-26 09:27 UTC by LazennG

# Document the changes in your pull request

the tar king fight is the worst not good so i tried lessening that

- melee damage was changed to a consistent 40
- AP changed from 50 to 40
- Rune damage changed from 45 to 25
- removed the move that spawns a billion tar legion heads
- chaser damage changed from 25 to 10
- sword hit damage changed from 35 to 15
- no more inflicting wounds
-changed gem and crown description to be less wordy
-added "murky signal" to it

# Why is this good for the game?

reducing the damage and removing wounds helps let players win and identify all moves as "oh this is the one that kills me"

# Testing

https://streamable.com/pz36r6

# Wiki Documentation

there's no documentation on the megafauna page so i'm just writing it now https://wiki.yogstation.net/wiki/Megafauna#Types_of_Megafauna

Tar King:

![tkchase](https://github.com/yogstation13/Yogstation/assets/58535870/62611652-6939-498a-8601-23b3112d9b72)
 A monarch whose reign must end. The sword isn't for decoration's sake, as he will relentlessly chase you down to prove it. Challenging him requires the combination of three broken crystals scattered throughout his places of worship.
 
 GPS Signal
"Murky Signal"
 and 
 "Reckoning Signal" for the crystal pieces

Statistics
Difficulty: Hard

Health: 2000

Melee Damage: 40

Speed: Fast

Attacks:

The tar king's fight takes place within a large room with tar at the borders, especially by the exit. This still leaves a lot of room to run, which is very much needed to keep you from being filleted while being chased. The tar king constantly has blades orbiting him, making it difficult to stay in typical kinetic accelerator range, while unleashing stronger attacks up close. Additionally, he will often produce tar pits to teleport to later and close the distance with.

The tar king's attacks are as follows:

-Flashing a rune momentarily before hurting everything near him
-A sweeping slash that covers 3 spaces in front of him within melee range
-A long stab that reaches 3 spaces straight ahead of him
-As he takes damage, the tar king will begin planting his sword in the ground and stand there, sending out rapid blades after you for several seconds before moving again

Loot:

When the tar king is put down, he'll drop:

-The crown of the tar king ![tkc](https://github.com/yogstation13/Yogstation/assets/58535870/41bb6c8a-0513-45b7-8728-185b75bed120), which would allow the wearer to deploy 3 tar pits to teleport to later
- A demon core ![dc](https://github.com/yogstation13/Yogstation/assets/58535870/2a531ee7-8bb4-42b6-9a79-c9bf9a291a59), which produces a protective barrier when attached to outerwear, or can be used to improve the efficiency of a supermatter crystal if applied there instead.

-A primal tarstone (no fucking sprite)

https://wiki.yogstation.net/wiki/Shaft_Miner#Gems
 New gem: Primal tarstone
 icon: n/a
 points: 3000
 export price: n/a
 material: none
 dropped by: tar king
 notes: glows dark
 
 
# Changelog

:cl:  
rscdel: Removed instaloss move from tar king  
bugfix: fixed tar king wounding when it shouldnt
tweak: tweaked tar king damage and AP down
spellcheck: cut down descriptions on some tar king loot
/:cl:

2024-04-26 18:10 UTC, ToasterBiome requested changes

2024-04-26 18:10 UTC, ToasterBiome commented on yogstation/code/modules/jungleland/jungle_items.dm
> +	desc = "And old and withered crown from bones of unknown origin with a vibrant pinkish crystal embedded in the central spike. It is warm to the touch."
```suggestion
	desc = "An old and withered crown from bones of unknown origin with a vibrant pinkish crystal embedded in the central spike. It is warm to the touch."
```

2024-04-26 18:10 UTC, ToasterBiome commented on yogstation/code/modules/jungleland/jungle_megafauna.dm
> -			if(SPAWN_ATTACK)
doesnt actually remove the existence of SPAWN_ATTACK so it will still include it in it's combo and stand there like an idiot

2024-04-26 18:10 UTC, ToasterBiome commented on yogstation/code/modules/jungleland/jungle_megafauna.dm
> +/obj/item/gps/internal/tar_king
are these internal GPSs even used anymore? GPS component replaced them iirc?

2024-04-26 21:54 UTC, LazennG commented on yogstation/code/modules/jungleland/jungle_megafauna.dm
> +/obj/item/gps/internal/tar_king
![image](https://github.com/yogstation13/Yogstation/assets/58535870/104df3cc-ffa4-47cb-beca-a72111206fd0)
yeah they're used!

2024-04-29 23:44 UTC, ToasterBiome approved these changes

2024-04-30 00:40 UTC, merged