Syndicate Icemoon, finished at last
yogstation13/Yogstation pull request #22042
Opened 2024-05-16 16:35 UTC by Addust

# Document the changes in your pull request

Fixes Syndicate Icemoon xenobio being dogshit (no need for extra console, adds more pens, makes it larger), upgrades the Command wing to allow for GLORIOUS PAPERWORK, gives security an inspector booth too, adds a jukebox and other knick-knacks to the kitchen (such as MORE OIL), very slightly squishes engineering and adds a telescreen.

Would have added botany but at that point it might as well just be syndicate station with the Nanotrasen station being as relevant as a ghostrole, so instead added maintenance/construction area for the one engineer to build shit in

also gives med blood supplies and fixes cryo i think for real this time trust me

also adds an observatory so people can have binoculars i guess
![image](https://github.com/yogstation13/Yogstation/assets/80979251/d57f6812-2856-4784-b0bd-4639cc2dffe0)
![image](https://github.com/yogstation13/Yogstation/assets/80979251/63decb43-b79e-4d8f-bc71-7d4d30ba9d6f)
![image](https://github.com/yogstation13/Yogstation/assets/80979251/7194d892-f976-4e3a-a688-4ebf788e52ae)
![image](https://github.com/yogstation13/Yogstation/assets/80979251/7d927cee-295e-4bff-a3f7-0d23f1281766)
![image](https://github.com/yogstation13/Yogstation/assets/80979251/98a4a32b-366f-4b05-ad50-9ed5f17e5083)
![image](https://github.com/yogstation13/Yogstation/assets/80979251/efc7acce-d172-426a-9998-06104f3928ce)

and adds random mineral turfs near the reactor because otherwise it renders weird as fuck

# Why is this good for the game?
Fixes a few bugs in the process of doing what I do, makes xenobiology actually good, and the Syndicate needs more paperwork

# Testing

# Changelog

:cl:  
rscadd: The Syndicate has somehow managed to justify upping the budget of the Syndicate Icemoon base, installing a new command wing and xenobiology department, as well as other minor upgrades.
/:cl:

2024-05-16 22:47 UTC, neeshacark requested changes
There are two decals under this crate in maint 
![image](https://github.com/yogstation13/Yogstation/assets/44718209/423aa2a8-28d3-4685-be05-8419e08b1dcd)

railings look a bit odd, might need the arrow decals like how HOP line does it - also office needs a office chair
 ![image](https://github.com/yogstation13/Yogstation/assets/44718209/9b87484e-71f3-477b-9644-4182dba01dd0)

what exactly is the point of this window on the interior here? 
![image](https://github.com/yogstation13/Yogstation/assets/44718209/eb97a7a2-eef2-4283-96aa-731be0e7fcba)

maybe move this air alarm elsewhere and put a second window in - the lack of symmetry is killing me 
![image](https://github.com/yogstation13/Yogstation/assets/44718209/6dd22985-a17b-41ff-b825-b17f85b06a0d)

thicken the river a bit here, its getting to be a little too small of a gap
![image](https://github.com/yogstation13/Yogstation/assets/44718209/c0455e6c-23c0-4c08-97e5-a3b0147a999f)

2024-05-17 07:22 UTC, Addust commented
> There are two decals under this crate in maint ![image](https://private-user-images.githubusercontent.com/44718209/331404078-423aa2a8-28d3-4685-be05-8419e08b1dcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzA2MjIsIm5iZiI6MTcxNTkzMDMyMiwicGF0aCI6Ii80NDcxODIwOS8zMzE0MDQwNzgtNDIzYWEyYTgtMjhkMy00Njg1LWJlMDUtODQxOWUwOGIxZGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA3MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZDRlYzhlNWUwMWRkMjhlMTMwMDU1ODgxYzY0ZWZkMmRjNWUyMDY3MGMxOTg4ZDMxNDE5YzExZjIxMTE0Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WR9MA7BNUIQ5LRdnANFdmiXWC6bcLMrx7m1RJCMjmRc)
> 
> railings look a bit odd, might need the arrow decals like how HOP line does it - also office needs a office chair ![image](https://private-user-images.githubusercontent.com/44718209/331404220-9b87484e-71f3-477b-9644-4182dba01dd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzA2MjIsIm5iZiI6MTcxNTkzMDMyMiwicGF0aCI6Ii80NDcxODIwOS8zMzE0MDQyMjAtOWI4NzQ4NGUtNzFmMy00NzdiLTk2NDQtNDE4MmRiYTAxZGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA3MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1Mzc4MTc5Zjk3OTBlNjkwY2I2OTA1YjdjMTI1NmIxYmMzYzk1ODMwM2IxNTU5MmNkN2MxNTk1MzI4YzMyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HpFpv5E_aBMaOIa3RBzF9-cunKO2Ufdb3tcEA-8t7XA)
> 
> what exactly is the point of this window on the interior here? ![image](https://private-user-images.githubusercontent.com/44718209/331404483-eb97a7a2-eef2-4283-96aa-731be0e7fcba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzA2MjIsIm5iZiI6MTcxNTkzMDMyMiwicGF0aCI6Ii80NDcxODIwOS8zMzE0MDQ0ODMtZWI5N2E3YTItZWVmMi00MjgzLTk2YWEtNzMxYmUwZTdmY2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA3MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNWNkMWNmY2E2MTlmYjY3NGVjZmU5ZmJlNWUyNDQ2NWVmNWQ1ZWZjODg3NWJkNTkxM2FmY2IzM2FmY2E1MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X9h6pOF3jKg66ZYElXcLsdXs7mBMSwmoNUsLhYmuEgI)
> 
> maybe move this air alarm elsewhere and put a second window in - the lack of symmetry is killing me ![image](https://private-user-images.githubusercontent.com/44718209/331404759-6dd22985-a17b-41ff-b825-b17f85b06a0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzA2MjIsIm5iZiI6MTcxNTkzMDMyMiwicGF0aCI6Ii80NDcxODIwOS8zMzE0MDQ3NTktNmRkMjI5ODUtYTE3Yi00MWZmLWI4MjUtYjE3Zjg1YjA2YTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA3MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NjBlYTJlMGU0NTg4OWJjZjVmNzI2YzFhZTFlMWVjYzE5NzQyNmI3MjYyNWM3MzUwYTUwZGRhOTAzZmNmMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z7HtUqHdfv0AZSMILRSEjonOG2GiwydbIvYxZj2ZfNg)
> 
> thicken the river a bit here, its getting to be a little too small of a gap ![image](https://private-user-images.githubusercontent.com/44718209/331405028-c0455e6c-23c0-4c08-97e5-a3b0147a999f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzA2MjIsIm5iZiI6MTcxNTkzMDMyMiwicGF0aCI6Ii80NDcxODIwOS8zMzE0MDUwMjgtYzA0NTVlNmMtMjNjMC00YzA4LTk3ZTUtYTNiMDE0N2E5OTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA3MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljZDZjMDc5Y2EzZjM4M2VkZGJkOGE1MTVjMzc4MzQxZGZhNmI3NTJkOWI0NGYzODM1OTg3NzliZGI0MjU0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SnCwTb7V0m1j26gc78aVgPxDFZpld0hQjbQzlRc3t_0)

done, awaiting review

2024-05-17 13:19 UTC, AMyriad commented
Okay. I have a few questions, like why are there two random explosives walls outside RnD and medical storage?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/d7b6b32f-c282-41a4-82a7-41d7e83ffe38)
![image](https://github.com/yogstation13/Yogstation/assets/143908044/306afe63-9507-4194-8d50-fd5a9b472804)


Why are you adding a chokepoint to a 2-tile wide hallway for the sake of moving the linen bin for a paper bin?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/9a6ade4e-06fc-4f06-87d9-248779f4adf7)

Why are you adding a hopline/office room to an outpost where handling access and handling paperwork isn't necessary for a crew that size?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/e7a8b1f5-6134-4d0b-aff9-90dde2ebb1ce)

Why are you adding a maintenance-style room to an outpost that seems to only serve as an expansion for the sake of expansion, and provide +1 sledgehammer? Why do they need it?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/8489d229-ea87-4e2f-a31b-23edd6b4215b)

Why are you adding an inspector booth to the security area when everyone has the exact same access? What purpose does it serve? Why does the autolathe in that room need 50 sheets of metal and glass in addition to the materials present elsewhere?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/9b0d53c3-1213-4f3d-a0f6-a6e0f9915400)

Why are these covered in firelocks?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/5b8784c2-b6b9-4d00-9b22-b1185892d796)
![image](https://github.com/yogstation13/Yogstation/assets/143908044/c1e77759-b22b-4753-94d7-ca4349b7b29b)

Why do these windows have two sets of shutters/blast doors?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/0e9af984-5957-493f-85a4-c4b88aec71ca)
![image](https://github.com/yogstation13/Yogstation/assets/143908044/2d11f417-415c-48bb-bd03-830899c11574)
![image](https://github.com/yogstation13/Yogstation/assets/143908044/9d3bfabc-8173-457b-8e3d-abcd5652a134)

Why is there a second observation room? Why is it inside the base? How much do you think they're going to be able to see from there?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/2a4bf57b-2e92-41cc-bd64-9e53f5b9baff)

2024-05-17 13:33 UTC, AMyriad reviewed
Okay. I have a few questions, like why are there two random explosives walls outside RnD and medical storage?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/d7b6b32f-c282-41a4-82a7-41d7e83ffe38)
![image](https://github.com/yogstation13/Yogstation/assets/143908044/306afe63-9507-4194-8d50-fd5a9b472804)


Why are you adding a chokepoint to a 2-tile wide hallway for the sake of moving the linen bin for a paper bin?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/9a6ade4e-06fc-4f06-87d9-248779f4adf7)

Why are you adding a hopline/office room to an outpost where handling access and handling paperwork isn't necessary for a crew that size?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/e7a8b1f5-6134-4d0b-aff9-90dde2ebb1ce)

Why are you adding a maintenance-style room to an outpost that seems to only serve as an expansion for the sake of expansion, and provide +1 sledgehammer? Why do they need it?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/8489d229-ea87-4e2f-a31b-23edd6b4215b)

Why are you adding an inspector booth to the security area when everyone has the exact same access? What purpose does it serve? Why does the autolathe in that room need 50 sheets of metal and glass in addition to the materials present elsewhere?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/9b0d53c3-1213-4f3d-a0f6-a6e0f9915400)

Why are these covered in firelocks?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/5b8784c2-b6b9-4d00-9b22-b1185892d796)
![image](https://github.com/yogstation13/Yogstation/assets/143908044/c1e77759-b22b-4753-94d7-ca4349b7b29b)

Why do these windows have two sets of shutters/blast doors?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/0e9af984-5957-493f-85a4-c4b88aec71ca)
![image](https://github.com/yogstation13/Yogstation/assets/143908044/2d11f417-415c-48bb-bd03-830899c11574)
![image](https://github.com/yogstation13/Yogstation/assets/143908044/9d3bfabc-8173-457b-8e3d-abcd5652a134)

Why is there a second observation room? Why is it inside the base? How much do you think they're going to be able to see from there?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/2a4bf57b-2e92-41cc-bd64-9e53f5b9baff)

Why are there so many firelocks here? Why are there any at all? Why do these cells need reinforced windoors?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/0d714b83-7b8e-4027-99bc-2cd9b84012dd)

2024-05-17 14:40 UTC, Addust commented
> Okay. I have a few questions, like why are there two random explosives walls outside RnD and medical storage? ![image](https://private-user-images.githubusercontent.com/143908044/331584683-d7b6b32f-c282-41a4-82a7-41d7e83ffe38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTY5MzIsIm5iZiI6MTcxNTk1NjYzMiwicGF0aCI6Ii8xNDM5MDgwNDQvMzMxNTg0NjgzLWQ3YjZiMzJmLWMyODItNDFhNC04MmE3LTQxZDdlODNmZmUzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTdlYTNjYWZmMTkzYWRhMmIyZjg2ZTkxNDM5YTg4NjY1Y2ZiN2E1YjYwMDAyOTJiMmVlMWMxN2Q2ZmQxZjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1P4JYMTZaigC1MxvaYYyBNNzPfSXXojC4Mq1uTa41CU) ![image](https://private-user-images.githubusercontent.com/143908044/331606150-306afe63-9507-4194-8d50-fd5a9b472804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTY5MzIsIm5iZiI6MTcxNTk1NjYzMiwicGF0aCI6Ii8xNDM5MDgwNDQvMzMxNjA2MTUwLTMwNmFmZTYzLTk1MDctNDE5NC04ZDUwLWZkNWE5YjQ3MjgwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDBmMzIzNjY3YTQxZWNiNmVkMGUwYzkzMmNmOGMyY2YwODIzYTZkYjk4ZmRlMGE1ZWNiZDI1MDdhZDcxYTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MUyeF6Or2cx-3lbeUTtUTP68mcb7AAcgJ6ewjR1kwII)
> 
> Why are you adding a chokepoint to a 2-tile wide hallway for the sake of moving the linen bin for a paper bin? ![image](https://private-user-images.githubusercontent.com/143908044/331584959-9a6ade4e-06fc-4f06-87d9-248779f4adf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTY5MzIsIm5iZiI6MTcxNTk1NjYzMiwicGF0aCI6Ii8xNDM5MDgwNDQvMzMxNTg0OTU5LTlhNmFkZTRlLTA2ZmMtNGYwNi04N2Q5LTI0ODc3OWY0YWRmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTJmMjdlODJjYzExYWIwOWVjMTBiZmNjNTNjODkxODFhNjIyMWY2YjE4NTZjMjNlYjZkOGZkN2UyZWU3ZDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cuDzH53vRDdyyHhJ_Pf_JSZf3Y8r-R-9O_9-wNgPzms)
> 
> Why are you adding a hopline/office room to an outpost where handling access and handling paperwork isn't necessary for a crew that size? ![image](https://private-user-images.githubusercontent.com/143908044/331585544-e7a8b1f5-6134-4d0b-aff9-90dde2ebb1ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTY5MzIsIm5iZiI6MTcxNTk1NjYzMiwicGF0aCI6Ii8xNDM5MDgwNDQvMzMxNTg1NTQ0LWU3YThiMWY1LTYxMzQtNGQwYi1hZmY5LTkwZGRlMmViYjFjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWEyMjk4ODE5ODNkZjRiMGIwMTkyNjEyNTZmNTJlMTI2OWI2OTI3OWViOGQ5YmRmMmMzMGUxZGZlYWIwMWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EHzasW-K3Z0klKicbULXaQhATu-pK2XtWW0DqyS1Sdo)
> 
> Why are you adding a maintenance-style room to an outpost that seems to only serve as an expansion for the sake of expansion, and provide +1 sledgehammer? Why do they need it? ![image](https://private-user-images.githubusercontent.com/143908044/331601984-8489d229-ea87-4e2f-a31b-23edd6b4215b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTY5MzIsIm5iZiI6MTcxNTk1NjYzMiwicGF0aCI6Ii8xNDM5MDgwNDQvMzMxNjAxOTg0LTg0ODlkMjI5LWVhODctNGUyZi1hMzFiLTIzZWRkNmI0MjE1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDE1ZGEwM2I0MTljMDAyZjY5YjhlMmI5ODQ5ZmNiYWYxZTgwOTQxZDA4NzJmYzQwNDFmZTMzYjczNmRlOWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-2i8kHKeuxq9iUbzxdvVR43h1SrrbO9POKk--itLb_M)
> 
> Why are you adding an inspector booth to the security area when everyone has the exact same access? What purpose does it serve? Why does the autolathe in that room need 50 sheets of metal and glass in addition to the materials present elsewhere? ![image](https://private-user-images.githubusercontent.com/143908044/331602894-9b0d53c3-1213-4f3d-a0f6-a6e0f9915400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTY5MzIsIm5iZiI6MTcxNTk1NjYzMiwicGF0aCI6Ii8xNDM5MDgwNDQvMzMxNjAyODk0LTliMGQ1M2MzLTEyMTMtNGYzZC1hMGY2LWE2ZTBmOTkxNTQwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzdiZGE1MGQwYmNkYWJjNmQ5NzljMGIyYTJkZDZjMmE5NmE5ZWI0OTM2ZWQ2YWE4MTA5M2IyNzMxODJhZDllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q6GAX1OmKo3v5TKH6VekKj8tpdP_7MeTF9jFd9fL6zo)
> 
> Why are these covered in firelocks? ![image](https://private-user-images.githubusercontent.com/143908044/331604684-5b8784c2-b6b9-4d00-9b22-b1185892d796.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTY5MzIsIm5iZiI6MTcxNTk1NjYzMiwicGF0aCI6Ii8xNDM5MDgwNDQvMzMxNjA0Njg0LTViODc4NGMyLWI2YjktNGQwMC05YjIyLWIxMTg1ODkyZDc5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTVlNmYyMGZlMGNjNjRkYjJiMmRiNmYyMmZhNWViMjFlNjkyMTdhNGJlOGIzMThiYjcwNzQ3YjBiMjdmZDI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8jl78wBKQmZrgAt0KQr9hZcTpvjzVd7E29swfUas-Ro) ![image](https://private-user-images.githubusercontent.com/143908044/331604781-c1e77759-b22b-4753-94d7-ca4349b7b29b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTY5MzIsIm5iZiI6MTcxNTk1NjYzMiwicGF0aCI6Ii8xNDM5MDgwNDQvMzMxNjA0NzgxLWMxZTc3NzU5LWIyMmItNDc1My05NGQ3LWNhNDM0OWI3YjI5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmVlZWRlOTE3YjQ0OTY4YzBiOTJmOTIzMjFlNTY4NWI4YWE0ZmQ2Yzk0N2M0NWY0NTVjNTc2MjdjMmU5YzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZOu96w_MOqE5iLgJaPQmWAk7ycpka-7JZIPKtngejEw)
> 
> Why do these windows have two sets of shutters/blast doors? ![image](https://private-user-images.githubusercontent.com/143908044/331604940-0e9af984-5957-493f-85a4-c4b88aec71ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTY5MzIsIm5iZiI6MTcxNTk1NjYzMiwicGF0aCI6Ii8xNDM5MDgwNDQvMzMxNjA0OTQwLTBlOWFmOTg0LTU5NTctNDkzZi04NWE0LWM0Yjg4YWVjNzFjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3 [...]

2024-05-17 14:41 UTC, Addust commented
observation room is the result of another spark of my mind, i just wanted more binocs and an excuse for it

2024-05-17 14:48 UTC, Addust commented
justification for the hopline is uhhh
- i felt like it
- gives a dedicated area for the fax machine and photocopier
- the syndicate could definitely use more paperwork
- i can remove or reduce if really wanted

construction area:
- really just an expanded barricade to keep vault behind at least 2 walls
- was once the botany department but that was axed mid-development of this version of the base, i can remove it if wanted

2024-05-19 03:08 UTC, neeshacark approved these changes

2024-05-19 03:10 UTC, neeshacark commented
my stuff is covered, imo extra firelocks are probably fine given how difficult it is to fix a flood of any kind on planets. up to myriad

2024-05-20 10:52 UTC, merged