Adjusts the effects of Stabilized red and Stabilized sepia slime cores
yogstation13/Yogstation pull request #22048
Opened 2024-05-17 22:24 UTC by cowbot92

# Document the changes in your pull request

Adds a 1.5x damage modifier for brute & burn to both Stabilized red and sepia slime cores which are removed when dropped.

# Why is this good for the game?

Move speed is a potent tool in this game, and the effects you gain from these cores warrant some drawbacks. I did not want to nerf the actual speed they grant, as I feel like this is a suitable trade-off, making you more like a glass-cannon in certain cases.

# Testing

With 1 core, from a toolbox you will take 22.5 brute from a toolbox (with base of 15), with both cores equipped it will become 32.8 (with no other physiology modifiers on humans)

With 1, from a welding tool you will take 18 burn from a welder (from a base of 12), with both cores equipped it will become 27 (with no other physiology modifiers on humans)

# Wiki Documentation

Add the "you take extra burn/brute" damage part to the wiki

# Changelog

:cl:  

tweak: Adds brute & burn modifiers to Red & Sepia Stabilized slime cores.

/:cl:

2024-05-17 22:24 UTC, ThePissGuy commented
stabilized red speed is barely noticeable

2024-05-17 22:28 UTC, cowbot92 commented
im just nuking them

2024-05-18 00:03 UTC, Mqiib commented
Honestly I think if you just added the stamina modifier that'd be enough.

2024-05-19 18:13 UTC, Mqiib commented
![image](https://github.com/yogstation13/Yogstation/assets/43766432/8ac6c84e-623b-4479-932f-7f9068970ea4)

Hey so could you also actually make it so the sepia slows you down as well as speeds you up because, according to the code here, it only applies a -1 or a 0 modifier.

2024-05-20 04:08 UTC, cowbot92 commented
> ![image](https://private-user-images.githubusercontent.com/43766432/331892059-8ac6c84e-623b-4479-932f-7f9068970ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzIyMjQsIm5iZiI6MTcxNjE3MTkyNCwicGF0aCI6Ii80Mzc2NjQzMi8zMzE4OTIwNTktOGFjNmM4NGUtNjIzYi00NDc5LTkzMmYtN2Y5MDY4OTcwZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAyMjUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZThjYzU2ZjMzZDg0MmFmZmQyZDc4ZjEyYjRlN2RhZmFmMWQ2NjVmZmYwYjIzMTNkMTAyMDNhYWQ0N2Y5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYvTiVj-9u-kdIVogtgSw6qw6l7qXCr_YGwplSDnueA)
> 
> Hey so could you also actually make it so the sepia slows you down as well as speeds you up because, according to the code here, it only applies a -1 or a 0 modifier.

Adjusts as requested

2024-05-20 10:49 UTC, Moltijoe requested changes
Damage modifications are too heavy handed
Stamina mod is totally fine though
Maybe include stunmod?
Perhaps look at arrhythmic dagger for sepia, that way it feels evel less consistent

2024-05-20 13:28 UTC, cowbot92 commented
> arrhythmic dagger

Removed the damage modifiers, added the stun modifier. Additionally adjusted the sepia code to work exactly like the knife (uses rand now instead of some weird psuedo rand)

2024-05-20 19:20 UTC, Moltijoe approved these changes

2024-05-20 19:20 UTC, merged