Adds 5 new ship templates for shipbreaking
yogstation13/Yogstation pull request #22047
Opened 2024-05-17 17:31 UTC by cowbot92

# Document the changes in your pull request

Adds 5 new ship templates:

The Chapel Ship
The Alien Ship
The Bathroom Ship
Several Old Escape Pods
The Stealth Cutter Ship

# Why is this good for the game?

More variety keeps people from getting bored

<details closed>
<summary>Ship Layouts</summary>
<br>
Chapel
![image](https://github.com/yogstation13/Yogstation/assets/75333826/8510de87-a170-4b7f-8e7f-1304e49e07f0)
Alien
![image](https://github.com/yogstation13/Yogstation/assets/75333826/7a74aaa5-0f18-4cdb-95de-79a97a2649c4)
Escape Pods
![image](https://github.com/yogstation13/Yogstation/assets/75333826/8ff64fc8-9e42-47bd-b9a5-ead3c6014248)
The Bathroom (read as if said by murdoc from the gorillaz)
![image](https://github.com/yogstation13/Yogstation/assets/75333826/2620ef34-f54c-4704-bf21-44731daf881c)
Stealth Cutter
![image](https://github.com/yogstation13/Yogstation/assets/75333826/acffb572-26e0-431d-977a-f0ef5e1b90f0)

</details>

# Testing

Follows the same format as the other ship spawns

# Wiki Documentation

Wiki PLEASE return my calls

# Changelog

:cl:  
rscadd: Adds 5 new ships to break!
mapping: Adds 5 new ships to break!

/:cl:

2024-05-17 17:32 UTC, Addust commented
"stealth cutter"



mmm
yes
sure
totally
definitely
surely
certainly
not just a small syndicate ripoff of the shiptest osprey

which is
definitely
totally
certainly
not renowned for
a peculiar hull design

2024-05-17 17:37 UTC, cowbot92 commented
> "stealth cutter"
> 
> mmm yes sure totally definitely surely certainly not just a small syndicate ripoff of the shiptest osprey
> 
> which is definitely totally certainly not renowned for a peculiar hull design

yes I made it look like a penis those are stealthy

2024-05-17 18:06 UTC, ToasterBiome requested changes
No alien tools

2024-05-17 18:07 UTC, cowbot92 commented
> No alien tools

removed

2024-05-18 00:26 UTC, Mqiib commented
Suggestion: add a list of notable objects on each shuttle in the pr next time you add more

2024-05-18 01:17 UTC, cowbot92 commented
> Suggestion: add a list of notable objects on each shuttle in the pr next time you add more

ok

2024-05-19 03:12 UTC, neeshacark commented
> > "stealth cutter"
> > mmm yes sure totally definitely surely certainly not just a small syndicate ripoff of the shiptest osprey
> > which is definitely totally certainly not renowned for a peculiar hull design
> 
> this is just what peak stealth ships look like

preparing for stealth penetration - i mean infiltration

2024-05-20 02:17 UTC, ToasterBiome approved these changes

2024-05-20 15:10 UTC, merged