Adds Shipbreaking to Gax, Fixes security reception area
yogstation13/Yogstation pull request #22053
Opened 2024-05-18 07:34 UTC by wonderinghost

# Document the changes in your pull request

adds ship breaking to gax. up in the garden next to sec
![image](https://github.com/yogstation13/Yogstation/assets/88801435/a9f19e93-84e0-4733-8d9a-120224a6857b)

fixes security reception windoors
![image](https://github.com/yogstation13/Yogstation/assets/88801435/0f9dbf97-a287-4c69-a2a1-234617d6dd3e)

updates mapmerge tool becuase it wasnt working for some odd reason

# Why is this good for the game?
since ship breaking was added to box its best to quickly start moving the feature over to the other maps

# Testing
checked when running the map 

# Changelog

:cl:  

mapping: adds shipbreaking to the top of the garden on gax (removes double light switch in garden also)
mapping: fixes security reception windoors covering the bell on Gax
tweak: updates mapmerge.py to fix a weird error
/:cl:

2024-05-18 17:18 UTC, ToasterBiome requested changes
make it normal airlocks with the airlock controller, no tiny fans

2024-05-18 20:06 UTC, AMyriad reviewed
Very nice work. I like especially where you've chosen to put the area and how you've built it. Though I want to see the placement of things more match the standards of #22043 (when that gets merged), like putting the recycler outside rather than in the room.
Also I'm not really digging the two reinforced floors, they look a tad random.

Will give an actual review sometime later...probably

2024-05-18 20:45 UTC, wonderinghost commented
I can get the floors once I get home. However I'm against the outside recycler unless you can hook up it via wire instead of zoning 1 tile

2024-05-23 07:07 UTC, AMyriad requested changes
1. Use normal stairs here, and apply ramp_corner shadows to make it look elevated properly (look how the stairs in the bar on Box are shaded)
![image](https://github.com/yogstation13/Yogstation/assets/143908044/e7b8df9c-7c3a-4011-9771-b2adbb1e02c8)
(Example of normal stairs (but not upside down))
![image](https://github.com/yogstation13/Yogstation/assets/143908044/5d0301f7-ea5f-4920-bb53-646bb6bf3fce)

2. Put da recycler outside, see how Box does it for reference

3. I recommend putting lattice in the middle here to make it look more structurally sound, and to put more holes in the middle of the catwalks near the airlocks
![image](https://github.com/yogstation13/Yogstation/assets/143908044/3748da63-0308-47c3-93f3-386aa59811aa)

2024-05-23 07:12 UTC, wonderinghost commented
I'll see what I can do about the recycler in the morning. If I can't use straight wiring then this is going to get limbo'd until it can

I'm not placing 5 random zone sections out in space for a grinder box and recycler

2024-05-25 18:22 UTC, neeshacark commented
i am of the opinion cowbot's is more logically placed - by evac same as box. closing in 24.

2024-05-26 00:05 UTC, neeshacark commented
will be closing now since cowbot fixed his fast

2024-05-26 00:05 UTC, closed without merging

2024-05-26 00:08 UTC, wonderinghost commented
No fuck off I got this completed. I didn't place it there so antags don't b rush command 

It's just stuck in review limbo
@AMyriad @ToasterBiome I'm looking at you two