Return of the Charcoal Nerf (Hobo returning to Coder Status V.2)
yogstation13/Yogstation pull request #22055
Opened 2024-05-18 21:21 UTC by Therandomhoboo

# Document the changes in your pull request

Stab number 2 at the charcoal nerf. So I've had some words with peeps in discord and come to the conclusion of reducing its effectiveness, increasing its toxin heal and increasing the effectiveness of Calomel so it gets used more despite it giving toxin damage

So as following:
Charcoal: 1 purge rate reduce to 0.5, Toxin heal increased from 2 --> 3.5
Calomel: Purge rate increased to 5 from 2.5

# Why is this good for the game?

Stops charcoal hoarding, makes chem make better purges, makes poisons, chems and drinks more viable early game than straight up getting told no because charcoal dumped it all out before it even tickled.

# Testing

Yee

# Wiki Documentation

Change Charcoal effectiveness to 0.5, toxin heal to 3.5, Calomel purge to 5 instead of 2.5

# Changelog

:cl:  

tweak: Charcoal purge rate reduced to 0.5 from 1
tweak: Charcoal Toxin heal increased to 3.5 from 2
tweak: Calomel Purge rate increased to 5 from 2.5

/:cl:

2024-05-20 01:05 UTC, Moltijoe commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	if(M.reagents.remove_reagent/R == TRUE)
do you uhh, want help with that?

2024-05-20 16:24 UTC, Majkl-J requested changes
I fucked up here, just send the src, more versatile

2024-05-20 16:24 UTC, Majkl-J commented on code/modules/reagents/chemistry/reagents.dm
> +    return
```suggestion
    SEND_SIGNAL(L, COMSIG_MOB_ADD_REAGENT, src)
    return
```
```suggestion
    SEND_SIGNAL(L, COMSIG_MOB_ADD_REAGENT, src.type)
    return
```

2024-05-20 16:24 UTC, Majkl-J commented on code/modules/reagents/chemistry/reagents.dm
> +    return
```suggestion
    SEND_SIGNAL(L, COMSIG_MOB_REMOVE_REAGENT, src)
    return
```
```suggestion
    SEND_SIGNAL(L, COMSIG_MOB_REMOVE_REAGENT, src.type)
    return
```

2024-05-20 17:13 UTC, Majkl-J requested changes

2024-05-20 17:13 UTC, Maia-J commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +		affected.adjustToxLoss(2.5*REM, 0)
```suggestion
	affected.adjustToxLoss(2.5*REM, 0)
```

2024-05-20 17:48 UTC, Majkl-J requested changes
Woops, again

2024-05-20 17:48 UTC, Majkl-J commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	return	..()
```suggestion
/datum/reagent/medicine/calomel/on_mob_delete(mob/living/L)
	UnregisterSignal(L,	COMSIG_MOB_REMOVE_REAGENT)
	return	..()
```

2024-05-20 17:51 UTC, Therandomhoboo commented
> Woops, again

Kek

2024-05-20 18:56 UTC, Therandomhoboo commented
So with how it works now. You get the tox damage after the chemical that it is purging is finished. With that in mind, I think personally raising tox damage a little would be best but as of current it does work.

2024-05-22 07:57 UTC, Moltijoe requested changes
This can be weaponized to kill someone in seconds
We've already discussed this, just requesting changes so someone like manatee cant merge

2024-05-31 04:17 UTC, Moltijoe approved these changes

2024-05-31 04:17 UTC, merged