Reduces the duke nukem announce from .05 to .2
yogstation13/Yogstation pull request #22081
Opened 2024-05-21 21:15 UTC by cowbot92

# Document the changes in your pull request

Reduces the announcer from .05 to .2 like the other ones

# Why is this good for the game?

Something in the code is doing the % wrong so instead of 5% chance its like 50% or more. This should put it in line with the rest

# Testing

I wouldnt make this if i didnt open a private server 10 times to hear duke

# Changelog

:cl:  

tweak:  tweaks how often duke nukem talks to us

/:cl:

2024-05-21 23:25 UTC, TheGamerdk requested changes
Change /datum/station_trait/announcement_duket to /datum/station_trait/announcement_duke on line 75

2024-05-21 23:25 UTC, TheGamerdk commented on code/datums/station_traits/neutral_traits.dm
> +	weight = 0.2
```suggestion
	weight = 0.05
```

2024-05-21 23:38 UTC, Yarinoi commented
whoops
but frankly, is this REALLY a flaw that needs to be corrected?

2024-05-22 00:57 UTC, cowbot92 commented on code/datums/station_traits/neutral_traits.dm
> +	weight = 0.2
Changes made

2024-05-22 09:56 UTC, TheGamerdk approved these changes

2024-05-22 09:56 UTC, merged