Fixes vines
yogstation13/Yogstation pull request #22129
Opened 2024-05-30 04:29 UTC by SapphicOverload

# Document the changes in your pull request

Fixes a number of bugs with vines, and makes thick clothing able to protect against thorny and toxic vines.

# Why is this good for the game?
Fixes bugs, adds counterplay to two vine types that previously had no counter.

# Testing
![image](https://github.com/yogstation13/Yogstation/assets/93578146/3975332d-31b5-41a7-ad85-28acb134978b)

# Changelog

:cl:  
tweak: Thorny and toxic vines now take protective clothing into account
bugfix: Fixed vines growing outside on the icemoon
bugfix: Fixed vines spreading through solid windows
bugfix: Fixed runtime error when clicking on vines
/:cl:

2024-05-30 19:59 UTC, warface1234455 commented
fixes #22061

2024-05-31 04:23 UTC, Moltijoe approved these changes

2024-05-31 04:23 UTC, Moltijoe commented on code/modules/events/spacevine.dm
> +		crosser.apply_damage(5 * (100 - crosser.getarmor(null, BIO)) / 100)
```suggestion
		crosser.apply_damage(5 * (100 - crosser.getarmor(null, BIO)) / 100, TOX)
```

2024-05-31 04:23 UTC, Moltijoe requested changes
ah sorry, i mean this

2024-05-31 07:00 UTC, Moltijoe approved these changes

2024-05-31 07:04 UTC, merged