Musket 2.0: All plugged up
yogstation13/Yogstation pull request #22140
Opened 2024-05-31 20:25 UTC by Scrambledeggs00

# Document the changes in your pull request

This PR makes some minor changes to the cartridges and gun version of the musket, and also adds in the plug bayonet and the plugged maintenance musket.

For cartridges, instead of needing cloth, they now need a strip of torn cloth. This makes the ammo easier to craft as cloth can be hard to come by, especially when once all of dorm's blankets are gone. They also now release smoke/bad rather than just smoke, so best to not stay in the cloud without internals.

For the musket, it now comes unloaded when crafted, meaning no free cartridge.

Finally, the plugged maintenance musket is essentially a spear. To make it, you will need to craft the plug bayonet, which only works with the musket. Using it on the musket will delete the musket and the bayonet and create a plugged maintenance musket, which can then be turned back into a musket and plug bayonet by using a screwdriver on it. To do this, the musket must first be unloaded and have no bayonet attached. This information is shown through bubble popups and in the items' descriptions as seen in the test video. Stat wise, the plug bayonet is just a reskinned knife that cannot be used as a normal bayonet. The plugged maintenance musket is a makeshift spear without the integrity system and with a lower throw speed and damage. It does 10 force, 10 throw force, and has a throw speed of 2. Like the spear, it gains an extra 8 damage when wielded for a total of 18 force.

Changes based around hwseo7's comments in development-public

# Why is this good for the game?

Adds a cool and unique interaction, along with making the ammo easier to craft.

# Testing

Video showing the plug bayonet and plugged musket:
https://www.youtube.com/watch?v=g0bsG7He0Wg

Pictures showing the plug bayonet in crafting menu and the new cartridge recipe:
![image](https://github.com/yogstation13/Yogstation/assets/113869252/90020408-b5b5-4d47-84f9-b9f0a8ea1f34)
![image](https://github.com/yogstation13/Yogstation/assets/113869252/531d0227-34d1-47b2-98d3-0f316e7a840b)

# Spriting

Mob sprites:
![PlugMaintMusketHands](https://github.com/yogstation13/Yogstation/assets/113869252/020d51f6-28df-44c2-b77e-baed04178b1c)

Object sprites:
![PlugMaintMusketObject](https://github.com/yogstation13/Yogstation/assets/113869252/5a2a3956-1b5d-462e-95fd-dd24654af511)

The plug bayonet uses the mob sprites of the kitchen knife.

# Wiki Documentation

The plug bayonet is made with a kitchen knife and one wooden plank and requires a wrench and screwdriver. It has the same stats as a kitchen knife, except that it cannot be used as a bayonet.

The plugged maintenance musket is made by applying a plug bayonet to a maintenance musket. It has the same stats as a spear, but does not have a chance to break and only has a throw force of 10 and a throw speed of 2. You can revert it back by using a screwdriver on it.

# Changelog

:cl:  
rscadd: Added plug bayonet and plugged maintenance musket  
tweak: Changed recipe for cartridges, effect switched from smoke to smoke/bad, and muskets now start unloaded
imageadd: Added sprites for new items
spellcheck: Fixed some grammar errors in the musket's reloading code
/:cl:

2024-05-31 20:29 UTC, MommaDragon commented
No more free cartridges from spamming muskets.

2024-05-31 21:00 UTC, Beeper-Skeeper commented
Own a musket for home defense, since that's what the founding fathers intended. Four ruffians break into my house. "What the devil?" As I grab my powdered wig and Kentucky rifle. Blow a golf ball sized hole through the first man, he's dead on the spot. Draw my pistol on the second man, miss him entirely because it's smoothbore and nails the neighbors dog. I have to resort to the cannon mounted at the top of the stairs loaded with grape shot, "Tally ho lads" the grape shot shreds two men in the blast, the sound and extra shrapnel set off car alarms. Fix bayonet and charge the last terrified rapscallion. He Bleeds out waiting on the police to arrive since triangular bayonet wounds are impossible to stitch up. Just as the founding fathers intended.

2024-06-05 19:08 UTC, cuackles approved these changes

2024-06-08 23:55 UTC, Moltijoe requested changes

2024-06-08 23:55 UTC, Moltijoe commented on code/game/objects/items/two_handed/spears.dm
> +	..()
```suggestion
	return ..()
```

2024-06-08 23:55 UTC, Moltijoe commented on code/game/objects/items/two_handed/spears.dm
> +	)
shouldn't need this, spears already come with two_handed, unless you specifically want to modify the damage_low and damage_high, which i don't think is really needed
also, make sure it doesn't break after some use, since i'm pretty sure regular spears do that

2024-06-09 01:16 UTC, Scrambledeggs00 commented on code/game/objects/items/two_handed/spears.dm
> +	)
I've been drinking so I may be misremembering, but I think the low high stuff is how much damage the spear takes on hitting stuff. If so then this change is necessary to keep it from breaking like the normal spear.

2024-06-09 01:17 UTC, Scrambledeggs00 commented on code/game/objects/items/two_handed/spears.dm
> +	)
![image](https://github.com/yogstation13/Yogstation/assets/113869252/3934db9b-6644-42e6-a892-381d648bcb8c)
Yea it seems so.

2024-06-09 20:32 UTC, Moltijoe commented on code/game/objects/items/two_handed/spears.dm
> +	)
Wait, thats what that stat is? Weird, but alright

2024-06-09 20:32 UTC, Moltijoe approved these changes

2024-06-09 20:32 UTC, merged