[BOUNTY] Liquids try #3: Return of the pee
yogstation13/Yogstation pull request #22169
Opened 2024-06-03 21:16 UTC by ToasterBiome

# Document the changes in your pull request

Ports some of https://github.com/Monkestation/Monkestation2.0/commit/8bbcd47bcbef614311a5a1a2819c25fff16e8709
https://github.com/Monkestation/Monkestation2.0/pull/2072

fulfills https://forums.yogstation.net/threads/300-liquid-simulation-tgcode-edition-ss13-server.27154/

Adds liquids from Monkestation. Adds some basic ocean turfs.

Things this does have:
Liquids
Interaction with liquids
Admin ability to add/remove liquids
Drains?

Things this does not have:
TG plumbing (further PR)
Ocean generation (further PR)

# Why is this good for the game?

More stuff to do and interact with = more fun

# Testing
![dreamseeker_z2PxOVK3J2](https://github.com/yogstation13/Yogstation/assets/5091394/ee57b591-2add-4fed-bb6e-1f13265f2426)
![dreamseeker_o7TSK5nLuC](https://github.com/yogstation13/Yogstation/assets/5091394/3926a309-3be4-46f5-ad11-740f8a3f20f2)

# Wiki Documentation

will fill out

# Changelog

:cl:  
rscadd: adds liquids
/:cl:

2024-06-03 21:17 UTC, neeshacark commented
finally, it is our time

2024-06-03 21:20 UTC, cowbot92 commented
im gonna pee so hard

2024-06-03 21:22 UTC, AMyriad commented
one step closer to ocean station inshallah

2024-06-03 21:24 UTC, wonderinghost commented
there better be jarate gameplay

2024-06-04 00:50 UTC, Moltijoe commented
Is there any way to tell a difference between a liquid and gas at a glance? They both just seem to be translucent overlays

2024-06-04 02:37 UTC, neeshacark commented
> Is there any way to tell a difference between a liquid and gas at a glance? They both just seem to be translucent overlays

its pretty obvious

2024-06-04 03:02 UTC, Chubbygummibear commented
![check out how hard i can](https://github.com/yogstation13/Yogstation/assets/46236974/340f3f96-e011-41a0-8fef-6d103ebdfeec)

2024-06-04 05:47 UTC, warface1234455 commented
> ![check out how hard i can](https://private-user-images.githubusercontent.com/46236974/336290056-340f3f96-e011-41a0-8fef-6d103ebdfeec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODAzMzgsIm5iZiI6MTcxNzQ4MDAzOCwicGF0aCI6Ii80NjIzNjk3NC8zMzYyOTAwNTYtMzQwZjNmOTYtZTAxMS00MWEwLThmZWYtNmQxMDNlYmRmZWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA1NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YTg2ODE1NmUxNWJmNzk4ZGIxOGJmMjdlM2MzOTkyOTYxMjcyNGQwNzE0ZTVmYTk5MTc3YmYxOGIxMzEwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lUK-1CSjv_97MrTRlRddNUD7CTD0ppueIbEVexqUlvs)

bro got a third stick

2024-06-04 06:29 UTC, Chubbygummibear commented
> > ![check out how hard i can](https://private-user-images.githubusercontent.com/46236974/336290056-340f3f96-e011-41a0-8fef-6d103ebdfeec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODAzMzgsIm5iZiI6MTcxNzQ4MDAzOCwicGF0aCI6Ii80NjIzNjk3NC8zMzYyOTAwNTYtMzQwZjNmOTYtZTAxMS00MWEwLThmZWYtNmQxMDNlYmRmZWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA1NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YTg2ODE1NmUxNWJmNzk4ZGIxOGJmMjdlM2MzOTkyOTYxMjcyNGQwNzE0ZTVmYTk5MTc3YmYxOGIxMzEwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lUK-1CSjv_97MrTRlRddNUD7CTD0ppueIbEVexqUlvs)
> 
> bro got a third stick

it's called a dixel

2024-06-04 17:00 UTC, Beeper-Skeeper commented
PISS

2024-06-04 17:00 UTC, Beeper-Skeeper commented
now we need Jarate

2024-06-04 20:54 UTC, Moltijoe commented on yogstation/code/modules/liquids/height_floors.dm
> +/turf/open/floor/iron/pool/rust_heretic_act()
Where is this declared

2024-06-05 19:10 UTC, cuackles approved these changes

2024-06-06 19:14 UTC, ToasterBiome commented on yogstation/code/modules/liquids/height_floors.dm
> +/turf/open/floor/iron/pool/rust_heretic_act()
> Where is this declared

right there

2024-06-08 07:36 UTC, Moltijoe commented on yogstation/code/modules/liquids/height_floors.dm
> +/turf/open/floor/iron/pool/rust_heretic_act()
gotcha, sure why not

2024-07-15 21:45 UTC, Moltijoe commented
water still gets stuck in dense structures
![image](https://github.com/user-attachments/assets/493a3e7b-bb27-4e14-a1aa-db27419c34d4)

space doesn't drain water
![image](https://github.com/user-attachments/assets/c7a5fbec-ea06-43bc-8298-b3b39abdabf1)

also, breaking welding fuel tanks and water tanks should release the respective liquid

water vapour should maybe condense into water puddles rather than making the floor wet
hell, the old "wet floor" system should be replaced with reagent puddles
![image](https://github.com/user-attachments/assets/48fc7b29-52f6-4e4d-b1ec-b4a3ddf2d497)

maints should probably also get access to the water spawning admin proc

2024-07-15 21:48 UTC, Moltijoe commented
hitting a surface with a beaker should probably just dump the liquid on the previous tile
![image](https://github.com/user-attachments/assets/e0a568c0-e12a-4bb6-9c35-ce887e4a3fa5)

2024-07-15 21:49 UTC, Moltijoe commented
water was being blocked by a space tile and when the space tile was filled in and changed to a regular turf tile it didn't update until water was specifically applied to that tile that used to be space

![image](https://github.com/user-attachments/assets/7a3de25a-5c5d-46fe-8d92-92cca2046b1f)

2024-07-16 01:18 UTC, Moltijoe commented
closing doors will delete the water on that tile
opening that door will splash water onto that tile even if the water isn't high enough
splashes should probably only happen if there's a certain level of volume difference
![image](https://github.com/user-attachments/assets/9f4c06d1-53d3-4d6d-b305-022123c9df10)

2024-07-16 02:55 UTC, Moltijoe commented
puddles don't like merging
![image](https://github.com/user-attachments/assets/a8bfaf6c-b51f-43de-8af5-d37b9498935d)

2024-08-07 19:56 UTC, Moltijoe requested changes

2024-08-07 19:56 UTC, Moltijoe commented on yogstation/code/modules/liquids/liquid_groups.dm
> +				return
probably worth putting reagents.reaction below the check
if the liquid isn't enough to push them, chances are it isn't gonna react with them

also, the react with reagents should probably still happen, even if the target is anchored or being pulled, or has infinity move resist

also also, magboots should probably resist this, checking heavy gravity is what it does

2024-08-07 20:13 UTC, Moltijoe approved these changes
fine, i guess it's alright, i can make those tweaks in a different pr
nothing fundamentally flawed with the pr

2024-08-07 20:41 UTC, Moltijoe approved these changes

2024-08-07 23:55 UTC, JamieD1 approved these changes
:/

2024-08-08 19:54 UTC, merged