Keypads 2.0: Its THE hacker to you
yogstation13/Yogstation pull request #22174
Opened 2024-06-05 13:11 UTC by Scrambledeggs00

# Document the changes in your pull request

Hacking keypads is boring as it is just standing around for 40 seconds to unlock one. This PR changes that by replacing the old way with three new ways. Once unlocked, you can then use a multitool on it to reset its code, which takes 10 seconds to do. It also adds in lock strength to keypad locks that determines what can force them and if they can have their code reset. Briefcases can be forced, hacked, and emaged while safes can only be hacked or emaged. A final level of strength makes it so it can only be hacked or emaged and cannot have its code reset, but I did not add any items that use it; it is there for others to use.

First way is by forcing the lock with an item. Currently, these items are jaws of life, changeling arm blade, umbral tendrils, and 
mantis blade. This can only be done on briefcases as safes are too strong to be forced. I originally planned a do_after for this to balance it, but it kept throwing errors so instant hacking I guess :I

Second way is with an emag which can force open any keypad lock.

Last way is by checking its memory for a game of Cows and Bulls. If an incorrect valid code was entered and you use a multitool on it while locked, you will get messages telling you the input code, how many digits were correct and in the right place, and how many were correct but in the wrong place.

When forced open with an item or emag, the item's sprite will blink and its description will say that its lock is bugged. To undo this, simply reset the keypad by pressing the R button in its UI. 

# Why is this good for the game?

Makes hacking keypad locks more interesting and not boring.

# Testing

Video showing the different methods in action:
https://www.youtube.com/watch?v=GbwMsVbh2rI

# Spriting

Forced open sprite:
![SuitcasesHack](https://github.com/yogstation13/Yogstation/assets/113869252/ffcb40f7-5825-40c0-9986-b00b8fc34009)

# Wiki Documentation

To force a briefcase open, either use a jaws of life, changeling arm blade, umbral tendrils, mantis blade, or emag on it. To get clues to the code, enter a five digit code, open its service panel with a screwdriver, and then use a multitool on it. Doing so will send messages telling you the code you tried, along with the number of correct digits in the correct place and correct digits in the wrong place. Using a multitool on it while unlocked and with its service panel open will start a 10 second timer. At the end of it, the keypad's code will be reset and you can give it a new code.

Safes work the same except they can only be forced open with an emag.

To fix a keypad lock that has been forced, simply press the R in the keypad's UI.

# Changelog

:cl:  
tweak: Changed how hacking keypad locks works
imageadd: Added sprites for forced keypad items 
/:cl:

2024-06-05 13:14 UTC, MommaDragon commented
Hackerman (boring)

2024-06-05 19:09 UTC, cuackles approved these changes

2024-06-11 08:43 UTC, Moltijoe requested changes

2024-06-11 08:43 UTC, Moltijoe commented on code/datums/components/keypad_lock.dm
> +	var/list/keypad_tools = list(/obj/item/jawsoflife,
Might be worth adding the light eater to this if the mantis blade and armblade already are

2024-06-11 08:43 UTC, Moltijoe commented on code/datums/components/keypad_lock.dm
> +			user.balloon_alert(user, "Reseting memory")
```suggestion
			user.balloon_alert(user, "Resetting memory")
```

2024-06-11 08:43 UTC, Moltijoe commented on code/datums/components/keypad_lock.dm
> +				user.balloon_alert(user, "Interupted!")
```suggestion
				user.balloon_alert(user, "Interrupted!")
```

2024-06-12 10:31 UTC, Moltijoe approved these changes

2024-06-12 10:31 UTC, merged