Refactors gas reagents
yogstation13/Yogstation pull request #22188
Opened 2024-06-08 23:39 UTC by SapphicOverload

# Document the changes in your pull request

Refactors how gas breath effects work, and the gas reagents themselves. Also fixes preterni sometimes not being affected by certain gases, and allows any gas with reagent effects to work in cryo tubes.

Closes #22187

# Why is this good for the game?
Significantly better code, allows most gases with breath effects to work in cryo tubes.

# Testing

![image](https://github.com/yogstation13/Yogstation/assets/93578146/d3bfa534-a0f6-4660-abb0-1311dfa3602a)

# Changelog

:cl:  
experimental: Refactored gas reagents and gas breath effects
tweak: Most gases with breath effects now work in cryo tubes
bugfix: Fixed certain gases sometimes not having effects on preterni
/:cl:

2024-06-08 23:54 UTC, wonderinghost commented
Gay

2024-06-09 03:04 UTC, warface1234455 commented
hot

2024-06-09 05:08 UTC, ynot01 commented
Solve lints

2024-06-10 00:43 UTC, ynot01 requested changes

2024-06-10 00:43 UTC, ynot01 commented on code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
> +	CRASH("AAAAAAAA")
Remove debug message

2024-06-10 23:43 UTC, ynot01 approved these changes

2024-06-10 23:43 UTC, merged