Adjusts the emergency shuttle call times and makes the shuttle autocall if the round goes past 2 hours
yogstation13/Yogstation pull request #22220
Opened 2024-06-19 22:09 UTC by ToasterBiome

# Document the changes in your pull request

AUTOEVAC: 15 minutes (was 25)
GREEN: 12 minutes (was 20)

makes shuttle autocall if the round goes past 2 hours, because everything should have been finished by then.

# Why is this good for the game?

- less time waiting for a shuttle for rounds "ended" (hopelessly lost)
- more pressure on sec to finish the round up by getting antagonists (less camping)
- more pressure on antagonists to do things (you cant just do all your objectives in the 20 minute call)

# Changelog

:cl:  
tweak: adjusts the values of autoevac and green alert emergency shuttle times (25 -> 15, 20 -> 12)
rscadd: the shuttle autocalls if the round goes past 2 hours
/:cl:

2024-06-19 22:15 UTC, SapphicOverload commented
Should probably also autocall if all crew are dead

2024-06-20 01:25 UTC, warface1234455 commented
> Should probably also autocall if all crew are dead

It's bugged

2024-06-20 01:25 UTC, warface1234455 commented
> Should probably also autocall if all crew are dead

It's bugged

2024-07-24 10:13 UTC, ktlwjec0 commented
I assume you know but just in case - the alert still comes up for lack of response even if the shuttle is already in transit.

2024-07-31 02:14 UTC, Moltijoe requested changes
make sure it doesn't trigger if it's already been called

2024-08-07 20:16 UTC, Moltijoe requested changes

2024-08-07 20:16 UTC, Moltijoe commented on code/controllers/subsystem/shuttle.dm
> +			return
add a check for if the shuttle is already called here too

2024-08-10 06:04 UTC, Moltijoe approved these changes

2024-08-10 06:04 UTC, merged