Nerfs ethereal martial art
yogstation13/Yogstation pull request #22275
Opened 2024-07-02 19:17 UTC by Moltijoe

Removes the stun from lightning flow dropkick (still has the knockdown)

# Why is this good for the game?
it's meant to be zipping about being annoying, not stun locking people

# Testing
i did, but forgot the screenshot, i can provide one if needed

:cl:  
tweak: Nerfs ethereal martial art infinite combo
/:cl:

2024-07-02 19:43 UTC, LassiH commented
isnt the martial made pretty useless by just wearing armor with electrical protection or having insulated ?

2024-07-02 22:06 UTC, Moltijoe commented
> isnt the martial made pretty useless by just wearing armor with electrical protection or having insulated gene ?

Yeah probably, i should probably do something about that

2024-07-04 19:14 UTC, ynot01 requested changes

2024-07-04 19:14 UTC, ynot01 commented on code/datums/martial/lightning_flow.dm
> +		var/mob/living/carbon/human/flicker
flicker is never assigned

2024-07-04 19:21 UTC, Moltijoe commented on code/datums/martial/lightning_flow.dm
> +		var/mob/living/carbon/human/flicker
true

2024-07-05 17:17 UTC, ynot01 approved these changes

2024-07-05 17:17 UTC, merged