Caffeine junkie quirk + drink tweaks
yogstation13/Yogstation pull request #22385
Opened 2024-07-15 23:56 UTC by Moltijoe

# Why is this good for the game?
some people live off coffee or energy drinks, only seems fitting to add a quirk when the other junkie quirks exist

# Testing
gotta

:cl:  
rscadd: Added caffeine junkie negative quirk
rscadd: Added caffeine as a reagent
tweak: most caffeinated drinks now give caffeine to the consumer
experimental: shifted how certain coffee drinks are handled, announce any unusual effects
/:cl:

2024-07-16 00:57 UTC, wonderinghost commented
is there a od effect of caffiene?

2024-07-16 00:59 UTC, Moltijoe commented
> is there a od effect of caffiene?

yes

2024-07-17 01:56 UTC, ToasterBiome requested changes
can you make Addict capital too

2024-08-03 02:54 UTC, ToasterBiome approved these changes

2024-08-03 08:27 UTC, SapphicOverload approved these changes

2024-08-06 23:03 UTC, merged