Fixes multi-z stairs being invisible, shunts old stair sprites to the abyss in favor of the goon ones
yogstation13/Yogstation pull request #22470
Opened 2024-07-31 03:01 UTC by AMyriad

# Document the changes in your pull request
- Fixed icemeta stairs being invisible
- Killed our current structure/stairs sprites since they're old and nasty

# Why is this good for the game?
Bug fix is good
current structure/stairs sprites are godawful and I don't want to see them mapped anywhere
also keeping them the same as turf stairs makes them more seamless, and helps height illusions

# Testing
Yes
![image](https://github.com/user-attachments/assets/f4dea7c9-734d-4fcd-8c64-1c0d463ae099)

# Spriting
Lots of these icons in the goon stairs file were inconsistent (like having differently set directions) so I changed it up a bit:

Old
![image](https://github.com/user-attachments/assets/a64df5a9-ceeb-4c9e-bff7-4de551f237e0)

New
![image](https://github.com/user-attachments/assets/82aaa92f-8587-4922-87d5-3623a35aae88)

# Changelog
:cl:
bugfix: Fixed multi-z stairs not rendering at all (see: icemeta)
imageadd: Multi-z stairs now look nice, like every other piece of stair in the game
imagedel: Tossed old multi-z stair sprites into the 9th circle of hell where they belong
/:cl:

2024-07-31 04:36 UTC, Moltijoe commented
dark middle looks upside down to me

2024-08-03 08:42 UTC, Aquizit requested changes
![image](https://github.com/user-attachments/assets/fb13c292-80a3-47d8-aaf9-2c86d0aec74a)

It's a "wall." I cannot move. The miner cannot go back up the stairs nor leave the ones they are on, and anyone outside cannot enter the stairs.

2024-08-03 23:27 UTC, ToasterBiome approved these changes

2024-08-06 22:00 UTC, AMyriad commented
merging this with access overhaul to avoid conflicts

2024-08-06 22:00 UTC, closed without merging