adds an alien lab ruin to icemeta underground
yogstation13/Yogstation pull request #22541
Opened 2024-08-19 01:16 UTC by LazennG

# Document the changes in your pull request
adds a new ruin to icemeta underground levels in an attempt to make it less barren

# Why is this good for the game?
icemeta is the worst mining experience by a long shot and im trying to make it not that

# Testing
played it and it works as intended

# Changelog

:cl:
rscadd: Added new ruin to icemeta 

/:cl:
thanks to @cowbot92 and @ToasterBiome and @AMyriad for answering several mapping questions

2024-08-19 03:50 UTC, ToasterBiome requested changes, later dismissed

2024-08-19 03:50 UTC, ToasterBiome commented on config/iceruinblacklist.txt
> +#maps/RandomRuins/IceRuins/icemoon_underground_alien_lab.dmm
```suggestion
#_maps/RandomRuins/IceRuins/icemoon_underground_alien_lab.dmm
```

2024-08-19 09:54 UTC, Aquizit commented
All the open space areas are incorrect. Should be /area/template_noop not space

2024-08-25 23:17 UTC, AMyriad commented on _maps/RandomRuins/IceRuins/icemoon_underground_alien_lab.dmm
> +/obj/structure/grille,
```suggestion

```
spawners already put down window + grille, this would be putting down 1 extra grille

2024-08-25 23:37 UTC, AMyriad approved these changes

2024-08-28 02:35 UTC, ToasterBiome approved these changes
you thought you could avoid me

2024-08-28 02:35 UTC, merged