New Emergency Shuttle: The Fleet
yogstation13/Yogstation pull request #22615
Opened 2024-09-19 20:31 UTC by CrazyDrakkon

# Document the changes in your pull request

(My first PR) Adds massive new "shuttle"/collection of shuttles, each representing a department, that are connected via quantum pads. Includes a brig and medical shuttle.

![image](https://github.com/user-attachments/assets/421fd11d-08a1-44a5-80b4-aec5c4ca7326)

# Why is this good for the game?

Adds a fun, high-end shuttle option. Alternative to the Luxury Shuttle that isn't ugly.

# Testing

Not tested, but yes it just barely fits on Box.

# Changelog

:cl:

rscadd: Added new emergency shuttle: The Fleet

/:cl:

2024-09-19 20:33 UTC, Scrambledeggs00 commented
You forgot to make a ship for the based department
![absolutecinema](https://github.com/user-attachments/assets/cbd2c334-ab41-4def-a1b3-81296a9b2c81)

2024-09-19 20:42 UTC, AMyriad commented
do it...dock?

![image](https://github.com/user-attachments/assets/86713c63-ac25-4057-a40e-347bd03ee320)

2024-09-19 20:48 UTC, CrazyDrakkon commented
> do it...dock?
> 
> ![image](https://private-user-images.githubusercontent.com/143908044/369162277-86713c63-ac25-4057-a40e-347bd03ee320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Nzg4MjIsIm5iZiI6MTcyNjc3ODUyMiwicGF0aCI6Ii8xNDM5MDgwNDQvMzY5MTYyMjc3LTg2NzEzYzYzLWFjMjUtNDA1Ny1hNDBlLTM0N2JkMDNlZTMyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQyMDQyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmI1YTAyMDFiYmE1YmJmZTQ5ZWFlYTM2MGM0ZjRmNzY0YjM4ZmFmY2E2YzI2Mzk2MDkyOWFiNjVjNWEzMTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._wdsPze-MamOMIdu8cTHYXpPaWA0VEwKpYCUIpk_lyA)

Measured it so that it's right on the edge of the area that makes you travel to the next z-level. (Atleast on Box 💀)

2024-09-20 07:10 UTC, ToasterBiome commented
This sucks

Upvote

2024-09-21 10:36 UTC, AMyriad requested changes
Agreed this is a mess I love it
On a more serious note, before I take a closer look, can you show proof of testing of this thing docking at the station and at centcom?

2024-09-27 06:13 UTC, CrazyDrakkon commented
> Agreed this is a mess I love it On a more serious note, before I take a closer look, can you show proof of testing of this thing docking at the station and at centcom?

Yup, it fits 👍

2024-10-02 12:26 UTC, AMyriad requested changes
Alright, so this is a pretty funny idea and I respect the effort you put into this, but I don't see it working as it is now. Balance concerns aside (there is a lot of space to run/hide in), the main problem is this thing is just too BIG.

I did some size estimates to check, and sadly yes this shuttle'll be too chonky to fit in a number of places, such as the syndicate hijack base and donutstation for example. I'm sure it fits on boxstation and centcom fine, but mind you those aren't the only maps in existence.

And since this'd be probably the biggest shuttle design we'd be adding, whatever maps we make from now on would have to abide by its size, meaning we'd be forced to keep the evac docks absolutely clear of anything in a large radius just so this beast could fit.

![image](https://github.com/user-attachments/assets/daffa9ea-d75f-47bd-9b3f-14a605145e86)
![image](https://github.com/user-attachments/assets/db213fd5-1e7a-409e-a6d8-ca648a633b4d)

2024-10-02 21:45 UTC, CrazyDrakkon commented
> I did some size estimates to check, and sadly yes this shuttle is too chonky to fit in a number of places, such as the syndicate hijack base and donutstation for example. I'm sure it fits on boxstation and centcom fine, but mind you those aren't the only maps in existence.
> 
> And since this'd be probably the biggest shuttle design we'd be adding, whatever maps we make from now on would have to abide by its size, meaning we'd be forced to keep the evac docks absolutely clear of anything in a large radius just so this beast could fit.

Large shuttles (emergency_meteor.dmm (40x40) and emergency_pubby.dmm (8x46) dock with other stations (which I'm having trouble testing without crashing) and can get hijacked, and this one is 37x47. When docking, they just "crash" into and remove what structures are in the way. The hyperspace adjusts to the size in transit.

Testing (It just freaked out from being rotated):

Gax:

![image](https://github.com/user-attachments/assets/ee4ad594-929b-49ad-8601-5db08e9504e1)

![image](https://github.com/user-attachments/assets/3dd0b846-6cab-4847-8bb3-63c070c4908d)

Hijacked:

![image](https://github.com/user-attachments/assets/b2f9ca78-4365-4c25-9a60-49c95c5bbdd0)

![image](https://github.com/user-attachments/assets/e1183a24-3fdb-49b9-9b8f-f59b5ce65a74)

2024-10-06 02:12 UTC, neeshacark commented
It crashing into the grilles of donut's shipbreaking isn't the biggest deal explicitly because if i ever get off my lazy ass (the time grows near) donut is getting replaced with a smaller, worser version

as for the syndibase would you lookie at that

2024-10-28 19:23 UTC, JamieD1 commented
I dislike some of the 1by1 sections, this reduces good combat and antics.

2024-11-02 21:37 UTC, CrazyDrakkon commented
> I dislike some of the 1by1 sections, this reduces good combat and antics.

Does this sufficiently fix?

![image](https://github.com/user-attachments/assets/ce17f13b-db80-4ac8-a9fe-366e161e27c3)

2024-11-10 16:16 UTC, JamieD1 commented
> > I dislike some of the 1by1 sections, this reduces good combat and antics.
> 
> Does this sufficiently fix?
> 
> ![image](https://private-user-images.githubusercontent.com/18729830/382509555-ce17f13b-db80-4ac8-a9fe-366e161e27c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTU2MzYsIm5iZiI6MTczMTI1NTMzNiwicGF0aCI6Ii8xODcyOTgzMC8zODI1MDk1NTUtY2UxN2YxM2ItZGI4MC00YWM4LWE5ZmUtMzY2ZTE2MWUyN2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE2MTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZTY0NmViMjU4MDQwZDM3ZDRiMWI5YzdlZjEwZjVhYTc0MGNmMTBiZDQ0YWM5MjQ1OWY4NTMxMmQyZTkyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HtO6KdTeeL9tvEYKBIwiMvdGLVR_NlhAPuW-Lm-f5c4)

You can put it back, I meant on most of the shuttles but, its not a game changer, will wait to hear from @yogstation13/map

2025-03-21 16:31 UTC, ToasterBiome commented
Doesnt compile

2025-03-21 16:31 UTC, closed without merging