[Meta] Fixes one single decal
yogstation13/Yogstation pull request #22634
Opened 2024-09-22 22:28 UTC by N3D6

# Document the changes in your pull request

Fixes one single decal in meta sec
# Why is this good for the game?

# Testing
Didn't

# Spriting

# Wiki Documentation

# Changelog

:cl:
mapping: fixes a decal in meta sec
/:cl:

2024-09-22 22:35 UTC, AMyriad requested changes
You added this by accident you silly goof
![image](https://github.com/user-attachments/assets/c2990bf8-7773-43d3-80aa-e6ec69b619af)

2024-09-22 22:46 UTC, N3D6 commented
> You added this by accident you silly goof ![image](https://private-user-images.githubusercontent.com/143908044/369721551-c2990bf8-7773-43d3-80aa-e6ec69b619af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNDQ4NDcsIm5iZiI6MTcyNzA0NDU0NywicGF0aCI6Ii8xNDM5MDgwNDQvMzY5NzIxNTUxLWMyOTkwYmY4LTc3NzMtNDNkMy04MGFhLWU2ZWM2OWI2MTlhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQyMjM1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmVjZDZhYzk1MTE1YmE1MjNlMTkzNzhhMDQ0N2ZkMTc5NTY2ZTkwNDJkNzYyMWJlYzAxMjNlMjM1OTk1MjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DZDM6PqqdRApHOlfy46bEKNW-wSAY--UXUtYPNoSJBI)

Holy shit I am truly the peak form of a mapper

2024-09-22 22:53 UTC, N3D6 commented
fixed another bad one

2024-09-23 08:29 UTC, AMyriad approved these changes

2024-09-23 22:51 UTC, merged