Suicide Vest Traitor Item
yogstation13/Yogstation pull request #22668
Opened 2024-10-01 02:05 UTC by ToasterBiome

# Document the changes in your pull request

Adds an extremely obvious suicide vest to the game that traitors can buy for 3 TC. It functions like a voice activated bomb, using an inclusive voice recorder. It makes a 2, 0.8, 0.4 explosion (same as microbomb implant) when it explodes, and you can only set the phrase one time (better not mess it up) additionally it's cursed so it can never be removed. When you die it also doesnt explode, so you best be quick.

# Why is this good for the game?

# Testing
![image](https://github.com/user-attachments/assets/f13075a9-2a8c-45cc-b282-af60ab20aa41)
![image](https://github.com/user-attachments/assets/f47c6a2e-6cb4-42ae-a97e-967adaa7a06e)

# Spriting
Just uses the reactive armor sprites

# Changelog

:cl:
rscadd: Adds a suicide vest for traitors to buy
/:cl:

2024-10-01 02:35 UTC, Mqiib requested changes
Make it something other than the reactive armor sprite

2024-10-01 02:56 UTC, ToasterBiome commented
> Make it something other than the reactive armor sprite

got any ideas?

2024-10-01 03:01 UTC, warface1234455 commented
Why do this when you can just activate a bomb in your hand

2024-10-01 03:13 UTC, iloveloopers commented
What a waste of 7 TC, you can just make a normal voice activated atmos bomb

2024-10-01 03:44 UTC, wonderinghost commented
looper i swear im going to add toolset implants to the uplink

2024-10-01 03:46 UTC, iloveloopers commented
> looper i swear im going to add toolset implants to the uplink

That would actually be useful as long as it isn't super expensive

2024-10-01 03:56 UTC, ToasterBiome commented
> What a waste of 7 TC, you can just make a normal voice activated atmos bomb

save yourself the 7 tc and make that instead

TC acts partially as a resource to get things you're unable to get, and partially as time gated things that you can get quicker (such as sentience potions)

2024-10-01 15:21 UTC, LassiH commented
the wheelchair bomb already exists which is cheaper and has a bigger explosion

2024-10-01 15:26 UTC, Mqiib commented
> > Make it something other than the reactive armor sprite
> 
> got any ideas?

Ideally something that looks like a bomb vest. Can't be that hard, it's not that big of a sprite. Perhaps something along the lines of:

![image](https://github.com/user-attachments/assets/5bd64d43-848c-4d93-abf7-9a6bee5bca69)

2024-10-03 00:13 UTC, ToasterBiome commented
I'll cook something up soon

2024-10-06 18:48 UTC, ynot01 commented
> > Make it something other than the reactive armor sprite
> 
> 
> 
> got any ideas?

theres literally a bomb vest sprite in the files already, the experimentor uses it i think

2024-10-12 17:33 UTC, Mqiib approved these changes
cool

2024-10-12 18:25 UTC, ynot01 commented on code/modules/clothing/suits/miscellaneous.dm
> +	name = "extremely obvious suicide vest"
this name is lame

2024-10-12 18:27 UTC, ynot01 requested changes

2024-10-12 18:27 UTC, ynot01 commented on code/modules/clothing/suits/miscellaneous.dm
> +	icon_state = "reactiveoff"
this is not the sprite you made

2024-10-13 17:02 UTC, ToasterBiome commented on code/modules/clothing/suits/miscellaneous.dm
> +	icon_state = "reactiveoff"
fixed

2024-10-13 17:02 UTC, ToasterBiome commented on code/modules/clothing/suits/miscellaneous.dm
> +	name = "extremely obvious suicide vest"
what should it be instead

2024-10-13 18:32 UTC, ynot01 commented on code/modules/clothing/suits/miscellaneous.dm
> +	name = "extremely obvious suicide vest"
explosive vest would be better imo

2024-10-13 18:33 UTC, ynot01 approved these changes

2024-10-14 21:29 UTC, ToasterBiome commented on code/modules/clothing/suits/miscellaneous.dm
> +	name = "extremely obvious suicide vest"
```suggestion
	name = "explosive vest"
```

2024-10-14 21:29 UTC, merged