Delete all gamemodes
yogstation13/Yogstation pull request #22661
Opened 2024-09-28 23:13 UTC by Moltijoe

# Why is this good for the game?
i hate when the game does stuff, so i'm removing them

# Testing
why should i need to test this

:cl:
rscdel: Deletes literally all gamemodes, buh bye
/:cl:

2024-09-28 23:14 UTC, teh4565 commented
Gone, reduced to atoms

2024-09-28 23:15 UTC, UselessTheremin commented
you have achieved rp. yogstation has been saved. YES

2024-09-29 11:27 UTC, TheGamerdk requested changes, later dismissed
can we get an actual description pls :3

2024-09-29 11:36 UTC, tattax commented on code/modules/events/tzimisce.dm
> +	description = "spawns a bloodsucker from ghost roles."
it is a specific clan

2024-09-29 21:28 UTC, Moltijoe commented on code/modules/events/tzimisce.dm
> +	description = "spawns a bloodsucker from ghost roles."
fixed

2024-09-29 21:28 UTC, Moltijoe commented
> can we get an actual description pls :3

certainly

2024-10-06 12:02 UTC, ktlwjec0 commented
grav anomaly announces itself as a flux anomaly

2024-10-18 22:19 UTC, ToasterBiome approved these changes
Ready

2024-10-18 22:20 UTC, merged