New Emag Shuttle: The Suspicious Shuttle
yogstation13/Yogstation pull request #22676
Opened 2024-10-06 03:56 UTC by neeshacark

# Document the changes in your pull request

Adds a new shuttle. 
![image](https://github.com/user-attachments/assets/8dcee886-1bb0-47ff-859b-e6dbd523a0d2)

Comes with 12 suspicious goats, sizeable departments, and an abandoned cargo area. This particular shuttle was a strange artefact that fell through bluespace into the Nanotrasen shipyards, its design is forbidden. As such, it is only available via emag.

i am not sorry

# Why is this good for the game?
more shuttle

# Changelog

:cl: cark
mapping: adds the suspicious shuttle
/:cl:

2024-10-06 15:03 UTC, Beeper-Skeeper commented
"Red sus"
"WE'RE ALL RED YOU FUCKING IDIOT"

2024-10-06 18:42 UTC, ynot01 approved these changes

2024-10-06 18:43 UTC, ynot01 requested changes

2024-10-06 18:43 UTC, ynot01 commented on code/datums/shuttles/emergency.dm
> +	suffix = "amongushuttle"
filename is "emergency_amogushuttle"

2024-10-07 07:50 UTC, neeshacark commented
i have no idea why it's not compiling

2024-10-07 09:03 UTC, ynot01 commented
> i have no idea why it's not compiling

```
[05:04:54] Runtime in _shuttles.dm,49: cannot read from list
  proc name: preload size (/datum/map_template/shuttle/preload_size)
  src: Suspicious Shuttle (/datum/map_template/shuttle/emergency/amogushuttle)
  call stack:
  Suspicious Shuttle (/datum/map_template/shuttle/emergency/amogushuttle): preload size("_maps/shuttles/emergency_amogu...", 0)
  Suspicious Shuttle (/datum/map_template/shuttle/emergency/amogushuttle): New(null, null, 0)
  Suspicious Shuttle (/datum/map_template/shuttle/emergency/amogushuttle): New()
  Suspicious Shuttle (/datum/map_template/shuttle/emergency/amogushuttle): New()
  Mapping (/datum/controller/subsystem/mapping): preloadShuttleTemplates()
  Mapping (/datum/controller/subsystem/mapping): preloadTemplates("_maps/templates/")
  Mapping (/datum/controller/subsystem/mapping): Initialize(null)
  Master (/datum/controller/master): init subsystem(Mapping (/datum/controller/subsystem/mapping))
  Master (/datum/controller/master): Initialize(10, 0, 1)
```

2024-10-07 17:27 UTC, neeshacark commented
i do not know what this means

2024-10-07 22:27 UTC, ynot01 approved these changes

2024-10-13 23:14 UTC, AMyriad requested changes
1. Take away outer layer of walls please, don't think they're needed for this
2. Take away the 2 extra dir-windows around the abandoned area please. If you want em to block sight or be tougher just varedit it
3. Can we get some dir-windows and/or firelocks inbetween the shuttle chairs in the middle? Space is a bit open and could use some more geometry or cover
4. Would like to see command/sec/med areas be a little more easier to identify by having some signs or use command/sec doors, as it stands it all blends together a bit much

2024-10-15 21:41 UTC, AMyriad approved these changes

2024-10-15 21:42 UTC, merged