Adds Skills
yogstation13/Yogstation pull request #22683
Opened 2024-10-07 22:07 UTC by SapphicOverload

# Documentation

Adds a skills system that affects various aspects of the game. On the start of the round players are given a base skillset depending on their role and a set amount of free points to allocate to whichever skills they want.

- Physiology - Medical knowledge and surgical precision. Affects tending wounds and surgery success rate.
- Mechanics - Construction and repair of structures and machinery. Affects the time taken to build, repair, and deconstruct things, as well as fix external damage on IPCs and cyborgs.
- Technical - Electronics, robot maintenance, and piloting. Affects identification of certain wires when hacking, internal maintenance of IPCs and cyborgs, and piloting exosuits.
- Science - Knowledge of various scientific fields. Affects the use of scientific machinery and tools, identification of plants, and slightly increases research point generation.
- Fitness - Physical prowess and accuracy with weapons. Affects carrying speed, punch damage, resistance to melee attacks, and gun accuracy. Increases hunger.

![image](https://github.com/user-attachments/assets/23036aaf-e380-46f5-bfa2-5829e0f36611)

![image](https://github.com/user-attachments/assets/d948f2da-63f8-475f-9550-9bd5628c86da)

# Why is this good for the game?

Currently there's nothing stopping a single person from doing everything perfectly. There are already modifiers that increases tool use speed based on role, such as engineers welding things more quickly, which is a good start but having them hard-coded based on your character's job is boring and restricting.

This skills system also significantly improves character customization by allowing players to specialize further within their role in ways they couldn't before. For example a roboticist can go all in on technical and be really good at piloting and fixing robots, or put points into mechanics to repair exosuits quicker, or physiology to install cybernetics more easily, or science in order to help with research. Skills can also be used to add detail or backstory to a character, such as a captain having mechanical skill because they used to be an engineer.

# Wiki Documentation

Soon

# Changelog

:cl:
wip: Adds a skills system
/:cl:

2024-10-07 22:09 UTC, Beeper-Skeeper commented
We can finally insult someone with "skill issue" and have it be IC

2024-10-07 22:29 UTC, UselessTheremin commented
very good pr

2024-10-07 22:33 UTC, Mqiib commented
I would think the captain should be able to do anything on the station at least a little bit, and suggest they get low rather than no skill across the board, save for fitness.

2024-10-07 22:49 UTC, Mqiib commented
Also I can't say that the CMO being forced to put all their extra points into physiology and science to be able to do all parts of their job is that great

2024-10-07 23:17 UTC, ToasterBiome commented
Looks good

2024-10-08 01:18 UTC, Junkyshell commented
nice

2024-10-08 05:19 UTC, neeshacark commented
I've made my stance on skills very clear over the years - **especially** my stance on skills that affect combat, which I think are just plain bad. 

Nothing is more unfun than "well I have to invest all my shit into combat or I'm just worse than other people at fighting because they do more damage, take less damage, and shoot more accurately." Combat should be entirely based on how good a player is at it - not what job they picked or how many points they invested into a skill.

2024-10-15 05:20 UTC, ynot01 requested changes
Really beautiful, I'm a huge fan of this PR, but there will obviously be balance problems to work out. This will have to be testmerged. Also, finish Wiki Documentation section <3

2024-10-15 05:20 UTC, ynot01 commented on code/game/mecha/mecha.dm
```if(repair_hint && capacitor?.rating)```
Repair hints would be hidden from people who can still repair it with level 4 mechanic/technical skill as defined in `/obj/mecha/proc/try_repair`

2024-10-15 05:20 UTC, ynot01 commented on code/game/machinery/computer/dna_console.dm
Having 4 points in science makes Joker instant with t1 parts, unlike the scramble cooldown (which sets the cooldown from 60 seconds to 36 seconds)

Please nerf

2024-10-15 05:20 UTC, ynot01 commented on code/game/mecha/mecha.dm
Mecha entry should NOT be instant with 4 technical skill. Make it a couple seconds at least

2024-10-15 05:20 UTC, ynot01 commented on code/game/objects/items/stacks/medical.dm
It might just be me, but the time difference between applying a suture with physiology being 0 and 4 felt virtually identical.

2024-10-15 05:20 UTC, ynot01 commented on code/modules/hydroponics/seeds.dm
Spam examining a plant has... weird effects, with left-side numbers getting bigger than right-side. Also, you should use seed-based RNG: compile all stats and REF() to get a rng hash

Using a seed that is unique(ish) to the instance and stats means spam-examining won't generate different results, preventing someone from spam-examining to get more accuracy

Some ways to seed RNG is to use rustg's perlin generator `rustg_dbp_generate()` or an md5 method is seen in `/datum/chatmessage/proc/colorize_string()`

2024-10-15 05:20 UTC, ynot01 commented on code/modules/jobs/job_types/detective.dm
Detective should have skill in physiology for autopsies and other crime scene evidence stuff

2024-10-15 05:20 UTC, ynot01 commented on code/modules/jobs/job_types/scientist.dm
Jeez scientists are a little fucked here, how about HIGH science skill? and maybe something that would help them with toxins?

2024-10-15 05:20 UTC, ynot01 commented on code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Definitely gonna have to nerf tiered chems but we can do that later

2024-10-15 05:20 UTC, ynot01 commented on code/modules/surgery/advanced/brainwashing.dm
Will traitors be able to do this if they have the disk? Since it's GENIUS requisite

2024-10-15 05:20 UTC, ynot01 commented on code/modules/projectiles/gun.dm
Should make the accuracy a bit more punishing on low fitness I think

2024-10-15 05:30 UTC, ynot01 commented
I'd also, personally, like to see health analyzers get certain sections omitted when not above certain skill levels, but I might be alone in that opinion

2024-10-15 05:58 UTC, SapphicOverload commented on code/modules/surgery/advanced/brainwashing.dm
Not a requisite, it's the skill level required to not have a penalty to failure chance. You get 10% chance to fail per level below the difficulty, so being at level 0 when you need level 5 gives you a 50% chance to fail.

2024-10-15 06:15 UTC, SapphicOverload commented on code/game/mecha/mecha.dm
It's a 36% reduction in delay at level 4, which reduces the normal 4 second entering time to 2.56 seconds.

2024-10-15 06:49 UTC, ynot01 commented on code/game/mecha/mecha.dm
Please test this on your end, I entered a firefighter and it was literally instantaneous

2024-10-15 09:31 UTC, SapphicOverload commented on code/game/mecha/mecha.dm
Turns out check_eva() caused an error making it complete instantly if there wasn't already an occupant in the mech, this is now fixed.

2024-10-15 10:40 UTC, ynot01 approved these changes

2024-10-18 22:57 UTC, cuackles approved these changes

2024-10-18 23:29 UTC, ToasterBiome commented
Is there a way for admins/ghosts to see skills?

2024-10-19 00:16 UTC, SapphicOverload commented
> Is there a way for admins/ghosts to see skills?

Not yet, I'll work on that

2024-10-19 12:25 UTC, ktlwjec0 commented
![image](https://github.com/user-attachments/assets/c2cb3c03-8189-4fdb-a061-91b4178a4a2b)
on round 54223 it said I had -1 points available and I couldn't clear the alert for selecting skills

2024-10-20 07:50 UTC, teh4565 commented
Chem dispenser doesnt dispense chem properly despite having high science level!! ive been scammed!!

Also I think getting higher chem from just science levels is overpowered

2024-10-24 19:49 UTC, N3D6 commented
my opinion on this has arrived

the top right "unassigned skills menu" button doesn't seem to work for me but the bottom one does

overall i don't really care about this one way or the other i just feel as if we need to make them easier to progress, i just went through a full 2 hour round doing stuff and none of my skills improved at all

2024-10-26 23:03 UTC, dcxgame commented
I have a few concerns:
- The average crew role has 6 total skill points, but the baseline is 3 total. This causes not only assistants to have less skills, but also all service roles besides botanist, as far as I can tell. I get the desire to differentiate people's capabilities by role, but there's nothing stopping you from at least allowing these roles more free points, to let them choose what skills make sense for their character's background.
In addition, security officers and the warden only get 4 skill points, and most of them are focused on fitness. There's a comment that officers "don't really do much" explaining this, which strikes me as you, similar to service roles having low skills, deciding the details of someone's character for them through the code.

- Head roles get 9 total skill points, except for the captain, who gets 8, and the head of security who, with the same logic as above, has been given 5.
If the reason for this is simply that their character has a higher social standing than the other crew members, does that satisfy a want related to game design, or simply "make sense" in a subjective sense? 
Or, if the logic is that they're at higher risk and have higher responsibilities, and therefore need to be more proficient, doesn't that effectively give players who by and large have a higher game knowledge a mechanical advantage on top of it, and wouldn't it be more appropriate in the context of a cooperative game if they matched their department's skills, and therefore had to rely on their department more to stay safe? The captain having one less point makes me assume a decision was made based on them having the best gear or the most game time out of any head, so I don't see why this relationship of skill points vs other advantages wouldn't be consistent all the way down.

- The hunger increase from fitness is an excellent check on the combat buffs associated with it, but I didn't see HUNGER_FACTOR modified within this PR, so it appears that, on average, this PR is also a global nerf to food, to the order of hunger being made 150% faster on average.

- I'm sure you anticipate this, but any sort of mechanic involving progression is going to lead to players choosing to waste some amount of the round grinding it. This isn't so much a problem for me, because a mechanic causing fun that isn't conducive to the quality of the round is pretty entertaining to me, but besides it just lowering interaction, there are also a lot of ways it can encourage players to spam clicks, as I've encountered while testing.

- I don't quite understand why you chose botanist out of all service jobs to elevate to 6 total skills, or why you gave them fitness low, but that does signify them as being the only role besides heads or security that can obtain fitness genius within 10 minutes of the round starting. Personally, I would have given that point to mechanical, since the botanist often wishes to rearrange their hydro trays, or technical, since you defined technical as including botany tasks in the comment directly attached to it. I don't know if botany needs another aspect that combat-focused players would want the role for.

- Finally, I can appreciate the sentiment that you don't want every single role to, say, be able to perform advanced surgery, character-wise. However, if you make a system like this too relevant to the success of a task like that, you run into a lose-lose regarding new players: Do they, A) use the assistant role for it's intended purpose, and risk either misunderstanding the skill system and failing at the task they intended to learn today, or using it and being unequipped to do anything else that round, or B) pick the intended role for the task they're learning, using up a slot in that department and possibly ending up one of the only members, lowering their chances of being properly coached?

The best case scenario for this system is that it seems to reward players who already know everything about the game, but will greatly diminish the experience of players who don't know anything. I personally enjoyed myself in testing, but my testing took place in a round with a relatively decent population, and I can tell that I ended up not really contributing to it.

2024-10-28 19:18 UTC, JamieD1 commented
Oh lord

2024-10-29 18:52 UTC, teh4565 commented
Alert alert bug report
round 54327 time 54:00
DNA scanner T4, science level 2
DNA console's joker cooldown becomes 0 seconds

2024-11-17 01:53 UTC, LassiH commented
restricting certain crafting recipes behind skills is not fun its basically just removing a recipe for a person

2024-12-30 18:51 UTC, merged