[DONUT] Redoes all of Engineering and some areas around it
yogstation13/Yogstation pull request #22719
Opened 2024-10-15 05:37 UTC by ToasterBiome

# Document the changes in your pull request

I think the engineering is UGLY so i want to make it BETTER
- Moves grav generator to Engineering
- Splits it into more areas
- Uses condensed SMES style like Gax/Mini
- Uses smaller Box Vault
- Slightly shortens lawyer room that's weirdly shaped
- Removes old grav generator area and makes it maint

![image](https://github.com/user-attachments/assets/e27aeb97-bbf5-46f5-9c32-df0b9457fc44)
![image](https://github.com/user-attachments/assets/56398135-1586-4f2c-968b-834000402dc6)

# Why is this good for the game?

Better looking = Better Functioning = Better Life

# Changelog

:cl:
mapping: DonutStation Engineering has been completely redone
/:cl:

2024-10-15 05:47 UTC, ynot01 approved these changes

2024-10-15 14:15 UTC, N3D6 commented
only 4 smes units stinky

2024-10-22 19:35 UTC, neeshacark requested changes
![image](https://github.com/user-attachments/assets/4254266a-3d0e-47bf-9907-f1c0647fc604)
fix the name of this door (no grav gen) and maybe make it a double door. it might look better.

![image](https://github.com/user-attachments/assets/72c8c680-88dc-47a7-92cf-cf6158931067)
the yellow decals outside might need to be rounded off with corner decals before they reach. your call but that's my take.

![image](https://github.com/user-attachments/assets/e9203685-fc9c-40b0-a503-596845f46cae)
this door is missing firelocks

![image](https://github.com/user-attachments/assets/24998cc1-df71-4ec7-be2d-508eafadfb47)
maybe remove this disposal pipe and redo it to connect out in the central hall instead of making it go under a table which is bad and cringe

![image](https://github.com/user-attachments/assets/58787600-5caf-457e-bb72-da94791b6612)
maybe put a fire alarm in this area

![image](https://github.com/user-attachments/assets/2b9d8a0a-5fbb-48f0-87b6-d83b91750581)
need a corner blue decal here

![image](https://github.com/user-attachments/assets/5a0bcdc4-6924-4ae8-97d9-256b173a93ff)
make this a normal wall it has no reason to be reinforced

2024-10-23 02:45 UTC, ToasterBiome commented
I've done all the changes except for the disposal one.

The reason why i am not changing it is because i dont like the sorter having multiple sort types and then we have to further sort it. I'd like to avoid this when possible (you can see that i do it in ministation too)

2024-10-23 21:21 UTC, neeshacark approved these changes

2024-10-23 21:21 UTC, merged