[s] Fixes cursed stomach vomitcrawl CC exploit
yogstation13/Yogstation pull request #22828
Opened 2024-12-01 20:41 UTC by Oblisk234

Fixes #20945

# Document the changes in your pull request

Cargo shuttle will now not launch if there is vomit on the shuttle, preventing vomitcrawling to CC.

# Testing
![image](https://github.com/user-attachments/assets/74051826-31ed-4bba-bb6b-222d9c6d7231)
![image](https://github.com/user-attachments/assets/f89c59cd-79cc-48f8-a2df-d0fe1c9a8b83)

# Changelog

:cl:
bugfix: Fixed an exploit where you could use the cursed stomach to vomitcrawl to Centcomm
/:cl:

2024-12-02 00:01 UTC, ToasterBiome requested changes
instead just make vomitcrawling not go to centcom level? unless the issue is that they sink into it and then have someone else move the shuttle while they’re in it?

2024-12-02 23:44 UTC, ToasterBiome requested changes
there's mapping helpers to check if you're on centcom

2024-12-02 23:47 UTC, Oblisk234 commented
> there's mapping helpers to check if you're on centcom

How can I check for those?

2024-12-02 23:52 UTC, Oblisk234 commented
Nevermind, found it.

2024-12-08 05:17 UTC, ToasterBiome approved these changes

2024-12-08 05:17 UTC, merged