healium tweaks p3
yogstation13/Yogstation pull request #22843
Opened 2024-12-10 19:35 UTC by warface1234455

# Document the changes in your pull request
healium now prevents body from rotting
cryo tube now prorperly heal dead body (with extra check to prevent healium duplication) to a reviable state when healium reagent exists in the body (#22133), broken by (#22188)

# Why is this good for the game?
healium could prevent organs from rotting but not the entire body is whack, allowing doctors to normally defib one without the need of revival surgery (body decayed) if healium exists in the bloodstream

plus bug fix

# Testing
tested on local

# Changelog

:cl:
tweak: healium now prevents body from rotting
tweak: cryo tube now prorperly heal dead body (with extra check to prevent healium duplication) to a reviable state when healium reagent exists in the body (#22133), broken by (#22188)
/:cl:

2024-12-14 10:30 UTC, ynot01 requested changes

2024-12-14 10:30 UTC, ynot01 commented on code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
> +				var/msg = "Dead body has been patched up to a reviable state."
revivable

2024-12-14 10:31 UTC, ynot01 commented
> healium now prevents body from rotting

looking at the code it seems that healium in fact reverses body rot, not just prevents it

2024-12-14 10:56 UTC, warface1234455 commented
> > healium now prevents body from rotting
> 
> looking at the code it seems that healium in fact reverses body rot, not just prevents it

Yeah maybe i have used the wrong word, but the point is allowing defib to work with rot body

2024-12-14 12:15 UTC, ynot01 commented
> Yeah maybe i have used the wrong word, but the point is allowing defib to work with rot body, if its at defib able state and with healium inside

change changelog to better reflect changes

2024-12-14 12:17 UTC, warface1234455 commented
> > Yeah maybe i have used the wrong word, but the point is allowing defib to work with rot body, if its at defib able state and with healium inside
> 
> change changelog to better reflect changes

I was going to make it actually prevent rot

2024-12-15 12:10 UTC, ynot01 requested changes

2024-12-15 12:10 UTC, ynot01 commented on code/datums/components/rot.dm
> +	if(!C.reagents.has_reagent(/datum/reagent/gas/healium))
this is incorrect, it should return if has_reagent returns true, as returning means no rotting

2024-12-15 12:14 UTC, warface1234455 commented on code/datums/components/rot.dm
> +	if(!C.reagents.has_reagent(/datum/reagent/gas/healium))
OH WAIT MY BAD

2025-01-05 01:23 UTC, ynot01 approved these changes

2025-03-21 16:32 UTC, ToasterBiome commented
No longer needed

2025-03-21 16:32 UTC, closed without merging