Mention Rule 3.7.3 when you spawn as a pyroclastic slime
yogstation13/Yogstation pull request #22865
Opened 2024-12-20 03:19 UTC by ToasterBiome

# Document the changes in your pull request

Does what it says on the tin

# Changelog

:cl:
rscadd: Mentions rule 3.7.3 when you spawn as a pyroclastic slime
/:cl:

2024-12-20 03:20 UTC, Oblisk234 commented
Minor spelling mistake, "anomoly slime"

2024-12-22 23:25 UTC, warface1234455 commented on code/game/objects/effects/anomalies.dm
> +		to_chat(S, "<b>As a pyroclastic anamoly slime, you are beholden to <a href='https://forums.yogstation.net/help/rules/#rule-3_7_3'>rule 3.7.3</a>: Slimes spawned from pyroclastic anomalies may kill
anamoly

2024-12-22 23:27 UTC, warface1234455 requested changes
silly

2024-12-22 23:27 UTC, warface1234455 commented on code/game/objects/effects/anomalies.dm
> +		to_chat(S, "<b>As a pyroclastic anamoly slime, you are beholden to <a href='https://forums.yogstation.net/help/rules/#rule-3_7_3'>rule 3.7.3</a>: Slimes spawned from pyroclastic anomalies may kill
```suggestion
		to_chat(S, "<b>As a pyroclastic anomaly slime, you are beholden to <a href='https://forums.yogstation.net/help/rules/#rule-3_7_3'>rule 3.7.3</a>: Slimes spawned from pyroclastic anomalies may kill to feed. They should not break significant station equipment in the hopes of broadly killing people. You are not an antagonist.</b>")
```

2024-12-22 23:32 UTC, warface1234455 commented on code/game/objects/effects/anomalies.dm
> +		to_chat(S, "<b>As a pyroclastic anamoly slime, you are beholden to <a href='https://forums.yogstation.net/help/rules/#rule-3_7_3'>rule 3.7.3</a>: Slimes spawned from pyroclastic anomalies may kill
failed twice....

2024-12-29 20:24 UTC, merged