fix unable to research ai tech using ruin type rnd console
yogstation13/Yogstation pull request #22878
Opened 2024-12-21 18:52 UTC by warface1234455

* fix #22425

# Testing
![image](https://github.com/user-attachments/assets/d4b7e7c2-e74c-4d6f-866f-749bb165edf2)

# Changelog

:cl:
 
bugfix: fix unable to research ai tech using ruin type rnd console
/:cl:

2024-12-27 22:52 UTC, ToasterBiome requested changes
This lets ruin people use the station's AI research. Also conversely lets station people use ruin's. Something that could be done is making a ruin rack creator.

2025-01-02 22:42 UTC, warface1234455 commented
> This lets ruin people use the station's AI research. Also conversely lets station people use ruin's. Something that could be done is making a ruin rack creator.

no it doesn't use normal station ai research, i have made a seperate techs

2025-01-02 22:43 UTC, warface1234455 commented on code/modules/mob/living/silicon/ai/decentralized/systech/rack_creator.dm
> +		stored_research = SSresearch.ruin_tech
here @ToasterBiome

2025-01-02 23:49 UTC, Oblisk234 commented on code/modules/mob/living/silicon/ai/decentralized/systech/rack_creator.dm
> +		stored_research = SSresearch.ruin_tech
Doesn't this mean that it's shared between all neutral factions, even ones which might oppose each other (e.g. free golems and free miners)?

2025-01-03 00:00 UTC, warface1234455 commented on code/modules/mob/living/silicon/ai/decentralized/systech/rack_creator.dm
> +		stored_research = SSresearch.ruin_tech
well the tech is learned in every factions outside from NT so yeah

2025-01-11 02:14 UTC, ToasterBiome requested changes
The issue here is that you can switch which version you're using. Someone in a ghost role can simply use a multitool to "lock" the rack creator circuit board and use the station's research.

2025-01-13 06:08 UTC, warface1234455 commented
> The issue here is that you can switch which version you're using. Someone in a ghost role can simply use a multitool to "lock" the rack creator circuit board and use the station's research.

Oh u mean that well i will make a their own version then

2025-03-21 16:32 UTC, ToasterBiome commented
Never addressed feedback

2025-03-21 16:32 UTC, closed without merging