adds back break bow, runes , magic arrow and ranger cloak to wizard
yogstation13/Yogstation pull request #22895
Opened 2024-12-29 12:44 UTC by LassiH

# Document the changes in your pull request
adds back runes, breakbow, magic arrow and ranger cloak to wizard spell book and removes embed chance of break bow blades
makes rune chest only give 1 chest instead of 2 

# Why is this good for the game?

 meant for wizard to have but they dont have them

# Wiki Documentation

mention that rune chest only gives 1 chest now

# Changelog

:cl:
rscadd: Added break bow, runes  magic arrow and ranger cloak back to wizard spellbook
tweak: removed embed chance on break bow blades 
tweak: rune chest now only gives 1 chest instead of 2
/:cl:

2024-12-29 13:26 UTC, LassiH commented
https://github.com/user-attachments/assets/0022bccd-5483-41bf-b7ff-6d04a1a3a2b9


https://github.com/user-attachments/assets/35342486-fa00-40d6-96a2-f5d14060fe40

2024-12-29 17:01 UTC, Oblisk234 requested changes
Your testing video doesn't show the summon magic arrow working, could you redo that while having robes (since it doesn't seem to be a robeless spell)?

2024-12-29 17:01 UTC, Oblisk234 commented on code/modules/antagonists/wizard/equipment/spellbook_entries/offensive.dm
> +	desc =" summons  magic arrows"
While it is true, it's not very descriptive. What can the magic arrows do, for example?

2024-12-29 18:03 UTC, LassiH commented
> Your testing video doesn't show the summon magic arrow working, could you redo that while having robes (since it doesn't seem to be a robeless spell)?


https://github.com/user-attachments/assets/25fba668-98d3-4c47-b575-d43635104d77

2025-03-01 04:16 UTC, ToasterBiome approved these changes
sure

2025-03-21 16:33 UTC, ToasterBiome commented
Bad grammar + conflicts

2025-03-21 16:33 UTC, closed without merging