Ports over some Traits from Hippie Station!
yogstation13/Yogstation pull request #2548
Opened 2018-09-14 20:35 UTC by fluffe9911

🆑 fluffe9911
add: Monochrome, Brown and Grey, Inverted Red and Blue Colors and Waddle Trait! 
/🆑
I regret nothing!

2018-09-14 20:47 UTC, Time-Green commented
We already have monochromy, and we also already have the waddle component, it’s just unused
I think you might want to remove those dupes

2018-09-14 20:49 UTC, Amelia0010 requested changes

2018-09-14 20:49 UTC, nichlas0010 commented on yogstation/code/datums/traits/neutral.dm
> +/datum/quirk/monochromatic
this is already a thing though https://github.com/yogstation13/Yogstation-TG/blob/c24df24f82d1cdb444d2b18ffa43223e1fdcef89/code/datums/traits/neutral.dm#L70

2018-09-14 22:18 UTC, fluffe9911 commented
The monochrome was just me not paying enough attention to traits and waddling was actually never enabled until now and theres a bit extra to it also made waddling cost a point due to it being a bit memey

2018-09-15 06:20 UTC, Time-Green commented
I said the component was already added but unused, not the quirk, thats new
https://github.com/yogstation13/Yogstation-TG/blob/76b6bca91b5577918132a8cf5def6834978e3786/code/datums/components/waddling.dm
The already existing waddle component is exactly the same, safe for a few sanity checks and additional variables

2018-09-15 09:53 UTC, nichlas0010 commented on yogstation/code/datums/traits/neutral.dm
> +	value = 1
honestly, having the waddle component means it's harder to change identity, whether it's via changeling transform or via chameleon kit, so maybe it should be 0 points or negative. *Or maybe a genetics mutation*

2018-09-15 17:54 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
fluffe's computer broke

2018-09-15 17:54 UTC, closed without merging

2018-09-15 19:09 UTC, nichlas0010 commented
oof