Donor chat
yogstation13/Yogstation pull request #2793
Opened 2018-10-02 13:13 UTC by thehighwayman

### Intent of your Pull Request
Re-adds donor chat so people can metacomm in peace

Fixes issue #1549

#### Changelog

:cl:  
rscadd: Adds in a ooc for donors
/:cl:

2018-10-02 14:51 UTC, Nickvr628 commented
but why

2018-10-02 16:17 UTC, nichlas0010 commented
Because it’s a prebase feature

2018-10-04 14:20 UTC, ThatLing requested changes

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +	if(is_donator(src))
``is_donator`` check isn't needed here.

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +	if(is_donator(src))
``is_donator`` check isn't needed here.

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +	set category = "Admin"
Mane, we don't need more clutter in the admin tab. Just give admins access to ``donor_ooc``.

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +var/global/normal_donor_ooc_colour = "#333333"
Put this in the css and use ``<span class='dooc'>``.

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +	if(!mob)	return
Don't use this same-line return, I wouldn't be surprised if BYOND didn't actually return because muh indentation.

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +	if(!msg)	return
Don't use this same-line return, I wouldn't be surprised if BYOND didn't actually return because muh indentation.

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +	return
Why return here?

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +		to_chat(src, "<span class='danger'>You have Donor muted.</span>")
You're checking is they have OOC muted though?

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +			to_chat(src, "<span class='danger'>Donor is globally muted.</span>")
Just change all these "Donor" messages to "OOC" to avoid any confusion.

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +
You're missing a jobban and ``QDELETED(src)`` check here.

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +	log_ooc("\[Donor\] [mob.name]/[key] : [msg]")
``mob.log_talk(raw_msg, LOG_OOC)``

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +
You're not sanitizing, limiting the length and applying the pretty filter to the message.

2018-10-04 14:20 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +		if(handle_spam_prevention(msg,MUTE_OOC))
Do this after ``msg`` has been sanitized and limited, this can be bypassed.

2018-10-04 14:24 UTC, ThatLing requested changes

2018-10-04 14:24 UTC, ThatLing commented on yogstation/code/modules/donor/donor_verbs.dm
> +/client/verb/donator_who()
Just remove the whole "being able to see donor mobs" thing and just display the ckeys of donors. Admins already have the playerpanel.

2018-10-10 06:02 UTC, nichlas0010 commented on yogstation/code/modules/donor/donor_verbs.dm
> +				msg += "\t[C] is a [C.holder.rank]"
so if they're not an admin it just says "Nichlas0010 is a "

2018-10-10 06:03 UTC, nichlas0010 commented on yogstation/code/modules/donor/donor_verbs.dm
>  					Lines += "[C.key])"
should be msg, not lines.

2018-10-21 18:45 UTC, ThatLing commented
Stale :(

2018-10-21 18:45 UTC, closed without merging