Allows catgirls to have collars put on them
yogstation13/Yogstation pull request #3381
Opened 2018-11-06 15:43 UTC by thehighwayman

### Intent of your Pull Request
I'm told by a particular catgirl that they would be able to have collars put on them by other people. this will allow that while disallowing humans from being subjugated.
#### Changelog

:cl:  
tweak: lets catgirls have collars put on them 
/:cl:

2018-11-06 15:44 UTC, MiasmaToast commented
bad PR unless it makes them valid

2018-11-06 15:46 UTC, thehighwayman commented
no clue why ktl likes this PR since it means I'm gonna put a collar on her every chance I get. Stockholm syndrome

2018-11-06 15:54 UTC, mrhugo13 commented on code/modules/clothing/neck/_neck.dm
> +		return TRUE
```suggestion
		gib()
```

2018-11-06 15:55 UTC, Nickvr628 commented
But they can already wear a collar in the next slot, like ties or scarfs.

2018-11-06 15:55 UTC, ShadowDeath6 commented
can we repo ban for this?

2018-11-06 18:37 UTC, Ktlwjec commented
i will delete all the maps if this gets closed

2018-11-06 21:43 UTC, Amelia0010 requested changes

2018-11-06 21:43 UTC, nichlas0010 commented on code/modules/clothing/neck/_neck.dm
> +	if(istype(M, /mob/living/carbon/human/species/felinid)) // yogs start - lets catpeople wear collars
you do realize we don't use this mob for purrbation, meaning this only affects people you've spawned in with this mobtype, right?

2018-11-06 21:50 UTC, nichlas0010 commented
[22:49] Nich or miss:
if(istype(M, /mob/living/carbon/human)
    var/mob/living/carbon/human/T = M
    if(istype(T.species, /datum/species/human/felinid)
        return TRUE
    return FALSE
[22:49] Thehighwayman5 (WILDCARD): can't do that
[22:49] Thehighwayman5 (WILDCARD): you'll get an error
[22:49] Nich or miss: okay then it's not getting merged

2018-11-06 22:24 UTC, Amelia0010 approved these changes

2018-11-06 22:25 UTC, Amelia0010 requested changes

2018-11-06 22:25 UTC, Amelia0010 commented on code/modules/clothing/neck/_neck.dm
> +	if(istype(M, /mob/living/carbon/human)  // yogs start - lets catpeople wear collars
you forgot the second parenthesis

2018-11-06 22:26 UTC, thehighwayman commented on code/modules/clothing/neck/_neck.dm
> +	if(istype(M, /mob/living/carbon/human)  // yogs start - lets catpeople wear collars
fuck you

2018-11-06 22:26 UTC, Ktlwjec commented on code/modules/clothing/neck/_neck.dm
> +	if(istype(M, /mob/living/carbon/human)  // yogs start - lets catpeople wear collars
silly sausage!

2018-11-14 16:14 UTC, Ktlwjec commented
https://forums.yogstation.net/index.php?threads/vote-merge-the-pr-to-allow-felinid-to-wear-pet-collars.17795/ yeeted

2018-11-14 16:21 UTC, Amelia0010 requested changes

2018-11-14 16:21 UTC, nichlas0010 commented on code/modules/clothing/neck/_neck.dm
> +	if(istype(M, /mob/living/carbon/human))  // yogs start - lets catpeople wear collars
if(ishuman(M))

2018-11-14 22:27 UTC, Amelia0010 approved these changes

2018-11-14 22:28 UTC, merged