Disposals Wires
yogstation13/Yogstation pull request #3651
Opened 2018-11-27 05:10 UTC by monster860

Basically, the way it works is really simple. There's the forward wire, side wire, and scan wire. The forward and side wires, when pulsed, set the current "sorting state" of the pipe to their respective zones. Forward is red and side is green. The scan wire, when cut, disables scanning, and when pulsed disables it for only 10 seconds. When scanning is disabled, the pipe does not scan the package for whether or not it should sort. Instead, it just reads the sorting state.

So in order to hack a disposals pipe, you need to disable scanning, and then specify a direction to travel.

Includes really shitty wire-panel-open sprites made by me:
![image](https://user-images.githubusercontent.com/3681297/49059666-f37b3200-f1d7-11e8-861b-6c6a40bade62.png)
It looks like someone dragged a dead body into the pipes. In fact, that yellow-grey blob is actually supposed to be a cover, and the red lines are supposed to be wires.

things you can do:

- set up a trap using a disposals loop and a proximity sensor that causes it to spit out it's contents at you when you approach. Feed it with sharp objects, and find an unsuspecting target.
- permanently redirect all trash into the RD's office. He might get suspicious though.
- Make a disposals loop, get a bunch of people inside, and then whack the button to redirect them into a pipe that spaces them at the same time. 
- Temporarily redirect disposals into space for when you're disposing of a body.
- I dunno, you figure shit out.

here's a 3-minute video demonstrating this feature: https://streamable.com/frfar

:cl: monster860
add: Disposals sorting pipes can now be hacked! Force them to always on or always off, or even temporarily force it with a remote signaller.
/:cl:

2018-11-27 06:43 UTC, Moja10 commented
amazing shit

2018-11-29 01:19 UTC, Amelia0010 requested changes

2018-11-29 01:19 UTC, nichlas0010 commented on yogstation/code/modules/recycling/disposal/pipe_sorting.dm
> +	if(I.tool_behaviour == TOOL_SCREWDRIVER)
screwdriver_act

2018-11-29 01:20 UTC, nichlas0010 commented on yogstation/code/modules/recycling/disposal/pipe_sorting.dm
> +	if(I.tool_behaviour == TOOL_SCREWDRIVER)
other than this it's fine

2018-11-29 01:31 UTC, merged