Lowers cost of certain vampire abilitys
yogstation13/Yogstation pull request #3656
Opened 2018-11-28 02:57 UTC by fluffe9911

More vamp stuff

2018-11-28 14:13 UTC, ShadowDeath6 commented
Changelog please

2018-11-29 01:11 UTC, Amelia0010 requested changes
what jelly said

2018-11-29 01:21 UTC, fluffe9911 commented
mk

2018-11-30 11:29 UTC, Amelia0010 approved these changes

2018-12-01 17:39 UTC, merged