Adds 8 New Bars To the Bar Randomizer (1 new) (7 old)
yogstation13/Yogstation pull request #3940
Opened 2018-12-22 00:57 UTC by fluffe9911

🆑 fluffe9911
add: 8 new bars that the regular bar can possibly become including a new space bar!
/🆑

Most of the Bars can be found here https://github.com/yogstation13/yogstation/pull/3109

Only new bar is a Space Bar which is a Bar but with fake space tiles some of the others have also been modified a bit to make them look better (mostly conveyor)

2018-12-22 11:21 UTC, Time-Green commented
h o l e b a r

2018-12-26 11:24 UTC, ThatLing requested changes

2018-12-26 11:24 UTC, ThatLing commented on tgstation.dme
> +#include "_maps\shuttles\whiteship_delta.dmm"
No

2018-12-26 20:56 UTC, fluffe9911 commented on tgstation.dme
> +#include "_maps\shuttles\whiteship_delta.dmm"
No idea how that got there

2019-01-03 01:21 UTC, closed without merging