Tool Switcher
yogstation13/Yogstation pull request #3943
Opened 2018-12-22 05:02 UTC by monster860

https://streamable.com/50jt6

:cl: monster860
rscadd: Adds tool switcher. Load it up with tools, and program a sequence of tools, then use it in your hand to play through that sequence
/:cl:

2018-12-22 06:14 UTC, Ratvar commented
Does it work on surgeon tools?
Why not make it work on *anything*?

2018-12-22 15:43 UTC, Moja10 commented
Looks broken beyond words. Should be traitor nukeop only imo

2018-12-22 20:23 UTC, ghost commented
Not faster than any of the upgraded tools, but it does eliminate the need for a toolbelt.

It's basically an arm-mounted surgical toolkit implant, but disarmable, and without the increased movespeed.

Give it a mineral req and it should be fine to shove over 'experimental tools'

2018-12-22 21:30 UTC, monster860 commented
It can do surgery but the circular saw doesn't fit in side so it's not that useful for that.

2018-12-23 13:33 UTC, jcatjmeow commented
"program a sequence of tools"
You guys are forgetting this part
10/10 i love this more than my son

2018-12-26 11:25 UTC, ThatLing requested changes

2018-12-26 11:25 UTC, ThatLing commented on code/modules/research/designs/tool_designs.dm
> +/datum/design/tool_switcher
yogs start

2018-12-26 19:05 UTC, monster860 commented on code/modules/research/designs/tool_designs.dm
> +/datum/design/tool_switcher
there fixed

2019-01-04 12:12 UTC, merged