Makes Family Heirloom Free but you can get it again
yogstation13/Yogstation pull request #3969
Opened 2018-12-25 15:41 UTC by fluffe9911

Its pretty neat

2018-12-28 19:27 UTC, ThatLing commented
modular

2018-12-29 19:18 UTC, fluffe9911 commented
oh yeah forgot about that

2019-01-01 20:26 UTC, ThatLing requested changes
still not modular

2019-01-02 18:23 UTC, fluffe9911 commented
ugh fine

2019-01-02 18:27 UTC, closed without merging