EXPAND YOUR GREMLIN
yogstation13/Yogstation pull request #4004
Opened 2019-01-01 19:09 UTC by fluffe9911

🆑 fluffe9911 for porting steamp0rt for actually coding it
add: gremlins can now randomly appear around the station and screw around with electronics!
/🆑

see https://github.com/HippieStation/HippieStation/pull/3098 for more details

2019-01-01 19:39 UTC, steamp0rt commented
is your idea list literally just searching hippie's repo for `author:steamp0rt`, @fluffe9911

2019-01-01 20:05 UTC, ThatLing commented
@steamp0rt stop ban evading

@fluffe9911 lower event chance

2019-01-01 20:27 UTC, ghost commented
@ThatLing let me appeal then. 


what if i port slings

2019-01-01 20:44 UTC, fluffe9911 commented
@steamp0rt Nah I just look threw random codebases for things I like and it just so happens hippie not only has a ton of N E A T ideas its also extremely easy to port since both yogs and hippie stay up to date with tg also mcdonald already ported slings ( gangs isnt ported yet though)

@ThatLing done

2019-01-01 20:54 UTC, steamp0rt commented
@fluffe9911 oh nice he used my shadowling code... without credit

2019-01-01 20:56 UTC, fluffe9911 commented
Yeah guess he didn't think to *shrug*

2019-01-04 11:50 UTC, ThatLing requested changes

2019-01-04 11:50 UTC, ThatLing commented on yogstation/code/modules/uplink/uplink_item.dm
> +	surplus = 5
no

2019-01-04 11:50 UTC, ThatLing commented on yogstation/code/modules/uplink/uplink_item.dm
> +	cost = 2
up this

2019-01-04 11:50 UTC, ThatLing commented on yogstation/code/modules/mob/living/simple_animal/gremlin/event.dm
> +	weight = 10
Lower this

2019-01-04 11:50 UTC, ThatLing commented on yogstation/code/modules/mob/living/simple_animal/gremlin/event.dm
> +	max_occurrences = 2
1

2019-01-04 12:03 UTC, ThatLing commented
@steamp0rt why can't you appeal?

2019-01-05 01:56 UTC, fluffe9911 commented
@ThatLing you are aware these are simple mobs and not naturally player controlled right?

2019-01-05 15:17 UTC, steamp0rt commented
@ThatLing i dunno i just assumed i can't. i guess i can

2019-01-05 22:09 UTC, closed without merging