Adds 7 New Bars To the Bar Randomizer (1 new) (6 old) Branch Edition V2!
yogstation13/Yogstation pull request #4116
Opened 2019-01-07 18:02 UTC by fluffe9911

🆑 fluffe9911
add: 7 new bars that the regular bar can possibly become including a xeno bar!
/🆑

Most of the Bars can be found here yogstation13/yogstation#3109

One new bar is Xeno bar which is pretty self explanatory

2019-01-07 18:02 UTC, Time-Green commented
you ok man?

2019-01-07 18:03 UTC, ThatLing commented
Delete corporate and xeno

2019-01-07 18:03 UTC, ThatLing commented on tgstation.dme
> +#include "yogstation\code\game\objects\effects\decals\turfdecal.dm"
Remove

2019-01-07 23:02 UTC, Ktlwjec commented
![image](https://user-images.githubusercontent.com/34506490/50798443-49abbc80-12d0-11e9-8627-9f4487b50df0.png)
I just noticed this table isn't reinforced on the server please change xoxo

2019-01-09 17:56 UTC, ThatLing requested changes

2019-01-09 17:56 UTC, ThatLing commented on tgstation.dme
> +#include "yogstation\code\game\objects\effects\decals\turfdecal.dm"
Remove this from tgstation.dme

2019-01-09 17:56 UTC, ThatLing commented on yogstation/code/datums/ruins/station.dm
> +/datum/map_template/ruin/station/box/bar/xeno
Remove xenobar, also isn't in

2019-01-09 17:56 UTC, ThatLing commented on yogstation/code/datums/ruins/station.dm
> +/datum/map_template/ruin/station/box/bar/ragecage
This one isn't even in?

2019-01-09 17:56 UTC, ThatLing commented on yogstation/code/datums/ruins/station.dm
> +/datum/map_template/ruin/station/box/bar/space
This one isn't in

2019-01-09 17:56 UTC, ThatLing commented on yogstation/code/datums/ruins/station.dm
> +/datum/map_template/ruin/station/box/bar/corporate
This one isn't in

2019-01-09 17:56 UTC, ThatLing commented on yogstation/code/game/objects/effects/landmarks.dm
> +	template_names = list("Bar Trek", "Bar Spacious", "Bar Box", "Bar Casino", "Bar Conveyor", "Bar Corporate", "Bar Diner", "Bar Disco", "Bar Purple", "Bar Ragecage", "Bar Space", "Bar Xeno")
Again, some of these aren't in

2019-01-09 17:56 UTC, ThatLing commented on yogstation/code/game/objects/structures/bar_stuff/bar_stuff.dm
> +/turf/open/floor/alien
Remove all this xenobar stuff, including icons

2019-01-11 16:18 UTC, Amelia0010 requested changes
Decal dirs were changed in https://github.com/tgstation/tgstation/pull/42261, mirrored in https://github.com/yogstation13/Yogstation-TG/pull/4141. To fix your decals, update your branch to latest master then run the fixcorners.txt script by doing the following after opening command line in the tools/mapmerge2 folder:

python -m update_paths --map [path-for-the-map-you're-updating] [path-for-the-fixcorners-script,-will-end-in-tools/mapmerge2/map_scripts/fixcorners.txt

2019-01-12 00:46 UTC, fluffe9911 commented
>nich tells me to use the script to fix my decals
>I have none of the effected decals in any of my map prs
>nich please

2019-01-12 12:53 UTC, Amelia0010 approved these changes
I just copy pasted that on all map PRs to make sure it wasn't bork :)

2019-01-12 17:20 UTC, closed without merging

2019-01-12 17:55 UTC, nichlas0010 commented
I swear to god stop fucking deleting your repos you mongrel