[WIP] NanoTrasen Scripting Language
yogstation13/Yogstation pull request #4217
Opened 2019-01-18 00:54 UTC by Altoids1

### Happy Rebase Anniversary!
![image](https://user-images.githubusercontent.com/29939414/51358463-f92f1e80-1a88-11e9-80ac-247708a69804.png)

I wanted to get this set up before I retired, but I got a bit busy. Anyways, here it is.

Yes, I know it's not modularized at all at the moment; I want to do that at the very end.

#### Changelog

:cl:  
rscadd: NTSL has finally returned!
/:cl:

2019-01-18 00:54 UTC, fluffe9911 commented
holy cow nice

2019-01-18 01:15 UTC, Fillywonk commented
Oh gosh, this is mighty mighty fine.

2019-01-18 01:18 UTC, Altoids1 commented
Travis seems to be complaining about shitcode that was already present prebase, so I guess I'll have to clean up the inner code itself, too. God help me.

2019-01-18 02:01 UTC, Moja10 commented
Very awesome!!!

2019-01-18 03:30 UTC, Amelia0010 commented
But does it let you edit UUID?

2019-01-18 11:09 UTC, ThatLing commented
But does it let you gib everyone on the server?

2019-01-18 14:08 UTC, alexkar598 commented
No it does not,if you can abuse this to run JavaScript than nothing in this game is safe from JavaScript injection

2019-01-19 21:16 UTC, steamp0rt commented
time to goatse everyone

2019-01-19 21:16 UTC, k-k-karma commented
how about programming the compielr in javascript and NOT FUCKING DM

2019-01-19 21:17 UTC, ghost commented
this nearly made me spit out my drink when @k-k-karma linked it

2019-01-20 17:40 UTC, monster860 commented
Oh god

\> uses datum paths that dont start with /datum
\> relative pathing
\> AAAAAAA

2019-01-20 20:01 UTC, Altoids1 commented
> Oh god
> 
> \>uses datum paths that dont start with /datum
> \>relative pathing
> \>AAAAAAA

Yeaah, it's definitely a mess. Reading through the code itself, you can also find a ton of just weird design decisions and inefficiencies by the original author, which I'm hoping I can start fixing either in this PR or in future ones.

2019-01-24 10:06 UTC, Altoids1 commented
![image](https://user-images.githubusercontent.com/29939414/51670925-5f3a0b00-1f8d-11e9-8e5a-934411640d45.png)

2019-01-25 02:48 UTC, MegaEmpirical commented
Lovely. Keep it up.

2019-01-27 04:50 UTC, Altoids1 commented
![image](https://user-images.githubusercontent.com/29939414/51796714-d0133a00-21bc-11e9-81c2-db0b807fd229.png)
It's good to be back.

2019-01-27 05:30 UTC, Altoids1 commented
**Ready for Review.**

2019-01-27 15:58 UTC, monster860 commented
```dm
proc name: Run (/datum/TCS_Compiler/proc/Run)
usr: Code_Anti-Thot/(Joseph Prat)
usr.loc: (Telecomms Control Room (161, 59, 2))
src: /datum/TCS_Compiler (/datum/TCS_Compiler)
call stack:
/datum/TCS_Compiler (/datum/TCS_Compiler): Run(/datum/signal (/datum/signal))
Code_Anti-Thot (/client): tcsrun()
```

2019-01-27 17:04 UTC, Amelia0010 requested changes

2019-01-27 17:04 UTC, Amelia0010 commented on yogstation/code/modules/scripting/Implementations/Telecomms.dm
> +	interpreter.SetVar("$sector" , 	signal.levels)
```suggestion
	interpreter.SetVar("$sector" , 	signal.lvls)
```

2019-01-27 17:04 UTC, Amelia0010 commented on yogstation/code/modules/scripting/Parser/Parser.dm
> +			if(curToken.value!=val || !istype(curToken,type))
[17:01:57] Runtime in Parser.dm, line 131: Cannot read null.value
```proc name: CheckToken (/n_Parser/nS_Parser/proc/CheckToken)
usr: Code_Anti-Thot/(Joseph Prat)
usr.loc: (Telecomms Control Room (161, 60, 2))
src: /n_Parser/nS_Parser (/n_Parser/nS_Parser)
call stack:
/n_Parser/nS_Parser (/n_Parser/nS_Parser): CheckToken(")", /token/symbol (/token/symbol), 1, 1)
/n_Keyword/nS_Keyword/kwIf (/n_Keyword/nS_Keyword/kwIf): Parse(/n_Parser/nS_Parser (/n_Parser/nS_Parser))
/n_Parser/nS_Parser (/n_Parser/nS_Parser): Parse()
/datum/TCS_Compiler (/datum/TCS_Compiler): Compile("def implode($vector, $adder)\n...")
Common Server (/obj/machinery/telecomms/server/presets/common): compile(Joseph Prat (/mob/living/carbon/human))
Code_Anti-Thot (/client): tcscompile()```

2019-01-27 17:04 UTC, Amelia0010 commented on yogstation/code/modules/scripting/Parser/Keywords.dm
> +/n_Keyword
could we please not do relative pathing

2019-01-27 17:04 UTC, Amelia0010 commented on yogstation/code/modules/scripting/Parser/Keywords.dm
> +/n_Keyword
Oh and non-datum datums :(

2019-01-27 17:04 UTC, Amelia0010 commented on yogstation/code/modules/scripting/Interpreter/Interaction.dm
> +				x = sanitize(x)
```suggestion
				x = sanitize(pretty_filter(x))
```
Players can't be trusted with shit

2019-01-27 18:49 UTC, ThatLing requested changes

2019-01-27 18:49 UTC, ThatLing commented on yogstation/code/modules/scripting/Implementations/Telecomms.dm
> +	interpreter.SetProc("randseed", /proc/n_randseed)
Delete this

2019-01-27 20:26 UTC, monster860 commented
bad:
```
/somePath
    subtype1
        x = 2
    subtype2
        x = 5
```

good:
```
/datum/some_path/subtype1
    x = 2
/datum/some_path/subtype2
    x = 5
```

2019-01-27 20:28 UTC, monster860 commented on yogstation/code/modules/scripting/Implementations/Telecomms.dm
> +	interpreter.SetProc("randseed", /proc/n_randseed)
Yeah, this could be used to consistently win a pulse rifle as a prize or something.

2019-01-27 20:36 UTC, monster860 requested changes

2019-01-27 20:36 UTC, monster860 commented on yogstation/code/modules/scripting/Parser/Parser.dm
> +				stmt.value:exp2=ParseExpression()
AaaAAAaaAAAAaaaaaaa no colon operators please

2019-01-27 20:36 UTC, monster860 commented on yogstation/code/modules/scripting/Implementations/Telecomms.dm
> +	signal.levels 				= interpreter.GetCleanVar("$sector", signal.levels)
nich forgot this one.

```suggestion
	signal.lvls 				= interpreter.GetCleanVar("$sector", signal.levels)
```

2019-01-27 20:49 UTC, Altoids1 commented
> bad:
> 
> ```
> /somePath
>     subtype1
>         x = 2
>     subtype2
>         x = 5
> ```
> good:
> 
> ```
> /datum/some_path/subtype1
>     x = 2
> /datum/some_path/subtype2
>     x = 5
> ```

Yes, I know. I didn't write that code. All of this is stuff that was present during prebase. I just haven't gotten to reformatting it yet because I wanted a working PR as soon as possible.

2019-01-27 20:59 UTC, Altoids1 commented
Current known bugs not yet listed by reviewers:

- [ ] Setting someone's job via the ID console to Signal Technician doesn't do anything.
- [ ] Signal Technicians do not have engineering access by default.

2019-01-28 12:49 UTC, Firewolf34 commented
I love you for making this. NTSL is awesome.

2019-01-28 20:53 UTC, monster860 requested changes

2019-01-28 20:53 UTC, monster860 commented on yogstation/code/modules/scripting/Implementations/Telecomms.dm
> +GLOBAL_LIST_INIT(allowed_custom_spans,list(SPAN_ROBOT,SPAN_YELL,SPAN_ITALICS,SPAN_SANS,SPAN_COMMAND))//Span classes that players are allowed to set in a radio transmission.
Please add .clown - you know, the one for the clown's megaphone.

2019-01-29 01:27 UTC, MegaEmpirical commented
There is no HUD icon for the signal tech job.

2019-01-29 01:32 UTC, MegaEmpirical commented
Also, some weird image appears for a fraction of a second when opening the scripting window. Some kind of comic?

2019-01-29 02:09 UTC, Altoids1 commented
> Also, some weird image appears for a fraction of a second when opening the scripting window. Some kind of comic?

...**_What?_**

@MegaEmpirical , if that is a genuine bug report, I am closing this PR and walking into the sea, for fear of being smited by whatever god of technology has cursed you and your computer.

2019-01-29 02:39 UTC, MegaEmpirical commented
I was hoping you'd know about it. I tried taking a screen shot but it's too fast. Guess I'll have to take a video and get the frame tomorrow.

2019-01-29 02:44 UTC, fluffe9911 commented
I know what he is talking about its a bug with menus in general where if you open it sometimes for a fraction of a second it will display whatever is on your background screen atm its a weird bug

2019-01-29 02:54 UTC, MegaEmpirical commented
Hmm, wasn't anything I recognized.... signal techs can't enter engineering from the monitoring hall?

2019-01-29 03:55 UTC, Altoids1 commented
> Hmm, wasn't anything I recognized.... signal techs can't enter engineering from the monitoring hall?
That's been fixed, which I've marked in the bug list a few posts up from here (as well as in the commit after that bugfix)

2019-01-30 02:17 UTC, Altoids1 commented on yogstation/code/modules/scripting/Parser/Parser.dm
> +			if(curToken.value!=val || !istype(curToken,type))
Implode is a function that I believe is already defined in NTSL. He might be getting that bug because the keyword is already being used by that default function, so the fault might be on him.

Regardless, yeah, that should result in an error message put on the server monitor, not a runtime. Will work on it.

2019-01-30 09:19 UTC, Altoids1 commented on yogstation/code/modules/scripting/Implementations/Telecomms.dm
> +	interpreter.SetVar("$sector" , 	signal.levels)
/datum/signal/subspace/vocal has no member called ``lvls``. Where are you getting that from?

2019-01-30 11:08 UTC, Altoids1 commented on yogstation/code/modules/scripting/Interpreter/Interaction.dm
> +				x = sanitize(x)
Using ``pretty_filter()`` directly is just going to replace the text with _"BAN ME ADMINS!"_ The real solution is to port some of the pretty filter code I did for Barony13 so I can have some custom ``message_admins()`` code here.

2019-01-30 11:43 UTC, Altoids1 commented on yogstation/code/modules/scripting/Parser/Keywords.dm
> +/n_Keyword
I'm just gonna have Fluffe deal with this for me.

2019-01-30 12:04 UTC, nichlas0010 commented on yogstation/code/modules/scripting/Interpreter/Interaction.dm
> +				x = sanitize(x)
or do what I did here https://github.com/yogstation13/Yogstation-TG/pull/123/files#diff-f3d16bf714186cf32008676797455af6R11

2019-01-30 22:08 UTC, Altoids1 commented on yogstation/code/modules/scripting/Implementations/Telecomms.dm
> +	interpreter.SetProc("randseed", /proc/n_randseed)
>  _  >

2019-02-01 22:33 UTC, Altoids1 commented
Apparently Nich decided to merge #4361 , so, that's the merge conflict that's "ToO ComPleX To SolVE In ThE WeB EdiTOr"

2019-02-01 23:11 UTC, nichlas0010 commented
appanrelty nick decisded to merge a mriror? woh'dve thonked

2019-02-03 21:21 UTC, Altoids1 commented
**_TAKE ME DOWN TO MERGE CONFLICT CITY WHERE THE MIRRORS ARE SHIT AND CHECKS AREN'T PRETTY_**

2019-02-04 20:51 UTC, TheGamerdk commented
fix merge conflict or face INSTANT DEATH

2019-02-07 21:20 UTC, Altoids1 commented on yogstation/code/modules/scripting/Parser/Parser.dm
> +			if(curToken.value!=val || !istype(curToken,type))
I don't know *exactly* what caused Code to have this error in the firstplace, so I can't be sure that I've fixed it, but I've eliminated the chance of it causing a runtime, so, :shrug:

2019-02-10 23:54 UTC, Altoids1 commented
# Ready.

2019-02-10 23:55 UTC, monster860 commented
![image](https://user-images.githubusercontent.com/3681297/52541637-61f67780-2d65-11e9-8ec2-4deb92bfcfe4.png)

2019-02-10 23:59 UTC, merged