Readding Old Lavaland Ruins Part 3 The Other Ones
yogstation13/Yogstation pull request #4309
Opened 2019-01-27 20:49 UTC by fluffe9911

🆑 fluffe9911 for porting Super3222 for making
add: The Necromancy House, DND Ritual, Goliath Mound, Legion Barracks, NT Surveyor are back!
add: Research Outpost, Syndicate Pod, Watcher Spiral, Weaver Nest and Wizard Den are also back!
add:  Marrow Weavers have also returned to lavaland as well as there recipes!
/🆑

2019-01-27 22:24 UTC, Bibby0110 commented
description = "Only Malarky the mad would be mad enough to live in a wooden shack on this planet"
WHAT IS THIS, FIX THIS INSTANTLY
description = "Only Malarky the Mad would be mad enough to live in a wooden shack on this planet"

2019-01-31 11:38 UTC, Amelia0010 requested changes

2019-01-31 11:38 UTC, nichlas0010 commented on _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
> +/obj/structure/closet/crate/necropolis,
>:(

2019-02-01 11:14 UTC, merged

2019-02-06 19:44 UTC, Time-Green commented
oh god no not marrow fucking weavers aaaa