:b:ig :b:ad :b:lock cult fix
yogstation13/Yogstation pull request #4443
Opened 2019-02-10 02:20 UTC by SomeguyManperson

This sets ocular wardens to shoot 4 times slower and deal 4 times more damage, as well as changing the mobility flag check to an isstun(). Wardens won't freeze people who are running but can still freeze people who are resting or walking if they have damage slowdown.
![fix](https://user-images.githubusercontent.com/24857008/52528582-539a5400-2cb0-11e9-8cb0-4569f8fa796c.PNG)

:cl:  Theos
bugfix: Ocular wardens will now shoot people who are resting
bugfix: Ocular wardens will also now not paralyze people from the legs down in most cases
/:cl:

2019-02-10 02:31 UTC, AdamElTablawy commented
i ded pr

2019-02-10 02:41 UTC, Nickvr628 commented
Does it shoot people laying down in crit as well, or just resting people?

2019-02-10 02:43 UTC, SomeguyManperson commented
the warden already checked for crit seperately, this won't change that

2019-02-22 19:03 UTC, monster860 requested changes

2019-02-22 19:03 UTC, monster860 commented on code/modules/antagonists/clockcult/clock_structures/ocular_warden.dm
> +					last_process = world.time
you should be doing a //yogs start and a //yogs end

2019-02-23 15:51 UTC, monster860 approved these changes
eh good enough

2019-02-23 15:52 UTC, merged