Fixing more ruin bugs!
yogstation13/Yogstation pull request #4490
Opened 2019-02-14 23:40 UTC by fluffe9911

🆑 fluffe9911
tweak: Cosmic Ashwalkers can now wear shoes!
bugfix: Chemistry Ruin is no longer filled with ash
tweak: More stuff has been added and or fixed with the gas station ruin!
/🆑

Cosmic Ashwalkers are now a lizard subtype instead of a ashwalker one so they can wear shoes now 
(they will still be ashwalkers lore wise though) and for the Gas Station Ruin they now have a slightly better toolbox, a instrument to play music and stuff, Display Cases to store more valuable things, Emergency Supplies so they can repair the gas station incase someone starts breaking it open and other bugs I fixed from #4481 

So yeah fixes #4481 and fixes #4487

2019-02-15 08:58 UTC, Time-Green commented
Why do they need to wear shoes? Ashwalkers can’t and cosmic ashwalker is simply an abducted ashwalker.

Unless its feet abductors in wich case it makes sense

2019-02-15 16:49 UTC, fluffe9911 commented
Because they got a pair of no slips in there locker and since theres no thing in place to make shoes digigrade compatible easily decided to just make it a lizard subtype just think of it as the abductors giving it normal feet since having feet that could not wear shoes would be a disadvantage for what the abductors planned on using the ashwalker for

2019-02-18 14:22 UTC, Time-Green commented
also just remove the digitgrade on cosmic ashwalkers
species_traits = list(MUTCOLORS,EYECOLOR,LIPS)
instead of species_traits = list(MUTCOLORS,EYECOLOR,LIPS,DIGITIGRADE)

2019-02-18 15:38 UTC, fluffe9911 commented
That is much better solution I did not think of will do

2019-02-21 22:51 UTC, Altoids1 approved these changes
Does not include any pulse rifle pistols, 👍 from me

2019-02-22 03:02 UTC, Altoids1 requested changes

2019-02-22 03:02 UTC, Altoids1 commented on yogstation/code/modules/ruins/lavaland_ruin_code.dm
> +	flavour_text = "<span class='big bold'>You are a Gas Station Clerk.</span><b> The gas station you worked most of your life in was moved to some hellhole in the middle of nowhere for some reason, you
You have a \<b\> in there with no ending \</b\>.

2019-02-22 03:06 UTC, Altoids1 approved these changes

2019-02-22 22:32 UTC, merged