Fixes Narsians' whispers being in Common
yogstation13/Yogstation pull request #4547
Opened 2019-02-22 20:41 UTC by Altoids1

### Jesus Christ this issue is from September how did you even find it Altoids

I've been going through a bunch of old Github issues and closing them for being fixed/stupid, and I came across one I thought I could fix in like 10 seconds.

I actually have no idea if this issue is even still existent, I just saw it on Github at school and wanted to get this PR set up before I had a test of it at home today.

Fixes #2714

#### Changelog

:cl:  Altoids
bugfix: Blood cultists no longer speak in Common when they're actually speaking in their scary scary blood language.
/:cl:

2019-02-22 22:41 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b approved these changes
doesn't suck

2019-02-22 23:39 UTC, monster860 requested changes

2019-02-22 23:39 UTC, monster860 commented on code/modules/antagonists/cult/cult_comms.dm
> +	user.whisper(html_decode(message), language = /datum/language/narsie)
```suggestion
	user.whisper(html_decode(message), language = /datum/language/narsie) // yogs
```

reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

2019-02-23 00:17 UTC, Altoids1 commented on code/modules/antagonists/cult/cult_comms.dm
> +	user.whisper(html_decode(message), language = /datum/language/narsie)
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

2019-02-23 00:23 UTC, monster860 approved these changes

2019-02-23 00:23 UTC, merged