[admin] Ports the AFK verb from prebase
yogstation13/Yogstation pull request #4663
Opened 2019-03-03 23:03 UTC by Altoids1

## Sokath, his eyes covered!
![image](https://user-images.githubusercontent.com/29939414/53703284-e329b300-3dd5-11e9-9f49-256cbbc8625d.png)

#### Changelog
:cl:  Altoids
rscadd: The AFK verb has been re-added! Use it when you want to quickly inform everyone of you being AFK.
/:cl:

2019-03-04 15:45 UTC, Amelia0010 requested changes

2019-03-04 15:45 UTC, nichlas0010 commented on yogstation/code/modules/client/verbs/afk.dm
> +		if(!M || !M.job)
```suggestion
		if(!M.job)
```
You already check whether there's a mob in line 6.

2019-03-04 15:45 UTC, nichlas0010 commented on yogstation/code/modules/client/verbs/afk.dm
> +			if(M.job == "AI" || istype(M, /mob/living/silicon))
```suggestion
			if(istype(M, /mob/living/silicon))
```

2019-03-04 15:45 UTC, nichlas0010 commented on yogstation/code/modules/client/verbs/afk.dm
> +			else if(M.job == "Captain" || M.job == "Head of Personnel" || M.job == "Head of Security" || M.job == "Chief Engineer" || M.job == "Research Director" || M.job == "Chief Medical Officer")
```suggestion
			else if(M.job in GLOB.command_positions)
```

2019-03-04 15:45 UTC, nichlas0010 commented on yogstation/code/modules/client/verbs/afk.dm
> +				M.say(".h [text] This is the [M.job] signing off for now.")
doesn't alert command?

2019-03-04 19:41 UTC, merged

2019-03-07 00:48 UTC, Lynameep commented
Thanks dad.