Puts a cap on butterflies spawned from the Severe Anxiety disease
yogstation13/Yogstation pull request #4671
Opened 2019-03-04 23:42 UTC by Altoids1

## Holy Shit why are there 500 dead butterfly corpses
![image](https://user-images.githubusercontent.com/29939414/53770363-6d404d00-3ea4-11e9-9c0e-290a954a3bd4.png)

So a few days back there was a highpop round where this Anxiety disease spread to just about everybody. 45 minutes later into the round, we had people (especially those on potato computers) lagging out hard or even having to disconnect, due to the 500-odd butterflies which had infested basically every tile of Medbay and the populous hallways.

This PR puts a cap on the total amount of butterflies that can be spawned by this disease, at a reasonable **250**. Hopefully this will help improve the performance of this.

#### Changelog
:cl:  Altoids
bugfix: The Anxiety disease can no longer spawn an infinite number of butterflies. Just 250.
/:cl:

2019-03-07 15:19 UTC, Amelia0010 requested changes
make butterflies dying bring the count down again.

2019-03-07 20:34 UTC, Altoids1 commented
Nich why would there need to be more than 250 butterflies on the station, dead or alive

2019-03-07 21:18 UTC, nichlas0010 commented
because otherwise it doesn't do butterflies anymore ;-;

2019-03-11 07:11 UTC, ThatLing commented
just kill the old ones when a new one spawns

2019-03-31 02:06 UTC, Kmc2000 commented on code/datums/diseases/anxiety.dm
> +				if(butterfly_count.len > 250)
This seems like an ultra clunky way to do it.
Could you not simply add a reference to this disease to the butterfly mobs, and then on death() have it remove itself from the list?

2019-03-31 02:06 UTC, Kmc2000 commented on yogstation/code/datums/diseases/anxiety.dm
> +	var/static/list/butterfly_count = list() // Counts how many butterflies have been spawned by this disease
Why static?

2019-03-31 02:06 UTC, Kmc2000 commented on code/datums/diseases/anxiety.dm
> +				var/mob/living/simple_animal/butterfly/Alpha = new(affected_mob.loc)
I don't get the point of this

2019-05-15 07:29 UTC, closed without merging