(Paid) Adds some more donator borgs + fixes a typo
yogstation13/Yogstation pull request #4688
Opened 2019-03-06 17:25 UTC by Kmc2000

### Intent of your Pull Request

![](https://cdn.discordapp.com/attachments/552507910236799007/552903376577232906/unknown.png)

Contact FatalEyes if you want to request borg skins.

#### Changelog

:cl: Kmc2000
rscadd: Added new borg skins for donators
/:cl:

2019-03-06 20:29 UTC, ThatLing requested changes

2019-03-06 20:29 UTC, ThatLing commented on yogstation/code/modules/donor/borg_ai_skin_datums.dm
> +/datum/borg_skin/snailborg
Yeah, no

2019-03-07 10:47 UTC, Kmc2000 commented
ready for merge

2019-03-07 13:17 UTC, Amelia0010 requested changes
You do not need to do `owner = null`, it inherits that from the parent type.

2019-03-07 13:17 UTC, Kmc2000 commented
I know Nich.
It's to clearly show which ones are universal

2019-03-07 13:18 UTC, nichlas0010 commented
🤔

2019-03-07 13:18 UTC, Kmc2000 commented
Pettiness 100

2019-03-07 13:19 UTC, nichlas0010 commented
101*

2019-03-07 15:17 UTC, merged