Fixes more King Goat Boss Cheese
yogstation13/Yogstation pull request #4823
Opened 2019-03-19 17:54 UTC by fluffe9911

Using the power of portals and science you can no longer cheese the king goat by standing outside the one way entrance and shooting at it honk

2019-03-20 00:37 UTC, Altoids1 requested changes

2019-03-20 00:37 UTC, Altoids1 commented on code/game/objects/effects/portals.dm
> +/obj/effect/portal/permanent/teleport(atom/movable/M, force = FALSE) // Yogs start made perma portals always teleport even in noteleport areas since they are mapmaker only
You could just move your copy of the proc over to the /yogstation/ folder, for modularity.

2019-03-20 00:37 UTC, Altoids1 commented on yogstation/code/game/objects/items/storage/boxes.dm
>  		new /obj/item/reagent_containers/food/snacks/monkeycube/goat(src)
Why, tho?

2019-03-20 14:15 UTC, fluffe9911 commented on yogstation/code/game/objects/items/storage/boxes.dm
>  		new /obj/item/reagent_containers/food/snacks/monkeycube/goat(src)
Altoids pls

2019-03-21 11:13 UTC, Altoids1 approved these changes

2019-03-22 00:15 UTC, merged