After nine years in development, hopefully it will have been worth the weight
yogstation13/Yogstation pull request #4924
Opened 2019-03-24 05:18 UTC by SomeguyManperson

### Intent of your Pull Request

![fryingpan](https://user-images.githubusercontent.com/24857008/54875262-0098de00-4dd2-11e9-8df6-e50db7dd46ba.png)

:cl:  
rscadd: Adds the frying pan, a weapon capable of annoying literally everyone to death
rscadd: Adds a special frying pan for traitors and nuke ops for the low low price of 40 TC
/:cl:

2019-03-24 05:46 UTC, Nickvr628 commented
PUBG copyright strike inbound!

2019-03-24 06:32 UTC, Altoids1 commented on yogstation/code/game/objects/structures/petrified_statue.dm
> +	S.desc = "If it takes forever, I will wait for you..."
This PR is so good

2019-03-24 06:32 UTC, Altoids1 approved these changes

2019-03-24 07:04 UTC, Altoids1 requested changes

2019-03-24 07:04 UTC, Altoids1 commented on yogstation/code/game/objects/structures/petrified_statue.dm
> +yogstation/mob/proc/petrify(statue_timer, pan = FALSE)
Remove this line.

2019-04-08 00:04 UTC, Altoids1 approved these changes

2019-04-08 00:40 UTC, merged