Adds More species to the charged Black extract
yogstation13/Yogstation pull request #4946
Opened 2019-03-25 23:19 UTC by boodaliboo

Before this pull request you could only get the round start races from this crossbreed which felt unfair as making atleast one of these could take around a hour atleast. so i made this pull request to fix it

2019-03-25 23:29 UTC, Jc1469 commented
how about not giving xeno more stuff thanks

2019-03-25 23:57 UTC, boodaliboo commented
> how about not giving xeno more stuff thanks

and why is that? most xeno bio items take most of the round to get the only thing thats really unbalanced is gold slimes

2019-03-26 00:27 UTC, drderp3635 commented
Might I point out to anyone who doesn't know how godawful inefficient charged black slimes are. You use 10 yellow extracts to an adult black, then you have to put 10 plasma in it. Then you get one random race roll, some of which are just awful. The actual amount of work you would have to put forward to actually get a specific race, is far more than what it is worth.

2019-03-26 08:46 UTC, ThatLing requested changes

2019-03-26 08:46 UTC, ThatLing commented on code/modules/mob/living/carbon/human/species_types/snail.dm
> +	changesource_flags = MIRROR_BADMIN | WABBAJACK | MIRROR_MAGIC | MIRROR_PRIDE | RACE_SWAP | SLIME_EXTRACT
No

2019-03-26 20:43 UTC, boodaliboo commented on code/modules/mob/living/carbon/human/species_types/snail.dm
> +	changesource_flags = MIRROR_BADMIN | WABBAJACK | MIRROR_MAGIC | MIRROR_PRIDE | RACE_SWAP | SLIME_EXTRACT
how do i change it to that?

2019-03-26 20:45 UTC, boodaliboo commented on code/modules/mob/living/carbon/human/species_types/snail.dm
> +	changesource_flags = MIRROR_BADMIN | WABBAJACK | MIRROR_MAGIC | MIRROR_PRIDE | RACE_SWAP | SLIME_EXTRACT
i think i did it

2019-03-28 00:39 UTC, monster860 requested changes

2019-03-28 00:39 UTC, monster860 commented on code/modules/mob/living/carbon/human/species_types/snail.dm
> +	changesource_flags = MIRROR_BADMIN | WABBAJACK | MIRROR_MAGIC | MIRROR_PRIDE | RACE_SWAP
AAAA YOU ADDED A SPACE AT THE END

2019-04-02 18:57 UTC, merged