Better handling of accidental IC in OOC
yogstation13/Yogstation pull request #4979
Opened 2019-03-28 23:46 UTC by wilfredrickson

### Intent of your Pull Request

Created a Regular Expression to handle accidental In Character chat in Out Of Character chat, while fixing false positives that existed in the previous implementation.

#### Changelog

:cl:  
bugfix: better accidental IC in OOC handling
/:cl:

2019-03-29 01:26 UTC, Altoids1 commented
![image](https://user-images.githubusercontent.com/29939414/55202982-b465e900-5197-11e9-9abc-98432db1f8da.png)

2019-03-29 02:03 UTC, Altoids1 requested changes

2019-03-29 02:03 UTC, Altoids1 commented on code/modules/client/verbs/ooc.dm
> +	if(ickock.Find(msg))
```suggestion
	if(length(msg) > 4 && ickock.Find(msg))
```
Just to make this a tad bit more robust against emoticon usage.

2019-03-29 02:03 UTC, Altoids1 commented on code/modules/client/verbs/ooc.dm
> -
Remove this whitespace change.

2019-03-29 02:03 UTC, Altoids1 commented on code/modules/client/verbs/ooc.dm
> -
Remove this whitespace change.

2019-03-29 03:22 UTC, wilfredrickson commented
Hopefully it's all in working order now, sorry for the fuss

2019-03-31 01:40 UTC, Altoids1 approved these changes

2019-03-31 01:53 UTC, merged