DB support
yogstation13/Yogstation pull request #498
Opened 2018-04-25 17:21 UTC by nichlas0010

honk

2018-04-25 17:21 UTC, Amelia0010 commented
oh and this is what I worked from https://github.com/yogstation13/yogstation/commit/dca81c68b10d94ed4d254e2d99ed9f7ff9f66b7e#diff-6f61adba58272a6ded4c7387effcac4e

2018-04-25 18:00 UTC, ThatLing commented on yogstation/code/modules/admin/admin_ranks.dm
> +			ranksFile << "##############################################################################################################\n# ADMIN RANK DEFINES
Use WRITE_FILE

2018-04-25 18:00 UTC, ThatLing commented on yogstation/code/modules/admin/admin_ranks.dm
> +			adminsFile << "###############################################################################################\n# Basically, ckey goes first. Rank goes after the '='
Use WRITE_FILE

2018-04-27 19:23 UTC, ThatLing requested changes

2018-04-27 19:23 UTC, ThatLing commented on code/modules/admin/DB_ban/functions.dm
> +		var/datum/DBQuery/query_check_adminban_amt = SSdbcore.NewQuery("SELECT count(id) AS num FROM [format_table_name("ban")] WHERE (a_ckey = '[a_ckey]') AND (bantype = 'ADMIN_PERMABAN'  OR (bantype = 'A
delete this change

2018-04-27 19:23 UTC, ThatLing commented on code/modules/admin/IsBanned.dm
> +		var/datum/DBQuery/query_ban_check = SSdbcore.NewQuery("SELECT ckey, a_ckey, reason, expiration_time, duration, bantime, bantype, id, round_id FROM [format_table_name("ban")] WHERE (ckey = '[ckeytex
delete this change

2018-04-27 19:23 UTC, ThatLing commented on code/modules/admin/IsBanned.dm
> +		/*var/ipquery = "" YOGS - DB support //yogs start - DB support
delete this change

2018-04-27 19:23 UTC, ThatLing commented on code/modules/admin/banjob.dm
> +		var/datum/DBQuery/query_jobban_check_ban = SSdbcore.NewQuery("SELECT reason FROM [format_table_name("ban")] WHERE ckey = '[sanitizeSQL(M.ckey)]' AND (bantype = 'JOB_PERMABAN'  OR (bantype = 'JOB_TE
delete this change

2018-04-27 19:23 UTC, ThatLing commented on code/modules/admin/banjob.dm
> +		var/datum/DBQuery/query_jobban_build_cache = SSdbcore.NewQuery("SELECT job, reason FROM [format_table_name("ban")] WHERE ckey = '[sanitizeSQL(C.ckey)]' AND (bantype = 'JOB_PERMABAN'  OR (bantype =
delete this change

2018-04-27 19:23 UTC, ThatLing commented on code/modules/admin/IsBanned.dm
> +		/*var/ipquery = "" YOGS - DB support //yogs start - DB support
these changes even

2018-04-27 19:43 UTC, ThatLing approved these changes

2018-04-27 19:43 UTC, merged