Fix liver abuse
yogstation13/Yogstation pull request #5042
Opened 2019-04-05 17:48 UTC by monster860

:cl: monster860
tweak: If you have corazone reagents will now process normally
/:cl:

2019-04-05 17:51 UTC, nichlas0010 commented
lol

2019-04-05 18:56 UTC, Altoids1 requested changes

2019-04-05 18:56 UTC, Altoids1 commented on code/modules/mob/living/carbon/life.dm
> +	reagents.metabolize(src, can_overdose=has_trait(TRAIT_STABLEHEART), liverless = !has_trait(TRAIT_STABLEHEART)) // make it so reagents process normally if you have corazone
Modularize me, daddy

2019-04-05 22:38 UTC, Ratvar commented
why not try merging this on teegee first

2019-04-06 04:55 UTC, Rayisken commented
Is this a straight negative to corazone for preventing liver failure? 

It is used in higher tier cryo setups and that should be taken into consideration as well.

2019-04-06 15:36 UTC, monster860 commented
not on tg because tg can suck a big fat dick

2019-04-08 00:21 UTC, Altoids1 approved these changes

2019-04-08 00:21 UTC, merged