[WIP] removes auto-blue alert, removes antag message
yogstation13/Yogstation pull request #5087
Opened 2019-04-08 21:26 UTC by nichlas0010

### Intent of your Pull Request

I still need to add an NT logo and the Admiral's stamp. 

#### Changelog

:cl:  
tweak: the roundstart report no longer specifies that antags exist or whether they exist at all, and it now doesn't escalate to blue alert either.
/:cl:

2019-04-08 21:26 UTC, nichlas0010 commented
![image](https://user-images.githubusercontent.com/20558591/55757999-c5471200-5a55-11e9-9174-6f1e3015bd7c.png)
 example so far

2019-04-08 21:27 UTC, BlueMemesauce commented
hello i made an account  i think this idea is very good

2019-04-08 21:51 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
now add a chance for extended

2019-04-08 23:32 UTC, fluffe9911 commented
Yeah this would only really work if there was atleast a small chance of a extended round (although it no longer being auto blue is nice)

2019-04-09 08:43 UTC, nichlas0010 commented
The whole point is turning off auto-blue, but if they get told there's antags they can just turn it up to blue. Turning it up to blue because "extended isn't in rotation" is what we in the adminning business would call metagaming 😎

2019-04-11 17:23 UTC, AsV9 commented
I approve removing automatic blue alert.

2019-04-11 19:01 UTC, nichlas0010 commented
stamps are bad

2019-04-11 21:02 UTC, FatalEYES commented
nice

2019-04-12 19:30 UTC, Altoids1 requested changes

2019-04-12 19:30 UTC, Altoids1 commented on yogstation/code/game/gamemodes/game_mode.dm
> +/datum/game_mode/send_intercept()
Can you put a note in the /TG/ version that this has been mirrored?

2019-04-16 04:25 UTC, closed without merging