[moderator]Update vision.dm
yogstation13/Yogstation pull request #5103
Opened 2019-04-11 15:53 UTC by aaqe

### Intent of your Pull Request

Makes eyeball removal impossible without future changes to virology or admin intervention.

Staff consensus against having a virus removing the eyeball organ from players en masse.

#### Changelog

:cl:  Makes eyeball organ removal from Hyphema require admin intervention.

2019-04-12 19:12 UTC, Altoids1 requested changes
This is not how you should be going about removing the eyeball removal aspect of this symptom.

If you actually want the eyeball stuff removed, you should just comment it out of this.
If you want to allow for possible adminbus, just comment out this bit:
```dm
	if(A.properties["resistance"] >= 12) //goodbye eyes
		remove_eyes = TRUE
```
and then have admins varedit ``remove_eyes`` to ``TRUE`` when they want to bus this in.

Also, this shit ain't modularized. Check our README about it:
https://github.com/yogstation13/Yogstation-TG/blob/master/yogstation/README.md

2019-04-12 20:19 UTC, aaqe commented
> This is not how you should be going about removing the eyeball removal aspect of this symptom.
> 
> If you actually want the eyeball stuff removed, you should just comment it out of this.
> If you want to allow for possible adminbus, just comment out this bit:
> 
> ```dm
> 	if(A.properties["resistance"] >= 12) //goodbye eyes
> 		remove_eyes = TRUE
> ```
> 
> and then have admins varedit `remove_eyes` to `TRUE` when they want to bus this in.
> 
> Also, this shit ain't modularized. Check our README about it:
> https://github.com/yogstation13/Yogstation-TG/blob/master/yogstation/README.md

DONE I THINK, I WILL MAKE THE RESISTANCE CHANGE PART OF THE SYNDICATE VIRUS ITEM IF IT EVER GETS FINISHED

2019-04-14 20:21 UTC, Altoids1 approved these changes

2019-04-16 07:40 UTC, AdamElTablawy commented
rip the only fun part of sentient disease

2019-05-15 07:33 UTC, closed without merging