[XENOARCH SPOILERS] [WIP] Gigadrill
yogstation13/Yogstation pull request #5233
Opened 2019-04-24 21:55 UTC by alexkar598

# WARNING: SPOILERS FOR XENOARCH
___
# DO NOT SCROLL DOWN IF YOU WANT TO KEEP THE FUN OF DISCOVERING XENOARCH LOOT
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

Readds the giga drill back from 2013,improved by /vg/. It's a vehicle that you can ride to mine,it is faster than the ripley due to the fact it will be hard-ish to get via xenoarch.Currently only admin spawnnable,please do not add a way to get it other than xenoarch.

No Change log due to this being unobtainable.

2019-04-24 21:56 UTC, alexkar598 commented on yogstation/code/modules/xenoarch/loot/gigadrill.dm
> +	D.set_vehicle_dir_layer(SOUTH, OBJ_LAYER)
Gotta change this to
```suggestion
	D.set_vehicle_dir_layer(SOUTH, ABOVE_MOB_LAYER)
```

2019-04-25 05:35 UTC, Time-Green commented on yogstation/code/modules/xenoarch/loot/gigadrill.dm
> +	OB = null
Assuming the orebox is an in internal thing, QDEL_NULL(OB) is preferable

2019-04-29 19:08 UTC, Altoids1 commented on yogstation/code/game/gamemodes/traitor/double_agents.dm
> -			hijack_objective.owner = owner.
What the hell...?

2019-04-29 19:10 UTC, Altoids1 requested changes

2019-04-29 19:10 UTC, Altoids1 commented on yogstation/code/modules/xenoarch/loot/gigadrill.dm
> +	desc = "This looks like any normal drill,except not,it is a giga drill.Drag and drop an ore box on it to load the box on and drag and drop to a adjacant turf to unlload the box."
put some spaces after your commas & periods, you cretin.

2019-05-07 09:35 UTC, Altoids1 approved these changes

2019-05-07 10:10 UTC, alexkar598 commented
Wrong button I hate my life and all form of dinosaurs.

2019-05-08 11:08 UTC, merged