removes the ambience from the supermatter
yogstation13/Yogstation pull request #562
Opened 2018-04-28 21:55 UTC by ShadowDeath6

not a fan of having tinnitus, thanks

:cl: ShadowDeath6
sounddel: Removed ambient ringing from supermatter shard.
/:cl:

2018-04-28 22:30 UTC, GrayRachnid requested changes
I feel retarded, just comment it out.

2018-04-28 22:57 UTC, GrayRachnid approved these changes
inb4 nich comes in and says no you retard remove it or modularize it but i don't deserve to have maintainer for this shit so i'm spewing crap outta my ass

2018-04-28 22:59 UTC, ShadowDeath6 commented
:pensive:

2018-04-29 08:54 UTC, ThatLing submitted a review, later dismissed

2018-04-29 08:54 UTC, ThatLing commented on code/datums/looping_sounds/machinery_sounds.dm
> +/*/datum/looping_sound/supermatter
dont comment this out

2018-04-29 08:54 UTC, ThatLing commented on code/modules/power/supermatter/supermatter.dm
> +	//var/datum/looping_sound/supermatter/soundloop
Please mark your changes as explained ![here](https://github.com/yogstation13/tg-rebase/blob/master/yogstation/README.md)

2018-04-29 08:54 UTC, ThatLing commented on code/modules/power/supermatter/supermatter.dm
> +	//soundloop = new(list(src), TRUE)
Please mark your changes as explained ![here](https://github.com/yogstation13/tg-rebase/blob/master/yogstation/README.md)

2018-04-29 08:54 UTC, ThatLing commented on code/modules/power/supermatter/supermatter.dm
> +	//QDEL_NULL(soundloop)
Please mark your changes as explained ![here](https://github.com/yogstation13/tg-rebase/blob/master/yogstation/README.md)

2018-04-29 08:54 UTC, ThatLing commented on code/modules/power/supermatter/supermatter.dm
> +		//soundloop.volume = min(40, (round(power/100)/50)+1) // 5 +1 volume per 20 power. 2500 power is max
Please mark your changes as explained ![here](https://github.com/yogstation13/tg-rebase/blob/master/yogstation/README.md)

2018-04-30 06:34 UTC, Amelia0010 approved these changes

2018-04-30 16:04 UTC, ThatLing approved these changes

2018-04-30 16:05 UTC, merged