replaces bloodcrawl spell with ctrl+click
yogstation13/Yogstation pull request #570
Opened 2018-04-29 04:02 UTC by ShadowDeath6

:cl: ShadowDeath6
rscadd: Replaced the bloodcrawl spell for slaughter demons with the ability to ctrl+click blood.
/:cl:

2018-04-29 09:05 UTC, ThatLing requested changes

2018-04-29 09:05 UTC, ThatLing commented on code/modules/antagonists/slaughter/slaughter.dm
> +/*/mob/living/simple_animal/slaughter/Initialize()
Don't comment this, just override it in a different file

2018-04-29 09:05 UTC, ThatLing commented on code/modules/antagonists/slaughter/slaughter.dm
> +	name = "Slaughter Demon"
Why?

2018-04-29 09:05 UTC, ThatLing commented on code/modules/antagonists/slaughter/slaughter.dm
> +/mob/living/simple_animal/slaughter/bloodpool_sink(obj/effect/decal/cleanable/B)
Put this in a /yogstation file

2018-04-29 09:05 UTC, ThatLing commented on code/modules/antagonists/slaughter/slaughter.dm
> +	boost = world.time + 20
Mark your changes ![like this](https://github.com/yogstation13/tg-rebase/blob/master/yogstation/README.md)

2018-04-29 09:05 UTC, ThatLing commented on code/modules/antagonists/slaughter/slaughter.dm
> +		to_chat(user, "<span class='warning'>...and you don't feel any different.</span>")
Mark your changes ![like this](https://github.com/yogstation13/tg-rebase/blob/master/yogstation/README.md)

2018-04-29 09:05 UTC, ThatLing commented on code/modules/mob/living/bloodcrawl.dm
> +	var/turf/bloodloc = get_turf(B.loc)
Just override this proc in a /yogstation file at this point

2018-04-29 09:05 UTC, ThatLing commented on code/modules/mob/living/living.dm
> +	else if(bloodcrawl == BLOODCRAWL_EAT) //so demons can ctrl + click tiles to teleport to them
Mark your changes ![like this](https://github.com/yogstation13/tg-rebase/blob/master/yogstation/README.md)

2018-04-29 09:05 UTC, ThatLing commented on code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
> +	bloodcrawl = BLOODCRAWL_EAT
Mark your changes ![like this](https://github.com/yogstation13/tg-rebase/blob/master/yogstation/README.md)

2018-04-29 09:05 UTC, ThatLing commented on code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
> +	/*var/obj/effect/proc_holder/spell/bloodcrawl/bloodspell = new
Mark your changes ![like this](https://github.com/yogstation13/tg-rebase/blob/master/yogstation/README.md)

2018-04-29 09:05 UTC, ThatLing commented on yogstation/code/modules/spells/spell_types/bloodcrawl.dm
> +			if(user.phaseout(target))
Remove the commented code

2018-05-01 04:32 UTC, ShadowDeath6 commented
closing this until I'm not busy

2018-05-01 04:32 UTC, closed without merging