Adds Janitor Chem Sprayer upgrade to Janitor Cyborg module
yogstation13/Yogstation pull request #6289
Opened 2019-07-09 18:34 UTC by ynot01

locked behind the advanced robotics and advanced janitor nodes
![08uycx6](https://user-images.githubusercontent.com/28408322/60913803-2bf6ea00-a256-11e9-9af8-d9258021038b.png)
![iVIEQst](https://user-images.githubusercontent.com/28408322/60913913-6791b400-a256-11e9-90ab-b0bd48ffccf0.png)
![MQrZRFm](https://user-images.githubusercontent.com/28408322/60913840-4335d780-a256-11e9-800a-6c5350d76ec8.png)
![C82hxz8](https://user-images.githubusercontent.com/28408322/60913864-4df06c80-a256-11e9-822c-212e2e143379.gif)

:cl:  
rscadd: Added Janitor Chem Sprayer upgrade to Janitor Cyborg module
/:cl:

2019-07-09 18:40 UTC, TheGamerdk commented
omg such buff

2019-07-09 21:57 UTC, HomocidlePancakes commented
Why tho

2019-07-10 04:51 UTC, ynot01 commented
to improve the life of a poor cyborg whose sole purpose is to clean shit up after others

2019-07-10 10:51 UTC, HomocidlePancakes commented
But he is already better at cleaning then anyone else. Why?

2019-07-10 18:45 UTC, ynot01 commented
because it makes it easier to clean up at the cost of some med-tier mats and 23,000 research points

2019-07-10 18:46 UTC, ynot01 commented
because it makes it easier to clean up at the cost of some med-tier mats and 23,000 research points

the only meta borgs right now are engi sec and med

2019-07-11 08:38 UTC, HomocidlePancakes commented
>But he is already better at cleaning then anyone else. Why?

>because it makes it easier to clean up

Well, you are just reciting the information that is already the question. I asked you “why are you doing this?”, not “what are you doing?”

>at the cost of some med-tier mats and 23,000 research points

1)I did not ask you for research requirments
2)How are it’s research requirments in any way justified this? You just recited them, without an actual explanation as to why you are making the change.

Also I am not to keen on making things, that were specifically made sparse AF, easily obtainable, especially with such a flimsy reasoning. Kinda kills it tbh. Come up with your own memes instead.

2019-07-11 09:52 UTC, TheGamerdk commented
I like this, merge when?

2019-07-11 10:04 UTC, ynot01 commented
i legit dont know how to tell you any more reasoning than "it makes it easier to clean"

as for the "sparse item made easily obtainable", it's a cyborg, not a carbon, which justifies powerful items specifically for the module. consider secborg having near limitless disabler and stun baton, or medbot being able to constantly synthesize a variety of incredibly useful chemicals into a hypospray, as well as having an entire surgical toolset in its back pocket, or engineering cyborg having access to an RCD that is dependent on charge instead of actual materials (which can be made infinite using yellow cell)

2019-07-11 10:05 UTC, HomocidlePancakes commented
I don't. ERT toys are for ERT, not borgs.

2019-07-11 11:10 UTC, HomocidlePancakes commented
>i legit dont know how to tell you any more reasoning than "it makes it easier to clean"

If you can't back up your idea with arguments, then it's invalid. Thats all I can say.

>as for the "sparse item made easily obtainable", it's a cyborg, not a carbon

You see, cyborgs will be present in pretty much every shift. ERT on the other hand, especially the janitorial one appears once in a blue moon. It being a avaiable only to borgs doesn't change anything.

> consider secborg having near limitless disabler and stun baton

Yeah, and it's retarded. Saying "This is clearly bad, but someone else is doing it, thus I can do" is just child level arguments. Remove secborg instead.

>or medbot being able to constantly synthesize a variety of incredibly useful chemicals into a hypospray

Sleepers can do this too, and everyone is fine with it. Makes sense that it should be on par with atleast roundstart medbay equipment. Not to mention that medborg, unlike secborg, can't 100% autonomously perform it's duties.

>as well as having an entire surgical toolset in its back pocket

Why shouldn't a medborg be able to perform surgery? It's kinda the whole purpose of it.

>or engineering cyborg having access to an RCD that is dependent on charge instead of actual materials (which can be made infinite using yellow cell)

List of things that the engineering cyborg can do:
Build walls
Lay pipes
Lay cable
Fix essential machinery (APCs, alarms, ETC)

List of thigs the engiborg can't do:
Build/fix specialized machinery
Set up the engine
Build reinforced walls

There are alot of drawbacks to the "Overpowered" ability of being able to build an infinite amount of walls, so don't try to use it as an argument.

Same can be said about all *usefull* cyborgs by the way. They perform general duties better then humans, but can't perform specialized tasks. The only exception to this rule is the secborg which is just yet another reason as to why it should be removed.

Also you've wrote just one line addressing the issues with your PR(which didn't have any arguments btw) and wrote an entire paragraph of mostly unrelated stuff. Do not try to derail the argument by referencing that at first glance looks like it the same, but after 30 second of thought it can easily be understood that it's outside the topic.

2019-07-11 18:00 UTC, alexkar598 requested changes

2019-07-11 18:00 UTC, alexkar598 commented on yogstation/code/modules/research/designs/mechfabricator_designs.dm
> +/datum/design/borg_upgrade_restart
Copypasta failure

2019-07-11 18:00 UTC, alexkar598 commented on yogstation/code/modules/research/techweb/all_nodes.dm
> +	description = "We really should fire those janitors."
```suggestion
	description = "We really should kill and borg those janitors."
```

2019-07-11 19:15 UTC, alexkar598 requested changes

2019-07-11 19:15 UTC, alexkar598 commented on yogstation/code/game/objects/items/robot/robot_upgrades.dm
> +		var/obj/item/reagent_containers/spray/chemsprayer/janitor/M = new (R.module)
```suggestion
		var/obj/item/reagent_containers/spray/cyborg_drying/M = new (R.module)
```

2019-07-12 01:15 UTC, alexkar598 commented on yogstation/code/game/objects/items/robot/robot_upgrades.dm
> +		var/obj/item/reagent_containers/spray/chemsprayer/janitor/M = new (R.module)
wait,this isn't replacing the drying spray,just get rid of those lines after the remove module

2019-07-12 06:48 UTC, TacticalSpacePilot commented
Honestly if this were added I would rather have the spray be on janiborg roundstart versus an upgrade which roboticists rarely make.

2019-07-19 19:08 UTC, alexkar598 commented
This PR has been denied due to negative response

2019-07-19 19:08 UTC, closed without merging

2019-07-19 19:10 UTC, Nickvr628 commented
What a shame