[admin] Adds logging to to_chat()
yogstation13/Yogstation pull request #6346
Opened 2019-07-14 17:17 UTC by alexkar598

Made with ❤️ for Qe

Screenshot of what it looks like is posted in IA admin chat for those who care since i dont want to risk posting stuff i dont wanna lol

tochat.log is unreadable without filtering

this includes viewing the chat for a single mob/client using PP

2019-07-15 12:59 UTC, nichlas0010 commented
jesus christ no, the fucking logfiles will be obscenely large

2019-07-15 13:17 UTC, Amelia0010 requested changes

2019-07-15 13:17 UTC, nichlas0010 commented on code/modules/goonchat/browserOutput.dm
> +			C.mob.log_message(message, LOG_TOCHAT)
add an argument to the to_chat proc, to choose whether to log the message or not, defaulting to not, please.

Logging to_chat should be opt-in on a message to message basis.

2019-07-15 14:10 UTC, nichlas0010 commented on code/modules/goonchat/browserOutput.dm
> +			C.mob.log_message(message, LOG_TOCHAT)
I just had a think;

Consider making the extra argument be the "name" of the log, as in:

```
/proc/to_chat(target, message, handle_whitespace=TRUE, logname)

    [...]

   if(logname)
         C.mob.log_message(logname + ": " + message, LOG_TOCHAT)
```

That way we can add `flavourtext` as an argument to to_chat, and we can then search for `flavourtext` in the log if we need to access it

2019-07-17 15:17 UTC, alexkar598 commented
The manually setting a flag to log it,defaulting to not is pointless as you can just add a logging thing there so imma close this

2019-07-17 15:17 UTC, closed without merging

2019-07-17 15:54 UTC, nichlas0010 commented
:(