Allows nuclear operatives to buy loud headsets
yogstation13/Yogstation pull request #6357
Opened 2019-07-15 18:28 UTC by yacabo

Loud headsets can now be bought for 1 TC by nuclear operatives, which is a syndicate headset with a volume setting. Communication has been an issue with nukies and while this won't fix the issue, it will help operatives differentiate between crew comms and operative comms.

2019-07-15 18:31 UTC, HomocidlePancakes commented
1)
>Communication has been an issue with nukies and while this won't fix the issue

Then whats the fucking point of this PR?

2)
>it will help operatives differentiate between crew comms and operative comms.

What stopped them from telling them appart prior? I know! Nothing.

This will lead to even more comms polution and I do not want this.

2019-07-15 18:39 UTC, yacabo commented
> Communication has been an issue with nukies and while this won't fix the issue
> 
> Then whats the fucking point of this PR?
> 
> 
> 
> 
> it will help operatives differentiate between crew comms and operative comms.
> 
> What stopped them from telling them appart prior? I know! Nothing.
> This will lead to even more comms polution and I do not want this.

Maybe I wasn't specific enough, the point is that it helps with the issue. When you're a nukie you need to take a little time as you can looking at comms, and trying to find a tiny text of vitally important information from one of your mates is quite a bit difficult when it is tiny compared to all the heads screaming in comms. I meant that there are other issues to the lack of communication on the side of nukies, but this makes it easier for them to spot syndicate comms.

2019-07-15 18:45 UTC, HomocidlePancakes commented
I personally never struggled with reading chat and I don't undertand how anyone else who has been playing this game for longer then a week would. This just polutes chat 4nr. If you are concerned about that small percent of people who actually have problems with this, then add a headset that makes all syndicomms show up in larger text instead of making you louder.

2019-07-15 20:15 UTC, Trustback commented
You see cidle, this 'small' percent of people are the Antags, so why not make it easier instead of hating all good change. Because from where you're standing, you absolutely hate QoL PRs for everyone.

2019-07-15 20:23 UTC, HomocidlePancakes commented
1)Still waiting on you listing those ethereal xeno nerfs you were going to do alongside the one you already made
2)Someone shitposting in chat is not QoL
3)I proposed a change that bypasses what I don’t like about this PR. Gonna recite it now

>add a headset that makes all syndicomms show up in larger text instead of making you louder.
 
If I really did hate QoL like you’ve been claiming, then I would’ve just continue shitting on this PR withoout providing any ideas, but thats clearly not the case innit?

2019-07-15 20:35 UTC, Alek2ander commented
This seems like something that should just be the default. Do you really expect people to spend TC on a barely useful nonmeme item?

Also instead of making all operatives loud just make operative radios ignore the commanding style from station radios because 
### HUGECHAT 
is obnoxious

2019-07-19 14:43 UTC, Firewolf34 commented
I think this is a great idea but you didn't go far enough with it. 

I agree with how Alek2ander thinks nobody will purchase the item. 

Due to that I think you should make the *default starting* Syndie Nuke Team headsets be Loud *by default*. 

I know some people think Loud chat is annoying, but they're thinking in terms of Common channel. If the SYNDIE COMMS channel is loud, only the nuke team will be able to hear it, there is no "noise pollution" there. And @yacabo is *one-hundred percent right* that it's damn near impossible to pay attention to comms when you're in a gun fight.

Nuke teams need loud chat. This item is a good idea, but it should be default. That's my opinion.

2019-07-20 17:22 UTC, Amelia0010 requested changes
why don't we just make their headsets loud by default :)

2019-07-23 06:52 UTC, MegaEmpirical commented
I think there is a bwtter way to do this an fits something I've wanted for a while:

1) Give the commander loud, like a command headset. 

2) Enable disabling either all of station radio or individual channels. I take my headset off until we get to the station because it's fucking too much during planning but then I can't hear syndi channel. When I'm station side I only care about 2 or 3 channels, though I'd settle for just hearing syndi chat.

2019-07-26 03:48 UTC, ynot01 commented
wait wait what if we put it in the pointless-badass category as an actual meme item for the syndies to intimidate the crew

2019-07-30 15:08 UTC, nichlas0010 commented
I'll just make another version of this using some of the ideas here

2019-08-11 19:47 UTC, alexkar598 commented
Stale,contact me or another maint on discord when you are ready to commit the requested changes.

2019-08-11 19:47 UTC, closed without merging