Adds sec magboots
yogstation13/Yogstation pull request #6359
Opened 2019-07-15 21:05 UTC by Ktlwjec

our lovely prebase security magboots

:cl:  
rscadd: Combat magboots can be found in the security suit storages.
/:cl:

2019-07-15 23:06 UTC, ghost requested changes

2019-07-15 23:06 UTC, Trustback commented on code/game/machinery/suit_storage_unit.dm
> +	storage_type = /obj/item/clothing/shoes/magboots/security
Where's the glorious //yogs?

2019-07-15 23:16 UTC, Kmc2000 commented
This PR is the greatest thing I have ever been fortunate enough to bear witness to. The simple idea of security magboots is sublime, but simultaneously removing their oxygen tank from the suit storage presents truly profound implications for the meta, and balance of the game as a whole. Innovation like this surpasses the mere substrate of ss13's old, tired code, what's more --- /tg/ code. No my friends, this surpasses everything before seen and sublimates /tg/'s codebase into a well oiled machine with each beautifully individual element balanced out with precision the likes of which could have never even been conceived by mortal minds, and yet somehow, the yogstation coder "ktlwjec" managed.

Overall, this PR gets a 6/10 from me

2019-07-16 02:39 UTC, alexkar598 commented on code/game/machinery/suit_storage_unit.dm
> +	storage_type = /obj/item/clothing/shoes/magboots/security
Modularisation is no longer enforced.

2019-07-16 02:40 UTC, alexkar598 approved these changes

2019-07-16 09:33 UTC, HomocidlePancakes commented
Port prebase RnD when?

2019-07-19 12:30 UTC, merged