hollow knight plush
yogstation13/Yogstation pull request #6373
Opened 2019-07-17 00:09 UTC by ynot01

:cl:  
rscadd: Added a hollow plushie
/:cl:

2019-07-17 00:10 UTC, Amelia0010 requested changes

2019-07-17 00:10 UTC, nichlas0010 commented on yogstation/code/game/objects/items/plushes.dm
> +	desc = "Ident is fucking stupid"
🤔

2019-07-17 00:12 UTC, ynot01 commented on yogstation/code/game/objects/items/plushes.dm
> +	desc = "Ident is fucking stupid"
![cwu3KPb](https://user-images.githubusercontent.com/28408322/61338124-0fceec00-a806-11e9-8471-e24f12378ece.png)

2019-07-17 00:13 UTC, Ihonkification commented
wow great pr. as head of hollow knight here at yogstation incorporated i approve of this pr.

2019-07-17 00:23 UTC, Ihonkification commented
after a recent commit i recede all support for this pr. i rate this pr to have sucked massive chonga

2019-07-17 00:27 UTC, ynot01 commented
why don't you want any interaction at all you dong

2019-07-17 00:29 UTC, Ihonkification commented
thank you travis at least someone is cultured in quality hollow knight prs

2019-07-17 00:48 UTC, ynot01 commented
you think i compiled this smh

2019-07-21 12:58 UTC, alexkar598 requested changes

2019-07-21 12:58 UTC, alexkar598 commented on yogstation/code/game/objects/items/plushes.dm
> +	component = /datum/component/squeak/lizardplushie
```suggestion
	squeak_override = list('sound/weapons/slash.ogg' = 1)
```

2019-07-22 23:00 UTC, alexkar598 commented
![img](https://i.imgur.com/6WZkq88.png)

2019-07-22 23:00 UTC, closed without merging