Streamlines the Tricorder's code without breaking everthing
yogstation13/Yogstation pull request #6564
Opened 2019-08-13 00:26 UTC by yacabo

Improves the Tricorder's code so that it is not 70% copy paste. Functionally the only difference is that the medical side of it has a different UI seen here:

![image](https://user-images.githubusercontent.com/5571930/62906993-36b60a80-bd3f-11e9-89f3-c7759e599fca.png)

The code however has been modified so that the gas analyzer now has a part of its code turned into a proc that can be used elsewhere, and as you can imagine, is now used in the tricorder code.

Also it can no longer tell how long someone has been dead.

(This is the second PR because GitHub broke the first (please don't kill me))
:cl:
tweak: Tricorder code has been redone, functionally it only gives it a unique medical scanner UI
tweak: Part of the gas analyzer can be now used as a proc.
/:cl:

2019-08-13 01:16 UTC, Amelia0010 requested changes

2019-08-13 01:16 UTC, nichlas0010 commented on code/game/objects/items/devices/scanners.dm
> +proc/scangasses(mob/user)
```suggestion
/obj/item/proc/scangasses(mob/user)
```

2019-08-13 01:16 UTC, nichlas0010 commented on yogstation/code/game/objects/items/devices/scanners.dm
>  proc/lesserhealthscan(mob/user, mob/living/M)
```suggestion
/obj/item/proc/lesserhealthscan(mob/user, mob/living/M)
```

2019-08-13 02:28 UTC, yacabo commented on code/game/objects/items/devices/scanners.dm
> +proc/scangasses(mob/user)
Done

2019-08-13 18:53 UTC, Amelia0010 requested changes

2019-08-13 18:53 UTC, nichlas0010 commented on code/game/objects/items/devices/scanners.dm
> +obj/item/proc/scangasses(mob/user)
```suggestion
/obj/item/proc/scangasses(mob/user)
```

2019-08-17 17:12 UTC, Amelia0010 approved these changes

2019-08-17 17:12 UTC, merged