Adds the hat of Doug Dimmadome, owner of the Dimmsdale Dimmadome to the game.
yogstation13/Yogstation pull request #6571
Opened 2019-08-15 01:25 UTC by fluffe9911

🆑
rscadd: For 1 million credits you can now purchase the hat of Doug Dimmadome, owner of the Dimmsdale Dimmadome!
/🆑

2019-08-15 01:59 UTC, Nickvr628 commented
The same Doug Dimmadome, owner of the Dimmsdale Dimmadome where they're showing Crash Nebula?

2019-08-15 02:57 UTC, fluffe9911 commented
On ice?

2019-08-15 02:58 UTC, Nickvr628 commented
Yeah!

2019-08-15 03:06 UTC, fluffe9911 commented
Thats right!

2019-08-15 23:11 UTC, drderp3635 commented
Sprites?

2019-08-15 23:46 UTC, fluffe9911 commented
check icon bot

2019-08-16 06:25 UTC, oklews commented
you should instantly explode if you wear this on the bike, or in any form of car

2019-08-17 17:26 UTC, Amelia0010 requested changes

2019-08-17 17:26 UTC, nichlas0010 commented on yogstation/code/modules/cargo/cargo_packs.dm
> +	cost = 500000
```
rscadd: For 1 million credits you can now purchase the hat of Doug Dimmadome, owner of the Dimmsdale Dimmadome!
```

```
	cost = 500000
```

![image](https://user-images.githubusercontent.com/20558591/63215311-ee269480-c124-11e9-8745-7e8c25dcc101.png)

2019-08-18 15:03 UTC, AsV9 commented
merging this so fluffe will stop bothering me about merging this

2019-08-18 15:03 UTC, merged