Zombie infection chance is lowered by armor
yogstation13/Yogstation pull request #6576
Opened 2019-08-15 22:36 UTC by SomeguyManperson

:cl: The CDC
rscadd: Zombie infections are now blocked a % of the time scaling with melee armor
/:cl:

2019-08-15 22:48 UTC, yacabo commented
This is a really good idea, a shame Travis does not agree

2019-08-15 22:59 UTC, SomeguyManperson commented
Travis is really mad at everything for some reason I don't understand but I did test it and it works

2019-08-16 01:59 UTC, alexkar598 requested changes

2019-08-16 01:59 UTC, alexkar598 commented on code/modules/zombie/items.dm
> +			if(prob(100-H.getarmor(flesh_wound, "melee"))
```suggestion
			if(prob(100-H.getarmor(flesh_wound, "melee")))
```

Should make this PR compilable

2019-08-16 02:05 UTC, alexkar598 submitted a review, later dismissed
God your a shitty coder

2019-08-16 02:05 UTC, alexkar598 commented on code/modules/zombie/items.dm
> +			var/mob/living/human/H = target
```suggestion
			var/mob/living/carbon/human/H = target
```

2019-08-16 13:57 UTC, TheGamerdk commented
Says Alexkar

2019-08-17 05:07 UTC, Nickvr628 commented
I like this

2019-08-19 13:10 UTC, Amelia0010 approved these changes

2019-08-19 13:10 UTC, merged