Chaplain's Holyparasite
yogstation13/Yogstation pull request #6613
Opened 2019-08-23 21:13 UTC by ynot01

### Intent of your Pull Request

fun

It heals at half the rate of the support holoparasite and deals about half the damage of a null rod, in exchange for your null rod. You are supposed to keep the deck of holy tarot cards as they retain the antimagic property of a null rod. The holyparasite also has the holy trait, deflecting magic.

#### Changelog

:cl:  
rscadd: Added a holyparasite to the null rod reskins
/:cl:

2019-08-23 21:15 UTC, Szyszkrzyneczka commented
KOREGA... REQUIEM DA

2019-08-23 21:19 UTC, drderp3635 commented
Stupidly strong. 

👎

2019-08-23 21:27 UTC, ynot01 commented
> Stupidly strong.
> 
> 👎

elaborate

2019-08-23 21:35 UTC, drderp3635 commented
Round start holoparasite is strong because its a fucking roundstart nonantag holoparasite even if its half healing and null rod damage. Chaplain still gets antimagic with the deck, amd the lower damage doesnt even matter because the chaplain can still be hitting the same target with a crowbar or some easily obtainable shit to deal more damage than any other null rod.
The healing is just the cherry on top for how strong this is because you are a one man medbay as someone who is supposed to be a rp role.

If you want to balance this take antimagic off the deck, and completely remove the healing.

2019-08-23 21:43 UTC, ynot01 commented
your bible already heals, so it's not like chaplain is new to healing, antimagic for the holypara is just so that chaplain doesnt get fucked by wizard spells where he'd normally be resistant

originally i didnt have it dealing damage at all, but folks in #coder wanted a balance to sacrificing your powercreep weapon, so i added some damage

once again, if you think any of the following values should be changed to better balance:
2.5 heal of brute/burn/toxin/oxy when in healer mode
100% damage transfer when in healer mode
10 damage to mobs and objects when in combat mode
90% damage transfer when in combat mode

please let me know

2019-08-23 21:44 UTC, drderp3635 commented
Bible healing is garbage, and inflicts brain damage

2019-08-23 21:45 UTC, ynot01 commented
> Bible healing is garbage, and inflicts brain damage

not if you're wearing a helmet

2019-08-23 21:51 UTC, jcatjmeow commented
I say remove the healing, I agree it's op. Even if you think the rate is fine, remember that the holoparasite can drag a chaplain's crit body out of danger and then heal it out of crit.

2019-08-23 21:58 UTC, Codeatmos commented
I don`t think its (that) strong,clock it down to 7 damage,remove anti-magic,BUT OH WAIT,ITS NOT OP
Holoparas are slower then humans
It heals 2.5 per punch,what the fuck are you gonna outheal?
If you die,you get DUSTED
It`s a second hitbox
It will not save your ass,its slower then most antags.
You dont have a null-rod,which means less deconversion of cult items.

2019-08-23 22:01 UTC, Ratvar commented
I propose making host of holyparasite to have antimagic instead of deck. This way you cannot give away tarot to HoS, which you are encouraged to do because tarot is useless for you now.

I encourage you to give chaplain PACIFISM braintrauma and to give holypara full nullrod damage. This way you trade off being able to attack staff like human in exchange for ability to reposition, block non-directly damaging projectiles and attack while critted. And also solve a problem of Holypara dealing 10 damage and you dealing 18 Spear damage at one. Will also make it closer to Jojo.

2019-08-23 22:41 UTC, jcatjmeow commented
"what the fuck are you gonna outheal?"
Oxyloss and bleeding damage from being in crit

2019-08-23 23:00 UTC, Ratvar commented
Jcat, we even talked on discord about removing ability to heal yourself/chaplain, stop pretending

2019-08-24 00:22 UTC, Wuatduhf commented
Ahh, something else Shitcurity can arrest the chaplain over!  /s

I do think that the healing could use the trade-off of the bible's healing of causing some amount of brain damage, even if the bible only does it in the absence of a helmet (see: majority of the time). 

0.5 to 1 brain damage per healing touch?

2019-08-24 01:17 UTC, yacabo commented
Give it a new sprite so that sec can tell the difference between syndicate holo and chap holo

2019-08-24 14:47 UTC, ynot01 commented
should be noted that chaplain's holypara is not skinned as tator holopara, but is skinned as the guardian spirit that wizard spawns and the same one you can get from lavaland

2019-08-24 15:52 UTC, fluffe9911 commented
neat

2019-08-25 19:16 UTC, ShadowDeath6 commented
no healing, chaplain doesn't need a way to heal itself especially when it brings an unstunnable body that can drag people around

Just cut out healing and make it do more damage (like 12 or something)

2019-08-25 20:44 UTC, Ratvar commented
I would like to remind people, again, that ynot didn't prevent holypara from healing itself or chaplain only because he doesn't know how yet.

2019-08-29 20:43 UTC, AdamElTablawy commented
imagine getting a free holoparasite at roundstart

2019-08-30 13:16 UTC, AsV9 requested changes
I think the healing aspect of this is just far too strong in it's current state, and I'd like to see that removed or changed somehow.

2019-09-03 02:37 UTC, Ratvar commented
I would like to remind people, again, that ynot didn't prevent holypara from healing itself or chaplain only because he doesn't know how **yet**.

2019-09-10 00:15 UTC, ShadowDeath6 commented
if(target == master)
return

2019-09-10 13:23 UTC, Ratvar commented
It would be much more helpful if you actually would show where to put that thing instead of showing that you know how and leaving, really. No, ynot's not a great byond coder and you know it, message alone doesn't help at all.

2019-09-10 18:10 UTC, ShadowDeath6 commented on code/modules/mob/living/simple_animal/guardian/types/chaplain.dm
> +		var/mob/living/carbon/C = target
if(C == summoner)
return

2019-09-10 18:11 UTC, ShadowDeath6 commented on code/modules/mob/living/simple_animal/guardian/types/chaplain.dm
> +		if(C == summoner)
get rid of this stuff

2019-09-16 23:38 UTC, ynot01 commented
will put these changes in sometime, been busy with college

2019-09-26 08:10 UTC, AsV9 reviewed
I'm still skeptical, but I suppose we can give this a try and tweak it later as needed.

2019-09-26 08:12 UTC, merged