M-556 Ospray [TESTMERG REQUESTED]
yogstation13/Yogstation pull request #6614
Opened 2019-08-24 01:09 UTC by Readystorm546

This is a PR i felt like doing because why the hell not and it adds a mini gun to the nuke opps radio. 

For the low low price of 36 TC you can get your hands on the one they only mini-gun. 👏 👏 

This thing packs quite the punch shooting 3 5.56mm rounds. The rounds do 45 brute damage making it weaker than the saw but for that weakness it makes up for the fact that this bad boy has 700 rounds in the mag.  

You might be asking how can you hold 700 rounds well ON YOUR BACK OF COURSE!!!!

![q3WDfOG5nU](https://user-images.githubusercontent.com/52303581/63630481-262c4c80-c5e9-11e9-8cc5-c4d401dbad01.gif)

By sacrificing your backpack slot you can put this bad boy on your back then equip it as if you were going to defib some one with only one defibrillator.

Watch out though this thing will slow you down when in your hands applying a 1.5 * movement speed penalty. You also need two hands to fire it so dont have anything else in your other hand or you might get that scary red text. 😲 

Though you may be slow you pack quite the punch as killing things that are unarmored and defenseless has never been easier!!!!!!!!!

![1y1ESowshQ](https://user-images.githubusercontent.com/52303581/63630502-5b389f00-c5e9-11e9-8aa4-7810a125b215.gif)

Whats that you dont like killing unarmored and defenseless people well then what about windows and doors!!!! This thing will tear of the the windows and door like your momma never could.

![jsuJcn9jLh](https://user-images.githubusercontent.com/52303581/63630546-da2dd780-c5e9-11e9-8acd-87562ab022c3.gif)

![8aAeYKaRw1](https://user-images.githubusercontent.com/52303581/63630549-ddc15e80-c5e9-11e9-9485-2d9b66fcf540.gif)

Watch out for honk bots....

Now you may be thinking that the 700 round mag seems OP well you would be right but be careful getting too trigger happy will make your gun overheat. Once it over heats it cant fire until it cools down.

![u7UbV0Rdgi](https://user-images.githubusercontent.com/52303581/63630574-2ed15280-c5ea-11e9-94b4-bd4ee97b4b46.gif)

Thats all i have for you today. Plese enjoy the fact that casings dont drop to cause lag less fun wooh.

:cl:  
Adds this big new and fun gun that shoots alot
/:cl:

2019-08-24 01:14 UTC, Nickvr628 commented
19 TC or no deal

2019-08-24 01:44 UTC, Wuatduhf commented
But does it have an ambient revving noise while held?

2019-08-24 01:46 UTC, Nickvr628 commented
To port over my suggestion from discord to here, the burst count should be much higher, I say 10. It is supposed to be an uncontrollable hail of bullets, not a bursting rifle.

2019-08-24 02:09 UTC, Readystorm546 commented
With my most recent commit i have upped the bullet count to 4 and made the spread really high,
The cap is 36 so you can shoot about 9 times before it over heats. Then you have to wait.

![V8vXt4Anuc](https://user-images.githubusercontent.com/52303581/63631233-aacf9880-c5f2-11e9-8942-7ad3ba30e316.gif)

2019-08-24 17:25 UTC, drderp3635 commented
Emag to disable heat lock, which lets you fire more, but can make it explode if you fire while overheated

2019-08-24 20:44 UTC, boodaliboo commented
ADD TO NUKE OPS FOR 50 TC

2019-08-24 20:51 UTC, Firewolf34 commented
Excellent PR quality

2019-08-24 20:57 UTC, Readystorm546 commented
> Emag to disable heat lock, which lets you fire more, but can make it explode if you fire while overheated

hahhahahah no....


> ADD TO NUKE OPS FOR 50 TC

Its on nuke oops for 36 tc at the moment.


> Excellent PR quality

Thanks

2019-08-25 07:01 UTC, TheGamerdk commented
Why not make the heat sensor emaggable?

2019-08-25 07:58 UTC, Alek2ander commented
Does it cost 400000 dollars to fire it for 12 seconds?

2019-08-25 13:39 UTC, Readystorm546 commented
> Why not make the heat sensor emaggable?

People are going to blowup and die from something and the fact of the matter is. That makes unfun rounds when you just die a loose your nukie round.

2019-08-25 13:39 UTC, Readystorm546 commented
> Does it cost 400000 dollars to fire it for 12 seconds?

Yes

2019-08-25 23:37 UTC, Ihonkification commented
will make the inhand and back sprites consistent if this passes testmerge.

also, if this hasn't already been rectified, it's called the M-556 but called the M-762 in the video in the PR.

2019-08-26 11:28 UTC, Amelia0010 requested changes
should be fine after this

2019-08-26 11:28 UTC, nichlas0010 commented on yogstation/code/modules/projectiles/guns/ballistic/minigun.dm
> +	var/armed = 0 //whether the gun is attached, 0 is attached, 1 is the gun is wielded.
```suggestion
	var/armed = FALSE //whether the gun is attached, FALSE is attached, TRUE is the gun is wielded.
```

2019-08-26 11:28 UTC, nichlas0010 commented on yogstation/code/modules/projectiles/guns/ballistic/minigun.dm
> +/obj/item/minigunbackpack/Destroy()
this should probably qdel the gun

2019-08-26 11:28 UTC, nichlas0010 commented on yogstation/code/modules/projectiles/guns/ballistic/minigun.dm
> +	if(src.loc == user)
```suggestion
	if(loc == user)
```

2019-08-26 11:28 UTC, nichlas0010 commented on yogstation/code/modules/projectiles/guns/ballistic/minigun.dm
> +				armed = 1
```suggestion
				armed = TRUE
```

2019-08-26 11:28 UTC, nichlas0010 commented on yogstation/code/modules/projectiles/guns/ballistic/minigun.dm
> +					armed = 0
```suggestion
					armed = FALSE
```

2019-08-26 11:28 UTC, nichlas0010 commented on yogstation/code/modules/projectiles/guns/ballistic/minigun.dm
> +	armed = 0
```suggestion
	armed = FALSE
```

2019-08-26 11:28 UTC, nichlas0010 commented on yogstation/code/modules/projectiles/guns/ballistic/minigun.dm
> +		src.visible_message("<span class='warning'>The [gun.name] snaps back onto the [name]!</span>")
```suggestion
		visible_message("<span class='warning'>The [gun.name] snaps back onto the [name]!</span>")
```

2019-08-26 14:27 UTC, Firewolf34 commented
Is there any way you could make the heat level of the gun visible? I used it yesterday and my principle complaint was not knowing when it would be ready to fire again. It's hard to manage the heat level when you don't know what it is.

Maybe you could examine the gun and it could tell you how hot the gun feels? Or maybe have the icon of the barrel glow red depending on heat level? Something to give some feedback on how close it is to overheating would be nice.

Some more feedback: it's cooling rate did seem relatively acceptable during my test. Personally, I'd like it to just cool down a *tad bit* faster, not a huge amount but a little bit. Considering you are giving up that backpack slot, and are relying on it completely.

But overall, really cool. It won me a nukie round, saving my ass as I went solo against the entire station because my other squadmembers immediately died to space exposure out the gate. Sooooo... it was just me and the Osprey against the world, there.

I like that you can walk faster by stowing it. Nice touch.

2019-08-26 14:30 UTC, Firewolf34 commented
Oh and one last thing. Is there a reason you chose that TC amount specifically? It's exactly 1 TC more than the starting TC amount for the team leader, at least it was in my case (I know sometimes they scale it based on pop). Perhaps that was intentional, perhaps not, but it was tough to convince my team members to give me that 1 TC. lol

2019-08-26 18:12 UTC, Readystorm546 commented
> Oh and one last thing. Is there a reason you chose that TC amount specifically? It's exactly 1 TC more than the starting TC amount for the team leader, at least it was in my case (I know sometimes they scale it based on pop). Perhaps that was intentional, perhaps not, but it was tough to convince my team members to give me that 1 TC. lol
Thats why i did it. To promote sharing and caring.

2019-08-26 18:17 UTC, Readystorm546 commented
> will make the inhand and back sprites consistent if this passes testmerge.
> 
> also, if this hasn't already been rectified, it's called the M-556 but called the M-762 in the video in the PR.

I fixed it thanks for reminding me :)

2019-08-26 23:16 UTC, ynot01 commented
imagine having a functional L6 SAW with 94TC worth of ammo (+the original price of the gun) for 36TC

2019-08-26 23:17 UTC, ynot01 commented
just saw the latest commit, sorry, 60TC worth of ammo

2019-08-27 02:54 UTC, Readystorm546 commented
> just saw the latest commit, sorry, 60TC worth of ammo

Assuming you hit all your shots and you know dont get shot in the process or overheat or get caught due to slowdown and you are willing to lose your backpack slot and give up all your TC +1 on a non war round for one item. Now i understand if its war you can buy more of these sure. Also im about to change the ammo so all of the above shit does not even matter

2019-08-28 11:26 UTC, Ihonkification commented
wheres the changelog

2019-08-28 11:40 UTC, nesisknesis reviewed
you'll be crucified by gun experts for this

2019-08-28 11:40 UTC, Ihonkification commented on code/modules/uplink/uplink_items.dm
> +			This deadly giant weapon has a massive 500-round magazine of devastating 5.46mm ammunition. Slaughter your enemies through \
```suggestion
			This deadly giant weapon has a massive 500-round magazine of devastating 5.46mm caseless ammunition. Slaughter your enemies through \
```

2019-08-28 11:40 UTC, Ihonkification commented on code/modules/uplink/uplink_items.dm
> +			sheer force and dont worry about bullet casings as the minigun shoots the whole bullet which is 65% more bullet per bullet. "
```suggestion
			sheer force."
```

2019-08-29 10:41 UTC, Firewolf34 commented
I just wanted to say that the Portal reference in the description for this is hilarious, and very fitting given the circumstances.

2019-08-30 12:51 UTC, AsV9 commented
why does this have 31 commits

2019-08-30 12:53 UTC, Readystorm546 commented
> why does this have 31 commits

Balance

2019-08-30 14:07 UTC, Firewolf34 commented
> why does this have 31 commits

This is no problem - maintainer just has to `git merge --squash` when it's ready if it's really that much of a concern.

2019-08-30 15:19 UTC, Readystorm546 commented
> > why does this have 31 commits
> 
> This is no problem - maintainer just has to `git merge --squash` when it's ready if it's really that much of a concern.
> 
> Better to have many commits than one really big one
> 
> Also @Readystorm546 : "We mad this gun soadvanced that it fires the whole bullet"

Me and my spelling. I will fix it

2019-09-06 19:47 UTC, alexkar598 commented
This is going to need an actual description of what it does

2019-09-08 14:00 UTC, TheGamerdk commented on yogstation/code/modules/projectiles/guns/ballistic/minigun.dm
> +		to_chat(user, "You need the more ammo to fire the gun!")
You need the more ammo to fire the gun!

2019-09-08 20:44 UTC, closed without merging