Infinity Gauntlet Test Merge
yogstation13/Yogstation pull request #6619
Opened 2019-08-24 11:36 UTC by sam0oneau

Adds a Gauntlet for admins

### Intent of your Pull Request

Explain what the purpose of your PR is.
Mention if you tested your changes. If you changed a map, make sure you used the mapmerge tool.

Mention if your PR is related to an issue.
You can type "Fixes issue #6" and issue 6 will be automatically closed when your pull request is merged. This is much easier for everyone.

Edit the changelog at the bottom for changes that are noticeable by the players. Remove it if this isn't the case.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.
Include [admin] in the title if it's something admin related.
Include [s] in the title if you don't want it to be announced on discord and the server.

#### Changelog

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images  
spellcheck: fixed a few typos  
experimental: This is experimental  
/:cl:

2019-08-24 12:18 UTC, AsV9 commented
what could possibly go wrong

2019-08-26 11:59 UTC, Amelia0010 requested changes

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +////obj/item/t_scanner/attack_self(mob/user)
?

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +		to_chat(user, "<span class='warning'>You destroy humanity</span>")
```suggestion
		to_chat(user, "<span class='warning'>You bring balance to humanity</span>")
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +		for(var/mob/living/carbon/M in GLOB.mob_list)
```suggestion
		for(var/mob/living/carbon/M in GLOB.alive_mob_list)
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +				if(!(user == M))
```suggestion
				if(!(user == M) && prob(50))
```
You know, don't kill all of em innit

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +		to_chat(user, "<span class='warning'>You need all the infinity gems to destroy humanity.</span>")
```suggestion
		to_chat(user, "<span class='warning'>You need all the infinity gems to bring balance to humanity.</span>")
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +/obj/effect/proc_holder/spell/targeted/tesla/gauntlet
a bunch of these spells have variables that are identical to the ones they inherit, like the name and description, so they don't need to be here as well.

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +/obj/effect/proc_holder/spell/aimed/resurrect/update_icon()
Should probably be finished

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +/obj/effect/proc_holder/spell/aimed/time/update_icon()
see above

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +/obj/effect/proc_holder/spell/aimed/animate/update_icon()
see above

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +/obj/item/gun/energy/beam_rifle/power_artifact/update_icon()
see above

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	new /obj/item/infinity_stone/power(loc, 1)
```suggestion
	new /obj/item/infinity_stone/power(get_turf(src), 1)
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	desc = "A cube of immense power. It's teleportation powers are unimaginable."
```suggestion
	desc = "A cube of immense power. Its teleportation powers are unimaginable."
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	uses = 100000 //A number so large it'll never be reached
```suggestion
	uses = INFINITY //A number so large it'll never be reached
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	new /obj/item/infinity_stone/space(loc, 1)
```suggestion
	new /obj/item/infinity_stone/space(get_turf(src), 1)
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	new /obj/item/infinity_stone/reality(loc, 1)
```suggestion
	new /obj/item/infinity_stone/reality(get_turf(src), 1)
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	////obj/item/t_scanner/attack_self(mob/user)
???

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	new /obj/item/infinity_stone/soul(loc, 1)
```suggestion
	new /obj/item/infinity_stone/soul(get_turf(src), 1)
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	empty = 1
I'm guessing this needs to be a TRUE

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +				to_chat(user, "<span class='notice'>[src] are useless on the dead.</span>")
```suggestion
				to_chat(user, "<span class='notice'>[src] is useless on the dead.</span>")
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	toggle = 1
```suggestion
	toggle = TRUE
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	toggle = 0
```suggestion
	toggle = FALSE
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +/proc/timestop_definitions(obj/effect/proc_holder/spell/aoe_turf/conjure/timestop/S) //Timestop needs to have the same path to ensure its host can timestop immune.
Why is this a global proc?

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	new /obj/item/infinity_stone/time(loc, 1)
```suggestion
	new /obj/item/infinity_stone/time(get_turf(src), 1)
```

2019-08-26 11:59 UTC, nichlas0010 commented on yogstation/code/modules/gauntlet/gauntlet.dm
> +	new /obj/item/infinity_stone/mind(loc, 1)
```suggestion
	new /obj/item/infinity_stone/mind(get_turf(src), 1)
```

2019-09-13 09:31 UTC, SomeguyManperson commented
is this kill?

2019-09-13 12:12 UTC, sam0oneau commented
Indeed

2019-09-13 13:26 UTC, nichlas0010 commented
mane then close the PR

2019-09-13 13:26 UTC, closed without merging