Updates the armory officer's uniform and adds spur boots to the warden's locker.
yogstation13/Yogstation pull request #6637
Opened 2019-08-26 17:02 UTC by Ihonkification

![image](https://user-images.githubusercontent.com/37936685/63707795-a988b080-c82a-11e9-8102-64735a53e40e.png)
![image](https://user-images.githubusercontent.com/37936685/63707798-ab527400-c82a-11e9-92b4-fa2857460150.png)
![image](https://user-images.githubusercontent.com/37936685/63707801-ad1c3780-c82a-11e9-810d-0b1cd9c1416d.png)

The original sprite had a green camouflage design which was dumb since woodland camouflage in space, and also looked out of place.

New uniform inspired by Revolver Ocelot from MGS3
![image](https://user-images.githubusercontent.com/37936685/63704710-827ab080-c823-11e9-9691-d46440e53a8f.png)

The spurs can be found in the warden's locker and makes a sound when the wearer moves around. 

it's probably annoying.

sprite renamed to GRU_officer from KR_officer

now you can be revolver ocelot (revolvers not included, steal the detectives and a syndicate's revolver)

you're pretty good.

when the warden is a catperson https://www.youtube.com/watch?v=y897tozJeg8

no more security stuff as per suggestion in another pr

#### Changelog

:cl:  Identification
rscadd: Adds spur boots to the warden's locker.  
soundadd: The spurs make a sound when the wearer moves. 
imageadd: Armory officer uniform updated. 
imageadd: Warden's spur jackboots.
tweak: Armory officer's uniform renamed to Gulag officer uniform.
/:cl:

2019-08-26 17:06 UTC, drderp3635 commented
Make the spurs deal damage to downed people you walk over if you are on harm intent

2019-08-26 21:28 UTC, fluffe9911 requested changes
Stop trying to replace stuff with drastically different stuff.

2019-08-26 21:28 UTC, fluffe9911 commented on yogstation/code/game/objects/structures/crates_lockers/closets/secure/command.dm
> -	new /obj/item/clothing/under/yogs/krofficer(src)
Why are you so intent on replacing outfits with drastically different ones reeee.

2019-08-26 21:47 UTC, Ihonkification commented on yogstation/code/game/objects/structures/crates_lockers/closets/secure/command.dm
> -	new /obj/item/clothing/under/yogs/krofficer(src)
duder, woodland camouflage does not belong in space, nor on the security team. i wish to make it contextually sound within spacemans. 
![image](https://user-images.githubusercontent.com/37936685/63725816-60008b80-c853-11e9-9cb8-a496c3098b46.png)

2019-08-26 21:50 UTC, fluffe9911 commented on yogstation/code/game/objects/structures/crates_lockers/closets/secure/command.dm
> -	new /obj/item/clothing/under/yogs/krofficer(src)
oh yeah sure but space russians, space wizards, doom esc hell monsters, pretty much all the autodrobe costumes and bloody waldo totally belong in space. Its a gameeeeeee let people dress how they want to dress man.

2019-08-26 21:51 UTC, Ihonkification commented on yogstation/code/game/objects/structures/crates_lockers/closets/secure/command.dm
> -	new /obj/item/clothing/under/yogs/krofficer(src)
space russians and bloody waldo can do what they want, i'm talking about the security team.

2019-08-28 01:00 UTC, Firewolf34 commented
NOOOOOOOOOOOO!

I love that green outfit. You gotta leave the green one.

The other one I was cool with replacing because HoS already has so many things but you gotta leave the green one! It isn't green because of woodland camouflage, it's green because of tradition and army olive drab. 

Many armies use olive drab because the color instantly gives the viewer the impression they are dealing with uniformed military, and because of tradition. 

I can understand how in space, in the year 2550, we probably would have moved away from some of these traditions, but the Olive Drab is there because the warden has a bit of a military meme to him. You can't take my olive drab! :(

I like the new uniform, but make it additional to the Olive Drab pleeeaaseee

I'll understand if you end up changing it, because, yes, it does make sense... but I just really really am biased towards that uniform. Hell I even got my entry into the Yogstation Wiki Contest wearing this uniform, so if you remove it, the Yogstation Wiki will be out of date! Consider that, huh? :)
![3582-fe95188cbb79ec117268479e17e73055 jpg](https://user-images.githubusercontent.com/2159739/63818548-16717880-c907-11e9-9272-61a4a6d8d9a8.png)

2019-08-28 11:26 UTC, Ihonkification commented
k

2019-08-28 13:45 UTC, fluffe9911 approved these changes

2019-08-28 13:48 UTC, merged

2019-09-04 19:03 UTC, Alexandria404 commented
Add it as an optional one?

2019-09-04 19:27 UTC, Firewolf34 commented
I just wanted to say, thank you @Ihonkification for keeping that beautiful, luscious green jacket in the game :)

And great work on the PR. Love the boots.