Minsky Sign Update
yogstation13/Yogstation pull request #6674
Opened 2019-09-03 02:06 UTC by MayhemSailor

Adds minsky signs to various stations

Updates various maps with Minsky signs

### Sign Update

Updates in-rotation maps with Minsky Signs, see changelog for details. Additionally #5757 is corrected. You can view the signs in #6667.

####Changelog

🆑
rscadd: Added Minsky Signs to Yogstation, YogsPubby, YogsMeta, Mining Outpost & Labor Prison
rscdel: Removed old signage from the aforementioned stations
bugfix: fixes #5757
spellcheck: fixed a few typos in signs_departments.dm introduced in #6667 

/🆑

2019-09-03 02:23 UTC, MayhemSailor commented
Whyfor you fail mapdiff? @Ktlwjec advise?

2019-09-03 19:08 UTC, MayhemSailor commented
It's not a revert... so the bot is off...

2019-09-08 13:50 UTC, alexkar598 requested changes
Replace the sprites for the original signs instead of creating a whole new subtype for no apparent reason

2019-09-09 20:51 UTC, MayhemSailor commented
@alexkar598 The subtype is ALREADY merged into yogs by #6667. Folks just asked they be implemented on the other yogs stations.

2019-09-13 08:07 UTC, merged