Surgical Clothing change
yogstation13/Yogstation pull request #6735
Opened 2019-09-19 19:48 UTC by Codeatmos

### Intent of your Pull Request
After a discussion about surgery on discord, A few things came to mind
Medbay has too much downtime, and no real purpose unless maxcapmcbuddyretard goes wild that round.
Surgery is too slow and risky.

So I decided to take a crack at fixing that, or at least making surgery a viable method for a possible series of PRS that shifts med bays downtime into RND like gameplay, in which you upgrade your fellow crewmembers with surgery.
You may say "THIS MAKES SURGERY SUPER OP AND PPWOERGAMEY WTF??!?!?!?!" 2 things
1-You are laying down, you are still slowed and most of all, open for attacks
2-You can't read what surgery is being done on you; I could take your heart out, or give you a CNS rebooter.

This may come along with a possible medbay mapping change, but anyhow, basically, (as of current)surgery is an unfocused, clunky, risky practice that gives no advantage and will be used to patch in the "an AFK medic would be doing the same job as me" rounds.

Future PRS may include
Reintroduction of Surgery Speedup chems/stasis bed upgrade surgery modifiers
Introduction of an upgraded round-start only medkit for medical doctors
Medbay layout changes, courtesy of Nickvr628
#### Changelog

:cl:  
tweak: You no longer have to full strip for surgery  
/:cl:

2019-09-19 23:00 UTC, SomeguyManperson commented
I'd put this behind an upgraded set of surgical drapes myself

2019-09-20 00:42 UTC, Codeatmos commented
I don't want research to have to invest 12381023801283102938120938 points(non surgery wise) to allow medbay to not be bored as fuck,so this won't be locked behind a RND wall.

2019-09-20 00:55 UTC, MegaEmpirical commented
You don't need to strip? Seems weird and stripping isn't that long.

2019-09-20 04:05 UTC, CMOisLing commented
I don't think this will change much. I spend a large majority of my time in medbay and a lot of the time people just don't want to because they either don't care or don't know surgery. But I'm down to see the  other changes you proposed.

2019-09-20 13:13 UTC, Codeatmos commented
This is mainly aimed at making surgery faster, and most importantly you don't have to take off sec/antag/powergaming gear just to get a simple surgery, to answer your question Lyis.

2019-09-20 13:19 UTC, MegaEmpirical commented
I think you should have to take it off. It's a risk of the surgery and an opportunity for the surgeon.

2019-09-20 20:03 UTC, Codeatmos commented
Well, you may not be accustomed to the new changes, that don't show the patient what they are operating on, so I could be like
"Hey Marc Mingle want a CNS rebooter"
He doesn't have to take his gear off, so it's just simple and fluid now.
I then can take his heart out, and due to him not pumping blood, he will suffocate nearly instantly and go unconscious, risks still exist.

2019-09-24 22:30 UTC, alexkar598 requested changes
Use can_inject instead so normal clothes don't block it but hardsuits don't.

2019-10-02 21:08 UTC, alexkar598 commented
PR marked as stale

2019-10-09 14:46 UTC, oklews commented
I’d also like to highlight you CAN tell most of what they are doing, you’d be pretty worried when you see “Doctor X begins removing something from your head” when you asked for an implant

2019-10-12 15:50 UTC, closed without merging