Various small map fixes/changes that were annoying me
yogstation13/Yogstation pull request #6849
Opened 2019-10-10 17:39 UTC by Ktlwjec

This is mostly a signs update, but then I corrected various issues (such as unconnected piping) whenever I saw it, and decided to fix the fire alarms too since that wouldn't be an issue.

**All maps**
Most, if not all, of the signs that were on windows have been moved onto walls.
Fixed a lot of positioning with various signs to make sure they could be seen from the appropriate direction(s) only.
Made sure every single fire alarm was facing the correct way, and that they all had the correct x+y positioning.

**Metastation**
Connected the fitness room pipes.
Connected the bar+theater pipes to the rest of the station.
Connected a vent in cargo.
Added some missing connector ports.
Moved the signal technician spawn to actually be in tcomms.
Added in some missing area tags on the Cargo Bay airlocks, just outside the vault.
Changed the Gear Room area to "Security Office" instead of "Warden Office", since it's not the warden's office.
Moved a genetics and a research sign.
Added access requirements to a maintenance airlock that previously had none.
Virology disposals no longer goes through a wall.

**Pubbystation**
Added in some missing maintenance pipes.
Readded the gravity generator airlock after some prankster removed it.
Removed the atmos signs dotted around the gravity generator.
Added airlock cyclelinks between the tcomms transit tube airlock and space airlock.
Added breath masks and emergency oxygen tanks to the Port Emergency Storage.
Added in a missing corner decal.
Replaced a tcomms sign with an engineering sign.
Added some medical signs.
Moved the genetics and hydroponics signs.
Turned some windows into window spawners (window+grille).

**Deltastation**
Added a few different colored pens to the QM's office.
Moved the QM's stamp to the new pens table.
Fixed the monkey pen windoors name.
Added in some missing nearstation area tags near the holodeck.
Added a tcomms and a virology sign.
Removed a botany sign.
Moved a botany sign.
Replace an exam sign with a nanotrasen sign.

**Omegastation**
Moved the high voltage signs by Engineering.
Removed an unconnected cable.
Swapped the chemical storage and the chemistry sign around.
Removed a medical, xenobiology and botany sign.
Moved a research, botany and robotics sign.
Added decals next to the robotics(?) sign, inbetween the firelocks.

**Boxstation**
Swapped the chemical storage and the chemistry sign around.
Removed department signs from maintenance.
Added robotics, evac and restroom signs.
Moved the science security, cargo security and mining signs.

:cl:  
rscadd: Fixes numerous issues across all the main maps.
/:cl:

2019-10-10 18:11 UTC, AsV9 commented
![image](https://user-images.githubusercontent.com/13056792/66594848-2d5be980-eb9a-11e9-9f57-6cead73de2e8.png)

2019-10-11 23:07 UTC, alexkar598 requested changes
Checkout that sign/firealarm on omega and fix Pubby's chapel windows please

2019-10-12 07:33 UTC, Ktlwjec commented
Sign was fine, windows done.

2019-10-12 15:46 UTC, alexkar598 approved these changes

2019-10-12 15:47 UTC, merged