IC issue button tells the receiver who hit them with the no u
yogstation13/Yogstation pull request #6854
Opened 2019-10-11 04:51 UTC by GuppyLaxx

Title.

Why?
Why not, it's transparency. I'm sure people get frustrated when they just get hit with the dumbest button that admins have available, so, why not let them know who did it?

2019-10-11 05:10 UTC, MayhemSailor commented
Guppy money when merged. I approve.

2019-10-11 07:59 UTC, Amelia0010 requested changes

2019-10-11 07:59 UTC, nichlas0010 commented on yogstation/code/modules/admin/verbs/adminhelp.dm
> +	var/msg = "<font color='red' size='4'><b>- AdminHelp marked as an IC issue by [key_name]! -</b></font><br>"
check for stealthmin.

2019-10-11 10:58 UTC, Mr-Space commented
Most admins tell you the reason before hitting it and we don't hit it nilly willy, if it's marked IC, it's IC.

2019-10-11 18:26 UTC, Amelia0010 approved these changes

2019-10-11 22:09 UTC, alexkar598 commented
Don't merge -BritishGrace over discord reacts

2019-10-11 23:44 UTC, GuppyLaxx commented
ok but why not

2019-10-12 02:41 UTC, alexkar598 commented
Don't merge -SuperGuy over discord reacts

2019-10-12 14:59 UTC, Rayisken commented
I suggest lowering the sodium in your diet. It really shouldn't matter who, if you disagree with a decision you can always utilize discord channels or make a complaint on the forums to get other admin input on how your situation was dealt with.

2019-10-12 15:06 UTC, GuppyLaxx commented
This is literally about nothing you've just said, please stop delusional, thanks.
How hard is it to comprehend how minuscule of a change this is :
If you're not stealthed, hitting the IC button now tells the person your ckey.
If you're stealthed, it tells them an administrator did it.
That's it.

2019-10-12 15:35 UTC, Rayisken commented
"If you're stealthed, it tells them an administrator did it."
They know an admin did it if they pushed the button in the first place.

I don't think insulting people is a productive way of getting this merged. Once again, it really shouldn't matter who pushed the IC button, if you disagree with a decision you can always utilize discord channels or make a complaint on the forums to get other admin input on how your situation was dealt with. If multiple administrators are on, tickets that deal with IC issues are usually discussed in achat prior to being assigned the IC designation making it an all administrator's decision, so it's not always the ticket handler/button pusher that has made the decision.

2019-10-12 15:41 UTC, alexkar598 commented
Alot of the staff are downvoting this so imma just...

2019-10-12 15:41 UTC, Oakboscage commented
I really don't see how this matters either way.

2019-10-12 15:42 UTC, GuppyLaxx commented
Ah yes, just close it because staff have the final decision.
if you don't see how it matters, then why not add it?
This is a situation of why not rather than a why, it's literal transparency for those playing, and doesn't affect the admin in any single way

2019-10-12 15:44 UTC, ynot01 commented
i feel this is a good change

2019-10-12 15:45 UTC, Rayisken commented
It's been explained to you very clearly why it does not work as you are expecting

2019-10-12 15:48 UTC, GuppyLaxx commented
That literally changes **nothing**. It's amazing to me how it's a literal gang up just because it says it affects admins

2019-10-13 09:48 UTC, ThatLing commented
Re-opening this because I asked the HCs what to do with this and alex closed it before they could even respond.

2019-10-13 12:36 UTC, alexkar598 commented
@GuppyLaxx if it changes nothing then no point having it now

2019-10-13 12:38 UTC, alexkar598 commented
Time to start marking issues as wiki instead of IC

2019-10-13 14:49 UTC, GuppyLaxx commented
It's a small quality of life for normal players. What's wrong with that, even if it's ineffective

2019-10-13 16:40 UTC, AsV9 commented
God stop being so god damn difficult

2019-10-13 16:41 UTC, merged

2019-10-13 17:18 UTC, AffectedArc07 commented
Reminder that $100 was paid for this 

![why](https://i.imgur.com/8AtkoY2.png)

2019-10-13 20:31 UTC, optimumtact commented
Worth it

2019-10-14 11:02 UTC, 81Denton commented
Fucking lol

2019-10-16 00:49 UTC, Colburn3000 commented
Imagine paying someone $100 to add one line of code.

2019-10-16 02:46 UTC, MayhemSailor commented
@Colburn3000 imagine $100 being spare change and being worth every penny.