[wip] new uplink items depending on your race
yogstation13/Yogstation pull request #6862
Opened 2019-10-11 21:33 UTC by boodaliboo

### Intent of your Pull Request
this pr currently has a few unique items for a couple of our round start races that they can buy in there uplink
angel potion for human 7tc
angry rant for preternis 20tc 
fire breath for lizards 7tc
dead mouse for felinid 1tc
disco ball for ethereal 2tc

#### Changelog

:cl:  
rscadd: added a few new items to the syndicate uplink so we have some cool items that different races can experiment with
wip: This is work in progress  
/:cl:

2019-10-11 21:45 UTC, Nickvr628 commented
My god look at all those commits

2019-10-11 21:53 UTC, boodaliboo commented
> My god look at all those commits
these were all webedits i made during class so i just made a seperate pr for each thing

2019-10-11 22:06 UTC, alexkar598 requested changes

2019-10-11 22:06 UTC, alexkar598 commented on yogstation/code/game/objects/items/premadepapers.dm
> +	<b>-kojuh: </b><span class=\"paper_field\"></span><br><br>
```suggestion
	info = {"<center><h3>THE RANT</h3></center><hr>\
	<b>powergame bad: </b><span class=\"paper_field\"></span><br><br>\
	<b>-kojuh: </b><span class=\"paper_field\"></span><br><br>"
```

2019-10-11 22:06 UTC, alexkar598 commented on code/game/objects/items/dna_injector.dm
> +	obj/item/dnainjector/firebreath
```suggestion
	/obj/item/dnainjector/firebreath
```

2019-10-11 22:06 UTC, alexkar598 commented on yogstation/code/game/objects/items/premadepapers.dm
> +	<b>-kojuh: </b><span class=\"paper_field\"></span><br><br>
Github is being an ass today,be sure to do it properly not weirdly like this

2019-10-11 23:17 UTC, fluffe9911 commented
racist

2019-10-11 23:27 UTC, alexkar598 commented
Note: I will be closing this PR on the 24h mark,its just shit

2019-10-11 23:40 UTC, boodaliboo commented
> Note: I will be closing this PR on the 24h mark,its just shit
why i spent a few hours on it

2019-10-11 23:41 UTC, boodaliboo commented
> Note: I will be closing this PR on the 24h mark,its just shit

and it passed travis

2019-10-11 23:48 UTC, Nickvr628 commented
I don't think this is a shit PR, it is a bit memey and might end up needing a balance pass later on but I think it is fine.

2019-10-12 01:34 UTC, boodaliboo commented
> Note: I will be closing this PR on the 24h mark,its just shit

alex changed his mind after i edited this

2019-10-12 19:07 UTC, MegaEmpirical commented
Racist. No plasmamen nor moth love.

2019-10-13 16:58 UTC, alexkar598 requested changes

2019-10-13 16:58 UTC, alexkar598 commented on code/game/objects/items/grenades/chem_grenade.dm
> +/obj/item/grenade/chem_grenade/metalfoam/Initialize()
epic
```suggestion
/obj/item/grenade/chem_grenade/radiation/Initialize()
```

2019-10-13 16:58 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	desc = "It looks like somebody dropped the bass on it. A Degenerate's favorite meal."
no

2019-10-13 16:58 UTC, alexkar598 commented on code/modules/uplink/uplink_items.dm
> +	cost = 5
too high for something you need to grow

2019-10-13 16:58 UTC, alexkar598 commented on code/modules/uplink/uplink_items.dm
> +	cost = 2
too low for an AOE ur fucked grenade

2019-10-13 19:40 UTC, boodaliboo commented
I’ll do your suggestions In a bit thanks

2019-10-14 11:23 UTC, alexkar598 approved these changes

2019-10-14 11:23 UTC, merged

2019-10-16 05:05 UTC, neeshacark commented
Still no tail eswords for lizards