DRAGnet manual teleport destination setting
yogstation13/Yogstation pull request #6889
Opened 2019-10-15 09:04 UTC by SomeguyManperson

hmm yes today we will set the teleport destination to that of entire and therefore end of the list of active teleporters

:cl:  
rscadd: DRAGnet now has its teleport destination set manually
/:cl:

2019-10-15 09:07 UTC, oklews commented
Ahh yes, straight to perma, no trial

2019-10-15 15:38 UTC, Hopekz commented
You mean now I don't actually have to work to catch a criminal as sec?

Before the dragnet wasn't an option for this because the victim would be teleported to a random location but now we have an "easy option" that would make dragnet the only tool needed for this job.

As it currently stands I think this is too good, removes the need to "deal" with the threat since the first shot of the dragnet locks the target and the 2nd-3rd shot teleports them to perma. You have created a one tool fits all solution where originally the dragnet did not fill this role. This is a balance PR .

2019-10-15 18:27 UTC, SomeguyManperson commented
This was the intended effect of the DRAGnet, but the code went through a list of all the teleporters so it was super unreliable (if hotel staff turned on their teleporter, it was likely to overwrite the current destination.
![image](https://user-images.githubusercontent.com/24857008/66858613-a58a2c80-ef57-11e9-85eb-7e14dce39272.png)
also the teleport field lasts only 3 seconds, so if someone's actually stunned by it you won't have enough time to cuff them unless you pull them off the net portal, which means you can't also stop them from carrying tools or a weapon

2019-10-21 15:54 UTC, Amelia0010 requested changes

2019-10-21 15:54 UTC, nichlas0010 commented on code/modules/projectiles/guns/energy/energy_gun.dm
> +		L["None (Dangerous)"] = null
```suggestion
	L["None (Dangerous)"] = null
```

2019-10-21 15:54 UTC, nichlas0010 commented on code/modules/projectiles/guns/energy/energy_gun.dm
> +	user.show_message("<span class='notice'>Locked In.</span>", 2)
Should it really say it's locked in, even if it locks in to `"None (Dangerous)"`

2019-10-24 09:21 UTC, Amelia0010 approved these changes

2019-10-28 09:17 UTC, merged