Trying to dab while rrstrained no longer deals brain damage
yogstation13/Yogstation pull request #6901
Opened 2019-10-16 15:41 UTC by SomeguyManperson

:(

:cl:  fun police
bugfix: dabbing while restrained no longer causes brain damage
/:cl:

2019-10-16 16:10 UTC, boodaliboo commented
Feature

2019-10-16 16:41 UTC, oklews commented
Bad PR, how will I meme on sec now?

2019-10-16 17:20 UTC, ynot01 commented
rrstrained

2019-10-16 19:15 UTC, Hopekz commented
You mean I can't get an imaginary friend to suffer with me when I'm getting arrested?

2019-10-17 05:43 UTC, SomeguyManperson commented
you aren't even dabbing you're just not dabbing and magically taking brain damage

2019-10-17 10:37 UTC, alexkar598 requested changes

2019-10-17 10:37 UTC, alexkar598 commented on yogstation/code/modules/mob/living/emote.dm
> +	if(ishuman(user) && !user.restrained())
```suggestion
	if(. && ishuman(user))
```

2019-10-17 18:52 UTC, oklews commented
Imagine not being able to emote while restrained

2019-10-17 19:35 UTC, Hopekz commented
> you aren't even dabbing you're just not dabbing and magically taking brain damage

Would be funny if you just get a message in your head saying that you go through the motion of dabbing but realize that your body is unable to follow because of the restraints so you take the brain damage doing a mental dab but nothing happens on the outside. The player went through the effort of going through the *dab

2019-10-21 01:28 UTC, merged