Cybernetic Organs should now be more worth while
yogstation13/Yogstation pull request #6931
Opened 2019-10-22 21:24 UTC by CMOisLing

Cybernetic organs are shit and really not worth it 90% of the time even for powergamers. So Ive improved them so they should actually be noticable in situations they should be a factor in. Might have buffed the liver too much but I doubt it will be an issue.

-Base level cyber heart now regenerates epinephrine
-Upgraded heart now gives atropine instead
-Base cyber lungs are now old upgraded lungs
-Upgraded lungs are much more robust and should allow you to survive in environments that would harm others
-Base cyber liver is now old upgraded liver
-Upgraded liver should be able to shrug off some fairly bad toxins, and slowly heal toxin damage

#### Changelog

:cl:    
tweak: Cybernetic organs have been improved 
/:cl:

2019-10-22 21:37 UTC, ynot01 commented
I'm for upgraded cyber organs getting buffed but default cyber organs should not have much benefit, if at all; they're supposed to be emergency replacements for when you dont have fresh organs lying around and fuckstick over here had major heart failiure

2019-10-22 21:37 UTC, SomeguyManperson commented
Cyber appendix when

2019-10-22 21:52 UTC, CMOisLing commented
> Cyber appendix when

I forgot I promised that next update I promise

2019-10-23 02:31 UTC, CMOisLing commented
Wait I’m an idiot I forgot to make it printable

2019-10-23 09:00 UTC, Amelia0010 requested changes

2019-10-23 09:00 UTC, nichlas0010 commented on code/modules/surgery/organs/appendix.dm
> +		M.emote("chuckle") //you really think that will stop me?
indent these 3 lines

2019-10-23 09:00 UTC, nichlas0010 commented on code/modules/surgery/organs/appendix.dm
> +	if(inflamed)
```suggestion
	if(inflamed)
		var/mob/living/carbon/M = owner
```

2019-10-23 09:00 UTC, nichlas0010 commented on code/modules/surgery/organs/liver.dm
> +	toxLethality = .007
```suggestion
	toxLethality = 0.007
```

2019-10-23 09:00 UTC, nichlas0010 commented on code/modules/surgery/organs/heart.dm
> +	addtimer(CALLBACK(src, .proc/restart), 80) //Can restart itself after an EMP so it isnt an insta death
```suggestion
	addtimer(CALLBACK(src, .proc/Restart), 80) //Can restart itself after an EMP so it isnt an insta death
```

2019-10-24 09:20 UTC, Amelia0010 approved these changes

2019-10-28 09:20 UTC, merged