Tickets now delay round end
yogstation13/Yogstation pull request #700
Opened 2018-05-04 11:24 UTC by nichlas0010

fixes: #630

2018-05-04 21:27 UTC, Altoids1 commented
Bless you

2018-05-04 22:26 UTC, nichlas0010 commented
This was done badly.

2018-05-04 22:27 UTC, nichlas0010 commented
I realize it's easier to work off this PR than it is to remake it

2018-05-06 09:27 UTC, ThatLing requested changes

2018-05-06 09:27 UTC, ThatLing commented on code/controllers/subsystem/ticker.dm
> +	if(GLOB.ahelp_tickets.ticketAmount) //YOGS - tickets
What if there's no admins online 🤔

2018-05-06 12:25 UTC, nichlas0010 commented on code/controllers/subsystem/ticker.dm
> +	if(GLOB.ahelp_tickets.ticketAmount) //YOGS - tickets
oh yeaaah

2018-05-06 13:37 UTC, ThatLing requested changes

2018-05-06 13:37 UTC, ThatLing commented on code/controllers/subsystem/ticker.dm
> +	if(GLOB.ahelp_tickets.ticketAmount && GLOB.admins.len) //YOGS - tickets
Make it show the "theres still tickets but no admins, make a complaint on the forum" message.

2018-05-06 15:10 UTC, ThatLing approved these changes

2018-05-06 15:10 UTC, merged