Mice can now eat cheese
yogstation13/Yogstation pull request #7048
Opened 2019-11-08 09:18 UTC by missatessatessy

Mice will eat any cheese they come across, and cheese can be 'fed' to them.

Fixes issue #841

(Side note, I still don't get how master stuff works, and I don't know how to keep it up to date with main yogs files without creating these prs that show up in this pr)
#### Changelog

:cl:  
tweak: Mice eat cheese
/:cl:

2019-11-08 11:27 UTC, alexkar598 requested changes
Add a cool down for the mouse eating it, a mouse is bound to go to the kitchen and just decimate your work

2019-11-08 23:21 UTC, Ratvar commented
Add a brain to chefs so they start hiding their cheese instead of leaving it for mice to eat as well

2019-11-09 03:09 UTC, missatessatessy commented
thats gonna be a bit harder

2019-11-09 22:13 UTC, Nickvr628 commented
If you place a cheese wedge on top of a mouse trap on the same tile, will the mouse trigger it and die?

2019-11-10 13:09 UTC, alexkar598 requested changes

2019-11-10 13:09 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +		addtimer(CALLBACK(src, .proc/digestFood), 3 MINUTES)
```suggestion
		addtimer(VARSET_CALLBACK(src, full, FALSE), 3 MINUTES)
```

2019-11-10 13:09 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +/mob/living/simple_animal/mouse/proc/digestFood()
Remove this proc

2019-11-10 13:09 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	if(stat == CONSCIOUS)
I....what? Remove this,there is no point in eating cheese during initialization

2019-11-10 13:09 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +		say("Squeak!")
```suggestion
		say("Burp!")
```

2019-11-10 13:09 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	if(CW && full == FALSE)
```suggestion
	if(!QDELETED(CW) && full == FALSE)
```

2019-11-10 13:09 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +		..()
```suggestion
		return ..()
```

2019-11-10 13:09 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +		qdel(CW)
You are deleting the cheese here but later you reference it at line 92 in the message. Move this below that message

2019-11-10 13:44 UTC, merged