ports snow golems from tg in preperation for christmas
yogstation13/Yogstation pull request #7050
Opened 2019-11-08 17:31 UTC by boodaliboo

### Intent of your Pull Request
nanotrasen officials have found a living snow man on the ice planet.

snowgolems are a type of golem that are incredibley weak to heat and cant be revived in any form when killed anyway (you can make a farm of these to grind for carrots if your insane) but they also have the two genetic cold related powers (geladkenesis, cryokenesis)
#### Changelog

:cl:  
rscadd: Ports Snow Golem
/:cl:

2019-11-15 22:36 UTC, alexkar598 commented
Who doesn't love space proof species

2019-11-17 10:17 UTC, boodaliboo commented
> Who doesn't love space proof species

golems are fun

2019-11-17 10:17 UTC, boodaliboo commented
> Who doesn't love space proof species

also this bridges a gap between genetics and xenobio

2019-11-21 10:29 UTC, ThatLing requested changes

2019-11-21 10:29 UTC, ThatLing commented on code/modules/holiday/halloween.dm
> +		returncode/modules/holiday/halloween.dm
wtf

2019-11-23 01:45 UTC, boodaliboo commented on code/modules/holiday/halloween.dm
> +		returncode/modules/holiday/halloween.dm
fixed

2019-11-27 23:23 UTC, merged