Adds a signal technician clothing vendor
yogstation13/Yogstation pull request #7058
Opened 2019-11-10 15:22 UTC by Ktlwjec

The others get vendors but the signal tech was stuck with a wardrobe :( I absolutely hate the name of it though, if anyone has a better suggestion please let me know.

A proud Signal Technician after finally getting recognition from NT:
![unknown](https://user-images.githubusercontent.com/34506490/68546376-75567200-03cd-11ea-8c7f-fc6004d1d8cd.png)

:cl:  
rscadd: Signal Technician's have a clothing vendor.
/:cl:

2019-11-10 17:31 UTC, Readystorm546 commented
I like this PR but im sad that i can no longer hide in that locker and set off a max cap during war opps. :(

2019-11-10 17:54 UTC, ynot01 requested changes
sorry i have no idea how reviews work but heres my name suggestion

2019-11-10 17:54 UTC, ynot01 commented on code/modules/vending/wardrobes.dm
> +	name = "SigtechDrobe"
SigDrobe?

2019-11-10 22:52 UTC, MegaEmpirical commented
I hate the vendrobes so much. This makes me incredibly sad. One of the last bastions of freedom dying.

2019-11-11 00:25 UTC, Xoxeyos commented
Keep the locker, you can do alot more with it, such as you know, hiding in it, there aren't many places to hide on the sat.

2019-11-11 04:25 UTC, Hopekz commented
Always thought that signal tech was a part of engineering in the past and since there is only one signal tech that locker kind of fit to cram all their shit in to.

I'm neutral as it is not a strong dislike just kind of **feels out of place in my opinion**.

2019-11-12 17:17 UTC, nesisknesis approved these changes
is that syd garland

2019-11-16 11:51 UTC, Ktlwjec commented
To address concerns:
I'm changing the name to SigDrobe, it's what I had originally and it really does sound better.
I'll add a new locker to boxstation tcomms, so there will be the same amount of lockers there as before.
It's not about whether you like the vendors or not, it's a matter of consistency. As we got this from TG, there was no vendor made to replace the Signal Technician wardrobe. If there was, we would've added it in when the other lockers were replaced.

2019-11-16 13:04 UTC, Ktlwjec commented
I'll just remake this, that is a brand new map copy idk what it's doing.

2019-11-16 13:21 UTC, closed without merging