independence day mysuc
yogstation13/Yogstation pull request #7065
Opened 2019-11-12 18:07 UTC by boodaliboo

### Intent of your Pull Request
adds american song for independence day
#### Changelog

:cl:  
rscadd: Adds a america music working this time 
/:cl:

2019-11-12 18:33 UTC, boodaliboo commented
Will fix this in a few hours

2019-11-12 19:15 UTC, MegaEmpirical commented
A bit late.

2019-11-12 23:27 UTC, boodaliboo commented
are you fucking kidding me

2019-11-12 23:52 UTC, boodaliboo commented
i broke every var somehow

2019-11-13 00:48 UTC, yacabo commented
I haven't looked into the code to confirm this or not so I apologies for my ignorance, but isn't there supposed to be a `)` at the end and or is there even a `lobby_music` var?

2019-11-13 01:15 UTC, boodaliboo commented
> I haven't looked into the code to confirm this or not so I apologies for my ignorance, but isn't there supposed to be a `)` at the end and or is there even a connected `lobby_music` var?

yeah thats one of the problems

2019-11-19 12:23 UTC, Amelia0010 requested changes

2019-11-19 12:23 UTC, nichlas0010 commented on code/modules/holiday/holidays.dm
> +		"https://www.youtube.com/watch?v=5uPoDNEn3I0", // americ
This will be really grating once you get to the 3rd round, please add more songs.

2019-11-19 19:16 UTC, boodaliboo commented
Yeah I will I just couldn’t think of other songs give me a bit to add some. Meore

2019-11-22 23:56 UTC, merged