Ninja jail is no longer permanent
yogstation13/Yogstation pull request #7178
Opened 2019-11-29 06:12 UTC by Darkstick

### Intent of your Pull Request

Once the ninja dies, the captured crew is teleported back onto the station.

This will not affect the ninja's experience, it will only mean that the captured crew will get the chance of seeing the station again if the ninja is defeated. Would motivate captured crew to not just go catatonic and leave my poor self alone with nobody to roleplay with.

#### Changelog

:cl:  
tweak: ninja dies and crew comes back
/:cl:

2019-11-29 06:13 UTC, ynot01 commented
laughter ninja

2019-11-29 06:26 UTC, Smudged commented
Finally a reason to just wait and not kill myself in the old Ninja dojo.

2019-11-29 06:28 UTC, ynot01 commented
tbh i find ninja jail to be quite nice, my last experience with it we plotted methods of escape while deconstructing the entire place, making shit with autolathe, and doing botany hoping for bluespace shit

2019-11-29 15:07 UTC, Ktlwjec commented
> tbh i find ninja jail to be quite nice, my last experience with it we plotted methods of escape while deconstructing the entire place, making shit with autolathe, and doing botany hoping for bluespace shit
Might be something for a future pr then, adding a portal that opens once the ninja is dead. So players can choose if they want to go back.

2019-11-30 00:01 UTC, alexkar598 requested changes

2019-11-30 00:01 UTC, alexkar598 commented on code/modules/antagonists/ninja/ninja.dm
> +			RegisterSignal(E, COMSIG_IMPLANT_ACTIVATED, .proc/on_death)
Why?

2019-11-30 06:02 UTC, SomeguyManperson commented on code/modules/antagonists/ninja/ninja.dm
> +			RegisterSignal(E, COMSIG_IMPLANT_ACTIVATED, .proc/on_death)
issue #7175 made COMSIG_MOB_DEATH unreliable

2019-12-09 05:50 UTC, SomeguyManperson commented
is there anything holding this up?

2019-12-09 08:56 UTC, merged