Adds a version of tator lings where anyone can be a xeno/tator for admemes
yogstation13/Yogstation pull request #7183
Opened 2019-11-29 21:24 UTC by fluffe9911

🆑 
add: new subtype of tator lings where anyone can be a tator/ling for admemery!
/🆑

2019-11-29 21:25 UTC, ynot01 commented
even like captain and sec?

2019-11-29 21:26 UTC, fluffe9911 commented
yes

2019-11-29 21:36 UTC, boodaliboo commented
Time to give captain some job exclusives

2019-11-29 23:47 UTC, alexkar598 commented
Admins can varedit ok

2019-11-29 23:51 UTC, fluffe9911 commented
yes but this makes it more convenient for the average admeme and is only like 5 lines of code

2019-11-30 00:41 UTC, Hopekz commented
Quality of life PR.
+1

2019-11-30 11:43 UTC, alexkar598 requested changes
Make it a flag to ignore the check that can be activated from secrets panel instead. E.

2019-11-30 11:53 UTC, Ktlwjec requested changes

2019-11-30 11:53 UTC, Ktlwjec commented on code/game/gamemodes/changeling/traitor_chan.dm
> +	name = "traitor + lings + anybody can be a antag"
name = "traitor + lings + anybody can be an antag"

2019-12-01 22:21 UTC, AsV9 commented
> Make it a flag to ignore the check that can be activated from secrets panel instead. E.

It's fine to leave this as a gamemode like raginmages.

2019-12-01 22:21 UTC, merged