Adds lifesaver achievement
yogstation13/Yogstation pull request #7210
Opened 2019-12-02 21:33 UTC by Lostlarry

it's that simple.(this one at least)

2019-12-02 21:41 UTC, ynot01 commented
defibrillate

2019-12-02 23:26 UTC, monster860 requested changes

2019-12-02 23:26 UTC, monster860 commented on code/datums/achievements/achievements.dm
> +	desc = "Successfuly defiblirate someone"
![image](https://user-images.githubusercontent.com/3681297/70003481-3ed5c800-1531-11ea-8779-6413fe3dfaa1.png)

2019-12-03 09:34 UTC, Amelia0010 requested changes

2019-12-03 09:34 UTC, nichlas0010 commented on code/datums/achievements/achievements.dm
> +	desc = "Successfuly defiblirate someone"
```suggestion
	desc = "Successfully defibrillate someone"
```

2019-12-03 12:56 UTC, closed without merging