adds a new fallout based tacti-cool kit and ports laser rifle from bad deathclaw
yogstation13/Yogstation pull request #7237
Opened 2019-12-04 16:59 UTC by boodaliboo

### Intent of your Pull Request
was listening to some fallout music and i thought to add a fallout based kit as we already have some fallout items altoids made for me months ago.
currently contains
a aer 9 laser rifle which does 40 damage per hit but has a 5 second shot cooldown
a t45b helmet
a t45b armor
a stimpack

#### Changelog

:cl:  
rscadd: Added a new gun and a new kit
imageadd: ported some bad deathclaw icons
/:cl:

2019-12-04 17:04 UTC, Ihonkification commented
pictures, icon bot is kill

2019-12-04 17:06 UTC, boodaliboo commented
> pictures, icon bot is kill

do my pictures even work im doing this as a web edit

2019-12-06 12:13 UTC, nesisknesis requested changes
images

2019-12-12 16:25 UTC, boodaliboo commented
oh theres aconflit one sec

2019-12-12 16:27 UTC, boodaliboo commented
should work now

2019-12-14 01:37 UTC, boodaliboo commented
WHAT IS EVEN PREVENTING IT

2019-12-15 11:51 UTC, Mr-Space commented
travis upsetti
code spaghetti

2019-12-16 08:35 UTC, missatessatessy commented on code/game/objects/items/storage/uplink_kits.dm
> +    	if("bond")
There's something up with the indentation here which is what is throwing travis off to start with.

2019-12-17 02:05 UTC, missatessatessy commented on code/game/objects/items/storage/uplink_kits.dm
> +    	if("bond")
Still not right

2019-12-17 02:08 UTC, missatessatessy commented on code/game/objects/items/storage/uplink_kits.dm
> +    	if("bond")
Try copying the the three lines from /obj to if, from the original code and pasting it in again (adding the brother)?

2019-12-17 02:12 UTC, missatessatessy commented on code/game/objects/items/storage/uplink_kits.dm
> +    	if("bond")
Also just noticed neo is wrong, should say "neo" = 1 but it says "neo=1"

2019-12-17 11:51 UTC, alexkar598 commented
That gun is stupid OP

2019-12-18 01:07 UTC, boodaliboo commented
> That gun is stupid OP

with a cooldown of 4 seconds and with this being a rng only item i feel like its fairly balanced

2019-12-20 16:34 UTC, Ihonkification commented
syndicate dont get lasers gun theyre too dumb

2019-12-20 23:01 UTC, boodaliboo commented
> syndicate dont get lasers gun theyre too dumb

they get lots of wacky tech

2019-12-29 22:45 UTC, alexkar598 commented
Conflict, not interested and noone seems willing to merge this or even look at it

2019-12-29 22:45 UTC, closed without merging