Emote cooldown framework (no more spam)
yogstation13/Yogstation pull request #7372
Opened 2019-12-21 00:50 UTC by Hopekz

Adds in a emote cooldown framework.
----
This means that emotes cannot be spammed anymore.

By default, a single emote cannot be repeated until 0.4 seconds have passed.
This is variable and is able to be set per emote.
I left *flip and *spin spam able because it's sacred and must be preserved.

I used this new emote delay framework to set *deathgasp emote delay to 3.4 seconds.
Why i did this: I remember how angry AI's sometimes spam their death sound every 0.01 seconds on a macro. This change removes this. 

yes, I cannibalized parts of TG code for this PR and edited it to fit in our codebase.

#### Changelog

:cl:  
rscadd: Emote cooldown framework has been added. This means you cannot spam a single emote in rapid succession (sorry macro kiddies).
rscadd: Used this new emote cooldown framework to add a longer delay to *deathgasp . Take that spamming silicons!
/:cl:

2019-12-23 01:28 UTC, alexkar598 requested changes

2019-12-23 01:28 UTC, alexkar598 commented on code/modules/mob/emote.dm
> +	cooldown = (0 SECONDS)
those () are not needed, macros are parsed before compile aka first

2019-12-23 01:28 UTC, alexkar598 commented on code/modules/mob/emote.dm
> +	cooldown = (0 SECONDS)
those () are not needed, macros are parsed before compile aka first

2019-12-23 01:28 UTC, alexkar598 commented on code/modules/mob/living/emote.dm
> +	cooldown = (3.4 SECONDS)
those () are not needed, macros are parsed before compile aka first

2019-12-23 01:28 UTC, alexkar598 commented on code/datums/emotes.dm
> +/datum/emote/proc/check_cooldown(mob/user, intentional)
```suggestion
/datum/emote/proc/check_cooldown(mob/user, intentional, update=TRUE) 
```

2019-12-23 01:28 UTC, alexkar598 commented on code/datums/emotes.dm
> +	if(!user.emotes_used)
```suggestion
	if(!update)
		return TRUE
	if(!user.emotes_used)
```

2019-12-27 22:19 UTC, Hopekz commented
Testing Alex's changes before I commit.

2019-12-28 20:04 UTC, Hopekz commented
Committed changes.

2019-12-29 23:12 UTC, alexkar598 requested changes

2019-12-29 23:12 UTC, alexkar598 commented on code/__DEFINES/components.dm
> +#define COMSIG_MOB_EMOTE "mob_emote" // from /mob/living/emote(): ()
Not used

2019-12-29 23:12 UTC, alexkar598 commented on code/modules/mob/emote.dm
> +			SEND_SIGNAL(src, COMSIG_MOB_EMOTE, P, act, m_type, message, intentional)
Not used

2020-01-04 06:49 UTC, Hopekz commented on code/modules/mob/emote.dm
> +			SEND_SIGNAL(src, COMSIG_MOB_EMOTE, P, act, m_type, message, intentional)
Did I do it?

2020-01-06 16:00 UTC, alexkar598 commented on code/modules/mob/emote.dm
> +			SEND_SIGNAL(src, P, act, m_type, message, intentional)
No like just delete this line
```suggestion
```

2020-01-07 14:23 UTC, merged