Fix dragging through firelocks
yogstation13/Yogstation pull request #7418
Opened 2019-12-27 20:52 UTC by monster860

:cl: monster860
tweak: When an edge firelock closes, if it closes between someone and something they're dragging it automatically pulls the thing they're dragging through.
/:cl:

2019-12-27 20:55 UTC, Hopekz commented
Yes finally speedmerge THIS IS WHAT IS NEEDED the answer to our prayers all hail #7418

2019-12-28 03:03 UTC, Nickvr628 commented
speedmerge

2019-12-29 23:38 UTC, alexkar598 requested changes

2019-12-29 23:38 UTC, alexkar598 commented on code/game/machinery/doors/firedoor.dm
> +			M.pulling.forceMove(T1)
Whoa whoa whoa, ripping people from chairs as the firelock closes?
```suggestion
			M.pulling.Move_Pulled(T1)
```

2019-12-29 23:38 UTC, alexkar598 commented on code/game/machinery/doors/firedoor.dm
> +			M.pulling.forceMove(T2)
```suggestion
			M.pulling.Move_Pulled(T2)
```

2019-12-30 04:21 UTC, Darkstick commented
s p e e d m e r g e

2019-12-31 15:08 UTC, alexkar598 requested changes
Make sure the pullers move_force is stronger than the pulled move_resist

2020-01-01 14:35 UTC, merged