I Fix The Mingun Osprey Through Sheer Willpower And Luck
yogstation13/Yogstation pull request #7541
Opened 2020-01-07 20:00 UTC by Readystorm546

So a long time ago i made this gun and then it was bad so i stopped making it, Then it somehow got merged so i took it as a sign and decided to try and "fix it" And i did. Also i did some more balance to the best of my ability.

Here i shoot a window
| 
|
V

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/52303581/71923765-bcf24380-315b-11ea-8a15-c41d173b123a.gif)

Here i shoot innocent civilians at close range
|
|
V

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/52303581/71923888-f62ab380-315b-11ea-8542-874aecb6054c.gif)

Here i shoot innocent civilians at long range
|
|
V

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/52303581/71923951-122e5500-315c-11ea-9c6e-2e5d1e082442.gif)

Here i shoot innocent doors at long range
|
|
V

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/52303581/71924020-2e31f680-315c-11ea-9387-d368259274d6.gif)

And this is the text it reads when you are shooting and when you have shot too much
|
|
V

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/52303581/71924134-620d1c00-315c-11ea-8295-59c37e9404cc.gif)

Better leave both hands free to fire...

![dreamseeker_3TUUWooB5E](https://user-images.githubusercontent.com/52303581/71924182-7d782700-315c-11ea-85d3-e15bb8d1d4df.png)

Stats for the gun include

	slowdown = 2 // The Slowdown effect on the player while equipped
	w_class = WEIGHT_CLASS_HUGE // Its big woah
	fire_delay = 1 // You cant fire right after a volley so wait a second
	burst_size = 3 / How many bullets per click
	recoil = 0.5 // Screen shake factor
	spread = 34 // The way the bullets come out
	fire_sound_volume = 60 //How loud the gun is
	overheat = 0 // Starting overheat level
	overheat_max = 30 // How far the overheat can go
	heat_diffusion = 2 // How fast heat diffuses 

#### Changelog

:cl:    
bugfix: I mean i just fixed the entire gun to work well
tweak: Made some balance changes to the gun  
/:cl:

2020-01-07 20:21 UTC, monster860 commented
[https://wiki.teamfortress.com/w/images/6/65/Heavy_specialcompleted07.wav](Cry some more)

2020-01-07 21:28 UTC, Hopekz commented
> [Cry some more](https://wiki.teamfortress.com/w/images/6/65/Heavy_specialcompleted07.wav)

It costs 400,000 credits to fire this weapon....for 120 deciseconds

2020-01-10 04:13 UTC, Nickvr628 commented
That small burst and delay doesn't feel minigun is... maybe a 7-10 round burst would be better?

2020-01-10 13:32 UTC, Readystorm546 commented
> That small burst and delay doesn't feel minigun is... maybe a 7-10 round burst would be better?

I was thinking about this too. But i think i have another solution in which it just fires faster because you can end up spamming it.

2020-01-11 01:14 UTC, alexkar598 requested changes

2020-01-11 01:14 UTC, alexkar598 commented on yogstation/code/modules/projectiles/guns/ballistic/minigun.dm
> +	automatic = 0
```suggestion
	automatic = FALSE
```

2020-01-17 12:55 UTC, alexkar598 approved these changes

2020-01-17 12:56 UTC, merged