Derelict additions
yogstation13/Yogstation pull request #7548
Opened 2020-01-09 00:35 UTC by Saratoubi

Added some stuff to Derelict in hopes of making it more feasible for drones to actually repair. Additions are: Old roboticist ID (for unlocking bots), Free Golem's blueprints (although they aren't called that), and 5 bluespace mesh so they can get a functional teleporter up and running.

:cl:  
tweak: Added some stuff to the Derelict in hopes of making it more feasible for the drones to repair.
/:cl:

2020-01-09 00:41 UTC, jcatjmeow commented
Robo id is fine.
Bluespace mesh is unnecessary. As a drone you are meant to rebuild the derilect. Teleporting to somewhere else is pointless and breaks your laws, but you could maybe make an argument for using it to get to mining for example...so meh.

Free golem is a huge no. Drones are expressly forbidden from interacting with other beings. There is zero reason a drone should be making golems, and even if you argue that creating beings doesn't count as interacting with them, you can't give them any orders. This breaks drone laws so hard

Robo id is fine, although I am a bit scared that it could be used by nondrones who find the Derilect. Mesh is meh. Free golem is NO.

2020-01-09 00:43 UTC, jcatjmeow commented
Also, I've spent entire rounds fixing the derlict back up to human habitation standards without any of these things, so saying that it's not feasible without them is a bit of a disservice to the sheer amount of Stuff and Things the Derilect already provides

2020-01-09 00:57 UTC, Idinuum commented
> Free golem is a huge no. Drones are expressly forbidden from interacting with other beings. There is zero reason a drone should be making golems, and even if you argue that creating beings doesn't count as interacting with them, you can't give them any orders. This breaks drone laws so hard

free golem blueprints, not shells retard

2020-01-09 02:00 UTC, LoliconSlayer commented
> Teleporting to somewhere else is pointless and breaks your laws

You realize that Drone laws don't actually bind the derelict drones to the Derelict Station right

2020-01-09 02:32 UTC, Saratoubi commented
The point of the bluespace crystals is mainly to go resource gathering. Without them its either, salvage the base for scrap metal, which can only get you so far, or float around in space looking for an asteroid or the station which takes ages.

2020-01-09 02:37 UTC, Saratoubi commented
Drone's laws do not bind them to the derelict either, technically they can improve whatever station they want. Be it the Derelict, the main station, or the free miners ship. In regards to the Free golems blueprints, they are mainly for creating new rooms, so creating new APCs and other stuff works. You can definitely make the station habitable for humans, but why stop there? Make the Derelict be the best it can be; fuck make it better than the main station, if you want. I just want to give drones the ability to get to that stage, before the main station calls the shuttle and the round is over.

2020-01-11 16:33 UTC, DerelictDrone commented
Glorious, finally we can make the derelict great again more than 30% of the time.

2020-01-13 04:37 UTC, Ktlwjec1 requested changes

2020-01-13 04:37 UTC, Ktlwjec1 commented on code/game/objects/items/cards_ids.dm
> +	desc = "An old Roboticit's ID. Surely it has some use?"
Roboticit's - Roboticist's

Will merge after that's done.

2020-01-29 21:04 UTC, Ktlwjec1 commented
Closing this, feel free to reopen when you have time to do the requested change.

2020-01-29 21:04 UTC, closed without merging