Unlinking Conveyors and Switches.
yogstation13/Yogstation pull request #7599
Opened 2020-01-13 18:53 UTC by DerelictDrone

### Intent of your Pull Request
Using a multitool, you can now unlink conveyor assemblies or randomly generate a new ID for switch assemblies.

#### Changelog

:cl:  
rscadd: Use a multitool on conveyor assemblies to unlink them from all switches, or use a multitool on a switch to randomly generate a new ID for linking conveyors.
/:cl:

2020-01-13 20:55 UTC, ynot01 commented
really enjoying the recent conveyer love

2020-01-15 11:06 UTC, alexkar598 commented
But why

2020-01-15 18:36 UTC, DerelictDrone commented
@alexkar598
Generating a new conveyor switch ID would allow you to re-use switches without fear that a conveyor somewhere on the station will also be affected, or having to pry up every single conveyor it may or may not be connected to just to unlink them.

Wherein unlinking individual conveyors would help save a player's time, rather than forcing them to just dump all the conveyors they want to re-use elsewhere into an autolathe to re-build them, or for instance if you separate a stack of conveyors, but link the wrong half of the stack.

Either way, these are some very easy quality of life changes that have been missing for far too long.

2020-01-17 13:00 UTC, alexkar598 requested changes

2020-01-17 13:00 UTC, alexkar598 commented on code/modules/recycling/conveyor2.dm
> +	return
No need to a return statement here

2020-01-23 11:44 UTC, merged