ports heart disease from bee
yogstation13/Yogstation pull request #7644
Opened 2020-01-14 17:36 UTC by boodaliboo

### Intent of your Pull Request
quote from orignal pr with one modification changing level 9 to 8 About The Pull Request
Adds a new simplemob, a really angry heart

"Adds a new level 8 symptom, Heart disease. The only level 8 kill symptom yet, but also quite hard to come back from.

More in depth:
Heart disease has -6 stage speed and a .5% chance, per tick, at stage 5, of causing a heart attack. Unless the stealth 2 threshold is met, this disease is incredibly noticeable as well, and does not debilitate the player until they reach this threshold, making a disease with this symptom easier to counteract if noticed"

Changelog
🆑
add: Heart Disease symptom
add: angry heart simplemob

/🆑

2020-01-14 17:39 UTC, boodaliboo commented
ugh guess im fixing this later

2020-01-14 17:42 UTC, missatessatessy commented on code/datums/diseases/advance/symptoms/heartattack.dm
> +					  <b>Stealth 2:</b> The disease is somewhat less noticable to the host."
threshold_descs = list(
		"Transmission 10" = "When the victim has a heart attack, their heart will pop right out of their chest, and attack!",
		"Stealth 2" = "The disease is somewhat less noticable to the host",
	)

2020-01-14 18:06 UTC, Idinuum commented
God bee are retarded

2020-01-14 18:16 UTC, Hopekz commented
That probability per ticket isn't too good IMO especially something that kills the user pretty quick after it activates.
A prob 1 per tick activates once every 4-8 seconds

So basically with the current balance of this PR at stage -6 you already have a good chance to die in the next 10-12 seconds.

I don't like this PR not sure why you chose to port this out of all other things.
Even with tick balancing to make it less ridiculous I don't really want more diseases that just straight up take you out of the game until you're cloned.
-1

2020-01-14 22:09 UTC, boodaliboo commented
It’s a level 8 symptom by the time you get this the rounds a hour in and there is rng anyways on even getting this I will do some nerfs though

2020-01-14 22:41 UTC, AdamElTablawy commented
There is already a symptom that effectively causes this. Bloat.

2020-01-15 05:08 UTC, Ktlwjec1 requested changes

2020-01-15 05:08 UTC, Ktlwjec1 commented on code/datums/diseases/advance/symptoms/heartattack.dm
> +	desc = "This disease infiltrates the host's heart, causing cardiac arrest after a long incubation period"
full stop

2020-01-15 05:08 UTC, Ktlwjec1 commented on code/datums/diseases/advance/symptoms/heartattack.dm
> +		to_chat(M, "<span class='userdanger'>[pick("Your chest hurts!.", "You feel like your heart skipped a beat!")]</span>")
wtf is this -> !.

2020-01-15 05:08 UTC, Ktlwjec1 commented on code/modules/mob/living/simple_animal/hostile/heart.dm
> +	desc = "A living heart. It's angry!."
!.

2020-01-15 05:08 UTC, Ktlwjec1 commented on code/modules/mob/living/simple_animal/hostile/heart.dm
> +	deathmessage = "falls lifeless."
stops beating.

Just a suggestion, ignore if you want.

2020-01-15 17:28 UTC, CMOisLing commented
> It’s a level 8 symptom by the time you get this the rounds a hour in and there is rng anyways on even getting this I will do some nerfs though

More like 15 to 30 depending on mining

Im not a big fan of the concept of this symptom, with high stage speed its just a luck game on whether you can walk to medbay before you get insta KO'ed and die shortly after. Combined with some annoying stun symptoms this would be awful. Even if you make it to medbay yogstations finest would probably just shove you in cryo. The whole transmission aspect is completely bypassed by sneezing. We have enough symptoms that are meant to kill you as fast as possible.

2020-01-16 23:38 UTC, boodaliboo commented
fine

2020-01-16 23:38 UTC, closed without merging

2020-01-16 23:47 UTC, Potototatoh commented
pffffffftgkhpythtohppghppfpgpgphphpttt