Achievement Get Part 1 - Greentext Achievements
yogstation13/Yogstation pull request #7657
Opened 2020-01-17 01:17 UTC by Altoids1

Hopek and Readystorm are paying me for this.
![image](https://user-images.githubusercontent.com/29939414/72580424-a5286700-38a1-11ea-81a4-011c7916e6a5.png)

## Overview

Included are 18 of the 88 achievements I'm being paid to add to the game, all of them having to do with greentexting.

There are also unique achievements for the leaders of team antag groups winning, too. Like Eminences get both the default "win as clockie" achievement as well as the "win as Eminence" one.

## Coder Warning

Doing this involved the creation of a new achievement type, ``/datum/achievement/greentext``. All achievements related to greentexting should be put under this type so that the user can also get the generic "get a greentext" achievement, too.

Additionally, ``/datum/antagonist`` got a new var: ``greentext_achieve``, which is the type of an achievement the antag will receive if they greentext as that antag type.

Not all antag types have been converted to the new ``greentext_achieve`` method, due to the excessive copypaste and lack of inheritence when it comes to determining win condition and objective accomplishment.

## Changelog
:cl:  Altoids
rscadd: Gangs, Clownops, Generic antags, EAAs, IAAs, Culties, Clockies, Revs, Sentient Diseases, Revenants, Vampires, Pirates and Blobs now all have unique achievements for greentexting!
/:cl:

2020-01-17 01:17 UTC, boodaliboo commented
do my kudzu bounty

2020-01-17 01:23 UTC, monster860 commented
You should add an achievement for greentexting as a nightmare.

2020-01-17 01:25 UTC, Altoids1 commented
> You should add an achievement for greentexting as a nightmare.

That'll be $0.34 at the next window please

2020-01-17 01:27 UTC, Hopekz commented
> You should add an achievement for greentexting as a nightmare.

LOL is there any way to NOT greentext as nightmare?

2020-01-17 08:53 UTC, Altoids1 commented
Okay, that should be all the Greentext achievements on my list done, with a couple runtime fixes already committed.

# Ready for Review.

2020-01-17 12:04 UTC, alexkar598 requested changes
My small little nitpick and also you have to write a database query to unlock the green text achievement on everybody who already has a green text achievement

2020-01-17 12:04 UTC, alexkar598 commented on code/datums/achievements/achievements.dm
> +/datum/achievement/greentext/internal
I realise this is a pretty fucking nitpick but can you rename this and the external one to iaa and eaa, internal makes it sound like it's some kind of abstract sub type for internal use

2020-01-18 23:32 UTC, merged

2020-02-01 20:38 UTC, Qustinnus commented on code/controllers/subsystem/achievements.dm
> +	if(istype(achievement,/datum/achievement/greentext) && achievementPath != /datum/achievement/greentext)
bruh

2020-02-01 20:40 UTC, Fikou commented on code/controllers/subsystem/achievements.dm
> +	if(istype(achievement,/datum/achievement/greentext) && achievementPath != /datum/achievement/greentext)
lol