adds new chem "graveyard"
yogstation13/Yogstation pull request #7694
Opened 2020-01-23 23:38 UTC by boodaliboo

adds a new chem that does what normal soda does but its combined into one you get it by combining space cola dr gibb and space-up.
name originates from what my friends growing up called it when you mixed every soda in the dispenser
#### Changelog

:cl:  
rscadd: Added new useless reagant
/:cl:

2020-01-23 23:48 UTC, ynot01 commented on code/modules/reagents/chemistry/recipes/others.dm
> +/datum/chemical_reaction/lube
this still says lube

2020-01-23 23:49 UTC, boodaliboo commented
Intended feature not bug intended

2020-01-24 09:53 UTC, Ktlwjec1 requested changes

2020-01-24 09:53 UTC, Ktlwjec1 commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	description = "What Happens when you mix all the sodas in the fountain you get this monstorsity"
description = "What happens when you mix all the sodas in the fountain? You get this monstrosity!"

2020-01-24 09:53 UTC, Ktlwjec1 commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	taste_description = "Tastes like liquid diabetes"
taste_description = "liquid diabetes"

2020-01-24 09:53 UTC, Ktlwjec1 commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	glass_desc = "just looking at is making you want feel sick"
glass_desc = "Just looking at this is making you feel sick."

2020-01-24 09:53 UTC, Ktlwjec1 commented on code/modules/reagents/chemistry/recipes/others.dm
> +	required_reagents = list(/datum/reagent/consumable/space_cola, /datum/reagent/consumable/dr_gibb, /datum/reagent/consumable/space_up = 1) //soda
required_reagents = list(/datum/reagent/consumable/space_cola = 1, /datum/reagent/consumable/dr_gibb = 1, /datum/reagent/consumable/space_up = 1)

2020-01-25 05:20 UTC, LoliconSlayer commented
Christ do you know what grammar is Bood

2020-01-25 08:25 UTC, boodaliboo commented
No and ktl ill impleiment your suggestion in a few days don’t have access to computer for a bit

2020-01-31 22:32 UTC, alexkar598 requested changes

2020-01-31 22:32 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	quality = DRINK_VERYGOOD
```suggestion
	quality = DRINK_GOOD
```
You dont need to be a genius to get this drink

2020-01-31 22:32 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +/datum/reagent/consumable/graveyard
```suggestion
/datum/reagent/consumable/gravedigger
```

2020-01-31 22:32 UTC, alexkar598 commented on code/modules/reagents/chemistry/recipes/others.dm
> +/datum/chemical_reaction/graveyard
```suggestion
/datum/chemical_reaction/gravedigger
```

2020-01-31 22:32 UTC, alexkar598 commented on code/modules/reagents/chemistry/recipes/others.dm
> +	id = /datum/reagent/consumable/graveyard
```suggestion
	id = /datum/reagent/consumable/gravedigger
```

2020-01-31 22:32 UTC, alexkar598 commented on code/modules/reagents/chemistry/recipes/others.dm
> +	results = list(/datum/reagent/consumable/graveyard = 3)
```suggestion
	results = list(/datum/reagent/consumable/gravedigger = 3)
```

2020-02-03 18:25 UTC, boodaliboo commented
It will be done my sire

2020-02-06 01:13 UTC, merged