Removes songs that suck
yogstation13/Yogstation pull request #7748
Opened 2020-02-01 18:55 UTC by swissloaf

### Intent of your Pull Request

Removes Jojo Theme, Running in 90s, Danzig, Elbow, and some other one idk.

#### Changelog

:cl:   
rscdel: Removes Jojo Theme, Running in 90s, Danzig, Elbow, and some other one idk.
/:cl:

2020-02-01 18:57 UTC, nesisknesis approved these changes
i approve

2020-02-01 19:24 UTC, overlord12345 commented
dont remove jojo theme

2020-02-01 20:29 UTC, nichlas0010 commented
```
/datum/controller/subsystem/ticker/proc/choose_lobby_music()
	//Add/remove songs from this list individually, rather than multiple at once. This makes it easier to judge PRs that change the list, since PRs that change it up heavily are less likely to meet broad support
	//Add a comment after the song link in the format [Artist - Name]
```

2020-02-01 23:19 UTC, swissloaf commented
> ```
> /datum/controller/subsystem/ticker/proc/choose_lobby_music()
> 	//Add/remove songs from this list individually, rather than multiple at once. This makes it easier to judge PRs that change the list, since PRs that change it up heavily are less likely to meet broad support
> 	//Add a comment after the song link in the format [Artist - Name]
> ```

cool

2020-02-02 02:10 UTC, deathslayer2481 commented
Why would you remove when you can fix

2020-02-02 20:13 UTC, ynot01 commented
dont remove jojo theme

2020-02-02 20:57 UTC, Amelia0010 requested changes
How do you manage to break both of the rules for editing the list?

2020-02-02 20:57 UTC, nichlas0010 commented on yogstation/code/controllers/subsystem/ticker.dm
> +		"https://www.youtube.com/watch?v=zlD5uvOt_Sw",                      // HL2 - Apprehension and Evasion
```suggestion
		"https://www.youtube.com/watch?v=zlD5uvOt_Sw",                      // Kelly Bailey - Apprehension and Evasion
```

2020-02-02 20:57 UTC, nichlas0010 commented on yogstation/code/controllers/subsystem/ticker.dm
> +		"https://www.youtube.com/watch?v=KFQpSp-3APw",                      // SS13 - Spectacular Suns
```suggestion
		"https://www.youtube.com/watch?v=KFQpSp-3APw",                      // Ken Arai - PINGU A GO! GO!
```

2020-02-02 21:24 UTC, AsV9 commented on yogstation/code/controllers/subsystem/ticker.dm
> +		"https://www.youtube.com/watch?v=KFQpSp-3APw",                      // SS13 - Spectacular Suns
nice one

2020-02-03 19:29 UTC, AsV9 commented
atomize the PR

2020-02-03 19:29 UTC, closed without merging