Nerf wizard academy 2
yogstation13/Yogstation pull request #7764
Opened 2020-02-06 01:08 UTC by JamieD1

Removing stand from wizard academy for power gamers

#### Changelog

:cl:  

rscdel: Removed stand from wizard academy

/:cl:

2020-02-06 03:20 UTC, boodaliboo commented
instead of removing it why not try buffing its defense or making it a stand arrow so theres a chance you will be gibbed

2020-02-06 06:22 UTC, Hopekz commented
I like bood's idea of except make it a one time use stand arrow

2020-02-06 12:43 UTC, overlord12345 commented
Stand arrows are multi-use just make it work like decks on lavaland that give you a random stand

2020-02-06 16:14 UTC, boodaliboo commented
It already gives a random one

2020-02-06 17:15 UTC, boodaliboo requested changes
add this between 406/407 or where you deleted the deck
/obj/item/stand_arrow

2020-02-06 17:23 UTC, boodaliboo commented on _maps/RandomRuins/SpaceRuins/Academy.dmm
> -/obj/item/guardiancreator,
/obj/item/stand_arrowadd this there

2020-02-06 18:11 UTC, Hopekz commented
No bood's fix is lazy.
Make a child for the arrow then edit the var for charges to make it a 1 time use.
Then add that child to the map

2020-02-06 18:21 UTC, ynot01 commented
just remove academy

2020-02-06 18:31 UTC, Alexandria404 commented
step in the right direction

2020-02-06 19:06 UTC, JamieD1 commented
What about 66% chance of gibbing one time use?

2020-02-06 19:34 UTC, Hopekz commented
> What about 66% chance of gibbing one time use?

I think the current arrow is about a 50% from what I remember. You should probably be fine with leaving the % chance unless you feel that it needs to be changed.

Seeing that this PR is meant to remove it I'd say going in the 60's is more in line with your original intent. 
Make sure to differentiate this arrow somehow from the normal one (different name/flavortext)

2020-02-06 19:36 UTC, JamieD1 commented
> I think the current arrow is about a 50% from what I remember. You should probably be fine with leaving the % chance unless you feel that it needs to be changed.
> 
> Seeing that this PR is meant to remove it I'd say going in the 60's is more in line with your original intent.
> Make sure to differentiate this arrow somehow from the normal one (different name/flavortext)
To be honest I want it gone to prevent people going for it, plus gibbing them would ruin the round for them and if they powergame xeno to get there maybe gibbing would stop them from trying it everytime. 

Im open to suggestions.

2020-02-06 22:01 UTC, SomeguyManperson commented
The arrow has variables for its kill chance, use amount, and if it can be used to requiem a holoparasite, so changing those shouldn't be difficult

2020-02-06 22:13 UTC, boodaliboo commented
IF you die there anyways your not getting ressed I see no problem with it Gibong

2020-02-06 22:34 UTC, Hopekz commented
> The arrow has variables for its kill chance, use amount, and if it can be used to requiem a holoparasite, so changing those shouldn't be difficult

Ye what Theos said because those variables already exist creating a child with those things changed should take you a few seconds + be the less lazy fix

2020-02-07 04:05 UTC, Ratvar commented
<Chance to die if used> is a lazy fix because there is a chance you *dont* die and then are free to abuse something OP. Just like with die of fate, there was a chance you would not get a wizard, uplink or a slave. Did not matter if you can get a wizard, uplink or a slave at all, and so it is removed.
If it dissuades people from using it, then it just becomes rarer, not better.
And then assistants who die just go ghostrole, it is not a severe downside those days.

2020-02-13 13:28 UTC, merged