slings now pack a punch when ascended
yogstation13/Yogstation pull request #7783
Opened 2020-02-08 05:03 UTC by ynot01

### Intent of your Pull Request

60 -> 200

#### Changelog

:cl:  
tweak: Shadowling ascendant melee damage increased
/:cl:

2020-02-08 05:10 UTC, monster860 commented
thats a lot of damage

2020-02-08 05:14 UTC, Hopekz commented
![one-punch-man-season-2-episode-6](https://user-images.githubusercontent.com/24533979/74079618-a449a780-49ff-11ea-902e-19a5011c9526.jpg)

2020-02-08 12:33 UTC, TheGamerdk commented
Why

2020-02-08 12:56 UTC, alexkar598 commented
Make it less tho, like 140, it's more fun to two shot people than one shot

2020-02-08 18:27 UTC, Hopekz commented
If we're keeping it at 200 change it to something like 2000 since it 1shots anyway might as well demolish someone unless you're doing Alex's 2 shot

2020-02-09 20:07 UTC, TheGamerdk commented
smh, they already have abilities for AOE lightning, instant gib, instant enthrall

2020-02-09 20:31 UTC, Hopekz commented
> smh, they already have abilities for AOE lightning, instant gib, instant enthrall

+1 to this
Hitting someone twice is now actually an inconvenience compared to literally making them instantly explode.

Not sure why we're going with 2 punches but its not a "bad" thing IMO just didn't make too much sense. 

Maybe it's for the ascended that like to play around with their prey? The unchanged punch did this well already.

2020-02-10 16:50 UTC, Darkstick commented
I'd say remove their ability to instant gib and make punching gib instead. Punching someone that hard sounds more satisfying to me than just staring at them so hard they implode.

2020-02-10 19:10 UTC, ShadowDeath6 commented
I prefer it as it is now since they get crippled by the slow and have to hobble around at like 30% movespeed while I laugh at them

2020-02-13 19:20 UTC, Idinuum commented on yogstation/code/modules/antagonists/shadowling/ascendant_shadowling.dm
> +	melee_damage_lower = 160 //Was 35, buffed
```suggestion
	melee_damage_lower = 160 //Was 60, buffed
```

2020-02-13 19:21 UTC, nesisknesis requested changes

2020-02-13 19:21 UTC, Idinuum commented on yogstation/code/modules/antagonists/shadowling/ascendant_shadowling.dm
> +	melee_damage_lower = 160 //Was 35, buffed
```suggestion
	melee_damage_lower = 160 //Was 60, buffed
```

2020-02-13 19:33 UTC, merged