Made 25 external airlocks work with Monstermos
yogstation13/Yogstation pull request #7821
Opened 2020-02-15 04:00 UTC by Hopekz

**This should also fix weird artifacts such as air getting all the way to bar when someone opens the escape external airlock.**

**Examples:**
-----
![1](https://user-images.githubusercontent.com/24533979/74581448-33f9d380-4f75-11ea-927d-84b0f8c83229.PNG)
![2](https://user-images.githubusercontent.com/24533979/74581449-35c39700-4f75-11ea-8a26-529b52061a1e.PNG)
![3](https://user-images.githubusercontent.com/24533979/74581450-36f4c400-4f75-11ea-9a4a-fb52fde66e13.PNG)
![4](https://user-images.githubusercontent.com/24533979/74581452-3825f100-4f75-11ea-971f-f2fe89237fd5.PNG)
![5](https://user-images.githubusercontent.com/24533979/74581453-39571e00-4f75-11ea-90c3-ae6bc87f1424.PNG)

#### Changelog

:cl:  
bugfix: Made 25 external airlocks work with Monstermos by adding air vents.
/:cl:

2020-02-15 04:02 UTC, Ktlwjec1 commented
Make sure all solars have air alarms!

2020-02-15 04:17 UTC, monster860 commented
I dont think this will help.

2020-02-15 04:57 UTC, Hopekz commented
> I dont think this will help.

This is mainly to stop people from getting yeeted into space when exiting an external airlock.

2020-02-15 05:02 UTC, monster860 commented
yeah like I said if you want to solve the problem, you want to install cycling airlocks. I recommend taking a look at minskystation, that station has cycling airlocks for some reason.

2020-02-15 15:43 UTC, MegaEmpirical commented
How does this help?

2020-02-15 16:03 UTC, deathslayer2481 commented
Scream to be heard

2020-02-18 04:34 UTC, Ktlwjec1 requested changes
This doesn't fix the issue, but I'm fine to merge it if you want after:

- Maintenance needs air alarms where the new vents are.
- Space pipe needs removing where the arrivals shuttle lands.
- Obviously merge conflict too.

2020-02-20 17:47 UTC, Firewolf34 commented
It's a good start to fixing the external airlock problems.

2020-02-20 17:48 UTC, MegaEmpirical commented
@firewolf34 how

2020-02-23 23:03 UTC, Hopekz commented
#7874 does what this PR was trying to do and is a better solution overall. Closing

2020-02-23 23:04 UTC, closed without merging