Infection Gamemode
yogstation13/Yogstation pull request #7869
Opened 2020-02-23 02:34 UTC by TheGamerdk

2020-02-23 02:34 UTC, TheGamerdk commented
51 commits

2020-02-23 02:34 UTC, Darkstick commented
What the heck is this, put a description on it you butt

2020-02-23 02:35 UTC, TheGamerdk commented
no

2020-02-23 02:35 UTC, TheGamerdk commented
merge it and find out

2020-02-24 04:06 UTC, Hopekz commented on code/modules/antagonists/blob/infection_admin.dm
> +	set name = "Start Blob Victory Timer"
```suggestion
	set name = "Make the Blob dab on everyone"
```

2020-02-24 04:06 UTC, Hopekz commented on code/modules/antagonists/blob/infection_admin.dm
> +	set name = "Give Factory Upgrade Points"
```suggestion
	set name = "Give Epic Gamer Upgrade Points"
```

2020-02-24 05:06 UTC, ShadowDeath6 commented
interesting pull request

2020-02-24 09:07 UTC, ThatLing requested changes
Add a description and changelog or I will close this

2020-02-24 11:34 UTC, closed without merging

2020-02-25 07:25 UTC, Whoneedspacee commented
based