adds a new reagant "america juice" (temporary name till i can think a new one up) that you can obtain by grinding the freedom hardsuit and other things in the future which can be used to make a heart of freedom
yogstation13/Yogstation pull request #7911
Opened 2020-03-04 01:34 UTC by boodaliboo

### Intent of your Pull Request
this pr adds a new reagent which currently its only use is to make a heart of freedom. you pour it on a normal heart to get it.

currently the only way to obtain this chemical is to grind a eagle hardsuit and helmet
#### Changelog

:cl:  
rscadd: Added a new chemical and a way to obtain the heart of freedom 
tweak: tweaked some text in heart of freedoms messages    
/:cl:

2020-03-04 14:05 UTC, CMOisLing commented
Could you not put the description in the title?

2020-03-05 00:10 UTC, boodaliboo commented
The Pr is done except for the chemical nans

2020-03-06 02:22 UTC, boodaliboo commented
the only part of this thats wip is the chems name

2020-03-07 04:38 UTC, SomeguyManperson commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +/datum/reagent/drying_agent/reaction_obj(obj/O, reac_volume)
Bruh

2020-03-07 04:39 UTC, SomeguyManperson commented
Consult with the totally important lore team on whether America juice is a lore friendly name

2020-03-07 06:11 UTC, boodaliboo commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +/datum/reagent/drying_agent/reaction_obj(obj/O, reac_volume)
whoops

2020-03-11 15:53 UTC, boodaliboo commented
Why does this have stale I updated it yesterday

2020-03-12 21:31 UTC, Ktlwjec1 requested changes
See if you can find a better name but if not this is good enough for now, suggest asking about in the wiki/mentor channel or OOC for ideas. Also needs a full stop after the description!!

2020-03-13 03:44 UTC, boodaliboo commented
ok will do

2020-03-23 19:14 UTC, boodaliboo commented
im not sure whats needing to be done as when ive asked people said my name for it was ok

2020-03-25 04:07 UTC, Hopekz requested changes

2020-03-25 04:07 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	name = "America Juice"
```suggestion
	name = "Freedom Juice"
```
Here is a "suggestion" on the name.
I'm not a part of the lore team but I think America doesn't exist in ss13

2020-03-25 19:21 UTC, boodaliboo commented
YHES

2020-03-28 03:52 UTC, alexkar598 commented
Going to close this because anyone grinding up their suit is a fucking moron and they probably wont exists

2020-03-28 03:52 UTC, closed without merging