Achievement Get Part 3 - Cargo Achievements
yogstation13/Yogstation pull request #7917
Opened 2020-03-05 00:06 UTC by Altoids1

![image](https://user-images.githubusercontent.com/29939414/75934686-d0abe480-5e42-11ea-8365-3f89fd65b43f.png)

This adds four more achievements, of the Cargonian variety.

#### Changelog
:cl:  Altoids
rscadd: Cargo now has a couple achievements of their own!
/:cl:

2020-03-05 00:09 UTC, boodaliboo commented
Assistant

2020-03-09 14:56 UTC, Altoids1 commented
# Ready for review.

2020-03-25 04:09 UTC, Hopekz approved these changes

2020-03-25 19:09 UTC, alexkar598 requested changes

2020-03-25 19:09 UTC, alexkar598 commented on code/modules/economy/account.dm
> +				break
You can't assume there aren't going to be any duplicated names due to genetic fuckery or something like that
```suggestion
```

2020-03-25 19:09 UTC, alexkar598 commented on code/modules/awaymissions/bluespaceartillery.dm
> +			SSachievements.unlock_achievement(/datum/achievement/cargo/bsa, usr.client)
This is an admin only version, not the cargo not
```suggestion
		message_admins("[ADMIN_LOOKUPFLW(usr)] has launched an artillery strike.")
```

2020-03-25 19:09 UTC, alexkar598 commented on code/modules/economy/account.dm
> +				SSachievements.unlock_achievement(/datum/achievement/cargo/bourgeois, M.client)
Please add a check within the unlock_achievement proc to check if the client exists, its too easy to forget a ``if(whatever.client)``

2020-03-28 03:29 UTC, merged