Adds pixel shifting
yogstation13/Yogstation pull request #7922
Opened 2020-03-06 10:13 UTC by monster860

originally an ERP pr on citadel. Certain people expressed interest in having it here. Not sure if it was sarcasm but I made a PR anyways. <https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11349/files>

:cl:  
use CTRL+SHIFT + direction to shift your pixel
/:cl:

2020-03-06 10:21 UTC, Hopekz commented
> originally an ERP pr on citadel. Certain people expressed interest in having it here. Not sure if it was sarcasm but I made a PR anyways. https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11349/files
> 
> 
> use CTRL+SHIFT + direction to shift your pixel
> /

Now you can lean against bartops and tables..and walls...and other things!

2020-03-06 10:25 UTC, Potototatoh commented
hover*

2020-03-06 11:36 UTC, deathslayer2481 commented
Urge to Purge intensifies.

2020-03-06 12:55 UTC, ThatLing commented
PR doesn't work btw

2020-03-06 12:56 UTC, ThatLing requested changes
``code/modules/keybindings/bindings_mob.dm`` isn't used, read the first line of the file. Also, your changelog is broken

2020-03-06 15:03 UTC, LoliconSlayer commented
Where's the fucking fetish content label

2020-03-06 18:11 UTC, overlord12345 commented
What dose this do im too dumb to understand

2020-03-06 18:16 UTC, Hopekz commented
> What dose this do im too dumb to understand

This allows you to shift your character sprite 16 pixels in any direction so you can be closer to something that is not on your tile or you can co-exist on the same tile potentially.
Didn't test this yet but its a "why not" feature from me. 
Adds functionality and I can't see why not.

2020-03-06 18:59 UTC, ThatLing commented on yogstation/code/modules/keybindings/bindings_mob.dm
> +				if(client.keys_held["Shift"])
```
user.prefs.bindings.isheld_key("Shift")
```

2020-03-07 11:02 UTC, ThatLing approved these changes

2020-03-14 17:22 UTC, merged