Buffs AI doorknob.
yogstation13/Yogstation pull request #799
Opened 2018-05-12 14:36 UTC by AsV9

You can now alt click a door to request the AI open it, but only every ten seconds to prevent spam.

That's about it.

HippieStation/HippieStation#3898 btw

2018-05-12 15:11 UTC, AsV9 commented
i realized I did an oopsie, don't merge this before I fix

2018-05-13 20:57 UTC, Kmc2000 commented
MANE HOW HARD IS IT TO DO MOD U LAR CODE

2018-05-14 17:01 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b requested changes

2018-05-14 17:01 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on yogstation/code/modules/mob/living/silicon/ai/ai.dm
> +	var/obj/machinery/door/airlock/A = locate(href_list["remotedoor"]) in GLOB.machines
Href exploit here, add `if(src != usr) return` to check if it was the AI who called this

2018-05-27 19:49 UTC, ShadowDeath6 commented on yogstation/code/game/machinery/doors/airlock.dm
> +		to_chat(user, "<span class='info'>The airlock's spam filter is blocking your request. Please wait at least 10 seconds between requests.</span>")
I would remove all of the feedback here except for the one that says request sent when it is successful, I don't think it's needed to display a message for every single thing

2018-06-03 20:15 UTC, closed without merging

2018-06-03 20:15 UTC, nichlas0010 commented
open it if you're actually working on it