Adds the song "Sole Survivor" by Blue Öyster Cult.
yogstation13/Yogstation pull request #8055
Opened 2020-03-28 05:48 UTC by Xoxeyos

The link for the song is here, for your enjoyment. https://www.youtube.com/watch?v=nRjLv1L0WF8

🆑
rscadd: Adds the Song "Sole Survivor" to the title screen.
/🆑

2020-03-28 05:51 UTC, boodaliboo commented
Wouldn’t it be funny if council updated he configs for the last song update

2020-03-28 05:53 UTC, Hopekz approved these changes

2020-03-28 16:41 UTC, swissloaf commented
> Wouldn’t it be funny if council updated he configs for the last song update

all songs are through the code now, not the config

2020-03-28 21:36 UTC, boodaliboo commented
> > Wouldn’t it be funny if council updated he configs for the last song update
> 
> all songs are through the code now, not the config

i was a dumbass somehow my song pr that got merged got reverted

2020-03-30 17:42 UTC, alexkar598 commented on yogstation/code/controllers/subsystem/ticker.dm
> +		"https://www.youtube.com/watch?v=nRjLv1L0WF8",                      // Blue Oyster Cult: Sole Survivor
```suggestion
		"https://www.youtube.com/watch?v=nRjLv1L0WF8",                      // Blue Oyster Cult - Sole Survivor
```

2020-03-30 17:42 UTC, alexkar598 requested changes
see above

2020-04-01 03:44 UTC, alexkar598 approved these changes

2020-04-02 16:59 UTC, Idinuum commented
ill leave it in for a week or so

2020-04-02 16:59 UTC, merged