Preternis Bug Fixes&Balance Changes(alexkar is my wife edition)
yogstation13/Yogstation pull request #8084
Opened 2020-03-31 18:39 UTC by Codeatmos

### Intent of your Pull Request

Preternis is shit balance wise and its outdated and dumb stinky 
<unironic time>
###Changes&reasons
Most Preternis upsides are INCREDIBLY situational outside of radiation and night vision so I will make this quick
Damage modifiers: Were not justified by its upsides,along with it basically making lasers/welders insta-kill
Welding Fuel,Teslium,Oil
Welding fuel mechanic was terrible,you are trading damage types,so I decided to make it heal a tiny amount of brute and deal NO toxin damage.(because Preternis had no brute heal chem.
Preternis don't take more damage from cold now,why you ask?
**monstermos is a shitty fucking system and Preternis downsides become way more common for the original intention of a niche fucking downside**
Fuck Virus resistance boost,we don't need preternis to make a superweapon from being near others its literally the hygine update but worse.
###Bugs
Teslium,Oil and Welding fuel were actually bugged for preternis and only hurt you,WHO KNEW!

###Future Plans
Future changes might include their lore to be more robot-like along with speech and maybe downsides to low HP similar to borgs with a new UNIQUE upside of WIRELESSLY INTERACTING WITH CONSOLES(powerful on paper,but not really I think.)

As always if you feel anything is unbalanced suggest away.

I'm a bit sleep deprived so sorry if I missed anything just say if you need me to explain anything outside of the strange commit names and commits that I did because git is a fucking shitty platform
#### Changelog

:cl:  
bugfix: Preternis chems should work properly now. 
tweak: Preternis is no longer immune to radiation,slight plasma leaks and uses a normal amount of 02 along with not taking as much damage as before and new CC regulations have made their lungs a bit more tolerant to cold temps
/:cl:

2020-03-31 18:40 UTC, Code611 commented
powercreep,based and banned.

2020-03-31 18:47 UTC, ReddTheDragon commented
oh god who taught code how to code

2020-03-31 18:50 UTC, Moja10 commented
I am council and I approve of code

2020-03-31 19:43 UTC, Hopekz requested changes
Can you avoid commenting on portions that you didn't edit?

Referring to:
![image](https://user-images.githubusercontent.com/24533979/78068217-a247f900-735d-11ea-9210-92fdaaa21b70.png)
![image](https://user-images.githubusercontent.com/24533979/78068254-b0961500-735d-11ea-96bc-095dc1f176d8.png)
![image](https://user-images.githubusercontent.com/24533979/78068303-c4417b80-735d-11ea-8da2-b76a2c7aedb5.png)

Also::
There is no point to leave this comment in the code now that this is getting removed.
Only comment (clarify) on things that are pertinent to the functionality of code.
Example:
![image](https://user-images.githubusercontent.com/24533979/78068395-f5ba4700-735d-11ea-8883-b8a2ed80a3bc.png)

The codebase isn't your personal blog.

2020-03-31 20:07 UTC, alexkar598 commented
What hopek said, its my personal blog, not yours

2020-03-31 20:19 UTC, Code611 commented
Sorry, Tortise git was being a bitch and I needed to change a couple of things just for it to know the file exists.

2020-03-31 20:41 UTC, alexkar598 requested changes

2020-03-31 20:41 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	return TRUE //more like stupid ternis lol
Return TRUE in the code that processes it for preternis instead of this

2020-03-31 20:41 UTC, alexkar598 commented on yogstation/code/modules/mob/living/carbon/human/species_types/preternis/organs.dm
> +	heat_level_3_threshold = 600 //HALP MY LUNGS ARE ON FIRE+fuck cold because monstermos and its consequences for the human race have been a disaster for preternis
Yeet those comments please.

2020-03-31 20:41 UTC, alexkar598 commented on yogstation/code/modules/mob/living/carbon/human/species_types/preternis/preternis.dm
> +	inherent_traits = list(TRAIT_NOHUNGER) //im sorry atmos,forgive me but it MUST BE DONE!
Yeet the comment
```suggestion
	inherent_traits = list(TRAIT_NOHUNGER)
```

2020-03-31 20:41 UTC, alexkar598 commented on yogstation/code/modules/mob/living/carbon/human/species_types/preternis/preternis.dm
> +	 // Remember the Virus boost? Me neither you powergaming FUCK.
Yeet this.

2020-03-31 20:41 UTC, alexkar598 commented on yogstation/code/modules/mob/living/carbon/human/species_types/preternis/preternis.dm
> +	screamsound = 'goon/sound/robot_scream.ogg' //haha stole from goon lol
And this too

2020-03-31 20:41 UTC, alexkar598 commented on yogstation/code/modules/mob/living/carbon/human/species_types/preternis/preternis.dm
>  	. = ..()
```suggestion
	..()
	. = FALSE
```

2020-03-31 20:41 UTC, alexkar598 commented on yogstation/code/modules/mob/living/carbon/human/species_types/preternis/preternis.dm
> +		H.adjustBruteLoss(-0.5*REAGENTS_EFFECT_MULTIPLIER,FALSE,FALSE, BODYPART_ANY) //Preternis can have a little bit of brute healing,as a treat.
```suggestion
		H.adjustBruteLoss(-0.5*REAGENTS_EFFECT_MULTIPLIER,FALSE,FALSE, BODYPART_ANY) //Preternis can have a little bit of brute healing,as a treat.
		. = TRUE
```

2020-03-31 20:41 UTC, alexkar598 commented on yogstation/code/modules/mob/living/carbon/human/species_types/preternis/preternis.dm
> +		H.adjustBruteLoss(-0.5*REAGENTS_EFFECT_MULTIPLIER,FALSE,FALSE, BODYPART_ANY) //Preternis can have a little bit of brute healing,as a treat.
Replace the return FALSE at the end with return

2020-03-31 22:13 UTC, Readystorm546 commented
Preternis is my main so can i get a TLDR of what you removed and what you added. I find this post very confusing

2020-03-31 22:19 UTC, Sniblet commented
> Preternis is my main so can i get a TLDR of what you removed and what you added. I find this post very confusing

the changelog is your tl;dr

> bugfix: Preternis chems should work properly now.
> tweak: Preternis is no longer immune to radiation,slight plasma leaks and uses a normal amount of 02 along with not taking as much damage as before and new CC regulations have made their lungs a bit more tolerant to cold temps

so far, and he says he plans to do more, he's removing a bunch of the environmental resistances and the damage vulnerabilities that make preternis unique
i hate it, and he knows it
radiation immunity is probably coming back, but his main focus is making combat more interesting for them than only being able to take one buckshot before die

2020-04-01 03:44 UTC, alexkar598 approved these changes

2020-04-03 13:23 UTC, Moggram commented
(A angry preterni kicks in the door)
![1397748704002](https://user-images.githubusercontent.com/63105585/78364460-790cb000-758b-11ea-8a97-b896c20ec34d.jpg)


Look here fuck'o. Some of us like play a hard mode race and you removing the damage modifiers is just a "I dead Q.Q". What is next, are you going to make it so Plasmamen don't need special jumpsuit and helmet in order to avoid burning or because its hard to clone them?

What is the point of have cool cybernetic lungs if they are just like your meat bags lungs? Removing of lung cold damage is bull shit. If you are mad about monstermos go yell at him and don't nerf us for it. Now I have to take a o2 tank when I am mining on lavaland and my air will run out quickly if I am in space. Thanks for that by the way. 

If you want to help us Preternis, here is a list of bugs you can fix and not get the nerf hammer dropped on us. 


Medbay is a nightmare.

DNA (Preternis have DAN and then we don't.)
►Some how we can be Cloned whit out DNA. (I don't think we should we be able to or pop us out as a human.)
►We can DNA lock Exosuits and PAI can ask for DNA.
►After you get cloned, your DNA locked Exosuits and PAI will no longer see you as the owner.
►We can some how can get cellular damage.


Cryogenics Tube (A.K.A. Limbo)
►Being cold inside the tube does not do damage.
►'IF' some one does lets you out, it will. (Pick one)


Medibot
►Stop injecting me over and over again.
►For the love of god, stop following me round the station when I have ten brute damage.


Sleeper beds (Not a bug, but a gripe)
►If you are in crit, it will only let Epinephrine be used. Now you get to lay there as the dum ass humans inject over and over again. (Can you make it so the Sleeper bed says what races person is in the window.)


-----------------------------------


And now on to odd things about power that I have ran into.


Borg Recharging Stations
►The stations don't recharge my power cell.
►When Upgrade, dose not repair us. (It be nice if it did. Just say'n)


Power CONSUME protocol
►You don't need any arms or legs to eat power.
►If you have any type of glove on and you are EMP, stuned or sleeping. It will say "gloves prevent electrical contact." But if you don't have any on, it will some times let you eat power. (Its a hard bug to pin down and you don't come across all that often.)
►You can still eat power if you are handcuffed (Did it one time to a secborg and he almost killed me for it because he thought I got out of the cuffs.)


Ninja Prison (Not a bug, but a gripe)
►There is no easy way to get power. (You can get the power cell out of the Borg Recharging Station or grow a lot of food in hydroponics)

There are more bugs, but I can't remember them right now.

2020-04-04 20:36 UTC, Codeatmos commented
> (A angry preterni kicks in the door)
> ![1397748704002](https://user-images.githubusercontent.com/63105585/78364460-790cb000-758b-11ea-8a97-b896c20ec34d.jpg)
> 
> Look here fuck'o. Some of us like play a hard mode race and you removing the damage modifiers is just a "I dead Q.Q". What is next, are you going to make it so Plasmamen don't need special jumpsuit and helmet in order to avoid burning or because its hard to clone them?
> 
> What is the point of have cool cybernetic lungs if they are just like your meat bags lungs? Removing lung cold damage is bull shit. If you are mad about monstermos go yell at him and don't nerf us for it. Now I have to take a o2 tank when I am mining on lavaland and my air will run out quickly if I am in space. Thanks for that by the way.
> 
> If you want to help us Preternis, here is a list of bugs you can fix and not get the nerf hammer dropped on us.
> 
> Medbay is a nightmare.
> 
> DNA (Preternis have DAN and then we don't.)
> ►Some how we can be Cloned whit out DNA. (I don't think we should we be able to or pop us out as a human.)
> ►We can DNA lock Exosuits and PAI can ask for DNA.
> ►After you get cloned, your DNA locked Exosuits and PAI will no longer see you as the owner.
> ►We can some how can get cellular damage.
> 
> Cryogenics Tube (A.K.A. Limbo)
> ►Being cold inside the tube does not do damage.
> ►'IF' some one does lets you out, it will. (Pick one)
> 
> Medibot
> ►Stop injecting me over and over again.
> ►For the love of god, stop following me round the station when I have ten brute damage.
> 
> Sleeper beds (Not a bug, but a gripe)
> ►If you are in crit, it will only let Epinephrine be used. Now you get to lay there as the dum ass humans inject over and over again. (Can you make it so the Sleeper bed says what races person is in the window.)
> 
> And now on to odd things about power that I have ran into.
> 
> Borg Recharging Stations
> ►The stations don't recharge my power cell.
> ►When Upgrade, dose not repair us. (It be nice if it did. Just say'n)
> 
> Power CONSUME protocol
> ►You don't need any arms or legs to eat power.
> ►If you have any type of glove on and you are EMP, stuned or sleeping. It will say "gloves prevent electrical contact." But if you don't have any on, it will some times let you eat power. (Its a hard bug to pin down and you don't come across all that often.)
> ►You can still eat power if you are handcuffed (Did it one time to a secborg and he almost killed me for it because he thought I got out of the cuffs.)
> 
> Ninja Prison (Not a bug, but a gripe)
> ►There is no easy way to get power. (You can get the power cell out of the Borg Recharging Station or grow a lot of food in hydroponics)
> 
> There are more bugs, but I can't remember them right now.

Some of this is actual valid ideas, most of it is babyrage tho
No shit I'm changing preternis you reactionary fuck,I'm going to make the combat more unique instead of 2 lasers = death buckshot = death breathing = death
Preternis is designed to be a fucking robot but doesn't feel like it at all, more of a resprite of a fucking human
I'm going to change it to uniquely interact in combat because I could literally fucking resprite preternis to human and the only difference in combat would be "he fell down due to an EMP" I'm going to change it that your body breaks before you do and that combat isn't just "oops got hurt better *You begin welding yourselfx20!*" and also make preternis more fucking synthetic like through flavortext and a upside that is replacing 02 **Wireless Interaction with most consoles**      
If preternis was a fucking hardmode game,I would prefer my hardmode have more depth then "enemies kill u in 1 hit lol"

2020-04-04 21:02 UTC, jcatjmeow commented
I like the bug fixes I don't like perentis still having rad immunity when that's the nichest of upsides only ever used by one job to grief

2020-04-04 21:07 UTC, Codeatmos commented
Alright,most of the preternis mains dont like it so no more preternis,go home.

2020-04-04 21:07 UTC, closed without merging