Ports the B.E.P.I.S
yogstation13/Yogstation pull request #8118
Opened 2020-04-05 02:03 UTC by Bastian0930

### Intent of your Pull Request
Ports the bepis. Tested all sprites and the bepis, from what I know. This is for a bounty, but I will fix bugs if pointed out. Pretty sure I used mapmerge correctly, but call me out if I'm wrong. I'm willing to improve the **port** if pointed in the right direction. I won't be balancing, however! The difference from the last pr is the problemsome maps have been reverted to what they are now. The only one that starts with one is yogstation, not any other maps.
Original link: https://github.com/tgstation/tgstation/pull/48040
#### Changelog

:cl:  
rscadd: The RnD department has been gifted a state-of-the-art new research tool, the B.E.P.I.S. by Nanotrasen's Venture Capital Labs, after repeatedly wasting all of their funds. Hopefully you'll find a... wiser use for it.
rscadd: A new Tech Node can be unlocked through proper investment with the B.E.P.I.S.
rscadd: In an unrelated piece of news, a deer was recently found to be the culprit of Nanotrasen Venture Capital Labs's onboard nuclear failsafe device detonating. Yes, we're sure it wasn't the Syndicate this time. Yes, we wish we were joking too.
bugfix: Fixes a small bug with tech disks containing hidden nodes not researching.
/:cl:

2020-04-05 02:03 UTC, boodaliboo commented
:)

2020-04-05 02:18 UTC, SynnGraffkin commented
Bepis is honestly a waste of space. The items it provides could just as well be unlocked with a destructive analyzer instead of being force behind a paywall where the meta is just "pay 5500" until you get all the few nodes that are available from it.

2020-04-05 02:23 UTC, boodaliboo commented
> Bepis is honestly a waste of space. The items it provides could just as well be unlocked with a destructive analyzer instead of being force behind a paywall where the meta is just "pay 5500" until you get all the few nodes that are available from it.

no

2020-04-05 03:47 UTC, Bastian0930 commented
> Bepis is honestly a waste of space. The items it provides could just as well be unlocked with a destructive analyzer instead of being force behind a paywall where the meta is just "pay 5500" until you get all the few nodes that are available from it.

I see where you are coming from, however I'm not balancing this.

I got paid to port, so that's what I'll do.

2020-04-09 17:07 UTC, FLME commented
cool

2020-04-12 04:45 UTC, Bastian0930 commented
Huh, bee makes me fix the conflicts. Oh well, less work for me.

2020-04-12 09:44 UTC, boodaliboo commented
you may want to fix the dmis

2020-04-18 22:58 UTC, alexkar598 requested changes

2020-04-18 22:58 UTC, alexkar598 commented on code/game/objects/items/RCD.dm
> +					user.Beam(A,icon_state="light_beam",time=15)
There is no such icon here

2020-04-18 22:58 UTC, alexkar598 commented on code/game/objects/items/RCD.dm
> +					user.Beam(A,icon_state="light_beam",time=15)
same as above, no such icon

2020-04-18 22:58 UTC, alexkar598 commented on code/game/objects/items/RCD.dm
> +					user.Beam(A,icon_state="light_beam",time=15)
no such icon

2020-04-18 22:58 UTC, alexkar598 commented on code/game/objects/items/airlock_painter.dm
> +			stored_color = selected_color
This is unsanitized input, verify that params["decals"] and params["colors"] contains valid selections

2020-04-18 22:58 UTC, alexkar598 commented on code/game/objects/items/airlock_painter.dm
> +	icon_state = "paint sprayer"
needless override

2020-04-18 22:58 UTC, alexkar598 commented on code/game/objects/items/airlock_painter.dm
> +	item_state = "paint sprayer"
sprite names shouldn't contain spaces

2020-04-18 22:58 UTC, alexkar598 commented on code/game/objects/items/devices/polycircuit.dm
> +	if(!user.get_inactive_held_item() == src)
```suggestion
	if(user.get_inactive_held_item() != src)
```

2020-04-18 22:58 UTC, alexkar598 commented on code/game/objects/items/devices/polycircuit.dm
> +	var/mob/living/carbon/human/H = user
You can't assume everyone with hands is human, what if xenos or monkeys tries to use it?

2020-04-18 22:58 UTC, alexkar598 commented on code/game/objects/items/devices/polycircuit.dm
> +	var/chosen_circuit = "airlock"
These can be scoped to the attack_hand proc, no need to have them on the item

2020-04-18 22:58 UTC, alexkar598 commented on code/game/objects/items/devices/polycircuit.dm
> +			if(!src || QDELETED(src))//Sanity Check.
```suggestion
			ifQDELETED(src))//Sanity Check.
```

Qdeleted already checks for !X

2020-04-18 22:58 UTC, alexkar598 commented on code/modules/clothing/gloves/color.dm
> +	qdel(src) //loose nodrop items bad
Use the DROPDEL flag instead of a snowflake check

2020-04-18 22:58 UTC, alexkar598 commented on code/modules/clothing/gloves/color.dm
> +		var/mob/living/carbon/U = user
Here you have between 1 and 3 problems:

user is type mob/living/carbon instead of mob/living
user isnt checked if it exists/is a carbon
U is needlessly assigned to user instead of simply using the user value

2020-04-18 22:58 UTC, alexkar598 commented on code/modules/paperwork/photocopier.dm
> +	max_charges = 200
The large one has reagents but not the extreme one?

2020-04-18 22:58 UTC, alexkar598 commented on code/modules/research/bepis.dm
> +	deposit_value = banking_amount
```suggestion
	var/deposit_value = banking_amount
```

2020-04-19 22:28 UTC, Bastian0930 commented on code/game/objects/items/RCD.dm
> +					user.Beam(A,icon_state="light_beam",time=15)
As I go through this, I'll place comments on what i'm fixing.

This will be first, just after I fix some other code I was working on.

2020-04-25 22:45 UTC, alexkar598 commented on code/game/objects/items/devices/polycircuit.dm
> +			ifQDELETED(src))//Sanity Check.
```suggestion
			if (QDELETED(src))//Sanity Check.
```

2020-04-28 19:54 UTC, ArcaneMusic commented on code/modules/paperwork/photocopier.dm
> +	max_charges = 200
The extreme toner cartridge is admin-spawn only, and as such it's not strictly necessary, but if you want you could always mover over the grind results of the large toner cartridge.

2020-04-28 20:02 UTC, ArcaneMusic commented
Not sure how I feel about something that I coded for free being ported for profit, considering this is the first I'm hearing about this.
You can go ahead with this, but I'd have REALLY appreciated being told about this beforehand.

2020-04-29 22:32 UTC, Bastian0930 commented
I apologise, @ArcaneMusic . Bounty owner should have probably talked to you.

2020-04-30 08:06 UTC, boodaliboo commented
> Not sure how I feel about something that I coded for free being ported for profit, considering this is the first I'm hearing about this.
> You can go ahead with this, but I'd have REALLY appreciated being told about this beforehand.

i payed for it because i previously tried to port it and failed

2020-04-30 21:03 UTC, Bastian0930 commented on code/modules/paperwork/photocopier.dm
> +	max_charges = 200
I don't think a admin only item needs grind results, @alexkar598 . Committing what I have now in a bit.

2020-05-01 16:22 UTC, Bastian0930 commented on code/modules/clothing/gloves/color.dm
> +		var/mob/living/carbon/U = user
Most of the rest are done, fixing this. The security flaw, however, is not done.

2020-05-01 16:27 UTC, Bastian0930 commented on code/game/objects/items/devices/polycircuit.dm
> +	var/mob/living/carbon/human/H = user
This handicaps a xeno as currently, you have to put them on after spraying them on. Monkeys also have no hand slot.

2020-05-04 02:29 UTC, Bastian0930 commented
Holy shit this is draining. First off, fuck the gloves. If I wasn't being paid to merge this, I'd skip over them. However, I'm having problems relating to the gloves not equiping automatically. I'll see what I can do to fix it.

2020-05-04 05:55 UTC, LemonInTheDark commented
> 
> 
> Holy shit this is draining. First off, fuck the gloves. If I wasn't being paid to merge this, I'd skip over them. However, I'm having problems relating to the gloves not equiping automatically. I'll see what I can do to fix it.

The spray-ons? I have great pity for you.

2020-05-04 06:07 UTC, yeeyeh commented
hi, creator of the gloves from hell here. sorry for shitcode but it was the first thing i ever made in byond, but i'd be glad to offer some help. what do you mean by gloves not equipping automatically?

2020-05-07 02:41 UTC, Bastian0930 commented
@yeeyeh In this specific portion of the code, it litterally will not autoequip them on yog when you spray them on. I'm unsure why. I keep looking at this, trying to fix it, losing motivation after a long while, taking a break for a day, then coming back to try to fix it again.

2020-05-07 03:17 UTC, Bastian0930 commented
I'm going to attempt to pay this back to the bounty author. On top of the original author wanting to be asked first, there's too much shitcode to fix for 15 bucks.

2020-05-07 03:44 UTC, closed without merging