Pet collar sounds
yogstation13/Yogstation pull request #8119
Opened 2020-04-05 02:25 UTC by Darkstick

### Intent of your Pull Request

I wanted collars to make little bell noises to maximize puppy realism. Also works on people.

Mechanically similar to clown shoes, a bell noise plays every time whatever's wearing the collar takes 3 steps.

#### -download links to both sound effect used-
https://discordapp.com/channels/326011850309500928/326011850309500928/696182584295555183

https://discordapp.com/channels/326011850309500928/326011850309500928/696182615295656112

#### Changelog

:cl:  
soundadd: collar bell noises
/:cl:

2020-04-05 02:33 UTC, Marmio64 commented
Degenerates like you belong on a cross.

2020-04-05 03:50 UTC, Readystorm546 commented
" Also works on people.

2020-04-05 10:15 UTC, overlord12345 commented
There is no bell on the collar very unrealistic

2020-04-05 20:26 UTC, Hopekz approved these changes
nice

2020-04-07 18:10 UTC, Hopekz approved these changes
After changes

2020-04-09 17:07 UTC, FLME commented
uh oh

2020-04-11 00:33 UTC, alexkar598 requested changes

2020-04-11 00:33 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/friendly/pet.dm
> +				pcollar.step_action()
Early returns are generally prefered, also whats up with the mobility_flags there?
```suggestion
	if(!pcollar)
		return
	if (!(mobility_flags & MOBILITY_STAND))
		return
	if(loc != NewLoc)
		return
	if(!has_gravity(loc))
		return
		
	pcollar.step_action()
```

2020-04-11 00:38 UTC, alexkar598 commented
The sound number 2 is kinda weird IMO when you listen to it by itself

2020-04-14 11:05 UTC, HomocidlePancakes commented
I disapprove.

2020-04-16 09:21 UTC, merged