Expands the functionality of the AFK verb, makes the Suicide verb warn important roles
yogstation13/Yogstation pull request #8123
Opened 2020-04-05 19:59 UTC by Altoids1

![image](https://user-images.githubusercontent.com/29939414/78508582-94bfb400-774d-11ea-9339-a01b52b1aeb7.png)

This is a response to this bounty: https://forums.yogstation.net/index.php?threads/5-antags-and-additional-limited-job-slots-using-the-afk-command-will-report-to-ahelp-ss13-server.21024/

## Overview

So I've tried to go a little bit above & beyond what the bounty request required, here.

The baseline would've been just to make Security and Antags do a bwoink when going AFK. I bothered to go a bit further, and add some extra functionality for some antag roles. Xenos get their own special IC message they shoot into the hivemind when going AFK, and Nukies/ERT/Deathsquad correctly shoot their messages to their correct, esoteric radio channels.

Also, attempting to suicide as an important role now gives a warning that doing so may be against the rules and that using the AFK verb is preferable. This should act as, at the very least, a soft barrier to the Captain suiciding. Regardless, there's also an entry in the admin log when the important role guy kills himself anyways, which should make noticing and responding to it easier.

## Coder Warnings

I've added a new proc, ``/mob/living/is_important()``, which returns TRUE if the player can be deemed "important to the game" programmatically. Right now it's only used by ``canSuicide()``, but I guess it could be used by something else, or expanded and complicated, as the need arises.

I want to note that *just* using ``special_role`` to determine whether someone is important (or even antag) is not sufficient; ERT and Xenos do not have a ``special_role`` AFAIK yet clearly should bwoink when going AFK. However, #8122 does indeed only use special_role, and so does not fully meet the criteria of this bounty request, per se.

## Changelog

:cl:  Altoids
rscadd: The AFK verb will now automatically ahelp if you go AFK as a Xeno, ERT, or most antagonists.
rscadd: The Suicide verb now warns people with important roles against suiciding.
/:cl:

2020-04-05 20:07 UTC, swissloaf commented
![image](https://user-images.githubusercontent.com/39781787/78508788-27148780-774f-11ea-9b2e-d7953eb20152.png)
GO GET IT ALTOIDS

2020-04-09 17:05 UTC, FLME commented
neat

2020-04-11 01:01 UTC, alexkar598 requested changes

2020-04-11 01:01 UTC, alexkar598 commented on code/modules/client/verbs/suicide.dm
> +	return TRUE
Return FALSE instead of NULL please

2020-04-11 01:01 UTC, alexkar598 commented on yogstation/code/modules/client/verbs/afk.dm
> +		"Whole round" = "My broodmembers, I must go quiet. I may never awaken during this cycle.",
this is deep

2020-04-11 01:01 UTC, alexkar598 commented on yogstation/code/modules/client/verbs/afk.dm
> +					channels = list(".y",".c") // Y for.... Centcom, of course!
Admins need to be alerted

2020-04-11 01:01 UTC, alexkar598 commented on yogstation/code/modules/client/verbs/afk.dm
> +			to_chat(src, "<span class='danger'>Admins will not be automatically alerted, because you are not in a critical station role.</span>")
```suggestion
			to_chat(src, "<span class='danger'>Admins will not be automatically alerted, because you do not seem to be in a critical station role.</span>")
			log_message("is now AFK for [time]", LOG_OWNERSHIP)
```

2020-04-11 01:01 UTC, alexkar598 commented on yogstation/code/modules/client/verbs/afk.dm
> +			adminhelp("I need to go AFK as '[important_role]' for duration of '[time]' [reason ? " with the reason: '[reason]'" : ""]")
```suggestion
			adminhelp("I need to go AFK as '[important_role]' for duration of '[time]' [reason ? " with the reason: '[reason]'" : ""]")
			log_message("is now AFK for [time] [reason ? " with the reason: '[reason]'" : ""]", LOG_OWNERSHIP)
```

2020-04-18 18:01 UTC, merged