Revival surgery no longer requires research
yogstation13/Yogstation pull request #8125
Opened 2020-04-06 18:34 UTC by SomeguyManperson

### Intent of your Pull Request

The revival surgery is stupid underused, it used to be important for fixing bodies past the defib timer but now that organs also decay it'd only be useful if you needed to revive someone in a scenario where you
A: have no cloning
B: have a mostly intact body, likely with decayed organs
C: have replacement organs
and D: have a full surgical setup and experimental research
by removing the technology requirement, it's now a ghetto revive usable if you can't get to a defib but have access to a stunbaton and some alcohol to even out lower surgery chances from using alternative tools.

#### Changelog

:cl:  
tweak: revival surgery is now a base surgery
/:cl:

2020-04-06 18:35 UTC, monster860 requested changes

2020-04-06 18:35 UTC, monster860 commented on code/modules/surgery/advanced/revival.dm
>  /datum/surgery/advanced/revival/can_start(mob/user, mob/living/carbon/target)
these type paths need to change to you fuck

2020-04-07 16:14 UTC, Hopekz commented
I think if our rules changed for this to be considered a "new life" to make people "forget" this may work on our server.

2020-04-09 17:03 UTC, FLME commented
sure

2020-04-11 01:12 UTC, alexkar598 commented
It fits the ability to be able to revive someone and get their memories of who killed them but at the cost of tech and resources, not a fan of this pr

2020-04-16 09:23 UTC, closed without merging