Adds world topic for !mentorwho
yogstation13/Yogstation pull request #8127
Opened 2020-04-06 18:45 UTC by swissloaf

### Intent of your Pull Request

Adds mentorwho world topic

#### Changelog

:cl:  
rscadd: Adds world topic so mentorwho can function 
/:cl:

2020-04-06 18:49 UTC, monster860 requested changes
do [mentor.key] in the square brackets instead of [mentor]

2020-04-07 18:08 UTC, Hopekz approved these changes

2020-04-09 17:02 UTC, FLME commented
cool

2020-04-11 00:15 UTC, monster860 approved these changes

2020-04-11 00:15 UTC, merged