Trip emote
yogstation13/Yogstation pull request #8134
Opened 2020-04-08 19:18 UTC by Darkstick

### Intent of your Pull Request

By saying *trip, you will now fall over! It does the same effects as being slipped.
With this exciting new addition, you will now be able to:

- Do more RP! (please)
- Replicate all sorts of cute shojo scenes!
- Have a cool way to stop chasing someone without it being awkward!
- Faceplant!
- Look clumsy!
- Smash your face!
- Frame the clown for slipping you and watch as the rest of the security team beats them!

And so much more!
Tie your shoes together and hurt yourself today!

#### Changelog

:cl:  
rscadd: Trip emote
/:cl:

2020-04-08 20:08 UTC, ReddicusDragon requested changes
"trips and fall!" should be "trips and falls!"

2020-04-09 05:56 UTC, monster860 commented
What would be nice is a way to do this without having to stop, press t, and type *trip. Kinda ruins the point of tripping while chasing someone

2020-04-09 16:59 UTC, FLME commented
neat

2020-04-09 22:33 UTC, Hopekz approved these changes

2020-04-11 01:22 UTC, alexkar598 requested changes

2020-04-11 01:22 UTC, alexkar598 commented on code/modules/mob/living/emote.dm
> +	key_third_person = "trip"
```suggestion
	key_third_person = "trips"
```

2020-04-12 02:09 UTC, alexkar598 approved these changes

2020-04-12 02:09 UTC, merged