This is up for debate (Ash-walker Update)
yogstation13/Yogstation pull request #8167
Opened 2020-04-12 21:22 UTC by Readystorm546

Ashwalkers can put on shoes because they cant craft the tribal shoes but cant put it on. I think thats dumb.

Oh and there was a unnecessary comment in the file i wad looking into that "may or may not oppress lizard people" so i fixed it

:cl:   
tweak: Allows ash walkers to but on the shoes they craft
spellcheck: Also fixed a bad comment
/:cl:

2020-04-12 21:32 UTC, FLME commented
good

2020-04-12 23:20 UTC, overlord12345 commented
would be better if you changed the shoes they craft to fit them instead of removeing the digitigrade trait

2020-04-12 23:28 UTC, Readystorm546 commented
> would be better if you changed the shoes they craft to fit them instead of removeing the digitigrade trait

The trait still exists. Just does not default to ashwalkers anymore.

2020-04-13 01:54 UTC, overlord12345 commented
> The trait still exists. Just does not default to ashwalkers anymore.

i might have worded it wrong, but what i mean is dont remove the trait from ashies

2020-04-13 06:27 UTC, nichlas0010 commented
>Ashwalkers can put on shoes because they cant craft the tribal shoes but cant put it on. I think thats dumb.

Just make them unable to craft shoes then :)

2020-04-13 07:31 UTC, HomocidlePancakes commented
HeEy y not hav them shudd gunz they kan mag gunz!1!11

2020-04-13 08:04 UTC, SomeguyManperson commented
if you want to let them use chitin boots make a species exception in the boots don't remove their digitigrade

2020-04-13 14:34 UTC, HomocidlePancakes commented
Fun fact, bone armor covers feet, but chitin armor doesn’t for whatever reason, even though the first used to craft the second.

2020-04-13 14:35 UTC, Readystorm546 commented
> if you want to let them use chitin boots make a species exception in the boots don't remove their digitigrade

This was my original idea. But the code for those legs is so convoluted that it was hard to find where it marked shoes and on top of that if it even marked it at all. Which makes me think how could i put in a variable or some sort of parameter that accepts only those shoes.

2020-04-13 15:12 UTC, alexkar598 requested changes
Leave the comments alone, dont keep all changes to a minimum. Also, what others said, make the shoes have an exception for them somehow. Removing a feature for a niche rarely used one is stupid.

2020-04-14 04:48 UTC, closed without merging

2020-04-14 05:17 UTC, Marmio64 commented
yeah lets keep ashwalkers with digitigrade legs and just make them be able to wear their specific craftable shoes, like what most people here have said.