Adds hierophant antenna traitor item
yogstation13/Yogstation pull request #8203
Opened 2020-04-17 19:29 UTC by Takahiru

Adds a 15 TC hierophant antenna traitor item, allows traitor shaft miners to use the hierophant club on the station.

2020-04-17 19:52 UTC, Takahiru commented
oh no what is merge conflict

2020-04-18 10:52 UTC, Alexandria404 commented
very nice

2020-04-19 17:07 UTC, alexkar598 requested changes

2020-04-19 17:07 UTC, alexkar598 commented on code/modules/mining/lavaland/necropolis_chests.dm
> +
```suggestion
/obj/item/hierophant_club/attackby(obj/item/I, mob/user)
	if(istype(I, /obj/item/hierophant_antenna))
		if(z_level_check)
			z_level_check = FALSE
			desc += " It has an ominous antenna attached."
			qdel(I)
		else
			to_chat(user, "<span class='warning'>The herald's power already reaches this club!</span>")
		return TRUE
	else
		return ..()

```

2020-04-19 17:07 UTC, alexkar598 commented on code/modules/mining/lavaland/necropolis_chests.dm
> +
That brings slightly cleaner code and proper parent calling

2020-04-20 05:01 UTC, merged