Fixes mime box being visible when hands are full, issue 7894
yogstation13/Yogstation pull request #8248
Opened 2020-04-22 22:25 UTC by Takahiru

mimes are now fixed

2020-04-23 00:54 UTC, Hopekz approved these changes

2020-04-23 12:55 UTC, PettyOfficer commented
Good coder.

2020-04-24 14:11 UTC, monster860 requested changes

2020-04-24 14:11 UTC, monster860 commented on code/modules/spells/spell_types/mime.dm
> +		if(usr.get_active_held_item() == B)
`user` not `usr` because above used `user`

2020-04-24 14:16 UTC, monster860 approved these changes

2020-04-24 14:28 UTC, merged