ports "Nullrods now use a radial menu to choose their skins #50512" from tg
yogstation13/Yogstation pull request #8261
Opened 2020-04-24 18:04 UTC by Jumps0

### About The Pull Request

Switches the null rod selection menu from a list to a radial menu similar to that of a borg or RCD.

All credit to Arkatos1, they did the original work, I'm just porting it here.

Example GIF:
![xyOcqnExTU](https://user-images.githubusercontent.com/49619518/80242956-1dc65e80-861b-11ea-91ec-634d3627d357.gif)

#### Changelog

:cl:  Arkatos
rscadd: Nullrod variants are now chosen via a radial menu. 
/:cl:

2020-04-24 18:08 UTC, Jumps0 commented
I totally understand if ppl don't want this to be merged due preference of item name > image on selection. Thats fine

2020-04-25 04:12 UTC, Hopekz requested changes

2020-04-25 04:12 UTC, Hopekz commented on code/game/objects/items/holy_weapons.dm
> +
```suggestion
  /*
  reskin_holy_weapon: Shows a user a list of all available nullrod reskins and based on his choice replaces the nullrod with the reskinned version
  
  Arguments:
  M : The mob choosing a nullrod reskin
  */
```

2020-04-25 04:12 UTC, Hopekz commented on code/game/objects/items/holy_weapons.dm
> +  */
```suggestion
  /*
  check_menu : Checks if we are allowed to interact with a radial menu
  
  Arguments:
  user : The mob interacting with a menu
  */
```

2020-04-25 18:08 UTC, Hopekz commented
Pretty nice; tried to break in my tests and it properly doesn't transform/closes if you get rid of the item. All good can't see this being a bad feature as it is replacing an ugly UI

2020-04-25 18:08 UTC, merged