[admin] Add spidirizing as a smiting option
yogstation13/Yogstation pull request #8290
Opened 2020-04-27 05:32 UTC by Birddude1230

### Intent of your Pull Request

[Implements this coding request.](https://forums.yogstation.net/index.php?threads/but-she-was-already-pouring-you-a-brimming-glass-of-spiders.20398/)

Adds a new entry under the admin smiting menu ("Spiderize") to explode a mob into spiders.  Specifically, the mob will be gibbed, and 2-4 spiderlings will spawn at its location. As the intent in the forum post is to deal with the body of a griefer, the brain is destroyed in the gibbing.

#### Changelog

:cl:  
rscadd: Adds a spidirizing smite that destroys the brain and spawns spiderlings!
/:cl:

2020-04-27 07:23 UTC, Hopekz requested changes
Smiting is meant to punish 1 player. 
If you spawn spiderlings you just create full-on big spiders later down the line.

Either make these spiderlings into a child that spawns into harmless spiderlings that don't do anything or have them be deleted sometime after so they don't transform (or both)

As an admin, I want a "smite and forget" solution and this is a "smite then worry about deleting spiderlings so I don't fuck up the shift with brood mothers" solution.

2020-04-27 17:02 UTC, Marmio64 commented
yeah, might wanna have the spiderlings be sterile and not grow up

2020-04-28 04:31 UTC, Hopekz commented
I think the idea is nice but the execution is a bit underwhelming.
Besides like 2-3 spiders spawning it isn't really that much different than a gib slay (at least not different enough to warrant adding it as a separate gib option compared to all the other options)

![4HyZGrGWD0](https://user-images.githubusercontent.com/24533979/80447425-f99aa400-88de-11ea-91f8-b32d59fb3dc1.gif)

Not sure what can be done to make it "different". More spiders? 
Maybe if you add like 10-20 spiders you might get the effect you are looking for.

2020-04-28 04:38 UTC, Idinuum commented
Make it stun them while spiders spawn with flavor text. Some nice text about crawling out of orifices or something. Then gib them, then more spiders.

2020-04-28 05:39 UTC, Birddude1230 commented
Would you happen to know an upper limit on the number of spiderlings I can spawn before it's dangerous to the server? Now that I've tried it, it's definitely a lot more effective when the spiderlings cover the room.
If it's not a really bad idea for performance something like stun -> spawn ~50 spiderlings -> gib -> spawn ~200 spiderlings. I should also add some variation to the death timer so they don't all die in the same tick, since that looks odd.

After all, it would take **a lot** of spiderlings to fill a body. 
![many spiderlings](https://user-images.githubusercontent.com/6487305/80451069-f01a3780-88f0-11ea-8490-34161895a2e3.gif)

2020-04-28 15:16 UTC, alexkar598 requested changes

2020-04-28 15:16 UTC, alexkar598 commented on code/modules/admin/verbs/randomverbs.dm
> +				addtimer(CALLBACK(S, .Destroy), 50) //just enough time for them to skitter around a little
use the QDEL_IN proc instead

2020-04-28 21:29 UTC, Birddude1230 commented on code/modules/admin/verbs/randomverbs.dm
> +				addtimer(CALLBACK(S, .Destroy), 50) //just enough time for them to skitter around a little
Thanks!

2020-04-28 21:46 UTC, Birddude1230 commented
Very small gif of player perspective -- maybe I should make it cause damage each time it spawns more spiders. Also not sure that the code is up to standard with regards to magic numbers and proc placement, but I didn't want to introduce a bunch of constants to this already-giant file.

Maybe I should figure out the file structure and put smiting in its own file.

![They crawl within you.](https://user-images.githubusercontent.com/6487305/80540775-f30c3b00-8977-11ea-81f5-bdfc3c4f1ebd.gif)

2020-05-04 05:24 UTC, Hopekz commented
So are these supposed to despawn?
In my tests, this leaves a lot of spiders just kind of littered everywhere.
Some despawn but not all of them.

![dreamseeker_LQAVCPKl8h](https://user-images.githubusercontent.com/24533979/80938085-601b3880-8d9d-11ea-8e9d-9a7ec2180de1.png)

Also, something to keep in mind is that they vent crawl as well so there might be spiders that are dead in the vents as well. Couldn't find them exit anywhere so thought I'd mention.

![dreamseeker_uA1t7tHZNT](https://user-images.githubusercontent.com/24533979/80938148-a1134d00-8d9d-11ea-9b42-01b94906277b.png)

2020-05-06 16:44 UTC, alexkar598 requested changes
Also im slightly concerned that it creates tons of dead spiderlings but I suppose it just creates free food

2020-05-06 16:44 UTC, alexkar598 commented on code/modules/admin/verbs/randomverbs.dm
> +		target.gib(TRUE)
1. This should really be a proc on the mob, not on the client of the admin
2. We only use the `as` modifier thing for procs which are called directly from the right hand panel(verbs)
3. Thats a bit too many spiders... 30 to 68 spiders is more reasonable than 135 to 165 spiders

```suggestion
/mob/living/carbon/proc/spiderize(progress = 1)
	SetAllImmobility(500)
	do_jitter_animation(progress * 200)
	visible_message("<span class='danger'>Spiders emerge from [target.name]!</span>", "<span class='userdanger'>They crawl within you.</span>")
	for (var/i in 1 to rand(progress * 3, progress * 5))
		var/obj/structure/spider/spiderling/S = new(drop_location())
		S.directive = "Erase the legacy of [target.name]."
		QDEL_IN(S, rand(50, 300)) //just enough time for them to skitter around a little
	if (progress < 5)
		addtimer(CALLBACK(src, /mob/living/carbon.proc/spiderize, progress + 1), 75)
		return
	visible_message("<span class='danger'>[target.name] explodes into a chittering mass!</span>", "<span class='userdanger'>The gods have rended your form.</span>")
	gib(TRUE)
```

2020-05-06 16:44 UTC, alexkar598 commented on code/modules/admin/verbs/randomverbs.dm
> +			addtimer(CALLBACK(src, /client/proc/spiderize_more, target, 1), 25)
Since its on the mob now instead of the client

```suggestion
			addtimer(CALLBACK(target, /mob/living/carbon.proc/spiderize), 25)
```

2020-05-19 20:12 UTC, alexkar598 commented
This PR has been closed due to being stale. Contact me or another maintainer on Discord if you wish for this PR to be reopened.

2020-05-19 20:12 UTC, closed without merging