Various small TGUI's
yogstation13/Yogstation pull request #8291
Opened 2020-04-27 08:16 UTC by TheGamerdk

### Intent of your Pull Request
This adds a TGUI for:
The teleporter
The timer
The mining vendor
The infrared thing
The proximity sensor
The radioactive microlaser

Also:
Fixes a small bug in the uplink
Makes it possible to switch to nightshift while an APC is locked
Adds a number input for the SMES input/output

#### Changelog

:cl:  TheGamerdk for porting, original authors for coding
rscadd: Various new TGUI's from TGstation
/:cl:

2020-04-27 08:18 UTC, TheGamerdk commented
oh god I forgot to compile it

2020-04-29 03:39 UTC, Firewolf34 commented
I love you for this.

2020-04-29 05:59 UTC, TheGamerdk commented
> I love you for this.

I'm not into that

2020-05-19 12:33 UTC, JamieD1 requested changes
Conflicts

2020-05-27 18:30 UTC, JamieD1 approved these changes

2020-05-28 05:50 UTC, SomeguyManperson commented on code/modules/vending/_vending.dm
> +	.["ignores_capitalism"] = L.ignores_capitalism
this runtimes for ghosts

2020-05-28 05:52 UTC, SomeguyManperson commented
I don't know what this means but it's a runtime so
![image](https://user-images.githubusercontent.com/24857008/83104028-e7e72080-a085-11ea-991f-90186c3c3865.png)

2020-05-28 07:34 UTC, TheGamerdk commented on code/modules/vending/_vending.dm
> +	.["ignores_capitalism"] = L.ignores_capitalism
Ghosts are mob/living?

2020-05-28 07:35 UTC, TheGamerdk commented
It means our codebase is fucked. They’re items with missing Icons. I’ll link some of the fix PRs

2020-05-28 07:36 UTC, TheGamerdk commented on code/modules/vending/_vending.dm
> +	.["ignores_capitalism"] = L.ignores_capitalism
Oh, nevermind

2020-05-29 20:09 UTC, TheGamerdk commented
> I don't know what this means but it's a runtime so
> ![image](https://user-images.githubusercontent.com/24857008/83104028-e7e72080-a085-11ea-991f-90186c3c3865.png)

see above

2020-05-31 21:39 UTC, JamieD1 commented
You could of just reversed it

2020-05-31 21:40 UTC, TheGamerdk commented
> You could of just reversed it

wat

2020-06-07 02:34 UTC, wejengin2 commented
What did the rastabeanie ever do to you

2020-06-08 08:54 UTC, TheGamerdk commented
> What did the rastabeanie ever do to you

Live without a sprite

2020-06-08 08:54 UTC, TheGamerdk commented
Updated the description because SOME people thought we had undocumented changes

2020-06-10 20:03 UTC, SomeguyManperson approved these changes

2020-06-14 21:52 UTC, merged