Ports ''changes cult sprites + radials"
yogstation13/Yogstation pull request #8294
Opened 2020-04-27 11:13 UTC by TheGamerdk

### Intent of your Pull Request
Ports 
https://github.com/tgstation/tgstation/pull/50620

New cult sprites

Better Narsie animation

Radials for selecting Construct type

Check the icondiff bot for changes, or the original PR
#### Changelog

:cl:  Fikou for code, thegamerdk for porting

imageadd: The cult constructs have gotten a new layer of paint!
/:cl:

2020-04-27 16:14 UTC, Xoxeyos commented
Can we please get some pictures?

2020-05-06 17:02 UTC, alexkar598 requested changes
Why remove the two air cans and the firelocks on the narsie shuttle?

2020-05-06 17:02 UTC, alexkar598 commented on code/game/objects/effects/temporary_visuals/miscellaneous.dm
> +	icon_state = "phase_shift2_angelic"
This lives in cult.dmi, the thing points to mob.dmi

2020-05-06 17:02 UTC, alexkar598 commented on code/game/objects/effects/temporary_visuals/miscellaneous.dm
> +	icon_state = "phase_shift_angelic"
This lives in cult.dmi, the thing points to mob.dmi

2020-05-06 17:02 UTC, alexkar598 commented on code/modules/admin/topic.dm
> +				M.change_mob_type( /mob/living/simple_animal/hostile/construct/artificer , null, null, delmob )
It may suprise you to learn you also need to update the admin panel to use these new names.

2020-05-06 17:02 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/constructs.dm
> +	environment_smash = ENVIRONMENT_SMASH_STRUCTURES //standard ai construct behavior, breaks things if it wants, but not walls.
Due to monstermos, id rather have new mobs not be able to smash walls at will.

```suggestion
	environment_smash = ENVIRONMENT_SMASH_STRUCTURES
	attack_sound = 'sound/weapons/punch2.ogg'
	playstyle_string = "<b>You are a Proteon. Your abilities in combat are outmatched by most combat constructs, but you are still fast and nimble. Run metal and supplies, and cooperate with your fellow cultists.</b>"

/mob/living/simple_animal/hostile/construct/proteon/hostile //Style of mob spawned by trapped cult runes in the cleric ruin.
	AIStatus = AI_ON
```

2020-05-06 18:29 UTC, TheGamerdk commented
Closed in favor of whatever Theos is doing

2020-05-06 18:29 UTC, closed without merging