Ports "Give a little #50710" from TG, an offer button
yogstation13/Yogstation pull request #8313
Opened 2020-04-28 09:20 UTC by ynot01

https://github.com/tgstation/tgstation/pull/50710
## About The Pull Request
Allows you to offer and accept items from people one tile away from you

## Why It's Good For The Game
You no longer have to throw or drop items to transfer them to someone else and its an easy way to alert the other person that you're trying to give them something

![image](https://user-images.githubusercontent.com/30060146/80320830-c248cc00-87e6-11ea-9504-6547d164fdfc.png)

## Changelog
:cl: Couls
add: Give item keybind, default to G. Press it while holding an item to offer it to someone nearby, they can click the alert they get to accept it or ignore it for it to go away
add: There is a right click menu option for giving
/:cl:

2020-04-28 09:31 UTC, Bibby0110 requested changes
there, review ported from TG, thank me later

2020-04-28 09:31 UTC, TheGamerdk commented on code/modules/mob/living/carbon/inventory.dm
> +		G.RegisterSignal(C, COMSIG_MOVABLE_MOVED, /obj/screen/alert/give/.proc/removeAlert)
All of this should probably be done in the alert instead

2020-04-28 09:31 UTC, TheGamerdk commented on code/modules/mob/living/carbon/inventory.dm
> +		G.desc = "[src] is offering [receiving]. Click this alert to accept it."
G.desc = "[src] is offering [receiving]. Click this alert to take it."

2020-04-28 10:54 UTC, MenacingManatee commented
Could you add a confirmation before giving? f is pretty close to the movement keys, and accidentally hitting f would make a visible alert to what you're holding, and may accidentally give items away
(Unless I'm the big dumb and overlooking a confirmation before the chat message is sent)

2020-04-28 17:01 UTC, monster860 requested changes
can you pick a different key, I wanted to use F for something else.

2020-04-28 17:18 UTC, ynot01 commented
> Could you add a confirmation before giving? f is pretty close to the movement keys, and accidentally hitting f would make a visible alert to what you're holding, and may accidentally give items away
> (Unless I'm the big dumb and overlooking a confirmation before the chat message is sent)

a confirmation would ruin flow imo, you can cancel it by moving out of the restrictive range of 1 tile or putting the item away

2020-04-29 15:53 UTC, Hopekz requested changes
If you want me to Merge this specifically I won't merge it with these ugly automated TG comments

2020-04-29 15:53 UTC, Hopekz commented on code/modules/mob/living/carbon/inventory.dm
> +  */
```suggestion
  /*
  Proc called when giving an item to another player
  
  This handles creating an alert and adding an overlay to it
  */
```

2020-04-29 15:53 UTC, Hopekz commented on code/modules/mob/living/carbon/inventory.dm
> +  */
```suggestion
  /*
  Proc called when the player clicks the give alert
  
  Handles checking if the player taking the item has open slots and is in range of the giver
  Also deals with the actual transferring of the item to the players hands
  Arguments:
  * giver - The person giving the original item
  * I - The item being given by the giver
  */
```

2020-04-30 21:54 UTC, merged