ports "Radial card hands #50729" from TG
yogstation13/Yogstation pull request #8316
Opened 2020-04-28 15:27 UTC by Jumps0

### Intent of your Pull Request

All Credit to **RaveRadbury** for coding, all I did was port it.

When viewing your hand of cards instead of being given a list menu you are now given a radial menu.
![hFxSOkZYB2](https://user-images.githubusercontent.com/49619518/80506044-f1b42180-8929-11ea-8d58-cae629ca8bde.gif)

#### Changelog

:cl:  RaveRadbury
tweak: Radial menu for hands of cards
/:cl:

2020-04-28 15:38 UTC, Jumps0 commented
i can't believe you've done this

2020-04-28 16:10 UTC, Jumps0 commented
ladies and gentlement, we got em

2020-04-30 22:01 UTC, Hopekz requested changes

2020-04-30 22:01 UTC, Hopekz commented on code/game/objects/items/toys.dm
> +/obj/item/toy/cards/cardhand/proc/update_sprite()
```suggestion
/// This proc updates the sprite for when you create a hand of cards
/obj/item/toy/cards/cardhand/proc/update_sprite()
```

2020-04-30 23:02 UTC, Jumps0 commented
HOW

2020-05-01 07:15 UTC, merged