Planting c4 on a backpack has a popup
yogstation13/Yogstation pull request #8367
Opened 2020-05-02 01:55 UTC by ToGWtF

### Intent of your Pull Request

Before:
First time nuke ops
Let me just buy some cool gear
Oooh free c4 on the table
I'll just put this in my backpack as well
"admin why am dead"

C4 will no longer be planted on backpacks if they are full. Rather, a popup will open asking if you are sure. 

#### Changelog

:cl:  
tweak: tweaked c4 a bit
/:cl:

2020-05-02 02:15 UTC, alexkar598 requested changes
make it check for a storage component instead

2020-05-02 13:37 UTC, HomocidlePancakes commented
Popups are bad. They steal focus and are annoying. Instead have a large scary message appear in chat. Also, hugbox.

2020-05-16 13:58 UTC, JamieD1 commented on code/game/objects/items/grenades/plastic.dm
> +	if(istype(AM, /obj/item/storage/backpack) || istype(AM, /obj/item/storage/box))
if(GetComponent(/datum/component/storage))

2020-05-19 12:49 UTC, JamieD1 approved these changes

2020-05-19 20:15 UTC, alexkar598 approved these changes

2020-05-19 20:16 UTC, merged