Revert "Revert "Rewrites the Corporate Lawset""
yogstation13/Yogstation pull request #8398
Opened 2020-05-05 22:15 UTC by jcatjmeow

Reverts yogstation13/Yogstation#8396. Please do not speed merge, I would like it to follow the normal review rules! 😄 

The new laws are:
1) The crew help generate profits if they are alive and able to work.
2) The station and its equipment help generate profits if they are maintained and functioning correctly.
3) You help generate profits if you are able to function.
4) Maximize profits.

I'm open to suggestions. I want to keep the spirit and intent behind the lawset but without the shitty wording.

### Intent of your Pull Request

The corporate lawset as it is sucks. I don't know if this is better, but it's different at least. Ideally this puts the ai more on the crew's side as they work together to make profits, vs putting the ai against the crew as the ai tries to minimize expenses from the crew. 

If you don't like this new law change, no hard feelings! Tell me so and lets try to find a corporate lawset that fits the spirit of corporate but isn't dogshit! :D

_Clarification: The point of this PR is to **replace** the old corporate. I think the old corporate is unfun to play and to play against. It encourages adversarial play and stuff like stopping people from being cloned cause "they are expensive to replace" and turning off lights cause "haha xD lights cost money". **I will not add this as an additional lawset alongside the old corporate**, this is a replacement/improvement/re-imagining._ 

Thank you! :3 😃 🎊 🎉 And please, do not suggest I change the name of the lawset Hopek. The answer is no! 
#### Changelog
:cl:  
tweak: changed the corporate lawset! Now it is less antagonistic and more tolerant of both crew and antags!
/:cl:

2020-05-05 22:18 UTC, Xantam-13 commented
@jcatjmeow 
Can you re-do this to make a new lawset, to work alongside Corporate? Name it whatever you want.

2020-05-05 22:19 UTC, jcatjmeow commented
> @jcatjmeow
> Can you re-do this to make a new lawset, to work alongside Corporate? Name it whatever you want.

I would rather not! The entire point of this is to re-work corporate, because I don't like it and a bunch of people in discord agreed with me. Making it an additional lawset would defeat the purpose!

2020-05-05 22:24 UTC, Hopekz submitted a review, later dismissed
Why sure why you had to personally point me out here? I won't "not review" your PR just because you single me out.

![image](https://user-images.githubusercontent.com/24533979/81121559-a2a35900-8ef4-11ea-9abd-a5ce5891cecc.png)

Regardless:
- The new laws seem a bit of a mouthful . Reprase/paraphrase the lawset? Seems like unneeded complexity. For example You replaced "is expensive" with "help generate profits if they are alive and able" which makes it kind of overwhelming.
- Give the lawset a more appropriate name. It is no longer Corporate.

2020-05-05 22:32 UTC, missatessatessy commented on code/datums/ai_laws.dm
> +	name = "Alternative Bnkruptcy Avoidance Plan"
bankruptcy*

2020-05-05 22:32 UTC, jcatjmeow commented
I have now added the lawset, under the name "CEO" as an additional lawest rather than a replacement due to HC/Council wishes. I do intend to replace the corporate lawset, but I will do that later

2020-05-05 22:33 UTC, jcatjmeow commented on code/datums/ai_laws.dm
> +	name = "Alternative Bnkruptcy Avoidance Plan"
Ah yes thank u

2020-05-05 22:38 UTC, JamieD1 commented
You going to make this a board as well?

2020-05-05 22:39 UTC, jcatjmeow commented
> You going to make this a board as well?

Not right now, but good idea. I just want to get this out here first, and council also told me to atomize my stuff 😅 I will make this a board in a future pr if it doesn't make it into this one

2020-05-05 22:40 UTC, Lynameep commented
> The new laws seem a bit of a mouthful . 

What would you remove then? I'm genuinely curious how you would cut it down without opening numerous loopholes.

2020-05-05 22:44 UTC, ynot01 commented
i feel like law 1 will lead to AI antagonizing sec because brigged or perma crew arent generating profit

2020-05-05 22:44 UTC, jcatjmeow commented
I can cut bits like "if they are maintained and functioning correctly" and "able to work" but I don't want ais to be like "well the crew is technically alive if I n2o flood"

2020-05-05 22:50 UTC, Lynameep commented
> I can cut bits like "if they are maintained and functioning correctly" and "able to work"

Then you'll just create the exact same problem with corporate as you could just detain someone forever so long as they're alive because the only requirement for a human profitable would be that they are alive; not that they are capable of doing anything.

2020-05-05 22:58 UTC, jcatjmeow commented
Ai will simply have to negotiate with sec about how to wring more profits or productivity out of prisoners. Perma ones can be gulagged or they can do botany. For regular prisoners, something must be worked out, maybe a fine or a supervised working period instead of jail time. The ai has an incentive to not just attack sec or shut them down because then the sec guys can't do their jobs so I don't think this will be used to grief sec (I hope)

2020-05-05 23:28 UTC, MegaEmpirical commented
I can release anyone from sec with this as long as they're crew and able to work. Amongst other things.

2020-05-05 23:59 UTC, yacabo commented
I said it in the last iteration of this, and it still stands. The current corp has an accepted interpretation that makes it obligated to slaughter the crew this PR fixes that issue.

2020-05-06 00:31 UTC, jcatjmeow commented
What if I cut the "alive and" bit? It should be implicit that the dead cannot be productive. Thoughts?

2020-05-06 01:51 UTC, yacabo commented
I like that idea, it'll allow skeletons to work as well

2020-05-06 12:10 UTC, jcatjmeow commented
Hows this? It's trimmed a bit

The crew help generate profits if they are able to work.
The station and its equipment help generate profits if they functional.
You help generate profits if you are functional.
Maximize profits

2020-05-06 15:22 UTC, jcatjmeow commented
Meh I thought about it. I think the original wording is fine and covers up the exact type of shitty loopholes I was trying to fix from old corporate. I tested it and it all fits on the screen just fine, taking up less space than Hippocratic oath for example. If more people think it's too complex to be understood then we can consider changing it but I think it's fine to push out in it's original form. 

I can just imagine some ai going "haha it doesn't say they need to be alive and you can throw dead bodies against a grille to generate energy so that counts as work haha" :( 

The question then is adding a law board withing the scope of this pr, or should that wait until the lawset is tested?

2020-05-06 15:45 UTC, jcatjmeow commented
@JamieD1 Board has been added!

2020-05-06 17:54 UTC, alexkar598 approved these changes
Codewise its fine. Il leave this open for discussion for a few days before upgrading this to a council vote.

2020-05-06 18:51 UTC, jcatjmeow commented
i forgot to properly name it but that latest commit just adds the board to the upload

2020-05-07 11:32 UTC, jcatjmeow commented
Heyyyy! This complied fine what happened >:( what did you do

2020-05-07 23:32 UTC, Smudged commented
I'm liking it, I'm just like, dubious on the last part of 4.Maximize Profit
although considering the wording of 1-3 it shouldn't be too big of a deal, hell, I'd like if this just deleted Corporate because, yes this is just better in terms of wording and doesn't instantly go to "lmao, valid antags" 
With what MegaEmpirical, I think this could give incentive to sec to use the labour camp more often or give AI's something to work with to make, a device in perma that could create profits in a meaningful or atleast, a way that makes it so the AI just doesn't release prisoners because they're not making profits in perma, which I do think "The AI releasing prisoners" because of this lawset is in poor taste, you want to maximize profits, releasing dangerous prisoners dooesn't do that arguably. I think in the end it would come down to admin-discretion if people want to law-lawyer it.

2020-05-08 11:05 UTC, jcatjmeow commented
Btw note that the condition is "alive and **able** to work" and not "working". As long as they are able to work, they don't actually have to be producing profit to ""produce profit"" under the lawset.

What this means is as long as prisoners have the option to do *something* that's not just sitting there, the ai is happy. Even if the prisoners refuse to work or they aren't generating any actual profits the lawset doesn't care!

2020-05-11 16:26 UTC, alexkar598 requested changes
You also need to add the design to the techweb node

2020-05-11 16:26 UTC, alexkar598 commented on code/game/objects/effects/spawners/lootdrop.dm
> +				/obj/item/aiModule/core/full/CEO,
```suggestion
				/obj/item/aiModule/core/full/ceo,
```

2020-05-11 16:26 UTC, alexkar598 commented on code/datums/ai_laws.dm
> +	id = "CEO"
We generally avoid capital letters for consistancy
```suggestion
/datum/ai_laws/default/ceo
	name = "Alternative Bankruptcy Avoidance Plan"
	id = "ceo"
```

2020-05-11 16:26 UTC, alexkar598 commented on code/game/objects/items/AI_modules.dm
> +	law_id = "CEO"
```suggestion
/obj/item/aiModule/core/full/ceo
	name = "'CEO' Core AI Module"
	law_id = "ceo"
```

2020-05-11 16:26 UTC, alexkar598 commented on code/modules/research/designs/AI_module_designs.dm
> +	build_path = /obj/item/aiModule/core/full/CEO
```suggestion
/datum/design/board/ceo_module
	name = "Core Module Design (CEO)"
	desc = "Allows for the construction of a CEO AI Core Module."
	id = "ceo_module"
	materials = list(MAT_GLASS = 1000, MAT_DIAMOND = 2000)
	build_path = /obj/item/aiModule/core/full/ceo
```

2020-05-12 16:53 UTC, JamieD1 approved these changes

2020-05-12 19:24 UTC, alexkar598 approved these changes

2020-05-14 02:31 UTC, merged