Adds gas mining to lavaland base for easier breach recovery and recycling scrubbed air.
yogstation13/Yogstation pull request #8400
Opened 2020-05-05 22:59 UTC by Lovebird-Frungy

The intent of this pr is to fix the horror that is the late shift mining base: airlocks not opening due to no air being available to minimize decompression, constant atmospheric alarms after the tiniest of breaches, and vacuums killing miners.

The old engineering layout has been overhauled, expanding it to make room for new machinery:
- A gas mining set up, taking from lavaland’s seemingly infinite n2 and o2 supply to collect them into pressurized air tanks, then combining the two (not unlike the main station) at a pressure better fit for human life to thrive.

- The scrubber system’s old air injector has been removed and the waste pipes linked to the gas mining setup, effectively removing a lot of waste, keeping the space sheperd fanatics happy.

Heres a drone captured picture of the room’s new look:
<img width="288" alt="NewPic" src="https://user-images.githubusercontent.com/64857565/81121481-25e1a080-8f2f-11ea-98f1-e1167b032053.png">
And heres the old one for reference (found on a dead miner’s body with a annotation saying "@%#? monstermos"):
<img width="224" alt="OldPic" src="https://user-images.githubusercontent.com/64857565/81121596-64775b00-8f2f-11ea-9795-c8ba648862b5.png">

Other minor changes include:
- Added a pump and a connector to make a refillable o2 tank for internals purposes, complete with analyzer for mole measurement!
- Moved around the lights, signs, welder tank, abandoned crate, and added an atmospheric sign for good measure!
- Added an air alarm for occasional tweaking of the new air vent.
- Added some lava to the outside to blend the changes with the landscape.

The following results were noted:
After having spaced all the air supply and putting the rooms in a vacuum, the base managed to easily recover!
The airlock used by miners is no longer stuck easily, but still manages to create a mini-vacuum, maybe a later change will fix this!

For a detailed picture of how it works:
<img width="288" alt="NewPic - Copie" src="https://user-images.githubusercontent.com/64857565/81122670-a73a3280-8f31-11ea-96c4-69d218354267.png">

Legend:
- Orange: lavaland air.
- Crismon: mining scrubbers’s waste in.
- Blue: pure o2.
- Red: pure n2.
- Light Blue: { (21% o2) (79% n2) } : the standard air mix!

Short explanation:
1. a. The vent pump tries to bring its own pressure to 4kpa, effectively "succing" lavaland’s atmosphere.

1. b. The scrubbers empty themselves in the same pipe, and if its too much to handle and the pipes clog, the pressure will go above 4kpa and so make the vent release gas, effectively preventing any clogs.

2. The first filter takes out the oxygen from the gas mix and leads it to the pressure tank for storage.

3. a. The second filter takes out the nitrogen from the gas mix and leads it to the pressure tank for storage.

3. b. The non filtered gases are sent to an injector in lavaland, and rejected as waste gases.

4. The two pure gases are brought to a gas mixer that will create breathable air out of them, which is then sent to the supply pipes for the normal vents to use.

Picture with steps masterfully surrounded:
<img width="288" alt="NewPic - Copie (2)" src="https://user-images.githubusercontent.com/64857565/81123335-1d8b6480-8f33-11ea-8f06-2d804f9ecc4e.png">

Lastly, the removed air injector:
<img width="212" alt="Annotation 2020-05-06 005221" src="https://user-images.githubusercontent.com/64857565/81123660-ec5f6400-8f33-11ea-8666-34660740b068.png">

And the moved scrubber and pipes, leading the waste to the filters:
<img width="137" alt="Annotation 2020-05-06 005330" src="https://user-images.githubusercontent.com/64857565/81123743-1a44a880-8f34-11ea-9cb5-2cdee3740ec5.png">

#### Changelog

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
/:cl:

2020-05-05 23:24 UTC, MegaEmpirical commented
Why use a vent to take in lavaland air?


Also, nice work.

2020-05-06 01:04 UTC, monster860 requested changes
I like this but please fix the changelog

2020-05-06 11:49 UTC, wejengin2 commented
Really good work man, please move the fuel tank though so it's next to the wall, just a minor cosmetic change. Maybe try the space between smes and pacmans?

2020-05-06 16:30 UTC, merged

2020-05-06 22:11 UTC, wejengin2 commented
This reverts all the other changes with firelocks and stronger windows