Adds a gang force converter, a compromise for the old implant breaker
yogstation13/Yogstation pull request #8415
Opened 2020-05-06 23:15 UTC by Takahiru

The force converter converts enemies gangsters to your gang, but it doesn't destroy mindshields/work on mindshieldeds.

This promotes less killing on gang rounds and may make people less salty.

2020-05-06 23:17 UTC, Hopekz commented
So how does this make people less salty if everyone just piles up on to 1 gang?

The mind breaker was making things unfun because it created this 1 giant mega gang that the crew can't fight and this just does the same thing.

2020-05-06 23:18 UTC, Xoxeyos commented
When a gang member gets converted to another gang, there will be hell to pay, this thing better cost alot, and have a long ass cooldown.

2020-05-06 23:19 UTC, Takahiru commented
I hate how gang rounds usually end up with a ton of killing and many people taken out of the round unlike any other conversion antag out there.

2020-05-06 23:20 UTC, Hopekz commented
> I hate how gang rounds usually end up with a ton of killing and many people taken out of the round unlike any other conversion antag out there.

Maybe the solution to your problem would be to make gangs have less "killing tools" like literal Uzi's and sketchins . 
This just piles every gang in to 1 gang .

Killing will still happen with this except it'll all be directed to the crew instead.

2020-05-06 23:22 UTC, Takahiru commented
If they had less killing tools they would still kill every other gang member because they literally have to, because the other gang members impede their progress. Blood Brothers can find ways to kill and so can gang members even if you take away all of their tools. Its a conversion gamemode and I don't see why it forces so many people to be forcefully taken out of the round unlike the other ones

2020-05-06 23:24 UTC, Hopekz commented
Fair enough.
I see your point I just don't think your PR is coming closer to fix the problem you have outlined.
All my opinion of course!

2020-05-06 23:33 UTC, Jarod1200 commented
what if we added some way for gangs to revive their fallen comrades? like a disposable defibrillator or something

2020-05-06 23:35 UTC, Hopekz approved these changes

2020-05-06 23:53 UTC, Hopekz commented
> what if we added some way for gangs to revive their fallen comrades? like a disposable defibrillator or something

To be honest I'd rather have gangs inherit leadership in an order set by the first gang leaders or "randomly" instead of having gangs do some magic field revive.

2020-05-07 00:20 UTC, Hopekz commented
@swissloaf 
I'll put the ready label on when it is ready 
![image](https://user-images.githubusercontent.com/24533979/81240975-9986ba80-8fce-11ea-875b-6ff41530f06b.png)

2020-05-07 14:35 UTC, alexkar598 requested changes
Move the check for implant in the success thing around like 40 so the message shows as resisting the implant if their mindshielded

2020-05-07 15:52 UTC, MegaEmpirical commented
I have two thoughts on this:

1) Gangs fighting and thus killing and reducing their numbers is important for the crew to be able to compete. This may be to potent a buff for gang. I could be wrong though.

2) The sweet release of death is the only way to enjoy a gang round and when I am converted I am instantly hoping to be deconverted or killed as soon as possible. Don't fuck me by having me shift gangs.

2020-05-07 18:18 UTC, SomeguyManperson commented
> So how does this make people less salty if everyone just piles up on to 1 gang?
> 
> The mind breaker was making things unfun because it created this 1 giant mega gang that the crew can't fight and this just does the same thing.

it's already possible to turn people via mindshield > implant removal so being able to buy an item to do that but faster doesn't really change much for the whole "everyone being piled into one gang" thing

2020-05-07 20:58 UTC, Takahiru commented
I thought the reason it was originally removed is because it destroys securities efforts to deconvert gangsters instantly, security having no real way to prevent people from being converted without just killing them

2020-05-08 19:35 UTC, boodaliboo commented
maybe you can make it so it only ressurects dead gang members?

2020-05-08 20:19 UTC, MegaEmpirical commented
What part of the only good thing about Gang is dying do you not get?!

2020-05-08 20:23 UTC, Hopekz commented
The server poll for this is going to end later today so I'll post the results here.

Seeing that feedback would be key in deciding to merge this since I do not see much positive support for this change at the moment.

2020-05-10 17:38 UTC, Hopekz commented
Here are the results of the poll:
Ignoring Neutral I do not think the result is decisive enough to ignore all the negative feedback on here.
I was really hoping for a larger majority to some side.

![image](https://user-images.githubusercontent.com/24533979/81506185-2e810080-92ba-11ea-8d18-61e95f8c3e78.png)

I won't merge this PR but some other maintainer might (code checks out)
Also won't close this PR to give a HC a chance to give their feedback in terms of if we actually need to merge this.

2020-05-11 01:05 UTC, alexkar598 commented on yogstation/code/game/objects/items/implants/implant_gang.dm
> +
```suggestion
			if(G)
				if(!istype(G, /datum/antagonist/gang/boss))
					success = TRUE	//Was not a gang boss, convert as usual
					target.mind.remove_antag_datum(/datum/antagonist/gang)
			else
				success = TRUE
			
			if(HAS_TRAIT(target, TRAIT_MINDSHIELD))
				success = FALSE
			
```

2020-05-11 01:05 UTC, alexkar598 approved these changes

2020-05-11 16:30 UTC, alexkar598 commented
Sure lets try this out

2020-05-11 16:30 UTC, merged