Disposal bins can now be alt clicked to toggle handle
yogstation13/Yogstation pull request #8451
Opened 2020-05-10 06:24 UTC by Hopekz

![f2kgGjBsq9](https://user-images.githubusercontent.com/24533979/81492408-f1d2ec00-925c-11ea-8e24-338402ac6b7a.gif)

#### Changelog

:cl:  Hopek
rscadd: Disposal bins can now be alt clicked to toggle handle
/:cl:

2020-05-17 10:18 UTC, JamieD1 approved these changes

2020-05-19 13:00 UTC, JamieD1 approved these changes

2020-05-21 02:40 UTC, alexkar598 requested changes

2020-05-21 02:40 UTC, alexkar598 commented on code/modules/recycling/disposal/bin.dm
> +		return
```suggestion
	if(!user.canUseTopic(src, TRUE)
		return
```

AIs cant flush bins

2020-05-21 02:40 UTC, alexkar598 commented on code/modules/recycling/disposal/bin.dm
> +		flush = TRUE
```suggestion
	flush = !flush
```

2020-05-27 17:56 UTC, JamieD1 approved these changes

2020-05-28 02:11 UTC, alexkar598 requested changes

2020-05-28 02:11 UTC, alexkar598 commented on code/modules/recycling/disposal/bin.dm
> +	if(!user.canUseTopic(src, TRUE)
```suggestion
	if(!user.canUseTopic(src, TRUE))
```

2020-05-29 19:15 UTC, merged