Better radio/headset suicide
yogstation13/Yogstation pull request #8454
Opened 2020-05-10 07:03 UTC by Hopekz

Instead of just bouncing the radio off your head.. you now:

Yell a brain damage line into the radio/headset and die from oxygen loss.
The message you yell into the radio is LOUD

**Current the headset turns off the LOUD function after suicide but here is a poll to vote on if it should stay on:**

https://strawpoll.com/bfxyb697

what this means:
If the LOUD stays on you'll be able to convert a radio or headset to LOUD for others by suiciding with it.

#### Changelog

:cl:  Hopek
rscadd: New radio/headset suicide
/:cl:

2020-05-10 09:12 UTC, TheGamerdk commented
Can't you just make the headset not loud after they say it

2020-05-11 15:31 UTC, swissloaf commented
how loud? normal command headset loud?

2020-05-11 19:48 UTC, Hopekz commented
> how loud? normal command headset loud?

Yeah just whatever the LOUD for command LOUD is at the time. 
It piggybacks off that so if command headsets are changed this will change as well.

2020-05-21 02:42 UTC, alexkar598 requested changes

2020-05-21 02:42 UTC, alexkar598 commented on code/game/objects/items/devices/radio/radio.dm
> +	use_command = FALSE
```suggestion
	talk_into(user, pick_list_replacements(BRAIN_DAMAGE_FILE, "brain_damage"), null, SPAN_COMMAND)
```

2020-05-27 17:55 UTC, JamieD1 approved these changes

2020-05-28 01:17 UTC, alexkar598 approved these changes

2020-05-28 01:17 UTC, merged