doubles the prize money for slots
yogstation13/Yogstation pull request #8488
Opened 2020-05-12 21:30 UTC by boodaliboo

### Intent of your Pull Request
tweaked how much pay you get from slots
now 
its 
5->10
400->800
1000->2000
10000->20000
#### Changelog

:cl:  
tweak: tweaked slots payment
/:cl:

2020-05-12 21:37 UTC, ynot01 commented
make slots viable for money generation maybe people will actually use them

2020-05-12 21:39 UTC, boodaliboo commented
> make slots viable for money generation maybe people will actually use them

what do you mean by this i use them

2020-05-19 06:11 UTC, ThatLing requested changes

2020-05-19 06:11 UTC, ThatLing commented on code/game/machinery/slotmachine.dm
> +#define JACKPOT 20000
You forgot to change the flavourtext that gets displayed when you win

2020-05-19 06:13 UTC, ThatLing commented
There is really no need for this, you can already easily steamroll into becoming a millionaire if you are lucky. This just increases the rate in which you earn money, not the chance of striking it rich.

2020-05-19 12:04 UTC, alexkar598 commented
>Make slots viable money generation
..... I have a feeling some people dont know the meaning of gambling...

2020-05-19 12:09 UTC, closed without merging