adds oxygen to tower caps
yogstation13/Yogstation pull request #8498
Opened 2020-05-14 18:58 UTC by boodaliboo

its a tree kinda
#### Changelog

:cl:  
rscadd: Adds oxygen to tower caps
/:cl:

2020-05-14 19:15 UTC, Moja10 commented
When botany mains make PRs like this, the first thing that should be done is looking up every chem that uses oxygen as part of a recipe and see what chems can now be made when combined with already existing chem from other plants. Then you will know their true intentions.

2020-05-15 23:36 UTC, JamieD1 requested changes

2020-05-15 23:36 UTC, JamieD1 commented on code/modules/hydroponics/grown/towercap.dm
> +
Can you remove the extra random line?

2020-05-17 05:43 UTC, SomeguyManperson commented
importantly this allows botanists to fabricate their own saltpetre

2020-05-21 03:08 UTC, alexkar598 commented
Id rather not powercreepe botany any further.

2020-05-21 03:08 UTC, closed without merging