disguisable prosthetics
yogstation13/Yogstation pull request #8502
Opened 2020-05-14 21:56 UTC by boodaliboo

allows you to disguise prosthetic limbs as normal limbs (appearance only they have the same name) by pouring synth flesh on them this doesnt work for cyborg limbs and they are still repaired like normal prosthetics
#### Changelog

:cl:  
rscadd: Added new synthflesh reaction and a way to disguise prosthetics 
/:cl:

2020-05-14 21:58 UTC, boodaliboo commented
fuck you travis

2020-05-14 21:59 UTC, DerelictDrone reviewed
You forgot to uncomment the left leg result

2020-05-14 21:59 UTC, DerelictDrone commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +		new //obj/item/bodypart/l_leg/robot/surplus/disguised(t_loc)
someone forgot to uncomment

2020-05-14 22:21 UTC, boodaliboo commented
what did it even mess up with

2020-05-15 16:34 UTC, boodaliboo commented
oh now it works

2020-05-15 20:11 UTC, JamieD1 commented
What happens if you put it on a lizard, do they have human looking arms?

2020-05-15 20:23 UTC, boodaliboo commented
> What happens if you put it on a lizard, do they have human looking arms?

its just using the basic human limb sprites so yes im not good enough at coding to do much more besides maybe adding a crafting recipe ontop of the disguised version to have lizard limbs

2020-05-15 21:45 UTC, JamieD1 commented
You could make it change based on which species its going on if you want to go advanced.

2020-05-21 03:11 UTC, alexkar598 requested changes
Your code doesnt work because you are overriding your own proc 3 times

This should honestly also be able to be used to on cyborg limbs but eh

Also just change the icon_state, no need for different subtypes

2020-05-26 19:43 UTC, boodaliboo commented
oh shit didnt see this comment give me a bit

2020-05-28 03:08 UTC, boodaliboo commented
i have lost my motivation and i need to take a break this is negatively impacting me

2020-05-28 03:08 UTC, closed without merging