adds a carp shank
yogstation13/Yogstation pull request #8513
Opened 2020-05-15 20:21 UTC by boodaliboo

adds a new shank that is craftable with carp tooth 5 cable coil a torn cloth and a metal rod
in order to obtain a carp tooth you must butcher a space carp
this shank does 17 damage 
#### Changelog

:cl:  
rscadd: Added carp tooth and carp shank
tweak: tweaked space carp drops added carp tooth  
imageadd: added two new sprites
/:cl:

2020-05-15 20:24 UTC, ynot01 commented
thats a lot of damage but then again you can print a butcher's cleaver for 15 force idk bro

if you sharpen it itll deal 21 damage

2020-05-15 20:25 UTC, BOBsHERE commented
it could also apply a small amount of carpotoxin on hit

2020-05-15 20:26 UTC, boodaliboo commented
what you reccomend its damage be and eh not sure on carpotoxin cant remeber how deadly it is

2020-05-15 20:34 UTC, Marmio64 commented
Make the shank deal 15 damage instead so its on par with a survival knife and bone dagger

2020-05-15 20:35 UTC, BOBsHERE commented
carpotoxin is a moderate poison on its own, its 2 damage per tick. If you lower the shank brute damage but make it apply some carpotoxin then its not just another knife and its unique and worth crafting.

2020-05-15 20:38 UTC, boodaliboo commented
yeah let me see

2020-05-15 20:42 UTC, boodaliboo commented
> carpotoxin is a moderate poison on its own, its 2 damage per tick. If you lower the shank brute damage but make it apply some carpotoxin then its not just another knife and its unique and worth crafting.



> Make the shank deal 15 damage instead so its on par with a survival knife and bone dagger

done

2020-05-15 21:25 UTC, Marmio64 commented
if you're having it deal carpotoxin should probably make it only deal 12 damage or something.

2020-05-15 21:40 UTC, boodaliboo commented
> if you're having it deal carpotoxin should probably make it only deal 10-12 damage or something.

done

2020-05-17 08:35 UTC, SomeguyManperson requested changes
also line ending issues by the looks of it

2020-05-17 08:35 UTC, SomeguyManperson commented on code/game/objects/items/weaponry.dm
> +	user.changeNext_move(CLICK_CD_RAPID)
🤔

2020-05-18 02:46 UTC, Hopekz commented on code/datums/components/crafting/recipes.dm
> +/datum/crafting_recipe/aispook
What is aispook? Why is this the path?
AI spook?
ais pook?
A is pook?

2020-05-18 23:45 UTC, Ktlwjec1 commented on code/game/objects/items/weaponry.dm
> +	desc = "a tooth harvested from a space carp."
A

2020-05-18 23:45 UTC, Ktlwjec1 commented on code/game/objects/items/weaponry.dm
> +	desc = "a shank made out of a metal rod, cable coil, and a carp tooth."
A

2020-05-21 03:14 UTC, alexkar598 requested changes
get. your. line. endings. together.

2020-05-26 19:45 UTC, boodaliboo commented
> get. your. line. endings. together.

i have no clue what you mean by this

2020-11-30 20:42 UTC, closed without merging