fixes it showing big bold in the ghost spawner for a few things
yogstation13/Yogstation pull request #8522
Opened 2020-05-16 06:43 UTC by boodaliboo

pm me if theirs more spawners with this
#### Changelog

:cl:  
bugfix: fixed  it showing big bold for a few ghost spawners
/:cl:

2020-05-16 13:03 UTC, Bibby0110 requested changes
Why are you even changing this?
They're big for emphasis

2020-05-16 13:03 UTC, TheGamerdk commented on _maps/RandomRuins/SpaceRuins/spacebar.dmm
> +	flavour_text = "You are a space bartender!</span><b> Time to mix drinks and change lives. Do not leave your post under any circumstances!!";
No introductory span, yet a closing one
Opening bold tag, no closing.

2020-05-16 13:03 UTC, TheGamerdk commented on code/game/objects/structures/ghost_role_spawners.dm
> +	flavour_text = "<span class='What...?</span><b> Where are you? Where are the others? This is still the animal hospital - you should know, you've been an intern here for weeks - but \
Empty class statement, no closing arrow thing.

2020-05-16 13:03 UTC, TheGamerdk commented on code/game/objects/structures/ghost_role_spawners.dm
> +	everyone? Where did they go? What happened to the hospital? And is that <i>smoke</i> you smell? You need to find someone else. Maybe they can tell you what happened."
No closing bold tag, yet an open one on line 265

2020-05-16 13:15 UTC, JamieD1 requested changes

2020-05-16 13:15 UTC, JamieD1 commented on _maps/RandomRuins/SpaceRuins/spacebar.dmm
> +	flavour_text = "You are a space bartender!</span><b> Time to mix drinks and change lives. Do not leave your post under any circumstances!!";
Either create a new span open tag or remove it. Also remove the bold tag or close it.

2020-05-16 13:15 UTC, JamieD1 commented on code/game/objects/structures/ghost_role_spawners.dm
> +	everyone? Where did they go? What happened to the hospital? And is that <i>smoke</i> you smell? You need to find someone else. Maybe they can tell you what happened."
If you are removing the bold close tag then remove the b open tag.

2020-05-16 13:20 UTC, JamieD1 commented on code/game/objects/structures/ghost_role_spawners.dm
> +	flavour_text = "<span class='What...?</span><b> Where are you? Where are the others? This is still the animal hospital - you should know, you've been an intern here for weeks - but \
<span class='What...?</span>

This needs to be completely redone..

2020-05-21 03:18 UTC, alexkar598 requested changes
I can understand why you would want to remove the big part of it, but what does the bold do bad?

Either come up with a reason to remove it or close this PR

2020-05-26 19:45 UTC, boodaliboo commented
i dont feel like explaining to alex why me removing it is needed

2020-05-26 19:45 UTC, closed without merging