[Admin] Non Lethal Smiting
yogstation13/Yogstation pull request #8540
Opened 2020-05-16 21:21 UTC by JamieD1

Pies

#### Changelog

:cl:  
rscadd: Pies
/:cl:

2020-05-16 21:42 UTC, MegaEmpirical commented
Now make it explode!

2020-05-17 00:05 UTC, ToGWtF commented
speedmerge

2020-05-21 02:38 UTC, Hopekz requested changes
Otherwise ready for merge

2020-05-21 02:38 UTC, Hopekz commented on code/modules/admin/verbs/randomverbs.dm
> +			if(confirm == "Yes")
```suggestion
			var/confirm = alert(usr, "Send honk message?", "Honk Message", "Yes", "No")
			if(confirm == "Yes")
			var/mob/living/carbon/C = target
```
Why:
If you quit the game before answering your text box that target variable will always be set.
Does it matter in the long run? No, but it looks prettier

2020-05-21 22:44 UTC, JamieD1 commented
Hows that

2020-05-23 14:16 UTC, Hopekz approved these changes

2020-05-23 14:16 UTC, merged