adds a new fermentable drink meant for ashwalkers to create
yogstation13/Yogstation pull request #8550
Opened 2020-05-17 22:42 UTC by boodaliboo

this pr adds cactus cooler a decently alcoholic drink made from fermenting cactus it also heals a minor amount of burn damage hopefully encouraging the use of lavaland fermenting
#### Changelog

:cl:  
rscadd: Added a new alcoholic drink thats fermentable from lavaland cacti
/:cl:

2020-05-17 22:44 UTC, boodaliboo commented
ill fix that error when i come back

2020-05-18 23:54 UTC, Ktlwjec1 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	description = "an alcoholic drink created by fermenting cactus, its color is odd looking"
"**A**n alcoholic drink created by fermenting cactus, its color is odd looking**.**"

2020-05-18 23:54 UTC, Ktlwjec1 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The byproduct of fermenting a cactus. For those wanting a refreshing drink in a barren wasteland"
wasteland**.**

2020-05-19 03:35 UTC, boodaliboo commented
WHY DID IT FAIL I LITTERALLY ONLY FIXED SPELLING ERRORS

2020-05-19 04:05 UTC, boodaliboo commented
thanks ktl

2020-05-21 20:21 UTC, JamieD1 approved these changes

2020-05-22 12:17 UTC, alexkar598 requested changes

2020-05-22 12:17 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +		. = 1
```suggestion
	if(M.getFireLoss() && prob(10))
		M.heal_bodypart_damage(0, 1)
		. = 1
```
The first argument is bruteloss, the second one is fireloss

2020-05-22 17:47 UTC, boodaliboo commented
i think i commited them right

2020-05-24 23:45 UTC, merged

2020-05-25 00:32 UTC, Marmio64 commented
should make a new PR to modify this to heal a minor bit of brute and burn since eating cactus does that on its own