Standardises null
yogstation13/Yogstation pull request #8554
Opened 2020-05-18 03:57 UTC by Hopekz

We shouldn't do it both ways.
Pick one and stick to it.

2020-05-19 12:23 UTC, JamieD1 approved these changes
Is this standards I see?

2020-05-21 20:32 UTC, JamieD1 requested changes

2020-05-21 20:32 UTC, JamieD1 commented on code/datums/beam.dm
>  	if(isnull(timing_id))
Alot of isnull(

Can you change them too?!? 👍

2020-05-22 13:01 UTC, alexkar598 commented
!X is not the same as X == null

!X:
0: true
"yeet": false
null: true

X == null:
0: false
"yeet": false
null: true

2020-05-22 13:01 UTC, closed without merging