ports hippie viro symptoms
yogstation13/Yogstation pull request #8558
Opened 2020-05-18 05:06 UTC by boodaliboo

original pr https://github.com/HippieStation/HippieStation/pull/7546
Deoxyribonucleic Acid Restoration The virus repairs the host's genome, purging negative mutations.
Tissue Regrowth The virus recycles dead and burnt tissues, speeding up the healing of damage caused by burns.
"Flesh Mending The virus rapidly mutates into body cells, effectively allowing it to quickly fix the host's wounds.
Viral aggressive metabolism The virus sacrifices its long term survivability to nearly instantly fully spread inside a host.  The virus will start at the last stage, but will eventually decay and die off by itself.
#### Changelog

:cl:  
rscadd: ports  some hippie viruses
/:cl:

2020-05-19 21:03 UTC, aaqe commented
Don't do this, virology currently has a great healing symptom that knocks you down for a bit before you revive. Old school viro was op and you could easily space walk with it.

2020-05-21 20:48 UTC, JamieD1 requested changes

2020-05-21 20:48 UTC, JamieD1 commented on code/datums/diseases/advance/symptoms/heal.dm
> +
Spaces

2020-05-22 12:50 UTC, alexkar598 commented
Hippiestation powercrepe

2020-05-22 12:50 UTC, closed without merging