just checking if this passes travis ill change the title if this works for now ignore
yogstation13/Yogstation pull request #8561
Opened 2020-05-18 07:35 UTC by boodaliboo

### Intent of your Pull Request

Explain what the purpose of your PR is.
Mention if you tested your changes. If you changed a map, make sure you used the mapmerge tool.

Mention if your PR is related to an issue.
You can type "Fixes issue #6" and issue 6 will be automatically closed when your pull request is merged. This is much easier for everyone.

Edit the changelog at the bottom for changes that are noticeable by the players. Remove it if this isn't the case.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.
Prefix the PR title with [admin] if it's something admin related.
Prefix the PR title with [s] if you are fixing an exploit so it is not announced on discord and the server.

#### Changelog

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images  
spellcheck: fixed a few typos  
experimental: This is experimental  
/:cl:

2020-05-18 07:40 UTC, boodaliboo commented
what is this reverting?

2020-05-18 21:53 UTC, aaqe commented
This doesn't seem like real medicine at all.

2020-05-19 00:24 UTC, boodaliboo commented
> This doesn't seem like real medicine at all.

and? ss13 medicine acts nothing like real medicine

2020-05-19 01:58 UTC, ToGWtF commented
>Heal all organs completely.
Dont. Make it heal a bit, or even quite a lot of damage, but don't let it literally cure heart disease with a few  bandaids.

2020-05-19 21:14 UTC, aaqe commented
I mean to say this isn't future tech and it's stupid.

2020-05-21 21:23 UTC, JamieD1 approved these changes

2020-05-22 12:52 UTC, alexkar598 requested changes
Erm... Why did you duplicate the proc at line 80 instead of changing it....

2020-05-22 17:45 UTC, boodaliboo commented
> Erm... Why did you duplicate the proc at line 80 instead of changing it....

im not sure what to do if i do remove it

2020-05-27 17:33 UTC, JamieD1 commented
Sent changes in discord

2020-05-28 10:06 UTC, Ktlwjec1 commented on code/modules/surgery/organ_manipulation.dm
> +			display_results(user, target, "<span class='notice'>You succesfully heal [target]'s [parse_zone(target_zone)]'s organs.</span>",
successfully

2020-06-08 02:08 UTC, alexkar598 requested changes
I have no words, this doesnt heal the person at all

2020-06-08 02:08 UTC, alexkar598 commented on code/modules/surgery/organ_manipulation.dm
> +					return -1
This should be before the M.use(3) check

2020-06-11 20:15 UTC, JamieD1 commented
@boodaliboo Update this or I close it

2020-06-14 17:32 UTC, closed without merging

2020-07-03 13:52 UTC, BobJoga commented
While i get giddy about my work being ported to other codebases, this PR does not port along the bugfixes and improvements i did to this code