Ports "Component-izes Altar of God Functionality" and adds the altar to Boxstation
yogstation13/Yogstation pull request #8582
Opened 2020-05-19 08:21 UTC by TheGamerdk

### Intent of your Pull Request

Ports https://github.com/tgstation/tgstation/pull/50708

Also adds the altar to boxstation, so it's not admin-only anymore

#### Changelog

:cl:  
rscadd: The Chaplain can now start his own religious following in the Chapel!
/:cl:

2020-05-19 22:53 UTC, SomeguyManperson commented
aa don't remove the chair it's vitally important

2020-05-20 08:57 UTC, SomeguyManperson requested changes
put the chair back and move the altar otherwise the chaplain has nowhere to sit

2020-05-20 09:25 UTC, TheGamerdk commented
Done

2020-05-20 17:48 UTC, SomeguyManperson approved these changes

2020-05-20 17:48 UTC, merged