makes all virus chems deal toxin damage when ingested
yogstation13/Yogstation pull request #8586
Opened 2020-05-19 19:16 UTC by boodaliboo

your drinking bacteria plasma mixed with bacteria mutagen mixed with bacteria and uranium infused liquids, you will feel sick
#### Changelog

:cl:  
tweak: makes virus chems deal toxin damage
/:cl:

2020-05-19 19:28 UTC, boodaliboo commented
fuck

2020-05-19 19:29 UTC, boodaliboo commented
why did you put thumbs down xantam is it because i thumbs downed yours?

2020-05-19 19:29 UTC, Xantam-13 commented
Don't like this. There are not enough doctors in game who actually know what they are doing, enough to treat serious toxin damage from virologists or the like.

2020-05-19 19:34 UTC, boodaliboo commented
> Don't like this. There are not enough doctors in game who actually know what they are doing, enough to treat serious toxin damage from virologists or the like.

this does incredibly little toxic damage and these work exactly like normal chem just drink some charcoal

2020-05-19 20:17 UTC, MegaEmpirical commented
They'll manage or die trying. MERGE.

2020-05-20 19:37 UTC, boodaliboo commented
still having trouble figuring out the errors help is appreciated

2020-05-21 04:37 UTC, Hopekz requested changes
- useless if statements that cannot possibly be not true.
- You don't need to return true for these; it doesn't hurt but a weird practice and inconsistent with rest of codebase.

2020-05-21 04:37 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +
```suggestion
	M.adjustToxLoss(toxpwr*REM, 0)
	..()

```

2020-05-21 04:37 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
```suggestion
	M.adjustToxLoss(toxpwr*REM, 0)
	..()

```

2020-05-21 04:37 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
```suggestion
	M.adjustToxLoss(toxpwr*REM, 0)
	..()

```

2020-05-21 04:37 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
```suggestion
	M.adjustToxLoss(toxpwr*REM, 0)
	..()

```

2020-05-21 04:37 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +
```suggestion
	M.adjustToxLoss(toxpwr*REM, 0)
	..()

```

2020-05-21 04:37 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +
```suggestion
	M.adjustToxLoss(toxpwr*REM, 0)
	..()

```

2020-05-21 04:37 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +
```suggestion
	M.adjustToxLoss(toxpwr*REM, 0)
	..()

```

2020-05-21 04:37 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +
```suggestion
	M.adjustToxLoss(toxpwr*REM, 0)
	..()

```

2020-05-22 20:38 UTC, boodaliboo commented
thanks hopek

2020-05-22 20:54 UTC, Hopekz requested changes
This is to make it compile
You keep defining the same variable over and over.

Might as well just put the values inside of the adjustToxLoss proc but you can do whatever other solution you make for this like making this an actual parent variable and not defining it every time instead.

2020-05-22 20:54 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +
```suggestion
	taste_description = "sourness"

/datum/reagent/toxin/mutagen/mutagenvirusfood/on_mob_life(mob/living/carbon/M)
	M.adjustToxLoss(1.5*REM, 0)
	..()

```

2020-05-22 20:54 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
```suggestion
	taste_description = "sweetness"
	
/datum/reagent/toxin/mutagen/mutagenvirusfood/sugar/on_mob_life(mob/living/carbon/M)
	M.adjustToxLoss(0.5*REM, 0)
	..()
```

2020-05-22 20:54 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
```suggestion
	taste_description = "bitterness"
	
/datum/reagent/medicine/synaptizine/synaptizinevirusfood/on_mob_life(mob/living/carbon/M)
	M.adjustToxLoss(0.25*REM, 0)
	..()
```

2020-05-22 20:54 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
```suggestion
	taste_description = "bitterness"
	taste_mult = 1.5
	
/datum/reagent/toxin/plasma/plasmavirusfood/on_mob_life(mob/living/carbon/M)
	M.adjustToxLoss(REM, 0)
	..()
```
Multiplying something by 1 is useless

2020-05-22 20:54 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
```suggestion
	taste_description = "bitterness"
	taste_mult = 1.5

/datum/reagent/toxin/plasma/plasmavirusfood/weak/on_mob_life(mob/living/carbon/M)
	M.adjustToxLoss(0.5*REM, 0)
	..()
```

2020-05-22 20:54 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
```suggestion
	taste_description = "the inside of a reactor"

/datum/reagent/uranium/uraniumvirusfood/on_mob_life(mob/living/carbon/M)
	M.adjustToxLoss(2.5*REM, 0)
	..()
```

2020-05-22 20:54 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
```suggestion
	color = "#2FF2CB" // rgb: 47,242,203
	taste_description = "the inside of a reactor"

/datum/reagent/uranium/uraniumvirusfood/unstable/on_mob_life(mob/living/carbon/M)
	M.adjustToxLoss(2*REM, 0)
	..()
```

2020-05-22 20:54 UTC, Hopekz commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
```suggestion
	taste_description = "the inside of a reactor"

/datum/reagent/uranium/uraniumvirusfood/stable/on_mob_life(mob/living/carbon/M)
	M.adjustToxLoss(1.5*REM, 0)
	..()
```

2020-05-23 19:50 UTC, Hopekz approved these changes
Code checks out. Going to let this marinate for a bit to collect opinions

2020-05-26 16:54 UTC, Hopekz commented
Let this marinate for 3 additional days.
Seems good from what I can tell I'll let us give this a try.

2020-05-26 16:54 UTC, merged