adds a weed cookie
yogstation13/Yogstation pull request #8593
Opened 2020-05-19 22:42 UTC by boodaliboo

the title is self explanatory
#### Changelog

:cl:  
rscadd: Adds weed cookie
/:cl:

2020-05-21 01:32 UTC, Hopekz requested changes
Undocumented changes in recipes_pastry.dm
Remove them or document them.

2020-05-28 10:05 UTC, Ktlwjec1 commented on code/modules/food_and_drinks/food/snacks_pastry.dm
> +	desc = "A cookie mixed with weed, often called a edible."
called an edible.

2020-06-01 17:27 UTC, SomeguyManperson commented
did you just copy the entire recipies_pastry.dm file from some other codebase and paste it over ours

2020-06-04 07:47 UTC, boodaliboo commented
> did you just copy the entire recipies_pastry.dm file from some other codebase and paste it over ours

no?

2020-06-05 21:30 UTC, JamieD1 requested changes
Undocumented changes

2020-06-10 00:37 UTC, boodaliboo commented
> Undocumented changes

i moved everything up in recipes?

2020-06-11 20:16 UTC, JamieD1 commented
Can you just redo it without moving everything around? Just add what you need to..
@boodaliboo

2020-06-15 02:45 UTC, boodaliboo commented
i forgot

2020-06-15 02:45 UTC, closed without merging