Pixel shifting fixes 2
yogstation13/Yogstation pull request #8621
Opened 2020-05-21 21:49 UTC by ReddTheDragon

Ports pixelshifting reset code, also fixes ais being able to pixelshift
:cl:  
rscadd: Pixel shifting now automatically resets when a player moves
rscdel: AIs cannot pixelshift
bugfix: **AIs cannot pixelshift**  
/:cl:

2020-05-21 22:27 UTC, boodaliboo commented
dumb stupid pr ruining fun

2020-05-21 23:27 UTC, Jarod1200 commented
Pixel shiting is important for ais to communicate with things that don't speak common, preternis, or lizard

2020-05-21 23:42 UTC, Hopekz requested changes
Atomize your PR.
Making the AI not being able to pixelshift at all and putting in a reset for pixelshifting after the pixel shift are 2 separate PR's

2020-05-22 04:17 UTC, boodaliboo commented
> Atomize your PR.
> Making the AI not being able to pixelshift at all and putting in a reset for pixelshifting after the pixel shift are 2 separate PR's

atomize i tagree

2020-05-27 18:53 UTC, JamieD1 commented
@ReddTheDragon

2020-06-14 16:06 UTC, alexkar598 approved these changes

2020-06-14 16:06 UTC, merged