adds the flaming moe a new animated bar drink
yogstation13/Yogstation pull request #8630
Opened 2020-05-22 17:16 UTC by boodaliboo

a drink ive wanted to make for months
https://cdn.discordapp.com/attachments/713291733303164938/713302316224086026/2020-05-22_14-08-00.mp4
moe 2 is the one in  use
it currently suppreses hallucinations and lessens stuns slightly and heats you up
and has a small chance to remove some toxins damage
made with tequila creme de menthe and synaptizine heated to 500

#### Changelog

:cl:  
rscadd: Added a new bar drink
mageadd: added animated icons for the flaming moe
/:cl:

2020-05-22 17:23 UTC, boodaliboo commented
can someone rerun travis

2020-05-23 04:18 UTC, iWuna commented
lol, nice

2020-05-23 04:38 UTC, iWuna commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	if(holder.has_reagent(/datum/reagent/toxin/mindbreaker))
why

2020-05-23 04:39 UTC, iWuna approved these changes
Checked code etc, looks fine, but i still dunno why it shold remove LCD from hooman

2020-05-24 21:59 UTC, alexkar598 commented
Not a fan of stun reduction

2020-05-25 02:41 UTC, MacHac commented
Chug Flaming Moes before a fight and be immune to go horizontal for a few minutes?

Also, shouldn't it be the Flaming Homer?

2020-05-26 02:54 UTC, Ktlwjec1 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "a amazing concotion of various different bar drinks and a secret ingredient"
an
concoction

2020-05-26 09:53 UTC, boodaliboo commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	if(holder.has_reagent(/datum/reagent/toxin/mindbreaker))
i copypasted some other code or something its like 4 am

2020-05-26 09:54 UTC, boodaliboo commented
> Chug Flaming Moes before a fight and be immune to go horizontal for a few minutes?
> 
> Also, shouldn't it be the Flaming Homer?

it technically should be but flaming moe sounds better

2020-05-28 10:03 UTC, Ktlwjec1 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "an amazing concotion of various different bar drinks and a secret ingredient"
concoction

2020-05-28 18:35 UTC, Hopekz commented
Why is this PR adding like 40 icons to icons/drinks.dmi?

2020-06-03 07:45 UTC, iWuna commented
> Why is this PR adding like 40 icons to icons/drinks.dmi?

because it's contains over 40 icon animations?

2020-06-05 21:36 UTC, JamieD1 requested changes
Code good, ident needs to review sprites.

2020-06-05 21:56 UTC, nesisknesis approved these changes

2020-06-12 03:44 UTC, merged