Fixes text2ratvar - Unicode broke it - Fixes 8523
yogstation13/Yogstation pull request #8638
Opened 2020-05-22 20:40 UTC by JamieD1

### Intent of your Pull Request

Fixes Clockcult text2ratvar

#### Changelog

:cl:  
bugfix: fixes text2ratvar
/:cl:

2020-05-22 20:41 UTC, Bibby0110 requested changes

2020-05-22 20:41 UTC, TheGamerdk commented on code/__HELPERS/text.dm
> +
space

2020-05-22 20:41 UTC, TheGamerdk commented on code/__HELPERS/text.dm
> +					continue
space

2020-05-22 20:41 UTC, TheGamerdk commented on code/__HELPERS/text.dm
> +
space

2020-05-22 20:41 UTC, TheGamerdk commented on code/__HELPERS/text.dm
> +
tabs*

2020-05-22 20:41 UTC, TheGamerdk commented on code/__HELPERS/text.dm
> +					continue
tabs*

2020-05-22 20:41 UTC, TheGamerdk commented on code/__HELPERS/text.dm
> +
tabs*

2020-05-23 01:05 UTC, Hopekz approved these changes

2020-05-23 07:56 UTC, merged