readds the ability to become a snail person through genetic meltdown and the chemical agents
yogstation13/Yogstation pull request #8642
Opened 2020-05-23 00:23 UTC by boodaliboo

the reason nich made these unavaiable was fixed a while ago
#### Changelog

:cl:  
rscadd: readded the ability to become snail
/:cl:

2020-05-23 00:41 UTC, Hopekz requested changes

2020-05-23 00:41 UTC, Hopekz commented on code/modules/mob/living/carbon/human/species_types/snail.dm
> +	. = .()
```suggestion
	. = ..()
```
Not sure what you're doing here.
It's like saying 1 is 1 pretty sure you meant to do this

Also, it should compile after this

2020-05-23 01:10 UTC, boodaliboo commented
nope

2020-05-23 01:45 UTC, Hopekz requested changes
pt:2
You re-included the file meaning you need to modify it to our new standards.

To make it compile:
modify line 62
from ADD_TRAIT(src, TRAIT_NODROP) to ADD_TRAIT(src, TRAIT_NODROP, CURSED_ITEM_TRAIT)

Also; please test your PR since you cannot have tested it since it didn't compile.

2020-05-23 02:10 UTC, boodaliboo commented
> pt:2
> You re-included the file meaning you need to modify it to our new standards.
> 
> To make it compile:
> modify line 62
> from ADD_TRAIT(src, TRAIT_NODROP) to ADD_TRAIT(src, TRAIT_NODROP, CURSED_ITEM_TRAIT)
> 
> Also; please test your PR since you cannot have tested it since it didn't compile.

i truthfully thought there would be no reason to test it as it was just commenting out things disabled

2020-05-24 12:42 UTC, nichlas0010 commented
>the reason nich made these unavaiable was fixed a while ago

Please don't lie. The reason I made these unavailable is because snails are bad.

2020-05-26 17:00 UTC, Hopekz approved these changes

2020-05-26 17:12 UTC, Hopekz commented
Going to let this PR marinate just in-case someone has any additional opinions on if this shouldn't be merged.

2020-05-28 01:41 UTC, merged