adds the moscow mule (port) and fixes sol dry having no sprite
yogstation13/Yogstation pull request #8648
Opened 2020-05-23 06:59 UTC by boodaliboo

original pr https://github.com/tgstation/tgstation/pull/48466/files
moscow mule is  just alcoholic no special effect this time
made with sol dry, vodka, lime juice, and ice

#### Changelog

:cl:  
rscadd: Added a new alcoholic drink
bugfix: fixed sol drys lack of sprite 
imageadd: added moscow mule sprite
/:cl:

2020-05-23 14:14 UTC, JamieD1 approved these changes

2020-05-24 20:53 UTC, Ktlwjec1 requested changes
Remove the new sol dry sprite, I fixed that already.

2020-05-24 21:53 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	taste_description = "refreshing spiciness"
```suggestion
	taste_description = "COMMUNISM"
```

2020-05-24 21:53 UTC, alexkar598 approved these changes

2020-05-24 21:54 UTC, alexkar598 commented
Fix the corn flakes

2020-06-05 21:52 UTC, JamieD1 commented
@boodaliboo

2020-06-05 23:40 UTC, closed without merging