Adds Syndicate Frying Basket, role restricted cook traitor item.
yogstation13/Yogstation pull request #8665
Opened 2020-05-23 21:37 UTC by Takahiru

While sitting on the toilet, a revelation appeared to me, what if I just add the ability to fry whole corpses? So I tried.

Adds a 10 TC syndicate frying basket traitor item, it allows the frying of any corpse whole, also strips the clothing off of dead corpses.

:cl:  
rscadd: Added new things  
imageadd: added some icons and images  
/:cl:

![frying basket](https://user-images.githubusercontent.com/30001910/82741010-02cf3300-9d1c-11ea-85a9-ccd426cb4fc1.png)

2020-05-23 21:39 UTC, DoubleTapper approved these changes

2020-05-24 07:38 UTC, Jarod1200 commented
Can you still throw the fried corpse and knock people down?

2020-05-24 15:41 UTC, JamieD1 requested changes

2020-05-24 15:41 UTC, JamieD1 commented on code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
> +				icon_state = "syndie_fryer_on"
```
icon_state = "fryer_on"
if(superfry)
    icon_state = "syndie_fryer_on"
```

2020-05-24 15:41 UTC, JamieD1 commented on code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
> +				icon_state = "syndie_fryer_off"
```
icon_state = "fryer_off"
if(superfry)
       icon_state = "syndie_fryer_off"
```

2020-05-24 15:41 UTC, JamieD1 commented on code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
> +
Space

2020-05-24 15:41 UTC, JamieD1 commented on code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
> +					icon_state = "syndie_fryer_on"
```
icon_state = "fryer_on"
if(superfry)
       icon_state = "syndie_fryer_on"
```

2020-05-24 15:56 UTC, JamieD1 commented on code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
> -
One space was fine!

2020-05-24 15:56 UTC, JamieD1 approved these changes

2020-05-24 15:58 UTC, Takahiru commented on code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
> -
heck

2020-05-24 17:54 UTC, Takahiru commented
@jarod1200 no it acts like a normal fried item

2020-05-25 00:18 UTC, ilikesaying commented
time to deep fry the clown

2020-05-25 12:32 UTC, Tipy1802 commented
10 TC is a bit much for what's essentialy a meme item. It does not really help you archiev your goals since to get fried the bodies need to be dead already. Actually using it may as well be a shooting yourself on the foot since it's very obvious when you use it (the grilles of the fryer become red) and just the exictance of fully fried corpses is a dead giveaway that you are a traitor.

Maybe make it cost 5 or 7 TC and maybe give it the abillity to fry people alive

2020-05-25 14:46 UTC, Takahiru commented
I was already thinking about changing the cost, it is in function just a slightly better gibber because you don't need to strip the corpse.

2020-05-25 20:39 UTC, Hopekz commented
> 10 TC is a bit much for what's essentialy a meme item.

This is a pretty good item from what I can tell. 
It allows you to fry and eat bodies whole to dispose of them with less trace than sticking them in a grinder.

2020-05-25 20:54 UTC, Jarod1200 commented
How hard can you valid the chef for having a red fry basket?

2020-05-25 21:02 UTC, Hopekz commented
> How hard can you valid the chef for having a red fry basket?

If it was meant to be "hidden" I'd imagine it would not be easily distinguishable just by looking at it.

2020-05-27 21:36 UTC, Hopekz approved these changes

2020-05-27 21:36 UTC, merged