Logs Bluespace Artillery better
yogstation13/Yogstation pull request #8677
Opened 2020-05-24 16:59 UTC by ToGWtF

### Intent of your Pull Request
Logs firing of Bluespace Artillerey to investigate panel so we dont have to href dive

2020-05-31 23:00 UTC, JamieD1 commented
Why the fuck ktl? this is all code change, bloody brick.

2020-05-31 23:00 UTC, JamieD1 approved these changes

2020-06-02 22:27 UTC, alexkar598 requested changes
log it to LOG_GAME instead of yet another investigate for something that happens once in 100 rounds

2020-06-04 21:42 UTC, JamieD1 approved these changes

2020-06-08 01:09 UTC, alexkar598 approved these changes

2020-06-08 01:09 UTC, merged