PASSCOMP flag for mobs items - Pass through computers
yogstation13/Yogstation pull request #8692
Opened 2020-05-25 15:36 UTC by JamieD1

#### Changelog

Added PASSCOMP - Pass through computers for mobs/items

Feel free to suggest changes to items/mobs that should or should not have it.

:cl:  
rscadd: Added PASSCOMP - Pass through computers for mobs/items
/:cl:

2020-05-25 16:30 UTC, MacHac commented
Wouldn't it make more sense to have a general PASSMACHINE that covers all full-tile machinery that blocks movement but not air?  Unless you're creating a very literal computer bug mob.

2020-05-25 16:42 UTC, JamieD1 commented
> Wouldn't it make more sense to have a general PASSMACHINE that covers all full-tile machinery that blocks movement but not air? Unless you're creating a very literal computer bug mob.

That was my original idea, however I cant remember now why I didnt do it, bear with me whilst I try and remember.

2020-05-25 20:41 UTC, Hopekz commented
+1 to Mac's comment.

Very odd to make a passthrough flag for only 1 object can't really think of too many reasons you'd apply this in particular unless you do have that reason in mind that I'm missing.

2020-05-28 01:55 UTC, alexkar598 requested changes
Having animals pass through things like computers and antimatter engines/smes feels too weird for me. Remove that please

2020-05-28 08:18 UTC, JamieD1 commented
> Having animals pass through things like computers and antimatter engines/smes feels too weird for me. Remove that please

One of the whole points was to let flying mobs go over computers, I got bullied by hopek to make it machines :(

2020-05-29 01:36 UTC, alexkar598 commented
Since when do cats fly?

2020-05-29 17:15 UTC, JamieD1 commented
> Since when do cats fly?

The whole cats on keyboard joke, get it? get it?

2020-06-08 02:59 UTC, alexkar598 requested changes

2020-06-08 02:59 UTC, alexkar598 commented on code/_globalvars/bitfields.dm
> +		"PASSMACHINES" = PASSMACHINES
You forgot to add passcomputers to the list

2020-06-15 15:16 UTC, alexkar598 approved these changes

2020-06-15 15:17 UTC, alexkar598 commented
Merge cornflakes

2020-06-17 22:07 UTC, merged