Da mafia update. Mob nicknames, new fedoras, suits! (port)
yogstation13/Yogstation pull request #8699
Opened 2020-05-26 03:07 UTC by boodaliboo

https://github.com/tgstation/tgstation/pull/49029 ORIGINAL PR
quote from original pr "This PR adds a new contraband crate to cargo; the Cosa Nostra starter pack.
The crate contains four complete mafia outfits, four pictures of the virgin Mary, 0-4 Italian moustaches and 10% chance of a single switchblade.

Burning a picture of the Madonna, inducts you into the mafia, letting you pick a mafia nickname that is inserted between your first and last name.

Lorenzo Robusto -> Lorenzo "The Carp" Robusto

adds three new clothing items: the beige suit, beige fedora and white fedora.

The type of outfits you get from the crates are randomized about 60% of the outfits are the black version, about 15% are white and 15% are beige."
end quote
i just want to see if theres any travis errors rn
#### Changelog

:cl:  
rscadd: Added a new cargo crate and a fun gimmick to join the mafia (not a actual antag)
imageadd: added various new sprites
/:cl:

2020-05-26 03:09 UTC, boodaliboo commented
some features of the original pr may not be here like resprited outfits as i had difficulty telling what we already had and whats new

2020-05-26 03:46 UTC, boodaliboo commented
this worked fine when i tested it personally but please tell me if it fucks up in anyway

2020-05-28 09:55 UTC, Ktlwjec1 requested changes
capcarapace icons are changed with this too

2020-05-28 10:01 UTC, Ktlwjec1 commented on code/game/objects/items/miscellaneous.dm
> +	joe.say("My soul will burn like this saint if I betray my familiy. I enter alive and I will have to get out dead.", forced = /obj/item/virgin_mary)
family

2020-05-31 23:07 UTC, JamieD1 requested changes

2020-05-31 23:07 UTC, JamieD1 commented on code/game/objects/items/miscellaneous.dm
> +	if(!ignition_msg)
```suggestion
	if(!ignition_msg || resistance_flags & ON_FIRE)
```

2020-05-31 23:07 UTC, JamieD1 commented on code/game/objects/items/miscellaneous.dm
> +	if(!ignition_msg)
Might as well combine them

2020-05-31 23:07 UTC, JamieD1 commented on code/game/objects/items/miscellaneous.dm
> +	if(used_up)
```suggestion
	if(used_up || !isliving(user) || !user.mind)
```

2020-05-31 23:07 UTC, JamieD1 commented on code/game/objects/items/miscellaneous.dm
> +	if(space_position)//Can we find a space?
```suggestion
    new_name = "[joe.real_name] \"[nickname]\""
	if(space_position)//Can we find a space?
	    new_name = "[copytext(joe.real_name, 1, space_position)] \"[nickname]\" [copytext(joe.real_name, space_position)]"
```

2020-05-31 23:07 UTC, JamieD1 commented on code/game/objects/items/miscellaneous.dm
> +	if(space_position)//Can we find a space?
Might as well get rid of the else

2020-06-05 21:55 UTC, JamieD1 commented
@boodaliboo

2020-06-11 21:08 UTC, JamieD1 requested changes

2020-06-11 21:08 UTC, JamieD1 commented on code/game/objects/items/miscellaneous.dm
> +		return
```suggestion
```
Duplicate

2020-06-11 21:08 UTC, JamieD1 commented on code/game/objects/items/miscellaneous.dm
> +		return
```suggestion
```
Duplicate

2020-06-11 21:08 UTC, JamieD1 commented on code/game/objects/items/miscellaneous.dm
> +	var/nickname = input(joe, "Pick a nickname", "Mafioso Nicknames") as text|null
Sanitise the input

2020-06-15 02:45 UTC, boodaliboo commented
god i hate forgetting about these and being to lazy to fix them

2020-06-15 02:45 UTC, closed without merging