EMP act for cameras
yogstation13/Yogstation pull request #8701
Opened 2020-05-26 03:18 UTC by Hopekz

Adds an EMP effect to cameras.

When EMP'd the camera will turn off for 60 seconds divided by EMP level (lower is more powerful)

So a level 1 EMP will turn it off for 60 seconds and a level 2 EMP will turn it off for 30 seconds

#### Changelog

:cl:  
rscadd: Cameras now have an EMP effect 
/:cl:

2020-05-26 04:27 UTC, Marmio64 commented
i thought they already had a emp effect....

2020-05-26 04:33 UTC, Hopekz commented
> i thought they already had a emp effect....

See? Seemless feature that everyone just assumed was there!
10/10 best PR in the world

2020-05-27 20:21 UTC, JamieD1 approved these changes

2020-05-28 01:51 UTC, alexkar598 requested changes
Use timers instead of sleep

2020-05-29 02:23 UTC, Marmio64 commented
> > i thought they already had a emp effect....
> 
> See? Seemless feature that everyone just assumed was there!
> 10/10 best PR in the world

but, its something that does exist. When you EMP cameras they have a chance to deactivate for a long period, turning blue, and then they eventually turn back on (which takes forever)

2020-05-29 15:57 UTC, SomeguyManperson commented
This is for handheld cameras not security cameras

2020-05-31 22:15 UTC, JamieD1 approved these changes

2020-06-02 22:20 UTC, merged