adds a coder line to the changelog crediting all our coders
yogstation13/Yogstation pull request #8738
Opened 2020-05-28 09:42 UTC by boodaliboo

the changelog credits spriters and mappers but not coders
@ me if you want to be added to the list
#### Changelog

:cl:  
rscadd: Added coders to the changelog
/:cl:

2020-05-28 10:32 UTC, AsV9 commented
The list of people that actively contributes to the server changes so frequently it's probably better to just have a link going to the contributors page and just leave it at that in my opinion.

2020-05-28 10:33 UTC, AsV9 commented on html/changelog.html
> +			<font size='2'><b>Coders:</b> Boodaliboo, Xoxoeyes, Nickvr, MacHac, ThatOneGuyWithTheFace, Jcat, Phpminor, JamieD12, Autisticfroggy r3d<br></font> // for some of these i copied there discord usern
Comments in HTML are `<!-- comment -->`.

2020-05-28 11:07 UTC, TheGamerdk commented
Why is bood on the list but not me

2020-05-28 11:45 UTC, ThatLing commented
@AsV9 There is already a link to that 2 lines up

2020-05-28 11:45 UTC, ThatLing commented on html/changelog.html
>  			<font size='2'><b>Currently Active GitHub contributor list:</b> <a href='https://github.com/yogstation13/Yogstation/graphs/contributors'>-Click Here-</a><br></font>
As AsV9 mentioned, this is a much better solution. Useless PR imho

2020-05-28 12:27 UTC, Hopekz commented
The turnaround for coders too frequent for static names imo

2020-05-29 06:04 UTC, boodaliboo commented
> The turnaround for coders too frequent for static names imo

i have no clue what this means

2020-05-30 13:26 UTC, jcatjmeow commented
I thought the changelog was broken and didn't update

2020-05-31 23:24 UTC, JamieD1 requested changes

2020-05-31 23:24 UTC, JamieD1 commented on html/changelog.html
> +			<font size='2'><b>Coders:</b> Boodaliboo, Xoxoeyes, Nickvr, MacHac, ThatOneGuyWithTheFace, Jcat, Phpminor, JamieD12, Autisticfroggy, TheGamer01, Hopek r3d<br></font>
```suggestion
			<font size='2'><b>Coders:</b> Boodaliboo, Xoxoeyes, Nickvr, MacHac, ThatOneGuyWithTheFace, Jcat, Phpminor, JamieD12, Autisticfroggy, TheGamer01, Hopek, r3d<br></font> 
```

2020-06-02 23:12 UTC, alexkar598 commented
Too many people to have this be a thing

2020-06-02 23:12 UTC, closed without merging