Mjor's clone attack now respects armor and gives a message
yogstation13/Yogstation pull request #8751
Opened 2020-05-29 18:58 UTC by MacHac

### Intent of your Pull Request
Mjor the Creative has a clone attack, where he spawns a bunch of clones and deals a large amount of damage if you hit one.

I have two issues with this attack.  First of all, it ignores armor and magically applies 50(!) brute damage.  Second of all, it doesn't actually tell you that you take damage from killing the clones; I had to go code diving to figure out how he was hitting so hard.

Hence, his attack now does 40 damage, respects armor, and gives a nice big bold message telling you you're taking damage.  I'm open to discussion on how much damage it should do, but 40 seems like a reasonable baseline with armor.

#### Changelog
:cl:  
tweak: Mjor the Creative's clones have been stripped of their magic and told to telegraph their attacks better.
/:cl:

2020-05-30 07:46 UTC, SomeguyManperson commented
it should probably have some AP so it still deals damage if someone brings good armor

2020-05-31 22:40 UTC, JamieD1 approved these changes

2020-06-02 22:34 UTC, alexkar598 requested changes

2020-06-02 22:34 UTC, alexkar598 commented on code/modules/mob/living/simple_animal/hostile/bosses/paperwizard.dm
> +		for(var/mob/living/carbon/L in range(5,src))
Undocumented changes, this makes slimes and other xenobio mobs completely immune to the attack. Document it or remove the change

2020-06-03 19:03 UTC, MacHac commented on code/modules/mob/living/simple_animal/hostile/bosses/paperwizard.dm
> +		for(var/mob/living/carbon/L in range(5,src))
That actually works in Mjor's favor, it means a damaged clone won't kill all his nearby minions.  I call that an acceptable trade-off for making sentient neutral mobs immune to the blowback from this one attack.

In practice, the list of things that can't be cheesed with neutral xenomobs is short, Mjor is hard to get to, and the fight isn't hard enough to push people into exploits.  It's plausible that this weakness will _never_ be exploited, especially since neutral mobs aren't immune to Mjor's other attacks or his minions with 10mm pistols.

2020-06-08 01:41 UTC, alexkar598 approved these changes

2020-06-08 01:41 UTC, merged