Stealth bloodsucking as vampire
yogstation13/Yogstation pull request #8759
Opened 2020-05-30 09:13 UTC by SomeguyManperson

see #8655 except without 200 commits
Vampires now have slight variation to their suck speed dependent on grab strength
not grabbing: stealth suck; vampire will not give off any blatantly obvious tells that they are a vampire, suck speed reduced to half, vampire will be alerted when they are about to pass the blood volume danger threshold, every successful suck afterwards will alert the victim while stealth and suck remain intact
passive or aggressive grab: normal sucking speed; no changes
neck or kill grab: vampire sucks 50% faster
These all smoothly transition into eachother except for anything into stealth because what's the point of going from not stealth to stealth
:cl:
rscadd: Vampire suck speed now has three different variations depending on grab strength
rscadd: Vampires now have a sneaky way to extract blood from the unwitting if they aren't grabbing them
/:cl:

2020-05-30 11:43 UTC, wejengin2 commented
Stealth is just bluespace fangs

2020-05-30 17:14 UTC, Marmio64 commented
i tried the other one before while it was test merged and it didnt work, have you changed anything that could've fixed it?

2020-05-30 18:26 UTC, SomeguyManperson commented
Yes it is now actually tested and from what I can tell functional

2020-05-31 22:50 UTC, JamieD1 requested changes

2020-05-31 22:50 UTC, JamieD1 commented on yogstation/code/datums/antagonists/vampire.dm
> +			blood_coeff = 0.8 //20 blood gain at base for living, 30 with aggressive grab, 10 with stealth
```suggestion
			blood_coeff = 0.8 //20 blood gain at base for living, 30 with aggressive grab, 10 with stealth
			if(H.stat == DEAD)
			    blood_coeff = 0.2 //5 blood gain at base for dead, 7 with aggressive grab, 2 with stealth
```

2020-06-02 23:16 UTC, merged