Heads of Staff can no longer roll traitor or changeling if its lowpop
yogstation13/Yogstation pull request #8830
Opened 2020-06-06 20:56 UTC by Takahiru

Being able to get funny roundstart all access and a free not suspicious pass because there was no captain is pretty darn powerful, it can pretty much guarantee a greentext may someone roll a head of staff as antag, and there's no captain present. This can create a problem on lowpop.

Controversial!

2020-06-06 21:01 UTC, yacabo commented
What happened to https://github.com/yogstation13/Yogstation/pull/8829?

2020-06-06 21:01 UTC, Takahiru commented
i closed it and reoponed another one

2020-06-06 21:05 UTC, Bibby0110 requested changes
This should probably also be a define somewhere

2020-06-06 21:05 UTC, TheGamerdk commented on code/game/gamemodes/changeling/changeling.dm
> +	if(num_players() < 31)
if(num_players() <= 30)

2020-06-06 21:05 UTC, TheGamerdk commented on code/game/gamemodes/traitor/traitor.dm
> +	if(num_players() < 31)
if(num_players() <= 30)

2020-06-07 00:06 UTC, JamieD1 approved these changes

2020-06-07 04:02 UTC, alexkar598 commented
I'd rather have this be a percentage based on the amounts of players tbh, to keep the oh shit he might be a baddie but without the hes a baddie every round

2020-06-07 07:53 UTC, Jarod1200 commented
Don't forget the free stroll into the armory since there's no sec and you implanted yourself

2020-06-07 15:30 UTC, Takahiru commented
Hopefully this code works, it's hopefully supposed to follow this chart here.
![image](https://user-images.githubusercontent.com/30001910/83973120-3f6d6380-a8b2-11ea-90a9-5e88b81e2e80.png)

2020-06-08 03:22 UTC, ynot01 commented
drats now how will i get antag as 4 pop CE

2020-06-09 23:24 UTC, Firewolf34 commented
Yes omg. It makes it too damn easy. The crew can't do anything against you if you just rush the spare as a head of staff in the first 5 minutes. Just pretend to be Captain... bang, all objectives complete. On Low Pop there's not even the chance anyone will try to stop you.

2020-06-17 21:34 UTC, alexkar598 requested changes

2020-06-17 21:34 UTC, alexkar598 commented on code/game/gamemodes/game_mode.dm
> +	var/list/lowpop_restricted_jobs = list() // Jobs that are restricted because the number of players are too low
Use GLOB.command_positions instead of yet another list

2020-06-17 21:34 UTC, alexkar598 commented on code/game/gamemodes/traitor/traitor.dm
> +	lowpop_restricted_jobs = list("Chief Engineer", "Research Director", "Chief Medical Officer")
~~you said command, wheres QM~~

2020-06-17 21:34 UTC, alexkar598 commented on code/game/gamemodes/traitor/traitor.dm
> +		if(prob((2*1.14^lowpop_amount)-2)) //exponential equation, chance of restriction goes up as pop goes down.
^ is XOR, ** is power

2020-06-18 17:18 UTC, Takahiru commented on code/game/gamemodes/traitor/traitor.dm
> +		if(prob((2*1.14^lowpop_amount)-2)) //exponential equation, chance of restriction goes up as pop goes down.
yes

2020-06-23 20:02 UTC, alexkar598 requested changes

2020-06-23 20:02 UTC, alexkar598 commented on code/game/gamemodes/changeling/changeling.dm
> +		if(prob((2*1.14**lowpop_amount)-2)) //exponential equation, chance of restriction goes up as pop goes down.
You have the thing in the wrong thingy, the way you have it, the more players you have, the less chance you have to have a traitor head

2020-06-29 20:10 UTC, jcatjmeow commented on code/game/gamemodes/changeling/changeling.dm
> +		if(prob((2*1.14**lowpop_amount)-2)) //exponential equation, chance of restriction goes up as pop goes down.
```suggestion
		if(prob((2*1.14**num_players())-2)) //exponential equation, chance of restriction goes up as pop goes down.
```

2020-06-29 20:11 UTC, TheGamerdk commented on code/game/gamemodes/changeling/changeling.dm
> +	lowpop_amount = 30
why are you redefining this here, it's already inherited as 30

2020-06-29 20:11 UTC, TheGamerdk commented on code/game/gamemodes/traitor/traitor.dm
> +	lowpop_amount = 30
see other comment

2020-06-29 20:12 UTC, jcatjmeow commented on code/game/gamemodes/changeling/changeling.dm
> +		if(prob((2*1.14**lowpop_amount)-2)) //exponential equation, chance of restriction goes up as pop goes down.
```suggestion
		if!(prob((2*1.14**num_players())-2)) //exponential equation, chance of restriction goes up as pop goes down.
```

2020-07-04 16:02 UTC, alexkar598 approved these changes

2020-07-04 16:03 UTC, merged