Closets/Bags auto close on closet closing now - Fixes #8821
yogstation13/Yogstation pull request #8832
Opened 2020-06-07 03:29 UTC by JamieD1

Fixes #8821 

Closet/Bags auto close on closet closing now 

#### Changelog

:cl:  
bugfix: 
/:cl:

2020-06-07 03:34 UTC, JamieD1 commented
Tog ETA on merge: 18th
Jamie ETA on merge: 11th

2020-06-15 15:18 UTC, alexkar598 requested changes

2020-06-15 15:18 UTC, alexkar598 commented on code/game/objects/structures/crates_lockers/closets.dm
> +		closeall.close_all()
```suggestion
	for(var/obj/object in contents)
		var/datum/component/storage/closeall = opened.GetComponent(/datum/component/storage)
		if(closeall)
			closeall.close_all()
```

2020-06-15 15:18 UTC, alexkar598 commented on code/game/objects/structures/crates_lockers/closets.dm
> +		closeall.close_all()
Storage is a component... the point is to not need to rely on typepath for behaviour

2020-06-17 21:37 UTC, alexkar598 approved these changes

2020-06-17 21:37 UTC, alexkar598 requested changes

2020-06-17 21:37 UTC, alexkar598 commented on code/game/objects/structures/crates_lockers/closets.dm
> +		var/datum/component/storage/closeall = opened.GetComponent(/datum/component/storage)
```suggestion
		var/datum/component/storage/closeall = object.GetComponent(/datum/component/storage)
```

imsmartok

2020-06-20 20:59 UTC, merged