Makes Luxury Good again
yogstation13/Yogstation pull request #8845
Opened 2020-06-08 17:17 UTC by JamieD1

Makes Luxury Shuttle not shit

- Adds ticket booth between coach and first class for hijackers
- Widens coach by one tile and adds chairs
- Adds shuttle brig, free to enter, still costs to get into first class
- Makes it so boarding cost is mentioned when luxury shuttle purchase is announced
- Makes it so shuttle names are announced when they arrive as another warning you need to pay for this one
- Adds interior windows to coach, with shutters operated from first class
- Moves bathroom for shuttle brig
- Changes ticket forcewalls to scanner gates, function the same but buzz and turn red when someone can't pass and turn blue when they do
- Bunch of other aesthetic changes seen below
Makes it so if the change doesn't go into a human's hands, they will be pulling it behind them instead.
- Makes it so change is placed in-hand, slimes aren't told to pull something when they can't and dragged IDs override worn IDs so a bank account is looked for on them instead

#### Changelog

:cl:  
tweak: Made Luxury shuttle not shit
/:cl:

2020-06-08 17:37 UTC, Hopekz commented
Why reverse the entire aesthetic?
This looks like it should be a separate shuttle people that like the luxury shuttle enjoy the previous red + gold theme.

Also the rich get less space here which is weird because the poor are an afterthought of the luxury shuttle now they're being accommodated more even getting seats and space.

2020-06-08 17:52 UTC, Tipy1802 commented
I like the changes over all but I think the old poor section was better, it was comidically ghetto and shit

2020-06-08 23:13 UTC, overlord12345 commented
Did you remove the no teleport and are the new walls no longer admin walls?

2020-06-14 05:45 UTC, Ktlwjec1 requested changes
Small map things:
- Flip the sink around so it's not facing the wall.
- Plating under the Steerage airlock.
- I suck at explaining so I did an image, move the button to the tile with the blue line, looks neater and makes more sense to be next to the shutters.
![image](https://user-images.githubusercontent.com/59522545/84585696-40e6e080-ae0a-11ea-8dcf-b47fe94362d4.png)
- As ugly as they look, you're going to need firelocks at least around the table, the bar area and inside all the airlocks.

2020-06-22 14:38 UTC, Alexandria404 commented
why add chairs

2020-06-22 14:44 UTC, wejengin2 commented
Give the poor people stools not chairs

2020-06-29 20:10 UTC, JamieD1 commented on code/modules/shuttle/special.dm
> +/obj/effect/forcefield/luxury_shuttle/CanAllowThrough(atom/movable/mover, turf/target)
```suggestion
/obj/machinery/scanner_gate/luxury_shuttle/CanAllowThrough(atom/movable/mover, turf/target)
```

2020-06-29 21:06 UTC, alexkar598 commented on code/modules/shuttle/special.dm
> +/obj/machinery/scanner_gate/luxury_shuttle/Crossed(atom/movable/AM)
```suggestion
/obj/machinery/scanner_gate/luxury_shuttle/auto_scan(atom/movable/AM)
```

2020-06-29 21:15 UTC, merged