gives engineers a medkit and toxins kit in the foyer
yogstation13/Yogstation pull request #8854
Opened 2020-06-09 18:01 UTC by FLME

cargo has a first aid kit, science has a toxins kit, sec even has their own small medical bay, why does engineering not at least have a first aid kit

engineers get injured sort of often and also often end up working around radiation, so this would be a very nice quality of life improvement so that they dont have to walk all the way from the engine room to medical to get healed

also pixel shifts the extra pair of mesons as well as the cell charger to make room

![image](https://user-images.githubusercontent.com/15719834/84183311-51d1d380-aa51-11ea-91fd-a1724ae26c29.png)

#### Changelog

:cl:  
rscadd: first aid kits in engi woooooo
tweak: mesons and cell chargers moved slightly to make room
/:cl:

2020-06-09 18:16 UTC, maxion12345 commented
not sure about this. Medkits were removed from most accessible places due to power gaming. The toxin medkit, though, could be useful. I'd suggest maybe one of the Nanomeds. Its harder to steal a vending machine, and it has all the things you need. Bruise patches, burn patches, charcoal pills, and those squirt cans of medicine.

2020-06-09 18:16 UTC, Hopekz commented
This is a good idea and I like it as a concept.

Because of how the medical system works in our codebase and the power of the white medkit it does however transform them into a mini medbay so balance-wise I have to disagree with this PR because of how powerful the base medkit is.
The effectiveness of base medkit on treating everything is the reason we removed public access medkits.

Possible "improvements":
- Remove the white one and give them only a toxin one
- Make an understocked shitty version of fully stocked medkits
- ???
- secret option nr.4 : redo the whole medical system to where brute patches and ointment can't heal everything

2020-06-09 18:18 UTC, Hopekz commented
> This is a good idea and I like it as a concept.
> 
> Because of how the medical system works in our codebase and the power of the white medkit it does however transform them into a mini medbay so balance-wise I have to disagree with this PR because of how powerful the base medkit is.
> The effectiveness of base medkit on treating everything is the reason we removed public access medkits.
> 
> Possible "improvements":
> 
> * Remove the white one and give them only a toxin one
> * Make an understocked shitty version of fully stocked medkits
> * maybe give them a shittily stocked emergency nanomed
> * ???
> * secret option nr.4 : redo the whole medical system to where brute patches and ointment can't heal everything with full effectiveness vs every other treatment

2020-06-09 19:13 UTC, JamieD1 commented
Add a couple patches or bruise packs and ointments instead,

Also add a fucking shower.

2020-06-09 19:44 UTC, wejengin2 commented
put the medkit in the engine rooms though,  not the foyer

2020-06-09 23:37 UTC, Ratvar commented
I think toxin medikit is the one engineers really need not to die near engine, and every other can disappear

2020-06-10 16:03 UTC, Ktlwjec1 requested changes
I'd suggest either:
- Adding one or two antitoxin pills in storage (where the insuls are kept, they used to be there) or in the foyer, and removing the two full medikits completely.
- Removing the firstaid kit and just having an antitoxin kit. I don't mind if that's kept in the foyer, although it being closer to the engine would be preferable.

2020-06-10 18:33 UTC, Jarod1200 commented
Make it a burn one and a toxin one instead.

2020-06-17 19:55 UTC, JamieD1 commented
@FLME Progress, you going to do the changes or shall I mark this as stale

2020-06-22 08:03 UTC, wejengin2 commented
Closing due to no action by author

2020-06-22 08:03 UTC, closed without merging