The Devil wears a suit and tie
yogstation13/Yogstation pull request #8874
Opened 2020-06-11 17:48 UTC by ToGWtF

### Intent of your Pull Request

Devils have obsessions. Can ONLY give contracts to your obsession
    Species, Gender, Age range, Bloodtype
        This will transfer over to game mode as well, which I haven't touched. Only midround.

Obsessions show up in EndRound screen.

Midround gets its own objectives so the game-mode isn't touched.
     Lower soul amount, or default soul quality objective. (Quality = Sell 1-2 contracts of a specific type)

Midround gets devil jaunt by default

Midround Devil can't fully ascend
    Will make them able to with objective. Rare. Still requires like 7 souls

Most contracts are now RNG what they give you, and will either have a chance of being something bad or will be something good with a bad twist

Employment contracts now have a cooldown on trying to use them on someone.
    Takes longer to spam it as an assistant with a 5% chance of deconverting.
          Get the hecking lawyer.

Power Contract changes
1/3 chance to get Hulk. Also gives gigantism mutation, and spastic brain damage
     Meaning you cannot hide, and you will randomly punch yourself and others.
1/3 to get a one-use full-heal organ.
     Also makes you scared of doctors and anything medical related.
1/3 to give you Telekinesis
    Bro I didnt have time to think of a downside to this

Wealth contract didnt get touched because its mostly useless and what else can I add to it?

Prestige Contract changes
1/3 chance to get an all access ID card
     Will also send an arrivals message that you just arrived as Captain
          Already a Captain? Gonna be some big thinks from him
                  No Captain? Bruh you lucked out enjoy all access
1/3 chance to upload an ion law to the AI.
      Its kinda an ass law but if you are good at argueing you can make it work
1/3 chance to send a CentCom announcement that you are a wanted criminal.
     You wanted fame? You got it bud
          Also going to try to make this spawn spacepol to arrest you

Magic Contract changes
Just read it. I added a few more spells you can get. No real downsides here because I couldn't think of any.

Knowledge Contract changes
1/3 chance for Xray, but you now hallucinate.
1/3 chance for a haunted eightball that lets you get yes or no answers from ghosts.
      But youre now scared of the Chaplain
1/3 chance to see ghosts, but only you

Friend Contract changes
4/5 chance to to be normal
1/5 chance to give you a split personality instead
       You got a friend, but he shares your body
#### Changelog

:cl:  
rscadd: Devils now have obsessions they have to work around. 
tweak: Devil boons have changed. You won't always get what you expected
/:cl:

2020-06-11 17:49 UTC, Jumps0 commented
Great job dude <3
![template](https://user-images.githubusercontent.com/49619518/84422012-41486700-abd1-11ea-90e1-d7c94de46d97.jpg)

2020-06-11 21:37 UTC, boodaliboo commented
good pr

2020-06-11 21:40 UTC, JamieD1 requested changes

2020-06-11 21:40 UTC, JamieD1 commented on code/game/gamemodes/devil/objectives.dm
```suggestion
	explanation_text = "Purchase, and retain control over at least [target_amount] souls."
```

2020-06-11 21:40 UTC, JamieD1 commented on code/game/gamemodes/devil/objectives.dm
>  /datum/objective/devil/soulquantity/check_completion()
```suggestion
/datum/objective/devil/soulquantity/check_completion()
```

2020-06-11 21:40 UTC, JamieD1 commented on code/game/gamemodes/devil/objectives.dm
> +	update_explanation_text()
```suggestion
	explanation_text = "Purchase, and retain control over at least [target_amount] souls."
```

2020-06-11 21:40 UTC, JamieD1 commented on code/modules/events/devil.dm
You might need to give it a weight for it to be spawnable

2020-06-11 21:40 UTC, JamieD1 commented on code/modules/paperwork/contract.dm
> +				id.access = get_all_accesses()+get_all_centcom_access()
Dont think it needs centcom access

2020-06-11 21:40 UTC, JamieD1 commented on code/modules/paperwork/contract.dm
> +				id.access = get_all_accesses()+get_all_centcom_access()
Dont think it needs centcom

2020-06-11 21:40 UTC, JamieD1 commented on code/modules/paperwork/contract.dm
> +			user.gain_trauma(/datum/brain_trauma/severe/split_personality)
Could probably just do <5

2020-06-11 21:40 UTC, JamieD1 commented on code/modules/spells/spell_types/devil.dm
> +
See discord

2020-06-12 03:08 UTC, ynot01 commented
this is amazing

2020-06-12 22:22 UTC, AdamElTablawy commented
I mean, that just makes people less likely to take devil contracts overall since they now come with downsides.

When the downside is, you know, you lose your soul. Make deconverting people also lose their given powers, and it'll fare a little better.

2020-06-22 22:29 UTC, Ratvar commented
Make wealth contract give user a literal midas touch

2020-06-29 20:18 UTC, JamieD1 commented on code/modules/mob/living/living.dm
> +//			M.cure_trauma_type(/datum/brain_trauma/mild/phobia/doctors)
Using it or losing it

2020-07-06 01:56 UTC, alexkar598 requested changes
Didnt fully review it yet

2020-07-06 01:56 UTC, alexkar598 commented on code/game/gamemodes/devil/objectives.dm
> +
Move the whole lessersoul thing below all the code for the soul quantity, it gets confusing when reading code while it hops around between datums

2020-07-06 01:56 UTC, alexkar598 commented on code/modules/antagonists/devil/devil.dm
> +			obsession = "species"
No magic string, use defines so that you cant typo your way into having an obsession of the `spices` type

2020-07-06 01:56 UTC, alexkar598 commented on code/modules/antagonists/devil/devil.dm
> +			actual_obsession_text = "people with the bloodtype [temp_bloodtype_obsession]"
Why not cut the middle man here?
actual_obsession = pick(bloodtype_obsession)
actual_obsession_text = "people with the blo...

2020-07-06 01:56 UTC, alexkar598 commented on code/modules/antagonists/devil/devil.dm
> +	to_chat(owner.current, "You are obsessed with the thought of collecting souls of [actual_obsession_text].")
Make it clearer thats what they need to do
```suggestion
	to_chat(owner.current, "You are obsessed with the thought of collecting souls of <span class='warning'>[actual_obsession_text].</span>")
```

2020-07-06 01:56 UTC, alexkar598 commented on code/modules/antagonists/devil/devil.dm
> +	randomobsession()
You dont have to change it here, but in the future, choose proc names that describe what it does, like set_random_obsession

2020-07-06 01:56 UTC, alexkar598 commented on code/modules/antagonists/devil/devil.dm
> +	antag_memory += "Your devilic true name is [truename]<br>[GLOB.lawlorify[LAW][ban]]<br>You may not use violence to coerce someone into selling their soul.<br>You may not directly and knowingly physi
```suggestion
	antag_memory += "Your devilic true name is [truename]<br>[GLOB.lawlorify[LAW][ban]]<br>You may not use violence to coerce someone into selling their soul.<br>You may not directly and knowingly physically harm a devil, other than yourself.<br>[GLOB.lawlorify[LAW][bane]]<br>[GLOB.lawlorify[LAW][obligation]]<br>[GLOB.lawlorify[LAW][banish]]<br>You are obsessed with the thought of collecting souls of <span class='warning'>[actual_obsession_text]</span><br>"
```

2020-07-11 05:32 UTC, PettyOfficer commented
Interesting.

2020-07-20 18:57 UTC, Ethan4303 commented
The all access contract doesn't work and doesn't give AA nor the announcement, i dont know how this works but was told to post a comment on what happened

2020-07-20 19:06 UTC, wejengin2 commented
> The all access contract doesn't work and doesn't give AA nor the announcement, i dont know how this works but was told to post a comment on what happened

I forced the midround devil, ask me for info

2020-07-24 18:51 UTC, Georgeur commented
Overall good PR. I've had rounds in which I've sold my soul 5 times, making me think I'm the dragonborn or some shit. 
I hope obsessions change upon going soulless, and etc.

2020-07-24 22:50 UTC, alexkar598 commented
I realize it took a while for the review to come in, but this is stale regardless

2020-07-24 22:50 UTC, closed without merging

2020-07-24 22:50 UTC, alexkar598 commented
This PR has been closed due to being stale. Contact me or another maintainer on Discord if you wish for this PR to be reopened.