Lavaland comms now has proper cooling - SYNDICATE EDITION
yogstation13/Yogstation pull request #8926
Opened 2020-06-16 03:10 UTC by MrHorizons

Due to the merging of #8836, my homies in the Syndicate have told me it'd be in my best interests to make this PR.

<details>
  <summary>Before</summary>
</details>

<details>
  <summary>After</summary>
</details>

#### Changelog

:cl:  
tweak: The Syndicate's Lavaland telecomm relay now generates heat. It has been outfitted with a simple cooling system to compensate.
/:cl:

2020-06-16 09:44 UTC, wejengin2 commented
consistency good

2020-06-16 09:57 UTC, patpol4 requested changes
Reminder that tcomms turfs are different then regular ones in case you didn't know.
Maybe try to arrange it in a way that makes the pipe not be under a window, ktl hates that.
Also make sure to add a helper to the airlocks so they cycle properly. 
And throw a space heater in there somewhere, maybe maint?

2020-06-16 16:17 UTC, MrHorizons commented
> Reminder that tcomms turfs are different then regular ones in case you didn't know.
> Maybe try to arrange it in a way that makes the pipe not be under a window, ktl hates that.
> Also make sure to add a helper to the airlocks so they cycle properly.
> And throw a space heater in there somewhere, maybe maint?

They are already tcomm turfs, so you don't have to worry about that. Though I will make the latter three changes.

2020-06-21 06:02 UTC, Ktlwjec1 requested changes
You need to use cyclelink_helper_target on the airlocks instead, and set the dirx and diry values to target the other airlock for each.

2020-06-21 18:49 UTC, MrHorizons commented
> You need to use cyclelink_helper_target on the airlocks instead, and set the dirx and diry values to target the other airlock for each.

Ah, I see. I have done that.

2020-06-22 07:54 UTC, patpol4 requested changes
1. The room needs a separate special tcomms air alarm for the air flow to work. Make sure to set req_access.txt to 150
2. The turf under the window needs to be a plating.
3. I see no reason not to keep the relay itself on use_power=0 , put it back just in case.
4. Your cyclelinks are set to "1" and "0" instead of 1 and 0

2020-06-22 17:54 UTC, patpol4 approved these changes

2020-06-23 07:43 UTC, Ktlwjec1 requested changes
One more thing and then it's fine to merge:
Since it has its own air alarm now, you'll need to create a new area in "code/game/area/areas/ruins/lavaland.dm" and make that room have that area. Otherwise there's no point in having the air alarm, since it can just be accessed from the one in the room right of it. Add a fire alarm into the room (on the freezer side) when you do that too.

2020-06-23 07:45 UTC, Ktlwjec1 approved these changes
nvm ignore me

2020-06-23 07:45 UTC, merged