Adds contents to tower-caps and steel-caps
yogstation13/Yogstation pull request #8973
Opened 2020-06-20 03:14 UTC by MrHorizons

Due to their previous lack of such, tower-caps and steel-caps now have reagent contents, of, respectively, 50% carbon and 50% iron.

#### Changelog

:cl:  
rscadd: Tower-caps contain 50% carbon and steel-caps contain 50% iron.
/:cl:

2020-06-20 03:16 UTC, boodaliboo commented
lol

2020-06-20 03:18 UTC, MrHorizons commented
> lol

lol

2020-06-22 22:11 UTC, JamieD1 requested changes

2020-06-22 22:11 UTC, JamieD1 commented on yogstation.dme
> +#include "code\game\objects\items\implants\implant_mindshieldtot.dm"
```suggestion
```

2020-06-22 22:12 UTC, JamieD1 commented on yogstation.dme
>  #include "code\game\objects\items\implants\implantuplink.dm"
```suggestion
#include "code\game\objects\items\implants\implantuplink.dm"
#include "code\game\objects\items\implants\implant_mindshieldtot.dm"
```

2020-06-22 22:18 UTC, JamieD1 approved these changes

2020-06-22 22:18 UTC, merged