a russian
yogstation13/Yogstation pull request #9032
Opened 2020-06-25 22:21 UTC by boodaliboo

#### Changelog

:cl:  
tweak: tweaks russian simple mobs name to make more sense when examined
/:cl:

2020-06-25 22:25 UTC, boodaliboo commented
![image](https://user-images.githubusercontent.com/40642354/85801640-26f5a980-b6f8-11ea-8725-471202af6fcd.png)
this is what it shows currently

2020-06-25 23:01 UTC, Bibby0110 requested changes

2020-06-25 23:01 UTC, TheGamerdk commented on code/modules/mob/living/simple_animal/hostile/russian.dm
> +	name = "A Russian"
```suggestion
	name = "\improper Russian"
```

2020-06-26 00:03 UTC, boodaliboo commented
does /improper just tell the game its not a proper noun

2020-06-26 08:46 UTC, Ratvar commented
уот так уот

2020-06-26 21:37 UTC, JamieD1 approved these changes

2020-06-26 21:38 UTC, merged