Unfucks the police: Adds tiny fans to labor station
yogstation13/Yogstation pull request #9044
Opened 2020-06-26 22:08 UTC by ToGWtF

### Intent of your Pull Request

Really. Can you not read?

2020-06-27 10:48 UTC, patpol4 approved these changes
Should be an actual airlock setup with vents but eh. Will have to do for now as a temporary fix.

2020-06-27 14:18 UTC, patpol4 requested changes
Just please fix your changelog so it actually documents the changes.

2020-06-28 19:51 UTC, patpol4 approved these changes

2020-06-29 06:38 UTC, Ktlwjec1 approved these changes

2020-06-29 06:38 UTC, merged