Adds the Funny finger. A new way to show players your appreciation
yogstation13/Yogstation pull request #9057
Opened 2020-06-27 23:57 UTC by ToGWtF

### Intent of your Pull Request

Adds a cute new way to tell players just how much you like them!

Just point it their way and show them how you really feel!

haha funny finger go wew

![hahafunnyfinger](https://i.snipboard.io/MhknER.jpg)

2020-06-28 01:47 UTC, Partheo commented
You finally got the sprite

2020-06-28 02:15 UTC, ToGWtF commented
I made it. Thats why its so shite

2020-06-28 18:47 UTC, Partheo requested changes
Use the version Dead.OS made

2020-07-06 09:34 UTC, DoubleTapper reviewed
how do you get t h e f u n n y f i n g e r

2020-07-08 03:08 UTC, Partheo approved these changes

2020-07-16 19:05 UTC, alexkar598 requested changes

2020-07-16 19:05 UTC, alexkar598 commented on yogstation/code/modules/projectiles/guns/funnyfinger.dm
> +/obj/item/gun/magic/funnyfinger/shoot_with_empty_chamber(mob/living/user as mob|obj)
Your mob cannot be an obj
```suggestion
/obj/item/gun/magic/funnyfinger/shoot_with_empty_chamber(mob/living/user as mob)
```

2020-07-16 19:05 UTC, alexkar598 commented on yogstation/code/modules/projectiles/guns/funnyfinger.dm
> +	to_chat(L, "<span class='userdanger'>Someone wanted you to know just how much they appreciate what you're doing!</span>")
```suggestion
/obj/item/projectile/magic/funnyfinger/on_hit(atom/target, blocked = FALSE)
	if(isliving(target))
		var/mob/living/L = target
		to_chat(L, "<span class='userdanger'>Someone wanted you to know just how much they appreciate what you're doing!</span>")
```

2020-07-24 22:54 UTC, alexkar598 commented
This PR has been closed due to being stale. Contact me or another maintainer on Discord if you wish for this PR to be reopened.

2020-07-24 22:54 UTC, closed without merging