Changes the MiniStation shuttle up.
yogstation13/Yogstation pull request #9061
Opened 2020-06-28 17:05 UTC by MrHorizons

_To bring the aging, so-called "Mini" emergency crew extraction shuttle in line with its more modern and/or reliable counterparts, we at the NTSCDOSD (NanoTrasen Shuttle Construction, Design, and Other Stuff Divison) has decided to refit the few still active with others' features. These include:_
- _Internal firelocks have been added, to avoid a breach of either window causing the entire main body of the shuttle to depressurize._
- _The port window has been widened to_ [three tiles]_, for "aesthetic purposes"._
- _More thorough emergency gear, now consisting of five sets of breath masks and emergency oxygen tanks, five lifejackets, five protective hats, and an oxygen deprivation medkit._
- _An additional status display and fire extinguisher cabinet has been added to the rear of the shuttle._
- _The floors have been redone and decals added beneath the chairs and external airlocks._
- _The shuttle cockpit's chairs have been replaced with comfy black ones._
- _A construction worker left their box of donuts in the cockpit and it is now a part of the shuttle._

_We wish you and your crew the best end of your shift!_

All faux-IC document pretense aside, I find the MiniStation shuttle to be quite charming, but in need of some upgrades. This PR is intended to implement said upgrades.

<details>
  <summary>Before</summary>
</details>

<details>
  <summary>After</summary>
</details>

#### Changelog

:cl:  
tweak: Changed up the MiniStation shuttle.
/:cl:

2020-06-28 20:29 UTC, patpol4 requested changes
Very nice work but I still have some things to request and ask about.
1. Did you test if all the stuff in the o2 closet actually fits inside it? (edit: it does)
2. Is the medkit/crowbar/fire extinguisher combo on every table actually needed? What if you put a nanomed in there and just store singular essential medkits in medbay.
3. Same with crowbars, what if you put all of them in a single crate somewhere, or just remove the altogether since escape shuttles don't really need crowbars as much as arrivals shuttles do.
4. Fire extinguisher cabinets so they don't just lie on the tables
5.
![chrome_8TZ7JHLoil](https://user-images.githubusercontent.com/48154165/85957363-11e57880-b98d-11ea-9dd0-02d9e9ab29e5.png)
6. Bridge has no light, medical and brig has very low light
7. What if you replaced the medical operation table with the stasis bed and put something else in place of the stasis bed, just not a sleeper please
8. The intercoms are named "station intercom" and the one on the bridge is set to general for some reason?

2020-06-28 21:37 UTC, MrHorizons commented
> Very nice work but I still have some things to request and ask about.
> 
> 1. Did you test if all the stuff in the o2 closet actually fits inside it? (edit: it does)
> 2. Is the medkit/crowbar/fire extinguisher combo on every table actually needed? What if you put a nanomed in there and just store singular essential medkits in medbay.
> 3. Same with crowbars, what if you put all of them in a single crate somewhere, or just remove the altogether since escape shuttles don't really need crowbars as much as arrivals shuttles do.
> 4. Fire extinguisher cabinets so they don't just lie on the tables
> 
> ![chrome_8TZ7JHLoil](https://user-images.githubusercontent.com/48154165/85957363-11e57880-b98d-11ea-9dd0-02d9e9ab29e5.png)
> 6. Bridge has no light, medical and brig has very low light
> 7. What if you replaced the medical operation table with the stasis bed and put something else in place of the stasis bed, just not a sleeper please
> 8. The intercoms are named "station intercom" and the one on the bridge is set to general for some reason?

Those changes make sense!

It seems you've already resolved 1, so I haven't had to take action.

I've resolved 2 through 4 by swapping them out with two NanoMeds and two fire extinguisher cabinets. I've also replaced the tables with potted plants.

I've resolved 5 the obvious way -- making the marked adjustments to the firelocks.

I've resolved 6 by adding two full light fixtures to the bridge and replacing the bulb in the brig with a fixture.

I've resolved 7 by making your suggested change, and put another stasis bed in the former position of the original.

However, I probably won't resolve 8, as almost every other emergency shuttle's intercoms are called "Station Intercoms" as well, and I'd rather not rename these to Shuttle Intercoms without renaming all the others. There is also usually a general station intercom in the bridge as well.

2020-06-28 22:04 UTC, patpol4 approved these changes
Oh yeah, sorry about the intercom thing, I made a mistake. Having plants on a shuttle is weird, but sure why not. Looks good to me as is except maybe for light fixture placement, but that's just me nitpicking.

2020-06-29 15:14 UTC, Marmio64 commented
This is just the omega emergency shuttle but not as good now.

2020-06-29 17:00 UTC, MrHorizons commented
> This is just the omega emergency shuttle but not as good now.

But does the Omega shuttle have a _complimentary donut box_? I didn't _think_ so.

2020-06-29 20:52 UTC, JamieD1 approved these changes

2020-06-29 20:52 UTC, merged