Emagged hug engine rework
yogstation13/Yogstation pull request #9074
Opened 2020-06-30 02:31 UTC by Darkstick

Emagged hugbox engine, once hugged, will buckle you to itself and cause brute damage until you reach 25 or less health, after which it crunches your spine, turning you paraplegic. 
The paraplegia is a severe brain trauma, meaning it can be healed via brain surgery, but not with neurine.
It is possible to rescue someone that is being crunched by simply unbuckling them from the machine.
Originally, the machine would just move you onto itself and cause brute damage until death.
:cl:  
rscadd: New emagged hugbox effect
tweak: Changed the variable check by a buckle check
/:cl:

2020-06-30 02:40 UTC, boodaliboo commented
more emag eff3ectds better

2020-06-30 03:16 UTC, Jarod1200 commented
Scp 106 wants to know your location

2020-06-30 05:15 UTC, ToGWtF commented
bad

2020-06-30 10:27 UTC, MegaEmpirical commented
Entirely against the point for hugbox engine.

2020-07-02 13:48 UTC, Hopekz commented
Is this the first emagged item in the game that applies a permanent negative debuff?
Paraplegic sounds like a really big debuff imo for just using an emagged item.

2020-07-03 01:58 UTC, Darkstick commented
> Is this the first emagged item in the game that applies a permanent negative debuff?
> Paraplegic sounds like a really big debuff imo for just using an emagged item.

It's not permanent, it can be fixed via brain surgery. I can reduce it to being able to fix it with simply neurine easily though.

2020-07-11 05:31 UTC, PettyOfficer commented
Let's hug it out.

2020-07-16 19:29 UTC, alexkar598 requested changes

2020-07-16 19:29 UTC, alexkar598 commented on yogstation/code/modules/power/hugbox.dm
> +	can_buckle = 1
TRUE

2020-07-16 19:29 UTC, alexkar598 commented on yogstation/code/modules/power/hugbox.dm
> +	buckle_lying = 0
FALSE

2020-07-16 19:29 UTC, alexkar598 commented on yogstation/code/modules/power/hugbox.dm
> +			unbuckle_mob(crunched, TRUE)
This will never happen
```suggestion
```

2020-07-16 19:29 UTC, alexkar598 commented on yogstation/code/modules/power/hugbox.dm
> +			crunched.adjustBruteLoss(4)
4 damage?

2020-07-16 19:29 UTC, alexkar598 commented on yogstation/code/modules/power/hugbox.dm
> +				crunched.adjustBruteLoss(4)
4 damage?

2020-07-16 19:29 UTC, alexkar598 commented on yogstation/code/modules/power/hugbox.dm
> +				crunched.adjustBruteLoss(5)
5 damage?

2020-07-16 19:30 UTC, alexkar598 requested changes

2020-07-16 19:30 UTC, alexkar598 commented on yogstation/code/modules/power/hugbox.dm
> +		else if(crunched.health <= 25)
If its not higher, its lower 
```suggestion
		else
```

2020-07-24 23:48 UTC, alexkar598 commented
This PR has been closed due to being stale. Contact me or another maintainer on Discord if you wish for this PR to be reopened.

2020-07-24 23:48 UTC, alexkar598 commented
And wrong tab

2020-07-25 01:35 UTC, alexkar598 approved these changes

2020-07-25 01:35 UTC, merged