Adds E-N (borgi)
yogstation13/Yogstation pull request #9078
Opened 2020-06-30 19:33 UTC by swissloaf

### Intent of your Pull Request

Adds E-N, the borgi that sparks.

![image](https://user-images.githubusercontent.com/39781787/86168970-8419a280-bade-11ea-93b9-1dab563dd20b.png)

Mappers feel free to add him to a spawn or something.

Also minor, adds a sprite for the generic (non-corgi) dog

![image](https://user-images.githubusercontent.com/39781787/86169039-a1e70780-bade-11ea-87a8-7fcf07b61282.png)

#### Changelog

:cl:  
rscadd: Adds E-N, the borgi
rscadd: Adds a sprite for generic dog
/:cl:

2020-07-01 00:08 UTC, Partheo approved these changes

2020-07-01 00:16 UTC, jcatjmeow requested changes

2020-07-01 00:16 UTC, jcatjmeow commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +	var/emagged = 0
```suggestion
	var/emagged = FALSE
```

2020-07-01 00:16 UTC, jcatjmeow commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +	del_on_death = 1
```suggestion
	del_on_death = TRUE
```

2020-07-01 00:16 UTC, jcatjmeow commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +		emagged = 1
```suggestion
		emagged = TRUE
```

2020-07-01 01:29 UTC, swissloaf commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +		emagged = 1
does not matter but ok

2020-07-01 01:59 UTC, swissloaf commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +	del_on_death = 1
does not matter but ok

2020-07-02 22:19 UTC, merged

2020-07-02 22:19 UTC, swissloaf commented
cucked ktl