adds a scrying orb to the abandoned ghost station
yogstation13/Yogstation pull request #9083
Opened 2020-07-01 03:12 UTC by boodaliboo

ruin is shit this makes it not shit

#### Changelog

:cl:  
rscadd: Added scrying orb to ghost station
/:cl:

2020-07-01 04:10 UTC, SomeguyManperson commented
lets you turn into a ghost and see/hear ghosts so uh no

2020-07-01 04:33 UTC, boodaliboo commented
give me ideas for a different item

2020-07-01 05:33 UTC, deathslayer2481 commented
Ghost sword

2020-07-01 08:25 UTC, patpol4 requested changes
Neither of those fit in, and are too powerful, if you want to add more loot to ruins, add something that makes sense. Not every ruin has to have powergamer loot.

2020-07-01 08:44 UTC, Ktlwjec1 requested changes
ye massive no, close this if you can't think of anything else

2020-07-01 09:00 UTC, Ratvar commented
Make people who enter station become a ghost forever

2020-07-02 00:23 UTC, wejengin2 commented
This has now become a code PR, transferring control over to codermans

2020-07-02 00:24 UTC, wejengin2 commented on code/modules/reagents/reagent_containers/syringes.dm
> +	name = "Gluttony's Blessing"
gluttony's blessing?

2020-07-02 00:25 UTC, wejengin2 commented on code/datums/diseases/transformation.dm
> +	stage3	= list("<span class='danger'>Your skin starts to look trasnparent</span>", "<span class='danger'>Your limbs begin to lose their shape.</span>")
trasnparent

2020-07-02 00:25 UTC, wejengin2 commented on code/datums/diseases/transformation.dm
> +	stage4	= list("<span class='danger'>your organs seems to suddenly disapeer.</span>")
disapeer

2020-07-03 09:41 UTC, Ktlwjec1 approved these changes
map fine

2020-07-07 12:17 UTC, Amelia0010 approved these changes

2020-07-07 21:13 UTC, JamieD1 approved these changes

2020-07-07 21:13 UTC, merged