YogsStation arrivals can fix itself
yogstation13/Yogstation pull request #9088
Opened 2020-07-01 15:04 UTC by redmoogle

###  Intent of your Pull Request

While this doesn't fix the issue of arrivals getting spaced this at least makes it so arrivals on Yogstation can fully repressurize itself instead of the one area not being to repressurize.

~~probably just need to make the shuttle depart slower~~
#### Changelog

:cl:  
bugfix: Yogstation arrivals can repressuirze itself fully.
/:cl:

2020-07-01 15:20 UTC, jcatjmeow commented
bad pr name
good pr

2020-07-01 15:21 UTC, redmoogle commented
> 
> 
> bad pr name
> good pr

better?

2020-07-01 16:08 UTC, patpol4 requested changes
1. The circled tile with arrows has double pipes
2. (optional) If you divided arrivals with firelocks even more, it would be even safer and easier to refill.
![StrongDMM_XKQIdcn3KC](https://user-images.githubusercontent.com/48154165/86266321-552a2c00-bbc5-11ea-87d0-2ae06a045d3a.png)

2020-07-01 17:35 UTC, patpol4 requested changes
Very cool but there is one last thing i have to ask for, in the upper section the pipes are on separate tiles, the reason we use layer 3 for waste and 1 for distro is so they can be on the same tile, neat and clean, just please put them on the same tile and this should be good to merge.
![StrongDMM_d5uUUXgHce](https://user-images.githubusercontent.com/48154165/86274434-f7e8a780-bbd1-11ea-9315-9edfaf40b3d0.png)

2020-07-01 18:06 UTC, patpol4 approved these changes
Looks good to me, ktl will doublecheck and this is mergable.

2020-07-02 07:09 UTC, Ktlwjec1 approved these changes

2020-07-02 07:10 UTC, merged