Cleaned up tank sprites, and updated inhands
yogstation13/Yogstation pull request #9120
Opened 2020-07-03 23:35 UTC by Partheo

Cleaned up the jetpack and air tank sprites, and made the classic jetpacks use an overlay when on instead of having a different sprite.

The air tank inhands have been updated, they now properly reflect the tank sprites we have (rather than the TG ones we had prior).

#### Changelog

:cl:  Partheo
imageadd: New inhand sprites for air tanks
/:cl:

2020-07-04 06:06 UTC, fluffe9911 commented
nice

2020-07-09 07:28 UTC, JamieD1 requested changes
Minor change, but then good to go

2020-07-09 07:28 UTC, JamieD1 commented on code/game/objects/items/tanks/jetpack.dm
> +		if(on)
```suggestion
	if(!classic && on) //does the jetpack have its own on sprite?
```

2020-07-09 07:37 UTC, JamieD1 commented on code/game/objects/items/tanks/jetpack.dm
> +			icon_state = "[initial(icon_state)]-on"
```suggestion
		icon_state = "[initial(icon_state)]-on"
```

2020-07-09 07:44 UTC, JamieD1 approved these changes

2020-07-09 07:44 UTC, merged