Adds an engine SMES
yogstation13/Yogstation pull request #9131
Opened 2020-07-04 22:58 UTC by alexkar598

This engine SMES serves a couple purposes:

1) If you forget to setup the engine, you still have 1 SMES left to use thats only connected to the engine
2) Powersinks can once again by used without releasing the singulo/tesla. Making it viable for non hijack traitors....

# NOTICE: THE SMES STARTS WITH OUTPUT DISABLED, YOU NEED TO TURN IT ON TO USE IT!!!

Also took the time to reorganize the tables

This is actually an issue that got added when we moved the SMES to the SMES room. The mapper that did this forgot that one of the four SMES was an engine SMES and not a normal SMES that outputs to the station.

2020-07-04 22:59 UTC, alexkar598 commented
Wiring is a bit wonky but i dont have much space
![img](https://imgur.com/Bkblfe1.png)

2020-07-06 08:37 UTC, patpol4 approved these changes
Looks good to me but i still want ktl to doublecheck wiring just to be sure.

2020-07-07 10:17 UTC, Ktlwjec1 requested changes
Sure, just swap the consoles back and also merge conflicts.

2020-07-07 19:38 UTC, patpol4 approved these changes
Did the things for alex, mapdiff bot is broke and it shows that i changed panels but i did not

2020-07-08 14:30 UTC, merged