Removes Budget Cards
yogstation13/Yogstation pull request #9133
Opened 2020-07-04 23:47 UTC by TheGamerdk

### Intent of your Pull Request
Ports https://github.com/tgstation/tgstation/pull/47256
Ports https://github.com/tgstation/tgstation/pull/47303

No longer will warops/revs/whatever make Cargo obsolete.

Budget cards are primarily used for buying stuff like mindshields or guns during warops.
Removing budget cards makes sure that cargo is required to actually do their job.

How does this affect balance you may ask?

It's a nerf to the crew, obviously. Especially so until people realize they need to help cargo gather stuff.
War ops won't be about getting the budget cards and sitting in cargo for 20 minutes, but ripping the station bare to buy whatever guns we can.

We made due before Budget cards, and I think we should go back to that.

#### Changelog

:cl:  
rscdel: Budget cards removed. Get to work Cargo!
/:cl:

2020-07-04 23:50 UTC, swissloaf commented
ok

2020-07-04 23:53 UTC, Xantam-13 commented
I think there should be one budget card, the brigs budget card, kept in the armoury for instances like needing emergency implants. But maybe have the budget on the card available scale to how many security you have.

2020-07-04 23:55 UTC, TheGamerdk commented
> I think there should be one budget card, the brigs budget card, kept in the armoury for instances like needing emergency implants. But maybe have the budget on the card available scale to how many security you have.

Currently this keeps the Cargo budget.

We could easily make it retain the sec budget.
Maybe make it make money depending on crew size.

Ensures there's still cash for SOME mindshields and guns on high pop.

Preferably coupled with a rule that says you can't use it without an emergency being present.

2020-07-05 02:30 UTC, AutisticFroggy commented
Alternatively, move emergency fund to raw cash bundles in vault safe, only for use in emergencies.

2020-07-06 20:54 UTC, Marmio64 commented
it'd be nice to keep the security budget, yeah. Especially for the rare off chance security start doing fines. Other then that, remove all the budgets.

2020-07-06 21:52 UTC, TheGamerdk commented
> it'd be nice to keep the security budget, yeah. Especially for the rare off chance security start doing fines. Other then that, remove all the budgets.
> 
> edit: are you keeping the steady income part for cargo? If not you really should, 500 credits per paycheck really isn't much but it'd be quite useful. Also, I believe it still works to just use the mint in mining to turn ores into coins and turn that into pure cash, so it really isn't that hard to get some money if you need it.

One step at a time.
We can remove the mint when we get there.

2020-07-16 19:22 UTC, alexkar598 requested changes

2020-07-16 19:22 UTC, alexkar598 commented on code/controllers/subsystem/economy.dm
> +		D.adjust_money(cargo_cash)
```suggestion
/datum/controller/subsystem/economy/proc/car_payout()
	var/datum/bank_account/D = get_dep_account(ACCOUNT_CAR)
	if(D)
		D.adjust_money(500)
```

2020-07-16 19:31 UTC, alexkar598 approved these changes

2020-07-16 19:31 UTC, merged