Gives yogsdelta chemistry a double door
yogstation13/Yogstation pull request #9135
Opened 2020-07-05 03:06 UTC by Takahiru

## Intent of your Pull Request

It's annoying without it
#### Changelog

:cl:  
tweak: gives yogsdelta chemistry a double door
/:cl:

2020-07-05 11:13 UTC, patpol4 requested changes
1. Update PR with the other change you did
2. Inner windoor access should be just 33
3. Outer windoor does not need an access var, The default is the same as 0 
4. Change changelog to say windoor instead of door

2020-07-05 13:56 UTC, Takahiru commented
1. No
2. I have it at the old access???
3. blame fastdmm2
4. you are nitpicking and biased

2020-07-06 08:14 UTC, wejengin2 commented
1. Turns out there is no conflict so it should be fine
2. Ok it should stay on 5,33 , delta has low iq access restrictions
3. Check the other chemistry windoor, it has no var. In fastdmm2 , just go to the variable, delete the value, press enter, it wont save it that way but still keep it at no access needed. This is a way of preventing unneeded variable bloat.
4. Thanks

2020-07-06 15:21 UTC, Takahiru commented
3. :thonk: it dosen't appear to be going away

2020-07-06 16:54 UTC, patpol4 approved these changes
It went away, you can check it by looking at if the variable is white or not, 
![chrome_SB3KpKc0sZ](https://user-images.githubusercontent.com/48154165/86618966-0f50d780-bfba-11ea-833b-a05b73441f6c.png)
![chrome_mknQniGAXS](https://user-images.githubusercontent.com/48154165/86618983-14ae2200-bfba-11ea-884a-8b1a0984ff49.png)

2020-07-06 16:54 UTC, wejengin2 commented on _maps/map_files/YogsDelta/YogsDelta.dmm
> +	name = "Chemistry Desk"
And it's not in here

2020-07-06 16:56 UTC, merged