Gives a description to sparkles overlay
yogstation13/Yogstation pull request #9138
Opened 2020-07-05 09:04 UTC by ynot01

### Intent of your Pull Request

![](https://i.imgur.com/JwOhS9M.png)
https://www.youtube.com/watch?v=mWtIxc38xNE

#### Changelog

2020-07-05 20:10 UTC, Partheo requested changes

2020-07-05 20:10 UTC, Partheo commented on code/game/objects/effects/overlays.dm
> +	desc = "Flashing lights, lights"
Leave a period at the end of your description

2020-07-05 20:10 UTC, Partheo commented
glad we have a kanye reference though, lmao

2020-07-07 13:02 UTC, ynot01 commented on code/game/objects/effects/overlays.dm
> +	desc = "Flashing lights, lights"
```suggestion
	desc = "Flashing lights, lights."
```

2020-07-07 21:06 UTC, JamieD1 approved these changes

2020-07-07 21:06 UTC, merged