Punishes the playerbase
yogstation13/Yogstation pull request #9172
Opened 2020-07-09 19:17 UTC by Partheo

![image](https://user-images.githubusercontent.com/10659549/87081402-4fe96480-c1f7-11ea-8503-4294fc3b4992.png)

:cl:  Partheo
tweak: flour sacks will now break if you fill them with water
tweak: scooping reagents from the floor now takes time
/:cl:

2020-07-10 04:22 UTC, Nickvr628 commented
No, this is bad

2020-07-10 04:29 UTC, Marmio64 commented
> No, this is bad

do you hate bowls?

2020-07-10 04:30 UTC, Nickvr628 commented
as a chef player I feel personally attacked that I cannot use my flour sacks to mix dough

2020-07-10 07:13 UTC, maxion12345 commented
It's a quality of life thing your removing I don't want to have to measure flour for bread it gets annoying :(

2020-07-10 10:57 UTC, Ratvar commented
Nothing in this pr makes you measure flour

2020-07-12 05:44 UTC, boodaliboo commented
seems like a unneeded difficulty thing

2020-07-14 17:26 UTC, JamieD1 requested changes

2020-07-14 17:26 UTC, JamieD1 commented on code/modules/food_and_drinks/food/condiment.dm
> +	else
Not needed, remove the else and tab it all out. Returns dont need else statements.

2020-07-14 17:26 UTC, JamieD1 commented on code/modules/food_and_drinks/food/condiment.dm
> +
This is horrible, check discord

2020-07-14 21:07 UTC, Partheo commented on code/modules/food_and_drinks/food/condiment.dm
> +
Any optimizations I've tried to make have broken functionality in some way; this is still the simplest way I can find that makes everything work

2020-07-16 20:10 UTC, JamieD1 approved these changes

2020-07-16 20:10 UTC, merged

2020-07-16 20:14 UTC, TheBimmer231 commented
This is the worst PR ever, who thought of this, I can't believe you did this Partheo

2020-07-16 20:57 UTC, TheBimmer231 commented
the chef union will hear about this