Arrivals shuttle additions!
yogstation13/Yogstation pull request #9213
Opened 2020-07-14 00:01 UTC by MrHorizons

(While I was tempted to include a whole NTSCDOSD writeup here, I decided that it'd be better to save it for more "major" shuttle-related projects.)

This PR incorporates some of the better features of the Omega and Delta arrivals shuttles, as well as ensuring every arrivals shuttle has a consistent set of features.

More specifically, that each shuttle has, among the "obvious" features:

- At least one first-aid kit
- At least one emergency toolbox
- A crate containing internals and other emergency supplies
- An AI and evacuation status display
- A holopad
- An emergency NanoMed
- At least two NanoTrasen signs

<details>
   <summary>Old</summary>

**Box:**
![image](https://user-images.githubusercontent.com/29339701/87359695-53058d00-c536-11ea-98e8-5afde73e169e.png)

**Pubby:**
![image](https://user-images.githubusercontent.com/29339701/87359661-42551700-c536-11ea-8df0-962954fddef1.png)

</details>

<details>
  <summary>New</summary>

**Box:**
![image](https://user-images.githubusercontent.com/29339701/87359532-fbffb800-c535-11ea-8fdc-aa37989d7efe.png)

**Pubby:** 
![image](https://user-images.githubusercontent.com/29339701/87359568-0cb02e00-c536-11ea-8c0a-70c68f73cf75.png)

</details>

#### Changelog

:cl:  
rscadd: The arrivals shuttles for Box and Pubby have now been fitted with emergency NanoMeds and tools for emergency disembarkation, as well as additional NanoTrasen branding.
/:cl:

2020-07-14 00:05 UTC, wejengin2 commented
h

2020-07-14 00:06 UTC, Hopekz commented
Oh no you reintroduced the super-duper OP medbay lobby white first aid kit except put it as the first thing people see when they arrive

2020-07-14 00:10 UTC, wejengin2 commented
Ill take a look at this tomorrow.
You could put one more emergency toolbox so there is more then one crowbar.

2020-07-14 03:40 UTC, MrHorizons commented
> Ill take a look at this tomorrow.
> You could put one more emergency toolbox so there is more then one crowbar.

There's already two emergency toolboxes (or at least, on the Box arrivals shuttle), just in the same space. Not that kosher, I know, but it somehow looks better than what I've tried for having them both be visible.

2020-07-14 16:21 UTC, alexkar598 submitted a review, later dismissed
Remove the med kit. We dont have public medkits on the map

EDIT: We shouldn't have public medkits anymore.

2020-07-14 18:09 UTC, patpol4 requested changes
What bossman said and:
1. Rogue decal under o2 crate
2. Change the deathsquad poster to a random official poster
3. Nanomed on pubby cant be in cockpit, just move some wall stuff around and you'll fit it.
4. Having a wall in the back of box is weird, just leave the engines be, im sure you can fit the nanomed somehow, if not, just remove the poster since we have nt signs now.
5. Did you check how the end of the shuttles looks after adding nodiagonal walls?
6. Mention your omega change in the changelog

2020-07-15 10:38 UTC, patpol4 approved these changes
changed the erp poster to a random one and its fine now ;)

2020-07-17 09:13 UTC, Ktlwjec1 requested changes
Just one thing and then it's good to merge, can you change the decals in the box and pubby shuttles to be like this, and (optional) fix omega's too. Just find the current ones really ugly and I was planning on doing this to omega anyway so I'd end up changing those in the future too:
![image](https://user-images.githubusercontent.com/59522545/87769640-d9132380-c815-11ea-81ef-e3c32f2fcb97.png)

2020-07-19 12:22 UTC, Ktlwjec1 approved these changes

2020-07-19 12:23 UTC, merged