Significantly buffs the greytide virus
yogstation13/Yogstation pull request #9220
Opened 2020-07-14 16:09 UTC by nichlas0010

It can now affect cameras, which it has a 75% chance of not doing (due to the sheer mass of cameras)
If it does affect a camera, it'll do one of the following:

- multitool it, which either shrinks or resets the view range
- emp it
- emp-proof it (with a 50% chance it's done in secret, like the malf upgrade)
- motion-activate it (which really can be a massive pain if it's in a location like the medbay)

It can also affect key-card auths, which will do the following:
When it reaches 2 auths, it'll open maint if it's not already open, otherwise it'll red alert
When it reaches 4 auths, it'll red alert

None of this is impossible to deal with, even the camera upgrades just require an engineer/engiborg to detach and retach the camera. The alert/maintenance can be dealt with from any command console by an AI/headofstaff

:cl:
rscadd: Greytide Virus now affects both cameras and keycard auths
/:cl: 

Any additional suggestions to either more stuff to affect or changes to the already affected items are welcome

2020-07-14 16:18 UTC, Jarod1200 commented
maybe some sort of interaction with apcs? like unlocking some randomly or something

2020-07-14 16:28 UTC, alexkar598 commented
I'd rather not have the multitool thing. Everything else is easably detectable or it fixes itself. The multitool thing you wont notice it at all until you need it

2020-07-14 16:31 UTC, alexkar598 requested changes

2020-07-14 16:31 UTC, alexkar598 commented on code/modules/events/prison_break.dm
> +				var/option = pick(list(1, 2, 3, 4))
rand(1,4)

2020-07-14 16:32 UTC, alexkar598 submitted a review, later dismissed

2020-07-14 16:32 UTC, alexkar598 commented on code/modules/events/prison_break.dm
> +						temp.setViewRange((view_range == initial(view_range)) ? short_range : initial(view_range))
Copy paste bad. Those are variables on the camera

2020-07-14 19:57 UTC, Moggram commented
>motion-activate it (which really can be a massive pain if it's in a location like the medbay)
![439315944066646026](https://user-images.githubusercontent.com/63105585/87470243-7e49b400-c5ea-11ea-9482-f3ca51793e14.gif)

This is a cool idea and I hate you for it.

2020-07-17 11:56 UTC, Ratvar commented
Maybe it could emag-hack apcs instead of just unlocking them
Could hack open borg and bot controls

2020-07-25 13:42 UTC, JamieD1 approved these changes

2020-07-25 13:42 UTC, merged