Baton changes from TG along with an antag bola nerf
yogstation13/Yogstation pull request #9285
Opened 2020-07-22 09:51 UTC by SomeguyManperson

inormormadatio n: tgstation/tgstation#45377
basically: stunbatons have their stun delayed by a short period, and deal stamina damage, classic/telescopic  batons only deal stamina damage and knockdown. If someone has the "pump up" chem in their system, the stunbaton stun will be decreased by 90% while still dealing full stamina damage.
Additionally, bolas are being hit to compensate for this; the reinforced and cult bola cause immobility for their duration rather than a full paralyze stun.

:cl:  
rscadd: Adds a new ghetto chem, Pump-Up, which can be made with epinephrine and coffee. Quick to metabolize, but massively lowers stun baton stun time. 2 epi : 5 coffee makes 5 units.
rscadd: Maintenance Pump-Up - a ghetto autoinjector containing the new chem, which is now part of the maintenance loot spawns.
tweak: Stun baton applies a delayed stun, with initial hit dealing stamina damage, slowdown and other effects. The stun will be applied 2 seconds after, but two hits put them in stamina crit instantly. There's a delay of two seconds before the baton can stun again.
tweak: Regular batons, e.g. telescopic, detective's, and contractor baton now deal a two second knockdown, with stamina damage. Two hits stuns them with a stamina crit.
tweak: reinforced and cult bola now cause immobility instead of a hard stun
/:cl:

2020-07-22 13:57 UTC, Partheo approved these changes
Sprites good.

Also, I like this change personally too.

2020-07-22 17:33 UTC, Jarod1200 commented
I like that this takes combat out of a one click win into something slightly more dynamic. This will force people to use slightly more than 1% of their brain.

2020-07-22 17:34 UTC, Alexandria404 commented
We have  few people playing sec, and those that do are often times not that good since they are newish.
Those that used to main sec stopped doing so, since it is such an uninviting task.
We under no circumstances can make sec less inviting.

This change especially with the other PRs in combination is a nerf to sec and a buff to the tide.

Exactly the opposite direction we need to go in.

2020-07-22 17:34 UTC, MegaEmpirical commented
I'm willing to test merge but I'm not optimistic.

2020-07-22 17:36 UTC, DiamondSentinel commented
Definitely better than before, although 2 attacks for a stamina crit seems a bit strong still. It still will lead to the wonder that is a Head/Detective easily winning a 3 or 4v1 because they have instawin items.

2020-07-22 17:44 UTC, LewdElf commented
This seems worth a try. I've seen similar work in other servers and it was perfectly fine. It also will force sec officers to use their bolas, too which they should learn to.

2020-07-22 17:48 UTC, Moja10 commented
Having tried the telebaton changes on /tg/ for a while now, they are completely awful. Getting someone out of the department is extremely difficult, he counters it with a free chem found in maint, and you are basically powerless if there's more than one person, on revs heads will basically have no defense. However the baton change is not as bad as people think. Batonning should be a little less brainless, and it's still quite easy to keep someone down with a baton, however mass bonking multiple with one baton is notoriously harder, whether that's a bad thing or not, dunno. I would prefer if it wasn't literally hopeless for heads of staff during rev rounds unless they have riot armor and a shotgun.

2020-07-22 17:50 UTC, asmcint commented
I'm not 100% sure how I feel about this. On the one hand, I feel like moving away from stun combat is a good move overall for the game, but from the perspective of a semi-frequent sec player(when I can actually play), I'm very apprehensive about such significant changes to the stun baton. It's always been a very high risk, high reward tool, and cutting away reward while still maintaining the full risk is a tough pill to swallow. I'd be a lot more comfortable personally if there were other changes which mitigated the need to take that risk so often in the first place. A mild boost to how much charge a disabler can hold by default, maybe.

I dunno, there's a lot of mixed feelings going into this one for me. When sec has to deal with so much shit, it's really hard to imagine just letting go of their biggest advantage. Still, at the very least, if this PR is testmerged when I can actually boot into Windows, I'll be more than happy to give it a fair shake and see if/how my opinion changes.

2020-07-22 17:50 UTC, drewnerd commented
"Pump-up" is feature creep. I would not add an unobtainable, overpowered chem, for a stunbaton nerf.

Chemistry is not intuitive, a majority of players will not have access to chem. In _theory_ you are trying to balance a stun nerf with an item anyone can make - but in practice, your average joe _never actually makes the chem,_ so what's the point?

/TG/ had a similar problem with Adrenals. An ability that basically gave antags max stamina at all times. In theory, this was to counter stuns, but having the zoomies was SO powerful, it was expected meta for a long time, nearly every traitor used it.

For veterans who can make the chem, it's overpowered. For the average player, it's ineffective at nerfing stunbatons.

2020-07-22 18:33 UTC, Spl99 commented
I mainly pay security, it can be hard sometimes to try and stun someone with a baton as it is. If you're against a robust person or if there's any kind of lag against you it can be a disaster. I feel like this change may not be productive for encouraging people to play security especially considering we can have a good few rounds without security officers. 
I feel like this change may cause more issues than it's worth and will discourage even more people from playing security

2020-07-22 18:39 UTC, TheLinuxOS commented
I played with this change on TG and it made the game much more fun, you arent immediately screwed if someone batons you. Adds more interesting situations to combat such as batoning someone after you are batoned to keep you in the fight, or popping a stim after being hit.

2020-07-22 18:42 UTC, MegaEmpirical commented
That's exactly what I expect a non-sec player to say.

2020-07-22 18:46 UTC, maxion12345 commented
On one hand:

No more funny "dead because clicked first"

on other hand:

"cant stop the greytider, he's injected epi and drank coffee and is now breaking windows at mach 5"

also:
literally every other stun chem needs effort, this is a chem tailored to defeat sec and it can be made by an assistant with an epi-pen and coffee. Thats only going to encourage additional greytiding.

I, for one, am split. I don't all like where combat is decided by who gets clicked with funny orange rod first, but I also don't think sec needs massive nerfs. Going to negative, because I think this is a wrong step in the right direction.

2020-07-22 18:50 UTC, Ratvar commented
Stunbaton being so op is the reason antags have such op things as cult stunmagic. Without nerfing one, you cannot nerf another - and being slapped by stunarm or ebow rather bad for officers. Plus, this nerfs non-security killing an unrobust officer and getting baton, people being -promoted- into shitcurity by HoP and anyone with stunprods, which **helps** officers. That tg did not shit on antags does not mean alexcar will not.

2020-07-22 18:59 UTC, Jarod1200 commented
yeah the free "pumped up chem" in maint seems kinda OP. maybe make it do some toxin damage or something while its in your system so you cant just be 100u of funni bootleg stimulants man

2020-07-22 19:07 UTC, Darkstick commented
I like having more ghetto chem options, looting epipens to fight sec sounds like fun

2020-07-22 19:14 UTC, AdamElTablawy commented
@MegaEmpirical The baton change is fine and i've taken to maining sec for a while on TG.

Telebaton change is shit.

2020-07-22 19:16 UTC, AdamElTablawy commented
@Jarod1200 

> 15% chance to cause loss of breath, and 5% to cause some jitter. If overdosed has 20% chance of causing loss of breath and 4 stamina damage, 15% to cause 2 toxin, 5% to drop held items, 5% to jitter and can also make you drool. Can be found in maintenance (Results in 5 parts instead of 7)

It already has an od and the effects you want.

2020-07-22 20:03 UTC, Spl99 commented
I honestly think this is a bad direction for security to go in. Going back to my points about lag or a robust player against sec. Security will now need to rely on their disabler which already a multiple hit weapon and is still affected by the above and the boola (which i quite like as a tool) but is also very susceptible to missing. So I don't see how this is beneficial to making the game more combat orientated, especially against a department that is already limited yet needs to rely on weapons

2020-07-22 20:20 UTC, AdamElTablawy commented
@Spl99 Try it before you shit on it. The baton is still quite powerful.

It's virtually impossible to fight back once you get batonned still-you have enough stam damage to slow you to a crawl and dizzied movement besides. You can effectively move one tile in a random direction after the baton, or hit back once, before the stun kicks in.

If anything, it's also a bit of a buff-adrenals and antistun chems like meth don't impact stam damage too much, so unlike before where meth made you immune to batons, the guy gets up fast but he's still considerably slow, allowing for a followup baton.

The stunbaton is still one of the best melee weapons in the game with this-it can still easily 1v1 any melee weapon. The delayed stun is not nearly as impactful as you imagine-someone batonned is still quite fucked. They're moving at a snail's pace, can't control where they move, and down in a second. The second hit shuts them down entirely.

What this actually means is that the baton is far worse at handling crowds, as you need to twice-baton multiple people, and that delay is costly. It's not that you can't handle a crowd with it-you can still 3v1-it's just harder to. Flashbangs, etc, are superior for this purpose, as they should be.

Security is not nearly as impacted by this as you believe. They're just as effective.

It also opens the door to weakening antag stuns like cult talismans in turn, so there's that.

2020-07-22 20:28 UTC, Marmio64 commented
make stunbaton still instantly stun people with 20 melee armor or less when you target the head/torso, mostly would allow security to deal with the average tider just as well, but still allowing opportunities to protect yourself. For reference, armor vests and helmet provide 30 melee protection, so they'd protect you from the instant stun.

yes i know its a port and you didn't make it, but still

neutral for now anyhow

2020-07-22 20:30 UTC, AdamElTablawy commented
@Marmio64 it still handles tiders just fine by default

2020-07-23 00:04 UTC, Partheo commented
Disclaimer: I think the chem could go. /tg/ are hyper powergamers so of course everyone is going to have some on them, on Yogs it could be better.

Y'all are dumbasses if you think this makes security any worse. Whoever has the baton in a fight is still nearly guaranteed to win, and security has *other* tools they can use.

I find this is a fantastic rebalance over the current state where whoever gets lucky and picks up the batons wins the fight 100% of the time. There's nothing more retarded than seeing a naked, hyped-up assistant fly through space to valid the fully equipped nukeop- AND WINNING- because he has a stunbaton. They are hilariously powerful.

This is a nerf to stunbatons, not a nerf to security. If we want to move away from disarm-spam, who-clicks-first combat, this is a great step to take. Security has tons of other tools they can use to keep the upper hand, so arguing that this "makes their job so much harder" is frankly just not trying hard enough. Also you're acting as if the stun baton doesn't stun anymore. It still does. The two second delay is just a huge amount of agency that feels really good for whatever player is on the beating end of the stick.

2020-07-23 00:09 UTC, Partheo commented
> I feel like this change may cause more issues than it's worth and will discourage even more people from playing security

Security is and almost always has been the most popular role. I'd be extremely surprised if this changes at all, even if you deleted the baton entirely. People are still gonna play sec.

2020-07-23 00:48 UTC, gaminada commented
I've tried it, i dont like it, honestly would not want it implemented.

2020-07-23 01:21 UTC, SomeguyManperson commented
reminder that the disarm rework allows you to get  a short stun on people who are knocked down, which classic batons do alongside stamina damage

2020-07-23 07:16 UTC, Alexandria404 commented
> 
> 
> > I feel like this change may cause more issues than it's worth and will discourage even more people from playing security
> 
> Security is and almost always has been the most popular role. I'd be extremely surprised if this changes at all, even if you deleted the baton entirely. People are still gonna play sec.

Screenshot taken when reading this comment, not some select time where there happened to be no sec.

![unknown](https://user-images.githubusercontent.com/30261137/88260512-d22c5b00-ccc4-11ea-8ec2-ae910a574443.png)

really makes you wonder

2020-07-23 08:13 UTC, Partheo commented
> really makes you wonder

This is probably the dumbest take in this whole thread.

- the pr isn't even merged yet, so the problem is unrelated

- people don't play security just for the instant stun on the baton 

- it's fucking 3 am

2020-07-23 08:19 UTC, SomeguyManperson commented
I've tried playing security and the main drawback is needing to DEAL with people (both other officers and the people you're arresting) and how much pressure is on you following the rules/space law properly while the people you have to deal with don't care/have that pressure, not you don't have good enough weapons. 
if you want to make security more inviting to play, giving them OP toys isn't going to help. Stronger enforcement of the "don't fuck with security just for fun" rule section would.

2020-07-23 16:13 UTC, Tipy1802 commented
We already have a MASSIVE greytiding problem with people breaking in places non stop and not bothering to ask if they can come in since “it’s just faster to break in”. You can’t prevent people from breaking in since everyone has tools and gloves and somehow everyone is a master hacker. At least heads were able to get tiders out of the their departments but now they won’t be able to do even that.

For the love of god can we stop buffing tiders and powergamers

2020-07-23 17:13 UTC, SomeguyManperson commented
> We already have a MASSIVE greytiding problem with people breaking in places non stop and not bothering to ask if they can come in since “it’s just faster to break in”. You can’t prevent people from breaking in since everyone has tools and gloves and somehow everyone is a master hacker. At least heads were able to get tiders out of the their departments but now they won’t be able to do even that.
> 
> For the love of god can we stop buffing tiders and powergamers



> reminder that the disarm rework allows you to get a short stun on people who are knocked down, which classic batons do alongside stamina damage

2020-07-23 18:30 UTC, TheLinuxOS commented
Officers already have the most powerful tool in the world against greytiders that are constantly breaking into departments and messing with people... its called ahelp. If you are complaining about changing this solely because UNGA GREYTIDE POWERFUL then maybe you should consider ahelping it when greytiders are robusting you and stealing all your sec gear.

2020-07-23 18:34 UTC, MegaEmpirical commented
Most greytide is treated as an IC issue so that doesn't hold any weight.

2020-07-23 21:30 UTC, Georgeur commented
Rick Randumb here. This indirectly buffs lethal weapons, and ranged options, maybe good, maybe bad, expect me to use lethals way more. But. WHY IN THE FUCK IS THERE AN ANTI SEC DRUG AS A MAINT SPAWN, WHY THE FUCK IS THE EFFECT SO STRONG, WHY THE FUCK IS THIS SEEN AS ANYTHING OTHER THAN ENCOURAGING GREYTIDING. Nerf stun batons? Sure. Give literally any job the ability to make an anti sec drug, so long as they buy a coffee, fucking no. The effect is so strong too.

2020-07-24 00:18 UTC, AdamElTablawy commented
@Georgeur 

It's not strong, it's fucking useless.

It does nothing for stamina.  It's noob bait-completely impotent.

2020-07-25 17:58 UTC, JamieD1 commented
Tested on server with staff, seems fine.

2020-07-26 16:49 UTC, Ludox235 commented
@AdamElTablawy 
Why do you still comment despite being banned from the server?

Also yeah I've seen the "nerfed" stunbaton in action and it's still a very good. It doesn't really gut security or anything.

Basically: yes please.

2020-07-26 19:39 UTC, Tipy1802 commented
Wait, is the “classic” baton the detective one? Really nerfing the detective as if he needed nerfs when all he has is the forensic scanner which on top of not being very fun to use is accessible to any officer once researched and roundstart to hos. The detective was already super fucked during conversion game modes like gang since he can’t do much detective duty during those and it’s super vulnerable yet he is mindshielded, this only makes the detective more vulnerable and “ghost simulator 2020” during gangs

2020-07-26 20:05 UTC, AdamElTablawy commented
@Ludox235 why not it takes five seconds

2020-07-26 20:35 UTC, Marmio64 commented
can you also make mechs not stun with punches anymore, since that is a major stun thing that needs to be removed, perhaps instead make it a small knockdown, like a 1 second knockdown.

2020-07-27 07:06 UTC, maxion12345 commented
Mech stuns are intentional, but I believe they are supposed to be a durand-only feature. Maybe just make the person fly back or something, it's a fuckin mech you shouldn't be melee combating a gygax anyways

2020-08-15 13:43 UTC, JamieD1 commented
Will be merging this if there is no opposition

2020-08-21 19:07 UTC, alexkar598 requested changes

2020-08-21 19:07 UTC, alexkar598 commented on code/game/objects/items/melee/misc.dm
> +	var/knockdown_time_carbon = (1.5 SECONDS) // Knockdown length for carbons.
This isnt a define
```suggestion
	var/knockdown_time_carbon = 1.5 SECONDS // Knockdown length for carbons.
```

2020-08-21 19:07 UTC, alexkar598 commented on code/game/objects/items/melee/misc.dm
> +	var/stun_time_silicon = (5 SECONDS) // If enabled, how long do we stun silicons.
```suggestion
	var/stun_time_silicon = 5 SECONDS // If enabled, how long do we stun silicons.
```

2020-08-21 19:07 UTC, alexkar598 commented on code/game/objects/items/melee/misc.dm
> +			target.adjustStaminaLoss(stamina_damage)
Wont this make the head's telebaton be able to put people into stamcrit and cuff them without external help?

2020-08-21 20:10 UTC, alexkar598 submitted a review, later dismissed

2020-08-21 20:10 UTC, alexkar598 commented on code/game/objects/items/stunbaton.dm
> +	var/cooldown = (2 SECONDS)
```suggestion
	var/cooldown = 2 SECONDS
```

2020-08-24 00:18 UTC, SomeguyManperson commented on code/game/objects/items/melee/misc.dm
> +			target.adjustStaminaLoss(stamina_damage)
yes but currently the telebaton can already stun long enough to cuff people in one hit or to chainstun up to 2 people on its own

2020-09-10 15:53 UTC, Tipy1802 commented
After playing with the changes I can say that I hate them. First of all did security really need a nerf? Security is so frustrating to play as and this just makes it worse, we have a problem of security being often understaffed and this would only make it worse. 
 But the worse part has to be the police and telebaton changes. The detective, while not supposed to chase crimianls, is supposed to arrest crimianls if they see the crime happen in front of them or security is understaffed (which happens a lot), making it so he can't stun criminals long enough to cuff them means that he can't do anything to stop criminals.
 The most annoying part of being a Head of Staff has to be dealing with shitters breaking in non stop into your department and this change only makes that ten times worse. Chasing a shitter through medbay so he won't steal all the medecine or break into genetics and become a mega shitter while I am supposed to keep someone alive and when I finally hit the shitter with my batton he gets up 1 second later and the chase continues till I do it 2 or 3 more times. NO NO NO why on earth do we need to buff greytiders? They are allready such a masive pain in the ass and they shouldn't even exist. This changes were made for TG, a powergaming, greytiding LRP shithole, something we try NOT to be

2020-09-12 19:50 UTC, Tipy1802 commented
Also detective baton should be balanced like an officer's baton or else detectives will just ask for one

2020-09-14 01:14 UTC, maxion12345 commented
after playing with this for awhile, its great for preventing the "one click now your dead" kind of stun combat. However, the PUMPUP and overall lowered stun times makes playing security during the 15 assistant rounds we've been having complete fucking hell

2020-09-14 15:55 UTC, Tipy1802 commented
Actually after playing for a while I do like the sec baton changes but the tele and police baton changes still suck since heads should be able to get shitters out of their departments easy.
 I also don't like the maint pill that bypasses stun, antags already have adrenalin and why should greytiders be immune to security or heads of staff taking action against their fuckery?

2020-09-27 17:29 UTC, JamieD1 approved these changes

2020-09-27 17:30 UTC, merged