documents premadepapers.dm
yogstation13/Yogstation pull request #9312
Opened 2020-07-25 19:43 UTC by ReddTheDragon

fuck autodoc

literally a test of autodocumentation since I'm a shitcoder

:cl:  
rscadd: added documentation to paperwork
/:cl:

2020-07-25 19:50 UTC, swissloaf requested changes

2020-07-25 19:50 UTC, swissloaf commented on yogstation/code/game/objects/items/premadepapers.dm
> +  * That's literally it.
"That's literally all it is." dont think is necessary in every paper tbh

2020-07-26 23:08 UTC, MrHorizons commented
Since they're all single-line, couldn't you just use `///` instead of using all the multi-line markup?

2020-07-26 23:09 UTC, ReddTheDragon commented
No bc autodoc

On Sun, Jul 26, 2020 at 7:09 PM Wayward Horizons <notifications@github.com>
wrote:

> Since they're all single-line, couldn't you just use /// instead of using
> all the multi-line markup?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yogstation13/Yogstation/pull/9312#issuecomment-664052256>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIYLPD5KU5I746MMWSNAKILR5SZQXANCNFSM4PHTMEMA>
> .
>

2020-07-26 23:31 UTC, MrHorizons commented
... I thought that was autodoc markup, but okay.

2020-07-29 23:00 UTC, ReddTheDragon commented
@MrHorizons wdym? Based off the guide, the multiline one is used for things that aren't just variables

2020-08-11 19:10 UTC, alexkar598 approved these changes

2020-08-11 19:10 UTC, merged