Tgui secrets
yogstation13/Yogstation pull request #9325
Opened 2020-07-27 18:55 UTC by swissloaf

Makes the admin secrets panel TGUI

https://github.com/BeeStation/BeeStation-Hornet/pull/2033 Original PR
![image](https://user-images.githubusercontent.com/39781787/88580031-9ec53580-d010-11ea-95bb-6ca4dc5c73b2.png)

Looks better than the current version
![image](https://user-images.githubusercontent.com/39781787/88580070-ac7abb00-d010-11ea-927e-c4492890c767.png)

#### Changelog

:cl:  
rscadd: Adds admin secret panel TGUI
/:cl:

2020-07-27 19:22 UTC, ynot01 commented
i cant help but notice that your secrets panel screenshot is outdated but the code looks fine

2020-07-27 19:41 UTC, swissloaf commented
> i cant help but notice that your secrets panel screenshot is outdated but the code looks fine

the new one I posted is updated, old one is from the wiki. its about 5-6 months old

2020-07-27 20:15 UTC, missatessatessy commented
So much nicer

2020-08-01 17:50 UTC, JamieD1 commented
@TheGamerdk

2020-08-12 14:04 UTC, fluffe9911 approved these changes
Code is probably fine but gots a conflict

2020-08-22 22:48 UTC, alexkar598 requested changes
This shit needs to be documented

2020-08-31 21:29 UTC, TriggeredBoi commented on code/modules/admin/secrets.dm
> -			var/dat = "<HTML><HEAD><meta charset='UTF-8'></HEAD><BODY><B>Admin Log<HR></B>"
You probably don't want to revert this UTF-8 stuff

2020-10-22 22:03 UTC, closed without merging