Obsession will forcibly enable mood since its effects are based on mood
yogstation13/Yogstation pull request #9373
Opened 2020-08-01 19:48 UTC by SomeguyManperson

mood is re-disabled if you are cured of it though

:cl:  
rscadd: Creep/obsession/what have you will forcibly enable mood since its effects are tied to mood, mood will be re-disabled for people who had it off if the trauma is cured
/:cl:

2020-08-07 18:55 UTC, alexkar598 requested changes
Add a message telling them they got mood enabled because of obsession. Enabling features like that without saying why is bad UX

2020-08-08 04:58 UTC, Firewolf34 commented
This is necessary.

2020-08-17 12:38 UTC, SomeguyManperson commented
doine

2020-08-21 01:22 UTC, alexkar598 approved these changes

2020-08-21 01:23 UTC, merged