ports cult of st. credit
yogstation13/Yogstation pull request #9390
Opened 2020-08-05 00:28 UTC by boodaliboo

########################################
########################################
https://github.com/tgstation/tgstation/pull/52132 original pr
########################################
########################################

### Intent of your Pull Request
adds a new capitalist religion that earns points through money allowing them to get a cool fancy suit and monicle when enough money is reached
#### Changelog

:cl:  
rscadd: Adds a new religion
/:cl:

2020-08-05 01:40 UTC, Xoxeyos commented
Time to L. Ron B Hubbard myself, build a megachurch, and make the station pay for it.

2020-08-05 01:47 UTC, Hopekz commented
Cool Scientology in ss13

2020-08-05 04:53 UTC, boodaliboo commented
opinions on buffing the rite rewards?

2020-08-05 14:49 UTC, fluffe9911 commented
#Bringthegolemback

2020-08-06 07:23 UTC, boodaliboo commented
> #Bringthegolemback

@alexkar598 would allowing a capitalist golem  to be created through religion for a insane ammount of money be okay. im thinking like 1 million dollars worth to become one

2020-08-06 17:48 UTC, jcatjmeow commented
Capitalist golem is a conversion antag. So, absolutely not

2020-08-07 01:57 UTC, boodaliboo commented
> Capitalist golem is a conversion antag. So, absolutely not

what do you think a reasonable reward could be?

2020-08-07 20:35 UTC, fluffe9911 commented
or instead of being dumb about it you could make a variant of the capitalist golem that DOESNT convert like the original pr author did before he removed the golem and it got closed

2020-08-07 22:25 UTC, boodaliboo commented
> or instead of being dumb about it you could make a variant of the capitalist golem that DOESNT convert like the original pr author did before he removed the golem and it got closed

later

2020-08-11 19:07 UTC, alexkar598 requested changes

2020-08-11 19:07 UTC, alexkar598 commented on code/modules/religion/religion_sects.dm
> +// cool new religion thats based off of money. (am i doing autodoc correctly?)
No you arent, read the guide

2020-08-11 19:07 UTC, alexkar598 commented on code/modules/religion/religion_sects.dm
> +		var/list/hurt_limbs = H.get_damaged_bodyparts(1, 1, null, BODYPART_ORGANIC)
Use TRUE instead of 1

2020-08-11 19:07 UTC, alexkar598 commented on code/modules/religion/rites.dm
> +/datum/religion_rites/looks
Autodocs

2020-08-13 02:24 UTC, boodaliboo commented on code/modules/religion/religion_sects.dm
> +		var/list/hurt_limbs = H.get_damaged_bodyparts(1, 1, null, BODYPART_ORGANIC)
i have no clue what your asking

2020-08-13 02:24 UTC, boodaliboo commented on code/modules/religion/rites.dm
> +/datum/religion_rites/looks
will be done soon

2020-08-22 22:51 UTC, alexkar598 submitted a review, later dismissed

2020-08-22 22:51 UTC, alexkar598 commented on code/modules/religion/religion_sects.dm
> +		var/list/hurt_limbs = H.get_damaged_bodyparts(1, 1, null, BODYPART_ORGANIC)
```suggestion
		var/list/hurt_limbs = H.get_damaged_bodyparts(TRUE, TRUE, null, BODYPART_ORGANIC)
```

2020-08-22 22:51 UTC, alexkar598 commented on code/modules/religion/religion_sects.dm
> +  */
Thats not how you format it, you need to have stars on each line
```c
/*
 *  text
 *  e
 */
```

2020-08-22 22:51 UTC, alexkar598 commented on code/modules/religion/religion_sects.dm
> +  */
Also you need to describe the religion better than this..

2020-08-22 22:51 UTC, alexkar598 commented on code/modules/religion/rites.dm
> +  */
Invalid comment structure

2020-08-23 00:16 UTC, boodaliboo commented on code/modules/religion/religion_sects.dm
> +  */
ok

2020-08-23 00:52 UTC, fluffe9911 approved these changes
ok

2020-08-23 00:52 UTC, merged