Cherries now juice into cherry juice
yogstation13/Yogstation pull request #9412
Opened 2020-08-08 08:01 UTC by SomeguyManperson

cherry juice was set as grind result not juice result so it would NEVER SHOW UP making it COMPLETELY NONEXISTENT :)))
:cl:  
bugfix: cherry juice is now attainable again
/:cl:

2020-08-08 08:22 UTC, wejengin2 commented
Important stuff ngl

2020-08-09 17:15 UTC, Hopekz requested changes
I don't think these will work if these are set to 0 as it might be getting 0 of the thing back after juice. 
Might be the whole reason it didn't exist in the first place after a grind from what I can tell since grinding vs juicing seems to just be flavortext + a different result if they have both grind and juice options.

2020-08-09 17:15 UTC, Hopekz commented on code/modules/hydroponics/grown/berries.dm
> +	juice_results = list(/datum/reagent/consumable/cherryjelly = 0)
```suggestion
	juice_results = list(/datum/reagent/consumable/cherryjelly = 1)
```

2020-08-09 17:15 UTC, Hopekz commented on code/modules/hydroponics/grown/berries.dm
> +	juice_results = list(/datum/reagent/consumable/bluecherryjelly = 0)
```suggestion
	juice_results = list(/datum/reagent/consumable/bluecherryjelly = 1)
```

2020-08-09 23:52 UTC, SomeguyManperson commented
/obj/item/reagent_containers/food/snacks/grown/on_juice()
	var/nutriment = reagents.get_reagent_amount(/datum/reagent/consumable/nutriment)
	if(juice_results&&juice_results.len)
		for(var/i in 1 to juice_results.len)
			juice_results[juice_results[i]] = nutriment
		reagents.del_reagent(/datum/reagent/consumable/nutriment)
		reagents.del_reagent(/datum/reagent/consumable/nutriment/vitamin)

2020-08-10 16:46 UTC, Hopekz commented
> ```
> /obj/item/reagent_containers/food/snacks/grown/on_juice()
> 	var/nutriment = reagents.get_reagent_amount(/datum/reagent/consumable/nutriment)
> 	if(juice_results&&juice_results.len)
> 		for(var/i in 1 to juice_results.len)
> 			juice_results[juice_results[i]] = nutriment
> 		reagents.del_reagent(/datum/reagent/consumable/nutriment)
> 		reagents.del_reagent(/datum/reagent/consumable/nutriment/vitamin)
> ```

clever code

2020-08-12 13:51 UTC, fluffe9911 approved these changes
hip

2020-08-12 13:51 UTC, merged