Mining Base 2: Electric Boogaloo
yogstation13/Yogstation pull request #9427
Opened 2020-08-11 01:50 UTC by maxion12345

Decided to re-work the mining base on feedback from some miner mains. The main change was swapping smeltery and the infirmary to allow the medic easier access to the miners. Also keeps the infirmary close to the shuttle.

Also includes QoL changes, such as a 2x2 hallway bridge instead of a 1x1. Based on the feedback I also added a mini-bar and a games vendor, for 'enhanced miner roleplay'. Whatever, now you have something to do after you go to lavaland during revs.

Current mining base

![](https://i.gyazo.com/1b8308f3f6bbb09a2286c0bb3d04e9a4.png)

Picture of the NEW BASE!

![](https://i.gyazo.com/87c173afa502e70dd4091ce6fc489c79.png)

:cl:  
tweak: The Lavaland Mining Base has been tweaked!
rscadd: Mining Medic area moved to the Smelter area, now features a morgue and surgical area!
rscadd: MIning Base crew rest area now has a mini-bar and a games vendor. Now when you run there to escape the blob, you can play UNO while ignoring the screams of your fellow crewmembers on the station.
rscdel: Deleted the old smelter.
tweak: The old Mining Base Infirmary is now home to a mini-smelter. Kinda mini. It's still pretty large.
/:cl:

2020-08-11 01:52 UTC, Partheo commented
um excuse me, this is removing the rp of politely waiting for fellow miners walking through the 1-tile wide hallway. worst pr, i ded, please speedmerge?

2020-08-11 02:02 UTC, MrHorizons commented
Why not just remove the hallway between the two "halves" of the mining base?

2020-08-11 03:00 UTC, Darkstick commented
> Why not just remove the hallway between the two "halves" of the mining base?

you need it to separate work zone with comfy zone

2020-08-11 06:36 UTC, maxion12345 commented
It'd mean having to shuffle the entire base around. What I honestly wouldn't mind one day is making a donut shaped mining base, with the shuttle in the middle. I think that'd be pretty neat. But I lack the mapping skills to do this.

2020-08-11 08:06 UTC, alao3alao3 commented
We ought to also add more monstermos air locks to the comfort hallway of the mining station, I think it’s been long overdue with how long it is.

2020-08-11 08:50 UTC, PettyOfficer commented
Did you really remove the vendor for smokes? At least put it near the extra mining gear lockers. Also, I like the one tile wide hallway.

2020-08-11 13:11 UTC, patpol4 requested changes
The west wing:
1. Decals (corners,stripes,warings,delivery,etc.) under the conveyor, and the entire place, if you dont want to make new ones just keep the old ones,
2. Name the conveyor switch
3.  This looks way better imo, i just yeeted the coin mint into the atmos maint room
![chrome_VXNnkonMMj](https://user-images.githubusercontent.com/48154165/89899295-572ed400-dbe2-11ea-91f9-7d122873efb8.png) 
vs
![chrome_2QN2nYedj0](https://user-images.githubusercontent.com/48154165/89899363-76c5fc80-dbe2-11ea-8e28-5bd92880e4a7.png)
4. You deleted the orm notice paper, if you don't know where to put it, just use a noticeboard:
![chrome_QgpAn4YZLK](https://user-images.githubusercontent.com/48154165/89899623-dcb28400-dbe2-11ea-8e51-36a175d0d9d6.png)
5. Also removed one of the oreboxes, you could fit it among the crates in the east part i guess.
6. Only put in a buttload of vents and scrubbers if you separate them with firelocks, 
![chrome_jCEENChTKB](https://user-images.githubusercontent.com/48154165/89900265-cc4ed900-dbe3-11ea-99ce-329610b14116.png)
7. Not 100% sure here but can miners use the boozeomat without bartender access? There is an all_access subtype, not sure what it does.
8. You did test if everything is properly lit right
9. Makes the tables feel less empty:
![chrome_dQc5Bv11pm](https://user-images.githubusercontent.com/48154165/89900793-7af31980-dbe4-11ea-9eaf-845b04ec91d1.png)
10. Honestly i dont like the 2 wide bridge, something is off with it, not sure what, might be symmetry or decals.
11. Kitchen grinder, 
![chrome_n1eTW1nrUD](https://user-images.githubusercontent.com/48154165/89901057-d7eecf80-dbe4-11ea-91c1-896ff3cb9aca.png)

That seems like it for the west part.
Will be doing part two of the review soon.

2020-08-11 13:34 UTC, patpol4 requested changes
Review part 2, East part:
1. Decals again, just fill it in with blue corners somehow so its not all white plasteel. Something like this:
![chrome_VgCBBK2Juq](https://user-images.githubusercontent.com/48154165/89902740-1d140100-dbe7-11ea-954f-efe8111ad7bc.png)
![chrome_OZefbaAsKa](https://user-images.githubusercontent.com/48154165/89902767-243b0f00-dbe7-11ea-9e32-5bcc732ee3aa.png)
2.  Remove the cam in morgue since the airlock is glass, change one of the other cams c_tag so its not the same (its the id that shows up on the camera console so you cant have two identical ones)
3. Firelocks in morgue door
3. The way you arranged the crate, the iv drip is inaccessible, this would work:
![chrome_uqou1r4uUG](https://user-images.githubusercontent.com/48154165/89902439-bb539700-dbe6-11ea-9fd4-2d5365274d04.png)
4. I like dark plasteel: 
![chrome_GB8Eu3lwhO](https://user-images.githubusercontent.com/48154165/89902501-d1615780-dbe6-11ea-9c14-18ace018f938.png)
5. The fire extinguisher is in the wall, should be inside, pixelshifted onto the wall
6. Remove one of the bulbs in morgue since they are too close to each other, you did test the light levels right?
7. I like the surgery part, especially the plant, plants are great. You just forgot the surgery drill
8. Don't put light fixtures and cams on the same wall,
9. Suggestion, more windows = more open rooms = usually looks better: 
![chrome_Pb0YlP3Pvp](https://user-images.githubusercontent.com/48154165/89903468-f86c5900-dbe7-11ea-92ef-8f1158386d6f.png)

I think that covers it but i might have missed something because mapdiffbot is broke.

2020-08-12 06:14 UTC, maxion12345 commented
> snip

sounds good mate, i'll get er done tomorrow.

2020-08-13 12:43 UTC, patpol4 requested changes
Alright, we're almost there, the list is considerably shorter:

1. Wrong decal i think
![chrome_UsRxqfl5Ex](https://user-images.githubusercontent.com/48154165/90134631-bec75980-dd71-11ea-8052-6175e0f003db.png)

2. Is the blue square intentional? Ruins the whole "parking space" thing imo.
![chrome_4lITFHUoF9](https://user-images.githubusercontent.com/48154165/90134654-c686fe00-dd71-11ea-8c25-42bcbf71d59c.png)

3. Usually you want a pair of a scrubber and a vent in each zone separated by firedoors, having two scrubbers in one zone and just a vent in other is bad.
![chrome_xFDs6xmqVm](https://user-images.githubusercontent.com/48154165/90134697-d999ce00-dd71-11ea-893d-830f564ebbdd.png)

4. You didn't put the missing ore box back, you could put it here instead of this crate and just move the d4 to the bar. 
![chrome_Fo6dTAeoc8](https://user-images.githubusercontent.com/48154165/90135446-f84c9480-dd72-11ea-92fc-aafe0f4c2d70.png)

5.
Light fixtures and cams on the same wall is bad mapping.
![chrome_YIB751oBP0](https://user-images.githubusercontent.com/48154165/90135697-59746800-dd73-11ea-919d-9b26869f1f0b.png)

2020-08-14 04:20 UTC, maxion12345 commented
> snip

Oh, you meant the crate? I thought you meant an actual ore box. That I left out because...holy fuck, they are everywhere already. Also craftable.

and no, the decals aren't intentional. I also meant "same wall tile" not the entire wall.

2020-08-15 22:33 UTC, maxion12345 commented
fixed some other things, mining base dorms halls was firelocked off but had no scrubber, and there was a cam/light combo next to the mining vendor that I moved

also realised i was big retard and you did mean ore box but whatever

![](https://cdn.discordapp.com/attachments/731402515970654233/735757838634451004/maybe_you_say..PNG)

2020-08-17 20:16 UTC, patpol4 approved these changes
Great work man i think it looks good now

2020-08-17 20:18 UTC, merged