remove teleporter from gamer ruin
yogstation13/Yogstation pull request #9434
Opened 2020-08-12 04:09 UTC by SomeguyManperson

Sure people are supposed to have an easy way back but all the teleporter is used for is for the gamers to harass people through repeatedly teleporting to the station

:cl:  
rscdel: Gamers no longer get a teleporter in their ruin. You know what you did.
/:cl:

2020-08-12 04:10 UTC, ynot01 commented
gamers game

2020-08-12 04:10 UTC, Mesalikepie commented
Honestly good idea for a ruin but it's never used and isn't really that fun. If I wanted to play uno or other shit would I be on ss13?

2020-08-12 05:01 UTC, boodaliboo commented
> Honestly good idea for a ruin but it's never used and isn't really that fun. If I wanted to play uno or other shit would I be on ss13?

we need more arcade games like pacman

2020-08-12 08:43 UTC, wejengin2 commented
As much as I'd like to see the ruin be actually put to it's use, it's just being used by griefers. Removing the tele is sadly a good thing.

2020-08-14 17:12 UTC, jcatjmeow commented
This is why we can't have nice things :(

2020-08-15 02:26 UTC, alexkar598 requested changes
Make the room not stupid please, move the wall one tile up and remove those frogs. We arent in france

2020-08-20 11:24 UTC, wejengin2 commented
@SomeguyManperson are you going to fix the frogs?

2020-08-22 19:47 UTC, closed without merging