[admin] Ticket based activity tracker
yogstation13/Yogstation pull request #9460
Opened 2020-08-13 21:37 UTC by AsV9

# Intent of your Pull Request

Implements a ticket based activity tracker.

Basically, whenever a ticket is left unclaimed it will log any admins who do not have a ticket assigned to them as inactive so that they do not receive tracked hours. This ensures that hours are being fairly tracked for admins who handle ticket, and punishes people who prioritize playing instead of handling tickets.

An additional benefit of this system is that it does not discriminate based on rank. Council, admins, retmins and host are all treated the same way by the code.

**I am aware that there are ways to game this system. I have had a thunk about how to improve this system, but I really can't be fucked to do anything about it now, and this is better than nothing.**

Additionally I also refactored how the 'rebwoink' system works. Basically before it would spam you with a notification every 50 seconds regardless of whether or not you had 4 active tickets already. Now it sends individual notifications for every unclaimed ticket, so you don't get like 10 bwoinks at the same time, instead they get spread out in accordance as to when the tickets came in.

Additionally, it will only send you an audio bwoink if you do not have any unclaimed tickets.

:cl:  
rscadd: New admin ticket based activity checker
/:cl:

2020-08-13 21:42 UTC, Hopekz commented
The way I see it this new system is bypassed by just keeping a ticket open and incentivizes slow responses to ensure you always have a ticket open.

In this new system, you are punished for taking care of tickets quicker/more efficiently than other admins in the same shift.

2020-08-13 21:54 UTC, AsV9 commented
> The way I see it this new system is bypassed by just keeping a ticket open

Yeah that's pretty much a weakness of the system, I've got some ideas for improving it which I'm not going to go into.

>  incentivizes slow responses to ensure you always have a ticket open.

Having one ticket open is exactly the same as having no tickets open. Did you just pull this shit straight out your ass?

2020-08-13 22:08 UTC, Hopekz commented
> Having one ticket open is exactly the same as having no tickets open. 

You misunderstand.

**I'll give you a scenario to help:**

Admin1: resolves 10 tickets in 20 minutes. Resolves tickets as they come. Doesn't hold on to them.
Admin2: resolves 2 tickets in 20 minutes. Holds on to each ticket for 10 minutes.

When Admin1 resolves a ticket efficiently he is then punished by being put into a "no ticket" state.
Admin1 then has to take additional tickets just because his activity is not going to count just because he resolved the previous tickets in a fast manner.

Admin2 does not get this "no ticket" state so he gets rewarded with less workload just for doing the tasks slower.

Both Admin1 and Admin2 get the same amount of credit for their work but Admin2's technique is what is encouraged in this system. The goal of this system is to do the least amount of work vs other Admins as that maximizes your "reward" vs work.

> Did you just pull this shit straight out your ass?

Did I trigger your PTSD or something?

2020-08-13 22:08 UTC, alexkar598 commented
Admin politics must remain out of the repo. This PR will be locked and limited to maintainers if any kind of admin drama starts to stir up, you have discord channels and a forums, do it there.

2020-08-13 22:10 UTC, alexkar598 requested changes
Exclude people without +BAN please.

2020-08-13 22:28 UTC, AsV9 commented
It already does in adminhelp.dm#192 @alexkar598

2020-10-02 14:36 UTC, alexkar598 commented
This would need to be adjusted to the new playtime tracker(job experience instead of connection logs)

2020-10-08 09:58 UTC, nichlas0010 commented
@AsV9 Status?

2020-10-14 10:49 UTC, nichlas0010 commented
asv is home on holiday so oh well

2020-10-14 10:49 UTC, closed without merging