Centers Honkmother on station when summoned by bananium bomb
yogstation13/Yogstation pull request #9464
Opened 2020-08-15 01:27 UTC by ynot01

### Intent of your Pull Request

title

#### Changelog

:cl:  
tweak: Honkmother is now centered on station when summoned by bananium bomb
/:cl:

2020-08-15 13:35 UTC, JamieD1 commented
Checks and Cornflakes

2020-08-17 20:29 UTC, jcatjmeow requested changes
These suggested changes will stop the duplicate definition.

If you wish, you may alternatively change the name of the var in the for loop below 
```
var/turf/T = get_turf(H)
		if(!T || T.z != z)
```
Or, you could have it just redefine T, in which case the change would be just deleting the "var/turf/" on the above line.

2020-08-17 20:29 UTC, jcatjmeow commented on code/game/gamemodes/clown_ops/bananium_bomb.dm
> +	var/turf/T = SSmapping.get_station_center()
```suggestion
	var/turf/center = SSmapping.get_station_center()
```

2020-08-17 20:29 UTC, jcatjmeow commented on code/game/gamemodes/clown_ops/bananium_bomb.dm
> +	var/x0 = T.x
```suggestion
	var/x0 = center.x
```

2020-08-17 20:29 UTC, jcatjmeow commented on code/game/gamemodes/clown_ops/bananium_bomb.dm
> +	var/y0 = T.y
```suggestion
	var/y0 = center.y
```

2020-08-17 20:29 UTC, jcatjmeow commented on code/game/gamemodes/clown_ops/bananium_bomb.dm
> +	for(var/I in spiral_range_turfs(255, T, tick_checked = TRUE))
```suggestion
	for(var/I in spiral_range_turfs(255, center, tick_checked = TRUE))
```

2020-08-17 20:29 UTC, jcatjmeow commented on code/game/gamemodes/clown_ops/bananium_bomb.dm
> +		T.honk_act(dist)
```suggestion
		center.honk_act(dist)
```

2020-08-19 02:43 UTC, ynot01 commented
this PR is on hold until honkmother exists

2020-08-20 20:51 UTC, ynot01 commented
replaced T with center thank you jcat

2020-08-20 20:59 UTC, ynot01 commented on code/game/gamemodes/clown_ops/bananium_bomb.dm
> +	new /obj/structure/destructible/honkmother(T)
```suggestion
	new /obj/structure/destructible/honkmother(center)
```

2020-08-20 22:07 UTC, fluffe9911 approved these changes
ok

2020-08-20 22:07 UTC, merged