Adds "Redesign Your Logo" by Lemon Demon to the lobby music
yogstation13/Yogstation pull request #9485
Opened 2020-08-16 20:23 UTC by MrHorizons

[Lemon Demon - Redesign Your Logo](https://youtu.be/qImHuiYnVQ0)

Aside from "sounding cool", I think the synth-heavy sounds and corporate surrealism jive very well with the tone and style of SS13, especially Yog. (see: that one round where Rotciv got brainwashed by Donk Co.)

#### Changelog

:cl:  
rscadd: Adds "Redesign Your Logo" by Lemon Demon to the lobby music.
/:cl:

2020-08-16 21:10 UTC, jcatjmeow approved these changes
Think about it this way
Guided evolution
This will be a new breed
Cutting edge but classic
Fully complimentary
Bold and self-sufficient
Symbolizing freedom
And, of course, your product
When the logo's finished
Then we will unveil it
Seven billion people
Instantly enlightened
Everyone's rebranded
All the fighting's over
Say goodbye to conflict
That design's rejected
There's no longer language
Only recognition
There's no longer country
Only corporate colors
Color makes us hungry
Hunger makes us human
Everyone can see it
Everything's connected

2020-08-17 04:39 UTC, ynot01 commented
are they even human?

2020-08-18 02:05 UTC, jcatjmeow commented on yogstation/code/controllers/subsystem/ticker.dm
> +		"https://www.youtube.com/watch?v=qImHuiYnVQ0")						// Lemon Demon - Redesign Your Logo
```suggestion
		"https://www.youtube.com/watch?v=HXk-0_rETJ8")						// Lemon Demon - Redesign Your Logo
```
This version is higher quality

2020-08-19 13:48 UTC, Partheo requested changes
Decent lobby theme, the repetitive synth beat feels like a cheese grater on my ears though. Waiting to get more opinions.

2020-08-21 15:41 UTC, jcatjmeow approved these changes

2020-09-08 03:06 UTC, closed without merging

2020-09-08 04:54 UTC, jcatjmeow commented
restore your branch, coward