mentors can set tip of the round
yogstation13/Yogstation pull request #9501
Opened 2020-08-17 23:43 UTC by GenericDM

mentors can now set tip of the round

completely untested ain't that funny
#### Changelog

:cl:  
rscadd: mentor can now set tip of the round
/:cl:

2020-08-17 23:56 UTC, maxion12345 commented
tip of the round might actually be useful

2020-08-18 01:08 UTC, boodaliboo commented
i will mentorhelp everyround so they say my tip

2020-08-18 03:58 UTC, GenericDM commented
just realized that i didnt even add this to mentor verbs... time to fix

2020-08-18 14:10 UTC, jcatjmeow commented
Proc isn't documented

2020-08-18 15:28 UTC, alexkar598 requested changes

2020-08-18 15:28 UTC, alexkar598 commented on yogstation/code/modules/mentor/mentor_verbs.dm
> +	var/input = input(usr, "Please specify your tip that you want to send to the players.", "Tip", "") as message|null
Going to have to be sanitized

2020-08-18 15:28 UTC, alexkar598 commented on yogstation/code/modules/mentor/mentor_verbs.dm
> +		SSticker.send_tip_of_the_round()
Yeah no, no giving mentor an announce button

2020-08-18 18:47 UTC, GenericDM commented
i dont have the time to fix this for standards, maybe later

2020-08-18 18:47 UTC, closed without merging

2020-08-18 18:48 UTC, Jarod1200 commented
f