bloodcult teleport spell costs 50 health up from 7 if used to teleport yourself
yogstation13/Yogstation pull request #9541
Opened 2020-08-22 10:06 UTC by SomeguyManperson

solidifies it as an escape spell by increasing the damage caused when it's cast so downtime is slightly increased

:cl:  
tweak: bloodcult teleport spell will cripple the arm it's used on if used to self teleport
/:cl:

2020-08-22 10:10 UTC, Tipy1802 commented
Sounds very interesting

2020-08-23 00:49 UTC, ToGWtF commented
50 seems high

2020-08-23 03:14 UTC, Marmio64 commented
crippling your arm seems unnessecary. Perhaps instead just have it so that teleporting will deal the 7 damage and also paralyze the person for 5 seconds on arrival at the teleport rune. Negative for now.

edit: neutral instead

2020-08-23 04:42 UTC, Darkstick commented
I like the idea. It will make people (by that I mean me who's constantly spamming that spell) reconsider before zipping away the very second someone with a disabler appears in their line of sight.

2020-08-23 21:25 UTC, SomeguyManperson commented
deals roughly 37.5 damage to max health due to it hitting a limb so you don't lose half your health outright to it, probably going to make sure it doesn't crit the person on using it

2020-09-01 08:16 UTC, JamieD1 requested changes
Lets not go overboard, even if they use it and they are bleeding or any sort of suffocating or toxin they will go into crit anyway, lets give them a little buffer.

2020-09-01 08:16 UTC, JamieD1 commented on code/modules/antagonists/cult/blood_magic.dm
> +	health_cost = 50
```suggestion
	health_cost = 40
```

2020-09-01 08:16 UTC, JamieD1 commented on code/modules/antagonists/cult/blood_magic.dm
> +		else if(user.health < 38) //at this point 50 damage to an arm will crit
```suggestion
		else if(user.health < 30) //at this point 50 damage to an arm will crit
```

2020-09-11 08:29 UTC, Moja10 commented
I think this is still worth looking into, perhaps could be testmerged and a couple sample rounds ran.

2020-09-14 18:17 UTC, closed without merging