Ghosts can now analyze plants and seeds by clicking them
yogstation13/Yogstation pull request #9567
Opened 2020-08-24 18:00 UTC by ynot01

### Intent of your Pull Request

pretty obvious isnit

#### Changelog

:cl:  
rscadd: Ghosts can now analyze plants and seeds by clicking them
/:cl:

2020-08-26 21:54 UTC, nichlas0010 requested changes
AFAIK attack_by doesn't trigger on ghost clicks, use attack_ghost() instead

2020-09-13 04:00 UTC, ynot01 commented
tested and works as intended as shown
![](https://i.imgur.com/10n5nAJ.png)

2020-09-13 10:24 UTC, nichlas0010 approved these changes

2020-09-14 18:39 UTC, JamieD1 approved these changes

2020-09-14 18:40 UTC, merged