ACTUALLY fixes Battle Royale
yogstation13/Yogstation pull request #9570
Opened 2020-08-25 07:41 UTC by ynot01

fuck

2020-08-25 07:43 UTC, ThatLing commented
and i said virGINS

2020-08-25 12:50 UTC, alexkar598 requested changes
Use TRUE/FALSE

Call parent

2020-08-25 13:36 UTC, Moja10 commented
PROMOTE THIS CHAD

2020-08-26 04:35 UTC, alexkar598 requested changes

2020-08-26 04:35 UTC, alexkar598 commented on yogstation/code/game/gamemodes/battle_royale/battleroyale.dm
>  		return 0
Return FALSE

2020-08-26 06:27 UTC, ynot01 commented on yogstation/code/game/gamemodes/battle_royale/battleroyale.dm
>  		return 0
```suggestion
		return FALSE
```

2020-08-26 06:28 UTC, ynot01 commented on yogstation/code/game/gamemodes/battle_royale/battleroyale.dm
>  		return 0
im sorry hc please dont spank me

2020-08-26 21:50 UTC, nichlas0010 approved these changes

2020-08-26 22:24 UTC, alexkar598 submitted a review, later dismissed
Actually looking over the changes myself, the first PR was bad and shouldnt of been merged at all, theres no need for an overridden can_start proc as all logic is already done at the parent /datum/game_mode/proc/can_start

tldr delete the entire proc it shouldnt exist

2020-08-29 16:25 UTC, fluffe9911 approved these changes
ok

2020-08-29 16:26 UTC, merged