Removes lies - 99% lag free is replaced by the actual lag percentage
yogstation13/Yogstation pull request #9596
Opened 2020-08-29 20:07 UTC by alexkar598

Lies are bad mkay

:cl:  alexkar598
tweak: 99% lag free replaced by the actual time dilation
/:cl:

2020-08-29 20:08 UTC, MegaEmpirical commented
I like it.

2020-08-29 20:47 UTC, AutisticFroggy commented
New mentor operation, how much lag can we create to make the number go as low as possible

2020-08-30 00:11 UTC, monster860 requested changes
This is bad maths, and will result in negative numbers sometimes.

`[round(10000 / (100 + SStime_track.time_dilation_current), 1)]`

^ that one is the one you want

2020-08-30 00:56 UTC, alexkar598 commented on yogstation/code/game/world.dm
> +	s += "<b>[station_name()]] -- [100 - round(SStime_track.time_dilation_current,1)]% LAG FREE</b><br>"; // The station & server name line
```suggestion
	s += "<b>[station_name()]] -- [[round(10000 / (100 + SStime_track.time_dilation_current), 1)]]% LAG FREE</b><br>"; // The station & server name line
```

2020-08-31 22:44 UTC, alexkar598 commented
Time to commmit based self merge

2020-08-31 22:44 UTC, merged