The Toxins Update - New machine & miner map tweaks
yogstation13/Yogstation pull request #9608
Opened 2020-09-01 03:53 UTC by MonsWTF

### Intent of your Pull Request

This PR adds a new machine to Toxins that resolves the issues plaguing interactions between Toxins Science and Mining. 

Introducing L.A.M., the Lavaland Artillery Mainframe. (spritework by Tipy)

![LAM](https://user-images.githubusercontent.com/7107685/91790825-449f2d80-ebd7-11ea-87f4-37cc8705501e.png)

The L.A.M. provides Toxins scientists a new, direct way to aid Miners both early and late into the shift - with proper authorization, of course. The console is locked by default, and requires Silicon or RD-level access in order to manipulate the controls. 

Once access is obtained, Toxins miners will be able to take properly-assembled TTV's and load them in. The L.A.M. can then be instructed to target one of the GPS coordinates visible on Lavaland.

![image](https://user-images.githubusercontent.com/7107685/91791048-c2633900-ebd7-11ea-8fa7-475a09f8c591.png)

As is in the name, the L.A.M. delivers volatile ordnance at the request of the Mining team. In order to facilitate safe practices and employee retention, all variable adjustments are announced directly through the science department radio.  The console also requires a delay between starting the Firing process and its deployment. (Minimum 15 seconds)

![image](https://user-images.githubusercontent.com/7107685/91791450-c93e7b80-ebd8-11ea-98a6-fcbdf3597779.png)

A demonstration of Firing sequence w/ last-second Abort can be seen here:

https://www.youtube.com/watch?v=j2RWRjtX0yc

The L.A.M. has been installed inside the following stations' Toxins Testing Chambers, with minimal alterations:
- Eclipse
- IceBox
- Box
- Delta
- Pubby
- Meta

As part of the roll-out, the L.A.M. has also been setup at:
- Runtime
- CentComm

### Related changes made in this PR:
- If statement added to obj/item/gps Initialization, along with editing var data of Mining GPSes on Lavaland. This was a necessary change, as miners should not have to worry about naughty Scientists accidentally'ing their base because a GPS was left on. The If statement prevents the Lavaland GPSes from "appearing" to be on but actually being off, due to the way icon update is implemented.

## Why it's good for the game

This is a feature expansion that brings Science & Mining together in ultimately a net-positive direction. Toxins gains a new avenue to produce and use their bombs, without the massive hurdles currently plaguing their job.

## Future expansion
### Ideas not attached to this PR, but should be under consideration:
- Adjusting Lavaland Bombcap Multiplier (since recent Maxcap nerf + Multiplier nerf 2 years ago to reduce lag)
- Bombing places other than Lavaland (and the station)
- A new machine that mimics L.A.M., but allows Cargo to drop supplies to their miners
- Allowing Emag'ing capabilities to the L.A.M. that doesn't undermine its existence

#### Changelog

:cl:  
rscadd: Adds the L.A.M. to Toxins.
rscdel: A table was removed to make way for one of the L.A.M.'s
tweak: Lavaland's Mining Base GPSes now start Off by default, for safety reasons.
imageadd: L.A.M. sprites created by Tipy
/:cl:

2020-09-01 05:23 UTC, Readystorm546 commented
I kid you not. This would get me back into toxins all by its self. This is an addition to toxins I never knew I wanted until now and I love it so much.

2020-09-01 06:49 UTC, maxion12345 commented
I feel like it would both be faster and safer to clear lavaland with plasmacutters, but it is also a unique and interesting idea that I don't see the harm in. Unless you get griffed by sir totsalot bombing you while mining. Maybe make it announce the GPS tag as well so you have time to yeet it and run

2020-09-01 09:51 UTC, wejengin2 requested changes
I Like it.
Pubby doesn't exist anymore and meta had some updates, update your branch

2020-09-01 10:40 UTC, MonsWTF commented
>Maybe make it announce the GPS tag as well so you have time to yeet it and run, emag effect of glitching the tag/Coords or a silent launch

Not going to toss in any Emag effects on the machine at this current time, but the GPS tag could be expanded. Also, when you first lock onto a GPS signal on Lavaland, the machine does shout the name over radio, so the miners hopefully shouldn't miss it.

2020-09-01 15:48 UTC, MonsWTF commented
While it's not in this PR itself, I'd like to mention the topic I brought up of the Lavaland Bombcap Multiplier, which allows bombs detonated on the Lavaland Z-level a larger explosion radius than the default maxcap.

It was reduced from 3x to 2x about 2 years ago to reduce lag https://github.com/yogstation13/Yogstation/commit/c4fd8715a5f5e9c3c0446072a5d526ee3e82c8f6

Maxcap is also down from 5/10/20, to 3/6/12, all-in-all bringing Lavaland bombs from 15/30/60 to 6/12/24.

I'd propose a PR after this one to raise the Lavaland multiplier to 4x, so that it's at least back up to 12/24/48.

2020-09-01 16:17 UTC, Jarod1200 commented
good nerf to lavaland blood cult too

2020-09-01 16:19 UTC, DiamondSentinel commented
Not that much of a nerf to lavaland cult as you have to target a GPS signal to bomb, just like BSA. 

Still, a good addition. Means that you don't have scientists giving security a heart attack by sprinting through the halls carrying a primed TTV. 

Does this machine have parts and can it be de/reconstructed?

2020-09-01 17:12 UTC, MonsWTF commented
> Does this machine have parts and can it be de/reconstructed?

For balance reasons, not in this PR. I intentionally left that out to avoid the "optimized" situations of putting it somewhere more efficient, or somewhere to hide it that it can still keep sending bombs to annoy Lavaland miners, annoying Scientists with the radio chatter, etc.

2020-09-02 08:24 UTC, wejengin2 approved these changes
Maps appear fine

2020-09-02 20:15 UTC, AutisticFroggy requested changes

2020-09-02 20:15 UTC, AutisticFroggy commented on code/game/machinery/sci_bombardment.dm
> +			var/a = text2num(stripped_input(usr, "Set a new countdown timer. (Minimum [mincount])", name, mincount))
slap a max arg on this. Some enterprising shitters will eventually find the list of href exploits and force this to hit negative and instantly send the bomb somehow.

2020-09-02 20:15 UTC, AutisticFroggy commented on code/game/machinery/sci_bombardment.dm
> +		if(G.emped || !G.tracking || pos.z != 5)
use the define for the z level and not a hard constant for maintainability please

2020-09-22 15:44 UTC, MonsWTF commented
Going to need to close to fix the conflicts and re-submit on my not-Master branch. Will eventually open new PR and refer to this one.

2020-09-22 16:23 UTC, Marmio64 commented
your video is a disappointment, wasn't even a last second abort, there was like, at least 3 seconds left before it launched.

2020-09-22 17:06 UTC, MonsWTF commented
I believe it's all fixed now.

2020-09-22 17:54 UTC, Partheo approved these changes

2020-09-24 19:39 UTC, Partheo approved these changes

2020-10-08 10:05 UTC, nichlas0010 approved these changes
Ping me when the merge conflicts are gone and I'll merge this

2020-10-14 21:54 UTC, wejengin2 commented
@MonsWTF just fix the conflicts and we will merge this

2020-10-17 11:35 UTC, JamieD1 approved these changes
Fix cornflakes

2020-10-23 14:20 UTC, wejengin2 commented
Fixed the map conflicts because I didn't want to see this go to waste, also may have accidentally fucked something up with the js tgui file when merging so make sure to check if it's not wrong. @yogstation13/maintainers

2020-10-25 17:53 UTC, merged