Changes pretty message blocking to using the helper proc
yogstation13/Yogstation pull request #9623
Opened 2020-09-02 15:25 UTC by nichlas0010

Proc was made specifically so we wouldn't have to do the logic in other procs but could just call the helper

2020-09-02 15:42 UTC, jcatjmeow requested changes

2020-09-02 15:42 UTC, jcatjmeow commented on code/modules/mob/say.dm
>  		message_admins("[key_name(usr)] just tripped a pretty filter: '[oldmsg]'.")
```suggestion
		message_admins("[key_name(usr)] just tripped a pretty filter: '[message]'.")
```

2020-09-02 15:42 UTC, jcatjmeow commented on code/modules/mob/say.dm
>  		message_admins("[key_name(usr)] just tripped a pretty filter: '[oldmsg]'.")
```suggestion
		message_admins("[key_name(usr)] just tripped a pretty filter: '[message]'.")
```

2020-09-08 22:19 UTC, JamieD1 approved these changes

2020-09-08 22:19 UTC, merged