Mindslave and Greytide implant antag hud
yogstation13/Yogstation pull request #9627
Opened 2020-09-02 22:04 UTC by ynot01

### Intent of your Pull Request

Mindslave and Greytide implant antag hud
![mindslave](https://user-images.githubusercontent.com/28408322/92041681-b1850580-ed46-11ea-9b1a-8039a964852f.png)
#### Changelog

:cl:  
rscadd: Mindslave and Greytide implant antag hud
/:cl:

2020-09-02 23:05 UTC, jcatjmeow commented
https://forums.yogstation.net/index.php?threads/a-guide-to-testing-your-prs-before-you-pr-them.22028/
SCREAM

2020-09-02 23:06 UTC, jcatjmeow requested changes

2020-09-02 23:06 UTC, jcatjmeow commented on code/datums/hud.dm
>  	ANTAG_HUD_COMMUNIST = new/datum/atom_hud/antag()
```suggestion
	ANTAG_HUD_COMMUNIST = new/datum/atom_hud/antag(),
```

2020-09-03 04:04 UTC, jcatjmeow approved these changes
Gave it a once over and it looks good, if it's tested then woot

2020-09-04 04:10 UTC, MegaEmpirical commented
Fucking finally, good work.

2020-09-04 10:51 UTC, SomeguyManperson submitted a review, later dismissed
need to actually call the new procs probably in apply_innate_effects for the antag or they won't do anything

2020-09-19 05:09 UTC, SomeguyManperson commented
wrong button aaaa

2020-09-24 18:05 UTC, JamieD1 approved these changes

2020-09-24 18:07 UTC, merged