[s] [admin] fullfills ash's request
yogstation13/Yogstation pull request #9644
Opened 2020-09-05 12:45 UTC by nichlas0010

See #maintainer-chat (I think)

2020-09-05 13:18 UTC, alexkar598 requested changes, later dismissed
Get a better name than this

2020-09-05 13:20 UTC, alexkar598 commented
like prefix the entries with with login_

2020-09-05 15:49 UTC, Moja10 commented
Council vote

2020-09-14 18:24 UTC, JamieD1 approved these changes

2020-09-14 18:25 UTC, merged