NTOS GPS
yogstation13/Yogstation pull request #9651
Opened 2020-09-08 02:38 UTC by FLME

### Intent of your Pull Request

Adds a GPS app to NTOS. Work in progress. Works the same/similarly to the GPS item.

#### Changelog

:cl:  
rscadd: GPS in NTOS
/:cl:

2020-09-08 02:40 UTC, AutisticFroggy commented
Time to begin review process. Gamer I'll ping you when it's ready for final review

2020-09-08 03:02 UTC, AutisticFroggy requested changes
We'll need to fix the strings put in data, but once that is done the tgui side should be easy to do. Ping me in MBrain once you're done with addressing these.

2020-09-08 03:02 UTC, ghost commented on tgui/packages/tgui/interfaces/Gps.js
> +export const NtosGPS = (props, context) => {
Do not change this file. This is for the regular handheld gps, not the ntos one.

2020-09-08 03:02 UTC, ghost commented on code/modules/modular_computers/file_system/programs/gps.dm
> +	var/turf/curr = get_turf_global(src) // yogs - get_turf_global instead of get_turf
use ui_holder instead of src. The program technically does not exist anywhere so this will end up janky. ui_holder contains a pointer to the thing that actually has the program running so you can grab its turf from there.

2020-09-08 03:02 UTC, ghost commented on code/modules/modular_computers/file_system/programs/gps.dm
> +	if(!tracking || emped) //Do not bother scanning if the GPS is off or EMPed
remove since modular computers have their own emp interactions.

2020-09-08 03:02 UTC, ghost commented on code/modules/modular_computers/file_system/programs/gps.dm
> +	var/emped = FALSE
remove this var too

2020-09-08 03:02 UTC, ghost commented on code/modules/modular_computers/file_system/programs/gps.dm
> +/datum/computer_file/program/ui_act(action, params)
/datum/computer_file/program/gps/ui_act(action, params)

remember to add gps so that you overload the right proc. Pretty sure at least half your compile errors come from this alone.

2020-09-08 03:02 UTC, ghost commented on code/modules/modular_computers/file_system/programs/gps.dm
> +			var/a = stripped_input(usr, "Please enter desired tag.", name, gpstag, 20)
We'll need to do a tgui input instead of a default input here. I'll teach you how

2020-09-08 03:02 UTC, AutisticFroggy commented on code/modules/modular_computers/file_system/programs/gps.dm
> +	for(var/gps in GLOB.GPS_list)
note to self, need to make modular comps have their own gps trackers somehow.

2020-09-09 07:29 UTC, AutisticFroggy requested changes

2020-09-09 07:29 UTC, AutisticFroggy commented on code/modules/modular_computers/file_system/programs/gps.dm
>  	data["currentArea"] = "[get_area_name(curr, TRUE)]"
ah found the bug, it's ui_host() not ui_holder

2020-09-12 06:57 UTC, TheGamerdk requested changes
Ping  me when this is feature complete and compiles, there's some things that need to be remade/renamed

2020-09-14 01:02 UTC, FLME commented
I HAVE NO IDEA WHAT IM DOING

2020-10-02 14:31 UTC, closed without merging

2020-10-02 14:31 UTC, alexkar598 commented
This PR has been closed due to being stale. Contact me or another maintainer on Discord if you wish for this PR to be reopened.