Makes it so wizards can win or halfwin based on objective completion
yogstation13/Yogstation pull request #9684
Opened 2020-09-12 13:11 UTC by nichlas0010

See: https://cdn.discordapp.com/attachments/134720091576205312/754083649380679830/Screenshot_20200911-165843_Firefox_Nightly.jpg

2020-09-12 14:09 UTC, alexkar598 commented
I dont think checking for objectives is a good idea, we dont enforce objectives on wizard and wizards dont follow their objectives. I doubt anyone would start following their objectives to see a light on my panel light up

2020-10-02 14:40 UTC, alexkar598 submitted a review, later dismissed

2020-10-02 14:40 UTC, alexkar598 commented on code/game/gamemodes/wizard/wizard.dm
> +		if(!wizard.considered_escaped())
Proc doesnt exist

2020-10-05 22:28 UTC, jcatjmeow requested changes

2020-10-05 22:28 UTC, jcatjmeow commented on code/game/gamemodes/wizard/wizard.dm
> +			didEscape = FALSE
You can cast your proc like so
```suggestion
	var/didEscape = TRUE
	var/datum/objective/O
	for(var/datum/mind/wizard in wizards)
		if(O.considered_escaped(wizard))
			didEscape = FALSE
```
This allows you to access /datum/objective/ procs even if you aren't in that file.

2020-10-06 18:49 UTC, jcatjmeow requested changes

2020-10-06 18:49 UTC, jcatjmeow commented on code/game/gamemodes/game_mode.dm
> +	return round_credits er
```suggestion
	return round_credits
```

2020-10-14 16:17 UTC, SomeguyManperson commented
this only checks for if the wizard escaped, and wizards can get survive until the end instead of escape objectives so they could score a loss even if they completed their objectives

2020-10-17 11:37 UTC, JamieD1 approved these changes

2020-10-17 11:37 UTC, merged