Lizards now gain a slight speed boost when resting at a cost of losing both arm functionality
yogstation13/Yogstation pull request #9737
Opened 2020-09-17 01:09 UTC by ynot01

### Intent of your Pull Request

![](https://thumbs-prod.si-cdn.com/umQqAxEqm891OKUva-PzedLNSa4=/fit-in/1600x0/filters:focal(389x292:390x293)/https://public-media.si-cdn.com/filer/6e/30/6e301885-a2c6-4dbb-b7a2-d8758e95d847/lizard.jpg)

#### Changelog

:cl:  
tweak: Lizards now gain a slight speed boost when resting at a cost of losing both arm functionality
/:cl:

2020-09-17 01:15 UTC, Hopekz commented
Makes sense but should be test merged once you get this to work to see how it feels in-game.

2020-09-17 01:15 UTC, jcatjmeow requested changes

2020-09-17 01:15 UTC, jcatjmeow commented on code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
> +/datum/species/lizard/spec_rest(mob/living/carbon/H, is_resting)
```suggestion
/datum/species/lizard/proc/spec_rest(mob/living/carbon/H, is_resting)
```

2020-09-17 01:20 UTC, Mesalikepie commented
Lizards zoom away from sec

2020-09-17 01:47 UTC, jcatjmeow commented on code/modules/mob/living/living.dm
> +		spec_rest(src, TRUE)
Ok, here's your issue. 
You're calling here spec_rest. What this actually means is "mob/living/spec_rest" of which a proc does not exist.

The only spec rest that exists is in datum/species/lizard

so, you need to make spec rest defined at the mob level instead. Or, you can make a temporary object like so
`var/datum/species/lizard/L = new()`
and then call the proc like this
`L.spec_rest(src, true)`

2020-09-17 01:47 UTC, jcatjmeow requested changes

2020-09-17 01:47 UTC, jcatjmeow commented on code/modules/mob/living/living.dm
> +		spec_rest(src, TRUE)
havent tested this but im like 80% sure itll work

2020-09-17 02:31 UTC, Mqiib commented
Can this be toggleable so I don't immediately drop everything when I'm trying to crawl under braindeads to fix something?

2020-09-17 06:50 UTC, maxion12345 commented
Lizards now unable to use hands.

Because no thumbs

2020-09-17 13:06 UTC, ynot01 commented
> Can this be toggleable so I don't immediately drop everything when I'm trying to crawl under braindeads to fix something?

No

2020-09-17 13:28 UTC, jcatjmeow commented
To be honest this should just be an option for all species, to scramble away fast

2020-09-17 15:42 UTC, UselessTheremin commented
this is really funny i want this now. as a trash scalie lizard main, i approve *hiss ing and skittering away from sec like the little goblin you are.

2020-09-17 16:06 UTC, Marmio64 commented
if you add this, nerf the heat resistance lizards get, so they have more drawbacks in relation to their upsides.

2020-09-17 22:47 UTC, Mqiib commented
Does this allow them to ignore the slowdown from crawling or does it make their crawl very slightly faster? If the former then this would be maybe balanced considering the speed bonus is very small, and if the latter then this is arguably a downside.

2020-09-18 04:39 UTC, ynot01 commented
> Does this allow them to ignore the slowdown from crawling or does it make their crawl very slightly faster? If the former then this would be maybe balanced considering the speed bonus is very small, and if the latter then this is arguably a downside.

as the code currently (non-functionally) stands they only get a slight speed boost over crawlspeed but i believe everyone thinks it's the latter so ill look into doing that

2020-09-18 05:01 UTC, Mqiib commented
Are you saying it's supposed to be slightly-faster-than-normal-crawl speed or slightly-faster-than-run speed? Because, again, if it's only slightly boosted crawl speed (ie slightly faster than slow) for the trade-off of not being able to use hands while resting then, assuming it's not toggleable, this is a bad thing.

2020-09-19 17:35 UTC, wejengin2 commented
Hot

2020-09-20 03:20 UTC, Reed0506 commented
this is pretty stupid and i dont like it.

lizards are far more human than animal and i cannot see a reason this would make sense.

2020-09-23 00:24 UTC, Jutastre commented
> 
> 
> Can this be toggleable so I don't immediately drop everything when I'm trying to crawl under braindeads to fix something?

What if you got a speed boost only if your hands are already empty? So you can still crawl at normal speed while holding items.

2020-09-25 17:19 UTC, ynot01 commented
lost motivation and probably wont merge

2020-09-25 17:19 UTC, closed without merging