changes readme.md to say four maps
yogstation13/Yogstation pull request #9766
Opened 2020-09-21 19:56 UTC by boodaliboo

we have 4 maps listed
#### Changelog

:cl:   
tweak: put the right ammount of maps
/:cl:

2020-09-21 20:05 UTC, alexkar598 requested changes
Yogstation currently comes equipped with the following maps.

Im getting tired of this being a mistake

2020-09-21 20:05 UTC, wejengin2 commented
Are you sure

2020-09-22 09:08 UTC, Ktlwjec1 requested changes
Five is correct, it's the map names+links that aren't:
```
* [BoxStation (default)](https://wiki.yogstation.net/wiki/BoxStation)
* [DeltaStation](https://wiki.yogstation.net/wiki/DeltaStation)
* [EclipseStation](https://wiki.yogstation.net/wiki/Maps)
* [MetaStation](https://wiki.yogstation.net/wiki/MetaStation)
* [OmegaStation](https://wiki.yogstation.net/wiki/OmegaStation)
```

2020-09-25 12:05 UTC, alexkar598 requested changes

2020-09-25 12:05 UTC, alexkar598 commented on README.md
> +Yogstation currently comes equipped with four maps.
```suggestion
Yogstation currently comes equipped with the following maps.
```

2020-09-29 18:17 UTC, JamieD1 approved these changes

2020-09-29 18:17 UTC, merged