Unopresses Mentors
yogstation13/Yogstation pull request #9797
Opened 2020-09-25 19:22 UTC by JamieD1

Maybe unoppresses mentors and fixes dme edit

:cl:
:tweak: Fixed mentors slots
/:cl:

2020-09-25 19:23 UTC, Reed0506 commented
based

2020-09-25 22:23 UTC, ynot01 commented
please attach https://github.com/yogstation13/Yogstation/issues/5169

2020-09-25 22:46 UTC, alexkar598 requested changes, later dismissed
Not the way to fix this, is donator already calls is mentor

https://github.com/yogstation13/Yogstation/blob/1c0e0ebe6784e51e79f72a36bdfb2b3c10aa6f37/yogstation/code/__HELPERS/mobs.dm#L36

2020-09-27 14:31 UTC, TheGamerdk commented on code/modules/client/preferences.dm
> +			else if(is_donator(C) || (C.ckey in get_donators()) || C.ckey in GLOB.mentor_datums)
```suggestion
			else if(is_donator(C) || (C.ckey in get_donators()) || (C.ckey in GLOB.mentor_datums))
```

2020-09-27 14:31 UTC, TheGamerdk requested changes
Also do the thing I DM'ed you about you dingus

Also figure out which of your PRs you're doing this in dingus x2

2020-09-27 18:53 UTC, fluffe9911 approved these changes
mentors rise up

2020-09-27 18:54 UTC, merged