Removes Banhammer
yogstation13/Yogstation pull request #9819
Opened 2020-09-27 18:40 UTC by ynot01

## Intent of your Pull Request

OOC in IC
Some instances that spawned the banhammer now spawn a bike horn instead

#### Changelog

:cl:  
rscdel: Removed the banhammer
tweak: Some instances that spawned the banhammer now spawn a bike horn instead
/:cl:

2020-09-27 18:44 UTC, jcatjmeow commented
Doesnt FUCKING COMPILE

But I do agree with this change

2020-09-27 18:45 UTC, ynot01 commented
> Doesnt FUCKING COMPILE
> 
> But I do agree with this change

FUDK yo

2020-09-27 18:50 UTC, maxion12345 commented
Fcuk you get baneNdx four no rasin

2020-09-27 18:55 UTC, FLME commented
as funny as the banhammer is, yeah, it's OOC in IC

2020-09-27 21:13 UTC, wejengin2 commented
Don't see a reason to remove it from the code, just erase all instances of it existing and keep it admin only

2020-09-27 22:28 UTC, ynot01 commented
> Don't see a reason to remove it from the code, just erase all instances of it existing and keep it admin only

> Dont add things that are ""bus only"", only ends in unmaintained bloat features

2020-09-27 23:27 UTC, boodaliboo commented
add it back to code

2020-09-28 04:27 UTC, ynot01 commented
there is no reason for it to exist, it is pointless in any bus scenario and would still be OOC in IC in those bus scenarios

2020-09-28 07:31 UTC, TheGamerdk commented
Remove it from the map not the code

2020-09-28 10:33 UTC, wejengin2 approved these changes
Up to headcoders then,it would be sad to see something go like this. Map is fine.

2020-09-28 19:02 UTC, JamieD1 requested changes

2020-09-28 19:02 UTC, JamieD1 commented on code/game/objects/items/weaponry.dm
>  /obj/item/sord
```suggestion
/obj/item/banhammer
	desc = "A banhammer."
	name = "banhammer"
	icon = 'icons/obj/items_and_weapons.dmi'
	icon_state = "toyhammer"
	slot_flags = ITEM_SLOT_BELT
	throwforce = 0
	force = 1
	w_class = WEIGHT_CLASS_TINY
	throw_speed = 3
	throw_range = 7
	attack_verb = list("banned")
	max_integrity = 200
	armor = list("melee" = 0, "bullet" = 0, "laser" = 0, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 100, "acid" = 70)
	resistance_flags = FIRE_PROOF

/obj/item/banhammer/suicide_act(mob/user)
		user.visible_message("<span class='suicide'>[user] is hitting [user.p_them()]self with [src]! It looks like [user.p_theyre()] trying to ban [user.p_them()]self from life.</span>")
		return (BRUTELOSS|FIRELOSS|TOXLOSS|OXYLOSS)
/* 
oranges says: This is a meme relating to the english translation of the ss13 russian wiki page on lurkmore.
mrdoombringer sez: and remember kids, if you try and PR a fix for this item's grammar, you are admitting that you are, indeed, a newfriend.
for further reading, please see: https://github.com/tgstation/tgstation/pull/30173 and https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=%2F%2Flurkmore.to%2FSS13&edit-text=&act=url
*/
/obj/item/banhammer/attack(mob/M, mob/user)
	if(user.zone_selected == BODY_ZONE_HEAD)
		M.visible_message("<span class='danger'>[user] are stroking the head of [M] with a bangammer</span>", "<span class='userdanger'>[user] are stroking the head with a bangammer</span>", "you hear a bangammer stroking a head");
	else
		M.visible_message("<span class='danger'>[M] has been banned FOR NO REISIN by [user]</span>", "<span class='userdanger'>You have been banned FOR NO REISIN by [user]</span>", "you hear a banhammer banning someone")
	playsound(loc, 'sound/effects/adminhelp.ogg', 15) //keep it at 15% volume so people don't jump out of their skin too much
	if(user.a_intent != INTENT_HELP)
		return ..(M, user)

/obj/item/sord
```

2020-09-28 19:08 UTC, merged