[AdminMaybe logs round station report
yogstation13/Yogstation pull request #9836
Opened 2020-09-29 20:29 UTC by JamieD1

Maybe adds logs to round start

#### Changelog

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images  
spellcheck: fixed a few typos  
experimental: This is experimental  
/:cl:

2020-10-02 19:32 UTC, alexkar598 requested changes

2020-10-02 19:32 UTC, alexkar598 commented on code/game/gamemodes/game_mode.dm
> +		log_admin("[msg.Join()]")
Why are you putting it in a string?

2020-10-02 19:37 UTC, JamieD1 commented on code/game/gamemodes/game_mode.dm
> +		log_admin("[msg.Join()]")
```suggestion
		log_admin([msg.Join()])
```

2020-10-02 19:41 UTC, alexkar598 requested changes, later dismissed

2020-10-02 19:41 UTC, alexkar598 commented on code/game/gamemodes/game_mode.dm
> +		log_admin([msg.Join()])
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

```suggestion
		log_admin([msg.Join())
```

2020-10-04 16:49 UTC, JamieD1 commented on code/game/gamemodes/game_mode.dm
> +		log_admin([msg.Join()])
REEEEEEEEEEEEE

2020-10-04 17:04 UTC, fluffe9911 approved these changes
should be fine now

2020-10-04 17:05 UTC, merged