Adds banner and removes making us look bad
yogstation13/Yogstation pull request #9875
Opened 2020-10-03 18:06 UTC by JamieD1

Adds new banner and removes the dynamic lag count as it makes us look bad.

#### Changelog

:cl:  
rscadd: Added Banner
rscdel: Removed dynamic lag counter
/:cl:

2020-10-03 18:08 UTC, jcatjmeow requested changes

2020-10-03 18:08 UTC, jcatjmeow commented on yogstation/code/game/world.dm
> +	s += "<b>[station_name()]] -- 99% LAG FREE</b><br>"; // The station & server name line
```suggestion
	s += "<b>[station_name()]] -- 99% FREE LAG</b><br>"; // The station & server name line
```

2020-10-03 18:36 UTC, alexkar598 submitted a review, later dismissed
Banner wont display, we ran out of characters for our description q long time ago. We cant even display the Hosted by part

2020-10-03 20:44 UTC, Reed0506 commented
lag percentage is funny jamie ur bad

2020-10-04 17:12 UTC, fluffe9911 approved these changes
he did win the competition and we got to include it even if it costs being honest

2020-10-04 17:12 UTC, merged