Fixes #9873
yogstation13/Yogstation pull request #9889
Opened 2020-10-05 23:56 UTC by ReddTheDragon

due to how it was written, it would stop right after the first G.item_color equaled wash_color in term screwing over whenever there was more than one subtype of glove.

Fixes #9873 
#### Changelog

:cl:  
bugfix: fixed washing gloves with a black crayon = forensic sprite
/:cl:

2020-10-06 03:11 UTC, jcatjmeow requested changes

2020-10-06 03:11 UTC, jcatjmeow commented on code/game/machinery/washing_machine.dm
> +				desc = "The colors are a bit dodgy." // removed break here, it should use the last item in the list for its color. See black gloves.
```suggestion
				desc = "The colors are a bit dodgy." 
```
Don't take this 100% as gospel truth, but you probably don't need this comment here. Nobody needs to know specifically that a break was removed, that's what github history is for. This info wont actually be useful to anyone reading the code, right? I dunno.

2020-10-06 03:16 UTC, ReddTheDragon commented
Could be in the future, if someone finds a better way

On Mon, Oct 5, 2020 at 11:11 PM jcatjmeow <notifications@github.com> wrote:

>
>
>
> *@jcatjmeow* requested changes on this pull request.
>
>
>
>
>
>
> ------------------------------
>
>
>
>
>
>
> In code/game/machinery/washing_machine.dm
> <https://github.com/yogstation13/Yogstation/pull/9889#discussion_r499981697>
> :
>
>
>
> > @@ -162,8 +162,7 @@
>
>
>  				icon_state = initial(G.icon_state)
>
>
>  				item_color = wash_color
>
>
>  				name = "washed gloves"
>
>
> -				desc = "The colors are a bit dodgy."
>
>
> -				break
>
>
> +				desc = "The colors are a bit dodgy." // removed break here, it should use the last item in the list for its color. See black gloves.
>
>
>
>
>
>
>
>
> ⬇️ Suggested change
>
>
> -				desc = "The colors are a bit dodgy." // removed break here, it should use the last item in the list for its color. See black gloves.
>
>
> +				desc = "The colors are a bit dodgy."
>
>
>
>
>
>
>
>
> Don't take this 100% as gospel truth, but you probably don't need this
> comment here. Nobody needs to know specifically that a break was removed,
> that's what github history is for. This info wont actually be useful to
> anyone reading the code, right? I dunno.
>
>
>
>
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yogstation13/Yogstation/pull/9889#pullrequestreview-502554127>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIYLPD7LWX4MSHCRSI3D4VDSJKDFRANCNFSM4SFKE57A>
> .
>
>
>
>

2020-10-06 03:18 UTC, jcatjmeow commented
> Could be in the future, if someone finds a better way

I guess? /shrug

2020-10-06 10:45 UTC, JamieD1 commented
Explain in the pr not the code

2020-10-06 19:00 UTC, ReddTheDragon commented
@JamieD1 updated the pr description

2020-10-07 08:31 UTC, JamieD1 commented
Revert my pr by adding back the correct name @ReddTheDragon

2020-10-11 21:20 UTC, JamieD1 approved these changes

2020-10-11 21:20 UTC, merged