Forced gender fixes
yogstation13/Yogstation pull request #9917
Opened 2020-10-09 01:44 UTC by Mqiib

Makes forced genders not get circumvented by all the standard methods I could think of (magic mirror, cloning, and xenobio gender potion). This only applies to polysmorphs currently.

#### Changelog

:cl:  
bugfix: Forced gender harder to get around for species that have it.
/:cl:

2020-10-09 01:45 UTC, AutisticFroggy commented
no more xeno femboy benis

2020-10-09 01:48 UTC, jcatjmeow requested changes
Add this so that if the thing is a carbon but has no dna (for whatever fucky reason) it wont runtime.

2020-10-09 01:48 UTC, jcatjmeow commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(!(MGENDER in C.dna.species.species_traits) && !(FGENDER in C.dna.species.species_traits) && !(AGENDER in C.dna.species.species_traits))
```suggestion
		if(C.dna && !(MGENDER in C.dna.species.species_traits) && !(FGENDER in C.dna.species.species_traits) && !(AGENDER in C.dna.species.species_traits)))
```

2020-10-09 01:52 UTC, jcatjmeow requested changes
sorry typo

2020-10-09 01:52 UTC, jcatjmeow commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(C.dna && !(MGENDER in C.dna.species.species_traits) && !(FGENDER in C.dna.species.species_traits) && !(AGENDER in C.dna.species.species_traits)))
```suggestion
		if(C.dna && !(MGENDER in C.dna.species.species_traits) && !(FGENDER in C.dna.species.species_traits) && !(AGENDER in C.dna.species.species_traits))
```

2020-10-09 01:53 UTC, Mqiib commented on code/modules/research/xenobiology/xenobiology.dm
> +		if(C.dna && !(MGENDER in C.dna.species.species_traits) && !(FGENDER in C.dna.species.species_traits) && !(AGENDER in C.dna.species.species_traits)))
I TRUSTED YOU

2020-10-09 14:40 UTC, FLME commented
ETHEREALS DONT HAVE GENDER PLEASE FIX IT FOR ETHEREALS TOO

2020-10-09 15:10 UTC, Mqiib commented
Etherials don't have the same issues polysmorphs have. Them not having a gender is already accounted for, as far as I know. If you can tell me exactly what isn't working right about them I could look into it.

2020-10-10 22:54 UTC, Mqiib commented
Ah don't merge this yet I have to fix the gender reassignment surgery too

2020-10-11 17:58 UTC, SomeguyManperson approved these changes

2020-10-12 10:08 UTC, merged