Fixes #9515 - github.com to pretty filter
yogstation13/Yogstation pull request #9927
Opened 2020-10-09 18:30 UTC by JamieD1

Fixes: #9515 

github.com to pretty filter

#### Changelog

:cl:  
rscadd: github.com to pretty filter
/:cl:

2020-10-09 18:33 UTC, nichlas0010 requested changes
put the entire thing in https://github.com/yogstation13/Yogstation/blob/master/config/minor_filter.txt instead

2020-10-11 21:19 UTC, JamieD1 commented
> put the entire thing in https://github.com/yogstation13/Yogstation/blob/master/config/minor_filter.txt instead

No

2020-10-12 10:09 UTC, nichlas0010 approved these changes

2020-10-12 10:10 UTC, nichlas0010 commented
@alexkar598

2020-10-14 23:19 UTC, merged