Adds new uncatchable flag for items
yogstation13/Yogstation pull request #9932
Opened 2020-10-10 11:09 UTC by JamieD1

Adds new uncatchable flag for items

### Intent of your Pull Request

Adds new uncatchable flag for items

#### Changelog

:cl:  
rscadd: Adds new uncatchable flag for items
/:cl:

2020-10-10 11:21 UTC, nichlas0010 requested changes
what even is a boolean

2020-10-10 11:21 UTC, nichlas0010 commented on code/game/objects/items.dm
> +	var/uncatchable = 0
:}

2020-10-10 11:21 UTC, nichlas0010 commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +	uncatchable = 1
:)

2020-10-10 11:21 UTC, nichlas0010 commented on code/modules/mob/living/carbon/carbon_defense.dm
> +				if(I.uncatchable == 1)
:)

2020-10-10 11:21 UTC, nichlas0010 commented on code/modules/mob/living/carbon/carbon_defense.dm
> +					return 0
:)

2020-10-10 13:25 UTC, SomeguyManperson commented on code/modules/mob/living/carbon/carbon_defense.dm
> +				if(I.uncatchable == FALSE)
What

2020-10-11 17:22 UTC, SomeguyManperson requested changes, later dismissed
also undocumented changes

2020-10-11 20:23 UTC, wejengin2 commented
fuck i misclicked and deleted the branch, thanks github mobile app

2020-10-11 20:41 UTC, JamieD1 commented
@SomeguyManperson Care to explain?

2020-10-11 20:42 UTC, alexkar598 requested changes, later dismissed
Use proper flags, dont create another variable

2020-10-11 20:42 UTC, JamieD1 commented on code/modules/mob/living/carbon/carbon_defense.dm
> +				if(I.uncatchable == FALSE)
?

2020-10-11 20:42 UTC, JamieD1 commented
> also undocumented changes

?

2020-10-11 20:43 UTC, JamieD1 commented
> Use proper flags, dont create another variable

Reee I knew you were going to ask that

2020-10-12 10:17 UTC, nichlas0010 approved these changes

2020-10-12 10:18 UTC, merged