Makes Budget Insuls have two charges of absorbing shocks, After which they turn to ash.
yogstation13/Yogstation pull request #9953
Opened 2020-10-11 23:37 UTC by JamieD1

Makes Budget Insuls have two charges of absorbing shocks,

After which they turn to ash.

#### Changelog

:cl:  
tweak: Makes Budget Insuls have two charges of absorbing shocks, After which they turn to ash.
/:cl:

2020-10-12 03:12 UTC, Marmio64 commented
honestly i think it would be better to have it only be one use, since budget insuls are pretty common

2020-10-12 06:16 UTC, Tipy1802 commented
We don’t need a buff to greytiding and avoiding player interactions.

If someone needs insulated gloves to hack in places to steal shit so they wouldn’t have to interact with people and powergame let them order them from cargo or have them ask an engineer for a spare.

2020-10-12 15:17 UTC, Moja10 commented
I think one would actually be plenty

2020-10-12 15:18 UTC, Hopekz commented
Why is one plenty when you are not required to hack a door 6 times (not including other machinery) per shift because of department wires?
What does your planned gameplay for us involve someone having 8 pairs of gloves in their backpack?

2020-10-12 15:19 UTC, Hopekz commented
> honestly i think it would be better to have it only be one use

> I think one would actually be plenty

Why is one plenty when you are now required to hack a door with different wires close to 6 times (not including other machinery) per shift because of department wires?
What does your planned gameplay for us involve someone having 8 pairs of gloves in their backpack?

2020-10-12 19:17 UTC, Marmio64 commented
> > honestly i think it would be better to have it only be one use
> 
> > I think one would actually be plenty
> 
> Why is one plenty when you are now required to hack a door with different wires close to 6 times (not including other machinery) per shift because of department wires?
> What does your planned gameplay for us involve someone having 8 pairs of gloves in their backpack?

Because greytiders shouldn't have an easy 'job', and budget insuls are already common, not to mention the fact that about every 2 electrical toolboxes, there is an extra pair of budget insuls.

2020-10-12 19:23 UTC, boodaliboo commented
> We don’t need a buff to greytiding and avoiding player interactions.
> 
> If someone needs insulated gloves to hack in places to steal shit so they wouldn’t have to interact with people and powergame let them order them from cargo or have them ask an engineer for a spare.

but you can hack without gloves

2020-10-13 18:04 UTC, jcatjmeow requested changes

2020-10-13 18:04 UTC, jcatjmeow commented on code/modules/mob/living/carbon/human/human_defense.dm
> +			if(greytide.damaged == TRUE)
```suggestion
			if(greytide.damaged)
```

2020-10-13 18:04 UTC, jcatjmeow commented on code/modules/mob/living/carbon/human/human_defense.dm
> +				greytide.damaged == TRUE
```suggestion
				greytide.damaged = TRUE
```

2020-10-14 16:14 UTC, SomeguyManperson requested changes
I don't think this actually stops the shock damage since the glove siemen coeff isn't changed and the glove check doesn't end the shocking

2020-10-14 16:20 UTC, Reed0506 commented
i like my RNG based gloves that may or may not fuck me up even worse than wearing no glove at all, and gotta be honest, i wouldnt like this change just because oops i touched something now my gloves are gone. i want to keep my gloves regardless of how useless they are,

2020-10-14 23:11 UTC, JamieD1 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +
```suggestion
				to_chat(src, "<span class='notice'>Your gloves absorb the shock and disintegrate!</span>")
				return
			else
				greytide.damaged = TRUE
				to_chat(src, "<span class='notice'>Your gloves absorb the shock!</span>")
				return
```

2020-10-20 19:03 UTC, SomeguyManperson commented
make it so the gloves have their siemens coefficient is set to 0 and have the damage handled inside the normal glove effect stuff so it doesn't let them fully block stuff like tesla shocks or break from illusory shocks

2020-12-13 11:56 UTC, JamieD1 commented
test

2020-12-14 13:40 UTC, TheGamerdk commented on code/modules/mob/living/carbon/human/human_defense.dm
> +			var/obj/item/clothing/gloves/color/fyellow/greytide = G
this is going to typecast ANY glove into greytide gloves and cause a runtime when using non-fyellow gloves isn't it?

2020-12-14 13:41 UTC, TheGamerdk requested changes

2020-12-14 13:41 UTC, TheGamerdk commented on code/modules/mob/living/carbon/human/human_defense.dm
> +			if(greytide)
```suggestion
			if(istype(greytide))
```

2020-12-14 13:41 UTC, TheGamerdk commented on code/modules/mob/living/carbon/human/human_defense.dm
> +			if(greytide)
```suggestion
			if(istype(greytide))
```

2020-12-31 11:24 UTC, merged