changes vampire hypnotize to be a sleep stun but makes it cost blood or something i guess this is supposed to be better since its prebase code
yogstation13/Yogstation pull request #9955
Opened 2020-10-12 19:35 UTC by SomeguyManperson

new vampire abilities:
Gaze: no cost, instantly stuns an adjacent target for 5 seconds, cooldown of 30 seconds
Hypnotize: costs 20 blood, 4 second delay, stuns and mutes target for 30 seconds if the target is still within 7 meters (subject to change)

:cl:  
fix: fixes some stupid action button things like blood 101 not having an icon and heretic background not having a name
fix: some spelling stuff in how to suck blood 101
rscadd: vampires now get two abilities, glare and hypnotize. Gaze is an instant short stun while hypnotize is a delayed longer stun-mute that costs blood to use. Neither work through flashproofing.
/:cl:

2020-10-12 20:02 UTC, Partheo approved these changes

2020-10-13 12:40 UTC, Marmio64 commented
people who wear sunglasses are immune?

2020-10-13 19:50 UTC, Xoxeyos commented
I think it should go through flash proofing, a vampire is literally a creature that is **super natural**, and I believe that making it flash proof will make it way harder for the vampire to start off; I shouldn't have to rely on a stun prod to catch my prey.

2020-10-13 22:53 UTC, AdamElTablawy commented
it is stopped by flashproofing so that you don't instantly gamer a security officer

'muh super natural' is not an argument @Xoxeyos

2020-10-14 10:30 UTC, nichlas0010 requested changes

2020-10-14 10:30 UTC, nichlas0010 commented on yogstation/code/game/gamemodes/vampire/vampire_powers.dm
> +	if(!ishuman(target))
Is there any reason not to just condense these two checks?

2020-10-14 10:30 UTC, nichlas0010 commented on yogstation/code/game/gamemodes/vampire/vampire_powers.dm
> +	if(!ishuman(target))
condense these two checks as well

2020-10-14 10:30 UTC, nichlas0010 commented on yogstation/code/game/gamemodes/vampire/vampire_powers.dm
> +		var/obj/item/clothing/mask/M = T.wear_mask
Check the helmet as well so you don't get got through spacesuit helmets

2020-10-14 17:31 UTC, Tipy1802 commented
Yeah hypnosis beeing free is really op, good change

2020-10-14 19:32 UTC, Nechronom commented
Maybe give gaze a very short cast time, so you can't just grab a rando and stuff him in a box during that split second. Well. you still could, but not if they're actively moving

2020-10-16 13:23 UTC, nichlas0010 approved these changes

2020-10-16 13:24 UTC, merged