Replaces the atmospheric burn test holodeck program by lava incinerator program. (Take two!)
yogstation13/Yogstation pull request #9972
Opened 2020-10-14 05:47 UTC by Darkstick

The atmospheric burn test holodeck program, AKA the one that immediately fills the entire station with enormous pressure of plasma near instantaneously at the cost of two button presses. It's overused, too easy to do, and far too effective for my liking.

With this PR, the EZ PLASMAFLOOD program will be replaced with a program that covers the holodeck in lava. Sweet sweet husking, evidence burning, sudden lava.

:cl:  
rscadd: lava holodeck
rscdel: plasmaflood holodeck
tweak: changed name of program accordingly
/:cl:

2020-10-14 07:46 UTC, Moja10 commented
PR is a noble goal but I think takes it in the wrong direction. Mayhaps I suggest it create an atmospheric room of miasma instead. That can spread and also be 10x more interesting

2020-10-14 08:43 UTC, maxion12345 commented
for the love of God don't give moja his emag fart flood, we'll take the lava just please not the fart program

2020-10-14 17:49 UTC, ToGWtF commented
Disagree, but agree that burn program needs a nerf. Maybe lower the amount of moles of plasma:oxygen that it spawns instead? So it can flood a small area but not all of central like it can now?

Also lava is pretty op. Its a pretty easy way to delete items to hide evidence. Only 3 other rooms in the station can do that

2020-10-15 06:04 UTC, maxion12345 commented
why can holographic plasma leave the holodeck 🤔

2020-10-16 17:50 UTC, Reed0506 commented
lava aint as strong as a plasmafire, and there are far more convenient ways to delete items than emagging the damn holodeck.
i dont see this being anything but an improvement, as it removes the extremely OP holodeck plasmaflood while keeping the toasty nature of the program.

2020-10-17 11:32 UTC, wejengin2 requested changes
As much as i want the plasmaflood program gone I won't merge with overwhelming negative votes. Let's give it another day or two and I'll close if nothing changes. Also make this compile.

2020-10-19 13:53 UTC, wejengin2 approved these changes
Looks like we have a tie with me not voting. I think this is a good change. If you want any of the other suggestions mentioned in the comments just pr them and they will be considered.

2020-10-19 13:53 UTC, merged