Adds Hardsuit Specific Flag for Medical Sprays / Patches
yogstation13/Yogstation pull request #9976
Opened 2020-10-14 18:03 UTC by JamieD1

Adds Hardsuit Specific Flag for Medical Sprays / Patches

#### Changelog

:cl:  
tweak: Adds Hardsuit Specific Flag for Medical Sprays / Patches
/:cl:

2020-10-14 22:46 UTC, jcatjmeow requested changes
wouldn't hurt to comment on uncatchable too although that's decently self explanatory

2020-10-14 22:46 UTC, jcatjmeow commented on code/__DEFINES/obj_flags.dm
> +#define MEDRESIST				(1<<14)
```suggestion
#define MEDRESIST				(1<<14) //This item will block medical sprays when worn
```

2020-10-16 09:54 UTC, nichlas0010 requested changes

2020-10-16 09:54 UTC, nichlas0010 commented on code/modules/reagents/reagent_containers/patch.dm
> +			to_chat(H, "<span class='warning'>[src] cannot be applied through a hardsuit!</span>")
```suggestion
			to_chat(H, "<span class='warning'>[src] cannot be applied through [H.wear_suit]!</span>")
```

2020-10-16 09:54 UTC, nichlas0010 commented on code/modules/reagents/reagent_containers/medspray.dm
> +		to_chat(H, "<span class='warning'>[src] cannot be applied through a hardsuit!</span>")
```suggestion
		to_chat(H, "<span class='warning'>[src] cannot be applied through [H.wear_suit]!</span>")
```

2020-10-16 17:41 UTC, Reed0506 commented
wow, code that isnt shittily made and doesnt cause problems unrelated to the original thing, incredible!

2020-10-18 20:05 UTC, merged