(port) New Pet, Frank the Turtle!
yogstation13/Yogstation pull request #9991
Opened 2020-10-15 19:52 UTC by boodaliboo

original pr: https://github.com/BeeStation/BeeStation-Hornet/pull/1413
"Adds an adorable new pal to the mining base, Frank the Turtle (Lovingly referred to as Yeeslow by some members of the Crew). Don't let his adorable appearance fool you, Frank is built like a tank and can take a lot of punishment. Don't expect him to come to the rescue though, as he likes to get down low and hide in his shell whenever he's in danger."

#### Changelog

:cl:  
rscadd: Added frank  the turtle
/:cl:

2020-10-15 20:15 UTC, fluffe9911 commented
gotta collect em all station pets!

2020-10-16 00:11 UTC, Hopekz commented on code/modules/mob/living/simple_animal/friendly/turtle.dm
> +	maxHealth = 2500
wut

2020-10-16 09:35 UTC, Partheo commented
Personally not a fan of more pets, I think there should be 2-3 max.

2020-10-16 09:36 UTC, Partheo approved these changes
Sprites fine

2020-10-16 10:02 UTC, wejengin2 requested changes
Not a fan of pet oversaturation but i can't help myself when i see a cowboy hat on a turtle.Make this compile please.

2020-10-17 11:35 UTC, wejengin2 approved these changes
Map technically fine, whoever presses the merge button think about if we need more pets.

2020-10-17 12:14 UTC, merged